IF NOT EXISTS(SELECT *  FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='FACTURACIONPE')
BEGIN
   INSERT INTO USPROH (IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_ADMINISTRATIVO', 'FACTURACIONPE', 'M', 'FACTURACION', 1, 'admin.facturacionPe', 'fa-solid fa-file-invoice-dollar', NULL, 0, 0, 12, 'Facturas,Boletas, Ventas', NULL, NULL
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FTR'  AND   C.NAME = 'ULRPTAAPI')
BEGIN
   ALTER TABLE FTR  ADD ULRPTAAPI VARCHAR(256)
END
IF NOT EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FTRAPILOG' AND XTYPE='U')
BEGIN
   CREATE TABLE FTRAPILOG( 
   ID INT IDENTITY(1,1),
   N_FACTURA VARCHAR(20),
   CNSFNOT  VARCHAR(20),
   TIPODOC   VARCHAR(10),
   ESTADOC   VARCHAR(5),
   ERRORES   VARCHAR(MAX),
   DESCSUNAT VARCHAR(MAX),
   METODO    VARCHAR(20),
   JSONSOLICITUD VARCHAR(MAX),
   JSONRESPUESTA VARCHAR(MAX)
   )
   ALTER TABLE FTRAPILOG
   ADD CONSTRAINT FTRAPILOGID
   PRIMARY KEY CLUSTERED (ID)
END
IF NOT EXISTS(SELECT * FROM SYS.indexes WHERE name='FTRAPILOGNFACTURAID')
BEGIN
   CREATE UNIQUE INDEX FTRAPILOGNFACTURAID ON FTRAPILOG (N_FACTURA,ID)
END
