IF EXISTS(SELECT  * FROM SYS.key_constraints WHERE name='FK_NEMP_NEMPNUMDOC')
BEGIN 
   ALTER TABLE NEMP DROP CONSTRAINT FK_NEMP_NEMPNUMDOC
END
IF EXISTS(SELECT  * FROM SYS.key_constraints WHERE name='FK_NPLA_NPLACODEMPLEADO')
BEGIN
   ALTER TABLE NPLA DROP CONSTRAINT FK_NPLA_NPLACODEMPLEADO
END
IF EXISTS(SELECT  * FROM SYS.key_constraints WHERE name='FK_NEMPF_NEMPFCODEMP')
BEGIN
   ALTER TABLE NEMPF DROP CONSTRAINT FK_NEMPF_NEMPFCODEMP
END
IF EXISTS(SELECT  * FROM SYS.key_constraints WHERE name='FK_NEMPFD_NEMPFDNUMDOC')
BEGIN
   ALTER TABLE NEMPFD DROP CONSTRAINT FK_NEMPFD_NEMPFDNUMDOC
END