CREATE OR ALTER PROCEDURE DBO.SPK_RESUMEN_TURNOS
@ANO VARCHAR(4),
@MES SMALLINT,
@IDUSUARIO VARCHAR(20)=NULL
	WITH ENCRYPTION
AS
DECLARE @USUARIO VARCHAR(20)
DECLARE @FECHA DATETIME
DECLARE @TIPOPERSONAL VARCHAR(20)
DECLARE @TIPO_USUARIO VARCHAR(20)
DECLARE @PERIODO VARCHAR(6)
BEGIN
   DELETE TSECRES WHERE YEAR(FECHA)=@ANO
   AND MONTH(FECHA)=@MES
   AND ESTADO<>'Definitivo'



   INSERT INTO TSECRES(CODTURNO, USUARIO, FECHA, TIPOPERSONAL, TIPO_USUARIO, CODNOV, HCUMP, HPEND, HNOV)
   SELECT CODTURNO,USUARIO,FECHA,TIPOPERSONAL,TIPO_USUARIO,CODNOVE,
   CASE WHEN COALESCE(CODNOVE,'')='' AND ESTADO=2 THEN MAX(DATEDIFF(HOUR,FECHAINICIAL,FECHAFINAL)) ELSE 0 END HCUMP,
   CASE WHEN COALESCE(CODNOVE,'')='' AND ESTADO<>2 THEN MAX(DATEDIFF(HOUR,FECHAINICIAL,FECHAFINAL)) ELSE 0 END HPEND,
   CASE WHEN COALESCE(CODNOVE,'')<>'' AND ESTADO=3 THEN MAX(DATEDIFF(HOUR,FECHAINICIAL,FECHAFINAL)) ELSE 0 END HNOV
   FROM TSECFU
   WHERE YEAR(FECHA)=@ANO
   AND MONTH(FECHA)=@MES
   AND COALESCE(RESUM,0)=0
   AND USUARIO=CASE WHEN @IDUSUARIO IS NOT NULL THEN @IDUSUARIO ELSE USUARIO END
   GROUP BY  FECHA,CODTURNO,USUARIO,TIPOPERSONAL,TIPO_USUARIO,CODNOVE,ESTADO
   ORDER BY  FECHA,CODTURNO,USUARIO

   UPDATE TSECRES SET ESTADO=CASE WHEN COALESCE(HPEND,0)>0 THEN 'Borrador' ELSE 
   CASE WHEN COALESCE(CODNOV,'')<>'' AND COALESCE(HCUMP,0)>0 THEN 'Error' ELSE 'Definitivo' END END,
   HCUMP=COALESCE(HCUMP,0),HPEND=COALESCE(HPEND,0),HNOV=COALESCE(HNOV,0),
   CODNOV=COALESCE(CODNOV,'')
   WHERE YEAR(FECHA)=@ANO
   AND MONTH(FECHA)=@MES
   AND USUARIO=CASE WHEN @IDUSUARIO IS NOT NULL THEN @IDUSUARIO ELSE USUARIO END

   DECLARE TSETDEF_CURSOR CURSOR FOR 
   SELECT USUARIO,FECHA, TIPOPERSONAL, TIPO_USUARIO  FROM TSECRES
   WHERE YEAR(FECHA)=@ANO
   AND MONTH(FECHA)=@MES
   AND ESTADO='Definitivo'
   AND USUARIO=CASE WHEN @IDUSUARIO IS NOT NULL THEN @IDUSUARIO ELSE USUARIO END
   AND NOT EXISTS(SELECT * FROM TSECRES X WHERE YEAR(X.FECHA)=@ANO
   AND MONTH(X.FECHA)=@MES AND X.ESTADO<>'Definitivo' AND X.FECHA=TSECRES.FECHA AND X.USUARIO=TSECRES.USUARIO)
   ORDER BY USUARIO 
   OPEN TSETDEF_CURSOR    
   FETCH NEXT FROM TSETDEF_CURSOR    
   INTO @USUARIO,@FECHA, @TIPOPERSONAL, @TIPO_USUARIO
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
      UPDATE TSECFU SET RESUM=1  WHERE YEAR(FECHA)=@ANO
      AND MONTH(FECHA)=@MES
      AND COALESCE(RESUM,0)=0
      AND USUARIO=@USUARIO 
      AND FECHA=@FECHA 

      FETCH NEXT FROM TSETDEF_CURSOR    
      INTO @USUARIO,@FECHA, @TIPOPERSONAL, @TIPO_USUARIO
   END
   CLOSE TSETDEF_CURSOR
   DEALLOCATE TSETDEF_CURSOR
-- CREO EL RESUMEN
 
--LIMPIO LA TABLA DEL PERIODO 
  SELECT @PERIODO=@ANO+CASE WHEN @MES<10 THEN '0'+CAST(@MES AS VARCHAR(1)) ELSE CAST(@MES AS VARCHAR(2)) END

  DELETE TURESUM  WHERE PERIODO=@PERIODO AND ESTADO='Abierto'  AND USUARIO=CASE WHEN @IDUSUARIO IS NOT NULL THEN @IDUSUARIO ELSE USUARIO END

  INSERT INTO TURESUM( PERIODO, USUARIO, TIPOPERSONAL, TIPO_USUARIO, CODNOV, HCUMP, HPEND, HNOV, ESTADO)
  SELECT @PERIODO,USUARIO,TIPOPERSONAL,TIPO_USUARIO,'',SUM(HCUMP),SUM(HPEND),SUM(HNOV),'Abierto'
  FROM TSECRES
  WHERE YEAR(FECHA)=@ANO
  AND MONTH(FECHA)=@MES
  GROUP BY USUARIO,TIPOPERSONAL,TIPO_USUARIO

-- LLENO LAS NOVDEDADES
-- BORRO LO QUE ESTA Abierto
--
  DELETE TURNOV WHERE ESTADO='Abierto' AND PERIODO=@PERIODO AND USUARIO=CASE WHEN @IDUSUARIO IS NOT NULL THEN @IDUSUARIO ELSE USUARIO END

  INSERT INTO TURNOV(PERIODO, USUARIO, TIPOPERSONAL, TIPO_USUARIO, CODNOV, HNOV, ESTADO, CNSPAGO)
  SELECT @PERIODO,USUARIO,TIPOPERSONAL,TIPO_USUARIO,CODNOV,SUM(HNOV),'Abierto',NULL
  FROM TSECRES
  WHERE YEAR(FECHA)=@ANO
  AND MONTH(FECHA)=@MES
  AND COALESCE(CODNOV,'')<>''
  AND COALESCE(HNOV,0)>0
  AND ESTADO='Definitivo'
  GROUP BY USUARIO,TIPOPERSONAL,TIPO_USUARIO,CODNOV
END