IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_GENERA_PROVISIONES' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_GENERA_PROVISIONES
END

GO
CREATE PROCEDURE [dbo].[SPK_GENERA_PROVISIONES]
@CNS        VARCHAR(20),
@CNSRESUMEN VARCHAR(20),
@FECHA      DATETIME   ,
@USUARIO    VARCHAR(20),
@IDSEDE     VARCHAR(2),
@COMPANIA   VARCHAR(5),
@CLASE     VARCHAR(10)
WITH ENCRYPTION
AS 
BEGIN
   DECLARE @CNSPROV VARCHAR(20)
   DECLARE @TOTAL   DECIMAL(14,2)
   
   
   SET @CNSPROV = SPACE(20)
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSPROV',  @CNSPROV OUTPUT  
   SELECT @CNSPROV = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSPROV))+LTRIM(RTRIM(@CNSPROV)),SPACE(1),0)
   
   INSERT INTO KPRO (TIPO,CNSPROV, FECHA, USUARIO,ANIO,MES,ESTADO,CLASE)
   SELECT 'PRO',@CNSPROV,@FECHA,@USUARIO,YEAR(@FECHA),MONTH(@FECHA),'Pendiente',@CLASE
   
   --SELECT * FROM KPROVD
   --SELECT TOP 10 * FROM RPDX WHERE CNS='0106781105'

   
   INSERT INTO KPROV(TIPO, CNSPROV, FECHA, USUARIO, ANIO, MES, CATEGORIA, TOTAL, ESTADO, IDTERCERO, NROCOMPROBANTE, SALDOFTR)
   SELECT 'PRO',@CNSPROV,@FECHA,@USUARIO,YEAR(@FECHA),MONTH(@FECHA),ID2,SUM(VALOR3),'Pendiente',IDTERCERO,NULL,VALOR1
   FROM RPDX WHERE CNS=@CNSRESUMEN
   GROUP BY ID2,IDTERCERO,VALOR1
   ORDER BY IDTERCERO
   
   INSERT INTO KPROVD(TIPO, CNSPROV, IDTERCERO, FECHA, N_FACTURA, CATEGORIA, DIAS, SALDONETO, ESTADO, AREAFUNCIONAL, CCOSTO, NROCBTE_PCONTABLE)
   SELECT 'PRO',@CNSPROV,IDTERCERO,@FECHA,ID1,ID2,MAX(CANTIDAD1),SUM(VALOR3),'Pendiente',NULL,NULL,NULL
   FROM RPDX WHERE CNS=@CNS
   GROUP BY IDTERCERO,ID1,ID2
   ORDER BY IDTERCERO
   
   SELECT @TOTAL=SUM(VALOR3) FROM RPDX WHERE CNS=@CNS
   
   UPDATE KPRO SET TOTAL= @TOTAL WHERE CNSPROV=@CNSPROV

END


