IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_PROCESO_VACACIONES' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_PROCESO_VACACIONES
END
GO
CREATE PROCEDURE DBO.SPK_PROCESO_VACACIONES 
@CNSPAGO  VARCHAR(20),
@PROCESO  VARCHAR(10),
@NUMDOCR   VARCHAR(20)=NULL
WITH ENCRYPTION
AS  
DECLARE @EXISTE INT
DECLARE @NUMDOC     VARCHAR(20)
DECLARE @CODCARGO   VARCHAR(20)
DECLARE @NIVEL      VARCHAR(10)
DECLARE @GRADO      VARCHAR(10)
DECLARE @FECHAING   DATETIME
DECLARE @FFINAL     DATETIME
DECLARE @FINICIAL   DATETIME
DECLARE @NPERIODOS  SMALLINT
DECLARE @ANOS       SMALLINT
DECLARE @MAX        SMALLINT
DECLARE @FECHARET   DATETIME
DECLARE @FECHACORTE DATETIME
DECLARE @F_ACTUALIZA DATETIME
DECLARE @ITEMV INT
DECLARE @DIASG DECIMAL(7,4)
DECLARE @DIASP DECIMAL(7,4)
DECLARE @DIASC DECIMAL(7,2)
BEGIN 
   SELECT @FECHACORTE=NULL
   IF COALESCE(@CNSPAGO,'')<>''
   BEGIN
      DECLARE PG_VACANOMI CURSOR FOR  
      SELECT NEMP.NUMDOC,CODCARGO,NIVEL,GRADO,FECHAINGRESO,NEDIA.FECHAFIN
      FROM NEMP INNER JOIN NEDIA ON NEMP.NUMDOC=NEDIA.NUMDOC
      WHERE EXISTS(SELECT * FROM NIEPE WHERE NEMP.NUMDOC=NIEPE.NUMDOC AND CNSPAGO=@CNSPAGO)
      AND NEDIA.CNSPAGO=@CNSPAGO
      AND NEDIA.IDEVENTO='RET'
      AND NEMP.NUMDOC=@NUMDOCR
   END
   ELSE
   BEGIN 
      DECLARE PG_VACANOMI CURSOR FOR  
      SELECT NUMDOC,CODCARGO,NIVEL,GRADO,FECHAINGRESO,COALESCE(FECHARETIRO,GETDATE()+1) 
      FROM NEMP
      WHERE ESTADO='Activo'
     -- AND COALESCE(FECHARETIRO,GETDATE()+1)>GETDATE()
      AND NUMDOC=CASE WHEN @NUMDOCR IS NULL THEN NUMDOC ELSE @NUMDOCR END
   END    
	OPEN PG_VACANOMI    
	FETCH NEXT FROM PG_VACANOMI    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@FECHAING,@FECHARET
	WHILE @@FETCH_STATUS = 0    
	BEGIN 
      PRINT '@NUMDOC='+@NUMDOC+ '@FECHARET='+CONVERT(VARCHAR,@FECHARET,103)
      SELECT  @F_ACTUALIZA=MAX(FECHAFIN)
      FROM NPER INNER JOIN NIEPE ON NPER.CNSPAGO=NIEPE.CNSPAGO
      WHERE NIEPE.NUMDOC=@NUMDOC
      AND NPER.CERRADO=1

      IF ISDATE(@FECHARET)=0
      BEGIN 
         SELECT @FECHACORTE=FECHAFIN FROM NPER WHERE CNSPAGO=@CNSPAGO
      END
      ELSE
      BEGIN
         SELECT @FECHACORTE=@FECHARET
         IF DBO.FNK_VALORVARIABLE('PERIODO_VACACIONES')='VIGENCIA'
         BEGIN
            SELECT @FECHAING=CAST('01/01/'+CONVERT(VARCHAR(4),YEAR(GETDATE())) AS date)
         END
      END
      IF ISDATE(@FECHACORTE)=0
      BEGIN 
         SELECT @FECHACORTE=@F_ACTUALIZA
      END
      PRINT '@FECHACORTE ='+CONVERT(VARCHAR,@FECHACORTE,103)
      PRINT '@FECHAING ='+CONVERT(VARCHAR,@FECHAING,103)
      IF EXISTS(SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC AND F_INICAL>@FECHACORTE)
      BEGIN
         PRINT 'Borramos periodos posteriores a la fecha de corte'
         DELETE NEMPV WHERE NUMDOC=@NUMDOC AND F_INICAL>=@FECHACORTE
      END
      SELECT @NPERIODOS=COALESCE(NVACACIONES,1) FROM NCARNG WHERE CODCARGO=@CODCARGO AND NIVEL=@NIVEL AND GRADO=@GRADO
      SELECT @MAX=MAX(ITEM) FROM NEMPV WHERE NUMDOC=@NUMDOC
      IF NOT EXISTS(SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC) OR COALESCE((SELECT MAX(F_FINAL) FROM NEMPV WHERE NUMDOC=@NUMDOC),@FECHAING)<COALESCE(@FECHACORTE,GETDATE())
      BEGIN
         PRINT 'INGRESO CON @NPERIODOS='+STR(@NPERIODOS)
         IF COALESCE(@NPERIODOS,0)>0
         BEGIN
            SELECT @ANOS=(DBO.FNK_DATEDIFF360(@FECHAING,@FECHACORTE)/360.00)+CASE WHEN (DBO.FNK_DATEDIFF360(@FECHAING,@FECHACORTE)%360.00)>0 THEN 1 ELSE 0 END
            PRINT '@ANOS = '+STR(@ANOS)
            IF NOT EXISTS(SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC)
            BEGIN
               PRINT 'COLOCAMOS LOS PERIODOS...'
               DECLARE @ANOSC INT
               SELECT @ANOSC =CASE WHEN @ANOS<=4 THEN @ANOS ELSE @ANOS-4 END

               SELECT @FINICIAL=CASE WHEN @ANOS<=4 THEN @FECHAING ELSE DATEADD(YEAR,-4,@FECHAING) END
               WHILE @ANOSC >0
               BEGIN
                  PRINT '@ANOSC = '+STR(@ANOSC)
                  PRINT '@FINICIAL ='+CONVERT(VARCHAR,@FINICIAL,103)
                  SELECT @MAX=MAX(ITEM) FROM NEMPV WHERE NUMDOC=@NUMDOC
                  SELECT @MAX=COALESCE(@MAX,0)+1  
                  
                  INSERT INTO NEMPV(NUMDOC, ITEM, CONCEPTO, F_CUMPLE, NDIAS, F_INICAL, F_FINAL, CNSPAGO, ESTADO, DIASG, DIASP)
                  SELECT @NUMDOC, @MAX, NULL, DATEADD(YEAR,1,@FECHAING), 15*@NPERIODOS, @FINICIAL, DATEADD(YEAR,1,@FINICIAL)-1, NULL, 'Proceso', 0, 0

                  SELECT @FINICIAL=(F_FINAL)+1 FROM NEMPV WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
                  UPDATE NEMPV SET DIASG=CASE WHEN F_FINAL<@FECHACORTE THEN 15.00 ELSE ((DBO.FNK_DATEDIFF360(F_INICAL,CASE WHEN F_INICAL>=COALESCE(@FECHARET,@FECHACORTE) THEN F_INICAL ELSE COALESCE(@FECHARET,@FECHACORTE)END)*(15.00*@NPERIODOS))/360) END
                  WHERE NUMDOC=@NUMDOC AND ITEM=@MAX  
                  IF @FINICIAL>GETDATE()
                  BEGIN
                     BREAK
                  END                  
                  SELECT @FFINAL=DATEADD(YEAR,1,@FINICIAL) 
                  SELECT @ANOSC=@ANOSC-1
               END
            END
            ELSE
            BEGIN
               SELECT @FINICIAL=(F_FINAL) FROM NEMPV WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
               SELECT @FFINAL=DATEADD(YEAR,1,@FINICIAL)
            END
         END
         IF COALESCE(@CNSPAGO,'')<>'' AND COALESCE(@NPERIODOS,0)>0
         BEGIN
            SELECT @MAX=MAX(ITEM) FROM NEMPV WHERE NUMDOC=@NUMDOC
            IF @PROCESO='CIERRE'
            BEGIN
               UPDATE NEMPV SET DIASG=DIASG+(NDIAS/12.00) WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
            END
            IF @PROCESO='ABRE'
            BEGIN
               UPDATE NEMPV SET DIASG=DIASG-(NDIAS/12.00) WHERE NUMDOC=@NUMDOC AND ITEM=@MAX
            END
         END
      END
	  ELSE
	  BEGIN
      PRINT 'INGRESO POR EL ELSE 1'
		IF EXISTS( SELECT * FROM NEMPV WHERE NUMDOC=@NUMDOC AND ESTADO='Proceso')
		BEGIN
         PRINT 'VOY A ACTUALIZAR EL ITEM EN PROCESO...'
         PRINT '@FECHARET='+CONVERT(VARCHAR,@FECHARET,103)
         PRINT '@FECHACORTE'+CONVERT(VARCHAR,@FECHACORTE,103)
         
			UPDATE NEMPV SET DIASG= CASE WHEN F_FINAL<@FECHACORTE THEN 15.00 ELSE ((DBO.FNK_DATEDIFF360(F_INICAL,CASE WHEN F_INICAL>=COALESCE(@FECHARET,@FECHACORTE) THEN F_INICAL ELSE COALESCE(@FECHARET,@FECHACORTE)END)*(15.00*@NPERIODOS))/360) END,
         ESTADO=CASE WHEN F_FINAL<@FECHACORTE  THEN CASE WHEN  DIASP<NDIAS  THEN 'Cumplidas' ELSE 'Pagado' END  ELSE 'Proceso' END
			WHERE NUMDOC=@NUMDOC AND ESTADO='Proceso'
		END	
	  END
     IF COALESCE(@NPERIODOS,0)<=0
     BEGIN
        UPDATE NEMPV SET DIASG=0 WHERE NUMDOC=@NUMDOC AND ESTADO='Proceso'
     END
      DECLARE NEMPVD_CURSOR CURSOR FOR 
      SELECT ITEM,COALESCE(DIASG,0),COALESCE(DIASP,0)  FROM NEMPV 
      WHERE NUMDOC=@NUMDOC
      ORDER BY   ITEM
      OPEN NEMPVD_CURSOR    
      FETCH NEXT FROM NEMPVD_CURSOR    
      INTO @ITEMV,@DIASG,@DIASP
      WHILE @@FETCH_STATUS = 0    
      BEGIN 
         IF @DIASP<@DIASG
         BEGIN
            SELECT @DIASC= SUM(NDIAS) FROM  NEMPVD WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV AND COALESCE(ESTADO,'')<>'Anulado'
            UPDATE NEMPV SET DIASP=COALESCE(@DIASC,0) WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
            UPDATE NEMPV SET ESTADO=CASE WHEN DIASG>=NDIAS THEN  CASE WHEN DIASP>=DIASG THEN  'Pagado' ELSE 'Cumplidas'  END ELSE 'Proceso' END  WHERE NUMDOC=@NUMDOC AND ITEM=@ITEMV
         END

         FETCH NEXT FROM NEMPVD_CURSOR    
         INTO @ITEMV,@DIASG,@DIASP
      END
      CLOSE NEMPVD_CURSOR
      DEALLOCATE NEMPVD_CURSOR

	FETCH NEXT FROM PG_VACANOMI    
	INTO @NUMDOC,@CODCARGO,@NIVEL,@GRADO,@FECHAING,@FECHARET
	END
	CLOSE PG_VACANOMI
	DEALLOCATE PG_VACANOMI   
END


