IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='BCO_CTA_SUC_IZIPAY')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO,OBSERVACION)
   SELECT 'BCO_CTA_SUC_IZIPAY','Datos banco, cuenta, sucursa IZIPAY BCO|CTA|SU','Alfanumerica','','Ingresar los datos de BCT separados por |'
END