IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME ='SPK_ADDDEL_CONCEPTOS_DE_CARGOS_NUMDOC' AND XTYPE='P')
BEGIN
	DROP PROCEDURE SPK_ADDDEL_CONCEPTOS_DE_CARGOS_NUMDOC
END
GO
CREATE PROCEDURE [dbo].[SPK_ADDDEL_CONCEPTOS_DE_CARGOS_NUMDOC]    
@OPERACION VARCHAR(12),    
@CNSPAGO VARCHAR(20),
@NUMDOC  VARCHAR(20)
WITH ENCRYPTION
AS    
DECLARE @FECHAINI        DATETIME    
DECLARE @FECHAFIN        DATETIME    
DECLARE @CODCARGO_CUR    VARCHAR(20)    
DECLARE @CODCONCEPTO_CUR VARCHAR(20)    
DECLARE @ITEM            VARCHAR(8)    
DECLARE @ITEM_N          INT    
DECLARE @ITEM_NEW        VARCHAR(8)    
DECLARE @NIVEL           VARCHAR(10)    
DECLARE @GRADO           VARCHAR(10)      
DECLARE @CODPLANTA       VARCHAR(20)    
DECLARE @MAXITEM         SMALLINT  
DECLARE @CODNOMINA       VARCHAR(2)   
DECLARE @MAXLINEA        INT  
DECLARE @LINEA           INT  
DECLARE @PTOPE           DECIMAL(14,6)  
DECLARE @INGRESOS        DECIMAL(15,6)  
DECLARE @EGRESOS         DECIMAL(15,6)  
DECLARE @VALOR_EMPLEADO  DECIMAL(15,6)  
DECLARE @ESTADO          VARCHAR(12)  
DECLARE @INFO            VARCHAR(2)  
DECLARE @V_VALOR_EMPLEADO    DECIMAL(15,6)  
DECLARE @V_VALOR_EMPRESA     DECIMAL(15,6)  
DECLARE @V_CANTIDAD          DECIMAL(15,6)  
DECLARE @V_IDTRANSPRESTAMO   VARCHAR(6)  
DECLARE @V_NUMDOCPRESTAMO    VARCHAR(20)  
DECLARE @V_NUMCUOTA          SMALLINT  
DECLARE @V_CODPRF            VARCHAR(20)  
DECLARE @V_IDTERCERO         VARCHAR(20)  
DECLARE @V_DETALLE           VARCHAR(10)  
DECLARE @V_VALOR100P         DECIMAL(15,6)  
DECLARE @V_BASE_PRESTACIONES VARCHAR(2)  
DECLARE @V_ITEMCONCEPTO      DECIMAL(14,0)  
DECLARE @HORAS_LAB           INT  
DECLARE @DIAS_LAB            INT  
DECLARE @GENERANOVEFU        SMALLINT  
DECLARE @CODNOVEFU           VARCHAR(20)  
DECLARE @BASE_CALCULO        DECIMAL(15,6)  
DECLARE @NUMDOC_CUR          VARCHAR(20)
DECLARE @NUMDOCN             VARCHAR(20)
DECLARE @NUMDOC_ANT          VARCHAR(20)
DECLARE @INCLUIR_EXCLUIR     VARCHAR(12)
DECLARE @TIPO                VARCHAR(12)
DECLARE @PRIORIDAD           INT
DECLARE @INS_NUMDOC VARCHAR(20),
        @INS_CNSPAGO VARCHAR(20),
        @INS_ITEM VARCHAR(8),
        @INS_LINEA	SMALLINT,
        @INS_CODCONCEPTO VARCHAR(20),
        @INS_DETALLE VARCHAR(10),
        @INS_VALOR	DECIMAL	(14,5),
        @INS_VALOR_EMPRESA	DECIMAL	(14,5),
        @INS_VALOR100P DECIMAL(14,5),
        @INS_CANTIDAD DECIMAL(14,5),
        @INS_IDTRANSPRESTAMO VARCHAR(6),
        @INS_NUMDOCPRESTAMO VARCHAR(20),
        @INS_NUMCUOTA SMALLINT,
        @INS_CODPRF VARCHAR(20),
        @INS_IDTERCERO VARCHAR(20),
        @INS_PSOBREINGRESOS DECIMAL(14,5),
        @INS_INCLUIR_EXCLUIR VARCHAR(12),
        @INS_LIQUIDAR VARCHAR(2),
        @INS_INFO VARCHAR(2),
        @INS_BASE_PRESTACIONES VARCHAR(2),
        @INS_ITEMCONCEPTO SMALLINT,
        @INS_CODCONCEPTO_PADRE VARCHAR(20),
        @INS_LINEA_PADRE SMALLINT,
        @INS_VALHORASLAB SMALLINT,
        @INS_GENERANOVEFU SMALLINT,
        @INS_CODNOVEFU VARCHAR(10),
        @INS_BASE_CALCULO DECIMAL(14,5)
DECLARE @PERIODOS SMALLINT
DECLARE @PERACTUAL VARCHAR(6)
DECLARE @VLRPROMEDIO DECIMAL(14,2)
DECLARE @IDPLANILLA VARCHAR(20)
DECLARE @RETIRO SMALLINT
BEGIN    
   SET @HORAS_LAB = -1 -- Indica que la Base de las Horas a liquidar se toman del Item de Concepto (NCOND.HORAS)  
   SET @DIAS_LAB  = -1 -- Indica que la Base de los Dias a liquidar se toman del Item de Concepto (NCOND.DIAS)  
   -------------------------------------------------------------------------------------------------  
   --- BUSCAMOS EL PAGO Y ALMACENAMOS SUS DATOS EN VARIABLES  
   -------------------------------------------------------------------------------------------------  
    SELECT @FECHAINI  = NPER.FECHAINI,   
           @FECHAFIN  = NPER.FECHAFIN,  
           @CODNOMINA = NOMI.CODNOMINA,  
           @PTOPE     = NOMI.MAXADEDUCIR,
           @IDPLANILLA=NOMI.IDPLANTILLA
    FROM NPER INNER JOIN NOMI ON NPER.CNSPAGO   = @CNSPAGO 
                             AND NPER.CODNOMINA = NOMI.CODNOMINA  
              INNER JOIN NOMIE ON NOMI.CODNOMINA=NOMIE.CODNOMINA
    WHERE NOMIE.NUMDOC=@NUMDOC
    IF @PTOPE IS NULL  
       SET @PTOPE=0  

    DELETE NEMPFD_RUN
    FROM NEMPFD_RUN X 
    WHERE X.CNSPAGO = @CNSPAGO AND X.NUMDOC = CASE WHEN ISNULL(@NUMDOC,'') = '' THEN NUMDOC ELSE @NUMDOC END AND
          X.SYS_COMPUTERNAME = HOST_NAME()

    --DBCC CHECKIDENT (NEMPFD_RUN, RESEED, 0)

    PRINT 'Borrando Empleados del Pago...'
    DELETE NEMPFD WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC
    DELETE NEMPF WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC
 
   ---- OPERACION ADICION  
   IF @OPERACION='ADD'    
   BEGIN    
      SELECT @ITEM=MAX(ITEM) FROM NEMPF WHERE LEFT(ITEM,3)='CAR' AND CNSPAGO=@CNSPAGO  AND NUMDOC=@NUMDOC
      IF @ITEM IS NULL OR @ITEM=''    
      BEGIN    
         PRINT 'NUEVO ITEM '
         SET @ITEM_NEW='CAR00001'    
      END    
      ELSE    
      BEGIN    
         SET @ITEM=RIGHT(@ITEM,5)    
         SET @ITEM_N=CAST(@ITEM AS INT)    
         SET @ITEM_N=@ITEM_N+1    
         SET @ITEM_NEW='CAR'+RIGHT('0000'+RTRIM(LTRIM(STR(@ITEM_N))),5)    
         PRINT 'SUMA DE ITEM '+@CODCARGO_CUR+' '+@ITEM_NEW    
      END     

      PRINT 'Insertando NEMPF...'
      INSERT INTO NEMPF(CNSPAGO, NUMDOC, ITEM)    
      SELECT @CNSPAGO, NEMP.NUMDOC, @ITEM_NEW
      FROM   NEMP INNER JOIN NOMIE ON NEMP.NUMDOC     = NOMIE.NUMDOC 
                                  AND NOMIE.CODNOMINA = @CODNOMINA 
                                  AND NOMIE.ESTADO    = 'Activo' 
                                  AND NEMP.ESTADO     = 'Activo' 
                   LEFT JOIN NEMPF ON NEMP.NUMDOC     = NEMPF.NUMDOC 
                                  AND NEMPF.CNSPAGO   = @CNSPAGO
      WHERE  NEMP.NUMDOC =@NUMDOC
   
      -- GENERANDO INGRESOS   
      PRINT 'Declarando Cursor de Ingresos...'
      DECLARE CUR_NCON CURSOR FOR    
     SELECT V.CODCONCEPTO, V.CODPLANTA, V.NUMDOC, V.ITEM, V.INFO  
      FROM (SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Ingreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
            AND NEMPF.NUMDOC=@NUMDOC
			AND NCON.CLASE IN('Normal','Tabla')
			AND NOT EXISTS(SELECT * FROM NEVE WHERE NCON.CODCONCEPTO=NEVE.CODCONCEPTO)
			UNION ALL
			SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Ingreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
            AND NEMPF.NUMDOC=@NUMDOC
			AND NCON.CLASE IN('Normal','Tabla')
		--	AND EXISTS(SELECT * FROM NEVE WHERE NCON.CODCONCEPTO=NEVE.CODCONCEPTO)
			AND EXISTS(SELECT * FROM NEDIA INNER JOIN NEVE ON NEDIA.IDEVENTO=NEVE.IDEVENTO 
				WHERE NCON.CODCONCEPTO=NEVE.CODCONCEPTO AND NEDIA.CNSPAGO=@CNSPAGO AND NEDIA.NUMDOC=@NUMDOC)
			UNION ALL
			SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Ingreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
			AND NCON.CLASE='Particular'
			AND EXISTS(SELECT * FROM NEMPDA WHERE NUMDOC=@NUMDOC AND NCON.CODCONCEPTO=NEMPDA.CODCONCEPTO )
			UNION ALL
			SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Ingreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
            AND NEMPF.NUMDOC=@NUMDOC
			AND NCON.CLASE='Manual'
			AND EXISTS(SELECT * FROM NPERC WHERE NUMDOC=@NUMDOC AND CNSPAGO=@CNSPAGO AND NCON.CODCONCEPTO=NPERC.CODCONCEPTO )
           ) AS V  
      ORDER BY V.NUMDOC, V.TIPO DESC, ISNULL(V.PRIORIDAD,0), V.CODCONCEPTO 
      -- DELETE NEMPFD_RUN WHERE SYS_COMPUTERNAME = HOST_NAME() AND CNSPAGO=@CNSPAGO AND TIPO='Ingreso'
   
      OPEN CUR_NCON    
      FETCH NEXT FROM CUR_NCON    
      INTO @CODCONCEPTO_CUR, @CODPLANTA, @NUMDOCN, @ITEM, @INFO  
      SET @LINEA = 0  
      WHILE @@FETCH_STATUS = 0    
      BEGIN    
         PRINT 'Insertando Ingresos... @ITEM ='+@ITEM+' - @CODCONCEPTO_CUR='+@CODCONCEPTO_CUR+' - @INFO='+@INFO
         PRINT '@HORAS_LAB='+CAST(@HORAS_LAB AS VARCHAR(10))
         PRINT '@DIAS_LAB='+CAST(@DIAS_LAB AS VARCHAR(10))
         PRINT '@FECHAINI='+CAST(@FECHAINI AS VARCHAR(20))
         PRINT '@FECHAFIN='+CAST(@FECHAFIN AS VARCHAR(20))
      
         INSERT INTO NEMPFD_RUN (NUMDOC, CNSPAGO, ITEM, CODCONCEPTO, DETALLE, CANTIDAD, VALOR, VALOR_EMPRESA, VALOR100P,   
                                 IDTRANSPRESTAMO, NUMDOCPRESTAMO, NUMCUOTA, CODPRF, IDTERCERO, INCLUIR_EXCLUIR, LIQUIDAR, INFO,   
                                 BASE_PRESTACIONES, ITEMCONCEPTO, VALHORASLAB, GENERANOVEFU, CODNOVEFU, BASE_CALCULO, TIPO,SYS_COMPUTERNAME)    
         SELECT @NUMDOC, @CNSPAGO, @ITEM, @CODCONCEPTO_CUR, V.DETALLE, V.CANTIDAD, V.VALOR_EMPLEADO,   
                V.VALOR_EMPRESA, V.VALOR100P, V.IDTRANSPRESTAMO, V.NUMDOCPRESTAMO, V.NUMCUOTA, V.CODPRF, V.IDTERCERO,   
                'Automatica', 'Si', @INFO, V.BASE_PRESTACIONES, V.ITEMCONCEPTO, 1, V.GENERANOVEFU, V.CODNOVEFU, V.BASE_CALCULO, 'Ingreso',HOST_NAME()
         FROM DBO.FNK_VALORCONCEPTO_NEMPFD_RUN(@NUMDOC,@CODCONCEPTO_CUR,@FECHAINI,@FECHAFIN,@CNSPAGO,1, @HORAS_LAB, @DIAS_LAB) AS V  
         WHERE ( V.VALOR_EMPLEADO + V.VALOR_EMPRESA ) > 0  
  
         FETCH NEXT FROM CUR_NCON    
         INTO @CODCONCEPTO_CUR, @CODPLANTA ,@NUMDOCN, @ITEM, @INFO  
      END      
      CLOSE CUR_NCON    
      DEALLOCATE CUR_NCON    
      IF DBO.FNK_VALORVARIABLE('FORMALIQRETIROS')<>'OTRASIPS'
      BEGIN
         --JEDM: 2014.06.09_001
         -- Proceso de Retiro
         EXEC SPK_CALCULAR_RETIROS @CNSPAGO,@NUMDOC
      END
      -- GENERANDO EGRESOS  
      PRINT 'Declarando Cursor de Egresos...'
      DECLARE CUR_NCON CURSOR FOR    
      SELECT V.CODCONCEPTO, V.CODPLANTA, V.NUMDOC, V.ITEM, V.INFO  
       FROM (SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Egreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
            AND NEMPF.NUMDOC=@NUMDOC
			AND NCON.CLASE='Aporte'
			AND EXISTS(SELECT * FROM NCOND WHERE NCON.CODCONCEPTO=NCOND.CODCONCEPTO AND EXISTS(SELECT * FROM NPRFE WHERE NCOND.CODPRF=NPRFE.CODPRF AND NPRFE.NUMDOC=@NUMDOC))
			UNION ALL
			SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Egreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
            AND NEMPF.NUMDOC=@NUMDOC
			AND NCON.CLASE IN('Parafiscal','Tabla','Prestamo','Normal','Provision','Tabla                                                                                                                                                                                                                                                       ')
			UNION ALL
			SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Egreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
			AND NCON.CLASE='Particular'
			AND EXISTS(SELECT * FROM NEMPDA WHERE NUMDOC=@NUMDOC AND NCON.CODCONCEPTO=NEMPDA.CODCONCEPTO )
			UNION ALL
			SELECT NCON.CODCONCEPTO,NCON.DESCRIPCION,NCON.CLASE, Z.CODPLANTA, NEMPF.NUMDOC, NEMPF.ITEM, NCON.TIPO, NCON.INFO,   
                   PRIORIDAD=CASE WHEN ISNULL(NCON.PRIORIDAD,0)=0 THEN 999999 ELSE NCON.PRIORIDAD END  
            FROM   NPLTCO X INNER JOIN NPLTCA Y ON X.IDPLANTILLA=Y.IDPLANTILLA
                          INNER JOIN FNK_INFO_NEMPHIS_NEMP(@FECHAFIN,@NUMDOC) Z ON Z.CODCARGO = Y.CODCARGO 
                                                                  AND Z.NIVEL    = Y.NIVEL 
                                                                  AND Z.GRADO    = Y.GRADO 
                          INNER JOIN NCON   ON X.CODCONCEPTO       = NCON.CODCONCEPTO 
                                           AND NCON.TIPO   = 'Egreso' 
                                           AND NCON.ESTADO = 'Activo' 
                          INNER JOIN NEMPF  ON NEMPF.CNSPAGO = @CNSPAGO 
                                           AND NEMPF.NUMDOC  = Z.NUMDOC 
            WHERE  NCON.CODCONCEPTO <> 'RET'
			AND X.IDPLANTILLA=@IDPLANILLA
            AND NEMPF.NUMDOC=@NUMDOC
			AND NCON.CLASE='Manual'
			AND EXISTS(SELECT * FROM NPERC WHERE NUMDOC=@NUMDOC AND CNSPAGO=@CNSPAGO AND NCON.CODCONCEPTO=NPERC.CODCONCEPTO )
           ) AS V  
      ORDER BY V.NUMDOC, V.TIPO DESC, ISNULL(V.PRIORIDAD,0), V.CODCONCEPTO 
      -- DELETE NEMPFD_RUN WHERE SYS_COMPUTERNAME = HOST_NAME() AND CNSPAGO=@CNSPAGO AND TIPO='Egreso'
    
      OPEN CUR_NCON    
  
      FETCH NEXT FROM CUR_NCON    
      INTO @CODCONCEPTO_CUR, @CODPLANTA, @NUMDOCN, @ITEM, @INFO  
      WHILE @@FETCH_STATUS = 0    
      BEGIN   
         SET @INGRESOS = 0  
         SET @EGRESOS  = 0  
         PRINT 'Calculando Ingresos y Egresos...'
         SELECT @INGRESOS = SUM(CASE WHEN NCON.TIPO='Ingreso' THEN VALOR ELSE 0 END), 
                @EGRESOS  = SUM(CASE WHEN NCON.TIPO='Egreso' THEN VALOR ELSE 0 END)
         FROM NEMPFD_RUN NEMPFD INNER JOIN 
              NCON ON NEMPFD.CODCONCEPTO=NCON.CODCONCEPTO AND CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND 
                      NEMPFD.LIQUIDAR='Si' AND ISNULL(NCON.INFO,'No') = 'No'   
         WHERE NEMPFD.SYS_COMPUTERNAME = HOST_NAME()
         PRINT 'Insertando Egresos...'
         PRINT @NUMDOC+','+@CODCONCEPTO_CUR+','+CONVERT(CHAR, @FECHAINI,103)+','+CONVERT(CHAR,@FECHAFIN,103)+','+@CNSPAGO+','+'1'+','+STR(@HORAS_LAB)+','+STR(@DIAS_LAB)
         INSERT INTO NEMPFD_RUN(NUMDOC, CNSPAGO, ITEM, CODCONCEPTO, DETALLE, CANTIDAD, VALOR, VALOR_EMPRESA, VALOR100P,  
                                IDTRANSPRESTAMO, NUMDOCPRESTAMO, NUMCUOTA, CODPRF, IDTERCERO, INCLUIR_EXCLUIR, LIQUIDAR, INFO,   
                                BASE_PRESTACIONES, ITEMCONCEPTO, VALHORASLAB, GENERANOVEFU, CODNOVEFU, BASE_CALCULO, TIPO,SYS_COMPUTERNAME)  
         SELECT @NUMDOC, @CNSPAGO, @ITEM, @CODCONCEPTO_CUR, V.DETALLE, V.CANTIDAD, V.VALOR_EMPLEADO,   
                V.VALOR_EMPRESA, V.VALOR100P, V.IDTRANSPRESTAMO, V.NUMDOCPRESTAMO, V.NUMCUOTA, V.CODPRF, V.IDTERCERO,   
                'Automatica', CASE WHEN ((@EGRESOS+V.VALOR_EMPLEADO)*100)/@INGRESOS>@PTOPE THEN 'No' ELSE 'Si' END, @INFO, 
                V.BASE_PRESTACIONES, V.ITEMCONCEPTO, 1, V.GENERANOVEFU, V.CODNOVEFU, V.BASE_CALCULO, 'Egreso',HOST_NAME() 
         FROM DBO.FNK_VALORCONCEPTO_NEMPFD_RUN(@NUMDOC,@CODCONCEPTO_CUR,@FECHAINI,@FECHAFIN,@CNSPAGO,1, @HORAS_LAB, @DIAS_LAB) AS V  
         WHERE ( V.VALOR_EMPLEADO + V.VALOR_EMPRESA ) > 0  
 
         FETCH NEXT FROM CUR_NCON    
         INTO @CODCONCEPTO_CUR, @CODPLANTA ,@NUMDOCN, @ITEM, @INFO  
      END    
      CLOSE CUR_NCON    
      DEALLOCATE CUR_NCON    
   END    
 
   DECLARE CUR_INST CURSOR FOR  
   SELECT NUMDOC, CNSPAGO, ITEM, CODCONCEPTO, DETALLE, VALOR, VALOR_EMPRESA, VALOR100P, CANTIDAD,
          IDTRANSPRESTAMO, NUMDOCPRESTAMO, NUMCUOTA, CODPRF, IDTERCERO, PSOBREINGRESOS, INCLUIR_EXCLUIR,
          LIQUIDAR, INFO, BASE_PRESTACIONES, ITEMCONCEPTO, CODCONCEPTO_PADRE, LINEA_PADRE, VALHORASLAB,
          GENERANOVEFU, CODNOVEFU, BASE_CALCULO
   FROM   NEMPFD_RUN 
   WHERE  SYS_COMPUTERNAME = HOST_NAME() 
   AND    CNSPAGO = @CNSPAGO  
   AND    NUMDOC=@NUMDOC
   ORDER BY NUMDOC, LINEA
   OPEN CUR_INST  
   
   FETCH NEXT FROM CUR_INST  
   INTO @INS_NUMDOC, @INS_CNSPAGO, @INS_ITEM, @INS_CODCONCEPTO, @INS_DETALLE, @INS_VALOR, @INS_VALOR_EMPRESA, 
        @INS_VALOR100P, @INS_CANTIDAD, @INS_IDTRANSPRESTAMO, @INS_NUMDOCPRESTAMO, @INS_NUMCUOTA, @INS_CODPRF, 
        @INS_IDTERCERO, @INS_PSOBREINGRESOS, @INS_INCLUIR_EXCLUIR, @INS_LIQUIDAR, @INS_INFO, @INS_BASE_PRESTACIONES, 
        @INS_ITEMCONCEPTO, @INS_CODCONCEPTO_PADRE, @INS_LINEA_PADRE, @INS_VALHORASLAB, @INS_GENERANOVEFU, 
        @INS_CODNOVEFU, @INS_BASE_CALCULO
   SET @NUMDOC_ANT = ''
   ALTER TABLE NEMPFD DISABLE TRIGGER TK_NEMPFD
   WHILE @@FETCH_STATUS = 0  
   BEGIN  
      IF @NUMDOC_ANT<>@INS_NUMDOC
      BEGIN
         SET @INS_LINEA = 0
         SET @NUMDOC_ANT = @INS_NUMDOC
      END
      SET @INS_LINEA = @INS_LINEA + 1  
      INSERT INTO NEMPFD(NUMDOC, CNSPAGO, ITEM, LINEA, CODCONCEPTO, DETALLE, VALOR, VALOR_EMPRESA, VALOR100P, CANTIDAD,
                         IDTRANSPRESTAMO, NUMDOCPRESTAMO, NUMCUOTA, CODPRF, IDTERCERO, PSOBREINGRESOS, INCLUIR_EXCLUIR,
                         LIQUIDAR, INFO, BASE_PRESTACIONES, ITEMCONCEPTO, CODCONCEPTO_PADRE, LINEA_PADRE, VALHORASLAB,
                         GENERANOVEFU, CODNOVEFU, BASE_CALCULO)   
      SELECT @INS_NUMDOC, @INS_CNSPAGO, @INS_ITEM, @INS_LINEA, @INS_CODCONCEPTO, @INS_DETALLE, @INS_VALOR, @INS_VALOR_EMPRESA, 
             @INS_VALOR100P, @INS_CANTIDAD, @INS_IDTRANSPRESTAMO, @INS_NUMDOCPRESTAMO, @INS_NUMCUOTA, @INS_CODPRF, 
             @INS_IDTERCERO, @INS_PSOBREINGRESOS, @INS_INCLUIR_EXCLUIR, @INS_LIQUIDAR, @INS_INFO, @INS_BASE_PRESTACIONES, 
             @INS_ITEMCONCEPTO, @INS_CODCONCEPTO_PADRE, @INS_LINEA_PADRE, @INS_VALHORASLAB, @INS_GENERANOVEFU, 
             @INS_CODNOVEFU, @INS_BASE_CALCULO 
       
      FETCH NEXT FROM CUR_INST  
      INTO @INS_NUMDOC, @INS_CNSPAGO, @INS_ITEM, @INS_CODCONCEPTO, @INS_DETALLE, @INS_VALOR, @INS_VALOR_EMPRESA, 
           @INS_VALOR100P, @INS_CANTIDAD, @INS_IDTRANSPRESTAMO, @INS_NUMDOCPRESTAMO, @INS_NUMCUOTA, @INS_CODPRF, 
           @INS_IDTERCERO, @INS_PSOBREINGRESOS, @INS_INCLUIR_EXCLUIR, @INS_LIQUIDAR, @INS_INFO, @INS_BASE_PRESTACIONES, 
           @INS_ITEMCONCEPTO, @INS_CODCONCEPTO_PADRE, @INS_LINEA_PADRE, @INS_VALHORASLAB, @INS_GENERANOVEFU, 
           @INS_CODNOVEFU, @INS_BASE_CALCULO
   END  
   CLOSE CUR_INST  
   DEALLOCATE CUR_INST  
   ALTER TABLE NEMPFD ENABLE TRIGGER TK_NEMPFD

   
   SELECT @RETIRO=COUNT(*) FROM NEDIA WHERE CNSPAGO = @CNSPAGO AND IDEVENTO = 'RET' AND NUMDOC=@NUMDOC

   IF @OPERACION='ADD' AND DBO.FNK_VALORVARIABLE('FORMALIQRETIROS')='OTRASIPS' AND @RETIRO>0
   BEGIN
      --JEDM: 2014.06.09_001
      -- Proceso de Retiro
      EXEC SPK_CALCULAR_RETIROS @CNSPAGO,@NUMDOC
      -- GENERANDO EGRESOS  
   END
   PRINT 'VAMOS A MIRAR LA RETENCION EN LA FUENTE EMPLEADOS'
   EXEC SPK_CALCULA_REFTE_NOMI @CNSPAGO,@NUMDOC,'Nomina'
   PRINT 'REVISO NUEVAMENTE LOS DESCUENTOS SI EXISTE ALGUNO QUE NO ALCANZO CON LA NOMINA Y DEBE SER COMPLETADA CON EL RETIRO '
   IF @RETIRO>0 AND EXISTS(SELECT * FROM NEMPFD WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND NEMPFD.LIQUIDAR='No' AND ISNULL(NEMPFD.INFO,'No') = 'No'  )
   BEGIN
      PRINT 'Calculando Ingresos y Egresos...'
      SELECT @INGRESOS = SUM(CASE WHEN NCON.TIPO='Ingreso' THEN VALOR ELSE 0 END), 
               @EGRESOS  = SUM(CASE WHEN NCON.TIPO='Egreso' THEN VALOR ELSE 0 END)
      FROM NEMPFD INNER JOIN 
            NCON ON NEMPFD.CODCONCEPTO=NCON.CODCONCEPTO AND CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND 
                     NEMPFD.LIQUIDAR='Si' AND ISNULL(NCON.INFO,'No') = 'No' 

      UPDATE NEMPFD SET  LIQUIDAR=CASE WHEN ((@EGRESOS+VALOR)*100)/@INGRESOS>@PTOPE THEN 'No' ELSE 'Si' END
      WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND NEMPFD.LIQUIDAR='No' AND ISNULL(NEMPFD.INFO,'No') = 'No'
   END

   PRINT 'Actualizando NEMPF...'  
   EXEC SPK_CALCULAR_NEMPF @CNSPAGO,@NUMDOC  
   UPDATE NEMPF SET CALC=1 WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC

   IF DBO.FNK_VALORVARIABLE('AUX_TRANS_VS_INGRESO')='SI'
   BEGIN 
      DECLARE @CODAUXTRANSP VARCHAR(20)
      DECLARE @SMLV DECIMAL(14,2)
      DECLARE @VLAUXTRASP DECIMAL(14,2)
      DECLARE @VLRINGRESOS DECIMAL(14,2)
      SELECT @CODAUXTRANSP=DBO.FNK_VALORVARIABLE('CODNOM_AUXTRANSPORTE'),@SMLV=CONVERT(DECIMAL(14,2),LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDSMMLV'))))
        
      
      SELECT @VLAUXTRASP=COALESCE(VALOR100P,0)  FROM NEMPFD WHERE CNSPAGO=@CNSPAGO AND CODCONCEPTO=@CODAUXTRANSP
      IF @VLAUXTRASP>0
      BEGIN 
         SELECT @VLRINGRESOS =VALOR_INGRESOS FROM NEMPF WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC
         IF (@VLRINGRESOS-@VLAUXTRASP)>(@SMLV*2)
         BEGIN
            DELETE NEMPFD WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND CODCONCEPTO=@CODAUXTRANSP
            PRINT 'Actualizando NEMPF...'  
            EXEC SPK_CALCULAR_NEMPF @CNSPAGO,@NUMDOC  
         END
      END

   END

   IF DBO.FNK_VALORVARIABLE('REDONCENT_APORTESNOM')='SI'
   BEGIN
      UPDATE NEMPFD SET VALOR= dbo.FNK_REDONDEA_MAS_EXCEL(VALOR,2),
                        VALOR_EMPRESA=dbo.FNK_REDONDEA_MAS_EXCEL(VALOR_EMPRESA,2),
                        VALOR100P=dbo.FNK_REDONDEA_MAS_EXCEL(VALOR100P,2)
      FROM NEMPFD INNER JOIN NPRF ON NEMPFD.CODPRF=NPRF.CODPRF
      WHERE CNSPAGO=@CNSPAGO
      AND NEMPFD.NUMDOC=@NUMDOC  
      AND NPRF.CLASE='Aporte'
   END
   PRINT 'Actualiza valores de NPER'
   UPDATE NPER SET 
   TOTAL_INGRESOS     = CASE WHEN V.TOTAL_INGRESOS IS NULL THEN 0 ELSE V.TOTAL_INGRESOS END, 
         TOTAL_EGRESOS      = CASE WHEN V.TOTAL_EGRESOS IS NULL THEN 0 ELSE V.TOTAL_EGRESOS END,  
         TOTAL_APORTES      = CASE WHEN V.TOTAL_APORTES IS NULL THEN 0 ELSE V.TOTAL_APORTES END,
   TOTAL_PARAFISCALES = CASE WHEN P.TOTAL_PARAFISCALES IS NULL THEN 0 ELSE P.TOTAL_PARAFISCALES END
   FROM NPER,
      (SELECT SUM(VALOR_INGRESOS) AS TOTAL_INGRESOS,SUM(VALOR_EGRESOS) AS TOTAL_EGRESOS,
         SUM(VALOR_APORTES) AS TOTAL_APORTES FROM NEMPF WHERE CNSPAGO=@CNSPAGO) V,
      (SELECT SUM(TOTAL_PARAFISCALES) AS TOTAL_PARAFISCALES
         FROM NPERP INNER JOIN NPRF ON NPRF.CODPRF=NPERP.CODPRF WHERE NPERP.CNSPAGO=@CNSPAGO AND NPRF.CLASE='Parafiscal') P
   WHERE CNSPAGO=@CNSPAGO

   UPDATE NPER SET TOTAL_NOMINA=TOTAL_INGRESOS+TOTAL_APORTES+TOTAL_PARAFISCALES 
   WHERE CNSPAGO=@CNSPAGO



   /*
   salario promedio
   */
   IF ISNUMERIC(LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('NROPERIODOS_SALAPROM'))))=1
   BEGIN
      SELECT @PERIODOS=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('NROPERIODOS_SALAPROM')))
      IF @PERIODOS-1<=0
      BEGIN
         PRINT 'No Existe Base para Salario Promedio'
         RETURN
      END
      SELECT @PERACTUAL= CAST(NPER.ANO+NPER.MES AS INT)-@PERIODOS FROM NPER WHERE CNSPAGO=@CNSPAGO
      PRINT 'PERIODO BASE ='+STR(@PERACTUAL)
      SELECT @VLRPROMEDIO= SUM(NEMPF.VALOR_INGRESOS)/@PERIODOS
      FROM NEMPF INNER JOIN NPER ON NEMPF.CNSPAGO=NPER.CNSPAGO
      WHERE NPER.CODNOMINA IN (SELECT LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('CODNOMINA_BASICA_MEN'))))
      AND NPER.CERRADO=1
      AND NEMPF.NUMDOC=@NUMDOC
      AND CAST(NPER.ANO+NPER.MES AS varchar(6))>=@PERACTUAL

      IF @VLRPROMEDIO>0
      BEGIN
         UPDATE NEMPF SET SALPROMEDIO=@VLRPROMEDIO WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC
      END
   END
   --PRINT 'ACTUALIZO LOS TERCEROS DE LA NOMINA'
   UPDATE NEMPFD SET IDTERCERO=NEMP.TERCEROID 
   FROM NEMPFD INNER JOIN NEMP ON IDTERCERO=NEMP.NUMDOC 
   WHERE CNSPAGO=@CNSPAGO 
   AND NEMPFD.NUMDOC=@NUMDOC 
   AND NEMP.NUMDOC=@NUMDOC
END