IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_PAGOSCAJA_QX' AND type = 'P')
   DROP PROCEDURE SPK_PAGOSCAJA_QX

GO
CREATE PROCEDURE DBO.SPK_PAGOSCAJA_QX 
@NOADMISION VARCHAR(16), 
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA   VARCHAR(2),
@SEDE       VARCHAR(5),  
@USUARIO    VARCHAR(12),
@IDTERCERO  VARCHAR(20),
@N_FACTURA  VARCHAR(20) = NULL
WITH ENCRYPTION
AS  
DECLARE @OK        SMALLINT
DECLARE @NVOCONSEC VARCHAR(20)
DECLARE @DATO      VARCHAR(80)
DECLARE @DATOFAC   VARCHAR(80)
DECLARE @VLRCOPAGO DECIMAL(14,2)
DECLARE @VLRPAGOCO DECIMAL(14,2)
DECLARE @VLRTOTAL  DECIMAL(14,2)
DECLARE @AUX       INT
DECLARE @VRDTO     DECIMAL(14,2)
DECLARE @DESCUENTO DECIMAL(14,2)
DECLARE @TIPODTO   VARCHAR(1)
DECLARE @RAZONSOCIAL VARCHAR(120)
DECLARE @IDAFILIADO  VARCHAR(20)
DECLARE @IDPLAN      VARCHAR(6) 
DECLARE @COPAGOVALOR DECIMAL(14,2)
DECLARE @TIPO_DOC    VARCHAR(10)
DECLARE @VRTOTAL     DECIMAL(14,2)
BEGIN
   SELECT @DATOFAC = DATO FROM USVGS WHERE IDVARIABLE = 'FORMA_FAC'
   IF @DATOFAC = 'IND'
   BEGIN
      SELECT @OK = 0
   END
   ELSE
   BEGIN
      SELECT   @OK = ISNULL(COUNT(*),0) FROM HADM WHERE NOADMISION = @NOADMISION AND COPAGO = 1
   END
     
   IF @OK > 0
   BEGIN
      RETURN
   END
   
   IF COALESCE(@N_FACTURA,'') = ''
   BEGIN
      SELECT @VLRCOPAGO = SUM(HPRED.VALORCOPAGO), @VLRPAGOCO = SUM(HPRED.VALORPCOMP),
             @VLRTOTAL  = SUM(HPRED.VALOREXCEDENTE) FROM HPRED, HPRE
      WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
      AND    HPRE.NOADMISION   = @NOADMISION
      AND    HPRED.IDTERCEROCA = @IDTERCERO
   END
   ELSE
   BEGIN
      SELECT @VLRCOPAGO = SUM(HPRED.VALORCOPAGO), @VLRPAGOCO = SUM(HPRED.VALORPCOMP),
             @VLRTOTAL  = SUM(HPRED.VALOREXCEDENTE) FROM HPRED, HPRE
      WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
      AND    HPRE.NOADMISION   = @NOADMISION
      AND    HPRED.IDTERCEROCA = @IDTERCERO
      AND    HPRED.N_FACTURA   = @N_FACTURA
   END

-- SE AVERIGUA SI TIENE DESCUENTO
   SELECT @DESCUENTO  = DESCUENTO,  @TIPODTO     = TIPODTO
   FROM   HADMDT 
   WHERE  NOADMISION = @NOADMISION 
   AND    IDTERCERO  = @IDTERCERO
   IF @DESCUENTO > 0
   BEGIN
      IF @TIPODTO = 'P'
         SELECT @VRDTO = ROUND(@VLRTOTAL * (@DESCUENTO/100),0)
      ELSE 
         SELECT @VRDTO = @DESCUENTO 
   END           
   ELSE
      SELECT @VRDTO = 0     
   
   IF @VLRCOPAGO IS NULL
      SELECT @VLRCOPAGO = 0
   IF @VLRPAGOCO IS NULL
      SELECT @VLRPAGOCO = 0
   IF @VLRTOTAL IS NULL
      SELECT @VLRTOTAL = 0
   IF @VRDTO IS NULL
      SELECT @VRDTO = 0
   /* SE CONTROLA LA EXISTENCIA DE FCJ PREVIA*/
   IF COALESCE(@N_FACTURA,'')=''
      SELECT @OK = COALESCE(COUNT(*),0) FROM FCJ WHERE NOADMISION = @NOADMISION AND CLASE_FAC = 'COBRO' AND IDENTIFICADOR = 'FACTURA QX' AND PROCEDENCIA='SALUD' AND ESTADO='P'
   ELSE
      SELECT @OK = COALESCE(COUNT(*),0) FROM FCJ WHERE NOADMISION = @NOADMISION AND CLASE_FAC = 'COBRO' AND IDENTIFICADOR = 'FACTURA QX' AND PROCEDENCIA='SALUD' AND ESTADO='P' AND N_FACTURA=COALESCE(@N_FACTURA,'')

   IF @OK>0
   BEGIN
      PRINT 'Ya Fue Generado y Esta en Caja'
      UPDATE HADM SET COPAGO=1 WHERE NOADMISION = @NOADMISION 
      RETURN
   END      

   /* SE CONTROLA LA EXISTENCIA DE TFCJ PREVIA*/
   SELECT @OK = COALESCE(COUNT(*),0) FROM TFCJ WHERE NOADMISION = @NOADMISION AND CLASE_FAC = 'COBRO' AND IDENTIFICADOR = 'FACTURA QX' AND PROCEDENCIA='SALUD'
   IF @OK > 0
   BEGIN
      DELETE TFCJDD
      FROM   TFCJDD INNER JOIN TFCJD ON TFCJDD.CNSFACJ = TFCJD.CNSFACJ
                                    AND TFCJDD.ITEM    = TFCJD.ITEM
                    INNER JOIN TFCJ  ON TFCJD.CNSFACJ  = TFCJ.CNSFACJ
      WHERE  TFCJ.NOADMISION = @NOADMISION              
      AND    CLASE_FAC = 'COBRO' 
      AND    IDENTIFICADOR = 'FACTURA QX'
      
      DELETE TFCJD
      FROM   TFCJD INNER JOIN TFCJ  ON TFCJD.CNSFACJ  = TFCJ.CNSFACJ
      WHERE  TFCJ.NOADMISION = @NOADMISION              
      AND    CLASE_FAC = 'COBRO' 
      AND    IDENTIFICADOR = 'FACTURA QX'
      
      DELETE TFCJ
      WHERE  TFCJ.NOADMISION = @NOADMISION              
      AND    CLASE_FAC = 'COBRO' 
      AND    IDENTIFICADOR = 'FACTURA QX'
      
   END
   
   SELECT @OK = COALESCE(COUNT(*),0) FROM HADM WHERE NOADMISION = @NOADMISION
   AND COPAGONOAUTORIZACION <> '' AND COPAGONOAUTORIZACION IS NOT NULL
   
   SELECT @RAZONSOCIAL = RAZONSOCIAL FROM TER WHERE IDTERCERO = @IDTERCERO
   
   SELECT @AUX = COUNT(*) FROM TER 
   WHERE IDTERCERO = @IDTERCERO 
   AND TER.ENVIODICAJA = 1
   PRINT '@OK=' +CAST(@OK AS VARCHAR(5))
   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@TFCJ', @NVOCONSEC OUTPUT  
   SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0) 
   SELECT @IDAFILIADO = AFI.IDAFILIADO FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO WHERE NOADMISION = @NOADMISION
   IF @OK > 0
   BEGIN     
      SELECT @COPAGOVALOR = COPAGOVALOR FROM HADM WHERE NOADMISION = @NOADMISION
      SELECT @RAZONSOCIAL = LEFT(LTRIM(RTRIM(AFI.PAPELLIDO))+' '+LTRIM(RTRIM(AFI.SAPELLIDO))
                                 +' '+LTRIM(RTRIM(AFI.PNOMBRE))+' '+LTRIM(RTRIM(AFI.SNOMBRE)),40)   
      FROM AFI WHERE IDAFILIADO = @IDAFILIADO
      
      INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
                       IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, PROCEDENCIA,
                       N_FACTURA, IDTERCERO, NOMBRECLIENTE,
                       CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, 
                       NROCOMPROBANTE, AREAPRESTACION, CCOSTO,
                       SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME)
      SELECT @NVOCONSEC, NULL,  'COBRO', @NOADMISION, NULL, @IDPLAN, 0, @COMPANIA,
         @IDAFILIADO,@TIPO_DOC, 0, GETDATE(), 'SALUD', @N_FACTURA, @IDTERCERO, @RAZONSOCIAL,  
         NULL, 'INTERNO', 0, 0, 0, 0, NULL, NULL, NULL, NULL, 'C', 'FACTURA QX',
         @USUARIO, @SYS_COMPUTERNAME
       
      SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJCOPA'
      
      INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, 
                        CANTIDAD, VALORTOTAL, IDSERVICIO,
                        TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
      SELECT NULL, @NVOCONSEC, 1,@DATO, NULL, @COPAGOVALOR, 1, @COPAGOVALOR,NULL, 0, 
                   'N', 0, 0
      UPDATE HADM SET COPAGO = 1 WHERE NOADMISION = @NOADMISION
	  IF DBO.FNK_VALORVARIABLE('IXCOUNTRY ') = 'PERU'
		BEGIN
		 SELECT @VRTOTAL = COALESCE(VR_TOTAL,0)
         FROM   FTR
         WHERE  N_FACTURA = @NVOCONSEC

		 UPDATE TFCJ SET VALORTOTAL = @VRTOTAL WHERE CNSFACJ = @NVOCONSEC
		END

   END
   ELSE     
   BEGIN
      IF @AUX = 1  -- ES PARTICULAR
      BEGIN
		 IF DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR')=@IDTERCERO
		 BEGIN
			SELECT @IDTERCERO=COALESCE(TER.IDTERCERO, AFI.IDAFILIADO), @RAZONSOCIAL=NOMBREAFI 
			FROM AFI INNER JOIN HADM ON HADM.IDAFILIADO=AFI.IDAFILIADO 
			LEFT JOIN TER ON TER.NIT=AFI.DOCIDAFILIADO
			WHERE HADM.NOADMISION=@NOADMISION
		 END
         INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
                       IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, PROCEDENCIA, 
                       N_FACTURA, IDTERCERO, NOMBRECLIENTE,
                       CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,
                       SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME, OBSERVACION)
         SELECT @NVOCONSEC, NULL,  'COBRO', @NOADMISION, NULL, @IDPLAN, 0, @COMPANIA,
         @IDAFILIADO,@TIPO_DOC, 0, GETDATE(), 'SALUD', @N_FACTURA, @IDTERCERO, LEFT(@RAZONSOCIAL,40),  
         NULL, 'INTERNO', 0, 0, 0, 0, NULL, NULL, NULL, NULL, 'C', 'FACTURA QX',
         @USUARIO, @SYS_COMPUTERNAME, 'ADMISION: '+@NOADMISION
         
         SELECT @OK = 1 
         
         SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJPART'
         INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, 
                           CANTIDAD, VALORTOTAL, IDSERVICIO,
                           TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
         SELECT NULL, @NVOCONSEC, @OK, @DATO, NULL, @VLRTOTAL - @VRDTO, 1, 
                      @VLRTOTAL - @VRDTO, NULL, 0, 'N', 0, 0
         SELECT @OK = @OK + 1  
         UPDATE HADM SET COPAGO = 1 WHERE NOADMISION = @NOADMISION
		 IF DBO.FNK_VALORVARIABLE('IXCOUNTRY ') = 'PERU'
		 BEGIN
			 SELECT @VRTOTAL = COALESCE(VR_TOTAL,0)
			 FROM   FTR
			 WHERE  N_FACTURA = @NVOCONSEC

			 UPDATE TFCJ SET VALORTOTAL = @VRTOTAL WHERE CNSFACJ = @NVOCONSEC
		 END

		

      END
      ELSE
      BEGIN
         IF @VLRCOPAGO = 0 AND @VLRPAGOCO = 0   
         BEGIN
            RETURN
         END   
         SELECT @IDTERCERO=COALESCE(TER.IDTERCERO, AFI.IDAFILIADO), @RAZONSOCIAL=NOMBREAFI 
		 FROM AFI INNER JOIN HADM ON HADM.IDAFILIADO=AFI.IDAFILIADO 
			LEFT JOIN TER ON TER.NIT=AFI.DOCIDAFILIADO
		 WHERE HADM.NOADMISION=@NOADMISION
			
         INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
                       IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, 
                       PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,
                       CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, 
                       NROCOMPROBANTE, AREAPRESTACION, CCOSTO,
                       SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME)
         SELECT @NVOCONSEC, NULL,  'COBRO', @NOADMISION, NULL, @IDPLAN, 0, @COMPANIA,
         @IDAFILIADO,@TIPO_DOC, 0, GETDATE(), 'SALUD', @N_FACTURA, @IDTERCERO, LEFT(@RAZONSOCIAL,40),  
           NULL, 'INTERNO', 0, 0, 0, 0, NULL, NULL, NULL, NULL, 'C', 'FACTURA QX',
         @USUARIO, @SYS_COMPUTERNAME 

		 IF DBO.FNK_VALORVARIABLE('IXCOUNTRY ') = 'PERU'
			BEGIN
			 SELECT @VRTOTAL = COALESCE(VR_TOTAL,0)
			 FROM   FTR
			 WHERE  N_FACTURA = @NVOCONSEC

			 UPDATE TFCJ SET VALORTOTAL = @VRTOTAL WHERE CNSFACJ = @NVOCONSEC
			END

			        
         SELECT @OK = 1 
         
         IF @VLRCOPAGO > 0 
         BEGIN
            SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJCOPA'
            INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, 
                              VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                              TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
            SELECT NULL, @NVOCONSEC, @OK,@DATO, NULL, @VLRCOPAGO, 1, @VLRCOPAGO, 
                   NULL, 0, 'N', 0, 0
            SELECT @OK = @OK + 1
            UPDATE HADM SET COPAGO = 1 WHERE NOADMISION = @NOADMISION  
         END
         IF @VLRPAGOCO > 0
         BEGIN
            SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJPACO'
            INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, 
                              VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                              TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
            SELECT NULL, @NVOCONSEC, @OK,@DATO, NULL, @VLRPAGOCO, 1, @VLRPAGOCO,
                         NULL, 0, 'N', 0, 0
            SELECT @OK = @OK + 1  
            UPDATE HADM SET COPAGO = 1 WHERE NOADMISION = @NOADMISION
         END       
      END       
   END
   
   SELECT @VLRTOTAL = SUM(VALORTOTAL) FROM TFCJD WHERE CNSFACJ = @NVOCONSEC
   
   UPDATE TFCJ SET VALORTOTAL = @VLRTOTAL WHERE CNSFACJ = @NVOCONSEC
  
   
END



