CREATE OR ALTER PROCEDURE DBO.SPQ_FTR_PERU @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			 ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				,@COMPANIA VARCHAR(2)			 ,@IDSEDE      VARCHAR(5)		
        ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
        ,@CONSECUTIVO VARCHAR(20)           ,@DPR VARCHAR(20)                ,@TIPOFAC VARCHAR(10)
        ,@FECHAFACT DATETIME                ,@IDTERCERO VARCHAR(20)          ,@N_FACTURA VARCHAR(20)
        ,@IDAUT VARCHAR(20)                 ,@PREFIJO VARCHAR(6)             ,@IDTERCEROCA VARCHAR(20)
        ,@IDPLAN VARCHAR(6)                 ,@GENERADO SMALLINT              ,@IDSERPAQ   VARCHAR(20)
        ,@VLRTOTALPAQ DECIMAL(14,2)         ,@CANTIPAQ SMALLINT              ,@PROCESO VARCHAR(20)
		,@IDMAD	INT							,@VLRPAQ DECIMAL(14,2)           ,@PAQUETE VARCHAR(20)
		,@NOADMISION VARCHAR(20)			,@IDSEDE2 VARCHAR(10)			 ,@RPDX	VARCHAR(20)
		,@ITEM INT							,@NOMBREEQUIPO VARCHAR(50)		 ,@NIT VARCHAR(40)
		,@VALOREXCEDENTE DECIMAL(16,2)		,@FECHAHPRE	DATETIME			 ,@IDCONCEPTORIPS VARCHAR(2)
		,@CCOSTO VARCHAR(20)				,@IDAREAH VARCHAR(20)			 ,@IDSERVICIO VARCHAR(20)
		,@VALORCOPAGO DECIMAL(16,4)			,@APOYODG_AMBITO VARCHAR(2)		 ,@NVOCONSEC   VARCHAR(20)
		,@IDAREA VARCHAR(20)				,@CNSHTX	VARCHAR(20)			 ,@CODCUPS	VARCHAR(20)
		,@IDKPAGE INT						,@ALTOCOSTO		VARCHAR(2)		 ,@FECHA_MAD DATE
		,@IDPLAN_MAD VARCHAR(6)				,@USUMARCA VARCHAR(20)			 ,@MARCAFAC BIT
		,@FECHAINI DATETIME					,@FECHAFIN DATETIME				 ,@ESCITCI BIT
		,@PROCESOFACTMAS INT				,@NUMCONCNSFACT INT = 0			 ,@NUMCONCNSFACT2 INT = 0 
		,@FECHAINIFIL DATE					,@FECHAFINFIL DATE				 ,@F_FACTURA DATETIME
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='FACTURAR_CITAUT'     
   BEGIN         
      SELECT @CONSECUTIVO=CONSECUTIVO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO'
      )
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      PRINT 'Valido sede'
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Sede: '+@IDSEDE+' No habilitada para emitir Facturas, Comuniquese con el Administrador del Sistema'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN

      END
	  IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'))
	  BEGIN
		INSERT INTO @TBLERRORES(ERROR)
		SELECT 'La atencion a facturar es Particular, por lo que no se puede facturar.'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
	  END
      IF NOT EXISTS(SELECT * FROM CIT WHERE COALESCE(FACTURADA,0)=1 AND COALESCE(N_FACTURA,'')='' AND COALESCE(VALORTOTAL,0)-COALESCE(VALORCOPAGO,0)>0 AND CONSECUTIVO=@CONSECUTIVO) 
      BEGIN
         BEGIN TRY           
            EXEC SPK_FACTURACE_PERU_CITAUT @CONSECUTIVO,@DPR,@COMPANIA,@IDSEDE, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Cita ya Facturada o con Valores en Cero(0), Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @N_FACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
      SELECT 'OK' OK,@N_FACTURA N_FACTURA
      RETURN 
   END
   IF @METODO='FACTURAR_CITPAQ'     
   BEGIN  
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
      SELECT @CONSECUTIVO=CONSECUTIVO, @IDSERPAQ=IDSERPAQ,@VLRTOTALPAQ=VLRTOTALPAQ,@CANTIPAQ=CANTIPAQ    
      FROM   OPENJSON (@DATOS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO',
      IDSERPAQ  VARCHAR(20)   '$.IDSERPAQ',
      VLRTOTALPAQ  VARCHAR(20)   '$.VLRTOTALPAQ',
      CANTIPAQ  VARCHAR(20)   '$.CANTIPAQ'
      )
      PRINT '@CONSECUTIVO='+@CONSECUTIVO
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      IF NOT EXISTS(SELECT * FROM CIT WHERE COALESCE(FACTURADA,0)=1 AND COALESCE(N_FACTURA,'')='') 
      BEGIN
         BEGIN TRY           
            EXEC SPK_FACTURACE_PERU_CITAUT_PAQ @CONSECUTIVO,@DPR,@COMPANIA,@IDSEDE, @USUARIO,@IDSERPAQ,@VLRTOTALPAQ,@CANTIPAQ,@FECHAFACT,@TIPOFAC, @IDTERCERO                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Cita ya Facturada o con Valores en Cero(0), Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @N_FACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
      SELECT 'OK' OK,@N_FACTURA N_FACTURA
      RETURN 
   END
   IF @METODO='NOTIFICA_BOLETAS'     
   OR @METODO='NOTIFICA_BOLETAS_DEBUG'     
   BEGIN 
      SELECT @PROCESO=PROCESO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      PROCESO VARCHAR(20) '$.PROCESO'
      )
     IF DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION')<>DB_NAME()
     BEGIN
         PRINT 'Modo Test No permite el envio de Documentos'
         SELECT 'OK' OK  
         RETURN
     END
     IF  EXISTS(SELECT *
         FROM FTR INNER JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA
         WHERE FTRE.NOTIFICADO=0
         AND FTR.TIPOFIN='N'
         AND COALESCE(MARCA,0)=1
         AND COALESCE(EQUIMARCA,'')<>''
         AND FTR.FECHA_PP IS NOT NULL
         AND DATEDIFF(MINUTE,FTR.FECHA_PP,DBO.FNK_GETDATE())>10)
      BEGIN
         PRINT 'Si encontre alguna marcada'
         UPDATE FTR SET EQUIMARCA=NULL,MARCA=0,FECHA_PP=NULL
         FROM FTR INNER JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA
         WHERE FTRE.NOTIFICADO=0
         AND FTR.TIPOFIN='N'
         AND COALESCE(MARCA,0)=1
         AND COALESCE(EQUIMARCA,'')<>''
         AND FTR.FECHA_PP IS NOT NULL
         AND DATEDIFF(MINUTE,FTR.FECHA_PP,DBO.FNK_GETDATE())>10
      END

      PRINT 'VOY AL UPDATE'
      UPDATE FTR SET EQUIMARCA=@USUARIO,MARCA=1,FECHA_PP=DBO.FNK_GETDATE()
      FROM FTR INNER JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA
                  INNER JOIN TER  ON FTR.IDTERCERO=TER.IDTERCERO
                  LEFT  JOIN AFI  ON FTR.IDAFILIADO=AFI.IDAFILIADO
         WHERE FTRE.NOTIFICADO=0
         AND FTR.TIPOFIN='N'
         AND COALESCE(MARCA,0)=0
         AND COALESCE(EQUIMARCA,'')=''

      SELECT 'OK' OK 
	  
     IF @PROCESO='FRONTEND'
     BEGIN
	     SELECT FTR.N_FACTURA,CONVERT(VARCHAR,F_FACTURA,103)F_FACTURA,FTR.VALORSERVICIOS,VIVA,VR_TOTAL,COALESCE(AFI.EMAIL,TER.EMAIL)CORREO,AFI.DOCIDAFILIADO,AFI.NOMBREAFI
         FROM FTR INNER JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA
                  INNER JOIN TER  ON FTR.IDTERCERO=TER.IDTERCERO
                  LEFT  JOIN AFI  ON FTR.IDAFILIADO=AFI.IDAFILIADO
         WHERE FTRE.NOTIFICADO=0
         AND FTR.TIPOFIN='N'
         AND COALESCE(MARCA,0)=1
         AND COALESCE(EQUIMARCA,'')=@USUARIO
     END
     ELSE
     BEGIN 
	     SELECT TOP 1 FTR.N_FACTURA,CONVERT(VARCHAR,F_FACTURA,103)F_FACTURA,FTR.VALORSERVICIOS,VIVA,VR_TOTAL,COALESCE(AFI.EMAIL,TER.EMAIL)CORREO,AFI.DOCIDAFILIADO,AFI.NOMBREAFI
         FROM FTR INNER JOIN FTRE ON FTR.N_FACTURA=FTRE.FTRN_FACTURA
                  INNER JOIN TER  ON FTR.IDTERCERO=TER.IDTERCERO
                  LEFT  JOIN AFI  ON FTR.IDAFILIADO=AFI.IDAFILIADO
         WHERE FTRE.NOTIFICADO=0
         AND FTR.TIPOFIN='N'
         AND COALESCE(MARCA,0)=1
         AND COALESCE(EQUIMARCA,'')=@USUARIO
       --AND 1=IIF(@METODO='NOTIFICA_BOLETAS_DEBUG', 1, 2)
     END


      RETURN
   END 
   IF @METODO='MARCA_ENVIO'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA' 
      )
      IF EXISTS(SELECT * FROM FTRE WHERE FTRN_FACTURA=@N_FACTURA)
      BEGIN
         UPDATE FTRE SET NOTIFICADO=1,FECHA_NOTIFICADO=DBO.FNK_GETDATE() WHERE FTRN_FACTURA=@N_FACTURA
         UPDATE FTR SET MARCA=0,EQUIMARCA=NULL,FECHA_PP=NULL   WHERE N_FACTURA=@N_FACTURA
      END
      SELECT 'OK'OK
      RETURN
   END  
   IF @METODO='SOPORTES_FTREPE'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
       N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )

      DECLARE @PROCEDENCIA VARCHAR(20)
      DECLARE @NOREFERENCIA VARCHAR(20)
      DECLARE @IDAFILIADO VARCHAR(20)
      DECLARE @CONSECUTIVOHCA VARCHAR(20)
      DECLARE @OBSERVACION1 VARCHAR(20)
      DECLARE @RUC VARCHAR(20)
      
      SELECT @PROCEDENCIA=PROCEDENCIA,@NOREFERENCIA=NOREFERENCIA,@IDAFILIADO=IDAFILIADO,@OBSERVACION1=LTRIM(RTRIM(COALESCE(OBSERVACION1,'')))
      FROM FTR WHERE N_FACTURA=@N_FACTURA
      PRINT @PROCEDENCIA

      IF @PROCEDENCIA='CI'
      BEGIN
         PRINT '@NOREFERENCIA='+COALESCE(@NOREFERENCIA,'SI REFERENCIA')+' @IDAFILIADO='+COALESCE(@IDAFILIADO,'SIN AFILIADO')
         IF @OBSERVACION1='CITAUT'
         BEGIN
            SELECT @CONSECUTIVOHCA=CONSECUTIVO FROM HCA WHERE CONSECUTIVOCIT=@NOREFERENCIA AND IDAFILIADO=@IDAFILIADO
         END
         ELSE
         BEGIN
            SELECT @CONSECUTIVOHCA=CONSECUTIVO FROM HCA WHERE CONSECUTIVOCIT=@NOREFERENCIA AND IDAFILIADO=@IDAFILIADO
         END
      END
      IF @PROCEDENCIA='CE'
      BEGIN
         SELECT @CONSECUTIVOHCA=CONSECUTIVOHCA FROM AUT WHERE IDAUT=@NOREFERENCIA
      END
      IF @PROCEDENCIA='SALUD'
      BEGIN
         IF EXISTS(SELECT * FROM CIT INNER JOIN HCA ON CIT.CONSECUTIVO=HCA.CONSECUTIVOCIT WHERE CIT.NOADMISION=@NOREFERENCIA)
         BEGIN
            SELECT @CONSECUTIVOHCA=HCA.CONSECUTIVO 
            FROM CIT INNER JOIN HCA ON CIT.CONSECUTIVO=HCA.CONSECUTIVOCIT 
            WHERE CIT.NOADMISION=@NOREFERENCIA 
            AND HCA.CLASE='HC'
         END
         ELSE
         BEGIN
            SELECT @CONSECUTIVOHCA=HCA.CONSECUTIVO 
            FROM HADM INNER JOIN HCA ON HADM.NOADMISION=HCA.NOADMISION 
            WHERE HADM.NOADMISION=@NOREFERENCIA 
            AND HCA.CLASE='HC'            
         END
      END

      SELECT @RUC=NIT
      FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

      SELECT 'OK'OK
      SELECT @CONSECUTIVOHCA CONSECUTIVO,@IDAFILIADO IDAFILIADO,@RUC RUC 
      RETURN
   
   END  
   IF @METODO='LISTOS_FACTURA'     
   BEGIN        

      SELECT @CONSECUTIVO = CONSECUTIVO    
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO'
      )
      DECLARE LISAUT_CURSOR CURSOR FOR 
      SELECT IDAUT,PREFIJO,IDTERCEROCA,IDPLAN,COALESCE(GENERADO,0)  FROM AUT 
      WHERE CONSECUTIVOCIT=CASE WHEN COALESCE(@CONSECUTIVO,'')<> '' THEN @CONSECUTIVO ELSE CONSECUTIVOCIT END
      AND COALESCE(FACTURADA,0)=0
      AND COALESCE(LISTOFACT,'PEND')='PEND'
      ORDER BY IDAUT
      OPEN LISAUT_CURSOR    
      FETCH NEXT FROM LISAUT_CURSOR    
      INTO @IDAUT,@PREFIJO,@IDTERCEROCA,@IDPLAN,@GENERADO
      WHILE @@FETCH_STATUS = 0    
      BEGIN 
         IF @PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS')
         BEGIN
            -- MEDICAMENTOS
            PRINT 'VALIDO SI EL SISTEMA ENTREGA MEDICAMENTOS '
            IF NOT EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCEROCA AND IDPLAN=@IDPLAN AND COALESCE(MEFARMACIA,0)=1)
            BEGIN
               PRINT 'CONVENIO NO ENTREGA MEDICAMENTOS'
               UPDATE AUT SET LISTOFACT='NOFACT' WHERE IDAUT=@IDAUT
            END
            ELSE
            BEGIN
               IF NOT EXISTS(SELECT * FROM IZSOL INNER JOIN IMOV ON IZSOL.CNSIZSOL=IMOV.NODOCUMENTO AND IMOV.PROCEDENCIA='CM_SOL'
                              WHERE IZSOL.NOADMISION=@IDAUT AND IZSOL.CLASE='CE'
                              AND IZSOL.ESTADO=1
                              AND IMOV.ESTADO=1)
               BEGIN
                  UPDATE AUT SET LISTOFACT='PEND' WHERE IDAUT=@IDAUT
               END
               ELSE
               BEGIN
                  UPDATE AUT SET LISTOFACT='OK' WHERE IDAUT=@IDAUT
                  UPDATE AUTD SET VALOREXCEDENTE=(VALOR*CANTIDAD)-COALESCE(VALORCOPAGO,0)
                  WHERE IDAUT=@IDAUT
                  AND COALESCE(AUTD.NOCOBRABLE,0)=0
                  AND COALESCE(AUTD.GENERADO,0)=1
                  AND COALESCE(AUTD.FACTURADA,0)=0
               END
            END
         END
         IF @PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO') OR @PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOAPOYODX')
         BEGIN
            PRINT 'AYUDAS DIAGNOSTICAS'
            IF COALESCE(@GENERADO,0)=0
            BEGIN
               FETCH NEXT FROM LISAUT_CURSOR    
               INTO @IDAUT,@PREFIJO,@IDTERCEROCA,@IDPLAN,@GENERADO
               CONTINUE
            END
            IF EXISTS(SELECT * FROM LING INNER JOIN LORD ON LING.NOINGRESO=LORD.NOINGRESO
                                          INNER JOIN AUTD ON LING.NOPRESTACION=AUTD.IDAUT AND AUTD.IDSERVICIO=LORD.IDSERVICIO
                        WHERE COALESCE(AUTD.NOCOBRABLE,0)=0
                        AND LING.NOPRESTACION=@IDAUT
                        AND LORD.ESTADO='I')
            BEGIN
               UPDATE AUT SET LISTOFACT='PEND' WHERE IDAUT=@IDAUT
            END
            ELSE
            BEGIN
               UPDATE AUT SET LISTOFACT='OK' WHERE IDAUT=@IDAUT
               UPDATE AUTD SET VALOREXCEDENTE=(VALOR*CANTIDAD)-COALESCE(VALORCOPAGO,0)
               WHERE IDAUT=@IDAUT
               AND COALESCE(AUTD.NOCOBRABLE,0)=0
               AND COALESCE(AUTD.GENERADO,0)=1
               AND COALESCE(AUTD.FACTURADA,0)=0
            END
         END
         IF @PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOCONSULTA')
         BEGIN
            UPDATE AUT SET LISTOFACT='NOFACT' WHERE IDAUT=@IDAUT 
         END
         FETCH NEXT FROM LISAUT_CURSOR    
         INTO @IDAUT,@PREFIJO,@IDTERCEROCA,@IDPLAN,@GENERADO
      END
      CLOSE LISAUT_CURSOR
      DEALLOCATE LISAUT_CURSOR

      SELECT 'OK'OK
      RETURN
   END  
   IF @METODO='SOPORTES_HCATD'     
   BEGIN         
      SELECT @CONSECUTIVO=CONSECUTIVO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
            CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO'
      )
      
         SELECT 'OK'OK, ( SELECT DISTINCT HCATD.CODOM
					,                                HCCOM.DESCRIPCION
					FROM HCA INNER JOIN HCATD ON HCA.CONSECUTIVO=HCATD.CONSECUTIVO
					INNER JOIN HCCOM ON HCCOM.CODOM = HCATD.CODOM
					WHERE HCATD.CONSECUTIVO =@CONSECUTIVO FOR JSON PATH) AS HCATD

      RETURN                 
   END  
   IF @METODO='SOPORTES_APDX_DOCS'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
            N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      
      SELECT 'OK'OK, DOCS.DocNombre,DocExtension,DOCS.DocFS AS ARCHIVO,'DOCS'PROCE
      FROM AUTD INNER JOIN LING ON AUTD.IDAUT=LING.NOPRESTACION AND LING.TIPOINGRESO='C'
                INNER JOIN LORD ON LING.NOINGRESO=LORD.NOINGRESO AND AUTD.IDSERVICIO=LORD.IDSERVICIO
                INNER JOIN DOCXTPO ON LORD.NORDEN=DOCXTPO.NODOCUMENTO AND TIPO='LORD'
                INNER JOIN DOCS ON DOCXTPO.DOCUMENTOID=DOCS.DocumentoID
      WHERE   @N_FACTURA IN(AUTD.N_FACTURA,AUTD.NFACTURA)
      UNION ALL 
      SELECT 'OK'OK,'Resultados_labo_interfax','pdf',LABO_DOCS.DOCBASE64 AS ARCHIVO,'INTER'PROCD
      FROM AUT INNER JOIN LABO_DOCS ON AUT.NOAUT=LABO_DOCS.NUM_ORDEN
      WHERE EXISTS(SELECT * FROM AUTD WHERE AUTD.IDAUT=AUT.NOAUT AND    @N_FACTURA IN(AUTD.N_FACTURA,AUTD.NFACTURA))
      RETURN                 
   END
   IF @METODO='FACTURAR_MAD'     
   BEGIN         
      SELECT @IDMAD=IDMAD        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         IDMAD  INT   '$.CONSECUTIVO'
      )
		
		IF EXISTS(SELECT 1 FROM CIT WHERE IDMAD = @IDMAD)
		BEGIN
			PRINT '@IDMAD >'  + COALESCE(STR(@IDMAD),' SIN @IDMAD')
			SELECT @IDTERCERO = IDTERCERO,  @IDPLAN_MAD = MAD.IDPLAN, @PAQUETE = CIT.IDSERVICIO, @FECHA_MAD = MAD.FECHA
			FROM    MAD
			INNER JOIN CIT ON CIT.CONSECUTIVO=MAD.CONSECUTIVOCIT
			WHERE ID = @IDMAD 

			SELECT @VLRPAQ = VALOR 
			FROM SERTOT 
			WHERE IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN_MAD AND IDSERVICIO = @PAQUETE
			AND CONVERT(DATE, @FECHA_MAD) BETWEEN SERTOT.FECHAINI AND SERTOT.FECHAFIN
		END
		ELSE
		BEGIN
			PRINT 'ES CITA CANCELADA' 
			PRINT '@IDMAD >'  + COALESCE(STR(@IDMAD),' SIN @IDMAD')
			SELECT @IDTERCERO = IDTERCERO,  @IDPLAN_MAD = MAD.IDPLAN, @PAQUETE = CITCI.IDSERVICIO_PENA, @FECHA_MAD = MAD.FECHA
			FROM    MAD
			INNER JOIN CITCI ON CITCI.IDMAD=MAD.ID
			WHERE ID = @IDMAD 

			PRINT '@IDTERCERO >'  + COALESCE(@IDTERCERO,' SIN @IDTERCERO')
			PRINT '@PAQUETE >'  + COALESCE(@PAQUETE,' SIN @PAQUETE')
			PRINT '@IDPLAN_MAD >'  + COALESCE(@IDPLAN_MAD,' SIN @IDPLAN_MAD')
			PRINT '@FECHA_MAD >'  + COALESCE(CONVERT(VARCHAR, @FECHA_MAD),' SIN @FECHA_MAD')

			SELECT @VLRPAQ = VALOR 
			FROM SERTOT 
			WHERE IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN_MAD AND IDSERVICIO = @PAQUETE
			AND CONVERT(DATE, @FECHA_MAD) BETWEEN SERTOT.FECHAINI AND SERTOT.FECHAFIN
		END


		PRINT '@PAQUETE >'  + COALESCE(@PAQUETE,' SIN @PAQUETE')
		PRINT '@VLRPAQ >'  + COALESCE(STR(@VLRPAQ),' SIN @VLRPAQ')
      IF NOT EXISTS(SELECT * FROM SER WHERE IDSERVICIO=@PAQUETE)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'El paquete asociado no existe en el Maestro de Servicios, Verique e intente de nuevo'
      END
      IF COALESCE(@VLRPAQ,0)<=0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Valor del Paquete no Puede ser menor o igual a cero(0)'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      PRINT 'Valido sede'
	  PRINT '@USUARIO >'  + COALESCE(@USUARIO,' SIN @USUARIO')
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 )
      BEGIN
		PRINT 'Sede no habilitada'
		PRINT '@IDSEDE >'  + COALESCE(@IDSEDE,' SIN @IDSEDE')
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Sede: '+@IDSEDE+' No habilitada para emitir Facturas, Comuniquese con el Administrador del Sistema'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN

      END
      BEGIN TRY 
			PRINT 'VOY A SPK_FACTURAMAD_PERU '
           EXEC SPK_FACTURAMAD_PERU @IDMAD,@DPR,@COMPANIA,@IDSEDE, @USUARIO,@FECHAFACT,@TIPOFAC, @IDTERCERO               
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,N_FACTURA  FROM MAD WHERE ID=@IDMAD
      RETURN 
   END  
   IF @METODO='QUITAR_ERROR_API'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      IF EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA AND FACTEP='104A')
      BEGIN
         UPDATE  FTR SET FACTEP=NULL WHERE N_FACTURA=@N_FACTURA AND FACTEP='104A'
         SELECT 'OK'OK 
         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO'OK,'No se fue encontrado el error, Verifique  e intente de nuevo'
         RETURN
      END
   END
	IF @METODO='FACTURAR_PHD'
	BEGIN
		SELECT @NOADMISION  = NOADMISION
				, @CNSHTX		= CNSHTX
				, @IDKPAGE		= IDKPAGE
				--, @IDAFILIADO	= IDAFILIADO
		FROM OPENJSON(@PARAMETROS)
		WITH(NOADMISION VARCHAR(16) '$.CONSECUTIVO'
			, CNSHTX		VARCHAR(16) '$.CNSHTX'
			, IDKPAGE	INT			'$.IDKPAGE'
			--, IDAFILIADO VARCHAR(20) '$.IDAFILIADO'
		)

		--SELECT @CNSHTX CNSHTX, @NOADMISION NOADMISION, @IDAFILIADO IDAFILIADO,@IDKPAGE IDKPAGE

		--SELECT COPAGONOAUTORIZACION, COPAGOVALOR,* FROM HADM WHERE NOADMISION = @NOADMISION
		SELECT @IDPLAN = HADM.IDPLAN, 
				@IDSEDE = HADM.IDSEDE,
				@CCOSTO = CEN.CCOSTO, @IDAREA=CEN.IDAREA,
				@ALTOCOSTO = COALESCE(GALTOCOSTO_QX,'No'),
				@IDTERCERO = HADM.IDTERCERO
		FROM HADM 
		INNER JOIN PLN ON PLN.IDPLAN = HADM.IDPLAN
		INNER JOIN CEN ON CEN.CCOSTO = PLN.CCOSTO
		WHERE NOADMISION = @NOADMISION

		SELECT @IDAREAH   = IDAREAH  FROM AFU WHERE IDAREA  = @IDAREA
		SELECT @NVOCONSEC= NOPRESTACION, @IDSERVICIO = IDSERVICIO FROM HTX WHERE CNSHTX = @CNSHTX
		SELECT @CODCUPS = @IDSERVICIO
		SELECT @IDCONCEPTORIPS = CODIGORIPS FROM SER WHERE IDSERVICIO = @IDSERVICIO
		--SELECT @IDPLAN, @IDAFILIADO, @IDKPAGE, @NOADMISION, @IDSERVICIO, @SEDE, @CCOSTO, @IDAREA, @IDAREAH, @ALTOCOSTO, @USUARIO USUARIO, @IDSERVICIO IDSERVICIO, @IDTERCERO IDTERCERO
		
		BEGIN TRY 

		UPDATE HPRE SET IDAREAH = @IDAREAH WHERE NOPRESTACION = @NVOCONSEC

		--SELECT NOADMISION, FECHA, IDPLAN, IDAREA, IDSEDE, ALTOCOSTO, USUARIO, PREFIJO, CCOSTO, IDAREAH, IDTERCEROCA, COBRARA, PROCEDENCIA
		--FROM HPRE 
		--WHERE NOPRESTACION = @NVOCONSEC

		SELECT @FECHAHPRE	= dbo.FNK_FECHA_SIN_MLS(GETDATE())
		SELECT @PREFIJO = PREFIJO, @APOYODG_AMBITO = AMBITO FROM SER WHERE IDSERVICIO = @IDSERVICIO
		
		--SELECT @VALOREXCEDENTE VALOREXCEDENTE, @FECHAHPRE FECHAHPRE, @APOYODG_AMBITO APOYODG_AMBITO, @CODCUPS CODCUPS, @IDCONCEPTORIPS IDCONCEPTORIPS

		SELECT @VALOREXCEDENTE = VLRSERVICIO FROM SERTOT
		WHERE  IDTERCERO  = @IDTERCERO 
		AND    IDPLAN     = @IDPLAN
		AND    IDSERVICIO = @IDSERVICIO
		AND    @FECHAHPRE >= FECHAINIFD
		AND    @FECHAHPRE <= FECHAFINFD
		AND    @FECHAHPRE >= FECHAINI
		AND    @FECHAHPRE <= FECHAFIN

		SELECT @VALORCOPAGO = VALOR FROM KPAGE WHERE IDKPAGE = @IDKPAGE
		SET @VALORCOPAGO = @VALORCOPAGO / (1.0+(COALESCE((SELECT VALOR FROM FIMPDV WHERE GETDATE() BETWEEN FECHAINI AND FECHAFIN AND IDIMPUESTO IN (SELECT DATO FROM USVGS WHERE IDVARIABLE='IDIMP_IVA')),18.0)/100))
		
		--SELECT @VALOREXCEDENTE VALOREXCEDENTE, @VALORCOPAGO VALORCOPAGO

		UPDATE  HPRED --SE ACTUALIZAN CAMPOS PORQUE VIENEN VACÍOS
		SET		 VALOR		    = @VALOREXCEDENTE
				,VALORCOPAGO    = @VALORCOPAGO
				,VALOREXCEDENTE = @VALOREXCEDENTE - @VALORCOPAGO
				,IDAREAH        = @IDAREAH
				,APOYODG_AMBITO = @APOYODG_AMBITO
				,ENCARGOS		= 0
				,MARCA			= 1
				,USUARIOMARCA   = @USUARIO
		WHERE NOPRESTACION = @NVOCONSEC AND IDSERVICIO = @IDSERVICIO

		--SELECT NOPRESTACION,IDSERVICIO,CANTIDAD,VALOR, VALORCOPAGO, VALOREXCEDENTE, VALORTOTALCOSTO,IDPLAN
		--	       ,IDCONCEPTORIPS, USUARIO, FECHA, IDAREAH, IDAREA, IDTERCEROCA, CCOSTO, CODCUPS
		--		   ,APOYODG_AMBITO, ENCARGOS, FECHASOL
		--FROM HPRED WHERE NOPRESTACION = @NVOCONSEC AND IDSERVICIO = @IDSERVICIO

		EXEC SPK_GENCONSECUTIVO '01',@IDSEDE,'@RPDX', @RPDX OUTPUT  
		SELECT @RPDX = @IDSEDE + REPLACE(SPACE(8 - LEN(@RPDX))+LTRIM(RTRIM(@RPDX)),SPACE(1),0)
		PRINT 'GENERO @RPDX: '+@RPDX	
		--SELECT @RPDX	

		PRINT 'EXEC SPK_AFACTURAR > ' + @NOADMISION + ', ' + @RPDX + ', ' + @USUARIO
		EXEC SPK_AFACTURAR @NOADMISION, @RPDX, @USUARIO, @MARCA_HPRED='NO'

		SELECT @ITEM = ITEM FROM RPDX WHERE CNS = @RPDX
		SELECT @NIT = NIT FROM SED WHERE IDSEDE ='01'
		SELECT @IDSEDE2 = (SELECT  SED.IDSEDE FROM USUSU 
				INNER JOIN UBEQ ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName
				INNER JOIN SED ON UBEQ.IDSEDE =  SED.IDSEDE
				WHERE USUSU.USUARIO = @USUARIO)
		SELECT @NOMBREEQUIPO = (SELECT  USUSU.SYS_ComputerName FROM USUSU WHERE USUSU.USUARIO = @USUARIO)

		PRINT 'SPK_FACTURAPHD_PERU > '+@NOADMISION+', '+@NIT+', 01, '+@IDSEDE+', '+@USUARIO+', '+@NOMBREEQUIPO+', '+@RPDX+ ', '+ CONVERT(VARCHAR,@ITEM)
		EXEC SPK_FACTURAPHD_PERU @NOADMISION, @NIT, '01', @IDSEDE2, @USUARIO, @NOMBREEQUIPO, @RPDX, @ITEM

		END TRY
		
		BEGIN CATCH  
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
			RETURN
			END 
		END CATCH	

		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,N_FACTURA FROM HADM WHERE NOADMISION=@NOADMISION
		RETURN
	END
	IF @METODO='ENVIAR_FACTURA_SAP'
	BEGIN 
		BEGIN TRY
			SELECT @N_FACTURA=N_FACTURA
			FROM   OPENJSON (@PARAMETROS)
			WITH   (
					N_FACTURA VARCHAR(20)  '$.N_FACTURA'
					)

			PRINT '@N_FACTURA > '+COALESCE(@N_FACTURA,'NO TENGO FACTURA')
			IF COALESCE(@N_FACTURA,'')='' OR NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA)
			BEGIN
				SELECT 'KO' OK, 'No existe el Documento En Facturacion' ERROR
				RETURN
			END
			IF EXISTS(SELECT 1 FROM FTR WHERE N_FACTURA=@N_FACTURA AND (COALESCE(VR_TOTAL,0)<=0 OR ESTADO<>'P'))
			BEGIN
				SELECT 'KO' OK, 'Factura Sin Valor o Anulada, No se Puede Enviar' ERROR
				RETURN
			END
			IF NOT EXISTS(SELECT 1 FROM FTRD WHERE N_FACTURA=@N_FACTURA )
			BEGIN
				SELECT 'KO' OK, 'Factura Sin Detalles, No se Puede Enviar' ERROR
				RETURN
			END
		
			IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
			BEGIN	
				PRINT 'INGRESO A ENVIO DE PROOVEDORES'
				IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='INTER_SAP'
				BEGIN
					EXEC SPK_JSON_FTR_PERU_INTERFAX @N_FACTURA
				END        
			END
		END TRY

		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH

		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' OK
		RETURN
	END
	IF @METODO='MARCAFACT_MAD'
	BEGIN 
		SELECT @DATOS=DATOS
		FROM   OPENJSON (@PARAMETROS)
		WITH (
			DATOS NVARCHAR(MAX) AS JSON,
			CNSFACT VARCHAR(20)         '$.CNSFACT'
		) 

		SELECT @IDMAD=ID,@MARCAFAC=MARCAFAC,@USUMARCA=USUMARCA
		FROM   OPENJSON (@DATOS)
		WITH   (
			ID INT						'$.ID',
			MARCAFAC BIT                '$.MARCAFAC',
			USUMARCA VARCHAR(20)        '$.USUMARCA'
			)

		PRINT 'MAD ='+STR(@IDMAD)
		PRINT '@MARCAFAC='+STR(@MARCAFAC)
		
		BEGIN TRY		
			PRINT 'MARCANDO MAD'
			UPDATE MAD SET MARCAFAC=CASE WHEN @MARCAFAC=0 THEN 1 ELSE 0 END, USUARIO_MARCAFAC=CASE WHEN @MARCAFAC=0 THEN @USUARIO ELSE NULL END
			FROM MAD 
			WHERE MAD.ID=@IDMAD AND COALESCE(MAD.FACTURADA,0)=0
		END TRY 
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
         
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK
	END
	IF @METODO='MARCAFACT_PHD'
	BEGIN 
		SELECT @DATOS=DATOS
		FROM   OPENJSON (@PARAMETROS)
		WITH (
			DATOS NVARCHAR(MAX) AS JSON,
			CNSFACT VARCHAR(20)         '$.CNSFACT'
		) 

		SELECT @NOADMISION=NOADMISION,@MARCAFAC=MARCAFAC,@USUMARCA=USUMARCA
		FROM   OPENJSON (@DATOS)
		WITH   (
			NOADMISION VARCHAR(20)						'$.NOADMISION',
			MARCAFAC SMALLINT                '$.MARCAFAC',
			USUMARCA VARCHAR(20)        '$.USUMARCA'
			)

		PRINT '@NOADMISION ='+STR(@NOADMISION)
		PRINT '@MARCAFAC='+STR(@MARCAFAC)
		
		BEGIN TRY		
			PRINT 'MARCANDO PHD'
			UPDATE HADM SET MARCA=CASE WHEN @MARCAFAC=0 THEN 1 ELSE 0 END, USUARIO_MARCAFAC=CASE WHEN @MARCAFAC=0 THEN @USUARIO ELSE NULL END
			WHERE HADM.NOADMISION=@NOADMISION AND COALESCE(HADM.FACTURADA,0)=0
		END TRY 
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
         
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK
	END
	IF @METODO='MARCATODOMASI'
	BEGIN 
		DECLARE @ACCION SMALLINT
		SELECT @DATOS=DATOS,@ACCION=ACCION,@ESCITCI=ESCITCI
		FROM   OPENJSON (@PARAMETROS)
		WITH (
			DATOS NVARCHAR(MAX) AS JSON,
			ACCION SMALLINT        '$.ACCION',
			ESCITCI BIT        '$.CITCI'
		) 

		SELECT @FECHAINI=F_INIMAS,@FECHAFIN=DATEADD(DAY,1,F_FINMAS),@IDTERCERO=IDTERMAS,
		@IDPLAN=IDPLANMAS,@IDSERVICIO=IDSERVICIOMAS,@PROCEDENCIA=PROCE
		FROM   OPENJSON (@DATOS)
		WITH   (
			F_INIMAS DATE          '$.F_INIMAS',
			F_FINMAS DATE          '$.F_FINMAS',
			IDTERMAS VARCHAR(20)   '$.IDTERMAS',
			IDPLANMAS VARCHAR(20)  '$.IDPLANMAS',
			IDSERVICIOMAS VARCHAR(20)   '$.IDSERVICIOMAS',
			PROCE VARCHAR(20)      '$.PROCE'
		)

		PRINT '@FECHAINI >'  + COALESCE(CONVERT(VARCHAR,@FECHAINI, 112),' SIN @FECHAINI')
		PRINT '@FECHAFIN >'  + COALESCE(CONVERT(VARCHAR, @FECHAFIN, 112),' SIN @FECHAFIN')
		PRINT '@ESCITCI >'  + COALESCE(STR(@ESCITCI),' SIN @ESCITCI')
		PRINT '@IDTERCERO >'  + COALESCE(@IDTERCERO,' SIN @IDTERCERO')
		PRINT '@IDPLAN >'  + COALESCE(@IDPLAN,' SIN @IDPLAN')
		PRINT '@IDSERVICIO >'  + COALESCE(@IDSERVICIO,' SIN @IDSERVICIO')

		BEGIN TRY
			IF @PROCEDENCIA='MAD'
			BEGIN

				IF @ESCITCI=0 AND @ACCION=1
				BEGIN 
					IF(SELECT COUNT(*) FROM MAD
					WHERE ID IN (SELECT IDMAD FROM CIT WHERE IDSERVICIO=@IDSERVICIO AND CIT.IDMAD=MAD.ID)
						AND	  COALESCE(FACTURADA,0) = 0
						AND   CONVERT(DATE,FECHA)>=@FECHAINI AND   CONVERT(DATE,FECHA)<@FECHAFIN
						AND   IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN
						AND   COALESCE(FACTURABLE,0) = 1
						AND   EXISTS (
								SELECT 1
								FROM CIT
								WHERE CIT.CONSECUTIVO = MAD.CONSECUTIVOCIT
								AND CIT.IDAFILIADO IS NOT NULL
								AND COALESCE(CIT.CUMPLIDA, 0) = 1
								)
					)<= 0
					BEGIN

					SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
						RETURN
					END
				END

				IF @ESCITCI=1 AND @ACCION=1
				BEGIN 
					IF(SELECT COUNT(*) FROM MAD
					WHERE ID IN (SELECT IDMAD FROM CITCI WHERE IDSERVICIO_PENA=@IDSERVICIO AND CITCI.IDMAD=MAD.ID)
						AND	  COALESCE(FACTURADA,0) = 0
						AND   CONVERT(DATE,FECHA)>=@FECHAINI AND   CONVERT(DATE,FECHA)<@FECHAFIN
						AND   IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN
						AND   COALESCE(FACTURABLE,0) = 1
						AND	  EXISTS (
								SELECT 1
								FROM CITCI
								WHERE CITCI.IDMAD = MAD.ID
								AND COALESCE(IDSERVICIO_PENA, '') <> ''
								)
					)<= 0
					BEGIN

					SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
						RETURN
					END
				END
		
					IF @ESCITCI=0
					BEGIN 
						PRINT 'MARCANDO MAD' 
						UPDATE MAD SET MARCAFAC=CASE WHEN @ACCION=1 THEN 1 ELSE 0 END,
						USUARIO_MARCAFAC=CASE WHEN @ACCION=1 THEN @USUARIO ELSE NULL END
						WHERE ID IN (SELECT IDMAD FROM CIT WHERE IDSERVICIO=@IDSERVICIO AND CIT.IDMAD=MAD.ID)
						AND	  COALESCE(FACTURADA,0) = 0
						AND   CONVERT(DATE,FECHA)>=@FECHAINI AND   CONVERT(DATE,FECHA)<@FECHAFIN
						AND   IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN
						AND   COALESCE(FACTURABLE,0) = 1
						AND   EXISTS (
								SELECT 1
								FROM CIT
								WHERE CIT.CONSECUTIVO = MAD.CONSECUTIVOCIT
								AND CIT.IDAFILIADO IS NOT NULL
								AND COALESCE(CIT.CUMPLIDA, 0) = 1
								)
					END
					ELSE
					BEGIN
						PRINT 'MARCANDO MAD DE CITAS CANCELADA' 
						UPDATE MAD SET MARCAFAC=CASE WHEN @ACCION=1 THEN 1 ELSE 0 END,
						USUARIO_MARCAFAC=CASE WHEN @ACCION=1 THEN @USUARIO ELSE NULL END
						WHERE ID IN (SELECT IDMAD FROM CITCI WHERE IDSERVICIO_PENA=@IDSERVICIO AND CITCI.IDMAD=MAD.ID)
						AND	  COALESCE(FACTURADA,0) = 0
						AND   CONVERT(DATE,FECHA)>=@FECHAINI AND   CONVERT(DATE,FECHA)<@FECHAFIN
						AND   IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN
						AND   COALESCE(FACTURABLE,0) = 1
						AND	  EXISTS (
								SELECT 1
								FROM CITCI
								WHERE CITCI.IDMAD = MAD.ID
								AND COALESCE(IDSERVICIO_PENA, '') <> ''
								)
					END
			END
			
			IF @PROCEDENCIA='PHD'
			BEGIN
				IF @ACCION=1
				BEGIN 
					IF(SELECT COUNT(*) FROM HADM
					WHERE COALESCE(FACTURADA,0) = 0
						AND   CONVERT(DATE,FECHA)>=@FECHAINI AND   CONVERT(DATE,FECHA)<@FECHAFIN
						AND   IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN
						AND   COALESCE(FACTURABLE,0) = 1
						AND	EXISTS(SELECT * FROM HPRE WHERE HPRE.NOADMISION=HADM.NOADMISION)
					)<= 0
					BEGIN

					SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
						RETURN
					END
				END
		
				PRINT 'MARCANDO HADM DE PHD' 
				UPDATE HADM SET MARCA=CASE WHEN @ACCION=1 THEN 1 ELSE 0 END,
				USUARIO_MARCAFAC=CASE WHEN @ACCION=1 THEN @USUARIO ELSE NULL END
				WHERE COALESCE(FACTURADA,0) = 0
				AND   CONVERT(DATE,FECHA)>=@FECHAINI AND   CONVERT(DATE,FECHA)<@FECHAFIN
				AND   IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN
				AND   COALESCE(FACTURABLE,0) = 1
				AND	EXISTS(SELECT * FROM HPRE WHERE HPRE.NOADMISION=HADM.NOADMISION)
			END
		END TRY 
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(1) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' OK
		RETURN
	END
	IF @METODO='CONTEOFTRMARCADAS'
	BEGIN
		SELECT @PROCESOFACTMAS = JSON_VALUE(@PARAMETROS,'$.PROCESO')
		,@IDTERCERO  = JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
		,@IDPLAN     = JSON_VALUE(@PARAMETROS,'$.IDPLAN')		
		,@IDSERVICIO =  JSON_VALUE(@PARAMETROS,'$.IDSERVICIOMAS')
		,@FECHAINIFIL   = JSON_VALUE(@PARAMETROS,'$.FINI')     
		,@FECHAFINFIL   = JSON_VALUE(@PARAMETROS,'$.FFIN')     
		,@PROCEDENCIA= JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')

		PRINT 'PROCESOFACTMAS='+CONVERT(VARCHAR,@PROCESOFACTMAS)
		PRINT '@USUARIO >'  + COALESCE(@USUARIO,' SIN @USUARIO')
		PRINT '@FECHAINI >'  + COALESCE(CONVERT(VARCHAR,@FECHAINIFIL, 112),' SIN @FECHAINI')
		PRINT '@FECHAFIN >'  + COALESCE(CONVERT(VARCHAR, @FECHAFINFIL, 112),' SIN @FECHAFIN')
		IF @PROCESOFACTMAS = 1
		BEGIN
			IF @PROCEDENCIA = 'MAD'
			BEGIN
				SELECT @NUMCONCNSFACT = COUNT(*) FROM MAD 
				WHERE  USUARIO_MARCAFAC = @USUARIO 
				AND    MARCAFAC= 1 
				AND    COALESCE(FACTURADA,0)=0
				AND    COALESCE(IDTERCERO,'') = @IDTERCERO
				AND    COALESCE(IDPLAN,'') = @IDPLAN
				AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
				AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
				AND    COALESCE(FACTURABLE,0) = 1
			
				SELECT @NUMCONCNSFACT2 = COUNT(*) FROM MAD 
				WHERE  USUARIO_MARCAFAC = @USUARIO 
				AND    MARCAFAC= 1 
				AND    COALESCE(FACTURADA,0)=0
				AND    COALESCE(FACTURABLE,0) = 1
				AND    (COALESCE(IDTERCERO,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
			END

			IF @PROCEDENCIA='PHD'
			BEGIN
				SELECT @NUMCONCNSFACT = COUNT(*) FROM HADM 
				WHERE  USUARIO_MARCAFAC = @USUARIO 
				AND    MARCA= 1 
				AND    COALESCE(FACTURADA,0)=0
				AND    COALESCE(IDTERCERO,'') = @IDTERCERO
				AND    COALESCE(IDPLAN,'') = @IDPLAN
				AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
				AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
				AND    COALESCE(FACTURABLE,0) = 1
			
				SELECT @NUMCONCNSFACT2 = COUNT(*) FROM HADM 
				WHERE  USUARIO_MARCAFAC = @USUARIO 
				AND    MARCA= 1 
				AND    COALESCE(FACTURADA,0)=0
				AND    COALESCE(FACTURABLE,0) = 1
				AND    (COALESCE(IDTERCERO,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
			END

			SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
			RETURN
		END
		RETURN
	END
	IF @METODO='FACTURAR_MASI'
	BEGIN 
		DECLARE @PRESTACION VARCHAR(20)
		DECLARE @N_FACTURADEV  VARCHAR(20)
		SELECT @DATOS=DATOS,@ACCION=ACCION
		FROM   OPENJSON (@PARAMETROS)
		WITH (
			DATOS NVARCHAR(MAX) AS JSON,
			ACCION SMALLINT  '$.ACCION'
		) 
		SELECT @FECHAINI=F_INIMAS,@FECHAFIN=F_FINMAS,@IDTERCERO=IDTERMAS,
		@IDPLAN=IDPLANMAS,@IDSERVICIO=IDSERVICIOMAS,@PROCEDENCIA=PROCE
		FROM   OPENJSON (@DATOS)
		WITH   (
			F_INIMAS DATE          '$.F_INIMAS',
			F_FINMAS DATE          '$.F_FINMAS',
			IDTERMAS VARCHAR(20)   '$.IDTERMAS',
			IDPLANMAS VARCHAR(20)  '$.IDPLANMAS',		
			IDSERVICIOMAS VARCHAR(20)   '$.IDSERVICIOMAS',
			PROCE VARCHAR(20)      '$.PROCE'
		)
		SELECT @F_FACTURA=DBO.FNK_GETDATE(),@COMPANIA='01',@NIT=NIT
		FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

		SELECT @IDSEDE=UBEQ.IDSEDE 
		FROM USUSU INNER JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME 
		WHERE USUARIO=@USUARIO

		IF COALESCE(@NIT,'')='' 
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Tercero Facturador No Identificado, Revise Configuración Terceros'
         
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		IF NOT EXISTS(SELECT 1 FROM PRI WHERE FECHA_INI<=DBO.FNK_GETDATE() AND FECHA_FIN+1>DBO.FNK_GETDATE() AND COALESCE(CERRADO,0)=0)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Periodo Contable No Existe o no Esta Abierto, Revise Configuración Peridos Contables'
         
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		PRINT '@ACCION >'  + COALESCE(STR(@ACCION),' SIN @ACCION')
		IF @ACCION=1 
		BEGIN
			PRINT '@PROCEDENCIA >'  + COALESCE(@PROCEDENCIA,' SIN @PROCEDENCIA')
			IF @PROCEDENCIA='MAD'
			BEGIN
				BEGIN TRY 
					EXEC SPK_FACTURAMAD_MASI_PERU @NIT,@COMPANIA,@IDSEDE,@USUARIO,@IDTERCERO,@IDPLAN,@F_FACTURA
				END TRY 
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
				IF(SELECT COUNT(*) FROM @TBLERRORES)>0
				BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
				SELECT 'OK' OK
				RETURN
			END

			IF @PROCEDENCIA='PHD'
			BEGIN
				BEGIN TRY 
					EXEC SPK_FACTURAPHD_MASI_PERU @NIT,@COMPANIA,@IDSEDE,@USUARIO,@IDTERCERO,@IDPLAN,@F_FACTURA
				END TRY 
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
				IF(SELECT COUNT(*) FROM @TBLERRORES)>0
				BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
				SELECT 'OK' OK
				RETURN
			END
		END
	END 
END



