CREATE OR ALTER PROCEDURE DBO.SPQ_AFICOL
	@JSON  NVARCHAR(MAX)
WITH ENCRYPTION
AS
DECLARE @PARAMETROS         NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
		 ,@GRUPO              VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
		 ,@IDAFILIADO         VARCHAR(20)	 ,@TIPO_DOC         VARCHAR(3)      ,@DOCIDAFILIADO VARCHAR(20)   ,@ESTADO         VARCHAR(20)
		 ,@PAPELLIDO          VARCHAR(30)    ,@SAPELLIDO        VARCHAR(30)     ,@PNOMBRE       VARCHAR(30)   ,@SNOMBRE        VARCHAR(30) 
		 ,@FNACIMIENTO        VARCHAR(10)    ,@CIUDADNAC        VARCHAR(5)      ,@SEXO          VARCHAR(9)    ,@ESTADO_CIVIL   VARCHAR(15) 
		 ,@GRUPO_SANG         VARCHAR(5)     ,@GRUPOETNICO      VARCHAR(1)                                    
		 ,@TIPODISCAPACIDAD   VARCHAR(1)     ,@IDESCOLARIDAD    VARCHAR(3)      ,@DIRECCION     VARCHAR(150)  ,@TELEFONORES    VARCHAR(15) 
		 ,@CELULAR            VARCHAR(20)    ,@CIUDAD           VARCHAR(7)      ,@ZONA          VARCHAR(12)   ,@IDBARRIO       VARCHAR(20) 
		 ,@EMAIL              VARCHAR(99)    ,@DIRECCIONLAB     VARCHAR(100)    ,@TELEFONOLAB   VARCHAR(20)   ,@IDOCUPACION    VARCHAR(5)  
		 ,@IDADMINISTRADORA   VARCHAR(20)    ,@IDPLAN           VARCHAR(6)      ,@NIVELSOCIOEC  VARCHAR(2)    ,@FECHAAFILSGSSS VARCHAR(10)    
		 ,@EDAD_ANIOS			 INT			    ,@EDAD_MESES		  INT			      ,@EDAD_DIAS	    INT           ,@CNSAFIAA	    VARCHAR(50)
		 ,@TIPOAFILIADO       VARCHAR(2)     ,@GRUPOPOB         VARCHAR(20)     ,@CONSECUTIVO   VARCHAR(13)   ,@CFDATA         NVARCHAR(MAX)
		 ,@PROCESO            VARCHAR(20)    ,@BARRIO           VARCHAR(100)    ,@PROTOCOLO     VARCHAR(20)   ,@ID             INT
       ,@CIUDADDOC          VARCHAR(20)    ,@PROGRAMA         NVARCHAR(MAX)   ,@GESTOR        NVARCHAR(MAX) ,@OBSERVACION VARCHAR(200)
       ,@AUX                NVARCHAR(MAX)  ,@IDPESPECIAL      VARCHAR(20)     ,@ESPECIALIDAD  NVARCHAR(MAX) ,@MEDICO      NVARCHAR(MAX)
       ,@IDMEDICO           VARCHAR(20)    ,@IDMEDICOORI      VARCHAR(12)     ,@RAZON         VARCHAR(20)   ,@PROCEDENCIA VARCHAR(20)
       ,@IDSEDE             VARCHAR(10)    ,@EDAD             VARCHAR(36)     ,@CORREGIMIENTO VARCHAR(50)   ,@PAIS         VARCHAR(50)
       ,@PREFIJO_1          VARCHAR(5)     ,@DPTO             VARCHAR(2)      ,@NOMBRE       VARCHAR(100)   ,@CIUDAD_NEW   VARCHAR(50)
       ,@PARENTESCO        VARCHAR(50)    ,@TELEFONO           VARCHAR(50)    ,@MARCA        INT            ,@NOMBREAFI    VARCHAR(200)
	   ,@CNSLOG			   VARCHAR(20)		,@ACCION		VARCHAR(20)		  ,@LAT_DIR		DECIMAL(14,9)	,@LNG_DIR	DECIMAL(14,9)
	   ,@PLANSALUD		   VARCHAR(21)		,@IDPROVEEDOR	VARCHAR(20)	
	   ,@CATEGORIA		   VARCHAR(20)
	   
DECLARE @F_NACIMIENTO DATE
BEGIN
	SET LANGUAGE Spanish; 
	SET DATEFORMAT dmy


	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	--PRINT 'INGRESE A SPQ_ACTI'
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)     AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
	PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
	PRINT 'SEDE='+@SEDE

	IF @METODO = 'CONSULTAAFI'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'        
		)
		--PRINT 'IDAFILIADO = '+@IDAFILIADO
		IF(SELECT COUNT(*) FROM AFI WHERE IDAFILIADO = @IDAFILIADO)=0
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El Paciente NO Existe en la Base de Datos'
		ELSE
			BEGIN TRY
			
			   -- Obtener la edad el paciente en anios, meses y dias EDAD --ESTADO_CIVIL
			   
			   SELECT @F_NACIMIENTO = FNACIMIENTO , @ESTADO = ESTADO, @CNSAFIAA = CNSAFIAA
			   FROM AFI WHERE IDAFILIADO=@IDAFILIADO
			   SELECT @EDAD_ANIOS=ANO, @EDAD_MESES=MES, @EDAD_DIAS=DIA 
			   FROM dbo.FNK_EDAD_ANO_MES_DIA(@F_NACIMIENTO, GETDATE())


				SELECT TIPO_DOC = TGEN.CODIGO -- Hay AFI.TIPO_DOC que no estan en TGEN EZERPA 20240505
					,TGEN.DESCRIPCION NOMBRETIPO_DOC
					,AFI.DOCIDAFILIADO      
					,AFI.IDPROVEEDOR      
					,AFI.CIUDADDOC          ,CIU2.NOMBRE NOMBRECIUDADDOC
					,AFI.ESTADO             
					,AFI.PAPELLIDO          
					,AFI.SAPELLIDO          
					,AFI.PNOMBRE            
					,AFI.SNOMBRE            
					,AFI.FNACIMIENTO        
					,AFI.CIUDADNAC          ,CIU.NOMBRE NOMBRECIUDADNAC
					,AFI.SEXO               
					,COALESCE( LTRIM(RTRIM(AFI.ESTADO_CIVIL))    ,'S/N')  ESTADO_CIVIL  
					,COALESCE(AFI.GRUPO_SANG  , 'S/N')    GRUPO_SANG    
					,COALESCE(AFI.GRUPOETNICO  , 'S/N')    GRUPOETNICO  
					,   COALESCE(AFI.TIPODISCAPACIDAD  , 'N')    TIPODISCAPACIDAD  
					,AFI.IDESCOLARIDAD      ,TGEN2.DESCRIPCION NOMBREIDESCOLARIDAD
					,AFI.DIRECCION          
					,AFI.TELEFONORES        
					,AFI.CELULAR            
					,AFI.CIUDAD             ,CIU3.NOMBRE NOMBRECIUDAD
					,COALESCE(AFI.ZONA,'S/N') ZONA              
					,AFI.IDBARRIO           ,CIUB.NOMBRE NOMBREIDBARRIO
					,AFI.EMAIL              
					,AFI.DIRECCIONLAB       
					,AFI.TELEFONOLAB        
					,AFI.IDOCUPACION        ,OCU.DESCRIPCION NOMBREIDOCUPACION
					,AFI.IDADMINISTRADORA   ,TER.RAZONSOCIAL NOMBREIDAMINISTRADORA
					,AFI.IDPLAN             ,PLN.DESCPLAN    NOMBREIDPLAN
					,AFI.NIVELSOCIOEC       ,TGEN3.DESCRIPCION NOMBRENIVELSOCIOEC
					,AFI.FECHAAFILSGSSS     
					,COALESCE(AFI.TIPOAFILIADO, 'S/N')TIPOAFILIADO
					,AFI.GRUPOPOB           ,TGEN4.DESCRIPCION NOMBREGRUPOPOB
					,EDAD_ANIOS = @EDAD_ANIOS
					,EDAD_MESES = @EDAD_MESES
					,EDAD_DIAS = @EDAD_DIAS
					,AFI.NOMBREAFI
					,AFI.FECHAAFILIACION
					,IPS.RAZONSOCIAL+ ' ' +COALESCE(IPS_CIU.NOMBRE, '') IPSASIGNADA
					,AFIAA.FECHAFINAL AFIAA_FECHAFINAL
					,DBO.FNK_TelefonosTercero (AFI.IDAFILIADO) TELEFONOS
					,AFI.IDAFILIADO
					,AFI.EDAD
					,DEP.NOMBRE DEPARTAMENTO
					,OCU.DESCRIPCION OCUPACION
					,floor((cast(convert(varchar(8),getdate(),112) as int)-cast(convert(varchar(8),AFI.FNACIMIENTO,112) as int) ) / 10000) as EDAD_LIMPIA
				   ,AFI.IDSEDE, SED.DESCRIPCION [NOM_SEDE]
				   ,PAIS.IDPAIS, PAIS.NOMBRE [NOMBREPAISNAC]
				   ,URG_NOMBRE,URG_DIR,URG_TELE,URG_VINCULO
				   ,LAT_DIR, LNG_DIR
				   ,PLANSALUD
				   ,AFI.CATEGORIA
				   ,DEP = (SELECT DEP.DPTO,DEP.NOMBRE FOR JSON PATH)
				   ,CIU = (SELECT CIU3.CIUDAD,CIU3.NOMBRE FOR JSON PATH)
				   ,CORREGIMIENTO = (
						SELECT TGEN.CODIGO, TGEN.DESCRIPCION, UMEREG.NOMBRE AS ZONA
						FROM TGEN 
						LEFT JOIN UMEREGD ON UMEREGD.DISTRITO= TGEN.CODIGO AND UMEREGD.CIUDAD=TGEN.CAMPO
						LEFT JOIN UMEREG ON UMEREG.ID = UMEREGD.IDUMEREG
						WHERE TABLA='CORREGIMIENTOS' 
						AND CAMPO=AFI.CIUDAD 
						AND CODIGO=AFI.CORREGIMIENTO 
						FOR JSON PATH
					)
			   into #AFI
				FROM  AFI LEFT JOIN CIU        ON AFI.CIUDADNAC        = CIU.CIUDAD
							LEFT JOIN CIU CIU2   ON AFI.CIUDADDOC        = CIU2.CIUDAD
							LEFT JOIN CIU CIU3   ON AFI.CIUDAD           = CIU3.CIUDAD
							LEFT JOIN DEP		   ON DEP.DPTO			   = CIU3.DPTO
							LEFT JOIN TGEN       ON AFI.TIPO_DOC         = TGEN.CODIGO AND TGEN.TABLA = 'General' AND TGEN.CAMPO = 'TIPOIDENT'
							LEFT JOIN TGEN TGEN2 ON AFI.IDESCOLARIDAD    = TGEN2.CODIGO AND TGEN2.TABLA = 'AFI' AND TGEN2.CAMPO = 'escolaridad'
							LEFT JOIN TGEN TGEN3 ON AFI.NIVELSOCIOEC     = TGEN3.CODIGO AND TGEN3.TABLA = 'General' AND TGEN3.CAMPO = 'NIVELSOCIOECO'
							LEFT JOIN TGEN TGEN4 ON AFI.GRUPOPOB         = TGEN4.CODIGO AND TGEN4.TABLA = 'General' AND TGEN4.CAMPO = 'GRUPOPOB'
							LEFT JOIN CIUB       ON AFI.CIUDAD           = CIUB.CIUDAD AND AFI.IDBARRIO = CIUB.IDBARRIO
							LEFT JOIN OCU        ON AFI.IDOCUPACION      = OCU.OCUPACION
							LEFT JOIN TER        ON AFI.IDADMINISTRADORA = TER.IDTERCERO
							LEFT JOIN PLN        ON AFI.IDPLAN           = PLN.IDPLAN
							LEFT JOIN TER IPS    ON AFI.IDPROVEEDOR	   = IPS.IDTERCERO
							LEFT JOIN CIU IPS_CIU ON IPS.CIUDAD		      = IPS_CIU.CIUDAD
							LEFT JOIN AFIAA      ON AFI.CNSAFIAA         = AFIAA.CNSAFIAA AND AFI.IDAFILIADO=AFIAA.IDAFILIADO AND AFI.ESTADO='Autorizado'
                     LEFT JOIN SED        ON AFI.IDSEDE           = SED.IDSEDE
                     LEFT JOIN DEP DEPNAC ON CIU.DPTO             = DEPNAC.DPTO    
                     LEFT JOIN PAIS       ON DEPNAC.PAIS          = PAIS.IDPAIS
				WHERE  AFI.IDAFILIADO = @IDAFILIADO

				SELECT TALR.DESCALTERTA DESCALERTA, ALR.OBS, ALR.CLASE
				INTO #ALR
				FROM ALR INNER JOIN TALR ON TALR.IDALERTA = ALR.IDALERTA
				WHERE IDAFILIADO = @IDAFILIADO
				AND		(FECHALIMITE IS NULL OR 
						CAST(FECHALIMITE AS DATE) >= CAST(GETDATE() AS DATE))

				
			END TRY
			BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()            
			END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES) >0
		BEGIN
			SELECT 'KO' OK, '' CONSECUTIVO
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT  'OK' OK, @IDAFILIADO IDAFILIADO

		SELECT * FROM #AFI
		SELECT * FROM #ALR

		SELECT DOCFS FOTO
		FROM AFI 
		INNER JOIN DOCS ON DocumentoID = AFI.IDFOTO
		WHERE AFI.IDAFILIADO = @IDAFILIADO AND COALESCE(IDFOTO,'')<>''


		--SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'MENUQ_CONSULTA_EXTERNA' AND IDCONTROL = 'CREA_HC_HIST'
		--SELECT COALESCE(DATO,'NO') PERMISO FROM USVGS WHERE IDVARIABLE = 'OCULTAR_ODONTOGRAMA'
		--SELECT COALESCE(DATO,'NO') PERMISO FROM USVGS WHERE IDVARIABLE = 'OCULTAR_VACUNACION'
		--SELECT COALESCE(DATO,'NO') PERMISO FROM USVGS WHERE IDVARIABLE = 'OCULTAR_COM_FAMILIAR'

		RETURN
	END
	IF @METODO = 'EDITAR' OR @METODO ='INSERTAR'
	BEGIN
		PRINT 'INGRESE= '+@METODO
		SELECT @IDAFILIADO = IDAFILIADO, @TIPO_DOC = TIPO_DOC 
			,@DOCIDAFILIADO    =dbo.FNK_LIMPIATEXTO(DOCIDAFILIADO,'0-9A-Z') 
			,@ESTADO		   =ESTADO				 ,@CIUDADDOC = CIUDADDOC
			,@PAPELLIDO        =LTRIM(RTRIM(PAPELLIDO))	,@SAPELLIDO     = LTRIM(RTRIM(SAPELLIDO))
			,@PNOMBRE		   = LTRIM(RTRIM(PNOMBRE))	,@SNOMBRE       = LTRIM(RTRIM(SNOMBRE))       
			,@FNACIMIENTO      =FNACIMIENTO          ,@CIUDADNAC     = CIUDADNAC         ,@SEXO         = SEXO         ,@ESTADO_CIVIL   = ESTADO_CIVIL  
			,@GRUPO_SANG       =GRUPO_SANG           ,@GRUPOETNICO   = GRUPOETNICO                      
			,@TIPODISCAPACIDAD =TIPODISCAPACIDAD     ,@IDESCOLARIDAD = IDESCOLARIDAD     ,@DIRECCION    = DIRECCION    ,@TELEFONORES    = TELEFONORES   
			,@CELULAR          =CELULAR              ,@CIUDAD        = CIUDAD            ,@ZONA         = ZONA         ,@IDBARRIO       = IDBARRIO      
			,@EMAIL            =EMAIL                ,@DIRECCIONLAB  = DIRECCIONLAB      ,@TELEFONOLAB  = TELEFONOLAB  ,@IDOCUPACION    = IDOCUPACION   
			,@IDADMINISTRADORA =IDADMINISTRADORA     ,@IDPLAN        = IDPLAN            ,@NIVELSOCIOEC = NIVELSOCIOEC ,@FECHAAFILSGSSS = FECHAAFILSGSSS   
			,@TIPOAFILIADO     =TIPOAFILIADO         ,@GRUPOPOB      = GRUPOPOB			 ,@PROCEDENCIA  = PROCEDENCIA   ,@IDSEDE           = IDSEDE
			,@LAT_DIR		   =LAT_DIR				 ,@LNG_DIR		 = LNG_DIR			 ,@IDPROVEEDOR = IDPROVEEDOR
			,@PLANSALUD		   =PLANSALUD
			,@CATEGORIA        =CATEGORIA
			,@CORREGIMIENTO	   =CORREGIMIENTO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)             '$.IDAFILIADO'
			,TIPO_DOC           VARCHAR(3)             '$.TIPO_DOC'
			,DOCIDAFILIADO      VARCHAR(20)            '$.DOCIDAFILIADO'
			,ESTADO             VARCHAR(12)            '$.ESTADO'
			,CIUDADDOC             VARCHAR(12)         '$.CIUDADDOC'
			,PAPELLIDO          VARCHAR(30)            '$.PAPELLIDO'
			,SAPELLIDO          VARCHAR(30)            '$.SAPELLIDO'       
			,PNOMBRE            VARCHAR(30)            '$.PNOMBRE'         
			,SNOMBRE            VARCHAR(30)            '$.SNOMBRE'         
			,FNACIMIENTO        DATE		           '$.FNACIMIENTO'     
			,CIUDADNAC          VARCHAR(5)             '$.CIUDADNAC'       
			,SEXO               VARCHAR(9)             '$.SEXO'            
			,ESTADO_CIVIL       VARCHAR(15)            '$.ESTADO_CIVIL'    
			,GRUPO_SANG         VARCHAR(5)             '$.GRUPO_SANG'      
			,GRUPOETNICO        VARCHAR(1)             '$.GRUPOETNICO'     
			,TIPODISCAPACIDAD   VARCHAR(1)             '$.TIPODISCAPACIDAD'
			,IDESCOLARIDAD      VARCHAR(3)             '$.IDESCOLARIDAD'   
			,DIRECCION          VARCHAR(150)           '$.DIRECCION'       
			,TELEFONORES        VARCHAR(15)            '$.TELEFONORES'     
			,CELULAR            VARCHAR(20)            '$.CELULAR'         
			,CIUDAD             VARCHAR(5)             '$.CIUDAD'          
			,ZONA               VARCHAR(12)            '$.ZONA'            
			,IDBARRIO           VARCHAR(20)            '$.IDBARRIO'        
			,EMAIL              VARCHAR(99)            '$.EMAIL'           
			,DIRECCIONLAB       VARCHAR(100)           '$.DIRECCIONLAB'    
			,TELEFONOLAB        VARCHAR(20)            '$.TELEFONOLAB'     
			,IDOCUPACION        VARCHAR(5)             '$.IDOCUPACION'     
			,IDADMINISTRADORA   VARCHAR(20)            '$.IDADMINISTRADORA' 
			,IDPLAN             VARCHAR(6)             '$.IDPLAN'          
			,NIVELSOCIOEC       VARCHAR(2)             '$.NIVELSOCIOEC'    
			,FECHAAFILSGSSS     DATE		             '$.FECHAAFILSGSSS'  
			,TIPOAFILIADO       VARCHAR(2)             '$.TIPOAFILIADO'    
			,GRUPOPOB           VARCHAR(20)            '$.GRUPOPOB'    
			,PROCEDENCIA        VARCHAR(20)            '$.PROCEDENCIA'
			,IDSEDE             VARCHAR(10)            '$.IDSEDE'
			,LAT_DIR			DECIMAL(14,9)		   '$.LAT_DIR'
			,LNG_DIR			DECIMAL(14,9)		   '$.LNG_DIR'
			,PLANSALUD			VARCHAR(21)            '$.PLANSALUD'
			,CATEGORIA			VARCHAR(20)            '$.CATEGORIA'
			,CORREGIMIENTO		VARCHAR(20)            '$.CORREGIMIENTO'
			,IDPROVEEDOR		VARCHAR(20)            '$.IDPROVEEDOR'

		)

		--SELECT * FROM SYS.OBJECTS O INNER JOIN SYS.COLUMNS C ON O.object_id = C.object_id WHERE O.NAME = 'AFI' AND C.NAME LIKE '%SANG%' 
		PRINT 'ANTES'
		IF COALESCE(@FNACIMIENTO,'')<> '' AND DBO.FNK_VALORVARIABLE('VALIDADEDADVSDOC')<> 'NO'
		BEGIN
			SELECT @EDAD_ANIOS=ANO, @EDAD_MESES=MES, @EDAD_DIAS=DIA 
			FROM dbo.FNK_EDAD_ANO_MES_DIA(@F_NACIMIENTO, GETDATE())
			
			IF @TIPO_DOC = 'CC' AND @EDAD_ANIOS < 18
			INSERT INTO @TBLERRORES(ERROR) SELECT 'La edad del Afiliado no corresponde con el Tipo de Documento'
			IF @TIPO_DOC = 'TI' AND (@EDAD_ANIOS > 18 OR @EDAD_ANIOS < 7 )
			INSERT INTO @TBLERRORES(ERROR) SELECT 'La edad del Afiliado no corresponde con el Tipo de Documento'
			IF @TIPO_DOC = 'RC' AND @EDAD_ANIOS > 10
			INSERT INTO @TBLERRORES(ERROR) SELECT 'La edad del Afiliado no corresponde con el Tipo de Documento'
			IF @TIPO_DOC IN ('MS','MSI') AND @EDAD_ANIOS > 18
			INSERT INTO @TBLERRORES(ERROR) SELECT 'La edad del Afiliado no corresponde con el Tipo de Documento'

		END
		IF @METODO = 'EDITAR'
		BEGIN
			IF (SELECT COUNT(*) FROM AFI WHERE IDAFILIADO = @IDAFILIADO)=0 
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El Paciente NO Existe en la Base de Datos'
			IF (SELECT COUNT(*) FROM AFI WHERE IDAFILIADO <> @IDAFILIADO AND  DOCIDAFILIADO = @DOCIDAFILIADO AND TIPO_DOC = @TIPO_DOC )>0 
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El Tipo de documento y N° de documento ya existen en el Sistema'

		END
		ELSE IF @METODO = 'INSERTAR'
		BEGIN
			PRINT 'POR EL METODO INSERTAR'

			IF (SELECT COUNT(1) FROM AFI WHERE IDAFILIADO = @IDAFILIADO AND COALESCE(@IDAFILIADO,'')<>'')>0 
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El Paciente YA Existe en la Base de Datos'
         IF (SELECT COUNT(1) FROM AFI WHERE  DOCIDAFILIADO = @DOCIDAFILIADO )>0 
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El Tipo de documento y N° de documento ya existen en el Sistema'
		END
		
		PRINT 'ANTES DE VER SI HUBO UN ERROR'
		IF(SELECT COUNT(*) FROM @TBLERRORES) = 0
		BEGIN
			PRINT 'INICIA PROCESO'
			IF @METODO = 'EDITAR'
			BEGIN
			   BEGIN TRY
			      PRINT 'EDITAR'
				   IF @FECHAAFILSGSSS = '' OR @FECHAAFILSGSSS='1900-01-01' SET @FECHAAFILSGSSS=NULL
				   ELSE SET @FECHAAFILSGSSS = REPLACE(@FECHAAFILSGSSS,'-', '')


				   --SELECT @CIUDAD,@CORREGIMIENTO

				   UPDATE AFI SET  TIPO_DOC          = @TIPO_DOC
								   ,DOCIDAFILIADO     = @DOCIDAFILIADO
								   ,ESTADO            = @ESTADO
								   ,CIUDADDOC         =  @CIUDADDOC
								   ,PAPELLIDO         = UPPER(@PAPELLIDO )      
								   ,SAPELLIDO         = UPPER(@SAPELLIDO)       
								   ,PNOMBRE           = UPPER(@PNOMBRE)         
								   ,SNOMBRE           = UPPER(@SNOMBRE)         
								   ,FNACIMIENTO       = REPLACE(@FNACIMIENTO,'-', '')
								   ,CIUDADNAC         = @CIUDADNAC       
								   ,SEXO              = @SEXO            
								   ,ESTADO_CIVIL      = @ESTADO_CIVIL    
								   ,GRUPO_SANG        = @GRUPO_SANG      
								   ,GRUPOETNICO       = @GRUPOETNICO     
								   ,TIPODISCAPACIDAD  = @TIPODISCAPACIDAD
								   ,IDESCOLARIDAD     = @IDESCOLARIDAD   
								   ,DIRECCION         = @DIRECCION       
								   ,TELEFONORES       = @TELEFONORES     
								   ,CELULAR           = @CELULAR         
								   ,CIUDAD            = @CIUDAD          
								   ,ZONA              = @ZONA            
								   ,IDBARRIO          = @IDBARRIO        
								   ,EMAIL             = @EMAIL           
								   ,DIRECCIONLAB      = @DIRECCIONLAB    
								   ,TELEFONOLAB       = @TELEFONOLAB     
								   ,IDOCUPACION       = @IDOCUPACION     
								   ,IDADMINISTRADORA  = @IDADMINISTRADORA 
								   ,IDPLAN            = @IDPLAN          
								   ,NIVELSOCIOEC      = @NIVELSOCIOEC    
								   ,FECHAAFILSGSSS    = @FECHAAFILSGSSS
								   ,TIPOAFILIADO      = @TIPOAFILIADO   
								   ,GRUPOPOB          = @GRUPOPOB
								   ,PROCEDENCIA	   = COALESCE(@PROCEDENCIA,'')
								   ,F_ACTUALIZA       = DBO.FNK_FECHA_SIN_MLS(DBO.FNK_GETDATE())
								   ,IDSEDE           = @IDSEDE
								   ,LAT_DIR			= @LAT_DIR
								   ,LNG_DIR			= @LNG_DIR
								   ,PLANSALUD		= @PLANSALUD
								   ,CATEGORIA		= @CATEGORIA
								   ,CORREGIMIENTO	= @CORREGIMIENTO
								   ,IDPROVEEDOR		= @IDPROVEEDOR
				   WHERE  IDAFILIADO = @IDAFILIADO

				--EXEC SPK_GENCONSECUTIVO '01', @SEDE, '@LOG', @CNSLOG OUTPUT
				--SELECT @CNSLOG = @SEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @CNSLOG), 8)

				--INSERT INTO USLOG (CNSLOG ,COMPANIA ,NOADMISION ,PROCESO ,REQUEST ,REFERENCIA ,USUARIO ,FECHA ,SYS_ComputerName ,TABLA)
				--SELECT	 @CNSLOG		,'01'		,@IDAFILIADO	,'EDITAR' 
				--,'CHANGE'	,@IDAFILIADO	,@USUARIO ,DBO.FNK_GETDATE() , @SYS_COMPUTERNAME	,'AFI'

				INSERT INTO AFIH ( FECHA, IDAFILIADO, TIPO_DOC, DOCIDAFILIADO, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, IDTERCERO, IDPLAN,  EMAIL, CELULAR, TELEFONORES, USUCAMBIA)
				SELECT  DBO.FNK_GETDATE(), @IDAFILIADO, @TIPO_DOC, @DOCIDAFILIADO, UPPER(@PAPELLIDO ), UPPER(@SAPELLIDO) , UPPER(@PNOMBRE) ,UPPER(@SNOMBRE) ,@IDADMINISTRADORA,@IDPLAN,  @EMAIL, @CELULAR, @TELEFONORES, @USUARIO


			   END TRY
			   BEGIN CATCH            
				   INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			   END CATCH
			END
			ELSE IF @METODO = 'INSERTAR'
			BEGIN
			   BEGIN TRY
               SELECT @IDSEDE = COALESCE(@IDSEDE,@SEDE)
				   PRINT 'GENERAMOS EL IDAFILIADO'
				 
				   --CIUDAD
				   EXEC SPK_GENCONSECUTIVO '01',@IDSEDE, '@AFI', @IDAFILIADO OUTPUT  
				   SELECT  @IDAFILIADO = @IDSEDE + REPLACE(SPACE(8 - LEN(@IDAFILIADO))+LTRIM(RTRIM(@IDAFILIADO)),SPACE(1),0)
				   PRINT '@IDAFILIADO='+COALESCE(@IDAFILIADO,'')
				   
               --IDPARENTESCO CIUDADDOC
				   INSERT INTO AFI (
						 IDAFILIADO		,IDSEDE		,TIPO_DOC	,CIUDADDOC
						,DOCIDAFILIADO	,ESTADO		,PAPELLIDO	,SAPELLIDO
						,PNOMBRE		,SNOMBRE	,FNACIMIENTO,CIUDADNAC
						,SEXO			,ESTADO_CIVIL			,GRUPO_SANG
						,GRUPOETNICO	,TIPODISCAPACIDAD		,IDESCOLARIDAD
						,DIRECCION		,TELEFONORES,CELULAR	,CIUDAD
						,ZONA			,IDBARRIO	,EMAIL		,DIRECCIONLAB
						,TELEFONOLAB	,IDOCUPACION,IDADMINISTRADORA
						,IDPLAN			,NIVELSOCIOEC
						,FECHAAFILSGSSS	,TIPOAFILIADO,GRUPOPOB	,NUMCARNET
						,IDPARENTESCO	,INCAPACIDADLABORAL		,GRUPOATESPECIAL
						,NACIONALIDAD	,CLASEAFILIACIONARS		,IDTIPOAFILIACION
						,IDCLASEAFILIACION			,DIR_PPAL	,IDPROVEEDOR
						,IDPAIS			,SISBENGRUPOB			,F_ACTUALIZA
						,PROCEDENCIA	,PLANSALUD	,CATEGORIA	,CORREGIMIENTO
						,LAT_DIR		,LNG_DIR
					)
					SELECT @IDAFILIADO
						,@IDSEDE
						,@TIPO_DOC
						,@CIUDADDOC
						,@DOCIDAFILIADO
						,'Activo'
						,UPPER(@PAPELLIDO)
						,UPPER(@SAPELLIDO)
						,UPPER(@PNOMBRE)
						,UPPER(@SNOMBRE)
						,SUBSTRING(@FNACIMIENTO, 9, 2) + '/' + SUBSTRING(@FNACIMIENTO, 6, 2) + '/' + SUBSTRING(@FNACIMIENTO, 1, 4)
						,@CIUDADNAC
						,@SEXO
						,@ESTADO_CIVIL
						,@GRUPO_SANG
						,@GRUPOETNICO
						,@TIPODISCAPACIDAD
						,@IDESCOLARIDAD
						,@DIRECCION
						,@TELEFONORES
						,@CELULAR
						,@CIUDAD
						,@ZONA
						,@IDBARRIO
						,@EMAIL
						,@DIRECCIONLAB
						,@TELEFONOLAB
						,@IDOCUPACION
						,@IDADMINISTRADORA
						,@IDPLAN
						,@NIVELSOCIOEC
						,SUBSTRING(@FECHAAFILSGSSS, 9, 2) + '/' + SUBSTRING(@FECHAAFILSGSSS, 6, 2) + '/' + SUBSTRING(@FECHAAFILSGSSS, 1, 4)
						,@TIPOAFILIADO
						,@GRUPOPOB
						,@IDAFILIADO
						,'N'
						,'No'
						,''
						,'COLOMBIANO'
						,'NV'
						,'Individual'
						,'NV'
						,'D'
						,@IDPROVEEDOR
						,(SELECT TOP 1 DEP.PAIS FROM CIU INNER JOIN DEP ON DEP.DPTO=CIU.DPTO WHERE CIU.CIUDAD=@CIUDAD)
						,1
						,DBO.FNK_FECHA_SIN_MLS(GETDATE())
						,COALESCE(@PROCEDENCIA, '')
						,@PLANSALUD
						,@CATEGORIA
						,@CORREGIMIENTO
						,@LAT_DIR			
						,@LNG_DIR
			   END TRY
			BEGIN CATCH            
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
			END
		END


		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK, '' CONSECUTIVO
			SELECT ERROR FROM @TBLERRORES
			RETURN
			SELECT 'KO' OK, '' CONSECUTIVO
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
			SELECT 'OK' OK, @IDAFILIADO CONSECUTIVO
		RETURN
	END
	IF @METODO = 'AFIFAM'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO ,@CFDATA = CFDATA , @CONSECUTIVO = CONSECUTIVO ,@PROCESO = PROCESO
 		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO',  
			CONSECUTIVO        VARCHAR(13)            '$.CONSECUTIVO',  
			PROCESO            VARCHAR(20)            '$.PROCESO',
			CFDATA             NVARCHAR(MAX) AS JSON
		)
      SELECT @ID = ID
      FROM OPENJSON (@CFDATA) WITH (
       ID         INT '$.ID'
      )
		--SELECT @CFDATA AS CFDATA
		IF @PROCESO = 'Insertar'
		BEGIN
			INSERT INTO AFIFAM (IDAFILIADO ,PNOMBRE ,SNOMBRE ,PAPELLIDO ,SAPELLIDO ,SEXO ,FNACIMIENTO ,PARENTESCO ,IDESCOLARIDAD ,IDOCUPACION ,FECHAREG ,USUARIOREG
                            ,OBSERVACION) 
			SELECT @IDAFILIADO ,PNOMBRE ,SNOMBRE ,PAPELLIDO ,SAPELLIDO
				,SEXO          = (SELECT VALOR FROM OPENJSON(SEXO)          WITH (VALOR VARCHAR(9) '$.value'))   
				,FNACIMIENTO
				,PARENTESCO    = (SELECT VALOR FROM OPENJSON(PARENTESCO)    WITH (VALOR VARCHAR(20) '$.value'))   
				,IDESCOLARIDAD = (SELECT VALOR FROM OPENJSON(IDESCOLARIDAD) WITH (VALOR VARCHAR(20) '$.value'))   
				,IDOCUPACION   = (SELECT VALOR FROM OPENJSON(IDOCUPACION)   WITH (VALOR VARCHAR(20) '$.value'))   
				,GETDATE(), @USUARIO ,OBSERVACION
			FROM OPENJSON (@CFDATA) WITH (
			 PNOMBRE        VARCHAR(30) '$.PNOMBRE'
			,SNOMBRE        VARCHAR(30) '$.SNOMBRE'
			,PAPELLIDO      VARCHAR(30) '$.PAPELLIDO'
			,SAPELLIDO      VARCHAR(30) '$.SAPELLIDO'
			,SEXO           NVARCHAR(MAX) AS JSON 
			,FNACIMIENTO    DATE    '$.FNACIMIENTO'
			,PARENTESCO     NVARCHAR(MAX) AS JSON 
			,IDESCOLARIDAD  NVARCHAR(MAX) AS JSON  
			,IDOCUPACION    NVARCHAR(MAX) AS JSON
         ,OBSERVACION    VARCHAR(MAX) '$.OBSERVACION'
			)
			SELECT 'OK' OK ,CONVERT(VARCHAR(20),@@IDENTITY) CONSECUTIVO
			RETURN
		END
      IF @PROCESO = 'Editar'
      BEGIN
         UPDATE AFIFAM 
         SET
          PNOMBRE       = X.PNOMBRE      
         ,SNOMBRE       = X.SNOMBRE      
         ,PAPELLIDO     = X.PAPELLIDO    
         ,SAPELLIDO     = X.SAPELLIDO    
         ,SEXO          = X.SEXO         
         ,FNACIMIENTO   = X.FNACIMIENTO  
         ,PARENTESCO    = X.PARENTESCO   
         ,IDESCOLARIDAD = X.IDESCOLARIDAD
         ,IDOCUPACION   = X.IDOCUPACION  
         ,OBSERVACION   = X.OBSERVACION  
         FROM (SELECT PNOMBRE 
                     ,SNOMBRE 
                     ,PAPELLIDO 
                     ,SAPELLIDO
				         ,SEXO          = (SELECT VALOR FROM OPENJSON(SEXO)          WITH (VALOR VARCHAR(9) '$.value'))   
				         ,FNACIMIENTO
				         ,PARENTESCO    = (SELECT VALOR FROM OPENJSON(PARENTESCO)    WITH (VALOR VARCHAR(20) '$.value'))   
				         ,IDESCOLARIDAD = (SELECT VALOR FROM OPENJSON(IDESCOLARIDAD) WITH (VALOR VARCHAR(20) '$.value'))   
				         ,IDOCUPACION   = (SELECT VALOR FROM OPENJSON(IDOCUPACION)   WITH (VALOR VARCHAR(20) '$.value'))   
				         ,OBSERVACION
			      FROM OPENJSON (@CFDATA) WITH (
			       PNOMBRE        VARCHAR(30) '$.PNOMBRE'
			      ,SNOMBRE        VARCHAR(30) '$.SNOMBRE'
			      ,PAPELLIDO      VARCHAR(30) '$.PAPELLIDO'
			      ,SAPELLIDO      VARCHAR(30) '$.SAPELLIDO'
			      ,SEXO           NVARCHAR(MAX) AS JSON 
			      ,FNACIMIENTO    DATE    '$.FNACIMIENTO'
			      ,PARENTESCO     NVARCHAR(MAX) AS JSON 
			      ,IDESCOLARIDAD  NVARCHAR(MAX) AS JSON  
			      ,IDOCUPACION    NVARCHAR(MAX) AS JSON
               ,OBSERVACION    VARCHAR(MAX) '$.OBSERVACION'
			      )
             ) X
         WHERE ID = @ID
         SELECT 'OK' OK ,CONVERT(VARCHAR(20),@ID) CONSECUTIVO
         RETURN
      END

      

		RETURN         
	END
	IF @METODO = 'AGREGAR_BARRIO'
	BEGIN
		SELECT @CIUDAD =  CIUDAD, @BARRIO = BARRIO
		FROM OPENJSON (@PARAMETROS)
		WITH (CIUDAD    VARCHAR(20)    '$.CIUDAD',
			BARRIO    VARCHAR(100)   '$.BARRIO')

			IF (SELECT  COUNT(1) FROM CIUB INNER JOIN CIU ON CIUB.CIUDAD = CIU.CIUDAD WHERE  CIU.CIUDAD = @CIUDAD AND CIUB.NOMBRE = @BARRIO  ) > 0
			BEGIN
					INSERT INTO @TBLERRORES(ERROR)
					SELECT 'Este barrio ya existe para la ciudad seleccionada ' ERROR    
			END
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
			END

		SELECT 'OK' OK

			SELECT @IDBARRIO = NULL
			EXEC SPK_GENCONSECUTIVO '01','01','@IDBARRIO', @IDBARRIO OUTPUT  
			SELECT @IDBARRIO = 'B' + REPLACE(SPACE(6 - LEN(@IDBARRIO))+LTRIM(RTRIM(@IDBARRIO)),SPACE(1),0)    

			INSERT INTO CIUB (CIUDAD, IDBARRIO, NOMBRE)
			VALUES (@CIUDAD, @IDBARRIO,LTRIM(RTRIM(@BARRIO)))
        
	END
	IF @METODO = 'AGREGAR_CIUDAD'
	BEGIN
		SELECT @CIUDAD =  CIUDAD, @PAIS = PAIS
		FROM OPENJSON (@PARAMETROS)
		WITH (CIUDAD    VARCHAR(100)    '$.CIUDAD',
			PAIS    VARCHAR(50)   '$.PAIS')

			IF EXISTS(SELECT *  FROM CIU
						INNER JOIN DEP ON CIU.DPTO = DEP.DPTO
						INNER JOIN PAIS ON DEP.PAIS = PAIS.IDPAIS 
						WHERE CIU.NOMBRE = LTRIM(RTRIM(@CIUDAD)) AND PAIS.IDPAIS = @PAIS)
			BEGIN
				INSERT INTO @TBLERRORES(ERROR)
				SELECT 'Este Ciudad ingresad ya existe para el Pais seleccionado ' ERROR    
			END
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END

		SELECT 'OK' OK

			IF EXISTS(SELECT * FROM DEP WHERE  PAIS = @PAIS)
			BEGIN
			SELECT TOP 1 @PREFIJO_1 = DPTO FROM DEP WHERE PAIS = @PAIS
			END
			ELSE
			BEGIN
			SELECT @DPTO = SUBSTRING(NOMBRE,0,3), @NOMBRE = NOMBRE FROM PAIS WHERE  IDPAIS = @PAIS
			INSERT INTO DEP (DPTO, NOMBRE, PAIS)
			SELECT @DPTO, @NOMBRE, @PAIS
			SELECT TOP 1 @PREFIJO_1 = DPTO FROM DEP WHERE PAIS = @PAIS
			END

			SELECT @CIUDAD_NEW = NULL
			EXEC SPK_GENCONSECUTIVO '01','01','@CIUDAD_NEW', @CIUDAD_NEW OUTPUT  
			SELECT @CIUDAD_NEW = @PREFIJO_1 + REPLACE(SPACE(3 - LEN(@CIUDAD_NEW))+LTRIM(RTRIM(@CIUDAD_NEW)),SPACE(1),0)    

			INSERT INTO CIU (CIUDAD, DPTO, NOMBRE, DESCENTRAL)
			SELECT @CIUDAD_NEW,@PREFIJO_1,  LTRIM(RTRIM(@CIUDAD)), 'No'
        
	END
	IF @METODO = 'INSERTA_MODELO'
	BEGIN
   SELECT @MODELO =  MODELO, @IDAFILIADO = IDAFILIADO, @PROTOCOLO = PROTOCOLO
   FROM OPENJSON (@PARAMETROS)
   WITH (MODELO         VARCHAR(20)    '$.MODELO',
         IDAFILIADO     VARCHAR(20)   '$.IDAFILIADO',
         PROTOCOLO      VARCHAR(20)    '$.PROTOCOLO')

         IF (SELECT  COUNT(1) FROM AFIPE INNER JOIN  MPE ON  AFIPE.IDPESPECIAL = MPE.IDPESPECIAL   WHERE  AFIPE.IDAFILIADO = @IDAFILIADO AND MPE.IDPESPECIAL = @MODELO  ) > 0
            BEGIN
			      INSERT INTO @TBLERRORES(ERROR)
			      SELECT 'Este modelo ya existe para el paciente seleccionado ' ERROR    
            END
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
            BEGIN
		         SELECT 'KO' OK
		         SELECT ERROR FROM @TBLERRORES
		         RETURN
            END

        SELECT 'OK' OK
        INSERT INTO AFIPE (IDAFILIADO, IDPESPECIAL, NIVELRIESGO, FECHA, FECHAFINAL, IDTERCEROENTREGA, DXPE, FECHADX, FECHA1TX, ALTERNO1, ESTADIO, IDPROT, IDGESTOR, ESTADO, IDMEDICOTRA, OBSERVACION)
        VALUES (@IDAFILIADO, @MODELO, 'N', NULL, NULL, '', '', NULL, NULL, '', '', @PROTOCOLO, NULL, 'Activo', '', NULL)

        EXEC SPK_GENERA_AFIPROTOCOLO @IDAFILIADO, @MODELO, @PROTOCOLO, '01', @SEDE, @USUARIO
        
   END
	IF @METODO = 'VALIDA_INSERTARAFI'
	BEGIN
		SELECT COUNT(1) val1 FROM USGRUH WHERE IDPROCEDIMIENTO = 'MENUQ_CONSULTA_EXTERNA' AND IDCONTROL = 'INSERTA_AFI' AND GRUPO = (SELECT DBO.FNK_DESCIFRAR(USUSU.GRUPO)  FROM USUSU WHERE  USUARIO = @USUARIO) AND PERMISO = 1
	END
	IF @METODO = 'VALIDA_EDITARAFI'
	BEGIN
		SELECT COUNT(1) val2 FROM USGRUH WHERE IDPROCEDIMIENTO = 'MENUQ_CONSULTA_EXTERNA' AND IDCONTROL = 'EDITAR_AFI' AND GRUPO = (SELECT DBO.FNK_DESCIFRAR(USUSU.GRUPO)  FROM USUSU WHERE  USUARIO = @USUARIO) AND PERMISO = 1
	END
	IF @METODO = 'VALIDA_INSERTARMODELO'
	BEGIN
		SELECT COUNT(1) val3 FROM USGRUH WHERE IDPROCEDIMIENTO = 'MENUQ_CONSULTA_EXTERNA' AND IDCONTROL = 'INSERTA_MODE' AND GRUPO = (SELECT DBO.FNK_DESCIFRAR(USUSU.GRUPO)  FROM USUSU WHERE  USUARIO = @USUARIO) AND PERMISO = 1
	END
	IF @METODO = 'ACTUALIZAR_CONTACTOS'
	BEGIN
	 SELECT @IDAFILIADO  =  IDAFILIADO, @EMAIL = EMAIL, 
			@TELEFONORES = @TELEFONORES,
			@CELULAR	 = CELULAR
	   FROM OPENJSON (@PARAMETROS)
	   WITH (
			IDAFILIADO  VARCHAR(20)   '$.IDAFILIADO',
			EMAIL       VARCHAR(99)   '$.EMAIL',
			TELEFONORES VARCHAR(15)   '$.TELEFONORES',
			CELULAR		VARCHAR(20)   '$.CELULAR'
		)

		UPDATE AFI SET 
			CELULAR = IIF(COALESCE(@CELULAR,'')='', CELULAR, @CELULAR),
			TELEFONORES = IIF(COALESCE(@TELEFONORES,'')='', TELEFONORES, @TELEFONORES),
			EMAIL = IIF(COALESCE(@EMAIL,'')='', EMAIL, @EMAIL)
		WHERE IDAFILIADO = @IDAFILIADO

		SELECT 'OK' AS OK, @IDAFILIADO AS IDAFILIADO

   END
	IF @METODO = 'CRUDAFIPE'
	BEGIN
     SELECT @AUX = DATOS FROM OPENJSON(@PARAMETROS) WITH  (DATOS NVARCHAR(MAX) AS JSON)
     SELECT   @PROCESO        =   PROCESO         ,
               @ESTADO        =   ESTADO         ,
               @OBSERVACION   =   OBSERVACION         ,
               @IDAFILIADO   =   IDAFILIADO         ,
               @GESTOR      = (SELECT VALOR FROM OPENJSON(GESTOR )    WITH (VALOR VARCHAR(20) '$.value'))  ,
               @PROGRAMA      = (SELECT VALOR FROM OPENJSON(PROGRAMA )    WITH (VALOR VARCHAR(20) '$.value'))  ,
               @PROTOCOLO     = (SELECT VALOR FROM OPENJSON(PROTOCOLO )    WITH (VALOR VARCHAR(20) '$.value')),
               @IDPESPECIAL = IDPESPECIAL
      FROM OPENJSON(@AUX) 
      WITH (	
            PROCESO          VARCHAR(30)   '$.PROCESO' ,
            PROGRAMA        NVARCHAR(MAX)   AS JSON,
            PROTOCOLO        NVARCHAR(MAX)   AS JSON,
            GESTOR         NVARCHAR(MAX)   AS JSON,
            OBSERVACION     VARCHAR(200)   '$.OBSERVACION' ,
            IDAFILIADO     VARCHAR(20)   '$.IDAFILIADO' ,
            ESTADO         VARCHAR(20)   '$.ESTADO' , 
            IDPESPECIAL         VARCHAR(20)   '$.IDPESPECIAL'  )
 
     IF UPPER(@PROCESO) = 'INSERTAR'
     BEGIN
         IF(SELECT COUNT(*) FROM AFIPE WHERE IDAFILIADO = @IDAFILIADO AND IDPESPECIAL = @PROGRAMA  ) > 0
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe este modelo para este paciente'
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
          IF(SELECT COUNT(*) FROM MPEMES WHERE 1=2 ) > 0
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) SELECT 'Aun por definir'
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END

         BEGIN TRY
            INSERT INTO AFIPE( IDAFILIADO, IDPESPECIAL, NIVELRIESGO, IDPROT, IDGESTOR, ESTADO, OBSERVACION
                        ) 
            SELECT @IDAFILIADO, @PROGRAMA ,'N',@PROTOCOLO, @GESTOR, @ESTADO, @OBSERVACION
         END TRY
         BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END

         SELECT 'OK' OK, @IDAFILIADO IDAFILIADO
         RETURN
      END
      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
          IF(@IDPESPECIAL <> @PROGRAMA ) 
            BEGIN
               IF(SELECT COUNT(*) FROM AFIPE WHERE IDAFILIADO = @IDAFILIADO AND IDPESPECIAL = @PROGRAMA ) > 0
               BEGIN
                  INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe este modelo para este paciente'
                  SELECT 'KO' OK
                  SELECT ERROR FROM @TBLERRORES
                  RETURN
               END
            END

        IF(SELECT COUNT(*) FROM AFIPE WHERE 1 = 2 ) > 0
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) SELECT 'Aun por definir'
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         BEGIN TRY
            UPDATE AFIPE SET IDPESPECIAL=@PROGRAMA, IDPROT=@PROTOCOLO, IDGESTOR=@GESTOR, ESTADO=@ESTADO, OBSERVACION=@OBSERVACION
            WHERE IDAFILIADO = @IDAFILIADO AND IDPESPECIAL=@IDPESPECIAL
         END TRY
         BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END

         SELECT 'OK' OK, @IDAFILIADO IDAFILIADO
         RETURN
      END
   END
	IF @METODO = 'CRUDAFIPEMES'
	BEGIN
     SELECT @AUX = DATOS FROM OPENJSON(@PARAMETROS) WITH  (DATOS NVARCHAR(MAX) AS JSON)
     SELECT    @PROCESO       =   PROCESO         ,
               @ESTADO        =   ESTADO         ,
               @ESPECIALIDAD  =   (SELECT VALOR FROM OPENJSON(ESPECIALIDAD )    WITH (VALOR VARCHAR(20) '$.value'))  ,        
               @IDAFILIADO    =   IDAFILIADO         ,
               @MEDICO        = (SELECT VALOR FROM OPENJSON(MEDICO )    WITH (VALOR VARCHAR(20) '$.value'))  ,
               @PROGRAMA      = (SELECT VALOR FROM OPENJSON(PROGRAMA )    WITH (VALOR VARCHAR(20) '$.value'))  ,
               @IDPESPECIAL   =   IDPESPECIAL  ,
               @IDMEDICO      =   IDMEDICO  ,
               @ID  =   ID
      FROM OPENJSON(@AUX) 
      WITH (	
            PROCESO          VARCHAR(30)   '$.PROCESO' ,
            ESTADO         VARCHAR(20)   '$.ESTADO' , 
            ESPECIALIDAD        NVARCHAR(MAX)   AS JSON,
            IDAFILIADO     VARCHAR(20)   '$.IDAFILIADO' ,
            MEDICO        NVARCHAR(MAX)   AS JSON,
            PROGRAMA         NVARCHAR(MAX)   AS JSON,
            IDPESPECIAL         VARCHAR(20)   '$.IDPESPECIAL' , 
            IDMEDICO         VARCHAR(20)   '$.IDMEDICO' ,
            ID         INT   '$.ID' 

      )
 
     IF UPPER(@PROCESO) = 'INSERTAR'
     BEGIN
         IF(SELECT COUNT(*) FROM AFIPEMES WHERE IDAFILIADO = @IDAFILIADO AND IDPESPECIAL = @PROGRAMA  AND IDEMEDICA = @ESPECIALIDAD) > 0
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe esta especialidad.'
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
          IF(SELECT COUNT(*) FROM MPEMES WHERE 1=2 ) > 0
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) SELECT 'Aun por definir'
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END

         BEGIN TRY
            INSERT INTO AFIPEMES( IDAFILIADO, IDPESPECIAL, IDEMEDICA, IDMEDICO, ESTADO, USUCREA, FECHACREA
                        ) 
            SELECT @IDAFILIADO, @PROGRAMA ,@ESPECIALIDAD,@MEDICO,  @ESTADO, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE())
         END TRY
         BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END

         SELECT 'OK' OK
         RETURN
      END
      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         
          IF(@IDPESPECIAL <> @PROGRAMA ) 
            BEGIN
               IF(SELECT COUNT(*) FROM AFIPEMES WHERE IDAFILIADO = @IDAFILIADO AND IDPESPECIAL = @PROGRAMA AND IDEMEDICA = @ESPECIALIDAD AND IDMEDICO = @MEDICO ) > 0
               BEGIN
                  INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe este medico registrado para esta especialidad'
                  SELECT 'KO' OK
                  SELECT ERROR FROM @TBLERRORES
                  RETURN
               END
            END

         IF(SELECT COUNT(*) FROM AFIPEMES WHERE 1 = 2 ) > 0
         BEGIN
            INSERT INTO @TBLERRORES(ERROR) SELECT 'Aun por definir'
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         
         SELECT @IDMEDICOORI = JSON_VALUE(@AUX, '$.MEDICOORIGINAL.value') ,@RAZON = JSON_VALUE(@AUX, '$.razonMedDiferente.value')
         --QUERY 2
         BEGIN TRY
            UPDATE AFIPEMES SET IDPESPECIAL=@PROGRAMA, IDEMEDICA=@ESPECIALIDAD, IDMEDICO=@MEDICO, ESTADO=@ESTADO
            WHERE ID = @ID
            IF @IDMEDICOORI <> @MEDICO
               INSERT INTO LOGVARIOS(TABLA,IDAFILIADO,IDPESPECIAL,IDEMEDICA,IDMEDICOANT,IDMEDICONVO,MOTIVO, USUARIO, FECHA)
               SELECT 'AFIPEMES',@IDAFILIADO, @IDPESPECIAL,@ESPECIALIDAD,@IDMEDICOORI,@MEDICO,@RAZON, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE())

         END TRY
         BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END

         SELECT 'OK' OK, @IDAFILIADO IDAFILIADO
         RETURN
      END
   END
	IF @METODO = 'PERMIAGENDA'
	BEGIN
      SELECT 'OK' OK
      SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'CONF_CONSULTA_EXTERNA' AND IDCONTROL = 'mod_reprograma'
      SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'CONF_CONSULTA_EXTERNA' AND IDCONTROL = 'mod_cuota'
      SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'CONF_CONSULTA_EXTERNA' AND IDCONTROL = 'mod_recaudar'
      SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'CONF_CONSULTA_EXTERNA' AND IDCONTROL = 'mod_editar_cita'
      SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'CONF_CONSULTA_EXTERNA' AND IDCONTROL = 'mod_facturar'
      SELECT COALESCE(PERMISO,0) PERMISO FROM USGRUH WHERE GRUPO = @GRUPO AND IDPROCEDIMIENTO = 'CONF_CONSULTA_EXTERNA' AND IDCONTROL = 'mod_cancelar_cita'
      RETURN
   END
	IF @METODO = 'VALIDAATENDER'
	BEGIN
		SELECT @CONSECUTIVO = CONSECUTIVO
		FROM OPENJSON (@PARAMETROS) WITH (
			CONSECUTIVO         VARCHAR(13)            '$.CONSECUTIVO'       
		)
      
	  IF (SELECT DATO FROM USVGS WHERE  IDVARIABLE = 'VALIDAR_PAGO_QASAR') = 'SI' AND (SELECT DBO.FNK_VALORVARIABLE ('IXCOUNTRY')) <> 'PERU'
			AND  EXISTS (SELECT 1 FROM CIT WHERE  CONSECUTIVO = @CONSECUTIVO AND COALESCE(CIT.GENEROCAJA,0)= 1 AND (COALESCE(VALORCOPAGO,0)>0 OR IDTERCEROCA=DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'))) --TABLA TEMPORAL TFCJ
			AND NOT EXISTS (SELECT 1 FROM FCJ WHERE NOADMISION =@CONSECUTIVO AND PROCEDENCIA='CITAS' AND COALESCE(ESTADO,'')='P'  AND COALESCE(CERRADA,0)=1)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'No se puede atender, la cita no ha sido pagada.'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
	  IF (SELECT DATO FROM USVGS WHERE  IDVARIABLE = 'VALIDAR_PAGO_QASAR') = 'SI'  AND (SELECT DBO.FNK_VALORVARIABLE ('IXCOUNTRY')) = 'PERU'
			AND  EXISTS (SELECT 1 FROM CIT WHERE  CONSECUTIVO = @CONSECUTIVO AND COALESCE(CIT.GENEROCAJA,0)= 1 AND (COALESCE(VALORCOPAGO,0)>0 OR IDTERCEROCA=DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'))) --TABLA TEMPORAL TFCJ
			AND NOT EXISTS (SELECT 1 FROM FCJ WHERE NOADMISION =@CONSECUTIVO AND PROCEDENCIA='CITAS' AND COALESCE(ESTADO,'')='P'  )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'No se puede atender, la cita no ha sido pagada.'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      IF (SELECT DATO FROM USVGS WHERE  IDVARIABLE = 'ATENDERSINLLEGAR') <> 'SI' AND  (SELECT FECHALLEGA FROM CIT WHERE  CONSECUTIVO = @CONSECUTIVO) IS NULL
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'No se puede atender, la cita se encuentra pendiente de llegada.'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      BEGIN TRY
         SELECT 'OK' OK
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
   RETURN
	END
	IF @METODO = 'VALIDA_DATOS_COMPLETOS'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO, @PROCEDENCIA = PROCEDENCIA
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'       
			,PROCEDENCIA       VARCHAR(20)            '$.PROCEDENCIA'       
		)
		
		IF  (SELECT  UPPER(DATO ) FROM USVGS  WHERE IDVARIABLE = 'VALIDA_DATOS_AFI' ) = 'SI'
		BEGIN
			SELECT @EDAD = COALESCE(EDAD,''),                           @FNACIMIENTO =COALESCE(FNACIMIENTO,'')                ,@PAPELLIDO = COALESCE(PAPELLIDO ,'')        ,@PNOMBRE = COALESCE(PNOMBRE ,'')
				,@CORREGIMIENTO = COALESCE(CORREGIMIENTO ,'')        ,@CIUDAD =COALESCE(CIUDAD ,'')                         ,@GRUPO_SANG =COALESCE(GRUPO_SANG ,'')       ,@GRUPOPOB = COALESCE(GRUPOPOB ,'') 
				,@GRUPOETNICO =COALESCE(GRUPOETNICO ,'')              ,@TIPODISCAPACIDAD =COALESCE(TIPODISCAPACIDAD ,'')    ,@IDESCOLARIDAD= COALESCE(IDESCOLARIDAD ,'') ,@DIRECCION=COALESCE(DIRECCION ,'') 
				,@TELEFONORES =COALESCE(TELEFONORES ,'')              ,@EMAIL =COALESCE(EMAIL ,'')                          ,@IDADMINISTRADORA =COALESCE(IDADMINISTRADORA ,'') ,@IDPLAN=COALESCE(IDPLAN ,'') 
				,@TIPOAFILIADO=COALESCE(TIPOAFILIADO ,'')             ,@IDSEDE=COALESCE(IDSEDE ,'') 
			FROM AFI WHERE  IDAFILIADO = @IDAFILIADO

			IF  @EDAD = '' OR @FNACIMIENTO = '' OR @PAPELLIDO = '' OR @PNOMBRE = '' OR /*@CORREGIMIENTO = '' OR*/ @CIUDAD = '' OR @GRUPO_SANG = '' OR @GRUPOPOB = ''
			OR @GRUPOETNICO = '' OR @TIPODISCAPACIDAD = '' OR @IDESCOLARIDAD = '' OR @DIRECCION = '' OR @TELEFONORES = '' OR @EMAIL = '' OR @IDADMINISTRADORA = '' OR @IDPLAN = ''
			OR @TIPOAFILIADO = '' OR @IDSEDE = '' OR @FNACIMIENTO = ''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT '¡Completa el registro del afiliado! Por favor, asegúrate de llenar todos los campos obligatorios para continuar el proceso.'
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			IF  @EDAD = ''
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'El Px no tinedad Edad registrada. Complete los datos.'
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
		END

      --COMPLETAR LOS DATOS A VALIDAR - PENDIENTE
     
      BEGIN TRY
         SELECT 'OK' OK
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
   RETURN
	END
	IF @METODO = 'VALIDA_TRIAGE'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'       
		)

      IF  EXISTS(SELECT * FROM AFI WHERE IDAFILIADO = @IDAFILIADO AND COALESCE(AFI.MTRIAGE,'') = 2)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Este paciente ya est? siendo atendido.'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      IF  EXISTS(SELECT * FROM AFI WHERE IDAFILIADO = @IDAFILIADO AND COALESCE(AFI.IDADMINISTRADORA,'') = '')
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Paciente no tiene configurado la empresa Administradora de su seguro en la ficha de afiliados.'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
     
      BEGIN TRY
         IF EXISTS(SELECT * FROM AFI WHERE IDAFILIADO = @IDAFILIADO AND COALESCE(AFI.MTRIAGE,'') = 1)
         BEGIN
            SELECT 'OK' OK, 1 ATENDIDO, (SELECT PRIORIDAD FROM AFI WHERE  IDAFILIADO = @IDAFILIADO) MARCA
         END
         ELSE
         BEGIN
            SELECT 'OK' OK, 0 ATENDIDO ,  URG_NOMBRE,URG_DIR,URG_TELE,URG_VINCULO, SEXO, EDAD
            , floor((cast(convert(varchar(8),getdate(),112) as int)-cast(convert(varchar(8),AFI.FNACIMIENTO,112) as int) ) / 10000) as EDAD_LIMPIA FROM AFI WHERE IDAFILIADO = @IDAFILIADO

			SELECT ROW_NUMBER() OVER(ORDER BY CNSTRIAGE DESC) AS FILA_CITA, PRIO_INGRESO, CNSTRIAGE, IDAFILIADO, FECHA, ATENDIDO, USUARIO, FMTRIAGE, IDSEDE, CLASI, CLASI_2, PRIO_INGRESO
				, CASE	WHEN HTRIAGE.PRIO_INGRESO= 1 THEN 'Atencion Normal'
						WHEN  HTRIAGE.PRIO_INGRESO= 2 THEN 'Discapacitado'
						WHEN HTRIAGE.PRIO_INGRESO= 3 THEN 'Adulto Mayor'
						WHEN HTRIAGE.PRIO_INGRESO= 4 THEN 'Pediatrico'
						WHEN HTRIAGE.PRIO_INGRESO= 5 THEN 'Obstétrico'
						WHEN HTRIAGE.PRIO_INGRESO= 6 THEN 'Accidente/Lesionado'
						WHEN HTRIAGE.PRIO_INGRESO= 7 THEN 'Quirurgico' END [PRIORIDAD_DESC_2]
			FROM HTRIAGE
			WHERE IDAFILIADO = @IDAFILIADO
			ORDER BY  HTRIAGE.FECHA  DESC
         END
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
   RETURN
	END
	IF @METODO = 'BUSCA_PX'
	BEGIN
		SELECT @DOCIDAFILIADO = DOCIDAFILIADO, @TIPO_DOC = TIPO_DOC
		FROM OPENJSON (@PARAMETROS) WITH (
			DOCIDAFILIADO         VARCHAR(20)            '$.DOCIDAFILIADO'    ,   
			TIPO_DOC         VARCHAR(20)            '$.TIPO_DOC'       
		)

      IF  NOT EXISTS(SELECT * FROM AFI WHERE DOCIDAFILIADO = @DOCIDAFILIADO AND TIPO_DOC = @TIPO_DOC)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'El acompa?ante ingresado no se encuentra en el sistema'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      BEGIN TRY
         SELECT  'OK' OK, NOMBREAFI,TELEFONORES, DIRECCION FROM AFI WHERE DOCIDAFILIADO = @DOCIDAFILIADO AND TIPO_DOC = @TIPO_DOC
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
   RETURN
	END
	IF @METODO = 'ASIGNA_TRIAGE'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO, @MARCA = MARCA, @TIPO_DOC = TIPO_DOC, @DOCIDAFILIADO = DOCIDAFILIADO, @NOMBREAFI = NOMBREAFI, @TELEFONO = TELEFONO, @DIRECCION = DIRECCION
      , @PARENTESCO = PARENTESCO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'    ,   
			MARCA                INT            '$.MARCA'    ,   
			TIPO_DOC         VARCHAR(20)            '$.TIPO_DOC'   ,    
			NOMBREAFI         VARCHAR(200)            '$.NOMBREAFI'    ,   
			TELEFONO         VARCHAR(20)            '$.TELEFONO'    ,   
			DOCIDAFILIADO         VARCHAR(20)            '$.DOCIDAFILIADO'    ,   
			DIRECCION         VARCHAR(200)            '$.DIRECCION'    ,   
			PARENTESCO         VARCHAR(50)            '$.PARENTESCO'     
		)

      IF  EXISTS (SELECT 1 FROM USVGS WHERE IDVARIABLE = 'DATACOMPAOBLIGA' AND COALESCE(DATO,'')= 'SI' AND (COALESCE(@NOMBREAFI,'')= '' OR COALESCE(@TELEFONO,'')= '' OR COALESCE(@DIRECCION,'')= '' OR COALESCE(@PARENTESCO,'')= '' ))
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'Los datos del acompa?ante son Obligatorios'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
	  IF (SELECT COUNT(1) FROM HADM WHERE IDAFILIADO = @IDAFILIADO AND CERRADA = 0 AND CLASEING = 'A')>0
	  BEGIN
         SELECT 'KO' OK
         SELECT ERROR = 'Usuario con ingreso sin cerrar, comuniquese con el personal encargado de admisiones'
         RETURN		
	  END
      BEGIN TRY
         UPDATE AFI SET FTRIAGE = DBO.FNK_FECHA_SIN_MLS(GETDATE()), MTRIAGE = 1,IDSEDETRIAGE = @SEDE, IDSEDE = @SEDE, PRIORIDAD = @MARCA, 
		 USUARIOATIENDE = @USUARIO  ,URG_NOMBRE = @NOMBREAFI,URG_DIR = @DIRECCION,URG_TELE = @TELEFONO, URG_VINCULO = @PARENTESCO
         WHERE  IDAFILIADO = @IDAFILIADO
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
   RETURN
	END
	IF @METODO = 'QUITA_TRIAGE'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'     
		)

      IF  1 <> 1
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'El acompa?ante ingresado no se encuentra en el sistema'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      BEGIN TRY
         UPDATE AFI SET FTRIAGE = NULL, MTRIAGE = 0,IDSEDETRIAGE = NULL,  PRIORIDAD = 0, USUARIOATIENDE = 'D'+@USUARIO  WHERE  IDAFILIADO = @IDAFILIADO
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT 'OK' OK
   RETURN
	END
	IF @METODO = 'GETFOTO'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'     
		)
		
		SELECT 'OK' OK

		SELECT DOCFS FOTO
		FROM AFI 
		INNER JOIN DOCS ON DocumentoID = AFI.IDFOTO
		WHERE AFI.IDAFILIADO = @IDAFILIADO AND COALESCE(IDFOTO,'')<>''
		
		RETURN
	END
	IF @METODO = 'CALC_NAC'
	BEGIN
		SELECT @F_NACIMIENTO = F_NACIMIENTO
		FROM OPENJSON (@PARAMETROS) WITH (
			F_NACIMIENTO         DATE            '$.F_NACIMIENTO'     
		)
		SELECT 'OK' OK, floor((cast(convert(varchar(8),getdate(),112) as int)-cast(convert(varchar(8),@F_NACIMIENTO,112) as int) ) / 10000) as EDAD
		RETURN
	END
	IF @METODO = 'AGREGA_NOTA'
	BEGIN
		SELECT @OBSERVACION = OBSERVACION, @IDAFILIADO = IDAFILIADO
		FROM OPENJSON (@PARAMETROS) WITH (
			OBSERVACION         VARCHAR(200)            '$.OBSERVACION'     
			,IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'     
		)
		SELECT 'OK' OK
		UPDATE AFI SET OBSERVACION = @OBSERVACION WHERE  IDAFILIADO = @IDAFILIADO
		RETURN
	END
	IF @METODO = 'LLAMAR_PACIENTE'
	BEGIN
		SELECT @CONSECUTIVO = CONSECUTIVO, @PROCEDENCIA = PROCEDENCIA, @ACCION = ACCION
	   FROM OPENJSON (@PARAMETROS)
	   WITH		 (
		CONSECUTIVO			VARCHAR(20)		'$.CONSECUTIVO'
		,PROCEDENCIA		VARCHAR(20)		'$.PROCEDENCIA'
		,ACCION				VARCHAR(20)		'$.ACCION'
		)

		IF UPPER(@ACCION)= 'LLAMAR' AND EXISTS(SELECT * FROM GTUR WHERE GTUR.CONSECUTIVO = @CONSECUTIVO AND GTUR.ESTADO = 0 )
			RETURN
		
		BEGIN TRY 
			IF UPPER(@ACCION)= 'LLAMAR'
			BEGIN
				
				DECLARE @CONSULTORIO VARCHAR(20)
				SELECT @CONSULTORIO = MED.CONSULTORIO
				FROM USUSU INNER JOIN MED ON MED.IDMEDICO=USUSU.IDMEDICO
				WHERE USUARIO = @USUARIO

				INSERT INTO GTUR ( FECHA, TIPOCNS, CONSECUTIVO, IDAFILIADO, IDMEDICO, IDEMEDICA, HABCAMA, ESTADO, CELULAR, EMAIL, USUARIO, FVENCE)
				SELECT DBO.FNK_GETDATE(), 'CIT', CONSECUTIVO, CIT.IDAFILIADO, IDMEDICO, IDEMEDICA, @CONSULTORIO, 0,  AFI.CELULAR,AFI.EMAIL,@USUARIO,  DATEADD(mi, 5 , DBO.FNK_GETDATE())
				FROM CIT 
				INNER JOIN AFI ON CIT.IDAFILIADO = AFI.IDAFILIADO
				WHERE CIT.CONSECUTIVO = @CONSECUTIVO
				/* NOTIFICAR AL CELULAR DEL PACIENTE */

			END

			IF UPPER(@ACCION)= 'QUITAR'
			BEGIN
				UPDATE GTUR SET GTUR.ESTADO = 2 WHERE GTUR.CONSECUTIVO = @CONSECUTIVO AND GTUR.ESTADO = 0
			END
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF EXISTS(SELECT 1 FROM @TBLERRORES)
		BEGIN
			SELECT 'KO' AS OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' AS OK
		RETURN
	END
	IF @METODO = 'CONSULTA_NOTAS'
	BEGIN
		SELECT @CONSECUTIVO = CONSECUTIVO
	   FROM OPENJSON (@PARAMETROS)
	   WITH		 (
		CONSECUTIVO			VARCHAR(20)		'$.CONSECUTIVO'
		)
		
		BEGIN TRY 
			SELECT 'OK' AS OK
			SELECT CITSE.CONSECUTIVO, CITSE.ITEM, CITSE.USUARIO, USUSU.NOMBRE, CITSE.SYS_COMPUTERNAME, CITSE.OBSERVACION, CITSE.FECHA, CITSE.IDAFILIADO
				, CITSE.TIPO 
			FROM  CITSE
				INNER JOIN USUSU ON CITSE.USUARIO = USUSU.USUARIO
			WHERE CITSE.TIPO = 'Nota' AND CITSE.CONSECUTIVO	 = @CONSECUTIVO
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR)
			SELECT ERROR_MESSAGE()
		END CATCH

		IF EXISTS(SELECT 1 FROM @TBLERRORES)
		BEGIN
			SELECT 'KO' AS OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' AS OK
		RETURN
	END
	IF @METODO = 'CONSULTA_ADMISIONES'
	BEGIN
		SELECT @IDAFILIADO = IDAFILIADO
		FROM OPENJSON (@PARAMETROS) WITH (
			IDAFILIADO         VARCHAR(20)            '$.IDAFILIADO'        
		)
		IF COALESCE(@IDAFILIADO,'')=''
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR='Debe indicar el idafiliado a consultar'
			RETURN
		END
		
		SELECT 'OK' AS OK
		SELECT DISTINCT NOADMISION as value, coalesce(NOADMISION,'')+ ' - ' + CONVERT(VARCHAR,HADM.FECHA,103) as label
		FROM HADM
		WHERE IDAFILIADO=@IDAFILIADO
		RETURN
	END
   IF @METODO='CREA_TERCERO'     
   BEGIN         
      SELECT @IDAFILIADO= IDAFILIADO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         IDAFILIADO VARCHAR(20) '$.IDAFILIADO'
            )           
      IF COALESCE(@IDAFILIADO,'')<>''
      BEGIN
         BEGIN TRY           
               EXEC SPK_INSERT_TERDEAFI @IDAFILIADO,'AFI'           
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH        
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR) SELECT 'No se Enviarion los datos Correctamente'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END   
END





