IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURA_ASIS_T' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURA_ASIS_T
END
GO
CREATE PROCEDURE DBO.SPK_FACTURA_ASIS_T
@NOADMISION       VARCHAR(16),
@NIT              VARCHAR(20),
@COMPANIA         VARCHAR(2),
@IDSEDE           VARCHAR(5),
@USUARIO          VARCHAR(12), 
@SYS_COMPUTERNAME VARCHAR(254),
@CNSRPDX          VARCHAR(20),
@TFECHA           SMALLINT = 0,
@FECHAFAC         DATETIME = NULL
WITH ENCRYPTION
AS    
DECLARE @ITEM INT  
DECLARE @ID2  VARCHAR(20)
BEGIN 
   DECLARE RPDX_CURSOR CURSOR FOR
   SELECT ITEM FROM RPDX WHERE CNS = @CNSRPDX AND COALESCE(VALOR10,0)=1
   OPEN RPDX_CURSOR
   FETCH NEXT FROM RPDX_CURSOR
   INTO @ITEM
   WHILE @@FETCH_STATUS = 0  
   BEGIN  
      IF DBO.FNK_VALORVARIABLE('CLASE_IPS')='IPS_DOMI'
      BEGIN
         IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX AND COALESCE(ID2,'')='C')
         BEGIN
            EXEC DBO.SPK_FACTURA_ADMISION_DOMI_COPA @NOADMISION, @NIT, @COMPANIA, @IDSEDE, @USUARIO, @SYS_COMPUTERNAME, @CNSRPDX, @ITEM, @TFECHA, @FECHAFAC
         END
         ELSE
         BEGIN
            EXEC DBO.SPK_FACTURA_ADMISION_DOMI @NOADMISION, @NIT, @COMPANIA, @IDSEDE, @USUARIO, @SYS_COMPUTERNAME, @CNSRPDX, @ITEM, @TFECHA, @FECHAFAC 
         END
      END
      ELSE
      BEGIN
         PRINT 'Verifico de nuevo el contrato'
         IF NOT EXISTS(SELECT * FROM PPT INNER JOIN RPDX ON PPT.IDTERCERO=RPDX.IDTERCERO AND PPT.IDPLAN=RPDX.ID1
                   WHERE RPDX.ITEM=@ITEM
                   AND  (COALESCE(CAPITADO,0)=1 OR COALESCE(PFACTURARIND,0)=0))
         BEGIN
            EXEC DBO.SPK_FACTURA_ASIS @NOADMISION, @NIT, @COMPANIA, @IDSEDE, @USUARIO, @SYS_COMPUTERNAME, @CNSRPDX, @ITEM, @TFECHA, @FECHAFAC 
         END
      END
      FETCH NEXT FROM RPDX_CURSOR
      INTO @ITEM
   END
   CLOSE RPDX_CURSOR
   DEALLOCATE RPDX_CURSOR
END




