CREATE OR ALTER PROCEDURE DBO.SPQ_ANEXOS_HADMFTR @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@NOADMISION VARCHAR(20)            ,@CNSRPDX  VARCHAR(20)           ,@TAB VARCHAR(20)
      ,@TANEXO VARCHAR(20)                ,@IDTERCERO VARCHAR(20)          ,@IDPLAN VARCHAR(6)
      ,@N_FACTURA VARCHAR(20)             ,@ANEXO VARCHAR(20)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='ANEXO_SINFAC'     
   BEGIN         
      SELECT @NOADMISION =NOADMISION      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION VARCHAR(20) '$.NOADMISION'
      )
      IF EXISTS(SELECT  * FROM HADM WHERE NOADMISION=@NOADMISION)
      BEGIN
         SELECT @IDSEDE=IDSEDE  FROM HADM WHERE NOADMISION=@NOADMISION
         IF COALESCE(@IDSEDE,'')=''
         BEGIN
            SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO
         END
         SELECT @CNSRPDX=SPACE(20)
         EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = 'RPDX', @NVOCONSEC = @CNSRPDX OUTPUT
         BEGIN TRY           
              EXEC SPK_AFACTURAR @NOADMISION,@CNSRPDX               
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encotro el Nro de Admision Verifique e Intente de Nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@CNSRPDX CNSRPDX
      RETURN 
   END 
   IF @METODO='BORRA_RPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSRPDX VARCHAR(20) '$.CNSRPDX'
      )
      DELETE RPDX WHERE CNS=@CNSRPDX  
   END 
   IF @METODO='IMPRIMIR_ANEXO'     
   BEGIN         
      SELECT @TAB=TAB,@TANEXO=TANEXO,@ANEXO=ANEXO,@NOADMISION=NOADMISION,@IDTERCERO=IDTERCERO,@IDPLAN=IDPLAN,@N_FACTURA=N_FACTURA       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
       TAB  VARCHAR(20)    '$.TAB',
       TANEXO  VARCHAR(20)   '$.TANEXO',
       ANEXO  VARCHAR(20)   '$.ANEXO',
       NOADMISION  VARCHAR(20)   '$.NOADMISION',
       IDTERCERO  VARCHAR(20)   '$.IDTERCERO',
       IDPLAN  VARCHAR(20)   '$.IDPLAN',
       N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      SELECT 'OK'OK,HADM.NOADMISION,DBO.FNK_FECHA_GRINGA(HADM.FECHA)+' '+CONVERT(VARCHAR,HADM.FECHA,108) FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,AFI.TIPOAFILIADO,
      TER.NIT,TER.RAZONSOCIAL,PPT.IDCONTRATO,PLN.TIPOSISTEMA,PLN.IDPLAN,AFI.NIVELSOCIOEC,DBO.FNK_FECHA_GRINGA(HADM.FECHAALTAMED)+' '+CONVERT(VARCHAR,HADM.FECHAALTAMED,108) F_ALTA,
      STUFF((
        SELECT DISTINCT ', '+N_FACTURA FROM HADMF WHERE  HADMF.NOADMISION=HADM.NOADMISION  AND ESTADO='P'
        FOR XML PATH('')
         ),1,1,'')FACTURAS,
      (SELECT TOP 1 DBO.FNK_FECHA_GRINGA(FTR.F_FACTURA) FROM FTR INNER JOIN HADMF ON FTR.N_FACTURA=FTR.N_FACTURA WHERE HADMF.NOADMISION=HADM.NOADMISION AND PROCEDENCIA='SALUD' AND FTR.ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')F_FACTURA,
      (SELECT TOP 1 DBO.FNK_FECHA_GRINGA(FTR.F_VENCE) FROM  FTR INNER JOIN HADMF ON FTR.N_FACTURA=FTR.N_FACTURA WHERE HADMF.NOADMISION=HADM.NOADMISION AND PROCEDENCIA='SALUD' AND FTR.ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')F_VENCE,
      @USUARIO USUARIORPT,DBO.FNK_FECHA_GRINGA(GETDATE())F_RPT, CONVERT(VARCHAR,GETDATE(),108)H_RPT,HADM.VLR_COPAGOEXTERNO
      FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
                INNER JOIN TER ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=TER.IDTERCERO
                INNER JOIN PLN ON CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PLN.IDPLAN
                LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                  CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
      WHERE HADM.NOADMISION=@NOADMISION
      IF @ANEXO='Normal'
      BEGIN
         SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
         CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                   CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                        CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                   ELSE SER.IDSERVICIO END
              ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
          END IDSERVICIO,
          REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
          CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
          CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
          HPRED.VALORCOPAGO)VALORCOPAGO,CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                   INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                   INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                   INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                   LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                   LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                   LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                     CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                   LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
         AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
         ORDER BY HPRE.PREFIJO ASC,HPRE.FECHA ASC
      END
      IF @ANEXO='Area'
      BEGIN
         SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
         CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                   CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                        CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                   ELSE SER.IDSERVICIO END
              ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
          END IDSERVICIO,
          REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
          CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
          CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
          HPRED.VALORCOPAGO)VALORCOPAGO,CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                   INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                   INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                   INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                   LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                   LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                   LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                     CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                   LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
         AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
         ORDER BY HPRE.IDAREA ASC,  HPRE.PREFIJO ASC,HPRE.FECHA ASC
      END
      IF @ANEXO='Prefijo'
      BEGIN
         SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,
         CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                   CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                        CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                   ELSE SER.IDSERVICIO END
              ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
          END IDSERVICIO,
          REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
          CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE SER.CODCUPS END CODCUM,
          CONVERT(INT,SUM(HPRED.CANTIDAD))CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
          SUM(HPRED.VALORCOPAGO))VALORCOPAGO,CONVERT(DECIMAL(14,2),SUM(HPRED.VALOREXCEDENTE))VALOREXCEDENTE
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                   INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                   INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                   INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                   LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                   LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                   LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                     CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                   LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
         AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
         GROUP BY  HPRE.PREFIJO,PRE.NOM_PREFIJO,
         CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                   CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                        CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                   ELSE SER.IDSERVICIO END
              ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
          END ,REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),''),
          CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE SER.CODCUPS END,
          CONVERT(DECIMAL(14,2),HPRED.VALOR)
         ORDER BY HPRE.PREFIJO ASC
      END
      IF @ANEXO='Ccosto'
      BEGIN
         SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
         CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                   CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                        CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                   ELSE SER.IDSERVICIO END
              ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
          END IDSERVICIO,
          REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
          CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
          CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
          HPRED.VALORCOPAGO)VALORCOPAGO,CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                   INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                   INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                   INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                   LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                   LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                   LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                     CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                   LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
         AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
         ORDER BY HPRE.CCOSTO ASC,  HPRE.PREFIJO ASC,HPRE.FECHA ASC
      END
      RETURN
   END  
END