IF NOT EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='TSECRES' AND XTYPE='U')
BEGIN
   CREATE TABLE TSECRES(
   IDTSECRES INT IDENTITY(1,1),
   CODTURNO VARCHAR(20),
   USUARIO  VARCHAR(20),
   FECHA DATETIME,
   TIPOPERSONAL VARCHAR(20),-
   TIPO_USUARIO VARCHAR(20),
   CODNOV       VARCHAR(20),
   HCUMP       INT,
   HPEND       INT,
   HNOV        INT,
   ESTADO      VARCHAR(10)
   )
   ALTER TABLE TSECRES
   ADD CONSTRAINT TSECRESIDTSECRES
   PRIMARY KEY CLUSTERED (IDTSECRES)
END
IF NOT EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='TURESUM' AND XTYPE='U')
BEGIN
   CREATE TABLE TURESUM(
   IDTURESUM    INT IDENTITY(1,1),
   PERIODO      VARCHAR(7),
   USUARIO      VARCHAR(20),
   TIPOPERSONAL VARCHAR(20),
   TIPO_USUARIO VARCHAR(20),
   CODNOV       VARCHAR(20),
   HCUMP        INT,
   HPEND        INT,
   HNOV         INT,
   ESTADO       VARCHAR(10)
   )
   ALTER TABLE TURESUM
   ADD CONSTRAINT TSECRESIDTURESUM
   PRIMARY KEY CLUSTERED (IDTURESUM)
END
IF NOT EXISTS(SELECT * FROM SYS.indexes WHERE name='TSECRESUSUARIOCODTURNOFECHA')
BEGIN
   CREATE UNIQUE INDEX TSECRESUSUARIOCODTURNOFECHA ON TSECRES (USUARIO,CODTURNO,FECHA,IDTSECRES)
END
IF NOT EXISTS(SELECT * FROM SYS.indexes WHERE name='TURESUMPERIODOUSUARIO')
BEGIN
   CREATE UNIQUE INDEX TURESUMPERIODOUSUARIO ON TURESUM (PERIODO,USUARIO)
END

IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'TSECFU'  AND   C.NAME = 'RESUM')
BEGIN
   ALTER TABLE TSECFU  ADD RESUM BIT
END

IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'TSECFU'  AND   C.NAME = 'IDTSECRES')
BEGIN
   ALTER TABLE TSECFU  ADD IDTSECRES INT
END