IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_ANULAR_DOCUMENTO_FACTEP' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_ANULAR_DOCUMENTO_FACTEP
END
GO
CREATE PROCEDURE DBO.SPK_ANULAR_DOCUMENTO_FACTEP 
@N_FACTURA  VARCHAR(20),
@CNSFNOT     VARCHAR(20)=NULL,
@MOTIVO      VARCHAR(255),
@USUARIO     VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE @JSON VARCHAR(MAX)
DECLARE @TOKEN VARCHAR(100)
DECLARE @NITEMISOR VARCHAR(20)
DECLARE @URLFACT VARCHAR(256)
DECLARE @TIPODOC   VARCHAR(2)
DECLARE @PREFACT VARCHAR(4)
DECLARE @CORRELATIVO VARCHAR(20)
DECLARE @F_EMISION VARCHAR(10)
DECLARE @sUrl VARCHAR(MAX) 
DECLARE @obj INT
DECLARE @valorDeRegreso INT
DECLARE @response VARCHAR(8000)
DECLARE @src VARCHAR(255)
DECLARE @desc VARCHAR(255)
DECLARE @BODY VARCHAR(MAX)
DECLARE @FACTEP VARCHAR(20)
DECLARE @CODQR VARCHAR(100)
DECLARE @CODHASH VARCHAR(50)
DECLARE @ESTDOC  VARCHAR(10)
DECLARE @URLFACTEP VARCHAR(256)
DECLARE @DESCSUNAT VARCHAR(MAX)
DECLARE @ERRORES VARCHAR(MAX)
DECLARE @NROCOMPORBANTE VARCHAR(20)
DECLARE @PROCEDENCIA VARCHAR(10)
DECLARE @NOREFERENCIA VARCHAR(20)
BEGIN
   IF DBO.FNK_VALORVARIABLE('PROVEEDOR_FACTUELECT')='MIFACT'
   BEGIN
      IF DB_NAME()=DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION')
      BEGIN
         SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRODJSON')
         SELECT @TOKEN=dbo.FNK_VALORVARIABLE('TOKEN_FACTU_ELE_PERU')
         --SELECT @NITEMISOR=dbo.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
         SELECT @NITEMISOR=NIT FROM TER  WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
      END
      ELSE
      BEGIN
         SELECT @URLFACT=DBO.FNK_VALORVARIABLE('URLFACT_ELE_PRUEJSON')
         SELECT @TOKEN='gN8zNRBV+/FVxTLwdaZx0w=='
         SELECT @NITEMISOR='20100100100'
      END
   
      IF LEN(COALESCE(@TOKEN,''))<20
      BEGIN
         PRINT 'No existe el token de seguridad'
         RETURN
      END
      IF COALESCE(@CNSFNOT,'')=''
      BEGIN
         PRINT 'ES FACTURA'
         SELECT @TIPODOC= CASE WHEN TIPOFIN='N' THEN '03' ELSE '01' END,@PREFACT=LEFT(N_FACTURA,4), @CORRELATIVO= RIGHT(N_FACTURA,8), 
         @F_EMISION=REPLACE(CONVERT(VARCHAR,F_FACTURA,102),'.','-') ,@FACTEP=FACTEP
         FROM FTR WHERE N_FACTURA=@N_FACTURA
      END
      ELSE
      BEGIN
          SELECT @TIPODOC= CASE FNOT.CLASE WHEN 'C' THEN '07' WHEN 'D' THEN '08' ELSE '' END,@PREFACT=LEFT(CNSDIANFE,4), @CORRELATIVO=RIGHT(CNSDIANFE,8),
          @F_EMISION=REPLACE(CONVERT(VARCHAR,F_NOTA,102),'.','-') 
          FROM FNOT WHERE N_FACTURA=@N_FACTURA AND CNSFNOT=@CNSFNOT
      END
      IF COALESCE(@FACTEP,'') NOT IN('OK','ERROR')
      BEGIN
         IF @TIPODOC IN('03','01')
         BEGIN
            UPDATE FTR SET ESTADO='A',RAZONANULACION=@MOTIVO WHERE N_FACTURA=@N_FACTURA
            SELECT @NROCOMPORBANTE=NROCOMPROBANTE,@PROCEDENCIA=PROCEDENCIA,@NOREFERENCIA=NOREFERENCIA FROM FTR WHERE N_FACTURA=@N_FACTURA
            IF EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPORBANTE)
            BEGIN
               UPDATE MCP SET ESTADO=1,ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPORBANTE
            END
            ELSE 
            BEGIN
               IF EXISTS(SELECT * FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPORBANTE)
               BEGIN
                  DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPORBANTE
                  DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPORBANTE
               END
            END
            IF @PROCEDENCIA='SALUD'
            BEGIN 
               IF @TIPODOC='01'
               BEGIN
                  UPDATE HPRED SET FACTURADA=0,N_FACTURA=NULL WHERE N_FACTURA=@N_FACTURA
               END
               ELSE
               BEGIN
                  UPDATE HPRED SET N_FACTURAH=NULL WHERE N_FACTURAH=@N_FACTURA
               END
               UPDATE HADMF SET ESTADO='A' WHERE N_FACTURA=@N_FACTURA AND NOADMISION=@NOREFERENCIA
            END
            ELSE
            BEGIN
               IF @PROCEDENCIA='CE'
               BEGIN
                  IF @TIPODOC='01'
                  BEGIN 
                     UPDATE AUT SET FACTURADA=0,N_FACTURA=NULL WHERE NOAUT=@NOREFERENCIA AND N_FACTURA=@N_FACTURA
                     UPDATE AUTD SET FACTURADA=0,N_FACTURA=NULL
                     FROM AUT INNER JOIN AUTD ON AUT.IDAUT=AUTD.IDAUT
                     WHERE AUT.IDAUT=@NOREFERENCIA
                     AND AUTD.N_FACTURA=@N_FACTURA
                  END
                  ELSE
                  BEGIN
                     UPDATE AUT SET FACTURADA=0,N_FACTURA=NULL WHERE NOAUT=@NOREFERENCIA AND N_FACTURA=@N_FACTURA
                     UPDATE AUTD SET NFACTURA=NULL
                     FROM AUT INNER JOIN AUTD ON AUT.IDAUT=AUTD.IDAUT
                     WHERE AUT.IDAUT=@NOREFERENCIA
                     AND AUTD.NFACTURA=@N_FACTURA
                  END
               END
               IF @PROCEDENCIA='CI'
               BEGIN
                  IF @TIPODOC='01'
                  BEGIN
                     UPDATE CIT SET FACTURADA=0,N_FACTURA=NULL WHERE CONSECUTIVO=@NOREFERENCIA AND N_FACTURA=@N_FACTURA
                  END
                  ELSE
                  BEGIN
                     UPDATE CIT SET NFACTURA=NULL WHERE CONSECUTIVO=@NOREFERENCIA AND NFACTURA=@N_FACTURA
                  END
               END
            END
         END
         ELSE
         BEGIN
            UPDATE  FNOT SET ESTADO='A' WHERE N_FACTURA=@N_FACTURA AND CNSFNOT=@CNSFNOT
         END
         PRINT 'ME DEVUELVO EL DOCUMENTO NO FUE ENVIADO'
         RETURN
      END
      SELECT @JSON=' { '
      SELECT @JSON=@JSON+'"TOKEN":"'+@TOKEN+'",'
      SELECT @JSON=@JSON+'"NUM_NIF_EMIS": "'+@NITEMISOR+'",'
      SELECT @JSON=@JSON+'"COD_TIP_NIF_EMIS": "6",'
      SELECT @JSON=@JSON+'"FEC_EMIS": "'+@F_EMISION+'",'
      SELECT @JSON=@JSON+'"COD_TIP_CPE": "'+@TIPODOC+'",'
      SELECT @JSON=@JSON+'"NUM_SERIE_CPE": "'+@PREFACT+'",'
      SELECT @JSON=@JSON+'"NUM_CORRE_CPE": "'+@CORRELATIVO+'",'
      SELECT @JSON=@JSON+'"TXT_DESC_MTVO": "'+dbo.FNK_LIMPIATEXTO(COALESCE(@MOTIVO,''),'0-9 A-Z().;:,')+'",'
      SELECT @JSON=@JSON+'"COD_PTO_VENTA": "'+@USUARIO+'"'

      SELECT @JSON=@JSON+' }    '
      
      IF LEN(@JSON)<10
      BEGIN
         PRINT 'NO TENGO DATOS'
         RETURN
      END
      IF LEN(@URLFACT)<30
      BEGIN
         PRINT 'No existe api valida para el envio '
         RETURN
      END

     PRINT 'DEFINITIVO'
     PRINT @JSON
     SELECT @sUrl=REPLACE(@URLFACT,'SendInvoice','LowInvoice')
     SELECT @BODY=@JSON

     PRINT '@sUrl='+@sUrl

      EXEC sys.sp_OACreate 'MSXML2.ServerXMLHttp', @obj OUT
      EXEC sys.sp_OAMethod @obj, 'Open', NULL, 'POST', @sUrl, false
      Exec sp_OAMethod @obj, 'setRequestHeader', null, 'Content-Type', 'application/json'
      Exec sp_OAMethod @obj, 'send', null, @body
      Exec sp_OAMethod @obj, 'responseText', @Response OUTPUT
      Exec sp_OADestroy @obj

      SELECT @CODQR=CODQR,@CODHASH=CODHASH,@ESTDOC=ESTDOC,@URLFACTEP=URLFACTEP,@DESCSUNAT=DESCSUNAT,@ERRORES=ERRORES
      FROM OPENJSON(@Response)
      WITH(
             CODQR       VARCHAR(100) '$.cadena_para_codigo_qr'
            ,CODHASH    VARCHAR(50) '$.codigo_hash'
            ,ESTDOC     VARCHAR(10) '$.estado_documento'
            ,URLFACTEP  VARCHAR(256) '$.url'
            ,ERRORES    VARCHAR(MAX) '$.errors'
            ,DESCSUNAT  VARCHAR(MAX) '$.sunat_description'
      )
      IF @ESTDOC='105' -- SI FUE ANULADO
      BEGIN
         IF @TIPODOC IN('03','01')
         BEGIN
            UPDATE FTR SET ESTADO='A',RAZONANULACION=@MOTIVO WHERE N_FACTURA=@N_FACTURA
            SELECT @NROCOMPORBANTE=NROCOMPROBANTE,@PROCEDENCIA=PROCEDENCIA,@NOREFERENCIA=NOREFERENCIA FROM FTR WHERE N_FACTURA=@N_FACTURA
            IF EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPORBANTE)
            BEGIN
               UPDATE MCP SET ESTADO=1,ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPORBANTE
            END
            ELSE 
            BEGIN
               IF EXISTS(SELECT * FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPORBANTE)
               BEGIN
                  DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPORBANTE
                  DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPORBANTE
               END
            END
            IF @PROCEDENCIA='SALUD'
            BEGIN 
               IF @TIPODOC='01'
               BEGIN
                  UPDATE HPRED SET FACTURADA=0,N_FACTURA=NULL WHERE N_FACTURA=@N_FACTURA
               END
               ELSE
               BEGIN
                  UPDATE HPRED SET N_FACTURAH=NULL WHERE N_FACTURAH=@N_FACTURA
               END
               UPDATE HADMF SET ESTADO='A' WHERE N_FACTURA=@N_FACTURA AND NOADMISION=@NOREFERENCIA
            END
            ELSE
            BEGIN
               IF @PROCEDENCIA='CE'
               BEGIN
                  IF @TIPODOC='01'
                  BEGIN 
                     UPDATE AUT SET FACTURADA=0,N_FACTURA=NULL WHERE NOAUT=@NOREFERENCIA AND N_FACTURA=@N_FACTURA
                     UPDATE AUTD SET FACTURADA=0,N_FACTURA=NULL
                     FROM AUT INNER JOIN AUTD ON AUT.IDAUT=AUTD.IDAUT
                     WHERE AUT.IDAUT=@NOREFERENCIA
                     AND AUTD.N_FACTURA=@N_FACTURA
                  END
                  ELSE
                  BEGIN
                     UPDATE AUT SET FACTURADA=0,N_FACTURA=NULL WHERE NOAUT=@NOREFERENCIA AND N_FACTURA=@N_FACTURA
                     UPDATE AUTD SET NFACTURA=NULL
                     FROM AUT INNER JOIN AUTD ON AUT.IDAUT=AUTD.IDAUT
                     WHERE AUT.IDAUT=@NOREFERENCIA
                     AND AUTD.NFACTURA=@N_FACTURA
                  END
               END
               IF @PROCEDENCIA='CI'
               BEGIN
                  IF @TIPODOC='01'
                  BEGIN
                     UPDATE CIT SET FACTURADA=0,N_FACTURA=NULL WHERE CONSECUTIVO=@NOREFERENCIA AND N_FACTURA=@N_FACTURA
                  END
                  ELSE
                  BEGIN
                     UPDATE CIT SET NFACTURA=NULL WHERE CONSECUTIVO=@NOREFERENCIA AND NFACTURA=@N_FACTURA
                  END
               END
            END
         END
         ELSE
         BEGIN
            UPDATE  FNOT SET ESTADO='A' WHERE N_FACTURA=@N_FACTURA AND CNSFNOT=@CNSFNOT
         END
      END
   END
END