IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'VWK_RESUCIT_AUT' AND TYPE='V')
BEGIN
 DROP VIEW VWK_RESUCIT_AUT
END
GO
CREATE VIEW VWK_RESUCIT_AUT
AS
SELECT X.CONSECUTIVOCIT,SUM(CASE WHEN DX_PEND=0 THEN  X.VLR_PROTOCOLO ELSE 0 END)VLR_PROTOCOLO,SUM(CASE WHEN DX_PEND=0 THEN VLR_AGUDO ELSE 0 END)VLR_AGUDO,
X.ESPROGRAMAS,SUM(DX_PEND)DX_PEND
FROM (
SELECT AUT.CONSECUTIVOCIT,AUT.NOAUT,AUT.ESPROGRAMAS,AUTD.IDSERVICIO,SUM(CASE WHEN COALESCE(AUTD.PROTOCOLO,0)= 1  THEN  AUTD.VALOREXCEDENTE ELSE 0 END)VLR_PROTOCOLO,
SUM(CASE WHEN COALESCE(AUTD.PROTOCOLO,0)= 0 THEN  AUTD.VALOREXCEDENTE ELSE 0 END)VLR_AGUDO,
CASE WHEN COALESCE(AUTD.ENLAB,0)=1 THEN 
      CASE WHEN EXISTS(SELECT * FROM  LING INNER JOIN LORD ON LING.NOINGRESO=LORD.NOINGRESO 
            WHERE LING.NOPRESTACION=AUT.NOAUT AND LORD.ESTADO='R') THEN 0 ELSE 1 END ELSE 0 END DX_PEND
FROM  AUT INNER JOIN AUTD ON AUTD.IDAUT     = AUT.IDAUT 
		INNER JOIN SER  ON SER.IDSERVICIO = AUTD.IDSERVICIO 
		LEFT JOIN TER  ON TER.IDTERCERO  = AUTD.IDTERCEROCA
WHERE COALESCE(AUTD.NOCOBRABLE,0)=0
AND COALESCE(AUTD.GENERADO,0)=1
AND COALESCE(AUTD.FACTURADA,0)=0
AND COALESCE(AUTD.VALOR,0)>0
AND COALESCE(AUTD.VALOREXCEDENTE,0)>0
AND NOT EXISTS(SELECT * FROM CIT WHERE AUT.CONSECUTIVOCIT=CIT.CONSECUTIVO AND COALESCE(FACTURADA,0)=1)
GROUP BY AUT.CONSECUTIVOCIT,AUT.NOAUT,AUTD.ENLAB,AUT.ESPROGRAMAS,AUTD.IDSERVICIO)X
GROUP BY X.CONSECUTIVOCIT,X.ESPROGRAMAS