CREATE OR ALTER PROCEDURE DBO.SPQ_CONFI_GRAL @JSON NVARCHAR(MAX)
WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX),@MODELO VARCHAR(100)   ,@METODO VARCHAR(100)
,@USUARIO VARCHAR(12)   ,@COMPANIA VARCHAR(2)      ,@IDSEDE      VARCHAR(5)
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@CIRUGIA BIT                   ,@PAQUETE BIT
      ,@CEMDOSIAUTOM BIT                  ,@LENTES BIT                    ,@MINVENTARIOS BIT
      ,@M_ATENCION VARCHAR(20)            ,@M_PROTOCOLO VARCHAR(20)       ,@REQ_PROVEED VARCHAR(20)
      ,@M_IMPUTABLE VARCHAR(20)           ,@REQSOLICITANTE VARCHAR(20)    ,@ESUNPROCEDIMIENTO VARCHAR(20)
      ,@IVA VARCHAR(20)                   ,@ESTADO VARCHAR(20)            ,@UTILIZADOEN VARCHAR(20)
      ,@GRUPO VARCHAR(20)                 ,@NOMGRUPO VARCHAR(20)          ,@FINALIDAD VARCHAR(2)
      ,@NFINALIDAD VARCHAR(20)            ,@PREFIJO VARCHAR(20)           ,@NOM_PREFIJO VARCHAR(20)
      ,@TIPOTRMA VARCHAR(20)              ,@CODRUBRO VARCHAR(20)          ,@TAREA VARCHAR(20)
      ,@IDAREA VARCHAR(20)                ,@VIGENCIA DECIMAL(14,2)        ,@NCOPIAS DECIMAL(14,2)
      ,@IDIMPUESTO VARCHAR(20)            ,@IDCLASE VARCHAR(20)          ,@IDPROVEEDORDEF VARCHAR(20)
      ,@IDTARIFA VARCHAR(5)               ,@DESCTARIFA VARCHAR(45)        ,@CODIFICACION VARCHAR(20)
      ,@REDONDEO VARCHAR(10)              ,@FACTORDINERO DECIMAL(14,2)    ,@FECHAINI DATETIME
      ,@FECHAFIN DATETIME                 ,@ITEM SMALLINT
      ,@TABLA VARCHAR(20)                 ,@CAMPO VARCHAR(20)             ,@CODIGO VARCHAR(20)
      ,@DESCRIPCION VARCHAR(1024)         ,@DATO1 VARCHAR(MAX)            ,@DATO2 VARCHAR(MAX)
      ,@VALOR1 BIT
BEGIN
   SELECT *
   INTO #JSON
   FROM OPENJSON(@json) WITH (
   MODELO VARCHAR(100) '$.MODELO'
   ,METODO VARCHAR(100) '$.METODO'
   ,USUARIO VARCHAR(12) '$.USUARIO'
   ,PARAMETROS NVARCHAR(MAX) AS JSON
   )

   SELECT   @MODELO = MODELO,@METODO = METODO
   ,@PARAMETROS = PARAMETROS,@USUARIO = USUARIO
   FROM #JSON

   IF @METODO='CRUD_PREFIJO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO,
         @CIRUGIA=CASE WHEN CIRUGIA='True' THEN 1 ELSE 0 END, @PAQUETE=CASE WHEN PAQUETE='True' THEN 1 ELSE 0 END,@CEMDOSIAUTOM=CASE WHEN CEMDOSIAUTOM='True' THEN 1 ELSE 0 END, @LENTES=CASE WHEN LENTES='True' THEN 1 ELSE 0 END,
         @MINVENTARIOS=CASE WHEN MINVENTARIOS='True' THEN 1 ELSE 0 END, @M_ATENCION=CASE WHEN M_ATENCION='True' THEN 'Si' ELSE 'No' END, @M_PROTOCOLO=CASE WHEN M_PROTOCOLO='True' THEN 'Si' ELSE 'No' END,
         @REQ_PROVEED=CASE WHEN REQ_PROVEED='True' THEN 'Si' ELSE 'No' END, @M_IMPUTABLE= CASE WHEN M_IMPUTABLE='True' THEN 'Si' ELSE 'No' END, @REQSOLICITANTE=CASE WHEN REQSOLICITANTE='True' THEN 'Si' ELSE 'No' END ,
         @ESUNPROCEDIMIENTO=CASE WHEN ESUNPROCEDIMIENTO='True' THEN 'Si' ELSE 'No' END , @IVA=CASE WHEN IVA='True' THEN 'Si' ELSE 'No' END, @ESTADO=ESTADO, @UTILIZADOEN=UTILIZADOEN, @GRUPO=GRUPO,
         @FINALIDAD=FINALIDAD, @PREFIJO=PREFIJO, @NOM_PREFIJO=NOM_PREFIJO, @TIPOTRMA=TIPOTRMA, @CODRUBRO=CODRUBRO, @TAREA=TAREA,@IDAREA=IDAREA, @VIGENCIA=VIGENCIA, @NCOPIAS=NCOPIAS,
         @IDIMPUESTO=IDIMPUESTO, @IDCLASE=IDCLASE,  @IDPROVEEDORDEF=IDPROVEEDORDEF    
      FROM   OPENJSON (@DATOS)
      WITH   (    
         PROCESO VARCHAR(20)            '$.PROCESO',
         CIRUGIA VARCHAR(20)            '$.CIRUGIA',
         PAQUETE VARCHAR(20)            '$.PAQUETE',
         CEMDOSIAUTOM VARCHAR(20)       '$.CEMDOSIAUTOM',
         LENTES VARCHAR(20)             '$.LENTES',
         MINVENTARIOS VARCHAR(20)       '$.MINVENTARIOS',
         M_ATENCION VARCHAR(20)         '$.M_ATENCION',
         M_PROTOCOLO VARCHAR(20)        '$.M_PROTOCOLO',
         REQ_PROVEED VARCHAR(20)        '$.REQ_PROVEED',
         M_IMPUTABLE VARCHAR(20)        '$.M_IMPUTABLE',
         REQSOLICITANTE VARCHAR(20)     '$.REQSOLICITANTE',
         ESUNPROCEDIMIENTO VARCHAR(20)  '$.ESUNPROCEDIMIENTO',
         IVA VARCHAR(20)                '$.IVA',
         ESTADO VARCHAR(20)             '$.ESTADO',
         UTILIZADOEN VARCHAR(20)        '$.UTILIZADOEN',
         GRUPO VARCHAR(20)              '$.GRUPO',
         FINALIDAD VARCHAR(2   )        '$.FINALIDAD',
         PREFIJO VARCHAR(20)            '$.PREFIJO',
         NOM_PREFIJO VARCHAR(20)        '$.NOM_PREFIJO',
         TIPOTRMA VARCHAR(20)           '$.TIPOTRMA',
         CODRUBRO VARCHAR(20)           '$.CODRUBRO',
         TAREA VARCHAR(20)              '$.TAREA',
         IDAREA VARCHAR(20)             '$.IDAREA',
         VIGENCIA DECIMAL(14,2)         '$.VIGENCIA',
         NCOPIAS DECIMAL(14,2)          '$.NCOPIAS',
         IDIMPUESTO VARCHAR(20)         '$.IDIMPUESTO',
         IDCLASE VARCHAR(20)            '$.IDCLASE',
         IDPROVEEDORDEF VARCHAR(20)     '$.IDPROVEEDORDEF'    
      )
      IF @PROCESO='Nuevo'
      BEGIN
         IF NOT EXISTS(SELECT  * FROM PRE WHERE PREFIJO=@PREFIJO)
         BEGIN
            BEGIN TRY           
               INSERT INTO PRE(PREFIJO,NOM_PREFIJO,CIRUGIA,MANEJAPQ,CEMDOSIAUTOM,LENTES,MINVENTARIOS,M_ATENCION,M_PROTOCOLO,REQ_PROVEED,M_IMPUTABLE,REQSOLICITANTE,ESUNPROCEDIMIENTO,IVA,ESTADO,UTILIZADOEN,
                              GRUPO,FINALIDAD,TIPOTRMA,CODRUBRO,TAREA,IDAREA,VIGENCIA,NCOPIAS,IDIMPUESTO,IDCLASE,IDPROVEEDORDEF)
               SELECT  @PREFIJO, @NOM_PREFIJO,@CIRUGIA, @PAQUETE, @CEMDOSIAUTOM, @LENTES, @MINVENTARIOS, @M_ATENCION, @M_PROTOCOLO, @REQ_PROVEED, @M_IMPUTABLE, @REQSOLICITANTE, @ESUNPROCEDIMIENTO, @IVA, @ESTADO, 
                               @UTILIZADOEN, @GRUPO GRUPO, @FINALIDAD, @TIPOTRMA,  @CODRUBRO,  @TAREA,@IDAREA, @VIGENCIA, @NCOPIAS, @IDIMPUESTO,  @IDCLASE,  @IDPROVEEDORDEF            
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'ya existe un prefijo con este codigo, Verifique e intente de nuevo'
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM PRE WHERE PREFIJO=@PREFIJO)
         BEGIN
            BEGIN TRY           
                  UPDATE PRE SET CIRUGIA=@CIRUGIA,MANEJAPQ=@PAQUETE,CEMDOSIAUTOM=@CEMDOSIAUTOM,LENTES=@LENTES,MINVENTARIOS=@MINVENTARIOS,M_ATENCION=@M_ATENCION,M_PROTOCOLO=@M_PROTOCOLO,REQ_PROVEED=@REQ_PROVEED,
                                 M_IMPUTABLE=@M_IMPUTABLE,REQSOLICITANTE=@REQSOLICITANTE,ESUNPROCEDIMIENTO=@ESUNPROCEDIMIENTO,IVA=@IVA,ESTADO=@ESTADO,UTILIZADOEN=@UTILIZADOEN,GRUPO=@GRUPO,FINALIDAD=@FINALIDAD,
                                 NOM_PREFIJO=@NOM_PREFIJO,TIPOTRMA=@TIPOTRMA,CODRUBRO=@CODRUBRO,TAREA=@TAREA,IDAREA=@IDAREA,VIGENCIA=@VIGENCIA,NCOPIAS=@NCOPIAS,IDIMPUESTO=@IDIMPUESTO,IDCLASE=@IDCLASE,IDPROVEEDORDEF=@IDPROVEEDORDEF
                  WHERE PREFIJO=@PREFIJO
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Prefijo no encontrado, Verique e intente de nuevo'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='CRUD_TARIFA'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO,@IDTARIFA=IDTARIFA,@DESCTARIFA=DESCTARIFA,@CODIFICACION=CODIFICACION      
      FROM   OPENJSON (@DATOS)
      WITH   (  
      PROCESO  VARCHAR(20)   '$.PROCESO',
      IDTARIFA  VARCHAR(20)   '$.IDTARIFA',
      DESCTARIFA  VARCHAR(20)   '$.DESCTARIFA',
      CODIFICACION  VARCHAR(20)   '$.CODIFICACION.CODIFICACION'
      )
      IF @PROCESO='Nuevo'
      BEGIN
         IF NOT EXISTS(SELECT * FROM TAR WHERE IDTARIFA=@IDTARIFA)
         BEGIN
            BEGIN TRY     
               PRINT 'VOY A INSERTAR'
               INSERT INTO TAR(IDTARIFA,DESCTARIFA,CODIFICACION)
               SELECT @IDTARIFA,@DESCTARIFA,@CODIFICACION               
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Ya Existe una tarifa con este codigo, Verifique e intente de nuevo'
         END
      END
      IF @PROCESO='Edita'
      BEGIN
         IF EXISTS(SELECT * FROM TAR WHERE IDTARIFA=@IDTARIFA)
         BEGIN
            UPDATE TAR SET DESCTARIFA=@DESCTARIFA, CODIFICACION=@CODIFICACION WHERE IDTARIFA=@IDTARIFA
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Tarifa no encontrada, Verfique e intente de nuevo'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='CRUD_TARF'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )        
      SELECT @PROCESO=PROCESO,@IDTARIFA=IDTARIFA,@FACTORDINERO=CASE WHEN ISNUMERIC(FACTORDINERO)=1 THEN CONVERT(decimal(14,2),FACTORDINERO) ELSE 0 END ,
      @ITEM=CONVERT(SMALLINT,COALESCE(ITEM,0)),@REDONDEO=REDONDEO,@FECHAINI=CAST(CONVERT(VARCHAR,CAST(LEFT(FECHAINI,10) AS date),103)+RIGHT(FECHAINI,9) AS DATETIME),
      @FECHAFIN=CAST(CONVERT(VARCHAR,CAST(LEFT(FECHAFIN,10) AS date),103)+RIGHT(FECHAFIN,9) AS DATETIME)
      FROM   OPENJSON (@DATOS)
      WITH   ( 
      PROCESO  VARCHAR(20)   '$.PROCESO',
      IDTARIFA  VARCHAR(20)   '$.IDTARIFA',
      FACTORDINERO  VARCHAR(20)   '$.FACTORDINERO',
      ITEM  VARCHAR(20)   '$.ITEM',
      REDONDEO  VARCHAR(20)   '$.REDONDEO',
      FECHAINI  VARCHAR(20)   '$.FECHAINI',
      FECHAFIN  VARCHAR(20)   '$.FECHAFIN'
      )    
      IF @FACTORDINERO<=0
      BEGIN
         SELECT 'KO'KO,'Factor de dinero no Valido debe ir separado por (.) Ej: 1.99'
         RETURN
      END
      IF @PROCESO='Nuevo'
      BEGIN
         IF EXISTS(SELECT * FROM TAR WHERE IDTARIFA=@IDTARIFA)
         BEGIN
            IF NOT EXISTS(SELECT * FROM TARF WHERE IDTARIFA=@IDTARIFA AND (FECHAINI<@FECHAINI OR FECHAFIN>@FECHAFIN))
            BEGIN
               SELECT @ITEM=MAX(ITEM) FROM TARF WHERE IDTARIFA=@IDTARIFA
               IF COALESCE(@ITEM,0)=0
               BEGIN
                  SELECT @ITEM=1
               END
               ELSE
               BEGIN
                  SELECT @ITEM=@ITEM+1
               END
               BEGIN TRY           
                  INSERT INTO TARF(IDTARIFA,ITEM,FACTORDINERO,REDONDEO,FECHAINI,FECHAFIN)
                  SELECT @IDTARIFA,@ITEM,@FACTORDINERO,@REDONDEO,@FECHAINI,@FECHAFIN
               END TRY
               BEGIN CATCH
                       INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
               END CATCH
            END
            ELSE
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'Inconsistencia en las fechas, Verifique que no existan vigencias mayores a fecha inicial o  mayores a la fecha final'
            END
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se encontro la Tarifa'+COALESCE(@IDTARIFA,'NADA')+'  en el maestro de tarifas, Verifique e intetne de nuevo'
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM TARF WHERE IDTARIFA=@IDTARIFA AND ITEM=@ITEM)
         BEGIN
            IF NOT EXISTS(SELECT * FROM TARF WHERE IDTARIFA=@IDTARIFA AND (FECHAINI<@FECHAINI OR FECHAFIN>@FECHAFIN))
            BEGIN
               UPDATE TARF SET FACTORDINERO=@FACTORDINERO,REDONDEO=@REDONDEO, FECHAINI=@FECHAINI,FECHAFIN=@FECHAFIN  WHERE IDTARIFA=@IDTARIFA AND ITEM=@ITEM
            END
            ELSE
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'Inconsistencia en las fechas, Verifique que no existan vigencias mayores a fecha inicial o  mayores a la fecha final'            
            END
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Tarifa Asociada a este item'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='CRUD_TGENDIS'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )           
      SELECT @PROCESO=PROCESO, @TABLA=TABLA, @CAMPO=CAMPO,  @CODIGO=CODIGO,  @DESCRIPCION=DESCRIPCION,  @DATO1=DATO1,  @DATO2=DATO2,@VALOR1=CASE WHEN VALOR1='True' THEN 1 ELSE 0 END
      FROM   OPENJSON (@DATOS)
      WITH   (
         PROCESO VARCHAR(20)       '$.PROCESO',
         TABLA VARCHAR(20)         '$.TABLA',
         CAMPO VARCHAR(20)         '$.CAMPO',
         CODIGO VARCHAR(20)        '$.CODIGO',
         DESCRIPCION VARCHAR(1024) '$.DESCRIPCION',
         VALOR1  VARCHAR(20)       '$.VALOR1',
         DATO1 VARCHAR(MAX)        '$.DATO1',
         DATO2 VARCHAR(MAX)        '$.DATO2'      
      )  
      IF @PROCESO='Nuevo'
      BEGIN
         IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA=@TABLA AND CAMPO=@CAMPO AND CODIGO=@CODIGO)
         BEGIN
            BEGIN TRY           
               INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION,VALOR1,DATO1,DATO2)
               SELECT @TABLA,@CAMPO,@CODIGO,@DESCRIPCION,@VALOR1,@DATO1,@DATO2
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Código del Distribuidor ya existe. Verifique e intente de nuevo'
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA=@TABLA AND CAMPO=@CAMPO AND CODIGO=@CODIGO)
         BEGIN
            UPDATE TGEN SET DATO1=@DATO1,@VALOR1=@VALOR1,DATO2=@DATO2 WHERE TABLA=@TABLA AND CAMPO=@CAMPO AND CODIGO=@CODIGO
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se encontro código del Distribuidor ya existe. Verifique e intente de nuevo'            
         END
      END
   END  
END