CREATE OR ALTER PROCEDURE DBO.SPQ_KPPTCRO_PE @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@IDTERCERO VARCHAR(20)          ,@NIT VARCHAR(20)
      ,@RAZONSOCIAL VARCHAR(120)          ,@IDPLAN VARCHAR(6)              ,@DESCPLAN VARCHAR(120)
      ,@ANIO VARCHAR(5)                   ,@MES SMALLINT                   ,@VALOR DECIMAL(14,2)
      ,@IDSERVICIO VARCHAR(20)            ,@IDAUT VARCHAR(20)              ,@NO_ITEM SMALLINT
      ,@PROTOCOLO BIT                     ,@NOADMISION VARCHAR(20)         ,@IDPPTCRO INT
      ,@VLRPAQ DECIMAL(14,2)              ,@PAQUETE VARCHAR(20)            ,@DPR VARCHAR(20)
      ,@TIPOFAC VARCHAR(20)               ,@FECHAFACT DATETIME
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='CRUD_KPPTCRO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO,@IDPPTCRO=IDPPTCRO, @IDTERCERO=IDTERCERO,@IDPLAN=IDPLAN, @ANIO=ANIO, @MES=MES,@VALOR=VALOR,@IDSERVICIO=IDSERVICIO
      FROM   OPENJSON (@DATOS)
      WITH   (   
      PROCESO VARCHAR(20)   '$.PROCESO',
      IDPPTCRO  INT         '$.IDPPTCRO',
      IDTERCERO VARCHAR(20) '$.IDTERCERO',
      IDPLAN VARCHAR(6)     '$.IDPLAN',
      ANIO VARCHAR(5)       '$.ANIO',
      MES SMALLINT          '$.MES',
      VALOR DECIMAL(14,2)   '$.VALOR',  
      IDSERVICIO  VARCHAR(20)   '$.IDSERVICIO'
      )    
      IF @PROCESO='Nuevo'
      BEGIN
         IF NOT EXISTS(SELECT * FROM PPTCRO WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND ANIO=@ANIO AND MES=@MES)
         BEGIN
            IF COALESCE(@IDSERVICIO,'')=''
            BEGIN
               SELECT @IDSERVICIO=IDSERVICIO FROM PLN WHERE IDPLAN=@IDPLAN
            END
            BEGIN TRY           
               INSERT INTO PPTCRO(IDTERCERO, IDPLAN, ANIO, MES, VALOR, IDSERVICIO)
               SELECT @IDTERCERO,@IDPLAN,@ANIO,@MES,@VALOR,@IDSERVICIO
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Ya existe un Periodo para este Tercero y este paquete, Verifique e intente de nuevo'
         END
      END
      IF @PROCESO='Edita'
      BEGIN
         IF EXISTS(SELECT * FROM PPTCRO WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND ANIO=@ANIO AND MES=@MES)
         BEGIN
            UPDATE PPTCRO SET VALOR=@VALOR,IDSERVICIO=@IDSERVICIO,IDTERCERO=@IDTERCERO,IDPLAN=@IDPLAN,ANIO=@ANIO,MES=@MES WHERE IDPPTCRO=@IDPPTCRO
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END 
   IF @METODO='ADDDEL_PROTOCOLO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
     
      SELECT @IDAUT=IDAUT,@NO_ITEM=NO_ITEM,@PROTOCOLO=PROTOCOLO       
      FROM   OPENJSON (@DATOS)
      WITH   (      
      IDAUT  VARCHAR(20)   '$.IDAUT',
      NO_ITEM  SMALLINT   '$.NO_ITEM',
      PROTOCOLO  BIT   '$.PROTOCOLO'
      ) 
      IF EXISTS(SELECT * FROM AUTD WHERE IDAUT=@IDAUT AND NO_ITEM=@NO_ITEM AND FACTURADA=0)
      BEGIN
         UPDATE AUTD SET PROTOCOLO=1-@PROTOCOLO WHERE IDAUT=@IDAUT AND NO_ITEM=@NO_ITEM 
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro el item  o ya se encuentra facturado, verique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN      
   END  
   IF @METODO='FACTURAR_CRONICO'     
   BEGIN         
      SELECT @NOADMISION=NOADMISION        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         NOADMISION  VARCHAR(20)   '$.CONSECUTIVO'
      )
           
      SELECT @VLRPAQ=PPTCRO.VALOR,@PAQUETE=PPTCRO.IDSERVICIO  
      FROM HADM INNER JOIN PPTCRO ON HADM.IDTERCERO=PPTCRO.IDTERCERO AND HADM.IDPLAN=PPTCRO.IDPLAN 
      WHERE HADM.NOADMISION=@NOADMISION
      AND YEAR(HADM.FECHA)=PPTCRO.ANIO
      AND MONTH(HADM.FECHA)=PPTCRO.MES

      IF NOT EXISTS(SELECT * FROM SER WHERE IDSERVICIO=@PAQUETE)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'El paquete asociado no existe en el Maestro de Servicios, Verique e intente de nuevo'
      END
      IF COALESCE(@VLRPAQ,0)<=0
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Valor del Paquete no Puede ser menor o igual a cero(0)'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      PRINT 'Valido sede'
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Sede: '+@IDSEDE+' No habilitada para emitir Facturas, Comuniquese con el Administrador del Sistema'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN

      END
      BEGIN TRY           
           EXEC SPK_FACTURACE_PERU_HADM_PAQ @NOADMISION,@DPR,@COMPANIA,@IDSEDE, @USUARIO,@FECHAFACT,@TIPOFAC, @IDTERCERO               
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,N_FACTURA  FROM HADM WHERE NOADMISION=@NOADMISION          
      RETURN 
   END  
END