IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='MANCCOSTO_CITAS_WEB')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'MANCCOSTO_CITAS_WEB','Maneja centro de costo en Agendamiento Web SI|NO','Alfanumerica',''
END