CREATE OR ALTER PROCEDURE DBO.SPQ_DEVOLU_PROVEEDOR
@JSON  NVARCHAR(MAX) 
WITH
ENCRYPTION
AS
DECLARE  @PARAMETROS   NVARCHAR(MAX) ,@MODELO           VARCHAR(100) ,@METODO           VARCHAR(100)  ,@USUARIO        VARCHAR(12),
			@GRUPO        VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254) ,@IDSEDE             VARCHAR(5)    ,@USUNOMBRE     VARCHAR(100), @SEDE VARCHAR(5),
			@FECHA        VARCHAR(10)   ,@IDEMEDICA        VARCHAR(4)	,@FECHA1           DATETIME		,@SQL            VARCHAR(MAX),
			@CODCAJERO		VARCHAR(20),@COMPANIA		VARCHAR(10)	,@IDAFILIADO VARCHAR(20)	,@IDMEDICO	VARCHAR(20)	,@FECHAINI DATE
			,@OBSERVACION	VARCHAR(MAX)	,@IDAUT	VARCHAR(20)	,@NO_ITEM INT	,@PROCEDENCIA VARCHAR(20)	,@VALOR DECIMAL(14,2)	,@DIA VARCHAR(10)
			,@CONSECUTIVO VARCHAR(20)	,@MODALIDAD VARCHAR(20)	,@IDSERVICIO VARCHAR(20)	,@CONSECUTIVOS NVARCHAR(MAX)	,@dataPRE NVARCHAR(MAX)
			,@FECHA_MOV DATETIME, @HORA VARCHAR(5)	,@FECHAI    VARCHAR(10)	,@CONSECUTIVOCIT VARCHAR(20)	,@IDTERCERO VARCHAR(20)	,@IDPLAN VARCHAR(20)
			,@FILTRO_REG BIT, @FECHA_FILTRO DATE	,@CNS VARCHAR(20), @dataIMOV_sel			NVARCHAR(MAX)	,@PROCESO varchar(20), @CNSRPDX varchar(20)
			,@NVOCONSEC varchar(20)	,@CNSITRA VARCHAR(20)	,@IDBODEGA VARCHAR(20), @CNSFCOM VARCHAR(20), @NODOCUMENTO VARCHAR(20), @IDSOLICITA VARCHAR(20)
			,@CNSCXP VARCHAR(20), @ESTADO VARCHAR(20), @CONTA INT, @SALDOCXP DECIMAL(14,2), @NROCOMPROBANTE VARCHAR(20), @CONFIRCONTA INT, @CNSMOV VARCHAR(20)
			,@datoIMOVH NVARCHAR(MAX)	,@DEVTOTAL BIT	,@CCOSTO VARCHAR(20)	,@IDAREA VARCHAR(20)	,@TIPODOCU VARCHAR(20)	,@IDARTICULO VARCHAR(20)
			,@IDARTICULO_REAL VARCHAR(20)	, @EXISTENCIA DECIMAL(18,6), @CANTIDAD INT, @PCOSTO VARCHAR(20), @NOLOTE VARCHAR(20) , @NOLOTEPEDIDO VARCHAR(20)
BEGIN 
	SET LANGUAGE Spanish;  
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIOpl,   --PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @USUNOMBRE = NOMBRE FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME, @COMPANIA = COMPANIA, @CODCAJERO= CODCAJERO FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @IDSEDE = IDSEDE, @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	PRINT '@USUARIO='+@USUARIO


	IF @METODO = 'GUARDA_REGISTRO'
	BEGIN
		SELECT @dataIMOV_sel= dataIMOV_sel 
		FROM OPENJSON(@PARAMETROS)
		WITH( dataIMOV_sel			NVARCHAR(MAX)		AS JSON )

		SELECT @PROCESO =UPPER( JSON_VALUE(@dataIMOV_sel,'$.PROCESO'))
				
		SELECT * INTO #dataIMOV_sel FROM  OPENJSON(@dataIMOV_sel)
		WITH (
		PROCESO			VARCHAR(20)		'$.PROCESO'		,OBSERVACION			VARCHAR(200)			'$.OBSERVACION'
		,CNSITRA			VARCHAR(20)			'$.CNSITRA'			,IDBODEGA				VARCHAR(20)					'$.IDBODEGA'
		,TIPODOCU			VARCHAR(20)					'$.TIPODOCU'		,IDTIPOMOV			VARCHAR(20)		'$.IDTIPOMOV'
		,IDTERCERO		VARCHAR(20)			'$.IDTERCERO'	,FECHA_MOV_1		VARCHAR(10)			'$.FECHA_MOV_1'
		,HORA_MOV_1			VARCHAR(5)			'$.HORA_MOV_1'		,NODOCUMENTO		VARCHAR(200)		'$.NODOCUMENTO'
		,IDSOLICITA			VARCHAR(20)			'$.IDSOLICITA', CNSMOV			VARCHAR(20)			'$.CNSMOV'
		,DEVTOTAL			BIT				'$.DEVTOTAL')

		SELECT @CNSITRA = CNSITRA, @IDSOLICITA = IDSOLICITA, @OBSERVACION = OBSERVACION, @CNSMOV  = CNSMOV, @DEVTOTAL = DEVTOTAL  FROM #dataIMOV_sel

		IF @PROCESO = 'NUEVO'
		BEGIN
			SELECT @FECHAI= REPLACE(FECHA_MOV_1,'-',''), @HORA = HORA_MOV_1 FROM #dataIMOV_sel
			SELECT @FECHA_MOV = CONVERT(DATETIME,CONCAT(@FECHAI,' ',@HORA))
		END
		PRINT 'CAPTURANDO DATOS'
		SELECT @IDBODEGA=IDBODEGA,@CNSFCOM=COALESCE(CNSFCOM,''),@IDTERCERO=IDTERCERO,@NODOCUMENTO=NODOCUMENTO 
		FROM IMOV WHERE CNSMOV=@CNSITRA

		IF @PROCESO = 'EDITAR' AND  EXISTS (SELECT * FROM IMOV WHERE CNSMOV = @CNSMOV AND COALESCE(IMOV.ESTADO,'0') <> 0 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra Devuleto'
		END
		IF @CNSFCOM=''
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'NO EXISTE LA ORDEN DE COMPRA'
		END
		IF @CNSFCOM<>''
		BEGIN
			SELECT @CNSCXP=CNSFCXP,@ESTADO=COALESCE(ESTADO,'A'),@CONTA=COALESCE(CONTABILIZADA,0),@SALDOCXP=SALDO,
					@NROCOMPROBANTE=NROCOMPROBANTE
			FROM   FCXP WHERE CNSFCOM=@CNSFCOM AND IDTERCERO=@IDTERCERO AND NOREFERENCIA=@NODOCUMENTO
			IF @ESTADO='A'
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'LA CXP: '+@CNSCXP+' SE ENCUENTRA ANULADA O NO EXISTE'  
			END
			IF @CONTA=0
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'LA CXP: '+@CNSCXP+' NO SE ENCUENTRA CONTABILZADA'   
			END
			IF @SALDOCXP<=0
			BEGIN
				INSERT INTO @TBLERRORES(ERROR) SELECT 'LA CXP: '+@CNSCXP+' NO SE TIENE SALDO DISPONIBLE'    
			END
			SELECT @CONFIRCONTA=CASE WHEN COALESCE(ANULADO,0)=1 THEN 3 ELSE ESTADO END FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE
			IF @CONFIRCONTA <> 2
			BEGIN
				IF @CONFIRCONTA=3
				BEGIN
   	  				INSERT INTO @TBLERRORES(ERROR) SELECT 'EL COMPROBANTE LA CXP: '+@CNSCXP+' SE ENCUENTRA ANULADO EN CONTABILIDAD'   
				END
				ELSE
				BEGIN
   	  				INSERT INTO @TBLERRORES(ERROR) SELECT 'EL COMPROBANTE LA CXP: '+@CNSCXP+' NO SE ENCUENTRA CONFIRMADO EN CONTABILIDAD'
				END
			END
		END
	
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
			IF @PROCESO = 'NUEVO'
			BEGIN
				SELECT @NVOCONSEC = NULL
				EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = '@MOV', @LONGITUD = 8, @NVOCONSEC = @NVOCONSEC OUTPUT

				INSERT INTO IMOV (CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, ESTADO, OBSERVACION, IDAREA, PROCEDENCIA, CNSITRA,TIPODOCU,TIPO_DOC_COMPRA, DEVTOTAL)
				SELECT @NVOCONSEC, IDBODEGA, DBO.FNK_VALORVARIABLE('IDINVDEVPROVEEDOR'), NODOCUMENTO, DBO.FNK_GETDATE(), CCOSTO, @IDSOLICITA, IDTERCERO, 0
				, CONCAT(@OBSERVACION + ' Factura Nro. ' + NODOCUMENTO, ', Proveedor: ' + IDTERCERO ), IDAREA, 'INV', CNSMOV, TIPODOCU, 'N', @DEVTOTAL
				FROM IMOV WHERE IMOV.CNSMOV = @CNSITRA
			END
			IF @PROCESO = 'EDITAR'
			BEGIN
				SELECT @NODOCUMENTO = NODOCUMENTO, @CCOSTO = CCOSTO, @IDTERCERO = IDTERCERO, @IDAREA = IDAREA, @TIPODOCU = TIPODOCU    FROM IMOV WHERE CNSMOV = @CNSITRA
				UPDATE IMOV SET  NODOCUMENTO = @NODOCUMENTO, FECHAMOV = DBO.FNK_GETDATE() , CCOSTO = @CCOSTO, IDSOLICITA = @IDSOLICITA, IDTERCERO = @IDTERCERO
				,  OBSERVACION = CONCAT(@OBSERVACION + ' Factura Nro. ' + @NODOCUMENTO, ', Proveedor: ' + @IDTERCERO ), IDAREA = @IDAREA,  CNSITRA = @CNSITRA, TIPODOCU = @TIPODOCU, DEVTOTAL = @DEVTOTAL
				FROM IMOV WHERE CNSMOV = @CNSMOV
			END
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
	IF @METODO = 'DEVOLUCION_TOTAL'
	BEGIN
		SELECT @CNSMOV = CNSMOV 
		FROM OPENJSON(@PARAMETROS)
		WITH( CNSMOV	VARCHAR(20)		'$.CNSMOV')

		SELECT @IDBODEGA = IDBODEGA, @CNSITRA = CNSITRA FROM IMOV WHERE CNSMOV = @CNSMOV
		
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				INSERT INTO IMOVH (CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO, NOLOTE, NOLOTEPEDIDO, FECHAVENCE, ESTADO,   
								IDARTICULOTF, CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, USUARIOCONF, FECHACONF, PRIEXI,     
								FECHAREPOSI, IDARTICULOORI, CANTIDADORI, TIENECAMBIO, DETALLE, CANT_EN_ACTIVOS, ENCXP, PIVA, VLRIVA, PDTO, 
								VLRDTO, CNSHTX, COTIZADO, IDIMPUESTO, IDCLASE, ITFC, CNSITFC, CUENTA_FIMPDV, IDITAR, CODCUM, CAMBIADO,     
								PCOSTOANTESMOD, USUARIOCAMBIO, IDFABRICANTE, CUENTADB, CUENTACR, IDSERVICIO, VLRIMPCONSUMO, NOPRESTACION,  
								RENFER, USUARIOR, CANTREP, DILUYENTE)                                                                      
				SELECT @CNSMOV, IMOVH.IDARTICULO, IEXI.EXISLOTE, IEXI.EXISLOTE, CANTIDAD, IMOVH.PCOSTO, IMOVH.NOLOTE, IMOVH.NOLOTEPEDIDO, IMOVH.FECHAVENCE, 0,      -- storres         
					IDARTICULOTF, CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, USUARIO, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,  
					CANTIDADORI, TIENECAMBIO, IMOVH.DETALLE, CANT_EN_ACTIVOS, ENCXP, PIVA, VLRIVA, PDTO, VLRDTO, CNSHTX, COTIZADO, IDIMPUESTO, IDCLASE, ITFC, 
					CNSITFC, CUENTA_FIMPDV, IDITAR, CODCUM, CAMBIADO, PCOSTOANTESMOD, USUARIOCAMBIO, IDFABRICANTE, CUENTADB, CUENTACR, IDSERVICIO,    
					VLRIMPCONSUMO, NOPRESTACION, RENFER, USUARIOR, CANTREP, DILUYENTE                                                                 
				FROM IMOVH INNER JOIN IEXI ON IEXI.IDARTICULO=IMOVH.IDARTICULO AND IMOVH.NOLOTE=IEXI.NOLOTE AND IEXI.IDBODEGA= @IDBODEGA
				WHERE IMOVH.CNSMOV = @CNSITRA AND  NOT EXISTS (SELECT * FROM IMOVH IM WHERE IM.CNSMOV = @CNSMOV AND IM.IDARTICULO = IMOVH.IDARTICULO )
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK , (SELECT COUNT(*) FROM IMOVH WHERE CNSMOV = @CNSMOV ) DETALLE
		END 
	END
	IF @METODO = 'DESHACER_DEVOLUCION_TOTAL'
	BEGIN
		SELECT @CNSMOV = CNSMOV 
		FROM OPENJSON(@PARAMETROS)
		WITH( CNSMOV	VARCHAR(20)		'$.CNSMOV')

		SELECT @IDBODEGA = IDBODEGA, @CNSITRA = CNSITRA FROM IMOV WHERE CNSMOV = @CNSMOV
		
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				DELETE IMOVH WHERE CNSMOV = @CNSMOV
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK, (SELECT COUNT(*) FROM IMOVH WHERE CNSMOV = @CNSMOV ) DETALLE
		END 
	END
	IF @METODO = 'GUARDA_REGISTRO_IMOVH'
	BEGIN
		SELECT @datoIMOVH = datoIMOVH 
		FROM OPENJSON(@PARAMETROS)
		WITH( datoIMOVH			NVARCHAR(MAX)		AS JSON )

		SELECT @PROCESO =UPPER( JSON_VALUE(@datoIMOVH,'$.PROCESO'))
				
		SELECT * INTO #datoIMOVH FROM  OPENJSON(@datoIMOVH)
		WITH (
		PROCESO			VARCHAR(20)		'$.PROCESO'		,CNSMOV			VARCHAR(200)			'$.CNSMOV'
		,CNSITRA			VARCHAR(20)			'$.CNSITRA'			,IDARTICULO				VARCHAR(20)					'$.IDARTICULO'
		,EXISTENCIA			INT				'$.EXISTENCIA'		,PCOSTO			DECIMAL(14,2)		'$.PCOSTO'
		,NOLOTE			VARCHAR(20)			'$.NOLOTE'			,NOLOTEPEDIDO		VARCHAR(20)			'$.NOLOTEPEDIDO'
		,FECHAVENCE			DATE			'$.FECHAVENCE'		,CODCUM		VARCHAR(200)		'$.CODCUM'
		,IDFABRICANTE			VARCHAR(20)			'$.IDFABRICANTE' ,CANTIDAD		INT		'$.CANTIDAD'
		,IDARTICULO_REAL VARCHAR(20)			'$.IDARTICULO_REAL')

		SELECT @CNSMOV = CNSMOV, @IDARTICULO = IDARTICULO, @IDARTICULO_REAL = IDARTICULO_REAL  FROM #datoIMOVH
	
		IF @PROCESO = 'NUEVO' AND EXISTS (SELECT * FROM IMOVH WHERE CNSMOV = @CNSMOV AND IDARTICULO = @IDARTICULO )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe el articulo, editelo.'
		END
		IF @PROCESO = 'EDITAR' AND EXISTS (SELECT * FROM IMOVH WHERE CNSMOV = @CNSMOV AND IDARTICULO = @IDARTICULO AND IDARTICULO <> @IDARTICULO_REAL )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Ya existe el articulo, editelo.'
		END
		
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				IF @PROCESO = 'NUEVO'
				BEGIN
					INSERT INTO IMOVH (CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO, NOLOTE, NOLOTEPEDIDO, FECHAVENCE, ESTADO)
					SELECT #datoIMOVH.CNSMOV, #datoIMOVH.IDARTICULO, #datoIMOVH.EXISTENCIA, #datoIMOVH.CANTIDAD, #datoIMOVH.CANTIDAD, IMOVH.PCOSTO, IMOVH.NOLOTE, IMOVH.NOLOTEPEDIDO, IMOVH.FECHAVENCE, 0
					FROM IMOVH, #datoIMOVH WHERE IMOVH.CNSMOV = #datoIMOVH.CNSITRA AND IMOVH.IDARTICULO = #datoIMOVH.IDARTICULO 
				END
				IF @PROCESO = 'EDITAR'
				BEGIN
					SELECT @IDARTICULO = IDARTICULO, @EXISTENCIA =EXISTENCIA ,@CANTIDAD = CANTIDAD,  @PCOSTO = PCOSTO, @NOLOTE = NOLOTE, @NOLOTEPEDIDO = NOLOTEPEDIDO  FROM #datoIMOVH
					UPDATE IMOVH SET IDARTICULO = @IDARTICULO, EXISTENCIA = @EXISTENCIA, CANTIDAD = @CANTIDAD, CANTPEDIDA = @CANTIDAD, PCOSTO = @PCOSTO, NOLOTE = @NOLOTE
							, NOLOTEPEDIDO = @NOLOTEPEDIDO, IMOVH.FECHAVENCE = #datoIMOVH.FECHAVENCE
					FROM IMOVH , #datoIMOVH WHERE IMOVH.CNSMOV = @CNSMOV  AND IMOVH.IDARTICULO = @IDARTICULO_REAL
				END
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
	IF @METODO = 'CONFIRMAR_DEVOLUCION'
	BEGIN
		SELECT @CNSMOV = CNSMOV 
		FROM OPENJSON(@PARAMETROS)
		WITH( CNSMOV		VARCHAR(20)		'$.CNSMOV'	 )

		SELECT @IDBODEGA = IDBODEGA FROM IMOV WHERE CNSMOV = @CNSMOV
		
		IF NOT EXISTS (SELECT * FROM IMOVH WHERE CNSMOV = @CNSMOV)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'No Ha Ingresado Ningún Articulo Para Devolución'
		END
		IF EXISTS (SELECT * FROM IMOV WHERE CNSMOV = @CNSMOV AND COALESCE(IMOV.ESTADO,'0') <> 0 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El Movimiento de Inventario No esta Preparado para Confirmar Revise'
		END
		IF EXISTS ( SELECT CASE WHEN B.EXISLOTE < A.CANTIDAD THEN 'ERROR' ELSE 'OK' END RESULTADO,'EXISTENCIAS INSUFICIENTES',
			A.IDARTICULO, IART.DESCRIPCION, A.NOLOTEPEDIDO, A.CANTIDAD, A.EXISTENCIA, B.EXISLOTE-A.CANTIDAD
			FROM IMOVH A 
			INNER JOIN IEXI B ON A.IDARTICULO=B.IDARTICULO AND A.NOLOTE=B.NOLOTE
			INNER JOIN IART ON A.IDARTICULO=IART.IDARTICULO            
			WHERE B.IDBODEGA= @IDBODEGA AND A.CNSMOV= @CNSMOV AND B.EXISLOTE < A.CANTIDAD )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'Existencias Insuficientes, Revise'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				DELETE ISAL WHERE CNSMOV= @CNSMOV
				INSERT INTO ISAL(CNSMOV,NOLOTE,IDARTICULO,CANTIDAD,FECHA,NOLOTEPEDIDO,FECHAVENCE,PCOSTO,IDARTICULO_IMOVH)
				SELECT CNSMOV,NOLOTE,IDARTICULO,CANTIDAD,GETDATE(),NOLOTEPEDIDO,FECHAVENCE,PCOSTO,IDARTICULO FROM IMOVH   
				WHERE CNSMOV= @CNSMOV

			  EXEC SPK_CONFIRMARSALIDAS @IDBODEGA, @CNSMOV, @USUARIO, @COMPANIA, @IDSEDE

			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
	IF @METODO = 'ELIMINAR_REGISTRO'
	BEGIN
		SELECT @CNSMOV = CNSMOV , @IDARTICULO = IDARTICULO
		FROM OPENJSON(@PARAMETROS)
		WITH( CNSMOV	VARCHAR(20)		'$.CNSMOV', IDARTICULO	VARCHAR(20)		'$.IDARTICULO')

		IF EXISTS (SELECT * FROM IMOV WHERE CNSMOV = @CNSMOV AND COALESCE(IMOV.ESTADO,'0') <> 0 )
		BEGIN
			INSERT INTO @TBLERRORES(ERROR) SELECT 'El registro ya se encuentra Devuleto'
		END
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				DELETE FROM IMOVH WHERE CNSMOV = @CNSMOV AND IDARTICULO = @IDARTICULO
			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
END


