CREATE OR ALTER PROCEDURE DBO.SPQ_VALIDAR_MAESTROS @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@TABLA VARCHAR(50)                 ,@CAMPO  VARCHAR(20)             ,@VALOR VARCHAR(100)
      ,@SQL VARCHAR(MAX)
      DECLARE @RESUL TABLE (OK VARCHAR(4),ERROR VARCHAR(100))
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='VALIDAR'     
   BEGIN         
      SELECT @TABLA=TABLA,@CAMPO=CAMPO,@VALOR=LTRIM(RTRIM(VALOR))
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      TABLA  VARCHAR(50)   '$.TABLA',
      CAMPO  VARCHAR(50)   '$.CAMPO',
      VALOR  VARCHAR(100)   '$.VALOR'
      )
      SET @SQL='IF NOT EXISTS(SELECT * FROM '+@TABLA+' WHERE '+@CAMPO+'='''+@VALOR+''') BEGIN SELECT ''KO'' OK, ''Dato no existe en el maestro'' ERROR END ELSE BEGIN SELECT ''OK'' OK END'
      PRINT @SQL
      INSERT INTO  @RESUL
      EXEC(@SQL)
      SELECT * FROM @RESUL
      RETURN
   END  
END