SELECT PRE.NOM_PREFIJO, CIT.CONSECUTIVO, AUT.IDAUT, AUT.FECHA,  AFI.NOMBREAFI [PACIENTE], AFI.TIPO_DOC [TIPO DOCUMENTO], 
       AFI.DOCIDAFILIADO [DOCUMENTO], AFI.FNACIMIENTO [F. NACIMIENTO], AFI.EDAD , AFI.EMAIL, AFI.CELULAR, MED.NOMBRE [MEDICO], 
       MES.DESCRIPCION [ESPECIALIDAD], PLN.DESCPLAN [PLAN], AFI.DIRECCION , TGEN.DESCRIPCION [DISTRITO],LORD.IDSERVICIO,SER.DESCSERVICIO,LORD.NORDEN,
       LORDD.ALFANUMERICO,LORDD.MEMO
FROM AUT
INNER JOIN PRE ON AUT.PREFIJO = PRE.PREFIJO
INNER JOIN AFI ON AUT.IDAFILIADO = AFI.IDAFILIADO
LEFT JOIN CIT ON AUT.CONSECUTIVOCIT = CIT.CONSECUTIVO
LEFT JOIN MED ON CIT.IDMEDICO = MED.IDMEDICO
LEFT JOIN MES ON CIT.IDEMEDICA = MES.IDEMEDICA
LEFT JOIN PLN ON AUT.IDPLAN = PLN.IDPLAN
LEFT JOIN LING ON AUT.NOADMISION=AUT.NOADMISION
LEFT JOIN LORD ON LING.NOINGRESO=LORD.NOINGRESO
LEFT JOIN SER ON LORD.IDSERVICIO=SER.IDSERVICIO
LEFT JOIN LORDD ON LORD.NORDEN=LORDD.NORDEN
LEFT JOIN TGEN ON TGEN.TABLA = 'CORREGIMIENTOS' AND AFI.CORREGIMIENTO = TGEN.CODIGO
WHERE AUT.PREFIJO IN ( DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO'), DBO.FNK_VALORVARIABLE('PREFIJOAPOYODX') )
AND CONVERT(DATE,AUT.FECHA)>= '01/03/2025' AND CONVERT(DATE,AUT.FECHA)<= '01/04/2025'


--SELECT  * FROM LORDD WHERE NORDEN='0100010390'