IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'KPAGE'  AND   C.NAME = 'F_EXPIRA')
BEGIN
   ALTER TABLE KPAGE  ADD F_EXPIRA DATETIME 
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IDSEDE_FACTURA_LINK')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IDSEDE_FACTURA_LINK','Id Sede Factura Link Pago, Si no existe  toma la de noadmision ','Alfanumerica',''
END
