CREATE OR ALTER PROC DBO.SPK_RPT_ANEXO_PREFAC
@NOADMISION  VARCHAR(16),
@CNS         VARCHAR(20),  
@ITEM        INT,
@CNS_D       VARCHAR(20),
@TIPO        INT,
@FECHA       DATETIME=NULL
WITH ENCRYPTION
AS
DECLARE @PAQUETE AS SMALLINT
DECLARE @VCOPAGO AS DECIMAL(14,2)
DECLARE @VEXCE   AS DECIMAL(14,2)
DECLARE @IDTERCEROHADM VARCHAR(20)
DECLARE @IDPLAN        VARCHAR(8)
DECLARE @FORMATOCODIGO INT
DECLARE @PRE_OXIGENO VARCHAR(20)
DECLARE @PREFIJOTRASLADO VARCHAR(20)
DECLARE @NOCOB VARCHAR(20)
DECLARE @FCOPA BIT
DECLARE @TARIFA VARCHAR(5)--TAR
DECLARE @IDGRUPOSER VARCHAR(20)
DECLARE @IDTARIFAOXIGENO VARCHAR(20)
BEGIN 
 --  SELECT @PAQUETE = COALESCE(PAQUETE,0) FROM HADM WHERE NOADMISION = @NOADMISION
   SELECT @PRE_OXIGENO=  LEFT(DBO.FNK_VALORVARIABLE('PREFIJOOXIGENO'),20)
   SELECT @PREFIJOTRASLADO=LEFT(DBO.FNK_VALORVARIABLE('PREFIJOTRASLADO'),20)
   SELECT @IDTARIFAOXIGENO=LEFT(DBO.FNK_VALORVARIABLE('IDTARIFAOXIGENO'),20)
   --MODIFICO CODIGOS POR PPT
   SELECT @IDTERCEROHADM=IDTERCERO,@IDPLAN=IDPLAN,@PAQUETE=COALESCE(PAQUETE,0) FROM FTR WHERE N_FACTURA=@CNS
   SELECT @FORMATOCODIGO=IMPRIMEIDALTERNA,@TARIFA=RTRIM(LTRIM(IDTARIFA)) FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN
   PRINT CONCAT('@FORMATOCODIGO=',@FORMATOCODIGO)
   SELECT @NOCOB=DATO FROM USVGS WHERE IDVARIABLE='FTRIMPRIMENOCOB'
   IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
   BEGIN
      SELECT @FCOPA=CASE WHEN COALESCE(TIPOFIN,'')='N' THEN 1 ELSE 0 END  FROM FTR WHERE N_FACTURA=@CNS
      IF @FCOPA=1
      BEGIN
         SELECT @TIPO=7
      END
      ELSE
      BEGIN
         SELECT @TIPO=8
      END
   END
   IF @TIPO = 1
   BEGIN     
      INSERT INTO RPDX (CNS, ID1, ID2, ID3, ID4, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
      SELECT @CNS_D, SER.PREFIJO, 
             CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                   THEN SER.IDALTERNA
                   ELSE HPRED.IDSERVICIO
             END, SER.IDSERVICIO, MAX(HPRED.IDARTICULO),
             LEFT(SER.DESCSERVICIO,150), HPRED.VALOR, SUM(HPRED.CANTIDAD), 
             SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS'
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                   INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
      WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.ITEM_RPDX = @ITEM
      AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
      AND    COALESCE(HPRE.ANULADO, 0)   = 0
      AND    COALESCE(HPRED.ANULADO, 0)  = 0
      AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE dbo.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE') WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0)
                                                 ELSE 0
                                            END
      AND    CONVERT(DATE,HPRE.FECHA)<=ISNULL(@FECHA,GETDATE())
      GROUP BY SER.PREFIJO, CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                                  THEN SER.IDALTERNA
                                  ELSE HPRED.IDSERVICIO
                            END, SER.IDSERVICIO,
               SER.DESCSERVICIO, HPRED.VALOR 
      ORDER BY SER.PREFIJO, CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                                  THEN SER.IDALTERNA
                                  ELSE HPRED.IDSERVICIO
                            END, 
               SER.DESCSERVICIO, HPRED.VALOR 
      --INSERTO CIRUGIAS
      INSERT INTO RPDX (CNS, ID1, ID2, ID4, ID5, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1 )
      SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
             HPRED.VALOR, HPRED.CANTIDAD, 
             HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                   INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
      WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.ITEM_RPDX = @ITEM
      AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
      AND    COALESCE(HPRE.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      AND    CONVERT(DATE,HPRE.FECHA)<=ISNULL(@FECHA,GETDATE())
      ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
        
		
        /* OXIGENO */
        IF @PRE_OXIGENO<>'' AND (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_HORA')<>'SI'
        BEGIN
           UPDATE RPDX SET 
               VALOR1=RPDX.VALOR1/A.VALOR,
               VALOR2=A.VALOR*RPDX.VALOR2
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID3=HPRED.IDSERVICIO
               INNER JOIN SERTOT A ON HPRED.IDSERVICIO=A.IDSERVICIO AND HPRE.IDTERCEROCA=A.IDTERCERO AND HPRE.IDPLAN=A.IDPLAN
                  AND HPRE.FECHA BETWEEN A.FECHAINI AND A.FECHAFIN AND HPRE.FECHA BETWEEN A.FECHAINIFD AND A.FECHAFINFD
                  AND A.PREFIJO=@PRE_OXIGENO
           WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
            AND COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
            AND COALESCE(HPRE.ANULADO, 0) = 0
            AND COALESCE(HPRED.ANULADO, 0) = 0
            AND COALESCE(HPRED.ENCARGOS, 0) = 0
            AND A.VALOR > 0

           UPDATE RPDX SET NOMBRE=NOMBRE+' (Total litros: '+(CONVERT(VARCHAR(20),CONVERT(BIGINT,ISNULL(SER.CANTMAXIMA,1)*VALOR2*60)))+')' --STORRES SE CAMBIA INT POR BIGINT. Oxigeno hace crecer demaciado el calculo total
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID3=HPRED.IDSERVICIO
               INNER JOIN SER ON SER.IDSERVICIO=HPRED.IDSERVICIO
           WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_MINUTOS')='SI'
           BEGIN
              UPDATE RPDX SET VALOR1=VALOR1/60, VALOR2=VALOR2*60
              FROM RPDX WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           END
        END

        
        IF @FORMATOCODIGO=1 --IDALTERNA
        BEGIN
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT('['+ID3+'] '+NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
               WHERE RPDX.CNS=@CNS_D
           ELSE
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
               WHERE RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=2 --CUM
        BEGIN
           UPDATE RPDX SET ID2=ISNULL(IART.CODCUM,SER.CODCUM), 
                  NOMBRE=LEFT('['+COALESCE(IART.IDGENERICO,SER.IDGENERICO,'')+'] - '+RPDX.NOMBRE,150)
           FROM RPDX
             INNER JOIN IART ON IART.IDARTICULO=RPDX.ID4
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

        END
        IF @FORMATOCODIGO=3 --ATC
        BEGIN
           UPDATE RPDX SET ID2=SER.IDALTERNA
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=4 --ADRES
        BEGIN
           UPDATE RPDX SET ID2=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=5 --SAVIA
        BEGIN
           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET ID2=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D
           
           UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,'')
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
              LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')) AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=6 --SISPRO
        BEGIN
           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=7 --INVIMA
        BEGIN
           UPDATE RPDX SET ID2=COALESCE(IART.INVIMA,'')
           FROM SER 
               INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID3
               LEFT JOIN (
                  SELECT IDSERVICIO, MAX(REGINVIMA) INVIMA
                  FROM IART
                  WHERE COALESCE(REGINVIMA,'') LIKE '%-%' AND LEN(REGINVIMA)>5
                     AND ESTADO='Activo'
                  GROUP BY IDSERVICIO
               )IART ON SER.IDSERVICIO=IART.IDSERVICIO
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
      IF @FORMATOCODIGO=8 --CUPS
      BEGIN
         UPDATE RPDX SET ID4=COALESCE(C.CODIGO,SER.CODCUPS,'')--, NOMBRE=LEFT(SER.DESCRIPCION_CUPS,150)
         FROM RPDX
            INNER JOIN IART ON IART.IDARTICULO=RPDX.ID5
            INNER JOIN SER  ON SER.PREFIJO=RPDX.ID2 AND SER.IDSERVICIO=RPDX.ID3
            LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
            --AND SER.PREFIJO=''
      END

   END
   IF @TIPO = 2
   BEGIN
      INSERT INTO RPDX (CNS, ID1, ID2, ID3, ID4, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
      SELECT @CNS_D, HPRE.CCOSTO, SER.PREFIJO, 
             CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                   THEN SER.IDALTERNA
                   ELSE HPRED.IDSERVICIO
             END, HPRED.IDSERVICIO,
             LEFT(SER.DESCSERVICIO,150), HPRED.VALOR, 
             SUM(HPRED.CANTIDAD), SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS'
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                   INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
      WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.ITEM_RPDX = @ITEM
      AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
      AND    COALESCE(HPRE.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE dbo.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE') WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0)
                                                 ELSE 0
                                            END   
      AND    CONVERT(DATE,HPRE.FECHA)<=ISNULL(@FECHA,GETDATE())    
      GROUP BY HPRE.CCOSTO, SER.PREFIJO, CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                                              THEN SER.IDALTERNA
                                              ELSE HPRED.IDSERVICIO
                                         END, HPRED.IDSERVICIO,
               SER.DESCSERVICIO, HPRED.VALOR 
      ORDER BY HPRE.CCOSTO, SER.PREFIJO, CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                                              THEN SER.IDALTERNA
                                              ELSE HPRED.IDSERVICIO
                                         END, 
               SER.DESCSERVICIO, HPRED.VALOR 
      --INSERTO CIRUGIAS
      INSERT INTO RPDX (CNS, ID1, ID2, ID3, ID4, ID5, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
      SELECT @CNS_D, HPRE.CCOSTO, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
             HPRED.VALOR, HPRED.CANTIDAD, 
             HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS'
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                   INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
      WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.ITEM_RPDX = @ITEM
      AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE dbo.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE') WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
      AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
      AND    COALESCE(HPRE.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      AND    CONVERT(DATE,HPRE.FECHA)<=ISNULL(@FECHA,GETDATE())
      ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
        
		
        /* OXIGENO */
        IF @PRE_OXIGENO<>'' AND (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_HORA')<>'SI'
        BEGIN
           UPDATE RPDX SET 
               VALOR1=RPDX.VALOR1/A.VALOR,
               VALOR2=A.VALOR*RPDX.VALOR2
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID4=HPRED.IDSERVICIO
               INNER JOIN SERTOT A ON HPRED.IDSERVICIO=A.IDSERVICIO AND HPRE.IDTERCEROCA=A.IDTERCERO AND HPRE.IDPLAN=A.IDPLAN
                  AND HPRE.FECHA BETWEEN A.FECHAINI AND A.FECHAFIN AND HPRE.FECHA BETWEEN A.FECHAINIFD AND A.FECHAFINFD
                  AND A.PREFIJO=@PRE_OXIGENO
           WHERE RPDX.CNS=@CNS_D AND ID2=@PRE_OXIGENO
            AND COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
            AND COALESCE(HPRE.ANULADO, 0) = 0
            AND COALESCE(HPRED.ANULADO, 0) = 0
            AND COALESCE(HPRED.ENCARGOS, 0) = 0
            AND A.VALOR>0

           UPDATE RPDX SET NOMBRE=NOMBRE+' (Total litros: '+(CONVERT(VARCHAR(20),CONVERT(INT,ISNULL(SER.CANTMAXIMA,1)*VALOR2*60)))+')'
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID4=HPRED.IDSERVICIO
               INNER JOIN SER ON SER.IDSERVICIO=HPRED.IDSERVICIO
           WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_MINUTOS')='SI'
           BEGIN
              UPDATE RPDX SET VALOR1=VALOR1/60, VALOR2=VALOR2*60
              FROM RPDX WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           END
        END
   END
   IF @TIPO = 3
   BEGIN   
      PRINT '@TIPO=3' 
      PRINT '@PAQUETE ='+STR(@PAQUETE)
      IF @PAQUETE = 0
      BEGIN
         UPDATE HPRED SET HPRED.VALOREXCEDENTE = HPRED.VALOR * HPRED.CANTIDAD - (HPRED.VALORPCOMP+HPRED.VALORCOPAGO)
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND    COALESCE(HPRED.VALOREXCEDENTE,0) = 0
         
         PRINT '@CNS_D='+@CNS_D
         IF DBO.FNK_VALORVARIABLE('CODCUMS_FIJO') NOT IN('SER.CODCUM','IART.CODCUM','SER.SISPRO')
         BEGIN
            INSERT INTO RPDX (CNS, ID1, ID2, ID3, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO,STRINGGRANDE1,ID9 )
            SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, MAX(HPRED.IDARTICULO),
                   LEFT(SER.DESCSERVICIO,150),                
                   HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                   SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS',SER.DESCSERVICIO,
				    CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN CASE COALESCE(HPRED.CODIGOCUM,'') WHEN '' THEN CASE COALESCE(IART.CODCUM,'') WHEN '' THEN SER.CODCUM ELSE IART.CODCUM END ELSE HPRED.CODIGOCUM END ELSE '' END
            FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                         INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
					     LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
            AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE dbo.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE') WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0)
                                                 ELSE 0
                                            END    --SIN NOCOBRABLES
            AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
            AND    COALESCE(HPRE.ANULADO, 0) = 0
            AND    COALESCE(HPRED.ANULADO, 0) = 0
            AND    COALESCE(HPRED.ENCARGOS, 0) = CASE WHEN HPRED. N_FACTURA =@CNS AND ENCARGOS=2 THEN COALESCE(HPRED.ENCARGOS, 0) ELSE  0 END 
            GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR,
				CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN  CASE COALESCE(HPRED.CODIGOCUM,'') WHEN '' THEN CASE COALESCE(IART.CODCUM,'') WHEN '' THEN SER.CODCUM ELSE IART.CODCUM END ELSE HPRED.CODIGOCUM END ELSE '' END
            ORDER BY PREFIJO, IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR
         END
         ELSE
         BEGIN
            INSERT INTO RPDX (CNS, ID1, ID2, ID3, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO,STRINGGRANDE1 )
            SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, MAX(HPRED.IDARTICULO),
                   LEFT(SER.DESCSERVICIO,150),                
                   HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                   SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS',SER.DESCSERVICIO
            FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                         INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
					     LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
            AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE dbo.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE') WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0)
                                                 ELSE 0
                                            END      --SIN NOCOBRABLES
            AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
            AND    COALESCE(HPRE.ANULADO, 0) = 0
            AND    COALESCE(HPRED.ANULADO, 0) = 0
            AND    COALESCE(HPRED.ENCARGOS, 0) = CASE WHEN HPRED. N_FACTURA =@CNS AND ENCARGOS=2 THEN COALESCE(HPRED.ENCARGOS, 0) ELSE  0 END 
            GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR
            ORDER BY PREFIJO, IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR
         END
         --BASE PROPIA CODCUMS 
         IF EXISTS(SELECT * FROM PPT  WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN AND COALESCE(CODBCUM,'')<>'')
         BEGIN
            PRINT 'GUARDO EL IDSEDERVIO ORIGINAL'
            UPDATE RPDX SET  ID7=SER.IDSERVICIO
            FROM RPDX INNER JOIN SER ON RPDX.ID2=SER.IDSERVICIO
            WHERE COALESCE(SER.MEDICAMENTOS,0)=1
            AND  RPDX.CNS=@CNS_D
         END         
         --INSERTO CIRUGIAS
         INSERT INTO RPDX (CNS, ID1, ID2, ID4, ID5, ID6, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1,STRINGGRANDE1, STRINGMEDIO2)
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, COALESCE(HPRED.IDCIRUGIA,''), HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
                HPRED.VALOR, HPRED.CANTIDAD, 
                HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA,
                SER.DESCSERVICIO, HPRED.NOAUTORIZACION
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE @NOCOB WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
         AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
         
		print 'omar'
		print @FORMATOCODIGO
        /* OXIGENO */
        IF @PRE_OXIGENO<>'' 
        BEGIN
			IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_HORA')<>'SI'
			BEGIN
				PRINT 'INGRESO ACA...'
			   UPDATE RPDX SET 
				   VALOR1=RPDX.VALOR1/A.VALOR,
				   VALOR2=A.VALOR*RPDX.VALOR2
			   FROM RPDX 
				   INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
				   INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND HPRED.N_FACTURA=@CNS AND RPDX.ID2=HPRED.IDSERVICIO
				   INNER JOIN SERTOT A ON HPRED.IDSERVICIO=A.IDSERVICIO AND HPRE.IDTERCEROCA=A.IDTERCERO AND HPRE.IDPLAN=A.IDPLAN
					  AND HPRE.FECHA BETWEEN A.FECHAINI AND A.FECHAFIN AND HPRE.FECHA BETWEEN A.FECHAINIFD AND A.FECHAFINFD
					  AND A.PREFIJO=@PRE_OXIGENO
			   WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
				AND COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
				AND COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
				AND COALESCE(HPRE.ANULADO, 0) = 0
				AND COALESCE(HPRED.ANULADO, 0) = 0
				AND COALESCE(HPRED.ENCARGOS, 0) = 0
				AND A.VALOR>0
            
			   UPDATE RPDX SET NOMBRE=NOMBRE+' (Total litros: '+(CONVERT(VARCHAR(20),CONVERT(BIGINT,ISNULL(SER.CANTMAXIMA,1)*VALOR2*60)))+')'
			   FROM RPDX 
				   INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
				   INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID2=HPRED.IDSERVICIO
				   INNER JOIN SER ON SER.IDSERVICIO=HPRED.IDSERVICIO
			   WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           
			   IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_MINUTOS')='SI'
			   BEGIN
				PRINT 'INGRESO A MINUTSO'
				  UPDATE RPDX SET VALOR1=VALOR1/60, VALOR2=VALOR2*60
				  FROM RPDX WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
			   END
			END
			ELSE
			BEGIN
			   IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_VAL_TAR')='SI'
			   BEGIN
					DECLARE @OXI_VAL_SERTOT VARCHAR(20) = (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_VAL_SERTOT')
					
				  UPDATE RPDX SET 
					   VALOR1 = IIF(@OXI_VAL_SERTOT='SI', IIF(TARF.FACTORDINERO>1, TARF.FACTORDINERO, A.FACTOR), VALOR4/VALOR2/ROUND(IIF(A.IDTARIFA=@IDTARIFAOXIGENO, A.VALOR, 60*A.FACTOR),0)),
					   NOMBRE = NOMBRE+' (Total litros: '+(CONVERT(VARCHAR(20),CONVERT(INT,ROUND(IIF(A.IDTARIFA=@IDTARIFAOXIGENO, A.VALOR, 60*A.FACTOR),0)*VALOR2)))+')'
					--SELECT SER.IDSERVICIO, SER.DESCSERVICIO, IIF(COALESCE(A.VALOR,0)=0, A.FACTOR, TARF.FACTORDINERO)
				   FROM RPDX 
					   INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
					   INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND HPRED.N_FACTURA=@CNS AND RPDX.ID2=HPRED.IDSERVICIO
					   INNER JOIN SER ON SER.IDSERVICIO=HPRED.IDSERVICIO
					   INNER JOIN SERTOT A ON HPRED.IDSERVICIO=A.IDSERVICIO AND HPRE.IDTERCEROCA=A.IDTERCERO AND HPRE.IDPLAN=A.IDPLAN
						  AND HPRE.FECHA BETWEEN A.FECHAINI AND A.FECHAFIN AND HPRE.FECHA BETWEEN A.FECHAINIFD AND A.FECHAFINFD
						  AND A.PREFIJO=@PRE_OXIGENO
						LEFT JOIN TARF ON TARF.IDTARIFA=A.IDTARIFA AND HPRE.FECHA BETWEEN TARF.FECHAINI AND TARF.FECHAFIN
				   WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
					AND COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
					AND COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
					AND COALESCE(HPRE.ANULADO, 0) = 0
					AND COALESCE(HPRED.ANULADO, 0) = 0
					AND COALESCE(HPRED.ENCARGOS, 0) = 0
					print 'voy a cambiar'
					UPDATE RPDX SET VALOR2=(VALOR4/VALOR1),NOMBRE=SER.DESCSERVICIO+' (Total Horas: '+CAST(VALOR2 AS VARCHAR(20)) +')'
					FROM RPDX INNER JOIN SER ON RPDX.ID2=SER.IDSERVICIO
					 WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
					 AND IDTERCERO='SERVICIOS'
	
		
			   END
			END
        END

        IF @FORMATOCODIGO=1 --IDALTERNA
        BEGIN
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT('['+ID2+'] '+NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D
           ELSE
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D

			   UPDATE RPDX SET ID2=SER.IDALTERNA, STRINGGRANDE1=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D

            PRINT 'ACTUALIZO PROCEDIMIENTOS A SOAT'
            UPDATE RPDX SET ID4=SER.IDALTERNA, STRINGGRANDE1=LEFT(NOMBRE,150)
            FROM SER INNER JOIN RPDX ON SER.IDSERVICIO=RPDX.ID4
            WHERE RPDX.CNS=@CNS_D AND IDTERCERO = 'PROCEDIMIENTOS'
        END
        IF @FORMATOCODIGO=2 --CUM
        BEGIN
           --UPDATE RPDX SET ID2=SER.CODCUM
           --FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           --WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

		   
		   UPDATE RPDX SET ID2=SUBSTRING(ISNULL(IART.CODCUM,SER.CODCUM),0,CHARINDEX('-',ISNULL(IART.CODCUM,SER.CODCUM),0))+'-'+CONVERT(VARCHAR,TRY_CAST(RIGHT(ISNULL(IART.CODCUM,SER.CODCUM),LEN(ISNULL(IART.CODCUM,SER.CODCUM))-CHARINDEX('-',ISNULL(IART.CODCUM,SER.CODCUM),0)) AS SMALLINT))
	       FROM RPDX
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID2
             LEFT JOIN IART ON IART.IDARTICULO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
		IF @FORMATOCODIGO=3 --ATC
        BEGIN
           UPDATE RPDX SET ID2=SER.IDALTERNA
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=4 --ADRES
        BEGIN
			PRINT  'INGRESO AL 4 AFRES'
           UPDATE RPDX SET ID2=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D

		   --
           IF DBO.FNK_VALORVARIABLE('CODCUMS_FIJO')='SER.CODCUM'
           BEGIN
              UPDATE RPDX SET ID2=SER.CODCUM
              FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
              WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
           END
		   ELSE 
		   BEGIN
			   IF DBO.FNK_VALORVARIABLE('CODCUMS_FIJO')='IART.CODCUM'
			   BEGIN
				  UPDATE RPDX SET ID2=IART.CODCUM
				  FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
						   INNER JOIN IART ON SER.IDARTICULO=IART.IDARTICULO
				  WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
			   END
			   ELSE 
			   BEGIN
				   IF DBO.FNK_VALORVARIABLE('CODCUMS_FIJO')='SER.CODSISPRO'
				   BEGIN
					  UPDATE RPDX SET ID2=SER.CODSISPRO
					  FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
							   INNER JOIN IART ON SER.IDARTICULO=IART.IDARTICULO
					  WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
				   END
				   ELSE
				   BEGIN
					   UPDATE RPDX SET ID2=ID9 WHERE   RPDX.CNS=@CNS_D AND  COALESCE(ID9,'')<>''
					END
				END
			END

			UPDATE RPDX SET ID2=LEFT(ID2,CHARINDEX('-',ID2,1)-1)+'-'+CAST(CONVERT(INT,RIGHT(ID2,LEN(ID2)-CHARINDEX('-',ID2,1)))AS VARCHAR(2))
			WHERE   RPDX.CNS=@CNS_D AND  COALESCE(ID9,'')<>''
			AND CHARINDEX('-',ID2,1)>0

        END
        IF @FORMATOCODIGO=5 --SAVIA
        BEGIN
           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET ID2=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D
           
           UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,'')
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
              LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')) AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=6 --SISPRO
        BEGIN
		   UPDATE RPDX SET ID2=SUBSTRING(SER.CODSISPRO,0,CHARINDEX('-',SER.CODSISPRO,0))+'-'+CONVERT(VARCHAR,TRY_CAST(RIGHT(SER.CODSISPRO,LEN(SER.CODSISPRO)-CHARINDEX('-',SER.CODSISPRO,0)) AS SMALLINT))
	       FROM RPDX
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=7 --INVIMA
        BEGIN
           UPDATE RPDX SET ID2=COALESCE(IART.INVIMA,'')
           FROM SER 
               INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               LEFT JOIN (
                  SELECT IDSERVICIO, MAX(REGINVIMA) INVIMA
                  FROM IART
                  WHERE COALESCE(REGINVIMA,'') LIKE '%-%' AND LEN(REGINVIMA)>5
                     AND ESTADO='Activo'
                  GROUP BY IDSERVICIO
               )IART ON SER.IDSERVICIO=IART.IDSERVICIO
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=8 --CUPS
        BEGIN
            UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,'')
            FROM RPDX 
                INNER JOIN SER ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO<>'PROCEDIMIENTOS'
            
			--NOMBRE DE PROCEDIMIENTO
            UPDATE RPDX SET ID6=COALESCE(C.CODIGO,SER.CODCUPS,''), STRINGGRANDE1=COALESCE(C.DESCRIPCION ,SER.DESCRIPCION_CUPS,'')
            FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID4
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'
			
			--DETALLE DE PROCEDIMIENTO
            UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,''), NOMBRE=COALESCE(C.DESCRIPCION ,SER.DESCRIPCION_CUPS,'')
            FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID2
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'
        END
        IF @FORMATOCODIGO=9 --CUM Y CUPS
        BEGIN
		   PRINT 'DESPUES DE'
		   UPDATE RPDX SET ID2=SUBSTRING(ISNULL(IART.CODCUM,SER.CODCUM),0,CHARINDEX('-',ISNULL(IART.CODCUM,SER.CODCUM),0))+'-'+CONVERT(VARCHAR,TRY_CAST(RIGHT(ISNULL(IART.CODCUM,SER.CODCUM),LEN(ISNULL(IART.CODCUM,SER.CODCUM))-CHARINDEX('-',ISNULL(IART.CODCUM,SER.CODCUM),0)) AS SMALLINT))
	       FROM RPDX
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID2
             LEFT JOIN IART ON IART.IDARTICULO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

	       UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,SER.IDSERVICIO),NOMBRE=LEFT(COALESCE(C.DESCRIPCION ,SER.DESCRIPCION_CUPS,''),150)
           FROM RPDX 
               INNER JOIN SER ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.MEDICAMENTOS,0)=0
           
			--NOMBRE DE PROCEDIMIENTO
            UPDATE RPDX SET ID6=COALESCE(C.CODIGO,SER.CODCUPS,''), STRINGGRANDE1=COALESCE(C.DESCRIPCION ,SER.DESCRIPCION_CUPS,'')
            FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID4
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'
			
			--DETALLE DE PROCEDIMIENTO
            UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,''), NOMBRE=COALESCE(C.DESCRIPCION ,SER.DESCRIPCION_CUPS,'')
            FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID2
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'

			PRINT 'Actualizo codgio CUM'
			UPDATE RPDX SET ID2=ID9 WHERE   RPDX.CNS=@CNS_D AND  COALESCE(ID9,'')<>''

			UPDATE RPDX SET ID2=LEFT(ID2,CHARINDEX('-',ID2,1)-1)+'-'+CAST(TRY_CONVERT(INT,RIGHT(ID2,LEN(ID2)-CHARINDEX('-',ID2,1)))AS VARCHAR(2))
			WHERE   RPDX.CNS=@CNS_D AND  COALESCE(ID9,'')<>''
			AND CHARINDEX('-',ID2,1)>0

        END
        IF @FORMATOCODIGO=11 --CUM Y SOAT
        BEGIN
		   UPDATE RPDX SET ID2=COALESCE(IART.CODCUM,SER.CODCUM)
           FROM RPDX
             LEFT JOIN IART ON IART.IDARTICULO=RPDX.ID3
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.MEDICAMENTOS,0)=1 

           UPDATE RPDX SET ID2=TARD.CODIFICACION,STRINGGRANDE1=KONVERT.DESC_CODIGO
           FROM RPDX 
               INNER JOIN SER ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               INNER JOIN TARD ON SER.IDSERVICIO=TARD.IDSERVICIO AND TARD.IDTARIFA=@TARIFA
               LEFT  JOIN KONVERT ON TARD.CODIFICACION=KONVERT.CODIGOORI
           WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.MEDICAMENTOS,0)=0 AND RPDX.IDTERCERO<>'PROCEDIMIENTOS'
           
		   print '@TARIFA='+@TARIFA
           UPDATE RPDX SET ID6=TARD.CODIFICACION, STRINGGRANDE1=KONVERT.DESC_CODIGO
           FROM RPDX 
               INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID4
               INNER JOIN TARD ON SER.IDSERVICIO=TARD.IDSERVICIO AND TARD.IDTARIFA=@TARIFA
               LEFT  JOIN KONVERT ON TARD.CODIFICACION=KONVERT.CODIGOORI
           WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'


        END 
      IF EXISTS(SELECT * FROM PPT  WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN AND COALESCE(CODBCUM,'')<>'')
      BEGIN
         SELECT @IDGRUPOSER=CODBCUM FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN  
         IF EXISTS(SELECT  * FROM GSSP WHERE IDGRUPOSER=@IDGRUPOSER)
         BEGIN
            UPDATE RPDX SET ID2=GSSP.CODCUM
            FROM RPDX INNER JOIN GSSP ON RPDX.ID7=GSSP.IDSERVICIO
            WHERE  RPDX.CNS=@CNS_D
            AND GSSP.IDGRUPOSER=@IDGRUPOSER
         END
      END        

        /* OXIGENO */
        IF @PREFIJOTRASLADO<>''
        BEGIN
           UPDATE RPDX SET NOMBRE=HPRED.COMENTARIOS, STRINGGRANDE1=HPRED.COMENTARIOS
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PREFIJOTRASLADO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND HPRED.N_FACTURA=@CNS AND RPDX.ID2=HPRED.IDSERVICIO
           WHERE RPDX.CNS=@CNS_D AND ID1=@PREFIJOTRASLADO
               AND COALESCE(HPRED.COMENTARIOS,'')<>''
        END

      END
      ELSE
      BEGIN
         PRINT 'POR PAQUETE'
         SELECT @VCOPAGO = SUM(HPRED.VALORCOPAGO)
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION

         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO,STRINGGRANDE1 )
         SELECT @CNS_D, 'PAQUETE', FTRD.REFERENCIA, LEFT(SER.DESCSERVICIO,150), FTRD.VLR_SERVICI, 1, 
                @VCOPAGO, FTRD.VR_TOTAL, 'SERVICIOS',SER.DESCSERVICIO
         FROM   FTRD INNER JOIN SER ON FTRD.REFERENCIA = SER.IDSERVICIO
         WHERE  FTRD.N_FACTURA = @CNS   
         AND COALESCE(PAQUETE,0) IN(0,1)
         AND PAQUETE IS NOT NULL
        PRINT '@FORMATOCODIGO ='+STR(@FORMATOCODIGO)
        IF @FORMATOCODIGO=9 --IDALTERNA
        BEGIN
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT('['+ID2+'] '+NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D
           ELSE
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D
               AND COALESCE(SER.MEDICAMENTOS,0)=0

			      UPDATE RPDX SET ID2=SER.IDALTERNA, STRINGGRANDE1=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON  SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D
               AND COALESCE(SER.MEDICAMENTOS,0)=0
        END
         
         --SE AGREGAN LOS CARGOS QUE ESTAN FUERA DEL PAQUETE.
         --IF @PAQUETE=2
         --BEGIN
             INSERT INTO RPDX (CNS, ID1, ID2, ID3, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO,STRINGGRANDE1,ID6 )
             SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, MAX(HPRED.IDARTICULO),
                    LEFT(SER.DESCSERVICIO,150),                
                    HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                    SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS',SER.DESCSERVICIO,COALESCE(HPRED.NOAUTORIZACION,'')
             FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                          INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
             WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
             AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
            -- AND    COALESCE(HPRE.CIRUGIA,'') <> 'SI' 
             AND    COALESCE(HPRE.ANULADO, 0) = 0
             AND    COALESCE(HPRED.ANULADO, 0) = 0
             AND    COALESCE(HPRED.ENCARGOS, 0) = 0
             AND    COALESCE(HPRED.PAQUETE, 0)=1
			 AND    COALESCE(HPRED.IDCIRUGIA,'')=''
             GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR,COALESCE(HPRED.NOAUTORIZACION,'')
             ORDER BY PREFIJO, IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         --END
         --BASE PROPIA CODCUMS 
         IF EXISTS(SELECT * FROM PPT  WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN AND COALESCE(CODBCUM,'')<>'')
         BEGIN
            PRINT 'GUARDO EL IDSEDERVIO ORIGINAL'
            UPDATE RPDX SET  ID7=SER.IDSERVICIO
            FROM RPDX INNER JOIN SER ON RPDX.ID2=SER.IDSERVICIO
            WHERE COALESCE(SER.MEDICAMENTOS,0)=1
            AND  RPDX.CNS=@CNS_D
         END
         --INSERTO CIRUGIAS
         INSERT INTO RPDX (CNS, ID1, ID2, ID4, ID5, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1,STRINGGRANDE1)
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
                HPRED.VALOR, HPRED.CANTIDAD, 
                HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA,SER.DESCSERVICIO
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE @NOCOB WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
         --AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI' /* mnkr 2018/05/15: Se comentariza ya que se puede marcar fuera del paquete cargos manuales */
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         AND    COALESCE(HPRED.PAQUETE, 0) = 1
         AND    COALESCE(HPRED.IDCIRUGIA,'')<>''
         ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA

        IF @FORMATOCODIGO=1 --IDALTERNA
        BEGIN
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT('['+ID2+'] '+NOMBRE,150),
               STRINGGRANDE1='['+ID2+'] '+NOMBRE+CASE WHEN LEN(COALESCE(ID6,''))>1 THEN ' - No.Autoriz.: '+ID6 ELSE '' END
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D
           ELSE
               UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               WHERE RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=2 --CUM
        BEGIN
           --UPDATE RPDX SET ID2=SER.CODCUM
           --FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           --WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

		   UPDATE RPDX SET ID2=ISNULL(IART.CODCUM,SER.CODCUM)
           FROM RPDX
             LEFT JOIN IART ON IART.IDARTICULO=RPDX.ID3
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
		IF @FORMATOCODIGO=3 --ATC
        BEGIN
           UPDATE RPDX SET ID2=SER.IDALTERNA
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=4 --ADRES
        BEGIN
           UPDATE RPDX SET ID2=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=5 --SAVIA
        BEGIN
           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET ID2=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D
           
           UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,'')
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
              LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')) AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=6 --SISPRO
        BEGIN
           UPDATE RPDX SET ID2=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=7 --INVIMA
        BEGIN
           UPDATE RPDX SET ID2=COALESCE(IART.INVIMA,'')
           FROM SER 
               INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               LEFT JOIN (
                  SELECT IDSERVICIO, MAX(REGINVIMA) INVIMA
                  FROM IART
                  WHERE COALESCE(REGINVIMA,'') LIKE '%-%' AND LEN(REGINVIMA)>5
                     AND ESTADO='Activo'
                  GROUP BY IDSERVICIO
               )IART ON SER.IDSERVICIO=IART.IDSERVICIO
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=8 --CUPS
        BEGIN
            UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,'')
            FROM RPDX 
                INNER JOIN SER ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D
            
            UPDATE RPDX SET ID6=COALESCE(C.CODIGO,SER.CODCUPS,'')
            FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID4
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'
        END
        IF @FORMATOCODIGO=9 --CUM Y CUPS
        BEGIN
		   UPDATE RPDX SET ID2=ISNULL(IART.CODCUM,SER.CODCUM)
           FROM RPDX
             LEFT JOIN IART ON IART.IDARTICULO=RPDX.ID3
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS,SER.IDSERVICIO)
           FROM RPDX 
               INNER JOIN SER ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
               LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.MEDICAMENTOS,0)=0
           
           UPDATE RPDX SET ID6=COALESCE(C.CODIGO,SER.CODCUPS,'')
           FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID4
               LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'
        END
      IF EXISTS(SELECT * FROM PPT  WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN AND COALESCE(CODBCUM,'')<>'')
      BEGIN
         SELECT @IDGRUPOSER=CODBCUM FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN  
         IF EXISTS(SELECT  * FROM GSSP WHERE IDGRUPOSER=@IDGRUPOSER)
         BEGIN
            UPDATE RPDX SET ID2=GSSP.CODCUM
            FROM RPDX INNER JOIN GSSP ON RPDX.ID7=GSSP.IDSERVICIO
            WHERE  RPDX.CNS=@CNS_D
            AND GSSP.IDGRUPOSER=@IDGRUPOSER
         END
      END
      END
   END
   IF @TIPO = 4  --- PARA EL SYAP COLOCAR EL COD CUM 
   BEGIN   
      IF @PAQUETE = 0
      BEGIN
      
         UPDATE HPRED SET HPRED.VALOREXCEDENTE = HPRED.VALOR * HPRED.CANTIDAD - HPRED.VALORPCOMP 
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND    COALESCE(HPRED.VALOREXCEDENTE,0) = 0
         
         PRINT '@CNS_D='+@CNS_D
         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, SER.PREFIJO,SER.CODCUM ,                              
                LEFT(SER.DESCSERVICIO,150),                
                HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS'
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
         AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         GROUP BY SER.PREFIJO,SER.CODCUM,SER.DESCSERVICIO, HPRED.VALOR 
         ORDER BY SER.PREFIJO,SER.CODCUM,SER.DESCSERVICIO, HPRED.VALOR 

         -- INSERTAMOS LOS NOCOBRABLES
         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, LEFT(SER.DESCSERVICIO,150), HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'NOCOBRABLE'
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0) <> 0
         AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         ORDER BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         
         --INSERTO CIRUGIAS
         INSERT INTO RPDX (CNS, ID1, ID2, ID4, ID5, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1 )
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
                HPRED.VALOR, HPRED.CANTIDAD, 
                HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE @NOCOB WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
         AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
      END   
      ELSE
      BEGIN
         --PRINT 'POR PAQUETE'
         SELECT @VCOPAGO = SUM(HPRED.VALORCOPAGO)
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, 'PAQUETE', HADM.IDSERVICIOPAQUETE, LEFT(SER.DESCSERVICIO,150), HADM.VLRSERVICIOPAQ, 1, 
                @VCOPAGO, HADM.VLRSERVICIOPAQ -@VCOPAGO, 'SERVICIOS'
         FROM   HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE = SER.IDSERVICIO
         WHERE  NOADMISION = @NOADMISION                      
      END
   END
   IF @TIPO = 5  --- PARA IMPRIMIR COD CUM Y CODIGO ATC JUNTO MED NOPOS
   BEGIN 
      PRINT 'NUEVO FORMATO'
      IF @PAQUETE = 0
      BEGIN  
         PRINT 'NUEVO FORMATO PAQUETE =0 '  
         UPDATE HPRED SET HPRED.VALOREXCEDENTE = HPRED.VALOR * HPRED.CANTIDAD - HPRED.VALORPCOMP 
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND    COALESCE(HPRED.VALOREXCEDENTE,0) = 0
         
         PRINT '@CNS_D='+@CNS_D
         INSERT INTO RPDX (CNS, ID1, STRINGMEDIO1, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, ID2, CANTIDAD, ID3)
         SELECT @CNS_D, PREFIJO, IDSERVICIO, LEFT(CODIGO+DESCSERVICIO, 150) NOMBRE, VALOR, SUM(CANTIDAD), SUM(VALORCOPAGO), SUM(TOTAL), 'SERVICIOS', NOPRESTACION, NOITEM, IDARTICULO=MAX(IDARTICULO)
         FROM (
             SELECT SER.PREFIJO, HPRED.IDSERVICIO,
                    '['+(CASE WHEN COALESCE(C.CODIGO,HPRED.CODCUPS,'')<>'' THEN COALESCE(C.CODIGO,HPRED.CODCUPS) ELSE SER.IDALTERNA END)+' ] - ' AS CODIGO, SER.DESCSERVICIO,                
                    HPRED.VALOR, HPRED.CANTIDAD, 
                    HPRED.VALORCOPAGO, HPRED.VALOR*HPRED.CANTIDAD-HPRED.VALORPCOMP AS TOTAL, --SUM(HPRED.VALOREXCEDENTE)
				    CASE WHEN COALESCE(HPRED.NOLOTE,'')='HOMOLOGO' THEN HPRED.NOPRESTACION ELSE NULL END AS NOPRESTACION,
                    CASE WHEN COALESCE(HPRED.NOLOTE,'')='HOMOLOGO' THEN HPRED.NOITEM ELSE NULL END AS NOITEM, 
                    HPRED.IDARTICULO
             FROM   HPRED 
                INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
                LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
             WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
             AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
             AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
             AND    COALESCE(HPRE.ANULADO, 0) = 0
             AND    COALESCE(HPRED.ANULADO, 0) = 0
             AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         ) X
         GROUP BY PREFIJO, CODIGO, IDSERVICIO, DESCSERVICIO, VALOR, NOPRESTACION, NOITEM
         ORDER BY PREFIJO, NOMBRE, DESCSERVICIO

         PRINT 'INSERTAMOS LOS NOCOBRABLES'
         INSERT INTO RPDX (CNS, ID1, STRINGMEDIO1, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, LEFT(SER.DESCSERVICIO,150), HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'NOCOBRABLE'
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0) <> 0
         AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         ORDER BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         
         PRINT'INSERTO CIRUGIAS'
         INSERT INTO RPDX (CNS, ID1, STRINGMEDIO1, ID4, STRINGMEDIO2, ID5, ID6, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1 )
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), A.DESCSERVICIO, HPRED.CONSECUTIVOCX, COALESCE(HPRED.IDCIRUGIA,''), HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
                HPRED.VALOR, HPRED.CANTIDAD, 
                HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
					  LEFT JOIN SER A ON A.IDSERVICIO=HPRED.IDCIRUGIA
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE @NOCOB WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
         AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
         
        --CODCUM EN FACTURAS POR AHORA
        --IF (SELECT COUNT(*) FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN AND IMPRIMEIDALTERNA=2)>0
        --BEGIN
        --   UPDATE RPDX SET NOMBRE=SER.CODCUM+'--'+SER.DESCSERVICIO
        --   FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
        --   WHERE SER.PREFIJO  = DBO.FnK_ValorVariable('PREFIJOMEDNOPOS')
        --   AND   COALESCE(SER.CODCUM,'')<>''
        --END

        /* OXIGENO */
        IF @PRE_OXIGENO<>'' AND (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_HORA')<>'SI'
        BEGIN
           UPDATE RPDX SET 
               VALOR1=RPDX.VALOR1/A.VALOR,
               VALOR2=A.VALOR*RPDX.VALOR2
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND HPRED.N_FACTURA=@CNS AND RPDX.ID2=HPRED.IDSERVICIO
               INNER JOIN SERTOT A ON HPRED.IDSERVICIO=A.IDSERVICIO AND HPRE.IDTERCEROCA=A.IDTERCERO AND HPRE.IDPLAN=A.IDPLAN
                  AND HPRE.FECHA BETWEEN A.FECHAINI AND A.FECHAFIN AND HPRE.FECHA BETWEEN A.FECHAINIFD AND A.FECHAFINFD
                  AND A.PREFIJO=@PRE_OXIGENO
           WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
            AND COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
            AND COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
            AND COALESCE(HPRE.ANULADO, 0) = 0
            AND COALESCE(HPRED.ANULADO, 0) = 0
            AND COALESCE(HPRED.ENCARGOS, 0) = 0
            AND A.VALOR>0
            
           UPDATE RPDX SET NOMBRE=NOMBRE+' (Total litros: '+(CONVERT(VARCHAR(20),CONVERT(INT,ISNULL(SER.CANTMAXIMA,1)*VALOR2*60)))+')'
           FROM RPDX 
               INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
               INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID2=HPRED.IDSERVICIO
               INNER JOIN SER ON SER.IDSERVICIO=HPRED.IDSERVICIO
           WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_MINUTOS')='SI'
           BEGIN
              UPDATE RPDX SET VALOR1=VALOR1/60, VALOR2=VALOR2*60
              FROM RPDX WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           END
        END
        PRINT '@FORMATOCODIGO'
        PRINT @FORMATOCODIGO
        IF @FORMATOCODIGO=1 --IDALTERNA
        BEGIN
           IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
               UPDATE RPDX SET STRINGMEDIO1=SER.IDALTERNA, NOMBRE=LEFT('['+ID2+'] '+NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
               WHERE RPDX.CNS=@CNS_D
           ELSE
               UPDATE RPDX SET STRINGMEDIO1=SER.IDALTERNA, NOMBRE=LEFT(NOMBRE,150)
               FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
               WHERE RPDX.CNS=@CNS_D
        END

--Query2
--Query2
        IF @FORMATOCODIGO=2 --CUM
        BEGIN
		   --ID1=PREFIJO, STRINGMEDIO1=IDSERVICIO, NOMBRE=CODIGO+DESCSERVICIO, VALOR1=HPRED.VALOR, ID2=NOPRESTACION, CANTIDAD=NOITEM, ID3=IDARTICULO
		   UPDATE RPDX SET NOMBRE=SER.DESCSERVICIO, STRINGMEDIO1=CASE WHEN COALESCE(IART.CODCUM,'')<>'' THEN IART.CODCUM ELSE SER.CODCUM END
           FROM RPDX
             INNER JOIN SER  ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
             LEFT JOIN IART ON IART.IDARTICULO=RPDX.ID3
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D		   
		   
		   UPDATE RPDX SET STRINGMEDIO1=CASE WHEN CHARINDEX('-',STRINGMEDIO1,0)=0 THEN STRINGMEDIO1 ELSE
                        CASE WHEN   LEN(LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0)-1))<8 
                            THEN   REPLACE(SPACE(8-LEN(LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0)-1)))+LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0)-1),SPACE(1),0)
                            ELSE   LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0)-1)
                        END +'-'+ 
                        CASE WHEN LEN(RIGHT(STRINGMEDIO1,LEN(STRINGMEDIO1)-LEN(LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0)))))<2
                            THEN '0'+RIGHT(STRINGMEDIO1,LEN(STRINGMEDIO1)-LEN(LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0))))
                            ELSE LEFT(RIGHT(STRINGMEDIO1,LEN(STRINGMEDIO1)-LEN(LEFT(STRINGMEDIO1,CHARINDEX('-',STRINGMEDIO1,0)))),2) END
                        END
			FROM RPDX
			INNER JOIN SER ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.ID6
			WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D AND STRINGMEDIO1 LIKE '%-%'
        END
		  IF @FORMATOCODIGO=3 --ATC
        BEGIN
           UPDATE RPDX SET STRINGMEDIO1=SER.IDALTERNA
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=4 --ADRES
        BEGIN
           UPDATE RPDX SET STRINGMEDIO1=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET STRINGMEDIO1=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=5 --SAVIA
        BEGIN
           UPDATE RPDX SET STRINGMEDIO1=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

           UPDATE RPDX SET STRINGMEDIO1=''
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D
           
           UPDATE RPDX SET STRINGMEDIO1=COALESCE(C.CODIGO,SER.CODCUPS,'')
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
              LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
           WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')) AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=6 --SISPRO
        BEGIN
           UPDATE RPDX SET STRINGMEDIO1=SER.CODSISPRO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=7 --INVIMA
        BEGIN
           UPDATE RPDX SET STRINGMEDIO1=COALESCE(IART.INVIMA,'')
           FROM SER 
               INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
               LEFT JOIN (
                  SELECT IDSERVICIO, MAX(REGINVIMA) INVIMA
                  FROM IART
                  WHERE COALESCE(REGINVIMA,'') LIKE '%-%' AND LEN(REGINVIMA)>5
                     AND ESTADO='Activo'
                  GROUP BY IDSERVICIO
               )IART ON SER.IDSERVICIO=IART.IDSERVICIO
           WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
        END
        IF @FORMATOCODIGO=8 --CUPS
        BEGIN
            UPDATE RPDX SET STRINGMEDIO1=COALESCE(C.CODIGO,SER.CODCUPS,''), NOMBRE=LEFT('['+SER.IDSERVICIO+'] - '+COALESCE(C.DESCRIPCION,SER.DESCRIPCION_CUPS,''),150)
            FROM RPDX INNER JOIN SER ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
                LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.CODCUPS,'')<>'' AND COALESCE(SER.DESCRIPCION_CUPS,'')<>'' AND SER.PREFIJO<>@PRE_OXIGENO AND ISNULL(SER.MEDICAMENTOS,0)=0

            IF (SELECT TIPORIPS FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN)='04'
			BEGIN
				 UPDATE RPDX SET NOMBRE=LEFT('['+COALESCE(C.CODIGO,SER.CODCUPS,'')+'] - '+COALESCE(C.DESCRIPCION,SER.DESCRIPCION_CUPS,''),150)
				FROM RPDX INNER JOIN SER ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
					LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
				WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.CODCUPS,'')<>'' AND COALESCE(SER.DESCRIPCION_CUPS,'')<>'' AND SER.PREFIJO<>@PRE_OXIGENO AND ISNULL(SER.MEDICAMENTOS,0)=1
			END

            UPDATE RPDX SET ID6=COALESCE(C.CODIGO,SER.CODCUPS,''), STRINGMEDIO2=COALESCE(C.DESCRIPCION,SER.DESCRIPCION_CUPS,'')  
            FROM RPDX INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID4
                LEFT  JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
            WHERE RPDX.CNS=@CNS_D AND RPDX.IDTERCERO='PROCEDIMIENTOS'

            UPDATE RPDX SET STRINGMEDIO1=SER.CODCUPS, NOMBRE=LEFT('['+SER.CODCUM+'] - '+SER.DESCRIPCION_CUPS,150)
            FROM RPDX INNER JOIN SER ON SER.PREFIJO=RPDX.ID1 AND SER.IDSERVICIO=RPDX.STRINGMEDIO1
            WHERE RPDX.CNS=@CNS_D AND COALESCE(SER.CODCUPS,'')<>'' AND COALESCE(SER.DESCRIPCION_CUPS,'')<>'' AND COALESCE(SER.CODCUM,'')<>''
               AND RPDX.ID1=@PRE_OXIGENO

            declare @COD_OXIGENO varchar(50), @NOM_OXIGENO varchar(200), @VALOR1 DECIMAL(17,2), @VALOR2 DECIMAL(17,2), @VALOR4 DECIMAL(17,2), @I_TO INT
            declare cursor1 cursor for
	            SELECT STRINGMEDIO1, NOMBRE, MAX(VALOR1), SUM(VALOR2), SUM(VALOR4), COUNT(1)
               FROM RPDX 
               WHERE CNS=@CNS_D AND ID1=@PRE_OXIGENO
               GROUP BY STRINGMEDIO1, NOMBRE
            open cursor1
            fetch next from cursor1
            into @COD_OXIGENO, @NOM_OXIGENO, @VALOR1, @VALOR2, @VALOR4, @I_TO
            while @@fetch_status = 0     
            begin
               IF @I_TO>1
               BEGIN
                  UPDATE RPDX SET VALOR1=@VALOR1, VALOR2=@VALOR2, VALOR4=@VALOR4
                  FROM (
                     SELECT ROW_NUMBER() OVER (ORDER BY ITEM) ID, ITEM FROM RPDX
                     WHERE CNS=@CNS_D AND ID1=@PRE_OXIGENO AND STRINGMEDIO1=@COD_OXIGENO AND NOMBRE=@NOM_OXIGENO
                  ) AS X INNER JOIN RPDX ON RPDX.CNS=@CNS_D AND RPDX.ITEM=X.ITEM AND X.ID=1

                  DELETE RPDX 
                  FROM (
                     SELECT ROW_NUMBER() OVER (ORDER BY ITEM) ID, ITEM FROM RPDX
                     WHERE CNS=@CNS_D AND ID1=@PRE_OXIGENO AND STRINGMEDIO1=@COD_OXIGENO AND NOMBRE=@NOM_OXIGENO
                  ) AS X INNER JOIN RPDX ON RPDX.CNS=@CNS_D AND RPDX.ITEM=X.ITEM AND X.ID>1
               END
	            fetch next from cursor1
	            into @COD_OXIGENO, @NOM_OXIGENO, @VALOR1, @VALOR2, @VALOR4, @I_TO
            end
            close cursor1
            deallocate cursor1

        END
      END   
      ELSE
      BEGIN
         --PRINT 'POR PAQUETE'
         SELECT @VCOPAGO = SUM(HPRED.VALORCOPAGO)
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         INSERT INTO RPDX (CNS, ID1, STRINGMEDIO1, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, 'PAQUETE', HADM.IDSERVICIOPAQUETE, LEFT(SER.DESCSERVICIO,150), HADM.VLRSERVICIOPAQ, 1, 
                @VCOPAGO, HADM.VLRSERVICIOPAQ -@VCOPAGO, 'SERVICIOS'
         FROM   HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE = SER.IDSERVICIO
         WHERE  NOADMISION = @NOADMISION                      
      END
   END
   IF @TIPO = 6
   BEGIN   
      IF @PAQUETE = 0
      BEGIN    
         UPDATE HPRED SET HPRED.VALOREXCEDENTE = HPRED.VALOR * HPRED.CANTIDAD - HPRED.VALORPCOMP 
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         AND    COALESCE(HPRED.VALOREXCEDENTE,0) = 0
         
         PRINT '@CNS_D='+@CNS_D
         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, SER.PREFIJO,                
                CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                   THEN SER.IDALTERNA
                   ELSE HPRED.IDSERVICIO
                END, 
                LEFT(SER.DESCSERVICIO,150),                
                HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'SERVICIOS'
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
        -- AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         AND  NOT EXISTS(SELECT * FROM HGQXD WHERE (HPRED.IDSERVICIO=HGQXD.CIRIDSERV OR HPRED.IDSERVICIO=ANEIDSERV OR HPRED.IDSERVICIO=AQXIDSERV
                                                     OR HPRED.IDSERVICIO=DSIDSERV OR HPRED.IDSERVICIO=MMIDSERV OR HPRED.IDSERVICIO=MEDIDSERV) )
         GROUP BY SER.PREFIJO, CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                                  THEN SER.IDALTERNA
                                  ELSE HPRED.IDSERVICIO
                               END, 
                  SER.DESCSERVICIO, HPRED.VALOR 
         ORDER BY SER.PREFIJO, CASE WHEN SER.CODIGORIPS    = DBO.FnK_ValorVariable('IDMEDNOPOSRIPS')
                                  THEN SER.IDALTERNA
                                  ELSE HPRED.IDSERVICIO
                               END, 
                  SER.DESCSERVICIO, HPRED.VALOR 
         -- INSERTAMOS LOS NOCOBRABLES
         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, LEFT(SER.DESCSERVICIO,150), HPRED.VALOR, SUM(HPRED.CANTIDAD), 
                SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'NOCOBRABLE'
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0) <> 0
         AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         ORDER BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         
         --INSERTO CIRUGIAS
         INSERT INTO RPDX (CNS, ID1, ID2, ID4, ID5, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1 )
         SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
                HPRED.VALOR, HPRED.CANTIDAD, 
                HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                      INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
         WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
         AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE @NOCOB WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
         AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
         AND    COALESCE(HPRE.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ANULADO, 0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         AND    EXISTS(SELECT * FROM HGQXD WHERE (HPRED.IDSERVICIO=HGQXD.CIRIDSERV OR HPRED.IDSERVICIO=ANEIDSERV OR HPRED.IDSERVICIO=AQXIDSERV
                                                     OR HPRED.IDSERVICIO=DSIDSERV OR HPRED.IDSERVICIO=MMIDSERV OR HPRED.IDSERVICIO=MEDIDSERV) )
         ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
         
        --CODCUM EN FACTURAS POR AHORA
        IF (SELECT COUNT(*) FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN AND IMPRIMEIDALTERNA=2)>0
        BEGIN
           UPDATE RPDX SET NOMBRE=SER.CODCUM+'--'+SER.DESCSERVICIO
           FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
           WHERE SER.PREFIJO  = DBO.FnK_ValorVariable('PREFIJOMEDNOPOS')
           AND   COALESCE(SER.CODCUM,'')<>''
        END
      END   
      ELSE
      BEGIN
         --PRINT 'POR PAQUETE'
         SELECT @VCOPAGO = SUM(HPRED.VALORCOPAGO)
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
         WHERE  HPRE.NOADMISION = @NOADMISION
         INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO )
         SELECT @CNS_D, 'PAQUETE', HADM.IDSERVICIOPAQUETE, LEFT(SER.DESCSERVICIO,150), HADM.VLRSERVICIOPAQ, 1, 
                @VCOPAGO, HADM.VLRSERVICIOPAQ -@VCOPAGO, 'SERVICIOS'
         FROM   HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE = SER.IDSERVICIO
         WHERE  NOADMISION = @NOADMISION                      
      END
   END
   IF @TIPO = 7
   BEGIN
      PRINT '@CNS_D='+@CNS_D
      INSERT INTO RPDX (CNS, ID1, ID2,ID3, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4,VALOR5, IDTERCERO )
      SELECT @CNS_D, SER.PREFIJO,SER.IDALTERNA,HPRED.IDSERVICIO,LEFT(SER.DESCSERVICIO,150),                
               (SUM(HPRED.VALORCOPAGO)/SUM(HPRED.CANTIDAD)), SUM(HPRED.CANTIDAD),0,SUM(HPRED.VALORCOPAGO),SUM(COALESCE(FTRD.VIVA,0)), 'SERVICIOS'
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                     INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
                     LEFT  JOIN FTRD ON HPRED.NOPRESTACION=FTRD.NOPRESTACION AND HPRED.NOITEM=FTRD.NOITEM    AND FTRD.N_FACTURA=HPRED.N_FACTURAH               
      WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURAH = @CNS
      AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
      -- AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
      AND    COALESCE(HPRE.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      GROUP BY SER.PREFIJO,SER.IDALTERNA,HPRED.IDSERVICIO,SER.DESCSERVICIO
      ORDER BY SER.PREFIJO,SER.IDALTERNA,HPRED.IDSERVICIO,SER.DESCSERVICIO

      PRINT 'SE AGREGA EL TIPO DE ARTICULO'
      UPDATE RPDX SET ID2=LTRIM(RTRIM(ID2))+CASE WHEN COALESCE(IART.ENTREGA_TURNO,0)=1 THEN ' M ' ELSE ' G ' END 
      FROM RPDX INNER JOIN IART ON RPDX.ID3=IART.IDARTICULO
      WHERE RPDX.CNS=@CNS_D
      AND LTRIM(RTRIM(RPDX.ID1))=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS')
        PRINT '@CNS_D='+@CNS_D
        --PRINT 'REVISO PERU.... COPAGOS FIJOS'
        --IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
        --BEGIN
        --   DECLARE @ITEMSF INT
        --   SELECT  @ITEMSF= COUNT(*) 
        --   FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
        --                INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
        --   WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
        --   AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
        --   AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
        --   AND    COALESCE(HPRE.ANULADO, 0) = 0
        --   AND    COALESCE(HPRED.ANULADO, 0) = 0
        --   AND    COALESCE(HPRED.ENCARGOS, 0) = 0 
            
        --    IF COALESCE(@ITEMSF,0)=0
        --    BEGIN 
        --       IF EXISTS(SELECT * FROM FTRD WHERE N_FACTURA=@CNS AND NOADMISION=@NOADMISION)
        --       BEGIN
        --          INSERT INTO RPDX (CNS, ID1, ID2, ID3, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO,STRINGGRANDE1 )
        --          SELECT @CNS_D, FTRD.PREFIJO, FTRD.REFERENCIA, FTRD.IDARTICULO,
        --                 LEFT(FTRD.ANEXO,150),                
        --                 FTRD.VALOR, SUM(FTRD.CANTIDAD), 
        --                 SUM(FTRD.VLR_COPAGOS), SUM(FTRD.VLR_SERVICI), 'SERVICIOS',FTRD.ANEXO
        --          FROM  FTRD 
        --          WHERE  FTRD.NOADMISION = @NOADMISION AND FTRD.N_FACTURA = @CNS
        --          GROUP BY FTRD.PREFIJO, FTRD.REFERENCIA, FTRD.IDARTICULO, FTRD.ANEXO, FTRD.VALOR 
        --          ORDER BY PREFIJO
        --       END
        --   END
        --END
   END
   IF @TIPO = 8
   BEGIN
      UPDATE HPRED SET HPRED.VALOREXCEDENTE = HPRED.VALOR * HPRED.CANTIDAD - (HPRED.VALORPCOMP+HPRED.VALORCOPAGO)
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
      WHERE  HPRE.NOADMISION = @NOADMISION
      AND    COALESCE(HPRED.VALOREXCEDENTE,0) = 0
         
      PRINT '@CNS_D='+@CNS_D
      INSERT INTO RPDX (CNS, ID1, ID2,ID3, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4,VALOR5, IDTERCERO,STRINGGRANDE1 )
      SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO,HPRED.IDSERVICIO, 
               LEFT(SER.DESCSERVICIO,150),                
               FTRD.VALOR, SUM(HPRED.CANTIDAD), 
               SUM(HPRED.VALORCOPAGO),SUM(HPRED.VALORCOPAGO)+ SUM(HPRED.VALOREXCEDENTE),SUM(COALESCE(FTRD.VIVA,0)) ,'SERVICIOS',SER.DESCSERVICIO
      FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
                     INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
                     LEFT  JOIN FTRD ON HPRED.NOPRESTACION=FTRD.NOPRESTACION AND HPRED.NOITEM=FTRD.NOITEM AND HPRED.N_FACTURA=FTRD.N_FACTURA
      WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
      AND    COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
      AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
      AND    COALESCE(HPRE.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ANULADO, 0) = 0
      AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, FTRD.VALOR 
      ORDER BY PREFIJO,HPRED.IDSERVICIO, SER.DESCSERVICIO, FTRD.VALOR 

      -- FOMATO PARA PERU POR AHORA SE COMENTARIZA
      -- INSERTAMOS LOS NOCOBRABLES
      --INSERT INTO RPDX (CNS, ID1, ID2, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO,STRINGGRANDE1 )
      --SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, LEFT(SER.DESCSERVICIO,150), HPRED.VALOR, SUM(HPRED.CANTIDAD), 
      --         SUM(HPRED.VALORCOPAGO), SUM(HPRED.VALOREXCEDENTE), 'NOCOBRABLE',SER.DESCSERVICIO
      --FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
      --               INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
      --WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
      --AND    COALESCE(HPRED.NOCOBRABLE,0) <> 0
      --AND    COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
      --AND    COALESCE(HPRE.ANULADO, 0) = 0
      --AND    COALESCE(HPRED.ANULADO, 0) = 0
      --AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      --GROUP BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
      --ORDER BY SER.PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR 
         
      ----INSERTO CIRUGIAS
      --INSERT INTO RPDX (CNS, ID1, ID2, ID4, ID5, CANTIDAD, NOMBRE, VALOR1, VALOR2, VALOR3, VALOR4, IDTERCERO, FECHA1,STRINGGRANDE1 )
      --SELECT @CNS_D, SER.PREFIJO, HPRED.IDSERVICIO, COALESCE(HPRED.IDCIRUGIA,''), HPRED.CONSECUTIVOCX, HPRED.ITEMCIRUGIA, LEFT(SER.DESCSERVICIO,150), 
      --         HPRED.VALOR, HPRED.CANTIDAD, 
      --         HPRED.VALORCOPAGO, HPRED.VALOREXCEDENTE, 'PROCEDIMIENTOS', HPRE.FECHA,
      --         SER.DESCSERVICIO
      --FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION 
      --               INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
      --WHERE  HPRE.NOADMISION = @NOADMISION AND HPRED.N_FACTURA = @CNS
      --AND    COALESCE(HPRED.NOCOBRABLE,0)=(CASE @NOCOB WHEN 'SI' THEN COALESCE(HPRED.NOCOBRABLE,0) ELSE 0 END)
      --AND    COALESCE(HPRE.CIRUGIA,'No') = 'SI'
      --AND    COALESCE(HPRE.ANULADO, 0) = 0
      --AND    COALESCE(HPRED.ANULADO, 0) = 0
      --AND    COALESCE(HPRED.ENCARGOS, 0) = 0
      --ORDER BY HPRED.IDCIRUGIA, HPRED.CONSECUTIVOCX, HPREd.ITEMCIRUGIA
         
		
      /* OXIGENO */
      IF @PRE_OXIGENO<>'' AND (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_HORA')<>'SI'
      BEGIN
         UPDATE RPDX SET 
            VALOR1=RPDX.VALOR1/A.VALOR,
            VALOR2=A.VALOR*RPDX.VALOR2
         FROM RPDX 
            INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
            INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND HPRED.N_FACTURA=@CNS AND RPDX.ID2=HPRED.IDSERVICIO
            INNER JOIN SERTOT A ON HPRED.IDSERVICIO=A.IDSERVICIO AND HPRE.IDTERCEROCA=A.IDTERCERO AND HPRE.IDPLAN=A.IDPLAN
               AND HPRE.FECHA BETWEEN A.FECHAINI AND A.FECHAFIN AND HPRE.FECHA BETWEEN A.FECHAINIFD AND A.FECHAFINFD
               AND A.PREFIJO=@PRE_OXIGENO
         WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
         AND COALESCE(HPRED.NOCOBRABLE,0) = 0   --SIN NOCOBRABLES
         AND COALESCE(HPRE.CIRUGIA,'No') <> 'SI'
         AND COALESCE(HPRE.ANULADO, 0) = 0
         AND COALESCE(HPRED.ANULADO, 0) = 0
         AND COALESCE(HPRED.ENCARGOS, 0) = 0
         AND A.VALOR>0
            
         UPDATE RPDX SET NOMBRE=NOMBRE+' (Total litros: '+(CONVERT(VARCHAR(20),CONVERT(INT,ISNULL(SER.CANTMAXIMA,1)*VALOR2*60)))+')'
         FROM RPDX 
            INNER JOIN HPRE ON HPRE.NOADMISION=@NOADMISION AND HPRE.PREFIJO=@PRE_OXIGENO
            INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION AND RPDX.ID2=HPRED.IDSERVICIO
            INNER JOIN SER ON SER.IDSERVICIO=HPRED.IDSERVICIO
         WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
           
         IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='OXI_EN_MINUTOS')='SI'
         BEGIN
            UPDATE RPDX SET VALOR1=VALOR1/60, VALOR2=VALOR2*60
            FROM RPDX WHERE RPDX.CNS=@CNS_D AND ID1=@PRE_OXIGENO
         END
      END

      IF @FORMATOCODIGO=1 --IDALTERNA
      BEGIN
         IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
            UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT('['+ID2+'] '+NOMBRE,150)
            FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
            WHERE RPDX.CNS=@CNS_D
         ELSE
            UPDATE RPDX SET ID2=SER.IDALTERNA, NOMBRE=LEFT(NOMBRE,150)
            FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
            WHERE RPDX.CNS=@CNS_D
      END
      IF @FORMATOCODIGO=2 --CUM
      BEGIN
         UPDATE RPDX SET ID2=SER.CODCUM
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
      END
      IF @FORMATOCODIGO=3 --ATC
      BEGIN
         UPDATE RPDX SET ID2=SER.IDALTERNA
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
      END
      IF @FORMATOCODIGO=4 --ADRES
      BEGIN
         --UPDATE RPDX SET ID2=''
         --FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         --WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D

         UPDATE RPDX SET ID2=SER.CODSISPRO
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D


      END
      IF @FORMATOCODIGO=5 --SAVIA
      BEGIN
         UPDATE RPDX SET ID2=SER.CODSISPRO
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D

         UPDATE RPDX SET ID2=''
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNS_D
           
         UPDATE RPDX SET ID2=COALESCE(C.CODIGO,SER.CODCUPS)
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
            LEFT JOIN dbo.VWK_CUPS C ON C.IDSERVICIO=SER.IDSERVICIO AND C.IDTERCERO=@IDTERCEROHADM AND C.IDPLAN=@IDPLAN
         WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')) AND RPDX.CNS=@CNS_D



      END
      IF @FORMATOCODIGO=6 --SISPRO
      BEGIN
         UPDATE RPDX SET ID2=SER.CODSISPRO
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
      END
      IF @FORMATOCODIGO=7 --INVIMA
      BEGIN
         UPDATE RPDX SET ID2=COALESCE(IART.INVIMA,'')
         FROM SER 
            INNER JOIN RPDX ON SER.PREFIJO=ID1 AND SER.IDSERVICIO=RPDX.ID2
            LEFT JOIN (
               SELECT IDSERVICIO, MAX(REGINVIMA) INVIMA
               FROM IART
               WHERE COALESCE(REGINVIMA,'') LIKE '%-%' AND LEN(REGINVIMA)>5
                  AND ESTADO='Activo'
               GROUP BY IDSERVICIO
            )IART ON SER.IDSERVICIO=IART.IDSERVICIO
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNS_D
      END
     PRINT 'SE AGREGA EL TIPO DE ARTICULO'
     UPDATE RPDX SET ID2=LTRIM(RTRIM(ID2))+CASE WHEN COALESCE(IART.ENTREGA_TURNO,0)=1 THEN ' M ' ELSE ' G ' END 
     FROM RPDX INNER JOIN IART ON RPDX.ID3=IART.IDARTICULO
     WHERE RPDX.CNS=@CNS_D
     AND RPDX.ID1=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS')
   END
END

