CREATE OR ALTER FUNCTION DBO.FNK_DEHTML_A_TEXTO(@HTML VARCHAR(MAX))
RETURNS VARCHAR(MAX)
AS
BEGIN
   DECLARE @TEXTO VARCHAR(MAX)
   SELECT @TEXTO=@HTML
   SET @TEXTO=REPLACE(@TEXTO,'<span style="white-space:pre">','')
   SET @TEXTO=REPLACE(@TEXTO,'</span>','')
   SET @TEXTO=REPLACE(@TEXTO,'&NBSP;',' ');
   SET @TEXTO=REPLACE(@TEXTO,'NOTE:','');
   DECLARE @STARTTAG VARCHAR(25) = '%[<]%'
   DECLARE @ENDTAG VARCHAR(25) = '%[>]%'
   DECLARE @ENDTAGINDEX INT =0;
   DECLARE @STARTTAGINDEX INT =0;
   WHILE PATINDEX(@STARTTAG,@TEXTO)>0
   BEGIN
       SET @STARTTAGINDEX=PATINDEX(@STARTTAG,@TEXTO);
       SET @ENDTAGINDEX=PATINDEX(@ENDTAG,@TEXTO);
       SET @TEXTO = STUFF(@TEXTO,@STARTTAGINDEX,(@ENDTAGINDEX-@STARTTAGINDEX)+1,'');
   END

   RETURN @TEXTO
END

