CREATE OR ALTER VIEW VWK_HCADX_PIVOT
AS
SELECT CONSECUTIVO,
MAX(CASE WHEN ID =1 THEN IDDX END) AS DX1,
MAX(CASE WHEN ID =1 THEN DESCRIPCION END) AS NDX1,
MAX(CASE WHEN ID =2 THEN IDDX END) AS DX2,
MAX(CASE WHEN ID =2 THEN DESCRIPCION END) AS NDX2,
MAX(CASE WHEN ID =3 THEN IDDX END) AS DX3,
MAX(CASE WHEN ID =3 THEN DESCRIPCION END) AS NDX3,
MAX(CASE WHEN ID =4 THEN IDDX END) AS DX4,
MAX(CASE WHEN ID =4 THEN DESCRIPCION END) AS NDX4,
MAX(CASE WHEN ID =5 THEN IDDX END) AS DX5,
MAX(CASE WHEN ID =5 THEN DESCRIPCION END) AS NDX5,
MAX(CASE WHEN ID =6 THEN IDDX END) AS DX6,
MAX(CASE WHEN ID =6 THEN DESCRIPCION END) AS NDX6,
MAX(CASE WHEN ID =7 THEN IDDX END) AS DX7,
MAX(CASE WHEN ID =7 THEN DESCRIPCION END) AS NDX7,
MAX(CASE WHEN ID =8 THEN IDDX END) AS DX8,
MAX(CASE WHEN ID =8 THEN DESCRIPCION END) AS NDX8,
MAX(CASE WHEN ID =9 THEN IDDX END) AS DX9,
MAX(CASE WHEN ID =9 THEN DESCRIPCION END) AS NDX9,
MAX(CASE WHEN ID =10 THEN IDDX END) AS DX10,
MAX(CASE WHEN ID =10 THEN DESCRIPCION END) AS NDX10
FROM(
    SELECT CONSECUTIVO,ROW_NUMBER() OVER(PARTITION BY CONSECUTIVO ORDER BY CONSECUTIVO DESC) ID, 
    HCADX.IDDX,MDX.DESCRIPCION
    FROM HCADX INNER JOIN MDX ON HCADX.IDDX=MDX.IDDX ) HCADX
GROUP BY CONSECUTIVO;