CREATE OR ALTER PROCEDURE DBO.SPQ_INFOMRES_INV @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@IDARTICULO VARCHAR(20)            ,@PCOSTO   DECIMAL(14,2)          ,@IDBODEGA VARCHAR(20)
      ,@TIPOMOV VARCHAR(20)               ,@F_INICIAL DATETIME              ,@F_FINAL DATETIME
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='IBOD_ITAR'     
   BEGIN         
      SELECT 'OK' OK
      SELECT IDBODEGA as value, DESCRIPCION AS label FROM IBOD
      WHERE EXISTS(SELECT * FROM IEXI WHERE IEXI.IDBODEGA=IBOD.IDBODEGA)
      AND IBOD.ESTADO='Activo'
      ORDER BY IBOD.IDBODEGA

      SELECT IDITAR AS value, DESCRIPCION AS label
      FROM ITAR 
      ORDER BY IDITAR ASC

      RETURN
    END   
   IF @METODO='IBOD_ITMO'     
   BEGIN         
      SELECT 'OK' OK
      SELECT IDBODEGA as value, DESCRIPCION AS label FROM IBOD
      WHERE EXISTS(SELECT * FROM IEXI WHERE IEXI.IDBODEGA=IBOD.IDBODEGA)
      AND IBOD.ESTADO='Activo'
      ORDER BY IBOD.IDBODEGA

      SELECT IDTIPOMOV AS value, DESCRIPCION AS label
      FROM ITMO 
      ORDER BY IDTIPOMOV ASC

      RETURN
    END 
   IF @METODO='TRAE_EXISTS'     
   BEGIN         
      SELECT @IDARTICULO=IDARTICULO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          IDARTICULO VARCHAR(20) '$.IDARTICULO'
            )    
      IF COALESCE(@IDARTICULO,'')<>'' AND EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
      BEGIN
         SELECT @PCOSTO=PCOSTO FROM IART WHERE IDARTICULO=@IDARTICULO
         SELECT 'OK'OK,@PCOSTO PCOSTO 

         SELECT IEXI.IDBODEGA,IBOD.DESCRIPCION,SUM(IEXI.EXISLOTE)CANTIDAD
         FROM IEXI INNER JOIN IBOD ON IEXI.IDBODEGA=IBOD.IDBODEGA
         WHERE IDARTICULO=@IDARTICULO
         AND EXISLOTE>0
         GROUP BY IEXI.IDBODEGA,IBOD.DESCRIPCION

         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO'KO
         RETURN
      END
        
   END   
   IF @METODO='BUSCAR_MOV'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      
         SELECT @IDBODEGA=IDBODEGA,   @TIPOMOV=TIPOMOV,  @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDARTICULO=IDARTICULO     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         IDBODEGA VARCHAR(20)       '$.IDBODEGA',
         TIPOMOV VARCHAR(20)       '$.TIPOMOV',
         F_INICIAL DATETIME        '$.F_INICIAL',
         F_FINAL DATETIME          '$.F_FINAL',
         IDARTICULO VARCHAR(20)    '$.IDARTICULO'       
         ) 
         IF EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
         BEGIN
            SELECT 'OK' OK
            PRINT 'Entradas'
            SELECT IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION, SUM(IMOVH.CANTIDAD)CANTIDAD, SUM(ISNULL(IMOVH.PCOSTO,0)) PCOSTO
            FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV  
                     INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV 
            WHERE IMOV.ESTADO=1 AND IMOVH.ESTADO=1 AND ITMO.TIPO='Credito' 
            AND   IMOVH.IDARTICULO=@IDARTICULO
            AND   IMOV.IDBODEGA=CASE WHEN COALESCE(@IDBODEGA,'Todas') <> 'Todas' THEN @IDBODEGA ELSE IMOV.IDBODEGA END 
            AND   IMOV.IDTIPOMOV=CASE WHEN COALESCE(@TIPOMOV,'Todos') <> 'Todos' THEN  @TIPOMOV ELSE IMOV.IDTIPOMOV END 
            AND   IMOV.FECHACONF>=@F_INICIAL
            AND   IMOV.FECHACONF<@F_FINAL+1
            GROUP BY IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION 

            PRINT 'SALIDAS'

            SELECT IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION, SUM(ISAL.CANTIDAD)CANTIDAD, SUM(ISNULL(ISAL.PCOSTO,0)) PCOSTO
            FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV                       
                     INNER JOIN ITMO ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV                 
            WHERE IMOV.ESTADO=1 AND ITMO.TIPO='Debito'                               
            AND   ISAL.IDARTICULO=@IDARTICULO
            AND   IMOV.IDBODEGA=CASE WHEN COALESCE(@IDBODEGA,'Todas') <> 'Todas' THEN @IDBODEGA ELSE IMOV.IDBODEGA END 
            AND   IMOV.IDTIPOMOV=CASE WHEN COALESCE(@TIPOMOV,'Todos') <> 'Todos' THEN  @TIPOMOV ELSE IMOV.IDTIPOMOV END 
            AND   IMOV.FECHACONF>=@F_INICIAL
            AND   IMOV.FECHACONF<@F_FINAL+1
            GROUP BY IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION 
         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO'KO
         RETURN
      END
   END   
   IF @METODO='DETALLE_ENTRADA'     
   BEGIN         
      SELECT @DATOS=DATOS,@IDBODEGA=IDBODEGA,@TIPOMOV=IDTIPOMOV       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON ,
         IDBODEGA VARCHAR(20) '$.IDBODEGA',
         IDTIPOMOV VARCHAR(20) '$.IDTIPOMOV'
            )           
         PRINT '@IDBODEGA ='+@IDBODEGA
         PRINT '@TIPOMOV ='+@TIPOMOV
         SELECT @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDARTICULO=IDARTICULO     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         F_INICIAL DATETIME        '$.F_INICIAL',
         F_FINAL DATETIME          '$.F_FINAL',
         IDARTICULO VARCHAR(20)    '$.IDARTICULO'       
         ) 
         IF EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
         BEGIN
            SELECT 'OK'OK
            IF @TIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS') OR @TIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_REMISION_EN')
            BEGIN
               PRINT 'Compras de Farmacia'
               SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
                      CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO)PCOSTO,IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,TER.NIT,TER.RAZONSOCIAL 
               FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                         INNER JOIN TER ON IMOV.IDTERCERO=TER.IDTERCERO
               WHERE IMOV.IDBODEGA=@IDBODEGA
               AND IMOV.IDTIPOMOV=@TIPOMOV
               AND IMOV.FECHACONF>=@F_INICIAL
               AND IMOV.FECHACONF<@F_FINAL+1
               AND IMOV.ESTADO=1
               RETURN
            END
            ELSE
            BEGIN
               PRINT 'OTROS MOVIMIENTOS'
               SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
               CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO),IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,AFI.DOCIDAFILIADO,AFI.NOMBREAFI
                     FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                               LEFT  JOIN HADM ON IMOV.NODOCUMENTO=HADM.NOADMISION
                               LEFT JOIN AFI   ON HADM.IDAFILIADO=AFI.IDAFILIADO
               WHERE IMOV.IDBODEGA=@IDBODEGA
               AND IMOV.IDTIPOMOV=@TIPOMOV
               AND IMOV.FECHACONF>=@F_INICIAL
               AND IMOV.FECHACONF<@F_FINAL+1
               AND IMOV.ESTADO=1
               AND IMOV.PROCEDENCIA<>'INV'
               UNION ALL
               SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
                      CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO),IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,TER.NIT,TER.RAZONSOCIAL 
               FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                         INNER JOIN TER ON IMOV.IDTERCERO=TER.IDTERCERO
               WHERE IMOV.IDBODEGA=@IDBODEGA
               AND IMOV.IDTIPOMOV=@TIPOMOV
               AND IMOV.FECHACONF>=@F_INICIAL
               AND IMOV.FECHACONF<@F_FINAL+1
               AND IMOV.ESTADO=1
            END
         END
      END
   IF @METODO='DETALLE_SALIDA'     
   BEGIN         
      SELECT @DATOS=DATOS,@IDBODEGA=IDBODEGA,@TIPOMOV=IDTIPOMOV       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON ,
         IDBODEGA VARCHAR(20) '$.IDBODEGA',
         IDTIPOMOV VARCHAR(20) '$.IDTIPOMOV'
            )           
         PRINT '@IDBODEGA ='+@IDBODEGA
         PRINT '@TIPOMOV ='+@TIPOMOV
         SELECT @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDARTICULO=IDARTICULO     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         F_INICIAL DATETIME        '$.F_INICIAL',
         F_FINAL DATETIME          '$.F_FINAL',
         IDARTICULO VARCHAR(20)    '$.IDARTICULO'       
         ) 
         IF EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
         BEGIN
            SELECT 'OK'OK
            PRINT 'SALIDAS DE INVENTARIO'
            SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
            CONVERT(INT,ISAL.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),ISAL.PCOSTO),ISAL.NOLOTE,ISAL.NOLOTEPEDIDO,IMOV.NODOCUMENTO,IMOV.CNSMOV,AFI.DOCIDAFILIADO,AFI.NOMBREAFI
                  FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
                              INNER JOIN IZSOL ON IMOV.NODOCUMENTO=IZSOL.CNSIZSOL
                              LEFT  JOIN HADM ON IZSOL.NOADMISION=HADM.NOADMISION
                              LEFT JOIN AFI   ON HADM.IDAFILIADO=AFI.IDAFILIADO
            WHERE IMOV.IDBODEGA=@IDBODEGA
            AND IMOV.IDTIPOMOV=@TIPOMOV
            AND IMOV.FECHACONF>=@F_INICIAL
            AND IMOV.FECHACONF<@F_FINAL+1
            AND IMOV.ESTADO=1
            AND IMOV.PROCEDENCIA='CM_SOL'
            UNION ALL
            SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
                     CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO),IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,TER.NIT,TER.RAZONSOCIAL 
            FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                        INNER JOIN TER ON IMOV.IDTERCERO=TER.IDTERCERO
            WHERE IMOV.IDBODEGA=@IDBODEGA
            AND IMOV.IDTIPOMOV=@TIPOMOV
            AND IMOV.FECHACONF>=@F_INICIAL
            AND IMOV.FECHACONF<@F_FINAL+1
            AND IMOV.ESTADO=1
            AND IMOV.PROCEDENCIA='INV'

         END
      END
END

