IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IDFORMATOFTR_BOLETA')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IDFORMATOFTR_BOLETA','Formato Facturacion Boletas de Venta','Alfanumerica',''
END
