IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IMP_SIN_DECIMAL_FTR')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IMP_SIN_DECIMAL_FTR','Imprime Facturas sin decimales SI|NO Eje 0,00 -> 0','Alfanumerica',''
END