SELECT * FROM #A

UPDATE #A SET FINGRESO=REPLACE(FINGRESO,'&','/'),FNACIMIENTO=REPLACE(FNACIMIENTO,'&','/')

ALTER TABLE #A ALTER COLUMN FNACIMIENTO DATETIME

06S0000221

SELECT * INTO #B FROM  #A WHERE NOT EXISTS(SELECT * FROM TER WHERE TER.NIT=#A.NIT)

ALTER TABLE #B ADD ID INT IDENTITY(1,1)

ALTER TABLE #B ADD IDTERCERO VARCHAR(20)

UPDATE #B SET IDTERCERO='06S0000'+CAST((221+ID) AS VARCHAR(4))

SELECT * FROM #B

SELECT  * FROM TER WHERE NIT='39177602'

SELECT DBO.FNK_SEPARA_NOMBRES('JOSE MANUEL JIMENEZ BUSTOS',3)

INSERT INTO TER (IDTERCERO,TIPO_ID,RAZONSOCIAL,NIT,TELEFONOS,DIRECCION,NATJURIDICA,CIUDAD,ESTADO,ENVIODICAJA,MODOCOPAGO,IDACTIVIDAD,EMAIL,TIPOREGIMEN,FORMAPRE,COD_RESP_FISCAL,MANEXO,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,DV)
SELECT IDTERCERO,TIPODOC,RAZONSOCIAL,NIT,TELEFONO,DIRECCION,'Natural','05001','Activo',0,'Normal','8699',EMAIL,'S','N','R-99-PN',0,DBO.FNK_SEPARA_NOMBRES(RAZONSOCIAL,1),
DBO.FNK_SEPARA_NOMBRES(RAZONSOCIAL,2),DBO.FNK_SEPARA_NOMBRES(RAZONSOCIAL,3),DBO.FNK_SEPARA_NOMBRES(RAZONSOCIAL,4),DBO.FNK_CALCULA_DV(NIT)
FROM #B

SELECT * INTO #C FROM NEMP WHERE EXISTS(SELECT * FROM #A WHERE NEMP.DOCIDEMPLEADO=#A.NIT)

SELECT  *  FROM #C

ALTER TABLE #G ADD ID INT IDENTITY(1,1)

ALTER TABLE #C ADD NUMDOCNVO VARCHAR(20)

UPDATE #C SET FECHAINGRESO='30/10/2024',FECHARETIRO=NULL,BASICO=0,CODCARGO=NULL,NIVEL=NULL,GRADO=NULL,HORASDELABOR=NULL,DIASXCARGO=NULL,CODPLANTA=NULL

SELECT DBO.FNK_COLUMNAS_TABLAS('NPRFED')

INSERT INTO NEMP(NUMDOC, SEXO, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR,  DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL,  FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, CODUNG, CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, EMAIL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TIPO_DOC, DOCIDEMPLEADO, TERCEROID)
SELECT NUMDOCNVO, SEXO, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR,  DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL,  FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, CODUNG, CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, EMAIL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TIPO_DOC, DOCIDEMPLEADO, TERCEROID
FROM #C

SELECT * FROM NOMIE

INSERT INTO NPRFED(NUMDOC, CODPRF, ITEM, FECHAINI, IDTERCERO)
SELECT #C.NUMDOCNVO,NPRFED.CODPRF,1,'30/10/2024',NPRFED.IDTERCERO  FROM NPRFED INNER JOIN #C ON NPRFED.NUMDOC=#C.NUMDOC

INSERT INTO NOMIE(CODNOMINA,NUMDOC,ESTADO)
SELECT '06',NUMDOCNVO,'Activo' FROM #C


ALTER TABLE #G ADD NUMDOCNVO VARCHAR(20)

SELECT  * FROM #G

ALTER TABLE #G ADD SEXO VARCHAR(20)

UPDATE #G SET SEXO=CASE WHEN #E.SEXO='M' THEN 'Masculino' ELSE 'Femenino' END
FROM #G INNER JOIN #E ON #G.NIT=#E.NIT

UPDATE #G SET NUMDOCNVO='070000000'+CAST((98+ID) AS VARCHAR(3)) WHERE ID=2
--
SELECT DBO.FNK_COLUMNAS_TABLAS('NEMP')
INSERT INTO NEMP(NUMDOC, SEXO, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR,  DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL,  FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, CODUNG, CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, EMAIL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TIPO_DOC, DOCIDEMPLEADO, TERCEROID)
SELECT #G.NUMDOCNVO, #G.SEXO, PNOMBRE, SNOMBRE, PAPELLIDO, SAPELLIDO, NULL, NULL, '30/10/2024', 'Activo', null, NULL, NULL, NULL, NULL, NULL, NULL,  NULL, NULL, TIPOSALARIO, NULL, NULL, NULL, NULL, NULL, NULL, TIPOCONTRATO, CODNOMINA, NULL, NULL, NULL,
#G.FNACIMIENTO, NULL, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, CODUNG, CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, #G.EMAIL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TER.TIPO_ID, TER.NIT, TER.IDTERCERO
FROM #G INNER JOIN TER ON #G.NIT=TER.NIT,#D


INSERT INTO NOMIE(CODNOMINA,NUMDOC,ESTADO)
SELECT '07',NUMDOCNVO,'Activo' FROM #B

SELECT * FROM #D

INSERT INTO NPRFE
SELECT #B.NUMDOCNVO,CODPRF  FROM NPRFE,#B  WHERE NUMDOC='060000000181'


SELECT * FROM NEMP WHERE DOCIDEMPLEADO='1004801793'
 
 DELETE NEMP WHERE NUMDOC='070000000103'

 DROP TABLE #H

 SELECT  NEMP.* INTO #H
 FROM #A LEFT JOIN NEMP ON #A.NIT=NEMP.DOCIDEMPLEADO
 WHERE NEMP.CODPLANTA IS NULL
 
 
 SELECT * FROM #G INNER JOIN TER ON #G.NIT=TER.NIT

SELECT * FROM #A WHERE RAZONSOCIAL='URRUTIA MENA KELBIN ALEXANDER'

UPDATE #A SET NIT='1020456337' WHERE RAZONSOCIAL='URRUTIA MENA KELBIN ALEXANDER'

UPDATE NEMP SET DOCIDEMPLEADO='1020456337' WHERE NUMDOC='070000000102'

SELECT *
FROM #A INNER  JOIN #H ON #A.NIT=#H.DOCIDEMPLEADO
        INNER JOIN #I ON #A.CARGO=#I.CARGODES

        SELECT * FROM #I

UPDATE #H SET CODCARGO=#I.CODCARGO,NIVEL=#I.NIVEL,GRADO=#I.GRADO
FROM #A INNER  JOIN #H ON #A.NIT=#H.DOCIDEMPLEADO
        INNER JOIN #I ON #A.CARGO=#I.CARGODES

        SELECT * FROM #H WHERE CODCARGO IS NULL

        UPDATE #H SET CODCARGO='11',NIVEL='1',GRADO='24' WHERE NUMDOC='070000000100'

        SELECT NUMDOC, FROM #A

        SELECT * FROM NPLA
        
        SELECT #H.NUMDOC,#H.CODCARGO,#H.GRADO,#H.NIVEL,CEN.IDAREA,#K.CCOSTO,#K.SEDE,#K.CODUNG INTO #L
        FROM #H INNER JOIN #K ON #H.DOCIDEMPLEADO=#K.NIT
                LEFT JOIN CEN ON #K.CCOSTO=CEN.CCOSTO


                ALTER TABLE #L ADD ID INT IDENTITY(1,1)

                SELECT * FROM #L

                ALTER TABLE #L ADD CODPLANTA VARCHAR(20)

                UPDATE #L SET CODPLANTA='07000000'+CAST(ID AS VARCHAR(3)) WHERE ID>=100 AND CODCARGO IS NOT NULL

                SELECT DBO.FNK_COLUMNAS_TABLAS('NPLA')

                INSERT INTO NPLA(CODPLANTA, IDAREA, CCOSTO, CODCARGO, NIVEL, GRADO, NUMDOC, IDSEDE, CODUNG)
                SELECT CODPLANTA, IDAREA, CCOSTO, CODCARGO, NIVEL, GRADO, NUMDOC, SEDE, CODUNG
                FROM #L
                WHERE CODPLANTA IS NOT NULL

                SELECT  * FROM #H
                SELECT  * FROM NCARNGV

                UPDATE #H SET CODPLANTA=#L.CODPLANTA,CCOSTO=#L.CCOSTO,BASICO=X.BASICO,HORASDELABOR=X.HORASDELABOR,DIASXCARGO=X.DIAS,IDAREA=#L.IDAREA
                FROM #H INNER JOIN #L ON #H.NUMDOC=#L.NUMDOC
                          INNER JOIN NCARNGV X ON #H.CODCARGO=X.CODCARGO AND #H.GRADO=X.GRADO AND #H.NIVEL=X.NIVEL
                WHERE #L.CODPLANTA IS NOT NULL


                UPDATE NEMP SET CODCARGO=#H.CODCARGO,GRADO=#H.GRADO,NIVEL=#H.NIVEL,CODPLANTA=#H.CODPLANTA,CCOSTO=#H.CCOSTO,BASICO=#H.BASICO,HORASDELABOR=#H.HORASDELABOR,DIASXCARGO=#H.DIASXCARGO,IDAREA=#H.IDAREA
                FROM NEMP INNER JOIN #H ON NEMP.NUMDOC=#H.NUMDOC
                WHERE #H.CODPLANTA IS NOT NULL


                SELECT DBO.FNK_COLUMNAS_TABLAS('NEMPHIS')

                INSERT INTO NEMPHIS(NUMDOC, FECHAMOV, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO,  TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50,  ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, USUARIOMOD, FECHAMOD, SYS_COMPUTERNAME, OPERACION)
                SELECT NUMDOC, '30/10/2024', SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO,  TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50,  ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, 'SOPORTE', '30/10/2024', 'SOPORTE', 'INSERT'
                FROM #H
                WHERE  CODPLANTA IS NOT NULL




USE KUNIPSSAM

SELECT * FROM FCJ WHERE CNSFACJ ='E00000847' AND CODCAJA='004'

UPDATE FCJ SET CERRADA=0 WHERE CNSFACJ ='E00000847' AND CODCAJA='004'

DELETE PCJ WHERE CNSFACJ ='E00000847' AND CODCAJA='004'

SELECT  * FROM CAJR WHERE CODCAJA='004'


UPDATE CAJR SET VALOR=55987 WHERE CODCAJA='004'