IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_NOMINA' AND IDCONTROL='CertiLaborales')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,DESCRIPCION,TIPO,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGO,PAISES)
   SELECT 'MENUQ_NOMINA','CertiLaborales','Cetificados Laborales','M',1,'nom.certiLab','fa-solid fa-user-tie',NULL,0,0,930,'Control Certificados',NULL,NULL
END