IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURA_ASIS' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURA_ASIS
END

GO
CREATE PROCEDURE DBO.SPK_FACTURA_ASIS
@NOADMISION       VARCHAR(16),
@NIT              VARCHAR(20),
@COMPANIA         VARCHAR(2),
@IDSEDE           VARCHAR(5),
@USUARIO          VARCHAR(12), 
@SYS_COMPUTERNAME VARCHAR(254),
@CNSRPDX          VARCHAR(20),
@ITEM             INT,
@TFECHA           SMALLINT = 0,
@FECHAFAC         DATETIME = NULL
WITH ENCRYPTION
AS      
DECLARE @NVOCONSEC     VARCHAR(20), @PRE VARCHAR(20), @CONSECFTR INT, @CNSRESOL VARCHAR(50)
DECLARE @NVOCONSEC1    VARCHAR(20)
DECLARE @CNSFTR        VARCHAR(20)
DECLARE @CERRADA       SMALLINT
DECLARE @FACTURADA     SMALLINT
DECLARE @FACTURABLE    SMALLINT
DECLARE @TIPOADM       VARCHAR(2)
DECLARE @IDTERCERO     VARCHAR(20)
DECLARE @IDPLAN        VARCHAR(6)
DECLARE @DATO          VARCHAR(80)
DECLARE @DATO1         VARCHAR(80)
DECLARE @DATO3         VARCHAR(80)
DECLARE @IDTERCERO1    VARCHAR(20)  
DECLARE @OK            INT
DECLARE @CA            VARCHAR(1)
DECLARE @IDAFILIADO    VARCHAR(20)
DECLARE @DV            SMALLINT
DECLARE @TV            VARCHAR(10)
DECLARE @CCOSTO_ALTA   VARCHAR(20)
DECLARE @IDAREA_ALTA   VARCHAR(20)
DECLARE @EC            SMALLINT
DECLARE @IDTERCEROF    VARCHAR(20)
DECLARE @IDTERPART     VARCHAR(20)
DECLARE @DESCUENTO     DECIMAL(14,2)
DECLARE @TIPODTO       VARCHAR(1)
DECLARE @VRTOTAL       DECIMAL(14,2)
DECLARE @VRSERV            DECIMAL(14,2)
DECLARE @VRCOPA            DECIMAL(14,2)
DECLARE @VRPACO            DECIMAL(14,2)
DECLARE @VRDTO             DECIMAL(14,2)
DECLARE @VRABONO           DECIMAL(14,2)
DECLARE @VEZ               INT
DECLARE @TIENE             INT
DECLARE @TOTALFACTURA      DECIMAL(14,2)
DECLARE @MPREFIJOS         SMALLINT
DECLARE @TERCEROPREFIJOS   SMALLINT
DECLARE @VARIASF           SMALLINT
DECLARE @NOFACTURAS        INT
DECLARE @CONTROLDEF        INT
DECLARE @ESGLOBAL          SMALLINT
DECLARE @TERCEROGLOBAL     SMALLINT
DECLARE @TTEC              VARCHAR(10)
DECLARE @VLRDEVOLUCION     DECIMAL(14,2)
DECLARE @CUENTACXC         VARCHAR(16)
DECLARE @CUENTACXC_RAD     VARCHAR(16)
DECLARE @DATOCCOSTO        VARCHAR(80) 
DECLARE @DATOFAC           VARCHAR(20)
DECLARE @AUX1              INT
DECLARE @AUX               INT
DECLARE @DESCRIPCION       VARCHAR(80)
DECLARE @NODESCUENTACOPAGO SMALLINT
DECLARE @CODUNG            VARCHAR(2)
DECLARE @CODPRG            VARCHAR(2)
DECLARE @PAQUETE           SMALLINT
DECLARE @LIBERADA          VARCHAR(2)=''
DECLARE @IDCATEGORIA       VARCHAR(10)
DECLARE @IDFORMATOFTR      VARCHAR(20)
DECLARE @VALOREXT          DECIMAL(14,2)
DECLARE @OBSERVACION       VARCHAR(2040)
DECLARE @NROAUTORIZAC      VARCHAR(20)
DECLARE @MONTO             DECIMAL(14,2)
BEGIN  
	SELECT @EC = 0
	SELECT @PAQUETE = COALESCE(PAQUETE,0) FROM HADM WHERE NOADMISION = @NOADMISION
	IF DBO.FNK_VALORVARIABLE('MMCORPORATIVO') = 'SI'
	BEGIN
		IF DBO.FNK_VALORVARIABLE('CUF_CPF_DE_SEDE') = 'SI'
		BEGIN
			SELECT @CODUNG = DBO.FNK_CODUNG_CODPRG(@USUARIO,'CODUNG')
			SELECT @CODPRG = DBO.FNK_CODUNG_CODPRG(@USUARIO,'CODPRG')
		END
	END
	Print '@FECHAFAC =' + cast(@FECHAFAC as varchar(20))
	-- SACAR DE DONDE SE TOMA EL CCOSTO
	SELECT @DATOCCOSTO =  DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
	--SELECT DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
	SELECT @CERRADA    = CERRADA,      @FACTURADA   = FACTURADA,   @FACTURABLE  = FACTURABLE,
			@TIPOADM    = TIPOADM,      @IDAFILIADO = AFI.IDAFILIADO, @IDAREA_ALTA = IDAREA_ALTA, 
			@CCOSTO_ALTA = CCOSTO_ALTA
	FROM   HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO WHERE NOADMISION = @NOADMISION 
	PRINT  'HICE SELECCION'

	IF DBO.FNK_VALORVARIABLE('FACTSEDE') = 'SI'
	BEGIN
		SELECT @IDSEDE = IDSEDE FROM   HADM WHERE NOADMISION = @NOADMISION 
		IF DBO.FNK_VALORVARIABLE('FACTSEDEEQUIPO') = 'SI'
		BEGIN         
			IF COALESCE(@SYS_COMPUTERNAME,'') = ''
			BEGIN
				SELECT @SYS_COMPUTERNAME = HOST_NAME()
			END
			SELECT @IDSEDE = IDSEDE FROM UBEQ WHERE SYS_COMPUTERNAME = @SYS_COMPUTERNAME
		END
	END

	SELECT @IDTERCERO = IDTERCERO, @IDPLAN = ID1, @AUX1 = CANTIDAD1, @AUX = CANTIDAD, @DESCRIPCION = NOMBRE,
          @NROAUTORIZAC=ID10
	FROM   RPDX 
	WHERE  CNS  = @CNSRPDX 
	AND    ITEM = @ITEM

	PRINT '@AUX1='+ STR(@AUX1)
	PRINT '@NOADMISION='+@NOADMISION
	PRINT '@IDTERCERO='+@IDTERCERO
	PRINT '@IDPLAN  ='+@IDPLAN
	PRINT '@AUX = '+STR(@AUX)

	IF @AUX1 = 0
	BEGIN
		SELECT @TIENE = COUNT(*), @VALOREXT=SUM(ISNULL(VALORCOPAGOEXTERNO,0))
		FROM HPRE, HPRED
		WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
		AND    HPRE.NOADMISION   = @NOADMISION
		AND    HPRED.IDTERCEROCA = @IDTERCERO
		AND    COALESCE(HPRED.FACTURADA,0)   = 0
		AND    COALESCE(HPRED.N_fACTURA,'')=''
		AND    HPRED.IDPLAN      = @IDPLAN     
		AND    COALESCE(HPRE.ANULADO,0)    = 0 --SJUNCO REQ 1803
		AND    COALESCE(HPRED.ANULADO,0)   = 0 --SJUNCO REQ 1803 
		AND    COALESCE(HPRED.ENCARGOS, 0) = 0
	END
	IF @AUX1 = 1
	BEGIN
		SELECT @TIENE = COUNT(*), @VALOREXT=SUM(ISNULL(VALORCOPAGOEXTERNO,0)) 
		FROM HPRE, HPRED
		WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
		AND    HPRE.NOADMISION   = @NOADMISION
		AND    HPRED.IDTERCEROCA = @IDTERCERO
		AND    COALESCE(HPRED.FACTURADA,0)   = 0
		AND    COALESCE(HPRED.N_fACTURA,'')=''
		AND    HPRED.IDPLAN      = @IDPLAN
		AND    HPRE.IDAREA IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
								AND    PPTFTRD.IDPLAN = @IDPLAN AND ITEM = @AUX)
		AND    ISNULL(HPRE.ANULADO,0)      = 0 --SJUNCO REQ 1803
		AND    ISNULL(HPRED.ANULADO,0)     = 0 --SJUNCO REQ 1803
		AND    COALESCE(HPRED.ENCARGOS, 0) = 0
	END
	IF @AUX1 = 2
	BEGIN
		SELECT @TIENE = COUNT(*), @VALOREXT=SUM(ISNULL(VALORCOPAGOEXTERNO,0))
		FROM HPRE, HPRED
		WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
		AND    HPRE.NOADMISION   = @NOADMISION
		AND    HPRED.IDTERCEROCA = @IDTERCERO
		AND    COALESCE(HPRED.FACTURADA,0)   = 0
		AND    COALESCE(HPRED.N_fACTURA,'')=''
		AND    HPRED.IDPLAN      = @IDPLAN
		AND    HPRE.IDAREA NOT IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
									AND PPTFTRD.IDPLAN = @IDPLAN)
		AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
		AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
		AND    COALESCE(HPRED.ENCARGOS, 0) = 0
	END
	IF @AUX1 = 3
	BEGIN
		SELECT @TIENE = COUNT(*), @VALOREXT=SUM(ISNULL(VALORCOPAGOEXTERNO,0)) 
		FROM HPRE, HPRED
		WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
		AND    HPRE.NOADMISION   = @NOADMISION
		AND    HPRED.IDTERCEROCA = @IDTERCERO
		AND    COALESCE(HPRED.FACTURADA,0)   = 0
		AND    COALESCE(HPRED.N_fACTURA,'')=''
		AND    HPRED.IDPLAN      = @IDPLAN
		AND    HPRE.CCOSTO IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
								AND    PPTFTRD.IDPLAN = @IDPLAN AND ITEM = @AUX)
		AND    ISNULL(HPRE.ANULADO,0)      = 0  --SJUNCO REQ 1803
		AND    ISNULL(HPRED.ANULADO,0)     = 0 --SJUNCO REQ 1803
		AND    COALESCE(HPRED.ENCARGOS, 0) = 0
	END
	IF @AUX1 = 4
	BEGIN
		SELECT @TIENE = COUNT(*), @VALOREXT=SUM(ISNULL(VALORCOPAGOEXTERNO,0)) 
		FROM HPRE, HPRED
		WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION
		AND    HPRE.NOADMISION   = @NOADMISION
		AND    HPRED.IDTERCEROCA = @IDTERCERO
		AND    COALESCE(HPRED.FACTURADA,0)   = 0
		AND    COALESCE(HPRED.N_fACTURA,'')=''
		AND    HPRED.IDPLAN      = @IDPLAN
		AND    HPRE.CCOSTO NOT IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
									AND    PPTFTRD.IDPLAN = @IDPLAN)
		AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
		AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
		AND    COALESCE(HPRED.ENCARGOS, 0) = 0
	END
	PRINT '@TIENE='+ STR(@TIENE)

    IF @TIENE > 0 
    BEGIN        
		-- SE MIRA SI ESTE TIPO DE ADMISION FACTURA POR PREFIJOS
		SELECT @MPREFIJOS = MPREFIJOS, @TERCEROPREFIJOS = TERCEROPREFIJOS, 
				@ESGLOBAL  = ESGLOBAL,  @TERCEROGLOBAL   = TERCERO
		FROM   HTAD
		WHERE  HTAD.TIPOADM = @TIPOADM
		-- SE CONTROLA SI ESTA CONFIGURADO EL TIPO DE ADMISION COMO MASIVA
		IF @ESGLOBAL = 1            
		BEGIN 
			-- SE PREGUNTA SI ES MASIVA POR TERCERO  O PARA TODOS LOS TERCEROS
			IF @TERCEROGLOBAL = 1
			BEGIN
				SELECT @OK = COUNT(*) FROM HTADT WHERE IDTERCERO = @IDTERCERO1 
				AND TIPOADM = @TIPOADM  
				IF @OK > 0
				BEGIN
					PRINT 'ES MASIVA'
				END
				ELSE
				BEGIN
					PRINT 'NO ES TERCERO GLOBAL'
				END
			END           
		END
		PRINT 'CREAR TABLA TMP FTRD1' 
		CREATE TABLE #FTRD1(CNSFTR         VARCHAR(40)   COLLATE database_default,   
							N_CUOTA	     smallint      IDENTITY, 
							FECHA          datetime,
							DB_CR          varchar(2)    COLLATE database_default,    
							AREAPRESTACION varchar(20)   COLLATE database_default,       
							UBICACION      varchar(16)   COLLATE database_default,
							VR_TOTAL       float,         
							IMPUTACION     varchar(16)   COLLATE database_default,       
							CCOSTO         varchar(20)   COLLATE database_default,
							PREFIJO        varchar(6)    COLLATE database_default,    
							ANEXO          varchar(1024) COLLATE database_default,     
							REFERENCIA     varchar(40)   COLLATE database_default, 
							IDCIRUGIA      varchar(20)   COLLATE database_default,   
							CANTIDAD       decimal(18,6),               
							VALOR          decimal(14,2),
							VLR_SERVICI    decimal(14,2), 
							VLR_COPAGOS    decimal(14,2),
							VLR_PAGCOMP    decimal(14,2), 
							IDPROVEEDOR    varchar(20)   COLLATE database_default,
							NOADMISION     varchar(16)   COLLATE database_default,   
							NOPRESTACION	  varchar(16)   COLLATE database_default,       
							NOITEM         int,	
							AREAFUNCONT    varchar(20)   COLLATE database_default,   
							N_FACTURA      varchar(16)   COLLATE database_default,
							SUBCCOSTO      varchar(4)    COLLATE database_default,    
							PCOSTO	        decimal(14,2),     
							FECHAPREST     datetime,
							IDPLAN         VARCHAR(6)    COLLATE database_default,    
							CODUNG         VARCHAR(2)    COLLATE database_default,        
							CODPRG         VARCHAR(2)    COLLATE database_default,
							PAQUETE        SMALLINT,
							VALORIND       DECIMAL(14,2),
							SYS_COMPUTERNAME VARCHAR(254)    COLLATE database_default,
							USUARIOFAC VARCHAR(254)    COLLATE database_default)
		/*JEDM:09.AGO.2011 INSERCION DE ITEM PARA MANEJO DE PAQUETE*/ 
        
		SELECT TOP 1 @CNSFTR=CNSFCT, @NVOCONSEC=N_FACTURA, @LIBERADA=ESTADO FROM FTR WHERE NOREFERENCIA=@NOADMISION AND ESTADO='L' AND TIPOFAC='I'

		PRINT '@LIBERADA=='+COALESCE(@LIBERADA,'')

		IF COALESCE(@LIBERADA,'') <> 'L'
		BEGIN
			PRINT 'AQUI LLAMO A GENCONSECUTIVO'   
			EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@CNSFTR', @CNSFTR OUTPUT  
			SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)
			PRINT '@CNSFTR='+COALESCE(@CNSFTR,'')
		END
		ELSE
		BEGIN
			IF EXISTS(SELECT * FROM FTRD WHERE  CNSFTR=@CNSFTR)
			BEGIN
				DELETE FTRD WHERE  CNSFTR=@CNSFTR
			END
		END
        
		SELECT @DV = DIASVTO, @TTEC = TIPOTERCONTABLE, @NODESCUENTACOPAGO = NODESCUENTACOPAGO
		FROM   PPT WHERE IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN
		PRINT 'DV-TTEC-NODESCUENTA'



		SELECT @CUENTACXC = CUENTA,@CUENTACXC_RAD=CUENTARAD FROM TTEC
		WHERE TIPO = @TTEC
		PRINT 'CUENTACXC-CUENTACXCRAD'

		IF @DV IS NULL
		BEGIN
			SELECT @DV = 30
		END
		IF @DV = 0
		BEGIN
			SELECT @DV = 30  
		END
		PRINT 'DV='+STR(@DV)

		SELECT @TV = 'Credito'
		SELECT @EC = ENVIODICAJA FROM TER WHERE IDTERCERO = @IDTERCERO
        
		IF @EC IS NULL
		BEGIN
			SELECT @EC = 0
		END
                
		SELECT @IDTERPART = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJTERCEROEXTERNO'
                
		IF @IDTERCERO = @IDTERPART 
		BEGIN   
			SELECT @TV = 'Contado'           
			SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
			PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
			EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA,'HADM',@NOADMISION
            
			SELECT TOP 1 @IDTERCEROF=TER.IDTERCERO 
			FROM AFI INNER JOIN TER ON TER.ESTADO='Activo' AND TER.NIT=AFI.DOCIDAFILIADO
			WHERE AFI.IDAFILIADO=@IDAFILIADO
		END 
		ELSE
		BEGIN
			SELECT @IDTERCEROF = @IDTERCERO
		END
            
		SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'          
		SELECT @OK = COALESCE(COUNT(*),0) FROM TER WHERE IDTERCERO = @IDTERCEROF
		PRINT 'ANTES DE IF OK = 0'       
		IF @OK = 0
		BEGIN
			SELECT  @IDCATEGORIA = DBO.FNK_VALORVARIABLE('TERCATAFILIADO')
			PRINT 'Inserta Tercero con SPK_INSERT_TERDEAFI '+@IDAFILIADO+','+@IDCATEGORIA
			EXEC SPK_INSERT_TERDEAFI @IDAFILIADO, @IDCATEGORIA
		END
                    
		SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'  
        

		IF @PAQUETE = 1
		BEGIN
			PRINT 'AQUI CUANDO ES PAQUETE'
         IF EXISTS(SELECT  * 			FROM   HADM INNER JOIN HPRE  ON HADM.NOADMISION = HPRE.NOADMISION
						INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
						INNER JOIN SER   ON HPRED.IDSERVICIO = SER.IDSERVICIO
			WHERE  HADM.NOADMISION   = @NOADMISION
			AND    HPRED.IDTERCEROCA = @IDTERCERO
			AND    HPRED.IDPLAN      = @IDPLAN
			AND    COALESCE(HPRED.FACTURADA,0)=0
			AND    COALESCE(HPRED.N_FACTURA,'')=''
			AND    COALESCE(HPRED.TIPOSERCIRUGIA,'') = 'PAQUETE'  
         )
         BEGIN 
			   /* aqui se ingresa el item paquete para que sea el valor del paquete*/
			   INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						   IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						   VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						   NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
						   FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)      
			   SELECT @CNSFTR, HADM.FECHA, 'DB', NULL, NULL, HPRED.VALOR, NULL, 
				   HPRE.CCOSTO , SER.PREFIJO, SER.DESCSERVICIO, HPRED.IDSERVICIO, HPRED.IDCIRUGIA, --STORRES 10/11/2017 - ESTA TOMANDO EL CCOSTO DE HPRED:CCOSTO SE CAMBIA PARA QUE LO TOME DE HPRE:CCOSTO
				   1, HPRED.VALOR, HPRED.VALOR, 0,
				   0, NULL, @NOADMISION, HPRED.NOPRESTACION, HPRED.NOITEM, NULL, @NVOCONSEC, NULL, 0,
				   HADM.FECHA, HADM.IDPLAN, @PAQUETE,@SYS_COMPUTERNAME,@USUARIO
			   FROM   HADM INNER JOIN HPRE  ON HADM.NOADMISION = HPRE.NOADMISION
						   INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
						   INNER JOIN SER   ON HPRED.IDSERVICIO = SER.IDSERVICIO
			   WHERE  HADM.NOADMISION   = @NOADMISION
			   AND    HPRED.IDTERCEROCA = @IDTERCERO
			   AND    HPRED.IDPLAN      = @IDPLAN
			   AND    COALESCE(HPRED.FACTURADA,0)=0
			   AND    COALESCE(HPRED.N_FACTURA,'')=''
			   AND    COALESCE(HPRED.TIPOSERCIRUGIA,'') = 'PAQUETE'   
         END
         ELSE
         BEGIN
            PRINT 'INSERTO EL ITEM SOLO CON EL SERVICIO DE HADM....'
            INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                        IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                        VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                        NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
                        FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)      
            SELECT TOP 1 @CNSFTR, HADM.FECHA, 'DB', NULL, NULL, HADM.VLRSERVICIOPAQ, NULL, 
                   HPRE.CCOSTO , SER.PREFIJO, SER.DESCSERVICIO, SER.IDSERVICIO, NULL, --STORRES 10/11/2017 - ESTA TOMANDO EL CCOSTO DE HPRED:CCOSTO SE CAMBIA PARA QUE LO TOME DE HPRE:CCOSTO
                   1, HADM.VLRSERVICIOPAQ,HADM.VLRSERVICIOPAQ, 0,
                   0, NULL, @NOADMISION,@NOADMISION, 99, NULL, @NVOCONSEC, NULL, 0,
                   HADM.FECHA, HADM.IDPLAN, 0,@SYS_COMPUTERNAME,@USUARIO
            FROM   HADM INNER JOIN HPRE  ON HADM.NOADMISION = HPRE.NOADMISION
                        --INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                        INNER JOIN SER   ON HADM.IDSERVICIOPAQUETE = SER.IDSERVICIO
            WHERE  HADM.NOADMISION   = @NOADMISION

         END
		END

		/*JJIMENEZ INSERCION DE ITEM PARA MANEJO DE PAQUETE TIPO 2*/      
		IF @PAQUETE = 2
		BEGIN
			PRINT 'AQUI CUANDO ES PAQUETE 2'
			/* aqui se ingresa el item paquete para que sea el valor del paquete*/
			SELECT @PAQUETE=1
		END           
		IF @AUX1 = 0
		BEGIN
			PRINT 'INSERTA POR AUX1 = 0' 
			INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
						FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)
			SELECT @CNSFTR, HPRE.FECHA, 'DB', HPRE.IDAREA, NULL, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 0
												ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 
																		THEN HPRED.VALORCOPAGONORMAL
																		ELSE 0
																		END                                         
											END 
				ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 THEN COALESCE(HPRED.VALORCOPAGONORMAL,0)
											ELSE 0
										END
				END,                                       
				NULL, 
				CASE @DATOCCOSTO WHEN 'SER:CCOSTO' THEN HPRED.CCOSTO ELSE HPRE.CCOSTO END, 
				SER.PREFIJO, SER.DESCSERVICIO, HPRED.IDSERVICIO, HPRED.IDCIRUGIA,
				HPRED.CANTIDAD, HPRED.VALOR-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN (ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD) ELSE 0 END,
				CASE WHEN  HPRED.NOLOTE='HOMOLOGO' THEN  (HPRED.VALOR-(ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD))*HPRED.CANTIDAD ELSE HPRED.CANTIDAD*HPRED.VALOR END, 
				CASE WHEN  @NODESCUENTACOPAGO = 1 THEN 0 ELSE HPRED.VALORCOPAGO END,
				HPRED.VALORPCOMP, HPRED.IDPROVEEDOR, @NOADMISION, HPRED.NOPRESTACION,
				HPRED.NOITEM, NULL, @NVOCONSEC, HPRE.SUBCCOSTO, HPRED.PCOSTO,
				HPRE.FECHA, HPRED.IDPLAN, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 2 
																			WHEN 1 THEN 3
											END                                  
								ELSE 0 
				END,@SYS_COMPUTERNAME,@USUARIO
			FROM   HPRE, HPRED, SER 
			WHERE  HPRE.NOADMISION   = @NOADMISION
			AND    HPRE.NOPRESTACION = HPRED.NOPRESTACION 
			AND    HPRED.IDSERVICIO  = SER.IDSERVICIO  
			AND    HPRED.IDTERCEROCA = @IDTERCERO
			AND    HPRED.IDPLAN      = @IDPLAN
			AND    COALESCE(HPRED.FACTURADA,0)=0
			AND    COALESCE(HPRED.N_FACTURA,'')=''
			AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
			AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
			AND    COALESCE(HPRED.ENCARGOS, 0) = 0 
			--AND    (    COALESCE(HPRED.TIPOSERCIRUGIA,'') <> 'PAQUETE' AND @PAQUETE = 1
			--        OR  COALESCE(HPRED.TIPOSERCIRUGIA,'') = COALESCE(HPRED.TIPOSERCIRUGIA,'')  AND @PAQUETE = 0)
                    
		END
		IF @AUX1 = 1
		BEGIN
			PRINT 'INSERTA POR AUX1 = 1'
			INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
						FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)
			SELECT @CNSFTR, HPRE.FECHA, 'DB', HPRE.IDAREA, NULL, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 0
												ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 
																		THEN HPRED.VALORCOPAGONORMAL
																		ELSE 0
																		END                                         
											END 
				ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 THEN HPRED.VALORCOPAGONORMAL
											ELSE 0
										END
				END, 
				NULL, 
				CASE @DATOCCOSTO WHEN 'SER:CCOSTO' THEN HPRED.CCOSTO ELSE HPRE.CCOSTO END, 
				SER.PREFIJO, SER.DESCSERVICIO, HPRED.IDSERVICIO, HPRED.IDCIRUGIA,
				HPRED.CANTIDAD, HPRED.VALOR-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN (ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD) ELSE 0 END,
				CASE WHEN  HPRED.NOLOTE='HOMOLOGO' THEN  (HPRED.VALOR-(ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD))*HPRED.CANTIDAD ELSE HPRED.CANTIDAD*HPRED.VALOR END, 
				CASE WHEN  @NODESCUENTACOPAGO = 1 THEN 0 ELSE HPRED.VALORCOPAGONORMAL END,
				HPRED.VALORPCOMP, HPRED.IDPROVEEDOR, @NOADMISION, HPRED.NOPRESTACION,
				HPRED.NOITEM, NULL, @NVOCONSEC, HPRE.SUBCCOSTO, HPRED.PCOSTO,
				HPRE.FECHA, HPRED.IDPLAN, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 2 
																			WHEN 1 THEN 3
											END                                  
								ELSE 0 
				END,@SYS_COMPUTERNAME,@USUARIO
			FROM   HPRE, HPRED, SER 
			WHERE  HPRE.NOADMISION   = @NOADMISION
			AND    HPRE.NOPRESTACION = HPRED.NOPRESTACION 
			AND    HPRED.IDSERVICIO  = SER.IDSERVICIO  
			AND    HPRED.IDTERCEROCA = @IDTERCERO
			AND    HPRED.IDPLAN      = @IDPLAN
			AND    COALESCE(HPRED.FACTURADA,0)   = 0
			AND    HPRE.IDAREA IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
								AND PPTFTRD.IDPLAN = @IDPLAN AND ITEM = @AUX)
			AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
			AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
			AND    COALESCE(HPRED.ENCARGOS, 0) = 0  
			AND    COALESCE(HPRED.FACTURADA,0)=0
			AND    COALESCE(HPRED.N_FACTURA,'')=''               
			AND    (    COALESCE(HPRED.TIPOSERCIRUGIA,'') <> 'PAQUETE' AND @PAQUETE = 1
					OR  COALESCE(HPRED.TIPOSERCIRUGIA,'') = COALESCE(HPRED.TIPOSERCIRUGIA,'')  AND @PAQUETE = 0)            
		END
		IF @AUX1 = 2
		BEGIN
			PRINT 'INSERTA POR AUX1 = 2'
			INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
						FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)
			SELECT @CNSFTR, HPRE.FECHA, 'DB', HPRE.IDAREA, NULL, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 0
												ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 
																		THEN HPRED.VALORCOPAGONORMAL
																		ELSE 0
																		END                                         
											END 
				ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 THEN HPRED.VALORCOPAGONORMAL
											ELSE 0
										END
				END, 
				NULL, 
				CASE @DATOCCOSTO WHEN 'SER:CCOSTO' THEN HPRED.CCOSTO ELSE HPRE.CCOSTO END, 
				SER.PREFIJO, SER.DESCSERVICIO, HPRED.IDSERVICIO, HPRED.IDCIRUGIA,
				HPRED.CANTIDAD, HPRED.VALOR-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN (ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD) ELSE 0 END,
				CASE WHEN  HPRED.NOLOTE='HOMOLOGO' THEN  (HPRED.VALOR-(ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD))*HPRED.CANTIDAD ELSE HPRED.CANTIDAD*HPRED.VALOR END, 
				CASE WHEN  @NODESCUENTACOPAGO = 1 THEN 0 ELSE HPRED.VALORCOPAGONORMAL END,
				HPRED.VALORPCOMP, HPRED.IDPROVEEDOR, @NOADMISION, HPRED.NOPRESTACION,
				HPRED.NOITEM, NULL, @NVOCONSEC, HPRE.SUBCCOSTO, HPRED.PCOSTO,
				HPRE.FECHA, HPRED.IDPLAN,
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 2 
																			WHEN 1 THEN 3
											END                                  
								ELSE 0 
				END,@SYS_COMPUTERNAME,@USUARIO
			FROM   HPRE, HPRED, SER 
			WHERE  HPRE.NOADMISION   = @NOADMISION
			AND    HPRE.NOPRESTACION = HPRED.NOPRESTACION 
			AND    HPRED.IDSERVICIO  = SER.IDSERVICIO  
			AND    HPRED.IDTERCEROCA = @IDTERCERO
			AND    HPRED.IDPLAN      = @IDPLAN
			AND    COALESCE(HPRED.FACTURADA,0)=0
			AND    COALESCE(HPRED.N_FACTURA,'')=''
			AND    HPRE.IDAREA NOT IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
							AND PPTFTRD.IDPLAN = @IDPLAN)
			AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
			AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
			AND    COALESCE(HPRED.ENCARGOS, 0) = 0  
			--AND    (    COALESCE(HPRED.TIPOSERCIRUGIA,'') <> 'PAQUETE' AND @PAQUETE = 1
			--        OR  COALESCE(HPRED.TIPOSERCIRUGIA,'') = COALESCE(HPRED.TIPOSERCIRUGIA,'')  AND @PAQUETE = 0)            
		END
		IF @AUX1 = 3
		BEGIN
			PRINT 'INSERTA POR AUX1 = 3'
			INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
						FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)
			SELECT @CNSFTR, HPRE.FECHA, 'DB', HPRE.IDAREA, NULL, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 0
												ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 
																		THEN HPRED.VALORCOPAGONORMAL
																		ELSE 0
																		END                                         
											END 
				ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 THEN HPRED.VALORCOPAGONORMAL
											ELSE 0
										END
				END, 
				NULL, 
				CASE @DATOCCOSTO WHEN 'SER:CCOSTO' THEN HPRED.CCOSTO ELSE HPRE.CCOSTO END, 
				SER.PREFIJO, SER.DESCSERVICIO, HPRED.IDSERVICIO, HPRED.IDCIRUGIA,
				HPRED.CANTIDAD, HPRED.VALOR-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN (ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD) ELSE 0 END,
				CASE WHEN  HPRED.NOLOTE='HOMOLOGO' THEN  (HPRED.VALOR-(ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD))*HPRED.CANTIDAD ELSE HPRED.CANTIDAD*HPRED.VALOR END, 
				CASE WHEN  @NODESCUENTACOPAGO = 1 THEN 0 ELSE HPRED.VALORCOPAGONORMAL END,
				HPRED.VALORPCOMP, HPRED.IDPROVEEDOR, @NOADMISION, HPRED.NOPRESTACION,
				HPRED.NOITEM, NULL, @NVOCONSEC, HPRE.SUBCCOSTO, HPRED.PCOSTO,
				HPRE.FECHA, HPRED.IDPLAN, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 2 
																			WHEN 1 THEN 3
											END                                  
								ELSE 0 
				END,@SYS_COMPUTERNAME,@USUARIO
			FROM   HPRE, HPRED, SER 
			WHERE  HPRE.NOADMISION   = @NOADMISION
			AND    HPRE.NOPRESTACION = HPRED.NOPRESTACION 
			AND    HPRED.IDSERVICIO  = SER.IDSERVICIO  
			AND    HPRED.IDTERCEROCA = @IDTERCERO
			AND    HPRED.IDPLAN      = @IDPLAN
			AND    COALESCE(HPRED.FACTURADA,0)=0
			AND    COALESCE(HPRED.N_FACTURA,'')=''
			AND    HPRE.CCOSTO IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
								AND PPTFTRD.IDPLAN = @IDPLAN AND ITEM = @AUX)
			AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
			AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
			AND    COALESCE(HPRED.ENCARGOS, 0) = 0 
			--AND    (    COALESCE(HPRED.TIPOSERCIRUGIA,'') <> 'PAQUETE' AND @PAQUETE = 1
			--        OR  COALESCE(HPRED.TIPOSERCIRUGIA,'') = COALESCE(HPRED.TIPOSERCIRUGIA,'')  AND @PAQUETE = 0)            
		END
		IF @AUX1 = 4
		BEGIN
			PRINT 'INSERTA POR AUX1 = 4'
			INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
						IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
						VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
						NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, 
						FECHAPREST, IDPLAN, PAQUETE,SYS_COMPUTERNAME,USUARIOFAC)
			SELECT @CNSFTR, HPRE.FECHA, 'DB', HPRE.IDAREA, NULL, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 0
												ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 
																		THEN HPRED.VALORCOPAGONORMAL
																		ELSE 0
																		END                                         
											END 
				ELSE HPRED.VALOREXCEDENTE + CASE WHEN @NODESCUENTACOPAGO = 1 THEN HPRED.VALORCOPAGONORMAL
											ELSE 0
										END
				END, 
				NULL, 
				CASE @DATOCCOSTO WHEN 'SER:CCOSTO' THEN HPRED.CCOSTO ELSE HPRE.CCOSTO END, 
				SER.PREFIJO, SER.DESCSERVICIO, HPRED.IDSERVICIO, HPRED.IDCIRUGIA,
				HPRED.CANTIDAD, HPRED.VALOR-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN (ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD) ELSE 0 END,
				CASE WHEN  HPRED.NOLOTE='HOMOLOGO' THEN  (HPRED.VALOR-(ISNULL(HPRED.VLRSERVICIOH,0)/HPRED.CANTIDAD))*HPRED.CANTIDAD ELSE HPRED.CANTIDAD*HPRED.VALOR END, 
				CASE WHEN  @NODESCUENTACOPAGO = 1 THEN 0 ELSE HPRED.VALORCOPAGONORMAL END,
				HPRED.VALORPCOMP, HPRED.IDPROVEEDOR, @NOADMISION, HPRED.NOPRESTACION,
				HPRED.NOITEM, NULL, @NVOCONSEC, HPRE.SUBCCOSTO, HPRED.PCOSTO,
				HPRE.FECHA, HPRED.IDPLAN, 
				CASE @PAQUETE WHEN 1 THEN CASE COALESCE(HPRED.PAQUETE,0) WHEN 0 THEN 2 
																			WHEN 1 THEN 3
											END                                  
								ELSE 0 
				END,@SYS_COMPUTERNAME,@USUARIO
			FROM   HPRE, HPRED, SER 
			WHERE  HPRE.NOADMISION   = @NOADMISION
			AND    HPRE.NOPRESTACION = HPRED.NOPRESTACION 
			AND    HPRED.IDSERVICIO  = SER.IDSERVICIO  
			AND    HPRED.IDTERCEROCA = @IDTERCERO
			AND    HPRED.IDPLAN      = @IDPLAN
			AND    COALESCE(HPRED.FACTURADA,0)=0
			AND    COALESCE(HPRED.N_FACTURA,'')=''
			AND    HPRE.CCOSTO NOT IN (SELECT IDAREA FROM PPTFTRD WHERE PPTFTRD.IDTERCERO = @IDTERCERO
									AND    PPTFTRD.IDPLAN = @IDPLAN)
			AND    ISNULL(HPRE.ANULADO,0) = 0  --SJUNCO REQ 1803
			AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
			AND    COALESCE(HPRED.ENCARGOS, 0) = 0
			--AND    (    COALESCE(HPRED.TIPOSERCIRUGIA,'') <> 'PAQUETE' AND @PAQUETE = 1
			--        OR  COALESCE(HPRED.TIPOSERCIRUGIA,'') = COALESCE(HPRED.TIPOSERCIRUGIA,'')  AND @PAQUETE = 0)            
		END

		IF (SELECT DBO.FNK_VALORVARIABLE('FAC_VALNOCOBRABLES') ) = 'SI'
		BEGIN
			IF ( SELECT COALESCE(COUNT(*),0)
				FROM   #FTRD1     
				WHERE  VALOR    <= 0
				OR     CANTIDAD < = 0 ) >0
			BEGIN
				RAISERROR('Items Con Valores Cero o Negativos.',16,1)
				RETURN
			END
		END
		IF (SELECT COUNT(*)  FROM #FTRD1
			WHERE SYS_COMPUTERNAME=@SYS_COMPUTERNAME
			AND USUARIOFAC=@USUARIO   
			AND NOADMISION=@NOADMISION  
		)<=0
		BEGIN
			RAISERROR('No existen items para Facturar, Me Devuelvo Posible Error ',16,1)
			RETURN
		END
      PRINT 'Valido el Moto Permitido'
      SELECT @MONTO=SUM(COALESCE(VLR_SERVICI,0))  FROM #FTRD1
      IF DBO.FNK_VALIDA_TOPE_FACTURA('SALUD',@MONTO)=0
      BEGIN
			RAISERROR('El monto a Facturar Sobrepasa el Valor Autorizado, No se Puede Generar la Factura ',16,1)
			RETURN         
      END
		-- EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT 
        --OMAR
		--BEGIN TRAN
		PRINT 'INICIA BEGIN TRAN' 

		IF COALESCE(@LIBERADA,'') <> 'L'
		BEGIN
			PRINT 'AQUI LLAMO A NUMFACTURA'         
			SET @NVOCONSEC = SPACE(20)
			EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
			PRINT 'REGRESE DE NUMFACTURA'
		END
		PRINT '@NVOCONSEC='+@NVOCONSEC  
		
		IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORMATOFTR,'')<>'')
		BEGIN
			SELECT @IDFORMATOFTR=IDFORMATOFTR  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORMATOFTR,'')<>''
		END
		ELSE
		BEGIN
			SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
		END
		IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
		BEGIN
			IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
			BEGIN
				SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR'
			END
			ELSE
			BEGIN
				SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = 'FTR'
			END
		END
        

		IF EXISTS (SELECT * FROM FTR WHERE N_FACTURA=@NVOCONSEC)
		BEGIN
			PRINT 'ACTUALIZO EN FTR'
			UPDATE FTR SET IDTERCERO=@IDTERCERO, IDPLAN=@IDPLAN, F_FACTURA=CASE @TFECHA WHEN 1 THEN @FECHAFAC ELSE DBO.FNK_FECHA_SIN_HORA(GETDATE()) END,
			F_VENCE=CASE @TFECHA WHEN 1 THEN @FECHAFAC + @DV ELSE DBO.FNK_FECHA_SIN_HORA(GETDATE()) + @DV END, ESTADO='P', 
			VR_TOTAL=0, EMPLEADO=@USUARIO, TIPOTTEC=@TTEC, CUENTACXC=@CUENTACXC, CUENTACXC_RAD=@CUENTACXC_RAD, CODUNG=@CODUNG, CODPRG=@CODPRG, PAQUETE=@PAQUETE,
			OBSERVACION=REPLACE(COALESCE(@OBSERVACION,''),'@N_FACTURA',@NVOCONSEC),VENDEDOR=@NROAUTORIZAC
			WHERE N_FACTURA=@NVOCONSEC
		END
		ELSE
		BEGIN
			PRINT 'INSERTO EN FTR'
			INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE, VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
							IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION, TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
							INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC, IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
							MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
							CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, CODUNG , CODPRG, PAQUETE, -- JEDM 09.AGO.2011 SE AUMENTA CAMPO PAQUETE
							IDSEDE, RDIAN, CNSRESOL,IDFORMATO)
			SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCEROF, @NVOCONSEC, CASE @TFECHA 
																		WHEN 1 THEN @FECHAFAC 
																		ELSE DBO.FNK_FECHA_SIN_HORA(GETDATE())
																	END, 
				CASE @TFECHA 
						WHEN 1 THEN @FECHAFAC + @DV
						ELSE DBO.FNK_FECHA_SIN_HORA(GETDATE()) + @DV
				END, 0, NULL,@NROAUTORIZAC, LEFT(@DATO,2), NULL, 'P', NULL, 
				@IDAFILIADO, @USUARIO, @NOADMISION, 'SALUD', 'I', REPLACE(COALESCE(@OBSERVACION,''),'@N_FACTURA',@NVOCONSEC), @TV, 0, 0, 0, 0, 
				0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO, GETDATE(), 0, 0, 0, 
				@IDPLAN, NULL, 'C', NULL, @IDAREA_ALTA, @CCOSTO_ALTA, @DATO3, @TTEC,
				@CUENTACXC,@CUENTACXC_RAD, @CODUNG , @CODPRG, @PAQUETE, @IDSEDE,
				CASE COALESCE(@CNSRESOL,'') WHEN '' THEN 0 ELSE 1 END, COALESCE(@CNSRESOL,''),@IDFORMATOFTR
		END

		--IF @@ERROR <> 0 
		--BEGIN 
		--	ROLLBACK TRANSACTION
		--	RAISERROR('ERROR EN FTR', 16, 1)
		--	RETURN
		--END 
		-- INSERTA LOS ITEMES DE LA FACTURA
		PRINT 'INSERTA LOS ITEMS DE LA FACTURA '
		INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
					IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
					VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
					NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,
					VLRNOTADB, VLRNOTACR, IDPLAN, CODUNG , CODPRG, PAQUETE)
		SELECT CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
				IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
				CASE WHEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('VAL_REDONDEO_FTRD'))) <> '' THEN ROUND(VALOR,CAST(DBO.FNK_VALORVARIABLE('VAL_REDONDEO_FTRD') AS INT)) ELSE VALOR END, 
				CASE WHEN LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('VAL_REDONDEO_FTRD'))) <> '' THEN ROUND(VLR_SERVICI,CAST(DBO.FNK_VALORVARIABLE('VAL_REDONDEO_FTRD') AS INT)) ELSE VLR_SERVICI END, 
				VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
				NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST,
				0, 0, IDPLAN, @CODUNG , @CODPRG, PAQUETE 
		FROM #FTRD1
		WHERE SYS_COMPUTERNAME=@SYS_COMPUTERNAME
		AND USUARIOFAC=@USUARIO   
		AND NOADMISION=@NOADMISION
		
		--IF @@ERROR <> 0 
		--BEGIN 
		--	ROLLBACK TRANSACTION
		--	RAISERROR('ERROR EN FTRD', 16, 1)
		--	RETURN
		--END 
        
		PRINT 'SE BORRA LA TABLA TEMPORAL'
		-- SE BORRA LA TABLA TEMPORAL
		DROP TABLE #FTRD1   
    
        
		IF @LIBERADA = 'L'
		BEGIN
			UPDATE HADMF SET ESTADO='P', ANEXOUNICO=@VARIASF, IDTERCERO=@IDTERCEROF, IDPLAN=@IDPLAN, ITEM=@ITEM, DESCRIPCION=@DESCRIPCION 
			WHERE NOADMISION=@NOADMISION AND ESTADO='L' AND N_FACTURA=@NVOCONSEC
		END
		ELSE
		BEGIN
			IF NOT EXISTS(SELECT  * FROM HADMF WHERE N_FACTURA=@NVOCONSEC)
			BEGIN
				INSERT INTO HADMF(NOADMISION, N_FACTURA, CNSFCT, ESTADO, ANEXOUNICO, IDTERCERO, IDPLAN, ITEM, DESCRIPCION)
				SELECT @NOADMISION, @NVOCONSEC, @CNSFTR, 'P', @VARIASF, @IDTERCEROF, @IDPLAN, @ITEM, @DESCRIPCION
			END
			ELSE 
			BEGIN
				RAISERROR('La Factura ya Existe... Posible error de duplicidad',16,1)
				RETURN
			END
		END

		--IF @@ERROR <> 0 
		--BEGIN 
		--	ROLLBACK TRANSACTION
		--	RAISERROR('ERROR EN HADMF', 16, 1)
		--	RETURN
		--END 

		--DE NO HABER ERROR HACE COMIT Y CONTINUA
		
		PRINT 'FINALIZA BEGIN TRAN' 
		---COMMIT 

		--ACTUALIZO HPRED DESPUES DE TODO EL PROCESO
		UPDATE HPRED SET FACTURADA = 1, N_FACTURA = @NVOCONSEC FROM FTRD
		WHERE  HPRED.NOPRESTACION  = FTRD.NOPRESTACION
		AND    HPRED.NOITEM        = FTRD.NOITEM
		AND    FTRD.N_FACTURA      = @NVOCONSEC       
		AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803   
		AND   FTRD.NOADMISION=@NOADMISION

      PRINT 'ACTUALIZO HADMAUT'
      IF EXISTS(SELECT * FROM HADMAUT WHERE NOADMISION=@NOADMISION AND AUTORIZACION=@NROAUTORIZAC AND COALESCE(N_FACTURA,'')='')
      BEGIN
         UPDATE HADMAUT SET N_FACTURA=@NVOCONSEC WHERE NOADMISION=@NOADMISION AND AUTORIZACION=@NROAUTORIZAC AND COALESCE(N_FACTURA,'')=''
      END

		SELECT @VRTOTAL = COALESCE(SUM(VR_TOTAL),0), @VRSERV = COALESCE(SUM(VLR_SERVICI),0), @VRCOPA = COALESCE(SUM(VLR_COPAGOS),0),
				@VRPACO  = COALESCE(SUM(VLR_PAGCOMP),0)
		FROM   FTRD 
		WHERE  N_FACTURA = @NVOCONSEC

		SELECT @VRCOPA = ROUND(@VRCOPA, 2)
            
		-- MOD. JQUIROGA 20090425 - Manejo de Copago Externo
		IF @PAQUETE = 1
		BEGIN     
			PRINT 'aqui actualizo valor de ftr'
            DECLARE @PAQUETECOUNT INT=0

			SELECT @VRSERV  = COALESCE(SUM(VLR_SERVICI),0),
					@VRTOTAL = COALESCE(SUM(VR_TOTAL),0) - COALESCE(@VRCOPA,0) - COALESCE(@VRPACO,0),
                    @PAQUETECOUNT = COUNT(1)
			FROM   FTRD 
			WHERE  COALESCE(PAQUETE,0) IN(0,3)
			AND    N_FACTURA = @NVOCONSEC

            IF @PAQUETECOUNT=0
                SELECT @VRSERV=VLRSERVICIOPAQ, @VRTOTAL=VLRSERVICIOPAQ FROM HADM WHERE NOADMISION=@NOADMISION

			UPDATE FTR SET VALORSERVICIOS = @VRSERV, 
							VALORPCOMP     = @VRPACO, 
							COPAGO_INT     = @VRCOPA, 
							COPAGO_EXT    = @VALOREXT,
							VALORCOPAGO   = @VRCOPA - @VALOREXT,
							VR_TOTAL       = @VRSERV - (@VRCOPA + @VRPACO)
			WHERE N_FACTURA = @NVOCONSEC                 
		END
		ELSE
		BEGIN
			UPDATE FTR SET VALORSERVICIOS = @VRSERV, 
						VALORPCOMP     = @VRPACO, 
						COPAGO_INT     = @VRCOPA, 
						COPAGO_EXT     = @VALOREXT,
						VALORCOPAGO    = @VRCOPA - @VALOREXT,
						VR_TOTAL       = @VRSERV - (@VRCOPA + @VRPACO) 
			WHERE N_FACTURA = @NVOCONSEC
		END  
		
		-- CALCULO DE DESCUENTO   
		PRINT 'TERCERO DEL DESCUENTO = ' + @IDTERCERO
		SELECT @DESCUENTO  = 0
		SELECT @DESCUENTO  = COALESCE(DESCUENTO, 0),  @TIPODTO     = TIPODTO
		FROM   HADMDT 
		WHERE  NOADMISION = @NOADMISION 
		AND    IDTERCERO  = @IDTERCERO
                        
		PRINT 'DESCUENTO = '+STR(@DESCUENTO) 
		IF @DESCUENTO > 0
		BEGIN
			IF @TIPODTO = 'P'
			BEGIN
				SELECT @VRDTO = ROUND(@VRTOTAL * (@DESCUENTO/100),0)
			END
			ELSE 
			BEGIN
				SELECT @VRDTO = @DESCUENTO 
			END
			PRINT 'VALOR DTO = ' +STR(@VRDTO)
		END           
		ELSE
		BEGIN
			SELECT @VRDTO = 0
		END
                    
		SELECT @VRABONO  = COALESCE(SUM(QXDING.VALOR),0) FROM QXDING 
		WHERE  NOINGRESO = @NOADMISION AND IDTERCERO = @IDTERCERO
		AND    DEVUELTO  = 0   
            
		UPDATE FTR SET DESCUENTO = @VRDTO, VR_ABONOS = @VRABONO
		WHERE  N_FACTURA = @NVOCONSEC
		--       SE MIRA SI EL VALOR ENTRE DESCUENTOS Y ABONOS SOBREPASA EL TOTAL DE LA FACTURA
                
		SELECT @VLRDEVOLUCION = VALORSERVICIOS - VALORCOPAGO - VALORPCOMP -DESCUENTO - VR_ABONOS --OJO
		FROM FTR WHERE N_FACTURA = @NVOCONSEC                                                    --OJO     
                            
		SELECT @TOTALFACTURA = VALORSERVICIOS - VALORCOPAGO - VALORPCOMP -DESCUENTO -- OJO QUITE MENOS ABONOS
		FROM FTR WHERE N_FACTURA = @NVOCONSEC 
      
		IF (SELECT SIIF FROM TER WHERE IDTERCERO = @IDTERCERO)=1
		BEGIN
			UPDATE FTR SET OBSERVACION='#$'+COALESCE(SIIFCODIGOPCI,'')+';'+COALESCE(SIIFCONTRATO,FTR.N_FACTURA,'')+';'+COALESCE(SIIFCORREOSUPER,'')+'#$'
			FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
         WHERE TER.IDTERCERO = @IDTERCERO 
         AND FTR.N_FACTURA=@NVOCONSEC
		END      -- OJO         
		
		IF @TOTALFACTURA >= 0
		BEGIN
			---
			SELECT @VRTOTAL = COALESCE(SUM(VR_TOTAL),0), @VRSERV = COALESCE(SUM(VLR_SERVICI),0), @VRCOPA = COALESCE(SUM(VLR_COPAGOS),0),
				@VRPACO  = COALESCE(SUM(VLR_PAGCOMP),0)
			FROM   FTRD 
			WHERE  N_FACTURA = @NVOCONSEC
			---     
			IF @PAQUETE = 0
			BEGIN
			IF DBO.FNK_VALORVARIABLE('MREDONDEFTR_VR_TOTAL') ='SI'
			BEGIN
				UPDATE FTR SET VR_TOTAL = ROUND(@VRSERV, 0) - @VRCOPA - @VRPACO - DESCUENTO + @VALOREXT -- OJO QUITE MENOS ABONOS
				WHERE  N_FACTURA = @NVOCONSEC      
			END
			ELSE
			BEGIN
				UPDATE FTR SET VR_TOTAL = @VRSERV - @VRCOPA - @VRPACO - DESCUENTO + @VALOREXT -- OJO QUITE MENOS ABONOS
				WHERE  N_FACTURA = @NVOCONSEC 
			END
			END   
		END
		ELSE
		BEGIN
			UPDATE FTR SET VR_TOTAL = 0
			WHERE  N_FACTURA = @NVOCONSEC    
		END


		IF @VLRDEVOLUCION < 0  --OJO ESTABA AL REVES 04.MAR.2005
		BEGIN                  --OJO
			EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'@TFCJ', @NVOCONSEC1 OUTPUT  
			SELECT @NVOCONSEC1 = @IDSEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC1))+LTRIM(RTRIM(@NVOCONSEC1)),SPACE(1),0) 
			INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
						IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,
						CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,
						SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME)
			SELECT @NVOCONSEC1, NULL,  'PAGO', @NOADMISION, NULL, HADM.IDPLAN, 
				@VLRDEVOLUCION * (-1), @COMPANIA,
				AFI.IDAFILIADO,AFI.TIPO_DOC, 0, GETDATE(), 'SALUD', NULL, AFI.IDAFILIADO, LEFT(LTRIM(RTRIM(AFI.PAPELLIDO))+' '+LTRIM(RTRIM(AFI.SAPELLIDO))
				+' ' +LTRIM(RTRIM(AFI.PNOMBRE))+' '+ LTRIM(RTRIM(AFI.SNOMBRE)),40),  
				NULL, 'INTERNO', 0, 0, 0, 0, NULL, NULL, NULL, NULL, 'C', 'FACTURA QX',
				@USUARIO, NULL
			FROM  HADM, AFI
			WHERE HADM.NOADMISION = @NOADMISION
			AND   HADM.IDAFILIADO = AFI.IDAFILIADO  
		END
		--          
		IF @EC <> 1
		BEGIN
			EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRSERV    
		END
        
		IF @VEZ = 1
		BEGIN
			UPDATE HADM SET HADM.FACTURADA = 1, HADM.N_FACTURA = @NVOCONSEC, HADM.CNSFCT = @CNSFTR, HADM.VFACTURAS = 1
			WHERE NOADMISION = @NOADMISION
		END
		
		--CAJA
		Print 'llamado a caja del tercero = ' + @IDTERCERO
		EXEC SPK_PAGOSCAJA_QX @NOADMISION, @SYS_COMPUTERNAME, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCERO, @NVOCONSEC
		UPDATE HADM SET COPAGO = 1 WHERE NOADMISION = @NOADMISION    
		SELECT @DATOFAC = DATO FROM USVGS WHERE IDVARIABLE = 'FTRIDSERVICIO'
		IF @DATOFAC = 'IDALTERNA'
		BEGIN
			UPDATE FTRD SET FTRD.REFERENCIA = SER.IDALTERNA FROM SER
			WHERE  FTRD.REFERENCIA = SER.IDSERVICIO
			AND    SER.IDALTERNA IS NOT NULL
			AND    SER.IDALTERNA <> ''
		END
        
		-- CONTABILIZACION
		IF DBO.FNK_VALORVARIABLE('CONTAB_FTR_JOB')='SI'
		BEGIN
			PRINT 'CONTABILIZACION POR TRABAJO'
			INSERT INTO FTRCO(N_FACTURA, USUARIO, SYS_COMPUTERNAME, COMPANIA, SEDE)
			SELECT @NVOCONSEC,@USUARIO,@SYS_COMPUTERNAME,@COMPANIA,@IDSEDE
		END
		ELSE
		BEGIN
			PRINT 'CONTABILIZACION DE FACTURA'
			EXEC SPK_NC_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''
		END
		-- CXP
		EXEC SPK_CREACXP_ASIS @NOADMISION, @COMPANIA, @IDSEDE, @USUARIO, @NVOCONSEC
    END
	--CIERRO TIENE >0

	IF DBO.FNK_VALORVARIABLE('PRESUP_CXC_ACTIVADO')= 'SI'  
	BEGIN 
		IF DBO.FNK_VALORVARIABLE('PRESUP_TIPORECO')='DESDEFTR'  
		BEGIN
			PRINT 'ENVIO AUTOMATICO A PRESUPUESTO'
			EXEC DBO.SPK_ENTREGA_FACTURA_PTTO @NVOCONSEC,@IDSEDE
		END
	END       
END



