IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'SER'  AND   C.NAME = 'BIOFAR')
BEGIN
   ALTER TABLE SER  ADD BIOFAR SMALLINT 
END