CREATE OR ALTER PROCEDURE DBO.SPQ_PASARELA_PAGOS @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      DECLARE @IDKPAGE INT                ,@NOADMISION VARCHAR(20)         ,@PROCEDENCIA VARCHAR(20)
      ,@TABLA VARCHAR(20)                 ,@VALOR DECIMAL(14,2)            ,@USUARIORESP  VARCHAR(20)
      ,@ESTADO VARCHAR(20)                ,@CODCAJA  VARCHAR(20)           ,@CODCAJERO VARCHAR(20)
      ,@CONSECUTIVO VARCHAR(20)           
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   SET @CODCAJA=DBO.FNK_VALORVARIABLE('CAJA_IZIPAY')
   SET @CODCAJERO=DBO.FNK_VALORVARIABLE('USUARIO_IZIPAY')

   IF @METODO='ACTUALIZA_UNO'     
   BEGIN         
      SELECT @IDKPAGE=IDKAPAGE        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      IDKAPAGE INT  '$.IDKPAGE'
      )
      PRINT '@IDKPAGE='+STR(@IDKPAGE)
      IF EXISTS(SELECT * FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND ESTADO IN('RUNNING','SEND','ERROR'))
      BEGIN
         PRINT 'VOY A ACTUALIZAR'
         BEGIN TRY           
              EXEC SPK_VALIDAR_IZIPAY_JOB @IDKPAGE,@CODCAJA,@CODCAJERO                
         END TRY
         BEGIN CATCH
              PRINT 'ERROR ACTUALIZA'
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE 
      BEGIN
         PRINT 'VOY POR EL ELSE'
         SELECT @ESTADO=ESTADO FROM KPAGE WHERE IDKPAGE=@IDKPAGE 
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'link de pago en Estado:'+@ESTADO+' no se permite cambios'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='ANULAR_UNO'     
   BEGIN         
      SELECT @IDKPAGE=IDKAPAGE        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      IDKAPAGE INT  '$.IDKPAGE'
      )
      PRINT '@IDKPAGE='+STR(@IDKPAGE)
      IF EXISTS(SELECT * FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND ESTADO IN('RUNNING','SEND'))
      BEGIN
         PRINT 'VOY A ANULAR'
         SELECT @CONSECUTIVO=CONSECUTIVO,@PROCEDENCIA=PROCEDENCIA,@TABLA=TABLA 
         FROM KPAGE WHERE IDKPAGE=@IDKPAGE 
         AND ESTADO IN('RUNNING','SEND')
         BEGIN TRY               
              EXEC DBO.SPK_GENERA_ORDENPAGO_IZIPAY @CONSECUTIVO,@TABLA,@PROCEDENCIA,'',0,'',@USUARIO,@IDKPAGE,'ANULAR'  
              IF EXISTS(SELECT * FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND ESTADO='CANCELED')
              BEGIN
                UPDATE KPAGE SET FECHARES=DBO.FNK_GETDATE(),USUGENERA=@USUARIO WHERE IDKPAGE=@IDKPAGE AND ESTADO='CANCELED'
              END
         END TRY
         BEGIN CATCH
              PRINT 'ERROR ANULAR'
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE 
      BEGIN
         PRINT 'VOY POR EL ELSE'
         SELECT @ESTADO=ESTADO FROM KPAGE WHERE IDKPAGE=@IDKPAGE 
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'link de pago en Estado:'+@ESTADO+' no se permite cambios'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END 
   IF @METODO='ACTUALIZA_TODOS'     
   BEGIN   
      PRINT'INGRESO'
      EXEC DBO.SPK_VALIDAR_IZIPAY_JOB 0,@CODCAJA,@CODCAJERO   
      SELECT 'OK'OK
      RETURN
   END   
END




