IF NOT EXISTS(SELECT  * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_AUDITORIA' AND IDCONTROL='AUDIGLOSAS')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGO,PAISES)
   SELECT 'MENUQ_AUDITORIA','AUDIGLOSAS','M','Glosas y Auditoria',1,'auditoria.glosas','fa-solid fa-envelopes-bulk',null,0,0,201,'Recepción, Aditoria, Respuestas',NULL,NULL
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FTR'  AND   C.NAME = 'TIPOCAP')
BEGIN
   ALTER TABLE FTR  ADD TIPOCAP SMALLINT 
END
