IF NOT EXISTS(SELECT  * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND IDCONTROL='CONF_COMPDOC')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,SUBLABEL,CODIGO,PAISES)
   SELECT 'MENUQ_CONFIGURACION','CONF_COMPDOC','M','Comprobantes por Documentos',1,'conf.CompDoc','fa-regular fa-cloud-bolt',NULL,0,0,'Comporbantes,Variables',NULL,NULL
END
IF NOT EXISTS(SELECT  * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND IDCONTROL='CONF_PARCONTA')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,SUBLABEL,CODIGO,PAISES)
   SELECT 'MENUQ_CONFIGURACION','CONF_PARCONTA','M','Parametros Contables',1,'conf.ParConta','fa-regular fa-cloud-bolt',NULL,0,0,'Mes Cierre,Cuentas de Orden',NULL,NULL
END

