IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_REINGRESO_MATERIAL_CESTE' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_REINGRESO_MATERIAL_CESTE
END
GO
CREATE PROCEDURE DBO.SPK_REINGRESO_MATERIAL_CESTE 
@CNSORIGEN  VARCHAR(20),
@CNSDESTINO VARCHAR(20),
@USUARIO    VARCHAR(20)
WITH ENCRYPTION
AS  
DECLARE @EXISTE INT
BEGIN  
   INSERT INTO KCEREP(CNSREP, FECHA, USUENTRE, SECTOR, CODPAQUETE, USUAREP, CLASE, IDTERCERO, ESTADO)
   SELECT @CNSDESTINO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),COALESCE(USURECHAZO,USUAREP), SECTOR, CODPAQUETE, USUAREP, CLASE, IDTERCERO, 'Recibido'
   FROM KCEREP
   WHERE CNSREP=@CNSORIGEN

   INSERT INTO KCEREPD(CNSREP,ITEM,IDARTICULO,CANT)
   SELECT @CNSDESTINO,ITEM,IDARTICULO,CANT
   FROM KCEREPD
   WHERE CNSREP=@CNSORIGEN

END

