CREATE OR ALTER PROCEDURE DBO.SPQ_ESTERILIZA_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@CODPAQUETE VARCHAR(20)        ,@DESCRIPCION VARCHAR(100)
      ,@IDARTICULO VARCHAR(20)            ,@CANT INT                      ,@NOITEM INT
      ,@ESTADO VARCHAR(10)                ,@EQUIPO VARCHAR(20)            ,@ESTEQUIPO BIT
      ,@CNSREP VARCHAR(20)                ,@USUENTREGA VARCHAR(20)        ,@SECTOR VARCHAR(20)
      ,@CLASE VARCHAR(20)                 ,@FLIMITE DATETIME              ,@TIPO VARCHAR(20)
      ,@IDTIPO VARCHAR(20)                ,@RESULTADO VARCHAR(20)         ,@OBSERVACIONES VARCHAR(250)
      ,@CNSPRUEBA VARCHAR(20)             ,@CNSCARGA VARCHAR(20)          ,@FINICIO DATETIME
      ,@NROAGENTE VARCHAR(20)             ,@FFINAL DATETIME               ,@RECHAZO VARCHAR(3)
      ,@MRECHAZO VARCHAR(255)             ,@USURECHAZO VARCHAR(20)        ,@REING BIT
      ,@PRUEBA1 VARCHAR(10)               ,@PRUEBA2 VARCHAR(10)           ,@ESTERIL BIT
      ,@LONGITUD SMALLINT                 ,@IDEQUIPO VARCHAR(20)          ,@IDPRUEBA VARCHAR(20)
      ,@ACCION SMALLINT
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='CRUD_KCEPAQ'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
         SELECT @PROCESO=PROCESO,@CODPAQUETE=CODPAQUETE,@DESCRIPCION=DESCRIPCION       
         FROM   OPENJSON (@DATOS)
         WITH   (    
         PROCESO VARCHAR(20)      '$.PROCESO',
         CODPAQUETE VARCHAR(20)   '$.CODPAQUETE',
         DESCRIPCION VARCHAR(100) '$.DESCRIPCION'
         )  
      IF @PROCESO='Nuevo'
      BEGIN
         IF NOT EXISTS(SELECT * FROM KCEPAQ WHERE CODPAQUETE=@CODPAQUETE)
         BEGIN
            INSERT INTO KCEPAQ(CODPAQUETE,DESCRIPCION)
            SELECT @CODPAQUETE,@DESCRIPCION
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Paquete ya existe'
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
      IF @PROCESO='Edita'
      BEGIN
         IF EXISTS(SELECT * FROM KCEPAQ WHERE CODPAQUETE=@CODPAQUETE)
         BEGIN
            UPDATE KCEPAQ SET DESCRIPCION=@DESCRIPCION WHERE CODPAQUETE=@CODPAQUETE
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Paquete ya existe'      
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END 
      IF @PROCESO='Borrar'
      BEGIN
         IF NOT EXISTS(SELECT * FROM KCEPAQD WHERE CODPAQUETE=@CODPAQUETE)
         BEGIN
            DELETE KCEPAQ WHERE CODPAQUETE=@CODPAQUETE
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Paquete con Detalles No se puede Continuar'             
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
   END
   IF @METODO='CRUD_KCEPAQD'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
         SELECT @PROCESO=PROCESO,@CODPAQUETE=CODPAQUETE,@NOITEM=ITEM,@IDARTICULO=IDARTICULO,@CANT=CANT,
         @ESTADO=CASE WHEN ESTADO='true' THEN 'Activo' ELSE 'Inactivo' END
         FROM   OPENJSON (@DATOS)
         WITH   (    
         PROCESO VARCHAR(20)      '$.PROCESO',
         CODPAQUETE VARCHAR(20)   '$.CODPAQUETE',
         ITEM INT                 '$.ITEM',
         IDARTICULO VARCHAR(100) '$.IDARTICULO',
         CANT       INT           '$.CANT',
         ESTADO VARCHAR(20)       '$.ESTADO'
         )  
      IF @PROCESO='Nuevo'
      BEGIN
         IF EXISTS(SELECT * FROM KCEPAQ WHERE CODPAQUETE=@CODPAQUETE)
         BEGIN
            SELECT @NOITEM=MAX(ITEM) FROM KCEPAQD WHERE CODPAQUETE=@CODPAQUETE
            INSERT INTO KCEPAQD(CODPAQUETE,ITEM,IDARTICULO,CANT,ESTADO)
            SELECT @CODPAQUETE,COALESCE(@NOITEM,0)+1,@IDARTICULO,@CANT,'Activo'
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Paquete no Encontrado'
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM KCEPAQD WHERE CODPAQUETE=@CODPAQUETE AND ITEM=@NOITEM)
         BEGIN
            UPDATE KCEPAQD SET IDARTICULO=@IDARTICULO,CANT=@CANT,ESTADO=@ESTADO WHERE CODPAQUETE=@CODPAQUETE AND ITEM=@NOITEM
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'item no Encontrado '      
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END 
      IF @PROCESO='Borrar'
      BEGIN
         IF EXISTS(SELECT * FROM  KCEPAQD WHERE CODPAQUETE=@CODPAQUETE AND ITEM=@NOITEM)
         BEGIN
            DELETE  KCEPAQD WHERE CODPAQUETE=@CODPAQUETE AND ITEM=@NOITEM
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT ' Item no Encontado no se puede continuar'             
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
   END
   IF @METODO='CRUD_TGEQUIP'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )  
         SELECT @PROCESO=PROCESO,@EQUIPO=EQUIPO,@DESCRIPCION=DESCRIPCION,@ESTEQUIPO=CASE WHEN ESTADO='True' THEN 1 ELSE 0 END
         FROM   OPENJSON (@DATOS)
         WITH   (    
         PROCESO VARCHAR(20)      '$.PROCESO',
         EQUIPO VARCHAR(20)   '$.EQUIPO',
         DESCRIPCION VARCHAR(100) '$.DESCRIPCION',
         ESTADO VARCHAR(20)       '$.ESTADO'
         )  
      IF @PROCESO='Nuevo'
      BEGIN
         IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='ESTERILIZACION' AND CAMPO='EQUIPO' AND CODIGO=@EQUIPO)
         BEGIN
            INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION,CHECK1)
            SELECT TABLA='ESTERILIZACION' , CAMPO='EQUIPO', @EQUIPO,@DESCRIPCION,1
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Equipo  ya existe'
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM TGEN WHERE TABLA='ESTERILIZACION' AND CAMPO='EQUIPO' AND CODIGO=@EQUIPO)
         BEGIN
            UPDATE TGEN SET DESCRIPCION=@DESCRIPCION,CHECK1=@ESTEQUIPO WHERE TABLA='ESTERILIZACION' AND CAMPO='EQUIPO' AND CODIGO=@EQUIPO
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Equipo No Encontrado, Verfique e intente de nuevo'      
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END 
      IF @PROCESO='Borrar'
      BEGIN
         IF  EXISTS(SELECT * FROM TGEN WHERE TABLA='ESTERILIZACION' AND CAMPO='EQUIPO' AND CODIGO=@EQUIPO)
             AND NOT EXISTS(SELECT * FROM KCECAR WHERE EQUIPO=@EQUIPO)
         BEGIN
            DELETE TGEN WHERE TABLA='ESTERILIZACION' AND CAMPO='EQUIPO' AND CODIGO=@EQUIPO
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Equipo Con Registros, No se puede Continuar'             
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
   END
   IF @METODO='CRUD_KCEREP'     
   BEGIN         
      SELECT @PROCESO=PROCESO,@CNSREP=CNSREP,@USUENTREGA=USUENTREGA,@SECTOR=SECTOR,@CODPAQUETE=CODPAQUETE,@CLASE=CLASE      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
           PROCESO VARCHAR(20) '$.PROCESO',
           CNSREP  VARCHAR(20) '$.CNSREP',
           USUENTREGA VARCHAR(20) '$.USUENTREGA',
           SECTOR VARCHAR(20) '$.SECTOR',
           CODPAQUETE VARCHAR(20) '$.CODPAQUETE',
           CLASE VARCHAR(20) '$.CLASE'
            )           
      
      IF @PROCESO='Nuevo'
      BEGIN
         BEGIN TRY
            SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO

            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')+' COMPANIA'+COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSREP=''
           -- EXEC SPQ_GENSEQUENCE @SEDE=@IDSEDE,@PREFIJO='@IZSOLD' ,@CNSREP=@CNSIZSOLD OUTPUT
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@KCEREP', @CNSREP OUTPUT  
            PRINT '@CNSREP='+COALESCE(@CNSREP,'')   
		      SELECT @CNSREP = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSREP))+LTRIM(RTRIM(@CNSREP)),SPACE(1),0)
		      PRINT '@CNSREP='+COALESCE(@CNSREP,'')                    
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            SELECT 'KO'KO, ERROR AS ERROR FROM  @TBLERRORES 
            RETURN
         END CATCH

         BEGIN TRY           
             INSERT INTO KCEREP(CNSREP, FECHA, USUENTRE, SECTOR, CODPAQUETE, USUAREP, CLASE,ESTADO)  
             SELECT @CNSREP,DBO.FNK_GETDATE(), @USUENTREGA, @SECTOR, @CODPAQUETE, @USUARIO, @CLASE,'Recibido'

             INSERT INTO KCEREPD (CNSREP,ITEM,IDARTICULO,CANT)
             SELECT @CNSREP,ROW_NUMBER() OVER(ORDER  BY @CNSREP  ASC),IDARTICULO, CANT 
             FROM KCEPAQD WHERE CODPAQUETE=@CODPAQUETE

         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
      IF @PROCESO='Edita'
      BEGIN
         IF EXISTS(SELECT  * FROM KCEREP WHERE  CNSREP=@CNSREP AND ESTADO='Recibido')
         BEGIN
            UPDATE KCEREP SET USUENTRE= @USUENTREGA,SECTOR= @SECTOR,CODPAQUETE=@CODPAQUETE,CLASE= @CLASE  
            WHERE  CNSREP=@CNSREP AND ESTADO='Recibido'
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Entrega en estado Recibido'             
         END
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN 
      END
   END    
   IF @METODO='CRUD_KCEREPD'     
   BEGIN   
      SELECT @PROCESO=PROCESO,@CNSREP=CNSREP,@NOITEM=ITEM,@IDARTICULO=IDARTICULO,@CANT=CANT     
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
           PROCESO VARCHAR(20) '$.PROCESO',
           CNSREP  VARCHAR(20) '$.CNSREP',
           ITEM   INT          '$.ITEM',
           IDARTICULO VARCHAR(20) '$.IDARTICULO',
           CANT INT '$.CANT'
            )           
      
      IF @PROCESO='Nuevo'
      BEGIN
         IF EXISTS(SELECT  * FROM KCEREP WHERE CNSREP=@CNSREP)
         BEGIN
            SELECT @NOITEM=MAX(COALESCE(ITEM,0)) FROM KCEREPD WHERE CNSREP=@CNSREP

            INSERT INTO KCEREPD(CNSREP,ITEM,IDARTICULO,CANT)
            SELECT @CNSREP,COALESCE(@NOITEM,0)+1,@IDARTICULO,@CANT
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Recepcion Para este Articulo'              
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         PRINT 'ESTOY EDITANDO '+@CNSREP+'@NOITEM='+STR(@NOITEM)
         IF EXISTS(SELECT * FROM KCEREPD WHERE CNSREP=@CNSREP AND ITEM=@NOITEM)
         BEGIN
            UPDATE KCEREPD SET IDARTICULO=@IDARTICULO,CANT=@CANT WHERE CNSREP=@CNSREP AND ITEM=@NOITEM
         END
         ELSE
         BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'No se Encontro Entrega para este Articulo '  
         END
      END
      IF @PROCESO='Borrar'
      BEGIN
         IF EXISTS(SELECT * FROM  KCEREP WHERE CNSREP=@CNSREP AND ESTADO='Recibido' )
         BEGIN
            IF EXISTS(SELECT * FROM KCEREPD WHERE CNSREP=@CNSREP AND ITEM=@NOITEM)
            BEGIN
               DELETE  KCEREPD  WHERE CNSREP=@CNSREP AND ITEM=@NOITEM
            END
            ELSE
            BEGIN
                  INSERT INTO @TBLERRORES(ERROR)
                  SELECT 'No se Encontro Entrega para este Articulo '  
            END
         END
         ELSE
         BEGIN
            
            INSERT INTO @TBLERRORES(ERROR)
             SELECT 'No se Encontro Recepcion o No tiene Dete'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='CERRAR_RECEP'     
   BEGIN         
      SELECT @CNSREP=CNSREP      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CNSREP VARCHAR(20) '$.CNSREP' 
            )           
      IF EXISTS(SELECT * FROM KCEREP WHERE CNSREP=@CNSREP AND ESTADO='Recibido')
         AND EXISTS(SELECT * FROM KCEREPD WHERE  CNSREP=@CNSREP)
      BEGIN
         UPDATE  KCEREP SET ESTADO='Inspeccion' WHERE CNSREP=@CNSREP AND ESTADO='Recibido'
      END
      ELSE
      BEGIN
         IF NOT EXISTS(SELECT * FROM KCEREPD WHERE  CNSREP=@CNSREP) 
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
             SELECT 'Consecutivo de Entrega sin detalles... No se puede Continuar'
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
             SELECT 'Consecutivo No Encontrado o ya Fue Cerrado.. '
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='CRUD_KCEPRU'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
      SELECT @PROCESO=PROCESO,@CNSPRUEBA=CNSPRUEBA,@FLIMITE=CONVERT(DATETIME,FLIMITE+' 23:59:59'),@TIPO=TIPO,@IDTIPO=IDTIPO,@RESULTADO=RESULTADO,@EQUIPO=EQUIPO,
      @OBSERVACIONES=OBSERVACIONES,@IDPRUEBA=IDPRUEBA
      FROM   OPENJSON (@DATOS)
      WITH   (  
      PROCESO VARCHAR(20) '$.PROCESO',
      CNSPRUEBA VARCHAR(20) '$.CNSPRUEBA',
      FLIMITE VARCHAR(20) '$.FLIMITE',
      TIPO    VARCHAR(20) '$.TIPO',
      IDTIPO  VARCHAR(20)  '$.IDTIPO',
      RESULTADO VARCHAR(20) '$.RESULTADO',
      EQUIPO VARCHAR(20)     '$.EQUIPO',
      OBSERVACIONES VARCHAR(255) '$.OBSERVACIONES',
      IDPRUEBA VARCHAR(20) '$.IDPRUEBA'
      )    
      --SELECT @PROCESO,@FLIMITE,@TIPO,@IDTIPO,@RESULTADO,@EQUIPO
      IF @PROCESO='Nuevo'
      BEGIN
         BEGIN TRY
            SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO

            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')+' COMPANIA'+COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSPRUEBA=''
           -- EXEC SPQ_GENSEQUENCE @SEDE=@IDSEDE,@PREFIJO='@IZSOLD' ,@CNSREP=@CNSIZSOLD OUTPUT
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@KCEPRU', @CNSPRUEBA OUTPUT  
            PRINT '@CNSREP='+COALESCE(@CNSPRUEBA,'')   
		      SELECT @CNSPRUEBA = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSPRUEBA))+LTRIM(RTRIM(@CNSPRUEBA)),SPACE(1),0)
		      PRINT '@CNSREP='+COALESCE(@CNSPRUEBA,'')                    
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            SELECT 'KO'KO, ERROR AS ERROR FROM  @TBLERRORES 
            RETURN
         END CATCH  

         INSERT INTO KCEPRU (CNSPRUEBA, FECHA, USUARIO, EQUIPO, TIPO, IDTIPO, RESULTADO, OBSERACIONES, ESTADO, FLIMITE,IDPRUEBA)
         SELECT @CNSPRUEBA, DBO.FNK_GETDATE(), @USUARIO, @EQUIPO, @TIPO, @IDTIPO, @RESULTADO, @OBSERVACIONES, 'Abierta', @FLIMITE,@IDPRUEBA
         IF @IDPRUEBA='PRUEBA1'
         BEGIN
            UPDATE KCEQUI SET RESULTADO1='Pendiente',RESULTADO2=NULL,ESTERIL=0 WHERE IDEQUIPO=@EQUIPO
         END
         IF @IDPRUEBA='PRUEBA2'
         BEGIN
            UPDATE KCEQUI SET RESULTADO2='Pendiente',ESTERIL=0 WHERE IDEQUIPO=@EQUIPO
         END
         SELECT 'OK'OK
         RETURN
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM KCEPRU WHERE CNSPRUEBA=@CNSPRUEBA AND ESTADO='Abierta')
         BEGIN
            UPDATE KCEPRU SET EQUIPO=@EQUIPO,TIPO=@TIPO,IDTIPO=@IDTIPO,RESULTADO=@RESULTADO,OBSERACIONES=@OBSERVACIONES,
            FLIMITE=@FLIMITE,IDPRUEBA=@IDPRUEBA
            WHERE  CNSPRUEBA=@CNSPRUEBA AND ESTADO='Abierta'
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Consuecutivo de la prueba, verique e intente de nuevo'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END   
   IF @METODO='CERRAR_KCEPRU'     
   BEGIN         
      SELECT @CNSPRUEBA=CNSPRUEBA,@IDPRUEBA=IDPRUEBA,@RESULTADO=RESULTADO,@OBSERVACIONES=OBSERVACIONES,@NOITEM=ACCION    
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSPRUEBA VARCHAR(20) '$.CNSPRUEBA',
      IDPRUEBA VARCHAR(20)  '$.IDPRUEBA',
      RESULTADO VARCHAR(20)  '$.RESULTADO',
      OBSERVACIONES VARCHAR(20)  '$.OBSERVACIONES',
      ACCION SMALLINT '$.ACCION'
      )
      IF EXISTS(SELECT  * FROM KCEPRU WHERE CNSPRUEBA=@CNSPRUEBA AND ESTADO='Abierta')
      BEGIN
         UPDATE KCEPRU SET RESULTADO=@RESULTADO,
         ESTADO=CASE WHEN @NOITEM=1 THEN 'Cerrada' WHEN @NOITEM= 2 THEN 'Anulada' ELSE ESTADO END,
         OBSERACIONES=@OBSERVACIONES
         WHERE CNSPRUEBA=@CNSPRUEBA AND ESTADO='Abierta'
         SELECT @EQUIPO=EQUIPO,@FLIMITE=FLIMITE FROM KCEPRU WHERE CNSPRUEBA=@CNSPRUEBA
         IF @IDPRUEBA='PRUEBA1'
         BEGIN
            UPDATE KCEQUI SET RESULTADO1=CASE WHEN @NOITEM=1 THEN @RESULTADO ELSE NULL END,
            ESTERIL=CASE WHEN PRUEBA2='NA' AND @RESULTADO='Negativo' THEN 1 ELSE 0 END,
            CNSPRUEBA=CASE WHEN PRUEBA2='NA' AND @RESULTADO='Negativo' THEN @CNSPRUEBA ELSE NULL END,
            F_VENCE=CASE WHEN PRUEBA2='NA' AND @RESULTADO='Negativo' THEN @FLIMITE ELSE NULL END
            WHERE IDEQUIPO=@EQUIPO
         END
         IF @IDPRUEBA='PRUEBA2'
         BEGIN
            UPDATE KCEQUI SET RESULTADO2=CASE WHEN @NOITEM=1 THEN CASE WHEN @RESULTADO='Negativo' THEN @RESULTADO ELSE NULL END ELSE NULL END,
            ESTERIL=CASE WHEN  @RESULTADO='Negativo' THEN 1 ELSE 0 END,
            ESTADO=CASE WHEN @RESULTADO='Positivo' THEN 'Manteni' ELSE ESTADO END,
            RESULTADO1=CASE WHEN   @RESULTADO='Negativo' THEN RESULTADO1 ELSE NULL END,
            CNSPRUEBA=CASE WHEN  @RESULTADO='Negativo' THEN @CNSPRUEBA ELSE 0 END,
            F_VENCE=CASE WHEN  @RESULTADO='Negativo' THEN @FLIMITE ELSE 0 END
            WHERE IDEQUIPO=@EQUIPO            
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro el Consecutivo de la prueba, Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='CRUD_KCECAR'     
   BEGIN         
      SELECT @PROCESO=PROCESO, @CNSCARGA=CNSCARGA,@CNSPRUEBA=CNSPRUEBA,@EQUIPO=EQUIPO,@FINICIO=CONVERT(DATETIME,FINICIO),
      @CNSPRUEBA=CNSPRUEBA,@OBSERVACIONES=OBSERVACIONES,@NROAGENTE=NROAGENTE
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      PROCESO VARCHAR(20) '$.PROCESO',
      CNSCARGA VARCHAR(20) '$.CNSCARGA',
      EQUIPO VARCHAR(20) '$.EQUIPO',
      NROAGENTE VARCHAR(20) '$.NROAGENTE',
      FINICIO VARCHAR(20) '$.FINICIO',
      CNSPRUEBA VARCHAR(20) '$.CNSPRUEBA',
      OBSERVACIONES VARCHAR(255) '$.OBSERVACIONES'
      )
      IF @PROCESO='Nuevo'
      BEGIN
         BEGIN TRY
            SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO
            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')+' COMPANIA'+COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSCARGA=''
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@KCECAR', @CNSCARGA OUTPUT  
		      SELECT @CNSCARGA = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSCARGA))+LTRIM(RTRIM(@CNSCARGA)),SPACE(1),0)
                
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            SELECT 'KO'KO, ERROR AS ERROR FROM  @TBLERRORES 
            RETURN
         END CATCH  
         INSERT KCECAR(CNSCARGA, FECHA, EQUIPO, USUARIO, CNSPRUEBA, NROAGENTE, ESTADO, FINICIO, FFINAL, OBSERVACIONES)
         SELECT @CNSCARGA,DBO.FNK_GETDATE(),@EQUIPO,@USUARIO,@CNSPRUEBA,@NROAGENTE,'Cargado',@FINICIO,NULL,@OBSERVACIONES

         SELECT  'OK' OK
         RETURN         
      END
      IF @PROCESO='Edita'
      BEGIN
         IF EXISTS(SELECT * FROM KCECAR WHERE CNSCARGA=@CNSCARGA AND ESTADO='Cargado')
         BEGIN
            UPDATE KCECAR SET EQUIPO=@EQUIPO,NROAGENTE=@NROAGENTE, FINICIO=@FINICIO,OBSERVACIONES=@OBSERVACIONES
            WHERE CNSCARGA=@CNSCARGA
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro el Consecutivo de Carga o Fue Cerrado, Verfique e intente de nuevo'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='ASIGNA_CARGA'     
   BEGIN         
      SELECT @CNSCARGA=CNSCARGA,@CNSREP=CNSREP        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
       CNSCARGA VARCHAR(20) '$.CNSCARGA',
       CNSREP   VARCHAR(20) '$.CNSREP'
      )
      IF EXISTS(SELECT * FROM KCECAR WHERE CNSCARGA=@CNSCARGA AND ESTADO='Cargado')  
      BEGIN
         IF NOT EXISTS(SELECT * FROM KCECARD WHERE CNSCARGA=@CNSCARGA AND CNSRECEP=@CNSREP)
         BEGIN
            INSERT INTO KCECARD(CNSCARGA,CNSRECEP)
            SELECT @CNSCARGA,@CNSREP

            UPDATE KCEREP SET ESTADO='Carga' WHERE CNSREP=@CNSREP
            SELECT 'OK' OK
            RETURN
         END
         ELSE
         BEGIN
            SELECT 'KO'KO,' No se Encontro Consecutivo de carga y/o Entrega verifique e intente de nuevo'
            RETURN
         END
      END
      ELSE
      BEGIN
            SELECT 'KO'KO,' Consecutivo de Carga no esta Disponible para esta Carga'
            RETURN      
      END  
   END
   IF @METODO='RETIRA_CARGA'     
   BEGIN         
      SELECT @CNSCARGA=CNSCARGA,@CNSREP=CNSREP        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
       CNSCARGA VARCHAR(20) '$.CNSCARGA',
       CNSREP   VARCHAR(20) '$.CNSREP'
      )
      IF EXISTS(SELECT * FROM KCECAR WHERE CNSCARGA=@CNSCARGA AND ESTADO='Cargado')  
      BEGIN
         IF EXISTS(SELECT * FROM KCECARD WHERE CNSCARGA=@CNSCARGA AND CNSRECEP=@CNSREP)
         BEGIN
            
            DELETE  KCECARD WHERE CNSCARGA=@CNSCARGA AND CNSRECEP=@CNSREP

            UPDATE KCEREP SET ESTADO='Inspeccion' WHERE CNSREP=@CNSREP
            SELECT 'OK' OK
            RETURN
         END
         ELSE
         BEGIN
            SELECT 'KO'KO,' No se Encontro Consecutivo de carga y/o Entrega verifique e intente de nuevo'
            RETURN
         END
      END
      ELSE
      BEGIN
            SELECT 'KO'KO,' Consecutivo de Carga no esta Disponible para Retirar '
            RETURN      
      END  
   END
   IF @METODO='FINALIZAR_CARGA'     
   BEGIN         
      SELECT @CNSCARGA=CNSCARGA,@FFINAL=CONVERT(DATETIME,FFINAL),@ACCION= ACCION     
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSCARGA VARCHAR(20) '$.CNSCARGA',
      FFINAL VARCHAR(20) '$.FFINAL',
      ACCION SMALLINT '$.ACCION'
      )
      IF EXISTS(SELECT * FROM KCECAR WHERE CNSCARGA=@CNSCARGA AND ESTADO='Cargado') 
      BEGIN
         IF EXISTS(SELECT * FROM KCECARD WHERE CNSCARGA=@CNSCARGA)
         BEGIN
            IF @ACCION=1
            BEGIN
               UPDATE KCECAR SET ESTADO='Terminado',FFINAL=CASE WHEN ISDATE(@FFINAL)=1 THEN @FFINAL ELSE DBO.FNK_GETDATE() END WHERE CNSCARGA=@CNSCARGA AND ESTADO='Cargado'
               UPDATE KCEREP SET ESTADO='Esteril',CNSCARGA=@CNSCARGA,F_ESTERIL=@FFINAL WHERE EXISTS(SELECT * FROM KCECARD WHERE CNSCARGA=@CNSCARGA AND KCEREP.CNSREP=KCECARD.CNSRECEP)
            END
            IF @ACCION=2
            BEGIN
               PRINT 'Voy Anular la carga'
               UPDATE KCECAR SET ESTADO='Anulado',FFINAL=CASE WHEN ISDATE(@FFINAL)=1 THEN @FFINAL ELSE DBO.FNK_GETDATE() END WHERE CNSCARGA=@CNSCARGA AND ESTADO='Cargado'
               UPDATE KCEREP SET ESTADO='Inspeccion',CNSCARGA=NULL,F_ESTERIL=NULL WHERE EXISTS(SELECT * FROM KCECARD WHERE CNSCARGA=@CNSCARGA AND KCEREP.CNSREP=KCECARD.CNSRECEP)
               PRINT 'Voy a Inabilitar el equipo'
               SELECT @EQUIPO=EQUIPO FROM KCECAR WHERE CNSCARGA=@CNSCARGA
               UPDATE KCEQUI SET ESTADO='Manteni',RESULTADO1=NULL,RESULTADO2=NULL,ESTERIL=0,CNSPRUEBA=NULL,F_VENCE=NULL WHERE IDEQUIPO=@EQUIPO
            END
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'la Carga no tiene Items Asociados no se puede Terminar si Detalles'
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro el Consecutivo de Carga o ya esta Finalizado, Verfique e intente de nuevo'
      END  
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='ENTREGA_MATERIAL'     
   BEGIN         
      SELECT @CNSREP=CNSREP,@USUENTREGA=USURECIBE       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSREP VARCHAR(20) '$.CNSREP',
      USURECIBE VARCHAR(20) '$.USURECIBE'
      )
      IF EXISTS(SELECT * FROM KCEREP WHERE CNSREP=@CNSREP AND ESTADO='Esteril')
      BEGIN
         UPDATE  KCEREP SET ESTADO='Entregado',USURECIBE=@USUENTREGA,USUSALIDA=@USUARIO,FECHASAL=DBO.FNK_GETDATE() WHERE CNSREP=@CNSREP AND ESTADO='Esteril'
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Consecutivo no fue encontrado o ya fue entregado, Verfique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
             SELECT 'KO' OK, ERROR FROM @TBLERRORES
             RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='FINALIZA_ENTREGA'     
   BEGIN  
      PRINT 'INGRESO A LA UNA'
      SELECT @CNSREP=CNSREP, @RECHAZO=RECHAZO,@MRECHAZO=MRECHAZO,@USURECHAZO=USURECHAZO,@REING=REING       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSREP VARCHAR(20) '$.CNSREP',
      RECHAZO VARCHAR(3) '$.RECHAZO',
      MRECHAZO VARCHAR(255) '$.MRECHAZO',
      USURECHAZO VARCHAR(20) '$.USURECHAZO',
      REING VARCHAR(3) '$.REING'
      )
      IF EXISTS(SELECT * FROM KCEREP WHERE CNSREP=@CNSREP AND ESTADO='Entregado')
      BEGIN
         UPDATE KCEREP SET ESTADO='Finalizado',RECHAZO=@RECHAZO,MRECHAZO=@MRECHAZO,USURECHAZO=@USURECHAZO,REING=@REING WHERE CNSREP=@CNSREP AND ESTADO='Entregado'
         IF @REING=1
         BEGIN
            DECLARE @CNSREPNVO VARCHAR(20)
            BEGIN TRY
               SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
               FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
               WHERE USUARIO=@USUARIO

               PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')+' COMPANIA'+COALESCE(@COMPANIA,'CIA') 
               SELECT @CNSREPNVO=''
              -- EXEC SPQ_GENSEQUENCE @SEDE=@IDSEDE,@PREFIJO='@IZSOLD' ,@CNSREP=@CNSIZSOLD OUTPUT
		         EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@KCEREP', @CNSREPNVO OUTPUT  
               PRINT '@CNSREP='+COALESCE(@CNSREPNVO,'')   
		         SELECT @CNSREPNVO = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSREPNVO))+LTRIM(RTRIM(@CNSREPNVO)),SPACE(1),0)
		         PRINT '@CNSREP='+COALESCE(@CNSREPNVO,'')    
               
               EXEC SPK_REINGRESO_MATERIAL_CESTE @CNSREP,@CNSREPNVO,@USUARIO

               UPDATE KCEREP SET CNSREING=@CNSREPNVO WHERE CNSREP=@CNSREP

            END TRY
            BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Consecutivo no Encontrado o Proceso ya Finalizado Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='CRUD_KCEQUI'     
   BEGIN  
     PRINT 'INBRESO'
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )    
      SELECT @PROCESO=PROCESO, @EQUIPO=IDEQUIPO, @DESCRIPCION=DESCRIPCION,  @ESTADO=ESTADO, @PRUEBA1=PRUEBA1, @PRUEBA2=PRUEBA2,
      @ESTERIL=ESTERIL
      FROM   OPENJSON (@DATOS)
      WITH   ( 
      PROCESO VARCHAR(10)   '$.PROCESO',
      IDEQUIPO VARCHAR(20) '$.EQUIPO',
      DESCRIPCION VARCHAR(255) '$.DESCRIPCION',
      ESTADO VARCHAR(10)     '$.ESTADO',
      PRUEBA1 VARCHAR(10)    '$.PRUEBA1',
      PRUEBA2 VARCHAR(10)    '$.PRUEBA2',
      ESTERIL BIT            '$.ESTERIL'
      )    
      IF @PROCESO='Nuevo'
      BEGIN
         PRINT 'VOY POR EL NUEVO'
         SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
         FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
         WHERE USUARIO=@USUARIO
	      SELECT @EQUIPO=SPACE(20)

         BEGIN TRY           
	         EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = 'KCEQUI', @LONGITUD = 5, @LLAMADO = 'ANT', @NVOCONSEC = @EQUIPO OUTPUT
            SELECT @EQUIPO ='EQUI'+ REPLACE(SPACE(5 - LEN(@EQUIPO)) + LTRIM(RTRIM(@EQUIPO)), SPACE(1), '0');

            INSERT INTO KCEQUI(IDEQUIPO, DESCRIPCION, ESTADO, PRUEBA1, PRUEBA2, ESTERIL)
            SELECT @EQUIPO, @DESCRIPCION, @ESTADO, @PRUEBA1, @PRUEBA2, @ESTERIL                             
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM KCEQUI WHERE IDEQUIPO=@EQUIPO)
         BEGIN
            BEGIN TRY           
               UPDATE KCEQUI SET DESCRIPCION=@DESCRIPCION,ESTADO=@ESTADO, PRUEBA1=@PRUEBA1,PRUEBA2=@PRUEBA2  WHERE IDEQUIPO=@EQUIPO                          
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro el Equipo Buscado, Verifique e intente de Nuevo'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END 
   IF @METODO='ESTADO_EQUIPO'     
   BEGIN         
      IF EXISTS(SELECT * FROM KCEQUI WHERE F_VENCE<GETDATE() AND ESTERIL=1)
      BEGIN
         UPDATE KCEQUI SET RESULTADO1=NULL,RESULTADO2=NULL,ESTERIL=0,CNSPRUEBA=NULL,F_VENCE=NULL WHERE F_VENCE<GETDATE() AND ESTERIL=1
      END
      SELECT 'OK'OK
      RETURN
   END  
END

