IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='URL_PASARELA_IZIPAY')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'URL_PASARELA_IZIPAY','URL PASARELA DE PAGOS IZPAY ANTES DEL VERBO ','Alfanumerica','https://api.micuentaweb.pe/api-payment/V4/Charge/'
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IZIPAYSERVCEMODETEST')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IZIPAYSERVCEMODETEST','Tokenn izipay modo pruebas','Alfanumerica',''
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'KPAGE'  AND   C.NAME = 'LINKPAGO')
BEGIN
   ALTER TABLE KPAGE  ADD LINKPAGO VARCHAR(256)
END
