IF EXISTS(SELECT * FROM USPROH WHERE  IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='RECAUDOS' AND CODIGOPADRE<>100)
BEGIN
   UPDATE USPROH SET CODIGOPADRE=100,ORDEN=110 WHERE  IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='RECAUDOS'
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='MCONCILIA')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGOPADRE)
   SELECT 'MENUQ_ADMINISTRATIVO','MCONCILIA','M','Conciliaciones de Glosa',1,'Admin.Conci','fa-solid fa-handshake',0,0,120,'Acta,Acuerdos de Pago','100'
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='MCIERRE')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGOPADRE)
   SELECT 'MENUQ_ADMINISTRATIVO','MCIERRE','M','Ciere de Cartera',1,'Admin.Cierre','fa-solid fa-key',0,0,100,'Historico Cartera','3001'
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='RPTCATERA')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGOPADRE)
   SELECT 'MENUQ_ADMINISTRATIVO','RPTCATERA','M','Consultas y Reportes',1,'Admin.RptCarte','fa-solid fa-key',0,0,105,'Vencimientos,Facturas Radicadas','3001'
END