IF EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='RECAUDOSCXC')
BEGIN
    DELETE USGRUH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='RECAUDOSCXC'
   DELETE  USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='RECAUDOSCXC'
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='MGLOSAS')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGOPADRE)
   SELECT 'MENUQ_ADMINISTRATIVO','MGLOSAS','M','Admin-Glosas',1,'Admin.Glosas','fa-solid fa-file-contract',0,0,105,'Envios, Recepción,Radicación','100'
END