IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_RIPS_CE_F' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_RIPS_CE_F
END

GO
CREATE PROCEDURE DBO.SPK_RIPS_CE_F
@ENVIO       VARCHAR(6),
@IDTERCERO   VARCHAR(20),
@FECINI      DATETIME,
@FECFIN      DATETIME,
@CODPREST    VARCHAR(20),
@RAZONSOCIAL VARCHAR(120), 
@TIPOID      VARCHAR(2),
@NUMID       VARCHAR(20),
@TIPOLLAMADO VARCHAR(2),
@IDPLAN      VARCHAR(6)= ''
WITH ENCRYPTION
AS 
DECLARE @COUNT_AC INT
DECLARE @COUNT_US INT
DECLARE @COUNT_AU INT
DECLARE @COUNT_AF INT
DECLARE @COUNT_AD INT
DECLARE @COUNT_AH INT
DECLARE @COUNT_AP INT
DECLARE @COUNT_AM INT
DECLARE @COUNT_AN INT
DECLARE @COUNT_AT INT
DECLARE @ESTADO   VARCHAR(2)
DECLARE @IPS   VARCHAR(20)
DECLARE @CODSER  VARCHAR(20)
DECLARE @ITEM INT
DECLARE @CANT INT 
DECLARE @BAND INT
DECLARE @RIPS_IDCONTRATO   VARCHAR(2)
BEGIN
	  SET @RIPS_IDCONTRATO	    = DBO.FNK_VALORVARIABLE('RIPS_IDCONTRATO')
	 SELECT @IPS=(CASE DATO WHEN '900450634' THEN 'CENDI' when '900261422' then 'CIME' when '900217463' then 'SANAS' WHEN '0100000014' THEN 'INOVA'   ELSE DATO END) FROM USVGS WHERE IDVARIABLE='IDTERCEROINSTALADO' 
   
  PRINT '@IDTERCERO='+ @IDTERCERO
  PRINT ' @ENVIO='+ @ENVIO 

  
  SELECT @ESTADO = ESTADO , @IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')='' THEN IDPLAN ELSE @IDPLAN END   
  FROM RIPS WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
  IF(@IPS='CENDI')
  BEGIN 
  DELETE RIPSD WHERE ENVIO=@ENVIO AND EXISTS (SELECT * FROM FNOT WHERE FNOT.N_FACTURA=RIPSD.N_FACTURA AND FNOT.ESTADO='O')
  END 

	IF ISNULL(@IDPLAN,'')=''
	BEGIN
		SELECT @IDPLAN=IDPLAN FROM FTR WHERE N_FACTURA=(SELECT TOP 1 N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO)
	END
  
   IF (SELECT COALESCE(RIPS.CODSERVICIO,'') FROM RIPS WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO)=''
   BEGIN 
   	   IF ISNULL(@IDPLAN,'')=''
		  SELECT TOP 1 @CODSER=IMPRIMEIDALTERNA FROM PPT WHERE IDTERCERO=@IDTERCERO AND ESTADO='Activo'
	   ELSE
		  SELECT @CODSER=IMPRIMEIDALTERNA FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN

		  IF @CODSER='9' SELECT @CODSER='8'
   END
   ELSE
   BEGIN
	  SELECT @CODSER=COALESCE(RIPS.CODSERVICIO,'') FROM RIPS WHERE ENVIO=@ENVIO	 AND IDTERCERO=@IDTERCERO
   END
   

  DECLARE @RIPS_CITSOLOCUMPLIDA VARCHAR(120) =   DBO.FNK_VALORVARIABLE('RIPS_CITSOLOCUMPLIDA')
  DECLARE @ENVIAR_NOCOB_CE_RIPS VARCHAR(120) = DBO.FNK_VALORVARIABLE('ENVIAR_NOCOB_CE_RIPS')
  DECLARE @ENVIAR_NOCOB_CI_RIPS VARCHAR(120) = DBO.FNK_VALORVARIABLE('ENVIAR_NOCOB_CI_RIPS')
  DECLARE @AUTSINHC VARCHAR(120) = DBO.FNK_VALORVARIABLE('AUTSINHC')
  DECLARE @IDPROTERQXRIPS VARCHAR(120) = DBO.FNK_VALORVARIABLE('IDPROTERQXRIPS')
  DECLARE @RIPS_AGRUPADOS VARCHAR(120) 
  DECLARE @RIPS_SINDEDUCCOPAGO VARCHAR(120) = DBO.FNK_VALORVARIABLE('RIPS_SINDEDUCCOPAGO')
  DECLARE @IDMEDPOSRIPS VARCHAR(120) = DBO.FNK_VALORVARIABLE('IDMEDPOSRIPS')
  DECLARE @RIPS_AM_DATOSMEDPOS VARCHAR(120) = DBO.FNK_VALORVARIABLE('RIPS_AM_DATOSMEDPOS')
  DECLARE @RIPS_VALORENTERO VARCHAR(120) = DBO.FNK_VALORVARIABLE('RIPS_VALORENTERO')
  DECLARE @RIPS_FEHAINIFINAL VARCHAR(120) = DBO.FNK_VALORVARIABLE('RIPS_FEHAINIFINAL')
  DECLARE @RIPS_COPAGOS VARCHAR(120) = DBO.FNK_VALORVARIABLE('RIPS_COPAGOS')
  DECLARE @RIPS_AGRUPADOSPPT VARCHAR(120) 

  SELECT @RIPS_AGRUPADOSPPT= CASE  WHEN  COALESCE(RIPSAGRUPADO,3)=3 THEN 'NULO' 
								   WHEN  COALESCE(RIPSAGRUPADO,3)=1 THEN 'SI' ELSE 'NO' END 
  FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN

  IF(@RIPS_AGRUPADOSPPT= 'SI' OR @RIPS_AGRUPADOSPPT='NO')
  BEGIN 
  PRINT 'ENTRE AQUI POR QUE ESTA CONFIGURADO EN PPT :'+ @RIPS_AGRUPADOSPPT
  SET @RIPS_AGRUPADOS=@RIPS_AGRUPADOSPPT
  END
  ELSE 
  BEGIN
  SET @RIPS_AGRUPADOS = DBO.FNK_VALORVARIABLE('RIPS_AGRUPADOS')
  END 



  IF @ESTADO <> '01'
  BEGIN
     RAISERROR('ENVIO EN ESTADO DIFERENTE DE 01 ', 16,1)
     RETURN
  END
   PRINT 'INSERTO TEMPORAL PARA DXPPAL, DXREL'
     SELECT CIT.N_FACTURA, HCA.FECHA, HCA.NOADMISION, HCA.IDAFILIADO,HCA.CONSECUTIVOCIT, HCA.CONSECUTIVO,HCA.IDDX DXPPAL, 
		CASE COALESCE([1],'') WHEN '' THEN HCA.DX1 ELSE COALESCE([1],'') END DX1,
		CASE COALESCE([2],'') WHEN '' THEN HCA.DX2 ELSE COALESCE([2],'') END DX2,
		CASE COALESCE([3],'') WHEN '' THEN HCA.DX3 ELSE COALESCE([3],'') END DX3 INTO #DX
		FROM HCA LEFT JOIN (
							SELECT *
							FROM (
								SELECT * FROM (select HCADX.CONSECUTIVO, ROW_NUMBER() over (partition by HCADX.CONSECUTIVO order by tipo) AS ITEMDX,	 HCADX.IDDX
											   from HCADX  INNER JOIN HCA ON HCA.CONSECUTIVO=HCADX.CONSECUTIVO
											   WHERE HCA.PROCEDENCIA='IPS' and HCA.CLASE='HC' ) HCADX
								WHERE ITEMDX IN (1,2,3)
								) Z 
							PIVOT
							(
							MAX(Z.IDDX )
							FOR ITEMDX IN ([1],[2],[3])
							) AS P ) P  ON HCA.CONSECUTIVO=P.CONSECUTIVO
			   INNER  JOIN CIT			ON HCA.NOADMISION=CIT.CONSECUTIVO AND  HCA.IDAFILIADO = CIT.IDAFILIADO AND  CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102) 
			   INNER JOIN RIPSD			ON CIT.N_FACTURA = RIPSD.N_FACTURA
			   INNER JOIN FTRD         ON RIPSD.N_FACTURA=FTRD.N_FACTURA AND CIT.CONSECUTIVO=FTRD.NOADMISION
			   LEFT  JOIN SER			ON SER.IDSERVICIO         = CIT.IDSERVICIO 
			   LEFT  JOIN RIPS_CP		ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
		WHERE RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
			--AND    RIPS_CP.ARCHIVO   = 'AC' 
			AND    RIPSD.PROCEDENCIA IN('CIT','CI')
    UNION ALL
   SELECT CIT.N_FACTURA, HCA.FECHA, HCA.NOADMISION, HCA.IDAFILIADO,HCA.CONSECUTIVOCIT, HCA.CONSECUTIVO,HCA.IDDX DXPPAL, 
    CASE COALESCE([1],'') WHEN '' THEN HCA.DX1 ELSE COALESCE([1],'') END DX1,
    CASE COALESCE([2],'') WHEN '' THEN HCA.DX2 ELSE COALESCE([2],'') END DX2,
    CASE COALESCE([3],'') WHEN '' THEN HCA.DX3 ELSE COALESCE([3],'') END DX3 
    FROM RIPSD INNER JOIN FTRD ON RIPSD.N_FACTURA=FTRD.N_FACTURA AND RIPSD.NOADMISION='VARIOS'
               INNER JOIN  CIT ON FTRD.NOADMISION=CIT.CONSECUTIVO
               LEFT  JOIN HCA  ON HCA.NOADMISION=FTRD.NOADMISION AND  HCA.IDAFILIADO = CIT.IDAFILIADO AND  CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102) 
                LEFT JOIN (
    					SELECT *
    					FROM (
    						SELECT * FROM (select HCADX.CONSECUTIVO, ROW_NUMBER() over (partition by HCADX.CONSECUTIVO order by tipo) AS ITEMDX,	 HCADX.IDDX
    									   from HCADX  INNER JOIN HCA ON HCA.CONSECUTIVO=HCADX.CONSECUTIVO
    									   WHERE HCA.PROCEDENCIA='IPS' and HCA.CLASE='HC' ) HCADX
    						WHERE ITEMDX IN (1,2,3)
    						) Z 
    					PIVOT
    					(
    					MAX(Z.IDDX )
    					FOR ITEMDX IN ([1],[2],[3])
    					) AS P ) P  ON HCA.CONSECUTIVO=P.CONSECUTIVO	
           			   LEFT  JOIN SER			ON SER.IDSERVICIO         = CIT.IDSERVICIO 
    	   LEFT  JOIN RIPS_CP		ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
    WHERE RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
        --AND    RIPS_CP.ARCHIVO   = 'AC' 
    	AND    RIPSD.PROCEDENCIA IN('CIT','CI')


  PRINT 'AC CIT'
  INSERT INTO RRIPS_AC(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,
                       FECHACONSULTA,NUMAUT,IDCONSULTA,FINCONSULTA,CAUSAEXT,IDDXPPAL,
                       IDDXREL1,IDDXREL2,IDDXREL3,TIPODX,VALORCONSULTA,VALORCUOTAM,
                       VALORNETO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, CANTIDAD,
                       PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL )
  SELECT @ENVIO, @IDTERCERO, 'I', CASE ISNULL(CIT.N_FACTURA,'') WHEN '' THEN FTRD.N_FACTURA
                                                    ELSE CIT.N_FACTURA
                      END, 
         @CODPREST, 
         LEFT(AFI.TIPO_DOC,2),  
         LEFT(REPLACE(AFI.DOCIDAFILIADO,'.',''),20), CIT.FECHA, 
         -- CASE LTRIM(RTRIM(LEFT(CIT.NOAUTORIZACION,15))) WHEN '' THEN 'NA' ELSE LEFT(CIT.NOAUTORIZACION,15) END, 
         LEFT(CIT.NOAUTORIZACION,20),     -- STORRES    
		 CASE @CODSER WHEN '0' THEN LEFT(SER.IDSERVICIO,8) WHEN '1' THEN LEFT(SER.IDALTERNA,8) WHEN '8' THEN LEFT(SER.CODCUPS,8) ELSE LEFT(SER.IDALTERNA,8) END, 
         LEFT(CASE WHEN CIT.FINCONSULTA IS NULL OR CIT.FINCONSULTA='' THEN '10' ELSE CIT.FINCONSULTA END,2), '13',
         CASE WHEN  COALESCE ((SELECT TOP 1 MDX.IDDX 
						       FROM  #DX HCA	LEFT JOIN MDX ON HCA.DXPPAL = MDX.IDDX
						       WHERE  HCA.IDAFILIADO = CIT.IDAFILIADO AND  COALESCE(HCA.NOADMISION,HCA.CONSECUTIVOCIT)=CIT.CONSECUTIVO 
						       AND    CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102)),'')=''
              THEN CASE SER.IDALTERNA 
                    WHEN '39141' THEN 'J00X' WHEN '36101' THEN 'K036' WHEN '37601' THEN 'E441' WHEN '39143' THEN 'L309' WHEN '39102' THEN 'F204' 
                    ELSE 'J00X'
                   END
              ELSE
                  LEFT((SELECT TOP 1 MDX.IDDX 
						       FROM  #DX HCA	LEFT JOIN MDX ON HCA.DXPPAL = MDX.IDDX
						       WHERE  HCA.IDAFILIADO = CIT.IDAFILIADO AND  COALESCE(HCA.NOADMISION,HCA.CONSECUTIVOCIT)=CIT.CONSECUTIVO
						       AND    CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102)),4)
         END,         
         CASE WHEN COALESCE ((	SELECT TOP 1 MDX.IDDX 
						FROM  #DX HCA	LEFT JOIN MDX ON HCA.DX1 = MDX.IDDX

						WHERE  HCA.IDAFILIADO = CIT.IDAFILIADO  AND COALESCE(HCA.NOADMISION,HCA.CONSECUTIVOCIT)=CIT.CONSECUTIVO
						AND CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102) ),'')=''
                  THEN ''
                  ELSE
                     (	SELECT TOP 1 MDX.IDDX 
						FROM  #DX HCA	LEFT JOIN MDX ON HCA.DX1 = MDX.IDDX

						WHERE  HCA.IDAFILIADO = CIT.IDAFILIADO  AND  COALESCE(HCA.NOADMISION,HCA.CONSECUTIVOCIT)=CIT.CONSECUTIVO 
						AND CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102) )
         END, SPACE(4),  SPACE(4),  
         CASE WHEN (SELECT TOP 1 TIPODX
                          FROM HCA LEFT JOIN 
                                MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
                          WHERE HCA.IDAFILIADO = CIT.IDAFILIADO AND MPL.AMBITO='CE' AND COALESCE(HCA.ANULADA,0)=0) IS NULL
                     THEN 1
                    ELSE
                     (SELECT TOP 1 
                       CASE TIPODX 
                        WHEN 'Presuntivo'   THEN 1
                        WHEN 'Impresion dx' THEN 1
                        WHEN 'Definitivo'   THEN 2
                        WHEN 'Conf Nuevo'   THEN 2
                        WHEN 'Conf Repet'   THEN 3
                       ELSE 1
                       END
                     FROM HCA LEFT JOIN 
                          MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
                     WHERE HCA.IDAFILIADO = CIT.IDAFILIADO AND MPL.AMBITO='CE' AND COALESCE(HCA.ANULADA,0)=0)
         END, 
         CIT.VALORTOTAL, IIF(@RIPS_COPAGOS='SI',CIT.VALORCOPAGO,0), 
         CASE WHEN @RIPS_COPAGOS<>'SI' THEN (FTRD.VALOR * FTRD.CANTIDAD)
            WHEN ISNULL(FTRD.VR_TOTAL,0)=0 THEN (FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS 
         ELSE FTRD.VR_TOTAL END, 
         CIT.CONSECUTIVO, NULL, FTRD.CNSFTR, FTRD.N_CUOTA, FTRD.CANTIDAD, 'CI', CIT.IDDX, SER.IDSERVICIO, FTRD.CODEVAL
  FROM   RIPSD INNER JOIN FTRD    ON RIPSD.N_FACTURA   = FTRD.N_FACTURA AND ISNULL(FTRD.PROCEDENCIA,'')=(CASE WHEN RIPSD.NOADMISION IN ('CEUNIFICADO','CEUNIFPE')  THEN 'CI' ELSE ISNULL(FTRD.PROCEDENCIA,'') END)
               INNER JOIN CIT     ON FTRD.NOPRESTACION = CIT.CONSECUTIVO 
               INNER JOIN AFI     ON CIT.IDAFILIADO    = AFI.IDAFILIADO 
                LEFT JOIN SER     ON CIT.IDSERVICIO    = SER.IDSERVICIO 
                LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    (RIPSD.PROCEDENCIA = 'CI' OR RIPSD.NOADMISION='CEUNIFICADO' OR RIPSD.NOADMISION='CEUNIFPE' )
  AND    RIPS_CP.ARCHIVO   = 'AC'  
  AND    COALESCE(FTRD.ITFC,0) <> 2
  AND    CIT.CUMPLIDA = CASE @RIPS_CITSOLOCUMPLIDA WHEN 'SI' THEN 1 ELSE CUMPLIDA END
  AND    FACTURABLE = CASE @ENVIAR_NOCOB_CI_RIPS WHEN 'NO' THEN 1 ELSE FACTURABLE END 
  -- AC CE
  PRINT 'AC CE' 
 
  
  INSERT INTO RRIPS_AC(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,
                       FECHACONSULTA,NUMAUT,IDCONSULTA,FINCONSULTA,CAUSAEXT,IDDXPPAL,
                       IDDXREL1,IDDXREL2,IDDXREL3,TIPODX,VALORCONSULTA,VALORCUOTAM,
                       VALORNETO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, CANTIDAD,
                       PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL)
  SELECT @ENVIO, @IDTERCERO, 'I', CASE ISNULL(AUTD.N_FACTURA,'') WHEN '' THEN FTRD.N_FACTURA
                                                     ELSE AUTD.N_FACTURA
                      END,
         @CODPREST,
         LEFT(AFI.TIPO_DOC,2),  
         LEFT(REPLACE(AFI.DOCIDAFILIADO,'.',''),20), AUT.FECHA, 
         CASE COALESCE(LEFT(AUTD.NOAUTORIZEXT,20),'') WHEN '' THEN LEFT(AUT.NUMAUTORIZA,20) ELSE LEFT(AUTD.NOAUTORIZEXT,20) END AS AUTORIZA,
         --CASE LTRIM(RTRIM(LEFT(AUT.NUMAUTORIZA,15))) WHEN '' THEN 'NA' ELSE LEFT(AUT.NUMAUTORIZA,15) END ,
		 CASE @CODSER WHEN '0' THEN LEFT(SER.IDSERVICIO,8) WHEN '1' THEN LEFT(SER.IDALTERNA,8) WHEN '8' THEN LEFT(SER.CODCUPS,8) ELSE LEFT(SER.IDALTERNA,8) END, 
         LEFT(CASE WHEN AUT.FINALIDAD IS NULL OR AUT.FINALIDAD='' THEN '10' 
                    ELSE CASE WHEN LEN(AUT.FINALIDAD)=1 THEN '0'+AUT.FINALIDAD ELSE AUT.FINALIDAD END 
              END,2), '13', 
         CASE 
         WHEN (SELECT TOP 1 MDX.IDDX 
               FROM #DX HCA LEFT JOIN 
                    MDX ON HCA.DXPPAL=MDX.IDDX 
              WHERE HCA.IDAFILIADO = AUT.IDAFILIADO  ) IS NULL
         THEN CASE SER.IDALTERNA 
               WHEN '39141' THEN 'J00X' 
               WHEN '36101' THEN 'K036' 
               WHEN '37601' THEN 'E441' 
               WHEN '39143' THEN 'L309' 
               WHEN '39102' THEN 'F204' 
              ELSE
               AUT.DXPPAL
              END
         ELSE
          LEFT((SELECT TOP 1 MDX.IDDX 
               FROM #DX HCA LEFT JOIN 
                    MDX ON HCA.DXPPAL=MDX.IDDX 
              WHERE HCA.IDAFILIADO = AUT.IDAFILIADO ),4)
         END,         
         CASE 
           WHEN (SELECT TOP 1 MDX.IDDX 
                  FROM #DX HCA LEFT JOIN 
                       MDX ON HCA.DX1=MDX.IDDX                      
                 WHERE HCA.IDAFILIADO = AUT.IDAFILIADO ) IS NULL
           THEN ''
           ELSE
            LEFT((SELECT TOP 1 MDX.IDDX 
                  FROM #DX HCA LEFT JOIN 
                       MDX ON HCA.DX1=MDX.IDDX 
                 WHERE HCA.IDAFILIADO = AUT.IDAFILIADO ),4)
         END, SPACE(4), SPACE(4),
         CASE 
           WHEN (SELECT TOP 1 TIPODX
                 FROM HCA LEFT JOIN 
                       MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
                 WHERE HCA.IDAFILIADO = AUT.IDAFILIADO AND MPL.AMBITO='CE' AND COALESCE(HCA.ANULADA,0)=0) IS NULL
            THEN 1
           ELSE
            (SELECT TOP 1 
              CASE TIPODX 
               WHEN 'Presuntivo'   THEN 1
               WHEN 'Impresion dx' THEN 1
               WHEN 'Definitivo'   THEN 2
               WHEN 'Conf Nuevo'   THEN 2
               WHEN 'Conf Repet'   THEN 3
              ELSE 1
              END
             FROM HCA LEFT JOIN 
                  MPL ON HCA.CLASEPLANTILLA = MPL.CLASEPLANTILLA
             WHERE HCA.IDAFILIADO = AUT.IDAFILIADO AND MPL.AMBITO='CE' AND COALESCE(HCA.ANULADA,0)=0)
         END,
         (FTRD.VALOR*FTRD.CANTIDAD), IIF(@RIPS_COPAGOS='SI',FTRD.VLR_COPAGOS,0),
         CASE WHEN @RIPS_COPAGOS<>'SI'THEN (FTRD.VALOR * FTRD.CANTIDAD)
            WHEN ISNULL(FTRD.VR_TOTAL,0)=0 THEN (FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS 
            ELSE (FTRD.VALOR*FTRD.CANTIDAD)
         END,
         AUT.NOAUT, AUTD.NO_ITEM, FTRD.CNSFTR, FTRD.N_CUOTA, FTRD.CANTIDAD, 'CE', AUT.DXPPAL, 
         SER.IDSERVICIO, FTRD.CODEVAL
  FROM   AUTD INNER JOIN AUT     ON AUTD.IDAUT             = AUT.IDAUT     
              INNER JOIN FTRD    ON AUT.NOAUT              = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM AND FTRD.N_FACTURA=AUTD.N_FACTURA
              INNER JOIN RIPSD   ON RIPSD.N_FACTURA        = FTRD.N_FACTURA
              INNER JOIN AFI     ON AUT.IDAFILIADO         = AFI.IDAFILIADO
               LEFT JOIN SER     ON SER.IDSERVICIO         = AUTD.IDSERVICIO 
               LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    RIPSD.PROCEDENCIA = 'CE'
  AND    RIPS_CP.ARCHIVO   = 'AC'  
  AND    COALESCE(FTRD.ITFC,0) <> 2


  AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
   SELECT @COUNT_AC = COUNT(*) FROM RRIPS_AC WHERE ENVIO = @ENVIO AND IDTERCERO=@IDTERCERO
   -- US CI
   PRINT 'US CIT'
   INSERT INTO RRIPS_US(ENVIO,IDTERCERO,ESTADO,TIPO_DOC,IDUSUARIO,CODENTIDADM,TIPOUSUARIO,PAPELLIDO,
                        SAPELLIDO,PNOMBRE,SNOMBRE,EDAD,UNMEDIDA,SEXO,DEPHABITUAL,MUNHABITUAL,
                        ZONAHABITUAL, TIPOAFILIADO)
   SELECT @ENVIO, @IDTERCERO, 'I', TIPO_DOC, DOCIDAFILIADO, IDALTERNA2, MAX(TIPOSISTEMA), PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE,
		MAX(EDAD), MAX(UM), SEXO, DEP, CIU, ZONA, TIPO
   FROM (
	  SELECT DISTINCT LEFT(AFI.TIPO_DOC,2) TIPO_DOC, AFI.DOCIDAFILIADO, 
	  CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END IDALTERNA2, 
        CASE PLN.TIPOSISTEMA WHEN 'Contributivo' THEN '1' 
                            WHEN 'Subsidiado'   THEN '2'
                            WHEN 'Vinculado'    THEN '3'
                            WHEN 'Particular'   THEN '4'
                            WHEN 'Otro'         THEN '5'
                            WHEN 'Prepagado'    THEN '5'
                            WHEN 'Desplazado Vinc'   THEN '8'
                            WHEN 'Desplazado Reg Cont' THEN '6'
                            WHEN 'Desplazado Reg Subs' THEN '7'
							ELSE '1'
        END TIPOSISTEMA, 
		LEFT(REPLACE(AFI.PAPELLIDO,',',' '),30) PAPELLIDO,  
		LEFT(REPLACE(AFI.SAPELLIDO,',',' '),30) SAPELLIDO, 
		LEFT(REPLACE(AFI.PNOMBRE,',',' '),20) PNOMBRE,  
        LEFT(REPLACE(AFI.SNOMBRE,',',' '),20) SNOMBRE, 
        CASE  
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=0 THEN 1  
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=30 THEN DATEDIFF(DAY,AFI.FNACIMIENTO,GETDATE())  
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=365 THEN 
                CASE WHEN DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(CIT.FECHA))  = 12 THEN 1
                    ELSE DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(CIT.FECHA))
                END
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=54750 THEN 
           CONVERT(INT,DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))/365.25)
        END EDAD,  
        CASE  
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=30 THEN '3'  
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=365 THEN 
                CASE WHEN DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(CIT.FECHA)) = 12 THEN '1'
                    ELSE '2'
                END  
            WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(CIT.FECHA))<=54750 THEN '1' 
        END UM,  
        CASE WHEN AFI.SEXO ='FEMENINO' THEN 'F' ELSE 'M' END SEXO,  
        LEFT(AFI.CIUDAD,2) DEP, 
        SUBSTRING(AFI.CIUDAD,3,3) CIU, 
        CASE WHEN AFI.ZONA='R' THEN 'R' ELSE 'U' END ZONA, 
		LEFT(AFI.TIPOAFILIADO,1) TIPO
	   FROM   RIPSD INNER JOIN FTRD   ON RIPSD.N_FACTURA     = FTRD.N_FACTURA AND ISNULL(FTRD.PROCEDENCIA,'')=(CASE WHEN RIPSD.NOADMISION IN ('CEUNIFICADO','CEUNIFPE')  THEN 'CI' ELSE ISNULL(FTRD.PROCEDENCIA,'') END)
					INNER JOIN CIT    ON FTRD.NOPRESTACION   = CIT.CONSECUTIVO
					INNER JOIN FTR    ON FTRD.CNSFTR         = FTR.CNSFCT
					 LEFT JOIN TER    ON FTR.IDTERCERO       = TER.IDTERCERO 
					INNER JOIN AFI    ON CIT.IDAFILIADO      = AFI.IDAFILIADO
					 LEFT JOIN PLN    ON CIT.IDPLAN          = PLN.IDPLAN
					 LEFT JOIN PPT    ON FTR.IDTERCERO=PPT.IDTERCERO AND PPT.IDPLAN=@IDPLAN
	   WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	   AND    (RIPSD.PROCEDENCIA = 'CI' OR RIPSD.NOADMISION='CEUNIFICADO' OR RIPSD.NOADMISION='CEUNIFPE' )  
	   AND    COALESCE(FTRD.ITFC,0) <> 2
	   AND    AFI.DOCIDAFILIADO NOT IN (SELECT IDUSUARIO FROM RRIPS_US WHERE ENVIO = @ENVIO )  
	   GROUP BY CIT.CONSECUTIVO,CIT.FECHA,TER.IDTERCERO,CIT.IDMEDICO,AFI.IDAFILIADO,AFI.TIPO_DOC,CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END,PLN.TIPOSISTEMA,AFI.PAPELLIDO,
			 AFI.SAPELLIDO,AFI.PNOMBRE,AFI.SNOMBRE,AFI.FNACIMIENTO,AFI.SEXO,AFI.CIUDAD,AFI.ZONA,CIT.N_FACTURA,CIT.IDPLAN,AFI.DOCIDAFILIADO,
			 AFI.TIPOAFILIADO
   ) AS X
   GROUP BY TIPO_DOC, DOCIDAFILIADO, IDALTERNA2,  PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, SEXO, DEP, CIU, ZONA, TIPO

	
   -- US CE
   PRINT 'US CE'
   -- BEGIN ARREGLO JEDM.SOG.001
   PRINT 'REALIZAO #AKK'
   SELECT DISTINCT @ENVIO AS ENVIO, LEFT(AFI.TIPO_DOC,2) AS TIPO_DOC, AFI.DOCIDAFILIADO,
          CASE PLN.TIPOSISTEMA WHEN 'Contributivo' THEN '1' 
                               WHEN 'Subsidiado'   THEN '2'
                               WHEN 'Vinculado'    THEN '3'
                               WHEN 'Particular'   THEN '4'
                               WHEN 'Otro'         THEN '5'
                               WHEN 'Prepagado'    THEN '5'
                               WHEN 'Desplazado Vinc'   THEN '8'
                               WHEN 'Desplazado Reg Cont' THEN '6'
                               WHEN 'Desplazado Reg Subs' THEN '7'  
							   ELSE '1' 
                               
          END AS TIPOSISTEMA
   INTO    #AKK
   FROM   AUTD  INNER JOIN AUT   ON AUTD.IDAUT       = AUT.IDAUT
                INNER JOIN FTRD  ON AUT.NOAUT        = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
                INNER JOIN RIPSD ON RIPSD.N_FACTURA  = FTRD.N_FACTURA
                INNER JOIN FTR   ON FTRD.CNSFTR      = FTR.CNSFCT
                INNER JOIN TER   ON FTR.IDTERCERO    = TER.IDTERCERO
                 LEFT JOIN AFI   ON AUT.IDAFILIADO   = AFI.IDAFILIADO
                 LEFT JOIN PLN   ON AUTD.IDPLAN      = PLN.IDPLAN
   WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
   AND    RIPSD.PROCEDENCIA = 'CE' 
   AND    COALESCE(FTRD.ITFC,0) <> 2
   AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
   AND    NOT EXISTS (SELECT * FROM RRIPS_US WHERE RRIPS_US.ENVIO = @ENVIO  
                      AND RRIPS_US.TIPO_DOC  = AFI.TIPO_DOC  
                      AND RRIPS_US.IDUSUARIO = AFI.DOCIDAFILIADO)
   --AND    AFI.DOCIDAFILIADO NOT IN (SELECT IDUSUARIO FROM RRIPS_US WHERE ENVIO = @ENVIO )
                                                                    
   PRINT '#AKK2'
   SELECT TIPO_DOC, DOCIDAFILIADO, COUNT(*)  AS VECES
   INTO   #AKK2
   FROM   #AKK
   GROUP BY TIPO_DOC, DOCIDAFILIADO
   HAVING COUNT(*) > 1
   PRINT 'BORRO #AKK'
   DELETE #AKK WHERE DOCIDAFILIADO IN ( SELECT DOCIDAFILIADO FROM #AKK2 
                                                  WHERE #AKK2.TIPO_DOC = #AKK.TIPO_DOC )
   
   -- END ARREGLO JEDM.SOG.001
   PRINT 'AHORA SI US CE'
   INSERT INTO RRIPS_US(ENVIO,IDTERCERO,ESTADO,TIPO_DOC,IDUSUARIO,CODENTIDADM,TIPOUSUARIO,PAPELLIDO,
                        SAPELLIDO,PNOMBRE,SNOMBRE,EDAD,UNMEDIDA,SEXO,DEPHABITUAL,MUNHABITUAL,
                        ZONAHABITUAL, TIPOAFILIADO)
   SELECT @ENVIO,@IDTERCERO, 'I', TIPO_DOC, DOCIDAFILIADO, IDALTERNA2, MAX(TIPOSISTEMA), PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE,
		MAX(EDAD), MAX(UM), SEXO, DEP, CIU, ZONA, TIPO
   FROM (
	   SELECT DISTINCT  
			  LEFT(AFI.TIPO_DOC,2)TIPO_DOC, 
			  LEFT(REPLACE(AFI.DOCIDAFILIADO,'.',''),20)DOCIDAFILIADO, 
			 CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END IDALTERNA2, 
			  CASE PLN.TIPOSISTEMA WHEN 'Contributivo' THEN '1' 
								   WHEN 'Subsidiado'   THEN '2'
								   WHEN 'Vinculado'    THEN '3'
								   WHEN 'Particular'   THEN '4'
								   WHEN 'Otro'         THEN '5'
								   WHEN 'Prepagado'    THEN '5'
								   WHEN 'Desplazado Vinc'   THEN '8'
								   WHEN 'Desplazado Reg Cont' THEN '6'
								   WHEN 'Desplazado Reg Subs' THEN '7'
								   ELSE '1' 
			  END TIPOSISTEMA, LEFT(REPLACE(AFI.PAPELLIDO,',',' '),30) PAPELLIDO,  LEFT(REPLACE(AFI.SAPELLIDO,',',' '),30) SAPELLIDO, LEFT(REPLACE(AFI.PNOMBRE,',',' '),20) PNOMBRE,  
			  LEFT(REPLACE(AFI.SNOMBRE,',',' '),20) SNOMBRE,  
	 EDAD         = CASE  
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=0 THEN 1  
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=30 THEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))  
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=365 THEN 
						  CASE WHEN DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(AUT.FECHA))  = 12 THEN 1
							   ELSE DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(AUT.FECHA))
						  END
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=54750 THEN 
                CONVERT(INT,DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))/365.25)
					END,  
	 UM      = CASE  
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=30 THEN '3'  
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=365 THEN 
						  CASE WHEN DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(AUT.FECHA)) = 12 THEN '1'
							   ELSE '2'
						  END  
					 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=54750 THEN '1' 
					END,  
			  CASE WHEN AFI.SEXO ='FEMENINO' THEN 'F' ELSE 'M' END SEXO,  
			  LEFT(AFI.CIUDAD,2) DEP,  
			  SUBSTRING(AFI.CIUDAD,3,3) CIU,  
			  CASE WHEN AFI.ZONA='R' THEN 'R' ELSE 'U' END ZONA, LEFT(AFI.TIPOAFILIADO,1) AS TIPO
	   FROM   AUTD  INNER JOIN AUT   ON AUTD.IDAUT       = AUT.IDAUT
					INNER JOIN FTRD  ON AUT.NOAUT        = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
					INNER JOIN RIPSD ON RIPSD.N_FACTURA  = FTRD.N_FACTURA
					INNER JOIN FTR   ON FTRD.CNSFTR      = FTR.CNSFCT
					INNER JOIN TER   ON FTR.IDTERCERO    = TER.IDTERCERO
					 LEFT JOIN AFI   ON AUT.IDAFILIADO   = AFI.IDAFILIADO
					 LEFT JOIN PLN   ON AUTD.IDPLAN      = PLN.IDPLAN
					 LEFT JOIN PPT ON PPT.IDTERCERO=TER.IDTERCERO AND PPT.IDPLAN=@IDPLAN 
	   WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	   AND    RIPSD.PROCEDENCIA = 'CE' 
	   AND    COALESCE(FTRD.ITFC,0) <> 2
	   AND    AFI.DOCIDAFILIADO NOT IN (SELECT IDUSUARIO FROM RRIPS_US WHERE ENVIO = @ENVIO )  
	   AND    AFI.DOCIDAFILIADO IN (SELECT DOCIDAFILIADO FROM #AKK)
	   AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
		GROUP BY REPLACE(AFI.DOCIDAFILIADO,'.',''),AFI.TIPO_DOC,TER.IDALTERNA2,PLN.TIPOSISTEMA,AFI.PAPELLIDO,
				AFI.SAPELLIDO,AFI.PNOMBRE,AFI.SNOMBRE,AFI.FNACIMIENTO,AFI.SEXO,AFI.CIUDAD,AFI.ZONA,AUTD.IDPLAN,AUTD.NO_ITEM,
				AFI.TIPOAFILIADO,CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END) X
		GROUP BY TIPO_DOC, DOCIDAFILIADO, IDALTERNA2, PAPELLIDO, SAPELLIDO, PNOMBRE, SNOMBRE, SEXO, DEP, CIU, ZONA, TIPO
   DECLARE @DOCIDAFILIADO VARCHAR(20)
   
   DECLARE USREP_CUR CURSOR FOR
   SELECT DOCIDAFILIADO FROM #AKK2
   PRINT 'LOS DUPLICADOS US CE DE A UNO'
   OPEN USREP_CUR
   
   FETCH NEXT FROM USREP_CUR
   INTO @DOCIDAFILIADO
   
   WHILE @@FETCH_STATUS = 0
   BEGIN          
      INSERT INTO RRIPS_US(ENVIO,IDTERCERO,ESTADO,TIPO_DOC,IDUSUARIO,CODENTIDADM,TIPOUSUARIO,PAPELLIDO,
                           SAPELLIDO,PNOMBRE,SNOMBRE,EDAD,UNMEDIDA,SEXO,DEPHABITUAL,MUNHABITUAL,
                           ZONAHABITUAL, TIPOAFILIADO)
      SELECT TOP 1 @ENVIO, @IDTERCERO, 'I', 
             LEFT(AFI.TIPO_DOC,2), 
             REPLACE(AFI.DOCIDAFILIADO,'.',''), 
             CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN  LEFT(ISNULL(TER.IDALTERNA2,''),6) ELSE COALESCE(PPT.IDALTERNA,'') END, 
             CASE PLN.TIPOSISTEMA WHEN 'Contributivo' THEN '1' 
                                  WHEN 'Subsidiado'   THEN '2'
                                  WHEN 'Vinculado'    THEN '3'
                                  WHEN 'Particular'   THEN '4'
                                  WHEN 'Otro'         THEN '5'
                                  WHEN 'Prepagado'    THEN '5'
                                  WHEN 'Desplazado Vinc'   THEN '8'
                                  WHEN 'Desplazado Reg Cont' THEN '6'
                                  WHEN 'Desplazado Reg Subs' THEN '7'
             END, LEFT(REPLACE(AFI.PAPELLIDO,',',' '),30),  LEFT(REPLACE(AFI.SAPELLIDO,',',' '),30), LEFT(REPLACE(AFI.PNOMBRE,',',' '),20),  
             LEFT(REPLACE(AFI.SNOMBRE,',',' '),20),  
 EDAD         = CASE  
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=0 THEN 1  
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=30 THEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))  
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=365 THEN 
                      CASE WHEN DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(AUT.FECHA))  = 12 THEN 1
                           ELSE DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(AUT.FECHA))
                      END
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=54750 THEN 
                 CONVERT(INT,DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))/365.25)
                END,  
 MEDEDAD      = CASE  
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=30 THEN '3'  
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=365 THEN 
                      CASE WHEN DATEDIFF(MONTH,AFI.FNACIMIENTO,MAX(AUT.FECHA)) = 12 THEN '1'
                           ELSE '2'
                      END  
                 WHEN DATEDIFF(DAY,AFI.FNACIMIENTO,MAX(AUT.FECHA))<=54750 THEN '1' 
                END, 
             CASE WHEN AFI.SEXO ='FEMENINO' THEN 'F' ELSE 'M' END,  
             LEFT(AFI.CIUDAD,2),  
             SUBSTRING(AFI.CIUDAD,3,3),  
             CASE WHEN AFI.ZONA='R' THEN 'R' ELSE 'U' END, LEFT(AFI.TIPOAFILIADO,1)
      FROM   AUTD  INNER JOIN AUT   ON AUTD.IDAUT       = AUT.IDAUT
                   INNER JOIN FTRD  ON AUT.NOAUT        = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
                   INNER JOIN RIPSD ON RIPSD.N_FACTURA  = FTRD.N_FACTURA
                   INNER JOIN FTR   ON FTRD.CNSFTR      = FTR.CNSFCT
                   INNER JOIN TER   ON FTR.IDTERCERO    = TER.IDTERCERO
                    LEFT JOIN AFI   ON AUT.IDAFILIADO   = AFI.IDAFILIADO
                    LEFT JOIN PLN   ON AUTD.IDPLAN      = PLN.IDPLAN
                    LEFT JOIN PPT   ON FTR.IDTERCERO    = PPT.IDTERCERO AND AUTD.IDPLAN=PPT.IDPLAN
      WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
      AND    RIPSD.PROCEDENCIA = 'CE' 
      AND    COALESCE(FTRD.ITFC,0) <> 2
      AND    AFI.DOCIDAFILIADO NOT IN (SELECT IDUSUARIO FROM RRIPS_US WHERE ENVIO = @ENVIO )  
      AND    AFI.DOCIDAFILIADO IN (SELECT DOCIDAFILIADO FROM #AKK2)
      AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
	  GROUP BY REPLACE(AFI.DOCIDAFILIADO,'.',''), AFI.TIPO_DOC,PLN.TIPOSISTEMA,AFI.PAPELLIDO,
			   AFI.SAPELLIDO,AFI.PNOMBRE,AFI.SNOMBRE,AFI.FNACIMIENTO,AFI.SEXO,AFI.CIUDAD,AFI.ZONA,AFI.TIPOAFILIADO,
               CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN  LEFT(ISNULL(TER.IDALTERNA2,''),6) ELSE COALESCE(PPT.IDALTERNA,'') END 

			      
      FETCH NEXT FROM USREP_CUR
      INTO @DOCIDAFILIADO

   END
   CLOSE USREP_CUR
   DEALLOCATE USREP_CUR
   
   DROP TABLE #AKK   
   DROP TABLE #AKK2   
   
   SELECT @COUNT_US = COUNT(1) FROM RRIPS_US WHERE ENVIO=@ENVIO

   -- AP CE   
 PRINT 'AP CE'
 INSERT INTO RRIPS_AP(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,FECHAPROCEDIMIENTO,
                      NUMAUT,IDPROCEDIMIENTO,AMBITO,FINPROCEDIMIENTO,PERSONALA,DXPPAL,DXREL,
                      COMPLICACION,ACTOQ, VALORPROCED, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, 
                      CANTIDAD, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL)
 SELECT @ENVIO, @IDTERCERO, 'I', FTRD.N_FACTURA, @CODPREST, 
        LEFT(AFI.TIPO_DOC,2),          
        REPLACE(AFI.DOCIDAFILIADO,'.',''),  AUT.FECHA, CASE  WHEN  @IPS ='SANAS' and ripsd.IDTERCERO='0100000169' THEN 'AISMA006' WHEN  COALESCE(LEFT(AUTD.NOAUTORIZEXT,20),'') = '' THEN LEFT(AUT.NUMAUTORIZA,20)
		ELSE LEFT(AUTD.NOAUTORIZEXT,20) END AS AUTORIZA,
		CASE @CODSER WHEN '0' THEN LEFT(SER.IDSERVICIO,8) WHEN '1' THEN LEFT(SER.IDALTERNA,8) WHEN '8' THEN LEFT(SER.CODCUPS,8) ELSE LEFT(SER.IDALTERNA,8) END, 
        CASE WHEN NOT AUT.AMBITO IN ('1','2','3') THEN '1' ELSE LEFT(AUT.AMBITO,1) END,  
        LEFT(CASE WHEN AUT.FINALIDAD IS NULL OR AUT.FINALIDAD='' THEN '5' ELSE AUT.FINALIDAD END,1),

		CASE WHEN SER.IDSERVICIO IN (SELECT CODIGO FROM TGEN WHERE TABLA='General' AND CAMPO='CODPARTOS')
		     THEN CASE WHEN AUT.PERSONAL_AT='' OR AUT.PERSONAL_AT IS NULL THEN '5' ELSE LEFT(AUT.PERSONAL_AT,1) END
			 ELSE CASE WHEN @IPS IN ('CIME','CENDI','INOVA') THEN '' ELSE LEFT(AUT.PERSONAL_AT,1)END END,
        CASE WHEN @IPS IN ('CIME','CENDI') THEN CASE WHEN @AUTSINHC = 'SI'
					THEN
					   CASE WHEN COALESCE(LEFT(AUT.DXPPAL,4),'') ='' THEN DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC') ELSE COALESCE(LEFT(AUT.DXPPAL,4),'') END 
		
										  ELSE (SELECT TOP 1 MDX.IDDX 
											   FROM  #DX HCA	LEFT JOIN MDX ON HCA.DXPPAL = MDX.IDDX
											   WHERE  HCA.IDAFILIADO = AUT.IDAFILIADO 
											   AND    CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,AUT.FECHA,102)
											   ) 
											   
										  END 
			 ELSE 
					 CASE WHEN COALESCE ((SELECT TOP 1 MDX.IDDX 
												   FROM  #DX HCA	LEFT JOIN MDX ON HCA.DXPPAL = MDX.IDDX
												   WHERE  HCA.IDAFILIADO = AUT.IDAFILIADO 
												   AND    CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,AUT.FECHA,102)),'')='' 
										  THEN CASE WHEN COALESCE(LEFT(AUT.DXPPAL,4),'') ='' THEN 'Z000'  ELSE LEFT(AUT.DXPPAL,4) END
					ELSE     
					   CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS
								 THEN 
									(CASE 
										WHEN (SELECT TOP 1 MDX.IDDX FROM HCA LEFT JOIN MDX ON HCA.IDDX=MDX.IDDX 
											  WHERE HCA.CONSECUTIVO=AUT.CONSECUTIVOHCA AND COALESCE(HCA.ANULADA,0)=0) IS NULL
										THEN 'Z000' 
										ELSE LEFT((SELECT TOP 1 MDX.IDDX FROM HCA LEFT JOIN MDX ON HCA.IDDX=MDX.IDDX 
											 WHERE HCA.CONSECUTIVO=AUT.CONSECUTIVOHCA AND COALESCE(HCA.ANULADA,0)=0),4)
									 END)
								 ELSE 'Z000' 
					   END
					END
		END  ,
        CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS
                  THEN 
                   (CASE 
                   WHEN (SELECT TOP 1 MDX.IDDX FROM HCA LEFT JOIN MDX ON HCA.DX1=MDX.IDDX 
                         WHERE HCA.CONSECUTIVO=AUT.CONSECUTIVOHCA AND COALESCE(HCA.ANULADA,0)=0) IS NULL
                   THEN '' 
                   ELSE
                    LEFT((SELECT TOP 1 MDX.IDDX FROM HCA LEFT JOIN MDX ON HCA.DX1=MDX.IDDX 
                           WHERE HCA.CONSECUTIVO=AUT.CONSECUTIVOHCA AND COALESCE(HCA.ANULADA,0)=0),4)
                    END)
                  ELSE ''
        END,
        CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS
                   THEN AUT.COMPLICACION
                   ELSE '' 
        END,  
        CASE WHEN @IPS='CIME' THEN ''
			 WHEN  @IPS IN ('SANAS','INOVA') THEN '1'	
			 WHEN @IPS IN ('SANAS','CENDI') AND  SER.CODIGORIPS = @IDPROTERQXRIPS THEN '1'	
			ELSE   CASE WHEN ISNULL(AUT.FORMAQX,'') <> ''
						THEN AUT.FORMAQX
						ELSE ''
						END
        END,  
        CASE WHEN @RIPS_SINDEDUCCOPAGO='SI' THEN
            CAST(CAST(ROUND((FTRD.VALOR * FTRD.CANTIDAD),2)AS decimal(14,0))AS VARCHAR(15))
             WHEN @RIPS_COPAGOS<>'SI' THEN 
            CAST(CAST(ROUND((FTRD.VALOR * FTRD.CANTIDAD),2)AS decimal(14,0))AS VARCHAR(15))
        ELSE
            CASE ISNULL(FTRD.VR_TOTAL,0) WHEN 0 THEN CONVERT(VARCHAR(15), (FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS) ELSE  CAST(CAST(VR_TOTAL AS DECIMAL(14,0)) AS VARCHAR(15))  END
        END, 
        AUT.NOAUT, AUTD.NO_ITEM, FTRD.CNSFTR, FTRD.N_CUOTA, FTRD.CANTIDAD, 'CE', 
        AUT.DXPPAL, SER.IDSERVICIO, FTRD.CODEVAL 
  FROM  AUTD INNER JOIN AUT     ON AUTD.IDAUT             = AUT.IDAUT
             INNER JOIN FTRD    ON AUT.NOAUT              = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
             INNER JOIN RIPSD   ON RIPSD.N_FACTURA        = FTRD.N_FACTURA
              LEFT JOIN AFI     ON AUT.IDAFILIADO         = AFI.IDAFILIADO
              LEFT JOIN SER     ON SER.IDSERVICIO         = AUTD.IDSERVICIO 
              LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    COALESCE(FTRD.ITFC,0) <> 2
  AND    RIPSD.PROCEDENCIA = 'CE'
  AND    RIPS_CP.ARCHIVO   = 'AP' 
  AND AUTD.CANTIDAD>=1 
  AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
  
  PRINT 'LA VARIABLE RIPSAGRUPADOS QUEDO ASI: '+ @RIPS_AGRUPADOS
  --IF EXISTS (SELECT * FROM RRIPS_AP WHERE CANTIDAD>1 AND ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) 
  --BEGIN

	 --  DECLARE RRIPS_AP_CUR CURSOR FOR 
  --    SELECT ITEM,CANTIDAD FROM RRIPS_AP WHERE CANTIDAD>1 AND ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
  --    ORDER BY ITEM 
	 --  OPEN RRIPS_AP_CUR    
	 --  FETCH NEXT FROM RRIPS_AP_CUR    
	 --  INTO @ITEM,@CANT
	 --  WHILE @@FETCH_STATUS = 0    
	 --  BEGIN
  --       UPDATE RRIPS_AP SET CANTIDAD=1,VALORPROCED=ROUND((CAST(VALORPROCED/@CANT AS DECIMAL(18,0))),0) WHERE ENVIO=@ENVIO AND ITEM=@ITEM --STORRES SE AGREGA CAST EN CAMPO VALORPROCED
  --       SELECT * INTO #XR FROM RRIPS_AP WHERE ENVIO=@ENVIO AND ITEM=@ITEM
  --       SELECT @BAND=1
  --       WHILE @BAND<@CANT
  --       BEGIN
  --           INSERT INTO RRIPS_AP(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,FECHAPROCEDIMIENTO,
  --                                NUMAUT,IDPROCEDIMIENTO,AMBITO,FINPROCEDIMIENTO,PERSONALA,DXPPAL,DXREL,
  --                                COMPLICACION,ACTOQ, VALORPROCED, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, 
  --                                CANTIDAD, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL)
  --           SELECT ENVIO,@IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,FECHAPROCEDIMIENTO,
  --                                NUMAUT,IDPROCEDIMIENTO,AMBITO,FINPROCEDIMIENTO,PERSONALA,DXPPAL,DXREL,
  --                                COMPLICACION,ACTOQ, VALORPROCED, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, 
  --                                CANTIDAD, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL
  --           FROM #XR
  --           SELECT @BAND=@BAND+1
  --       END
  --       DROP TABLE #XR
	 --  FETCH NEXT FROM RRIPS_AP_CUR    
	 --  INTO @ITEM,@CANT
	 --  END
	 --  CLOSE RRIPS_AP_CUR
	 --  DEALLOCATE RRIPS_AP_CUR      
  --END



  -- AP CI   
  PRINT 'AP CI'
  INSERT INTO RRIPS_AP(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,FECHAPROCEDIMIENTO,
                       NUMAUT,IDPROCEDIMIENTO, AMBITO,FINPROCEDIMIENTO,PERSONALA,DXPPAL,DXREL,
                       COMPLICACION, ACTOQ, VALORPROCED, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, 
                       CANTIDAD, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL )
  SELECT @ENVIO, @IDTERCERO, 'I', CIT.N_FACTURA, @CODPREST,
         LEFT(AFI.TIPO_DOC,2),  
         REPLACE(AFI.DOCIDAFILIADO,'.',''), CIT.FECHA, LEFT(CIT.NOAUTORIZACION,15),  
		 CASE @CODSER WHEN '0' THEN LEFT(SER.IDSERVICIO,8) WHEN '1' THEN LEFT(SER.IDALTERNA,8) WHEN '8' THEN LEFT(SER.CODCUPS,8) ELSE LEFT(SER.IDALTERNA,8) END,  
          '1' ,  
         LEFT(CASE WHEN CIT.FINALIDAD IS NULL OR CIT.FINALIDAD='' THEN '5' ELSE CIT.FINALIDAD END,1), '',  
           CASE WHEN @IPS='CENDI' THEN  CASE WHEN COALESCE ((SELECT TOP 1 MDX.IDDX 
												   FROM  #DX HCA	LEFT JOIN MDX ON HCA.DXPPAL = MDX.IDDX
												   WHERE  HCA.IDAFILIADO = CIT.IDAFILIADO  
												 AND( FTRD.N_FACTURA=HCA.N_FACTURA OR  CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102)) AND  HCA.DXPPAL<>'Z000'),'')='' 
												   
										  THEN 'Z000' 
										  ELSE (SELECT TOP 1 MDX.IDDX 
											   FROM  #DX HCA	LEFT JOIN MDX ON HCA.DXPPAL = MDX.IDDX
											   WHERE  HCA.IDAFILIADO = CIT.IDAFILIADO 
											   AND( FTRD.N_FACTURA=HCA.N_FACTURA OR  CONVERT(VARCHAR,HCA.FECHA,102) = CONVERT(VARCHAR,CIT.FECHA,102)) AND HCA.DXPPAL<>'Z000') 
										  END 
			 ELSE 
		 CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS
                   THEN CASE WHEN LEFT(COALESCE(HCA.IDDX, 'SINH'),4) ='SINH'  AND @AUTSINHC='SI' 
							 THEN    DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC')
							 ELSE LEFT(COALESCE(HCA.IDDX, 'SINHC'),4) END                --STORRES SE CAMBIA CIT.IDDX POR HCA.IDDX Y SE AGREGA PARA QEU SOLO TRAIGA LOS 4 PRIMEROS DIGITOS
                   ELSE CASE WHEN COALESCE(CIT.IDDX,'') = '' THEN COALESCE(HCA.IDDX, DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC')) ELSE COALESCE(CIT.IDDX,'') END END
		 END, '', '', CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS THEN '1' ELSE '' END ACTOQX , 
        CASE WHEN @RIPS_SINDEDUCCOPAGO='SI' THEN
            CAST(CAST(ROUND((FTRD.VALOR * FTRD.CANTIDAD),2)AS decimal(14,0))AS VARCHAR(15))
             WHEN @RIPS_COPAGOS<>'SI' THEN 
            CAST(CAST(ROUND((FTRD.VALOR * FTRD.CANTIDAD),2)AS decimal(14,0))AS VARCHAR(15))
        ELSE
            CASE ISNULL(FTRD.VR_TOTAL,0) WHEN 0 THEN CONVERT(VARCHAR(15), (FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS) ELSE  CAST(CAST(VR_TOTAL AS DECIMAL(14,0)) AS VARCHAR(15))  END
        END,        
         CIT.CONSECUTIVO, NULL, FTRD.CNSFTR, FTRD.N_CUOTA, FTRD.CANTIDAD, 'CI', 
        CASE WHEN LEFT(COALESCE(HCA.IDDX, 'SINH'),4) ='SINH'  AND @AUTSINHC='SI'
			 THEN    DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC') 
			 ELSE LEFT(COALESCE(HCA.IDDX, 'SINH'),4) END , SER.IDSERVICIO, FTRD.CODEVAL           --STORRES SE CAMBIA CIT.IDDX POR HCA.IDDX Y SE AGREGA PARA QEU SOLO TRAIGA LOS 4 PRIMEROS DIGITOS
  FROM   RIPSD INNER JOIN FTRD    ON RIPSD.N_FACTURA   = FTRD.N_FACTURA
               INNER JOIN CIT     ON FTRD.NOPRESTACION = CIT.CONSECUTIVO
                LEFT JOIN AFI     ON CIT.IDAFILIADO    = AFI.IDAFILIADO 
                LEFT JOIN SER     ON CIT.IDSERVICIO    = SER.IDSERVICIO 
                LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
                LEFT JOIN (SELECT HCA.NOADMISION,MAX( HCA.IDDX) IDDX, MAX(HCA.CONSECUTIVO) AS CONSECUTIVO   --STORRES  SE AGREGA CONSULTA DE HCA PARA UNIR A LA CONSULTA LOS DATOS DE LOS DIAGNOSTICOS 
                           FROM HCA                                                               --SIN DUPLICIDAD Y ASI NO DA?AR LA CONSULTA ORIGINAL
                           WHERE HCA.PROCEDENCIA = 'IPS' AND COALESCE(HCA.ANULADA,0)=0
                           GROUP BY HCA.NOADMISION
                          )   HCA ON CIT.CONSECUTIVO = HCA.NOADMISION          
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    RIPSD.PROCEDENCIA = CASE WHEN RIPSD.NOADMISION='CEUNIFICADO' THEN RIPSD.PROCEDENCIA ELSE 'CI' END
  AND    RIPS_CP.ARCHIVO   = 'AP'  
  AND    COALESCE(FTRD.ITFC,0) <> 2
  AND    FACTURABLE = CASE @ENVIAR_NOCOB_CI_RIPS WHEN 'NO' THEN 1 ELSE FACTURABLE END 
  UNION ALL
  SELECT @ENVIO, @IDTERCERO, 'I', FTR.N_FACTURA, @CODPREST,
         LEFT(AFI.TIPO_DOC,2),  
         REPLACE(AFI.DOCIDAFILIADO,'.',''), FTR.F_FACTURA, LEFT('',15),  --PENDIENTE AUTORIZACION
		 CASE @CODSER WHEN '0' THEN LEFT(SER.IDSERVICIO,8) WHEN '1' THEN LEFT(SER.IDALTERNA,8) WHEN '8' THEN LEFT(SER.CODCUPS,8) ELSE LEFT(SER.IDALTERNA,8) END,  
          '1' ,  
         LEFT('5',1), '',  
		 CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS
                   THEN CASE WHEN LEFT(COALESCE(HCA.IDDX, 'SINH'),4) ='SINH'  AND @AUTSINHC='SI' 
							 THEN    DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC')
							 ELSE LEFT(COALESCE(HCA.IDDX, 'SINHC'),4) END                --STORRES SE CAMBIA CIT.IDDX POR HCA.IDDX Y SE AGREGA PARA QEU SOLO TRAIGA LOS 4 PRIMEROS DIGITOS
                   ELSE CASE WHEN COALESCE('','') = '' THEN COALESCE(HCA.IDDX, DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC')) ELSE '' 
				   END
		 END, '', '', CASE WHEN SER.CODIGORIPS = @IDPROTERQXRIPS THEN '1' ELSE '' END ACTOQX , 
        CASE WHEN @RIPS_SINDEDUCCOPAGO='SI' THEN
            CAST(CAST(ROUND((FTRD.VALOR * FTRD.CANTIDAD),2)AS decimal(14,0))AS VARCHAR(15))
             WHEN @RIPS_COPAGOS<>'SI' THEN 
            CAST(CAST(ROUND((FTRD.VALOR * FTRD.CANTIDAD),2)AS decimal(14,0))AS VARCHAR(15))
        ELSE
            CASE ISNULL(FTRD.VR_TOTAL,0) WHEN 0 THEN CONVERT(VARCHAR(15), (FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS) ELSE  CAST(CAST(FTRD.VR_TOTAL AS DECIMAL(14,0)) AS VARCHAR(15))  END
        END,        
         FMAS.CNSFMAS, NULL, FTRD.CNSFTR, FTRD.N_CUOTA, FTRD.CANTIDAD, 'CI', 
        CASE WHEN LEFT(COALESCE(HCA.IDDX, 'SINH'),4) ='SINH'  AND @AUTSINHC='SI'
			 THEN    DBO.FNK_VALORVARIABLE('RIPS_DX_CITA_SIN_HC') 
			 ELSE LEFT(COALESCE(HCA.IDDX, 'SINH'),4) END , SER.IDSERVICIO, FTRD.CODEVAL           --STORRES SE CAMBIA CIT.IDDX POR HCA.IDDX Y SE AGREGA PARA QEU SOLO TRAIGA LOS 4 PRIMEROS DIGITOS
  FROM   RIPSD INNER JOIN FTRD    ON RIPSD.N_FACTURA   = FTRD.N_FACTURA
               INNER JOIN FTR     ON FTR.CNSFCT    = FTRD.CNSFTR 
               INNER JOIN FMAS     ON FMAS.N_FACTURA = FTR.N_FACTURA AND FTRD.REFERENCIA=FMAS.IDSERPAQ
			   INNER JOIN AFI ON AFI.IDAFILIADO=FTR.IDAFILIADO
                INNER JOIN SER     ON FMAS.IDSERPAQ    = SER.IDSERVICIO 
                LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
                LEFT JOIN (SELECT HCA.NOADMISION,MAX( HCA.IDDX) IDDX, MAX(HCA.CONSECUTIVO) AS CONSECUTIVO   --STORRES  SE AGREGA CONSULTA DE HCA PARA UNIR A LA CONSULTA LOS DATOS DE LOS DIAGNOSTICOS 
                           FROM HCA                                                               --SIN DUPLICIDAD Y ASI NO DA?AR LA CONSULTA ORIGINAL
                           WHERE HCA.PROCEDENCIA = 'IPS' AND COALESCE(HCA.ANULADA,0)=0
                           GROUP BY HCA.NOADMISION
                          )   HCA ON FTRD.NOADMISION = HCA.NOADMISION
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    RIPSD.PROCEDENCIA = 'CI'
  AND    RIPS_CP.ARCHIVO   = 'AP'
  AND    COALESCE(FTRD.ITFC,0) <> 2
 PRINT 'LA VARIABLE RIPSAGRUPADOS QUEDO ASI: '+ @RIPS_AGRUPADOS
 IF DBO.FNK_VALORVARIABLE('RIPS_RETIRA_FMASDPAQ')='SI'
 BEGIN
    PRINT 'BUSCO LAS FACTURAS'
    DECLARE @DATOFMAS TABLE(N_FACTURA VARCHAR(20),IDSERVICIO VARCHAR(20),NUMAUT VARCHAR(20),FECHAPROCE DATETIME)
    INSERT INTO @DATOFMAS
    SELECT  N_FACTURA,IDSERPAQ,NULL,NULL FROM FMAS 
    WHERE EXISTS(SELECT  * FROM RRIPS_AP 
    WHERE ENVIO=@ENVIO 
    AND RRIPS_AP.NUMFACTURA=FMAS.N_FACTURA
    AND COALESCE(PAQUETE,0)=1)

    UPDATE @DATOFMAS SET NUMAUT=RP.NUMAUT,FECHAPROCE=FECHAPRO
    FROM @DATOFMAS F INNER JOIN (SELECT NUMFACTURA,NUMAUT,MAX(FECHAPROCEDIMIENTO)FECHAPRO
                              FROM RRIPS_AP WHERE ENVIO=@ENVIO 
                              AND COALESCE(NUMAUT,'')<>'' 
                              AND LEN(NUMAUT)>5 
                              GROUP BY NUMFACTURA,NUMAUT) RP ON F.N_FACTURA=RP.NUMFACTURA
    WHERE F.N_FACTURA=RP.NUMFACTURA
    
    DELETE RRIPS_AP
    FROM RRIPS_AP INNER JOIN @DATOFMAS X ON RRIPS_AP.NUMFACTURA=X.N_FACTURA
    WHERE RRIPS_AP.ENVIO=@ENVIO
    AND RRIPS_AP.IDSERVICIO<>X.IDSERVICIO

    UPDATE RRIPS_AP SET NUMAUT=X.NUMAUT,FECHAPROCEDIMIENTO=X.FECHAPROCE
    FROM RRIPS_AP INNER JOIN @DATOFMAS X ON RRIPS_AP.NUMFACTURA=X.N_FACTURA
    WHERE RRIPS_AP.ENVIO=@ENVIO

 END
  IF EXISTS (SELECT * FROM RRIPS_AP WHERE CANTIDAD>1 AND ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) 
  BEGIN
      SET @ITEM = 0
      SET @CANT =0 
      SET @BAND =0
	   DECLARE RRIPS_AP_CUR CURSOR FOR 
      SELECT ITEM,CANTIDAD FROM RRIPS_AP WHERE CANTIDAD>1 AND ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
      ORDER BY ITEM 
	   OPEN RRIPS_AP_CUR    
	   FETCH NEXT FROM RRIPS_AP_CUR    
	   INTO @ITEM,@CANT
	   WHILE @@FETCH_STATUS = 0    
	   BEGIN
         UPDATE RRIPS_AP SET CANTIDAD=1,VALORPROCED=CONVERT(VARCHAR,IIF(@RIPS_VALORENTERO='SI', ROUND((CAST(VALORPROCED AS DECIMAL(18,0))/@CANT),0), ROUND((CAST(CAST(VALORPROCED AS DECIMAL(18,2))/@CANT AS DECIMAL(18,2))),2))) WHERE ENVIO=@ENVIO AND ITEM=@ITEM --STORRES SE AGREGA CAST EN CAMPO VALORPROCED
         SELECT * INTO #XR FROM RRIPS_AP WHERE ENVIO=@ENVIO AND ITEM=@ITEM
         SELECT @BAND=1
         WHILE @BAND<@CANT
         BEGIN
             INSERT INTO RRIPS_AP(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,FECHAPROCEDIMIENTO,
                                  NUMAUT,IDPROCEDIMIENTO,AMBITO,FINPROCEDIMIENTO,PERSONALA,DXPPAL,DXREL,
                                  COMPLICACION,ACTOQ, VALORPROCED, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, 
                                  CANTIDAD, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL)
             SELECT ENVIO,@IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,FECHAPROCEDIMIENTO,
                                  NUMAUT,IDPROCEDIMIENTO,AMBITO,FINPROCEDIMIENTO,PERSONALA,DXPPAL,DXREL,
                                  COMPLICACION,ACTOQ, VALORPROCED, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA, 
                                  CANTIDAD, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL
             FROM #XR
             SELECT @BAND=@BAND+1
         END
         DROP TABLE #XR
	   FETCH NEXT FROM RRIPS_AP_CUR    
	   INTO @ITEM,@CANT
	   END
	   CLOSE RRIPS_AP_CUR
	   DEALLOCATE RRIPS_AP_CUR      
  END
   IF @RIPS_AGRUPADOS = 'SI' 
   BEGIN
      PRINT 'ENTRE AQUI HAGO TEMPORAL'

	  SELECT * INTO #A FROM RRIPS_AP WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO

	  PRINT 'BORRO RRIPS_AP'

	  DELETE RRIPS_AP WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO

	  PRINT 'LUEGO INSERTO REGISTRO DE LA TEMPORAL'
      
	  INSERT INTO RRIPS_AP (ENVIO, IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHAPROCEDIMIENTO, NUMAUT, IDPROCEDIMIENTO, AMBITO, FINPROCEDIMIENTO, PERSONALA, DXPPAL, DXREL,
							COMPLICACION, ACTOQ,VALORPROCED,FECHARECIBO, ESTADO, FECHAENVIO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA,CANTIDAD, IDDX, PROCEDENCIA, IDSERVICIO, CODEVAL)
	  SELECT ENVIO, @IDTERCERO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHAPROCEDIMIENTO, NUMAUT, IDPROCEDIMIENTO, AMBITO, FINPROCEDIMIENTO, PERSONALA, DXPPAL, DXREL,
	  COMPLICACION, ACTOQ,CONVERT(VARCHAR(15), SUM(CONVERT(DECIMAL(14,0),VALORPROCED)))VALORPROCED, 
	  FECHARECIBO, ESTADO, FECHAENVIO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA,1 CANTIDAD, IDDX, PROCEDENCIA, IDSERVICIO, CODEVAL
	  FROM #A WHERE ENVIO=@ENVIO 
	  GROUP BY ENVIO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, FECHAPROCEDIMIENTO, NUMAUT, IDPROCEDIMIENTO, AMBITO, FINPROCEDIMIENTO, PERSONALA, DXPPAL, DXREL, COMPLICACION, ACTOQ ,
		FECHARECIBO, ESTADO, FECHAENVIO, NOPRESTACION, NOITEM, CNSFTR, N_CUOTA,  IDDX, PROCEDENCIA, IDSERVICIO, CODEVAL

      PRINT 'DESPUES DE INSERTAR BORRO LA TEMPORAL '
      DROP TABLE #A 
	  PRINT 'EXITOSO'
   END                                               
 SELECT @COUNT_AP = COUNT(*) FROM RRIPS_AP WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
 SELECT @COUNT_AP = COUNT(*) FROM RRIPS_AP WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
--query2
--query2
 -- AM 
 PRINT 'AM'
 INSERT INTO RRIPS_AM(ENVIO,IDTERCERO,ESTADO,NUMFACTURA,IDPRESTADOR,TIPO_DOC,IDUSUARIO,NUMAUT,
                      IDMEDICAMENTO, TIPOMEDICAMENTO, NOMBREMEDI, FORMAFARMA, CONCMEDI,
                      UMEDMEDI, NUMUNIDADES, VALORUNIMEDI, VALORTOTMEDI, NOPRESTACION, 
                      NOITEM, CNSFTR, N_CUOTA, PROCEDENCIA, IDDX, IDSERVICIO, CODEVAL, 
                      FECHAMEDICAMENTO) 
 SELECT @ENVIO, @IDTERCERO, 'I', AUTD.N_FACTURA, @CODPREST, 
        LEFT(AFI.TIPO_DOC,2),  REPLACE(AFI.DOCIDAFILIADO,'.',''), CASE COALESCE(LEFT(AUTD.NOAUTORIZEXT,20),'') WHEN '' THEN LEFT(AUT.NUMAUTORIZA,20) ELSE LEFT(AUTD.NOAUTORIZEXT,20) END AS AUTORIZA,    
        CASE WHEN SER.CODIGORIPS='12' THEN SER.IDALTERNA ELSE '' END,  
        CASE WHEN SER.CODIGORIPS='12' THEN '1' WHEN SER.CODIGORIPS='13' THEN '2' END,  
        LEFT(REPLACE(SER.DESCSERVICIO,',',';'),30),  
             CASE SER.CODIGORIPS WHEN  @IDMEDPOSRIPS THEN CASE WHEN @RIPS_AM_DATOSMEDPOS = 'SI' THEN ISNULL(LEFT(IFFA.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(IFFA.DESCRIPCION,20),'') END,
             CASE SER.CODIGORIPS WHEN  @IDMEDPOSRIPS THEN CASE WHEN @RIPS_AM_DATOSMEDPOS = 'SI' THEN ISNULL(LEFT(ICCN.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(ICCN.DESCRIPCION,20),'') END,
             CASE SER.CODIGORIPS WHEN  @IDMEDPOSRIPS THEN CASE WHEN @RIPS_AM_DATOSMEDPOS = 'SI' THEN ISNULL(LEFT(IUNI.DESCRIPCION,20),'') ELSE '' END  ELSE ISNULL(LEFT(IUNI.DESCRIPCION,20),'') END, 
        CONVERT(INT,AUTD.CANTIDAD), AUTD.VALOR,    
        CASE WHEN ISNULL(FTRD.VR_TOTAL,0)=0 
            THEN CAST ((FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS AS DECIMAL (14,2)) 
             WHEN @RIPS_COPAGOS<>'SI'
            THEN CAST ((FTRD.VALOR * FTRD.CANTIDAD) AS DECIMAL (14,2)) 
        ELSE CAST (FTRD.VR_TOTAL AS DECIMAL (14,2)) END,         
        AUT.NOAUT, AUTD.NO_ITEM, FTRD.CNSFTR, FTRD.N_CUOTA, 'CE', AUT.DXPPAL, 
        SER.IDSERVICIO, FTRD.CODEVAL, AUT.FECHA
 FROM  AUTD INNER JOIN AUT     ON AUTD.IDAUT             = AUT.IDAUT
             INNER JOIN FTRD    ON AUT.NOAUT              = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
             INNER JOIN RIPSD   ON RIPSD.N_FACTURA        = FTRD.N_FACTURA
              LEFT JOIN AFI     ON AUT.IDAFILIADO         = AFI.IDAFILIADO
              LEFT JOIN SER     ON SER.IDSERVICIO         = AUTD.IDSERVICIO 
              LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
              LEFT JOIN IART    ON IART.IDARTICULO        = SER.IDARTICULO 
              LEFT JOIN IUNI    ON IART.IDUNIDAD       = IUNI.IDUNIDAD
              LEFT JOIN ICCN    ON IART.IDCONCENTRA    = ICCN.IDCONCENTRA
              LEFT JOIN IFFA    ON IART.IDFORFARM      = IFFA.IDFORFARM
              LEFT JOIN IGEN    ON IART.IDGENERICO        = IGEN.IDGENERICO  
 WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
 AND    RIPSD.PROCEDENCIA = 'CE'
 AND    RIPS_CP.ARCHIVO   = 'AM'  
 AND    COALESCE(FTRD.ITFC,0) <> 2   
 AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
  
  SELECT @COUNT_AM = COUNT(*) FROM RRIPS_AM WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
  PRINT 'AT' 
  INSERT INTO RRIPS_AT(ENVIO, IDTERCERO, ESTADO, NUMFACTURA, IDPRESTADOR, TIPO_DOC, IDUSUARIO, NUMAUT, TIPOSERVICIO,
                       IDSERVICIO, DESCRIPCIONSER, CANTIDAD, VLRUNITMAT, VLRTOTMAT, NOPRESTACION, 
                       NOITEM, CNSFTR, N_CUOTA, PROCEDENCIA, IDDX, IDSERVICIOORI, CODEVAL,
                       FECHAPROCEDIMIENTO )
  SELECT @ENVIO, @IDTERCERO, 'I', AUTD.N_FACTURA, @CODPREST, 
         LEFT(AFI.TIPO_DOC,2),  
         REPLACE(AFI.DOCIDAFILIADO,'.',''), CASE COALESCE(LEFT(AUTD.NOAUTORIZEXT,20),'') WHEN '' THEN LEFT(AUT.NUMAUTORIZA,20) ELSE LEFT(AUTD.NOAUTORIZEXT,20) END AS AUTORIZA,  
         CASE RIPS_CP.IDCONCEPTORIPS
                     WHEN '06' THEN '3'  
                     WHEN '07' THEN '4'  
                     WHEN '08' THEN '3'  
                     WHEN '09' THEN '1'  
                     WHEN '10' THEN '1'  
                     WHEN '11' THEN '1'  
                     WHEN '14' THEN '2' 
         END,
		 CASE @CODSER WHEN '0' THEN LEFT(SER.IDSERVICIO,8) WHEN '1' THEN LEFT(SER.IDALTERNA,8) WHEN '8' THEN LEFT(SER.CODCUPS,8) ELSE LEFT(SER.IDALTERNA,8) END,
		 CASE @CODSER WHEN '8' THEN LEFT(REPLACE(SER.DESCRIPCION_CUPS,',',';'),30) ELSE LEFT(REPLACE(SER.DESCSERVICIO,',',';'),30) END, 
         CONVERT(INT,AUTD.CANTIDAD)CANTIDAD, AUTD.VALOR, 
         CASE ISNULL(FTRD.VR_TOTAL,0)WHEN 0 THEN CAST ((FTRD.VALOR * FTRD.CANTIDAD) - FTRD.VLR_COPAGOS AS DECIMAL (14,2)) ELSE CAST (FTRD.VR_TOTAL AS DECIMAL (14,0)) END,
         AUT.NOAUT, AUTD.NO_ITEM, FTRD.CNSFTR, FTRD.N_CUOTA, 'CE', AUT.DXPPAL, SER.IDSERVICIO, 
         FTRD.CODEVAL, AUT.FECHA
  FROM   AUTD INNER JOIN AUT     ON AUTD.IDAUT             = AUT.IDAUT
              INNER JOIN FTRD    ON AUT.NOAUT              = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
              INNER JOIN RIPSD   ON RIPSD.N_FACTURA        = FTRD.N_FACTURA
               LEFT JOIN AFI     ON AUT.IDAFILIADO         = AFI.IDAFILIADO
               LEFT JOIN SER     ON SER.IDSERVICIO         = AUTD.IDSERVICIO 
               LEFT JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    RIPSD.PROCEDENCIA = 'CE'
  AND    RIPS_CP.ARCHIVO   = 'AT'  
  AND    COALESCE(FTRD.ITFC,0) <> 2     
  AND    COALESCE(AUTD.NOCOBRABLE,0)= CASE WHEN @ENVIAR_NOCOB_CE_RIPS = 'NO' THEN 0 ELSE COALESCE(AUTD.NOCOBRABLE,0) END
 --para que vengan las consultas de gestion CEM
   UNION ALL
    SELECT @ENVIO, @IDTERCERO, 'I',CIT.N_FACTURA, @CODPREST, 
          LEFT(AFI.TIPO_DOC,2),  
          REPLACE(AFI.DOCIDAFILIADO,'.',''), LEFT(CIT.NOAUTORIZACION,15),  
          CASE RIPS_CP.IDCONCEPTORIPS
                     WHEN '06' THEN '3'  
                     WHEN '07' THEN '4'  
                     WHEN '08' THEN '3'  
                     WHEN '09' THEN '1'  
                     WHEN '10' THEN '1'  
                     WHEN '11' THEN '1'  
                     WHEN '14' THEN '2' 
         END,  
         REPLACE(SER.IDALTERNA,'-',''),  LEFT(REPLACE(SER.DESCRIPCION_CUPS,',',';'),30),  
         CAST (ROUND ( CIT.CANTIDADC,0)AS INT), CIT.VALORTOTAL, 
       CAST (ROUND (CASE ISNULL((CIT.VALORTOTAL * CIT.CANTIDADC),0)WHEN 0 THEN (CIT.VALORTOTAL * CIT.CANTIDADC) - CIT.VALORCOPAGO ELSE (CIT.VALORTOTAL * CIT.CANTIDADC) END,0)AS INT )
		, 
         CIT.CONSECUTIVO, 1, ISNULL(CIT.CNSFACT,'EXTERNO'), 1, 'CE', CIT.IDDX, SER.IDSERVICIO, 
         'CODEVAL', CIT.FECHA
  	FROM   CIT	INNER JOIN RIPSD   ON RIPSD.NOADMISION       = CIT.CONSECUTIVO
				   INNER JOIN AFI     ON CIT.IDAFILIADO         = AFI.IDAFILIADO
				   LEFT  JOIN SER     ON SER.IDSERVICIO         = CIT.IDSERVICIO 
			   	LEFT  JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
               LEFT  JOIN MPE     ON MPE.IDPESPECIAL=CIT.IDPESPECIAL 
	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	AND    (RIPS_CP.ARCHIVO   = 'AT' OR RIPS_CP.ARCHIVO   = 'AH')
	AND    RIPSD.PROCEDENCIA = 'CI'
	--FACTURACION MASIVA PENDIENTE POR VALIDAR
	--UNION ALL
	--SELECT @ENVIO, @IDTERCERO, 'I',FTRD.N_FACTURA, @CODPREST, 
 --         LEFT(AFI.TIPO_DOC,2),  
 --         REPLACE(AFI.DOCIDAFILIADO,'.',''), LEFT('',15),  
 --         CASE RIPS_CP.IDCONCEPTORIPS
 --                    WHEN '06' THEN '3'  
 --                    WHEN '07' THEN '4'  
 --                    WHEN '08' THEN '3'  
 --                    WHEN '09' THEN '1'  
 --                    WHEN '10' THEN '1'  
 --                    WHEN '11' THEN '1'  
 --                    WHEN '14' THEN '2' 
 --        END,  
 --        REPLACE(SER.IDALTERNA,'-',''),  LEFT(REPLACE(SER.DESCRIPCION_CUPS,',',';'),30),  
 --        1, FTRD.VR_TOTAL, CAST (FTRD.VR_TOTAL AS INT ), 
 --        FMAS.CNSFMAS, 1, ISNULL(FTR.CNSFCT,'EXTERNO'), 1, 'CE', '', SER.IDSERVICIO, 
 --        'CODEVAL', FTR.F_FACTURA
	--	FROM FTRD
	--	INNER JOIN FTR ON FTR.CNSFCT=FTRD.CNSFTR
	--	INNER JOIN RIPSD ON RIPSD.N_FACTURA = FTR.N_FACTURA
	--	INNER JOIN AFI ON AFI.IDAFILIADO=FTR.IDAFILIADO
	--	INNER JOIN FMAS ON FMAS.N_FACTURA=FTR.N_FACTURA
	--	LEFT  JOIN SER     ON SER.IDSERVICIO         = FMAS.IDSERPAQ 
	--	LEFT  JOIN RIPS_CP ON RIPS_CP.IDCONCEPTORIPS = SER.CODIGORIPS 
	--	WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
	--	AND    (RIPS_CP.ARCHIVO   = 'AT' OR RIPS_CP.ARCHIVO   = 'AH')
	--	AND    RIPSD.PROCEDENCIA = 'CI'

	--AND    CIT.CUMPLIDA =	 CASE @RIPS_CITSOLOCUMPLIDA WHEN 'SI' THEN 1 ELSE CUMPLIDA END AND CIT.IDPLAN =CASE WHEN COALESCE(@IDPLAN,'')='' THEN  CIT.IDPLAN ELSE @IDPLAN END   
   PRINT 'SE CREARON EN AT CE ' + CONVERT(VARCHAR,@@ROWCOUNT) + ' ITEMS'


  SELECT @COUNT_AT = COUNT(*) FROM RRIPS_AT WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
  PRINT 'UPDATE AD'
  UPDATE RRIPS_AD SET CANTIDAD      = B.CANTIDAD      + A.CANTIDAD, 
                      TOTALCONCEPTO = B.TOTALCONCEPTO + A.TOTALCONCEPTO
  FROM   (SELECT @ENVIO ENVIO, LEFT(@CODPREST,12) IDPRESTADOR, N_FACTURA NUMFACTURA, CODCONCEPTO, 
               SUM(CANTIDAD) CANTIDAD, SUM(VALTOTALCONCEP) TOTALCONCEPTO
         FROM VWK_RIPS_AD_CE 
         WHERE CONTRATANTE=@IDTERCERO AND N_FACTURA IN (SELECT N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) AND 
               IDPLAN = CASE WHEN @IDPLAN = '' THEN IDPLAN ELSE @IDPLAN END
         GROUP BY N_FACTURA , CODCONCEPTO) A LEFT JOIN
         RRIPS_AD B
         ON A.ENVIO=B.ENVIO AND A.IDPRESTADOR = B.IDPRESTADOR AND A.NUMFACTURA=B.NUMFACTURA AND A.CODCONCEPTO = B.CODCONCEPTO
  WHERE  NOT B.ENVIO IS NULL
  PRINT 'INSERT AD'     
  INSERT INTO RRIPS_AD(ENVIO, IDTERCERO, ESTADO, NUMFACTURA, IDPRESTADOR, CODCONCEPTO, CANTIDAD, VALORUNITARIO, TOTALCONCEPTO)
  SELECT @ENVIO ENVIO, @IDTERCERO IDTERCERO,'I' ESTADO, A.N_FACTURA, LEFT(@CODPREST,12), A.CODCONCEPTO, SUM(A.CANTIDAD), 0, SUM(A.VALTOTALCONCEP)
  FROM VWK_RIPS_AD_CE A LEFT JOIN
       RRIPS_AD B ON @ENVIO=B.ENVIO AND LEFT(@CODPREST,12) = B.IDPRESTADOR AND 
                    A.N_FACTURA=B.NUMFACTURA AND A.CODCONCEPTO = B.CODCONCEPTO
  WHERE A.CONTRATANTE=@IDTERCERO AND A.N_FACTURA IN (SELECT N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO) AND 
        A.IDPLAN = CASE WHEN @IDPLAN = '' THEN A.IDPLAN ELSE @IDPLAN END AND
        B.ENVIO IS NULL
  GROUP BY A.CODCONCEPTO, A.N_FACTURA
  ORDER BY A.CODCONCEPTO, A.N_FACTURA
  
  SELECT @COUNT_AD=COUNT(*) FROM RRIPS_AD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
  
  PRINT 'Insertando en AF CI'
 
   IF @RIPS_VALORENTERO = 'SI'
  INSERT INTO RRIPS_AF(ENVIO,IDTERCERO,ESTADO,IDPRESTADOR,RAZONSOCIAL,TIPO_ID,NUMIDENTIFICACION,NUMFACTURA,
                       FECHAEXPEDICION,FECHAINICIO,FECHAFINAL,CODENTIDADM,NOMBREENTIDADM,
                       NUMEROCONTRATO,PLANBENEFICIOS,NUMPOLIZA,VALORTOTALCOPAGO,VALORCOMISION,
                       VALORTOTALDESC,VALORNETO)
   SELECT ENVIO, @IDTERCERO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA,
      MIN(FECHAINICIO), MAX(FECHAFINAL),
      CODENTIDADM, NOMBREENTIDADM, CONTRATO, PLANBENEFICIOS, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL
   FROM (
     SELECT DISTINCT @ENVIO AS ENVIO,'I' AS ESTADO,LEFT(@CODPREST,12) AS IDPRESTADOR, @RAZONSOCIAL AS RAZONSOCIAL, @TIPOID AS TIPO_ID, 
          @NUMID AS NUMIDENTIFICACION, RIPSD.N_FACTURA, FTR.F_FACTURA,
		    CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN DBO.FNK_FECHA_SIN_HORA( CIT.FECHA )ELSE  @FECINI  END AS FECHAINICIO,
		    CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN DBO.FNK_FECHA_SIN_HORA( COALESCE (CIT.FECHAATENCION, CIT.FECHA)) ELSE  @FECFIN END AS FECHAFINAL,
		      CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END  AS CODENTIDADM, LEFT(TER.RAZONSOCIAL,30) AS NOMBREENTIDADM, 
            LEFT(COALESCE (CNT.IDALTERNA, PPT.IDCONTRATO,  CASE COALESCE(@RIPS_IDCONTRATO,'') when 'NO' THEN '' ELSE CIT.IDPLAN END ),15) AS CONTRATO,
          '' AS PLANBENEFICIOS, '' AS NUMPOLIZA, CAST (COALESCE(FTR.VALORCOPAGO,0) AS INT ) AS VALORCOPAGO,  '0' AS VALORCOMISION, '0' AS VALORTOTALDESC, 
		    CONVERT (VARCHAR (15),CONVERT(DECIMAL(14,2), FTR.VR_TOTAL)) AS VR_TOTAL
     FROM   RIPSD INNER JOIN FTRD   ON RIPSD.N_FACTURA     = FTRD.N_FACTURA
                  INNER JOIN CIT    ON FTRD.NOPRESTACION   = CIT.CONSECUTIVO
                  INNER JOIN FTR    ON FTRD.CNSFTR         = FTR.CNSFCT
                   LEFT JOIN TER    ON FTR.IDTERCERO       = TER.IDTERCERO 
				   LEFT JOIN PPT ON PPT.IDTERCERO=FTR.IDTERCERO AND PPT.IDPLAN=FTR.IDPLAN			   
				   LEFT JOIN CNT   ON PPT.IDCONTRATO = CNT.IDCONTRATO
     WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
     AND    RIPSD.PROCEDENCIA = CASE WHEN RIPSD.NOADMISION='CEUNIFICADO' THEN RIPSD.PROCEDENCIA ELSE 'CI' END
     AND    COALESCE(FTRD.ITFC,0) <> 2
  )X
  GROUP BY ENVIO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA, CODENTIDADM, NOMBREENTIDADM, CONTRATO, PLANBENEFICIOS, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL

  ELSE 
   INSERT INTO RRIPS_AF(ENVIO,IDTERCERO,ESTADO,IDPRESTADOR,RAZONSOCIAL,TIPO_ID,NUMIDENTIFICACION,NUMFACTURA,
                       FECHAEXPEDICION,FECHAINICIO,FECHAFINAL,CODENTIDADM,NOMBREENTIDADM,
                       NUMEROCONTRATO,PLANBENEFICIOS,NUMPOLIZA,VALORTOTALCOPAGO,VALORCOMISION,
                       VALORTOTALDESC,VALORNETO)
   SELECT ENVIO, @IDTERCERO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA,
      MIN(FECHAINICIO), MAX(FECHAFINAL),
      CODENTIDADM, NOMBREENTIDADM, CONTRATO, PLANBENEFICIOS, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL
   FROM (
     SELECT DISTINCT @ENVIO AS ENVIO,'I' AS ESTADO,LEFT(@CODPREST,12) AS IDPRESTADOR, @RAZONSOCIAL AS RAZONSOCIAL, @TIPOID AS TIPO_ID, 
          @NUMID AS NUMIDENTIFICACION, RIPSD.N_FACTURA, FTR.F_FACTURA,
		    CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN DBO.FNK_FECHA_SIN_HORA( CIT.FECHA )ELSE  @FECINI  END AS FECHAINICIO,
		    CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN DBO.FNK_FECHA_SIN_HORA( COALESCE (CIT.FECHAATENCION, CIT.FECHA)) ELSE  @FECFIN END AS FECHAFINAL,
		      CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END  AS CODENTIDADM, LEFT(TER.RAZONSOCIAL,30) AS NOMBREENTIDADM, 
            LEFT(COALESCE (CNT.IDALTERNA, PPT.IDCONTRATO, CASE COALESCE(@RIPS_IDCONTRATO,'') when 'NO' THEN '' ELSE CIT.IDPLAN END ),15) AS CONTRATO,
          '' AS PLANBENEFICIOS, '' AS NUMPOLIZA, COALESCE(FTR.VALORCOPAGO,0) VALORCOPAGO,  '0' AS VALORCOMISION, '0' AS VALORTOTALDESC, 
		    FTR.VR_TOTAL
     FROM   RIPSD INNER JOIN FTRD   ON RIPSD.N_FACTURA     = FTRD.N_FACTURA
                  INNER JOIN CIT    ON FTRD.NOPRESTACION   = CIT.CONSECUTIVO
                  INNER JOIN FTR    ON FTRD.CNSFTR         = FTR.CNSFCT
                   LEFT JOIN TER    ON FTR.IDTERCERO       = TER.IDTERCERO 
				   LEFT JOIN PPT ON PPT.IDTERCERO=FTR.IDTERCERO AND PPT.IDPLAN=FTR.IDPLAN			   
				   LEFT JOIN CNT   ON PPT.IDCONTRATO = CNT.IDCONTRATO
     WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
     AND    RIPSD.PROCEDENCIA = CASE WHEN RIPSD.NOADMISION='CEUNIFICADO' THEN RIPSD.PROCEDENCIA ELSE 'CI' END
     AND    COALESCE(FTRD.ITFC,0) <> 2
  )X
  GROUP BY ENVIO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA, CODENTIDADM, NOMBREENTIDADM, CONTRATO, PLANBENEFICIOS, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL

  
  PRINT 'Insertando en AF CE'   
  /*
  INSERT INTO RRIPS_AF(ENVIO,IDPRESTADOR,NUMFACTURA)
  SELECT DISTINCT @ENVIO AS ENVIO,LEFT(@CODPREST,10),
         CASE ISNULL(AUTD.N_FACTURA,'')  WHEN '' THEN FTRD.N_FACTURA
                                         ELSE AUTD.N_FACTURA
         END
  FROM   AUTD INNER JOIN AUT   ON AUTD.IDAUT     = AUT.IDAUT
              INNER JOIN FTRD  ON AUT.NOAUT      = FTRD.NOPRESTACION AND AUTD.NO_ITEM = FTRD.NOITEM
              INNER JOIN RIPSD ON FTRD.N_FACTURA = RIPSD.N_FACTURA
              INNER JOIN FTR   ON FTRD.CNSFTR    = FTR.CNSFCT
               LEFT JOIN TER   ON FTR.IDTERCERO  = TER.IDTERCERO 
  WHERE  RIPSD.ENVIO       = @ENVIO
  AND    RIPSD.PROCEDENCIA = 'CE'
  AND    FTRD.ITFC         <> 2  
  */   
  IF @RIPS_VALORENTERO = 'SI'
  INSERT INTO RRIPS_AF(ENVIO,IDTERCERO,ESTADO,IDPRESTADOR,RAZONSOCIAL,TIPO_ID,NUMIDENTIFICACION,NUMFACTURA,
                       FECHAEXPEDICION,FECHAINICIO,FECHAFINAL,CODENTIDADM,NOMBREENTIDADM,
                       NUMEROCONTRATO,NUMPOLIZA,VALORTOTALCOPAGO,VALORCOMISION,
                       VALORTOTALDESC,VALORNETO)
  SELECT ENVIO, @IDTERCERO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA,
      MIN(FECHAINICIO), MAX(FECHAFINAL),
      CODENTIDADM, NOMBREENTIDADM, CONTRATO, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL
  FROM (
     SELECT DISTINCT @ENVIO AS ENVIO,'I' AS ESTADO,LEFT(@CODPREST,12) AS IDPRESTADOR, @RAZONSOCIAL AS RAZONSOCIAL, @TIPOID AS TIPO_ID, 
          @NUMID AS NUMIDENTIFICACION, FTRD.N_FACTURA, FTR.F_FACTURA, 
		 CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN CASE WHEN DBO.FNK_FECHA_SIN_HORA( AUT.FECHA)>FTR.F_FACTURA THEN FTR.F_FACTURA ELSE DBO.FNK_FECHA_SIN_HORA( AUT.FECHA) END ELSE @FECINI END AS FECHAINICIO,
		 CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN CASE WHEN DBO.FNK_FECHA_SIN_HORA( AUT.FECHA)>FTR.F_FACTURA THEN FTR.F_FACTURA ELSE DBO.FNK_FECHA_SIN_HORA( AUT.FECHA) END ELSE @FECFIN END AS FECHAFINAL, 
         CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END  CODENTIDADM, LEFT(TER.RAZONSOCIAL,30) NOMBREENTIDADM, 
         LEFT(COALESCE (CNT.IDALTERNA, PPT.NROCONTRATO, CASE COALESCE(@RIPS_IDCONTRATO,'') when 'NO' THEN '' ELSE AUT.IDPLAN END),20) AS CONTRATO,
       '' AS NUMPOLIZA, CAST (  CAST(COALESCE(FTR.VALORCOPAGO,0)AS INT )AS VARCHAR (15)) AS VALORCOPAGO, '0' AS VALORCOMISION,'0' AS VALORTOTALDESC, 
       CAST(CAST(FTR.VR_TOTAL AS DECIMAL(14,0))AS VARCHAR(15)) AS VR_TOTAL
  FROM   AUTD INNER JOIN AUT   ON AUTD.IDAUT     = AUT.IDAUT
              INNER JOIN FTRD  ON AUT.NOAUT      = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
              INNER JOIN RIPSD ON FTRD.N_FACTURA = RIPSD.N_FACTURA
              INNER JOIN FTR   ON FTRD.CNSFTR    = FTR.CNSFCT
               LEFT JOIN TER   ON FTR.IDTERCERO  = TER.IDTERCERO 
			   LEFT JOIN PPT ON PPT.IDTERCERO=FTR.IDTERCERO AND PPT.IDPLAN=FTR.IDPLAN			   
			   LEFT JOIN CNT   ON PPT.IDCONTRATO = CNT.IDCONTRATO
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    RIPSD.PROCEDENCIA = 'CE'
  AND    COALESCE(FTRD.ITFC,0) <> 2
  AND	 NOT EXISTS (SELECT 1 FROM RRIPS_AF WHERE RRIPS_AF.ENVIO=RIPSD.ENVIO AND RRIPS_AF.IDTERCERO=RIPSD.IDTERCERO AND RRIPS_AF.NUMFACTURA=FTRD.N_FACTURA) 
  )X
  GROUP BY ENVIO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA, CODENTIDADM, NOMBREENTIDADM, CONTRATO, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL

  ELSE 
   INSERT INTO RRIPS_AF(ENVIO,IDTERCERO,ESTADO,IDPRESTADOR,RAZONSOCIAL,TIPO_ID,NUMIDENTIFICACION,NUMFACTURA,
                       FECHAEXPEDICION,FECHAINICIO,FECHAFINAL,CODENTIDADM,NOMBREENTIDADM,
                       NUMEROCONTRATO,NUMPOLIZA,VALORTOTALCOPAGO,VALORCOMISION,
                       VALORTOTALDESC,VALORNETO)
  SELECT ENVIO, @IDTERCERO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA,
      MIN(FECHAINICIO), MAX(FECHAFINAL),
      CODENTIDADM, NOMBREENTIDADM, CONTRATO, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL
  FROM (
     SELECT DISTINCT @ENVIO AS ENVIO,'I' AS ESTADO,LEFT(@CODPREST,12) AS IDPRESTADOR, @RAZONSOCIAL AS RAZONSOCIAL, @TIPOID AS TIPO_ID, 
          @NUMID AS NUMIDENTIFICACION, FTRD.N_FACTURA, FTR.F_FACTURA, 
		 CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN CASE WHEN DBO.FNK_FECHA_SIN_HORA( AUT.FECHA)>FTR.F_FACTURA THEN FTR.F_FACTURA ELSE DBO.FNK_FECHA_SIN_HORA( AUT.FECHA) END ELSE @FECINI END AS FECHAINICIO,
		 CASE WHEN @RIPS_FEHAINIFINAL = 'SI' THEN CASE WHEN DBO.FNK_FECHA_SIN_HORA( AUT.FECHA)>FTR.F_FACTURA THEN FTR.F_FACTURA ELSE DBO.FNK_FECHA_SIN_HORA( AUT.FECHA) END ELSE @FECFIN END AS FECHAFINAL, 
         CASE WHEN COALESCE(PPT.IDALTERNA,'')='' THEN LEFT(TER.IDALTERNA2,6)ELSE left(PPT.IDALTERNA,6) END  CODENTIDADM, LEFT(TER.RAZONSOCIAL,30) NOMBREENTIDADM, LEFT(COALESCE (CNT.IDALTERNA, PPT.NROCONTRATO, AUT.IDPLAN),20) AS CONTRATO,
       '' AS NUMPOLIZA, COALESCE(FTR.VALORCOPAGO,0) VALORCOPAGO, '0' AS VALORCOMISION,'0' AS VALORTOTALDESC, 
       CAST(CAST(FTR.VR_TOTAL AS DECIMAL(14,0))AS VARCHAR(15)) AS VR_TOTAL
  FROM   AUTD INNER JOIN AUT   ON AUTD.IDAUT     = AUT.IDAUT
              INNER JOIN FTRD  ON AUT.NOAUT      = FTRD.NOADMISION AND AUTD.NO_ITEM = FTRD.NOITEM
              INNER JOIN RIPSD ON FTRD.N_FACTURA = RIPSD.N_FACTURA
              INNER JOIN FTR   ON FTRD.CNSFTR    = FTR.CNSFCT
               LEFT JOIN TER   ON FTR.IDTERCERO  = TER.IDTERCERO 
			   LEFT JOIN PPT   ON PPT.IDTERCERO=FTR.IDTERCERO AND PPT.IDPLAN=FTR.IDPLAN
			   LEFT JOIN CNT   ON PPT.IDCONTRATO = CNT.IDCONTRATO
  WHERE  RIPSD.ENVIO       = @ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
  AND    RIPSD.PROCEDENCIA = 'CE'
  AND    COALESCE(FTRD.ITFC,0) <> 2
  AND	 NOT EXISTS (SELECT 1 FROM RRIPS_AF WHERE RRIPS_AF.ENVIO=RIPSD.ENVIO AND RRIPS_AF.IDTERCERO=RIPSD.IDTERCERO AND RRIPS_AF.NUMFACTURA=FTRD.N_FACTURA)
  )X
  GROUP BY ENVIO, ESTADO, IDPRESTADOR, RAZONSOCIAL, TIPO_ID, NUMIDENTIFICACION, N_FACTURA, F_FACTURA, CODENTIDADM, NOMBREENTIDADM, CONTRATO, NUMPOLIZA, VALORCOPAGO, VALORCOMISION, VALORTOTALDESC, VR_TOTAL

  
  UPDATE RRIPS_AF SET PLANBENEFICIOS = FTR.IDPLAN
  FROM   RRIPS_AF INNER JOIN FTR ON RRIPS_AF.NUMFACTURA = FTR.N_FACTURA
  WHERE  RRIPS_AF.ENVIO = @ENVIO AND RRIPS_AF.IDTERCERO=@IDTERCERO
  
  SELECT @COUNT_AF=COUNT(1) FROM RRIPS_AF WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
  
  DELETE RRIPS_AC WHERE ENVIO = @ENVIO AND NUMFACTURA NOT IN (SELECT N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) AND IDTERCERO=@IDTERCERO
  DELETE RRIPS_AP WHERE ENVIO = @ENVIO AND NUMFACTURA NOT IN (SELECT N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) AND IDTERCERO=@IDTERCERO
  DELETE RRIPS_AM WHERE ENVIO = @ENVIO AND NUMFACTURA NOT IN (SELECT N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) AND IDTERCERO=@IDTERCERO
  DELETE RRIPS_AT WHERE ENVIO = @ENVIO AND NUMFACTURA NOT IN (SELECT N_FACTURA FROM RIPSD WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO) AND IDTERCERO=@IDTERCERO
  DELETE RRIPS_CT WHERE ENVIO = @ENVIO

  INSERT INTO RRIPS_CT(ENVIO,IDTERCERO,IDPRESTADOR,FECHAREMISION,CODIGOARCHIVO,TOTALREGISTROS)
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AC'+@ENVIO,@COUNT_AC
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'US'+@ENVIO,@COUNT_US
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AU'+@ENVIO,@COUNT_AU
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AF'+@ENVIO,@COUNT_AF
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AD'+@ENVIO,@COUNT_AD
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AH'+@ENVIO,@COUNT_AH
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AP'+@ENVIO,@COUNT_AP
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AM'+@ENVIO,@COUNT_AM
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AN'+@ENVIO,@COUNT_AN
  UNION ALL
  SELECT @ENVIO,@IDTERCERO,LEFT(@CODPREST,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AT'+@ENVIO,@COUNT_AT
  
  DELETE FROM RRIPS_CT WHERE (TOTALREGISTROS=0 OR TOTALREGISTROS IS NULL ) AND ENVIO = @ENVIO AND IDTERCERO=@IDTERCERO
  
  UPDATE RIPS SET ENVIADO='G' WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO

  PRINT 'QUITANDO CARACTERES ESPECIALES'

  UPDATE RRIPS_US SET PNOMBRE=UPPER(DBO.FNK_LIMPIATEXTO(PNOMBRE,'A-Z')), SNOMBRE=UPPER(DBO.FNK_LIMPIATEXTO(SNOMBRE,'A-Z')),
  PAPELLIDO=UPPER(DBO.FNK_LIMPIATEXTO(PAPELLIDO,'A-Z')), SAPELLIDO=UPPER(DBO.FNK_LIMPIATEXTO(SAPELLIDO,'A-Z'))
  WHERE ENVIO=@ENVIO

END





