CREATE OR ALTER PROCEDURE DBO.SPQ_FTR_MASIVA_COL
@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS
DECLARE @PARAMETROS     NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO     VARCHAR(12)
       ,@GRUPO          VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A           INT
       ,@IDENTITY       INT            ,@PROCESO          VARCHAR(20)   
       ,@DATOS          NVARCHAR(MAX)  ,@ACCION           VARCHAR(1)      ,@REGISTRO      NVARCHAR(MAX)
       ,@NOAUT          VARCHAR(16)    ,@CNSFACT          VARCHAR(20)     ,@FECHAINI      DATE          ,@FECHAFIN        DATE
       ,@IDTERCERO      VARCHAR(20)    ,@IDPLAN           VARCHAR(6)      ,@IDSEDEF       VARCHAR(7)    ,@PROCEDENCIA     VARCHAR(20)
       ,@IDSEDE         VARCHAR(7)     ,@F_FACTURA        DATETIME        ,@COMPANIA      VARCHAR(2)    ,@NIT             VARCHAR(20)
       ,@FFACTURA       DATE           ,@IDAUT            VARCHAR(13)     ,@NUMCONCNSFACT INT = 0       ,@NUMCONCNSFACT2  INT = 0
       ,@PROCESOFACTMAS INT            ,@FECHAINIFIL      DATE            ,@FECHAFINFIL   DATE          ,@OBSERVACION     VARCHAR(MAX)
       ------- nuevas de jose manuel
       ,@CONSECUTIVO VARCHAR(20)           ,@DPR VARCHAR(20)                 ,@TIPOFAC VARCHAR(2)
       ,@N_fACTURA VARCHAR(20)             ,@FECHAFACT DATETIME             
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
      
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A FTR_MASIVA_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'MARCAAUT_FTR'
   BEGIN
      PRINT 'MARCAAUT_FTR'
      SELECT @DATOS=DATOS,@ACCION=ACCION, @REGISTRO=REGISTRO
		FROM   OPENJSON (@PARAMETROS)
		WITH   (
			DATOS      NVARCHAR(MAX)     AS JSON,
			ACCION     VARCHAR(1)       '$.ACCION',
         REGISTRO   NVARCHAR(MAX)     AS JSON
			)
      IF @ACCION = '3'
      BEGIN
         PRINT 'ESTOY MARCANDO INDIVIDUAL AUT'
        
         SELECT @NOAUT = JSON_VALUE(@REGISTRO, '$.NOAUT')
         SELECT @CNSFACT=''
			SELECT @SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO

         IF (SELECT COUNT(1) FROM AUT WHERE NOAUT = @NOAUT AND COALESCE(VALORTOTAL,0)<=0 ) > 0
         BEGIN
            INSERT INTO @TBLERRORES (ERROR ) SELECT 'Sin Valor'
            SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
         END

			--EXEC SPK_GENCONSECUTIVO '01',@SEDE, '@RPDX', @CNSFACT OUTPUT  
			--SELECT @CNSFACT = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFACT))+LTRIM(RTRIM(@CNSFACT)),SPACE(1),0)     
         BEGIN TRY 
            IF (SELECT COALESCE(MARCAFAC,0) FROM AUT WHERE NOAUT = @NOAUT)= 0
            BEGIN
               UPDATE AUT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 
               UPDATE AUT SET CNSFACT = NULL  WHERE NOAUT = @NOAUT AND COALESCE(MARCAFAC,0) = 0 
            END
            ELSE 
            BEGIN
               UPDATE AUT SET MARCAFAC = 0 ,CNSFACT = NULL WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 --AND CNSFACT = @USUARIO
            END
         END TRY 
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH

			IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
         SELECT 'OK' OK
      END
      ELSE IF @ACCION = '4'
      BEGIN
         PRINT 'ESTOY MARCANDO INDIVIDUAL UNIFICADA'
         DECLARE @PROCEDENCIAFACTURACION VARCHAR(10)
         SELECT @PROCEDENCIAFACTURACION = JSON_VALUE(@REGISTRO,'$.PROCEDENCIAFACTURACION')
         PRINT '@PROCEDENCIAFACTURACION='+@PROCEDENCIAFACTURACION
         IF @PROCEDENCIAFACTURACION = 'CIT'
         BEGIN
            PRINT 'INICIO MARCACION UNIFICADA UNA CITA'
            SELECT @IDAUT = JSON_VALUE(@REGISTRO, '$.IDAUT')
            SELECT @CNSFACT=''
			   SELECT @SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO

            IF (SELECT COUNT(1) FROM CIT WHERE CONSECUTIVO = @IDAUT AND COALESCE(VALORTOTAL,0)<=0 ) > 0
            BEGIN
               INSERT INTO @TBLERRORES (ERROR ) SELECT 'Sin Valor'
               SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
            END
            BEGIN TRY 
               IF (SELECT COALESCE(MARCAFAC,0) FROM CIT WHERE CONSECUTIVO = @IDAUT)= 0
               BEGIN
                  UPDATE CIT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE CONSECUTIVO = @IDAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 
                  UPDATE CIT SET CNSFACT = NULL  WHERE CONSECUTIVO = @IDAUT AND COALESCE(MARCAFAC,0) = 0 
               END
               ELSE 
               BEGIN
                  UPDATE CIT SET MARCAFAC = 0 ,CNSFACT = NULL WHERE CONSECUTIVO = @IDAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 --AND CNSFACT = @USUARIO
               END
            END TRY 
			   BEGIN CATCH
				   INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			   END CATCH

			   IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			   BEGIN
				   SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
			   END
            SELECT 'OK' OK
         END
         ELSE IF @PROCEDENCIAFACTURACION = 'AUT'
         BEGIN
            PRINT 'INICIO MARCACION UNIFICADA UN AUT'
            SELECT @NOAUT = JSON_VALUE(@REGISTRO, '$.NOAUT')
            SELECT @CNSFACT=''
			   SELECT @SEDE=IDSEDE FROM USUSU WHERE USUARIO=@USUARIO

            IF (SELECT COUNT(1) FROM AUT WHERE NOAUT = @NOAUT AND COALESCE(VALORTOTAL,0)<=0 ) > 0
            BEGIN
               INSERT INTO @TBLERRORES (ERROR ) SELECT 'Sin Valor'
               SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
            END
            BEGIN TRY 
               IF (SELECT COALESCE(MARCAFAC,0) FROM AUT WHERE NOAUT = @NOAUT)= 0
               BEGIN
                  UPDATE AUT SET MARCAFAC = 1 ,CNSFACT = @USUARIO WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 
                  UPDATE AUT SET CNSFACT = NULL  WHERE NOAUT = @NOAUT AND COALESCE(MARCAFAC,0) = 0 
               END
               ELSE 
               BEGIN
                  UPDATE AUT SET MARCAFAC = 0 ,CNSFACT = NULL WHERE NOAUT = @NOAUT AND COALESCE(FACTURABLE,0)=1 AND COALESCE(FACTURADA,0) = 0 --AND CNSFACT = @USUARIO
               END
            END TRY 
			   BEGIN CATCH
				   INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			   END CATCH

			   IF(SELECT COUNT(*) FROM @TBLERRORES)>0
			   BEGIN
				   SELECT 'KO' OK
				   SELECT ERROR FROM @TBLERRORES
				   RETURN
			   END
            SELECT 'OK' OK

         END
      END
      ELSE 
      BEGIN
         SELECT @FECHAINI=F_INIMAS,@FECHAFIN=DATEADD(DAY,1,F_FINMAS),@IDTERCERO=IDTERMAS,
		          @IDPLAN=IDPLANMAS,@PROCEDENCIA=PROCE,@IDSEDEF=SEDEFMAS
		   FROM   OPENJSON (@DATOS)
		   WITH   (
			   F_INIMAS DATE          '$.F_INIMAS',
			   F_FINMAS DATE          '$.F_FINMAS',
			   IDTERMAS VARCHAR(20)   '$.IDTERMAS',
			   IDPLANMAS VARCHAR(20)  '$.IDPLANMAS',
			   PROCE VARCHAR(20)      '$.PROCE',
			   SEDEFMAS VARCHAR(20)   '$.SEDEFMAS'
            --,FACTURABLE BIT         '$.FACTURABLE'
            --,ESTADOFACTAUT SMALLINT '$.ESTADOFACT.value'
		   )
         PRINT '@FECHAINI='+CONVERT(VARCHAR,@FECHAINI)
         PRINT '@FECHAFIN='+CONVERT(VARCHAR,@FECHAFIN)
         PRINT '@IDTERCERO='+@IDTERCERO
         PRINT '@IDPLAN='+@IDPLAN
         PRINT '@IDSEDEF='+@IDSEDEF
         PRINT '@ACCION='+STR(@ACCION)
         IF @ACCION = 1
         BEGIN
            IF( 
                SELECT COUNT(*) --AUTD.IDAUT
                FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                AND    COALESCE(AUTD.FACTURADA,0) = 0      
                AND    COALESCE(AUTD.VALOR,0)>0 
                AND    COALESCE(AUT.FACTURABLE,0) = 1
                AND    COALESCE(AUT.MARCAFAC,0) = 0
                AND    AUT.ESTADO <> 'Anulada'
                --AND    COALESCE(CNSFACT,'') 
             ) <= 0
            BEGIN
               SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
			      RETURN
            END

            UPDATE AUT SET MARCAFAC = 1 , CNSFACT = @USUARIO
            FROM (
                     SELECT DISTINCT AUTD.IDAUT
                     FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                     WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                     AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                     AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                     AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                     AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                     AND    COALESCE(AUTD.FACTURADA,0) = 0      
                     AND    COALESCE(AUTD.VALOR,0)>0 
                     AND    COALESCE(AUT.FACTURABLE,0) = 1
                     AND    COALESCE(AUT.MARCAFAC,0) = 0
                     AND    AUT.ESTADO <> 'Anulada'
                 ) X
             WHERE  AUT.IDAUT = X.IDAUT

             SELECT 'OK' OK
         END
         ELSE IF @ACCION = 2
         BEGIN
            IF( 
                SELECT COUNT(*) --AUTD.IDAUT
                FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                AND    COALESCE(AUTD.FACTURADA,0) = 0      
                AND    COALESCE(AUTD.VALOR,0)>0 
                AND    COALESCE(AUT.FACTURABLE,0) = 1
                AND    COALESCE(AUT.MARCAFAC,0) = 1
                AND    AUT.ESTADO <> 'Anulada'
                AND    COALESCE(CNSFACT,'') = @USUARIO
             ) <= 0
            BEGIN
               SELECT 'KO' OK,'No Existen Registros para ' + CASE WHEN @ACCION = 1 THEN 'Marcar' ELSE 'Desmarcar' END ERROR
			      RETURN
            END
            UPDATE AUT SET MARCAFAC = 0  , CNSFACT = NULL
            FROM (
                     SELECT DISTINCT AUTD.IDAUT
                     FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
                     WHERE  AUTD.IDTERCEROCA = @IDTERCERO
                     AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                     AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINI 
                     AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFIN
                     AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
                     AND    COALESCE(AUTD.FACTURADA,0) = 0      
                     AND    COALESCE(AUTD.VALOR,0)>0 
                     AND    COALESCE(AUT.FACTURABLE,0) = 1
                     AND    COALESCE(AUT.MARCAFAC,0) = 1
                     AND    AUT.ESTADO <> 'Anulada'
                     AND    COALESCE(CNSFACT,'') = @USUARIO
                 ) X
            WHERE  AUT.IDAUT = X.IDAUT

            SELECT 'OK' OK
         END
      END
      RETURN
   END
   IF @METODO = 'FACTURAR_MASI'
   BEGIN
      DECLARE @PRESTACION VARCHAR(20)
		DECLARE @N_FACTURADEV  VARCHAR(20)
		SELECT @DATOS=DATOS,@ACCION=ACCION,@FFACTURA = FFACTURA ,@OBSERVACION = OBSERVACION
		FROM   OPENJSON (@PARAMETROS)
		WITH (
			DATOS       NVARCHAR(MAX) AS JSON,
			ACCION      SMALLINT     '$.ACCION',
         FFACTURA    DATE         '$.FFACTURA',
         OBSERVACION VARCHAR(MAX) '$.OBSERVACION'
		) 
		SELECT @FECHAINI=F_INIMAS ,@FECHAFIN   =F_FINMAS,@IDTERCERO=IDTERMAS,
		       @IDPLAN  =IDPLANMAS,@PROCEDENCIA=PROCE   ,@IDSEDEF  =SEDEFMAS
		FROM   OPENJSON (@DATOS)
		WITH   (
			F_INIMAS DATE          '$.F_INIMAS',
			F_FINMAS DATE          '$.F_FINMAS',
			IDTERMAS VARCHAR(20)   '$.IDTERMAS',
			IDPLANMAS VARCHAR(20)  '$.IDPLANMAS',
			PROCE VARCHAR(20)      '$.PROCE',
			SEDEFMAS VARCHAR(6)    '$.SEDEFMAS'
		)
      IF COALESCE(@FFACTURA,'') = ''
         SELECT @F_FACTURA=DBO.FNK_GETDATE()
      ELSE
         SELECT @F_FACTURA=@FFACTURA

		SELECT @COMPANIA='01',@NIT=NIT
		FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
		IF dbo.FNK_VALORVARIABLE('FACTSEDE')='SI'
		BEGIN
         IF @IDSEDEF = 'Todas'
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Escogio Todas las Sedes y esta IPS Tiene configurado Facturación por Sede'
			   SELECT 'KO' OK
			   SELECT ERROR FROM @TBLERRORES
			   RETURN
         END
         ELSE
			   SELECT @IDSEDE=@IDSEDEF
		END
		ELSE
			SELECT @IDSEDE=UBEQ.IDSEDE 
			FROM USUSU INNER JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME 
			WHERE USUARIO=@USUARIO

		IF COALESCE(@NIT,'')='' 
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Tercero Facturador No Identificado, Revise Configuración Terceros'
         
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		IF NOT EXISTS(SELECT 1 FROM PRI WHERE FECHA_INI<=@F_FACTURA AND FECHA_FIN+1>@F_FACTURA AND COALESCE(CERRADO,0)=0)
		BEGIN
			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'Periodo Contable No Existe o no Esta Abierto, Revise Configuración Peridos Contables'
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
      IF @PROCEDENCIA='AUT'
      BEGIN
         IF @ACCION = 1
         BEGIN
            BEGIN TRY 
					EXEC SPQ_FACTURACE_ESCMA @USUARIO,@NIT,@COMPANIA,@IDSEDE,@USUARIO,@IDTERCERO,@IDPLAN,'',@IDTERCERO,'VARIOS',1,@FECHAFAC=@F_FACTURA
				END TRY 
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
				IF(SELECT COUNT(1) FROM @TBLERRORES)>0
				BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
				SELECT 'OK' OK
         END
      END
      ELSE IF @PROCEDENCIA='UNI'
      BEGIN
         IF @ACCION = 1
         BEGIN
            BEGIN TRY 
					EXEC SPQ_FACTURACE_ESCMA @USUARIO,@NIT,@COMPANIA,@IDSEDE,@USUARIO,@IDTERCERO,@IDPLAN,@OBSERVACION,@IDTERCERO,'CEUNIFICADO',1,@FECHAFAC=@F_FACTURA
				END TRY 
				BEGIN CATCH
					INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
				END CATCH
				IF(SELECT COUNT(1) FROM @TBLERRORES)>0
				BEGIN
					SELECT 'KO' OK
					SELECT ERROR FROM @TBLERRORES
					RETURN
				END
				SELECT 'OK' OK
         END
      END
      RETURN
   END
   IF @METODO='CONTEOFTRMARCADAS'
   BEGIN
      SELECT @PROCESOFACTMAS = JSON_VALUE(@PARAMETROS,'$.PROCESO')
      ,@IDTERCERO  = JSON_VALUE(@PARAMETROS,'$.IDTERCERO')
      ,@IDPLAN     = JSON_VALUE(@PARAMETROS,'$.IDPLAN')   
      ,@IDSEDEF    = JSON_VALUE(@PARAMETROS,'$.IDSEDE')   
      ,@FECHAINIFIL= JSON_VALUE(@PARAMETROS,'$.FINI')     
      ,@FECHAFINFIL= JSON_VALUE(@PARAMETROS,'$.FFIN')     
      ,@PROCEDENCIA= JSON_VALUE(@PARAMETROS,'$.PROCEDENCIA')
      PRINT 'PROCESOFACTMAS='+CONVERT(VARCHAR,@PROCESOFACTMAS) 
      IF @PROCESOFACTMAS = 4 OR @PROCESOFACTMAS = 3
      BEGIN
         IF @PROCEDENCIA = 'CIT'
         BEGIN
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
            WHERE  USUARIONOFACTURABLE = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDCONTRATANTE,'') = @IDTERCERO
            AND    COALESCE(IDPLAN,'') = @IDPLAN
            AND    COALESCE(IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDCONTRATANTE,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM CIT 
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  USUARIONOFACTURABLE = @USUARIO 
               AND    MARCAFAC= 1 
               AND    COALESCE(FACTURADA,0)=0
               AND    COALESCE(FACTURABLE,0) = 1
               AND    (COALESCE(IDCONTRATANTE,'') <> @IDTERCERO OR COALESCE(IDPLAN,'') <> @IDPLAN OR COALESCE(IDSEDE,'') <> @IDSEDEF OR CONVERT(DATE, FECHA) < @FECHAINIFIL OR CONVERT(DATE, FECHA) > @FECHAFINFIL )
         END
         
         SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
         RETURN
      END
      ELSE IF @PROCESOFACTMAS = 1
      BEGIN
         IF @PROCEDENCIA = 'AUT'
         BEGIN
            --SELECT @FECHAINIFIL FECHAINI,@FECHAFINFIL FECHAFIN
            SELECT @NUMCONCNSFACT = COUNT(*) 
            FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
            WHERE  AUTD.IDTERCEROCA = @IDTERCERO
            AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
            AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINIFIL 
            AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFINFIL
            AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    COALESCE(AUTD.FACTURADA,0) = 0      
            AND    COALESCE(AUTD.VALOR,0)>0 
            AND    COALESCE(AUT.FACTURABLE,0) = 1
            AND    COALESCE(AUT.MARCAFAC,0) = 1
            AND    AUT.ESTADO <> 'Anulada'
            AND    COALESCE(CNSFACT,'') = @USUARIO           

            IF @IDSEDEF='TODAS'
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT  
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  COALESCE(CNSFACT,'') = @USUARIO       
               AND    COALESCE(AUT.MARCAFAC,0) = 1
               AND    COALESCE(AUTD.FACTURADA,0) = 0      
               AND    COALESCE(AUTD.VALOR,0)>0 
               AND    COALESCE(AUT.FACTURABLE,0) = 1
               AND    (   AUTD.IDTERCEROCA != @IDTERCERO OR AUTD.IDPLAN <> CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                       OR CONVERT(DATE,AUT.FECHA) < @FECHAINIFIL OR CONVERT(DATE,AUT.FECHA) >  @FECHAFINFIL )
            ELSE
               SELECT @NUMCONCNSFACT2 = COUNT(*) FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT  
               --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
               WHERE  COALESCE(CNSFACT,'') = @USUARIO       
               AND    COALESCE(AUT.MARCAFAC,0) = 1
               AND    COALESCE(AUTD.FACTURADA,0) = 0      
               AND    COALESCE(AUTD.VALOR,0)>0 
               AND    COALESCE(AUT.FACTURABLE,0) = 1
               AND    (   AUTD.IDTERCEROCA != @IDTERCERO OR AUTD.IDPLAN <> CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
                       OR CONVERT(DATE,AUT.FECHA) < @FECHAINIFIL OR CONVERT(DATE,AUT.FECHA) >  @FECHAFINFIL 
                       OR COALESCE(AUT.IDSEDE,'') <> @IDSEDEF)
            SELECT 'OK' OK, @NUMCONCNSFACT CANTIDAD, @NUMCONCNSFACT2 CANTIDADFUERA 
            RETURN
         END
         ELSE IF @PROCEDENCIA = 'UNI'
         BEGIN
            PRINT 'INGRESE A UNI'
            PRINT '@USUARIO='+@USUARIO
            PRINT '@IDTERCERO='+@IDTERCERO
            PRINT '@IDPLAN='+@IDPLAN
            PRINT '@IDSEDEF='+@IDSEDEF
            --SELECT @FECHAINIFIL FECHAINIFIL ,@FECHAFINFIL FECHAFINFIL
            SELECT @NUMCONCNSFACT = COUNT(*) FROM CIT 
            --SELECT COALESCE(FACTURADA,0),COALESCE(FACTURABLE,0),COALESCE(IDPLAN,''),COALESCE(IDSEDE,''),CONVERT(DATE, FECHA),* FROM CIT 
            WHERE  CNSFACT = @USUARIO 
            AND    MARCAFAC= 1 
            AND    COALESCE(FACTURADA,0)=0
            AND    COALESCE(IDCONTRATANTE,'') = @IDTERCERO
            AND    COALESCE(IDPLAN,'') = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN COALESCE(IDPLAN,'') ELSE  COALESCE(@IDPLAN,'') END
            AND    COALESCE(IDSEDE,'') = CASE WHEN @IDSEDEF='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    CONVERT(DATE, FECHA) >= @FECHAINIFIL
            AND    CONVERT(DATE, FECHA) <= @FECHAFINFIL
            AND    COALESCE(FACTURABLE,0) = 1

            SELECT @NUMCONCNSFACT2 = COUNT(*) 
            FROM   AUTD INNER JOIN AUT ON AUTD.IDAUT = AUT.IDAUT 
            WHERE  AUTD.IDTERCEROCA = @IDTERCERO
            AND    AUTD.IDPLAN      = CASE WHEN COALESCE(@IDPLAN,'') = '' THEN AUTD.IDPLAN ELSE @IDPLAN END
            AND    CONVERT(DATE,AUT.FECHA) >= @FECHAINIFIL 
            AND    CONVERT(DATE,AUT.FECHA) <  @FECHAFINFIL
            AND    AUT.IDSEDE=CASE WHEN UPPER(@IDSEDEF)='TODAS' THEN IDSEDE ELSE @IDSEDEF END
            AND    COALESCE(AUTD.FACTURADA,0) = 0      
            AND    COALESCE(AUTD.VALOR,0)>0 
            AND    COALESCE(AUT.FACTURABLE,0) = 1
            AND    COALESCE(AUT.MARCAFAC,0) = 1
            AND    AUT.ESTADO <> 'Anulada'
            AND    COALESCE(CNSFACT,'') = @USUARIO       
            SELECT 'OK' OK, @NUMCONCNSFACT CANTIDADCIT, @NUMCONCNSFACT2 CANTIDADAUT
            RETURN
         END
      END
      RETURN
   END
   IF @METODO='FACTURAR_CITAUT'   
   BEGIN         
      SELECT @CONSECUTIVO=CONSECUTIVO,@OBSERVACION=OBSERVACION        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO',
      OBSERVACION  VARCHAR(2048)   '$.OBSERVACION'
      )
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      PRINT 'Valido sede'
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Sede: '+@IDSEDE+' No habilitada para emitir Facturas, Comuniquese con el Administrador del Sistema'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN

      END
	  IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'))
	  BEGIN
		INSERT INTO @TBLERRORES(ERROR)
		SELECT 'La atencion a facturar es Particular, por lo que no se puede facturar.'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
	  END
      IF NOT EXISTS(SELECT * FROM CIT WHERE COALESCE(FACTURADA,0)=1 AND COALESCE(N_FACTURA,'')='' AND CONSECUTIVO=@CONSECUTIVO) 
      BEGIN
         BEGIN TRY   
            EXEC SPK_FACTURACE_CITAUT_COL @CONSECUTIVO,@DPR,@COMPANIA,@IDSEDE, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         SELECT @N_fACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
         IF COALESCE(@OBSERVACION,'')<>''
         BEGIN
            UPDATE FTR SET OBSERVACION=@OBSERVACION WHERE N_FACTURA=@N_fACTURA
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Cita ya Facturada o con Valores en Cero(0), Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @N_FACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
      SELECT 'OK' OK,@N_FACTURA N_FACTURA
      RETURN 
   END
END