IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'FNOT'  AND   C.NAME = 'FRADICA_RIPS')
BEGIN
   ALTER TABLE FNOT   ADD  FRADICA_RIPS DATETIME
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'FNOT'  AND   C.NAME = 'CUV')
BEGIN
   ALTER TABLE FNOT   ADD  CUV VARCHAR(256)
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'FGLO'  AND   C.NAME = 'FRADICA_RIPS')
BEGIN
   ALTER TABLE FGLO   ADD  FRADICA_RIPS DATETIME
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'FGLO'  AND   C.NAME = 'CUV')
BEGIN
   ALTER TABLE FGLO   ADD  CUV VARCHAR(256)
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'FCXCR'  AND   C.NAME = 'FRADICA_RIPS')
BEGIN
   ALTER TABLE FCXCR   ADD  FRADICA_RIPS DATETIME
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'FCXCR'  AND   C.NAME = 'CUV')
BEGIN
   ALTER TABLE FCXCR   ADD  CUV VARCHAR(256)
END
IF NOT EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNOTJSON' AND XTYPE='U')
BEGIN
   CREATE TABLE [dbo].[FNOTJSON](
	   [ID] [int] IDENTITY(1,1) NOT NULL,
	   [CNSFNOT] [varchar](40) NOT NULL,
	   [CLASE] [varchar](1) NOT NULL,
	   [JSON_ENVIO] [nvarchar](max) NULL,
	   [JSON_RESPUESTA] [nvarchar](max) NULL,
	   [CUV] [varchar](256) NULL,
	   [FRADICA_RIPS] [datetime] NULL,
   PRIMARY KEY CLUSTERED 
   (
	   [ID] ASC
   )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
   ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
