IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_FACTURACI_ESCIP_MASI' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURACI_ESCIP_MASI
END
GO
CREATE PROCEDURE DBO.SPK_FACTURACI_ESCIP_MASI
@CNSRPDX  VARCHAR(20),
@NIT      VARCHAR(20),
@COMPANIA VARCHAR(2),
@IDSEDE   VARCHAR(5),
@USUARIO  VARCHAR(12),
@IDTERCEROCA1 VARCHAR(20),
@IDPLAN VARCHAR(20),
@OBSERVACION VARCHAR(20),
@F_FACTURA    DATETIME,
@IDSERVICIOPAQ  VARCHAR(20),
@VLRPAQUETE     DECIMAL(14,2),
@CANTIDAD       SMALLINT =0,
@VLRPAQUETENVO  DECIMAL(14,2)=0
WITH ENCRYPTION
AS
DECLARE @IDAFILIADO VARCHAR(20)
DECLARE @NOMBREAFI VARCHAR(70)
DECLARE @CNSFMAS   VARCHAR(20)
DECLARE @NPAQUETE   VARCHAR(256)
DECLARE @IDTERINSTALADO VARCHAR(20)
BEGIN
   PRINT 'EMPIEO EL SPK DE FACTURA'
   PRINT 'VERIFICO VARIABLES'
   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'NADA')
   PRINT '@IDTERCEROCA1='+COALESCE(@IDTERCEROCA1,'NADA TER')
   SELECT @IDTERINSTALADO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

   DECLARE AUT_CURSOR CURSOR FOR
   SELECT DISTINCT(CIT.IDAFILIADO), AFI.NOMBREAFI
   FROM CIT
   LEFT JOIN TER ON CIT.IDTERCEROCA=TER.IDTERCERO
   INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO
   WHERE CIT.IDTERCEROCA = @IDTERCEROCA1 AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX
   AND   COALESCE(FACTURABLE,0)=1 
   AND   COALESCE(CIT.DESCUENTO,0)<CASE WHEN COALESCE(CIT.TIPODTO,'P')='P' THEN 100 ELSE CIT.VALORTOTAL END
   AND   (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
          (TER.IDTERCERO IS NULL AND @IDTERCEROCA1<>''))
   ORDER BY AFI.NOMBREAFI

   OPEN AUT_CURSOR  
   FETCH NEXT FROM AUT_CURSOR  
   INTO @IDAFILIADO, @NOMBREAFI
   WHILE @@FETCH_STATUS = 0  
   BEGIN     
      --EXEC SPK_FACTURACI_ESCMA  @CNSRPDX, @NIT, @COMPANIA, @IDSEDE, @USUARIO, @IDTERCEROCA1, @IDPLAN, @OBSERVACION, @IDTERCEROCA1, @F_FACTURA, NULL, NULL, 'CUE', @IDAFILIADO
      IF EXISTS(SELECT 1 FROM CIT WHERE CIT.CNSFACT = @CNSRPDX 
         AND EXISTS(SELECT * FROM FMASD INNER JOIN FMAS ON FMAS.PROCEDENCIA='CI' AND FMASD.CNSFMAS=FMAS.CNSFMAS
                     WHERE FMASD.NOADMISION=CIT.CONSECUTIVO AND  CIT.IDTERCEROCA = @IDTERCEROCA1 
                           AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) 
                           AND CIT.MARCAFAC = 1 
                           AND CIT.CNSFACT = @CNSRPDX
                           AND CIT.IDAFILIADO=@IDAFILIADO
                           AND COALESCE(FACTURABLE,0)=1 
                           AND COALESCE(CIT.DESCUENTO,0)<CASE WHEN CIT.TIPODTO='P' THEN 100 ELSE CIT.VALORTOTAL END )    
                           )
      BEGIN 
          print 'cnsfmas'
                 SELECT TOP 1 @CNSFMAS= FMASD.CNSFMAS  
                 FROM FMASD INNER JOIN FMAS ON FMAS.PROCEDENCIA='CI' AND FMASD.CNSFMAS=FMAS.CNSFMAS
                            INNER JOIN CIT ON FMASD.NOADMISION=CIT.CONSECUTIVO 
                 WHERE  CIT.CNSFACT = @CNSRPDX  AND CIT.IDTERCEROCA = @IDTERCEROCA1 
         AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) 
         AND CIT.MARCAFAC = 1 
         AND CIT.CNSFACT = @CNSRPDX
         AND CIT.IDAFILIADO=@IDAFILIADO
         AND COALESCE(FACTURABLE,0)=1 
         AND COALESCE(CIT.DESCUENTO,0)<CASE WHEN COALESCE(CIT.TIPODTO,'P')='P' THEN 100 ELSE CIT.VALORTOTAL END

		 PRINT 'Encontre fmas BORRO todo'

		 DELETE FMASD WHERE CNSFMAS=@CNSFMAS
		 DELETE FMAS WHERE CNSFMAS=@CNSFMAS
       END
      PRINT 'EMPIEZO A CREAR FMAS'
	  IF COALESCE(@CNSFMAS,'')=''
	  BEGIN
		SET @CNSFMAS=SPACE(20)
		EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE,'@FMAS',@CNSFMAS OUTPUT   
		SELECT @CNSFMAS = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSFMAS))+LTRIM(RTRIM(@CNSFMAS)),SPACE(1),0)
	 END
      PRINT '@CNSFMAS='+@CNSFMAS
      INSERT INTO FMAS(CNSFMAS, COMPANIA, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE, ESTADO, OBSERVACION, VR_TOTAL, FACTURADA, IDPLAN, PAQUETE, MSER, PROCEDENCIA, IDSERPAQ,						VALORPAQ,MCANT,CANT,MCVALOR,VALORNVO)
      SELECT @CNSFMAS, @COMPANIA, @IDTERCEROCA1, NULL, NULL, NULL, 'P','FACTURACION DE '+@NPAQUETE, 0, 0, @IDPLAN, 1, 0, 'CI', @IDSERVICIOPAQ, CASE WHEN					         @VLRPAQUETE<>@VLRPAQUETENVO AND COALESCE(@VLRPAQUETENVO,0)>0 THEN @VLRPAQUETENVO ELSE @VLRPAQUETE END,CASE WHEN @CANTIDAD IN(0,1) THEN 0 ELSE 1 END,@CANTIDAD,
             CASE WHEN @VLRPAQUETE<>@VLRPAQUETENVO THEN 1 ELSE 0 END,CASE WHEN @VLRPAQUETE<>COALESCE(@VLRPAQUETENVO,0) AND COALESCE(@VLRPAQUETENVO,0)>0 THEN @VLRPAQUETENVO 
			 ELSE @VLRPAQUETE END

      INSERT INTO FMASD(CNSFMAS, NOADMISION, VR_TOTAL, FACTURADA, VLR_IVA)
      SELECT @CNSFMAS,CONSECUTIVO,CIT.VALORTOTAL-CIT.VALORCOPAGO,0,0
      FROM CIT
      LEFT JOIN TER ON CIT.IDTERCEROCA=TER.IDTERCERO
      INNER JOIN AFI ON AFI.IDAFILIADO=CIT.IDAFILIADO
      WHERE CIT.IDTERCEROCA = @IDTERCEROCA1 
      AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) 
      AND CIT.MARCAFAC = 1 
      AND CIT.CNSFACT = @CNSRPDX
      AND CIT.IDAFILIADO=@IDAFILIADO
      AND COALESCE(FACTURABLE,0)=1 
      AND COALESCE(CIT.DESCUENTO,0)<CASE WHEN COALESCE(CIT.TIPODTO,'P')='P' THEN 100 ELSE CIT.VALORTOTAL END
      AND (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
          (TER.IDTERCERO IS NULL AND @IDTERCEROCA1<>''))
      ORDER BY CIT.CONSECUTIVO

      PRINT 'VOY A FACTURAR MASIVO'
     

      EXEC SPK_FAC_MASIVA_TER @CNSFMAS,@COMPANIA,@IDSEDE,@USUARIO,@IDTERINSTALADO

      FETCH NEXT FROM AUT_CURSOR  
      INTO @IDAFILIADO, @NOMBREAFI
   END
   CLOSE AUT_CURSOR
   DEALLOCATE AUT_CURSOR

   UPDATE CIT SET MARCAFAC=0,CNSFACT=NULL,USUARIONOFACTURABLE=NULL
   FROM CIT
   WHERE CIT.MARCAFAC = 1 AND CIT.CNSFACT = @CNSRPDX
END
