CREATE OR ALTER PROCEDURE DBO.SPQ_MDX_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX)) 
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@IDDX VARCHAR(10)               ,@DESCRIPCION VARCHAR(512)
      ,@ESTADO VARCHAR(20)                ,@RUTA VARCHAR(20)               ,@PYP VARCHAR(20)
      ,@RESOLUCION VARCHAR(20)            ,@CONFIDENCIAL VARCHAR(20)       ,@SEXO VARCHAR(20)
      ,@EDADINICIAL DECIMAL(14,2)         ,@EDADFINAL DECIMAL(14,2)        ,@ALTOCOSTO VARCHAR(20)
      ,@MREPORTE VARCHAR(20)              ,@DIASINCAP VARCHAR(20)          ,@CLASE VARCHAR(20)
      ,@GRUPOENF VARCHAR(20)              ,@SUBGRUPO VARCHAR(20)           ,@CLASI1 VARCHAR(20)
      ,@CLASI2 VARCHAR(20)                ,@COMENTARIOS VARCHAR(20)        ,@TEDAD VARCHAR(2)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
END
