IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IDTIPOMOV_INTER_SAL')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IDTIPOMOV_INTER_SAL','Tipo Movimiento Salida Interfax Inventario','Alfanumerica',''
END

IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IDTIPOMOV_INTER_ENT')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IDTIPOMOV_INTER_ENT','Tipo Movimiento Entrada Interfax Inventario','Alfanumerica',''
END
