IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'KMAIL'  AND   C.NAME = 'IDTERCERO')
BEGIN
   ALTER TABLE KMAIL  ADD IDTERCERO VARCHAR(20) 
END