IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_MAIL_PAGOS' AND type = 'P')
BEGIN
   DROP PROCEDURE SPK_MAIL_PAGOS
END
GO
CREATE PROCEDURE DBO.SPK_MAIL_PAGOS
   @CNSPAGO    VARCHAR(20),
   @NUMDOC     VARCHAR(20),
   @CNSMAILG   VARCHAR(20),
   @CNSMAIL    VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @ARCHIVO    VARCHAR(255)
DECLARE @TEMPLATEID VARCHAR(100)
DECLARE @NOMINA     VARCHAR(60)
DECLARE @1FINI      VARCHAR(10)
DECLARE @2FFIN      VARCHAR(10)
DECLARE @USUARIO    VARCHAR(12)
DECLARE @EMAIL      VARCHAR(100)=''
DECLARE @DOCUMENTO  VARCHAR(20)
DECLARE @ASUNTO     VARCHAR(200) 
DECLARE @MSG        VARCHAR(200) 

BEGIN
   SET @TEMPLATEID = 'PAGOSNOMINA'
   
   SELECT @NOMINA=DESCRIPCION, @1FINI=CONVERT(VARCHAR(10),CONVERT(DATE,FECHAINI)), @2FFIN=CONVERT(VARCHAR(10),CONVERT(DATE,FECHAFIN))
   FROM NPER INNER JOIN NOMI ON NPER.CODNOMINA=NOMI.CODNOMINA WHERE CNSPAGO=@CNSPAGO
   
   SELECT @ARCHIVO=DATO1+@CNSMAIL+' - '+@CNSPAGO+'.pdf' FROM TGEN WHERE TABLA='General' AND CAMPO='MAIL_NOM' AND CODIGO='PATH'
   SELECT @ARCHIVO=DATO1+@CNSMAIL+' - '+@CNSPAGO+'.pdf' FROM TGEN WHERE TABLA='General' AND CAMPO='MAIL_NOM' AND CODIGO='PATH'
   SELECT @ASUNTO=DATO1                                 FROM TGEN WHERE TABLA='General' AND CAMPO='MAIL_NOM' AND CODIGO='SUBJECT'
   SELECT @MSG=DATO1                                    FROM TGEN WHERE TABLA='General' AND CAMPO='MAIL_NOM' AND CODIGO='MESSAGE' 




   SELECT @USUARIO=USUARIO FROM NIEPE WHERE CNSPAGO=@CNSPAGO

   --SELECT EMAIL=DBO.FNK_PrimerEmailTercero(@NUMDOC)
   SELECT @EMAIL=EMAIL, @DOCUMENTO=COALESCE(DOCIDEMPLEADO,NUMDOC) FROM NEMP WHERE NUMDOC=@NUMDOC
   IF COALESCE(@EMAIL,'') LIKE '%@%.%'
      PRINT 'Correo correcto'
   ELSE
   BEGIN
      SELECT @EMAIL=EMAIL FROM TER WHERE NIT=@DOCUMENTO AND ESTADO='Activo' AND EXISTS (SELECT 1 FROM TEXCA WHERE TEXCA.IDTERCERO=TER.IDTERCERO AND IDCATEGORIA=(SELECT DATO FROM USVGS WHERE IDVARIABLE='TERCATEMPLEADO'))
      IF COALESCE(@EMAIL,'') LIKE '%@%.%'
          PRINT 'Correo correcto'
      ELSE
          RETURN
   END


   --Insertando template
   IF NOT EXISTS (SELECT * FROM KMAILT WHERE TEMPLATEID=@TEMPLATEID)
   BEGIN
      INSERT INTO KMAILT(TEMPLATEID,TEMPLATE)
	   SELECT @TEMPLATEID, '@MSG. @NOMINA de @1FINI al @2FFIN' 
   END

   IF EXISTS(SELECT * FROM KMAILG WHERE CNSMAILG=@CNSMAILG AND CNSMAIL=@CNSMAIL) OR @EMAIL=''
   BEGIN
      RETURN
   END

   --Insertando Grupo de correos
   IF NOT EXISTS (SELECT * FROM KMAILG WHERE CNSMAILG=@CNSMAILG AND CNSMAIL=@CNSMAIL)
   BEGIN
	   INSERT INTO KMAILG(CNSMAILG,CNSMAIL,USUARIO,CAMPO_MAIL, PROCESO,CONSECUTIVO)
	   SELECT @CNSMAILG,@CNSMAIL,@USUARIO,'MAIL_NOM','NOMINA',@CNSPAGO
   END

   --Inserto el correo
   IF NOT EXISTS (SELECT * FROM KMAIL WHERE CNSMAIL=@CNSMAIL)
   BEGIN
      INSERT INTO KMAIL(CNSMAIL,TEMPLATEID, CNSMAILG,ASUNTO,IDTERCERO)
	   SELECT @CNSMAIL,@TEMPLATEID,@CNSMAILG,@ASUNTO,@NUMDOC
   END

   --Inserto los correos
   IF NOT EXISTS (SELECT * FROM KMAILD WHERE CNSMAIL=@CNSMAIL)
   BEGIN
      INSERT INTO KMAILD(CNSMAIL,EMAIL,NOMBRES,CC)
	   SELECT @CNSMAIL,DBO.FNK_LIMPIATEXTO(@EMAIL,'A-Z0-9.@_-'),DBO.FNK_LIMPIATEXTO(RAZONSOCIAL,'A-Z0-9 .,-)/('),0 FROM TER WHERE IDTERCERO=@NUMDOC
   END

   --Inserto Parametros
   IF NOT EXISTS (SELECT * FROM KMAILV WHERE CNSMAIL=@CNSMAIL)
   BEGIN
      INSERT INTO KMAILV(CNSMAIL,NOMBREVARIABLE,VALOR)
	   SELECT @CNSMAIL,'@NOMINA',@NOMINA UNION ALL
	   SELECT @CNSMAIL,'@1FINI' ,@1FINI  UNION ALL
	   SELECT @CNSMAIL,'@2FFIN' ,@2FFIN  UNION ALL
	   SELECT @CNSMAIL,'@MSG'   ,@MSG 

   END

   --Inserto los adjuntos
   INSERT INTO KMAILA(CNSMAIL,ARCHIVOURL,MOVER)
   SELECT @CNSMAIL,@ARCHIVO,1
END

