CREATE OR ALTER PROCEDURE DBO.SPK_ASIGNACOPAGOS_AUTPE
@IDAUT VARCHAR(20),
@NOITEM SMALLINT
WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @CONSECUTIVOCIT VARCHAR(20)
DECLARE @PORCENTAJE  DECIMAL(14,2)
DECLARE @PREFIJO VARCHAR(10)
DECLARE @VLR_COPA_VAR DECIMAL(14,2)
DECLARE @VLR_COPA_FIJO DECIMAL(14,2)
DECLARE @VLR_COPA_VARAUT DECIMAL(14,2)
DECLARE @VLR_PRCOPA_FIJO DECIMAL(14,2)
DECLARE @VLR_PORCOPA_VARAUT DECIMAL(14,2)
DECLARE @EXISTEPPCNT BIT
DECLARE @PREFIJOMED VARCHAR(10)
DECLARE @PREFIJOLAB VARCHAR(10)
DECLARE @PREFIJOAPO VARCHAR(10)
DECLARE @PREFIJOCON VARCHAR(10)
BEGIN
   PRINT 'SPK_ASIGNACOPAGOS_AUTPE '+@IDAUT+'NOITEMN '+CAST(@NOITEM AS VARCHAR(20))
   SELECT @CONSECUTIVOCIT=CONSECUTIVOCIT,@PREFIJO=PREFIJO FROM AUT WHERE IDAUT=@IDAUT 
   SET  @PREFIJOMED=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS')
   SET  @PREFIJOLAB=DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')
   SET  @PREFIJOAPO=DBO.FNK_VALORVARIABLE('PREFIJOAPOYODX')
   SET  @PREFIJOCON=DBO.FNK_VALORVARIABLE('PREFIJOCONSULTA')

   SELECT  @PORCENTAJE=100-CASE @PREFIJO WHEN @PREFIJOMED THEN COPA_VAR_PORC WHEN @PREFIJOLAB THEN  COPA_VAR_EXA 
          WHEN @PREFIJOAPO THEN COPA_VAR_APOYO WHEN @PREFIJOCON THEN COPA_VAR_INTERC ELSE 0 END,
          @VLR_COPA_VARAUT=CASE @PREFIJO WHEN @PREFIJOMED THEN COPAGO_VA_FAR WHEN @PREFIJOLAB THEN COPAGO_VA_EXA 
          ELSE 0 END,
          @VLR_COPA_FIJO=CASE @PREFIJO WHEN @PREFIJOMED THEN COPAGO_FI_FAR WHEN @PREFIJOLAB THEN  COPAGO_FI_EXA 
          ELSE 0 END
   FROM CIT 
   WHERE CONSECUTIVO=@CONSECUTIVOCIT

   IF EXISTS(SELECT * FROM PPTCNT INNER JOIN AUT ON PPTCNT.IDTERCERO=AUT.IDTERCEROCA AND PPTCNT.IDPLAN=AUT.IDPLAN AND PPTCNT.PREFIJO=AUT.PREFIJO)
   BEGIN
      SELECT @VLR_COPA_FIJO=COALESCE(PPTCNT.COPAFIJO,0), @VLR_COPA_VARAUT=COALESCE(PPTCNT.COPAVAR,0),@VLR_PRCOPA_FIJO=COALESCE(PPTCNT.PRCOPAFIJO,0)
      ,@VLR_PORCOPA_VARAUT=COALESCE(PPTCNT.PRCOPAVAR,0) 
      FROM PPTCNT INNER JOIN AUT ON PPTCNT.IDTERCERO=AUT.IDTERCEROCA AND PPTCNT.IDPLAN=AUT.IDPLAN AND PPTCNT.PREFIJO=AUT.PREFIJO
      SELECT @EXISTEPPCNT=1
   END
   UPDATE AUT SET COPAGO_FIJO=@VLR_COPA_FIJO,COPAGO_VARIABLE=@VLR_COPA_VARAUT
   WHERE IDAUT=@IDAUT 

   SELECT @VLR_COPA_VARAUT=CASE WHEN COALESCE(@VLR_COPA_VARAUT,0)>0 AND COALESCE(@VLR_COPA_VARAUT,0)<100 THEN 100-@VLR_COPA_VARAUT ELSE 0 END
   SELECT @VLR_PORCOPA_VARAUT=CASE WHEN COALESCE(@VLR_PORCOPA_VARAUT,0)>0 AND COALESCE(@VLR_PORCOPA_VARAUT,0)<100 THEN 100-@VLR_PORCOPA_VARAUT ELSE 0 END

   PRINT '@PORCENTAJE '+CAST(@PORCENTAJE AS VARCHAR(20))
   PRINT '@PREFIJO '+@PREFIJO

   IF @PORCENTAJE>0  AND COALESCE(@EXISTEPPCNT,0)=0
   BEGIN
      SELECT @VLR_COPA_VAR=ROUND(VALOR*(@PORCENTAJE/100),2) FROM AUTD WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
      UPDATE  AUTD SET VALORCOPAGO=(@VLR_COPA_VAR*CANTIDAD) WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
      UPDATE  AUTD SET VALOREXCEDENTE=(VALOR*CANTIDAD)-VALORCOPAGO WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM  
   END
   ELSE
   BEGIN
      IF COALESCE(@EXISTEPPCNT,0)=1
      BEGIN 
         IF EXISTS(SELECT * FROM AUTD  WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM AND COALESCE(PROTOCOLO,0)=1)
         BEGIN
            SELECT @VLR_COPA_VAR=ROUND(VALOR*(@VLR_PORCOPA_VARAUT/100),2) FROM AUTD WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
            UPDATE  AUTD SET VALORCOPAGO=(@VLR_COPA_VAR*CANTIDAD) WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
            UPDATE  AUTD SET VALOREXCEDENTE=(VALOR*CANTIDAD)-VALORCOPAGO WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
            UPDATE AUTD SET COPAGO_FIJO=@VLR_PRCOPA_FIJO,COPAGO_VARIABLE=100-@VLR_PRCOPA_FIJO WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM         
         END
         ELSE
         BEGIN
            SELECT @VLR_COPA_VAR=ROUND(VALOR*(@VLR_COPA_VARAUT/100),2) FROM AUTD WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
            UPDATE  AUTD SET VALORCOPAGO=(@VLR_COPA_VAR*CANTIDAD) WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
            UPDATE  AUTD SET VALOREXCEDENTE=(VALOR*CANTIDAD)-VALORCOPAGO WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
            UPDATE AUTD SET @VLR_COPA_FIJO=@VLR_PRCOPA_FIJO,COPAGO_VARIABLE=100-@VLR_COPA_VARAUT WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM         

         END
      END
      ELSE
      BEGIN
         UPDATE  AUTD SET VALOREXCEDENTE=(VALOR*CANTIDAD) WHERE IDAUT=@IDAUT AND NO_ITEM=@NOITEM
      END
   END

END





