IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NEVEC'  AND   C.NAME = 'REQNOV')
BEGIN
   ALTER TABLE NEVEC  ADD REQNOV BIT 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NEVEC'  AND   C.NAME = 'ENLIQUI')
BEGIN
   ALTER TABLE NEVEC  ADD ENLIQUI BIT 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NEVEC'  AND   C.NAME = 'ACCION')
BEGIN
   ALTER TABLE NEVEC  ADD ACCION VARCHAR(10) 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NEVEC'  AND   C.NAME = 'BNOVE')
BEGIN
   ALTER TABLE NEVEC  ADD BNOVE BIT
END