IF NOT EXISTS(SELECT  * FROM USPRO WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS')
BEGIN
   INSERT INTO USPRO(IDPROCEDIMIENTO,DESCPROCEDIMIENTO,WEB)
   SELECT 'ADMINQ_FACTURAS','Catalogo Facturacion',1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='NOTIDIAN')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','NOTIDIAN','P','Notificación Dian',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_MASIVA')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_MASIVA','P','Facturacion Masiva',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_HOSPIURG')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_HOSPIURG','P','Facturacion Hospitaliza urgencias',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_TRASLADAR')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_TRASLADAR','P','Trasladar y Recibir Facturas',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_INFORMES')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_INFORMES','P','Informes de Facturacion',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_ANULAR')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_ANULAR','P','Anular Facturas',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_LIBERAR')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_LIBERAR','P','liberar Facturas',1,1
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_FACTURAR')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,AUTOMATICO)
   SELECT 'ADMINQ_FACTURAS','FACT_FACTURAR','P','Crear Facturas',1,1
END