CREATE OR ALTER  FUNCTION [dbo].[FNK_RETIRA_HTML]
	(@HTMLTEXT VARCHAR(MAX))
	RETURNS VARCHAR(MAX)
	AS
BEGIN
	DECLARE @START INT
	DECLARE @END INT
	DECLARE @LENGTH INT
	SET @START = CHARINDEX('<',@HTMLTEXT)
	SET @END = CHARINDEX('>',@HTMLTEXT,CHARINDEX('<',@HTMLTEXT))
	SET @LENGTH = (@END - @START) + 1
	WHILE @START > 0
	   AND @END > 0
	   AND @LENGTH > 0
	BEGIN
	   SET @HTMLTEXT = STUFF(@HTMLTEXT,@START,@LENGTH,'')
	   SET @START = CHARINDEX('<',@HTMLTEXT)
	   SET @END = CHARINDEX('>',@HTMLTEXT,CHARINDEX('<',@HTMLTEXT))
	   SET @LENGTH = (@END - @START) + 1
	END
	RETURN LTRIM(RTRIM(REPLACE(@HTMLTEXT,'&nbsp;','')))
END