IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_AFACTURAR' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_AFACTURAR
END

GO
CREATE PROC DBO.SPK_AFACTURAR
@NOADMISION VARCHAR(16),
@CNSRPDX    VARCHAR(20),
@USUARIO    VARCHAR(20)=NULL,
@MARCA_HPRED VARCHAR(2)=NULL -- 18-03-2025 EBRAVO
WITH ENCRYPTION
AS          
DECLARE @TIPOFACTURACION VARCHAR(1)
DECLARE @FACTPORAFU      SMALLINT
DECLARE @IDTERCEROCA     VARCHAR(20)
DECLARE @IDPLAN          VARCHAR(6)
DECLARE @DESCRIPCION     VARCHAR(80)
DECLARE @OK              INT
DECLARE @ITEM            INT
DECLARE @IDSEDE          VARCHAR(5)
DECLARE @ITEMRPDX        INT
DECLARE @PFACTURARIND    SMALLINT
DECLARE @TIPOTERCONTA    VARCHAR(10)
DECLARE @VALORTOTAL      DECIMAL(14,2)
DECLARE @VALORCOPAGO     DECIMAL(14,2)
DECLARE @VALOREXCEDENTE  DECIMAL(14,2)
DECLARE @PAQUETE  BIT
BEGIN
   --Valido copago fijo para Expertta
   --IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
   --BEGIN
   --    IF EXISTS (SELECT 1 FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
   --               WHERE HPRE.NOADMISION=@NOADMISION AND ISNULL(HPRED.FACTURADA,0)=0
   --                  AND ISNULL(HPRED.ENCARGOS,0)=0 AND ISNULL(HPRED.MARCA,0)=1 AND HPRE.PROCEDENCIA='HADMAUT')
   --    BEGIN
   --        IF NOT EXISTS (SELECT 1 FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
   --                       WHERE HPRE.NOADMISION=@NOADMISION AND ISNULL(HPRED.FACTURADA,0)=0
   --                         AND ISNULL(HPRED.ENCARGOS,0)=0 AND ISNULL(HPRED.MARCA,0)=1 AND HPRE.PROCEDENCIA<>'HADMAUT')
   --        BEGIN
   --           RETURN
   --        END

   --        DECLARE @N_FACTURAH VARCHAR(20), @COPAGOFIJO DECIMAL(14,2), @NPRE VARCHAR(20), @NITEM INT
            
   --        SELECT @N_FACTURAH=HPRED.N_FACTURAH, @COPAGOFIJO=(HPRED.VALORCOPAGO/1.18)
   --        FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
   --        WHERE HPRE.NOADMISION=@NOADMISION AND ISNULL(HPRED.FACTURADA,0)=0
   --           AND ISNULL(HPRED.ENCARGOS,0)=0 AND ISNULL(HPRED.MARCA,0)=1 AND HPRE.PROCEDENCIA='HADMAUT'
           
   --        UPDATE HPRED SET USUARIOMARCA=NULL, MARCA=0, NOCOBRABLE=1
   --        FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
   --        WHERE HPRE.NOADMISION=@NOADMISION AND ISNULL(HPRED.FACTURADA,0)=0
   --           AND ISNULL(HPRED.ENCARGOS,0)=0 AND ISNULL(HPRED.MARCA,0)=1 AND HPRE.PROCEDENCIA='HADMAUT'
           
   --        SELECT TOP 1 @NPRE=HPRED.NOPRESTACION, @NITEM=HPRED.NOITEM
   --        FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
   --        WHERE HPRE.NOADMISION=@NOADMISION AND ISNULL(HPRED.FACTURADA,0)=0
   --           AND ISNULL(HPRED.ENCARGOS,0)=0 AND ISNULL(HPRED.MARCA,0)=1 AND HPRE.PROCEDENCIA<>'HADMAUT'
   --           AND HPRED.VALOREXCEDENTE>ISNULL(@COPAGOFIJO,0) --AND HPRE.PREFIJO='009'
   --        ORDER BY HPRED.VALOREXCEDENTE DESC

   --        UPDATE HPRED SET N_FACTURAH=@N_FACTURAH, VALORCOPAGO=@COPAGOFIJO, VALOREXCEDENTE=(VALOREXCEDENTE-ISNULL(@COPAGOFIJO,0))
   --        WHERE NOPRESTACION=@NPRE AND NOITEM=@NITEM
   --    END
   --END

   PRINT '@CNSRPDX='+@CNSRPDX
   SELECT @PAQUETE=PAQUETE FROM HADM WHERE NOADMISION=@NOADMISION
   DECLARE HADMFTR_CURSOR CURSOR FOR
   SELECT DISTINCT PPT.TIPOFACTURACION, PPT.FACTPORAFU, HPRED.IDTERCEROCA, HPRED.IDPLAN, HADM.IDSEDE,COALESCE(PPT.PFACTURARIND,0),COALESCE(PPT.TIPOTERCONTABLE,'NO')
   FROM   PPT, HADM, HPRE, HPRED 
   WHERE  HPRED.NOPRESTACION = HPRE.NOPRESTACION
   AND    HPRE.NOADMISION    = HADM.NOADMISION
   AND    HADM.NOADMISION    = @NOADMISION
   AND    PPT.IDTERCERO      = HPRED.IDTERCEROCA  
   AND    PPT.IDPLAN         = HPRED.IDPLAN
   AND    COALESCE(HPRED.FACTURADA,0) = 0
   AND    COALESCE(HPRED.ENCARGOS, 0) = 0
   AND    ISNULL(HPRED.ANULADO,0) = 0
   AND    ISNULL(HPRE.ANULADO,0) = 0
   AND    COALESCE(HPRED.MARCA,0)=CASE WHEN COALESCE('','')='COPAGO' THEN 1 ELSE COALESCE(HPRED.MARCA,0) END
   OPEN HADMFTR_CURSOR  
   FETCH NEXT FROM HADMFTR_CURSOR  
   INTO @TIPOFACTURACION, @FACTPORAFU, @IDTERCEROCA, @IDPLAN, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
   WHILE @@FETCH_STATUS = 0  
   BEGIN  
      print 'comienzo cursor'
      IF @FACTPORAFU = 1
      BEGIN
         DECLARE PPTFTR_CURSOR CURSOR FOR
         SELECT  DESCRIPCION, ITEM 
         FROM    PPTFTR 
         WHERE   IDTERCERO = @IDTERCEROCA 
         AND     IDPLAN    = @IDPLAN
         OPEN PPTFTR_CURSOR
         FETCH NEXT FROM PPTFTR_CURSOR
         INTO @DESCRIPCION, @ITEM
         WHILE @@FETCH_STATUS = 0  
         BEGIN  
            SELECT @OK = COUNT(*) FROM HPRED, HPRE, PPTFTRD
            WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
            AND    HPRED.IDPLAN       = @IDPLAN
            AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
            AND    HPRE.NOADMISION    = @NOADMISION
            AND    HPRE.IDAREA        = PPTFTRD.IDAREA
            AND    PPTFTRD.IDTERCERO  = @IDTERCEROCA
            AND    PPTFTRD.IDPLAN     = @IDPLAN
            AND    PPTFTRD.ITEM       = @ITEM
            AND    COALESCE(HPRED.FACTURADA,0) = 0
            AND    COALESCE(HPRED.ENCARGOS, 0) = 0
            AND    ISNULL(HPRED.ANULADO,0) = 0
            AND    ISNULL(HPRE.ANULADO,0) = 0
            IF @OK > 0
            BEGIN
               PRINT 'INSERTO OPCION AFU'
               INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID4,VALOR10,ID5) 
               SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN, @DESCRIPCION, @ITEM, 1, @OK, @TIPOFACTURACION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
               
               SELECT @ITEMRPDX = ITEM FROM RPDX 
               WHERE  CNS = @CNSRPDX AND IDTERCERO = @IDTERCEROCA AND ID1 = @IDPLAN AND NOMBRE = @DESCRIPCION
               AND    CANTIDAD = @ITEM AND CANTIDAD1 = 1 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION 
               AND    ID4 = @IDSEDE
               
               UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX
               FROM HPRED, HPRE, PPTFTRD
               WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
               AND    HPRED.IDPLAN       = @IDPLAN
               AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
               AND    HPRE.NOADMISION    = @NOADMISION
               AND    HPRE.IDAREA        = PPTFTRD.IDAREA
               AND    PPTFTRD.IDTERCERO  = @IDTERCEROCA
               AND    PPTFTRD.IDPLAN     = @IDPLAN
               AND    PPTFTRD.ITEM       = @ITEM
               AND    COALESCE(HPRED.FACTURADA,0) = 0
               AND    COALESCE(HPRED.ENCARGOS, 0) = 0
               AND    ISNULL(HPRED.ANULADO,0) = 0
               AND    ISNULL(HPRE.ANULADO,0) = 0
            END
            
            FETCH NEXT FROM PPTFTR_CURSOR
            INTO @DESCRIPCION, @ITEM
         END      
         CLOSE      PPTFTR_CURSOR
         DEALLOCATE PPTFTR_CURSOR
         SELECT @OK = COUNT(*) FROM HPRED, HPRE
         WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
         AND    HPRED.IDPLAN       = @IDPLAN
         AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
         AND    HPRE.NOADMISION    = @NOADMISION
         AND    COALESCE(HPRED.FACTURADA,0) = 0
         AND    COALESCE(HPRED.ENCARGOS, 0) = 0
         AND    ISNULL(HPRED.ANULADO,0) = 0
         AND    ISNULL(HPRE.ANULADO,0) = 0
         AND    HPRE.IDAREA        NOT IN (SELECT PPTFTRD.IDAREA FROM PPTFTRD
                                           WHERE PPTFTRD.IDTERCERO  = @IDTERCEROCA
                                           AND    PPTFTRD.IDPLAN     = @IDPLAN )
         IF @OK > 0
         BEGIN
            PRINT 'INSERTO OTROS'
            INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID3, ID4,VALOR10,ID5) 
            SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN, 'OTRAS AREAS', 0, 2, @OK, @TIPOFACTURACION, @NOADMISION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
            
            SELECT @ITEMRPDX = ITEM FROM RPDX 
            WHERE  CNS = @CNSRPDX AND IDTERCERO = @IDTERCEROCA AND ID1 = @IDPLAN AND NOMBRE = 'OTRAS AREAS'
            AND    CANTIDAD = 0 AND CANTIDAD1 = 2 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION AND ID3 = @NOADMISION 
            AND    ID4 = @IDSEDE
            
            UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX
            FROM HPRED, HPRE
            WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
            AND    HPRED.IDPLAN       = @IDPLAN
            AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
            AND    HPRE.NOADMISION    = @NOADMISION
            AND    COALESCE(HPRED.FACTURADA,0) = 0
            AND    COALESCE(HPRED.ENCARGOS, 0) = 0
            AND    ISNULL(HPRED.ANULADO,0) = 0
            AND    ISNULL(HPRE.ANULADO,0) = 0
            AND    HPRE.IDAREA        NOT IN (SELECT PPTFTRD.IDAREA FROM PPTFTRD
                                              WHERE PPTFTRD.IDTERCERO  = @IDTERCEROCA
                                              AND   PPTFTRD.IDPLAN     = @IDPLAN )                        
         END
      END
      ELSE
      BEGIN
         IF @FACTPORAFU = 2
         BEGIN
            PRINT 'POR CENTRO DE COSTO'
            /*************************************************************/
            DECLARE PPTFTR_CURSOR CURSOR FOR
            SELECT  DESCRIPCION, ITEM 
            FROM    PPTFTR 
            WHERE   IDTERCERO = @IDTERCEROCA 
            AND     IDPLAN    = @IDPLAN
            OPEN PPTFTR_CURSOR
            FETCH NEXT FROM PPTFTR_CURSOR
            INTO @DESCRIPCION, @ITEM
            WHILE @@FETCH_STATUS = 0  
            BEGIN  
               SELECT @OK = COUNT(*) FROM HPRED, HPRE, PPTFTRD
               WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
               AND    HPRED.IDPLAN       = @IDPLAN
               AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
               AND    HPRE.NOADMISION    = @NOADMISION
               AND    HPRE.CCOSTO        = PPTFTRD.IDAREA
               AND    PPTFTRD.IDTERCERO  = @IDTERCEROCA
               AND    PPTFTRD.IDPLAN     = @IDPLAN
               AND    PPTFTRD.ITEM       = @ITEM
               AND    COALESCE(HPRED.FACTURADA,0) = 0
               AND    COALESCE(HPRED.ENCARGOS, 0) = 0
               AND    ISNULL(HPRED.ANULADO,0) = 0
               AND    ISNULL(HPRE.ANULADO,0) = 0
               IF @OK > 0
               BEGIN
                  PRINT 'INSERTO OPCION CEN'
                  INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID4,VALOR10,ID5) 
                  SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN, @DESCRIPCION, @ITEM, 3, @OK, @TIPOFACTURACION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
                  SELECT @ITEMRPDX = 0 
                  PRINT 'ANTES DE RECOGER EL ITEM EN CEN'

                  SELECT @ITEMRPDX = ITEM FROM RPDX 
                  WHERE  CNS = @CNSRPDX AND IDTERCERO = @IDTERCEROCA AND ID1 = @IDPLAN AND NOMBRE = @DESCRIPCION
                  AND    CANTIDAD = @ITEM AND CANTIDAD1 = 3 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION AND ID4 = @IDSEDE
                  
                  PRINT 'DESPUES =' +STR(@ITEMRPDX)
                  
                  UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX
                  FROM   HPRED INNER JOIN HPRE    ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
                               INNER JOIN PPTFTRD ON HPRE.CCOSTO        = PPTFTRD.IDAREA
                                                 AND PPTFTRD.IDTERCERO  = @IDTERCEROCA
                                                 AND PPTFTRD.IDPLAN     = @IDPLAN
                                                 AND PPTFTRD.ITEM       = @ITEM
                  WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
                  AND    HPRED.IDPLAN       = @IDPLAN
                  AND    HPRE.NOADMISION    = @NOADMISION
                  AND    COALESCE(HPRED.FACTURADA,0) = 0
                  AND    COALESCE(HPRED.ENCARGOS, 0) = 0
                  AND    ISNULL(HPRED.ANULADO,0) = 0
                  AND    ISNULL(HPRE.ANULADO,0) = 0
               END
               FETCH NEXT FROM PPTFTR_CURSOR
               INTO @DESCRIPCION, @ITEM
            END      
            CLOSE      PPTFTR_CURSOR
            DEALLOCATE PPTFTR_CURSOR

            SELECT @OK = COUNT(*) FROM HPRED, HPRE
            WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
            AND    HPRED.IDPLAN       = @IDPLAN
            AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
            AND    HPRE.NOADMISION    = @NOADMISION
            AND    COALESCE(HPRED.FACTURADA,0) = 0
            AND    COALESCE(HPRED.ENCARGOS, 0) = 0
            AND    ISNULL(HPRED.ANULADO,0) = 0
            AND    ISNULL(HPRE.ANULADO,0) = 0
            AND    HPRE.CCOSTO        NOT IN (SELECT PPTFTRD.IDAREA FROM PPTFTRD
                                              WHERE  PPTFTRD.IDTERCERO  = @IDTERCEROCA
                                              AND    PPTFTRD.IDPLAN     = @IDPLAN )
            IF @OK > 0
            BEGIN
               PRINT 'INSERTO OTROS'
               INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID3, ID4,VALOR10,ID5) 
               SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN, 'OTROS CENTROS', 0, 4, @OK, @TIPOFACTURACION, @NOADMISION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA

               SELECT @ITEMRPDX = ITEM FROM RPDX 
               WHERE  CNS = @CNSRPDX AND IDTERCERO = @IDTERCEROCA AND ID1 = @IDPLAN AND NOMBRE = 'OTROS CENTROS'
               AND    CANTIDAD = 0 AND CANTIDAD1 = 4 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION AND ID3 = @NOADMISION 
               AND    ID4 = @IDSEDE
               
               UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX
               FROM HPRED, HPRE
               WHERE  HPRED.IDTERCEROCA  = @IDTERCEROCA
               AND    HPRED.IDPLAN       = @IDPLAN
               AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
               AND    HPRE.NOADMISION    = @NOADMISION
               AND    COALESCE(HPRED.FACTURADA,0) = 0
               AND    COALESCE(HPRED.ENCARGOS, 0) = 0
               AND    ISNULL(HPRED.ANULADO,0) = 0
               AND    ISNULL(HPRE.ANULADO,0) = 0
               AND    HPRE.CCOSTO        NOT IN (SELECT PPTFTRD.IDAREA FROM PPTFTRD
                                                 WHERE  PPTFTRD.IDTERCERO  = @IDTERCEROCA
                                                 AND    PPTFTRD.IDPLAN     = @IDPLAN )
            END
         END
         /*************************************************************/
         ELSE
         BEGIN   
            PRINT 'INSERTO SIN AREA'
            IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
            BEGIN
               DECLARE @N_FACTURAAUD VARCHAR(20)
               SELECT @N_FACTURAAUD=N_FACTURA FROM HADM WHERE NOADMISION=@NOADMISION
               IF COALESCE(@USUARIO,'')<>'COPAGO'
               BEGIN
                  PRINT 'DIFERENTE A COPAGO'
                  SELECT @OK = COUNT(*) FROM HPRED, HPRE
                  WHERE  HPRE.IDTERCEROCA  = @IDTERCEROCA
                  AND    HPRE.IDPLAN       = @IDPLAN
                  AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
                  AND    HPRE.NOADMISION    = @NOADMISION
                  AND    COALESCE(HPRED.FACTURADA,0) = 0
                  AND    COALESCE(HPRED.MARCA,0)= CASE WHEN COALESCE(@MARCA_HPRED,'SI')='SI' AND COALESCE(@USUARIO,'')<>'' THEN  1 ELSE COALESCE(HPRED.MARCA,0) END
                  AND    COALESCE(HPRED.USUARIOMARCA,'')=CASE WHEN COALESCE(@MARCA_HPRED,'SI')='SI' AND COALESCE(@USUARIO,'')<>'' THEN @USUARIO ELSE COALESCE(HPRED.USUARIOMARCA,'') END
                  AND    ISNULL(HPRED.ANULADO,0) = 0
                  AND    ISNULL(HPRE.ANULADO,0) = 0
                  IF @OK>0
                  BEGIN
                     INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID3, ID4,VALOR10,ID5) 
                     SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN, 'TODAS', 0, 0, @OK,  @TIPOFACTURACION, @NOADMISION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
            
                     SELECT @ITEMRPDX = ITEM FROM RPDX 
                     WHERE  CNS = @CNSRPDX AND IDTERCERO = @IDTERCEROCA AND ID1 = @IDPLAN AND NOMBRE = 'TODAS'
                     AND    CANTIDAD = 0 AND CANTIDAD1 = 0 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION AND ID3 = @NOADMISION 
                     AND    ID4 = @IDSEDE
            
                     UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX            
                     FROM   HPRED, HPRE
                     WHERE  HPRE.IDTERCEROCA  = @IDTERCEROCA
                     AND    HPRE.IDPLAN       = @IDPLAN
                     AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
                     AND    HPRE.NOADMISION    = @NOADMISION
                     AND    COALESCE(HPRED.FACTURADA,0) =CASE WHEN @NOADMISION LIKE '%R%' THEN COALESCE(HPRED.FACTURADA,0) ELSE   0 END
                     AND    COALESCE(HPRED.MARCA,0)= CASE WHEN COALESCE(@USUARIO,'')<>'' THEN  1 ELSE COALESCE(HPRED.MARCA,0) END
                     AND    COALESCE(HPRED.USUARIOMARCA,'')=CASE WHEN COALESCE(@USUARIO,'')<>'' THEN @USUARIO ELSE COALESCE(HPRED.USUARIOMARCA,'') END
                     AND    COALESCE(HPRED.N_FACTURA,'')=CASE WHEN COALESCE(@N_FACTURAAUD,'')<>'' THEN @N_FACTURAAUD ELSE COALESCE(HPRED.N_FACTURA,'') END
                     AND    ISNULL(HPRED.ANULADO,0) = 0
                     AND    ISNULL(HPRE.ANULADO,0) = 0
                  END
               END
               ELSE
               BEGIN
                  PRINT 'CON COPAGO  A BORDO'
                  SELECT @OK = COUNT(*) FROM HPRED, HPRE
                  WHERE  HPRE.IDTERCEROCA  = @IDTERCEROCA
                  AND    HPRE.IDPLAN       = @IDPLAN
                  AND    HPRED.NOPRESTACION = HPRE.NOPRESTACION
                  AND    HPRE.NOADMISION    = @NOADMISION
                  AND    COALESCE(HPRED.N_FACTURAH,'')=''
                  AND    COALESCE(HPRED.VALORCOPAGO,0)>0
                  AND    COALESCE(HPRED.MARCA,0)=CASE WHEN COALESCE(@USUARIO,'')='COPAGO' THEN 1 ELSE COALESCE(HPRED.MARCA,0) END
                  AND    ISNULL(HPRED.ANULADO,0) = 0
                  AND    ISNULL(HPRE.ANULADO,0) = 0
                  
                  IF @OK>0
                  BEGIN
                     DECLARE @NODOCUMENTO VARCHAR(20)
                     DECLARE @IDPLANPART  VARCHAR(7)
                     SELECT @NODOCUMENTO=AFI.DOCIDAFILIADO,@IDPLANPART=DBO.FNK_VALORVARIABLE('IDPLANPART') 
                     FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
                     WHERE HADM.NOADMISION=@NOADMISION
                     SELECT @TIPOTERCONTA=DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART')

                     INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID3, ID4,VALOR10,ID5) 
                     SELECT @CNSRPDX, @NODOCUMENTO, @IDPLANPART, 'COPAGOS', 0, 0, @OK,  @TIPOFACTURACION, @NOADMISION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
            
                     SELECT @ITEMRPDX = ITEM FROM RPDX 
                     WHERE  CNS = @CNSRPDX AND IDTERCERO = @NODOCUMENTO AND ID1 = @IDPLANPART AND NOMBRE = 'COPAGOS'
                     AND    CANTIDAD = 0 AND CANTIDAD1 = 0 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION AND ID3 = @NOADMISION 
                     AND    ID4 = @IDSEDE

                     PRINT 'HAGO EL UPDATE'
                     UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX            
                     FROM   HPRED, HPRE
                     WHERE  HPRED.NOPRESTACION = HPRE.NOPRESTACION
                     AND    HPRE.NOADMISION    = @NOADMISION
                     AND    COALESCE(HPRED.N_FACTURAH,'')=''
                     AND    COALESCE(HPRED.VALORCOPAGO,0)>0
                     AND    COALESCE(HPRED.MARCA,0)=CASE WHEN COALESCE(@USUARIO,'')='COPAGO' THEN 1 ELSE COALESCE(HPRED.MARCA,0) END
                     AND    ISNULL(HPRED.ANULADO,0) = 0
                     AND    ISNULL(HPRE.ANULADO,0) = 0
                  END
               END
            END
            ELSE
            BEGIN
               SELECT @VALORTOTAL=SUM(HPRED.CANTIDAD*COALESCE(HPRED.VALOR,0)), @VALORCOPAGO=SUM(HPRED.VALORCOPAGO), @VALOREXCEDENTE=SUM(HPRED.VALOREXCEDENTE), @OK=COUNT(1)
			   FROM HPRED, HPRE
               WHERE  HPRED.NOPRESTACION = HPRE.NOPRESTACION
               AND    HPRE.NOADMISION    = @NOADMISION
			   AND	  HPRED.IDTERCEROCA  = @IDTERCEROCA
               AND    HPRED.IDPLAN       = @IDPLAN
               AND    COALESCE(HPRED.FACTURADA,0) = 0
               AND    COALESCE(HPRED.ENCARGOS, 0) = CASE WHEN DBO.FNK_VALORVARIABLE ('VALIDAR_APOYODX') = 'SI' THEN 0 ELSE COALESCE(HPRED.ENCARGOS, 0) END -- ST - Se agrega validacion
               AND    ISNULL(HPRED.NOCOBRABLE,0) = 0
               AND    ISNULL(HPRED.ANULADO,0) = 0
               AND    ISNULL(HPRE.ANULADO,0) = 0
               AND    1= CASE WHEN COALESCE(1,0)=1 THEN CASE WHEN COALESCE(HPRED.PAQUETE,0) =1  THEN 1 ELSE 0 END ELSE 1 END

               IF @OK>0
               BEGIN
                   INSERT INTO RPDX ( CNS, IDTERCERO, ID1, NOMBRE, CANTIDAD, CANTIDAD1, CANTIDAD2, ID2, ID3, ID4,VALOR10,ID5, VALOR2, VALOR3, VALOR4) 
                   SELECT @CNSRPDX, @IDTERCEROCA, @IDPLAN, 'TODAS', 0, 0, @OK,  @TIPOFACTURACION, @NOADMISION, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA, @VALORTOTAL, @VALORCOPAGO, @VALOREXCEDENTE
            
                   SELECT @ITEMRPDX = ITEM FROM RPDX 
                   WHERE  CNS = @CNSRPDX AND IDTERCERO = @IDTERCEROCA AND ID1 = @IDPLAN AND NOMBRE = 'TODAS'
                   AND    CANTIDAD = 0 AND CANTIDAD1 = 0 AND CANTIDAD2 = @OK AND ID2 = @TIPOFACTURACION AND ID3 = @NOADMISION 
                   AND    ID4 = @IDSEDE
            
                   UPDATE HPRED SET ITEM_RPDX = @ITEMRPDX            
                   FROM   HPRED, HPRE
                   WHERE  HPRED.NOPRESTACION = HPRE.NOPRESTACION
                   AND    HPRE.NOADMISION    = @NOADMISION
				   AND	  HPRED.IDTERCEROCA  = @IDTERCEROCA
                   AND    HPRED.IDPLAN       = @IDPLAN
                   AND    COALESCE(HPRED.FACTURADA,0) = 0
                   AND    COALESCE(HPRED.ENCARGOS, 0) = CASE WHEN DBO.FNK_VALORVARIABLE ('VALIDAR_APOYODX') = 'SI' THEN 0 ELSE COALESCE(HPRED.ENCARGOS, 0)END  -- ST - Se agrega validacion
                   AND    ISNULL(HPRED.ANULADO,0) = 0
                   AND    ISNULL(HPRE.ANULADO,0) = 0
               END
            END
         END             
      END
      FETCH NEXT FROM HADMFTR_CURSOR  
      INTO @TIPOFACTURACION, @FACTPORAFU, @IDTERCEROCA, @IDPLAN, @IDSEDE,@PFACTURARIND,@TIPOTERCONTA
        
   END
   CLOSE HADMFTR_CURSOR
   DEALLOCATE HADMFTR_CURSOR
    
END


