CREATE OR ALTER VIEW VWK_FACTURAS_ENCXC
AS
SELECT ROW_NUMBER() OVER(ORDER  BY FCXCD.CNSCXC,FCXCD.N_FACTURA  ASC) ID, FCXCD.CNSCXC,FCXCD.N_FACTURA,DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA)F_FACTURA,
IIF(FCXC.F_RECIBIDO IS NOT NULL,DBO.FNK_FECHA_DDMMAA(FCXC.F_RECIBIDO),'')F_RECIBIDO,
FTR.TIPOTTEC,PLN.TIPOSISTEMA,CASE WHEN FTR.CAPITADA=1 THEN 'Capita'ELSE 'Evento'END CAPITADA,
IIF(EXISTS(SELECT * FROM LGCOBD WHERE NOREFERENCIA=FTR.N_FACTURA),'Si','No')COBROJUR,
IIF(EXISTS(SELECT * FROM FCXCR WHERE N_FACTURA=FTR.N_FACTURA),'Si','No')DEVUELTA,
TER.NIT,FTR.IDTERCERO,TER.RAZONSOCIAL,COALESCE(FCXC.SUCURSAL,'')SUCURSAL,FTR.VALORSERVICIOS,FTR.VALORCOPAGO,
FCXCD.VALORFACTURA,FCXCD.SALDONETO,FCXCD.DEDUCCIONES,
IIF(EXISTS (SELECT * FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),
   (SELECT TOP 1 DBO.FNK_FECHA_DDMMAA(FPAG.FECHAPAGO) FROM FGLO INNER JOIN FPAG ON FGLO.CNSFPAG=FPAG.CNSFPAG
   WHERE FGLO.N_fACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC ORDER BY FPAG.FECHAPAGO),'')FECHAGLO,
IIF(EXISTS (SELECT * FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),
   (SELECT TOP 1 FGLO.VLRGLOSA FROM FGLO INNER JOIN FPAG ON FGLO.CNSFPAG=FPAG.CNSFPAG
   WHERE FGLO.N_fACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC ORDER BY FPAG.FECHAPAGO),0)GLOSAINI,
IIF(EXISTS (SELECT * FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),
(SELECT SUM(FGLO.VLRGLOSA)  FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),0)VLRGLOSAS,
IIF(EXISTS (SELECT * FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),
(SELECT SUM(VLRRECUPERAR)  FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),0)VLRRECUPERA,
IIF(EXISTS (SELECT * FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),
(SELECT SUM(VLRACEPTADO)  FROM FGLO WHERE FGLO.N_FACTURA=FCXCD.N_FACTURA AND FGLO.CNSCXC=FCXCD.CNSCXC),0)VLRACEPTADO,
FCXCD.VLRPAGOS,FCXCD.VLRNOTADB,FCXCD.VLRNOTACR,FCXCD.VLRLEVANTADO,
IIF(EXISTS(SELECT * FROM FCONCID WHERE N_fACTURA=FCXCD.N_FACTURA AND CNSCXC=FCXCD.CNSCXC),
(SELECT TOP 1 DBO.FNK_FECHA_DDMMAA(FCONCI.FECHACONC) FROM FCONCI INNER JOIN FCONCID ON FCONCI.IDFCONCI=FCONCID.IDFCONCI 
WHERE FCONCID.N_FACTURA=FCXCD.N_FACTURA AND FCONCID.CNSCXC=FCXCD.CNSCXC AND FCONCI.ESTADO='Cerrada'),'')F_CONCI,
AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,CASE WHEN FCXC.INDRECIBIDO=1 THEN 'Si' ELSE 'No' END RADICADA,
CASE FTR.PROCEDENCIA WHEN 'SALUD' THEN (SELECT DBO.FNK_FECHA_DDMMAA(HADM.FECHA) FROM HADM WHERE NOADMISION=FTR.NOREFERENCIA)
     WHEN 'CE' THEN (SELECT DBO.FNK_FECHA_DDMMAA(AUT.FECHA) FROM AUT WHERE NOAUT=FTR.NOREFERENCIA)
     WHEN 'CI' THEN (SELECT DBO.FNK_FECHA_DDMMAA(CIT.FECHA) FROM CIT WHERE CONSECUTIVO=FTR.NOREFERENCIA)
     ELSE  DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA) END FECHAING,
CASE FTR.PROCEDENCIA WHEN 'SALUD' THEN (SELECT DBO.FNK_FECHA_DDMMAA(COALESCE(HADM.FECHAALTAMED,HADM.FECHAALTA)) FROM HADM WHERE NOADMISION=FTR.NOREFERENCIA)
     WHEN 'CE' THEN (SELECT DBO.FNK_FECHA_DDMMAA(AUT.FECHA) FROM AUT WHERE NOAUT=FTR.NOREFERENCIA)
     WHEN 'CI' THEN (SELECT DBO.FNK_FECHA_DDMMAA(CIT.FECHA) FROM CIT WHERE CONSECUTIVO=FTR.NOREFERENCIA)
     ELSE  DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA) END FECHAEGR
FROM FCXCD INNER JOIN FTR ON FCXCD.N_FACTURA=FTR.N_FACTURA
           INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
           INNER JOIN FCXC ON FCXCD.CNSCXC=FCXC.CNSCXC
           LEFT JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
           LEFT JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
