IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_CREA_FACTURA_DESDE_CAJA' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_CREA_FACTURA_DESDE_CAJA
END
GO
CREATE PROCEDURE DBO.SPK_CREA_FACTURA_DESDE_CAJA
@CNSFACJ	VARCHAR(20),
@CODCAJA VARCHAR(10),
@CNSPCJ  VARCHAR(20),
@CNSDOC  VARCHAR(20),
@COMPANIA	VARCHAR(2)='01',
@SEDE		VARCHAR(5),
@USUARIO	VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),	
@FACTURADOC  VARCHAR(20) OUTPUT
WITH ENCRYPTION
AS
DECLARE @CNSFCT		VARCHAR(40)
DECLARE @N_FACTURA	VARCHAR(16)
DECLARE @F_FACTURA	DATETIME
DECLARE @F_VENCE	DATETIME
DECLARE @PREFIJOFAC	VARCHAR(8)
DECLARE @IDTERCERO	VARCHAR(20)
DECLARE @IDACTIVO	VARCHAR(20)
DECLARE @IDAREA		VARCHAR(20)
DECLARE @CCOSTO		VARCHAR(20)
DECLARE @VALOR		DECIMAL(14,2)
DECLARE @PREFIJO	VARCHAR(6)
DECLARE @PCOSTO		DECIMAL(14,2)
DECLARE @OBSERVACION	VARCHAR(100)
DECLARE @N_CUOTA	INT
DECLARE @DATO           VARCHAR(80)
DECLARE @CNSIACTH       VARCHAR(20)
BEGIN
   PRINT 'INGRESE A CREAR LA FACUTRA'


   SET @CNSFCT=SPACE(40)
   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@CNSFTR',@CNSFCT OUTPUT   
   SELECT @CNSFCT = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFCT))+LTRIM(RTRIM(@CNSFCT)),SPACE(1),0)
   IF DBO.FNK_VALORVARIABLE('GENERA_FTR_DE_PAGARE')='SI'
   BEGIN 
      SET @N_FACTURA = SPACE(20)
      EXEC SPK_GENNUMEROFACTURA @COMPANIA, @SEDE, NULL, @N_FACTURA OUTPUT  
   END
   ELSE
   BEGIN
      SET @N_FACTURA = SPACE(20)
      SELECT @N_FACTURA=@CNSDOC
   END 



   SET @F_FACTURA=DBO.FNK_FECHA_SIN_HORA(GETDATE())
   SET @F_VENCE=@F_FACTURA+30
 

   INSERT INTO FTR (CNSFCT,COMPANIA,CLASE,IDTERCERO,N_FACTURA,F_FACTURA,F_VENCE,VR_TOTAL,
		            COBRADOR,VENDEDOR,MONEDA,OCOMPRA,ESTADO,F_CANCELADO,IDAFILIADO,EMPLEADO,
	   	         NOREFERENCIA,PROCEDENCIA,TIPOFAC,OBSERVACION,TIPOVENTA,VALORCOPAGO,
		            DESCUENTO,VALORPCOMP,CREDITO,INDCARTERA,INDCXC,MARCA,INDASIGCXC,MARCACONT,
		            CONTABILIZADA,NROCOMPROBANTE,IMPRESO,VALORSERVICIOS,CLASEANULACION,CNSLOG,
		            USUARIOFACTURA,FECHAFAC,MIVA,PIVA,IDPLAN,VR_ABONOS,FECHAPASOCXC,TIPOFIN,
		            CNSFMAS,IDAREA_ALTA,CCOSTO_ALTA,IDDEP,TIPOCOPAGO,VLRNOTADB,VLRNOTACR,
		            TIPOTTEC,CUENTACXC,RAZONANULACION,CODUNG,CODPRG)
   SELECT @CNSFCT,@COMPANIA,'C',PCJ.IDTERCERO,@N_FACTURA,@F_FACTURA,@F_VENCE,
	      PCJ.VALOR,'','','' AS MONEDA,NULL,'P',NULL,'',@USUARIO,@CNSDOC,'CAJA','I',
	      FPA.DESCRIPCION+' NOADMISION: '+FCJ.NOADMISION+' RECIBO CAJA'+@CNSFACJ+' CODCAJA'+@CODCAJA,'Credito',0,0,0,0,0,0,0,0,0,0,'',0,
         PCJ.VALOR,NULL,NULL,@USUARIO,
	      DBO.FNK_FECHA_SIN_MLS(GETDATE()),0,0,DBO.FNK_VALORVARIABLE('IDPLANPART'),0,NULL,'C',NULL,NULL,NULL,NULL,
	      NULL,NULL,NULL,DBO.FNK_VALORVARIABLE('IDTERCONTABLEPART'),PCJ.CUENTA,NULL,'',''
   FROM  PCJ INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO
             INNER JOIN FCJ ON PCJ.CODCAJA=FCJ.CODCAJA AND PCJ.CNSFACJ=FCJ.CNSFACJ
   WHERE PCJ.CNSFACJ=@CNSFACJ
   AND PCJ.CODCAJA=@CODCAJA
   AND PCJ.CNSPCJ=@CNSPCJ
   AND PCJ.CNSDOC=@CNSDOC

     SET @N_CUOTA=1

   INSERT INTO FTRD (CNSFTR,IDPROVEEDOR,N_CUOTA,FECHA,DB_CR,AREAPRESTACION,AREAFUNCONT,
		      UBICACION,VR_TOTAL,IMPUTACION,CCOSTO,PREFIJO,ANEXO,REFERENCIA,IDCIRUGIA,
		      CANTIDAD,VALOR,VLR_SERVICI,VLR_COPAGOS,VLR_PAGCOMP,NOADMISION,
		      NOPRESTACION,NOITEM,N_FACTURA,SUBCCOSTO,PCOSTO,FECHAPREST,VLRNOTADB,
		      VLRNOTACR,TIPO)
   SELECT @CNSFCT,PCJ.IDTERCERO,@N_CUOTA,DBO.FNK_FECHA_SIN_MLS(GETDATE()),'DB',@IDAREA,@IDAREA,
	   NULL,PCJ.VALOR,NULL,@CCOSTO,@PREFIJO,@OBSERVACION,@IDACTIVO,NULL,1,PCJ.VALOR,PCJ.VALOR,0,0,
	   '','','',@N_FACTURA,NULL,@PCOSTO,NULL,0,0,NULL
   FROM  PCJ INNER JOIN FPA ON PCJ.TIPOPAGO=FPA.FORMAPAGO
             INNER JOIN FCJ ON PCJ.CODCAJA=FCJ.CODCAJA AND PCJ.CNSFACJ=FCJ.CNSFACJ
   WHERE PCJ.CNSFACJ=@CNSFACJ
   AND PCJ.CODCAJA=@CODCAJA
   AND PCJ.CNSPCJ=@CNSPCJ
   AND PCJ.CNSDOC=@CNSDOC

  PRINT 'DEVUELVO EL N_FACTURA'
  SELECT @FACTURADOC=@N_FACTURA
  PRINT '@FACTURADOC='+@FACTURADOC
END

