IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_OM' AND XTYPE='TF')
BEGIN
   DROP FUNCTION FNK_OM
END

GO
CREATE FUNCTION DBO.FNK_OM(@CONSECUTIVO VARCHAR(13)) 
RETURNS @L_OM TABLE (OM VARCHAR(10),CODOM VARCHAR(80), IDSERVICIO VARCHAR(20), DESCSERVICIO VARCHAR(512), CANTIDAD DECIMAL(14,2),PRESUNI VARCHAR(20), 
                     VIA VARCHAR(13), CLASE VARCHAR(10), FRECUENCIA DECIMAL(14,2), DURACION DECIMAL(14,2), ESTADO VARCHAR(40), LUNES SMALLINT,
                     MARTES SMALLINT, MIERCOLES SMALLINT, JUEVES SMALLINT, VIERNES SMALLINT, SABADO SMALLINT, DOMINGO SMALLINT, OBSERVACION VARCHAR(2048), RAZONNEC SMALLINT)
WITH ENCRYPTION
AS
BEGIN
   DECLARE @NUT VARCHAR(20)=DBO.FNK_VALORVARIABLE('OMCODNUTRICIONP')

   INSERT INTO @L_OM
   SELECT 
      HCATD.CODOM,
      CASE ROW_NUMBER() OVER(PARTITION BY HCATD.CODOM ORDER BY HCATD.CODOM) WHEN 1 THEN HCCOM.DESCRIPCION ELSE '' END OM,
      CASE WHEN @NUT<>HCATD.CODOM THEN HCATD.IDSERVICIO ELSE HCATDH.IDSERVICIOD END IDSERVICIO,  
      SER.DESCSERVICIO,
      CONVERT(DECIMAL(14,2), CASE WHEN @NUT<>HCATD.CODOM THEN (CASE ISNULL(HCA.BOLO,0) WHEN 0 THEN HCATD.CANTIDAD ELSE HCATD.CANTIDADBOLO END) ELSE HCATDH.CANTIDAD END) CANTIDAD, 
      CASE WHEN @NUT<>HCATD.CODOM THEN HCATD.IDTIPOCONC ELSE SER.PRESUNI END PRESUNI, 
      HCATD.VIA, 
      CASE HCATD.CLASE WHEN 'I' THEN 'Iniciar' WHEN 'C' THEN 'Continuar' WHEN 'S' THEN 'Suspender' WHEN 'B' THEN 'Cambiar' END CLASE,
      HCATD.FRECUENCIA, 
      HCATD.DURACION, 
      CASE ISNULL(HCCOMD.AYUDADX,0) WHEN 1 THEN DBO.FNK_ESTADO_LABORATORIO (HCATD.NOPRESTACION, HCATD.NOITEM, HCATD.CODOM, HCATD.IDSERVICIO) ELSE '' END ESTADO, 
      ISNULL(HCATD.LUNES,0), ISNULL(HCATD.MARTES,0), ISNULL(HCATD.MIERCOLES,0), ISNULL(HCATD.JUEVES,0), ISNULL(HCATD.VIERNES,0), ISNULL(HCATD.SABADO,0), ISNULL(HCATD.DOMINGO,0),
      REPLACE(REPLACE(HCATD.OBSERVACION,CHAR(10),''),CHAR(13),''),
      HCATD.RAZONNEC
   FROM HCATD 
      INNER JOIN HCA   ON HCATD.CONSECUTIVO = HCA.CONSECUTIVO
      LEFT JOIN HCATDH ON HCA.CONSECUTIVO   = HCATDH.CONSECUTIVO AND HCATD.IDSERVICIO = HCATDH.IDSERVICIO AND HCATDH.CODOM=@NUT
      LEFT JOIN SER    ON SER.IDSERVICIO    = CASE WHEN @NUT<>HCATD.CODOM THEN HCATD.IDSERVICIO ELSE HCATDH.IDSERVICIOD END
      LEFT JOIN HCCOM  ON HCATD.CODOM       = HCCOM.CODOM
      LEFT JOIN HCCOMD ON HCCOMD.CODOM      = HCCOM.CODOM 
                AND HCCOMD.PREFIJO=(CASE COALESCE(HCCOMD.IDSERVICIO,'') WHEN '' THEN SER.PREFIJO ELSE HCCOMD.PREFIJO END)
                AND COALESCE(HCCOMD.IDSERVICIO,'')=(CASE COALESCE(HCCOMD.IDSERVICIO,'') WHEN '' THEN COALESCE(HCCOMD.IDSERVICIO,'') ELSE HCATD.IDSERVICIO END)
   WHERE HCA.CONSECUTIVO = @CONSECUTIVO 
   ORDER BY HCCOM.ORDEN
   RETURN
END

