IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND IDCONTROL='Config_Mdx')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_CONFIGURACION', 'Config_Mdx', 'M', 'Diagnósticos', 1, 'conf.Diganosticos', 'fa-solid fa-person-chalkboard', 6, 0, 0, 80, 'Grupos de Enfermedades', NULL, NULL
END