CREATE OR ALTER PROCEDURE DBO.SPQ_HCINP_COL
@JSON  NVARCHAR(MAX)
WITH  
ENCRYPTION
AS
DECLARE @PARAMETROS    NVARCHAR(MAX)  ,@MODELO           VARCHAR(100)    ,@METODO        VARCHAR(100)  ,@USUARIO        VARCHAR(12)
       ,@GRUPO         VARCHAR(8)     ,@SYS_COMPUTERNAME VARCHAR(254)    ,@SEDE          VARCHAR(5)	   ,@A              INT
       ,@IDENTITY      INT 
       ,@PROCESO       VARCHAR(20)    ,@HCINP            NVARCHAR(MAX)
       ,@CIRUGIA       VARCHAR(20)    ,@ID               INT
       ,@IDSER         VARCHAR(20)    ,@DESCSERVICIO     VARCHAR(255)
       ,@CANTIDADEST   FLOAT          ,@PROCEDENCIA      VARCHAR(20)
       ,@BASICO        SMALLINT       ,@BASICOBOOLEAN    BIT
       ,@TIPO          VARCHAR(20)    ,@IDMEDICO         VARCHAR(12)
       ,@DESTINO       VARCHAR(20)    ,@CANASTA          NVARCHAR(MAX)  ,@TIPOAUX  VARCHAR(20)
BEGIN
   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END
   PRINT 'INGRESE A SPQ_HCINP_COL'
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
     MODELO         VARCHAR(100)     '$.MODELO',
     METODO         VARCHAR(100)     '$.METODO',
     USUARIO        VARCHAR(12)      '$.USUARIO',
     PARAMETROS     NVARCHAR(MAX)     AS JSON
   )
   
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   --SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   --SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE
   IF @METODO = 'CRUDHCINP'
   BEGIN
      PRINT 'CRUDHCINP'
      SELECT @HCINP  = REGISTRO
      FROM OPENJSON (@PARAMETROS)
      WITH(
         REGISTRO   NVARCHAR(MAX)     AS JSON
      )
      SELECT @PROCEDENCIA = JSON_VALUE(@PARAMETROS ,'$.PROCEDENCIA')
      
      SELECT @PROCESO     = JSON_VALUE(@HCINP ,'$.PROCESO')
      --Leo Campos enviados y los coloco en las variables respectivas
      SELECT @ID             = JSON_VALUE(@HCINP , '$.ID')
      SELECT @CIRUGIA        = JSON_VALUE(@HCINP , '$.CIRUGIA' )
      SELECT @IDSER          = JSON_VALUE(@HCINP , '$.IDSER' )
      SELECT @DESCSERVICIO   = JSON_VALUE(@HCINP , '$.DESCSERVICIO')
      SELECT @CANTIDADEST    = JSON_VALUE(@HCINP , '$.CANTIDADEST' )
      SELECT @BASICOBOOLEAN  = JSON_VALUE(@HCINP , '$.BASICO' )
      SELECT @TIPO           = JSON_VALUE(@HCINP , '$.TIPO.value' )
      SELECT @IDMEDICO       = JSON_VALUE(@HCINP , '$.IDMEDICO')
      IF UPPER(@PROCESO) = 'INSERTAR'
      BEGIN
         PRINT 'INSERTAR'
         IF @TIPO <> 'TODOS'
         BEGIN
            IF COALESCE(@IDMEDICO,'') <> ''
               SELECT @TIPO = @TIPO + '_' + @IDMEDICO
         END
         BEGIN TRY
            INSERT INTO HCINP(CIRUGIA,IDSER,CANTIDADEST,BASICO,TIPO)
            SELECT @CIRUGIA,@IDSER,@CANTIDADEST,@BASICOBOOLEAN,@TIPO
            SELECT @IDENTITY = SCOPE_IDENTITY()
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK ,str(@IDENTITY) CNS 
         RETURN
      END
      IF UPPER(@PROCESO) = 'EDITAR'
      BEGIN
         PRINT '@IDMEDICO='+@IDMEDICO
         IF @TIPO <> 'TODOS'
         BEGIN
            IF COALESCE(@IDMEDICO,'') <> ''
               SELECT @TIPO = @TIPO + '_' + @IDMEDICO
         END
         PRINT '@TIPO='+@TIPO
         --SELECT * FROM HCINP WHERE ID = @ID
         BEGIN TRY
            UPDATE HCINP SET CIRUGIA = @CIRUGIA,IDSER = @IDSER,CANTIDADEST = @CANTIDADEST,BASICO = @BASICOBOOLEAN,TIPO = @TIPO
            WHERE ID = @ID
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
         IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
         RETURN
      END
      IF UPPER(@PROCESO) = 'BORRAR'
      BEGIN
         DELETE HCINP WHERE ID = @ID
         SELECT 'OK' OK
         RETURN
      END
      RETURN
   END
   IF @METODO = 'TRAECANASTA'
   BEGIN
      SELECT @CIRUGIA = JSON_VALUE(@PARAMETROS ,'$.CIRUGIA')
      SELECT 'OK' OK
      SELECT HCINP.IDSER ,SER.DESCSERVICIO ,HCINP.CANTIDADEST
      FROM   HCINP INNER JOIN SER ON HCINP.IDSER = SER.IDSERVICIO
      WHERE  HCINP.CIRUGIA = @CIRUGIA
      RETURN
   END
   IF @METODO = 'COPIARCANASTA'
   BEGIN
     
      SELECT @CIRUGIA  = JSON_VALUE(@PARAMETROS, '$.CIRUGIA')
            ,@DESTINO  = JSON_VALUE(@PARAMETROS, '$.DESTINO')
            ,@TIPO     = JSON_VALUE(@PARAMETROS, '$.TIPO')
            ,@IDMEDICO = JSON_VALUE(@PARAMETROS, '$.MEDICO')
            ,@CANASTA  = JSON_QUERY(@PARAMETROS, '$.CANASTA');

      CREATE TABLE #TempCanasta (IDSERVICIO  VARCHAR(20) collate DATABASE_DEFAULT)
      INSERT INTO #TempCanasta (IDSERVICIO) SELECT value  FROM OPENJSON(@CANASTA)


      IF @TIPO <> 'TODOS'
      BEGIN
         IF @IDMEDICO <> ''
            SELECT @TIPOAUX = @TIPO + '_' + @IDMEDICO 
         ELSE
            SELECT @TIPOAUX = @TIPO 
      END
      ELSE
         SELECT @TIPOAUX = 'TODOS'

      IF(SELECT COUNT(*) FROM HCINP WHERE CIRUGIA = @DESTINO AND TIPO = @TIPOAUX) >0
      BEGIN
         INSERT INTO @TBLERRORES (ERROR) SELECT 'La Canasta Destino ya contiene Items Configurados.'
         SELECT 'KO' OK
         SELECT ERROR FROM @TBLERRORES
      END

      INSERT INTO HCINP (CIRUGIA, IDSER, CANTIDADEST, BASICO, TIPO) 
      SELECT @DESTINO, HCINP.IDSER, HCINP.CANTIDADEST, HCINP.BASICO, @TIPOAUX
      FROM   HCINP INNER JOIN #TempCanasta TC ON HCINP.IDSER = TC.IDSERVICIO 
      WHERE  HCINP.CIRUGIA = @CIRUGIA

      SELECT 'OK' OK

      RETURN         
   END
END




