CREATE OR ALTER PROCEDURE DBO.SPQ_RIPS_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			    ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		       ,@IDSEDE      VARCHAR(5)		
      ,@PREFIJO   VARCHAR(20)       		,@SYS_COMPUTERNAME VARCHAR(200)	 ,@CNSLOG	VARCHAR(20)			        	
      ,@IDMODELOAG VARCHAR(12)	         ,@PROCESO VARCHAR(100)= 'INSERT'	 ,@DATOS VARCHAR(MAX)
      ,@NOADMISION VARCHAR(20)            ,@CNSRPDX VARCHAR(20)             ,@EXISTE INT
      ,@ITEMRPDX   INT                    ,@FECHAFAC DATE                   ,@NIT VARCHAR(20)
      ,@F_CORTE  DATETIME                 ,@NOAUTORIZA VARCHAR(20)          ,@F_INICIAL DATETIME
      ,@F_FINIAL DATETIME                 ,@HADMAUT_ID INT                  ,@TIPORPT VARCHAR(20)
      ,@FECHA VARCHAR(20)                 ,@REQSEDE VARCHAR(3)              ,@IDTERCERO VARCHAR(20)
      ,@RAZONSOCIAL VARCHAR(60)           ,@F_FINAL VARCHAR(20)             ,@CAPITADO BIT   
      ,@PORCXC BIT                         ,@IDPLAN VARCHAR(20)             ,@DESCPLAN VARCHAR(26)
      ,@CNSCXC VARCHAR(20)                ,@N_FACTURA VARCHAR(20)           ,@CODSERVICIO VARCHAR(20)   
      ,@CODMEDICA VARCHAR(20)             ,@ESTADO VARCHAR(20)              ,@ENVIO VARCHAR(20)
      ,@IDSEDEF  VARCHAR(5)               ,@IDSGSSS VARCHAR(20)             ,@ENVIO_AC VARCHAR(MAX)
      ,@ENVIO_AP VARCHAR(MAX)             ,@ENVIO_AT VARCHAR(MAX)           ,@ENVIO_AM VARCHAR(MAX)
      ,@ENVIO_AU VARCHAR(MAX)             ,@ENVIO_AH VARCHAR(MAX)           ,@ENVIO_AN VARCHAR(MAX)
      ,@ENVIO_US VARCHAR(MAX)             ,@ENVIO_AF VARCHAR(MAX)           ,@ENVIO_AD VARCHAR(MAX)
      ,@ENVIO_CT VARCHAR(MAX)             ,@COUNT_AC INT                    ,@COUNT_US INT
      ,@COUNT_AU INT                      ,@COUNT_AF INT                    ,@COUNT_AD INT
      ,@COUNT_AH INT                      ,@COUNT_AP INT                    ,@COUNT_AM INT
      ,@COUNT_AN INT                      ,@COUNT_AT INT                    ,@COMANDO VARCHAR(MAX)
      ,@PROCEDENCIA VARCHAR(20)
  BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='CREAR_ENVIO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      
         SELECT @PROCESO=PROCESO, @ENVIO=ENVIO, @TIPORPT=TIPORPT, @FECHA=CONVERT(DATETIME,FECHA),  @REQSEDE=CAST(CASE WHEN ISNUMERIC(REQSEDE)=1 THEN REQSEDE ELSE CASE WHEN COALESCE(REQSEDE,'')<>'SI' THEN 0 ELSE 1 END END AS BIT), @IDSEDE=IDSEDE, @IDTERCERO=COALESCE(IDTERCERO,''),
                @F_INICIAL=CONVERT(DATETIME,F_INICIAL) ,@F_FINAL=CONVERT(DATETIME,F_FINAL),@CAPITADO=CAST(CAPITADO AS BIT),
                @PORCXC=CAST(PORCXC AS BIT),@IDPLAN=IDPLAN,@CNSCXC=CNSCXC,@N_FACTURA=N_FACTURA,@CODSERVICIO=CODSERVICIO,
                @CODMEDICA=CODMEDICA     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         PROCESO VARCHAR(10)    '$.PROCESO',
         ENVIO VARCHAR(6)       '$.ENVIO',
         TIPORPT VARCHAR(20)    '$.TIPORPT',
         FECHA DATE             '$.FECHA',
         REQSEDE VARCHAR(10)    '$.REQSEDE',
         IDSEDE VARCHAR(6)      '$.IDSEDE',
         IDTERCERO VARCHAR(20)  '$.IDTERCERO',
         F_INICIAL DATE         '$.F_INICIAL',
         F_FINAL DATE           '$.F_FINAL',
         CAPITADO VARCHAR(10)   '$.CAPITADO',
         PORCXC VARCHAR(10)     '$.PORCXC',
         IDPLAN VARCHAR(6)      '$.IDPLAN',
         CNSCXC VARCHAR(20)     '$.CNSCXC',
         N_FACTURA VARCHAR(20)  '$.N_FACTURA',
         CODSERVICIO VARCHAR(20)'$.CODSERVICIO',
         CODMEDICA VARCHAR(20)  '$.CODMEDICA'      
         )
      PRINT '@PROCESO='+@PROCESO
      SELECT @IDSEDEF=COALESCE(LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL'))),'01')
      IF @PROCESO='ADD'
      BEGIN
         IF DBO.FNK_VALORVARIABLE('NUMENVIORIPS_AUT')='SI'
         BEGIN
		      PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
            SELECT @ENVIO=''
		      EXEC SPK_GENCONSECUTIVO '01',@IDSEDEF, '@RIPS', @ENVIO OUTPUT  
            PRINT '@ENVIO ANTERS ='+COALESCE(@ENVIO,'')  
		      SELECT @ENVIO = REPLACE(SPACE(6 - LEN(@ENVIO))+LTRIM(RTRIM(@ENVIO)),SPACE(1),0)
		      PRINT '@ENVIO='+COALESCE(@ENVIO,'')            
         END
         BEGIN TRY           
               INSERT INTO RIPS(ENVIO, ENVIADO, FECHAENVIO, IDTERCERO, ITEM, CAPITADO, FECHAINICIAL, MASIVA, FECHAFINAL, N_FACTURA, FECHAFAC,
                                 PORIPSASIGNADA, IDIPS, PORNIVELES, NIVEL1, NIVEL2, NIVEL3, NIVEL4, IDPLAN,  IDVALIDADOR, PORCXC, CNSCXC, 
                                 ESTADO, PYP, TIPORPT, RPTGLO, USUARIO, FECHA, USUCIERRA, FCIERRA, OBS, CODSERVICIO, CODMEDICAMENTO, 
                                 MSEDE, IDSEDE, MFACT)    
               SELECT @ENVIO, 'N', @FECHA, @IDTERCERO, 0, @CAPITADO,@F_INICIAL, 0, @F_FINAL,COALESCE(@N_FACTURA,''), NULL, 0, 
                     '', 0, 0, 0, 0, 0, @IDPLAN,  'OTROS', @PORCXC, @CNSCXC, '01', 0, @TIPORPT, 
                     0, @USUARIO, DBO.FNK_GETDATE(), NULL, NULL, '',@CODSERVICIO,@CODMEDICA, @REQSEDE, @IDSEDE, 0
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH

         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN
         END
      END
      ELSE
      BEGIN
         IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO AND ESTADO='01')
         BEGIN
            SELECT 'KO' OK, 'Risp ya Generados, No se Permiten Cambios' ERROR
            RETURN            
         END
         UPDATE RIPS SET FECHAENVIO=@FECHA, IDTERCERO=@IDTERCERO,CAPITADO=@CAPITADO, FECHAINICIAL=@F_INICIAL,FECHAFINAL=@F_FINAL,
                IDPLAN=@IDPLAN,N_FACTURA=@N_FACTURA, PORCXC=@PORCXC, CNSCXC=@CNSCXC, CODSERVICIO=@CODSERVICIO, CODMEDICAMENTO=@CODMEDICA, MSEDE=@REQSEDE,
                IDSEDE=@IDSEDE,TIPORPT=@TIPORPT
         WHERE ENVIO=@ENVIO
      END
      IF @PORCXC= 1 AND COALESCE(@CNSCXC,'')<>''
      BEGIN
         BEGIN TRY  
		      PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
            SELECT @CNSRPDX=''
		      EXEC SPK_GENCONSECUTIVO '01',@IDSEDEF, '@RPDX', @CNSRPDX OUTPUT  
		      SELECT @CNSRPDX = @IDSEDEF+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		      PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'') 
         
            DELETE RIPSD WHERE ENVIO=@ENVIO

            INSERT INTO RPDX( CNS, ID1, IDTERCERO, ID2, ID3, ID4, ID5) 
            SELECT @CNSRPDX,@ENVIO,@IDTERCERO,FCXCD.N_FACTURA,COALESCE(FTR.NOREFERENCIA,''), FTR.PROCEDENCIA, FTR.CNSFCT 
            FROM FCXCD, FTR 
            WHERE FCXCD.CNSCXC = @CNSCXC
            AND FCXCD.N_FACTURA = FTR.N_FACTURA  
            AND NOT EXISTS(SELECT 1 FROM RIPSD 
                     WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO 
                     AND RIPSD.N_FACTURA=FCXCD.N_FACTURA
                     ) ORDER BY FTR.CNSFCT

            INSERT INTO RIPSD(ENVIO, IDTERCERO, NOITEM, NOADMISION, N_FACTURA, PROCEDENCIA) 
            SELECT ID1, IDTERCERO, ROW_NUMBER() OVER(ORDER  BY ID5) + 0, ID3, ID2, ID4 
            FROM RPDX WHERE CNS =@CNSRPDX

         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      IF @CAPITADO=1
      BEGIN
         BEGIN TRY           
            EXEC SPK_RIPS_QX @ENVIO,@IDTERCERO,@N_FACTURA,@IDPLAN, 0                  
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@ENVIO ENVIO
      RETURN 
   END   
   IF @METODO='PREVAL_ENVIO'     
   BEGIN         
      SELECT @ENVIO=ENVIO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         ENVIO VARCHAR(6) '$.ENVIO'
            ) 
      
      IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO)
      BEGIN
         SELECT 'KO','Envio no encontrado'error
         RETURN
      END
      SELECT @IDTERCERO=IDTERCERO,@CAPITADO=CAPITADO,@PORCXC=PORCXC
      FROM RIPS WHERE ENVIO=@ENVIO

      IF @PORCXC=1
      BEGIN
         IF COALESCE(@IDSEDEF,'')=''
         BEGIN
            SELECT @IDSEDEF= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO            
         END
		   PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDEF,'SIN SEDE')   
         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO '01',@IDSEDEF, '@RPDX', @CNSRPDX OUTPUT  
		   SELECT @CNSRPDX = @IDSEDEF+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'') 
         EXEC SPK_VALIDA_RIPS @CNSRPDX,@ENVIO,@IDTERCERO
         IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX)
         BEGIN
            INSERT INTO @TBLERRORES
            SELECT STRINGGRANDE2 FROM RPDX WHERE CNS=@CNSRPDX

            SELECT 'KO' OK, ERROR FROM @TBLERRORES
            RETURN

         END
         IF DBO.FNK_VALORVARIABLE('MFORMATORIPSMED') ='SI'
         BEGIN
            DECLARE @TIPORIPS VARCHAR(10)
            SELECT @TIPORIPS=PPT.TIPORIPS FROM PPT INNER JOIN RIPS ON PPT.IDTERCERO=RIPS.IDTERCERO AND PPT.IDPLAN=RIPS.IDPLAN 
            WHERE RIPS.ENVIO=@ENVIO 
            IF @TIPORIPS='01' AND EXISTS( SELECT * FROM ( 
                  SELECT FTRD.N_FACTURA, FTRD.N_CUOTA, 
                     CASE WHEN IART.IDARTICULO IS NULL THEN 'SERVICIO' ELSE 'ARTICULO' END AS TIPO, 
                     COALESCE(IART.IDARTICULO,SER.IDSERVICIO) AS CODIGO, 
                     COALESCE(IART.DESCRIPCION,SER.DESCSERVICIO) AS DESCRIPCION, 
                     IART.CODCUM AS CUMA, SER.CODCUM AS CUMS 
                  FROM RIPSD 
                     INNER JOIN FTRD  ON RIPSD.N_FACTURA=FTRD.N_FACTURA 
                     INNER JOIN HPRED ON FTRD.NOPRESTACION=HPRED.NOPRESTACION AND FTRD.NOITEM=HPRED.NOITEM 
                     INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO 
                     LEFT  JOIN IART  ON HPRED.IDARTICULO=IART.IDARTICULO 
                  WHERE RIPSD.ENVIO=@ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
                     AND RIPSD.PROCEDENCIA='SALUD' 
                     AND ISNULL(FTRD.ITFC,0)<>2 
                     AND ISNULL(HPRED.NOCOBRABLE,0)=0 
                     AND ISNULL(SER.MEDICAMENTOS,0)=1 
                     AND SER.CODIGORIPS IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('IDMEDNOPOSRIPS','IDMEDPOSRIPS')) 
            ) AS X 
            WHERE COALESCE(CUMA,CUMS,'')<>'NA' AND COALESCE(CUMA,CUMS,'')<>'NA' AND (COALESCE(CUMA,CUMS,'')='' OR COALESCE(CUMA,CUMS,'') NOT LIKE '%-%')
            )
            BEGIN
               INSERT INTO @TBLERRORES
               SELECT  DISTINCT CODIGO+' -- '+DESCRIPCION+': CODIGO CUM:'+COALESCE(CUMA,CUMS,'')+' - No Valido' FROM ( 
                              SELECT FTRD.N_FACTURA, FTRD.N_CUOTA, 
                                 CASE WHEN IART.IDARTICULO IS NULL THEN 'SERVICIO' ELSE 'ARTICULO' END AS TIPO, 
                                 COALESCE(IART.IDARTICULO,SER.IDSERVICIO) AS CODIGO, 
                                 COALESCE(IART.DESCRIPCION,SER.DESCSERVICIO) AS DESCRIPCION, 
                                 IART.CODCUM AS CUMA, SER.CODCUM AS CUMS 
                              FROM RIPSD 
                                 INNER JOIN FTRD  ON RIPSD.N_FACTURA=FTRD.N_FACTURA 
                                 INNER JOIN HPRED ON FTRD.NOPRESTACION=HPRED.NOPRESTACION AND FTRD.NOITEM=HPRED.NOITEM 
                                 INNER JOIN SER   ON HPRED.IDSERVICIO=SER.IDSERVICIO 
                                 LEFT  JOIN IART  ON HPRED.IDARTICULO=IART.IDARTICULO 
                              WHERE RIPSD.ENVIO=@ENVIO AND RIPSD.IDTERCERO=@IDTERCERO
                                 AND RIPSD.PROCEDENCIA='SALUD' 
                                 AND ISNULL(FTRD.ITFC,0)<>2 
                                 AND ISNULL(HPRED.NOCOBRABLE,0)=0 
                                 AND ISNULL(SER.MEDICAMENTOS,0)=1 
                                 AND SER.CODIGORIPS IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('IDMEDNOPOSRIPS','IDMEDPOSRIPS')) 
                        ) AS X 
                        WHERE COALESCE(CUMA,CUMS,'')<>'NA' AND COALESCE(CUMA,CUMS,'')<>'NA' AND (COALESCE(CUMA,CUMS,'')='' OR COALESCE(CUMA,CUMS,'') NOT LIKE '%-%')
                  IF(SELECT COUNT(*) FROM @TBLERRORES)>0
                  BEGIN
                     SELECT 'KO' KO
                     SELECT  ERROR FROM @TBLERRORES
                     RETURN
                  END
            END
         END
      END
      ELSE
      BEGIN
         IF NOT EXISTS(SELECT * FROM RIPSD WHERE ENVIO=@ENVIO)
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Relacion de servicios de la Factura Asociada al Envio'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='GENERAR_ENVIO'     
   BEGIN         
      SELECT @ENVIO=ENVIO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         ENVIO VARCHAR(6) '$.ENVIO'
            ) 
      
      IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO)
      BEGIN
         SELECT 'KO','Envio no encontrado'error
         RETURN
      END
      SELECT @IDTERCERO=IDTERCERO,@CAPITADO=COALESCE(CAPITADO,0),@F_INICIAL=FECHAINICIAL,
             @F_FINAL=FECHAFINAL,@REQSEDE=MSEDE,@IDSEDEF=IDSEDE,@IDPLAN = IDPLAN,@TIPORPT=TIPORPT
      FROM RIPS WHERE ENVIO=@ENVIO
      IF @REQSEDE=1
      BEGIN
         SELECT @RAZONSOCIAL=TER.RAZONSOCIAL,@NIT=TER.NIT,@IDSGSSS=SED.IDSGSSS 
         FROM SED INNER JOIN TER ON SED.NIT=TER.NIT 
         WHERE IDSEDE=@IDSEDEF        
      END
      ELSE
      BEGIN
         SELECT @RAZONSOCIAL=TER.RAZONSOCIAL,@NIT=TER.NIT,@IDSGSSS=TER.IDALTERNA2 
         FROM TER
         WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') 
      END 


      PRINT 'EMPIEZO A GENERAR LOS RIPS @TIPORPT='+@TIPORPT
      IF @TIPORPT='D'
      BEGIN
         IF @CAPITADO=1
         BEGIN
            PRINT 'CAPITADO'
            BEGIN TRY           
               EXEC SPK_RIPS_CE_F_CAP @ENVIO,@IDTERCERO,@F_INICIAL,@F_FINAL,@IDSGSSS,@RAZONSOCIAL,'NI',@NIT, '', @IDPLAN 
            END TRY
            BEGIN CATCH
               PRINT ' ERORR SPK_RIPS_CE_F_CAP'
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()

               EXEC SPK_RIPS_ELIMINAR @ENVIO,@IDTERCERO

               SELECT 'KO' OK, ERROR FROM @TBLERRORES
            END CATCH
            BEGIN TRY           
               EXEC SPK_RIPS_CXC_ASIS_CAP @ENVIO,@IDTERCERO,@IDSGSSS,@RAZONSOCIAL,@NIT                    
            END TRY
            BEGIN CATCH
               PRINT ' ERROR  SPK_RIPS_CXC_ASIS_CAP '
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()

               EXEC SPK_RIPS_ELIMINAR @ENVIO,@IDTERCERO
               SELECT 'KO' OK, ERROR FROM @TBLERRORES
               RETURN
            END CATCH
         END
         ELSE
         BEGIN
            PRINT 'POR CXC'
            BEGIN TRY      
               PRINT 'SPK_RIPS_CE_F'
               EXEC SPK_RIPS_CE_F @ENVIO,@IDTERCERO,@F_INICIAL,@F_FINAL,@IDSGSSS,@RAZONSOCIAL,'NI',@NIT, '', @IDPLAN                 
            END TRY
            BEGIN CATCH
               PRINT ' ERORR SPK_RIPS_CE_F'
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()

               EXEC SPK_RIPS_ELIMINAR @ENVIO,@IDTERCERO

               SELECT 'KO' OK, ERROR FROM @TBLERRORES
               RETURN
            END CATCH
            BEGIN TRY  
               PRINT ' SPK_RIPS_CXC_ASIS'
               EXEC SPK_RIPS_CXC_ASIS @ENVIO,@IDSGSSS,@RAZONSOCIAL,@NIT,@IDTERCERO                 
            END TRY
            BEGIN CATCH
               PRINT ' ERROR  SPK_RIPS_CXC_ASIS'
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()

               EXEC SPK_RIPS_ELIMINAR @ENVIO,@IDTERCERO
               SELECT 'KO' OK, ERROR FROM @TBLERRORES
               RETURN
            END CATCH
            EXEC DBO.SPK_RIPS_QX_VAL @ENVIO,@IDTERCERO
            EXEC DBO.SPK_RIPS_AJUS_VAL @ENVIO,@IDTERCERO
  
         END

         DELETE RRIPS_CT WHERE ENVIO=@ENVIO

         SELECT @COUNT_AC = COUNT(*) FROM RRIPS_AC WHERE ENVIO = @ENVIO
         SELECT @COUNT_US = COUNT(*) FROM RRIPS_US WHERE ENVIO = @ENVIO
         SELECT @COUNT_AU = COUNT(*) FROM RRIPS_AU WHERE ENVIO = @ENVIO
         SELECT @COUNT_AF = COUNT(*) FROM RRIPS_AF WHERE ENVIO = @ENVIO 
         SELECT @COUNT_AD = COUNT(*) FROM RRIPS_AD WHERE ENVIO = @ENVIO 
         SELECT @COUNT_AH = COUNT(*) FROM RRIPS_AH WHERE ENVIO = @ENVIO 
         SELECT @COUNT_AP = COUNT(*) FROM RRIPS_AP WHERE ENVIO = @ENVIO 
         SELECT @COUNT_AM = COUNT(*) FROM RRIPS_AM WHERE ENVIO = @ENVIO 
         SELECT @COUNT_AN = COUNT(*) FROM RRIPS_AN WHERE ENVIO = @ENVIO 
         SELECT @COUNT_AT = COUNT(*) FROM RRIPS_AT WHERE ENVIO = @ENVIO 


         INSERT INTO RRIPS_CT(ENVIO,IDTERCERO,IDPRESTADOR,FECHAREMISION,CODIGOARCHIVO,TOTALREGISTROS)
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AC'+@ENVIO,@COUNT_AC
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'US'+@ENVIO,@COUNT_US
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AU'+@ENVIO,@COUNT_AU
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AF'+@ENVIO,@COUNT_AF
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AD'+@ENVIO,@COUNT_AD
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AH'+@ENVIO,@COUNT_AH
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AP'+@ENVIO,@COUNT_AP
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AM'+@ENVIO,@COUNT_AM
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AN'+@ENVIO,@COUNT_AN
         UNION ALL
         SELECT @ENVIO,@IDTERCERO,LEFT(@IDSGSSS,12),DBO.FNK_FECHA_SIN_MLS(GETDATE()),'AT'+@ENVIO,@COUNT_AT
  
         DELETE FROM RRIPS_CT WHERE (TOTALREGISTROS=0 OR TOTALREGISTROS IS NULL ) AND ENVIO = @ENVIO 
      END
      ELSE
      BEGIN
         PRINT 'Voy para lo Consolidados'
         BEGIN TRY           
            EXEC SPK_RIPS_TOTAL @ENVIO,@IDTERCERO,@IDSGSSS,'NI',@NIT,@RAZONSOCIAL,@ENVIO,1                  
         END TRY
         BEGIN CATCH
               PRINT ' ERROR  SPK_RIPS_TOTAL'
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
               SELECT 'KO' OK, ERROR FROM @TBLERRORES
               RETURN
         END CATCH
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      ELSE 
      BEGIN
         PRINT 'CIERRO ENVIO'
         UPDATE RIPS SET ESTADO='02' WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO
         DECLARE @VLR_ARCHIVOAC DECIMAL(14,2)
         DECLARE @VLR_ARCHIVOAP DECIMAL(14,2)
         DECLARE @VLR_ARCHIVOAT DECIMAL(14,2)
         DECLARE @VLR_ARCHIVOAM DECIMAL(14,2)

         SELECT @VLR_ARCHIVOAC=SUM(CONVERT(DECIMAL(14,2),COALESCE(VALORNETO,'0'))) FROM RRIPS_AC WHERE ENVIO =@ENVIO 
         SELECT @VLR_ARCHIVOAP=SUM(CONVERT(DECIMAL(14,2),COALESCE(VALORPROCED,'0'))) FROM RRIPS_AP WHERE ENVIO=@ENVIO
         SELECT @VLR_ARCHIVOAT=SUM(CONVERT(DECIMAL(14,2),COALESCE(VLRTOTMAT,'0'))) FROM RRIPS_AT WHERE ENVIO =@ENVIO
         SELECT @VLR_ARCHIVOAM=SUM(CONVERT(DECIMAL(14,2),COALESCE(VALORTOTMEDI,'0'))) FROM RRIPS_AM WHERE ENVIO = @ENVIO

         UPDATE RIPS SET VLRTOTAL_AC=COALESCE(@VLR_ARCHIVOAC,0),VLRTOTAL_AP=COALESCE(@VLR_ARCHIVOAP,0),
                         VLRTOTAL_AT=COALESCE(@VLR_ARCHIVOAT,0),VLRTOTAL_AM=COALESCE(@VLR_ARCHIVOAM,0)
         WHERE ENVIO=@ENVIO

      END
      SELECT 'OK' OK,@ENVIO ENVIO, COALESCE(@VLR_ARCHIVOAC,0) VLRTOTAL_AC ,COALESCE(@VLR_ARCHIVOAP,0) VLRTOTAL_AP,COALESCE(@VLR_ARCHIVOAT,0) VLRTOTAL_AT,COALESCE(@VLR_ARCHIVOAM,0) VLRTOTAL_AM
      RETURN 
   END
   IF @METODO='DESHACER_ENVIO'     
   BEGIN         
      SELECT @ENVIO=ENVIO, @IDTERCERO=IDTERCERO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         ENVIO VARCHAR(6) '$.ENVIO',
         IDTERCERO VARCHAR(20) '$.IDTERCERO'
            )           
       
      IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND ESTADO='02')
      BEGIN
         SELECT 'KO'OK,'Envio no Encontrado o no esta generado' ERROR 
         RETURN
      END
      BEGIN TRY           
           EXEC SPK_RIPS_ELIMINAR @ENVIO,@IDTERCERO                 
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@ENVIO ENVIO
      RETURN 
   END 

   IF @METODO='TRAEFACTU_ENVIO'     
   BEGIN         
      SELECT @ENVIO=ENVIO, @IDTERCERO=IDTERCERO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         ENVIO VARCHAR(6) '$.ENVIO',
         IDTERCERO VARCHAR(20) '$.IDTERCERO'
            )           
       
      IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO AND ESTADO<>'02')
      BEGIN
         SELECT 'KO'OK,'Envio no Encontrado o no esta generado' ERROR 
         RETURN
      END
      SELECT @PORCXC=PORCXC,@CNSCXC=CNSCXC,@IDSEDEF=CASE WHEN MSEDE=1 THEN IDSEDE ELSE DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL') END 
      FROM RIPS WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO

      IF @PORCXC= 1 AND COALESCE(@CNSCXC,'')<>''
      BEGIN TRY  
		   PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO '01',@IDSEDEF, '@RPDX', @CNSRPDX OUTPUT  
		   SELECT @CNSRPDX = @IDSEDEF+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'') 
         
         DELETE RIPSD WHERE ENVIO=@ENVIO

         INSERT INTO RPDX( CNS, ID1, IDTERCERO, ID2, ID3, ID4, ID5) 
         SELECT @CNSRPDX,@ENVIO,@IDTERCERO,FCXCD.N_FACTURA,COALESCE(FTR.NOREFERENCIA,''), FTR.PROCEDENCIA, FTR.CNSFCT 
         FROM FCXCD, FTR 
         WHERE FCXCD.CNSCXC = @CNSCXC
         AND FCXCD.N_FACTURA = FTR.N_FACTURA  
         AND NOT EXISTS(SELECT 1 FROM RIPSD 
                  WHERE ENVIO=@ENVIO AND IDTERCERO=@IDTERCERO 
                  AND RIPSD.N_FACTURA=FCXCD.N_FACTURA
                  ) ORDER BY FTR.CNSFCT

         INSERT INTO RIPSD(ENVIO, IDTERCERO, NOITEM, NOADMISION, N_FACTURA, PROCEDENCIA) 
         SELECT ID1, IDTERCERO, ROW_NUMBER() OVER(ORDER  BY ID5) + 0, ID3, ID2, ID4 
         FROM RPDX WHERE CNS =@CNSRPDX 
           EXEC SPK_RIPS_ELIMINAR @ENVIO,@IDTERCERO                 
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH

      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@ENVIO ENVIO
      RETURN          
   END 
   IF @METODO='ENVIAR_RIPS'     
   BEGIN   
     SELECT @ENVIO=ENVIO, @IDTERCERO=IDTERCERO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         ENVIO VARCHAR(6) '$.ENVIO',
         IDTERCERO VARCHAR(20) '$.IDTERCERO'
            )           
       
      IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO AND IDTERCERO=COALESCE(@IDTERCERO,'') AND ESTADO='02')
      BEGIN
         SELECT 'KO'OK,'Envio no Encontrado o no esta generado' ERROR 
         RETURN
      END  
      DECLARE @VL_ENTERO VARCHAR(20)=DBO.FNK_VALORVARIABLE('RIPS_VALORENTERO')

      SELECT @ENVIO_CT=COALESCE(DBO.FNK_GEN_PLANOS_RIPS_CT(@ENVIO),'')
      SELECT 'OK' OK,@ENVIO_CT ENVIO_CT
      PRINT 'Devuelvo los archivos'     
      PRINT 'ARCHIVO @ENVIO_AC'

      SELECT REPLACE(NUMFACTURA+','+IDPRESTADOR+','+TIPO_DOC+','+IDUSUARIO+','+CONVERT(VARCHAR,FECHACONSULTA,103)
      +','+COALESCE(NUMAUT,'')+','+COALESCE(IDCONSULTA,'')+','+COALESCE(FINCONSULTA,'')+','+COALESCE(CAUSAEXT,'')+','
      +RTRIM(COALESCE(IDDXPPAL,''))+','+RTRIM(COALESCE(IDDXREL1,''))+','+RTRIM(COALESCE(IDDXREL2,''))+','+RTRIM(COALESCE(IDDXREL3,''))+','+RTRIM(COALESCE(TIPODX,'')) +','+
      CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,COALESCE(VALORCONSULTA,0))AS VARCHAR(20)) ELSE CAST(COALESCE(VALORCONSULTA,'0') AS VARCHAR(20)) END +','+
      CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,COALESCE(VALORCUOTAM,0)) AS VARCHAR(20)) ELSE CAST(COALESCE(VALORCUOTAM,'0') AS VARCHAR(20)) END+','+
	  CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,COALESCE(VALORNETO,0))AS VARCHAR(20)) ELSE CAST(COALESCE(VALORNETO,0) AS VARCHAR(20)) END 
	  ,CHAR(13),'')+CHAR(13)+CHAR(10) PLANO
      FROM RRIPS_AC
      WHERE ENVIO=@ENVIO

      PRINT 'ARCHIVO @ENVIO_AP'
      SELECT REPLACE(NUMFACTURA+','+IDPRESTADOR+','+TIPO_DOC+','+IDUSUARIO+','+CONVERT(VARCHAR,FECHAPROCEDIMIENTO,103)+','+COALESCE(NUMAUT,'')+','+LTRIM(RTRIM(COALESCE(IDPROCEDIMIENTO,'')))+','+COALESCE(AMBITO,'2')+','
      +COALESCE(FINPROCEDIMIENTO,'')+','+COALESCE(PERSONALA,'1')+','+COALESCE(DXPPAL,'')+','+COALESCE(DXREL,'')+','+COALESCE(COMPLICACION,'')
      +','+COALESCE(ACTOQ,'1')+','+CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,CONVERT(DECIMAL(14,2),VALORPROCED)) AS VARCHAR(20)) ELSE VALORPROCED END,CHAR(13),'')+CHAR(13)+CHAR(10) PLANO
      FROM RRIPS_AP WHERE ENVIO=@ENVIO

      PRINT 'ARCHIVO @ENVIO_AT'
      SELECT REPLACE(NUMFACTURA+','+IDPRESTADOR+','+TIPO_DOC+','+IDUSUARIO+','+COALESCE(NUMAUT,'')+','+CAST(TIPOSERVICIO AS VARCHAR(2))+','+IDSERVICIO+','+
      COALESCE(DESCRIPCIONSER,'')+','+CAST(CONVERT(INT,CONVERT(DECIMAL(14,2),COALESCE(CANTIDAD,'0.00'))) AS VARCHAR(4))+','+CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,CONVERT(DECIMAL(14,2),COALESCE(VLRUNITMAT,'0.00'))) AS VARCHAR(20))  ELSE COALESCE(VLRUNITMAT,'0') END +','+
      CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,CONVERT(DECIMAL(14,2),COALESCE(VLRTOTMAT,'0.00'))) AS VARCHAR(20)) ELSE  COALESCE(VLRTOTMAT,'0') END ,CHAR(13),'')+CHAR(13)+CHAR(10) PLANO
	   FROM RRIPS_AT WHERE ENVIO=@ENVIO
	  
      PRINT 'ARCHIVO @ENVIO_AM'
	   SELECT REPLACE(NUMFACTURA+','+IDPRESTADOR+','+TIPO_DOC+','+IDUSUARIO+','+COALESCE(NUMAUT,'')+','+IDMEDICAMENTO+','+TIPOMEDICAMENTO+','+
			  NOMBREMEDI+','+COALESCE(FORMAFARMA,'')+','+COALESCE(CONCMEDI,'')+','+COALESCE(UMEDMEDI,'')+','+CAST(NUMUNIDADES AS VARCHAR(4))+','+
			  CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,COALESCE(VALORUNIMEDI,0))AS VARCHAR(20)) ELSE CAST(COALESCE(VALORUNIMEDI,'0') AS VARCHAR(20)) END +','+
              CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,COALESCE(VALORTOTMEDI,0)) AS VARCHAR(20)) ELSE CAST(COALESCE(VALORTOTMEDI,'0') AS VARCHAR(20)) END,CHAR(13),'')+CHAR(13)+CHAR(10) PLANO
	   FROM RRIPS_AM 
	   WHERE ENVIO=@ENVIO

      PRINT 'ARCHIVO @ENVIO_AN'
	   SELECT  REPLACE(NUMFACTURA+','+IDPRESTADOR+','+TIPOIDM+','+IDMADRE+','+CONVERT(VARCHAR,FNACIMIENTO,103)+','+LEFT(CONVERT(VARCHAR,FNACIMIENTO,108),5)+','+COALESCE(EDADGEST,'')+','+COALESCE(CPRENATAL,'')+','+
			   COALESCE(SEXO,'')+','+CAST(PESO AS VARCHAR(4))+','+CAST(COALESCE(DXRN,'') AS VARCHAR(4))+','+COALESCE(CBM,'')+','+COALESCE(CONVERT(VARCHAR,FMUERTE,103),'')+','
            +LEFT(COALESCE(CONVERT(VARCHAR,FMUERTE,108),''),5),CHAR(13),'')+CHAR(13)+CHAR(10)  PLANO
	   FROM RRIPS_AN
	   WHERE ENVIO=@ENVIO


      PRINT 'ARCHIVO @ENVIO_AH'

      SELECT REPLACE(NUMFACTURA+','+IDPRESTADOR+','+TIPO_DOC+','+IDUSUARIO+','+COALESCE(VIAINGRESO,'')+','+CONVERT(VARCHAR,FECHAINGRESO,103)+','+
	   LEFT(CONVERT(VARCHAR,FECHAINGRESO,108),5)+','+COALESCE(NUMAUT,'')+','+CAUSAEXT+','+COALESCE(DXINGRESO,'')+','+
	   COALESCE(DXEGRESO,'')+','+COALESCE(DXREL1,'')+','+COALESCE(DXREL2,'')+','+COALESCE(DXREL3,'')+','+COALESCE(DXCOMP,'')+','+
	   COALESCE(ESTSALIDA,'')+','+COALESCE(DXCBM,'')+','+CONVERT(VARCHAR,FECHAEGRESO,103)+','+
      LEFT(CONVERT(VARCHAR,FECHAEGRESO,108),5),CHAR(32),'')+CHAR(13)+CHAR(10) PLANO
	   FROM RRIPS_AH WHERE ENVIO=@ENVIO


      PRINT 'ARCHIVO @ENVIO_AU'

		SELECT REPLACE( NUMFACTURA+','+IDPRESTADOR+','+TIPO_DOC+','+IDUSUARIO+','+COALESCE(CONVERT(VARCHAR,FECHAINGRESO,103),'')+','+
             LEFT(COALESCE(CONVERT(VARCHAR,FECHAINGRESO,108),''),5)+','+COALESCE(NUMAUT,'')+','+COALESCE(CAUSAEXT,'')+','+
             COALESCE(DXSALIDA,'')+','+COALESCE(IDDXREL1,'')+','+COALESCE(IDDXREL2,'')+','+ COALESCE(IDDXREL3,'')+','+
             COALESCE(DESTINOSALIDA,'')+','+COALESCE(ESTSALIDA,'')+','+COALESCE(CBMU,'')+','+COALESCE(CONVERT(VARCHAR,FECHASALIDA,103),'')+','+
             LEFT(COALESCE(CONVERT(VARCHAR,FECHASALIDA,108),''),5),CHAR(13),'')+CHAR(13)+CHAR(10)  PLANO
		FROM RRIPS_AU ES
		WHERE ENVIO=@ENVIO


      PRINT 'ARCHIVO @ENVIO_AF'
	   SELECT REPLACE(IDPRESTADOR+','+RAZONSOCIAL+','+TIPO_ID+','+NUMIDENTIFICACION+','+NUMFACTURA+','+CONVERT(VARCHAR,FECHAEXPEDICION,103)+','+
	   CONVERT(VARCHAR,FECHAINICIO,103)+','+CONVERT(VARCHAR,FECHAFINAL,103)+','+COALESCE(CODENTIDADM,'')+','+LTRIM(RTRIM(NOMBREENTIDADM))+','+
	   COALESCE(NUMEROCONTRATO,'')+','+COALESCE(PLANBENEFICIOS,'')+','+COALESCE(NUMPOLIZA,'')+','+
	   CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN CAST(CONVERT(INT,CONVERT(DECIMAL(14,2),VALORTOTALCOPAGO)) AS VARCHAR(20)) ELSE  COALESCE(VALORTOTALCOPAGO,'0') END +','+
      CAST(COALESCE(VALORCOMISION,'0')AS VARCHAR(20))+','+
	  CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN  CAST(CONVERT(BIGINT,CONVERT(DECIMAL(14,2),VALORTOTALDESC)) AS VARCHAR(20)) ELSE COALESCE(VALORTOTALDESC,'0')END +','+
      CASE WHEN COALESCE(@VL_ENTERO,'')='SI' THEN  CAST(CONVERT(BIGINT,CONVERT(DECIMAL(14,2),VALORNETO,0)) AS VARCHAR(20)) ELSE COALESCE(VALORNETO,'0') END,CHAR(13),'')+CHAR(13)+CHAR(10) PLANO
	   FROM RRIPS_AF 
      WHERE ENVIO=@ENVIO


      PRINT 'ARCHIVO @ENVIO_US'

	   SELECT REPLACE( TIPO_DOC+','+IDUSUARIO+','+CODENTIDADM+','+TIPOUSUARIO+','+COALESCE(PAPELLIDO,'')+','+COALESCE(SAPELLIDO,'')+','+
			   COALESCE(PNOMBRE,'')+','+COALESCE(SNOMBRE,'')+','+CAST(EDAD AS VARCHAR(3))+','+CAST(UNMEDIDA AS VARCHAR(1))+','+
			   SEXO+','+COALESCE(DEPHABITUAL,'')+','+COALESCE(MUNHABITUAL,'')+','+ZONAHABITUAL,CHAR(13),'')+CHAR(13)+CHAR(10)  PLANO
	   FROM RRIPS_US 
      WHERE ENVIO=@ENVIO
 

      PRINT 'ARCHIVO @ENVIO_AD'
      SELECT REPLACE( NUMFACTURA+','+IDPRESTADOR+','+CODCONCEPTO+','+CAST(CONVERT(INT,IIF(ISNUMERIC(CANTIDAD)=1,CANTIDAD,0))AS VARCHAR(20))+','+
      CAST(CONVERT(bigint,IIF(ISNUMERIC(VALORUNITARIO)=1,COALESCE(VALORUNITARIO,0),0)) AS VARCHAR(20))+','+
      CAST(CONVERT(bigint,IIF(ISNUMERIC(TOTALCONCEPTO)=1,COALESCE(TOTALCONCEPTO,0),0)) AS VARCHAR(20)),CHAR(13),'')+CHAR(13)+CHAR(10) PLANO
      FROM RRIPS_AD 
      WHERE ENVIO=@ENVIO


      PRINT 'ARCHIVO @ENVIO_CT'

      RETURN 
   END 
   IF @METODO='CONDICIONES_ENVIO'     
   BEGIN         
      SELECT @ENVIO=ENVIO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         ENVIO VARCHAR(6) '$.ENVIO'
            ) 
      SELECT @IDTERCERO=IDTERCERO,@N_FACTURA=N_FACTURA,@IDPLAN=IDPLAN FROM RIPS WHERE ENVIO=@ENVIO
      IF NOT EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO)
      BEGIN
         SELECT 'KO','Envio no encontrado'error
         RETURN
      END

      BEGIN TRY           
         EXEC SPK_RIPS_QX @ENVIO,@IDTERCERO,@N_FACTURA,@IDPLAN, 0                  
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='CRUD_RIPSD'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO,@ENVIO=ENVIO,@IDTERCERO=IDTERCERO,@NOADMISION=NOADMISION,@N_FACTURA=N_FACTURA,@PROCEDENCIA=PROCEDENCIA,@IDSEDE=IDSEDE,
             @ITEMRPDX=NOITEM
      FROM   OPENJSON (@DATOS)
      WITH   ( 
      PROCESO  VARCHAR(20)   '$.PROCESO', 
      ENVIO  VARCHAR(20)   '$.ENVIO', 
      IDTERCERO  VARCHAR(20)   '$.IDTERCERO',
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA',
      NOADMISION  VARCHAR(20)   '$.NOADMISION',
      PROCEDENCIA  VARCHAR(20)   '$.PROCEDENCIA',
      IDSEDE VARCHAR(5) '$.IDSEDE',
      NOITEM  SMALLINT   '$.NOITEM'
      )  
      IF EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO AND ESTADO='01' AND PORCXC=0 AND CAPITADO=0 AND TIPORPT='D')
      BEGIN
         IF @PROCESO='Nuevo'
         BEGIN
            SELECT @ITEMRPDX=COALESCE(MAX(NOITEM),0)+1 FROM RIPSD WHERE ENVIO=@ENVIO
            INSERT INTO RIPSD(ENVIO,IDTERCERO,NOITEM,NOADMISION,N_FACTURA,PROCEDENCIA,IDSEDE)
            SELECT @ENVIO,@IDTERCERO,@ITEMRPDX,@NOADMISION,@N_FACTURA,@PROCEDENCIA,@IDSEDE
         END
         IF @PROCESO='Editar'
         BEGIN
            UPDATE RIPSD SET NOADMISION=@NOADMISION,N_FACTURA=@N_FACTURA,PROCEDENCIA=@PROCEDENCIA,IDSEDE=@IDSEDE  WHERE ENVIO=@ENVIO AND NOITEM=@ITEMRPDX
         END
         IF @PROCESO='Borrar'
         BEGIN
            DELETE RIPSD WHERE ENVIO=@ENVIO AND NOITEM=@ITEMRPDX
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Envio no encontrado Verfique e Intente de nuevo '
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END
   IF @METODO='CARGAR_RIPSD'     
   BEGIN         
      DECLARE @N_FACTU VARCHAR(20)
      DECLARE @NROLINEAS INT
      DECLARE @INDICE    SMALLINT
      DECLARE @ERROR VARCHAR(120)

      SELECT  @NROLINEAS=COUNT(*)
	   FROM OPENJSON(@PARAMETROS, '$.LINEAS') 

      IF @NROLINEAS>0
      BEGIN

		   DECLARE @LINEA AS VARCHAR(MAX)
		   DECLARE @TABLA AS TABLE(
			   ITEM INT IDENTITY(1,1),
			   VALOR VARCHAR(MAX)
		   )

		   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		   WHERE USUSU.USUARIO=@USUARIO

		   PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT  
		   SELECT @CNSRPDX = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'') 

         SELECT @INDICE=0
		   DECLARE SUBIR_CURSOR CURSOR FOR   
	      SELECT VALUE 
		   FROM OPENJSON(@PARAMETROS, '$.LINEAS')		  
		   OPEN SUBIR_CURSOR  
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   WHILE @@FETCH_STATUS = 0  
		   BEGIN
			   DELETE FROM @TABLA WHERE 1=1

			   INSERT INTO @TABLA(VALOR)
			   SELECT VALUE FROM string_split(@LINEA,',')
            
            SELECT @N_FACTU=VALOR FROM @TABLA WHERE ITEM=1+@INDICE


            SET @ERROR=''
            IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTU AND ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')
            BEGIN
               SET @ERROR += 'Factura no existe o se encuentra anulada, no se puede procesar'
            END  
            IF COALESCE(@ERROR,'')=''
            BEGIN
               INSERT INTO RPDX(CNS,ID1,IDTERCERO,ID2,ID3,ID4,STRINGGRANDE2,CANTIDAD)
               SELECT @CNSRPDX,@N_FACTU,IDTERCERO,NOREFERENCIA,PROCEDENCIA,IDSEDE,@ERROR,CASE WHEN LEN(@ERROR)>1 THEN 1 ELSE 0 END 
               FROM FTR 
               WHERE N_FACTURA=@N_FACTU
            END
            ELSE
            BEGIN 
               INSERT INTO RPDX(CNS,ID1,IDTERCERO,ID2,ID3,ID4,STRINGGRANDE2,CANTIDAD)
               SELECT @CNSRPDX,@N_FACTU,NULL,NULL,NULL,NULL,@ERROR,0
            END
            SET @INDICE +=1
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   END
		  
		   CLOSE SUBIR_CURSOR  
		   DEALLOCATE SUBIR_CURSOR  

         SELECT @NROLINEAS=COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=1


         SELECT 'OK' OK,@CNSRPDX CNSRPDX,@NROLINEAS ERRADOS
         RETURN
      END
   END  
   IF @METODO='PROCE_PLANO'     
   BEGIN         
      SELECT @ENVIO=ENVIO,@CNSRPDX=CNSRPDX      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      ENVIO  VARCHAR(20)   '$.ENVIO',
      CNSRPDX  VARCHAR(20)   '$.CNSRPDX'
      )
      IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX) AND EXISTS(SELECT * FROM RIPS WHERE ENVIO=@ENVIO AND COALESCE(PORCXC,0)=0 AND COALESCE(CAPITADO,0)=0 AND TIPORPT='D' AND ESTADO='01')
      BEGIN
         SELECT @ITEMRPDX=MAX(NOITEM) FROM RIPSD WHERE ENVIO=@ENVIO
         IF @ITEMRPDX IS NULL
         BEGIN
            SELECT @ITEMRPDX=0
         END
         BEGIN TRY           
            INSERT INTO RIPSD(ENVIO,IDTERCERO,NOITEM,N_FACTURA,NOADMISION,PROCEDENCIA,IDSEDE)
            SELECT @ENVIO,IDTERCERO,@ITEMRPDX+ROW_NUMBER() OVER(ORDER  BY ID1  ASC),ID1,ID2,ID3,ID4
            FROM RPDX
            WHERE CNS=@CNSRPDX
            ORDER BY ID1 ASC
            
            DELETE RPDX WHERE CNS=@CNSRPDX
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH 

      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro el envio o no existen datos temporares'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN            
   END  
   IF @METODO='PROCE_PLANO'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSRPDX  VARCHAR(20)   '$.CNSRPDX'
      )
      IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX)
      BEGIN
         DELETE RPDX WHERE CNS=@CNSRPDX 
      END
      SELECT  'OK' OK
      RETURN
   END
   IF @METODO='BORRAR_RIPSD'     
   BEGIN         
      SELECT @ENVIO=ENVIO     
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      ENVIO  VARCHAR(20)   '$.ENVIO'
      )
      IF EXISTS(SELECT * FROM RIPSD WHERE ENVIO=@ENVIO)
      BEGIN
         DELETE RIPSD WHERE ENVIO=@ENVIO
      END
      SELECT  'OK' OK
      RETURN
   END
END



