CREATE OR ALTER PROCEDURE DBO.SPQ_RPT_NOMINA @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@CNSNIEPE VARCHAR(20)              ,@CNSPAGO  VARCHAR(20)           ,@NUMDOC    VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='COLILLAS'     
   BEGIN  
      PRINT 'INGRESO AL DATO'
      SELECT @CNSNIEPE=CNSNIEPE,@CNSPAGO=CNSPAGO,@NUMDOC=NUMDOC       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSNIEPE VARCHAR(20) '$.CNSNIEPE',
        CNSPAGO VARCHAR(20) '$.CNSPAGO',
        NUMDOC VARCHAR(20) '$.NUMDOC'
       )           
      IF EXISTS(SELECT * FROM NIEPE WHERE CNSNIEPE=@CNSNIEPE AND CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC)
      BEGIN
         SELECT  'OK' OK
         SELECT NIEPE.CODNOMINA,NIEPE.CNSPAGO,NIEPE.NOMBRE_PERIODO,NOMBRE_AREA,NOMBRE_CCOSTO,TER.NIT,TER.RAZONSOCIAL,
         NIEPE.DETALLE_CARGO,NIEPE.BASICO,NIEPE.VALOR_INGRESOS,VALOR_EGRESOS,NIEPE.VALOR_APORTES,NIEPE.VALOR_NETO
         FROM NIEPE INNER JOIN NPER ON NIEPE.CNSPAGO=NPER.CNSPAGO
                    INNER JOIN NPPAG ON NPER.CODPPAG=NPPAG.CODPPAG
                    INNER JOIN TER ON NIEPE.NUMDOC=TER.IDTERCERO
         WHERE CNSNIEPE=@CNSNIEPE 
         AND NIEPE.CNSPAGO=@CNSPAGO 
         AND NUMDOC=@NUMDOC
         SELECT CODCONCEPTO+'  '+NOMBRE_CONCEPTO+CASE WHEN COALESCE(IDTERCERO_PRF,'')<>'' AND IDTERCERO_PRF<>NUMDOC THEN ' : '+RAZONSOCIAL_PRF ELSE '' END NOMBRE_CONCEPTO,
                CONVERT(DECIMAL(14,2),CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),CASE WHEN TIPO='Ingreso' THEN VALOR ELSE 0 END) DEVENGADOS,
                CONVERT(DECIMAL(14,2),CASE WHEN TIPO='Egreso' AND VALOR> 0 THEN VALOR ELSE 0 END) DEDUCIDOS,
                CONVERT(DECIMAL(14,2),CASE WHEN TIPO='Egreso' AND VALOR =0 THEN VALOR_APORTES ELSE 0 END) EMPLEADOR 
         FROM NIEPED
         WHERE CNSNIEPE=@CNSNIEPE 
         AND NUMDOC=@NUMDOC
      END
   END   

END