IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_RPT_ANEXO' AND type = 'P')
   DROP PROCEDURE SPK_RPT_ANEXO

GO
CREATE PROC DBO.SPK_RPT_ANEXO
@NOADMISION   VARCHAR(16),
@IDTERCERO    VARCHAR(20),
@TIPOANEXO    VARCHAR(1),
@IDPLANCA     VARCHAR(6),
@CNSRPDX      VARCHAR(20),
@CLASE        VARCHAR(2) = ''
WITH ENCRYPTION
AS
DECLARE @IDTERCEROHADM VARCHAR(20)
DECLARE @IDPLAN        VARCHAR(8)
DECLARE @FORMATOCODIGO INT
BEGIN
   IF @CLASE = ''
   BEGIN
      INSERT INTO RPDX ( CNS, ID1, STRINGGRANDE1, ID2, STRINGMEDIO1, ID3, ID4, ID5, STRINGGRANDE2, VALOR1, CANTIDAD)
      SELECT @CNSRPDX, HPRED.IDCIRUGIA, C.DESCSERVICIO , SER.PREFIJO, PRE.NOM_PREFIJO, HPRED.IDSERVICIO, HPRED.IDSERVICIO, MAX(HPRED.IDARTICULO),
             SER.DESCSERVICIO, HPRED.VALOR, SUM(HPRED.CANTIDAD) AS CANTIDAD
      FROM   HPRED INNER JOIN HPRE  ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                    LEFT JOIN SER C ON HPRED.IDCIRUGIA   = C.IDSERVICIO
                    LEFT JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
                    LEFT JOIN PRE   ON SER.PREFIJO       = PRE.PREFIJO 
      WHERE  HPRE.NOADMISION   = @NOADMISION
      AND    HPRED.IDTERCEROCA = CASE @TIPOANEXO WHEN '1' THEN HPRED.IDTERCEROCA ELSE @IDTERCERO END 
      AND    HPRED.IDPLAN      = CASE @TIPOANEXO WHEN '3' THEN @IDPLANCA ELSE HPRED.IDPLAN END
      AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE'),'') <> 'SI' THEN 0 ELSE COALESCE(HPRED.NOCOBRABLE,0) END
      AND    COALESCE(HPRED.PAQUETE,0)    = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('VISUALIZA_DETPAQUETE'),'') = 'SI' THEN 0 ELSE COALESCE(HPRED.PAQUETE,0) END
      AND    COALESCE(HPRED.ENCARGOS,0)   = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('VISUALIZA_CARGOS'),'') = 'SI' THEN COALESCE(HPRED.ENCARGOS,0) ELSE 0  END
      AND    COALESCE(HPRED.ANULADO, 0)   = 0 
      --AND    COALESCE(HPRED.VALOR,0)      > 0 
      GROUP BY HPRED.IDCIRUGIA, C.DESCSERVICIO,  SER.PREFIJO, PRE.NOM_PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, HPRED.VALOR
      ORDER BY HPRED.IDCIRUGIA, SER.PREFIJO

      UPDATE RPDX SET VALOR2 = CANTIDAD * VALOR1
      WHERE  CNS = @CNSRPDX

      SELECT @IDTERCEROHADM=IDTERCERO, @IDPLAN=IDPLAN FROM HADM WHERE NOADMISION=@NOADMISION
      SELECT @FORMATOCODIGO=IMPRIMEIDALTERNA FROM PPT WHERE IDTERCERO=@IDTERCEROHADM AND IDPLAN=@IDPLAN

      IF @FORMATOCODIGO=1 --IDALTERNA
      BEGIN
         PRINT 'INGRESO POR ACA...'
         IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
            UPDATE RPDX SET ID4=SER.IDALTERNA
            FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
            WHERE RPDX.CNS=@CNSRPDX
         ELSE
            UPDATE RPDX SET ID4=SER.IDALTERNA
            FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
            WHERE RPDX.CNS=@CNSRPDX
      END
      IF @FORMATOCODIGO=2 --CUM
      BEGIN
         UPDATE RPDX SET ID4=ISNULL(IART.CODCUM,SER.CODCUM), 
            NOMBRE=LEFT('['+COALESCE(IART.IDGENERICO,SER.IDGENERICO,'')+'] - '+RPDX.NOMBRE,150)
         FROM RPDX
            INNER JOIN IART ON IART.IDARTICULO=RPDX.ID5
            INNER JOIN SER  ON SER.PREFIJO=RPDX.ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX

      END
      IF @FORMATOCODIGO=3 --ATC
      BEGIN
         UPDATE RPDX SET ID4=SER.IDALTERNA
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX
      END
      IF @FORMATOCODIGO=4 --ADRES
      BEGIN
         UPDATE RPDX SET ID4=''
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNSRPDX

         UPDATE RPDX SET ID4=SER.CODSISPRO
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX
      END
      IF @FORMATOCODIGO=5 --SAVIA
      BEGIN
         UPDATE RPDX SET ID4=SER.CODSISPRO
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX

         UPDATE RPDX SET ID4=''
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES')) AND RPDX.CNS=@CNSRPDX
           
         UPDATE RPDX SET ID4=SER.CODCUPS
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE SER.PREFIJO IN (DBO.FNK_VALORVARIABLE('PREFIJOLABORATORIO')) AND RPDX.CNS=@CNSRPDX
      END
      IF @FORMATOCODIGO=6 --SISPRO
      BEGIN
         UPDATE RPDX SET ID4=SER.CODSISPRO
         FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX
      END
      IF @FORMATOCODIGO=7 --INVIMA
      BEGIN
         UPDATE RPDX SET ID4=COALESCE(IART.INVIMA,'')
         FROM SER 
            INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
            LEFT JOIN (
               SELECT IDSERVICIO, MAX(REGINVIMA) INVIMA
               FROM IART
               WHERE COALESCE(REGINVIMA,'') LIKE '%-%' AND LEN(REGINVIMA)>5
                  AND ESTADO='Activo'
               GROUP BY IDSERVICIO
            )IART ON SER.IDSERVICIO=IART.IDSERVICIO
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX
      END
      IF @FORMATOCODIGO=8 --CUPS
      BEGIN
         UPDATE RPDX SET ID4=ISNULL(SER.CODCUPS,'')--, NOMBRE=LEFT(SER.DESCRIPCION_CUPS,150)
         FROM RPDX
            INNER JOIN IART ON IART.IDARTICULO=RPDX.ID5
            INNER JOIN SER  ON SER.PREFIJO=RPDX.ID2 AND SER.IDSERVICIO=RPDX.ID3
         WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX
            --AND SER.PREFIJO=''
      END
      IF @FORMATOCODIGO=9 --IDALTERNA
      BEGIN
         PRINT 'INGRESO POR ACA...'
         IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='FTR_MUESTRAIDSER')='SI'
            UPDATE RPDX SET ID4=SER.IDALTERNA
            FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
            WHERE RPDX.CNS=@CNSRPDX
         ELSE
            UPDATE RPDX SET ID3=SER.IDALTERNA
            FROM SER INNER JOIN RPDX ON SER.PREFIJO=ID2 AND SER.IDSERVICIO=RPDX.ID3
            WHERE RPDX.CNS=@CNSRPDX
            AND COALESCE(SER.MEDICAMENTOS,0)=0

            UPDATE RPDX SET ID3=COALESCE(IART.CODCUM, SER.CODCUM,'')--, NOMBRE=LEFT(SER.DESCRIPCION_CUPS,150)
            FROM RPDX
               INNER JOIN IART ON IART.IDARTICULO=RPDX.ID5
               INNER JOIN SER  ON SER.PREFIJO=RPDX.ID2 AND SER.IDSERVICIO=RPDX.ID3
            WHERE COALESCE(SER.MEDICAMENTOS,0)=1 AND RPDX.CNS=@CNSRPDX


      END
   END
   ELSE IF @CLASE = '01'
   BEGIN
      INSERT INTO RPDX ( CNS, ID1, STRINGGRANDE1, ID2, STRINGMEDIO1, ID3, STRINGGRANDE2, NOMBRE, VALOR1, CANTIDAD)
      SELECT @CNSRPDX, HPRED.IDCIRUGIA, C.DESCSERVICIO , SER.PREFIJO, PRE.NOM_PREFIJO, HPRED.IDSERVICIO, 
             SER.DESCSERVICIO, 
             CASE DBO.FNK_VALORVARIABLE('IMPRIMIR_CUPS') WHEN 'SI'   -- MNKR 9/02/2017: Solo imprime CUPS/CUM solo si esta activa variable
                  THEN CASE ISNULL(SER.MEDICAMENTOS,0) WHEN 1        -- Si es medicamento miestra CUM
                            THEN COALESCE(IART.CODCUM,'')
                       ELSE SER.CODCUPS                              -- Sino CodCups
                  END 
                  ELSE '' 
             END,
             HPRED.VALOR, SUM(HPRED.CANTIDAD) AS CANTIDAD
      FROM   HPRED INNER JOIN HPRE  ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                    LEFT JOIN SER C ON HPRED.IDCIRUGIA   = C.IDSERVICIO
                    LEFT JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
                    LEFT JOIN PRE   ON SER.PREFIJO       = PRE.PREFIJO 
                    LEFT JOIN IART  ON COALESCE(HPRED.IDARTICULO,'')  = COALESCE(IART.IDARTICULO,'')
      WHERE  HPRE.NOADMISION   = @NOADMISION
      AND    HPRED.IDTERCEROCA = CASE @TIPOANEXO WHEN 1 THEN HPRED.IDTERCEROCA ELSE @IDTERCERO END 
      AND    HPRED.IDPLAN      = CASE @TIPOANEXO WHEN 3 THEN @IDPLANCA ELSE HPRED.IDPLAN END
      AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE'),'') <> 'SI' THEN 0 ELSE COALESCE(HPRED.NOCOBRABLE,0) END
      AND    COALESCE(HPRED.PAQUETE,0)    = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('VISUALIZA_DETPAQUETE'),'') = 'SI' THEN 0 ELSE COALESCE(HPRED.PAQUETE,0) END
      AND    COALESCE(HPRED.ENCARGOS,0)   = 0
      AND    COALESCE(HPRED.ANULADO, 0)   = 0 
      --AND    COALESCE(HPRED.VALOR,0)      > 0 
      GROUP BY HPRED.IDCIRUGIA, C.DESCSERVICIO,  SER.PREFIJO, PRE.NOM_PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, IART.CODCUM, HPRED.VALOR, SER.CODCUPS, SER.MEDICAMENTOS 
      ORDER BY HPRED.IDCIRUGIA, SER.PREFIJO

      UPDATE RPDX SET VALOR2 = CANTIDAD * VALOR1
      WHERE  CNS = @CNSRPDX
   END
   ELSE IF @CLASE IN ('FA','FB','FC')
   BEGIN
   INSERT INTO RPDX ( CNS, ID1, STRINGGRANDE1, ID2, STRINGMEDIO1, ID3, STRINGGRANDE2, NOMBRE,ID5, VALOR1, CANTIDAD,VALOR10, ID6)
      SELECT @CNSRPDX, HPRED.IDCIRUGIA, C.DESCSERVICIO , SER.PREFIJO, PRE.NOM_PREFIJO, HPRED.IDSERVICIO, 
             SER.DESCSERVICIO,
             CASE DBO.FNK_VALORVARIABLE('IMPRIMIR_CUPS') WHEN 'SI'   -- MNKR 9/02/2017: Solo imprime CUPS/CUM solo si esta activa variable
                  THEN CASE ISNULL(SER.MEDICAMENTOS,0) WHEN 1        -- Si es medicamento miestra CUM
                            THEN COALESCE(IART.CODCUM,'')
                       ELSE SER.CODCUPS                              -- Sino CodCups
                  END 
                  ELSE '' 
             END,  COALESCE(C.CODCUPS,''),
             HPRED.VALOR, SUM(HPRED.CANTIDAD) AS CANTIDAD,COALESCE(HPRED.PAQUETE,0), HPRED.IDARTICULO
      FROM   HPRED INNER JOIN HPRE  ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
                    LEFT JOIN SER C ON HPRED.IDCIRUGIA   = C.IDSERVICIO
                    LEFT JOIN SER   ON HPRED.IDSERVICIO  = SER.IDSERVICIO
                    LEFT JOIN PRE   ON SER.PREFIJO       = PRE.PREFIJO 
                    LEFT JOIN IART  ON COALESCE(HPRED.IDARTICULO,'')  = COALESCE(IART.IDARTICULO,'')
      WHERE  HPRE.NOADMISION = @NOADMISION
      AND    HPRED.N_FACTURA = @IDTERCERO
      AND    COALESCE(HPRED.NOCOBRABLE,0) = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE'),'') <> 'SI' THEN 0 ELSE COALESCE(HPRED.NOCOBRABLE,0) END
      AND    COALESCE(HPRED.PAQUETE,0)    = CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('VISUALIZA_DETPAQUETE'),'') = 'SI' THEN 0 ELSE COALESCE(HPRED.PAQUETE,0) END
      AND    COALESCE(HPRED.ENCARGOS,0)   = 0
      AND    COALESCE(HPRED.ANULADO, 0)   = 0 
      --AND    COALESCE(HPRED.VALOR,0)      > 0 
      GROUP BY HPRED.IDCIRUGIA, C.DESCSERVICIO,  SER.PREFIJO, PRE.NOM_PREFIJO, HPRED.IDSERVICIO, SER.DESCSERVICIO, IART.CODCUM, HPRED.VALOR, SER.CODCUPS,
      COALESCE(C.CODCUPS,''), SER.MEDICAMENTOS,COALESCE(HPRED.PAQUETE,0), HPRED.IDARTICULO
      ORDER BY HPRED.IDCIRUGIA, SER.PREFIJO


      UPDATE RPDX SET RPDX.NOMBRE = X.CODCUM
      FROM   RPDX INNER JOIN ( SELECT SER.IDSERVICIO, SER.IDARTICULO, RPDX.ID3, IART.CODCUM
                               FROM   SER INNER JOIN RPDX ON SER.IDSERVICIO = RPDX.ID3
                                          INNER JOIN IART ON SER.IDARTICULO = IART.IDARTICULO
                               WHERE  RPDX.CNS = @CNSRPDX
                               AND    COALESCE(SER.IDARTICULO,'') <> DBO.FNK_VALORVARIABLE('IDINVARTNA')
                             ) X ON RPDX.ID3 = X.IDSERVICIO 
      WHERE  RPDX.CNS = @CNSRPDX
      AND    COALESCE(RPDX.NOMBRE,'') = ''


      UPDATE RPDX SET VALOR2 = CANTIDAD * VALOR1
      WHERE  CNS = @CNSRPDX
      IF EXISTS(SELECT * FROM HADM WHERE NOADMISION=@NOADMISION AND COALESCE(PAQUETE,0)=2)
      BEGIN
         UPDATE RPDX SET VALOR2 = 0, VALOR1=0
         WHERE  CNS = @CNSRPDX
         AND VALOR10=0
      END

      IF @CLASE='FB' OR @CLASE='FC'
      BEGIN
         UPDATE RPDX SET NOMBRE=
            CASE ISNULL(SER.MEDICAMENTOS,0) 
               WHEN 1 THEN LEFT(IART.CODCUM+' / '+LEFT(IART.IDGENERICO,7),150)
               ELSE IART.CODCUM 
            END
         FROM RPDX
            INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID3 
            INNER JOIN IART ON IART.IDARTICULO=(CASE ISNULL(RPDX.ID6,'') WHEN '' THEN SER.IDARTICULO ELSE RPDX.ID6 END)
         WHERE RPDX.CNS=@CNSRPDX AND COALESCE(SER.IDARTICULO,'')<>DBO.FNK_VALORVARIABLE('IDINVARTNA')
      END
      IF @CLASE='FC'
      BEGIN
         UPDATE RPDX SET NOMBRE=SER.IDSERVICIO,ID3=SER.CODCUPS
         FROM RPDX
            INNER JOIN SER ON SER.IDSERVICIO=RPDX.ID3 
         WHERE RPDX.CNS=@CNSRPDX AND COALESCE(SER.IDARTICULO,'')=DBO.FNK_VALORVARIABLE('IDINVARTNA')
      END
   END
END


