IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND COALESCE(CHECK1,0)=0)
BEGIN
   UPDATE TGEN SET CHECK1=1 WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND COALESCE(CHECK1,0)=0
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='21')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','21','Accidente de trabajo'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='22')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','22','Accidente en el hogar'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='23')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','23','Accidente de tránsito de origen común'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='24')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','24','Accidente de tránsito de origen  laboral'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='25')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','25','Accidente en el entorno educativo'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='26')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','26','Otro tipo de accidente'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='27')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','27','Evento catastrófico de origen natural'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='28')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','28','Lesión por agresión'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='29')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','29','Lesión auto infligida'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='30')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','30','Sospecha de violencia física'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='31')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','31','Sospecha de violencia psicológica'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='32')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','32','Sospecha de violencia sexual'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='33')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','33','Sospecha de negligencia y abandono'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='34')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','34','IVE relacionado con peligro a la Salud o  vida de la mujer'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='35')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','35','IVE por malformación congénita  incompatible con la vida'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='36')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','36','IVE por violencia sexual, incesto o por inseminación artificial o  transferencia de ovulo fecundado no consentida'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='37')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','37','Evento adverso en salud'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='38')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','38','Enfermedad general'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='39')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','39','Enfermedad laboral'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='40')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','40','Promoción y mantenimiento de la salud – intervenciones individuales'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='41')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','41','Intervención colectiva'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='42')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','42','Atención de población materno perinatal'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='43')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','43','Riesgo ambiental'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='44')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','44','Otros eventos Catastróficos'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='45')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','45','Accidente de mina antipersonal – MAP'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='46')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','46','Accidente de Artefacto Explosivo Improvisado – AEI'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='47')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','47','Accidente de Munición Sin Explotar- MUSE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='48')
BEGIN
   INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'General','CAUSAEXTERNA','48','Otra víctima de conflicto armado colombiano'
END
-- HOMOLOGACION

IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='01' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='21' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='01' AND COALESCE(DATO1,'')=''
END

IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='02' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='23' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='02' AND COALESCE(DATO1,'')=''
END

IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='03' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='26' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='03' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='04' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='26' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='04' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='05' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='26' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='05' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='06' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='27' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='06' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='07' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='28' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='07' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='08' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='29' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='08' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='09' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='30' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='09' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='10' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='32' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='10' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='11' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='32' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='11' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='12' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='31' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='12' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='13' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='38' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='13' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='14' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='39' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='14' AND COALESCE(DATO1,'')=''
END
IF EXISTS(SELECT * FROM TGEN WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='15' AND COALESCE(DATO1,'')='')
BEGIN
   UPDATE TGEN SET DATO1='38' WHERE TABLA='General' AND CAMPO='CAUSAEXTERNA' AND CODIGO='15' AND COALESCE(DATO1,'')=''
END
-- FORMAS FARMACEUTICAS
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C28944' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C28944','CREMA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C29167' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C29167','LOCION'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C29269' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C29269','ENJUAGUE'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42887' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42887','AEROSOL'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42902' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42902','CAPSULA DE LIBERACION RETARDADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42905' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42905','TABLETAS DE LIBERACION RETARDADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42909' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42909','GRANULOS EFERVESCENTES'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42912' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42912','ELIXIR'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42914' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42914','EMULSION INYECTABLE'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42916' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42916','CAPSULA DE LIBERACION PROLONGADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42927' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42927','TABLETAS DE LIBERACION PROLONGADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42932' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42932','CINTA ADHESIVA / PELICULA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42933' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42933','GAS'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42938' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42938','GRANULOS CONVENCIONALES'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42941' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42941','GOMA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42942' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42942','IMPLANTE'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42948' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42948','GELES y JALEAS'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42953' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42953','LIQUIDO (Diferentes a soluciones)'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42966' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42966','UNGÜENTO'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42967' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42967','PASTA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42968' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42968','SISTEMAS TRANSDERMICOS'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42969' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42969','PELLETS'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42983' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42983','JABONES Y CHAMPU'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42989' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42989','ESPRAY'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42993' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42993','SUPOSITORIO / OVULO'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42994' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42994','SUSPENSION'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C42996' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C42996','JARABE'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C43000' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C43000','TINTURA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C47913' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C47913','EMPLASTO'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C47914' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C47914','TIRA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C47915' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C47915','SISTEMAS INTRAUTERINOS'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C64898' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C64898','ESPUMA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C64904' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C64904','CAPSULA CUBIERTA DURA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C64909' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C64909','CAPSULA BLANDA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C69031' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C69031','SISTEMAS OCULARES'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C91199' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C91199','SISTEMAS DE ANILLOS VAGINALES'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='C91200' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','C91200','SISTEMAS'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF001' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF001','TABLETAS DE LIBERACION NO MODIFICADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF002' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF002','POLVOS PARA NO RECONSTITUIR'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF003' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF003','POLVOS PARA RECONSTITUIR'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF004' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF004','OTRAS SOLUCIONES'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF005' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF005','OTRAS EMULSIONES'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF006' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF006','CAPSULAS DE LIBERACION NO MODIFICADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF007' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF007','CAPSULAS DE LIBERACION MODIFICADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF008' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF008','TABLETAS DE LIBERACION MODIFICADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF009' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF009','GRANULOS DE LIBERACION NO MODIFICADA'
END
IF NOT EXISTS(SELECT  * FROM TGEN WHERE TABLA='RIPSJSON' AND CAMPO='FFM' AND CODIGO='COLFF010' )
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','FFM','COLFF010','GRANULOS DE LIBERACION MODIFICADA'
END
-- SE CREA EL CAMPO HOMOLOG
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'IFFA'  AND   C.NAME = 'HOMOJSON')
BEGIN
   ALTER TABLE IFFA  ADD HOMOJSON VARCHAR(20)
END

UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),10)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),10) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL
UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),9)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),9) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL
UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),8)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),8) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL

UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),7)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),7) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL

UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),6)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),6) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL

UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),5)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),5) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL

UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),4)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),4) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL

UPDATE IFFA SET HOMOJSON=TGEN.CODIGO
FROM IFFA INNER JOIN TGEN ON LEFT(LTRIM(RTRIM(IFFA.DESCRIPCION)),3)=LEFT(LTRIM(RTRIM(TGEN.DESCRIPCION)),3) AND TGEN.CAMPO='FFM' AND TGEN.TABLA='RIPSJSON'
WHERE HOMOJSON IS NULL