CREATE OR ALTER PROCEDURE DBO.SPQ_FCONCI_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@ESTADO VARCHAR(20)             ,@FECHACONC DATETIME
      ,@FECHADIG DATETIME                 ,@IDTERCERO VARCHAR(20)          ,@CNSEXTERNO DECIMAL(14,2)
      ,@VALOR DECIMAL(14,2)               ,@FECHAPAGCONC DATETIME         ,@OBSERVACION VARCHAR(255)
      ,@IDFCONCI VARCHAR(20)              ,@PORCENTAJE DECIMAL(14,2)      ,@FUNCIONARIOADMIN VARCHAR(120)
      ,@TIPO VARCHAR(20)                  ,@CONDCONCEPTO VARCHAR(20)      ,@N_FACTURA VARCHAR(20)
      ,@CNSCXC VARCHAR(20)                ,@ITEM_FCXCDV INT               ,@CNSGLO VARCHAR(20)
      ,@SALDONETO DECIMAL(14,2)           ,@VLRRECUPERAR DECIMAL(14,2)    ,@VLRACEPTADO DECIMAL(14,2)
      ,@CONCEPTO VARCHAR(24)              ,@CNSFCGLO VARCHAR(20)          ,@ITEM_FCONCID INT        
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),  @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
    WHERE USUSU.USUARIO=@USUARIO

   IF @METODO='CRUD_FCONCI'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO,@IDFCONCI=IDFCONCI,@ESTADO=ESTADO,@FECHACONC=CONVERT(DATE,FECHACONC),@FECHADIG=CONVERT(DATE,FECHADIG),
             @IDTERCERO=IDTERCERO,@CNSEXTERNO=CNSEXTERNO,@VALOR=VALOR,@FECHAPAGCONC=CONVERT(DATE,FECHAPAGCONC),
             @OBSERVACION=OBSERVACION,@FUNCIONARIOADMIN=FUNCIONARIOADMIN,@TIPO=TIPO,@PORCENTAJE=PORCENTAJE   
      FROM   OPENJSON (@DATOS)
      WITH   ( 
         PROCESO VARCHAR(20)             '$.PROCESO',
         IDFCONCI  VARCHAR(20)           '$.IDFCONCI',
         ESTADO VARCHAR(20)              '$.ESTADO',
         FECHACONC VARCHAR(20)           '$.FECHACONC',
         FECHADIG VARCHAR(20)            '$.FECHADIG',
         IDTERCERO VARCHAR(20)           '$.IDTERCERO',
         CNSEXTERNO DECIMAL(14,2)        '$.CNSEXTERNO',
         VALOR DECIMAL(14,2)             '$.VALOR',
         FECHAPAGCONC VARCHAR(20)        '$.FECHAPAGCONC',
         OBSERVACION VARCHAR(255)        '$.OBSERVACION',
         FUNCIONARIOADMIN  VARCHAR(120)   '$.FUNCIONARIOADMIN',
         TIPO VARCHAR(20)                '$.TIPO.value',
         PORCENTAJE DECIMAL(7,2)          '$.PORCENTAJE'
      ) 
      PRINT '@PROCESO='+@PROCESO
      IF @PROCESO='Nueva'
      BEGIN
         BEGIN TRY           
               PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
               SELECT @IDFCONCI=''
		         EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@CONCI', @IDFCONCI OUTPUT  
		         SELECT @IDFCONCI = @IDSEDE + REPLACE(SPACE(8 - LEN(@IDFCONCI))+LTRIM(RTRIM(@IDFCONCI)),SPACE(1),0)
		         PRINT '@CNSFTR='+COALESCE(@IDFCONCI,'')              
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
                 SELECT * FROM @TBLERRORES
                 RETURN
         END CATCH
         INSERT INTO FCONCI(IDFCONCI, IDTERCERO, FECHACONC, CNSEXTERNO, USUARIO, FECHADIG, ESTADO, VALOR, FUNCIONARIOADMIN, OBSERVACION, FECHA_PAGCONC, TIPO, PORCENTAJE, CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA,  IDSEDE)
         SELECT @IDFCONCI, @IDTERCERO, @FECHACONC, @CNSEXTERNO, @USUARIO, @FECHADIG, 'Ingresada', @VALOR, @FUNCIONARIOADMIN,@OBSERVACION,@FECHAPAGCONC, @TIPO, @PORCENTAJE, 0, NULL, 'CXC', @IDSEDE
      END
      IF @PROCESO='Editar'
      BEGIN
         IF EXISTS(SELECT * FROM FCONCI WHERE IDFCONCI=@IDFCONCI AND ESTADO='Ingresada')
         BEGIN
            UPDATE FCONCI SET IDTERCERO=@IDTERCERO, FECHACONC=@FECHACONC, CNSEXTERNO=@CNSEXTERNO,VALOR=@VALOR,FUNCIONARIOADMIN=@FUNCIONARIOADMIN,
                   OBSERVACION=@OBSERVACION, FECHA_PAGCONC=@FECHACONC, TIPO=@TIPO, PORCENTAJE=@PORCENTAJE
            WHERE IDFCONCI=@IDFCONCI
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se Encontro Conciliación o ya Esta cerrada, Verifique e intente de nuevo '
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK 
      RETURN 
   END  
   IF @METODO='CRUD_FCONCID'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO, @ESTADO=ESTADO, @IDFCONCI=IDFCONCI, @CONDCONCEPTO=CONDCONCEPTO, @N_FACTURA=N_FACTURA, @CNSCXC=CNSCXC,
         @ITEM_FCXCDV=ITEM_FCXCDV, @TIPO=TIPO, @CNSGLO=CNSGLO, @SALDONETO=SALDONETO,@VLRRECUPERAR=VLRRECUPERAR,@VLRACEPTADO=VLRACEPTADO,
         @CNSFCGLO=CNSFCGLO,@OBSERVACION=OBSERVACION,@ITEM_FCONCID=ITEM_FCONCID
      FROM   OPENJSON (@DATOS)
      WITH   (  
         PROCESO VARCHAR(20)        '$.PROCESO',
         ESTADO VARCHAR(20)         '$.ESTADO',
         IDFCONCI VARCHAR(20)       '$.IDFCONCI',
         ITEM_FCONCID  INT          '$.ITEM_FCONCID',
         CONDCONCEPTO VARCHAR(20)   '$.CONDCONCEPTO',
         N_FACTURA VARCHAR(20)      '$.N_FACTURA',
         CNSCXC VARCHAR(20)         '$.CNSCXC',
         ITEM_FCXCDV INT            '$.ITEM_FCXCDV',
         TIPO VARCHAR(20)           '$.TIPO',
         CNSGLO VARCHAR(20)         '$.CNSGLO',
         SALDONETO DECIMAL(14,2)    '$.SALDONETO',
         VLRRECUPERAR DECIMAL(14,2) '$.VLRRECUPERAR',
         VLRACEPTADO DECIMAL(14,2)  '$.VLRACEPTADO',
         CNSFCGLO VARCHAR(20)       '$.CNSFCGLO',
         OBSERVACION VARCHAR(255)   '$.OBSERVACION'    
       )    
       IF EXISTS(SELECT * FROM FCONCI WHERE IDFCONCI=@IDFCONCI AND ESTADO='Ingresada')
       BEGIN
          IF @PROCESO='Nueva'
          BEGIN
             IF NOT EXISTS(SELECT * FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV)
             BEGIN
                SELECT @ITEM_FCONCID=COALESCE(MAX(ITEM_FCONCID),0)+1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI

                INSERT INTO FCONCID(IDFCONCI, ITEM_FCONCID, CNSCXC, N_FACTURA, ITEM_FCXCDV, TIPO, CNSGLO, SALDONETO, VLRACEPTADO, VLRRECUPERAR, 
                                    CNSFNOT, CLASE, ESTADO, OBSERVACION, CONDCONCEPTO, CNSFCGLO, CNSNOTADB, NROCOMPROBANTE_A )
                SELECT @IDFCONCI, @ITEM_FCONCID, @CNSCXC, @N_FACTURA, @ITEM_FCXCDV, @TIPO, @CNSGLO, @SALDONETO, @VLRACEPTADO, @VLRRECUPERAR, 
                       NULL, 'C', @ESTADO, @OBSERVACION, @CONDCONCEPTO, @CNSFCGLO, NULL, NULL 

             END
             ELSE
             BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'Ya existe este item en esta conciliación. Verifique e intente de nuevo'
             END
          END
          IF @PROCESO='Editar'
          BEGIN
             IF EXISTS(SELECT * FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV  AND ITEM_FCONCID=@ITEM_FCONCID)
             BEGIN
               UPDATE FCONCID SET VLRACEPTADO=@VLRACEPTADO,VLRRECUPERAR=@VLRRECUPERAR,CONDCONCEPTO=@CONDCONCEPTO,CNSFCGLO=@CNSFCGLO,OBSERVACION=@OBSERVACION
               WHERE IDFCONCI=@IDFCONCI
               AND ITEM_FCXCDV=@ITEM_FCXCDV
               AND ITEM_FCONCID=@ITEM_FCONCID
             END
             ELSE
             BEGIN
                DELETE FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCONCID=@ITEM_FCONCID
                SELECT @ITEM_FCONCID=COALESCE(MAX(ITEM_FCONCID),0)+1 FROM FCONCID WHERE IDFCONCI=@IDFCONCI

                INSERT INTO FCONCID(IDFCONCI, ITEM_FCONCID, CNSCXC, N_FACTURA, ITEM_FCXCDV, TIPO, CNSGLO, SALDONETO, VLRACEPTADO, VLRRECUPERAR, 
                                    CNSFNOT, CLASE, ESTADO, OBSERVACION, CONDCONCEPTO, CNSFCGLO, CNSNOTADB, NROCOMPROBANTE_A )
                SELECT @IDFCONCI, @ITEM_FCONCID, @CNSCXC, @N_FACTURA, @ITEM_FCXCDV, @TIPO, @CNSGLO, @SALDONETO, @VLRACEPTADO, @VLRRECUPERAR, 
                       NULL, 'C', @ESTADO, @OBSERVACION, @CONDCONCEPTO, @CNSFCGLO, NULL, NULL 
             END
          END
          IF @PROCESO='Borrar'
          BEGIN
              IF EXISTS(SELECT * FROM FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV  AND ITEM_FCONCID=@ITEM_FCONCID)
              BEGIN
                  DELETE FCONCID WHERE IDFCONCI=@IDFCONCI AND ITEM_FCXCDV=@ITEM_FCXCDV  AND ITEM_FCONCID=@ITEM_FCONCID
              END
              ELSE
              BEGIN
                 INSERT INTO @TBLERRORES(ERROR)
                 SELECT 'Item no encontrado. Varifique los datos e intente de nuevo '
              END
          END
       END
       ELSE
       BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Conciliación no Encontrada o ya fue cerrada, Verifique e intente de neuvo '
       END
       IF(SELECT COUNT(*) FROM @TBLERRORES)>0
       BEGIN
          SELECT 'KO' OK, ERROR FROM @TBLERRORES
          RETURN
       END
       SELECT 'OK' OK 
       RETURN 
   END  
   IF @METODO='CERRAR_FCONCI'     
   BEGIN         
      SELECT @IDFCONCI=IDFCONCI       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      IDFCONCI  VARCHAR(20)   '$.IDFCONCI'
      )
      IF EXISTS(SELECT * FROM FCONCI WHERE IDFCONCI=@IDFCONCI AND ESTADO='Ingresada')
      BEGIN
         BEGIN TRY           
              EXEC SPK_APLICA_CONCILIACION @IDFCONCI,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME              
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro el Registro o ya Fue aplicado, Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK 
      RETURN 
   END  
END
