IF EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='FACTURACIONPE' AND DBO.FNK_VALORVARIABLE('IXCOUNTRY')<> 'PERU')
BEGIN
   DELETE USGRUH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='FACTURACIONPE'
   DELETE USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='FACTURACIONPE'
END

IF NOT EXISTS(SELECT  * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_AUDITORIA' AND IDCONTROL='AUDIFACTURA')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,TIPO,DESCRIPCION,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,SUBLABEL,CODIGO,PAISES)
   SELECT 'MENUQ_AUDITORIA','AUDIFACTURA','M','Auditoría Facturas',1,'auditoria.factura','fa-solid fa-pen-ruler',null,0,0,'Recepción, Entrega Facturas',NULL,NULL
END