IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND IDCONTROL='CONF_PREFIJOS' )
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_CONFIGURACION', 'CONF_PREFIJOS', 'M','Prefijos', 1, 'conf.Prefijo', 'fa-solid fa-sliders', NULL, 0, 0, 850, 'Maestro Prefijos', NULL, NULL
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_CONFIGURACION' AND IDCONTROL='CONF_TARIFAS' )
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_CONFIGURACION', 'CONF_TARIFAS', 'M','Configuracion Tarifas', 1, 'conf.tarifa', 'fa-solid fa-receipt', NULL, 0, 0, 800, 'Codificación, Vigencias', NULL, NULL
END