CREATE OR ALTER PROCEDURE DBO.SPQ_XAUTD
	@JSON  NVARCHAR(MAX)
WITH
ENCRYPTION
AS   
DECLARE @PARAMETROS         NVARCHAR(MAX) ,@MODELO           VARCHAR(100)    ,@METODO	VARCHAR(100)  ,@USUARIO        VARCHAR(12)
	    ,@GRUPO             VARCHAR(8)	  ,@SYS_COMPUTERNAME VARCHAR(254)    ,@IDSEDE	VARCHAR(5)    ,@A              INT
       ,@IDAFILIADO         VARCHAR(20)   ,@PROCEDENCIA      VARCHAR(10)
	   ,@COMPANIA			VARCHAR(2)		,@IDBODEGA		 VARCHAR(5)
BEGIN		
	SET LANGUAGE Spanish; 
	SET DATEFORMAT dmy
	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	--PRINT 'INGRESE A SPQ_FME_COL'
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)     AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS , @USUARIO = USUARIO
	FROM #JSON
	--DEFINICION DE TABLA DE ERRORES
	DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
	-- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
	PRINT 'USUARIO:'+@USUARIO
	SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
	SELECT @IDSEDE = IDSEDE, @COMPANIA=COMPANIA, @IDBODEGA = COALESCE(IDBODEGA, IDBODEGA2, IDBODEGANOCHE, IDBODEGACONSUMO) 
	FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
	SELECT @IDSEDE = COALESCE(@IDSEDE,'01')

	IF @METODO = 'CONSULTA'
	BEGIN
		SELECT @PROCEDENCIA = PROCEDENCIA, @METODO = IDPLAN, @IDAFILIADO=IDAFILIADO
		FROM OPENJSON (@PARAMETROS)
		WITH (
			PROCEDENCIA         VARCHAR(20)     '$.PROCEDENCIA',
			IDAFILIADO          VARCHAR(20)     '$.IDAFILIADO',
			IDPLAN		        VARCHAR(20)     '$.IDPLAN'
		)
		DECLARE @SEXO VARCHAR(20), @ANOS SMALLINT
		SELECT @SEXO=SEXO, @ANOS=DATEDIFF(YEAR,FNACIMIENTO,GETDATE()) FROM AFI WHERE IDAFILIADO=@IDAFILIADO
		SELECT 'OK' OK
      if @PROCEDENCIA='GS'
      BEGIN
         SELECT @PROCEDENCIA='CE'
      END
		SELECT IDXAUTD, NOMBRE, A.SEXO, COALESCE(EDADINICIAL,0) EDADINICIAL, COALESCE(EDADFINAL,0) EDADFINAL, COALESCE(A.IDPLAN,'') IDPLAN, A.CODOM, HCCOM.DESCRIPCION DESCCODOM, CLASEORDEN, A.IDESPECIAL, B.DESCESPECIAL			
		FROM XAUTD A
			LEFT JOIN HCCOM ON A.CODOM=HCCOM.CODOM
			LEFT JOIN MPE B ON B.IDPESPECIAL=A.IDESPECIAL AND A.CLASEORDEN='PYP'
		WHERE A.TIPO='HCCOM' AND COALESCE(A.PROCEDENCIA,'') IN ('', @PROCEDENCIA)

		SELECT A.IDXAUTD, A.IDSERVICIO, B.DESCSERVICIO, A.CANTIDAD, A.FRECUENCIA, A.DURACION,
			B.SEXO, COALESCE(B.CIRUGIA, 0) CIRUGIA, COALESCE(B.MEZCLA, 0) MEZCLA, 
			CASE WHEN COALESCE(EXCLUYEPOSOLOGIA, 0) = 1 THEN 0 ELSE COALESCE(B.MEDICAMENTOS, 0) END MEDICAMENTOS,
			COALESCE(B.IDARTICULO, 'NA') IDARTICULO, CAST(CASE WHEN COALESCE(EXCLUYEPOSOLOGIA, 0) = 1 THEN 0 ELSE COALESCE(B.MDOSIF, 0) END AS BIT) MDOSIF,
			COALESCE(EQUICC, 0.0) EQUICC, COALESCE(B.MULTIDOSIS, 0) MULTIDOSIS, B.PRESUNI, B.VIA, COALESCE(LIBREFORMULACION, 0) LIBREFORMULACION,
			CAST(COALESCE(EXCLUYEPOSOLOGIA, 0) AS BIT)EXCLUYEPOSOLOGIA, CAST(COALESCE(C.BIOLOGICO, 0) AS BIT) BIOLOGICO,
			CAST(COALESCE(T_ESTABILIDAD, 0.0) AS INT) T_ESTABILIDAD, 0 RAZONNEC, CAST(0 AS BIT) LUNES, CAST(0 AS BIT) MARTES, CAST(0 AS BIT) MIERCOLES,
			CAST(0 AS BIT) JUEVES, CAST(0 AS BIT) VIERNES, CAST(0 AS BIT) SABADO, CAST(0 AS BIT) DOMINGO, C.ALERTA, B.EQUICCINF, GETDATE() FECHAINI,
			B.TERAPIA, COALESCE(B.MEZCLA,0) SEMEZCLA, COALESCE(B.CANTMAXIMA,0) CANTMAXIMA, COALESCE(B.CANTMAXIMA_CE,0) CANTMAXIMA_CE,
			(SELECT T.IDSERVICIOREL value, T.IDSERVICIOREL+'-'+U.DESCSERVICIO label FROM SERR T LEFT JOIN SER U ON T.IDSERVICIOREL=U.IDSERVICIO WHERE T.IDSERVICIO=B.IDSERVICIO AND T.TIPO='DI' FOR JSON PATH ) SER_MEZCLA,
			CONT_ESPECIAL = CAST(COALESCE(C.CONT_ESPECIAL,0) AS BIT), UNIRS = (SELECT ITEM,DXUNIRS FROM IARTDX WHERE IDARTICULO=B.IDARTICULO FOR JSON AUTO),			
			VALOROXI = (SELECT TOP 1 COALESCE(CEILING(VALOR/60),1) FROM TARDV WHERE IDSERVICIO=B.IDSERVICIO ORDER BY NOITEM DESC),
			CODOM = (SELECT TOP 1 X.CODOM FROM HCCOMD X WHERE X.PREFIJO=B.PREFIJO),
			CODOM_DESCRIPCION = (SELECT TOP 1 Y.DESCRIPCION FROM HCCOMD X INNER JOIN HCCOM Y ON Y.CODOM=X.CODOM  WHERE X.PREFIJO=B.PREFIJO)
		FROM XAUTDD A
			INNER JOIN XAUTD D ON D.IDXAUTD=A.IDXAUTD
			INNER JOIN SER B ON B.IDSERVICIO=A.IDSERVICIO
			LEFT JOIN IART C ON C.IDARTICULO=B.IDARTICULO
		WHERE D.TIPO='HCCOM' AND COALESCE(D.PROCEDENCIA,'') IN ('', @PROCEDENCIA) 
			AND B.ESTADO='Activo'
			AND COALESCE(B.SEXO,'Ambos') IN ('', @SEXO, 'Ambos')
			AND (REPLACE(COALESCE(TIPORANGOE,''),'NA','') = '' 
				OR (COALESCE(TIPORANGOE,'')='I' AND @ANOS BETWEEN COALESCE(B.EDADINICIAL, 0) AND COALESCE(B.EDADFINAL, 120))
				OR (COALESCE(TIPORANGOE,'')='E' AND @ANOS NOT BETWEEN COALESCE(B.EDADINICIAL, 0) AND COALESCE(B.EDADFINAL, 120))
				)
			AND EXISTS(SELECT 1 FROM CPPAF WHERE CPPAF.IDPLAN=@METODO AND CPPAF.IDSERVICIO=B.IDSERVICIO)
	END
END

