IF NOT EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='INTERFAXINV' AND XTYPE='U')
BEGIN
   CREATE TABLE INTERFAXINV (
   ID INT IDENTITY(1,1),
   FECHA DATETIME,
   ID_TRX VARCHAR(50),
   PROCESO VARCHAR(10),
   SOLICITUD VARCHAR(MAX),
   FORMATEADO VARCHAR(MAX),
   RESPUESTA VARCHAR(MAX),
   ESTADO VARCHAR(10),
   CNSMOV VARCHAR(20),
   IDARTICULO VARCHAR(20)
   )
END
IF NOT EXISTS(SELECT  * FROM SYS.objects WHERE name='INTERFAXINVID')
BEGIN
   ALTER TABLE INTERFAXINV  ADD CONSTRAINT INTERFAXINVID PRIMARY KEY CLUSTERED (ID)
END

