IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_PASA_MCP_MCPNIIF' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_PASA_MCP_MCPNIIF
END
GO
CREATE PROCEDURE DBO.SPK_PASA_MCP_MCPNIIF
@NROCOMPROBANTEMCP VARCHAR(20),
@COMPANIA            VARCHAR(2),
@USUARIO             VARCHAR(12),
@SYS_COMPUTERNAME    VARCHAR(254),
@SEDE                VARCHAR(5),
@COM                 VARCHAR(5),
@NROCOMPROBANTENIIF      VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @IDMODELOCONT    VARCHAR(2)
DECLARE @PREFIJO_USCXS   VARCHAR(10)
DECLARE @NOREFERENCIA    VARCHAR(20)
DECLARE @PROCEDENCIA     VARCHAR(20)
BEGIN
   IF DBO.FNK_VALORVARIABLE('IDPROCESOCONTABLE')='NIIF'
   BEGIN
      PRINT 'SOLO ESTOY TRABAJANDO EN NIIF ME REGRESO NO DEBO CONTINUAR'
      RETURN
   END
   IF EXISTS(SELECT * FROM MCPNIIF WHERE NROCOMPROBANTEMCP=@NROCOMPROBANTEMCP) 
   BEGIN
      PRINT 'YA ESTA EN NIIF'
      DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF  AND EXISTS(SELECT * FROM MCPE WHERE NROCOMPROBANTE=MCHE.NROCOMPROBANTE AND CLASECONTB='NIIF')
      DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF AND CLASECONTB='NIIF'
      
      UPDATE MCPNIIF SET ESTADO=0 WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF
      DELETE MCHNIIF WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF

      ALTER TABLE MCP DISABLE TRIGGER TK_MCP_MOVIMIENTOS
      UPDATE MCP SET ENVNIIF=0 WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP
      ALTER TABLE MCP ENABLE TRIGGER TK_MCP_MOVIMIENTOS

      IF EXISTS(SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP AND COALESCE(ANULADO,0)=1)
      BEGIN
         UPDATE MCPNIIF SET ANULADO=1 WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF
         RETURN
      END
   END
   PRINT '@COM ='+@COM
   IF COALESCE(@NROCOMPROBANTEMCP,'')=''
   BEGIN
      PRINT 'NO EXISTE COMPROBANTE MCP'
      RETURN
   END
   ELSE
   BEGIN
      IF NOT EXISTS (SELECT * FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP AND ESTADO=2 AND COALESCE(ANULADO,0)<>1)
      BEGIN
         PRINT 'EL COMPROBANTE EN MCP NO ESTA CONFIRMADO'
         RETURN
      END
   END
   IF COALESCE(@NROCOMPROBANTENIIF,'')=''
   BEGIN
      SET @NROCOMPROBANTENIIF = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCPNIIF',@NROCOMPROBANTENIIF OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTENIIF,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	SELECT @NROCOMPROBANTENIIF = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTENIIF) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTENIIF) END)+LTRIM(RTRIM(@NROCOMPROBANTENIIF)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTENIIF,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
   	 --GENERO EL CONSECUTIVO DEL TIPO DE COMPROBANTE
   	SET @PREFIJO_USCXS='@COMNIIF'+ISNULL(@COM,'')
   	SET @NOREFERENCIA=SPACE(20)
        
   	EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
   	SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
   	PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
   	PRINT 'Comprobante Contable (MCP)'

      PRINT 'Se Crea MCPNIIF'

      INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                            REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE,  ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, 
                            RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO,CLASECONTB,NROCOMPROBANTEMCP )
      SELECT COMPANIA, @NROCOMPROBANTENIIF, PROCEDENCIA, @NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, 
             REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE,  1, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, 
             RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO,'NIIF',@NROCOMPROBANTEMCP 
      FROM MCP 
      WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP
   END
   ELSE
   BEGIN
      IF NOT EXISTS(SELECT * FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF AND CLASECONTB='NIIF')
      BEGIN
         INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                               REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE,  ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, 
                               RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO,CLASECONTB,NROCOMPROBANTEMCP )
         SELECT COMPANIA, @NROCOMPROBANTENIIF, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, 
                REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE,  1, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, 
                RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO,'NIIF',@NROCOMPROBANTEMCP
         FROM MCP 
         WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP

         DELETE MCHNIIF WHERE  NROCOMPROBANTE=@NROCOMPROBANTENIIF
         DELETE MCPNIIF WHERE  NROCOMPROBANTE=@NROCOMPROBANTENIIF
      END
      DELETE MCHNIIF WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF
   END
   DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF AND EXISTS(SELECT * FROM MCPE WHERE NROCOMPROBANTE=MCHE.NROCOMPROBANTE AND CLASECONTB='NIIF')
   PRINT 'SE CREA MCHE'

   INSERT INTO MCHE(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, 
                        F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, 
                        PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG,  ERROR, IDPROVEEDOR, ENPRESUPUESTO)
   SELECT @NROCOMPROBANTENIIF, MCH.COMPANIA,MCH.TIPO, CASE WHEN COALESCE(CUE.CUENTANIIF,'')<>CUE.CUENTA THEN CUENTANIIF ELSE  CUE.CUENTA END, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, 
         F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF,  USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, 1, PROCESO, VALOR_PORCIMP, BASE_IMP, 
         PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG,  ERROR, IDPROVEEDOR, ENPRESUPUESTO
   FROM MCH INNER JOIN CUE ON MCH.CUENTA=CUE.CUENTA
   WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP

   EXEC SPK_NC_SUMA_NIIF_DBCR @NROCOMPROBANTENIIF
   EXEC SPK_NC_REVISAR_COMPROBANTE_MCPE_NIIF @COMPANIA,@NROCOMPROBANTENIIF

   IF (SELECT ESTADO FROM MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF)=1
   BEGIN
      PRINT 'CREO NIIF'
      INSERT INTO MCPNIIF (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, 
                           ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO, NROCOMPROBANTEMCP)
      SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO, TOTALCREDITO, REFERENCIA1, REFERENCIA2, REFERENCIA3, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, 
            ESTADO, ANULADO, COMPROBANTE, IDTERCERO, BANCO, NOCHEQUE, VALOR_CHEQUE, RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO, NROCOMPROBANTEMCP
      FROM MCPE 
      WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF

      INSERT INTO MCHNIIF(NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
                           USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
                           ERROR, IDPROVEEDOR, ENPRESUPUESTO)
      SELECT NROCOMPROBANTE, COMPANIA, TIPO, CUENTA, IDTERCERO, CCOSTO, DETALLE, VALOR, REFERENCIA1, REFERENCIA2, REFERENCIA3, N_FACTURA, F_FACTURAREF, F_VENCE, GENERA, CLASE_GENERA, CNSPAGO, ITEMREF, 
             USUARIO, FECHA, PREFIJO, IDAREA, CLASECONT, ESTADO, PROCESO, VALOR_PORCIMP, BASE_IMP, PROCEDENCIA, REFERENCIA_PRO, CONCILIADO, FECHACONCILIACION, CNSFCXCXP, CODUNG, CODPRG, 
             ERROR, IDPROVEEDOR, ENPRESUPUESTO
      FROM MCHE 
      WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF

      UPDATE MCHNIIF SET ESTADO=2 WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF 
      UPDATE MCPNIIF SET ESTADO=2 WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF  
      
      
      DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF
      DELETE MCPE WHERE NROCOMPROBANTE=@NROCOMPROBANTENIIF
   END
   ALTER TABLE MCP DISABLE TRIGGER TK_MCP_MOVIMIENTOS
   UPDATE MCP SET ENVNIIF=1,NROCOMPROBANTENIIF=@NROCOMPROBANTENIIF WHERE NROCOMPROBANTE=@NROCOMPROBANTEMCP
   ALTER TABLE MCP DISABLE TRIGGER TK_MCP_MOVIMIENTOS
END

