CREATE OR ALTER PROCEDURE DBO.SPQ_FTR_RPT_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(20)               ,@F_INICIAL DATETIME               ,@F_FINAL DATETIME
      ,@IDTERCERO VARCHAR(20)             ,@IDPLAN VARCHAR(20)              ,@PARTICULAR VARCHAR(20)
      ,@IDSEDEF VARCHAR(20)               ,@PROCEDENCIA VARCHAR(20)         ,@USUARIOFACTU VARCHAR(20)
      ,@TERCONTABLE VARCHAR(20)           ,@AREAFUNCIONAL VARCHAR(20)       ,@PREFIJO VARCHAR(20)
      ,@IDSERVICIO VARCHAR(20)            ,@PART VARCHAR(MAX)               ,@SQL VARCHAR(MAX)
      ,@ESTFTR VARCHAR(120)               ,@WHERE VARCHAR(MAX)              ,@SELECT VARCHAR(MAX)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='GENERAR_RPT'     
   BEGIN         
      SELECT @PROCESO=PROCESO, @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH ( 
         PROCESO VARCHAR(20) '$.PROCESO',
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      
         SELECT  @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDTERCERO=IDTERCERO, @IDPLAN=IDPLAN, @PARTICULAR=PARTICULAR, @IDSEDEF=IDSEDEF,
         @PROCEDENCIA=PROCEDENCIA, @USUARIOFACTU=USUARIOFACTU, @TERCONTABLE=TERCONTABLE, @AREAFUNCIONAL=AREAFUNCIONAL,  @PREFIJO=PREFIJO,
         @IDSERVICIO=IDSERVICIO     
         FROM   OPENJSON (@DATOS)
         WITH   (  
         F_INICIAL DATE            '$.F_INICIAL',
         F_FINAL DATE              '$.F_FINAL',
         IDTERCERO VARCHAR(20)     '$.IDTERCERO',
         IDPLAN VARCHAR(6)         '$.IDPLAN',
         PARTICULAR VARCHAR(20)    '$.PARTICULAR',
         IDSEDEF VARCHAR(6)        '$.IDSEDE',
         PROCEDENCIA VARCHAR(20)   '$.PROCEDENCIA',
         USUARIOFACTU VARCHAR(20)  '$.USUARIOFACTU',
         TERCONTABLE VARCHAR(20)   '$.TERCONTABLE',
         AREAFUNCIONAL VARCHAR(20) '$.AREAFUNCIONAL',
         PREFIJO VARCHAR(20)       '$.PREFIJO',
         IDSERVICIO VARCHAR(20)    '$.IDSERVICIO'       
         )   
      IF (OBJECT_ID('tempdb.dbo.#FTR','U')) IS NULL
      BEGIN
         CREATE TABLE #FTR(N_FACTURA VARCHAR(20) COLLATE database_default)
      END
      ELSE
      BEGIN
         DELETE #FTR
      END
      IF  DBO.FNK_VALORVARIABLE('SEPARA_NC_RPT_FACT')<>'NO' AND @PROCESO <> 'NotasCr'
      BEGIN
         INSERT INTO #FTR(N_FACTURA)
         SELECT DISTINCT FTR.N_FACTURA 
         FROM FTR INNER JOIN FNOT ON FTR.N_FACTURA = FNOT.N_FACTURA
         WHERE COALESCE(TIPOANULACION, '') = 'NC'
         AND F_FACTURA>=CONVERT(VARCHAR(10),@F_INICIAL,103)
         AND F_FACTURA< CONVERT(VARCHAR(10),@F_FINAL + 1,103)
      END
      --ARMADO DE CLAUSULA PARTICULARES
      SELECT @PART = ''
      IF LEFT(@PARTICULAR,1) = '1'
      BEGIN
         SELECT @PART = ' AND  FTR.IDPLAN NOT IN( SELECT DATO FROM USVGS WHERE IDVARIABLE IN
         (''IDPLANPART'',''IDPLANPART2'',''IDPLANPART3'',''IDPLANPART4'',''IDPLANPART5''))'
      END
      ELSE IF  LEFT(@PARTICULAR,1) = '2'
      BEGIN
         SELECT @PART = ' AND  FTR.IDPLAN IN( SELECT DATO FROM USVGS WHERE IDVARIABLE IN
         (''IDPLANPART'',''IDPLANPART2'',''IDPLANPART3'',''IDPLANPART4'',''IDPLANPART5''))'
      END
      ELSE
      BEGIN
         SELECT @PART = ''
      END
      SELECT @ESTFTR=''
      IF @PROCESO='Anuladas'
      BEGIN 
         SELECT @ESTFTR=' AND FTR.ESTADO=''A'' '
      END
      ELSE
      BEGIN
         IF @PROCESO='NotasCr'
         BEGIN 
            SELECT @ESTFTR=' AND COALESCE(FTR.TIPOANULACION,'''')=''NC'' '
         END
         ELSE
         BEGIN
            IF UPPER(@PROCESO) <> 'GENERAL'
            BEGIN
               SELECT @ESTFTR='  AND FTR.ESTADO=''P'' AND COALESCE(FTR.TIPOANULACION,'''')<>''NC'' '
            END 
            ELSE
            BEGIN
               SELECT @ESTFTR='  AND FTR.ESTADO=FTR.ESTADO '
            END
         END
      END

      PRINT '@PROCESO='+@PROCESO
      IF UPPER(@PROCESO) IN('FACTURADO','TODO','TERCERO','IDPLAN','TERCONTA','ANULADAS','NOTACR')
      BEGIN
         IF UPPER(@PROCESO)='TERCERO' 
         BEGIN
            IF  COALESCE(@IDTERCERO,'')=''
            BEGIN
               SELECT @SQL=
                  'SELECT FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL, COUNT(*) CANTIDAD, SUM(FTR.VALORSERVICIOS) VALOR_SERVICIOS, SUM(FTR.VALORCOPAGO) VALORCOPAGO, 
                  SUM(FTR.VALORPCOMP) VALOR_PCOMP, SUM(FTR.DESCUENTO) DESCUENTO, SUM(FTR.VALORSERVICIOS)-SUM(FTR.DESCUENTO)-SUM(FTR.VALORPCOMP)-SUM(FTR.VALORCOPAGO) VR_TOTAL,
                  SUM(CASE WHEN  FTR.ESTADO=''P'' AND COALESCE(TIPOANULACION,'''')<>''NC'' THEN 1 ELSE 0 END) ACTIVAS,SUM(CASE WHEN  FTR.ESTADO=''A'' THEN 1 ELSE 0 END)ANULADAS,
                  SUM( CASE WHEN COALESCE(FTR.TIPOANULACION,'''')=''NC'' THEN 1 ELSE 0 END) NOTACR,SUM(CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN 1 ELSE 0 END) ENCOLA,
                  SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 1 THEN 1  ELSE 0 END) ENCOLA,SUM(CASE WHEN COALESCE(FTR.FACTE,0)=2 THEN 1 ELSE 0 END) ENVIADA,
                  SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 3 THEN 1 ELSE 0 END)CONERROR,SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 4 THEN 1 ELSE 0 END) RECEPCION
                  FROM   FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                  WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
                  AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
                  AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
                  AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+COALESCE(@IDSEDEF,'Todas')+'''<>''Todas'' THEN '''+COALESCE(@IDSEDEF,'Todas')+''' ELSE COALESCE(FTR.IDSEDE,'''') END
                  AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+COALESCE(@PROCEDENCIA,'Todas')+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+COALESCE(@PROCEDENCIA,'Todas')+''' END 
                  AND    FTR.IDTERCERO = CASE WHEN COALESCE('''+COALESCE(@IDTERCERO,'')+''','''')='''' THEN FTR.IDTERCERO ELSE '''+COALESCE(@IDTERCERO,'')+''' END 
                  ' +@PART+@ESTFTR+
                  ' GROUP BY FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL,FTR.ESTADO,COALESCE(FTR.TIPOANULACION,'''') ' 
               PRINT @SQL
               SELECT 'OK' OK
               EXECUTE(@SQL)
            END
            ELSE
            BEGIN
               PRINT 'DETALLE POR TERCERO'
               SELECT @ESTFTR='  AND FTR.ESTADO=FTR.ESTADO '
               SELECT @SQL=
                  'SELECT FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL,FTR.N_FACTURA,CONVERT(VARCHAR,F_FACTURA,103)F_FACTURA,FTR.PROCEDENCIA,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,
                  FTR.VALORSERVICIOS,FTR.VALORCOPAGO AS VALORCOPAGO, 
                  FTR.VALORPCOMP VALOR_PCOMP, FTR.DESCUENTO DESCUENTO, FTR.VALORSERVICIOS-FTR.DESCUENTO-FTR.VALORPCOMP-FTR.VALORCOPAGO VR_TOTAL,
                  CASE WHEN FTR.ESTADO=''P'' AND COALESCE(TIPOANULACION,'''')<>''NC'' THEN ''ACTIVA'' ELSE ''ANULADA'' END ESTADO,
                  CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN ''SINENVIAR'' WHEN 1 THEN ''ENCOLA'' WHEN 2 THEN ''NOTIFICADA'' WHEN 3 THEN ''CONERROR''
                  WHEN 4 THEN ''NOTIFICADA'' ELSE ''OTRO'' END ESTADODIAN,FTR.USUARIOFACTURA,USUSU.NOMBRE 
                  FROM   FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                             LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
                             LEFT  JOIN USUSU ON FTR.USUARIOFACTURA=USUSU.USUARIO
                  WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
                  AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
                  AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
                  AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+COALESCE(@IDSEDEF,'Todas')+'''<>''Todas'' THEN '''+COALESCE(@IDSEDEF,'Todas')+''' ELSE COALESCE(FTR.IDSEDE,'''') END
                  AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+COALESCE(@PROCEDENCIA,'Todas')+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+COALESCE(@PROCEDENCIA,'Todas')+''' END 
                  AND    FTR.IDTERCERO = CASE WHEN COALESCE('''+COALESCE(@IDTERCERO,'')+''','''')='''' THEN FTR.IDTERCERO ELSE '''+COALESCE(@IDTERCERO,'')+''' END 
                  ' +@PART+@ESTFTR
                  PRINT @SQL
                  SELECT 'OK' OK
                  EXECUTE(@SQL)
            END
         END
         IF UPPER(@PROCESO)='IDPLAN'  
         BEGIN
            IF COALESCE(@IDPLAN,'')=''
            BEGIN
               SELECT @SQL=
                  'SELECT FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN, COUNT(*) CANTIDAD, SUM(FTR.VALORSERVICIOS) VALOR_SERVICIOS, SUM(FTR.VALORCOPAGO) VALORCOPAGO, 
                  SUM(FTR.VALORPCOMP) VALOR_PCOMP, SUM(FTR.DESCUENTO) DESCUENTO, SUM(FTR.VALORSERVICIOS)-SUM(FTR.DESCUENTO)-SUM(FTR.VALORPCOMP)-SUM(FTR.VALORCOPAGO) VR_TOTAL,
                  SUM(CASE WHEN  FTR.ESTADO=''P'' AND COALESCE(TIPOANULACION,'''')<>''NC'' THEN 1 ELSE 0 END) ACTIVAS,SUM(CASE WHEN  FTR.ESTADO=''A'' THEN 1 ELSE 0 END)ANULADAS,
                  SUM( CASE WHEN COALESCE(FTR.TIPOANULACION,'''')=''NC'' THEN 1 ELSE 0 END) NOTACR,SUM(CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN 1 ELSE 0 END) ENCOLA,
                  SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 1 THEN 1  ELSE 0 END) ENCOLA,SUM(CASE WHEN COALESCE(FTR.FACTE,0)=2 THEN 1 ELSE 0 END) ENVIADA,
                  SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 3 THEN 1 ELSE 0 END)CONERROR,SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 4 THEN 1 ELSE 0 END) RECEPCION
                  FROM   FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                             LEFT  JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
                  WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
                  AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
                  AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
                  AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+COALESCE(@IDSEDEF,'Todas')+'''<>''Todas'' THEN '''+COALESCE(@IDSEDEF,'Todas')+''' ELSE COALESCE(FTR.IDSEDE,'''') END
                  AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+COALESCE(@PROCEDENCIA,'Todas')+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+COALESCE(@PROCEDENCIA,'Todas')+''' END 
                  AND    FTR.IDTERCERO = CASE WHEN COALESCE('''+COALESCE(@IDTERCERO,'')+''','''')='''' THEN FTR.IDTERCERO ELSE '''+COALESCE(@IDTERCERO,'')+''' END 
                  ' +@PART+@ESTFTR+
                  ' GROUP BY FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL,FTR.ESTADO,COALESCE(FTR.TIPOANULACION,''''),FTR.IDPLAN,PLN.DESCPLAN ' 
               PRINT @SQL
               SELECT 'OK' OK
               EXECUTE(@SQL)
            END
            ELSE
            BEGIN
               PRINT 'DETALLE POR TERCERO Y PLAN '
               SELECT @ESTFTR='  AND FTR.ESTADO=FTR.ESTADO '
               SELECT @SQL=
                  'SELECT FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,FTR.N_FACTURA,CONVERT(VARCHAR,F_FACTURA,103)F_FACTURA,FTR.PROCEDENCIA,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,
                  FTR.VALORSERVICIOS,FTR.VALORCOPAGO AS VALORCOPAGO, 
                  FTR.VALORPCOMP VALOR_PCOMP, FTR.DESCUENTO DESCUENTO, FTR.VALORSERVICIOS-FTR.DESCUENTO-FTR.VALORPCOMP-FTR.VALORCOPAGO VR_TOTAL,
                  CASE WHEN FTR.ESTADO=''P'' AND COALESCE(TIPOANULACION,'''')<>''NC'' THEN ''ACTIVA'' ELSE ''ANULADA'' END ESTADO,
                  CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN ''SINENVIAR'' WHEN 1 THEN ''ENCOLA'' WHEN 2 THEN ''NOTIFICADA'' WHEN 3 THEN ''CONERROR''
                  WHEN 4 THEN ''NOTIFICADA'' ELSE ''OTRO'' END ESTADODIAN,FTR.USUARIOFACTURA,USUSU.NOMBRE 
                  FROM   FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                             LEFT  JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
                             LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
                             LEFT  JOIN USUSU ON FTR.USUARIOFACTURA=USUSU.USUARIO
                  WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
                  AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
                  AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
                  AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+COALESCE(@IDSEDEF,'Todas')+'''<>''Todas'' THEN '''+COALESCE(@IDSEDEF,'Todas')+''' ELSE COALESCE(FTR.IDSEDE,'''') END
                  AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+COALESCE(@PROCEDENCIA,'Todas')+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+COALESCE(@PROCEDENCIA,'Todas')+''' END 
                  AND    FTR.IDTERCERO = CASE WHEN COALESCE('''+COALESCE(@IDTERCERO,'')+''','''')='''' THEN FTR.IDTERCERO ELSE '''+COALESCE(@IDTERCERO,'')+''' END 
                  AND    FTR.IDPLAN = CASE WHEN COALESCE('''+COALESCE(@IDPLAN,'')+''','''')='''' THEN FTR.IDPLAN ELSE '''+COALESCE(@IDPLAN,'')+''' END 
                  ' +@PART+@ESTFTR
                  PRINT @SQL
                  SELECT 'OK' OK
                  EXECUTE(@SQL)
             END
         END
         IF UPPER(@PROCESO)='TERCONTA'  
         BEGIN
            IF COALESCE(@TERCONTABLE,'')=''
            BEGIN
               SELECT @SQL=
                  'SELECT COALESCE(FTR.TIPOTTEC,''SINTTEC'')TIPOTTEC,COALESCE(TTEC.DETALLE,''NO DEFINIDO'')DETALLE, COUNT(*) CANTIDAD, SUM(FTR.VALORSERVICIOS) VALOR_SERVICIOS, SUM(FTR.VALORCOPAGO) VALORCOPAGO, 
                  SUM(FTR.VALORPCOMP) VALOR_PCOMP, SUM(FTR.DESCUENTO) DESCUENTO, SUM(FTR.VALORSERVICIOS)-SUM(FTR.DESCUENTO)-SUM(FTR.VALORPCOMP)-SUM(FTR.VALORCOPAGO) VR_TOTAL,
                  SUM(CASE WHEN  FTR.ESTADO=''P'' AND COALESCE(TIPOANULACION,'''')<>''NC'' THEN 1 ELSE 0 END) ACTIVAS,SUM(CASE WHEN  FTR.ESTADO=''A'' THEN 1 ELSE 0 END)ANULADAS,
                  SUM( CASE WHEN COALESCE(FTR.TIPOANULACION,'''')=''NC'' THEN 1 ELSE 0 END) NOTACR,SUM(CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN 1 ELSE 0 END) ENCOLA,
                  SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 1 THEN 1  ELSE 0 END) ENCOLA,SUM(CASE WHEN COALESCE(FTR.FACTE,0)=2 THEN 1 ELSE 0 END) ENVIADA,
                  SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 3 THEN 1 ELSE 0 END)CONERROR,SUM(CASE WHEN COALESCE(FTR.FACTE,0)= 4 THEN 1 ELSE 0 END) RECEPCION
                  FROM   FTR LEFT JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO 
                  WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
                  AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
                  AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
                  AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+COALESCE(@IDSEDEF,'Todas')+'''<>''Todas'' THEN '''+COALESCE(@IDSEDEF,'Todas')+''' ELSE COALESCE(FTR.IDSEDE,'''') END
                  AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+COALESCE(@PROCEDENCIA,'Todas')+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+COALESCE(@PROCEDENCIA,'Todas')+''' END 
                  AND    FTR.TIPOTTEC = CASE WHEN COALESCE('''+COALESCE(@TERCONTABLE,'')+''','''')='''' THEN FTR.TIPOTTEC ELSE '''+COALESCE(@TERCONTABLE,'')+''' END 
                  ' +@PART+@ESTFTR+
                  ' GROUP BY FTR.TIPOTTEC,TTEC.DETALLE,FTR.ESTADO,COALESCE(FTR.TIPOANULACION,'''')' 
               PRINT @SQL
               SELECT 'OK' OK
               EXECUTE(@SQL)
            END
            ELSE
            BEGIN
               PRINT 'DETALLE POR TIPO DE TERCERO '
               SELECT @ESTFTR='  AND FTR.ESTADO=FTR.ESTADO '
               SELECT @SQL=
                  'SELECT FTR.IDTERCERO, TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,COALESCE(FTR.TIPOTTEC,''SINTTEC'')TIPOTTEC,COALESCE(TTEC.DETALLE,''NO DEFINIDO'')DETALLE,FTR.N_FACTURA,CONVERT(VARCHAR,F_FACTURA,103)F_FACTURA,FTR.PROCEDENCIA,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,
                  FTR.VALORSERVICIOS,FTR.VALORCOPAGO AS VALORCOPAGO, 
                  FTR.VALORPCOMP VALOR_PCOMP, FTR.DESCUENTO DESCUENTO, FTR.VALORSERVICIOS-FTR.DESCUENTO-FTR.VALORPCOMP-FTR.VALORCOPAGO VR_TOTAL,
                  CASE WHEN FTR.ESTADO=''P'' AND COALESCE(TIPOANULACION,'''')<>''NC'' THEN ''ACTIVA'' ELSE ''ANULADA'' END ESTADO,
                  CASE COALESCE(FTR.FACTE,0) WHEN 0 THEN ''SINENVIAR'' WHEN 1 THEN ''ENCOLA'' WHEN 2 THEN ''NOTIFICADA'' WHEN 3 THEN ''CONERROR''
                  WHEN 4 THEN ''NOTIFICADA'' ELSE ''OTRO'' END ESTADODIAN,FTR.USUARIOFACTURA,USUSU.NOMBRE 
                  FROM   FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                             LEFT  JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
                             LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
                             LEFT  JOIN USUSU ON FTR.USUARIOFACTURA=USUSU.USUARIO
                             LEFT  JOIN TTEC ON FTR.TIPOTTEC=TTEC.TIPO
                  WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
                  AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
                  AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
                  AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+COALESCE(@IDSEDEF,'Todas')+'''<>''Todas'' THEN '''+COALESCE(@IDSEDEF,'Todas')+''' ELSE COALESCE(FTR.IDSEDE,'''') END
                  AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+COALESCE(@PROCEDENCIA,'Todas')+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+COALESCE(@PROCEDENCIA,'Todas')+''' END 
                  AND    FTR.IDTERCERO = CASE WHEN COALESCE('''+COALESCE(@IDTERCERO,'')+''','''')='''' THEN FTR.IDTERCERO ELSE '''+COALESCE(@IDTERCERO,'')+''' END 
                  AND    FTR.IDPLAN = CASE WHEN COALESCE('''+COALESCE(@IDPLAN,'')+''','''')='''' THEN FTR.IDPLAN ELSE '''+COALESCE(@IDPLAN,'')+''' END 
                  AND    FTR.TIPOTTEC = CASE WHEN COALESCE('''+COALESCE(@TERCONTABLE,'')+''','''')='''' THEN FTR.TIPOTTEC ELSE '''+COALESCE(@TERCONTABLE,'')+''' END 
                  ' +@PART+@ESTFTR
                  PRINT @SQL
                  SELECT 'OK' OK
                  EXECUTE(@SQL)
             END
         END
      END
       IF UPPER(@PROCESO) ='PREFIJO' --,'SERVICIO','IDAREA')
      BEGIN
         PRINT 'INGRESO AL TODO'
         SELECT @SQL=
         'SELECT FTR.IDTERCERO,TER.NIT,TER.RAZONSOCIAL,FTR.IDPLAN,PLN.DESCPLAN,N_FACTURA,FTR.PROCEDENCIA,F_FACTURA,F_VENCE, 1 CANTIDAD, FTR.VALORSERVICIOS , FTR.VALORCOPAGO , FTR.VALORPCOMP ,FTR.DESCUENTO, FTR.VALORSERVICIOS-FTR.DESCUENTO-FTR.VALORCOPAGO - FTR.VALORPCOMP
          FROM   FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
                     INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
          WHERE  FTR.N_FACTURA NOT IN (SELECT N_FACTURA FROM #FTR)
          AND    F_FACTURA >= '''+CONVERT(VARCHAR(10),@F_INICIAL,103)+'''
          AND    F_FACTURA <  '''+CONVERT(VARCHAR(10),@F_FINAL + 1,103)+'''
          AND    COALESCE(FTR.IDSEDE,'''') = CASE  WHEN '''+@IDSEDEF+'''<>''Todas'' THEN '''+@IDSEDEF+''' ELSE COALESCE(FTR.IDSEDE,'''') END
          AND    FTR.PROCEDENCIA = CASE WHEN COALESCE('''+@PROCEDENCIA+''',''Todas'')=''Todas'' THEN FTR.PROCEDENCIA ELSE '''+@PROCEDENCIA+''' END ' +@PART+
          ''
          SELECT 'OK' OK
          EXECUTE(@SQL)
      END
   END   
END

