IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='URL_INTERFAX_CIPERU')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'URL_INTERFAX_CIPERU','URL Api Interfax rhapsody CI ','Alfanumerica',''
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='URL_API_QRYSTAL_PROD')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'URL_API_QRYSTAL_PROD','URL  Qrystalos Producción','Alfanumerica',''
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='URL_API_QRYSTAL_TEST')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'URL_API_QRYSTAL_TEST','URL  Qrystalos Entorno Pruebas','Alfanumerica',''
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='USER_API_PROD')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'USER_API_PROD','Credenciasles Usuario Api Produccion CIA,USUARIO,CLAVE','Alfanumerica',''
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='USER_API_TEST')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'USER_API_TEST','Credenciasles Usuario Api Produccion CIA,USUARIO,CLAVE','Alfanumerica',''
END
