CREATE OR ALTER PROCEDURE DBO.SPK_ENVIA_TRAMAS_CIPERU @ENDPOINT VARCHAR(256), @TRAMA VARCHAR(MAX),@OK VARCHAR(4) OUTPUT,  @RESPUESTA VARCHAR(MAX) OUTPUT
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @JWT_QRYSTALOS VARCHAR(MAX)
DECLARE @TABLA_TMP AS TABLE (ITEM INT IDENTITY(1,1), RESPONSE VARCHAR(MAX))
DECLARE @sUrl VARCHAR(3096) 
DECLARE @CREDENCIAL VARCHAR(100)
DECLARE @CIA VARCHAR(2) 
DECLARE @USER VARCHAR(20) 
DECLARE @CLAVE VARCHAR(20) 
DECLARE @obj INT
DECLARE @response VARCHAR(max)
DECLARE @Body VARCHAR(max) 
BEGIN
   PRINT 'SPK_ENVIA_TRAMAS_CIPERU '+COALESCE(@ENDPOINT,'SIN ENDPOINT')+','+COALESCE(@TRAMA,'SIN TRAMA')
   -- TRAIGO EL TOKEN
   EXEC SPK_GENERA_TOKEN_WEB @TRANSIENT='JWT_QRYSTALOS',@OK=@OK OUTPUT,  @JWT=@JWT_QRYSTALOS OUTPUT

   IF COALESCE(@OK,'KO')='KO' OR LEN(@JWT_QRYSTALOS)<20
   BEGIN
      SELECT @OK='KO',@RESPUESTA=@JWT_QRYSTALOS
      RETURN
   END
   PRINT 'VOY AL SERVICIO'
   --https://api-test.qrystalos.com/api/rhapsody
   SELECT @sUrl =LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('URL_INTERFAX_CIPERU')))
   SELECT @Body = @TRAMA
   EXEC sys.sp_OACreate 'MSXML2.ServerXMLHttp', @obj OUT
   EXEC sys.sp_OAMethod @obj, 'Open', NULL, 'POST', @sUrl, false
	EXEC sys.sp_OAMethod @Obj, 'setRequestHeader', null, 'Authorization', @JWT_QRYSTALOS
	EXEC sys.sp_OAMethod @Obj, 'setRequestHeader', null, 'EndPoint', @ENDPOINT
	EXEC sys.sp_OAMethod @Obj, 'setRequestHeader', null, 'Content-Type', 'application/json'
	EXEC SYS.sp_OAMethod @obj, 'send', null, @Body
	EXEC sys.sp_OAMethod @obj, 'responseText', @response OUTPUT

	IF @response IS NULL
	BEGIN
		INSERT INTO @TABLA_TMP(RESPONSE)
		EXEC sys.sp_OAGetProperty @obj, 'responseText'
		SELECT @response=RESPONSE FROM @TABLA_TMP
	END

	EXEC sys.sp_OADestroy @obj
   
   SELECT @RESPUESTA=@response
   RETURN
END
