IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IDFORMATOFTR_INV')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'IDFORMATOFTR_INV','Id formato Factura ventas desde Inventario','Alfanumerica',''
END