CREATE OR ALTER PROCEDURE DBO.SPQ_TGEN_COL
@JSON  NVARCHAR(MAX)
WITH ENCRYPTION
AS
DECLARE   @PARAMETROS  NVARCHAR(MAX) ,@MODELO           VARCHAR(100)  ,@METODO     VARCHAR(100) ,@USUARIO     VARCHAR(12)   ,@ID     INT
			,@FILTRO      VARCHAR(250)  ,@CAMPO            VARCHAR(100)  ,@TABLA      VARCHAR(250) ,@MODELOACT   NVARCHAR(MAX) ,@A      INT
			,@TABLAAUX    VARCHAR(15)   ,@CAMPOAUX         VARCHAR(20)   ,@CODIGOAUX  VARCHAR(20)  ,@QUERY       VARCHAR(MAX)
			,@DESCRIPCION VARCHAR(1000) ,@TGEN             NVARCHAR(MAX) ,@PROCESO    VARCHAR(20)  ,@OBSERVACION VARCHAR(MAX)  
         ,@GRUPO       VARCHAR(8)    ,@SYS_COMPUTERNAME VARCHAR(254)  ,@SEDE       VARCHAR(5)	,@IDENTITY    INT		,@DATO1 VARCHAR(100)
         ,@CODIGO VARCHAR (100) ,  @IDTGEN INT
BEGIN --TGEN
/*	SPQ_TGEN_COL
	Modulo:		CONFIGURACION TGEN
	Funcion:	Metodos para agregar, y actualizar la configuracion de TGEN 
	Metodos:	INSERT 
	Elabora:	Edgardo Martinez
	Fecha:		03-07-2024
	Modificado:
*/

   SET LANGUAGE Spanish
   SET DATEFORMAT dmy
   PRINT 'INGRESE'
   SELECT @A = ISJSON(@JSON)
   IF @A = 0
   BEGIN
     RAISERROR('Json: Formato Erroneo',16,1)
     RETURN
   END

   PRINT @json

	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)
	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON

   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200))
   -- TOMA DEL GRUPO, SYS_COMPUTERNAME, SEDE   DE ACUERDO AL USUARIO
   PRINT 'USUARIO:'+@USUARIO
   SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO) FROM USUSU WHERE USUARIO = @USUARIO
   SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME FROM USUSU WHERE USUARIO = @USUARIO
   SELECT @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
   IF COALESCE(@SEDE,'') = '' SELECT @SEDE = '01'
   PRINT 'SEDE='+@SEDE


SELECT * INTO #MODELOIN
FROM   OPENJSON (@PARAMETROS)   --TGEN
WITH (
	TABLA             varchar(15)   '$.TABLA',
	CAMPO             varchar(20)   '$.CAMPO',
	CODIGO            varchar(20)   '$.CODIGO',
	DESCRIPCION       varchar(1000) '$.DESCRIPCION',
	VALOR1            decimal(9)    '$.VALOR1',
	DATO1             varchar(255)  '$.DATO1',
	DFECHA            int			'$.DFECHA',
	OPCIONESLIBRES    int			'$.OPCIONESLIBRES',
	VALORINI          decimal(9)    '$.VALORINI',
	VALORFIN          decimal(9)    '$.VALORFIN',
	VALOR2            decimal(9)    '$.VALOR2',
	DATO2             varchar(255)  '$.DATO2',
	CHECK1            int			'$.CHECK1',
	CHECK2            int			'$.CHECK2',
	CHECK3            int			'$.CHECK3',
	CHECK4            int			'$.CHECK4',
	CHECK5            inT			'$.CHECK5',
	VALOR3            decimal(9)    '$.VALOR3',
	VALOR4            decimal(9)    '$.VALOR4',
	VALOR5            decimal(9)    '$.VALOR5',
	DATO3             varchar(255)  '$.DATO3',
	DATO4             varchar(255)  '$.DATO4',
	DATO5             varchar(255)  '$.DATO5',
	OBSERVACION       varchar(MAX)    '$.OBSERVACION',
	FECHA1            date          '$.FECHA1'
	)
		
	--select * from #MODELOIN

	IF @METODO = 'INSERT'
	BEGIN
		DECLARE @MAXTGEN INT
		PRINT '-----------------ENTRE AL INSERT '
		SELECT @MAXTGEN  = MAX(IDTGEN)+1 FROM TGEN
		PRINT @MAXTGEN 

		IF EXISTS( SELECT 1  FROM TGEN INNER JOIN #MODELOIN ON TGEN.TABLA = #MODELOIN.TABLA AND TGEN.CAMPO = #MODELOIN.CAMPO AND TGEN.CODIGO = #MODELOIN.CODIGO )
		BEGIN
			PRINT 'YA ESITE'
			INSERT INTO @TBLERRORES(ERROR) SELECT 'YA ESISTE ESTE REGISTRO EN LA TABLA GENERICA'
		END
		ELSE IF EXISTS( SELECT 1  FROM  #MODELOIN where TABLA IS NULL OR  CAMPO IS NULL  OR  CODIGO IS NULL )
		BEGIN
			PRINT 'FALTA UN DATO EN LOS CAMPOS TABLA , CAMPO O CODIGO '
			INSERT INTO @TBLERRORES(ERROR) SELECT 'FALTA UN DATO EN LOS CAMPOS TABLA , CAMPO O CODIGO '
		END
		ELSE IF NOT EXISTS( SELECT 1  FROM TGEN INNER JOIN #MODELOIN ON TGEN.TABLA = #MODELOIN.TABLA AND TGEN.CAMPO = #MODELOIN.CAMPO AND TGEN.CODIGO = #MODELOIN.CODIGO )
		BEGIN
			BEGIN TRY
				INSERT INTO TGEN(TABLA,CAMPO,CODIGO,DESCRIPCION,VALOR1,DATO1,DFECHA,OPCIONESLIBRES,VALORINI,VALORFIN,VALOR2,DATO2,CHECK1,CHECK2,CHECK3,CHECK4,CHECK5,VALOR3,VALOR4,VALOR5,DATO3,DATO4,DATO5,OBSERVACION,FECHA1)
				SELECT * from #MODELOIN           
				 SELECT 'OK' OK ,@IDENTITY CNS
				 RETURN
			 END TRY
			 BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			 END CATCH
		END
        
	END  ---INSERT
	
	IF @METODO = 'UPDATE'
	BEGIN
		PRINT 'ENTRE AL UPDATE '
		SELECT @IDTGEN = IDTGEN
		FROM  OPENJSON (@PARAMETROS)
		WITH (
		IDTGEN            int	        '$.IDTGEN'
		)
		PRINT @IDTGEN 
		IF  EXISTS( SELECT 1  FROM TGEN WHERE TGEN.IDTGEN = @IDTGEN)
		BEGIN
			BEGIN TRY
				UPDATE TGEN SET
				TABLA			=	#MODELOIN.TABLA,
				CAMPO			=  #MODELOIN.CAMPO,
				CODIGO          =  #MODELOIN.CODIGO,
				DESCRIPCION     =  #MODELOIN.DESCRIPCION,
				VALOR1          =  #MODELOIN.VALOR1,
				DATO1           =  #MODELOIN.DATO1,
				DFECHA          =  #MODELOIN.DFECHA,
				OPCIONESLIBRES  =  #MODELOIN.OPCIONESLIBRES,
				VALORINI        =  #MODELOIN.VALORINI,
				VALORFIN        =  #MODELOIN.VALORFIN,
				VALOR2          =  #MODELOIN.VALOR2,
				DATO2           =  #MODELOIN.DATO2,
				CHECK1          =  #MODELOIN.CHECK1,
				CHECK2          =  #MODELOIN.CHECK2,
				CHECK3          =  #MODELOIN.CHECK3,
				CHECK4          =  #MODELOIN.CHECK4,
				CHECK5          =  #MODELOIN.CHECK5,
				VALOR3          =  #MODELOIN.VALOR3,
				VALOR4          =  #MODELOIN.VALOR4,
				VALOR5          =  #MODELOIN.VALOR5,
				DATO3           =  #MODELOIN.DATO3,
				DATO4           =  #MODELOIN.DATO4,
				DATO5           =  #MODELOIN.DATO5,
				OBSERVACION     =  #MODELOIN.OBSERVACION,
				FECHA1          =  #MODELOIN.FECHA1
				FROM TGEN INNER JOIN #MODELOIN ON  TGEN.IDTGEN = @IDTGEN

				 SELECT 'OK' OK ,  @IDTGEN CNS
				 RETURN
			 END TRY
			 BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			 END CATCH
		END
	END

	IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
    BEGIN
		SELECT 'KO' OK
		SELECT ERROR FROM @TBLERRORES
		RETURN
    END
END




