IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_CUENTA_KMCOM' AND XTYPE='FN')
BEGIN
   DROP FUNCTION FNK_CUENTA_KMCOM
END

GO
CREATE FUNCTION DBO.FNK_CUENTA_KMCOM(
	@IDMODELOCONT	VARCHAR(20),
	@IDTIPOCONT	VARCHAR(20),
	@TIPO		VARCHAR(2),
	@PREFIJO	VARCHAR(20),
	@IDAREA		VARCHAR(20),
	@CCOSTO		VARCHAR(20),
	@CLASECONT	VARCHAR(1),
	@IDSERVICIO	VARCHAR(20)) 
RETURNS VARCHAR(16)
WITH ENCRYPTION
AS
BEGIN
 DECLARE @CUENTA VARCHAR(16)
-- IF @CLASECONT='S'
-- BEGIN
  SET @CUENTA=(SELECT TOP 1 CUENTA 
	            FROM   KMCOMS 
               WHERE  IDMODELOCONT = @IDMODELOCONT 
               AND    IDTIPOCONT   = @IDTIPOCONT 
               AND    TIPO         = @TIPO 
               AND    PREFIJO      = @PREFIJO 
               AND    IDAREA       = @IDAREA 
               AND    CCOSTO       = @CCOSTO 
               AND    IDSERVICIO   = @IDSERVICIO)
-- END
 IF @CUENTA IS NULL OR @CUENTA='' --OR @CLASECONT='P'
 BEGIN
   SET @CUENTA=(SELECT TOP 1 CUENTA 
	             FROM   KMCOM 
                WHERE  IDMODELOCONT = @IDMODELOCONT 
                AND    IDTIPOCONT   = @IDTIPOCONT 
                AND    TIPO         = @TIPO 
                AND    PREFIJO      = @PREFIJO 
                AND    IDAREA       = @IDAREA 
                AND    CCOSTO       = @CCOSTO)
 END
 IF @CUENTA IS NULL OR @CUENTA=''
    SET @CUENTA = 'NO DEF.KMCOM'
 RETURN(@CUENTA)
END


