IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NEMP'  AND   C.NAME = 'TERCEROID')
BEGIN
   ALTER TABLE NEMP ADD TERCEROID VARCHAR(20) NOT NULL
END
IF EXISTS(SELECT * FROM NEMP WHERE COALESCE(TERCEROID,'') = '')
BEGIN
   UPDATE NEMP SET TERCEROID = NUMDOC WHERE COALESCE(TERCEROID,'') = ''
END
IF NOT EXISTS(SELECT * FROM SYS.indexes WHERE name='NEMPTERCEROID')
BEGIN
   CREATE UNIQUE INDEX NEMPTERCEROID ON NEMP (TERCEROID,NUMDOC)
END
