IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FGLOCG'  AND   C.NAME = 'OBSERVACION')
BEGIN
   ALTER TABLE FGLOCG  ADD  OBSERVACION VARCHAR(1024)
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FCXPI'  AND   C.NAME = 'TERDIF')
BEGIN
   ALTER TABLE FCXPI   ADD  TERDIF BIT
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FCXPI'  AND   C.NAME = 'IDTERCEROIMP')
BEGIN
   ALTER TABLE FCXPI   ADD  IDTERCEROIMP VARCHAR(20)
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='MBUSQUEDAFTR')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_ADMINISTRATIVO', 'MBUSQUEDAFTR', 'M', 'Busqueda Facturas', 1, 'admin.BuscarFact', 'fa-solid fa-minimize', null, 0, NULL, 16, 'Ubicación, Traspasos, Cuentas', null, NULL
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='MSEGUIMIENTO')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_ADMINISTRATIVO', 'MSEGUIMIENTO', 'M', 'Seguimiento de Cartera', 1, 'admin.SeguiCXC', 'fa-solid fa-phone-volume', 100, 0, NULL, 16, 'Gestión de Clientes,Cartera', null, NULL
END
