IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'TK_PTPAG_UPDATE' AND TYPE = 'TR')
   DROP TRIGGER TK_PTPAG_UPDATE

GO
CREATE TRIGGER DBO.TK_PTPAG_UPDATE
ON PTPAG
WITH ENCRYPTION
FOR UPDATE
AS 
 DECLARE @COMPANIA VARCHAR(2)
 DECLARE @CONSECUTIVO VARCHAR(20)
 DECLARE @MES INT
 DECLARE @CLASE VARCHAR(10)
 DECLARE @RUBRO VARCHAR(50)
 DECLARE @ESTADO VARCHAR(12)
 DECLARE @VALOR DECIMAL(14,2)
 DECLARE @CDP VARCHAR(20)
 DECLARE @RP  VARCHAR(20)
 DECLARE @CNSCXP  VARCHAR(20) 
 DECLARE @CNSPAGO  VARCHAR(20)
 DECLARE @ITEM SMALLINT
 DECLARE @CONT INT
 DECLARE @CCOSTO VARCHAR(20)
 DECLARE @IDTIPOMOV VARCHAR(2)
 DECLARE @VIGENCIA  VARCHAR(10)
 DECLARE @ITEMCDPD SMALLINT
 PRINT 'M'
--  SELECT @CONT = COUNT(*)
--  FROM INSERTED A WHERE A.ESTADO='Confirmado'
--  IF @CONT > 0
--  BEGIN
--   RAISERROR ('No es posible modificar un registro Confirmado.', 16, 1)
--   ROLLBACK TRANSACTION
--   RETURN
--  END

 IF (SELECT COUNT(*) 
     FROM INSERTED A INNER JOIN PTPTO B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO 
     WHERE B.ESTADO='Cerrado')>0
 BEGIN
     RAISERROR ('ERROR: El Presupuesto se encuentra Cerrado', 16, 1)
     ROLLBACK TRANSACTION
     RETURN
 END

 SELECT @CONT = COUNT(*) 
 FROM INSERTED A INNER JOIN
      PTCXP   B ON A.COMPANIA = B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND 
                   A.CNSCXP=B.CNSCXP
 WHERE B.ESTADO<>'Confirmado'
 IF @CONT > 0
 BEGIN
  RAISERROR ('No es posible Modificar Registros en un PAGO con %d. CXP No Confirmada.', 16, 1, @CONT)
  ROLLBACK TRANSACTION
  RETURN
 END

 SELECT @CONT = COUNT(*)
 FROM INSERTED A INNER JOIN
      PTPAGD B ON A.COMPANIA = B.COMPANIA AND A.CONSECUTIVO = B.CONSECUTIVO AND A.CDP = B.CDP AND A.RP=B.RP AND 
                  A.CNSCXP=B.CNSCXP AND A.CNSPAGO=B.CNSPAGO LEFT JOIN
      PTPTOG C ON B.COMPANIA = C.COMPANIA AND B.CONSECUTIVO = C.CONSECUTIVO AND B.CLASE = C.CLASE AND 
                  B.RUBRO = C.RUBRO AND A.CCOSTO = C.CCOSTO
 WHERE C.CONSECUTIVO IS NULL

 IF @CONT > 0
 BEGIN
  RAISERROR ('Hay %d Rubro(s) que no tienen Saldos en el Presupuesto de Gastos. Revice los saldos.', 16, 1, @CONT)
  ROLLBACK TRANSACTION
  RETURN
 END

 UPDATE PTCXPD
 SET VALOR_PAG = ISNULL(B.VALOR,0)
 FROM PTCXPD A INNER JOIN
      INSERTED C ON A.COMPANIA=C.COMPANIA AND A.CONSECUTIVO=C.CONSECUTIVO AND A.CDP=C.CDP AND A.RP=C.RP AND 
                    A.CNSCXP = C.CNSCXP LEFT JOIN
      (SELECT A.COMPANIA, A.CONSECUTIVO, A.CDP, A.RP, A.CNSCXP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD, SUM(A.VALOR) VALOR 
       FROM PTPAGD A INNER JOIN
            PTPAG  B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND 
                        A.CNSCXP=B.CNSCXP AND A.CNSPAGO=B.CNSPAGO
       WHERE B.ESTADO = 'Confirmado'
       GROUP BY A.COMPANIA, A.CONSECUTIVO, A.CDP, A.RP, A.CNSCXP, A.CLASE, A.RUBRO, B.CCOSTO,A.ITEMCDPD) B ON
        A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP=B.CDP AND A.RP=B.RP AND A.CNSCXP = B.CNSCXP AND
        A.CLASE=B.CLASE AND A.RUBRO=B.RUBRO AND C.CCOSTO = B.CCOSTO AND A.ITEMCDPD =B.ITEMCDPD

 DECLARE CUR CURSOR FOR  
 SELECT A.COMPANIA, A.CCOSTO, A.CONSECUTIVO, MONTH(A.FECHA), B.CLASE, B.RUBRO, A.ESTADO, B.VALOR, 
        A.CDP, A.RP, A.CNSCXP, A.CNSPAGO,B.ITEMCDPD
 FROM INSERTED A INNER JOIN
      PTPAGD B ON A.COMPANIA=B.COMPANIA AND A.CONSECUTIVO=B.CONSECUTIVO AND A.CDP = B.CDP AND A.RP=B.RP AND 
                  A.CNSCXP=B.CNSCXP AND A.CNSPAGO=B.CNSPAGO INNER JOIN
      DELETED C ON A.COMPANIA=C.COMPANIA AND A.CONSECUTIVO=C.CONSECUTIVO AND A.CDP = C.CDP AND A.RP=C.RP AND 
                   A.CNSCXP=C.CNSCXP AND A.CNSPAGO=C.CNSPAGO
 WHERE A.ESTADO <> C.ESTADO AND NOT C.ESTADO IS NULL

 OPEN CUR

 FETCH NEXT FROM CUR
 INTO @COMPANIA, @CCOSTO, @CONSECUTIVO, @MES, @CLASE, @RUBRO, @ESTADO, @VALOR, @CDP, @RP, @CNSCXP, @CNSPAGO,@ITEMCDPD

 WHILE @@FETCH_STATUS = 0
 BEGIN
  PRINT 'ESTOY DENTRO'
  SELECT @IDTIPOMOV = B.CLASIFICACION,@VIGENCIA=COALESCE(A.VIGENCIA,'Actual')  
  FROM PTCDPD A INNER JOIN PTTMOV B ON A.COMPANIA=B.COMPANIA AND A.IDTIPOMOV=B.IDTIPOMOV
  WHERE A.COMPANIA = @COMPANIA AND A.CONSECUTIVO = @CONSECUTIVO AND A.CDP = @CDP AND A.CLASE = @CLASE AND A.RUBRO = @RUBRO
  AND A.ITEM=@ITEMCDPD

  PRINT '@ITEMCDPD '+STR(@ITEMCDPD)
  PRINT '@VIGENCIA='+COALESCE(@VIGENCIA,'NADA DE NADA')

  IF @ESTADO = 'Confirmado'
  BEGIN
   IF @MES = 1
    UPDATE PTPTOG   
    SET PAG01 = COALESCE(PAG01,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA01=COALESCE(PAGA01,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
    ELSE
   IF @MES = 2
    UPDATE PTPTOG   
    SET PAG02 = COALESCE(PAG02,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA02=COALESCE(PAGA02,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 3
    UPDATE PTPTOG   
     SET PAG03 = COALESCE(PAG03,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA03=COALESCE(PAGA03,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 4
    UPDATE PTPTOG   
    SET PAG04 = COALESCE(PAG04,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA04=COALESCE(PAGA04,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 5
    UPDATE PTPTOG   
     SET PAG05 = COALESCE(PAG05,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA05=COALESCE(PAGA05,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 6
    UPDATE PTPTOG   
    SET PAG06 = COALESCE(PAG06,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA06=COALESCE(PAGA06,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 7
    UPDATE PTPTOG   
     SET PAG07 = COALESCE(PAG07,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA07=COALESCE(PAGA07,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 8
    UPDATE PTPTOG   
     SET PAG08 = COALESCE(PAG08,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA08=COALESCE(PAGA08,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 9
    UPDATE PTPTOG   
     SET PAG09 = COALESCE(PAG09,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA09=COALESCE(PAGA09,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 10
   UPDATE PTPTOG   
    SET PAG10 = COALESCE(PAG10,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA10=COALESCE(PAGA10,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 11
    UPDATE PTPTOG   
    SET PAG11 = COALESCE(PAG11,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA11=COALESCE(PAGA11,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 12
    UPDATE PTPTOG   
    SET PAG12 = COALESCE(PAG12,0) +CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA12=COALESCE(PAGA12,0)+ CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
  END
  ELSE
  IF @ESTADO = 'NoConfirmado' OR @ESTADO = 'Vencido' OR @ESTADO = 'Anulado'
  BEGIN
   IF @MES = 1
    UPDATE PTPTOG   
     SET PAG01 = COALESCE(PAG01,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA01=COALESCE(PAGA01,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 2
    UPDATE PTPTOG   
    SET PAG02 = COALESCE(PAG02,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA02=COALESCE(PAGA02,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 3
    UPDATE PTPTOG   
    SET PAG03 = COALESCE(PAG03,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA03=COALESCE(PAGA03,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 4
    UPDATE PTPTOG   
    SET PAG04 = COALESCE(PAG04,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA04=COALESCE(PAGA04,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 5
    UPDATE PTPTOG   
    SET PAG05 = COALESCE(PAG05,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA05=COALESCE(PAGA05,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 6
    UPDATE PTPTOG   
    SET PAG06 = COALESCE(PAG06,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA06=COALESCE(PAGA06,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 7
    UPDATE PTPTOG   
    SET PAG07 = COALESCE(PAG07,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA07=COALESCE(PAGA07,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 8
    UPDATE PTPTOG   
    SET PAG08 = COALESCE(PAG08,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA08=COALESCE(PAGA08,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 9
    UPDATE PTPTOG   
    SET PAG09 = COALESCE(PAG09,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA09=COALESCE(PAGA09,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 10
   UPDATE PTPTOG   
    SET PAG10 = COALESCE(PAG10,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA10=COALESCE(PAGA10,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 11
    UPDATE PTPTOG   
     SET PAG11 = COALESCE(PAG11,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA11=COALESCE(PAGA11,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
   ELSE
   IF @MES = 12
    UPDATE PTPTOG   
     SET PAG12 = COALESCE(PAG12,0) -CASE WHEN @VIGENCIA='Actual'  THEN   @VALOR ELSE 0 END, PAGA12=COALESCE(PAGA12,0)- CASE WHEN  @VIGENCIA='Actual' THEN  0   ELSE @VALOR END
    WHERE COMPANIA = @COMPANIA AND CONSECUTIVO = @CONSECUTIVO AND CLASE = @CLASE AND RUBRO = @RUBRO AND CCOSTO=@CCOSTO AND IDTIPOMOV = @IDTIPOMOV
  END
  FETCH NEXT FROM CUR
  INTO @COMPANIA, @CCOSTO, @CONSECUTIVO, @MES, @CLASE, @RUBRO, @ESTADO, @VALOR, @CDP, @RP, @CNSCXP, @CNSPAGO,@ITEMCDPD
 END
 DEALLOCATE CUR


