IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'QXRCN'  AND   C.NAME = 'TIPODOC')
BEGIN
   ALTER TABLE QXRCN  ADD TIPODOC VARCHAR(2) 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'QXRCN'  AND   C.NAME = 'NRODOCUMENTO')
BEGIN
   ALTER TABLE QXRCN  ADD NRODOCUMENTO VARCHAR(20) 
END