IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='FNK_VLR_SERVICIO')
BEGIN
   DROP FUNCTION FNK_VLR_SERVICIO
END

GO
CREATE FUNCTION DBO.FNK_VLR_SERVICIO(@IDTERCERO VARCHAR(20), @IDSERVICIO VARCHAR(20), @IDPLAN VARCHAR(6), 
                                     @IDAREA VARCHAR(20), @FECHA DATETIME) 
RETURNS DECIMAL(14,2)
AS   
BEGIN
   DECLARE @VALOR        DECIMAL(14,2)  
   DECLARE @CIRUGIA      SMALLINT
   DECLARE @IDTARIFA     VARCHAR(5)
   DECLARE @FACTORDINERO DECIMAL(10,2)
   -- INICIO: RECARGO NOCTURNO
   DECLARE @TIPRECARGONOC    VARCHAR(10)
   DECLARE @CONT             INT
   DECLARE @VLRRECCARGONOC   DECIMAL(14,2)
   DECLARE @HIRECNOC         INT
   DECLARE @HFRECNOC         INT
   DECLARE @DIASIGRN         SMALLINT
   DECLARE @LUNES            SMALLINT 
   DECLARE @MARTES           SMALLINT 
   DECLARE @MIERCOLES        SMALLINT 
   DECLARE @JUEVES           SMALLINT 
   DECLARE @VIERNES          SMALLINT 
   DECLARE @SABADO           SMALLINT 
   DECLARE @DOMINGO          SMALLINT 
   DECLARE @FESTIVOTOTAL     SMALLINT 
   DECLARE @DOMIGOTOTAL      SMALLINT 
   DECLARE @DHOY             INT
	DECLARE @PAQUETE			  BIT
	DECLARE @FECHASINH		  DATE
   DECLARE @MIN_HI INT, @HOR_HI INT, @MIN_HID INT, @MIN_HF INT, @HOR_HF INT, @MIN_HFD INT, @FI_RN DATETIME, @FF_RN DATETIME   

	SET @FECHASINH = DBO.FNK_FECHA_SIN_HORA(@FECHA)

   -- FIN: RECARGO NOCTURNO  
   SELECT @VALOR = ISNULL(VLRSERVICIO,0), @CIRUGIA = CIRUGIA, @IDTARIFA = IDTARIFA, @PAQUETE = ISNULL(PAQUETE,0)
   FROM   SERTOT 
   WHERE  IDTERCERO  = @IDTERCERO
   AND    IDPLAN     = @IDPLAN
   AND    IDSERVICIO = @IDSERVICIO
   AND    @FECHA BETWEEN FECHAINIFD AND FECHAFINFD
   AND    @FECHA BETWEEN FECHAINI   AND FECHAFIN
   --AND    IDAREACA   = @IDAREA   
   SELECT @VALOR = COALESCE(@VALOR,0)
   SELECT @CONT = COUNT(1) 
   FROM   FES 
   WHERE  FECHA = @FECHASINH
        
   SELECT @DHOY  = DATEPART(DW, @FECHASINH)
            
   SELECT @TIPRECARGONOC = RNXT.TIPORECARGONOC, @VLRRECCARGONOC = RNXT.VLRRECARGONOC,
          @HIRECNOC      = RNXT.HIRECNOC,       @HFRECNOC       = RNXT.HFRECNOC, 
          @DIASIGRN      = RNXT.DIASIGRN,       @LUNES          = RNXT.LUNES,
          @MARTES        = RNXT.MARTES,         @MIERCOLES      = RNXT.MIERCOLES,
          @JUEVES        = RNXT.JUEVES,         @VIERNES        = RNXT.VIERNES,
          @SABADO        = RNXT.SABADO,         @DOMINGO        = RNXT.DOMINGO,
          @FESTIVOTOTAL  = RNXT.FESTIVOTOTAL,   @DOMIGOTOTAL    = RNXT.DOMIGOTOTAL,
          @MIN_HI  = (RNXT.HIRECNOC/100)/60,     @MIN_HF = (RNXT.HFRECNOC/100)/60,
          @HOR_HI  = ((RNXT.HIRECNOC/100)/60) / 60,
          @HOR_HF  = ((RNXT.HFRECNOC/100)/60) / 60,
          @MIN_HID = ((RNXT.HIRECNOC/100)/60) - ((((RNXT.HIRECNOC/100)/60) / 60) * 60),
          @MIN_HFD = ((RNXT.HFRECNOC/100)/60) - ((((RNXT.HFRECNOC/100)/60) / 60) * 60)      
   FROM   RNXT INNER JOIN SER ON RNXT.PREFIJO   = SER.PREFIJO 
   WHERE  RNXT.IDTERCERO = @IDTERCERO
   AND    RNXT.IDPLAN    = @IDPLAN
   AND    SER.IDSERVICIO = @IDSERVICIO  
                      
   IF @CONT > 0
   BEGIN
      IF @FESTIVOTOTAL = 1
      BEGIN
         IF @TIPRECARGONOC IS NOT NULL
         BEGIN
            IF @VLRRECCARGONOC IS NOT NULL
            BEGIN
               IF @TIPRECARGONOC = 'Valor'
               BEGIN
                  SELECT  @VALOR = @VALOR + @VLRRECCARGONOC 
               END
               ELSE
               BEGIN
                  SELECT  @VALOR = @VALOR * ( 1 + ( @VLRRECCARGONOC / 100 ) )
               END
            END
         END
      END   
   END
   ELSE
   BEGIN 
      IF DATEPART(HOUR, @FECHA) <= 7
      BEGIN
         SELECT @DHOY = @DHOY -1 
         IF @DHOY = 0 
         BEGIN
            SELECT @DHOY = 7
         END
      END
      IF    (@DHOY = 1 AND @LUNES = 1)   OR (@DHOY = 2 AND @MARTES = 1) OR (@DHOY = 3 AND @MIERCOLES = 1) OR (@DHOY = 4 AND @JUEVES = 1)
            OR (@DHOY = 5 AND @VIERNES = 1) OR (@DHOY = 6 AND @SABADO = 1) OR (@DHOY = 7 AND @DOMINGO = 1)
      BEGIN
         SELECT @FI_RN = CONVERT(DATETIME, (CONVERT(VARCHAR(10),@FECHASINH, 103)+' '+CAST(@HOR_HI AS VARCHAR(2))+':'+CAST(@MIN_HID AS VARCHAR(2))+':00.000'))
         IF @DIASIGRN = 1
         BEGIN
            SELECT @FF_RN = CONVERT(DATETIME, (CONVERT(VARCHAR(10),DBO.FNK_FECHA_SIN_HORA(@FECHA+1), 103)+' '+CAST(@HOR_HF AS VARCHAR(2))+':'+CAST(@MIN_HFD AS VARCHAR(2))+':59.999'))
         END
         ELSE
         BEGIN
            SELECT @FF_RN = CONVERT(DATETIME, (CONVERT(VARCHAR(10),@FECHASINH, 103)+' '+CAST(@HOR_HF AS VARCHAR(2))+':'+CAST(@MIN_HFD AS VARCHAR(2))+':59.999'))
         END                                      
         IF @FECHA >= @FI_RN AND @FECHA <= @FF_RN
         BEGIN
            IF @TIPRECARGONOC = 'Valor'
            BEGIN
               SELECT  @VALOR = @VALOR + @VLRRECCARGONOC 
            END   
            ELSE
            BEGIN
               SELECT  @VALOR = @VALOR * ( 1 + ( @VLRRECCARGONOC / 100 ) )
            END   
         END
      END
   END
     
   IF @CIRUGIA = 1 AND @PAQUETE=0
   BEGIN 
      SELECT @FACTORDINERO = FACTORDINERO
      FROM   TARF
      WHERE  IDTARIFA      = @IDTARIFA
      AND    @FECHA BETWEEN FECHAINI AND FECHAFIN
      
      SELECT @VALOR = @VALOR * @FACTORDINERO
   END
   IF RIGHT(CONVERT(DECIMAL(14,2),@VALOR),2)>0 AND 
      EXISTS(SELECT   *    FROM   TARF
      WHERE  IDTARIFA      = @IDTARIFA
      AND    @FECHA BETWEEN FECHAINI AND FECHAFIN
      AND REDONDEO='Centena')
   BEGIN
      SELECT @VALOR=ROUND(@VALOR,0)
   END
   RETURN(@VALOR)
END

