IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'FNPAG'  AND   C.NAME = 'ESTADO_OPE')
BEGIN
   ALTER TABLE FNPAG  ADD ESTADO_OPE VARCHAR(20) 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'PTRUB'  AND   C.NAME = 'CPC')
BEGIN
   ALTER TABLE PTRUB  ADD CPC VARCHAR(20) 
END