CREATE OR ALTER  FUNCTION DBO.FNK_TRAE_TIPOCOPAGO(@NOPRESTACION VARCHAR(20),@PROCEDENCIA VARCHAR(10))
RETURNS VARCHAR(5)
AS
BEGIN
   DECLARE @TCOPAGO VARCHAR(10)
   DECLARE @TSISTEMA VARCHAR(20)
   DECLARE @VLRCOPAGO DECIMAL(14,2)
   DECLARE @COPAPROPIO BIT
   DECLARE @TCOPAPROPIO VARCHAR(3)
   DECLARE @IDPLAN VARCHAR(7)
   IF @PROCEDENCIA='CI'
   BEGIN
      SELECT @VLRCOPAGO=COALESCE(VALORCOPAGO,0),@COPAPROPIO=COALESCE(COPAGOPROPIO,0),@TCOPAPROPIO=COALESCE(TIPOCOPAGO,''),@IDPLAN=IDPLAN  FROM CIT WHERE CONSECUTIVO=@NOPRESTACION
   END
   IF @PROCEDENCIA='CE'
   BEGIN
      SELECT @VLRCOPAGO=COALESCE(VALORCOPAGO,0),@COPAPROPIO=COALESCE(COPAGOPROPIO,0),@TCOPAPROPIO=COALESCE(TIPOCOPAGO,''),@IDPLAN=IDPLAN  FROM AUT WHERE NOAUT=@NOPRESTACION
   END
   IF COALESCE(@VLRCOPAGO,0)>0
   BEGIN
      SELECT @TSISTEMA=TIPOSISTEMA FROM PLN WHERE IDPLAN=@IDPLAN
      IF @TSISTEMA='Prepagado'
      BEGIN
         SELECT @TCOPAGO='03'
      END
      ELSE
      BEGIN
         IF  @COPAPROPIO=0
         BEGIN
            SELECT @TCOPAGO=CASE WHEN @TCOPAPROPIO='M' THEN '02' ELSE '01' END
         END
         ELSE
         BEGIN
            IF @TSISTEMA='Contributivo' AND EXISTS(SELECT * FROM MOCCD WHERE TIPODEPAGO='Moderadora' AND VALOR=@VLRCOPAGO)
            BEGIN
                SELECT @TCOPAGO='02'
            END
            ELSE
            BEGIN
               SELECT @TCOPAGO='01'
            END
         END
      END
   END
   ELSE
   BEGIN 
      SELECT @TCOPAGO='05'
   END  
   RETURN @TCOPAGO
END