IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURACE_MASMA' AND XTYPE='P')
BEGIN
 DROP PROCEDURE SPK_FACTURACE_MASMA
END

GO
CREATE PROCEDURE  DBO.SPK_FACTURACE_MASMA
@CNSRPDX VARCHAR(20),
@NIT VARCHAR(20),
@COMPANIA VARCHAR(2),
@IDSEDE  VARCHAR(5),
@USUARIO VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @IDTERCERO VARCHAR(20),@PRE VARCHAR(20), @CONSECFTR INT, @CNSRESOL VARCHAR(50)
DECLARE @FECHAINI  DATETIME
DECLARE @FECHAFIN  DATETIME
DECLARE @NOAUT     VARCHAR(16) 
DECLARE @IDPLAN    VARCHAR(6)
DECLARE @PYP       DECIMAL(14,2)
DECLARE @TIPOPLAN  DECIMAL(14,2) 
DECLARE @CLASEORDEN VARCHAR(10)
DECLARE @PRE1 VARCHAR(6)
DECLARE @PRE2 VARCHAR(6)
DECLARE @PRE3 VARCHAR(6)
DECLARE @PRE4 VARCHAR(6)
DECLARE @PRE5 VARCHAR(6) 
DECLARE @OK   INT
DECLARE @DV   INT
DECLARE @DATO VARCHAR(80)
DECLARE @NVOCONSEC  VARCHAR(20)
DECLARE @CNSFTR     VARCHAR(20)
DECLARE @CERRADA    SMALLINT
DECLARE @DATO1      VARCHAR(80)
DECLARE @CCOSTO     VARCHAR(20)
DECLARE @IDAREA     VARCHAR(20)
DECLARE @EC          SMALLINT
DECLARE @DESCUENTO   DECIMAL(14,2)
DECLARE @TIPODTO     VARCHAR(1)
DECLARE @VRTOTAL     DECIMAL(14,2)
DECLARE @VRSERV      DECIMAL(14,2)
DECLARE @VRCOPA      DECIMAL(14,2)
DECLARE @VRPACO      DECIMAL(14,2)
DECLARE @VRDTO       DECIMAL(14,2)
DECLARE @VRABONO     DECIMAL(14,2)
DECLARE @DATO3       VARCHAR(20)
DECLARE @DATOCCOSTO  VARCHAR(80)
DECLARE @TTEC        VARCHAR(10)
DECLARE @CUENTACXC   VARCHAR(16)
DECLARE @CUENTACXC_RAD   VARCHAR(16)
DECLARE @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @IDFORMATOFTR     VARCHAR(20)
BEGIN
   SET @SYS_COMPUTERNAME = HOST_NAME()
   SELECT @DATOCCOSTO = DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
   
   SELECT @IDTERCERO = IDTERCERO, @FECHAINI = FECHA1, @FECHAFIN = FECHA2, @IDPLAN = ID1,
          @PYP = VALOR1, @PRE1 = CNS1, @PRE2 = CNS2, @PRE3 = CNS3, @PRE4 = CNS4, @PRE5 = CNS5,
          @TIPOPLAN = VALOR2  
   FROM RPDX WHERE CNS = @CNSRPDX
   
   SELECT @DV = DIASVTO FROM PPT WHERE IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN
   SELECT @DATO3 = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'          
   SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDMONEDABASE'
   SELECT @OK   = COUNT(*) FROM TER WHERE IDTERCERO = @IDTERCERO
           
   IF  @OK IS NULL
       SELECT @OK = 0
          
   IF @OK = 0
      RETURN
   
   CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	int IDENTITY, FECHA datetime,
                DB_CR varchar(2), AREAPRESTACION varchar(20), UBICACION varchar(16),
                VR_TOTAL float, IMPUTACION varchar(16), CCOSTO varchar (20),
                PREFIJO varchar(6), ANEXO varchar(1024), REFERENCIA varchar(40), 
                IDCIRUGIA varchar(20), CANTIDAD smallint, VALOR decimal(14,2),
                VLR_SERVICI decimal(14,2), VLR_COPAGOS decimal(14,2),
                VLR_PAGCOMP decimal(14,2), IDPROVEEDOR varchar(20),
                NOADMISION varchar(16), NOPRESTACION	varchar(16), NOITEM int,
                PROCEDENCIA VARCHAR(10),TCOPAGO VARCHAR(10),
                AREAFUNCONT varchar(20), N_FACTURA varchar(16),
                SUBCCOSTO varchar(4), PCOSTO	decimal(14,2), FECHAPREST datetime)
   IF @PYP = 1   
   BEGIN                
      IF @DATOCCOSTO = 'SER:CCOSTO'
      BEGIN
         INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
         SELECT @CNSFTR, GETDATE(), 'DB', @IDAREA, NULL, (AUTD.CANTIDAD * AUTD.VALOR) - AUTD.VALORCOPAGO, 
                NULL, AUTD.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL,
                AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), AUTD.VALORCOPAGO,
                0, AUT.IDPROVEEDOR, @NOAUT, @NOAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA ,
                'CE',DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
         FROM   AUT, AUTD, SER 
         WHERE  AUT.IDCONTRATANTE = @IDTERCERO
         AND    AUT.FACTURADA  = 0
         AND    AUT.ESTADO     <> 'Anulada'
         AND    AUT.FECHA BETWEEN @FECHAINI AND @FECHAFIN
         AND    AUT.IDPLAN     = @IDPLAN
         AND    AUTD.IDAUT     = AUT.IDAUT 
         AND    SER.IDSERVICIO = AUTD.IDSERVICIO 
         AND    SER.PREFIJO    <> @PRE1
         AND    SER.PREFIJO    <> @PRE2
         AND    SER.PREFIJO    <> @PRE3
         AND    SER.PREFIJO    <> @PRE4
         AND    SER.PREFIJO    <> @PRE5        
         AND    AUT.CLASEORDEN = 'PyP' 
      END
      ELSE
      BEGIN
         INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
         SELECT @CNSFTR, GETDATE(), 'DB', @IDAREA, NULL, (AUTD.CANTIDAD * AUTD.VALOR) - AUTD.VALORCOPAGO, 
                NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL,
                AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), AUTD.VALORCOPAGO,
                0, AUT.IDPROVEEDOR, @NOAUT, @NOAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA,
                'CE',DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
         FROM   AUT, AUTD, SER 
         WHERE  AUT.IDCONTRATANTE = @IDTERCERO
         AND    AUT.FACTURADA  = 0
         AND    AUT.ESTADO     <> 'Anulada'
         AND    AUT.FECHA BETWEEN @FECHAINI AND @FECHAFIN
         AND    AUT.IDPLAN     = @IDPLAN
         AND    AUTD.IDAUT     = AUT.IDAUT 
         AND    SER.IDSERVICIO = AUTD.IDSERVICIO 
         AND    SER.PREFIJO    <> @PRE1
         AND    SER.PREFIJO    <> @PRE2
         AND    SER.PREFIJO    <> @PRE3
         AND    SER.PREFIJO    <> @PRE4
         AND    SER.PREFIJO    <> @PRE5        
         AND    AUT.CLASEORDEN = 'PyP' 
      END
   END
   IF @PYP = 2
      IF @DATOCCOSTO = 'SER:CCOSTO'
      BEGIN
         INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
         SELECT @CNSFTR, GETDATE(), 'DB', @IDAREA, NULL, (AUTD.CANTIDAD * AUTD.VALOR) - AUTD.VALORCOPAGO, 
                NULL, AUTD.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL,
                AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), AUTD.VALORCOPAGO,
                0, AUT.IDPROVEEDOR, @NOAUT, @NOAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA,
                'CE',DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
         FROM   AUT, AUTD, SER 
   
         WHERE  AUT.IDCONTRATANTE = @IDTERCERO
         AND    AUT.FACTURADA  = 0
         AND    AUT.ESTADO     <> 'Anulada'
         AND    AUT.FECHA BETWEEN @FECHAINI AND @FECHAFIN
         AND    AUT.IDPLAN     = @IDPLAN
         AND    AUTD.IDAUT     = AUT.IDAUT 
         AND    SER.IDSERVICIO = AUTD.IDSERVICIO 
         AND    SER.PREFIJO    <> @PRE1
         AND    SER.PREFIJO    <> @PRE2
         AND    SER.PREFIJO    <> @PRE3
         AND    SER.PREFIJO    <> @PRE4
         AND    SER.PREFIJO    <> @PRE5        
         AND    AUT.CLASEORDEN <> 'PyP' 
      END
      ELSE
      BEGIN
         INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
         SELECT @CNSFTR, GETDATE(), 'DB', @IDAREA, NULL, (AUTD.CANTIDAD * AUTD.VALOR) - AUTD.VALORCOPAGO, 
                NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL,
                AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), AUTD.VALORCOPAGO,
                0, AUT.IDPROVEEDOR, @NOAUT, @NOAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA,
                'CE',DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
         FROM   AUT, AUTD, SER 
         WHERE  AUT.IDCONTRATANTE = @IDTERCERO
         AND    AUT.FACTURADA  = 0
         AND    AUT.ESTADO     <> 'Anulada'
         AND    AUT.FECHA BETWEEN @FECHAINI AND @FECHAFIN
         AND    AUT.IDPLAN     = @IDPLAN
         AND    AUTD.IDAUT     = AUT.IDAUT 
         AND    SER.IDSERVICIO = AUTD.IDSERVICIO 
         AND    SER.PREFIJO    <> @PRE1
         AND    SER.PREFIJO    <> @PRE2
         AND    SER.PREFIJO    <> @PRE3
         AND    SER.PREFIJO    <> @PRE4
         AND    SER.PREFIJO    <> @PRE5        
         AND    AUT.CLASEORDEN <> 'PyP' 
      END
   IF @PYP = 3
      IF @DATOCCOSTO = 'SER:CCOSTO'
      BEGIN
         INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
         SELECT @CNSFTR, GETDATE(), 'DB', @IDAREA, NULL, (AUTD.CANTIDAD * AUTD.VALOR) - AUTD.VALORCOPAGO, 
                NULL, AUTD.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL,
                AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), AUTD.VALORCOPAGO,
                0, AUT.IDPROVEEDOR, @NOAUT, @NOAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA,
                'CE',DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
         FROM   AUT, AUTD, SER 
         WHERE  AUT.IDCONTRATANTE = @IDTERCERO
         AND    AUT.FACTURADA  = 0
         AND    AUT.ESTADO     <> 'Anulada'
         AND    AUT.FECHA BETWEEN @FECHAINI AND @FECHAFIN
         AND    AUT.IDPLAN     = @IDPLAN
         AND    AUTD.IDAUT     = AUT.IDAUT 
         AND    SER.IDSERVICIO = AUTD.IDSERVICIO 
         AND    SER.PREFIJO    <> @PRE1
         AND    SER.PREFIJO    <> @PRE2
         AND    SER.PREFIJO    <> @PRE3
         AND    SER.PREFIJO    <> @PRE4
         AND    SER.PREFIJO    <> @PRE5        
      END 
      ELSE
      BEGIN
         INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
         SELECT @CNSFTR, GETDATE(), 'DB', @IDAREA, NULL, (AUTD.CANTIDAD * AUTD.VALOR) - AUTD.VALORCOPAGO, 
                NULL, AUT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, AUTD.IDSERVICIO, NULL,
                AUTD.CANTIDAD, AUTD.VALOR, (AUTD.CANTIDAD * AUTD.VALOR), AUTD.VALORCOPAGO,
                0, AUT.IDPROVEEDOR, @NOAUT, @NOAUT, AUTD.NO_ITEM, NULL, 
                @NVOCONSEC, AUT.SUBCCOSTO, AUTD.VALORTOTALCOSTO,AUT.FECHA,
                'CE',DBO.FNK_TRAE_TIPOCOPAGO(AUT.NOAUT,'CE')
         FROM   AUT, AUTD, SER 
         WHERE  AUT.IDCONTRATANTE = @IDTERCERO
         AND    AUT.FACTURADA  = 0
         AND    AUT.ESTADO     <> 'Anulada'
         AND    AUT.FECHA BETWEEN @FECHAINI AND @FECHAFIN
         AND    AUT.IDPLAN     = @IDPLAN
         AND    AUTD.IDAUT     = AUT.IDAUT 
         AND    SER.IDSERVICIO = AUTD.IDSERVICIO 
         AND    SER.PREFIJO    <> @PRE1
         AND    SER.PREFIJO    <> @PRE2
         AND    SER.PREFIJO    <> @PRE3
         AND    SER.PREFIJO    <> @PRE4
         AND    SER.PREFIJO    <> @PRE5
      END
   SELECT @OK = COUNT(*) FROM #FTRD1
   IF @OK = 0
      RETURN
   
   SET @NVOCONSEC = SPACE(20)
   EXEC SPK_GENNUMEROFACTURA @COMPANIA, @IDSEDE, NULL, @NVOCONSEC OUTPUT   
   SET @CNSFTR = SPACE(20)
   EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@CNSFTR',  @CNSFTR OUTPUT  
   SELECT @CNSFTR = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)

   SELECT @TTEC = TTEC.TIPO, @CUENTACXC= TTEC.CUENTA,@CUENTACXC_RAD=CUENTARAD  
   FROM PPT INNER JOIN
        TTEC ON PPT.TIPOTERCONTABLE = TTEC.TIPO
   WHERE PPT.IDTERCERO = @IDTERCERO AND PPT.IDPLAN = @IDPLAN
   
   IF UPPER(DBO.FNK_VALORVARIABLE('BLOQUEADIAN')) = 'SI'
   BEGIN
       EXEC SPK_PREFIJOFACTURA @COMPANIA, @IDSEDE, @PRE OUTPUT  
       SELECT @CONSECFTR = CONSECUTIVO FROM USCXS WHERE COMPANIA = '01' AND IDSEDE = @IDSEDE AND PREFIJO = @PRE
       SELECT @CNSRESOL  = CNSRESOL FROM FDIAN WHERE IDENTIFICADOR = @IDSEDE AND VENCIDA = 0 AND CNSINICIAL <= @CONSECFTR AND CNSFINAL >= @CONSECFTR
   END
   
   IF EXISTS(SELECT * FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>'')
   BEGIN
       SELECT @IDFORMATOFTR=IDFORFTRCE FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND COALESCE(MFORMATOFACTURAIND,0)=1 AND COALESCE(IDFORFTRCE,'')<>''
   END
   ELSE
   BEGIN
       SELECT @IDFORMATOFTR=DBO.FNK_VALORVARIABLE('IDFORMATOFTR')
   END

   INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
                VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
                IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
                TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
                INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
                IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA, FECHAFAC,
                MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC, TIPOFIN, CNSFMAS, IDAREA_ALTA,
                CCOSTO_ALTA, IDDEP, TIPOTTEC, CUENTACXC,CUENTACXC_RAD, IDSEDE , RDIAN, CNSRESOL, IDFORMATO)
   SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCERO, @NVOCONSEC, GETDATE(), GETDATE()+@DV,
       0, NULL, NULL, LEFT(@DATO,2), NULL, 'P', NULL, NULL, @USUARIO, NULL,
       'CE', 'M', '', 'Credito', 0, 0, 0, 0, 0, 0, 0, 0, NULL, 0, 0, 0, 0, NULL, NULL, @USUARIO,
       GETDATE(), 0, 0, 0, @IDPLAN, NULL, 'C', NULL, NULL, NULL, @DATO3, @TTEC, @CUENTACXC,@CUENTACXC_RAD,@IDSEDE,CASE WHEN COALESCE(@CNSRESOL,'')<>'' THEN 1 ELSE 0 END,COALESCE(@CNSRESOL,''), @IDFORMATOFTR
       
   INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
               IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
               VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
               NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
   SELECT @CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
          IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
          VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
          NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO           
   FROM #FTRD1
          
   DROP TABLE #FTRD1   
            
   SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI), @VRCOPA = SUM(VLR_COPAGOS),
          @VRPACO  = SUM(VLR_PAGCOMP)
   FROM FTRD WHERE N_FACTURA = @NVOCONSEC
   
   IF @VRTOTAL IS NULL
      SELECT @VRTOTAL = 0
   IF @VRSERV IS NULL
      SELECT @VRSERV = 0
   IF @VRCOPA IS NULL
      SELECT @VRCOPA = 0
   IF @VRPACO IS NULL
      SELECT @VRPACO = 0   
      
   UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = @VRCOPA, VALORPCOMP = @VRPACO,
                  VR_TOTAL = @VRTOTAL
   WHERE N_FACTURA = @NVOCONSEC
   
   IF @DESCUENTO IS NULL
      SELECT @DESCUENTO = 0
          
   IF @DESCUENTO > 0
   BEGIN
      IF @TIPODTO = 'P'
         SELECT @VRDTO = ROUND(@VRTOTAL * (@DESCUENTO/100),0)
      ELSE 
         SELECT @VRDTO = @DESCUENTO 
   END           
   ELSE
      SELECT @VRDTO = 0
          
   IF @VRABONO IS NULL
      SELECT @VRABONO = 0

   UPDATE FTR SET DESCUENTO = @VRDTO, VR_ABONOS = @VRABONO
   WHERE  N_FACTURA = @NVOCONSEC
        
   UPDATE FTR SET VR_TOTAL = VALORSERVICIOS - VALORCOPAGO - VALORPCOMP -DESCUENTO - VR_ABONOS
   WHERE  N_FACTURA = @NVOCONSEC      
   IF (SELECT DBO.FNK_VALORVARIABLE('CONTABFACCE_AUTOM') ) = 'SI'
   BEGIN
      EXEC SPK_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''
   END
END

