IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_FACTURACI_ENFTREXISTENTE' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_FACTURACI_ENFTREXISTENTE
END

GO
CREATE PROCEDURE DBO.SPK_FACTURACI_ENFTREXISTENTE
@CNSRPDX      VARCHAR(20),
@NIT          VARCHAR(20),
@COMPANIA     VARCHAR(2),
@IDSEDE       VARCHAR(5),
@USUARIO      VARCHAR(12),
@IDTERCERO    VARCHAR(20),
@IDPLAN       VARCHAR(6),
@OBSERVACION  VARCHAR(255),
@IDTERCEROCA1 VARCHAR(20),
@NVOCONSEC    VARCHAR(16) 
WITH ENCRYPTION
AS
DECLARE @CNSFTR      VARCHAR(20)
DECLARE @DATO        VARCHAR(80)
DECLARE @DATO1       VARCHAR(80) 
DECLARE @DV          INT
DECLARE @DATO3       VARCHAR(20)
DECLARE @DATO2       VARCHAR(80) 
DECLARE @VRTOTAL     DECIMAL(14,2)
DECLARE @VRSERV      DECIMAL(14,2) 
DECLARE @VRCOPA      DECIMAL(14,2)
DECLARE @VRPACO      DECIMAL(14,2)
DECLARE @OK          INT
DECLARE @DESCUENTO   DECIMAL(14,2)
DECLARE @VRDTO       DECIMAL(14,2) 
DECLARE @VRABONO     DECIMAL(14,2)
DECLARE @TTEC        VARCHAR(10)
DECLARE @IDTERCEROCA VARCHAR(20)
DECLARE @CUENTACXC   VARCHAR(16)
DECLARE @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @NC          INT
BEGIN
   SELECT @NC = COUNT(*) FROM FTRD WHERE N_FACTURA = @NVOCONSEC
   SELECT @NC = @NC + 1
   SELECT @CNSFTR = CNSFCT FROM FTR WHERE N_FACTURA = @NVOCONSEC
   CREATE TABLE #FTRD1(CNSFTR VARCHAR(40), N_CUOTA	int IDENTITY(1000,1), FECHA datetime,
                DB_CR varchar(2), AREAPRESTACION varchar(20), UBICACION varchar(16),
                VR_TOTAL float, IMPUTACION varchar(16), CCOSTO varchar (20),
                PREFIJO varchar(6), ANEXO varchar(1024), REFERENCIA varchar(40), 
                IDCIRUGIA varchar(20), CANTIDAD smallint, VALOR decimal(14,2),
                VLR_SERVICI decimal(14,2), VLR_COPAGOS decimal(14,2),
                VLR_PAGCOMP decimal(14,2), IDPROVEEDOR varchar(20),
                NOADMISION varchar(16), NOPRESTACION	varchar(16), NOITEM int,	
                AREAFUNCONT varchar(20), N_FACTURA varchar(16),
                SUBCCOSTO varchar(4), PCOSTO	decimal(14,2), FECHAPREST datetime,PROCEDENCIA VARCHAR(10),TCOPAGO VARCHAR(10))
   
   DECLARE CUR_FTR CURSOR FOR
   SELECT DISTINCT CASE WHEN TER.IDTERCERO IS NULL THEN @IDTERCERO ELSE CIT.IDTERCEROCA END
   FROM CIT LEFT JOIN 
        TER ON CIT.IDTERCEROCA=TER.IDTERCERO
   WHERE CIT.CNSFACT = @CNSRPDX AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND
         (TER.IDTERCERO = (CASE WHEN @IDTERCEROCA1='' THEN TER.IDTERCERO ELSE @IDTERCEROCA1 END) OR
          (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA1 AND @IDTERCEROCA1<>'') OR
          (TER.IDTERCERO IS NULL AND @IDTERCEROCA1=''))
   
   OPEN CUR_FTR
   
   FETCH NEXT FROM CUR_FTR
   INTO @IDTERCEROCA
   
   WHILE @@FETCH_STATUS = 0  
   BEGIN 
     PRINT 'ENTRE A CURSOR'
     INSERT INTO #FTRD1(CNSFTR, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                 IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                 VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                 NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
     SELECT @CNSFTR, GETDATE(), 'DB', CIT.IDAREA, NULL, ISNULL(CIT.VALORTOTAL - CIT.VALORCOPAGO,0), 
            NULL, CIT.CCOSTO, SER.PREFIJO, SER.DESCSERVICIO, CIT.IDSERVICIO, NULL,
            1, ISNULL(CIT.VALORTOTAL,0), ISNULL(CIT.VALORTOTAL,0) , ISNULL(CIT.VALORCOPAGO,0),
            0, CIT.IDMEDICO, CIT.CONSECUTIVO, CIT.CONSECUTIVO, NULL, NULL, 
            @NVOCONSEC, CIT.SUBCCOSTO, ISNULL(CIT.VALORTOTALCOS, 0), CIT.FECHA,
            'CI',DBO.FNK_TRAE_TIPOCOPAGO(CIT.CONSECUTIVO,'CI')
     FROM   CIT INNER JOIN 
            SER ON SER.IDSERVICIO = CIT.IDSERVICIO LEFT JOIN 
            TER ON CIT.IDTERCEROCA = TER.IDTERCERO
     WHERE  CIT.CNSFACT = @CNSRPDX AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND
            (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA))
     
     SELECT @OK = COUNT(*) FROM #FTRD1
     IF @OK > 0
     BEGIN
        PRINT 'EN MAYOR QUE 0 ' 
         
        UPDATE #FTRD1 SET 
        CANTIDAD    = CASE WHEN CANTIDAD    IS NULL THEN 0 ELSE CANTIDAD    END,
        VALOR       = CASE WHEN VALOR       IS NULL THEN 0 ELSE VALOR       END,
        VLR_SERVICI = CASE WHEN VLR_SERVICI IS NULL THEN 0 ELSE VLR_SERVICI END,
        VR_TOTAL    = CASE WHEN VR_TOTAL    IS NULL THEN 0 ELSE VR_TOTAL    END,
        VLR_COPAGOS = CASE WHEN VLR_COPAGOS IS NULL THEN 0 ELSE VLR_COPAGOS END,
        VLR_PAGCOMP = CASE WHEN VLR_PAGCOMP IS NULL THEN 0 ELSE VLR_PAGCOMP END
         
        PRINT ' VOY A INSERTAR @CNSFTR='+@CNSFTR
         
        INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                         IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                         VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                         NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO)
        SELECT @CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
               IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
               VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
               NOPRESTACION, NOITEM, AREAFUNCONT, @NVOCONSEC, SUBCCOSTO, PCOSTO, FECHAPREST,PROCEDENCIA,TCOPAGO          
        FROM   #FTRD1
            
        TRUNCATE TABLE #FTRD1   
            
        SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI), @VRCOPA = SUM(VLR_COPAGOS),
               @VRPACO  = SUM(VLR_PAGCOMP)
        FROM FTRD WHERE N_FACTURA = @NVOCONSEC
        
        IF @VRTOTAL IS NULL
           SELECT @VRTOTAL = 0
        IF @VRSERV IS NULL
           SELECT @VRSERV = 0
        IF @VRCOPA IS NULL
           SELECT @VRCOPA = 0
        IF @VRPACO IS NULL
           SELECT @VRPACO = 0   
        
        UPDATE FTR SET VALORSERVICIOS = @VRSERV, VALORCOPAGO = @VRCOPA, VALORPCOMP = @VRPACO,
                       VR_TOTAL = @VRTOTAL
        WHERE N_FACTURA = @NVOCONSEC
        
        SELECT @DESCUENTO = 0, @VRDTO = 0, @VRABONO = 0
        
        UPDATE FTR SET DESCUENTO = @VRDTO, VR_ABONOS = @VRABONO
        WHERE  N_FACTURA = @NVOCONSEC
           
        UPDATE FTR SET VR_TOTAL = VALORSERVICIOS - VALORCOPAGO - VALORPCOMP -DESCUENTO - VR_ABONOS
        WHERE  N_FACTURA = @NVOCONSEC      
       
        -- GENERA LA DEDUCCION DE IMPUESTOS ESPERADA
        SELECT @VRTOTAL = VR_TOTAL FROM FTR WHERE  N_FACTURA = @NVOCONSEC 
        EXEC SPK_FAC_IMPDEDUC @NIT, @CNSFTR, @NVOCONSEC, @VRTOTAL    
        
        UPDATE CIT SET FACTURADA = 1, N_FACTURA = @NVOCONSEC, CNSFCT = @CNSFTR, VFACTURAS = 0, MARCAFAC = 0
        FROM CIT LEFT JOIN 
             TER ON CIT.IDTERCEROCA=TER.IDTERCERO
        WHERE CIT.CNSFACT = @CNSRPDX AND (CIT.FACTURADA = 0 OR CIT.FACTURADA IS NULL) AND CIT.MARCAFAC = 1 AND
            (TER.IDTERCERO = @IDTERCEROCA OR (TER.IDTERCERO IS NULL AND @IDTERCERO=@IDTERCEROCA))
     END
     FETCH NEXT FROM CUR_FTR
     INTO @IDTERCEROCA
   END
   CLOSE CUR_FTR
   DEALLOCATE CUR_FTR
   DROP TABLE #FTRD1  


   IF (SELECT DBO.FNK_VALORVARIABLE('CONTABFACCE_AUTOM') ) = 'SI'
   BEGIN 
      EXEC SPK_CONTAB_FTR @NVOCONSEC, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @IDSEDE, ''
   END
END

