GO
CREATE OR ALTER PROCEDURE DBO.SPK_ADDSERCAP  
    @CNSFTR      VARCHAR(20),  
    @N_CUOTA     INT,  
    @IDTERCERO   VARCHAR(20),  
    @IDPLAN      VARCHAR(6), 
    @FECHAINI    DATETIME,
    @FECHAFIN    DATETIME,
    @PROCEDENCIA VARCHAR(4),
    @CLASEORDEN  VARCHAR(10)='',
    @IDPESPECIAL VARCHAR(5)='', 
    @RIESGO      VARCHAR(20)='',
    @NOADMISION VARCHAR(20)=NULL,
    @IDSEDE     VARCHAR(6)= NULL
WITH ENCRYPTION
AS  
DECLARE @N_FACTURA VARCHAR(20)              ,@COPAGOAUT  DECIMAL(14,2)  ,@COPAGOS_CP  DECIMAL(14,2)
        ,@MODERADORA DECIMAL(14,2)          ,@COPAGOPROP BIT  

BEGIN 

    SELECT @N_FACTURA = N_FACTURA,@COPAGOPROP=COALESCE(COPAPROPIO,0) FROM FTR WHERE CNSFCT=@CNSFTR  
    PRINT 'Asignando Servicios a la Factura No. '+@N_FACTURA +' PROCEDENCIA '+@PROCEDENCIA

    INSERT INTO FTRDC (CNSFTR,N_CUOTA,PROCEDENCIA,FECHA,NOADMISION,PACIENTE,NOPRESTACION,NOITEM,IDSERVICIO,IDAREA,IDPLAN,  
                       CCOSTO,PREFIJO,CANTIDAD,VALOR,VALORTOTAL,VLR_COPAGO,VLR_PAGCOMP,VALOREXCEDENTE,DESCUENTO,TIPOTERCERO,  
                       CUENTA,ENRECAUDOS,IDSEDE,TCOPAGO)  
    SELECT @CNSFTR,@N_CUOTA,A.PROCEDENCIA,A.FECHA,A.NOADMISION,A.PACIENTE, A.NOPRESTACION,A.NOITEM,A.IDSERVICIO,A.IDAREA,A.IDPLAN,A.CCOSTO,A.PREFIJO,A.CANTIDAD,  
           A.VALOR,A.VALORTOTAL,CASE WHEN DBO.FNK_VALORVARIABLE('SOLO_COPA_RECAUDADO')='SI' AND VALORCOPAGO > 0 AND ENCAJA = 0 THEN 0 ELSE A.VALORCOPAGO END,
           A.VALORPCOMP,A.VALOREXCEDENTE,A.DESCUENTO,A.TIPOTERCONTABLE,TTEC.CUENTA,0,IDSEDE,
           CASE WHEN PROCEDENCIA='SALUD' AND VALORCOPAGO >0 THEN '01' WHEN PROCEDENCIA IN('CIT','ONCO') 
                THEN DBO.FNK_TRAE_TIPOCOPAGO(A.NOADMISION,'CI') ELSE DBO.FNK_TRAE_TIPOCOPAGO(A.NOADMISION,'CE') END 
    FROM VWK_CARGOS_HADMAUTCIT A LEFT JOIN  
         TTEC ON A.TIPOTERCONTABLE = TTEC.TIPO  
    WHERE A.FECHA>=@FECHAINI AND A.FECHA<@FECHAFIN+1 
    AND A.IDPLAN=@IDPLAN AND A.IDTERCEROCA=@IDTERCERO
    AND   A.PROCEDENCIA = CASE WHEN @PROCEDENCIA='TODA' THEN A.PROCEDENCIA ELSE @PROCEDENCIA END 
    AND   A.CLASEORDEN  = CASE WHEN @CLASEORDEN IN ('TODAS','') THEN A.CLASEORDEN ELSE @CLASEORDEN END 
    AND A.IDPESPECIAL = CASE WHEN @IDPESPECIAL='' THEN A.IDPESPECIAL ELSE @IDPESPECIAL END 
    AND A.RIESGO      = CASE WHEN @RIESGO='' THEN A.RIESGO ELSE @RIESGO END
	 AND COALESCE(A.FACTURADA,0)=0 
    AND A.NOADMISION=CASE WHEN COALESCE(@NOADMISION,'')='' THEN A.NOADMISION ELSE @NOADMISION END
    AND A.IDSEDE = CASE WHEN COALESCE(@IDSEDE,'')='' THEN A.IDSEDE ELSE @IDSEDE END
	 AND NOT EXISTS(SELECT * FROM FTRDC WHERE CNSFTR=@CNSFTR AND N_CUOTA=@N_CUOTA AND PROCEDENCIA=A.PROCEDENCIA AND NOADMISION=A.NOADMISION AND NOPRESTACION=A.NOPRESTACION AND NOITEM=A.NOITEM)
    IF @PROCEDENCIA='TODA' OR @PROCEDENCIA='HADM'  
    BEGIN  
     
      PRINT 'Colocando el N_Factura en HADMF...'+@N_FACTURA+'NO ADMISION '+COALESCE(@NOADMISION,'')
      INSERT INTO HADMF (NOADMISION,N_FACTURA,CNSFCT,ESTADO,N_FACTURAR,ANEXOUNICO,IDTERCERO,IDPLAN,DESCRIPCION,ITFC,CNSITFC)
      SELECT DISTINCT A.NOADMISION,@N_FACTURA,@CNSFTR,'P',NULL,NULL,@IDTERCERO,@IDPLAN,'FACTURA CAPITADA',0,NULL
      FROM HPRED INNER JOIN  
           VWK_CARGOS_HADMAUTCIT A ON HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM  
      WHERE A.FECHA>=@FECHAINI 
      AND A.FECHA<@FECHAFIN+1 
      AND A.IDPLAN=@IDPLAN 
      AND A.IDTERCEROCA=@IDTERCERO 
      AND A.PROCEDENCIA = 'HADM'
	   AND COALESCE(A.FACTURADA,0)=0	  
      AND A.NOADMISION=CASE WHEN COALESCE(@NOADMISION,'')='' THEN A.NOADMISION ELSE @NOADMISION END
      AND A.IDSEDE = CASE WHEN COALESCE(@IDSEDE,'')='' THEN A.IDSEDE ELSE @IDSEDE END

	   PRINT 'Asignando No. de Factura a las Prestaciones...'  
      UPDATE HPRED SET FACTURADA=1, N_FACTURA=@N_FACTURA  
      FROM HPRED INNER JOIN  
           VWK_CARGOS_HADMAUTCIT A ON HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM  
      WHERE A.FECHA>=@FECHAINI 
      AND A.FECHA<@FECHAFIN+1 
      AND A.IDPLAN=@IDPLAN 
      AND A.IDTERCEROCA=@IDTERCERO 
      AND A.PROCEDENCIA = 'HADM'
	   AND COALESCE(A.FACTURADA,0)=0 
      AND A.NOADMISION=CASE WHEN COALESCE(@NOADMISION,'')='' THEN A.NOADMISION ELSE @NOADMISION END
      AND A.IDSEDE = CASE WHEN COALESCE(@IDSEDE,'')='' THEN A.IDSEDE ELSE @IDSEDE END

    END  
    IF @PROCEDENCIA='TODA' OR @PROCEDENCIA='AUT'   
    BEGIN   
      PRINT 'Asignando No. de Factura a las Autorizaciones...'  
      UPDATE AUTD SET FACTURADA=1, N_FACTURA=@N_FACTURA    
      FROM AUTD INNER JOIN FTRDC A ON AUTD.IDAUT=A.NOPRESTACION AND AUTD.NO_ITEM=A.NOITEM  
      WHERE A.CNSFTR=@CNSFTR  
      AND A.PROCEDENCIA = 'AUT'
       
	  
      UPDATE AUT SET FACTURADA=1, N_FACTURA=@N_FACTURA    
      FROM AUT INNER JOIN  
           FTRDC A ON AUT.IDAUT=A.NOPRESTACION 
      WHERE A.CNSFTR=@CNSFTR  
      AND A.PROCEDENCIA = 'AUT' 




    END  
    IF @PROCEDENCIA='TODA' OR @PROCEDENCIA='CIT'  
    BEGIN  
      PRINT 'Asignando No. de Factura a las Citas...'  
      UPDATE CIT SET FACTURADA=1, N_FACTURA=@N_FACTURA    
      FROM CIT INNER JOIN FTRDC A ON CIT.CONSECUTIVO=A.NOPRESTACION   
      WHERE A.CNSFTR=@CNSFTR
      AND A.PROCEDENCIA = 'CIT' 
    END  
    IF @PROCEDENCIA='TODA' OR @PROCEDENCIA='ONCO'  
    BEGIN  
      PRINT 'Asignando No. de Factura a las Citas... SECCIONES -- ONCO '  
      UPDATE CIT SET FACTURADA=1, N_FACTURA=@N_FACTURA    
      FROM CIT INNER JOIN FTRDC A ON CIT.CONSECUTIVO=A.NOPRESTACION   
      WHERE A.CNSFTR=@CNSFTR
      AND A.PROCEDENCIA = 'ONCO' 
    END 
    --SELECT  * FROM MOCCD WHERE TIPODEPAGO='Moderadora'
     IF DBO.FNK_VALORVARIABLE('CUOTMODE_ENFACTFINAN')='SI' AND @COPAGOPROP=0
     BEGIN
        SELECT @MODERADORA=SUM(VLR_COPAGO)
        FROM FTRDC 
        WHERE CNSFTR=@CNSFTR 
        AND PROCEDENCIA<>'HADM' 
        AND CASE WHEN EXISTS(SELECT * FROM MOCCD WHERE TIPODEPAGO='Moderadora' AND VLR_COPAGO=MOCCD.VALOR) THEN  1 ELSE 0 END=1
     END

   --MODIFICACION DE NUEVO YA QUE SOLO TOMABA UN UNICO COPAGO	
   /* YA NO SE NECESITA POR QUE EL COPAGO AUT QUEDA EN UNA SOLA LINEA JJIMENEZ 05.09.2018 */
	--SELECT @COPAGOAUT=  SUM(VALORCOPAGO) FROM ( SELECT  DISTINCT AUT.NOAUT,  COALESCE(AUT.VALORCOPAGO,0) VALORCOPAGO
	--							FROM AUT INNER JOIN FTRDC ON FTRDC.CNSFTR=@CNSFTR AND FTRDC.NOADMISION=AUT.IDAUT AND FTRDC.PROCEDENCIA='AUT')Z
	-- MOD.001 - JQUIROGA con RUTHFORD JAY 20090110
	-- Actualizar el Valor de los Copagos en FTRD
	-- INICIO MOD.002
    UPDATE FTRD SET VLR_COPAGOS =CASE WHEN dbo.FNK_VALORVARIABLE('REDONDEOFTRFINANC' )='SI'
	THEN ROUND(V.VALORCOPAGO ,0) ELSE V.VALORCOPAGO END
    FROM (SELECT VALORCOPAGO = SUM( VLR_COPAGO) FROM FTRDC WHERE CNSFTR = @CNSFTR AND  N_CUOTA=@N_CUOTA) V  
    WHERE CNSFTR = @CNSFTR  
    AND N_CUOTA=@N_CUOTA

    SELECT  @COPAGOS_CP=SUM(COALESCE(COPAGOS_CP,0))  FROM FTRD WHERE CNSFTR = @CNSFTR  

    UPDATE FTR SET CP_VLR_SERVICIOS =CASE WHEN dbo.FNK_VALORVARIABLE('REDONDEOFTRFINANC' )='SI' 
	THEN ROUND( V.VALORTOTAL,0) ELSE  V.VALORTOTAL END,
                   CP_VLR_COPAGOS   = 				   
	CASE WHEN dbo.FNK_VALORVARIABLE('REDONDEOFTRFINANC' )='SI' 
		THEN ROUND(CASE WHEN FTR.COPAPROPIO=1 THEN @COPAGOS_CP ELSE  V.VALORCOPAGO END,0)
		ELSE CASE WHEN FTR.COPAPROPIO=1 THEN @COPAGOS_CP ELSE  V.VALORCOPAGO END END,
                   CP_VLR_PAGCOMP   = 
				   CASE WHEN dbo.FNK_VALORVARIABLE('REDONDEOFTRFINANC' )='SI' 
				        THEN ROUND(V.VALORPCOMP,0) ELSE V.VALORPCOMP END,
	-- MOD.001 - JQUIROGA con RUTHFORD JAY 20090110
	-- INICIO MOD.001
				   VALORCOPAGO   = 
				   CASE WHEN dbo.FNK_VALORVARIABLE('REDONDEOFTRFINANC' )='SI' THEN ROUND(V.VALORCOPAGO ,0)
				   ELSE V.VALORCOPAGO  END
	-- FIN MOD.001
    FROM (SELECT VALORTOTAL = SUM(VALORTOTAL), VALORCOPAGO = SUM(VLR_COPAGO  ), VALORPCOMP = SUM(VLR_PAGCOMP) 
          FROM FTRDC WHERE CNSFTR = @CNSFTR ) V  
    WHERE CNSFCT = @CNSFTR  

    IF COALESCE(@MODERADORA,0)>0
    BEGIN
       UPDATE FTR SET VALORMODERADORA=@MODERADORA,VALORCOPAGO=VALORCOPAGO-@MODERADORA WHERE N_FACTURA=@N_FACTURA
    END

	-- FIN MOD.002

	IF DBO.FNK_VALORVARIABLE('DESCCOP_CAPI')='SI'
	BEGIN 
	    UPDATE FTR SET VR_TOTAL=IIF( FTR.COPAPROPIO=1,VALORSERVICIOS-COALESCE(CP_VLR_COPAGOS
,0),		CASE WHEN dbo.FNK_VALORVARIABLE('REDONDEOFTRFINANC' )='SI' THEN 
		round((SELECT SUM(VALOR*CANTIDAD)-SUM( VLR_COPAGOS) FROM FTRD WHERE CNSFTR = @CNSFTR  ),0)
		ELSE (SELECT SUM(VALOR*CANTIDAD)-SUM( VLR_COPAGOS) FROM FTRD WHERE CNSFTR = @CNSFTR  ) END)
		
		WHERE  CNSFCT = @CNSFTR
	END 
END


