IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SPK_FAC_MASIVA_TER' AND type = 'P')
   DROP PROCEDURE SPK_FAC_MASIVA_TER

GO
CREATE PROCEDURE DBO.SPK_FAC_MASIVA_TER  
@CNSFMAS  VARCHAR(20), 
@COMPANIA VARCHAR(2), 
@SEDE     VARCHAR(5),
@USUARIO  VARCHAR(12),
@NIT      VARCHAR(20)
WITH ENCRYPTION
AS       
DECLARE @CNSFTR      VARCHAR(20)
DECLARE @FACT        VARCHAR(16)
DECLARE @VALCOPAGO   DECIMAL(14,2)
DECLARE @VALPCOMP    DECIMAL(14,2)
DECLARE @VALSERV     DECIMAL(14,2)
DECLARE @VALEXCE     DECIMAL(14,2)
DECLARE @IDTERCERO   VARCHAR(20)
DECLARE @A_INT       VARCHAR(20)
DECLARE @PREFIJOFAC  VARCHAR(20)
DECLARE @OBSERVACION VARCHAR(255)
DECLARE @VALABONOS   DECIMAL(14,2)
DECLARE @VALORTOTAL  DECIMAL(14,2)
DECLARE @PROPIETARIO VARCHAR(20)
DECLARE @HOY         DATETIME
DECLARE @IDDEP       VARCHAR(80)
DECLARE @DATOCCOSTO  VARCHAR(80)
DECLARE @TTEC        VARCHAR(10)
DECLARE @CUENTACXC   VARCHAR(16)
DECLARE @SYS_COMPUTERNAME VARCHAR(254)
DECLARE @PAQUETE INT
DECLARE @VLRPAQUETES DECIMAL(14,2)
DECLARE @VRTOTAL DECIMAL(14,2)
DECLARE @VRCOPA  DECIMAL(14,2)
DECLARE @VRSERV  DECIMAL(14,2)
DECLARE @VRPACO  DECIMAL(14,2)
DECLARE @CUENTACXC_RAD VARCHAR(20)
DECLARE @IDPLAN    VARCHAR(7)
DECLARE @FECHAFAC DATETIME
DECLARE @LIBERADA SMALLINT
DECLARE @CNSRESOL VARCHAR(50)
DECLARE @PROCEDENCIA VARCHAR(10)
DECLARE @VLRPAQUETE DECIMAL(14,2)
DECLARE @IDSERPAQ VARCHAR(20)
DECLARE @CUANTOS SMALLINT
DECLARE @REFERENCIA VARCHAR(20)
DECLARE @IDAFILIADOUNI VARCHAR(20)
DECLARE @CANTIPAQ SMALLINT
BEGIN
   SELECT @SYS_COMPUTERNAME = HOST_NAME(),@PAQUETE=0
   -- SACAR DE DONDE SE TOMA EL CCOSTO
   SELECT @DATOCCOSTO = DATO FROM USVGS WHERE IDVARIABLE = 'CCOSTOENPRESTACION'
   SELECT @PROCEDENCIA=PROCEDENCIA FROM FMAS WHERE CNSFMAS=@CNSFMAS
   IF @PROCEDENCIA='CI'
   BEGIN
      SELECT @CUANTOS=COUNT(*) FROM (SELECT DISTINCT CIT.IDAFILIADO 
                                    FROM FMASD INNER JOIN CIT ON FMASD.NOADMISION=CIT.CONSECUTIVO 
                                    WHERE FMASD.CNSFMAS=@CNSFMAS)X
      IF @CUANTOS=1
      BEGIN
         SELECT @REFERENCIA= MAX(NOADMISION) FROM FMASD WHERE CNSFMAS=@CNSFMAS

         SELECT @IDAFILIADOUNI= MAX(IDAFILIADO) FROM CIT INNER JOIN FMASD ON FMASD.NOADMISION=CIT.CONSECUTIVO 
         WHERE FMASD.CNSFMAS=@CNSFMAS
		 
	

      END
   END
   CREATE TABLE #ICXP (ITEM INT IDENTITY, NOADMISION VARCHAR(16) COLLATE database_default, IDSERVICIO   VARCHAR(20) COLLATE database_default,  
                       VALOREXCEDENTE DECIMAL(14,2), DESCSERVICIO VARCHAR(255) COLLATE database_default,  
                       IDAREA VARCHAR(20) COLLATE database_default,IDCIRUGIA VARCHAR(20) COLLATE database_default, VALSERVICIO DECIMAL(14,2), 
                       VALORCOPAGO DECIMAL(14,2), VALORPCOMP DECIMAL(14,2) ,
                       PREFIJO VARCHAR(6) COLLATE database_default,  IDPROVEEDOR VARCHAR(20) COLLATE database_default,
                       NOPRESTACION VARCHAR(16) COLLATE database_default,  NOITEM SMALLINT ,
                       VALOR DECIMAL(14,2),CANTIDAD INT,
                       AREAFUNCONT VARCHAR(20) COLLATE database_default, PCOSTO DECIMAL(14,2), 
                       N_FACTURA VARCHAR(16) COLLATE database_default, FECHAPREST DATETIME, CCOSTO VARCHAR(20) COLLATE database_default,
                       SUBCCOSTO VARCHAR(4) COLLATE database_default, CODUNG VARCHAR(5) COLLATE database_default,
                       CODPRG	VARCHAR(20) COLLATE database_default, PROCEDENCIA VARCHAR(10) COLLATE database_default, TCOPAGO VARCHAR(10) COLLATE database_default)
   IF @PROCEDENCIA='SALUD'
   BEGIN
      IF @DATOCCOSTO = 'SER:CCOSTO'
      BEGIN
         INSERT INTO #ICXP (NOADMISION ,IDSERVICIO , VALOREXCEDENTE , DESCSERVICIO,  
                            IDAREA, IDCIRUGIA, VALSERVICIO, VALORCOPAGO , VALORPCOMP,
                            PREFIJO, IDPROVEEDOR, NOPRESTACION, NOITEM,
                            VALOR, CANTIDAD, AREAFUNCONT, PCOSTO, FECHAPREST, CCOSTO, SUBCCOSTO, CODUNG, CODPRG,PROCEDENCIA )
         SELECT HPRE.NOADMISION, HPRED.IDSERVICIO, HPRED.VALOREXCEDENTE,
                 SER.DESCSERVICIO, HPRE.IDAREA, HPRED.IDCIRUGIA, (HPRED.CANTIDAD*HPRED.VALOR), 
                 HPRED.VALORCOPAGO, HPRED.VALORPCOMP, SER.PREFIJO, HPRED.IDPROVEEDOR, 
                 HPRED.NOPRESTACION, HPRED.NOITEM, HPRED.VALOR, HPRED.CANTIDAD, NULL, 
                 HPRED.PCOSTO, HPRE.FECHA, HPRED.CCOSTO, HPRE.SUBCCOSTO, HPRED.CODUNG, HPRED.CODPRG,@PROCEDENCIA
         FROM   HPRE,HPRED,SER,HADM 
         WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION 
                 AND HPRED.IDSERVICIO = SER.IDSERVICIO 
                 AND HPRE.NOADMISION = HADM.NOADMISION 
                 AND HADM.FACTURABLE = 1 
                 AND HADM.CERRADA = 1 
			     AND COALESCE(HADM.FACTURADA,0)=0 
                 AND EXISTS (SELECT * FROM FMASD WHERE FMASD.NOADMISION=HADM.NOADMISION AND CNSFMAS = @CNSFMAS)

      END
      ELSE
      BEGIN
         INSERT INTO #ICXP (NOADMISION ,IDSERVICIO , VALOREXCEDENTE , DESCSERVICIO,  
                             IDAREA, IDCIRUGIA, VALSERVICIO, VALORCOPAGO , VALORPCOMP,
                             PREFIJO, IDPROVEEDOR, NOPRESTACION, NOITEM,
                             VALOR, CANTIDAD, AREAFUNCONT, PCOSTO, FECHAPREST, CCOSTO, SUBCCOSTO, CODUNG, CODPRG,PROCEDENCIA )
         SELECT HPRE.NOADMISION, HPRED.IDSERVICIO, HPRED.VALOREXCEDENTE,
                 SER.DESCSERVICIO, HPRE.IDAREA, HPRED.IDCIRUGIA, (HPRED.CANTIDAD*HPRED.VALOR), 
                 HPRED.VALORCOPAGO, HPRED.VALORPCOMP, SER.PREFIJO, HPRED.IDPROVEEDOR, 
                 HPRED.NOPRESTACION, HPRED.NOITEM, HPRED.VALOR, HPRED.CANTIDAD, NULL, 
                 HPRED.PCOSTO, HPRE.FECHA, HPRE.CCOSTO, HPRE.SUBCCOSTO, HPRED.CODUNG, HPRED.CODPRG,@PROCEDENCIA
         FROM   HPRE,HPRED,SER,HADM 
         WHERE  HPRE.NOPRESTACION = HPRED.NOPRESTACION 
                 AND HPRED.IDSERVICIO = SER.IDSERVICIO 
                 AND HPRE.NOADMISION = HADM.NOADMISION 
                 AND HADM.FACTURABLE = 1 
                 AND HADM.CERRADA = 1 
			     AND COALESCE(HADM.FACTURADA,0)=0 
                 AND EXISTS (SELECT * FROM FMASD WHERE FMASD.NOADMISION=HADM.NOADMISION AND CNSFMAS = @CNSFMAS)
      END
   END
   ELSE
   BEGIN
      IF @PROCEDENCIA='CI'
      BEGIN
         INSERT INTO #ICXP (NOADMISION ,IDSERVICIO , VALOREXCEDENTE , DESCSERVICIO,  
                             IDAREA, IDCIRUGIA, VALSERVICIO, VALORCOPAGO , VALORPCOMP,
                             PREFIJO, IDPROVEEDOR, NOPRESTACION, NOITEM,
                             VALOR, CANTIDAD, AREAFUNCONT, PCOSTO, FECHAPREST, CCOSTO, SUBCCOSTO, CODUNG, CODPRG,PROCEDENCIA,TCOPAGO )
         SELECT CIT.CONSECUTIVO, CIT.IDSERVICIO, CIT.VALORTOTAL,
                 SER.DESCSERVICIO, CIT.IDAREA, CIT.IDCIRUGIA, VALORTOTAL, 
                 CIT.VALORCOPAGO, 0, SER.PREFIJO, CIT.IDMEDICO, 
                 CIT.CONSECUTIVO, 1, VALORTOTAL, 1, NULL, 
                 0, CIT.FECHA, CIT.CCOSTO, CIT.SUBCCOSTO, CIT.CODUNG, CIT.CODPRG,@PROCEDENCIA,
                 DBO.FNK_TRAE_TIPOCOPAGO(CIT.CONSECUTIVO,'CI')
         FROM   CIT,SER 
         WHERE  CIT.IDSERVICIO = SER.IDSERVICIO  
                 AND COALESCE(CIT.FACTURABLE,1) = 1 
                 AND COALESCE(CIT.FACTURADA,0) = 0
                 --AND CIT.CNSFACT=@CNSFMAS
                 AND EXISTS (SELECT * FROM FMASD WHERE FMASD.NOADMISION=CIT.CONSECUTIVO AND CNSFMAS = @CNSFMAS)         

      END
   END

   IF EXISTS (SELECT 1 FROM FTR WHERE CNSFMAS=@CNSFMAS AND ESTADO='L')
   BEGIN
	   SELECT @FACT=N_FACTURA, @CNSFTR=CNSFCT, @LIBERADA=1 FROM FTR WHERE CNSFMAS=@CNSFMAS AND ESTADO='L' 
      PRINT '@FACT ='+@FACT
   END
   ELSE
   BEGIN
	   SET @LIBERADA=0
	   SET @FACT = SPACE(20)
	   EXEC SPK_GENNUMEROFACTURA @COMPANIA, @SEDE, NULL, @FACT OUTPUT   
	   SET @CNSFTR = SPACE(20)
	   EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@CNSFTR',  @CNSFTR OUTPUT  
	   SELECT @CNSFTR = @SEDE + REPLACE(SPACE(8 - LEN(@CNSFTR))+LTRIM(RTRIM(@CNSFTR)),SPACE(1),0)
   END
   IF DBO.FNK_VALORVARIABLE('BLOQUEADIAN')='SI'
	BEGIN
		IF DBO.FNK_VALORVARIABLE('FACTSEDE')='SI'
		BEGIN
			SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE IDENTIFICADOR=@SEDE AND VENCIDA=0 AND PROCEDENCIA = 'FTR' 
		END
		ELSE
		BEGIN
			SELECT  @CNSRESOL=CNSRESOL FROM FDIAN WHERE  VENCIDA=0 AND PROCEDENCIA = 'FTR'
		END
	END
    
   SELECT @VALCOPAGO = SUM(VALORCOPAGO), @VALPCOMP  = SUM(VALORPCOMP),
          @VALSERV   = SUM(VALSERVICIO), @VALEXCE   = SUM(VALOREXCEDENTE)
   FROM   #ICXP 
   
   SELECT @IDTERCERO = IDTERCERO, @OBSERVACION = OBSERVACION ,@IDPLAN=IDPLAN,@PAQUETE=PAQUETE,
   @VLRPAQUETE=IIF(COALESCE(VALORNVO,0)=0, COALESCE(VALORPAQ,0),VALORNVO),@IDSERPAQ=IDSERPAQ,
   @FECHAFAC=COALESCE(F_FACTURA,GETDATE())
   FROM   FMAS WHERE CNSFMAS = @CNSFMAS
       
   SELECT @VALABONOS =  SUM(QXDING.VALOR) 
   FROM   QXDING, FMASD
   WHERE  QXDING.NOINGRESO = FMASD.NOADMISION
   AND    FMASD.CNSFMAS    = @CNSFMAS
   AND    QXDING.DEVUELTO = 0
             
   IF @VALABONOS IS NULL
   BEGIN
      SELECT @VALABONOS = 0
   END      
   SELECT @VALORTOTAL = @VALSERV - 0 - @VALCOPAGO - @VALPCOMP - @VALABONOS
   
   SELECT @IDDEP = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'IDFDEPFACTURACION'   

   --SELECT @TTEC = TTEC.TIPO, @CUENTACXC = TTEC.CUENTA 
   --FROM (SELECT TOP 1 HADM.IDTERCERO, HADM.IDPLAN, COUNT(*) CANT 
   --      FROM   HADM INNER JOIN 
   --             FMASD ON HADM.NOADMISION = FMASD.NOADMISION
   --      WHERE  CNSFMAS = @CNSFMAS
   --      GROUP BY HADM.IDTERCERO, HADM.IDPLAN
   --      ORDER BY COUNT(*) DESC) X INNER JOIN PPT  ON PPT.IDTERCERO = X.IDTERCERO 
   --                                               AND PPT.IDPLAN    = X.IDPLAN 
   --                                INNER JOIN TTEC ON PPT.TIPOTERCONTABLE = TTEC.TIPO


   SELECT @TTEC=TIPOTERCONTABLE
   FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN

   IF COALESCE(@TTEC,'')<>''
   BEGIN
	  SELECT @CUENTACXC=CUENTA,@CUENTACXC_RAD=CUENTARAD FROM TTEC WHERE TIPO=@TTEC
   END


   IF @LIBERADA=1
   BEGIN
	    PRINT '@LIBERADA=1' 
		UPDATE FTR SET IDTERCERO=@IDTERCERO, ESTADO='P', F_FACTURA=@FECHAFAC, F_VENCE=@FECHAFAC+30, VR_TOTAL=@VALORTOTAL, VALORCOPAGO=@VALCOPAGO,
		VALORPCOMP=@VALPCOMP, VALORSERVICIOS=@VALSERV, USUARIOFACTURA=@USUARIO, FECHAFAC=GETDATE(), VR_ABONOS=@VALABONOS, IDPLAN=@IDPLAN
		WHERE N_FACTURA=@FACT
   END
   ELSE
   BEGIN
	   INSERT INTO FTR(CNSFCT, COMPANIA, CLASE, IDTERCERO, N_FACTURA, F_FACTURA, F_VENCE,
					   VR_TOTAL, COBRADOR, VENDEDOR, MONEDA, OCOMPRA, ESTADO, F_CANCELADO,
					   IDAFILIADO, EMPLEADO, NOREFERENCIA, PROCEDENCIA, TIPOFAC, OBSERVACION,
					   TIPOVENTA, VALORCOPAGO, DESCUENTO, VALORPCOMP, CREDITO, INDCARTERA,
					   INDCXC, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, MARCA, INDASIGCXC,
					   IMPRESO, VALORSERVICIOS, CLASEANULACION, CNSLOG, USUARIOFACTURA,
					   FECHAFAC, MIVA, PIVA, VR_ABONOS, IDPLAN, FECHAPASOCXC,
					   TIPOFIN, CNSFMAS, IDDEP, TIPOTTEC, CUENTACXC,IDSEDE,PAQUETE,CUENTACXC_RAD, RDIAN, CNSRESOL)
		SELECT @CNSFTR, @COMPANIA, 'C', @IDTERCERO, @FACT, @FECHAFAC, @FECHAFAC + 30,
			   @VALORTOTAL, '01', '01', '01', NULL, 'P', NULL, 
			   CASE WHEN COALESCE( @IDAFILIADOUNI,'')='' THEN  'MASIVA' ELSE @IDAFILIADOUNI END , @USUARIO, 'MASIVA',@PROCEDENCIA, 'M', @OBSERVACION, 
			   NULL, @VALCOPAGO, 0, @VALPCOMP, 0, 0, 
			   0, 0, 0,  NULL, 0, 0, 
			   0, @VALSERV, NULL, NULL, @USUARIO, 
			   GETDATE(), 0, 0,  @VALABONOS, @IDPLAN, NULL, 
			   NULL, @CNSFMAS, @IDDEP, @TTEC, @CUENTACXC,@SEDE,  CASE WHEN COALESCE(@PAQUETE,0)>0 THEN 1 ELSE 0 END,@CUENTACXC_RAD, 1, @CNSRESOL
    END
     PRINT'-- INGRESO DE LOS DETALLES'

    INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                     IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                     VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                     NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, CODUNG, CODPRG,PAQUETE,PROCEDENCIA,TCOPAGO) 
    SELECT @CNSFTR, ITEM, FECHAPREST, 'DB', IDAREA, NULL, VALSERVICIO, NULL, CCOSTO, 
           PREFIJO, DESCSERVICIO, IDSERVICIO, IDCIRUGIA, CANTIDAD, VALOR, VALSERVICIO,
           VALORCOPAGO, VALORPCOMP, IDPROVEEDOR, NOADMISION, NOPRESTACION, NOITEM,
           AREAFUNCONT, @FACT, SUBCCOSTO, PCOSTO, CODUNG, CODPRG,CASE WHEN COALESCE(@PAQUETE,0)>0 THEN 2 ELSE 0 END,PROCEDENCIA,TCOPAGO 
    FROM   #ICXP

	--RETURN

    DROP TABLE #ICXP
    IF @PROCEDENCIA='SALUD'
    BEGIN
       UPDATE HADM SET FACTURADA = 1, N_FACTURA = @FACT, CNSFCT = @CNSFTR,
              TIPOFAC   = 'M' FROM FTRD
              WHERE HADM.NOADMISION = FTRD.NOADMISION
              AND   FTRD.N_FACTURA  = @FACT

       UPDATE HPRED SET FACTURADA = 1, N_FACTURA = @FACT  FROM FTRD
       WHERE HPRED.NOPRESTACION = FTRD.NOPRESTACION
       AND   HPRED.NOITEM       = FTRD.NOITEM
       AND   FTRD.N_FACTURA     = @FACT
    END
    ELSE
    BEGIN
       IF @PROCEDENCIA='CI'
       BEGIN
	      PRINT  'ENTRE AQUI Y ACTUALIZO ESTADOS DE CIT'
         UPDATE CIT SET FACTURADA=1,N_FACTURA=FTRD.N_FACTURA
         FROM CIT INNER JOIN FTRD ON CIT.CONSECUTIVO=FTRD.NOPRESTACION
         WHERE FTRD.N_FACTURA=@FACT
         --AND CIT.CNSFACT=@CNSFMAS
		   AND EXISTS (SELECT * FROM FMASD WHERE FMASD.NOADMISION=CIT.CONSECUTIVO AND CNSFMAS = @CNSFMAS)
         IF @CUANTOS=1
         BEGIN
            UPDATE FTR SET NOREFERENCIA=@REFERENCIA WHERE N_FACTURA=@FACT
         END
         
         SELECT @CANTIPAQ=CASE WHEN COALESCE(MCANT,0)=1 THEN CANT ELSE 1 END FROM FMAS WHERE CNSFMAS = @CNSFMAS
       END
    END
    EXEC SPK_FAC_IMPDEDUC  @NIT, @CNSFTR, @FACT, @VALORTOTAL 

    UPDATE FMAS SET N_FACTURA = @FACT, F_FACTURA = @HOY , 
                    F_VENCE = @HOY +30, FACTURADA = 1
    WHERE CNSFMAS = @CNSFMAS 

    SELECT @VRTOTAL = SUM(VR_TOTAL), @VRSERV = SUM(VLR_SERVICI), @VRCOPA = SUM(VLR_COPAGOS),
             @VRPACO  = SUM(VLR_PAGCOMP)
    FROM   FTRD 
    WHERE  N_FACTURA = @FACT
            
    SELECT @VRCOPA = ROUND(@VRCOPA, 0)

	IF @PAQUETE = 1
	BEGIN    
       IF @PROCEDENCIA='SALUD'
       BEGIN
           SELECT @VRSERV  = COALESCE(SUM(VR_TOTAL),0),
                  @VRTOTAL = COALESCE(SUM(VR_TOTAL),0) - COALESCE(@VRCOPA,0) - COALESCE(@VRPACO,0)
           FROM   FTRD 
           WHERE  COALESCE(PAQUETE,0) IN (1,3) 
           AND    N_FACTURA = @FACT

           UPDATE FTR SET VALORSERVICIOS = COALESCE(@VRSERV,0), 
                       VALORPCOMP     = COALESCE(@VRPACO,0), 
                       COPAGO_INT     = COALESCE(@VRCOPA,0), 
	                       COPAGO_EXT     = 0,
	                       VALORCOPAGO    =COALESCE( @VRCOPA,0), -- (SELECT ISNULL(VLR_COPAGOEXTERNO,0) FROM HADM WHERE NOADMISION = @NOADMISION),
                       VR_TOTAL       = COALESCE(@VRTOTAL,0)
           WHERE N_FACTURA = @FACT         
        END
        ELSE
        BEGIN
           IF DBO.FNK_VALORVARIABLE('VLR_PAQUE_DETA_CITAS')='PAQUETE'
           BEGIN
              UPDATE FTRD SET VR_TOTAL=0,VLR_SERVICI=0,VALOR=0 WHERE N_FACTURA=@FACT
           END
  
            SELECT @VRSERV  = COALESCE(SUM(VR_TOTAL),0),
                  @VRTOTAL = COALESCE(SUM(VR_TOTAL),0) - COALESCE(@VRCOPA,0) - COALESCE(@VRPACO,0)
            FROM   FTRD 
            WHERE  N_FACTURA = @FACT  
            
            DECLARE @DIFPAQ DECIMAL(14,2)
            SELECT @DIFPAQ=@VLRPAQUETE-@VRSERV
            IF @DIFPAQ< 0
            BEGIN
               SELECT @difpaq=0
            END
            
            DECLARE @ITEM INT 
            SELECT @ITEM=MAX(N_CUOTA) FROM FTRD WHERE N_FACTURA=@FACT

            INSERT INTO FTRD(CNSFTR, N_CUOTA, FECHA, DB_CR, AREAPRESTACION, UBICACION, VR_TOTAL,
                           IMPUTACION, CCOSTO, PREFIJO, ANEXO, REFERENCIA, IDCIRUGIA, CANTIDAD,
                           VALOR, VLR_SERVICI, VLR_COPAGOS, VLR_PAGCOMP, IDPROVEEDOR, NOADMISION,
                           NOPRESTACION, NOITEM, AREAFUNCONT, N_FACTURA, SUBCCOSTO, PCOSTO, CODUNG, CODPRG,PAQUETE) 
            SELECT TOP 1 CNSFTR, @ITEM+1,FECHA , 'DB', AREAPRESTACION, NULL, @DIFPAQ, NULL,FTRD.CCOSTO, 
                  SER.PREFIJO, DESCSERVICIO, IDSERVICIO, IDCIRUGIA,  @CANTIPAQ ,CONVERT(DECIMAL(14,2),@DIFPAQ/@CANTIPAQ),  @DIFPAQ,
                  0, 0, IDPROVEEDOR, NOADMISION, NOPRESTACION+'1', 99,
                  AREAFUNCONT, @FACT, SUBCCOSTO, PCOSTO, CODUNG, CODPRG,0      
            FROM   FTRD,SER 
            WHERE N_FACTURA=@FACT
            AND SER.IDSERVICIO=@IDSERPAQ

            SELECT @VRSERV  = COALESCE(SUM(VR_TOTAL),0),
                  @VRTOTAL = COALESCE(SUM(VR_TOTAL),0) - COALESCE(@VRCOPA,0) - COALESCE(@VRPACO,0)
            FROM   FTRD 
            WHERE  N_FACTURA = @FACT

            UPDATE FTR SET VALORSERVICIOS = COALESCE(@VRSERV,0), 
                        VALORPCOMP     = COALESCE(@VRPACO,0), 
                        COPAGO_INT     = COALESCE(@VRCOPA,0), 
	                        COPAGO_EXT     = 0,
	                        VALORCOPAGO    =COALESCE( @VRCOPA,0), -- (SELECT ISNULL(VLR_COPAGOEXTERNO,0) FROM HADM WHERE NOADMISION = @NOADMISION),
                        VR_TOTAL       = COALESCE(@VRTOTAL,0)
            WHERE N_FACTURA = @FACT                        
        END
	END
	ELSE
	BEGIN
		UPDATE FTR SET VALORSERVICIOS = COALESCE(@VRSERV,0), VALORPCOMP = COALESCE(@VRPACO,0), COPAGO_INT = COALESCE(@VRCOPA,0), 
						COPAGO_EXT   =0,
						VALORCOPAGO    = COALESCE(@VRCOPA,0), -- - (SELECT ISNULL(VLR_COPAGOEXTERNO,0) FROM HADM WHERE NOADMISION = @NOADMISION),
					VR_TOTAL       = COALESCE(@VRSERV,0) - COALESCE(@VRCOPA,0) - COALESCE(@VRPACO,0)
		WHERE N_FACTURA = @FACT
    END
   IF @PROCEDENCIA='SALUD'
   BEGIN
	   IF @PAQUETE>0 
	   BEGIN
		   PRINT 'ES PAQUETE'
		   SELECT @VLRPAQUETES=SUM(COALESCE(VLRSERVICIOPAQ,0)+COALESCE(VLRSERVICIOPAQ2,0)) FROM HADM WHERE EXISTS (SELECT * FROM FMASD WHERE FMASD.NOADMISION=HADM.NOADMISION AND CNSFMAS = @CNSFMAS)
		   PRINT '@VLRPAQUETES === '+LTRIM(RTRIM(STR(@VLRPAQUETES)))
		   UPDATE FTR SET VALORSERVICIOS=@VLRPAQUETES,VR_TOTAL=@VLRPAQUETES-VALORCOPAGO WHERE N_FACTURA=@FACT
	   END

	   PRINT 'REALIZO EL INSERT EN HADMF'
	   IF @LIBERADA=0
	   BEGIN
		   INSERT INTO HADMF(NOADMISION,N_FACTURA,CNSFCT,ESTADO,N_FACTURAR,ANEXOUNICO,IDTERCERO,IDPLAN,DESCRIPCION,ITFC,CNSITFC)
		   SELECT  NOADMISION,@FACT,@CNSFTR,'P',NULL,NULL,IDTERCERO,IDPLAN,'FACTURACION MASIVA'+IDPLAN,0,NULL 
		   FROM HADM WHERE  EXISTS(SELECT * FROM FMASD WHERE FMASD.NOADMISION=HADM.NOADMISION AND CNSFMAS = @CNSFMAS)
	   END
   END
   EXEC SPK_NC_CONTAB_FTR @FACT, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE, ''
END



