IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='CUOTMODE_ENFACTFINAN')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'CUOTMODE_ENFACTFINAN','Separa Valor de Cuota moderadora y copago en Factura Capitada SI|NO','Alfanumerica',''
END