IF EXISTS (SELECT name FROM sysobjects  WHERE name = 'SPK_TOTALFACTURFIN' AND type = 'P')
   DROP PROCEDURE SPK_TOTALFACTURFIN

GO
CREATE PROCEDURE DBO.SPK_TOTALFACTURFIN
@N_FACTURA VARCHAR(16)
WITH ENCRYPTION
AS
DECLARE @MODERADORA DECIMAL(14,2)=0
BEGIN
   PRINT 'ENTRE A TOTALES'
   CREATE TABLE #TEMP (VALORSERVICIOS DECIMAL(14,2), 
                     VALORCOPAGO    DECIMAL(14,2), 
                     VALORPCOMP     DECIMAL(14,2), 
                     COPAGOCP       DECIMAL(14,2),
                     VR_TOTAL       DECIMAL(14,2),
                     VIVA           DECIMAL(14,2),
                     PIVA           DECIMAL(7,2))
   INSERT INTO #TEMP
   SELECT COALESCE(SUM(VLR_SERVICI),0),COALESCE(SUM(VLR_COPAGOS),0),COALESCE(SUM(VLR_PAGCOMP),0),COALESCE(SUM(COPAGOS_CP),0),COALESCE(SUM(VR_TOTAL),0), COALESCE(SUM(VIVA*CANTIDAD),0),MAX(COALESCE(PIVA,0)) 
   FROM FTRD WHERE N_FACTURA = @N_FACTURA

   IF DBO.FNK_VALORVARIABLE('CUOTMODE_ENFACTFINAN')='SI' 
   BEGIN
      IF EXISTS(SELECT * FROM FTRDC INNER JOIN FTR ON FTRDC.CNSFTR=FTRDC.CNSFTR WHERE  COALESCE(FTR.COPAPROPIO,0)=0 )
      BEGIN
         SELECT @MODERADORA=SUM(VLR_COPAGO)
          FROM FTRDC INNER JOIN FTR ON FTRDC.CNSFTR=FTR.CNSFCT 
         WHERE FTR.N_FACTURA=@N_FACTURA
         AND  FTRDC.PROCEDENCIA<>'HADM' 
         AND  COALESCE(FTR.COPAPROPIO,0)=0 
         AND CASE WHEN EXISTS(SELECT * FROM MOCCD WHERE TIPODEPAGO='Moderadora' AND VLR_COPAGO=MOCCD.VALOR) THEN  1 ELSE 0 END=1
     END
   END             
   UPDATE FTR SET VALORSERVICIOS = #TEMP.VALORSERVICIOS,
                  VALORCOPAGO    = #TEMP.VALORCOPAGO,
                  VALORPCOMP     = #TEMP.VALORPCOMP,
                  CP_VLR_COPAGOS = #TEMP.COPAGOCP,
                  VR_TOTAL       = CASE WHEN COALESCE(FTR.COPAPROPIO,0)=1 THEN #TEMP.VALORSERVICIOS-(#TEMP.COPAGOCP)-  ISNULL(FTR.DESCUENTO,0) - ISNULL(FTR.VR_ABONOS,0)   
										WHEN COALESCE(FTR.VALORMODERADORA,0)>0 THEN #TEMP.VALORSERVICIOS - FTR.VALORCOPAGO -  ISNULL(FTR.DESCUENTO,0) - ISNULL(FTR.VR_ABONOS,0)   - COALESCE(FTR.VALORMODERADORA,0) 
                                       ELSE  #TEMP.VR_TOTAL -  ISNULL(FTR.DESCUENTO,0) - ISNULL(FTR.VR_ABONOS,0) 
                                 END, 
                  VIVA           = #TEMP.VIVA,
                  PIVA           = #TEMP.PIVA
   FROM #TEMP
   WHERE FTR.N_FACTURA = @N_FACTURA

   IF COALESCE(@MODERADORA,0)>0
   BEGIN
      UPDATE FTR SET VALORMODERADORA=@MODERADORA,VALORCOPAGO=VALORCOPAGO-@MODERADORA WHERE N_FACTURA=@N_FACTURA
   END

   DROP TABLE #TEMP
END







