CREATE OR ALTER PROCEDURE DBO.SPK_ENVIA_INTERFAX_INV @CNSMOV VARCHAR(20)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @BDATOS VARCHAR(20)
DECLARE @SQL    VARCHAR(MAX)
DECLARE @IDBODEGAEXT VARCHAR(20)
DECLARE @IDMOVENT    VARCHAR(20)
DECLARE @IDTERCERO VARCHAR(20)
DECLARE @DTER TABLE(IDTERCERO VARCHAR(20))
DECLARE @DCOS TABLE (IDAREA VARCHAR(20),CCOSTO VARCHAR(20))
DECLARE @IDAREA VARCHAR(20)
DECLARE @CCOSTO VARCHAR(20)
DECLARE @CREAR TABLE (IDARTICULO VARCHAR(20))
DECLARE @CNSMOVDES VARCHAR(20)
BEGIN
   IF EXISTS(SELECT name FROM sys.databases WHERE [NAME]=DBO.FNK_VALORVARIABLE('INTERFAZ_INV'))
   BEGIN
      IF EXISTS(SELECT * FROM IMOV WHERE CNSMOV=@CNSMOV AND ENTREGADO=1)
      BEGIN
         PRINT 'EL MOVIMIENTO YA FUE PASADO EN LA INTERFAX'
         RETURN
      END
      SELECT @BDATOS=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('INTERFAZ_INV')))
      SELECT @CNSMOVDES=LEFT(@CNSMOV,2)+'IX'+RIGHT(@CNSMOV,LEN(@CNSMOV)-2)
      SELECT @IDMOVENT=WORD FROM DBO.FNK_EXPLODE(LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDTIPOMOV_INTER_ENT'))),',') WHERE WORDID=1
      SELECT @IDBODEGAEXT=WORD FROM DBO.FNK_EXPLODE(LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IDTIPOMOV_INTER_ENT'))),',') WHERE WORDID=2
      SELECT @IDTERCERO=NIT FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
      SELECT @SQL='SELECT IDTERCERO FROM '+@BDATOS+'.DBO.TER WHERE NIT='''+@IDTERCERO+''''
      INSERT INTO @DTER(IDTERCERO)
      EXECUTE(@SQL)

      SELECT @SQL='SELECT IDAREA,CCOSTO FROM '+@BDATOS+'.DBO.IBOD WHERE IDBODEGA='''+@IDBODEGAEXT+''''

      INSERT INTO @DCOS
      EXECUTE(@SQL)

      SELECT @SQL='SELECT IDARTICULO FROM ISAL WHERE CNSMOV='''+@CNSMOV+''' AND NOT EXISTS(SELECT * FROM '+@BDATOS+'.DBO.IART WHERE ISAL.IDARTICULO=IART.IDARTICULO) '
      
      INSERT INTO @CREAR
      EXECUTE(@SQL)

      IF EXISTS(SELECT * FROM @CREAR)
      BEGIN
         DECLARE @IDART VARCHAR(20)

         DECLARE VCREA_CURSOR CURSOR FOR 
         SELECT IDARTICULO FROM @CREAR
         OPEN VCREA_CURSOR    
         FETCH NEXT FROM VCREA_CURSOR    
         INTO @IDART
         WHILE @@FETCH_STATUS = 0    
         BEGIN 
            SELECT @SQL='INSERT INTO '+@BDATOS+'.DBO.IART (IDARTICULO, IDCLASE, IDSUBCLASE, IDGRUPO, DESCRIPCION, IDPRINACTIVO, IDFORFARM, IDCONCENTRA,
                         IDUNIDAD, PCOSTO, EXISTOTAL, STOCKMINIMO, STOCKMAXIMO, PUNTOREORDEN, IDITAR, ESTRANSFORMABLE,  ESTADO, IDGENERICO,
                         CUENTA, IDFABRICANTE, ESACTIVO, IDTIPOACTIVO, IDALTERNA, REGINVIMA, ALTO_COSTO, CONT_ESPECIAL, ENTREGA_TURNO, 
                         UTILIDAD, DOSIFICADO, NDOSIS, CODCUM, ESCALA_RIESGO,  IDSERVICIO, PRINCIPAL, CLASERIESGO, TESTABILIDAD, CLASE, 
                         MLOTEO, IDSERVICIOBASE, CANTIDADBASE, IDSERVICIOMEZCLA, CANTIDADMEZCLA, CODIBASE, CENTRAL, IDSERVICIOCOBRO, CTV,  
                         F_VIGENCIAINV, REGULADO, PRECOMERCIAL, NOPOS, CONTADOR, GRUPO, LABILIDAD, HEMOCLASIFICACION, JUSTIFICACION, 
                         CODBARRA, INSTITUCIONAL, TEMPERATURA, ICBU, RMINSTOCK, STOCKMINREQ, REQAUTCOMP,  REQRECEP, REFERENCIA, IUM, 
                         IDSERVICIO_FAC, CESTE, MIVA, PROCEDIMIENTO, MCADFRIO, BIOLOGICO, UNIRS, ALERTA, TEMPERATURA_FIN, HUMEDAD_MIN, 
                         HUMEDAD_MAX)
                         SELECT IDARTICULO, IDCLASE, IDSUBCLASE, IDGRUPO, DESCRIPCION, IDPRINACTIVO, IDFORFARM, IDCONCENTRA,
                         IDUNIDAD, PCOSTO, EXISTOTAL, STOCKMINIMO, STOCKMAXIMO, PUNTOREORDEN, IDITAR, ESTRANSFORMABLE,  ESTADO, IDGENERICO,
                         CUENTA, IDFABRICANTE, ESACTIVO, IDTIPOACTIVO, IDALTERNA, REGINVIMA, ALTO_COSTO, CONT_ESPECIAL, ENTREGA_TURNO, 
                         UTILIDAD, DOSIFICADO, NDOSIS, CODCUM, ESCALA_RIESGO,  IDSERVICIO, PRINCIPAL, CLASERIESGO, TESTABILIDAD, CLASE, 
                         MLOTEO, IDSERVICIOBASE, CANTIDADBASE, IDSERVICIOMEZCLA, CANTIDADMEZCLA, CODIBASE, CENTRAL, IDSERVICIOCOBRO, CTV,  
                         F_VIGENCIAINV, REGULADO, PRECOMERCIAL, NOPOS, CONTADOR, GRUPO, LABILIDAD, HEMOCLASIFICACION, JUSTIFICACION, 
                         CODBARRA, INSTITUCIONAL, TEMPERATURA, ICBU, RMINSTOCK, STOCKMINREQ, REQAUTCOMP,  REQRECEP, REFERENCIA, IUM, 
                         IDSERVICIO_FAC, CESTE, MIVA, PROCEDIMIENTO, MCADFRIO, BIOLOGICO, UNIRS, ALERTA, TEMPERATURA_FIN, HUMEDAD_MIN, 
                         HUMEDAD_MAX FROM IART WHERE IDARTICULO='''+LTRIM(RTRIM(@IDART))+''''
             BEGIN TRY           
                   EXECUTE (@SQL)              
             END TRY
             BEGIN CATCH
                     PRINT @SQL
                     PRINT 'ERROR AL CREAR EL ARTICULO:'+ERROR_MESSAGE()
             END CATCH
            FETCH NEXT FROM VCREA_CURSOR    
            INTO @IDART
         END
         CLOSE VCREA_CURSOR
         DEALLOCATE VCREA_CURSOR
      END
      SELECT @IDTERCERO=IDTERCERO FROM @DTER
      SELECT @IDAREA=IDAREA,@CCOSTO=CCOSTO FROM @DCOS

      SELECT @SQL='INSERT INTO '+@BDATOS+'.DBO.IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU, FECHAMOV, CCOSTO, IDSOLICITA,
                   IDTERCERO, IDFUNCIONARIO, IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, CNSTRAN, OBSERVACION, CNSFCOM,  SUBIOCOMPRA, 
                   NOPRESTACION, IDAREA, CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO, USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, 
                   NIVELATENCION, SYS_ComputerName, TIENECAMBIO,  IDITAR, ESTRANSITO, CNSREP, CNSIDEV, IDDEP, CNSITRA, SECONTABILIZA, 
                   F_FACTURA, F_VENCE, MARCACONT, VLR_FLETE, CODUNG, CODPRG, ITFC, CNSITFC, IDARTICULODESTINO, CANTIDADDESTINO,  GENFACTURA, 
                   IDPLAN, FACTURADA, N_FACTURA, TIPO_DOC_COMPRA, NOCONSECUTIVO, CNSDBCR, ITEMDBCR, DEVTOTAL, CLASEPED, USURECIBE, VLRCOMPRA, 
                   IDTERCEROENVIA, F_ENVIA, USUENVIA, NROGUIA,  VLRENVIA, ENTREGADO, F_ENTREGADO, USUENTREGADO, IDFIRMAENTRE, IDFIRMARECI, TIPOENT, 
                   IDKPAGE, IDTERCERORESP) '
      SELECT @SQL=@SQL+' SELECT '''+@CNSMOVDES+''','''+@IDBODEGAEXT+''','''+@IDMOVENT+''','''+@CNSMOV+''', TIPODOCU, FECHAMOV, '''+@CCOSTO+''', IDSOLICITA,'''+@IDTERCERO+''', 
                  IDFUNCIONARIO, IDRECIBE, FACTORVENTA, 0, IDBODEGA, CNSTRAN, ''Traslado por Prestamo entre '', CNSFCOM,  SUBIOCOMPRA, 
                  NOPRESTACION,'''+@IDAREA+''', CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO, USUARIOCONF, NULL, PARCIAL, 
                  IDAREAH, NIVELATENCION, SYS_ComputerName, TIENECAMBIO,  IDITAR, ESTRANSITO, CNSREP, CNSIDEV, IDDEP, CNSITRA, 
                  SECONTABILIZA, F_FACTURA, F_VENCE, MARCACONT, VLR_FLETE, CODUNG, CODPRG, ITFC, CNSITFC, IDARTICULODESTINO, 
                  CANTIDADDESTINO,  GENFACTURA, IDPLAN, FACTURADA, N_FACTURA, TIPO_DOC_COMPRA, NOCONSECUTIVO, CNSDBCR, ITEMDBCR, 
                  DEVTOTAL, CLASEPED, USURECIBE, VLRCOMPRA, IDTERCEROENVIA, F_ENVIA, USUENVIA, NROGUIA,  VLRENVIA, ENTREGADO, 
                  F_ENTREGADO, USUENTREGADO, IDFIRMAENTRE, IDFIRMARECI, TIPOENT, IDKPAGE, IDTERCERORESP
                  FROM IMOV WHERE CNSMOV='''+@CNSMOV+'''
                  '
         BEGIN TRY           
               EXECUTE(@SQL)              
         END TRY
         BEGIN CATCH
                 RETURN
         END CATCH

         SELECT @SQL='INSERT INTO '+@BDATOS+'.DBO.IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO, NOLOTE, NOLOTEPEDIDO,
                      FECHAVENCE, ESTADO, IDARTICULOTF, CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, USUARIOCONF,  FECHACONF, 
                      PRIEXI, FECHAREPOSI, IDARTICULOORI,CANTIDADORI, TIENECAMBIO, DETALLE, CANT_EN_ACTIVOS, ENCXP, PIVA, VLRIVA, PDTO,
                      VLRDTO, CNSHTX, COTIZADO, IDIMPUESTO,IDCLASE,  ITFC, CNSITFC, CUENTA_FIMPDV, IDITAR, CODCUM, CAMBIADO, PCOSTOANTESMOD,
                      USUARIOCAMBIO, IDFABRICANTE, CUENTADB, CUENTACR, IDSERVICIO, VLRIMPCONSUMO, NOPRESTACION, RENFER, USUARIOR,  CANTREP,
                      DILUYENTE, RINVIMA, SELLOCALIDAD, CAPACIDAD, ODESFERA, OIESFERA, ODCILINDRO, OICILINDRO, ODEJE, OIEJE, ODADICION, 
                      OIADICION, ODALT, OIALT, ODAVL, OIAVL, ODTLENTE, OITLENTE,  ODDNP, OIDNP, ENVIADO, EXISLOTE, PCOSTOPP, VIVACOPA, 
                      VIVATCOPA, VIVATVENTA, PVENTAT, COBRACOPA, AUTORIZADO, USUAUTORIZA, VLR_COPAGO, ESPART, ESTANTE)
                      SELECT '''+@CNSMOVDES+''', ISAL.IDARTICULO, 0, ISAL.CANTIDAD, 0, ISAL.PCOSTO, ISAL.NOLOTE, ISAL.NOLOTEPEDIDO,
                      ISAL.FECHAVENCE, 0, IDARTICULOTF, CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, USUARIOCONF,  FECHACONF, 
                      PRIEXI, FECHAREPOSI, IDARTICULOORI,CANTIDADORI, TIENECAMBIO, DETALLE, CANT_EN_ACTIVOS, ENCXP, PIVA, VLRIVA, PDTO,
                      VLRDTO, CNSHTX, COTIZADO, IDIMPUESTO,IDCLASE,  ITFC, CNSITFC, CUENTA_FIMPDV, IDITAR, CODCUM, CAMBIADO, PCOSTOANTESMOD,
                      USUARIOCAMBIO, IDFABRICANTE, CUENTADB, CUENTACR, IDSERVICIO, VLRIMPCONSUMO, NOPRESTACION, RENFER, USUARIOR,  CANTREP,
                      DILUYENTE, RINVIMA, SELLOCALIDAD, CAPACIDAD, ODESFERA, OIESFERA, ODCILINDRO, OICILINDRO, ODEJE, OIEJE, ODADICION, 
                      OIADICION, ODALT, OIALT, ODAVL, OIAVL, ODTLENTE, OITLENTE,  ODDNP, OIDNP, ENVIADO, ISAL.EXISLOTE, PCOSTOPP, VIVACOPA, 
                      VIVATCOPA, VIVATVENTA, PVENTAT, COBRACOPA, AUTORIZADO, USUAUTORIZA, VLR_COPAGO, ESPART, ESTANTE
                      FROM IMOVH INNER JOIN ISAL ON IMOVH.CNSMOV=ISAL.CNSMOV AND IMOVH.IDARTICULO=ISAL.IDARTICULO_IMOVH 
                      WHERE IMOVH.CNSMOV='''+@CNSMOV+''''
      
      BEGIN TRY           
           EXECUTE(@SQL)              
      END TRY
      BEGIN CATCH
              PRINT @SQL
              PRINT 'ERROR INSERT IMOVH '+ERROR_MESSAGE()
              SELECT @SQL='DELETE '+@BDATOS+'.DBO.IMOV WHERE CNSMOV='''+@CNSMOVDES+''''
              EXECUTE(@SQL)
              RETURN
      END CATCH
      
      UPDATE IMOV SET ENTREGADO=1,NROGUIA=@CNSMOVDES,F_ENTREGADO=DBO.FNK_GETDATE() WHERE CNSMOV=@CNSMOV

   END

END
