IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_GENCOBRO_INSCENTRAL' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_GENCOBRO_INSCENTRAL 
END
GO
CREATE  PROCEDURE DBO.SPK_GENCOBRO_INSCENTRAL  
@CNSMOV     VARCHAR(20),
@NOADMISION VARCHAR(20),
@SECTOR     VARCHAR(20),
@USUARIO    VARCHAR(20),
@SEDE       VARCHAR(6) 
WITH ENCRYPTION
AS  
DECLARE @EXISTE    INT
DECLARE @EXISTEA   INT
DECLARE @DXPPAL    VARCHAR(5)
DECLARE @NVOCONSEC VARCHAR(20)
DECLARE @IDTERCERO VARCHAR(20)
DECLARE @IDPLAN    VARCHAR(6)
DECLARE @FECHA     DATETIME
DECLARE @SYS_COMPUTERNAME VARCHAR(255) 
DECLARE @CCOSTO    VARCHAR(20)
DECLARE @IDAREA    VARCHAR(20)
DECLARE @IDAREAH   VARCHAR(5)
DECLARE @ALTOCOSTO VARCHAR(5)
DECLARE @PREFIJO   VARCHAR(10)
DECLARE @COMPANIA  VARCHAR(5)='01'
DECLARE @CNSIZSOL  VARCHAR(20)
DECLARE @CLASE     VARCHAR(10)
DECLARE @ITEM      INT
DECLARE @NOPROGRAMACION VARCHAR(20)
DECLARE @CNSQXPCX       VARCHAR(20)
DECLARE @USUARIOSOL     VARCHAR(20)
DECLARE @COBRAMEZCLA    SMALLINT
DECLARE @IZSOLCNSMOV    VARCHAR(20)
DECLARE @IX             VARCHAR(20)
DECLARE @MODOCOBROMEDHBALI VARCHAR(20)=DBO.FNK_VALORVARIABLE('MODOCOBROMEDHBALI')
DECLARE @OMCODMEZCLA    VARCHAR(20)=DBO.FNK_VALORVARIABLE('OMCODMEZCLA')
DECLARE @OMCODNUTRICIONP VARCHAR(20)=DBO.FNK_VALORVARIABLE('OMCODNUTRICIONP')
DECLARE @IENF_MEZCLA    VARCHAR(20)=DBO.FNK_VALORVARIABLE('IENF_MEZCLA')
DECLARE @IENF_NUTP      VARCHAR(20)=DBO.FNK_VALORVARIABLE('IENF_NUTP')
DECLARE @SPD            SMALLINT
DECLARE @HOY            DATETIME=CONVERT(smalldatetime,GETDATE())
DECLARE @VT             DECIMAL(14,2)
DECLARE @VE             DECIMAL(14,2)
DECLARE @VC             DECIMAL(14,2)
DECLARE @VP             DECIMAL(14,2)
DECLARE @FECHASOL       DATETIME
DECLARE @IDSERVICIO     VARCHAR(20)
DECLARE @NOAUT     VARCHAR(20)
DECLARE @IDAUT     VARCHAR(20)
DECLARE @CONSECUTIVOHC VARCHAR(20)
DECLARE @CONSECUTIVOCIT VARCHAR(20)
DECLARE @NOITEMS  SMALLINT
DECLARE @VLR_TOTAL DECIMAL(14,2)
BEGIN 
   SELECT @IX=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('IXCOUNTRY')))
   SELECT @CNSIZSOL=IZSOL.CNSIZSOL,@CLASE=IZSOL.CLASE,@USUARIOSOL=USUARIOSOL, @IZSOLCNSMOV=IZSOL.CNSMOV 
   FROM IMOV  INNER JOIN IZSOL ON IMOV.NODOCUMENTO=IZSOL.CNSIZSOL AND IMOV.PROCEDENCIA='CM_SOL'
   WHERE IMOV.CNSMOV=@CNSMOV
   IF @CLASE='HPRE' 
   BEGIN
      PRINT 'YA ESTA COBRADO'
      SELECT @NVOCONSEC=CNSIZSOLM FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL
      UPDATE IMOV  SET NOPRESTACION=@NVOCONSEC WHERE CNSMOV=@CNSMOV
      UPDATE IMOVH SET NOPRESTACION=@NVOCONSEC WHERE CNSMOV=@CNSMOV
      UPDATE HPRED SET CNSMOV=@CNSMOV WHERE NOPRESTACION=@NVOCONSEC
      UPDATE HPRE SET CNSMOV=@CNSMOV WHERE NOPRESTACION=@NVOCONSEC
      RETURN
   END
   IF @CLASE='HTX'
   BEGIN
      PRINT 'SE COBRA EN HTX'
      IF @IX='PERU'
      BEGIN
         UPDATE HTX SET ENTREGADO=1, LISTOENTREGA=1, 
               CANTIDADINV=CASE ISNULL(HTX.APLICADO,0) WHEN 1 THEN CANTIDADINV ELSE ISNULL(HTX.CANTIDADINV,0)+IMOVH.CANTIDAD END,
               APLICADO=CASE ISNULL(SER.SPD,0) WHEN 1 THEN HTX.APLICADO ELSE 1 END, 
               ENCARGOS=CASE ISNULL(SER.SPD,0) WHEN 1 THEN HTX.ENCARGOS ELSE 1 END
         FROM IMOVH INNER JOIN IZSOLD ON IMOVH.CNSHTX=IZSOLD.CNSIZSOLD
                    INNER JOIN HTX ON IZSOLD.CNSHBALI=HTX.CNSHTX
                    INNER JOIN SER ON IMOVH.IDSERVICIO=SER.IDSERVICIO
         WHERE IMOVH.CNSMOV=@CNSMOV

         SELECT @USUARIO=ISNULL(HCA.USUARIO,@USUARIO), @FECHASOL=CONVERT(SMALLDATETIME,HCA.FECHA)
         FROM HTX INNER JOIN HCA ON HCA.CONSECUTIVO=HTX.CONSECUTIVOHCA
         WHERE HTX.CNSMOV=@CNSMOV
      END
      ELSE
      BEGIN
         UPDATE HTX SET ENTREGADO=1, LISTOENTREGA=1 WHERE CNSMOV=@CNSMOV
         RETURN
      END
   END
   IF @CLASE='CE'
   BEGIN
      
      IF @IX='PERU' 
      BEGIN
         SELECT * INTO #AUT FROM AUT  WHERE NOAUT=@NOADMISION 
         SELECT @IDTERCERO=IDTERCEROCA,@IDPLAN=IDPLAN,@CONSECUTIVOHC=CONSECUTIVOHCA FROM AUT WHERE NOAUT=@NOADMISION
         IF COALESCE(@CONSECUTIVOHC,'')<>''
         BEGIN
            SELECT @CONSECUTIVOCIT=CONSECUTIVOCIT  FROM HCA WHERE CONSECUTIVO=@CONSECUTIVOHC
         END
         PRINT 'SERVICIOS AFECTOS'
         IF EXISTS(SELECT * FROM IMOVH INNER JOIN SER ON IMOVH.IDARTICULO=SER.IDSERVICIO WHERE COALESCE(SER.IVA,'')<>'' AND COALESCE(SER.IDIMPUESTO,'')<>'' AND COALESCE(SER.IDCLASE,'')<>'' AND COALESCE(ESPART,0)=0 AND COALESCE(IMOVH.NOPRESTACION,'')='')
         BEGIN
            SELECT @IDAUT = SPACE(20)
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@AUT',@IDAUT OUTPUT
            SELECT @IDAUT = @SEDE + REPLACE(SPACE(8 - LEN(@IDAUT))+LTRIM(RTRIM(@IDAUT)), SPACE(1),0)

            PRINT '@IDAUT='+@IDAUT
   
            SELECT @NOAUT = SPACE(20)
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@AUTF',@NOAUT OUTPUT
            SELECT @NOAUT = @SEDE + REPLACE(SPACE(8 - LEN(@NOAUT))+LTRIM(RTRIM(@NOAUT)), SPACE(1),0)

            INSERT INTO AUTD (IDAUT, NO_ITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALORCOPAGOCOSTO, VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                        COMENTARIOS, PCOBERTURA, OBS, NORDEN, CCOSTO,  CODIGOCPCJ, MARCAPAGO, NOAUTORIZEXT, ESDELAB, ENLAB, IDTERCEROCA, IDCONTRATO, FACTURADA, 
                        N_FACTURA, CNSFCT, AQUIENCOBRO, MARCACOPAGOORDEN, VALORPROV, PCOSTO, ITFC, CNSITFC, SYS_COMPUTERNAME,  NOCOBRABLE, MDOSIFICACION, CANTIDIA, 
                        DIAS, FRECUENCIA, CODCUPS, POSOLOGIA, SINCRONIZADO, APOYODG_AMBITO, CITAAUTORIZADA, DOSISAPL, DURACIONTTOF, DURACIONTTOC, CLASEPOSOLOGIA,  
                        MARCA, USUARIOMARCA, NUM_ORDEN, PROCESADA, PRIORIDAD, HOMOLOGO, IDSERVICIOH, CANTIDADH, VALORHOMO, NO_ITEMH, N_FACTURAORI, DESCUENTO, 
                        TIPODTO, CNSFMED, F_INGLAB, F_SALILAB,  IDARTICULO, IMPORTADO, NFACTURA )
            SELECT      @IDAUT, ROW_NUMBER() OVER(ORDER  BY IMOVH.IDARTICULO  ASC), IMOVH.IDARTICULO, IMOVH.CANTIDAD, PVENTA, VLR_COPAGO*IMOVH.CANTIDAD, 0, (PVENTA*IMOVH.CANTIDAD)-COALESCE(VLR_COPAGO,0),
                        (IMOVH.CANTIDAD*IMOVH.PCOSTO), @IDPLAN, 0, 1, NULL, 100, NULL, NULL, NULL,  NULL, NULL, NULL, 0, 0, @IDTERCERO, NULL, 0, 
                        NULL, NULL, NULL, NULL, NULL, IMOVH.PCOSTO, NULL, NULL, @SYS_COMPUTERNAME,  NULL, NULL, NULL, 
                        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                        'V', NULL, NULL, NULL,  IART.IDSERVICIO, NULL, NULL
            FROM IMOVH INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
                        INNER JOIN SER ON  IMOVH.IDARTICULO=SER.IDSERVICIO 
            WHERE CNSMOV=@CNSMOV
            AND COALESCE(SER.IVA,'')<>'' 
            AND COALESCE(SER.IDIMPUESTO,'')<>'' 
            AND COALESCE(SER.IDCLASE,'')<>''
            AND COALESCE(ESPART,0)=0
            AND COALESCE(IMOVH.NOPRESTACION,'')=''

            PRINT '@NOAUT='+@NOAUT

            UPDATE #AUT SET IDAUT=@IDAUT,NOAUT=@NOAUT,CONSECUTIVOCIT=@CONSECUTIVOCIT,FACTURADA=0,N_FACTURA=NULL,ESTADO='Pendiente' WHERE 1=1
            INSERT INTO AUT(IDAUT, NOAUT, FECHA, FECHAVENCE, FECHASOL, IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, IDSEDEORIGEN, TIPOAUTORIZACION, 
                              ALTOCOSTO, ATENCION, URGENCIA, IMPUTABLE_A, IDSOLICITANTE,  IDPROVEEDOR, ESTADO, CONSANULADO, IDOPERADORANULA, FECHAANULA, 
                              CAUSALANULA, NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO,  IMPRESO,
                              CXPGEN, CXCGEN, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, IDPESPECIAL, IDESTADOE, USUARIO, RECOBRARA, FUENTE, 
                              IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL,  DXRELACIONADO, COMPLICACION, FORMAQX, TIPOURGENCIA, SPD, NORECIBOCAJA, 
                              CLASEORDEN, GENEROCAJA, IDCONTRATANTE, TIPOCOPAGO, PEDIDOINV, ENVIO, OBS, ESCONTINUACION, NOAUTORIGEN,  SEMANASCOT, LIQUIDAPC, 
                              OBSDX, COMITE, CERTIFICACION, IDCLASEAUT, CLASECONT, ESDEINV, NOGENERACIONOPS, FECHAGEN, CNSAFIAA, PROCEDENCIA, IDAREAH, 
                              IDAREA, CCOSTO, SUBCCOSTO, NIVELATENCION,  FACTURADA, N_FACTURA, CNSFCT, VFACTURAS, FACTURABLE, DESCUENTO, TIPODTO, MARCAFAC, 
                              IDIPS, CLASECONTRATO, ENPAQUETE, IDCIRUGIA, SOAT, NOADMISION, IDCONTRATO, RUBRO, CLASERUBRO,  PERIODICIDAD, CNSFACT, 
                              CONTINUACION, VLRUTOTRA, TIPOCONT, DXRELACIONADO2, FECHACOMITE, IDALTERNA, MARCAENV, COPAGOPROPIO, CNSHACTRAN, ESDELAB, ENLAB,
                              COBRARA, IDTERCEROCA, CONSECUTIVOHCA,  RAZONANULACION, PIDECCOSTO, FECHAREALIZACION, CODCAJA, TIPOCAJA, IDGRUPOSER, PEXTERNA, 
                              AQUIENCOBRO, CODUNG, CODPRG, ITFC, CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, TIPOUSUARIO,  NOADMISIONCE, INDLABCORE, CERRADA, 
                              CONTABILIZADA, NROCOMPROBANTE, MARCACONT, SINCRONIZADO, IDPLAN_AFI, IDTERCERO_AFI, USUARIONOFACTURABLE, FECHA_NOFAC, RIESGO, 
                              IDSUCURSAL,  CIUDAD, FUNCIONARIO_AUT, IDIPSSOLICITA, IDMEDICOSOLICITA, DIRECCION, ORIGEN, VLRDEPOSITOS, NOTIFICADO, ENTREGADO,
                              FENTREGA, UENTREGA, TIPOAFILIADO, MENTREGA, NRO_ENTREGA, CANT_ENTREGAS,  RUBRO_ID, IDFIRMAPTE, IDFIRMARESP, CNSMOV, 
                              CONSECUTIVOCIT)
              SELECT @IDAUT, @NOAUT, DBO.FNK_GETDATE(), DBO.FNK_GETDATE()+30, DBO.FNK_GETDATE(), IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, IDSEDEORIGEN, TIPOAUTORIZACION, 
                              ALTOCOSTO, ATENCION, URGENCIA, IMPUTABLE_A, IDSOLICITANTE,  IDPROVEEDOR, ESTADO, CONSANULADO, IDOPERADORANULA, FECHAANULA, 
                              CAUSALANULA, NO_ITEMES, 0, 0, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO,  0,
                              CXPGEN, CXCGEN, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, IDPESPECIAL, IDESTADOE, @USUARIO, RECOBRARA, FUENTE, 
                              IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL,  DXRELACIONADO, COMPLICACION, FORMAQX, TIPOURGENCIA, SPD, NULL, 
                              CLASEORDEN, GENEROCAJA, IDCONTRATANTE, TIPOCOPAGO, 1, ENVIO, OBS, ESCONTINUACION, NOAUTORIGEN,  SEMANASCOT, LIQUIDAPC, 
                              OBSDX, COMITE, CERTIFICACION, IDCLASEAUT, CLASECONT, 1, NOGENERACIONOPS, FECHAGEN, CNSAFIAA, PROCEDENCIA, IDAREAH, 
                              IDAREA, CCOSTO, SUBCCOSTO, NIVELATENCION,  FACTURADA, N_FACTURA, CNSFCT, VFACTURAS, FACTURABLE, DESCUENTO, TIPODTO, MARCAFAC, 
                              IDIPS, CLASECONTRATO, ENPAQUETE, IDCIRUGIA, SOAT, NOADMISION, IDCONTRATO, RUBRO, CLASERUBRO,  PERIODICIDAD, CNSFACT, 
                              CONTINUACION, VLRUTOTRA, TIPOCONT, DXRELACIONADO2, FECHACOMITE, IDALTERNA, MARCAENV, COPAGOPROPIO, CNSHACTRAN, ESDELAB, ENLAB,
                              COBRARA, IDTERCEROCA, @CONSECUTIVOHC,  RAZONANULACION, PIDECCOSTO, FECHAREALIZACION, NULL, NULL, IDGRUPOSER, PEXTERNA, 
                              AQUIENCOBRO, CODUNG, CODPRG, ITFC, CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, TIPOUSUARIO,  NOADMISIONCE, INDLABCORE, CERRADA, 
                              0, NULL, 0, SINCRONIZADO, IDPLAN_AFI, IDTERCERO_AFI, USUARIONOFACTURABLE, FECHA_NOFAC, RIESGO, 
                              IDSUCURSAL,  CIUDAD, FUNCIONARIO_AUT, IDIPSSOLICITA, IDMEDICOSOLICITA, DIRECCION, ORIGEN, VLRDEPOSITOS, NOTIFICADO, ENTREGADO,
                              FENTREGA, UENTREGA, TIPOAFILIADO, MENTREGA, NRO_ENTREGA, CANT_ENTREGAS,  RUBRO_ID, IDFIRMAPTE, IDFIRMARESP, CNSMOV, 
                              @CONSECUTIVOCIT
               FROM #AUT

               SELECT @NOITEMS=COUNT(*) FROM AUTD WHERE IDAUT=@IDAUT
               SELECT @VLR_TOTAL=SUM(VALOR*CANTIDAD) FROM AUTD WHERE IDAUT=@IDAUT

               UPDATE AUT SET NO_ITEMES=@NOITEMS,VALORTOTAL=@VLR_TOTAL,VALOREXEDENTE=@VLR_TOTAL WHERE IDAUT=@IDAUT 

               UPDATE IMOVH SET NOPRESTACION= @IDAUT
               FROM IMOVH INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
                           INNER JOIN SER ON  IMOVH.IDARTICULO=SER.IDSERVICIO 
               WHERE CNSMOV=@CNSMOV
               AND COALESCE(SER.IVA,'')<>'' 
               AND COALESCE(SER.IDIMPUESTO,'')<>'' 
               AND COALESCE(SER.IDCLASE,'')<>''
               AND COALESCE(ESPART,0)=0
               AND COALESCE(IMOVH.NOPRESTACION,'')=''

         END
         PRINT 'SERVICIOS INAFECTOS...'
         IF EXISTS(SELECT * FROM IMOVH INNER JOIN SER ON IMOVH.IDARTICULO=SER.IDSERVICIO WHERE COALESCE(SER.IVA,'')='' AND COALESCE(SER.IDIMPUESTO,'')='' AND COALESCE(SER.IDCLASE,'')='' AND COALESCE(ESPART,0)=0 AND COALESCE(IMOVH.NOPRESTACION,'')='' )
         BEGIN
            SELECT @IDAUT = SPACE(20)
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@AUT',@IDAUT OUTPUT
            SELECT @IDAUT = @SEDE + REPLACE(SPACE(8 - LEN(@IDAUT))+LTRIM(RTRIM(@IDAUT)), SPACE(1),0)

            PRINT '@IDAUT='+@IDAUT
   
            SELECT @NOAUT = SPACE(20)
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@AUTF',@NOAUT OUTPUT
            SELECT @NOAUT = @SEDE + REPLACE(SPACE(8 - LEN(@NOAUT))+LTRIM(RTRIM(@NOAUT)), SPACE(1),0)

            INSERT INTO AUTD (IDAUT, NO_ITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALORCOPAGOCOSTO, VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                        COMENTARIOS, PCOBERTURA, OBS, NORDEN, CCOSTO,  CODIGOCPCJ, MARCAPAGO, NOAUTORIZEXT, ESDELAB, ENLAB, IDTERCEROCA, IDCONTRATO, FACTURADA, 
                        N_FACTURA, CNSFCT, AQUIENCOBRO, MARCACOPAGOORDEN, VALORPROV, PCOSTO, ITFC, CNSITFC, SYS_COMPUTERNAME,  NOCOBRABLE, MDOSIFICACION, CANTIDIA, 
                        DIAS, FRECUENCIA, CODCUPS, POSOLOGIA, SINCRONIZADO, APOYODG_AMBITO, CITAAUTORIZADA, DOSISAPL, DURACIONTTOF, DURACIONTTOC, CLASEPOSOLOGIA,  
                        MARCA, USUARIOMARCA, NUM_ORDEN, PROCESADA, PRIORIDAD, HOMOLOGO, IDSERVICIOH, CANTIDADH, VALORHOMO, NO_ITEMH, N_FACTURAORI, DESCUENTO, 
                        TIPODTO, CNSFMED, F_INGLAB, F_SALILAB,  IDARTICULO, IMPORTADO, NFACTURA )
            SELECT      @IDAUT, ROW_NUMBER() OVER(ORDER  BY IMOVH.IDARTICULO  ASC), IMOVH.IDARTICULO, IMOVH.CANTIDAD, PVENTA, VLR_COPAGO*IMOVH.CANTIDAD, 0, (PVENTA*IMOVH.CANTIDAD)-COALESCE(VLR_COPAGO,0),
                        (IMOVH.CANTIDAD*IMOVH.PCOSTO), @IDPLAN, 0, 1, NULL, 100, NULL, NULL, NULL,  NULL, NULL, NULL, 0, 0, @IDTERCERO, NULL, 0, 
                        NULL, NULL, NULL, NULL, NULL, IMOVH.PCOSTO, NULL, NULL, @SYS_COMPUTERNAME,  NULL, NULL, NULL, 
                        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                        'V', NULL, NULL, NULL,  IART.IDSERVICIO, NULL, NULL
            FROM IMOVH INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
                        INNER JOIN SER ON  IMOVH.IDARTICULO=SER.IDSERVICIO 
            WHERE CNSMOV=@CNSMOV
            AND COALESCE(SER.IVA,'')='' 
            AND COALESCE(SER.IDIMPUESTO,'')='' 
            AND COALESCE(SER.IDCLASE,'')=''
            AND COALESCE(ESPART,0)=0
            AND COALESCE(IMOVH.NOPRESTACION,'')=''

            PRINT '@NOAUT='+@NOAUT

            UPDATE #AUT SET IDAUT=@IDAUT,NOAUT=@NOAUT,CONSECUTIVOCIT=@CONSECUTIVOCIT,FACTURADA=0,N_FACTURA=NULL WHERE 1=1
            INSERT INTO AUT(IDAUT, NOAUT, FECHA, FECHAVENCE, FECHASOL, IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, IDSEDEORIGEN, TIPOAUTORIZACION, 
                              ALTOCOSTO, ATENCION, URGENCIA, IMPUTABLE_A, IDSOLICITANTE,  IDPROVEEDOR, ESTADO, CONSANULADO, IDOPERADORANULA, FECHAANULA, 
                              CAUSALANULA, NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO,  IMPRESO,
                              CXPGEN, CXCGEN, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, IDPESPECIAL, IDESTADOE, USUARIO, RECOBRARA, FUENTE, 
                              IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL,  DXRELACIONADO, COMPLICACION, FORMAQX, TIPOURGENCIA, SPD, NORECIBOCAJA, 
                              CLASEORDEN, GENEROCAJA, IDCONTRATANTE, TIPOCOPAGO, PEDIDOINV, ENVIO, OBS, ESCONTINUACION, NOAUTORIGEN,  SEMANASCOT, LIQUIDAPC, 
                              OBSDX, COMITE, CERTIFICACION, IDCLASEAUT, CLASECONT, ESDEINV, NOGENERACIONOPS, FECHAGEN, CNSAFIAA, PROCEDENCIA, IDAREAH, 
                              IDAREA, CCOSTO, SUBCCOSTO, NIVELATENCION,  FACTURADA, N_FACTURA, CNSFCT, VFACTURAS, FACTURABLE, DESCUENTO, TIPODTO, MARCAFAC, 
                              IDIPS, CLASECONTRATO, ENPAQUETE, IDCIRUGIA, SOAT, NOADMISION, IDCONTRATO, RUBRO, CLASERUBRO,  PERIODICIDAD, CNSFACT, 
                              CONTINUACION, VLRUTOTRA, TIPOCONT, DXRELACIONADO2, FECHACOMITE, IDALTERNA, MARCAENV, COPAGOPROPIO, CNSHACTRAN, ESDELAB, ENLAB,
                              COBRARA, IDTERCEROCA, CONSECUTIVOHCA,  RAZONANULACION, PIDECCOSTO, FECHAREALIZACION, CODCAJA, TIPOCAJA, IDGRUPOSER, PEXTERNA, 
                              AQUIENCOBRO, CODUNG, CODPRG, ITFC, CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, TIPOUSUARIO,  NOADMISIONCE, INDLABCORE, CERRADA, 
                              CONTABILIZADA, NROCOMPROBANTE, MARCACONT, SINCRONIZADO, IDPLAN_AFI, IDTERCERO_AFI, USUARIONOFACTURABLE, FECHA_NOFAC, RIESGO, 
                              IDSUCURSAL,  CIUDAD, FUNCIONARIO_AUT, IDIPSSOLICITA, IDMEDICOSOLICITA, DIRECCION, ORIGEN, VLRDEPOSITOS, NOTIFICADO, ENTREGADO,
                              FENTREGA, UENTREGA, TIPOAFILIADO, MENTREGA, NRO_ENTREGA, CANT_ENTREGAS,  RUBRO_ID, IDFIRMAPTE, IDFIRMARESP, CNSMOV, 
                              CONSECUTIVOCIT)
              SELECT @IDAUT, @NOAUT, DBO.FNK_GETDATE(), DBO.FNK_GETDATE()+30, DBO.FNK_GETDATE(), IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, IDSEDEORIGEN, TIPOAUTORIZACION, 
                              ALTOCOSTO, ATENCION, URGENCIA, IMPUTABLE_A, IDSOLICITANTE,  IDPROVEEDOR, ESTADO, CONSANULADO, IDOPERADORANULA, FECHAANULA, 
                              CAUSALANULA, NO_ITEMES, 0, 0, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO,  0,
                              CXPGEN, CXCGEN, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, IDPESPECIAL, IDESTADOE, @USUARIO, RECOBRARA, FUENTE, 
                              IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL,  DXRELACIONADO, COMPLICACION, FORMAQX, TIPOURGENCIA, SPD, NULL, 
                              CLASEORDEN, GENEROCAJA, IDCONTRATANTE, TIPOCOPAGO, 1, ENVIO, OBS, ESCONTINUACION, NOAUTORIGEN,  SEMANASCOT, LIQUIDAPC, 
                              OBSDX, COMITE, CERTIFICACION, IDCLASEAUT, CLASECONT, 1, NOGENERACIONOPS, FECHAGEN, CNSAFIAA, PROCEDENCIA, IDAREAH, 
                              IDAREA, CCOSTO, SUBCCOSTO, NIVELATENCION,  FACTURADA, N_FACTURA, CNSFCT, VFACTURAS, FACTURABLE, DESCUENTO, TIPODTO, MARCAFAC, 
                              IDIPS, CLASECONTRATO, ENPAQUETE, IDCIRUGIA, SOAT, NOADMISION, IDCONTRATO, RUBRO, CLASERUBRO,  PERIODICIDAD, CNSFACT, 
                              CONTINUACION, VLRUTOTRA, TIPOCONT, DXRELACIONADO2, FECHACOMITE, IDALTERNA, MARCAENV, COPAGOPROPIO, CNSHACTRAN, ESDELAB, ENLAB,
                              COBRARA, IDTERCEROCA, @CONSECUTIVOHC,  RAZONANULACION, PIDECCOSTO, FECHAREALIZACION, NULL, NULL, IDGRUPOSER, PEXTERNA, 
                              AQUIENCOBRO, CODUNG, CODPRG, ITFC, CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, TIPOUSUARIO,  NOADMISIONCE, INDLABCORE, CERRADA, 
                              0, NULL, 0, SINCRONIZADO, IDPLAN_AFI, IDTERCERO_AFI, USUARIONOFACTURABLE, FECHA_NOFAC, RIESGO, 
                              IDSUCURSAL,  CIUDAD, FUNCIONARIO_AUT, IDIPSSOLICITA, IDMEDICOSOLICITA, DIRECCION, ORIGEN, VLRDEPOSITOS, NOTIFICADO, ENTREGADO,
                              FENTREGA, UENTREGA, TIPOAFILIADO, MENTREGA, NRO_ENTREGA, CANT_ENTREGAS,  RUBRO_ID, IDFIRMAPTE, IDFIRMARESP, CNSMOV, 
                              @CONSECUTIVOCIT
               FROM #AUT

               SELECT @NOITEMS=COUNT(*) FROM AUTD WHERE IDAUT=@IDAUT
               SELECT @VLR_TOTAL=SUM(VALOR*CANTIDAD) FROM AUTD WHERE IDAUT=@IDAUT

               UPDATE AUT SET NO_ITEMES=@NOITEMS,VALORTOTAL=@VLR_TOTAL,VALOREXEDENTE=@VLR_TOTAL WHERE IDAUT=@IDAUT 


               UPDATE IMOVH SET NOPRESTACION=@IDAUT
               FROM IMOVH INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
                           INNER JOIN SER ON  IMOVH.IDARTICULO=SER.IDSERVICIO 
               WHERE CNSMOV=@CNSMOV
               AND COALESCE(SER.IVA,'')='' 
               AND COALESCE(SER.IDIMPUESTO,'')='' 
               AND COALESCE(SER.IDCLASE,'')=''
               AND COALESCE(ESPART,0)=0
               AND COALESCE(IMOVH.NOPRESTACION,'')=''

            END

         PRINT 'SERVICIOS PARTICULARES...'
         IF EXISTS(SELECT * FROM IMOVH INNER JOIN SER ON IMOVH.IDARTICULO=SER.IDSERVICIO WHERE COALESCE(ESPART,0)=1 AND COALESCE(IMOVH.NOPRESTACION,'')='')
         BEGIN
            DECLARE @IDTERPART VARCHAR(20)
            DECLARE @IDPLANPART VARCHAR(20)
            SELECT @IDTERPART=DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'),@IDPLANPART=DBO.FNK_VALORVARIABLE('IDPLANPART')
            SELECT @IDAUT = SPACE(20)
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@AUT',@IDAUT OUTPUT
            SELECT @IDAUT = @SEDE + REPLACE(SPACE(8 - LEN(@IDAUT))+LTRIM(RTRIM(@IDAUT)), SPACE(1),0)

            PRINT '@IDAUT='+@IDAUT
   
            SELECT @NOAUT = SPACE(20)
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@AUTF',@NOAUT OUTPUT
            SELECT @NOAUT = @SEDE + REPLACE(SPACE(8 - LEN(@NOAUT))+LTRIM(RTRIM(@NOAUT)), SPACE(1),0)

            INSERT INTO AUTD (IDAUT, NO_ITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALORCOPAGOCOSTO, VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                        COMENTARIOS, PCOBERTURA, OBS, NORDEN, CCOSTO,  CODIGOCPCJ, MARCAPAGO, NOAUTORIZEXT, ESDELAB, ENLAB, IDTERCEROCA, IDCONTRATO, FACTURADA, 
                        N_FACTURA, CNSFCT, AQUIENCOBRO, MARCACOPAGOORDEN, VALORPROV, PCOSTO, ITFC, CNSITFC, SYS_COMPUTERNAME,  NOCOBRABLE, MDOSIFICACION, CANTIDIA, 
                        DIAS, FRECUENCIA, CODCUPS, POSOLOGIA, SINCRONIZADO, APOYODG_AMBITO, CITAAUTORIZADA, DOSISAPL, DURACIONTTOF, DURACIONTTOC, CLASEPOSOLOGIA,  
                        MARCA, USUARIOMARCA, NUM_ORDEN, PROCESADA, PRIORIDAD, HOMOLOGO, IDSERVICIOH, CANTIDADH, VALORHOMO, NO_ITEMH, N_FACTURAORI, DESCUENTO, 
                        TIPODTO, CNSFMED, F_INGLAB, F_SALILAB,  IDARTICULO, IMPORTADO, NFACTURA )
            SELECT      @IDAUT, ROW_NUMBER() OVER(ORDER  BY IMOVH.IDARTICULO  ASC), IMOVH.IDARTICULO, IMOVH.CANTIDAD, PVENTA, 0, 0, (PVENTA*IMOVH.CANTIDAD),
                        (IMOVH.CANTIDAD*IMOVH.PCOSTO), @IDPLANPART, 0, 1, NULL, 100, NULL, NULL, NULL,  NULL, NULL, NULL, 0, 0, @IDTERPART, NULL, 0, 
                        NULL, NULL, NULL, NULL, NULL, IMOVH.PCOSTO, NULL, NULL, @SYS_COMPUTERNAME,  NULL, NULL, NULL, 
                        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                        'V', NULL, NULL, NULL,  IART.IDSERVICIO, NULL, NULL
            FROM IMOVH INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
                        INNER JOIN SER ON  IMOVH.IDARTICULO=SER.IDSERVICIO 
            WHERE CNSMOV=@CNSMOV
            AND COALESCE(ESPART,0)=1
            AND COALESCE(IMOVH.NOPRESTACION,'')=''

            PRINT '@NOAUT='+@NOAUT

            UPDATE #AUT SET IDAUT=@IDAUT,NOAUT=@NOAUT,CONSECUTIVOCIT=@CONSECUTIVOCIT,FACTURADA=0,N_FACTURA=NULL,IDTERCEROCA=@IDTERPART,IDPLAN=@IDPLANPART WHERE 1=1
            INSERT INTO AUT(IDAUT, NOAUT, FECHA, FECHAVENCE, FECHASOL, IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, IDSEDEORIGEN, TIPOAUTORIZACION, 
                              ALTOCOSTO, ATENCION, URGENCIA, IMPUTABLE_A, IDSOLICITANTE,  IDPROVEEDOR, ESTADO, CONSANULADO, IDOPERADORANULA, FECHAANULA, 
                              CAUSALANULA, NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO,  IMPRESO,
                              CXPGEN, CXCGEN, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, IDPESPECIAL, IDESTADOE, USUARIO, RECOBRARA, FUENTE, 
                              IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL,  DXRELACIONADO, COMPLICACION, FORMAQX, TIPOURGENCIA, SPD, NORECIBOCAJA, 
                              CLASEORDEN, GENEROCAJA, IDCONTRATANTE, TIPOCOPAGO, PEDIDOINV, ENVIO, OBS, ESCONTINUACION, NOAUTORIGEN,  SEMANASCOT, LIQUIDAPC, 
                              OBSDX, COMITE, CERTIFICACION, IDCLASEAUT, CLASECONT, ESDEINV, NOGENERACIONOPS, FECHAGEN, CNSAFIAA, PROCEDENCIA, IDAREAH, 
                              IDAREA, CCOSTO, SUBCCOSTO, NIVELATENCION,  FACTURADA, N_FACTURA, CNSFCT, VFACTURAS, FACTURABLE, DESCUENTO, TIPODTO, MARCAFAC, 
                              IDIPS, CLASECONTRATO, ENPAQUETE, IDCIRUGIA, SOAT, NOADMISION, IDCONTRATO, RUBRO, CLASERUBRO,  PERIODICIDAD, CNSFACT, 
                              CONTINUACION, VLRUTOTRA, TIPOCONT, DXRELACIONADO2, FECHACOMITE, IDALTERNA, MARCAENV, COPAGOPROPIO, CNSHACTRAN, ESDELAB, ENLAB,
                              COBRARA, IDTERCEROCA, CONSECUTIVOHCA,  RAZONANULACION, PIDECCOSTO, FECHAREALIZACION, CODCAJA, TIPOCAJA, IDGRUPOSER, PEXTERNA, 
                              AQUIENCOBRO, CODUNG, CODPRG, ITFC, CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, TIPOUSUARIO,  NOADMISIONCE, INDLABCORE, CERRADA, 
                              CONTABILIZADA, NROCOMPROBANTE, MARCACONT, SINCRONIZADO, IDPLAN_AFI, IDTERCERO_AFI, USUARIONOFACTURABLE, FECHA_NOFAC, RIESGO, 
                              IDSUCURSAL,  CIUDAD, FUNCIONARIO_AUT, IDIPSSOLICITA, IDMEDICOSOLICITA, DIRECCION, ORIGEN, VLRDEPOSITOS, NOTIFICADO, ENTREGADO,
                              FENTREGA, UENTREGA, TIPOAFILIADO, MENTREGA, NRO_ENTREGA, CANT_ENTREGAS,  RUBRO_ID, IDFIRMAPTE, IDFIRMARESP, CNSMOV, 
                              CONSECUTIVOCIT)
              SELECT @IDAUT, @NOAUT, DBO.FNK_GETDATE(), DBO.FNK_GETDATE()+30, DBO.FNK_GETDATE(), IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, IDSEDEORIGEN, TIPOAUTORIZACION, 
                              ALTOCOSTO, ATENCION, URGENCIA, IMPUTABLE_A, IDSOLICITANTE,  IDPROVEEDOR, ESTADO, CONSANULADO, IDOPERADORANULA, FECHAANULA, 
                              CAUSALANULA, NO_ITEMES, 0, 0, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO,  0,
                              CXPGEN, CXCGEN, AUTORIZADOPOR, NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, IDPESPECIAL, IDESTADOE, @USUARIO, RECOBRARA, FUENTE, 
                              IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL,  DXRELACIONADO, COMPLICACION, FORMAQX, TIPOURGENCIA, SPD, NULL, 
                              CLASEORDEN, GENEROCAJA, IDCONTRATANTE, TIPOCOPAGO, 1, ENVIO, OBS, ESCONTINUACION, NOAUTORIGEN,  SEMANASCOT, LIQUIDAPC, 
                              OBSDX, COMITE, CERTIFICACION, IDCLASEAUT, CLASECONT, 1, NOGENERACIONOPS, FECHAGEN, CNSAFIAA, PROCEDENCIA, IDAREAH, 
                              IDAREA, CCOSTO, SUBCCOSTO, NIVELATENCION,  FACTURADA, N_FACTURA, CNSFCT, VFACTURAS, FACTURABLE, DESCUENTO, TIPODTO, MARCAFAC, 
                              IDIPS, CLASECONTRATO, ENPAQUETE, IDCIRUGIA, SOAT, NOADMISION, IDCONTRATO, RUBRO, CLASERUBRO,  PERIODICIDAD, CNSFACT, 
                              CONTINUACION, VLRUTOTRA, TIPOCONT, DXRELACIONADO2, FECHACOMITE, IDALTERNA, MARCAENV, COPAGOPROPIO, CNSHACTRAN, ESDELAB, ENLAB,
                              COBRARA, IDTERCEROCA, @CONSECUTIVOHC,  RAZONANULACION, PIDECCOSTO, FECHAREALIZACION, NULL, NULL, IDGRUPOSER, PEXTERNA, 
                              AQUIENCOBRO, CODUNG, CODPRG, ITFC, CNSITFC, SYS_COMPUTERNAME, CNSLABCOR, TIPOUSUARIO,  NOADMISIONCE, INDLABCORE, CERRADA, 
                              0, NULL, 0, SINCRONIZADO, IDPLAN_AFI, IDTERCERO_AFI, USUARIONOFACTURABLE, FECHA_NOFAC, RIESGO, 
                              IDSUCURSAL,  CIUDAD, FUNCIONARIO_AUT, IDIPSSOLICITA, IDMEDICOSOLICITA, DIRECCION, ORIGEN, VLRDEPOSITOS, NOTIFICADO, ENTREGADO,
                              FENTREGA, UENTREGA, TIPOAFILIADO, MENTREGA, NRO_ENTREGA, CANT_ENTREGAS,  RUBRO_ID, IDFIRMAPTE, IDFIRMARESP, CNSMOV, 
                              @CONSECUTIVOCIT
               FROM #AUT

               SELECT @NOITEMS=COUNT(*) FROM AUTD WHERE IDAUT=@IDAUT
               SELECT @VLR_TOTAL=SUM(VALOR*CANTIDAD) FROM AUTD WHERE IDAUT=@IDAUT

               UPDATE AUT SET NO_ITEMES=@NOITEMS,VALORTOTAL=@VLR_TOTAL,VALOREXEDENTE=@VLR_TOTAL WHERE IDAUT=@IDAUT 

               UPDATE IMOVH SET NOPRESTACION=@IDAUT
               FROM IMOVH INNER JOIN IART ON IMOVH.IDARTICULO=IART.IDARTICULO
                           INNER JOIN SER ON  IMOVH.IDARTICULO=SER.IDSERVICIO 
               WHERE CNSMOV=@CNSMOV
               AND COALESCE(ESPART,0)=1

            END
         PRINT 'TERMINO COBRO EN AUT Y AUTD'
         RETURN
      END
      PRINT 'YA ESTA COBRADO'
      RETURN
   END
   IF @CLASE='APOYODX'
   BEGIN
      PRINT 'Cargo a LORDI'
      UPDATE LORDI SET CANTIDADREAL=ISNULL(CANTIDADREAL,0)+M.CANTIDAD
      FROM LORDI 
         INNER JOIN DBO.VWK_HERMANOS_INVENTARIO H ON H.IDARTICULO=LORDI.IDARTICULO
         INNER JOIN (
            SELECT IDSERVICIO AS IDARTICULO, SUM(CANTIDAD) AS CANTIDAD 
            FROM IMOVH WHERE CNSMOV=@CNSMOV GROUP BY IDSERVICIO
        ) M ON M.IDARTICULO=H.HERMANO_MAYOR
      WHERE LORDI.NORDEN=@IZSOLCNSMOV 
      RETURN
   END
   IF @CLASE='QXPGCX'
   BEGIN
      PRINT 'Canasta Cirugia programacion'
	  SELECT @NOPROGRAMACION=CNSIZSOLM FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL
      IF EXISTS(SELECT * FROM QXPCX WHERE NOPROGRAMACION=@NOPROGRAMACION OR CONSECUTIVO=@NOPROGRAMACION)
      BEGIN
         SELECT @CNSQXPCX=CONSECUTIVO FROM QXPCX WHERE NOPROGRAMACION=@NOPROGRAMACION OR CONSECUTIVO=@NOPROGRAMACION
	     UPDATE QXPCXI SET CANTIDADREAL=IZSOLD.CANTIDAD
         FROM QXPCXI INNER JOIN (
               SELECT IZSOLD.CNSIZSOL, IZSOLD.IDSERVICIO, MAX(IZSOLDT.CNSMOV) CNSMOV, SUM(IZSOLDT.CANTIDADSOL) CANTIDAD
               FROM IZSOLD INNER JOIN IZSOLDT ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD AND IZSOLD.IDARTICULO=IZSOLDT.IDARTICULO
               WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
               GROUP BY IZSOLD.CNSIZSOL, IZSOLD.CNSHBALI, IZSOLD.IDSERVICIO
            )IZSOLD ON QXPCXI.CNSMOV=IZSOLD.CNSIZSOL AND QXPCXI.ARTICULO=IZSOLD.IDSERVICIO
	      WHERE QXPCXI.CONSECUTIVO=@CNSQXPCX
	      AND COALESCE(PEDIDOINV,0)=1
          AND QXPCXI.CNSMOV=@CNSIZSOL        
      END
	     UPDATE CXPSI SET CANTIDADREAL=IZSOLD.CANTIDAD
         FROM CXPSI INNER JOIN (
               SELECT IZSOLD.CNSIZSOL, IZSOLD.IDSERVICIO, MAX(IZSOLDT.CNSMOV) CNSMOV, SUM(IZSOLDT.CANTIDADSOL) CANTIDAD
               FROM IZSOLD INNER JOIN IZSOLDT ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD AND IZSOLD.IDARTICULO=IZSOLDT.IDARTICULO
               WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
               GROUP BY IZSOLD.CNSIZSOL, IZSOLD.CNSHBALI, IZSOLD.IDSERVICIO
            )IZSOLD ON CXPSI.CNSMOV=IZSOLD.CNSIZSOL AND CXPSI.IDSERVICIO=IZSOLD.IDSERVICIO
	      WHERE CXPSI.NOPROGRAMACION=@NOPROGRAMACION
	      AND COALESCE(PEDIDOINV,0)=1
          AND CXPSI.CNSMOV=@CNSIZSOL  
      RETURN
   END
   IF (SELECT ESTADO FROM IMOV WHERE CNSMOV=@CNSMOV )<>1
   BEGIN
       PRINT 'MOVIMIENTO DE INVENTARIO NO CONFIRMADO'
       RETURN
   END

   IF @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN ('OMEDICA','24HORAS')
   BEGIN
      SET @COBRAMEZCLA=0

      IF EXISTS (SELECT 1 FROM IMOVH 
            INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL AND IMOVH.CNSMOV=IZSOLDT.CNSMOV
            INNER JOIN IZSOLD  ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
            INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
         WHERE IMOVH.CNSMOV=@CNSMOV AND IZSOLDT.CNSMOV=@CNSMOV AND IZSOLD.CNSIZSOL=@CNSIZSOL AND COALESCE(IMOVH.NOPRESTACION,'')='' 
            AND (1=(CASE WHEN @IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA THEN 1 ELSE 0 END) 
              OR 1=(CASE WHEN @IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP THEN 1 ELSE 0 END))
      )
         SET @COBRAMEZCLA=1

      IF @COBRAMEZCLA=0
         RETURN
   END

   IF @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN ('SENFER')
   BEGIN
      SET @COBRAMEZCLA=0

      IF EXISTS (SELECT 1 FROM IMOVH  
            INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL AND IMOVH.CNSMOV=IZSOLDT.CNSMOV
            INNER JOIN IZSOLD  ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
            INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
         WHERE IMOVH.CNSMOV=@CNSMOV AND IZSOLDT.CNSMOV=@CNSMOV AND IZSOLD.CNSIZSOL=@CNSIZSOL 
            AND COALESCE(IMOVH.NOPRESTACION,'')='' AND ISNULL(SER.MEDICAMENTOS,0)=0 
      )
         SET @COBRAMEZCLA=1

      IF @COBRAMEZCLA=0
         RETURN
   END

   PRINT 'CAPTURO LOS DATOS'
   IF DBO.FNK_VALORVARIABLE('FECHAMOVSOL')='SI' 
      SELECT @FECHA=FECHAMOV FROM IMOV WHERE CNSMOV=@CNSMOV
   ELSE 
      SELECT @FECHA=FECHACONF FROM IMOV WHERE CNSMOV=@CNSMOV

   IF @FECHA IS NULL
      SET @FECHA=@HOY

   SELECT @SYS_COMPUTERNAME=HOST_NAME(),@COMPANIA='01',  @DXPPAL = DXINGRESO, @IDTERCERO = IDTERCERO, @IDPLAN = IDPLAN 
   FROM HADM 
   WHERE NOADMISION = @NOADMISION 

   SELECT @IDAREA=HHAB.IDAREA, @CCOSTO=HHAB.CCOSTO FROM  HHAB  WHERE HHAB.SECTOR = @SECTOR AND CLASE = 'Sector'
   IF COALESCE(@CCOSTO,'')=''
      SELECT @IDAREA=IDAREA,@CCOSTO=CCOSTO  FROM IMOV WHERE CNSMOV=@CNSMOV

   IF COALESCE(@CCOSTO,'')=''
      SELECT @IDAREA=HTAD.IDAREA, @CCOSTO=HTAD.CCOSTO
      FROM HADM INNER JOIN HTAD ON HTAD.TIPOADM=HADM.TIPOADM
      WHERE NOADMISION=@NOADMISION

   SELECT @IDAREAH=IDAREAH FROM AFU WHERE IDAREA=@IDAREA
   SELECT @ALTOCOSTO= COALESCE(GALTOCOSTO_QX,'No') FROM CEN WHERE CCOSTO=@CCOSTO  

   PRINT '@IDTERCERO == '+@IDTERCERO
   PRINT '@IDPLAN == '+@IDPLAN
   PRINT '@CNSIZSOL =='+@CNSIZSOL

   DECLARE HPRE_CUR CURSOR FOR 
   SELECT DISTINCT SER.PREFIJO 
   FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                  AND IMOVH.CNSMOV=IZSOLDT.CNSMOV
               INNER JOIN IZSOLD  ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
               INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
   WHERE IMOVH.CNSMOV=@CNSMOV 
   AND IZSOLDT.CNSMOV=@CNSMOV 
   AND IZSOLD.CNSIZSOL=@CNSIZSOL
   AND COALESCE(IMOVH.NOPRESTACION,'')=''
   AND 1=(CASE @IX WHEN 'PERU' THEN (CASE ISNULL(SER.SPD,0) WHEN 1 THEN 0 ELSE 1 END) ELSE 1 END)
   AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
   AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
   
   --AND SER.ESTADO='Activo'
   --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END 
   --            AND CPPAF.IDPLAN=@IDPLAN)

   OPEN HPRE_CUR    
   FETCH NEXT FROM HPRE_CUR    
   INTO @PREFIJO
   WHILE @@FETCH_STATUS = 0    
   BEGIN    
      PRINT 'EMPIEZA EL CURSOR.... PREFIJO ::::     ::::: '+COALESCE(@PREFIJO,'')  
      PRINT 'REVISO SI YA EXISTE LA PRESTACION DEL DIA........'

      IF @IX='PERU'
      BEGIN
         IF @CLASE='HTX'
            SELECT TOP 1 @IDPLAN=HTX.IDPLAN, @CCOSTO=HTX.CCOSTO,
               @IDAREA=ISNULL((CASE ISNULL(PRE.TAREA,'') 
                  WHEN 'Prefijo' THEN ISNULL(PRE.IDAREA,'')
                  WHEN 'Personal' THEN (
                     SELECT MAX(TGEN.DATO1) FROM USUSU 
                        INNER JOIN MED ON USUSU.IDMEDICO=MED.IDMEDICO 
                        INNER JOIN TGEN ON TGEN.TABLA='MED' AND TGEN.CAMPO='TIPO_USUARIO' AND TGEN.CODIGO=MED.TIPO_USUARIO
                     WHERE USUSU.USUARIO=@USUARIO)
                  ELSE NULL END),@IDAREA)
            FROM HTX 
               INNER JOIN SER ON SER.IDSERVICIO=HTX.IDSERVICIO
               INNER JOIN PRE ON PRE.PREFIJO=SER.PREFIJO
               LEFT JOIN IMOVH ON IMOVH.CNSMOV=@CNSMOV AND IMOVH.IDSERVICIO=SER.IDSERVICIO
            WHERE HTX.CNSMOV=@CNSMOV AND ISNULL(SER.SPD,0)=0 AND SER.PREFIJO=@PREFIJO
         ELSE
            SELECT @CCOSTO=CEN.CCOSTO, @IDAREA=CEN.IDAREA
            FROM PLN INNER JOIN CEN ON CEN.CCOSTO=PLN.CCOSTO
            WHERE PLN.IDPLAN=@IDPLAN

         SELECT @IDAREA=ISNULL((CASE ISNULL(PRE.TAREA,'') 
            WHEN 'Prefijo' THEN ISNULL(PRE.IDAREA,'')
            WHEN 'Personal' THEN (
               SELECT MAX(TGEN.DATO1) FROM USUSU 
                  INNER JOIN MED ON USUSU.IDMEDICO=MED.IDMEDICO 
                  INNER JOIN TGEN ON TGEN.TABLA='MED' AND TGEN.CAMPO='TIPO_USUARIO' AND TGEN.CODIGO=MED.TIPO_USUARIO
               WHERE USUSU.USUARIO=@USUARIO)
            ELSE NULL END),@IDAREA)
         FROM PRE WHERE PREFIJO=@PREFIJO
      END


      SELECT @EXISTE=COUNT(*) FROM HPRE WHERE PREFIJO=@PREFIJO AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@FECHA) AND NOADMISION=@NOADMISION 
      AND PROCEDENCIA = 'CMEZCLAS' AND CCOSTO=@CCOSTO

      IF COALESCE(@EXISTE,0)<=0
      BEGIN 
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@HPRE', @NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         PRINT 'CONSECUTIVO='+@NVOCONSEC 
         PRINT 'INSERT.....P'
         INSERT INTO HPRE (NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREA, IDSEDE, ALTOCOSTO, 
                     NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALOREXEDENTE, IMPRESO, AUTORIZADOPOR,
                     NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, USUARIO, CERRADA, 
                     VALORPCOMP, CIRUGIA, PCUBRIMIENTO, CLASEORDEN, CONSECUTIVO, ESDEINV,
                     PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,
                     AMBITO, PERSONAL_AT, DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX,
                     ESCONSULTA, IDAREAH, NIVELATENCION, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA,
                     IDTERCEROCA,PROCEDENCIA,CONSECUTIVOHCA )
         SELECT @NVOCONSEC, @NOADMISION, @FECHA, @IDPLAN, @IDAREA, @SEDE, @ALTOCOSTO,
                  0, 0,0,0,0, NULL, NULL, NULL, 0, @USUARIO,
                  0, 0, 'No', 100, NULL, NODOCUMENTO, 1, 1, @CNSMOV, 0, @PREFIJO,
                  @CCOSTO, '', 2, 2, 1, @DXPPAL, NULL, NULL, NULL, 0, 
                  @IDAREAH, 1, NULL, 0, @USUARIOSOL, 'C', @IDTERCERO,'CMEZCLAS',''
         FROM IMOV WHERE CNSMOV=@CNSMOV
      END
      ELSE
      BEGIN
         SELECT @NVOCONSEC=NOPRESTACION,@IDTERCERO=IDTERCEROCA,@IDPLAN=IDPLAN,@IDAREA=IDAREA 
         FROM HPRE 
         WHERE PREFIJO=@PREFIJO 
         AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@FECHA) 
         AND NOADMISION=@NOADMISION 
         AND PROCEDENCIA='CMEZCLAS'
         AND CCOSTO=@CCOSTO
         PRINT 'YA EXISTE ESTA ES LA PRESTACION: '+@NVOCONSEC+'  @NOADMISION ::=:: '+@NOADMISION
      END
      IF @CLASE='SENFER' OR COALESCE(DBO.FNK_VALORVARIABLE('MDEVOLUCIONDOSIS'),'')='NO' OR COALESCE(DBO.FNK_VALORVARIABLE('COBRAENREGAFARMACIA'),'')='SI'
      BEGIN --SELECT TOP 1  * FROM HPRED
         PRINT 'INGRESO 1'
         IF @CLASE='SENFER' OR DBO.FNK_VALORVARIABLE('MODOCOBROMEDHBALI')<>'HBALI'
         BEGIN
            SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC
            IF COALESCE(@ITEM,0)<=0
            BEGIN 
               SELECT @ITEM=0
            END 
            PRINT '@CLASE = '+@CLASE 
            PRINT '@ITEM '  +STR(@ITEM)

            IF @IX='PERU'
            BEGIN 
               SELECT @IDAREA=ISNULL((CASE ISNULL(PRE.TAREA,'') 
                     WHEN 'Prefijo' THEN ISNULL(PRE.IDAREA,'')
                     WHEN 'Personal' THEN (
                        SELECT MAX(TGEN.DATO1) FROM USUSU 
                           INNER JOIN MED ON USUSU.IDMEDICO=MED.IDMEDICO 
                           INNER JOIN TGEN ON TGEN.TABLA='MED' AND TGEN.CAMPO='TIPO_USUARIO' AND TGEN.CODIGO=MED.TIPO_USUARIO
                        WHERE USUSU.USUARIO=@USUARIO)
                     ELSE NULL END),HTX.IDAREA)
               FROM HTX 
                  INNER JOIN SER ON SER.IDSERVICIO=HTX.IDSERVICIO
                  INNER JOIN PRE ON PRE.PREFIJO=SER.PREFIJO
                  LEFT JOIN IMOVH ON IMOVH.CNSMOV=@CNSMOV AND IMOVH.IDSERVICIO=SER.IDSERVICIO
               WHERE HTX.CNSMOV=@CNSMOV AND ISNULL(SER.SPD,0)=0 AND SER.PREFIJO=@PREFIJO

               
               INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                              VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                              COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                              VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                              TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                              CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                              INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                              CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                             IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,CNSHBALI,
                             CLASEOM,IDAREA,CCOSTO,FECHASOL)
               SELECT  @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
                       SER.IDSERVICIO,CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.NUMDOSIS ELSE SUM(IZSOLDT.CANTIDADSOL) END,
                       CASE WHEN @IX='PERU' THEN CASE WHEN COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN SUM(IMOVH.CAPACIDAD) ELSE  SUM(IMOVH.PVENTA)/COUNT(IMOVH.CNSMOV) END ELSE  0 END,
                       CASE WHEN @IX='PERU' THEN CASE WHEN COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN 0 ELSE SUM(IMOVH.CAPACIDAD *IMOVH.CANTIDAD)/COUNT(IMOVH.CNSMOV) END ELSE  0 END,
                       CASE WHEN @IX='PERU' THEN CASE WHEN COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN SUM((IMOVH.CAPACIDAD *IMOVH.CANTIDAD))  
                            ELSE SUM((IMOVH.PVENTA *IMOVH.CANTIDAD)-(IMOVH.CAPACIDAD *IMOVH.CANTIDAD))/COUNT(IMOVH.CNSMOV) END ELSE  0 END,
                       0, @IDPLAN,0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
                       'CMEZCLAS', 
                       CASE WHEN @IX='PERU' AND COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN 1 ELSE 0 END, 
                       NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                       0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                       IMOVH.IDARTICULO,IMOVH.CNSMOV,IMOVH.NOLOTE,100,'N',CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.CNSIZSOLD ELSE NULL END,
                       CASE WHEN IZSOLD.TIPOENT=2 THEN 'DOSIS' ELSE NULL END, @IDAREA, @CCOSTO, @FECHASOL
               FROM IMOVH  
                  INNER JOIN IART    ON IART.IDARTICULO=IMOVH.IDARTICULO
                  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                  INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                  INNER JOIN SER     ON SER.IDSERVICIO=(CASE ISNULL(IART.IDSERVICIO_FAC,'') WHEN '' THEN IZSOLD.IDSERVICIO ELSE IART.IDSERVICIO_FAC END)
               WHERE IMOVH.CNSMOV=@CNSMOV 
               AND IZSOLDT.CNSMOV=@CNSMOV 
               AND IZSOLD.CNSIZSOL=@CNSIZSOL
               AND SER.PREFIJO=@PREFIJO
               AND COALESCE(IMOVH.NOPRESTACION,'')=''
               AND 1=(CASE ISNULL(SER.SPD,0) WHEN 1 THEN 0 ELSE 1 END)
			   AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 	   	  CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
			   AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 	      CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
               GROUP BY SER.IDSERVICIO,IMOVH.IDARTICULO,IMOVH.CNSMOV,IMOVH.NOLOTE,SER.CODIGORIPS,IZSOLD.TIPOENT,IZSOLD.NUMDOSIS, 
                     CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.CNSIZSOLD ELSE NULL END ,COALESCE(IMOVH.ODCILINDRO,'')
            END
            ELSE
            BEGIN
               INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                              VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                              COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                              VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                              TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                              CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                              INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                              CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                             IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,CNSHBALI,CLASEOM,FECHASOL)
               SELECT  @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
                       IZSOLD.IDSERVICIO,CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.NUMDOSIS ELSE SUM(IMOVH.CANTIDAD)END,
                       CASE WHEN @IX='PERU' THEN CASE WHEN COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN SUM(IMOVH.CAPACIDAD) ELSE  SUM(IMOVH.PVENTA) END ELSE  0 END,
                       CASE WHEN @IX='PERU' THEN CASE WHEN COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN 0 ELSE SUM(IMOVH.CAPACIDAD *IMOVH.CANTIDAD) END ELSE  0 END,
                       CASE WHEN @IX='PERU' THEN CASE WHEN COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN SUM((IMOVH.CAPACIDAD *IMOVH.CANTIDAD))  
                            ELSE SUM((IMOVH.PVENTA *IMOVH.CANTIDAD)-(IMOVH.CAPACIDAD *IMOVH.CANTIDAD)) END ELSE  0 END,
                       0, @IDPLAN,0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
                       'CMEZCLAS', 
                       CASE WHEN @IX='PERU' AND COALESCE(IMOVH.ODCILINDRO,'')='Si' THEN 1 ELSE 0 END, 
                       NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                       0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                       IMOVH.IDARTICULO,IMOVH.CNSMOV,IMOVH.NOLOTE,100,'N',CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.CNSIZSOLD ELSE NULL END,
                       CASE WHEN IZSOLD.TIPOENT=2 THEN 'DOSIS' ELSE NULL END, @FECHASOL
               FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                              AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                           INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                           INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
               WHERE IMOVH.CNSMOV=@CNSMOV 
               AND IZSOLDT.CNSMOV=@CNSMOV 
               AND IZSOLD.CNSIZSOL=@CNSIZSOL
               AND SER.PREFIJO=@PREFIJO
               AND COALESCE(IMOVH.NOPRESTACION,'')=''
			   AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 	   	  CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
			   AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 	      CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
               --AND SER.ESTADO='Activo'
               --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END 
               --            AND CPPAF.IDPLAN=@IDPLAN)
               GROUP BY IZSOLD.IDSERVICIO,IMOVH.IDARTICULO,IMOVH.CNSMOV,IMOVH.NOLOTE,SER.CODIGORIPS,IZSOLD.TIPOENT,IZSOLD.NUMDOSIS, 
                     CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.CNSIZSOLD ELSE NULL END,COALESCE(IMOVH.ODCILINDRO,'') --, CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END
            END

            PRINT 'INSERT EN HPRED '

            UPDATE IMOVH SET NOPRESTACION=@NVOCONSEC
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 	   	CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 	    CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
            --AND SER.ESTADO='Activo'
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END 
            --            AND CPPAF.IDPLAN=@IDPLAN)
            PRINT 'ACTUALIZO IMOVH....'
         END
         ELSE
         BEGIN
            SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC
            IF COALESCE(@ITEM,0)<=0
            BEGIN 
               SELECT @ITEM=0
            END 
            PRINT '@CLASE = '+@CLASE 
            PRINT '@ITEM '  +STR(@ITEM)     
			   PRINT 'ENTRE POR AQUI'
            INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                           VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                           COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                           VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                           TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                           CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                           INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                           CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                          IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,CNSHBALI,CLASEOM,FECHASOL)
            SELECT  @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
                    IZSOLD.IDSERVICIO,CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.NUMDOSIS ELSE SUM(IZSOLDT.CANTIDADSOL)END,0, 0,0,0, @IDPLAN,
                    0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
                    'CMEZCLAS', 
                    CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END, 
                    NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                    IMOVH.IDARTICULO,IMOVH.CNSMOV,IMOVH.NOLOTE,100,'N',CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.CNSIZSOLD ELSE NULL END,
                    CASE WHEN IZSOLD.TIPOENT=2 THEN 'DOSIS' ELSE NULL END, @FECHASOL
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
            AND 1=(CASE @CLASE WHEN 'APOYODX' THEN 1 ELSE (CASE WHEN IZSOLD.CODOM IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('OMCODMEZCLA','OMCODNUTRICIONP')) THEN 1 ELSE 0 END) END)
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 	   	CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 	    CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
            --AND EXISTS(SELECT 1 FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END
            --           AND CPPAF.IDPLAN=@IDPLAN)
            GROUP BY IZSOLD.IDSERVICIO,IMOVH.IDARTICULO,IMOVH.CNSMOV,IMOVH.NOLOTE,SER.CODIGORIPS,IZSOLD.TIPOENT,IZSOLD.NUMDOSIS, 
                     CASE WHEN IZSOLD.TIPOENT=2 THEN IZSOLD.CNSIZSOLD ELSE NULL END, CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END

            UPDATE IMOVH SET NOPRESTACION=@NVOCONSEC
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 	   	CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 	    CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
            --AND SER.ESTADO='Activo'
            AND 1=(CASE @CLASE WHEN 'APOYODX' THEN 1 ELSE (CASE WHEN IZSOLD.CODOM IN (SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('OMCODMEZCLA','OMCODNUTRICIONP')) THEN 1 ELSE 0 END) END)
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
            --AND EXISTS (SELECT 1 FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END 
            --         AND CPPAF.IDPLAN=@IDPLAN)

         END
      END
      ELSE
      BEGIN
         SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC
         IF COALESCE(@ITEM,0)<=0
         BEGIN 
            SELECT @ITEM=0
         END 
         PRINT '@CLASE = '+@CLASE
         PRINT '@ITEM '  +STR(COALESCE(@ITEM,0))    
         IF COALESCE(DBO.FNK_VALORVARIABLE('COBRAENREGAFARMACIA'),'')<>'NO'
         BEGIN
            PRINT 'COBRAENREGAFARMACIA=SI'
            INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                           VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                           COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                           VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                           TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                           CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                           INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                           CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                          IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,FECHASOL)
            SELECT  @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
                    IZSOLD.IDSERVICIO,CASE WHEN CEILING(IZSOLD.CANTIDAD/CASE WHEN SER.MDOSIF=1 
                                                                          THEN  
                                                                              CASE 
                                                                                  WHEN COALESCE(SER.EQUICC,0)<=0 
                                                                                  THEN 1 
                                                                                  ELSE 
                                                                                     SER.EQUICC 
                                                                                  END 
                                                                          ELSE 1 
                                                                          END
                                        )>1
                                        THEN  CEILING(IZSOLD.CANTIDAD/CASE WHEN SER.MDOSIF=1 
                                                                           THEN  
                                                                              CASE WHEN COALESCE(SER.EQUICC,0)<=0 
                                                                                   THEN 1 
                                                                                   ELSE 
                                                                                      SER.EQUICC 
                                                                                   END 
                                                                           ELSE 1 
                                                                           END
                                              )*   NUMDOSIS   
                                        ELSE CASE WHEN  IZSOLD.TIPOENT=2 THEN IZSOLDT.CANTIDADSOL ELSE  IZSOLD.NUMDOSIS END 
                                        END,0, 0,0,0, @IDPLAN,
                    0, 0, NULL, NULL, SER.CODIGORIPS,0,NULL, @USUARIO, 0, 0,
                    'CMEZCLAS', 
                    CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END, 
                    NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                    IZSOLDT.IDARTICULOREAL,@CNSMOV,IZSOLDT.NOLOTE,100,'N', @FECHASOL
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
            AND IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS')
            GROUP BY IZSOLD.IDSERVICIO,IZSOLDT.IDARTICULOREAL,IZSOLDT.NOLOTE,IZSOLD.CANTIDAD,SER.MDOSIF,SER.EQUICC,IZSOLD.NUMDOSIS,SER.CODIGORIPS,IZSOLD.TIPOENT,IZSOLDT.CANTIDADSOL,
            CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END


            --RETURN
            SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC

            PRINT 'INCLUIMOS LAS ORDENES DE MEDICAMENTOS'

            INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                           VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                           COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                           VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                           TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                           CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                           INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                           CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                          IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,FECHASOL)
            SELECT  @NVOCONSEC,ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
                    IZSOLD.IDSERVICIO,CASE WHEN IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODMEZCLA') OR IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODLIQUIDOSPARE')
                                       THEN SUM(IZSOLD.CANTIDADSOL) 
                                       ELSE SUM(CEILING(IZSOLD.DURACION/IZSOLD.FRECUENCIA)*CEILING(IZSOLD.CANTIDAD/CASE WHEN COALESCE(SER.EQUICC,0)<=0 THEN 1 ELSE SER.EQUICC END))
                                       END,0, 0,0,0, @IDPLAN,
                    0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
                    'CMEZCLAS', 
                    CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END, 
                    NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                    IZSOLDT.IDARTICULOREAL,@CNSMOV,IZSOLDT.NOLOTE,100,'N', @FECHASOL
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
            AND IZSOLD.CODOM<>DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS') 
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
            GROUP BY IZSOLD.IDSERVICIO,IZSOLDT.IDARTICULOREAL,IZSOLDT.NOLOTE,SER.CODIGORIPS,IZSOLD.CODOM,
            CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END
                                  
         END
--Query2
         ELSE
         BEGIN
            PRINT 'COBRAENREGAFARMACIA=NO....'
            INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                           VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                           COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                           VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                           TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                           CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                           INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                           CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                          IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,FECHASOL)
            SELECT  @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
                    IZSOLD.IDSERVICIO,CASE WHEN CEILING(IZSOLD.CANTIDAD/CASE WHEN SER.MDOSIF=1 
                                                                          THEN  
                                                                              CASE 
                                                                                  WHEN COALESCE(SER.EQUICC,0)<=0 
                                                                                  THEN 1 
                                                                                  ELSE 
                                                                                     SER.EQUICC 
                                                                                  END 
                                                                          ELSE 1 
                                                                          END
                                        )>1
                                        THEN  CEILING(IZSOLD.CANTIDAD/CASE WHEN SER.MDOSIF=1 
                                                                           THEN  
                                                                              CASE WHEN COALESCE(SER.EQUICC,0)<=0 
                                                                                   THEN 1 
                                                                                   ELSE 
                                                                                      SER.EQUICC 
                                                                                   END 
                                                                           ELSE 1 
                                                                           END
                                              )*   NUMDOSIS   
                                        ELSE CASE WHEN  IZSOLD.TIPOENT=2 THEN IZSOLD.CANTIDADSOL ELSE  IZSOLD.NUMDOSIS END 
                                        END,0, 0,0,0, @IDPLAN,
                    0, 0, NULL, NULL, SER.CODIGORIPS,0,NULL, @USUARIO, 0, 0,
                    'CMEZCLAS', 
                    CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END, 
                    NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                    IZSOLD.IDARTICULO,@CNSMOV,NULL,100,'N',@FECHASOL
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
            AND IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS')
            AND COALESCE(IZSOLD.COBRADODY,0)=0 
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 		CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
		    AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 		CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
            GROUP BY IZSOLD.IDSERVICIO,IZSOLD.IDARTICULO,IZSOLD.CANTIDAD,SER.MDOSIF, SER.EQUICC,NUMDOSIS,IZSOLD.TIPOENT,SER.CODIGORIPS,IZSOLD.CANTIDADSOL,
            CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END

            PRINT 'MARCO IZSOLD  COMO COBRADO '
            UPDATE IZSOLD SET COBRADODY=1
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
         -- AND COALESCE(IMOVH.NOPRESTACION,'')=''
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
            AND IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS')
            AND COALESCE(IZSOLD.COBRADODY,0)=0
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 		CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
		    AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 		CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
            --RETURN
            SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC

            PRINT 'INCLUIMOS LAS ORDENES DE MEDICAMENTOS'

            INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
                           VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
                           COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
                           VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
                           TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
                           CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
                           INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
                           CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
                          IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,FECHASOL)
            SELECT  @NVOCONSEC,ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
            --JHON GOMEZ SE AGREGA LINEA AGRENADO LA ORDEN MEDICA DE NUTRICION PARA QUE LLEGUEN CORRECTAMENTE LOS CARGOS 
                    IZSOLD.IDSERVICIO,CASE WHEN IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODMEZCLA') OR IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODLIQUIDOSPARE')
					 OR  IZSOLD.CODOM=DBO.FNK_VALORVARIABLE('OMCODNUTRICIONP')
                                       THEN SUM(IZSOLD.CANTIDADSOL) 
                                       ELSE SUM(CEILING(IZSOLD.DURACION/IZSOLD.FRECUENCIA)*CEILING(IZSOLD.CANTIDAD/CASE WHEN COALESCE(SER.EQUICC,0)<=0 THEN 1 ELSE SER.EQUICC END))
                                       END,0, 0,0,0, @IDPLAN,
                    0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
                    'CMEZCLAS', 
                    CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END, 
                    NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
                    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
                    IZSOLD.IDARTICULO,@CNSMOV,NULL,100,'N',@FECHASOL
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
            AND IZSOLD.CODOM<>DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS') 
            AND COALESCE(IMOVH.NOPRESTACION,'')=''
            AND COALESCE(IZSOLD.COBRADODY,0)=0 
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 		CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
		    AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 		CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
            GROUP BY IZSOLD.IDSERVICIO,IZSOLD.IDARTICULO,IZSOLD.CANTIDADSOL,IZSOLD.DURACION,IZSOLD.FRECUENCIA,IZSOLD.CANTIDAD,SER.EQUICC,SER.CODIGORIPS,IZSOLD.CODOM,
            CASE WHEN @IX='PERU' AND IMOVH.ODCILINDRO='Si' THEN 1 ELSE 0 END
            
            PRINT 'MARCO IZSOLD  COMO COBRADO '
            UPDATE IZSOLD SET COBRADODY=1
            FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                           AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                        INNER JOIN IZSOLD  ON IZSOLDT.CNSIZSOLD=IZSOLD.CNSIZSOLD
                        INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
            WHERE IMOVH.CNSMOV=@CNSMOV 
            AND IZSOLDT.CNSMOV=@CNSMOV 
            AND IZSOLD.CNSIZSOL=@CNSIZSOL
            AND SER.PREFIJO=@PREFIJO
            --AND SER.ESTADO='Activo'
            --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
            AND IZSOLD.CODOM<>DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS') 
           -- AND COALESCE(IMOVH.NOPRESTACION,'')=''
            AND COALESCE(IZSOLD.COBRADODY,0)=0  
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 		CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
		    AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 		CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)

         END
         PRINT 'RELACIONO INVENTARIO CON HPRE'
         UPDATE IMOVH SET NOPRESTACION=@NVOCONSEC
         FROM IMOVH  INNER JOIN IZSOLDT ON IMOVH.IDARTICULO=IZSOLDT.IDARTICULOREAL
                                        AND IMOVH.CNSMOV=IZSOLDT.CNSMOV AND IMOVH.NOLOTE = IZSOLDT.NOLOTE
                     INNER JOIN IZSOLD  ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
                     INNER JOIN SER  ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
         WHERE IMOVH.CNSMOV=@CNSMOV 
         AND IZSOLDT.CNSMOV=@CNSMOV 
         AND IZSOLD.CNSIZSOL=@CNSIZSOL
         --AND SER.ESTADO='Activo'  
         AND SER.PREFIJO=@PREFIJO
         AND COALESCE(IMOVH.NOPRESTACION,'')=''
			AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('OMEDICA','24HORAS') THEN (
		 		CASE WHEN (@IENF_MEZCLA<>'SI' AND IZSOLD.CODOM=@OMCODMEZCLA) OR (@IENF_NUTP<>'SI' AND IZSOLD.CODOM=@OMCODNUTRICIONP) THEN 1 ELSE 0 END) ELSE 1 END)
		    AND 1=(CASE WHEN @MODOCOBROMEDHBALI='HBALI' AND @CLASE IN('SENFER') THEN (
		 		CASE WHEN ISNULL(SER.MEDICAMENTOS,0)=1 THEN 0 ELSE 1 END) ELSE 1 END)
         --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)

      END
      PRINT 'ACTUALIZO VALORES'

	  IF @CLASE<>'FMEX'
	  BEGIN
		EXEC SPK_VALORES_HPRED @NVOCONSEC,@IDTERCERO,@IDPLAN
	  END
      PRINT 'ACTUALIZO VALORES ADMISION'
      IF @IX='PERU'
      BEGIN
         SELECT @VT = SUM(HPRED.VALOR * HPRED.CANTIDAD), @VE = SUM(HPRED.VALOREXCEDENTE),
                @VC = SUM(HPRED.VALORCOPAGO), @VP = SUM(HPRED.VALORPCOMP)
         FROM HPRED
         WHERE HPRED.NOPRESTACION = @NVOCONSEC
     
         UPDATE HPRE SET VALORTOTAL  = @VT,VALOREXEDENTE = @VE,
                         VALORCOPAGO = @VC,VALORPCOMP    = @VP 
         WHERE HPRE.NOPRESTACION = @NVOCONSEC
      END
      ELSE
      BEGIN
         --EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION   
         EXEC SPK_RELIQUIDACOPAGOQX_HPRE @NVOCONSEC
         --REVISO SI QUEDAN PRESTACIONES CON EL VALOREXCEDENTE DIFERENTE
         EXEC SPK_VERIFICA_COPAGOQX @NOADMISION
      END
      FETCH NEXT FROM HPRE_CUR    
      INTO @PREFIJO
   END
   CLOSE HPRE_CUR
   DEALLOCATE HPRE_CUR

   PRINT 'PROCESO PARA COBRAR LOS DILUYENTES DE LOS PREPARADOS' -- MEDICAMENTOS PREPARADOS

   IF (SELECT COUNT(*) FROM IZSOLD WHERE CNSIZSOL=@CNSIZSOL AND TIPOENT=2)>0
   BEGIN
      DECLARE HPRE_CUR_DY CURSOR FOR 
      SELECT DISTINCT SER.PREFIJO 
      FROM IZSOLD INNER JOIN SER ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
      WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
      AND   IZSOLD.TIPOM='DY'
      AND   IZSOLD.TIPOENT=2
      AND   IZSOLD.ESTADO=0
      --AND SER.ESTADO='Activo'  
      --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
      AND   COALESCE(IZSOLD.COBRADODY,0)=0
      OPEN HPRE_CUR_DY    
      FETCH NEXT FROM HPRE_CUR_DY    
      INTO @PREFIJO
      WHILE @@FETCH_STATUS = 0    
      BEGIN    
         PRINT 'EMPIEZA EL CURSOR.... PREFIJO ::::     ::::: '+COALESCE(@PREFIJO,'')  
         PRINT 'REVISO SI YA EXISTE LA PRESTACION DEL DIA........'
         SELECT @EXISTE=COUNT(*) FROM HPRE WHERE PREFIJO=@PREFIJO AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@FECHA) AND NOADMISION=@NOADMISION AND PROCEDENCIA='CMEZCLAS'
         IF COALESCE(@EXISTE,0)<=0
         BEGIN 
            IF DBO.FNK_VALORVARIABLE('FECHAMOVSOL')='SI' 
                SELECT @FECHA=FECHAMOV FROM IMOV WHERE CNSMOV=@CNSMOV
            ELSE 
                SELECT @FECHA=FECHACONF FROM IMOV WHERE CNSMOV=@CNSMOV

            IF @FECHA IS NULL
                SET @FECHA=@HOY

            SELECT @SYS_COMPUTERNAME=HOST_NAME(),@COMPANIA='01',  @DXPPAL = DXINGRESO, @IDTERCERO = IDTERCERO, @IDPLAN = IDPLAN 
            FROM HADM 
            WHERE NOADMISION = @NOADMISION 
            SELECT @IDAREA=HHAB.IDAREA, @CCOSTO=HHAB.CCOSTO FROM  HHAB  WHERE HHAB.SECTOR = @SECTOR
            IF COALESCE(@CCOSTO,'')=''
            BEGIN 
               SELECT @IDAREA=IDAREA,@CCOSTO=CCOSTO  FROM IMOV WHERE CNSMOV=@CNSMOV
            END  
            SELECT @IDAREAH=IDAREAH FROM AFU WHERE IDAREA=@IDAREA
            SELECT @ALTOCOSTO= COALESCE(GALTOCOSTO_QX,'No') FROM CEN WHERE CCOSTO=@CCOSTO  
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@HPRE', @NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
            PRINT 'CONSECUTIVO='+@NVOCONSEC 
            PRINT 'INSERT.....P'
            INSERT INTO HPRE (NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREA, IDSEDE, ALTOCOSTO, 
                        NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALOREXEDENTE, IMPRESO, AUTORIZADOPOR,
                        NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, USUARIO, CERRADA, 
                        VALORPCOMP, CIRUGIA, PCUBRIMIENTO, CLASEORDEN, CONSECUTIVO, ESDEINV,
                        PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,
                        AMBITO, PERSONAL_AT, DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX,
                        ESCONSULTA, IDAREAH, NIVELATENCION, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA,
                        IDTERCEROCA,PROCEDENCIA,CONSECUTIVOHCA )
            SELECT @NVOCONSEC, @NOADMISION, @FECHA, @IDPLAN, @IDAREA, @SEDE, @ALTOCOSTO,
                     0, 0,0,0,0, NULL, NULL, NULL, 0, @USUARIO,
                     0, 0, 'No', 100, NULL, NODOCUMENTO, 1, 1, @CNSMOV, 0, @PREFIJO,
                     @CCOSTO, '', 2, 2, 1, @DXPPAL, NULL, NULL, NULL, 0, 
                     @IDAREAH, 1, NULL, 0, @USUARIOSOL, 'C', @IDTERCERO,'CMEZCLAS',''
            FROM IMOV WHERE CNSMOV=@CNSMOV
         END
         ELSE
         BEGIN
            SELECT @NVOCONSEC=NOPRESTACION,@IDTERCERO=IDTERCEROCA,@IDPLAN=IDPLAN,@IDAREA=IDAREA 
            FROM HPRE 
            WHERE PREFIJO=@PREFIJO 
            AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@FECHA) 
            AND NOADMISION=@NOADMISION 
            AND PROCEDENCIA='CMEZCLAS'
            PRINT 'YA EXISTE ESTA ES LA PRESTACION: '+@NVOCONSEC+'  @NOADMISION ::=:: '+@NOADMISION
         END
	     SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC
	     IF COALESCE(@ITEM,0)<=0
	     BEGIN 
		    SELECT @ITEM=0
	     END 
	     PRINT '@CLASE = '+@CLASE 
	     PRINT '@ITEM '  +STR(@ITEM)     
	     INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
		    			   VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
			    		   COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
				    	   VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
					      TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
					      CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
					      INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
					      CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
					      IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,CNSHBALI,CLASEOM,FECHASOL)
		   SELECT @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
				    IZSOLD.IDSERVICIO, IZSOLD.NUMDOSIS,0, 0,0,0, @IDPLAN,
				    0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
				    'CMEZCLAS', 0, NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
				    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
				    IZSOLD.IDARTICULO,@CNSMOV,NULL,100,'N',
                (SELECT CNSIZSOLD  FROM IZSOLD A WHERE A.CNSIZSOL=@CNSIZSOL AND A.IDPRINCIPIO=IZSOLD.IDPRINCIPIO AND A.TIPOM='PR'),
                'PREPARADO', @FECHASOL
         FROM IZSOLD INNER JOIN SER ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
         WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
         AND   IZSOLD.TIPOM='DY'
         AND   IZSOLD.TIPOENT=2
         AND   IZSOLD.ESTADO=0
         --AND   SER.ESTADO='Activo'
         AND   SER.PREFIJO=@PREFIJO
		   --AND   EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
         AND   COALESCE(IZSOLD.COBRADODY,0)=0
		  GROUP BY IZSOLD.IDSERVICIO,IZSOLD.IDARTICULO,IZSOLD.NUMDOSIS,SER.CODIGORIPS,IZSOLD.IDPRINCIPIO


        PRINT 'ACTUALIZO ISZSOLD..........'

        UPDATE IZSOLD SET COBRADODY=1
        FROM IZSOLD INNER JOIN SER ON IZSOLD.IDSERVICIO=SER.IDSERVICIO
        WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
        AND   IZSOLD.TIPOM='DY'
        AND   IZSOLD.TIPOENT=2
        AND   IZSOLD.ESTADO=0
        --AND   SER.ESTADO='Activo'
        AND   SER.PREFIJO=@PREFIJO
		  --AND   EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
        AND   COALESCE(IZSOLD.COBRADODY,0)=0

   
        PRINT 'ACTUALIZO VALORES'
        EXEC SPK_VALORES_HPRED @NVOCONSEC,@IDTERCERO,@IDPLAN
        PRINT 'ACTUALIZO VALORES ADMISION'
         --EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION   
        EXEC SPK_RELIQUIDACOPAGOQX_HPRE @NVOCONSEC
        --REVISO SI QUEDAN PRESTACIONES CON EL VALOREXCEDENTE DIFERENTE
         EXEC SPK_VERIFICA_COPAGOQX @NOADMISION

        FETCH NEXT FROM HPRE_CUR_DY    
        INTO @PREFIJO
     END
     CLOSE HPRE_CUR_DY
     DEALLOCATE HPRE_CUR_DY	  

      /* SE COBRAN LAS JERINGAS, AGUJAS Y ADISIONALES     */
      PRINT 'ADISIONALES A LOS PREPARADOS.... '

      DECLARE HPRE_CUR_MAT CURSOR FOR 
      SELECT DISTINCT SER.PREFIJO 
      FROM IZSOLD INNER JOIN IZSOLDT ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
                  INNER JOIN ITXA    ON IZSOLDT.IDARTICULOREAL=ITXA.IDARTICULO
                  INNER JOIN SER     ON ITXA.IDARTICULOTF=SER.IDARTICULO
      WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
      AND   IZSOLD.TIPOM='PR'
      AND   IZSOLD.TIPOENT=2
      AND   IZSOLD.ESTADO=0
      --AND   SER.ESTADO='Activo'  
      --AND   EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END AND CPPAF.IDPLAN=@IDPLAN)
      AND   COALESCE(IZSOLDT.COBRADOINS,0)=0
      OPEN HPRE_CUR_MAT    
      FETCH NEXT FROM HPRE_CUR_MAT    
      INTO @PREFIJO
      WHILE @@FETCH_STATUS = 0    
      BEGIN    
         PRINT 'EMPIEZA EL CURSOR.... PREFIJO ::::     ::::: '+COALESCE(@PREFIJO,'')  
         PRINT 'REVISO SI YA EXISTE LA PRESTACION DEL DIA........'
         SELECT @EXISTE=COUNT(*) FROM HPRE WHERE PREFIJO=@PREFIJO AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@FECHA) AND NOADMISION=@NOADMISION AND PROCEDENCIA='CMEZCLAS'
         IF COALESCE(@EXISTE,0)<=0
         BEGIN 
            IF DBO.FNK_VALORVARIABLE('FECHAMOVSOL')='SI' 
                SELECT @FECHA=FECHAMOV FROM IMOV WHERE CNSMOV=@CNSMOV
            ELSE 
                SELECT @FECHA=FECHACONF FROM IMOV WHERE CNSMOV=@CNSMOV

            IF @FECHA IS NULL
                SET @FECHA=@HOY

            SELECT @SYS_COMPUTERNAME=HOST_NAME(),@COMPANIA='01',  @DXPPAL = DXINGRESO, @IDTERCERO = IDTERCERO, @IDPLAN = IDPLAN 
            FROM HADM 
            WHERE NOADMISION = @NOADMISION 
            SELECT @IDAREA=HHAB.IDAREA, @CCOSTO=HHAB.CCOSTO FROM  HHAB  WHERE HHAB.SECTOR = @SECTOR
            IF COALESCE(@CCOSTO,'')=''
            BEGIN 
               SELECT @IDAREA=IDAREA,@CCOSTO=CCOSTO  FROM IMOV WHERE CNSMOV=@CNSMOV
            END  
            SELECT @IDAREAH=IDAREAH FROM AFU WHERE IDAREA=@IDAREA
            SELECT @ALTOCOSTO= COALESCE(GALTOCOSTO_QX,'No') FROM CEN WHERE CCOSTO=@CCOSTO  
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@HPRE', @NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
            PRINT 'CONSECUTIVO='+@NVOCONSEC 
            PRINT 'INSERT.....P'
            INSERT INTO HPRE (NOPRESTACION, NOADMISION, FECHA, IDPLAN, IDAREA, IDSEDE, ALTOCOSTO, 
                        NO_ITEMES, VALORTOTAL, VALORCOPAGO, VALOREXEDENTE, IMPRESO, AUTORIZADOPOR,
                        NUMAUTORIZA, FECHAAUTORIZA, AUTORIZADO, USUARIO, CERRADA, 
                        VALORPCOMP, CIRUGIA, PCUBRIMIENTO, CLASEORDEN, CONSECUTIVO, ESDEINV,
                        PEDIDOINV, CNSMOV, INDDEVOLUCION, PREFIJO, CCOSTO, SUBCCOSTO, FINALIDAD,
                        AMBITO, PERSONAL_AT, DXPPAL, DXRELACIONADO, COMPLICACION, FORMAQX,
                        ESCONSULTA, IDAREAH, NIVELATENCION, IDAREAEQUIPO, IMPRESOP, IDMEDICO, COBRARA,
                        IDTERCEROCA,PROCEDENCIA,CONSECUTIVOHCA )
            SELECT @NVOCONSEC, @NOADMISION, @FECHA, @IDPLAN, @IDAREA, @SEDE, @ALTOCOSTO,
                     0, 0,0,0,0, NULL, NULL, NULL, 0, @USUARIO,
                     0, 0, 'No', 100, NULL, NODOCUMENTO, 1, 1, @CNSMOV, 0, @PREFIJO,
                     @CCOSTO, '', 2, 2, 1, @DXPPAL, NULL, NULL, NULL, 0, 
                     @IDAREAH, 1, NULL, 0, @USUARIOSOL, 'C', @IDTERCERO,'CMEZCLAS',''
            FROM IMOV WHERE CNSMOV=@CNSMOV
         END
         ELSE
         BEGIN
            SELECT @NVOCONSEC=NOPRESTACION,@IDTERCERO=IDTERCEROCA,@IDPLAN=IDPLAN,@IDAREA=IDAREA 
            FROM HPRE 
            WHERE PREFIJO=@PREFIJO 
            AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@FECHA) 
            AND NOADMISION=@NOADMISION 
            AND PROCEDENCIA='CMEZCLAS'
            PRINT 'YA EXISTE ESTA ES LA PRESTACION: '+@NVOCONSEC+'  @NOADMISION ::=:: '+@NOADMISION
         END
	     SELECT @ITEM=MAX(COALESCE(NOITEM,0))  FROM HPRED WHERE NOPRESTACION=@NVOCONSEC
	     IF COALESCE(@ITEM,0)<=0
	     BEGIN 
		    SELECT @ITEM=0
	     END 
	     PRINT '@CLASE = '+@CLASE 
	     PRINT '@ITEM '  +STR(@ITEM)     
	     INSERT INTO HPRED(NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO,
		    			   VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, IMPRESO, AUTORIZADO, 
			    		   COMENTARIOS, IDPROVEEDOR, IDCONCEPTORIPS, 
				    	   VALORPCOMP, IDCIRUGIA, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT,
					      TIPOSERCIRUGIA, FACTURADA, N_FACTURA ,VLRAPLICADO1, VLRAPLICADO2, 
					      CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION,
					      INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, ITEMCIRUGIA, PCOSTO,
					      CXP, FECHA, VIA, PEDIDOINV, CONSECUTIVOCX, COBRARA,
					      IDTERCEROCA,IDARTICULO,CNSMOV,NOLOTE,PCUBRIMIENTO,TIPODTO,CNSHBALI,CLASEOM,FECHASOL)
		   SELECT @NVOCONSEC, ROW_NUMBER() OVER(ORDER  BY @NVOCONSEC  ASC)+COALESCE(@ITEM,0),
				    SER.IDSERVICIO, IZSOLD.NUMDOSIS*ITXA.CANTIDADTF ,0, 0,0,0, @IDPLAN,
				    0, 0, NULL, NULL, SER.CODIGORIPS, 0, NULL, @USUARIO, 0, 0,
				    'CMEZCLAS', 0, NULL, 0, 0, 1, 0, NULL, 0, 0, NULL, 0, 1, 0,
				    0, @HOY, 'NA', 0,@NOADMISION, 'C', @IDTERCERO,
				    IZSOLDT.IDARTICULO,@CNSMOV,NULL,100,'N',IZSOLD.CNSIZSOLD,'PREPARADO',@FECHASOL
         FROM IZSOLD INNER JOIN IZSOLDT ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
                     INNER JOIN ITXA    ON IZSOLDT.IDARTICULOREAL=ITXA.IDARTICULO
                     INNER JOIN SER     ON ITXA.IDARTICULOTF=SER.IDARTICULO
         WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
         AND   IZSOLD.TIPOM='PR'
         AND   IZSOLD.TIPOENT=2
         AND   IZSOLD.ESTADO=0
         --AND   SER.ESTADO='Activo'
         AND   SER.PREFIJO=@PREFIJO 
         AND   COALESCE(IZSOLDT.COBRADOINS,0)=0
         --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END 
         --            AND CPPAF.IDPLAN=@IDPLAN)

        PRINT 'ACUTALIZO IZSOLDT INSUMOS ADICIONALES'
        UPDATE IZSOLDT SET COBRADOINS=1
        FROM IZSOLD INNER JOIN IZSOLDT ON IZSOLD.CNSIZSOLD=IZSOLDT.CNSIZSOLD
                    INNER JOIN ITXA    ON IZSOLDT.IDARTICULOREAL=ITXA.IDARTICULO
                    INNER JOIN SER     ON ITXA.IDARTICULOTF=SER.IDARTICULO
        WHERE IZSOLD.CNSIZSOL=@CNSIZSOL
        AND   IZSOLD.TIPOM='PR'
        AND   IZSOLD.TIPOENT=2
        AND   IZSOLD.ESTADO=0
        --AND   SER.ESTADO='Activo'
        AND   SER.PREFIJO=@PREFIJO 
        AND   COALESCE(IZSOLDT.COBRADOINS,0)=0
        --AND EXISTS(SELECT * FROM CPPAF WHERE SER.IDSERVICIO=CPPAF.IDSERVICIO AND COALESCE(CPPAF.IDTERCEROCA,'')=CASE WHEN CPPAF.COBRARA='O' THEN COALESCE(CPPAF.IDTERCEROCA,'') ELSE @IDTERCERO END 
        --          AND CPPAF.IDPLAN=@IDPLAN)

         PRINT 'ACTUALIZO VALORES'
         EXEC SPK_VALORES_HPRED @NVOCONSEC,@IDTERCERO,@IDPLAN
         PRINT 'ACTUALIZO VALORES ADMISION'
         --EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION   
         EXEC SPK_RELIQUIDACOPAGOQX_HPRE @NVOCONSEC
         --REVISO SI QUEDAN PRESTACIONES CON EL VALOREXCEDENTE DIFERENTE
         EXEC SPK_VERIFICA_COPAGOQX @NOADMISION


         FETCH NEXT FROM HPRE_CUR_MAT    
         INTO @PREFIJO
      END
      CLOSE HPRE_CUR_MAT
      DEALLOCATE HPRE_CUR_MAT	           
   END

   
   PRINT'REVISO AUDITORIA DE MEDICAMENTOS.....'
   SELECT @EXISTE=COUNT(*) FROM CTRAUD WHERE NOADMISION=@NOADMISION AND DBO.FNK_FECHA(FECHA)=DBO.FNK_FECHA(@HOY)
   IF COALESCE(@EXISTE,0)<=0
   BEGIN 
      PRINT 'INSERTO EN AUDITORIA....'
      INSERT INTO CTRAUD(NOADMISION,FECHA,HABCAMA,CODOM,ESTADO,USUARIOAUD)
      SELECT @NOADMISION,DBO.FNK_FECHA_SIN_HORA(@HOY),@SECTOR,'01','Pediente',NULL
   END

   PRINT 'ACTUALIZO VALORES'--SE AGREGA VALIDACIONES, PARA AGREGAR DELIVERY
	IF @IX = 'PERU'
	BEGIN
		  IF @IX='PERU' AND EXISTS (SELECT * FROM PPT WHERE  IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN AND MSERADICIONALES = 1) 
						AND EXISTS (SELECT * FROM PPTADI WHERE  IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN AND DIRECTO = 1 AND MODULO = 'FARMACIA'  )
		  BEGIN
			 --Inserto DELIVERY
			 SELECT @ITEM=MAX(NOITEM) FROM HPRED WHERE NOPRESTACION=@NVOCONSEC
			 SELECT @IDSERVICIO = (SELECT TOP 1 IDSERVICIOCOBRO FROM PPTADI WHERE  IDTERCERO = @IDTERCERO AND IDPLAN = @IDPLAN  AND DIRECTO = 1 AND MODULO = 'FARMACIA' )
			  SELECT @VT =ROUND(VLRSERVICIO,2) FROM SERTOT1
			  WHERE IDPLAN=@IDPLAN
			  AND IDTERCERO=@IDTERCERO
			  AND IDSERVICIO=@IDSERVICIO
			  AND FECHAFIN>GETDATE()
			  AND FECHAINI<=GETDATE()
			  AND FECHAFINFD>GETDATE()
			  AND FECHAINIFD<=GETDATE()

			 INSERT INTO HPRED (
				 NOPRESTACION, NOITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALOREXCEDENTE, IDPLAN, IMPRESO, AUTORIZADO, 
				 IDCONCEPTORIPS, VALORPCOMP, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, TIPOSERCIRUGIA, FACTURADA, N_FACTURA, 
				 VLRAPLICADO1, VLRAPLICADO2, CANTIDADORIGINAL, CANTIDADDEVUELTA, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO, 
				 CXP, FECHA, VIA, IDAREAH, IDAREA, NIVELATENCION, PEDIDOINV, NOLOTE, COBRARA, IDTERCEROCA, 
				 PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO, CCOSTO, ENLAB, CNSMOV, ANULADO, FECHASOL)
			 SELECT 
				 NOPRESTACION, NOITEM+1, @IDSERVICIO, CANTIDAD=1, @VT, 0, @VT, IDPLAN, IMPRESO, AUTORIZADO, 
				 IDCONCEPTORIPS, VALORPCOMP, USUARIO, UTISOAT, VLRFALTAAPLICARSOAT, CONSECUTIVOCX, ITEMCIRUGIA, TIPOSERCIRUGIA, FACTURADA=0, N_FACTURA=NULL, 
				 VLRAPLICADO1, VLRAPLICADO2, 0, 0, CNSIDEV, INDDEVOLUCION, INDDEVAPLICADA, USUARIODEV, NOCOBRABLE, PCOSTO=0, 
				 CXP, FECHA, VIA, IDAREAH, IDAREA, NIVELATENCION, PEDIDOINV=0, NOLOTE=NULL, COBRARA, IDTERCEROCA, 
				 PCUBRIMIENTO, TIPODTO, DESCUENTO, NORDEN, VALORTOTALCOSTO=0, CCOSTO=0, ENLAB, CNSMOV, ANULADO, FECHASOL
			 FROM HPRED WHERE NOPRESTACION=@NVOCONSEC AND NOITEM=@ITEM

			 SELECT @VT = SUM(HPRED.VALOR * HPRED.CANTIDAD), @VE = SUM(HPRED.VALOREXCEDENTE),
					@VC = SUM(HPRED.VALORCOPAGO), @VP = SUM(HPRED.VALORPCOMP)
			 FROM HPRED
			 WHERE HPRED.NOPRESTACION = @NVOCONSEC
     
			 SET @ITEM+=1
     		 EXEC SPK_COPAGOQX @NOADMISION, @NVOCONSEC, @ITEM


			 UPDATE HPRE SET VALORTOTAL  = @VT,VALOREXEDENTE = @VE,
							 VALORCOPAGO = @VC,VALORPCOMP    = @VP 
			 WHERE HPRE.NOPRESTACION = @NVOCONSEC
		  END
      END
      ELSE
      BEGIN
         EXEC SPK_VALORES_HPRED @NVOCONSEC,@IDTERCERO,@IDPLAN
         PRINT 'ACTUALIZO VALORES ADMISION'
         --EXEC SPK_RELIQUIDACOPAGOQX @NOADMISION   
         EXEC SPK_RELIQUIDACOPAGOQX_HPRE @NVOCONSEC
         --REVISO SI QUEDAN PRESTACIONES CON EL VALOREXCEDENTE DIFERENTE
         EXEC SPK_VERIFICA_COPAGOQX @NOADMISION
   END

END



