CREATE OR ALTER PROCEDURE [dbo].SPK_CALCULA_REFTE_NOMI    
@CNSPAGO VARCHAR(20),
@NUMDOC  VARCHAR(20),
@PROCEDENCIA VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE 
@CNSLIQRET             VARCHAR(20), 
@FECHA                 DATETIME   , 
@IDTERCERO             VARCHAR(20) , 
@NOREFERENCIA          VARCHAR(20) , 
@DEVENGOS              DECIMAL(14,0) , 
@DEDUCCION             DECIMAL(14,0) , 
@DEDUCCIONEXT          DECIMAL(14,0),
@RENTAEXEP             DECIMAL(14,0) , 
@BASERET               DECIMAL(14,0) , 
@VLRUVT                DECIMAL(14,0) , 
@UVTLIQ                DECIMAL(7,0) , 
@VLR_REFTE             DECIMAL(14,0),
@CODNOMI               VARCHAR(20),
@ENPAGO                BIT,
@NUVTS                 DECIMAL(14,4),
@UVTMIN                SMALLINT,
@UVTMAX                SMALLINT,
@UVTADI                SMALLINT,
@TMARGIN               DECIMAL(7,2),
@COMPANIA              VARCHAR(2),
@IDSEDE                VARCHAR(6),
@TERCEROID             VARCHAR(20)
BEGIN
   SELECT @TERCEROID=TERCEROID  FROM NEMP WHERE NUMDOC=@NUMDOC
   IF NOT EXISTS(SELECT * FROM RETTER WHERE IDTERCERO=@TERCEROID)
   BEGIN
      PRINT 'No esta Configurado el tercero '
      RETURN
   END
   IF @PROCEDENCIA='Nomina'
   BEGIN
      SELECT @CODNOMI=DBO.FNK_VALORVARIABLE('IDCONCEPTO_RETEFTE')
      IF NOT EXISTS(SELECT * FROM NCON WHERE CODCONCEPTO=@CODNOMI AND TIPO='Egreso')
      BEGIN
         PRINT 'Concepto de Retencion no configuradado'
      END
      IF EXISTS(SELECT * FROM NEMPFD WHERE NUMDOC=@NUMDOC AND CNSPAGO=@CNSPAGO AND CODCONCEPTO=@CODNOMI )
      BEGIN
         SELECT @ENPAGO=1
      END
      ELSE
      BEGIN
         PRINT 'Concepto no configurado en la nomina, me devuelvo'
         RETURN
      END
      SELECT @DEVENGOS=COALESCE(SUM(NEMPFD.VALOR),0)
      FROM NEMPFD INNER JOIN NEMP ON NEMPFD.NUMDOC=NEMP.NUMDOC
                  INNER JOIN RETTER ON NEMP.TERCEROID=RETTER.IDTERCERO AND NEMPFD.CODCONCEPTO=RETTER.CODRETI
      WHERE CNSPAGO=@CNSPAGO
      AND NEMP.NUMDOC=@NUMDOC
      AND RETTER.ESNOMINA=1
      AND RETTER.ESTADO='Activo'
      AND RETTER.CLASE='Suma'
      AND NEMPFD.CODCONCEPTO<>@CODNOMI



      SELECT @DEDUCCION=COALESCE(SUM(NEMPFD.VALOR),0)
      FROM NEMPFD INNER JOIN NEMP ON NEMPFD.NUMDOC=NEMP.NUMDOC
                  INNER JOIN RETTER ON NEMP.TERCEROID=RETTER.IDTERCERO AND NEMPFD.CODCONCEPTO=RETTER.CODRETI
      WHERE CNSPAGO=@CNSPAGO
      AND NEMP.NUMDOC=@NUMDOC
      AND RETTER.ESNOMINA=1
      AND RETTER.ESTADO='Activo'
      AND RETTER.CLASE='Resta'
      AND NEMPFD.CODCONCEPTO<>@CODNOMI

      SELECT @DEDUCCIONEXT=COALESCE(SUM(VALOR),0)
      FROM RETTER
      WHERE IDTERCERO=@TERCEROID
      AND ESNOMINA=0
      AND CLASE='Resta'
      AND ESTADO='Activo'

      SELECT @VLRUVT=CONVERT(DECIMAL(14,2),CASE WHEN ISNUMERIC(DBO.FNK_VALORVARIABLE('VALOR_UVT_RETEFTE'))=1 THEN DBO.FNK_VALORVARIABLE('VALOR_UVT_RETEFTE') ELSE 0 END)
      IF @VLRUVT <=0
      BEGIN
         PRINT 'Varible con el valor del la UVT no configurada: VALOR_UVT_RETEFTE '
         RETURN
      END
      SELECT @RENTAEXEP=((@DEVENGOS-(@DEDUCCION+@DEDUCCIONEXT))*0.25)
   
      --PENDIENTE VALIDAR EL LIMITE

      SELECT @BASERET=@DEVENGOS-(@RENTAEXEP+@DEDUCCION+@DEDUCCIONEXT)

      PRINT '@BASERET '+STR(@BASERET)
      PRINT '@VLRUVT '+STR(@VLRUVT)
   
      SELECT @NUVTS=(@BASERET/@VLRUVT)

      PRINT '@NUVTS ='+STR(@NUVTS)
      --BUSCO EN LA TABLA
      SELECT @UVTMIN=UVTMIN,@UVTMAX=UVTMAX,@UVTADI=UVTADI,@TMARGIN=TARMARG FROM RETUVT
      WHERE UVTMIN<=@NUVTS AND UVTMAX>@NUVTS
      AND ESTADO='Activo'

      IF @TMARGIN=0
      BEGIN
         SELECT @VLR_REFTE=0
      END
      ELSE
      BEGIN
        PRINT 'VOY A CALCULAR EL VALOR SEGUN UVT'
         SELECT @VLR_REFTE=ROUND((((((@NUVTS-@UVTMIN))*(@TMARGIN/100))*@VLRUVT)+(@UVTADI*@VLRUVT)),-3)
        -- SELECT @VLR_REFTE=(@NUVTS-@UVTMIN)
        PRINT '@VLR_REFTE='+STR(@VLR_REFTE)
      END

      -- CREAMOS LA LIQUIDACION 

      SELECT @COMPANIA='01',@IDSEDE=DBO.FNK_VALORVARIABLE('IDSEDEPRINCIPAL')
      SELECT @FECHA=FECHAFIN FROM NPER WHERE CNSPAGO=@CNSPAGO
      IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@IDSEDE)
      BEGIN
         SELECT TOP 1 @IDSEDE=IDSEDE FROM SED
      END
      IF EXISTS(SELECT * FROM RETEL WHERE IDTERCERO=@TERCEROID AND NOREFERENCIA=@CNSPAGO)
      BEGIN
         SELECT @CNSLIQRET=CNSLIQRET FROM RETEL WHERE IDTERCERO=@TERCEROID AND NOREFERENCIA=@CNSPAGO
         PRINT 'BORRAMOS'
         DELETE RETELD WHERE CNSLIQRET=@CNSLIQRET
         DELETE RETEL WHERE CNSLIQRET=@CNSLIQRET
      END
      ELSE
      BEGIN 
	      PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
         SELECT @CNSLIQRET=''
	      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RETEL', @CNSLIQRET OUTPUT  
	      SELECT @CNSLIQRET = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSLIQRET))+LTRIM(RTRIM(@CNSLIQRET)),SPACE(1),0)
	      PRINT '@CNSFTR='+COALESCE(@CNSLIQRET,'')
      END
      INSERT INTO RETEL(CNSLIQRET, FECHA, IDTERCERO, NOREFERENCIA, PROCEDENCIA, DEVENGOS, DEDUCCION, RENTAEXEP, BASERET, VLRUVT, UVTLIQ, VLR_REFTE)
      SELECT @CNSLIQRET, @FECHA, @TERCEROID, @CNSPAGO, 'Nomina', @DEVENGOS, @DEDUCCION, @RENTAEXEP, @BASERET, @VLRUVT, @NUVTS, @VLR_REFTE

      INSERT INTO RETELD(CNSLIQRET, CODIGO, CLASE, OBSERVACION, VLR_ITEM)
      SELECT @CNSLIQRET,NEMPFD.CODCONCEPTO,RETTER.CLASE,RETTER.DESCRIPCION,SUM(NEMPFD.VALOR)
      FROM NEMPFD INNER JOIN NEMP ON NEMPFD.NUMDOC=NEMP.NUMDOC
                  INNER JOIN RETTER ON NEMP.TERCEROID=RETTER.IDTERCERO AND NEMPFD.CODCONCEPTO=RETTER.CODRETI
      WHERE CNSPAGO=@CNSPAGO
      AND NEMP.NUMDOC=@NUMDOC
      AND RETTER.ESNOMINA=1
      AND RETTER.ESTADO='Activo'
      AND RETTER.CLASE='Suma'
      AND NEMPFD.CODCONCEPTO<>@CODNOMI
      GROUP BY NEMPFD.CODCONCEPTO,RETTER.CLASE,RETTER.DESCRIPCION
      UNION ALL
      SELECT @CNSLIQRET,NEMPFD.CODCONCEPTO,RETTER.CLASE,RETTER.DESCRIPCION,SUM(NEMPFD.VALOR)
      FROM NEMPFD INNER JOIN NEMP ON NEMPFD.NUMDOC=NEMP.NUMDOC
                  INNER JOIN RETTER ON NEMP.TERCEROID=RETTER.IDTERCERO AND NEMPFD.CODCONCEPTO=RETTER.CODRETI
      WHERE NEMPFD.CNSPAGO=@CNSPAGO
      AND NEMPFD.NUMDOC=@NUMDOC
      AND RETTER.ESNOMINA=1
      AND RETTER.ESTADO='Activo'
      AND RETTER.CLASE='Resta'
      AND NEMPFD.CODCONCEPTO<>@CODNOMI
      GROUP BY NEMPFD.CODCONCEPTO,RETTER.CLASE,RETTER.DESCRIPCION
      UNION ALL
      SELECT @CNSLIQRET,RETTER.CODRETI,RETTER.CLASE,RETTER.DESCRIPCION,RETTER.VALOR
      FROM RETTER
      WHERE IDTERCERO=@TERCEROID
      AND ESNOMINA=0
      AND CLASE='Resta'
      AND ESTADO='Activo'

      PRINT 'ACTUALIZO NOMINA'
      IF @ENPAGO=1
      BEGIN
         IF COALESCE(@VLR_REFTE,0)>0
         BEGIN
            UPDATE NEMPFD SET VALOR=@VLR_REFTE,CNSLIQRET=@CNSLIQRET
            WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND CODCONCEPTO=@CODNOMI

         END
         ELSE
         BEGIN
            PRINT 'LO BORRO'
            DELETE NEMPFD   WHERE CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC AND CODCONCEPTO=@CODNOMI         
         END
      END
   END
END


