CREATE OR ALTER PROCEDURE DBO.SPQ_FGLO_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@CNSGLO VARCHAR(20)                ,@CNSFCGLO VARCHAR(20)           ,@VALOR DECIMAL(14,2)
      ,@PROCESO VARCHAR(20)               ,@TIPO  VARCHAR(20)              ,@TIPORESPUESTA  VARCHAR(20)
      ,@RADICADO  VARCHAR(20)             ,@IDCONCEPTO  VARCHAR(20)        ,@VLRACEPTADO  DECIMAL(14,2)
      ,@OBSERVACION  VARCHAR(MAX)         ,@FECHARESP  DATETIME            ,@USURESPONRTA  VARCHAR(20)
      ,@OBSERVACIONRTA  VARCHAR(MAX)      ,@CODRPTA  VARCHAR(20)           ,@RESPUESTA  VARCHAR(MAX)
      ,@CONCEPTO  VARCHAR(20)             ,@DESCRIPCION  VARCHAR(512)       ,@VLRGLOSA  VARCHAR(20)
      ,@CODGLOSA  VARCHAR(20)             ,@CANTIDAD  VARCHAR(20)          ,@VR_UNITARIO  VARCHAR(20)
      ,@ITEM  INT                         ,@IDSERVICIO  VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='TRAE_MOTIGLO'     
   BEGIN         
      SELECT @CNSGLO=CNSGLO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSGLO  VARCHAR(20)   '$.CNSGLO' 
      )
      SELECT 'OK'OK
      SELECT FGLOCG.CNSFCGLO,FCGLO.DESCRIPCION,FGLOCG.VALOR 
      FROM FGLOCG INNER JOIN FCGLO ON FGLOCG.CNSFCGLO=FCGLO.CNSFCGLO
      WHERE FGLOCG.CNSGLO=@CNSGLO

      SELECT  ITEM,TIPO,CODGLOSA,CODRPTA,VLRGLOSA,VLRACEPTADO,VLRRECUPERAR,
              IDSERVICIO,CONCEPTO,DESCRIPCION,OBSERVACION,RESPUESTA,CANTIDAD,
              VR_UNITARIO
      FROM FGLOD 
      WHERE CNSGLO=@CNSGLO

      RETURN
   END  
   IF @METODO='CRUD_FGLOCG'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @PROCESO=PROCESO, @CNSGLO =CNSGLO,@CNSFCGLO=CNSFCGLO,@VALOR=VALOR
      FROM   OPENJSON (@DATOS)
      WITH   (  
      PROCESO  VARCHAR(20)   '$.PROCESO',
      CNSGLO  VARCHAR(20)   '$.CNSGLO',
      CNSFCGLO  VARCHAR(20)   '$.CNSFCGLO',
      VALOR  DECIMAL(14,2)   '$.VALOR'
      )   
      IF NOT EXISTS(SELECT * FROM  FGLO WHERE CNSGLO=@CNSGLO AND CERRADA=0)
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Consecutivo de Glosa no Encontrado O ya se encuentra Cerrada, Verifique e intente de nuevo'
      END
      ELSE
      BEGIN
         IF @PROCESO='Nuevo'
         BEGIN
            IF NOT EXISTS(SELECT * FROM FGLOCG WHERE CNSGLO=@CNSGLO AND CNSFCGLO=@CNSFCGLO)
            BEGIN
               INSERT INTO FGLOCG(CNSGLO,CNSFCGLO,VALOR)
               SELECT @CNSGLO,@CNSFCGLO,@VALOR
            END
            ELSE
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'Ya Existe un Motivo de Glosa con este Código, Verifique e Intente de nuevo'
            END
         END
         IF @PROCESO='Editar'
         BEGIN
            IF EXISTS(SELECT * FROM FGLOCG WHERE CNSGLO=@CNSGLO AND CNSFCGLO=@CNSFCGLO)
            BEGIN
               UPDATE FGLOCG SET VALOR=@VALOR WHERE CNSGLO=@CNSGLO AND CNSFCGLO=@CNSFCGLO
            END
            ELSE
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'Codigo de Glosa no Fue Encontrado, Verifique e intente de nuevo'
            END
         END
         IF @PROCESO='Borrar'
         BEGIN
            IF EXISTS(SELECT * FROM FGLOCG INNER JOIN FGLO ON FGLOCG.CNSGLO=FGLO.CNSGLO WHERE FGLOCG.CNSGLO=@CNSGLO AND CNSFCGLO=@CNSFCGLO AND FGLO.CERRADA=0)
            BEGIN
               DELETE FGLOCG WHERE FGLOCG.CNSGLO=@CNSGLO AND CNSFCGLO=@CNSFCGLO
            END
            ELSE
            BEGIN
               INSERT INTO @TBLERRORES(ERROR)
               SELECT 'No Fue posible Borrar el registro, verifique si la glosa ya fue cerrada'
            END
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @VALOR=SUM(VALOR) FROM FGLOCG WHERE CNSGLO=@CNSGLO
      SELECT 'OK' OK,@VALOR VALOR
      RETURN 
   END  
   IF @METODO='CRUD_FGLO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
      DECLARE @APLICA  BIT
      
      SELECT @CNSGLO=CNSGLO,@TIPO=TIPO,@TIPORESPUESTA=TIPORESPUESTA,@RADICADO=RADICADO,@IDCONCEPTO=IDCONCEPTO,
             @VLRACEPTADO=VLRACEPTADO,@OBSERVACION=OBSERVACION,@FECHARESP=CONVERT(DATE,FECHARESP),@USURESPONRTA=USURESPONRTA,
             @OBSERVACIONRTA=OBSERVACIONRTA,@APLICA=APLICA
      FROM   OPENJSON (@DATOS)
      WITH   ( 
      CNSGLO  VARCHAR(20)          '$.CNSGLO',
      TIPO  VARCHAR(20)            '$.TIPO.value',
      TIPORESPUESTA  VARCHAR(20)   '$.TIPORESPUESTA.value',
      RADICADO  VARCHAR(20)        '$.RADICADO',
      IDCONCEPTO  VARCHAR(20)      '$.IDCONCEPTO',
      VLRACEPTADO  DECIMAL(14,2)   '$.VLRACEPTADO',
      OBSERVACION  VARCHAR(MAX)    '$.OBSERVACION',
      FECHARESP  VARCHAR(20)       '$.FECHARESP',
      USURESPONRTA  VARCHAR(20)    '$.USURESPONRTA',
      OBSERVACIONRTA  VARCHAR(MAX) '$.OBSERVACIONRTA',
      APLICA  BIT   '$.APLICA'
      )   
      IF EXISTS(SELECT * FROM FGLO WHERE CNSGLO=@CNSGLO AND CERRADA=0)
      BEGIN
         BEGIN TRY           
            UPDATE FGLO SET TIPO=@TIPO,TIPORESPUESTA=@TIPORESPUESTA,RADICADO=@RADICADO,IDCONCEPTO=@IDCONCEPTO,VLRACEPTADO=COALESCE(@VLRACEPTADO,0),
            VLRRECUPERAR=VLRGLOSA-COALESCE(@VLRACEPTADO,0),OBSERVACION=@OBSERVACION,OBSERVACIONRTA=@OBSERVACIONRTA,USURESPONRTA=@USURESPONRTA,
            FECHARESP=@FECHARESP,USUARIO=CASE WHEN COALESCE(USUARIO,'')='' THEN  @USUARIO ELSE USUARIO END,USUARIOINGRTA=@USUARIO
            WHERE CNSGLO=@CNSGLO

            IF COALESCE(@APLICA,0)=1
            BEGIN
               PRINT 'Voy a aplicar la glosa FECHARESP'+CONVERT(VARCHAR,@FECHARESP,103)
               IF EXISTS(SELECT * FROM PRI WHERE CONVERT(DATE,FECHA_INI)<=@FECHARESP AND CONVERT(DATE,FECHA_FIN)>=@FECHARESP AND COALESCE(CERRADO,0)=0 AND COALESCE(CERRADO_CARTERA,0)=0 )
               BEGIN
                  SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA,'01'),
                  @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_COMPUTERNAME,HOST_NAME())
                  FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
                  WHERE USUSU.USUARIO=@USUARIO
                  BEGIN TRY 
                        PRINT 'Si pase voy a llamar el spk'
                        EXEC SPK_RESPUESTAGLOSA @CNSGLO,3,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,0                                   
                  END TRY
                  BEGIN CATCH
                          INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
                  END CATCH
               END
            END
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro la Glosa o ya esta Cerrada, Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @TIPORESPUESTA=TIPORESPUESTA FROM FGLO WHERE CNSGLO=@CNSGLO
      SELECT 'OK' OK,@TIPORESPUESTA TIPORESP
      RETURN 
   END 
   IF @METODO='CRUD_FGLOD'     
   BEGIN   
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )         
      SELECT @PROCESO =PROCESO,@CNSGLO =CNSGLO,@VLRACEPTADO =VLRACEPTADO,@VLRGLOSA =VLRGLOSA,@TIPO =TIPO,@CODGLOSA =CODGLOSA,@OBSERVACION =OBSERVACION,
      @CODRPTA =CODRPTA,@RESPUESTA =RESPUESTA,@CONCEPTO =CONCEPTO,@DESCRIPCION =DESCRIPCION,@CANTIDAD =CANTIDAD,@VR_UNITARIO =VR_UNITARIO,
      @IDSERVICIO =IDSERVICIO,@ITEM =ITEM
      FROM   OPENJSON (@DATOS)
      WITH   (  
      PROCESO  VARCHAR(20)       '$.PROCESO',
      CNSGLO  VARCHAR(20)        '$.CNSGLO',
      VLRACEPTADO  VARCHAR(20)   '$.VLRACEPTADO',
      VLRGLOSA  VARCHAR(20)      '$.VLRGLOSA',
      TIPO  VARCHAR(20)          '$.TIPO.value',
      CODGLOSA  VARCHAR(20)      '$.CODGLOSA',
      OBSERVACION  VARCHAR(MAX)  '$.OBSERVACION',
      CODRPTA  VARCHAR(20)       '$.CODRPTA',
      RESPUESTA  VARCHAR(MAX)    '$.RESPUESTA',
      CONCEPTO  VARCHAR(20)      '$.CONCEPTO',
      DESCRIPCION  VARCHAR(512)  '$.DESCRIPCION',
      CANTIDAD  VARCHAR(20)      '$.CANTIDAD',
      VR_UNITARIO  VARCHAR(20)   '$.VR_UNITARIO',
      ITEM  INT                  '$.ITEM',
      IDSERVICIO  VARCHAR(20)    '$.IDSERVICIO'
      )   
      IF EXISTS(SELECT * FROM FGLO WHERE CNSGLO=@CNSGLO AND CERRADA=0)
      BEGIN
         IF @PROCESO='Nuevo'
         BEGIN
            SELECT @ITEM=MAX(ITEM) FROM FGLOD WHERE CNSGLO=@CNSGLO
            SELECT @ITEM=COALESCE(@ITEM,0)+1
            INSERT INTO FGLOD (CNSGLO, ITEM, CNSCXC, N_FACTURA, USUARIO, FECHANOVEDAD, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
                               VLRGLOSA, VLRACEPTADO, VLRRECUPERAR, OBSERVACION, CERRADA, RESPUESTA, FECHARESP,  CONCEPTO,ASIGRESP, RESPONSABLE,
                               OBSRESPON, VALORFINAL, AUTORIZA, ESTADO, N_CUOTAS, USUARIOCE, TIPOTEC, F_CIERRE, CONTABILIZADA, NROCOMPROBANTE,
                               IDAREA, CCOSTO, CODUNG,  CODPRG, N_CUOTA, CODGLOSA, CODRPTA)
            SELECT CNSGLO, @ITEM, CNSCXC, N_FACTURA, USUARIO, DBO.FNK_GETDATE(), @TIPO, @IDSERVICIO, @DESCRIPCION, @CANTIDAD, @VR_UNITARIO, 
                   @VLRGLOSA, @VLRACEPTADO, (@VLRGLOSA-@VLRACEPTADO), @OBSERVACION,CERRADA, @RESPUESTA,NULL, @CONCEPTO, NULL, NULL, NULL,NULL,
                   NULL, NULL, NULL,NULL,NULL,NULL,NULL,NULL,NULL, NULL, NULL,  NULL, NULL, @CODGLOSA, @CODRPTA
            FROM FGLO 
            WHERE CNSGLO=@CNSGLO
         END
         IF @PROCESO='Editar'
         BEGIN
            
            UPDATE FGLOD SET TIPO=@TIPO,@IDSERVICIO=@IDSERVICIO,DESCRIPCION=@DESCRIPCION,CANTIDAD=@CANTIDAD,VR_UNITARIO=@VR_UNITARIO,
                             VLRGLOSA=@VLRGLOSA,VLRACEPTADO=@VLRACEPTADO,VLRRECUPERAR=(@VLRGLOSA-@VLRACEPTADO),OBSERVACION=@OBSERVACION,
                             RESPUESTA=@RESPUESTA,CONCEPTO=@CONCEPTO,CODGLOSA=@CODGLOSA,CODRPTA=@CODRPTA
            WHERE CNSGLO=@CNSGLO
            AND ITEM=@ITEM
         END
         IF @PROCESO='Borrar'
         BEGIN
            DELETE FGLOD 
            WHERE CNSGLO=@CNSGLO
            AND ITEM=@ITEM
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se encontro la glosa o ya esta cerrada, verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @VALOR=SUM(VLRGLOSA) FROM FGLOD WHERE CNSGLO=@CNSGLO
      SELECT 'OK' OK,@VALOR VALOR
      RETURN 
   END 
   IF @METODO='APLICAR_GLOSA'     
   BEGIN         
      SELECT @CNSGLO =CNSGLO       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSGLO  VARCHAR(20)   '$.CNSGLO'
      )   
      IF EXISTS(SELECT * FROM FGLO WHERE CNSGLO=@CNSGLO AND CERRADA=0)
      BEGIN
         SELECT @FECHARESP=FECHARESP FROM FGLO WHERE CNSGLO=@CNSGLO
         PRINT 'Voy a aplicar la glosa FECHARESP'+CONVERT(VARCHAR,@FECHARESP,103)
         IF EXISTS(SELECT * FROM PRI WHERE CONVERT(DATE,FECHA_INI)<=@FECHARESP AND CONVERT(DATE,FECHA_FIN)>=@FECHARESP AND COALESCE(CERRADO,0)=0 AND COALESCE(CERRADO_CARTERA,0)=0 )
         BEGIN
            SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA,'01'),
            @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_COMPUTERNAME,HOST_NAME())
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
            WHERE USUSU.USUARIO=@USUARIO
            BEGIN TRY 
                  PRINT 'Si pase voy a llamar el spk'
                  EXEC SPK_RESPUESTAGLOSA @CNSGLO,3,@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,0                                   
            END TRY
            BEGIN CATCH
                     INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Periodo contable, cerrado o no existe, Verifique e intente de nuevo'
         END
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se encontro el Cnsglosa o ya fue aplicado, verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
END

