IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='ADMINQ_FACTURAS' AND IDCONTROL='FACT_COTIZA')
BEGIN 
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'ADMINQ_FACTURAS', 'FACT_COTIZA', 'P', 'Crear Cotizaciones', 1, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL
END