CREATE OR ALTER PROCEDURE DBO.SPQ_UPLOAD
(
	@NOMBRE_ARCHIVO	VARCHAR(128)
	,@EXTENSION		VARCHAR(10)
	,@ARCHIVO		VARBINARY(MAX)
	,@USUARIO       VARCHAR(20)

	,@CONSECUTIVO   VARCHAR(100) = NULL
	,@CONSECUTIVO2  VARCHAR(100) = NULL
	,@PROCESO       VARCHAR(20) = ''
	,@FECHADOCUMENTO DATE = NULL
)
WITH ENCRYPTION   
AS   
DECLARE @DOCUMENTOID UNIQUEIDENTIFIER = NEWID()
DECLARE @AHORA DATETIME = DBO.FNK_GETDATE()
DECLARE @TBLERRORES TABLE(ERROR VARCHAR(1000));

BEGIN    
  
	SET DATEFORMAT dmy
	SET @FECHADOCUMENTO = COALESCE(@FECHADOCUMENTO, @AHORA)

	BEGIN TRY
    
		IF (COALESCE(@CONSECUTIVO2,'') ='FOTO' ) 
		BEGIN
			-- COLOCO LA EXTENSION POR DEFECTO PORQUE SE TOMO CON LA CAMARA
			SET @EXTENSION	='png'
		END

		IF COALESCE(@PROCESO, '') IN ('', 'HCA' ,'RCONREFD', 'FIRMA_HCA' ,'QUEJAS', 'HCINF', 'GESTION_DOCUMENTAL','FIRMA_CIT','IMEREV','AFI','IMGDESCRITA_MPLD'
                                   ,'RCLD','FIRMA_HADM','GUIAS','ASEGURADORAS','ENCU','NOVTUR')
		BEGIN
			INSERT INTO DBO.DOCS(DocumentoID, DocNombre, DocExtension, DocFS, 
			DocFechaRegistro, DocUsuario, DocConsecutivo, DocCnsAuxiliar, DocTipo)
			VALUES(
				 @DOCUMENTOID
				,DBO.FNK_LIMPIATEXTO(@NOMBRE_ARCHIVO,'A-Z0-9. ')
				,@EXTENSION
				,@ARCHIVO
				,@AHORA
				,@USUARIO
				,@CONSECUTIVO
				,@CONSECUTIVO2
				,COALESCE(@PROCESO, '')
			)
		END

		IF COALESCE(@PROCESO,'') = 'MED'
		BEGIN
			INSERT INTO ARCHIVOS(NOMBRE,DICOM)
			SELECT @NOMBRE_ARCHIVO,@ARCHIVO

			UPDATE MED SET IDFIRMA=@@IDENTITY WHERE IDMEDICO = @CONSECUTIVO
			
			SELECT 'OK' OK, @@IDENTITY DocumentoID
			
			RETURN
		END

		
		IF COALESCE(@PROCESO,'') = 'AFI'
		BEGIN
			
			IF EXISTS (SELECT DocumentoID
			FROM AFI 
			INNER JOIN DOCS ON DocumentoID = AFI.IDFOTO
			WHERE AFI.IDAFILIADO = @CONSECUTIVO )
			BEGIN 
				PRINT 'Si existe una foto previa la borro para liberar el espacio'
				
				DELETE DBO.DOCS 
				FROM AFI 
					INNER JOIN DOCS ON DocumentoID = AFI.IDFOTO
				WHERE AFI.IDAFILIADO = @CONSECUTIVO
				
			END
			
			update afi set idfoto=@DOCUMENTOID where idafiliado=@CONSECUTIVO 
				SELECT 'OK' OK, @@IDENTITY DocumentoID
			RETURN
		END

	END TRY
	BEGIN CATCH
		INSERT INTO @TBLERRORES(ERROR) 
		SELECT ERROR_MESSAGE()            
	END CATCH

	IF EXISTS(SELECT * FROM @TBLERRORES)
	BEGIN
		SELECT 'KO'OK
		SELECT ERROR FROM @TBLERRORES
	END
	ELSE
	BEGIN
		SELECT 'OK' OK, @DOCUMENTOID DocumentoID
	END
END







