CREATE OR ALTER PROCEDURE DBO.SPQ_XML_CREA_IART @JSON NVARCHAR(MAX)
WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX),@MODELO VARCHAR(100)   ,@METODO VARCHAR(100)
,@USUARIO VARCHAR(12)   ,@COMPANIA VARCHAR(2)      ,@IDSEDE      VARCHAR(5)
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)          ,@DATOS1 VARCHAR(MAX)      
      ,@TIP_OPE VARCHAR(10)               ,@TIP_ART VARCHAR(10)            ,@COD_ART  varchar(20)
      ,@DES_ART varchar(200)              ,@COD_LAB VARCHAR(20)            ,@IDSERVICIO VARCHAR(20)
      ,@ID_TRX VARCHAR(50)
BEGIN
SELECT *
INTO #JSON
FROM OPENJSON(@json) WITH (
MODELO VARCHAR(100) '$.MODELO'
,METODO VARCHAR(100) '$.METODO'
,USUARIO VARCHAR(12) '$.USUARIO'
,PARAMETROS NVARCHAR(MAX) AS JSON
)


SELECT   @MODELO = MODELO,@METODO = METODO
,@PARAMETROS = PARAMETROS,@USUARIO = USUARIO
FROM #JSON

   IF @METODO='CREA_ARTICULO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS VARCHAR(MAX)
      )
      SELECT @DATOS1=@DATOS
      SELECT @DATOS=REPLACE(@DATOS,'ns1:','')
      SELECT @DATOS=REPLACE(@DATOS,' xmlns:ns1="http://integrador.clinicainternacional.com.pe/Articulo"','')
      SELECT @DATOS=dbo.FNK_LIMPIATEXTO(@DATOS,'0-9 A-Z </>:.=_"')

      DECLARE @XmlDocumentHandle int;

      EXEC sp_xml_preparedocument @XmlDocumentHandle OUTPUT, @DATOS;

     SELECT @ID_TRX=ID_TRX, @TIP_OPE=TIP_OPE,@TIP_ART=TIP_ART,@COD_ART=COD_ART,@DES_ART=DES_ART,@COD_LAB=COD_LAB
     FROM OPENXML (@XmlDocumentHandle, '/Articulo',2)
               WITH (ID_TRX VARCHAR(50),
                     TIP_OPE VARCHAR(10),
                     TIP_ART VARCHAR(10),
                     COD_ART  varchar(20),
                     DES_ART varchar(200),
                     COD_LAB VARCHAR(20)
                     );
     EXEC sp_xml_removedocument @XmlDocumentHandle;
       
     PRINT 'Comienzo las validaciones'
     PRINT '@COD_ART ='+@COD_ART
     IF NOT EXISTS(SELECT * FROM IART WHERE IDARTICULO=@COD_ART)
     BEGIN
       PRINT 'NO EXISTE'
        BEGIN TRY           
           INSERT INTO IART(IDARTICULO,IDCLASE,IDSUBCLASE,IDGRUPO,DESCRIPCION,IDPRINACTIVO,IDFORFARM,IDCONCENTRA,IDUNIDAD,PCOSTO,EXISTOTAL,IDITAR,IDSERVICIO,PRINCIPAL,IDFABRICANTE)   
           SELECT @COD_ART,'NA','NA','NA',@DES_ART,'NA','NA','NA','NA',0,0,CASE WHEN @TIP_ART='ZMED' THEN '01' ELSE '02' END,@COD_ART,1,@COD_LAB

           PRINT 'INSERTANDO EN SER'
      IF (OBJECT_ID('tempdb.dbo.#SERINTER','U')) IS NOT  NULL
      BEGIN
      DROP TABLE #SERINTER
      END
            SELECT TOP 1 PREFIJO, IDSERVICIO, DESCSERVICIO, IDACTIVIDAD, NIVELATENCION, NIVELFUNCIONARIO, NIVELSEDE, GRUPOQX, IDJERARQUIA, 
                        IDSUBJERARQUIA, NOM_GENERICO, PRESENTACION, CANTIDAD, CANTMAXIMA, COMENTARIOS,  DIASRESTAUTO, POSS, POS, ESTADO, SEXO,
                        TIPORANGOE, EDADINICIAL, EDADFINAL, IDPREPARACION, MPROVEEDOR, CLASIF1, CLASIF2, CODIGORIPS, MEDICAMENTOS, IDALTERNA,
                        PYP, SPD,  MRECARGONOCTURNO, TIPORECARGONOC, VLRRECARGONOC, HIRECNOC, HFRECNOC, DIASIGRN, IDREFERENCIA, CCOSTO, 
                        IDARTICULO, MPERSONAL_AT, IDMODELOCONT, MSUBSERVICIO, REQAUTORIZACION, TIPOAUTORIZACION,  MOBSOBLIGATORIA, CIRUGIA,
                        IDSECCION, IDPLANILLA, IDMUESTRA, DURACIONMUESTRA, IDGRUPOIMP, IMPRIMELAB, IDGENERICO, ISS04, ACLARAISS04, IVA, 
                        IDIMPUESTO, IDCLASE, ITFC, CNSITFC,  IDALTERNA_ORI, ESVACUNA, CODCUPS, DESCRIPCION_CUPS, MAMOGRAFIA, CODCUM, 
                        CODFURIPS, AMBITO, MCF, CODFCT, CLASEHTX, MDOSIF, EQUICC, PRESUNI, T_ESTABILIDAD, VLRCOSTO, 
                        MEZCLA, VIA,  IDSERVICIOM, TERAPIA, SERIAL, EQUICCINF, VPAI, VTIPOEDAD, VEDADINI, VEDADFIN, COLOR, 
                        ANTECESOR, IDEMEDICA, ENINTERFAZ, ANESTESIA, SERIADO, CODSISPRO, MULTIDOSIS, REPORTA, TEXDEFAUL,  
                        GRUPO, EXCLUYEPOSOLOGIA, TRANSFORMADO, GARANTIA, MINUTOSMS, CANTMAXIMA_CE, CANTMAXIMA_FME, TELECONSULTA, SMS, 
                        LIBREFORMULACION, ATENCION, MLATERALIDAD, PRIORITARIO, VEXIST,  CUPS_ID, DURACIONCITA, EQUIPOMUES, 
                        IDEQUIPO_MUESTRA, INICIALES, MPRINCIPAL, BIOFAR, SESIONES, TIPOSES, ONCOLOGIA, HORARIO, HDESDE, HHASTA INTO #SERINTER
            FROM SER 
            WHERE PREFIJO=CASE WHEN @TIP_ART='ZMED'  THEN DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS') 
                  ELSE DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES') END
            AND SER.ESTADO='Activo'
            AND EXISTS(SELECT * FROM TARDV WHERE SER.IDSERVICIO=TARDV.IDSERVICIO)

            SELECT @IDSERVICIO= IDSERVICIO FROM #SERINTER

            UPDATE #SERINTER SET IDSERVICIO=@COD_ART,IDARTICULO=@COD_ART,DESCSERVICIO=@DES_ART,DESCRIPCION_CUPS=@DES_ART,IDALTERNA=@COD_ART,
                                 EQUICC=NULL,MDOSIF=0
            WHERE IDSERVICIO=@IDSERVICIO

            INSERT INTO SER(PREFIJO, IDSERVICIO, DESCSERVICIO, IDACTIVIDAD, NIVELATENCION, NIVELFUNCIONARIO, NIVELSEDE, GRUPOQX, IDJERARQUIA, 
                        IDSUBJERARQUIA, NOM_GENERICO, PRESENTACION, CANTIDAD, CANTMAXIMA, COMENTARIOS,  DIASRESTAUTO, POSS, POS, ESTADO, SEXO,
                        TIPORANGOE, EDADINICIAL, EDADFINAL, IDPREPARACION, MPROVEEDOR, CLASIF1, CLASIF2, CODIGORIPS, MEDICAMENTOS, IDALTERNA,
                        PYP, SPD,  MRECARGONOCTURNO, TIPORECARGONOC, VLRRECARGONOC, HIRECNOC, HFRECNOC, DIASIGRN, IDREFERENCIA, CCOSTO, 
                        IDARTICULO, MPERSONAL_AT, IDMODELOCONT, MSUBSERVICIO, REQAUTORIZACION, TIPOAUTORIZACION,  MOBSOBLIGATORIA, CIRUGIA,
                        IDSECCION, IDPLANILLA, IDMUESTRA, DURACIONMUESTRA, IDGRUPOIMP, IMPRIMELAB, IDGENERICO, ISS04, ACLARAISS04, IVA, 
                        IDIMPUESTO, IDCLASE, ITFC, CNSITFC,  IDALTERNA_ORI, ESVACUNA, CODCUPS, DESCRIPCION_CUPS, MAMOGRAFIA, CODCUM, 
                        CODFURIPS, AMBITO, MCF, CODFCT, CLASEHTX, MDOSIF, EQUICC, PRESUNI, T_ESTABILIDAD, VLRCOSTO, 
                        MEZCLA, VIA,  IDSERVICIOM, TERAPIA, SERIAL, EQUICCINF, VPAI, VTIPOEDAD, VEDADINI, VEDADFIN, COLOR, 
                        ANTECESOR, IDEMEDICA, ENINTERFAZ, ANESTESIA, SERIADO, CODSISPRO, MULTIDOSIS, REPORTA, TEXDEFAUL,  
                        GRUPO, EXCLUYEPOSOLOGIA, TRANSFORMADO, GARANTIA, MINUTOSMS, CANTMAXIMA_CE, CANTMAXIMA_FME, TELECONSULTA, SMS, 
                        LIBREFORMULACION, ATENCION, MLATERALIDAD, PRIORITARIO, VEXIST,  CUPS_ID, DURACIONCITA, EQUIPOMUES, 
                        IDEQUIPO_MUESTRA, INICIALES, MPRINCIPAL, BIOFAR, SESIONES, TIPOSES, ONCOLOGIA, HORARIO, HDESDE, HHASTA)
            SELECT PREFIJO, IDSERVICIO, DESCSERVICIO, IDACTIVIDAD, NIVELATENCION, NIVELFUNCIONARIO, NIVELSEDE, GRUPOQX, IDJERARQUIA, 
                        IDSUBJERARQUIA, NOM_GENERICO, PRESENTACION, CANTIDAD, CANTMAXIMA, COMENTARIOS,  DIASRESTAUTO, POSS, POS, ESTADO, SEXO,
                        TIPORANGOE, EDADINICIAL, EDADFINAL, IDPREPARACION, MPROVEEDOR, CLASIF1, CLASIF2, CODIGORIPS, MEDICAMENTOS, IDALTERNA,
                        PYP, SPD,  MRECARGONOCTURNO, TIPORECARGONOC, VLRRECARGONOC, HIRECNOC, HFRECNOC, DIASIGRN, IDREFERENCIA, CCOSTO, 
                        IDARTICULO, MPERSONAL_AT, IDMODELOCONT, MSUBSERVICIO, REQAUTORIZACION, TIPOAUTORIZACION,  MOBSOBLIGATORIA, CIRUGIA,
                        IDSECCION, IDPLANILLA, IDMUESTRA, DURACIONMUESTRA, IDGRUPOIMP, IMPRIMELAB, IDGENERICO, ISS04, ACLARAISS04, IVA, 
                        IDIMPUESTO, IDCLASE, ITFC, CNSITFC,  IDALTERNA_ORI, ESVACUNA, CODCUPS, DESCRIPCION_CUPS, MAMOGRAFIA, CODCUM, 
                        CODFURIPS, AMBITO, MCF, CODFCT, CLASEHTX, MDOSIF, EQUICC, PRESUNI, T_ESTABILIDAD, VLRCOSTO, 
                        MEZCLA, VIA,  IDSERVICIOM, TERAPIA, SERIAL, EQUICCINF, VPAI, VTIPOEDAD, VEDADINI, VEDADFIN, COLOR, 
                        ANTECESOR, IDEMEDICA, ENINTERFAZ, ANESTESIA, SERIADO, CODSISPRO, MULTIDOSIS, REPORTA, TEXDEFAUL,  
                        GRUPO, EXCLUYEPOSOLOGIA, TRANSFORMADO, GARANTIA, MINUTOSMS, CANTMAXIMA_CE, CANTMAXIMA_FME, TELECONSULTA, SMS, 
                        LIBREFORMULACION, ATENCION, MLATERALIDAD, PRIORITARIO, VEXIST,  CUPS_ID, DURACIONCITA, EQUIPOMUES, 
                        IDEQUIPO_MUESTRA, INICIALES, MPRINCIPAL, BIOFAR, SESIONES, TIPOSES, ONCOLOGIA, HORARIO, HDESDE, HHASTA
            FROM #SERINTER

            PRINT 'INSERTANDO TARIFAS'

            INSERT INTO TARD(IDTARIFA, IDSERVICIO, VALOR, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION)
            SELECT TOP 1 IDTARIFA, @COD_ART, VALOR, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION
            FROM TARD WHERE IDSERVICIO=@IDSERVICIO
            

            INSERT INTO TARDV(IDTARIFA, IDSERVICIO, NOITEM, VALOR, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION, TIPOVALOR)
            SELECT TOP 1 IDTARIFA, @COD_ART, NOITEM, 0, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION, TIPOVALOR
            FROM TARDV 
            WHERE IDSERVICIO=@IDSERVICIO
            ORDER BY NOITEM DESC
   
        END TRY
        BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
     END
     ELSE
     BEGIN
        PRINT 'ACTUALIZO'
        SELECT * FROM IART WHERE IDARTICULO=@COD_ART
        UPDATE IART SET DESCRIPCION=@DES_ART,IDITAR=CASE WHEN @TIP_ART='ZMED' THEN '01' ELSE '02' END,IDFABRICANTE=@COD_LAB WHERE IDARTICULO=@COD_ART
     END
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
        SELECT TOP 1 DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_OPE='MM1' THEN 'CREA IART' ELSE 'ACT IART' END,@DATOS1,@DATOS,ERROR,'ERRORES',NULL,@COD_ART FROM @TBLERRORES

        SELECT 'KO' OK, ERROR FROM @TBLERRORES
        RETURN
     END
     INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
     SELECT DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_OPE='MM1' THEN 'CREA IART' ELSE 'ACT IART' END,@DATOS1,@DATOS,'OK','TERMINADO',NULL,@COD_ART

     SELECT 'OK' OK
     RETURN 
   END  
END