IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='AGRUPAR_XML_SIMAYOR')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'AGRUPAR_XML_SIMAYOR','Agrupar el Xlm Dian si supera las 10000 lineas  SI|NO','Alfanumerica',''
END

