IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'KPAGE'  AND   C.NAME = 'ULTIMA_RESP')
BEGIN
   ALTER TABLE KPAGE  ADD ULTIMA_RESP VARCHAR(MAX)
END