IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='APOYODG_EE')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'APOYODG_EE','Ambito de apoyo diagnóstico Electro Encefalograma','Alfanumerica',''
END