CREATE OR ALTER PROCEDURE DBO.SPQ_CONTA_RPT @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
SET Language 'Spanish';
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@CUENTAINI VARCHAR(20)             ,@CUENTAFINAL VARCHAR(20)        ,@F_INICIAL DATETIME
      ,@F_FINAL DATETIME                  ,@F_CERTIFICADO DATETIME         ,@IDTERCERO VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='IMP_CERTIFICADO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
      SELECT @CUENTAINI=CUENTAINI,@CUENTAFINAL=CUENTAFINAL,@F_INICIAL=F_INICIAL,@F_FINAL=F_FINAL,@F_CERTIFICADO=F_CERTIFICADO,
      @IDTERCERO=IDTERCERO       
      FROM   OPENJSON (@DATOS)
      WITH   (   
      CUENTAINI  VARCHAR(20)   '$.CUENTAINI',
      CUENTAFINAL  VARCHAR(20) '$.CUENTAFINAL',
      F_INICIAL  DATE          '$.F_INICIAL',
      F_FINAL  DATE            '$.F_FINAL',
      F_CERTIFICADO  DATE      '$.F_CERTIFICADO',
      IDTERCERO  VARCHAR(20)   '$.IDTERCERO'
      )   

      SELECT 'OK'OK,TER.TIPO_ID, NIT,DV,RAZONSOCIAL,DBO.FNK_VALORVARIABLE('IDFORMATO_CERTI_RFTE')IDFORMATO,DBO.FNK_FECHA_DDMMAA(@F_INICIAL)F_INI,
      DBO.FNK_FECHA_DDMMAA(@F_FINAL) F_FIN,
      CASE WHEN YEAR(@F_INICIAL)=YEAR(@F_FINAL) THEN YEAR(@F_INICIAL) 
           ELSE CONCAT(CAST(YEAR(@F_INICIAL) AS VARCHAR(4)),' - ',CAST(YEAR(@F_FINAL) AS VARCHAR(4))) END ANIO
      FROM TER WHERE IDTERCERO=@IDTERCERO



      SELECT VK.CUENTA,VK.NOMCUENTA,SUM(VK.VALOR)VALOR,SUM(VK.BASE)BASE 
      FROM VWK_LIQ_IMP VK INNER JOIN PRI ON VK.ANO=PRI.ANO AND VK.MES=PRI.MES
      WHERE VK.CUENTA>=@CUENTAINI
      AND   VK.CUENTA<=@CUENTAFINAL
      AND   PRI.FECHA_INI>=@F_INICIAL
      AND   PRI.FECHA_FIN<=@F_FINAL
      AND   VK.IDTERCERO=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE VK.IDTERCERO END
      GROUP BY VK.CUENTA,VK.NOMCUENTA


      SELECT NIT,DV,RAZONSOCIAL,CONCAT(CIU.NOMBRE,'-',DEP.NOMBRE)CIUDAD,TER.TIPO_ID,
      CONCAT(CIU.NOMBRE,', ',CAST(DAY(@F_CERTIFICADO) AS VARCHAR(2)),' de ',DATENAME(MONTH,@F_CERTIFICADO),' de ',CAST(YEAR(@F_CERTIFICADO) AS VARCHAR(6))) FECHA
      FROM TER LEFT JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
               LEFT JOIN DEP ON DEP.DPTO=CIU.DPTO
      WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')


      SELECT SUM(VALOR)VALORT,SUM(BASE)BASET, 
      LTRIM(RTRIM(TRIM(DBO.FNK_DE_VALORES_A_LETRAS(SUM(VALOR)))))+' PESOS ***** ***** ***** ***** ***** ***** *****'AS LETRAS
      FROM VWK_LIQ_IMP VK INNER JOIN PRI ON VK.ANO=PRI.ANO AND VK.MES=PRI.MES
      WHERE VK.CUENTA>=@CUENTAINI
      AND   VK.CUENTA<=@CUENTAFINAL
      AND   PRI.FECHA_INI>=@F_INICIAL
      AND   PRI.FECHA_FIN<=@F_FINAL
      AND   VK.IDTERCERO=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE VK.IDTERCERO END
      RETURN
   END  
END

