IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='IDCJFPAIZIPAY')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO,TABLA,CAMPO_CODIGO,CAMPO_DESC)
   SELECT 'IDCJFPAIZIPAY','Forma de Pago IZIPAY','Alfanumerica','','FPA','FORMAPAGO','DESCRIPCION'
END


