IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='CONTAB_RECAUDO_PART')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'CONTAB_RECAUDO_PART','Contabliza los Recaudos de particulares SI|NO','Alfanumerica',''
END
