CREATE OR ALTER PROCEDURE DBO.SPQ_INFOMRES_INV @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@IDARTICULO VARCHAR(20)            ,@PCOSTO   DECIMAL(14,2)          ,@IDBODEGA VARCHAR(20)
      ,@TIPOMOV VARCHAR(20)               ,@F_INICIAL DATETIME              ,@F_FINAL DATETIME
      ,@CNSRPDX VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='IBOD_ITAR'     
   BEGIN         
      SELECT 'OK' OK
      SELECT IDBODEGA as value, DESCRIPCION AS label FROM IBOD
      WHERE EXISTS(SELECT * FROM IEXI WHERE IEXI.IDBODEGA=IBOD.IDBODEGA)
      AND IBOD.ESTADO='Activo'
      ORDER BY IBOD.IDBODEGA

      SELECT IDITAR AS value, DESCRIPCION AS label
      FROM ITAR 
      ORDER BY IDITAR ASC

      RETURN
    END   
   IF @METODO='IBOD_ITMO'     
   BEGIN         
      SELECT 'OK' OK
      SELECT IDBODEGA as value, DESCRIPCION AS label FROM IBOD
      WHERE EXISTS(SELECT * FROM IEXI WHERE IEXI.IDBODEGA=IBOD.IDBODEGA)
      AND IBOD.ESTADO='Activo'
      ORDER BY IBOD.IDBODEGA

      SELECT IDTIPOMOV AS value, DESCRIPCION AS label
      FROM ITMO 
      ORDER BY IDTIPOMOV ASC

      RETURN
    END 
   IF @METODO='TRAE_EXISTS'     
   BEGIN         
      SELECT @IDARTICULO=IDARTICULO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          IDARTICULO VARCHAR(20) '$.IDARTICULO'
            )    
      IF COALESCE(@IDARTICULO,'')<>'' AND EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
      BEGIN
         SELECT @PCOSTO=PCOSTO FROM IART WHERE IDARTICULO=@IDARTICULO
         SELECT 'OK'OK,@PCOSTO PCOSTO 

         SELECT IEXI.IDBODEGA,IBOD.DESCRIPCION,SUM(IEXI.EXISLOTE)CANTIDAD
         FROM IEXI INNER JOIN IBOD ON IEXI.IDBODEGA=IBOD.IDBODEGA
         WHERE IDARTICULO=@IDARTICULO
         AND EXISLOTE>0
         GROUP BY IEXI.IDBODEGA,IBOD.DESCRIPCION

         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO'KO
         RETURN
      END
        
   END   
   IF @METODO='BUSCAR_MOV'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      
         SELECT @IDBODEGA=IDBODEGA,   @TIPOMOV=TIPOMOV,  @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDARTICULO=IDARTICULO     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         IDBODEGA VARCHAR(20)       '$.IDBODEGA',
         TIPOMOV VARCHAR(20)       '$.TIPOMOV',
         F_INICIAL DATETIME        '$.F_INICIAL',
         F_FINAL DATETIME          '$.F_FINAL',
         IDARTICULO VARCHAR(20)    '$.IDARTICULO'       
         ) 
         IF EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
         BEGIN
            SELECT 'OK' OK
            PRINT 'Entradas'
            SELECT IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION, SUM(IMOVH.CANTIDAD)CANTIDAD, SUM(ISNULL(IMOVH.PCOSTO,0)) PCOSTO
            FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV  
                     INNER JOIN ITMO  ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV 
            WHERE IMOV.ESTADO=1 AND IMOVH.ESTADO=1 AND ITMO.TIPO='Credito' 
            AND   IMOVH.IDARTICULO=@IDARTICULO
            AND   IMOV.IDBODEGA=CASE WHEN COALESCE(@IDBODEGA,'Todas') <> 'Todas' THEN @IDBODEGA ELSE IMOV.IDBODEGA END 
            AND   IMOV.IDTIPOMOV=CASE WHEN COALESCE(@TIPOMOV,'Todos') <> 'Todos' THEN  @TIPOMOV ELSE IMOV.IDTIPOMOV END 
            AND   IMOV.FECHACONF>=@F_INICIAL
            AND   IMOV.FECHACONF<@F_FINAL+1
            GROUP BY IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION 

            PRINT 'SALIDAS'

            SELECT IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION, SUM(ISAL.CANTIDAD)CANTIDAD, SUM(ISNULL(ISAL.PCOSTO,0)) PCOSTO
            FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV                       
                     INNER JOIN ITMO ON IMOV.IDTIPOMOV=ITMO.IDTIPOMOV                 
            WHERE IMOV.ESTADO=1 AND ITMO.TIPO='Debito'                               
            AND   ISAL.IDARTICULO=@IDARTICULO
            AND   IMOV.IDBODEGA=CASE WHEN COALESCE(@IDBODEGA,'Todas') <> 'Todas' THEN @IDBODEGA ELSE IMOV.IDBODEGA END 
            AND   IMOV.IDTIPOMOV=CASE WHEN COALESCE(@TIPOMOV,'Todos') <> 'Todos' THEN  @TIPOMOV ELSE IMOV.IDTIPOMOV END 
            AND   IMOV.FECHACONF>=@F_INICIAL
            AND   IMOV.FECHACONF<@F_FINAL+1
            GROUP BY IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION 
         RETURN
      END
      ELSE
      BEGIN
         SELECT 'KO'KO
         RETURN
      END
   END   
   IF @METODO='DETALLE_ENTRADA'     
   BEGIN         
      SELECT @DATOS=DATOS,@IDBODEGA=IDBODEGA,@TIPOMOV=IDTIPOMOV       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON ,
         IDBODEGA VARCHAR(20) '$.IDBODEGA',
         IDTIPOMOV VARCHAR(20) '$.IDTIPOMOV'
            )           
         PRINT '@IDBODEGA ='+@IDBODEGA
         PRINT '@TIPOMOV ='+@TIPOMOV
         SELECT @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDARTICULO=IDARTICULO     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         F_INICIAL DATETIME        '$.F_INICIAL',
         F_FINAL DATETIME          '$.F_FINAL',
         IDARTICULO VARCHAR(20)    '$.IDARTICULO'       
         ) 
         IF EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
         BEGIN
            SELECT 'OK'OK
            IF @TIPOMOV = DBO.FNK_VALORVARIABLE('IDINVMOV_COMPRAS') OR @TIPOMOV=DBO.FNK_VALORVARIABLE('IDINVMOV_REMISION_EN')
            BEGIN
               PRINT 'Compras de Farmacia'
               SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
                      CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO)PCOSTO,IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,TER.NIT,TER.RAZONSOCIAL 
               FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                         INNER JOIN TER ON IMOV.IDTERCERO=TER.IDTERCERO
               WHERE IMOV.IDBODEGA=@IDBODEGA
               AND IMOV.IDTIPOMOV=@TIPOMOV
               AND IMOV.FECHACONF>=@F_INICIAL
               AND IMOV.FECHACONF<@F_FINAL+1
               AND IMOV.ESTADO=1
               RETURN
            END
            ELSE
            BEGIN
               PRINT 'OTROS MOVIMIENTOS'
               SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
               CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO),IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,AFI.DOCIDAFILIADO,AFI.NOMBREAFI
                     FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                               LEFT  JOIN HADM ON IMOV.NODOCUMENTO=HADM.NOADMISION
                               LEFT JOIN AFI   ON HADM.IDAFILIADO=AFI.IDAFILIADO
               WHERE IMOV.IDBODEGA=@IDBODEGA
               AND IMOV.IDTIPOMOV=@TIPOMOV
               AND IMOV.FECHACONF>=@F_INICIAL
               AND IMOV.FECHACONF<@F_FINAL+1
               AND IMOV.ESTADO=1
               AND IMOV.PROCEDENCIA<>'INV'
               UNION ALL
               SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
                      CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO),IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,TER.NIT,TER.RAZONSOCIAL 
               FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                         INNER JOIN TER ON IMOV.IDTERCERO=TER.IDTERCERO
               WHERE IMOV.IDBODEGA=@IDBODEGA
               AND IMOV.IDTIPOMOV=@TIPOMOV
               AND IMOV.FECHACONF>=@F_INICIAL
               AND IMOV.FECHACONF<@F_FINAL+1
               AND IMOV.ESTADO=1
            END
         END
      END
   IF @METODO='DETALLE_SALIDA'     
   BEGIN         
      SELECT @DATOS=DATOS,@IDBODEGA=IDBODEGA,@TIPOMOV=IDTIPOMOV       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON ,
         IDBODEGA VARCHAR(20) '$.IDBODEGA',
         IDTIPOMOV VARCHAR(20) '$.IDTIPOMOV'
            )           
         PRINT '@IDBODEGA ='+@IDBODEGA
         PRINT '@TIPOMOV ='+@TIPOMOV
         SELECT @F_INICIAL=F_INICIAL, @F_FINAL=F_FINAL, @IDARTICULO=IDARTICULO     
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         F_INICIAL DATETIME        '$.F_INICIAL',
         F_FINAL DATETIME          '$.F_FINAL',
         IDARTICULO VARCHAR(20)    '$.IDARTICULO'       
      ) 
      IF EXISTS(SELECT * FROM IART WHERE IDARTICULO=@IDARTICULO)
      BEGIN
         SELECT 'OK'OK
         PRINT 'SALIDAS DE INVENTARIO'
         SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
         CONVERT(INT,ISAL.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),ISAL.PCOSTO),ISAL.NOLOTE,ISAL.NOLOTEPEDIDO,IMOV.NODOCUMENTO,IMOV.CNSMOV,AFI.DOCIDAFILIADO,AFI.NOMBREAFI
               FROM IMOV INNER JOIN ISAL ON IMOV.CNSMOV=ISAL.CNSMOV
                           INNER JOIN IZSOL ON IMOV.NODOCUMENTO=IZSOL.CNSIZSOL
                           LEFT  JOIN HADM ON IZSOL.NOADMISION=HADM.NOADMISION
                           LEFT JOIN AFI   ON HADM.IDAFILIADO=AFI.IDAFILIADO
         WHERE IMOV.IDBODEGA=@IDBODEGA
         AND IMOV.IDTIPOMOV=@TIPOMOV
         AND IMOV.FECHACONF>=@F_INICIAL
         AND IMOV.FECHACONF<@F_FINAL+1
         AND IMOV.ESTADO=1
         AND IMOV.PROCEDENCIA='CM_SOL'
         UNION ALL
         SELECT DBO.FNK_FECHA_GRINGA(IMOV.FECHAMOV)FECHAMOV,DBO.FNK_FECHA_GRINGA(IMOV.FECHACONF)FECHACONF,IMOV.NODOCUMENTO,DBO.FNK_FECHA_GRINGA(IMOV.F_FACTURA)F_FACTURA,
                  CONVERT(INT,IMOVH.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),IMOVH.PCOSTO),IMOVH.NOLOTE,IMOVH.NOLOTEPEDIDO,IMOV.CNSFCOM,IMOV.CNSMOV,TER.NIT,TER.RAZONSOCIAL 
         FROM IMOV INNER JOIN IMOVH ON IMOV.CNSMOV=IMOVH.CNSMOV
                     INNER JOIN TER ON IMOV.IDTERCERO=TER.IDTERCERO
         WHERE IMOV.IDBODEGA=@IDBODEGA
         AND IMOV.IDTIPOMOV=@TIPOMOV
         AND IMOV.FECHACONF>=@F_INICIAL
         AND IMOV.FECHACONF<@F_FINAL+1
         AND IMOV.ESTADO=1
         AND IMOV.PROCEDENCIA='INV'

      END
   END
   IF @METODO='MEDPEN_APLICAR'     
   BEGIN       
      SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA) 
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
      WHERE USUARIO=@USUARIO
         
      BEGIN TRY
         PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')  +COALESCE(@COMPANIA,'CIA') 
         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT  
         PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'')   
		   SELECT @CNSRPDX = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'')                    
      END TRY
      BEGIN CATCH
         INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         SELECT ERROR AS ERROR FROM  @TBLERRORES 
         RETURN
      END CATCH

      INSERT INTO RPDX (CNS, IDTERCERO, STRINGMEDIO1, ID1, ID2, NOMBRE, CANTIDAD, FECHA1, CANTIDAD1,VALOR1)
        SELECT @CNSRPDX, 'IENF', SEC.DESCRIPCION, I.NOADMISION, I.IDSERVICIO, SER.DESCSERVICIO, I.CANTIDAD,
              F_RECIBIDO=I.FECHA, HORAS=DATEDIFF(HOUR,I.FECHA,GETDATE()),ROW_NUMBER() OVER(ORDER  BY @CNSRPDX  ASC) AS ID
        FROM (
        		SELECT NOADMISION=NOREFERENCIA, FECHA=MIN(FECHA), IDSERVICIO, CANTIDAD=COUNT(1)
        		FROM IENF WHERE IENF.TIPO='NOADMISION' AND IENF.COBRADO=0 AND IENF.DEVUELTO=0 AND IENF.APLICADO=0 
            AND IENF.DESECHADO=0 AND IENF.ENTREGADO=0
        		GROUP BY NOREFERENCIA, CONVERT(DATE,FECHA), IDSERVICIO
        	) AS I
           INNER JOIN HHAB ON HHAB.NOADMISION=I.NOADMISION AND HHAB.CLASE='Cama' AND HHAB.ESTADOHAB='Ocupada'
           INNER JOIN HHAB SEC ON SEC.HABCAMA=HHAB.SECTOR AND SEC.CLASE='Sector'
           INNER JOIN SER ON SER.IDSERVICIO=I.IDSERVICIO
        ORDER BY HORAS DESC

        SELECT 'OK'OK,@CNSRPDX AS CNSRPDX
        RETURN 
   END   
   IF @METODO='BORRAR_RPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSRPDX  VARCHAR(20) '$.CNSRPDX'
         )               
      DELETE RPDX WHERE CNS=@CNSRPDX
    END   
END

