IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_CIERRE_DE_CAJA' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_CIERRE_DE_CAJA
END

GO
CREATE PROCEDURE DBO.SPK_CIERRE_DE_CAJA
@CODCAJA          VARCHAR(4),
@SYS_COMPUTERNAME VARCHAR(254), 
@IDSEDE           VARCHAR(5),
@COMPANIA         VARCHAR(2) 
WITH ENCRYPTION
AS
DECLARE @NVOCONSEC VARCHAR(20)
BEGIN
    SELECT @NVOCONSEC = CNSACJ FROM CAJ WHERE CODCAJA = @CODCAJA
    UPDATE CAJ SET ABIERTA = 0 WHERE CODCAJA = @CODCAJA 

    UPDATE ACJ SET FECHACIERRE  = GETDATE(), ABIERTA = 0 WHERE CNSACJ = @NVOCONSEC

    INSERT INTO ACJD( CNSACJ, FORMAPAGO, TIPO, SALDO, CODCAJERO  )
    SELECT @NVOCONSEC, FORMAPAGO, 'Saldo Final', VALOR , NULL
    FROM   CAJR
    WHERE  CODCAJA = @CODCAJA
    AND    VALOR > 0
    
    PRINT 'CONTABILIZANDO CIERRE DE CAJA'

    EXEC SPK_NC_CONTAB_CIERRE_CAJ @NVOCONSEC,@IDSEDE,@SYS_COMPUTERNAME,''

END


