CREATE OR ALTER PROCEDURE DBO.SPQ_FORMATOS_NOMINA @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@PROCESO VARCHAR(10)               ,@CONTRATOS BIT                  ,@ESTADO VARCHAR(10)
      ,@TIPO    VARCHAR(20)               ,@OBSERVACION VARCHAR(255)       ,@CNSFORMATO VARCHAR(20)
      ,@CUERPO VARCHAR(MAX)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='CRUD_NCERTC'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )      
      SELECT @PROCESO=PROCESO,@CNSFORMATO=CNSFORMATO,@CONTRATOS=CASE WHEN CONTRATOS='true' THEN 1 ELSE 0 END,@ESTADO=ESTADO,@OBSERVACION=OBSERVACION,
             @TIPO=TIPO
      FROM   OPENJSON (@DATOS)
      WITH   (   
      PROCESO VARCHAR(20) '$.PROCESO',
      CNSFORMATO VARCHAR(20) '$.CNSFORMATO',
      CONTRATOS  VARCHAR(10) '$.CONTRATOS',
      ESTADO  VARCHAR(10)    '$.ESTADO',
      OBSERVACION VARCHAR(255) '$.OBSERVACION',
      TIPO VARCHAR(20)    '$.TIPO'
      )
      IF @PROCESO='Nuevo'
      BEGIN
         BEGIN TRY           
               SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
               FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
               WHERE USUARIO=@USUARIO

               PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')+' COMPANIA'+COALESCE(@COMPANIA,'CIA') 
               SELECT @CNSFORMATO=''
               EXEC SPQ_GENSEQUENCE @SEDE=@IDSEDE,@PREFIJO='@NCERTC' ,@NVOCONSEC=@CNSFORMATO OUTPUT
		         PRINT '@CNSFORMATO='+COALESCE(@CNSFORMATO,'')                
               INSERT INTO NCERTC(CNSFORMATO, ENCABEZADO, CUERPO, FINAL, ESTADO, CONTRATOS, TIPO, MINUTA, OBSERVACION, RLOGO, LSUPER,WEB)
               SELECT @CNSFORMATO,NULL,NULL,NULL,@ESTADO,@CONTRATOS,@TIPO,NULL,@OBSERVACION,NULL,NULL,1
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH

      END
      IF @PROCESO='Edita'
      BEGIN
         IF EXISTS(SELECT * FROM NCERTC WHERE CNSFORMATO=@CNSFORMATO)
         BEGIN
            PRINT @CONTRATOS
            UPDATE NCERTC SET ESTADO=@ESTADO,TIPO=@TIPO,CONTRATOS=@CONTRATOS,OBSERVACION=@OBSERVACION WHERE CNSFORMATO=@CNSFORMATO
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'No se encontro el Certificado, Verifique e intente de nuevo'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='TRAER_CUERPO'     
   BEGIN         
      SELECT @CNSFORMATO=CNSFORMATO,@TIPO=TIPO      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFORMATO VARCHAR(20) '$.CNSFORMATO',
      TIPO       VARCHAR(20) '$.TIPO'
      )
      IF EXISTS(SELECT * FROM NCERTC WHERE CNSFORMATO=@CNSFORMATO)
      BEGIN
         SELECT 'OK' OK,CUERPO=FORMATOWEB FROM NCERTC WHERE CNSFORMATO=@CNSFORMATO
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se encontro el Formato Solicitado, verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
                   
   END  
   IF @METODO='GUARDAR_CUERPO'     
   BEGIN         
      SELECT @DATOS=CUERPO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CUERPO NVARCHAR(MAX) AS JSON 
      )
      PRINT @DATOS           
      SELECT @CNSFORMATO=CNSFORMATO,@TIPO=TIPO,@CUERPO=CUERPO        
      FROM   OPENJSON (@DATOS)
      WITH   (  
      CNSFORMATO VARCHAR(20) '$.CNSFORMATO',
      TIPO  VARCHAR(20) '$.TIPO',
      CUERPO VARCHAR(MAX) '$.CUERPO'
      )   
      IF EXISTS(SELECT * FROM NCERTC WHERE CNSFORMATO=@CNSFORMATO AND TIPO=@TIPO)
      BEGIN
         BEGIN TRY           
             UPDATE NCERTC SET FORMATOWEB=@CUERPO WHERE CNSFORMATO=@CNSFORMATO AND TIPO=@TIPO                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encontro el formato '
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='TRAER_CONCEPTOS'     
   BEGIN         
      SELECT 'OK'
      SELECT CODCONCEPTO value,DESCRIPCION label
      FROM NCON 
      WHERE ESTADO='Activo'
   END  
END

