IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_MULTAS_CE' AND XTYPE='P')
BEGIN
 DROP PROCEDURE SPK_MULTAS_CE
END
GO
CREATE PROCEDURE DBO.SPK_MULTAS_CE
  @IDAFILIADO	    VARCHAR (20),  
  @CONSECUTIVOCAN  VARCHAR (20),                          	 
  @COMPANIA        VARCHAR(2),  
  @SEDE            VARCHAR(5)   
WITH ENCRYPTION
AS       
DECLARE @IDMODELOPCA         VARCHAR(5)
DECLARE @NIVELSOCIOEC	     VARCHAR(2)
DECLARE @VALORMULTA          DECIMAL (14,2)
DECLARE @NVOCONSEC           VARCHAR(20)
DECLARE @CNSACJ              VARCHAR(20)
DECLARE @CODIGOCPCJ          VARCHAR(16)
DECLARE @CNSFACJ             VARCHAR(20)
                          
BEGIN
      PRINT 'Entre'
      SELECT @IDMODELOPCA      = PPT.IDMODELOPCA
      FROM   AFI INNER JOIN PPT ON AFI.IDADMINISTRADORA=PPT.IDTERCERO
      WHERE  AFI.IDAFILIADO    = @IDAFILIADO         
      AND    PPT.IDPLAN        = AFI.IDPLAN       
      PRINT  'MODELODEPAGOCOMPARTIDO=' + @IDMODELOPCA

      SELECT @NIVELSOCIOEC     = AFI.NIVELSOCIOEC
      FROM   AFI 
      WHERE  AFI.IDAFILIADO    = @IDAFILIADO           
      PRINT 'NIVELSOCIO=' + @NIVELSOCIOEC

      SELECT @VALORMULTA      = MOCM.VALORMULTA,
             @CODIGOCPCJ      = MOCM.CODIGOCPCJ  
      FROM MOCM
      WHERE MOCM.IDMODELOPC   = @IDMODELOPCA
      AND   MOCM.ESCALASE     = @NIVELSOCIOEC

      PRINT '@VALORMULTA ='+STR(COALESCE(@VALORMULTA,0))

      UPDATE CITCI SET VALORMULTA = @VALORMULTA
      WHERE CITCI.CONSECUTIVOCAN  = @CONSECUTIVOCAN

--INSERTAR EN TFCJ
      EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@TFCJ', @NVOCONSEC OUTPUT    
      SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)   
         
         INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,  
                          IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO, CERRADA, FECHA, 
                          PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,  
                          CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,  
                          SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME)  
         SELECT @NVOCONSEC, NULL,  'COBRO', CONSECUTIVOCAN, '', 
                AFI.IDPLAN, CITCI.VALORMULTA, @COMPANIA, CITCI.IDAFILIADO, 0, GETDATE(), 
                'CEM', '', AFI.IDADMINISTRADORA, LEFT(LTRIM(RTRIM(AFI.PAPELLIDO))+' '+LTRIM(RTRIM(AFI.SAPELLIDO))  
                +' ' +LTRIM(RTRIM(AFI.PNOMBRE))+' '+ LTRIM(RTRIM(AFI.SNOMBRE)),40),    
                @CNSACJ, 'EXTERNO', 0, 0, 0, 0, NULL, CIT.IDAREA, CIT.CCOSTO, 
                CIT.SUBCCOSTO, 'C', '', CIT.USUARIO, CIT.SYS_COMPUTERNAME  
         FROM CITCI INNER JOIN  CIT  ON CITCI.CONSECUTIVO =CIT.CONSECUTIVO
         INNER JOIN  AFI  ON CITCI.IDAFILIADO = AFI.IDAFILIADO
         WHERE CITCI.CONSECUTIVOCAN = @CONSECUTIVOCAN
         AND   CITCI.IDAFILIADO     = @IDAFILIADO


         INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,  
                           TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)  
         SELECT NULL, @NVOCONSEC, 1,@CODIGOCPCJ, CIT.IDAREA, CITCI.VALORMULTA, 1, CITCI.VALORMULTA,NULL, 0, 
                'N', 0, 0  
         FROM CITCI INNER JOIN  CIT  ON CITCI.CONSECUTIVO =CIT.CONSECUTIVO
         WHERE CITCI.CONSECUTIVOCAN = @CONSECUTIVOCAN
         AND   CITCI.IDAFILIADO     = @IDAFILIADO
         
         SELECT @CNSFACJ = TFCJ.NOADMISION
         FROM TFCJ
         WHERE TFCJ.NOADMISION= @CONSECUTIVOCAN
         AND PROCEDENCIA  ='CEM'
 
         UPDATE CITCI SET CNSFACJ     = @CNSFACJ,TIPOCAJA='FCJ'
         WHERE CITCI.CONSECUTIVOCAN   = @CONSECUTIVOCAN

END


