IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'SER'  AND   C.NAME = 'TIPOMED')
BEGIN
   ALTER TABLE SER  ADD  TIPOMED VARCHAR(5)
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'SER'  AND   C.NAME = 'UPR')
BEGIN
   ALTER TABLE SER  ADD  UPR VARCHAR(5)
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER    JOIN SYS.columns C ON O.object_id = C.object_id  
               WHERE O.NAME = 'SER'  AND   C.NAME = 'TIPOOTRO')
BEGIN
   ALTER TABLE SER  ADD  TIPOOTRO VARCHAR(5)
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOMED' AND CODIGO='01')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOMED','01','Medicamento con uso con registro sanitario'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOMED' AND CODIGO='02')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOMED','02','Medicamento con uso como vital no disponible definido por INVIMA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOMED' AND CODIGO='03')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOMED','03','Preparacion magistral'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOMED' AND CODIGO='04')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOMED','04','Medicamento con uso no incluido en  el registro sanitario (Listado UNIRS)'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOMED' AND CODIGO='05')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOMED','05','Medicamento con autorizacion sanitaria de uso emergencia ASUE'
END
---
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOOTRO' AND CODIGO='01')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOOTRO','01','DISPOSITIVOS MEDICOS E INSUMOS'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOOTRO' AND CODIGO='02')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOOTRO','02','TRASLADOS'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOOTRO' AND CODIGO='03')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOOTRO','03','ESTANCIAS'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOOTRO' AND CODIGO='04')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOOTRO','04','SERVICIOS COMPLEMENTARIOS'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='TIPOOTRO' AND CODIGO='05')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','TIPOOTRO','05','HONORARIOS'
END
---
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='01')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','01','AMPOLLA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='10')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','10','ENVASE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='11')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','11','CAJA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='12')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','12','LATA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='13')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','13','FRASCO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='14')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','14','CAPSULA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='15')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','15','CARTON'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='16')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','16','CARTUCHO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='17')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','17','ESTUCHE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='18')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','18','PELICULA DE PVC TRANSPARENTE DE COLORES'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='19')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','19','UNIDADES CLINICAS'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='02')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','02','APLICADOR'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='20')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','20','RECUBRIMIENTO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='21')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','21','CONTENEDOR'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='22')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','22','RECUENTO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='23')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','23','COPA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='24')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','24','CILINDRO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='25')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','25','VASOS DEWAR'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='26')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','26','DIAL PACK'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='27')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','27','DISCO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='28')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','28','DOSIS EN ENVASE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='29')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','29','GOTAS'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='03')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','03','BOLSA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='30')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','30','TAMBOR - BOMBO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='31')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','31','PELICULA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='32')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','32','GENERADOR'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='33')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','33','GLOBULO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='34')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','34','DILUCION HOMEOPATICA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='35')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','35','IMPLANTE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='36')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','36','INHALACION'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='37')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','37','INHALADOR'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='38')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','38','INHALADOR, RECARGA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='39')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','39','INSERTO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='04')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','04','BARRA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='40')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','40','FRASCO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='41')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','41','JARRA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='42')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','42','UNIDAD INHIBIDORA DE CALICREINA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='43')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','43','KIT'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='44')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','44','PASTILLA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='45')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','45','EMBALAJE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='46')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','46','PAQUETE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='47')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','47','BALDE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='48')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','48','PARTES'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='49')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','49','PARCHE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='05')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','05','PERLA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='50')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','50','PILDORA (PELLET)'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='51')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','51','PIEZA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='53')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','53','UNIDADES DE PRESION'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='54')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','54','ANILLO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='55')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','55','SATURADO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='56')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','56','CUCHARA MEDIDORA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='57')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','57','ESPONJA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='58')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','58','ATOMIZADOR (SPRAY)'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='59')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','59','CENTIMETRO CUADRADO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='06')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','06','BLISTER'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='61')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','61','TIRA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='63')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','63','SUPOSITORIO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='64')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','64','HISOPO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='65')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','65','JERINGA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='66')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','66','TABLETA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='67')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','67','TABMINDER'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='68')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','68','TAMPON'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='69')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','69','TANQUE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='07')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','07','ENVASE BLISTER'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='70')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','70','PRUEBA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='71')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','71','BANDEJA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='72')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','72','TROCHE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='73')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','73','TUBO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='74')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','74','UNIDADES'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='75')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','75','VIAL'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='76')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','76','OBLEA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='77')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','77','TERMO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='78')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','78','SOBRE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='79')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','79','PLUMA'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='08')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','08','BLOQUE'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='80')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','80','LITRO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='81')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','81','OVULO'
END
IF NOT EXISTS(SELECT * FROM TGEN WHERE TABLA ='RIPSJSON' AND CAMPO='UPR' AND CODIGO='09')
BEGIN
   INSERT INTO TGEN (TABLA,CAMPO,CODIGO,DESCRIPCION)
   SELECT 'RIPSJSON','UPR','09','BOLO'
END
