IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_ACTUALIZA_IMOVH_DISAL' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_ACTUALIZA_IMOVH_DISAL
END

GO
CREATE PROCEDURE DBO.SPK_ACTUALIZA_IMOVH_DISAL
@CNSMOV VARCHAR(20)
WITH ENCRYPTION
AS 
DECLARE @CUANTOS INT
DECLARE @BASEPE   DECIMAL(14,2)
DECLARE @IDARTICULO_CUR VARCHAR(20)
DECLARE @CANTIDADP  DECIMAL(14,2)
DECLARE @CANTIDADE  DECIMAL(14,2)
DECLARE @NOLOTE     VARCHAR(20)
DECLARE @PCOSTO     DECIMAL(14,2)
DECLARE @FECHAVENCE DATETIME
DECLARE @CANTIDAD2  DECIMAL(14,2)
DECLARE @IDARTICULO VARCHAR(20)
DECLARE @ITEM       SMALLINT
DECLARE @IDTIPOMOV  VARCHAR(20)
DECLARE @IDBODEGA   VARCHAR(4)
BEGIN
   DECLARE JM_CURSOR CURSOR FOR 
   SELECT A.IDARTICULO,SUM(A.CANTPEDIDA),X.CANT
   FROM IMOVH A INNER JOIN (
                             SELECT A.CNSMOV,dbo.FNK_ARTICULO_MAYOR(B.IDSERVICIO,A.IDARTICULO)IDARTICULO,SUM(A.CANTIDAD)CANT
                             FROM   ISAL A INNER JOIN IART B ON A.IDARTICULO=B.IDARTICULO
                             WHERE  A.CNSMOV=@CNSMOV
					              GROUP BY A.CNSMOV,dbo.FNK_ARTICULO_MAYOR(B.IDSERVICIO,A.IDARTICULO)
					            ) X ON A.CNSMOV=X.CNSMOV AND A.IDARTICULO=X.IDARTICULO
   GROUP BY A.IDARTICULO,X.CANT
   OPEN JM_CURSOR    
   FETCH NEXT FROM JM_CURSOR    
   INTO @IDARTICULO_CUR,@CANTIDADP,@CANTIDADE
   WHILE @@FETCH_STATUS = 0    
   BEGIN
		SELECT  TOP 1 @NOLOTE=A.NOLOTE,@PCOSTO=B.PCOSTO,@FECHAVENCE=A.FECHAVENCE
		FROM ISAL A INNER JOIN IART B ON A.IDARTICULO=B.IDARTICULO
		WHERE A.CNSMOV=@CNSMOV AND dbo.FNK_ARTICULO_MAYOR(B.IDSERVICIO,A.IDARTICULO)=@IDARTICULO_CUR
  	  					  
		IF @CANTIDADP=@CANTIDADE
		BEGIN 
		   UPDATE IMOVH SET CANTIDAD=CANTPEDIDA ,FECHAVENCE=@FECHAVENCE,PCOSTO=@PCOSTO
			WHERE CNSMOV=@CNSMOV AND IDARTICULO=@IDARTICULO_CUR
		END
		IF @CANTIDADP>@CANTIDADE
		BEGIN
         PRINT 'ENTRE POR @CANTIDADP > @CANTIDADE // @CANTIDADP = ' + CONVERT(VARCHAR(20), @CANTIDADP) + '// @CANTIDADE = '+ CONVERT(VARCHAR(20), @CANTIDADE)
		   SELECT @BASEPE=@CANTIDADE 
		   DECLARE JM_CURSOR1 CURSOR FOR  
			SELECT IDARTICULO,COALESCE(ITEM,0), CANTPEDIDA FROM IMOVH 
			WHERE  CNSMOV=@CNSMOV AND IDARTICULO=@IDARTICULO_CUR    
         OPEN JM_CURSOR1    
			FETCH NEXT FROM JM_CURSOR1    
			INTO @IDARTICULO,@ITEM,@CANTIDAD2
			WHILE @@FETCH_STATUS = 0    
			BEGIN 
			   IF @CANTIDAD2<=@BASEPE
			   BEGIN
               print 'ENTRE POR @CANTIDAD2<=@BASEPE'
				   UPDATE IMOVH SET CANTIDAD=CANTPEDIDA,FECHAVENCE=@FECHAVENCE,PCOSTO=@PCOSTO
				   WHERE CNSMOV=@CNSMOV AND IDARTICULO=@IDARTICULO AND ITEM=@ITEM
														
				   --SELECT @BASEPE-@CANTIDAD2		       
	         END
			   IF @CANTIDAD2>@BASEPE
			   BEGIN
               print '@CANTIDAD2>@BASEPE   // @BASEPE = ' + CONVERT(VARCHAR(20), @BASEPE)+ ' // @ITEM	='+ CONVERT(VARCHAR(20),@ITEM)
			      UPDATE IMOVH SET CANTIDAD=@BASEPE,NOLOTE=@NOLOTE,FECHAVENCE=@FECHAVENCE,PCOSTO=@PCOSTO
				   WHERE CNSMOV=@CNSMOV AND IDARTICULO=@IDARTICULO AND COALESCE(ITEM,0)=COALESCE(@ITEM,0)
				   --SELECT @BASEPE-@BASEPE	
			   END

			   FETCH NEXT FROM JM_CURSOR1
			   INTO @IDARTICULO,@ITEM,@CANTIDAD2
		   END
		   CLOSE JM_CURSOR1
		   DEALLOCATE JM_CURSOR1
	   END

      PRINT 'ACTUALIZA PRECIOS DE COSTO EN ISAL' 
      SELECT @IDTIPOMOV=IDTIPOMOV,@IDBODEGA=IDBODEGA FROM IMOV WHERE CNSMOV=@CNSMOV
      IF @IDTIPOMOV=dbo.FNK_VALORVARIABLE('IDINVTRASLACTIVOS')
      BEGIN
         PRINT 'ES DE ACTIVOS....'
         UPDATE ISAL SET PCOSTO=IEXI.PCOSTO
         FROM ISAL INNER JOIN IEXI ON ISAL.IDARTICULO=IEXI.IDARTICULO AND ISAL.NOLOTE=IEXI.NOLOTE
         WHERE IEXI.IDBODEGA=@IDBODEGA	  
         AND ISAL.CNSMOV=@CNSMOV

         UPDATE ISAL SET VR_ANTESIVA=IEXI.VR_ANTESIVA,VR_IVA=IEXI.VR_IVA
         FROM ISAL INNER JOIN IEXI ON ISAL.IDARTICULO=IEXI.IDARTICULO AND ISAL.NOLOTE=IEXI.NOLOTE
         WHERE IEXI.IDBODEGA=@IDBODEGA AND ISAL.CNSMOV=@CNSMOV	AND ISAL.IDARTICULO_IMOVH=@IDARTICULO_CUR         
      END
      ELSE
      BEGIN

         UPDATE ISAL SET PCOSTO=IART.PCOSTO
         FROM ISAL INNER JOIN IART  ON ISAL.IDARTICULO=IART.IDARTICULO
         WHERE ISAL.CNSMOV=@CNSMOV AND ISAL.IDARTICULO_IMOVH=@IDARTICULO_CUR

         UPDATE ISAL SET VR_ANTESIVA=IEXI.VR_ANTESIVA,VR_IVA=IEXI.VR_IVA,PCOSTO=CASE WHEN COALESCE(ISAL.PCOSTO,0)<=0 OR COALESCE(IEXI.PCOSTO,0)-COALESCE(IEXI.VR_ANTESIVA,0) <0 THEN COALESCE(IEXI.VR_ANTESIVA,0) ELSE ISAL.PCOSTO END
         FROM ISAL INNER JOIN IEXI ON ISAL.IDARTICULO=IEXI.IDARTICULO AND ISAL.NOLOTE=IEXI.NOLOTE
         WHERE IEXI.IDBODEGA=@IDBODEGA AND ISAL.CNSMOV=@CNSMOV	AND ISAL.IDARTICULO_IMOVH=@IDARTICULO_CUR

         IF EXISTS(SELECT * FROM ISAL WHERE ISAL.CNSMOV=@CNSMOV AND ISAL.IDARTICULO_IMOVH=@IDARTICULO_CUR AND COALESCE(PCOSTO,0)<=0)
         BEGIN
            PRINT'EMERGENCIA EN EL CCOSTO....'
            DECLARE @PCOSTOX DECIMAL(14,2)
            SELECT TOP 1 @PCOSTOX=IIF(COALESCE(PCOSTO,0)<=0,COALESCE(VR_ANTESIVA,0),COALESCE(PCOSTO,0)) FROM IEXI WHERE IDARTICULO=@IDARTICULO_CUR 
            AND NOLOTE=@NOLOTE AND (COALESCE(PCOSTO,0)>0 OR COALESCE(VR_ANTESIVA,0)>0)
            ORDER BY FECHAMOV DESC

            UPDATE ISAL SET PCOSTO=@PCOSTOX
            FROM ISAL INNER JOIN IART  ON ISAL.IDARTICULO=IART.IDARTICULO
            WHERE ISAL.CNSMOV=@CNSMOV AND ISAL.IDARTICULO_IMOVH=@IDARTICULO_CUR

         END
      END

	   FETCH NEXT FROM JM_CURSOR    
	   INTO @IDARTICULO_CUR,@CANTIDADP,@CANTIDADE
   END
   CLOSE JM_CURSOR
   DEALLOCATE JM_CURSOR 
   PRINT 'ACTUALIZO PCOSTOS EN LA SALIDA'
   UPDATE IMOVH SET PCOSTO=ISAL.PCOSTO
   FROM  (
   SELECT ISAL.CNSMOV, ISAL.IDARTICULO_IMOVH,SUM(PCOSTO)PCOSTO FROM ISAL WHERE CNSMOV=@CNSMOV
   GROUP BY ISAL.CNSMOV, ISAL.IDARTICULO_IMOVH)ISAL INNER JOIN IMOVH ON IMOVH.CNSMOV=ISAL.CNSMOV AND IMOVH.IDARTICULO=ISAL.IDARTICULO_IMOVH
   WHERE IMOVH.CNSMOV=@CNSMOV
END

