IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='MTERCEROCTABCOCONTA')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'MTERCEROCTABCOCONTA','Maneja Tercero en Contabilizacion Cuenta de Bancos SI|NO','Alfanumerica','SI'
END