CREATE OR ALTER PROCEDURE DBO.SPQ_HCCOMCOL
@JSON  NVARCHAR(MAX)
WITH   ENCRYPTION
AS
DECLARE @PARAMETROS   NVARCHAR(MAX),  @MODELO   VARCHAR(100), @CLASEPLANTILLA VARCHAR(20)
		,@METODO      VARCHAR(100),   @USUARIO  VARCHAR(20), @A INT, @IDEMEDICA VARCHAR(20)
		,@IDAFILIADO VARCHAR(20),	  @NOADMISION VARCHAR(20), @CLASEPROGRAMA VARCHAR (20)
BEGIN
	SELECT @A = ISJSON(@JSON)
	IF @A = 0 
	BEGIN
		RAISERROR('Json: Formato Erroneo',16,1)
		RETURN
	END
	
	SET LANGUAGE Spanish; 
	SET DATEFORMAT dmy

	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(20)     '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON

	IF @METODO='PLANTILLA'
	BEGIN
		SELECT @CLASEPLANTILLA=CLASEPLANTILLA, @IDAFILIADO = IDAFILIADO, @NOADMISION = NOADMISION
		FROM OPENJSON (@PARAMETROS)
		WITH (CLASEPLANTILLA  VARCHAR(20) '$.CLASEPLANTILLA', IDAFILIADO  VARCHAR(20) '$.IDAFILIADO', NOADMISION  VARCHAR(20) '$.NOADMISION' )

		DECLARE @CODIGO_MED VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS')
		DECLARE @OMCODMEZCLA VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODMEZCLA')
		DECLARE @OMCODNUTRICIONP VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODNUTRICIONP')
		DECLARE @OMCODLABORATORIO VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODLABORATORIO')
		DECLARE @OMCODONCOLOGIA VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODONCOLOGIA')
		DECLARE @OMCODCITADECONTROL VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODCITADECONTROL')
		DECLARE @OMCODMOBILIARIO VARCHAR(20) = DBO.FNK_VALORVARIABLE('OMCODMOBILIARIO')

		SELECT @IDEMEDICA = IDEMEDICA FROM MED INNER JOIN USUSU ON USUSU.IDMEDICO=MED.IDMEDICO WHERE USUSU.USUARIO=@USUARIO

		SELECT @CLASEPROGRAMA = HTAD.CLASEPROGRAMA FROM HADM INNER JOIN HTAD ON HADM.TIPOADM=HTAD.TIPOADM WHERE NOADMISION=@NOADMISION
		SELECT 'OK' OK ,@CLASEPLANTILLA CLASEPLANTILLA

		SELECT TGEN.CAMPO CLASEPLANTILLA, TGEN.CODIGO CODOM, HCCOM.DESCRIPCION, hccom.ORDEN, HCCOM.TIPO
			, CASE WHEN TGEN.CODIGO=@CODIGO_MED THEN 1 ELSE 0 END MEDICAMENTOS
			, COALESCE(dbo.HCCOM.MBOLO,0) MBOLO
			, CASE WHEN @OMCODMEZCLA = HCCOM.CODOM THEN 1 ELSE 0 END MEZCLA
			, CASE WHEN @OMCODNUTRICIONP = HCCOM.CODOM THEN 1 ELSE 0 END NPT
			, CASE WHEN @OMCODLABORATORIO = HCCOM.CODOM THEN 1 ELSE 0 END LX
			, CASE WHEN @OMCODONCOLOGIA = HCCOM.CODOM THEN 1 ELSE 0 END ONCOLOGIA
			, CAST(IIF(COALESCE(USVGS.DATO,'') <> '', 1, 0)AS BIT) GESTION
			, CAST(CASE WHEN @OMCODCITADECONTROL = HCCOM.CODOM THEN 1 ELSE 0 END AS BIT) CITADECONTROL
			, VALIDAEXIST = CAST(IIF(UBEQ.MBODEGA = 1 AND IIF(TGEN.CODIGO=@CODIGO_MED,1,0)=1,1,0) AS BIT)
			, STAFF = CAST(IIF(HCCOM.CODOM = 'JM', 1, 0) AS BIT)
		INTO #HCCOM
		FROM TGEN 
			INNER JOIN	dbo.HCCOM ON dbo.TGEN.CODIGO = dbo.HCCOM.CODOM
			LEFT JOIN	USVGS ON IDVARIABLE='OMCODGESTION' AND DATO=TGEN.CODIGO
			LEFT JOIN	USUSU ON USUSU.USUARIO = @USUARIO
			LEFT JOIN	UBEQ ON UBEQ.SYS_ComputerName = USUSU.SYS_ComputerName
		WHERE TGEN.TABLA = 'HC_CODOM'
			AND NOT EXISTS (
				SELECT	B.DATO1
				FROM	TGEN B
				WHERE	B.TABLA ='EXCEPCION'
				AND		B.CAMPO = TGEN.CAMPO
				AND     B.CODIGO = @IDEMEDICA
			)
			AND	TGEN.CAMPO = @CLASEPLANTILLA
			--AND HCCOM.CODOM = IIF(@CLASEPROGRAMA='HD', @OMCODMOBILIARIO,HCCOM.CODOM) /* SE COMENTA PORQUE SE SOLICITA REQ PERO REALMENTE NO FUNCIONA ASÍ*/
		ORDER BY	TGEN.CAMPO, dbo.HCCOM.ORDEN

        CREATE TABLE #PROT (IDSERVICIO VARCHAR(20),DESCSERVICIO VARCHAR(256),ANOMAX VARCHAR(4), MESMAX VARCHAR(20),CODOM VARCHAR(10),CODOM_DESCRIPCION VARCHAR(50),MARCA BIT, FECHA DATETIME )
        
        INSERT INTO #PROT (IDSERVICIO ,DESCSERVICIO ,ANOMAX , MESMAX ,CODOM ,CODOM_DESCRIPCION ,MARCA , FECHA)
		SELECT DISTINCT CROVIGD.IDSERVICIO, SER.DESCSERVICIO, YEAR(CROVIGD.FECHAMAX) ANOMAX, DATENAME(MONTH,(CROVIGD.FECHAMAX)) MESMAX
			,(SELECT TOP 1 A.CODOM FROM HCCOM A INNER JOIN HCCOMD B ON A.CODOM=B.CODOM WHERE B.PREFIJO=SER.PREFIJO) AS CODOM
			,(SELECT TOP 1 A.DESCRIPCION FROM HCCOM A INNER JOIN HCCOMD B ON A.CODOM=B.CODOM WHERE B.PREFIJO=SER.PREFIJO) AS CODOM_DESCRIPCION
			,CAST (0 AS BIT) MARCA, CROVIGD.FECHAMAX
		FROM CROVIGD
			INNER JOIN SER ON CROVIGD.IDSERVICIO = SER.IDSERVICIO AND SER.PREFIJO IN(SELECT DATO FROM USVGS WHERE IDVARIABLE IN ('PREFIJOAPOYODX','PREFIJOLABORATORIO'))
			LEFT JOIN AFIPAT ON AFIPAT.IDCROVIG=CROVIGD.IDCROVIG
			LEFT JOIN PAT ON PAT.IDPATOLOGIA=AFIPAT.IDPATOLOGIA			
		WHERE CROVIGD.IDAFILIADO = @IDAFILIADO 
			AND CONVERT(DATE,CROVIGD.FECHAMAX) <= EOMONTH(GETDATE())
			AND CROVIGD.CUMPLIDA = 0 AND VISIBLE=1
        UNION ALL
		SELECT DISTINCT AFIPROT.IDSERVICIO, SER.DESCSERVICIO, YEAR(AFIPROT.F_DEFAULT) ANOMAX, DATENAME(MONTH,(AFIPROT.F_DEFAULT)) MESMAX
			,(SELECT TOP 1 A.CODOM FROM HCCOM A INNER JOIN HCCOMD B ON A.CODOM=B.CODOM WHERE B.PREFIJO=SER.PREFIJO) AS CODOM
			,(SELECT TOP 1 A.DESCRIPCION FROM HCCOM A INNER JOIN HCCOMD B ON A.CODOM=B.CODOM WHERE B.PREFIJO=SER.PREFIJO) AS CODOM_DESCRIPCION
			,CAST (0 AS BIT) MARCA, AFIPROT.F_DEFAULT
		FROM AFIPROT
            INNER JOIN SER ON SER.IDSERVICIO=AFIPROT.IDSERVICIO
		WHERE AFIPROT.IDAFILIADO=@IDAFILIADO AND CONVERT(DATE,AFIPROT.F_DEFAULT) <= EOMONTH(GETDATE())
		ORDER BY  FECHAMAX 


		SELECT * FROM #HCCOM
		SELECT * FROM #PROT
        DROP TABLE #PROT
		RETURN
	END
END







