IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_NOMINA' AND IDCONTROL='ConfigFmtCerLab')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO,IDCONTROL,DESCRIPCION,TIPO,WEB,RUTA,ICONO,CODIGOPADRE,AUTOMATICO,SEPARADOR,ORDEN,SUBLABEL,CODIGO,PAISES)
   SELECT 'MENUQ_NOMINA','ConfigFmtCerLab','Formatos Nomina','M',1,'nom.fmtCertilab','fa-solid fa-pen-fancy',NULL,0,0,925,'Certificados, Contratos',NULL,NULL
END
--SE DEBE AGREGAR AL DICCIONARIO DE NOMINA -->K3IX
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NCERTC'  AND   C.NAME = 'WEB')
BEGIN
   ALTER TABLE NCERTC  ADD WEB BIT 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'NCERTC'  AND   C.NAME = 'FORMATOWEB')
BEGIN
   ALTER TABLE NCERTC  ADD FORMATOWEB VARCHAR(MAX) 
END