IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_PAGOSCAJA_CIT' AND type = 'P')
   DROP PROCEDURE SPK_PAGOSCAJA_CIT

GO
CREATE  PROCEDURE DBO.SPK_PAGOSCAJA_CIT
@CONSECUTIVO VARCHAR(13),
@SYS_COMPUTERNAME VARCHAR(254),
@COMPANIA VARCHAR(2),
@SEDE VARCHAR(5),
@USUARIO VARCHAR(12),
@PART SMALLINT
WITH ENCRYPTION
AS  
DECLARE @OK         SMALLINT
DECLARE @PREFCAJA   SMALLINT
DECLARE @CODCAJA    VARCHAR(4)
DECLARE @NVOCONSEC  VARCHAR(20)
DECLARE @DATO       VARCHAR(80)
DECLARE @CNSACJ     VARCHAR(20)
DECLARE @TIPOCOPAGO VARCHAR(1)
DECLARE @CETIPOAUT  VARCHAR(80)
DECLARE @VAUX       DECIMAL(14,2)
DECLARE @DESCUENTO DECIMAL (14,2)
DECLARE @FACTURADA         SMALLINT
BEGIN
   PRINT 'ENTRE SPK_PAGOSCAJA_CIT @PART=' + str(@PART)
   SELECT   @OK = COUNT(*) FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND GENEROCAJA = 1
   SELECT  @DESCUENTO = COALESCE (DESCUENTO ,0), @FACTURADA=COALESCE(FACTURADA,0) FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO 

     
   IF @OK IS NULL
      SELECT @OK= 0  
      
   IF @OK > 0
      RETURN
      
   SELECT @CETIPOAUT = DATO FROM USVGS WHERE IDVARIABLE = 'CETIPOAUTORIZACION'
   
   IF @PART <> 1
   BEGIN
      SELECT @VAUX = VALORCOPAGO FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO 
      IF @VAUX IS NULL
         SELECT @VAUX = 0
      
      IF @VAUX = 0
         RETURN      
   END
   
   PRINT 'PASE'   
   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@TFCJ', @NVOCONSEC OUTPUT  
   SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0) 
   
   IF @PART = 0
   BEGIN
      PRINT 'NO ES PART'
      INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
                         IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,
                         CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,
                         SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME, OBSERVACION,IDSEDE)
      SELECT @NVOCONSEC, NULL,  'COBRO', @CONSECUTIVO, NULL, CIT.IDPLAN, (CIT.VALORCOPAGO -@DESCUENTO), @COMPANIA,
            AFI.IDAFILIADO,TIPO_DOC, 0, GETDATE(), 'CITAS', NULL, CIT.IDCONTRATANTE,LEFT(LTRIM(RTRIM(DBO.FNK_NOMBRE_AFI(CIT.IDAFILIADO))),40),  
             NULL, 'INTERNO', 0, 0, 0, 0, NULL, NULL, NULL, NULL, 'C', CIT.IDMEDICO,
           @USUARIO, @SYS_COMPUTERNAME, CIT.FECHA,CIT.IDSEDE
      FROM CIT, AFI
      WHERE CONSECUTIVO = @CONSECUTIVO
      AND CIT.IDAFILIADO = AFI.IDAFILIADO
      
      PRINT 'NVOCONSEC='+@NVOCONSEC

      SELECT @DATO=MOCC.CODIGOCPCJ
      FROM CIT INNER JOIN PPT ON CIT.IDTERCEROCA=PPT.IDTERCERO AND CIT.IDPLAN=PPT.IDPLAN
               LEFT  JOIN MOCC ON PPT.IDMODELOPCA=MOCC.IDMODELOPC
      WHERE CIT.CONSECUTIVO=@CONSECUTIVO
      
      IF COALESCE(@DATO,'')='' OR NOT EXISTS(SELECT * FROM CPCJ WHERE CODIGO=@DATO)
      BEGIN
         SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJMODE'  
      END
      
      INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                     TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
      SELECT NULL, @NVOCONSEC, 1,@DATO, NULL, CIT.VALORCOPAGO, 1, CIT.VALORCOPAGO,NULL, 0, 'N', 0, 0
      FROM CIT
      WHERE CONSECUTIVO = @CONSECUTIVO  

	  PRINT 'PROBLEMA ESTA AQUI'

	        
      SELECT  @DATO = DATO	  FROM USVGS WHERE IDVARIABLE = 'PREFIJOCITAS'                            
      INSERT INTO TFCJDD(CNSFACJ, ITEM, RENGLON, CODCAJA, PREFIJO, AREAFUNCIONAL, CCOSTO,
                         N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                         TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
      SELECT @NVOCONSEC, 1, 1, NULL, LEFT(@DATO,6), IDAREA, CCOSTO, NULL, NULL, VALORCOPAGO-@DESCUENTO, 1,
             VALORCOPAGO, NULL, NULL, NULL, NULL, NULL
      FROM CIT 
      WHERE CONSECUTIVO = @CONSECUTIVO
      UPDATE CIT SET GENEROCAJA = 1, NORECIBOCAJA = @NVOCONSEC, TIPOCAJA = 'TFCJ' 
      WHERE CONSECUTIVO = @CONSECUTIVO
      
   END
   ELSE
   BEGIN
      PRINT 'ES PART '
      SELECT @OK = ISNULL(NOCOBRAR ,0) FROM CIT WHERE  CONSECUTIVO = @CONSECUTIVO 
      IF @OK = 0
      BEGIN
		 IF DBO.FNK_VALORVARIABLE('GENERA_PAGO_PART_FAC')='SI' AND @FACTURADA=0 
			RETURN


         PRINT '@NVOCONSEC='+@NVOCONSEC
         INSERT INTO TFCJ(CNSFACJ, N_RECIBO, CLASE_FAC, NOADMISION, NOPRESTACION,
                          IDPLAN, VALORTOTAL, COMPANIA, IDAFILIADO,TIPO_DOC, CERRADA, FECHA, PROCEDENCIA, N_FACTURA, IDTERCERO, NOMBRECLIENTE,
                          CNSACJ, TIPO, ESTADO, IMPRESO, MARCACONT, CONTABILIZADA, NROCOMPROBANTE, AREAPRESTACION, CCOSTO,
                          SUBCCOSTO, CLASER, IDENTIFICADOR, USUARIO, SYS_COMPUTERNAME, OBSERVACION,IDSEDE)
         SELECT @NVOCONSEC, NULL,  'COBRO', @CONSECUTIVO, NULL, CIT.IDPLAN, CIT.VALORTOTAL -@DESCUENTO, @COMPANIA,
                AFI.IDAFILIADO,AFI.TIPO_DOC, 0, GETDATE(), 'CITAS', NULL, CIT.IDCONTRATANTE, LEFT(LTRIM(RTRIM(DBO.FNK_NOMBRE_AFI(CIT.IDAFILIADO))),40),  
                NULL, 'INTERNO', 0, 0, 0, 0, NULL, NULL, NULL, NULL, 'C', CIT.IDMEDICO,
                @USUARIO, @SYS_COMPUTERNAME, CIT.FECHA,CIT.IDSEDE
         FROM CIT, AFI
         WHERE CONSECUTIVO = @CONSECUTIVO
         AND CIT.IDAFILIADO = AFI.IDAFILIADO
         
         SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'IDCJPART'   
          
         INSERT INTO TFCJD(N_RECIBO, CNSFACJ, ITEM, CONCEPTO, AREAFUNCIONAL, VALORUNITARIO  , CANTIDAD, VALORTOTAL, IDSERVICIO,
                           TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
         SELECT NULL, @NVOCONSEC, 1, @DATO, NULL,CIT.VALORTOTAL-@DESCUENTO, 1,CIT.VALORTOTAL-@DESCUENTO,NULL, 0, 'N', 0, 0
         FROM CIT
         WHERE CONSECUTIVO = @CONSECUTIVO
         --SELECT  @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'PREFIJOCITAS'  
		 SELECT @DATO = (SELECT COALESCE(SER.PREFIJO,DBO.FNK_VALORVARIABLE('PREFIJOCITAS') ) FROM CIT INNER JOIN SER ON CIT.IDSERVICIO = SER.IDSERVICIO WHERE CIT.CONSECUTIVO = @CONSECUTIVO)
		
         INSERT INTO TFCJDD(CNSFACJ, ITEM, RENGLON, CODCAJA, PREFIJO, AREAFUNCIONAL, CCOSTO,
                             N_RECIBO, CONCEPTO, VALORUNITARIO, CANTIDAD, VALORTOTAL, IDSERVICIO,
                              TDESCUENTO, TIPODCTO, DCTO, VLRDESCUENTO)
         SELECT @NVOCONSEC, 1, 1, NULL, @DATO, IDAREA, CCOSTO, NULL, NULL, VALORTOTAL, 1,
                VALORTOTAL, NULL, NULL, NULL, NULL, NULL
         FROM CIT 
         WHERE CONSECUTIVO = @CONSECUTIVO
         
         UPDATE CIT SET GENEROCAJA = 1, NORECIBOCAJA = @NVOCONSEC, TIPOCAJA = 'TFCJ' 
         WHERE CONSECUTIVO = @CONSECUTIVO
         
      END      
   END
END





