CREATE OR ALTER PROCEDURE DBO.SPQ_CARTERA_RPT @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@N_FACTURA VARCHAR(20)             ,@CNSCXC VARCHAR(20)             ,@SQL VARCHAR(MAX)

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='TRAE_DETALLES'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA,@CNSCXC=CNSCXC        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA',
      CNSCXC  VARCHAR(20)   '$.CNSCXC'
      )
      SELECT 'OK'OK

      SELECT CNSCXC,OBSERVACION,USUSU.NOMBRE,DBO.FNK_FECHA_DDMMAA(FECHA)FECHA,PROCESO,
      MOTIVO1,MOTIVO2,COD_RESPUESTA,COD_REP1,COD_REP2
      FROM FCXCR INNER JOIN USUSU ON FCXCR.USUARIO=USUSU.USUARIO  
      WHERE N_FACTURA=@N_FACTURA

      SELECT CNSFNOT,DBO.FNK_FECHA_DDMMAA(F_NOTA)F_NOTA,CLASE,VR_TOTAL,PROCEDENCIA,OBSERVACION,ESTADO,
      CASE WHEN CERRADA=0 THEN 'Abierta'ELSE 'Aplicada'END APLICADA,NROCOMPROBANTE
      FROM FNOT 
      WHERE N_fACTURA=@N_FACTURA

      SELECT FPAG.CNSFPAG,DBO.FNK_FECHA_DDMMAA(FPAG.FECHAPAGO)FECHAPAGO,FPAG.INGRESO,FPAG.NROCOMPROBANTE,
      FPAGD.VLRFACTURA,FPAGD.VLRGLOSA,FPAGD.VLRIMPUESTO,FPAGD.VALORPAGO,FPAGD.CLASE,CASE WHEN FPAG.CERRADO=1 THEN 'Aplicado' ELSE 'Abierto' END CERRADO,
      DBO.FNK_FECHA_DDMMAA(FPAG.FECHA)FECHA,USUSU.NOMBRE,FPAGD.CNSGLO
      FROM FPAGD INNER JOIN FPAG ON FPAGD.CNSFPAG=FPAG.CNSFPAG
                 INNER JOIN USUSU ON FPAG.USUARIO=USUSU.USUARIO
      WHERE FPAGD.N_FACTURA=@N_FACTURA

      SELECT FGLO.CNSGLO,DBO.FNK_FECHA_DDMMAA(FPAG.FECHA)FECHA,FGLO.TIPO,CASE WHEN FGLO.CERRADA=1 THEN 'Cerrada' ELSE 'Abierta' END CERRADA,
      FGLO.VLRGLOSA,FGLO.VLRACEPTADO,FGLO.VLRRECUPERAR,DBO.FNK_FECHA_DDMMAA(FGLO.FECHARESP)FECHARRESP,FGLO.CNSGLOI,
      DBO.FNK_FECHA_DDMMAA(FGLOI.FECHA)FIMPRESION,FGLOI.RADICADO,DBO.FNK_FECHA_DDMMAA(FGLOI.FECHARAD)FECHARAD,FGLO.CNSFNOT,
      DBO.FNK_RTF(FGLO.OBSERVACION)OBSERVACION,DBO.FNK_RTF(FGLO.OBSERVACIONRTA)OBSERVACIONRTA,FGLO.NROCOMPROBANTE
      FROM FGLO LEFT JOIN FGLOI ON FGLO.CNSGLOI=FGLOI.CNSGLOI
                LEFT JOIN FPAG ON FGLO.CNSFPAG=FPAG.CNSFPAG
      WHERE FGLO.N_FACTURA=@N_FACTURA


      SELECT FCONCI.IDFCONCI,DBO.FNK_FECHA_DDMMAA(FCONCI.FECHACONC)FECHACONC,FCONCI.ESTADO,FCONCID.ITEM_FCONCID,FCONCID.ITEM_FCXCDV,FCONCID.SALDONETO,FCONCID.VLRACEPTADO,
      FCONCID.VLRRECUPERAR,FCONCID.OBSERVACION,DBO.FNK_FECHA_DDMMAA(FCONCI.FECHADIG)FECHADIG
      FROM FCONCID INNER JOIN FCONCI ON FCONCID.IDFCONCI=FCONCID.IDFCONCI
      WHERE FCONCID.N_FACTURA=@N_FACTURA

      RETURN
      
   END 
   IF @METODO='RELIQUIDA_FTR'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA,@CNSCXC=CNSCXC        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA',
      CNSCXC  VARCHAR(20)   '$.CNSCXC'
      )  
      BEGIN TRY           
         EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='TRAER_TTEC'     
   BEGIN    
      SELECT 'OK'OK
      SELECT  TIPO AS value,DETALLE as label
      FROM TTEC 
   END 
   IF @METODO='TRAER_TOTAL1'     
   BEGIN         
      SELECT @DATOS=WHEREF        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      WHEREF  VARCHAR(MAX)   '$.WHEREF'
      )
      --SELECT @DATOS=REPLACE(@DATOS,'''','''''')
      SELECT 'OK'OK
       SELECT @SQL=' SELECT SUM(SALDOTOT)SALDOTOT,SUM(PORVENCER)PORVENCER, SUM(SALDO_0_30)SALDO_0_30,SUM(SALDO_31_60)SALDO_31_60, SUM(SALDO_61_90)SALDO_61_90, 
         SUM(SALDO_91_120)SALDO_91_120, SUM(SALDO_121_150)SALDO_121_150, SUM(SALDO_151_180)SALDO_151_180,SUM(SALDO_181_360)SALDO_181_360,
         SUM(SALDO_361_MAS)SALDO_361_MAS,SUM(NORADICADA)NORADICADA   
         FROM [dbo].[VWK_VCTOS] INNER JOIN  TER ON VWK_VCTOS.IDTERCERO=TER.IDTERCERO 
         WHERE '+@DATOS 
         
      PRINT @SQL
      EXEC(@SQL)
      RETURN
   END 
   IF @METODO='EXPORT_DETA'     
   BEGIN         
      SELECT @DATOS=WHEREF        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      WHEREF  VARCHAR(MAX)   '$.WHEREF'
      )
      SELECT 'OK'OK
      SELECT @SQL='SELECT ANO, MES, B.NIT ,B.RAZONSOCIAL, CNSCXC, N_FACTURA, ITEM, CNSGLO, TIPO, SALDONETO, DBO.FNK_FECHA_DDMMAA(FECHA)FECHA,DBO.FNK_FECHA_DDMMAA(F_VENCE)F_VENCE,DBO.FNK_FECHA_DDMMAA(F_RECIBIDO)F_RECIBIDO, SALDOINICIAL, MARCAPAGO, DIASVENCE, 
         PORVENCER, DM361_MAS, DM181_360, DM151_180, DM121_150,  DM91_120, DM61_90, DM31_60, DM0_30, D0_30, D31_60, D61_90, D91_120, D121_150, D151_180, D181_360, D361_MAS,
         PROCEDENCIA, IDPLAN, NORADICADA, PARTICULAR, RAD, REGIMEN, TIPOTTEC,  CLASEINFO
         FROM VWK_CXCDIASVTO A INNER JOIN TER B ON A.IDTERCERO=B.IDTERCERO
         WHERE '+@DATOS 
         
      PRINT @SQL
      EXEC(@SQL)               
      RETURN
   END  
END