IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_ADMINISTRATIVO' AND IDCONTROL='PASARELAIZI')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_ADMINISTRATIVO', 'PASARELAIZI', 'P', 'Pasarela de pagos Izipay', 1, 'admin.pasaizipay', 'fa-solid fa-money-bill-transfer', NULL, 0, 0, 20, 'Seguimiento,Link Pago', NULL, NULL
END