IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_COPIA_HC_QX' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_COPIA_HC_QX
END
GO
CREATE PROCEDURE DBO.SPK_COPIA_HC_QX 
@NOADMISIONORI VARCHAR(16),
@CONSECUTIVO   VARCHAR(13), 
@NOADMISIONDES VARCHAR(16),    
@USUARIO       VARCHAR(12),
@COMPANIA      VARCHAR(2),
@SEDE          VARCHAR(5), 
@ITEMRED       INT = NULL,
@CLASECOPIA    VARCHAR(1) = '1',
@SERVERBDIX    VARCHAR(40) = NULL,
@COMPANIAREAL  VARCHAR(2) = '01'
WITH ENCRYPTION
AS
DECLARE @NVOCONSEC          VARCHAR(20)
DECLARE @NVOCONSECUTIVOHCA  VARCHAR(20)
DECLARE @NVOCONSECUTIVONHI  VARCHAR(20)
DECLARE @IDAFILIADO         VARCHAR(20)
DECLARE @IDMEDICO           VARCHAR(12)
DECLARE @CLASEPLANTILLAHRED VARCHAR(20)
DECLARE @NVOITEMRED         INT
DECLARE @SERVIDOR_DBLOG     NVARCHAR(50) 
DECLARE @DB_LOG             NVARCHAR(50) 
DECLARE @LINEA              VARCHAR(4000)
DECLARE @HC TABLE (ID INT IDENTITY, CONSECUTIVO VARCHAR(20))
DECLARE @I INT, @I_TO INT
DECLARE @EPI VARCHAR(20)=DBO.FNK_VALORVARIABLE('HCPLANTILLAEPI')
BEGIN
    IF @CLASECOPIA = '1'
    BEGIN
        IF (SELECT COUNT(*) FROM HCA WHERE CONSECUTIVO = @CONSECUTIVO ) = 0
        BEGIN
            RAISERROR('No existe HC',16,1)
            RETURN
        END
    END
    IF (SELECT COUNT(*) FROM HADM WHERE NOADMISION  = @NOADMISIONDES ) = 0
    BEGIN
        RAISERROR('No existe admision destino',16,1)
        RETURN
    END

    SELECT @IDAFILIADO=IDAFILIADO FROM HADM WHERE NOADMISION=@NOADMISIONDES

    IF @CLASECOPIA = '1'
        INSERT INTO @HC (CONSECUTIVO)
        SELECT @CONSECUTIVO
    ELSE
        INSERT INTO @HC (CONSECUTIVO)
        SELECT CONSECUTIVO FROM HCA 
        WHERE NOADMISION=@NOADMISIONORI AND PROCEDENCIA='QX' AND CLASEPLANTILLA<>@EPI

    SELECT @I=1, @I_TO=MAX(ID) FROM @HC
    
    WHILE @I<=@I_TO
    BEGIN 
        SELECT @CONSECUTIVO=CONSECUTIVO FROM @HC WHERE ID=@I
    
        SELECT @NVOITEMRED = MAX(ITEMRED) FROM HCA WHERE NOADMISION=@NOADMISIONDES

        SET @NVOITEMRED = ISNULL(@NVOITEMRED,0)+1

        EXEC SPK_GENCONSECUTIVO '01', @SEDE,'@HC',@NVOCONSECUTIVOHCA OUTPUT  
        SELECT @NVOCONSECUTIVOHCA = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSECUTIVOHCA))+LTRIM(RTRIM(@NVOCONSECUTIVOHCA)),SPACE(1),0)
    
        INSERT INTO HCA (
            CONSECUTIVO, CLASEPLANTILLA, FECHA, IDMEDICO, IDAFILIADO, NOADMISION, IDDX, TIPODX, IMPRESO, EDAD, FINALIDAD, 
            DX1, DX2, DX3, IDMEDICODILIGENCIA, IDDXEG, N_HISTORIA, PROCEDENCIA, REVISAESP, IDMEDICOESP, PIDEDX,
            PIDESV, TAS, TAD, FC, FR, TEMP, TALLA, PULSO, PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, 
            ITEMHADM, IDAREA, ANULADA, USUARIOANU, FECHA_ANU, OBSERVAANU, AMBITO, MED_ESPEC, CAUSA_EXT, SINCRONIZADO,
            IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, ITEMRED, PLANDEMANEJO, RESUMEN, EVOLSUB, ANALISIS,
            ESTANCIA, RESPARACLINI, JUSTESTANCIA, TAM, SOAT, BOLO, DIURESIS, CNSNESIGVIT_SV, CNSNESIGVIT_GC, 
            CNSNESIGVIT_GA, TIPOSV, PLANDEMANEJOMED, CONSECUTIVO_RED_ORI, ITEMRED_RED_ORI, CNSNESIGVIT_GV, CNSNESIGVIT_PV,
            CNSNESIGVIT_IO, TIPOPM, COPIADA, CONSECUTIVOCOPIA
        )
        SELECT 
            @NVOCONSECUTIVOHCA, CLASEPLANTILLA, FECHA, IDMEDICO, @IDAFILIADO, @NOADMISIONDES, IDDX, TIPODX, IMPRESO, EDAD, FINALIDAD, 
            DX1, DX2, DX3, IDMEDICODILIGENCIA, IDDXEG, N_HISTORIA, PROCEDENCIA, REVISAESP, IDMEDICOESP, PIDEDX,
            PIDESV, TAS, TAD, FC, FR, TEMP, TALLA, PULSO, PESO, GLASGOW, TIPOGLASGOW, HIDRATACION, ALTA, CLASE, 
            ITEMHADM, IDAREA, ANULADA, USUARIOANU, FECHA_ANU, OBSERVAANU, AMBITO, MED_ESPEC, CAUSA_EXT, SINCRONIZADO,
            IDPLAN, CCOSTO, ENEPICRISIS, CERRADA, EVOLUCION, @NVOITEMRED, PLANDEMANEJO, RESUMEN, EVOLSUB, ANALISIS,
            ESTANCIA, RESPARACLINI, JUSTESTANCIA, TAM, SOAT, BOLO, DIURESIS, CNSNESIGVIT_SV, CNSNESIGVIT_GC, 
            CNSNESIGVIT_GA, TIPOSV, PLANDEMANEJOMED, CONSECUTIVO_RED_ORI, ITEMRED_RED_ORI, CNSNESIGVIT_GV, CNSNESIGVIT_PV,
            CNSNESIGVIT_IO, TIPOPM, 1, @CONSECUTIVO
        FROM HCA WHERE CONSECUTIVO=@CONSECUTIVO

        --HCAD
        INSERT INTO HCAD(
            CONSECUTIVO, CLASEPLANTILLA, CAMPO, SECUENCIA, NADA, NORMAL, ANORMAL, DETALLAR, NOTAS, TIPOCAMPO, ALFANUMERICO,
            FECHA, MEMO, OBS, LISTA, ENEPICRISIS, SINCRONIZADO, MINIMO, MAXIMO, PROMEDIO, VALORGRAFICA
        )
        SELECT 
            @NVOCONSECUTIVOHCA, CLASEPLANTILLA, CAMPO, SECUENCIA, NADA, NORMAL, ANORMAL, DETALLAR, NOTAS, TIPOCAMPO, ALFANUMERICO,
            FECHA, MEMO, OBS, LISTA, ENEPICRISIS, SINCRONIZADO, MINIMO, MAXIMO, PROMEDIO, VALORGRAFICA
        FROM HCAD WHERE CONSECUTIVO=@CONSECUTIVO

        PRINT'--HCADL'
        INSERT INTO HCADL(CONSECUTIVO, SECUENCIA, ITEM, VALORLISTA, CHECKM, DESCRIPCION, SINCRONIZADO)
        SELECT @NVOCONSECUTIVOHCA, SECUENCIA, ITEM, VALORLISTA, CHECKM, DESCRIPCION, SINCRONIZADO
        FROM HCADL WHERE CONSECUTIVO=@CONSECUTIVO

        PRINT'--HCATD'
        INSERT INTO HCATD(
            CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, APLICADA, CONSECUTIVONE,
            NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION, TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR , CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO,
            OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI)
        SELECT 
            @NVOCONSECUTIVOHCA, @NVOITEMRED, CODOM, IDSERVICIO, CANTIDAD, IDTIPOCONC, VIA, OBSERVACION, CLASE, ENCARGOS, NOPRESTACION, APLICADA, CONSECUTIVONE,
            NOITEM, NOINGRESO, NORDEN, FRECUENCIA, DURACION, TIPO, AVISADOENF, FECHAGA, IDPROVEEDOR , CANTIDADNOCC, CNSHJNOPOS, DESCRIPTIVA, DESTINO,
            OBSDESCRIPTIVA, CANTIDADINV, IDPERFIL, COPIADO, CANTIDADBOLO, PRIMER, CANTIDADORI
        FROM HCATD WHERE CONSECUTIVO=@CONSECUTIVO
        
        INSERT INTO HCATDH (CONSECUTIVO, ITEMRED, CODOM, IDSERVICIO, HORA, CANTIDAD, IDSERVICIOD)
        SELECT @NVOCONSECUTIVOHCA, @NVOITEMRED, CODOM, IDSERVICIO, HORA, CANTIDAD, IDSERVICIOD
        FROM HCATDH WHERE CONSECUTIVO=@CONSECUTIVO

        --HCASER
        INSERT INTO HCASER(CONSECUTIVO, IDSERVICIO, CANTIDAD, NOPRESTACION, NOITEM_HPRED, AUTOMATICO)
        SELECT @NVOCONSECUTIVOHCA, IDSERVICIO, CANTIDAD, NOPRESTACION, NOITEM_HPRED, AUTOMATICO
        FROM HCASER WHERE CONSECUTIVO=@CONSECUTIVO
        
        --HCAPM
        INSERT INTO HCAPM (CONSECUTIVO, ORDEN, CLASE, OBSERVACION, IDSERVICIO,CLAMED,SECOPIA)
        SELECT @NVOCONSECUTIVOHCA, ORDEN, CLASE, OBSERVACION, IDSERVICIO,CLAMED,SECOPIA
        FROM HCAPM WHERE CONSECUTIVO=@CONSECUTIVO
        
        --HJNOPOS
        INSERT INTO HJNOPOS (
            CNSHJNOPOS, NOADMISION, CONSECUTIVOHCA, ITEMRED, CODOM, IDSERVICIO, OBSERVACION, IDSERVICIOPOS1, NOMGENERICO1, PRESENTACION1, DOSISFRECU1, IDSERVICIOPOS2, NOMGENERICO2, PRESENTACION2, 
            DOSISFRECU2, IDSERVICIOPOS3, NOMGENERICO3, PRESENTACION3, DOSISFRECU3, IDSERVICIOPOS4, NOMGENERICO4, PRESENTACION4, DOSISFRECU4, RAZONNOFORMPOS, IDDX, RESUMENHIST, JUSTYPERTUSO, 
            SOPCIENTBIBLI, DOSIS, FRECUENCIA, DURACION, TOTALREQ, CANTIDADNOCC, CANTIDADINV, ESTADO, ORDENADOS, FALTAN, DIASTTO1, DIASTTO2, DIASTTO3, DIASTTO4, CANTMES1, CANTMES2, CANTMES3, 
            CANTMES4, POSOLOGIA, POSOLOGIA1, POSOLOGIA2, POSOLOGIA3, POSOLOGIA4, REGINVIMA, DOSISIMPREG, DURACIONIMPREG, TIPODURACIONTRAT, NUMAUTORIZA
        )
        SELECT 
            CNSHJNOPOS+'-'+CONVERT(VARCHAR(5),@NVOITEMRED), @NOADMISIONDES, @NVOCONSECUTIVOHCA, @NVOITEMRED, CODOM, IDSERVICIO, OBSERVACION, IDSERVICIOPOS1, NOMGENERICO1, PRESENTACION1, DOSISFRECU1, IDSERVICIOPOS2, NOMGENERICO2, PRESENTACION2, 
            DOSISFRECU2, IDSERVICIOPOS3, NOMGENERICO3, PRESENTACION3, DOSISFRECU3, IDSERVICIOPOS4, NOMGENERICO4, PRESENTACION4, DOSISFRECU4, RAZONNOFORMPOS, IDDX, RESUMENHIST, JUSTYPERTUSO, 
            SOPCIENTBIBLI, DOSIS, FRECUENCIA, DURACION, TOTALREQ, CANTIDADNOCC, CANTIDADINV, ESTADO, ORDENADOS, FALTAN, DIASTTO1, DIASTTO2, DIASTTO3, DIASTTO4, CANTMES1, CANTMES2, CANTMES3, 
            CANTMES4, POSOLOGIA, POSOLOGIA1, POSOLOGIA2, POSOLOGIA3, POSOLOGIA4, REGINVIMA, DOSISIMPREG, DURACIONIMPREG, TIPODURACIONTRAT, NUMAUTORIZA
        FROM HJNOPOS WHERE CONSECUTIVOHCA=@CONSECUTIVO

        INSERT INTO HCAAPD (CNSHCAAP, FINGRESO, CONSECUTIVOHCA, ANTECEDENTE, NUMERICO, FECHA, CNSTGANTOP, ORDEN)
        SELECT CNSHCAAP, FINGRESO, @NVOCONSECUTIVOHCA, ANTECEDENTE, NUMERICO, FECHA, CNSTGANTOP, ORDEN
        FROM HCAAPD WHERE CONSECUTIVOHCA=@CONSECUTIVO

        INSERT INTO HCACP (CONSECUTIVO, CAMPO, ITEM, CLASE, IDMEDICO, FECHA, NOADMISION, DATOX, DATOY, NOTA1, NOTA2)
        SELECT @NVOCONSECUTIVOHCA, CAMPO, @NVOITEMRED, CLASE, IDMEDICO, FECHA, NOADMISION, DATOX, DATOY, NOTA1, NOTA2
        FROM HCACP WHERE CONSECUTIVO=@CONSECUTIVO

        INSERT INTO HCACPH (CONSECUTIVO, CAMPO, ITEM, CLASE, IDMEDICO, FECHA, NOADMISION, DATOX, DATOY, NOTA1, NOTA2)
        SELECT @NVOCONSECUTIVOHCA, CAMPO, @NVOITEMRED, CLASE, IDMEDICO, FECHA, NOADMISION, DATOX, DATOY, NOTA1, NOTA2
        FROM HCACPH WHERE CONSECUTIVO=@CONSECUTIVO

        INSERT INTO HCASV (CONSECUTIVO, CODIGOSV, GRUPO, DATO, CLASESV, VALOR, SINCRONIZADO, ORDENSV)
        SELECT @NVOCONSECUTIVOHCA, CODIGOSV, GRUPO, DATO, CLASESV, VALOR, SINCRONIZADO, ORDENSV
        FROM HCASV WHERE CONSECUTIVO=@CONSECUTIVO

        INSERT INTO HCADX (CONSECUTIVO, IDDX, TIPO, ESTADO, TIPODX)
        SELECT @NVOCONSECUTIVOHCA, IDDX, TIPO, ESTADO, TIPODX
        FROM HCADX WHERE CONSECUTIVO=@CONSECUTIVO

        IF DBO.FNK_VALORVARIABLE('TIPOHTX')<>'HORIZONTAL'
        BEGIN
            --HTX
            INSERT INTO HTX (
                CNSHTX, CONSECUTIVOHCA, CODOM, ITEMRED, TIPOHISTORIA, IDSERVICIO, CANTIDAD, FECHAORDEN, IDTIPOCONC, VIA, FECHAREQ,
                CLASE, TIPO, IDENFERMERIA, FECHAAPLI, SOLICITADO, APLICADO, ENCARGOS, CNSMOV, NOPRESTACION, NOITEM, NOADMISION,
                ESTADO, CCOSTO, IDAREA, LISTOENTREGA, FECHALE, ENTREGADO, FECHAENTREGA, USUARIOENTREGA, CONSECUTIVORED, 
                IDFUNCIONARIORECIBE, APROBADO, PEDIRINV, CARGOGENERADO, USUARIOPIDEI, FECHAPIDEI, TTOTRAIDOAFI, USUARIORECIBE,
                CNSHBLIQ, CANTIDADAPLI, FECHASUSPEN, SUSPENDER, OBSERVACIONES, NOCOBRAR, IDPAQUETE, REQUISICION, TIPOREQ, MARCAINV,
                MARCADEV, INDDEV, CNSMOVDEV, CLASEHTX, MDOSIF, EQUICC, QDOSIS, TIPOGCC, HOST_MPEDINV, HOST_MDEVINV, HOST_APLICA,
                CANTIDADNOCC, ANULADA, CLASEANULA, USUARIOANULA, CLASEANUINV, CANTIDAD_CARGOS, CCFALT_LOCARGADO, FALTANCARGAR,
                CCDESECHADOS, CANTIDADDEV, CANTIDADINV, FFINESTAB, CNSHDUXS, CNSHDUXS2, CNSDIRINV, ANT_UNICOMP, ANT_CC, GENINV,
                IDARTICULO
            )
            SELECT 
                CNSHTX+ '-'+ CONVERT(VARCHAR,ROW_NUMBER() OVER(ORDER BY FECHAORDEN) ), @NVOCONSECUTIVOHCA, CODOM, ITEMRED, 
                TIPOHISTORIA, IDSERVICIO, CANTIDAD, FECHAORDEN, IDTIPOCONC, VIA, FECHAREQ,
                CLASE, TIPO, IDENFERMERIA, FECHAAPLI, SOLICITADO, APLICADO, ENCARGOS, CNSMOV, NOPRESTACION, NOITEM, @NOADMISIONDES,
                ESTADO, CCOSTO, IDAREA, LISTOENTREGA, FECHALE, ENTREGADO, FECHAENTREGA, USUARIOENTREGA, CONSECUTIVORED, 
                IDFUNCIONARIORECIBE, APROBADO, PEDIRINV, CARGOGENERADO, USUARIOPIDEI, FECHAPIDEI, TTOTRAIDOAFI, USUARIORECIBE,
                CNSHBLIQ, CANTIDADAPLI, FECHASUSPEN, SUSPENDER, OBSERVACIONES, NOCOBRAR, IDPAQUETE, REQUISICION, TIPOREQ, MARCAINV,
                MARCADEV, INDDEV, CNSMOVDEV, CLASEHTX, MDOSIF, EQUICC, QDOSIS, TIPOGCC, HOST_MPEDINV, HOST_MDEVINV, HOST_APLICA,
                CANTIDADNOCC, ANULADA, CLASEANULA, USUARIOANULA, CLASEANUINV, CANTIDAD_CARGOS, CCFALT_LOCARGADO, FALTANCARGAR,
                CCDESECHADOS, CANTIDADDEV, CANTIDADINV, FFINESTAB, CNSHDUXS, CNSHDUXS2, CNSDIRINV, ANT_UNICOMP, ANT_CC, GENINV,
                IDARTICULO
            FROM HTX WHERE CONSECUTIVOHCA=@CONSECUTIVO
        END

        /* --Se retira envio a USLOG ya que ni funcionaba además de estar consumiendo muchos recursos
        PRINT 'LOG DE AUDITORIA....'
        EXEC SPK_RETURN_KIXLOG @SERVERBDIX, @COMPANIAREAL, @SERVIDOR_DBLOG OUTPUT, @DB_LOG OUTPUT
        PRINT '@DB_LOG='+COALESCE(@DB_LOG,'NO HAY BASE')
        EXEC SPK_GENCONSECUTIVO @COMPANIA, @SEDE, '@USLOG',  @NVOCONSEC OUTPUT  
        SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
        PRINT 'INSERT LOG--- @NVOCONSEC='+@NVOCONSEC
        SELECT @LINEA = ' INSERT INTO ['+@SERVIDOR_DBLOG+'].['+@DB_LOG+'].DBO.USLOG (CNSLOG, COMPANIA, NOADMISION, PROCESO, REQUEST, REFERENCIA, USUARIO, FECHA, SYS_COMPUTERNAME) 
                            SELECT '''+@NVOCONSEC+''', '''+@COMPANIA+''', '''+@NOADMISIONDES+''', ''COPIA_HC'', ''COPY'', '''+ @NVOCONSECUTIVOHCA+''', '''+@USUARIO+''',  '''+ 
                            CONVERT(VARCHAR(30), GETDATE(),103)+ ' '+ CONVERT(VARCHAR(30), GETDATE(),114)+ ''', '''+ HOST_NAME()+''''
        EXEC(@LINEA)
        PRINT 'INSERTO EL DETALLE'
        SELECT @LINEA= ' INSERT INTO ['+@SERVIDOR_DBLOG+'].['+@DB_LOG+'].DBO.USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO )
                            SELECT '''+@NVOCONSEC+''', 1, ''NOADMISION:ORI->>DES'', '''+@NOADMISIONORI+''', '''+ @NOADMISIONDES + ''''
        EXEC(@LINEA) 
        SELECT @LINEA = ' INSERT INTO ['+@SERVIDOR_DBLOG+'].['+@DB_LOG+'].DBO.USLOGH( CNSLOG, ITEM, CAMPO, VALORANT, VALORNVO )
                            SELECT '''+@NVOCONSEC+''', 2, ''CONSECUTIVO:ORI->>DES'', '''+@CONSECUTIVO+''', '''+ @NVOCONSECUTIVOHCA + ''''
        EXEC(@LINEA) 
        */
    
        SET @I+=1
    END   
    DELETE @HC
END

