IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='CODCUMS_FIJO')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'CODCUMS_FIJO','Toma el Codcum Fijo de un Campo SER.CODCUM,IART.CODCUM,SER.SISRPO','Alfanumerica',''
END
IF NOT EXISTS(SELECT * FROM USVGS WHERE IDVARIABLE='URL_SERV_RIPS_PRUEBA')
BEGIN   
   INSERT INTO USVGS (IDVARIABLE,DESCRIPCION,TP_VARIABLE,DATO)
   SELECT 'URL_SERV_RIPS_PRUEBA','URL SERVIDOR DOCKER DE RIPS Pruebas ','Alfanumerica','https://fevrips-test.qrystalos.com/'
END