IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_NC_CONTAB_CXPFNT' AND XTYPE='P')
BEGIN
   DROP PROCEDURE SPK_NC_CONTAB_CXPFNT
END

GO
CREATE PROCEDURE DBO.SPK_NC_CONTAB_CXPFNT 
	@CNSFCXP             VARCHAR(20),
        @ITEM                INT,
	@USUARIO             VARCHAR(12),
	@SYS_COMPUTERNAME    VARCHAR(254),
	@COMPANIA            VARCHAR(2),
	@SEDE                VARCHAR(5),
	@NROCOMPROBANTE      VARCHAR(20) 
WITH ENCRYPTION
AS
 DECLARE @NOREFERENCIA    VARCHAR(20)
 DECLARE @MAUX		        VARCHAR(20)
 DECLARE @ANO		        VARCHAR(4)
 DECLARE @MES		        INT
 DECLARE @REFERENCIA_PRO  VARCHAR(20)
 DECLARE @PROCEDENCIA	  VARCHAR(10)
 DECLARE @COM             VARCHAR(2)  
 DECLARE @PREFIJO_USCXS   VARCHAR(10)
 DECLARE @FECHACONTABLE   DATETIME
 DECLARE @ESTADO          VARCHAR(1)
 DECLARE @VALORPAGO       DECIMAL(14,2)
 DECLARE @IDTERCERO       VARCHAR(20)
 DECLARE @N_FACTURA       VARCHAR(20)
 DECLARE @F_FACTURA       DATETIME
 DECLARE @F_VENCE         DATETIME
 DECLARE @GIMPUESTOS      TINYINT
 DECLARE @IDAREA          VARCHAR(20)
 DECLARE @CCOSTO          VARCHAR(20)
 DECLARE @TIPOMOV         VARCHAR(5)
 DECLARE @IDMODELOCONT    VARCHAR(10)
 DECLARE @CUENTACR        VARCHAR(16)
 DECLARE @CUENTAAUX       VARCHAR(16)
 DECLARE @CNSMOVANT       VARCHAR(20)
 DECLARE @VALOR_REAL      DECIMAL(14,2)
 DECLARE @VALOR_REALIVA   DECIMAL(14,2)
 DECLARE @VLR_IVA         DECIMAL(14,2)
 DECLARE @TIPO            VARCHAR(2)
 DECLARE @CNSMOVDEV       VARCHAR(20)
 DECLARE @VALORCALCULO    DECIMAL(14,2)
 DECLARE @IVACALCULO      DECIMAL(14,2)
 DECLARE @CAMTER          TINYINT
 DECLARE @GENCXP          TINYINT
 DECLARE @TIENEIVA        DECIMAL(14,2)
 DECLARE @TER_AUTORE      INT
 DECLARE @T_IMPUESTO      DECIMAL(14,2) 
 DECLARE @GIVA            SMALLINT 
 DECLARE @VLRRETIVA       DECIMAL(14,2)
 DECLARE @FACT_RETEIVA    DECIMAL(14,2)
 DECLARE @VDB		      DECIMAL(14,2)
 DECLARE @VCR			  DECIMAL(14,2)
 DECLARE @VIMP			  DECIMAL(14,2)
 DECLARE @VFNOT           DECIMAL(14,2)
 DECLARE @IVA           DECIMAL(7,2)
 DECLARE @CUENTAIVAX    VARCHAR(20)
 DECLARE @VLRPROAUDT DECIMAL(14,2)
BEGIN
   SELECT * INTO #T  FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM 
   SELECT @GIMPUESTOS = GIMPUESTOS, @CAMTER = CAMTER, @GENCXP = GENCXP, @GIVA = COALESCE(GIVA, 0) FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM 
   SET @REFERENCIA_PRO = @CNSFCXP
   SELECT 
   @ESTADO         = #T.ESTADO,
   @ANO            = YEAR(#T.FECHA),
   @MES            = MONTH(#T.FECHA),
   @FECHACONTABLE  = #T.FECHA,
   @VALORPAGO      = #T.VALOR,
   @COM            = FNT.COMPROBANTE,
   @IDTERCERO      = FCXP.IDTERCERO,
   @PROCEDENCIA    = COALESCE(#T.PROCEDENCIA,''),
   @N_FACTURA      = #T.N_FACTURA,
   @CUENTACR       = FCXP.CUECREDITO,
   @TIPO           = #T.TIPO,  
   @CUENTAIVAX     = #T.CUENTA_CR
   FROM #T INNER JOIN FNT  ON #T.IDNOTA  = FNT.IDNOTA 
          INNER JOIN FCXP ON #T.CNSFCXP = FCXP.CNSFCXP
  
  PRINT 'ESTA ES LA PROCEDENCIA:'+@PROCEDENCIA
  PRINT 'ESTA ES LA FACTURA: ' +@N_FACTURA   
  SELECT @IDMODELOCONT= DBO.FNK_VALORVARIABLE('IDMODELOCONTABLE')
  PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
  PRINT '@TIPO = '+@TIPO

  IF(@PROCEDENCIA='AUDT')
  BEGIN 
    SET @VLRPROAUDT = ( SELECT CASE WHEN COALESCE(VLR_NETO,0) =0 THEN VALOR ELSE CASE WHEN VALOR> VLR_NETO THEN VALOR ELSE VLR_NETO END END  FROM FCXPDBCR WHERE CNSFCXP=@CNSFCXP AND ITEM=@ITEM)
	
  END
   IF (SELECT COUNT(*) FROM TER WHERE COALESCE(TIPOREGIMEN, '') = 'C' AND COALESCE(AUTORETENEDOR, 0) = 1 AND IDTERCERO = @IDTERCERO) > 0
      BEGIN
         SELECT @TER_AUTORE = 1
         SELECT @T_IMPUESTO = COALESCE(SUM(VALORIMP), 0) FROM FCXPI WHERE CNSFCXP = @CNSFCXP AND IDIMPUESTO <> (SELECT DBO.FNK_VALORVARIABLE('IDIMP_RETEIVA'))

      END
   ELSE
   BEGIN
      SELECT @TER_AUTORE = 0
   END
   IF @PROCEDENCIA <> 'INV'
   BEGIN
      IF @GIVA =1 AND (SELECT SUM(VLR_IVA) FROM FCXPD WHERE CNSFCXP=@CNSFCXP AND VLR_IVA>0)>0
      BEGIN
         SELECT @IVA=MAX(ROUND(((VLR_IVA*100 )/VLR_NETO),0)) FROM FCXPD WHERE CNSFCXP=@CNSFCXP AND VLR_IVA>0
         SELECT @TIENEIVA = COALESCE(ROUND(FCXPDBCR.VALOR*(@IVA/100.00), 0), 0) FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM
         SELECT @VALOR_REAL = COALESCE(ROUND(FCXPDBCR.VLR_NETO, 0), 0) FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM
      END
      ELSE
      BEGIN
	  PRINT 'ENTRE AQUI VALOR REAL ES VLRNETO Y PROCEDENCIA DIFERENTE DE INV'
	      SELECT @TIENEIVA = 0
         SELECT @VALOR_REAL = COALESCE(ROUND(FCXPDBCR.VLR_NETO, 0), 0) FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM
      END
      SELECT @VALOR_REALIVA = COALESCE(FCXPDBCR.VALORIVA, 0)  FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM
  END


  IF ISNULL(@NROCOMPROBANTE,'') = '' -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
  BEGIN
     IF @COM IS NULL OR @COM=''
     BEGIN
        SET @COM = RTRIM(LTRIM(DBO.FNK_VALORVARIABLE('IDCON_TCOM_DEFAULT')))
     END 
     IF @COM IS NULL OR @COM=''
     BEGIN
        SET @COM='IX'
     END
     
     SET @NROCOMPROBANTE = SPACE(20) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
     EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MCP',@NROCOMPROBANTE OUTPUT -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
     SELECT @NROCOMPROBANTE = @SEDE + REPLACE(SPACE(8 - CASE WHEN LEN(@NROCOMPROBANTE) > 8 THEN 8 ELSE LEN(@NROCOMPROBANTE) END)+LTRIM(RTRIM(@NROCOMPROBANTE)),SPACE(1),0) -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
     PRINT '@NROCOMPROBANTE:' + ISNULL(@NROCOMPROBANTE,'') -- MODIFICADO POR R.JAY 2009.04.18 PARA ELIMINAR DUPLICIDAD
     
     SET @PREFIJO_USCXS='@COM'+@COM
     SET @NOREFERENCIA=SPACE(20)
     EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,@PREFIJO_USCXS,@NOREFERENCIA OUTPUT   
     SELECT @NOREFERENCIA = REPLACE(SPACE(8 - LEN(@NOREFERENCIA))+LTRIM(RTRIM(@NOREFERENCIA)),SPACE(1),0)
     PRINT 'Nuevo Comprobante: '+@COM+' '+@NOREFERENCIA
     
     IF NOT EXISTS(SELECT COMPANIA,ANO,MES FROM PRI WHERE COMPANIA=@COMPANIA AND ANO=@ANO AND MES=@MES)
     BEGIN
        RAISERROR('Periodo Contable NO Existe', 16, 1)
        RETURN
     END
     PRINT '-- COMPROBANTE CONTABLE (MCP) '
     INSERT INTO MCPE(NROCOMPROBANTE, COMPANIA, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO,
                     TOTALCREDITO, REFERENCIA1, REFERENCIA2, USUARIO, FECHA, LOTE, OBSERVACION, IDSEDE, ESTADO, 
                     COMPROBANTE, IDTERCERO)
     SELECT @NROCOMPROBANTE, @COMPANIA, 'NOTDBCRCXP', @NOREFERENCIA, @ANO, @MES, CAST(STR(DAY(@FECHACONTABLE))+'/'+LTRIM(STR(@MES))+'/'+@ANO AS DATETIME),
            0, 0, @CNSFCXP, @ITEM, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), NULL, 'NOTAS DE CUENTAS POR PAGAR', 
            @SEDE, 0, @COM, @IDTERCERO
     FROM   #T 
  END
  ELSE
  BEGIN
     PRINT '@NROCOMPROBANTE <>'''' '
     IF (SELECT COUNT(*) FROM MCP WHERE NROCOMPROBANTE=@NROCOMPROBANTE)>0
     BEGIN
         INSERT INTO MCPE (COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                          REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                          RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO)
         SELECT COMPANIA, NROCOMPROBANTE, PROCEDENCIA, NOREFERENCIA, ANO, MES, FECHACONTABLE, TOTALDEBITO ,TOTALCREDITO, REFERENCIA1, REFERENCIA2,
                          REFERENCIA3, USUARIO, FECHA, LOTE ,OBSERVACION ,IDSEDE ,ESTADO ,ANULADO ,COMPROBANTE ,IDTERCERO, BANCO ,NOCHEQUE, VALOR_CHEQUE,
                          RPT_COMPROBANTE, FECHARADICACION, MARCA, SYS_COMPUTERNAME_MARCA, ESTADOIMP, CBTEINTERNO
         FROM   MCP
         WHERE NROCOMPROBANTE=@NROCOMPROBANTE
         --se borran de mcp, mch
         DELETE MCH WHERE NROCOMPROBANTE = @NROCOMPROBANTE
         DELETE MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE   
      END
      DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE
   END  
   PRINT 'BUSCO LOS MCHE'
   SELECT @ANO = ANO, @MES = MES,@COM=COMPROBANTE, @FECHACONTABLE = FECHACONTABLE FROM MCP WHERE NROCOMPROBANTE = @NROCOMPROBANTE
      
   IF @ESTADO='A' 
   BEGIN 
       DELETE MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND PROCEDENCIA='NOTDBCRCXP' AND REFERENCIA_PRO=@REFERENCIA_PRO AND REFERENCIA2 = @ITEM
         
       UPDATE MCPE 
       SET ESTADO  = CASE WHEN MCH.NROCOMPROBANTE IS NULL THEN '2' ELSE MCPE.ESTADO END,
           ANULADO = CASE WHEN MCH.NROCOMPROBANTE IS NULL THEN 1 ELSE 0 END
       FROM MCPE LEFT JOIN MCH ON MCPE.NROCOMPROBANTE=MCH.NROCOMPROBANTE 
       WHERE MCPE.COMPANIA=@COMPANIA AND MCPE.NROCOMPROBANTE=@NROCOMPROBANTE
      
       EXEC SPK_SUMA_DBCR @NROCOMPROBANTE 
       
       UPDATE FCXPDBCR SET CONTABILIZADA=1, MARCACONT=0, NROCOMPROBANTE=@NROCOMPROBANTE WHERE CNSFCXP=@CNSFCXP AND ITEM=@ITEM
       RETURN
   END
   IF @GIMPUESTOS = 1  /*JEDM.2011.ABR.26  SI GENERA IMPUESTOS*/
   BEGIN
      -- ADD.JQUIROGA 20090521 - REQ.1651
      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
	  	                     REFERENCIA1, REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
	  	                     ESTADO, PROCESO, GENERA, VALOR_PORCIMP, BASE_IMP,
	  	                     N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
	   SELECT  @NROCOMPROBANTE,@COMPANIA, CASE WHEN @PROCEDENCIA ='INV' THEN 'DB' ELSE CASE WHEN @TIPO = 'DB'  THEN 'DB' ELSE 'CR' END END,
              FIMPDV.CUENTA,FCXP.IDTERCERO, '','IMPUESTO POR '+UPPER(FIMPD.DESCRIPCION), 
               CASE WHEN FCXPI.IDIMPUESTO <> (SELECT DBO.FNK_VALORVARIABLE('IDIMP_RETEIVA')) 
                    THEN CASE WHEN FCXPDBCR.PROCEDENCIA ='INV' THEN ROUND((FCXPI.VALORIMP * FCXPDBCR.VALOR)/100,0) ELSE 
                                 CASE FCXPDBCR.GIVA WHEN 0 THEN CASE WHEN COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)>0 
                                                                     THEN  ROUND((FCXPI.VALORIMP * CASE WHEN COALESCE(@VLRPROAUDT,0)>0 THEN @VLRPROAUDT ELSE  FCXPDBCR.VALOR END )/100,0) 
                                                                     ELSE  ROUND((FCXPI.VALORIMP * CASE WHEN COALESCE(@VLRPROAUDT,0)>0 THEN @VLRPROAUDT ELSE  FCXPDBCR.VALOR END )/100,0)  
                                                                     END
                                    ELSE CASE WHEN COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)>0 
                                             THEN ROUND((FCXPI.VALORIMP *  CASE WHEN COALESCE(@VLRPROAUDT,0)>0 THEN @VLRPROAUDT ELSE  FCXPDBCR.VALOR END)/100,0) 
                                             ELSE  ROUND((FCXPI.VALORIMP *  CASE WHEN COALESCE(@VLRPROAUDT,0)>0 THEN @VLRPROAUDT ELSE  FCXPDBCR.VLR_NETO END)/100,0) END
                                 END 
                               END
                    ELSE CASE WHEN FCXPDBCR.PROCEDENCIA ='INV' THEN ROUND((FCXPI.VALORIMP * FCXPDBCR.VLR_NETO)/100,0) ELSE ROUND((FCXPI.VALORIMP * FCXPDBCR.VLR_NETO)/100,0) END
               END , 
 	         FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM, NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,'','S',
 	  	      1,'NOTDBCRCXP_DB_IMP','Movimiento',FIMPDV.VALOR,
              CASE WHEN FCXPDBCR.PROCEDENCIA ='INV'THEN CASE WHEN FCXPI.IDIMPUESTO <> (SELECT DBO.FNK_VALORVARIABLE('IDIMP_RETEIVA')) 
                                                      THEN @VALORCALCULO ELSE @VLRRETIVA END 
                                            ELSE CASE WHEN COALESCE(@VLRPROAUDT,0)>0 THEN FCXPDBCR.VALOR ELSE  FCXPDBCR.VALOR END END , 
	            FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 
	  	         FCXP.PROCEDENCIA,'NOTDBCRCXP',@CNSFCXP, FCXP.CODUNG, FCXP.CODPRG
	   FROM    FCXP, FCXPI, FIMPD, FIMPDV, FCXPDBCR 
	   WHERE   FCXP.CNSFCXP     = FCXPI.CNSFCXP 
      AND     FCXPI.IDIMPUESTO = FIMPD.IDIMPUESTO 
      AND     FCXPI.IDCLASE    = FIMPD.IDCLASE 
      AND     FIMPD.IDIMPUESTO = FIMPDV.IDIMPUESTO 
      AND     FIMPD.IDCLASE    = FIMPDV.IDCLASE 
      AND     FCXPI.ITEM       = FIMPDV.ITEM 
      AND     FCXPDBCR.CNSFCXP = FCXP.CNSFCXP 
      AND     FCXPI.VALOR     <> 0 
      --AND     FCXPI.TIPOCALCULO = 'Automatico' 
      AND     FCXP.CNSFCXP      = @CNSFCXP 
      AND     FCXPDBCR.ITEM     = @ITEM
	  AND     FCXPDBCR.CNSFCXP  =@CNSFCXP
   
	   --ADD.JQUIROGA 20090521 - REQ.1651
	  PRINT '- Contabilizando Impuestos Asumidos Credito.'
	  INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
			                REFERENCIA1, REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
			                ESTADO, PROCESO, GENERA, VALOR_PORCIMP, BASE_IMP,
			                N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
     SELECT  @NROCOMPROBANTE,@COMPANIA,CASE WHEN @TIPO = 'DB'  THEN 'CR' ELSE 'DB' END,FCXPI.CUENTA_ASUM,FCXP.IDTERCERO, '','IMPUESTO POR '+UPPER(FIMPD.DESCRIPCION), (FCXPI.VALORIMP * FCXPDBCR.VALOR)/100, 
 		        FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM, NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,'','S',
 			       1,'NOTDBCRCXP_DB_IMP','Movimiento',FIMPDV.VALOR,FCXPDBCR.VALOR,
			        FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 
			        FCXP.PROCEDENCIA,'NOTDBCRCXP',@CNSFCXP, FCXP.CODUNG, FCXP.CODPRG
	  FROM    FCXP,FCXPI,FIMPD,FIMPDV,FCXPDBCR 
	  WHERE   FCXP.CNSFCXP=FCXPI.CNSFCXP AND FCXPI.IDIMPUESTO=FIMPD.IDIMPUESTO AND FCXPI.IDCLASE=FIMPD.IDCLASE AND
			        FIMPD.IDIMPUESTO=FIMPDV.IDIMPUESTO AND FIMPD.IDCLASE=FIMPDV.IDCLASE AND FCXPI.ITEM=FIMPDV.ITEM AND FCXPDBCR.CNSFCXP = FCXPI.CNSFCXP AND
			        FCXPI.VALOR<>0 AND FCXP.CNSFCXP = @CNSFCXP AND FCXPDBCR.ITEM = @ITEM AND ISNULL(FCXPI.IMPUESTO_ASUM,0) = 1 
                    --AND FCXPI.TIPOCALCULO='Automatico'

      
   END
   SELECT @VIMP = SUM(COALESCE(VALOR,0)) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'DB' and proceso='NOTDBCRCXP_DB_IMP'
   IF COALESCE(@VIMP,0)>0
   BEGIN 
      UPDATE FCXPDBCR SET VLR_IMPUESTOS=@VIMP, VLR_NETO = CASE WHEN VLR_NETO<>0 AND VALOR>VLR_NETO THEN  VALOR-@VIMP ELSE VLR_NETO END 
	  WHERE CNSFCXP=@CNSFCXP AND ITEM=@ITEM
   END
   IF COALESCE(@PROCEDENCIA,'')='INV'
   BEGIN
      PRINT 'BUSCO DESCUENTOS E IVA'
      SELECT @TIPOMOV=IDTIPOMOV,@IDAREA=IDAREA,@CCOSTO=CCOSTO,@CNSMOVANT=CNSITRA  
      FROM IMOV WHERE CNSDBCR=@CNSFCXP AND ITEMDBCR=@ITEM
      
      SELECT IDARTICULO,SUM(VLRDTO)VLRDTO INTO #IMOVH  
      FROM IMOVH WHERE CNSMOV=@CNSMOVANT
      GROUP BY IDARTICULO

      SELECT @CNSMOVDEV = CNSMOV FROM  IMOV WHERE  CNSDBCR = @CNSFCXP AND ITEMDBCR = @ITEM

      PRINT 'ESTE ES EL MOVIMIENTO DE COMPRA ::: '+COALESCE(@CNSMOVANT,'NO ENCONTRE LA ORDEN')

      SELECT @IVACALCULO =COALESCE(ROUND(SUM(((IMOVH.CANTIDAD*IMOVH.PCOSTO / (1+FIMPDV.VALOR/100))-COALESCE(B.VLRDTO,0))*(FIMPDV.VALOR/100)),0),0)
      FROM  #T INNER JOIN FCXPD ON #T.CNSFCXP = FCXPD.CNSFCXP
					         INNER JOIN IMOVH ON IMOVH.IDARTICULO = FCXPD.IDSERVICIO AND IMOVH.NOLOTEPEDIDO = FCXPD.NOLOTE AND IMOVH.CNSMOV = @CNSMOVDEV
							 INNER JOIN IMOVH B ON B.IDARTICULO=IMOVH.IDARTICULO AND B.CNSMOV=@CNSMOVANT
					      INNER JOIN FIMPD ON FCXPD.IDIMPUESTO=FIMPD.IDIMPUESTO AND FCXPD.IDCLASE=FIMPD.IDCLASE
					      INNER JOIN FIMPDV   ON FIMPD.IDIMPUESTO=FIMPDV.IDIMPUESTO AND  FIMPD.IDCLASE=FIMPDV.IDCLASE
      WHERE #T.CNSFCXP =  @CNSFCXP
      AND #T.ITEM = @ITEM
      AND DBO.FNK_VALORVARIABLE('IDIMP_IVA') = FIMPD.IDIMPUESTO
      AND COALESCE(FCXPD.VLR_IVA, 0)<> 0
      AND FIMPDV.FECHAINI<#T.FECHA
      AND FIMPDV.FECHAFIN>#T.FECHA
      PRINT 'SALGO DE BUSCA EL IVA'
      IF COALESCE(@IVACALCULO,0)=0
      BEGIN
         SET @IVACALCULO = 0
      END

	 
      SELECT @VALORCALCULO =  ROUND(SUM((IMOVH.CANTIDAD*IMOVH.PCOSTO / (1+COALESCE(FIMPDV.VALOR,0)/100))),0)
      FROM  #T INNER JOIN FCXPD ON #T.CNSFCXP = FCXPD.CNSFCXP
					         INNER JOIN IMOVH ON IMOVH.IDARTICULO = FCXPD.IDSERVICIO AND IMOVH.NOLOTEPEDIDO = FCXPD.NOLOTE 
                        AND IMOVH.CNSMOV = @CNSMOVDEV
						LEFT JOIN FIMPD ON FCXPD.IDIMPUESTO=FIMPD.IDIMPUESTO AND FCXPD.IDCLASE=FIMPD.IDCLASE   AND DBO.FNK_VALORVARIABLE('IDIMP_IVA') = FIMPD.IDIMPUESTO
					      LEFT JOIN FIMPDV   ON FIMPD.IDIMPUESTO=FIMPDV.IDIMPUESTO AND  FIMPD.IDCLASE=FIMPDV.IDCLASE  AND FIMPDV.FECHAINI<#T.FECHA   AND FIMPDV.FECHAFIN>#T.FECHA
      WHERE #T.CNSFCXP = @CNSFCXP
      AND #T.ITEM = @ITEM

      PRINT 'BUSCO RETEIVA'
      IF EXISTS( SELECT * FROM FCXPI WHERE CNSFCXP=@CNSFCXP AND IDIMPUESTO=DBO.FNK_VALORVARIABLE('IDIMP_RETEIVA') )
      BEGIN
         SELECT @FACT_RETEIVA=VALORIMP  FROM FCXPI WHERE CNSFCXP=@CNSFCXP AND IDIMPUESTO=DBO.FNK_VALORVARIABLE('IDIMP_RETEIVA')

         SELECT @VLRRETIVA=ROUND(@IVACALCULO *(@FACT_RETEIVA/100),0)
      END
      ELSE
      BEGIN
         SELECT @VLRRETIVA=0
      END
      SELECT @VALOR_REAL = COALESCE(ROUND(FCXPDBCR.VALOR-@IVACALCULO, 0), 0), @VALOR_REALIVA =@IVACALCULO  FROM FCXPDBCR WHERE CNSFCXP = @CNSFCXP AND ITEM = @ITEM
     --PRINT '@VALOR_REAL ='+STR(LTRIM(RTRIM(@VALOR_REAL)))
     --PRINT '@VALOR_REALIVA ='+STR(LTRIM(RTRIM(@VALOR_REALIVA)))
     ---- PRINT 'ESTE ES EL DESCUENTO'+STR(COALESCE(A.VLRDTO,0)) 
     
   END
   PRINT '- Contabilizando el Debito. @TER_AUTORE='+STR(@TER_AUTORE)
   PRINT @NROCOMPROBANTE

   -- MOD.JQUIROGA 20090521 - Descontar valor de Impuestos REQ.1651
   INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
                    REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
                    ESTADO,PROCESO,GENERA,N_FACTURA,F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO,
                    CODUNG, CODPRG)
   SELECT @NROCOMPROBANTE, @COMPANIA, 'DB', CASE WHEN COALESCE(@PROCEDENCIA,'')='INV' THEN #T.CUENTA_CR ELSE #T.CUENTA_DB END, FCXP.IDTERCERO, #T.CCOSTO, 
          'NOTA '+UPPER(#T.TIPO)+' POR '+UPPER(FNT.DESCRIPCION)+CHAR(13)+CHAR(10)+ #T.OBSERVACION+CHAR(13)+CHAR(10)+ 
          'DOCUMENTO No. '+CASE WHEN #T.TIPO='DB' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END,
           CASE #T.TIPO WHEN 'DB' THEN CASE WHEN @TER_AUTORE = 1 
                                            THEN CASE WHEN COALESCE(@PROCEDENCIA,'')='INV' 
                                                      THEN  FCXPDBCR.VALOR
                                                      ELSE  CASE WHEN FCXPDBCR.PROCEDENCIA='AUDT' THEN @VLRPROAUDT-COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)
															ELSE (FCXPDBCR.VALOR+FCXPDBCR.VALORIVA)+COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)
															END
                                                  END 
                                            ELSE CASE WHEN COALESCE(@VLRPROAUDT,0) >0 THEN  @VLRPROAUDT-COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)
													  WHEN FCXPDBCR.PROCEDENCIA<>'AUDT' THEN  (FCXPDBCR.VALOR+FCXPDBCR.VALORIVA)-COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)--ACA
													  ELSE  FCXPDBCR.VALOR END 
                                       END 
                                  ELSE CASE COALESCE(@GIVA, 0) WHEN 1 
                                                  THEN (FCXPDBCR.VLR_NETO+FCXPDBCR.VALORIVA)-COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)
                                                  ELSE #T.VALOR +COALESCE(FCXPDBCR.VLR_IMPUESTOS,0)
                                       END 
            END,
          @CNSFCXP, @ITEM, '', NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '', '', 'P', 1, 'NOTDBCRCXP_DB', 'Movimiento', 
          CASE WHEN #T.TIPO='DB' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END, DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), 
          DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'NOTDBCRCXP',  @CNSFCXP, #T.CODUNG, #T.CODPRG
   FROM   #T INNER JOIN FCXP ON #T.CNSFCXP = FCXP.CNSFCXP 
             INNER JOIN  FNT ON #T.IDNOTA  = FNT.IDNOTA
             LEFT JOIN FCXPDBCR ON FCXPDBCR.CNSFCXP = #T.CNSFCXP AND FCXPDBCR.ITEM = #T.ITEM 
    
   PRINT '- Contabilizando el Credito.'
   IF COALESCE(@PROCEDENCIA,'')='INV'
   BEGIN
      PRINT 'PROCEDENCIA INV'
	     INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
						               	REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
							               ESTADO,PROCESO,GENERA,N_FACTURA,F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO,
							               CODUNG, CODPRG)
	     SELECT @NROCOMPROBANTE, @COMPANIA, 'CR', 
		 CASE WHEN COALESCE(@PROCEDENCIA,'')='INV' THEN DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'CXP_COMPRAS','DB',IART.IDITAR, IMOV.CCOSTO,'P','',0) 
               ELSE DBO.FNK_NC_CUENTA_KMCOM(@IDMODELOCONT,'CXP_COMPRAS','CR',IART.IDITAR, IMOV.CCOSTO,'P','',0) END, FCXP.IDTERCERO, IMOV.CCOSTO, 
               'NOTA '+UPPER(#T.TIPO)+' POR '+UPPER(FNT.DESCRIPCION)+#T.OBSERVACION+CHAR(13)+CHAR(10)+'IDARTICULO : '+ IMOVH.IDARTICULO,
			   ROUND(CONVERT(DECIMAL(14,2),(IMOVH.CANTIDAD*IMOVH.PCOSTO / CASE WHEN COALESCE(B.PIVA,0) >0 THEN  (1+COALESCE(FIMPDV.VALOR,0)/100) ELSE 1 END)), 0), 
               @CNSFCXP, @ITEM, '', NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), IART.IDITAR, IMOV.IDAREA, 'P', 1, 'NOTDBCRCXP_CR', 'Movimiento', 
				   CASE WHEN #T.TIPO='CR' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END, DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), 
               DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'NOTDBCRCXP',  @CNSFCXP, #T.CODUNG, #T.CODPRG
	     FROM  #T INNER JOIN FCXPD ON #T.CNSFCXP = FCXPD.CNSFCXP
                  INNER JOIN FCXP  ON #T.CNSFCXP = FCXP.CNSFCXP
					   INNER JOIN FNT   ON #T.IDNOTA  = FNT.IDNOTA
					   INNER JOIN IMOVH ON IMOVH.IDARTICULO = FCXPD.IDSERVICIO AND IMOVH.NOLOTEPEDIDO = FCXPD.NOLOTE AND IMOVH.CNSMOV = @CNSMOVDEV
					   INNER JOIN IMOVH B ON B.IDARTICULO=IMOVH.IDARTICULO AND IMOVH.NOLOTE=B.NOLOTE AND B.CNSMOV=@CNSMOVANT
                  INNER JOIN IMOV  ON IMOV.CNSMOV = @CNSMOVDEV
					   INNER JOIN IART  ON IMOVH.IDARTICULO=IART.IDARTICULO
					    LEFT JOIN FIMPD ON FCXPD.IDIMPUESTO=FIMPD.IDIMPUESTO AND FCXPD.IDCLASE=FIMPD.IDCLASE   AND DBO.FNK_VALORVARIABLE('IDIMP_IVA') = FIMPD.IDIMPUESTO
					      LEFT JOIN FIMPDV   ON FIMPD.IDIMPUESTO=FIMPDV.IDIMPUESTO AND  FIMPD.IDCLASE=FIMPDV.IDCLASE  AND FIMPDV.FECHAINI<#T.FECHA   AND FIMPDV.FECHAFIN>#T.FECHA
         
         PRINT '- Contabilizando IVA Credito.'
	      INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
			                     REFERENCIA1, REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
			                     ESTADO, PROCESO, GENERA, VALOR_PORCIMP, BASE_IMP,
			                     N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
         SELECT  @NROCOMPROBANTE,@COMPANIA, 'CR',FCXPD.CUENTA_IVA, FCXP.IDTERCERO, '','IMPUESTO POR '+UPPER(FIMPD.DESCRIPCION), 
                COALESCE(ROUND(SUM(((IMOVH.CANTIDAD*IMOVH.PCOSTO / (1+FIMPDV.VALOR/100))-COALESCE(B.VLRDTO,0))*(FIMPDV.VALOR/100)),0),0), --SE REEMPLAZA CEILING POR ROUND YA QUE SIEMPRE SE PASABA UN PESO 20220221 OSOLANO, --SE TOMA EL IVA DE LA NOTA DADO A QUE YA SE CORRE EL CALCULO Y EL VALOR EN EL CAMPO DE LA NOTA 01/02/16 KLEYDER
 	               FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM, NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,'','S',
 		            1,'NOTDBCRCXP_DB_IMP','Movimiento',FIMPDV.VALOR, ROUND(SUM(IMOVH.CANTIDAD*FCXPD.VALOR), 0),
	               FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 
	               FCXP.PROCEDENCIA,'NOTDBCRCXP',@CNSFCXP, FCXP.CODUNG, FCXP.CODPRG
         FROM  #T INNER JOIN FCXPD ON #T.CNSFCXP = FCXPD.CNSFCXP
                  INNER JOIN FCXP  ON #T.CNSFCXP =FCXP.CNSFCXP
					   INNER JOIN IMOVH ON IMOVH.IDARTICULO = FCXPD.IDSERVICIO AND IMOVH.NOLOTEPEDIDO = FCXPD.NOLOTE AND IMOVH.CNSMOV = @CNSMOVDEV
					   INNER JOIN IMOVH B ON B.IDARTICULO=IMOVH.IDARTICULO AND IMOVH.NOLOTE=B.NOLOTE AND B.CNSMOV=@CNSMOVANT
					   INNER JOIN FIMPD ON FCXPD.IDIMPUESTO=FIMPD.IDIMPUESTO AND FCXPD.IDCLASE=FIMPD.IDCLASE
					   INNER JOIN FIMPDV   ON FIMPD.IDIMPUESTO=FIMPDV.IDIMPUESTO AND  FIMPD.IDCLASE=FIMPDV.IDCLASE
         WHERE #T.CNSFCXP =  @CNSFCXP
         AND #T.ITEM = @ITEM
         AND DBO.FNK_VALORVARIABLE('IDIMP_IVA') = FIMPD.IDIMPUESTO
         AND COALESCE(B.PIVA, 0)<> 0
         AND FIMPDV.FECHAINI<#T.FECHA
         AND FIMPDV.FECHAFIN>#T.FECHA
	      GROUP BY FCXPD.CUENTA_IVA, FCXP.IDTERCERO, FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM, FIMPDV.VALOR,#T.VALOR,FCXP.NOREFERENCIA,
                  FCXP.PROCEDENCIA,FCXP.CODUNG, FCXP.CODPRG, UPPER(FIMPD.DESCRIPCION), FCXP.F_FACTURAREF, FCXP.F_VENCE,#T.VALORIVA
   END
   ELSE
    BEGIN
    PRINT '@CAMTER = '+CONVERT(VARCHAR(20), @CAMTER)
	
      SELECT @VLR_IVA = COALESCE(SUM(VLR_IVA),0) FROM FCXPD WHERE CNSFCXP = @CNSFCXP
      IF @VLR_IVA > 0  AND COALESCE(@GIVA,0)=1
      BEGIN
         IF (SELECT VALORIVA FROM #T)>0
         BEGIN
            SELECT @VALOR_REALIVA=VALORIVA FROM #T
         END
         INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
						      REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
							   ESTADO,PROCESO,GENERA,N_FACTURA,F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO,
							   CODUNG, CODPRG)
	      SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',#T.CUENTA_CR, FCXP.IDTERCERO, #T.CCOSTO, 
				         'NOTA '+UPPER(#T.TIPO)+' POR '+UPPER(FNT.DESCRIPCION)+CHAR(13)+CHAR(10)+
				         #T.OBSERVACION+CHAR(13)+CHAR(10)+ 
				         'DOCUMENTO No. '+CASE WHEN #T.TIPO='CR' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END,
				          CASE #T.TIPO WHEN 'DB' 
                                  THEN CASE COALESCE(@GIVA, 0) WHEN 1 
                                                  THEN #T.VALOR
                                                  ELSE #T.VLR_NETO 
                                       END 
                                   ELSE CASE WHEN @TER_AUTORE = 1 
                                             THEN #T.VALOR-ROUND((@T_IMPUESTO * @VALOR_REAL)/100,0) 
                                             ELSE #T.VLR_NETO 
                                        END 
                      END, 
                      @CNSFCXP, @ITEM, '', NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), 
                     '', '', 'P', 1, 'NOTDBCRCXP_CR', 'Movimiento',  CASE WHEN #T.TIPO='CR' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END, 
                     DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'NOTDBCRCXP',  @CNSFCXP, #T.CODUNG, #T.CODPRG
	      FROM   #T INNER JOIN FCXP ON #T.CNSFCXP = FCXP.CNSFCXP 
					    INNER JOIN FNT  ON #T.IDNOTA  = FNT.IDNOTA
         IF @GIVA =1
         BEGIN
            PRINT '- Contabilizando IVA Credito.'
	         INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
			                        REFERENCIA1, REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
			                        ESTADO, PROCESO, GENERA, VALOR_PORCIMP, BASE_IMP,
			                        N_FACTURA,F_FACTURAREF, F_VENCE, CLASE_GENERA, PROCEDENCIA, REFERENCIA_PRO, CODUNG, CODPRG)
            SELECT TOP 1 @NROCOMPROBANTE,@COMPANIA,CASE WHEN @TIPO = 'DB' THEN 'CR' ELSE 'DB' END,
                     COALESCE(FCXPD.CUENTA_IVA,@CUENTAIVAX), FCXP.IDTERCERO, '','IMPUESTO POR '+UPPER(FIMPD.DESCRIPCION),AVG(FCXPDBCR.VALORIVA), 
 	                  FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM, NULL,@USUARIO,DBO.FNK_FECHA_SIN_MLS(GETDATE()),NULL,'','S',
 		               1,'NOTDBCRCXP_DB_IMP','Movimiento',FIMPDV.VALOR, @VALOR_REAL,
	                  FCXP.NOREFERENCIA,DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 
	                  FCXP.PROCEDENCIA,'NOTDBCRCXP',@CNSFCXP, FCXP.CODUNG, FCXP.CODPRG
            FROM FCXPD INNER JOIN FCXPDBCR ON FCXPD.CNSFCXP = FCXPDBCR.CNSFCXP AND FCXPDBCR.ITEM = @ITEM
                        INNER JOIN FCXP     ON FCXP.CNSFCXP  = FCXPD.CNSFCXP,
                  FIMPD INNER JOIN FIMPDV   ON FIMPD.IDIMPUESTO=FIMPDV.IDIMPUESTO AND  FIMPD.IDCLASE=FIMPDV.IDCLASE
            WHERE FCXPD.CNSFCXP = @CNSFCXP
            AND DBO.FNK_VALORVARIABLE('IDIMP_IVA') = FIMPD.IDIMPUESTO
            AND COALESCE(FCXPD.VLR_IVA, 0)<> 0
            AND FCXP.FECHA BETWEEN FIMPDV.FECHAINI AND FIMPDV.FECHAFIN
            GROUP BY FCXPD.CUENTA_IVA, FCXP.IDTERCERO, FIMPD.DESCRIPCION, FIMPDV.IDIMPUESTO,FIMPDV.IDCLASE,FIMPDV.ITEM, FIMPDV.VALOR,FCXPDBCR.VALOR,
	         FCXP.NOREFERENCIA, FCXP.F_FACTURAREF, FCXP.F_VENCE, FCXP.PROCEDENCIA, FCXP.CODUNG, FCXP.CODPRG
        END

      END
      ELSE
      BEGIN
	         PRINT ('ES IGUAL A CERO ')+STR(COALESCE(@CAMTER,0))+STR(COALESCE(@GENCXP,0))
           INSERT INTO MCHE(NROCOMPROBANTE,COMPANIA,TIPO,CUENTA,IDTERCERO,CCOSTO,DETALLE,VALOR,
						      REFERENCIA1,REFERENCIA2,REFERENCIA3,ITEMREF,USUARIO,FECHA,PREFIJO,IDAREA,CLASECONT,
							   ESTADO,PROCESO,GENERA,N_FACTURA,F_FACTURAREF, F_VENCE, PROCEDENCIA, REFERENCIA_PRO,
							   CODUNG, CODPRG)
	      SELECT @NROCOMPROBANTE, @COMPANIA, 'CR',#T.CUENTA_CR, 
                     CASE WHEN (COALESCE(@CAMTER,0) = 1 OR COALESCE(@GENCXP,0) = 1) AND COALESCE(#T.IDTERCEROGENCXP,'')<>'' THEN #T.IDTERCEROGENCXP ELSE FCXP.IDTERCERO END, #T.CCOSTO, 
				         'NOTA '+UPPER(#T.TIPO)+' POR '+UPPER(FNT.DESCRIPCION)+CHAR(13)+CHAR(10)+
				         #T.OBSERVACION+CHAR(13)+CHAR(10)+ 
				         'DOCUMENTO No. '+CASE WHEN #T.TIPO='CR' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END,
				         CASE WHEN #T.TIPO = 'CR' THEN  CASE WHEN COALESCE(#T.VLR_NETO,0)=0 THEN  #T.VALOR ELSE COALESCE(#T.VLR_NETO,0) END   
							ELSE CASE WHEN  #T.TIPO ='DB' AND @PROCEDENCIA<>'AUDT' THEN #T.VALOR ELSE COALESCE(@VLRPROAUDT,0) END  END, @CNSFCXP, @ITEM, '', NULL, @USUARIO, DBO.FNK_FECHA_SIN_MLS(GETDATE()), '', '', 'P', 1, 'NOTDBCRCXP_CR', 'Movimiento', 
				         CASE WHEN #T.TIPO='CR' THEN FCXP.NOREFERENCIA ELSE #T.NOREFERENCIA END, DBO.FNK_FECHA_SIN_HORA(FCXP.F_FACTURAREF), 
				         DBO.FNK_FECHA_SIN_HORA(FCXP.F_VENCE), 'NOTDBCRCXP',  @CNSFCXP, #T.CODUNG, #T.CODPRG
	      FROM   #T INNER JOIN FCXP ON #T.CNSFCXP = FCXP.CNSFCXP AND #T.ITEM = @ITEM
					    INNER JOIN FNT  ON #T.IDNOTA  = FNT.IDNOTA

      END
    END

   EXEC SPK_NC_SUMA_DBCR @NROCOMPROBANTE

	SELECT @VDB = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'DB'
	SELECT @VCR = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'CR'
	SELECT @VFNOT = VLR_NETO FROM FCXPDBCR WHERE CNSFCXP= @CNSFCXP AND ITEM=@ITEM

	SELECT @VIMP = SUM(VALOR) FROM MCHE WHERE NROCOMPROBANTE = @NROCOMPROBANTE AND TIPO = 'DB' and proceso='NOTDBCRCXP_DB_IMP'

	PRINT '@VDB'+convert(varchar(max),(@VDB))
	PRINT '@VCR'+convert(varchar(max),(@VCR))
	PRINT '@VIMP'+convert(varchar(max),(@VIMP))
	PRINT '@VFNOT'+STR(@VFNOT)
	IF ROUND(@VDB,0) < ROUND(@VCR,0)
	BEGIN 
	PRINT 'ENTRE AQUI DB MENOR QUE CR'
		UPDATE MCHE SET VALOR = CONVERT(decimal(14, 6),MCHE.VALOR)  + ( CONVERT(decimal(14, 6),@VFNOT) - CONVERT(decimal(14, 6),C.VALOR))
		FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE WHERE  NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB') AS B,
				(SELECT SUM(CONVERT(decimal(14, 6),VALOR)) AS VALOR FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' ) AS C
		WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VFNOT-C.VALOR) <> 0 
	END
	IF ROUND( @VDB,0) >  ROUND(@VCR,0)
	BEGIN
	PRINT 'ENTRE AQUI DB MAYOR QUE CR'
		UPDATE MCHE SET VALOR = CONVERT(decimal(14, 6),MCHE.VALOR)  - ( CONVERT(decimal(14, 6),C.VALOR - CONVERT(decimal(14, 6),@VFNOT)))
		FROM (SELECT MAX(NROASIENTO) AS NROASIENTO FROM MCHE WHERE  NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB') AS B,
				(SELECT SUM(CONVERT(decimal(14, 6),VALOR)) AS VALOR FROM MCHE WHERE NROCOMPROBANTE=@NROCOMPROBANTE AND TIPO='DB' ) AS C
		WHERE MCHE.NROASIENTO=B.NROASIENTO AND (@VFNOT-C.VALOR) <> 0 
	END
	
	IF DBO.FNK_VALORVARIABLE('FCXP_ENVIO_DIAN_AUTO')='SI'
	BEGIN
		UPDATE FCXPDBCR SET ESTADODIAN=1 FROM FCXPDBCR A INNER JOIN FCXP B ON A.CNSFCXP=B.CNSFCXP 
		WHERE A.CNSFCXP=@CNSFCXP AND A.ITEM=@ITEM AND COALESCE(B.DOCEQUIVALENTE,0)=1 AND COALESCE(A.CNSRESOL,'')<>'' 
				AND COALESCE(B.N_FACTURA,'')<>'' AND COALESCE(A.ESTADODIAN,0)=0 
				AND EXISTS (SELECT 1 FROM FNT WHERE FNT.IDNOTA=A.IDNOTA AND COALESCE(FNT.HOMOLOGODIAN,'')<>'')
	END
	EXEC SPK_NC_REVISAMCPE @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SEDE, @SYS_COMPUTERNAME
	EXEC SPK_PASA_MCP_MCPNIIF @NROCOMPROBANTE, @COMPANIA, @USUARIO, @SYS_COMPUTERNAME, @SEDE,@COM,''
	DROP TABLE #T
END


