IF EXISTS (SELECT name FROM sysobjects  WHERE name = 'SPK_TOTALFACTURFIN' AND type = 'P')
   DROP PROCEDURE SPK_TOTALFACTURFIN

GO
CREATE PROCEDURE DBO.SPK_TOTALFACTURFIN
@N_FACTURA VARCHAR(16)
WITH ENCRYPTION
AS
BEGIN
   PRINT 'ENTRE A TOTALES'
   CREATE TABLE #TEMP (VALORSERVICIOS DECIMAL(14,2), 
                     VALORCOPAGO    DECIMAL(14,2), 
                     VALORPCOMP     DECIMAL(14,2), 
                     COPAGOCP       DECIMAL(14,2),
                     VR_TOTAL       DECIMAL(14,2),
                     VIVA           DECIMAL(14,2),
                     PIVA           DECIMAL(7,2))
   INSERT INTO #TEMP
   SELECT COALESCE(SUM(VLR_SERVICI),0),COALESCE(SUM(VLR_COPAGOS),0),COALESCE(SUM(VLR_PAGCOMP),0),COALESCE(SUM(COPAGOS_CP),0),COALESCE(SUM(VR_TOTAL),0), COALESCE(SUM(VIVA*CANTIDAD),0),MAX(COALESCE(PIVA,0)) 
   FROM FTRD WHERE N_FACTURA = @N_FACTURA
                                     
   UPDATE FTR SET VALORSERVICIOS = #TEMP.VALORSERVICIOS,
                  VALORCOPAGO    = #TEMP.VALORCOPAGO,
                  VALORPCOMP     = #TEMP.VALORPCOMP,
                  CP_VLR_COPAGOS = #TEMP.COPAGOCP,
                  VR_TOTAL       = CASE WHEN COALESCE(FTR.COPAPROPIO,0)=1 THEN #TEMP.VALORSERVICIOS-(#TEMP.COPAGOCP)-  ISNULL(FTR.DESCUENTO,0) - ISNULL(FTR.VR_ABONOS,0)   
										WHEN COALESCE(FTR.VALORMODERADORA,0)>0 THEN #TEMP.VALORSERVICIOS - FTR.VALORCOPAGO -  ISNULL(FTR.DESCUENTO,0) - ISNULL(FTR.VR_ABONOS,0)   - COALESCE(FTR.VALORMODERADORA,0) 
                                       ELSE  #TEMP.VR_TOTAL -  ISNULL(FTR.DESCUENTO,0) - ISNULL(FTR.VR_ABONOS,0) 
                                 END, 
                  VIVA           = #TEMP.VIVA,
                  PIVA           = #TEMP.PIVA
   FROM #TEMP
   WHERE FTR.N_FACTURA = @N_FACTURA

   DROP TABLE #TEMP
END





