IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_NOMINA' AND IDCONTROL='Desprendibles')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_NOMINA', 'Desprendibles', 'M','Liquidación Nomina', 1, 'nom.Desprendibles', 'fa-solid fa-receipt', NULL, 0, 0, 920,'Imprimir Desprendibles', NULL, NULL
END