IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_GENITEMS_NOTACR' AND type = 'P')
   DROP PROCEDURE SPK_GENITEMS_NOTACR

GO
CREATE PROCEDURE DBO.SPK_GENITEMS_NOTACR 
@CNSFNOT  VARCHAR(20), 
@CLASE    VARCHAR(1), 
@USUARIO  VARCHAR(12)
WITH ENCRYPTION
AS
DECLARE @AUX     INT
DECLARE @REB_IND DECIMAL(14,2)
DECLARE @TOT     DECIMAL(14,2)
DECLARE @CONCEPTO      TINYINT
DECLARE @IDCONCEPTO    VARCHAR(20)
DECLARE @TIPOCONCEPTO  VARCHAR(1)
DECLARE @VALORCONCEPTO DECIMAL(19,2)
DECLARE @N_FACTURA     VARCHAR(20)
DECLARE @LIBERAHADM    SMALLINT
DECLARE @VR_TOTAL      DECIMAL(19,2)
DECLARE @VLRAREBAJAR_P DECIMAL(19,10)
DECLARE @VALORTOTAL    DECIMAL(19,2)
DECLARE @VLRDIST       DECIMAL(19,2) 
DECLARE @A             SMALLINT 
DECLARE @ITEM          SMALLINT 
DECLARE @NUMITEM       INT
DECLARE @DETGENERADOS  SMALLINT
DECLARE @TIPODTO       VARCHAR(1)
DECLARE @VLRAREBAJAR   DECIMAL(19,2)
DECLARE @PAQUETE       BIT=0
DECLARE @IDSERPAQ     VARCHAR(20)
DECLARE @DESCPAQ      VARCHAR(512)
DECLARE @NOADMISION   VARCHAR(20)
DECLARE @TIPOFAC      VARCHAR(2)
DECLARE @SALDOVK      DECIMAL(14,2) -- SALDO REAL EN CARTERA
DECLARE @CNSCXC       VARCHAR(20)
BEGIN
   PRINT 'CAPTURO DATOS'
   SELECT @N_FACTURA     = N_FACTURA, @CONCEPTO = CONCEPTO, @IDCONCEPTO = IDCONCEPTO, @TIPOCONCEPTO = TIPOCONCEPTO,
          @VALORCONCEPTO = VALORCONCEPTO, @LIBERAHADM = LIBERAHADM, @DETGENERADOS = DETGENERADOS,@CNSCXC=COALESCE(CNSCXC,'')
   FROM   FNOT
   WHERE  CNSFNOT = @CNSFNOT
   AND    CLASE   = @CLASE   
   
   PRINT 'COMIENZO' 

   IF COALESCE(@CONCEPTO,0) = 0
   BEGIN
      RETURN
   END
   ELSE
   BEGIN
      IF @DETGENERADOS = 1
      BEGIN
         RETURN
      END
   END
   DELETE FNOTD WHERE CNSFNOT = @CNSFNOT

   SELECT @VR_TOTAL = VR_TOTAL,@PAQUETE=COALESCE(PAQUETE,0),@NOADMISION=NOREFERENCIA,@TIPOFAC=FTR.TIPOFAC 
   FROM FTR WHERE N_FACTURA   = @N_FACTURA

   SELECT  @TIPODTO = @TIPOCONCEPTO, @VLRAREBAJAR = @VALORCONCEPTO
   
   SELECT @AUX = COALESCE(COUNT(*),0), @TOT = SUM(FTRD.VR_TOTAL)
   FROM   FTRD 
   WHERE  N_FACTURA   = @N_FACTURA  
   
   SELECT @SALDOVK=SALDO FROM  VWK_FTRNDCR WHERE N_FACTURA=@N_FACTURA AND COALESCE(CNSCXC,'')=@CNSCXC

   IF @VR_TOTAL>@SALDOVK
   BEGIN
      IF @TIPODTO='V'
      BEGIN
	  print 'entre aqui vr_total'
         --SELECT @VR_TOTAL=@SALDOVK
      END
      ELSE
      BEGIN
         SELECT @VLRAREBAJAR_P=(((@SALDOVK*(@VLRAREBAJAR/100))*100)/@VR_TOTAL)

      END
   END
   
   IF @TIPODTO  = 'V'
   BEGIN
      SELECT @VLRAREBAJAR_P = (@VLRAREBAJAR * 100) / @VR_TOTAL 
   END
   ELSE
   BEGIN
      SELECT @VLRAREBAJAR_P = @VLRAREBAJAR
   END 
   
   IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' AND (@PAQUETE=1 OR @TIPOFAC='M')
   BEGIN
      PRINT 'Ingreso por paquete de peru'
      IF @PAQUETE=1
      BEGIN
         SELECT @IDSERPAQ=HADM.IDSERVICIOPAQUETE,@DESCPAQ=SER.DESCSERVICIO 
         FROM HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE=SER.IDSERVICIO
         WHERE NOADMISION=@NOADMISION
      END
      ELSE
      BEGIN
         SELECT @DESCPAQ=dbo.FNK_LIMPIATEXTO(CASE WHEN COALESCE(OBSERVACION,'')<>'' 
               THEN  OBSERVACION ELSE PLN.DESCPLAN END,'0-9 A-Z '),
               @IDSERPAQ=dbo.FNK_LIMPIATEXTO(COALESCE(@IDSERPAQ,FTR.IDPLAN),'0-9 A-Z ')
      FROM FTR INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN   
      WHERE N_FACTURA=@N_FACTURA
      END
      PRINT 'INGRESO POR PAQUETES DETALLES'
      INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
                         VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
      SELECT @CNSFNOT, 'C', 1, 'S', @IDSERPAQ, @DESCPAQ, 1, VR_TOTAL,VR_TOTAL, '01', @USUARIO, NULL, 1, PIVA, VIVA, @N_FACTURA,NULL,NULL,NULL,NULL
      FROM   FTR 
      WHERE  N_FACTURA   = @N_FACTURA      
   END
   ELSE
   BEGIN
      IF @PAQUETE=1
      BEGIN
         PRINT 'INGRESO A PAQUETES'
         SELECT @IDSERPAQ=HADM.IDSERVICIOPAQUETE,@DESCPAQ=SER.DESCSERVICIO 
         FROM HADM INNER JOIN SER ON HADM.IDSERVICIOPAQUETE=SER.IDSERVICIO
         WHERE NOADMISION=@NOADMISION

         PRINT 'INGRESO LOS ITEMS  DEL PAQUETE Y LOS QUE ESTAN POR FUERA'

		   INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
	 						 VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
	 	   SELECT @CNSFNOT, 'C', N_CUOTA, 'S', LEFT(REFERENCIA,20),left (ANEXO,512), 1,
	 	   (COALESCE(VLR_SERVICI,0) - COALESCE(VLR_COPAGOS,0))* (@VLRAREBAJAR_P/100), 
	 		 ROUND((COALESCE(VLR_SERVICI,0) - COALESCE(VLR_COPAGOS,0))* (@VLRAREBAJAR_P/100),2), '01', @USUARIO, NULL, N_CUOTA, PIVA, VIVA, @N_FACTURA,CCOSTO,AREAPRESTACION,PREFIJO,CUENTACR
	  	   FROM   FTRD 
		   WHERE  N_FACTURA   = @N_FACTURA
         AND COALESCE(PAQUETE,0) IN(1,3) 
		   and ROUND((COALESCE(VLR_SERVICI,0) - COALESCE(VLR_COPAGOS,0))* (@VLRAREBAJAR_P/100),2)<>0

      END
	   ELSE
	   BEGIN
		   INSERT INTO FNOTD( CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO,
	 						 VR_TOTAL, COMPANIA, USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA,CCOSTO,IDAREA,PREFIJO,CUENTA)
	 	   SELECT @CNSFNOT, 'C', N_CUOTA, 'S', LEFT(REFERENCIA,20),left (ANEXO,512), 1,
	 	   (COALESCE(VLR_SERVICI,0) - COALESCE(VLR_COPAGOS,0))* (@VLRAREBAJAR_P/100), 
	 		 ROUND((COALESCE(VLR_SERVICI,0) - COALESCE(VLR_COPAGOS,0))* (@VLRAREBAJAR_P/100),2), '01', @USUARIO, NULL, N_CUOTA, PIVA, VIVA, @N_FACTURA,CCOSTO,AREAPRESTACION,PREFIJO,CUENTACR
	  	   FROM   FTRD 
		   WHERE  N_FACTURA   = @N_FACTURA
		   and ROUND((COALESCE(VLR_SERVICI,0) - COALESCE(VLR_COPAGOS,0))* (@VLRAREBAJAR_P/100),2)<>0
	   END
   END

   PRINT 'DESPUES DE LOS DETALLE SIN NADA...'
   
   SELECT @VR_TOTAL = SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
    
  UPDATE FNOT SET VR_TOTAL = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN ROUND(@VR_TOTAL,2) ELSE ROUND(@VR_TOTAL,0) END WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE

   IF @TIPODTO  = 'V'
   BEGIN
      SELECT @VALORTOTAL = SUM(FNOTD.VR_TOTAL)
      FROM   FNOTD
      WHERE  CNSFNOT = @CNSFNOT AND CLASE = @CLASE
      IF @VLRAREBAJAR <> @VALORTOTAL
      BEGIN
         PRINT 'ERROR EN VALORES @VALORTOTAL='+CAST(@VALORTOTAL AS VARCHAR(20))+'--@VLRAREBAJAR='+CAST(@VLRAREBAJAR AS VARCHAR(20))
         /*
         IF @VALORTOTAL > @VLRAREBAJAR
         BEGIN
            SELECT @NUMITEM = COALESCE(COUNT(*),0) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
            SELECT @VLRDIST = (@VALORTOTAL - @VLRAREBAJAR ) * 100
            IF @VLRDIST <= 15 AND (@NUMITEM > @VLRDIST )
            BEGIN
               SELECT @A = 1
               DECLARE DIST_CURSOR CURSOR FOR
               SELECT  ITEM FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
               OPEN  DIST_CURSOR
               FETCH NEXT FROM DIST_CURSOR
               INTO  @ITEM 
               WHILE @@FETCH_STATUS = 0    
               BEGIN                             
                  UPDATE FNOTD SET VR_TOTAL = VR_TOTAL - 0.01 WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE AND ITEM = @ITEM
                  SELECT @A = @A +1
                  IF @A > @VLRDIST
                  BEGIN
                     BREAK
                  END 
                  FETCH NEXT FROM DIST_CURSOR
                  INTO  @ITEM 
               END
               CLOSE DIST_CURSOR
               DEALLOCATE DIST_CURSOR
            END
         END   
         ELSE
         BEGIN
            IF @VALORTOTAL < @VLRAREBAJAR
            BEGIN
               SELECT @NUMITEM = COALESCE(COUNT(*),0) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
               SELECT @VLRDIST = (@VLRAREBAJAR - @VALORTOTAL ) * 100
               IF @VLRDIST <= 15 AND (@NUMITEM > @VLRDIST )
               BEGIN
                  SELECT @A = 1
                  DECLARE DIST_CURSOR CURSOR FOR
                  SELECT  ITEM FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
                  OPEN  DIST_CURSOR
                  FETCH NEXT FROM DIST_CURSOR
                  INTO  @ITEM 
                  WHILE @@FETCH_STATUS = 0    
                  BEGIN                             
                     UPDATE FNOTD SET VR_TOTAL = VR_TOTAL + 0.01 WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE AND ITEM = @ITEM
                     SELECT @A = @A +1
                     IF @A > @VLRDIST
                     BEGIN
                        BREAK
                     END 
                     FETCH NEXT FROM DIST_CURSOR
                     INTO  @ITEM 
                  END
                  CLOSE DIST_CURSOR
                  DEALLOCATE DIST_CURSOR
               END                 
            END
         END
         */
      END       
   END  
   SELECT @VR_TOTAL = SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   UPDATE FNOT SET VR_TOTAL = CASE WHEN DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU' THEN ROUND(@VR_TOTAL,2) ELSE ROUND(@VR_TOTAL,0) END,DETGENERADOS = 1 WHERE CNSFNOT = @CNSFNOT AND CLASE = @CLASE
   
END
