CREATE OR ALTER PROCEDURE DBO.SPQ_NCINGRET_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@DOCIDEMPLEADO DECIMAL(14,2)       ,@NOMBRES VARCHAR(23)            ,@FECHA DATETIME
      ,@FDESDE DATETIME                   ,@FHASTA DATETIME                ,@ANO VARCHAR(4)
      ,@VLR_UVT DECIMAL(14,2)             ,@ESTADO VARCHAR(20)             ,@PROCESO VARCHAR(20)
      ,@CNSCERTI VARCHAR(20)              ,@NUMDOC VARCHAR(20)             ,@USUCREA VARCHAR(20)
      ,@VLR_TOTAL DECIMAL(14,2)           ,@SUMAS DECIMAL(14,2)            ,@CODRET VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='CRUD_NCINGRET'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
         SELECT @PROCESO=PROCESO, @CNSCERTI=CNSCERTI, @NUMDOC=NUMDOC, @DOCIDEMPLEADO=DOCIDEMPLEADO, @NOMBRES=NOMBRES,
         @FECHA=CONVERT(DATETIME,FECHA),  @FDESDE=CONVERT(DATETIME,FDESDE), @FHASTA=CONVERT(DATETIME,FHASTA),  @ANO=ANO, @VLR_UVT=VLR_UVT, @USUCREA=USUARIO,  @ESTADO=ESTADO       
         FROM   OPENJSON (@DATOS)
         WITH   (       
         PROCESO VARCHAR(20)          '$.PROCESO',
         CNSCERTI VARCHAR(20)          '$.CNSCERTI',
         NUMDOC VARCHAR(20)          '$.NUMDOC',
         DOCIDEMPLEADO DECIMAL(14,2)          '$.DOCIDEMPLEADO',
         NOMBRES VARCHAR(23)          '$.NOMBRES',
         FECHA DATE                  '$.FECHA',
         FDESDE DATE          '$.FDESDE',
         FHASTA DATE          '$.FHASTA',
         ANO VARCHAR(4 )          '$.ANO',
         VLR_UVT DECIMAL(14,2)          '$.VLR_UVT',
         USUARIO VARCHAR(20)          '$.USUARIO',
         ESTADO VARCHAR(20)          '$.ESTADO'
         )
      IF @PROCESO='Nuevo'    
      BEGIN
         IF COALESCE(@CNSCERTI,'')=''
         BEGIN
         BEGIN TRY
            SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO

            PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')  +COALESCE(@COMPANIA,'CIA') 
            SELECT @CNSCERTI=''
		      EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@NCINGRET', @CNSCERTI OUTPUT  
            PRINT '@CNSCERTI='+COALESCE(@CNSCERTI,'')   
		      SELECT @CNSCERTI = @IDSEDE + REPLACE(SPACE(8 - LEN(@CNSCERTI))+LTRIM(RTRIM(@CNSCERTI)),SPACE(1),0)
		      PRINT '@CNSCERTI='+COALESCE(@CNSCERTI,'')                    
         END TRY
         BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            SELECT ERROR AS ERROR FROM  @TBLERRORES 
            RETURN
         END CATCH         
         END
         INSERT INTO NCINGRET (CNSCERTI, NUMDOC, FECHA, FDESDE, FHASTA, ANO, VLR_UVT, USUARIO, ESTADO)
         SELECT @CNSCERTI,@NUMDOC,@FECHA,@FDESDE,@FHASTA,@ANO,@VLR_UVT,@USUARIO,@ESTADO

         PRINT 'CREO EL DETALLE'
         INSERT INTO NCINGRETD(CNSCERTI, CODRET, DESCRIPCION, VLR_TOTAL)
         SELECT @CNSCERTI,CODIGO,DESCRIPCION,0
         FROM TGEN 
         WHERE TABLA='NOMINA'
         AND CAMPO='CERTINGRETE'
      END
      ELSE
      BEGIN
         PRINT 'ACTUALIZANDO EL CERTIFICADO'
         UPDATE NCINGRET SET ANO=@ANO,NUMDOC=@NUMDOC,FDESDE=@FDESDE,FHASTA=@FHASTA WHERE CNSCERTI=@CNSCERTI
      END
      PRINT 'BUSCO LOS VALORES'
      DECLARE CODRET_CURSOR CURSOR FOR 
      SELECT CODIGO
      FROM TGEN 
      WHERE TABLA='NOMINA'
      AND CAMPO='CERTINGRETE'
      ORDER BY CODIGO
      OPEN CODRET_CURSOR    
      FETCH NEXT FROM CODRET_CURSOR    
      INTO @CODRET
      WHILE @@FETCH_STATUS = 0    
      BEGIN 
         SELECT @SUMAS=0
         SELECT @SUMAS=SUM(NIEPED.TOTAL_NOMINA)
         FROM NIEPE INNER JOIN NPER ON NIEPE.CNSPAGO=NPER.CNSPAGO
                     INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
                     INNER JOIN NCON ON NIEPED.CODCONCEPTO=NCON.CODCONCEPTO
         WHERE NIEPE.ANO=@ANO
         AND NIEPE.NUMDOC=@NUMDOC
         AND NCON.CODRET=@CODRET

         IF COALESCE(@SUMAS,0)>0
         BEGIN
            UPDATE NCINGRETD SET VLR_TOTAL=@SUMAS WHERE CNSCERTI=@CNSCERTI AND CODRET=@CODRET
         END
         FETCH NEXT FROM CODRET_CURSOR    
         INTO @CODRET
      END
      CLOSE CODRET_CURSOR
      DEALLOCATE CODRET_CURSOR

      SELECT  'OK'OK
      SELECT CODRET,DESCRIPCION,VLR_TOTAL FROM NCINGRETD  WHERE CNSCERTI=@CNSCERTI
      RETURN
   END   
   IF @METODO='AJUSTA_VRTOTAL'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      
         SELECT   @CNSCERTI=CNSCERTI,@CODRET=CODRET,@VLR_TOTAL=VLR_TOTAL
         FROM   OPENJSON (@DATOS)
         WITH   ( 
         CNSCERTI VARCHAR(20)   '$.CNSCERTI',
         CODRET   VARCHAR(20)   '$.CODRET',
         VLR_TOTAL DECIMAL(14,2)  '$.VLR_TOTAL'
      )
      PRINT '@VLR_TOTAL='+CAST(@VLR_TOTAL AS VARCHAR(20))
      PRINT '@CODRET='+COALESCE(@CODRET,'NADA')
      PRINT '@CNSCERTI='+COALESCE(@CNSCERTI,'NADA')

      IF COALESCE(@VLR_TOTAL,0)>0
      BEGIN
         BEGIN TRY           
            UPDATE NCINGRETD SET VLR_TOTAL=@VLR_TOTAL WHERE CNSCERTI=@CNSCERTI AND CODRET=@CODRET                                
         END TRY
         BEGIN CATCH
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      IF NOT EXISTS(SELECT * FROM @TBLERRORES)
      BEGIN
         SELECT 'OK' OK
      END
      ELSE
      BEGIN
         SELECT 'KO' KO, ERROR FROM @TBLERRORES
      END
   RETURN
   END   
   IF @METODO='TRAE_DETALLE'     
   BEGIN         
      SELECT @CNSCERTI= CNSCERTI        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          CNSCERTI VARCHAR(20)   '$.CNSCERTI'
            )           
   
       SELECT 'OK' OK
       SELECT CODRET,DESCRIPCION,VLR_TOTAL  
       FROM NCINGRETD WHERE CNSCERTI=@CNSCERTI 
       ORDER BY CODRET
      RETURN
   END   
   IF @METODO='RELIQUIDAR_DETA'     
   BEGIN         
      SELECT @CNSCERTI= CNSCERTI        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          CNSCERTI VARCHAR(20)   '$.CNSCERTI'
            )           
            PRINT 'BUSCO LOS VALORES'
         
         SELECT @ANO=ANO,@NUMDOC=NUMDOC FROM NCINGRET WHERE CNSCERTI=@CNSCERTI
         DECLARE CODRET_CURSOR CURSOR FOR 
         SELECT CODIGO
         FROM TGEN 
         WHERE TABLA='NOMINA'
         AND CAMPO='CERTINGRETE'
         ORDER BY CODIGO
         OPEN CODRET_CURSOR    
         FETCH NEXT FROM CODRET_CURSOR    
         INTO @CODRET
         WHILE @@FETCH_STATUS = 0    
         BEGIN 
            --PRINT 'COMIENZO '+@CODRET
            --PRINT '@ANO '+@ANO
            --PRINT '@NUMDOC '+@NUMDOC
            SELECT @SUMAS=0
            SELECT @SUMAS=SUM(NIEPED.TOTAL_NOMINA)
            FROM NIEPE INNER JOIN NPER ON NIEPE.CNSPAGO=NPER.CNSPAGO
                       INNER JOIN NIEPED ON NIEPE.CNSNIEPE=NIEPED.CNSNIEPE AND NIEPE.NUMDOC=NIEPED.NUMDOC
                       INNER JOIN NCON ON NIEPED.CODCONCEPTO=NCON.CODCONCEPTO
            WHERE NIEPE.ANO=@ANO
            AND NIEPE.NUMDOC=@NUMDOC
            AND COALESCE(NCON.CODRET,'')=@CODRET

            IF COALESCE(@SUMAS,0)>0
            BEGIN
               PRINT 'VOY AL UPDATE'
               UPDATE NCINGRETD SET VLR_TOTAL=@SUMAS WHERE CNSCERTI=@CNSCERTI AND CODRET=@CODRET
            END
            FETCH NEXT FROM CODRET_CURSOR    
            INTO @CODRET
         END
         CLOSE CODRET_CURSOR
         DEALLOCATE CODRET_CURSOR
       SELECT 'OK' OK
       SELECT CODRET,DESCRIPCION,VLR_TOTAL  
       FROM NCINGRETD WHERE CNSCERTI=@CNSCERTI 
       ORDER BY CODRET
      RETURN
   END   
   IF @METODO='CERRAR_CERTI'     
   BEGIN         
      SELECT @CNSCERTI= CNSCERTI        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          CNSCERTI VARCHAR(20)   '$.CNSCERTI'
            )           
            PRINT 'BUSCO LOS VALORES'
         
      IF EXISTS(SELECT  * FROM NCINGRET WHERE CNSCERTI=@CNSCERTI AND ESTADO='Abierto')
      BEGIN
         UPDATE  NCINGRET SET ESTADO='Cerrado',USUARIO=@USUARIO WHERE CNSCERTI=@CNSCERTI AND ESTADO='Abierto'
      END
      SELECT 'OK' OK
      RETURN
   END  
   IF @METODO='IMPRIMIR_CERT'     
   BEGIN         
      SELECT @CNSCERTI= CNSCERTI        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          CNSCERTI VARCHAR(20)   '$.CNSCERTI'
            )           
            PRINT 'BUSCO LOS VALORES'
         
      IF EXISTS(SELECT  * FROM NCINGRET WHERE CNSCERTI=@CNSCERTI AND ESTADO='Cerrado')
      BEGIN
         SELECT 'OK' OK,CNSCERTI,CONVERT(VARCHAR,FECHA,103)FECHA,ANO,NEMP.TIPO_DOC,NEMP.DOCIDEMPLEADO,NEMP.PRIMERAPELLIDO,NEMP.SEGUNDOAPELLIDO,NEMP.PRIMERNOMBRE,
               NEMP.SEGUNDONOMBRE,CONVERT(VARCHAR,FDESDE,103)FDESDE,CONVERT(VARCHAR,FHASTA,103)FHASTA,TER.NIT,TER.DV,
               TER.RAZONSOCIAL,CIU.NOMBRE,CIU.DPTO,RIGHT(CIU.CIUDAD,3)MUNICIPIO
         FROM NCINGRET INNER JOIN NEMP ON NCINGRET.NUMDOC=NEMP.NUMDOC,TER 
                      INNER JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
         WHERE NCINGRET.CNSCERTI=@CNSCERTI
         AND TER.IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

         SELECT CODRET,DESCRIPCION,VLR_TOTAL
         FROM NCINGRETD
         WHERE CNSCERTI=@CNSCERTI
         RETURN                
                    
      END
      SELECT 'KO' KO
      RETURN
   END 
   IF @METODO='IMPRIMIR_LIQRET'     
   BEGIN         
      SELECT @CNSCERTI= CNSCERTI        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
          CNSCERTI VARCHAR(20)   '$.CNSCERTI'
            )           
       PRINT 'BUSCO LOS VALORES'  
       SELECT 'OK' OK, T1.NIT AS NIT1,T1.DV AS DV1,T1.RAZONSOCIAL AS RAZONSOCIAL1,TER.NIT,TER.RAZONSOCIAL,'MES '+NIEPE.MES+' '+NIEPE.ANO AS PERIODO,'UVT '+NIEPE.ANO AS UVTANO,
       RETEL.VLRUVT,RETEL.DEVENGOS,RETEL.DEDUCCION,RETEL.RENTAEXEP,RETEL.BASERET,UVTLIQ,VLR_REFTE,
       (SELECT SUM(VLR_ITEM) FROM RETELD   WHERE CNSLIQRET=@CNSCERTI AND CLASE='Resta' AND OBSERVACION LIKE '%PENSION%' AND OBSERVACION  NOT LIKE '%FONDO%' )APENSION,
       (SELECT SUM(VLR_ITEM) FROM RETELD   WHERE CNSLIQRET=@CNSCERTI AND CLASE='Resta' AND OBSERVACION LIKE '%PENSION%' AND OBSERVACION  LIKE '%FONDO%' )AFONDO,
       (SELECT SUM(VLR_ITEM) FROM RETELD   WHERE CNSLIQRET=@CNSCERTI AND CLASE='Resta' AND OBSERVACION LIKE '%SALUD%')ASALUD
       FROM RETEL INNER JOIN TER ON RETEL.IDTERCERO=TER.IDTERCERO
                  LEFT  JOIN NIEPE ON RETEL.NOREFERENCIA=NIEPE.CNSPAGO AND RETEL.IDTERCERO=NIEPE.NUMDOC AND RETEL.PROCEDENCIA='Nomina'
                  ,TER AS T1
       WHERE T1.IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
       AND RETEL.CNSLIQRET=@CNSCERTI

       SELECT CODIGO,OBSERVACION,VLR_ITEM
       FROM RETELD
       WHERE CNSLIQRET=@CNSCERTI
       AND CLASE='Resta'



   END      
END



