CREATE OR ALTER PROCEDURE DBO.SPK_VALIDAR_IZIPAY_JOB
@IDKAPAGE INT = 0,
@CODCAJA VARCHAR(4)= NULL,
@USUCAJA VARCHAR(20)=NULL
WITH ENCRYPTION
AS 
DECLARE @IDKPAGE INT
DECLARE @paymentOrderId VARCHAR(20)
DECLARE @NOADMISION VARCHAR(20)
DECLARE @DPR VARCHAR(20)
DECLARE @SEDE VARCHAR(6)
DECLARE @SEDEV VARCHAR(6) --SEDE FACTURA LINK
DECLARE @USUARIO VARCHAR(20)
DECLARE @IDTERCERO VARCHAR(20)
DECLARE @TIPOFAC   VARCHAR(10)
DECLARE @FECHAFACT  DATETIME
DECLARE @COMPANIA   VARCHAR(2)
DECLARE @PROCEDENCIA VARCHAR(20)
DECLARE @TABLA       VARCHAR(20)
DECLARE @VALOR       DECIMAL(14,2)
DECLARE @FACTURA     VARCHAR(20)
DECLARE @ESTADO      VARCHAR(20)
DECLARE @SQL         VARCHAR(MAX)
DECLARE @CNSFACJ     VARCHAR(20)
DECLARE @CNSACJ      VARCHAR(20)
DECLARE @CNSPCJ      VARCHAR(20)
DECLARE @BCO         VARCHAR(3)
DECLARE @CTA         VARCHAR(40)
DECLARE @SUC         VARCHAR(2)
DECLARE @DATOBCO     VARCHAR(100)
DECLARE @DOCIDAFILIADO	VARCHAR(20),	@NOMBREAFI VARCHAR(200), @NOMBRE_SEDE VARCHAR(20),	@SMS VARCHAR(MAX),		@MENSAJE VARCHAR(MAX)
		,@RAZONSOCIAL	VARCHAR(200),	@LINK VARCHAR(1000),	 @IDAFILIADO VARCHAR(20),	@NUMERO VARCHAR(20),	@NOMBREMEDI			VARCHAR(50)
		,@MODALIDADCIT	VARCHAR(10)	,		@FECHA				DATETIME
BEGIN
   SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@SEDEV=DBO.FNK_VALORVARIABLE('IDSEDE_FACTURA_LINK')
   SELECT @TIPOFAC='Boleta',@FECHAFACT=DBO.FNK_GETDATE()

   DECLARE PG_CURSOR CURSOR FOR 
   SELECT IDKPAGE,CONSECUTIVO,USUCOBRA,RESPONSABLEPAGO,PROCEDENCIA,TABLA,paymentOrderId,VALOR,ESTADO 
   FROM  KPAGE 
   WHERE IDKPAGE=CASE WHEN @IDKAPAGE=0 THEN IDKPAGE ELSE @IDKAPAGE END
   AND ESTADO IN('SEND','RUNNING','PAID')
   AND 1=CASE WHEN ESTADO IN('SEND','RUNNING') THEN 1 ELSE CASE WHEN COALESCE(REF_PAGO,'')='' THEN 1 ELSE 0 END END
   ORDER BY IDKPAGE
   OPEN PG_CURSOR    
   FETCH NEXT FROM PG_CURSOR    
   INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
      PRINT 'Valido el kpage'
      IF @ESTADO<>'PAID'
      BEGIN
         BEGIN TRY           
            EXEC DBO.SPK_GENERA_ORDENPAGO_IZIPAY @NOADMISION,@TABLA,@PROCEDENCIA,@IDTERCERO,@VALOR,'',@USUARIO,@IDKPAGE,'VALIDAR'                 
         END TRY
         BEGIN CATCH
               FETCH NEXT FROM PG_CURSOR    
               INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
               CONTINUE
         END CATCH
      END
      PRINT 'Valido el kpage'
      IF EXISTS(SELECT * FROM KPAGE WHERE IDKPAGE=@IDKPAGE AND ESTADO='PAID' AND COALESCE(REF_PAGO,'')='')
      BEGIN 
         PRINT 'Voy a Generar la Boleta'
         IF NOT EXISTS(SELECT * FROM SED WHERE IDSEDE=@SEDEV)
         BEGIN
            IF @TABLA='CIT'
            BEGIN
               SELECT @SEDE=IDSEDE,@SEDEV=IDSEDE,@IDTERCERO=IDAFILIADO FROM CIT WHERE CONSECUTIVO=@NOADMISION
            END
         END
         ELSE
         BEGIN
            IF @TABLA='CIT'
            BEGIN
                SELECT @SEDE=IDSEDE,@IDTERCERO=IDAFILIADO  FROM CIT WHERE CONSECUTIVO=@NOADMISION
            END
         END
         IF @TABLA='CIT'
         BEGIN
            EXEC SPK_FACTURACE_PERU_COPA @NOADMISION,@DPR,@COMPANIA,@SEDEV, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO   
            SELECT @FACTURA=NULL

            SELECT @FACTURA=COALESCE(NFACTURA,N_FACTURA) FROM CIT WHERE CONSECUTIVO=@NOADMISION

            UPDATE FTR SET IDSEDE=@SEDE WHERE N_FACTURA=@FACTURA
            UPDATE KPAGE SET FACTURADO='Si',REF_PAGO=@FACTURA WHERE IDKPAGE=@IDKPAGE

            PRINT 'Voy a recaudar'
            IF COALESCE(@CODCAJA,'')<>'' AND EXISTS(SELECT * FROM CAJ WHERE CODCAJA=@CODCAJA)
            BEGIN
               SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"INFO_CITA_RECAUDAR","PARAMETROS":{"CONSECUTIVO":"'+@NOADMISION+'","CODCAJA":"'+@CODCAJA+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'
               EXEC SPQ_JSON @SQL

               --
               PRINT 'Verifico la creación del recibo'
               IF EXISTS(SELECT * FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS')
               BEGIN
                  SELECT @CNSFACJ=CNSFACJ,@CNSACJ=CNSACJ FROM FCJ WHERE CODCAJA=@CODCAJA AND NOADMISION=@NOADMISION AND CERRADA=0 AND ESTADO='P' AND USUARIO=@USUCAJA AND PROCEDENCIA='CITAS'

                  UPDATE FCJ SET RECAUDO=1,ENPAGOS=0,N_FACTURA=@FACTURA,IDKPAGE=@IDKPAGE WHERE CNSFACJ=@CNSFACJ AND CNSACJ=@CNSACJ AND CODCAJA=@CODCAJA

	               EXEC SPQ_GENSEQUENCE @SEDE = @SEDE, @PREFIJO = 'PCJ', @LONGITUD = 8, @LLAMADO = NULL, @NVOCONSEC = @CNSPCJ OUTPUT

                  SELECT @CNSPCJ=@SEDE + REPLACE(SPACE(6 - LEN(@CNSPCJ))+LTRIM(RTRIM(@CNSPCJ)),SPACE(1),0)

                  SELECT @DATOBCO=LTRIM(RTRIM(DBO.FNK_VALORVARIABLE('BCO_CTA_SUC_IZIPAY')))

                  SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=1
                  SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=2
                  SELECT @BCO=WORD FROM DBO.FNK_EXPLODE(@DATOBCO,'|') WHERE WORDID=3

                  INSERT INTO PCJ(CODCAJA,CNSPCJ,CNSFACJ,TIPOPAGO,VALOR,FECHA,CNSACJ,BANCO,CTA_BCO,SUCURSAL)
                  SELECT @CODCAJA,@CNSPCJ,@CNSFACJ,DBO.FNK_VALORVARIABLE('IDCJFPAIZIPAY'),@VALOR,DBO.FNK_GETDATE(),@CNSACJ,@BCO,@CTA,@SUC

                  SELECT @SQL='{"MODELO":"CIT_VALIDA","METODO":"CONFIRMAR_RECIBO","PARAMETROS":{"CNSFACJ":"'+@CNSFACJ+'","CODCAJA":"'+@CODCAJA+'","CNSACJ":"'+@CNSACJ+'","INFO":"NO"}, "USUARIO":"'+@USUCAJA+'"}'

                  EXEC SPQ_JSON @SQL
               END
            END
			IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @NOADMISION AND COALESCE(N_FACTURA,'') <> '' AND COALESCE(CIT.MODALIDAD,'') = 'Virtual') 
			BEGIN

				SELECT @IDAFILIADO = CIT.IDAFILIADO, @NOMBREAFI = AFI.NOMBREAFI, @FECHA = FECHA , @MODALIDADCIT = COALESCE(CIT.MODALIDAD,'')
					, @DOCIDAFILIADO = TRIM(AFI.DOCIDAFILIADO),  @NUMERO = DBO.FNK_PrimerMovilTercero(@IDAFILIADO)
					, @NOMBREMEDI=UPPER(REPLACE( COALESCE(LTRIM(RTRIM(MED.PNOMBRE)),''), CHAR(9),'') + ' ' + REPLACE( COALESCE(LTRIM(RTRIM(MED.PAPELLIDO)),''), CHAR(9),'') )
				FROM CIT INNER JOIN AFI ON AFI.IDAFILIADO = CIT.IDAFILIADO
					LEFT JOIN MED ON MED.IDMEDICO=CIT.IDMEDICO
				WHERE CONSECUTIVO = @NOADMISION

				SELECT @NOMBRE_SEDE = DESCRIPCION 
				FROM SED INNER JOIN UBEQ ON UBEQ.IDSEDE = SED.IDSEDE
				INNER JOIN USUSU ON USUSU.SYS_ComputerName = UBEQ.SYS_ComputerName

				SELECT @RAZONSOCIAL = RAZONSOCIAL FROM TER
				WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')

				SELECT @SMS = 'https://meet.jit.si/' + @DOCIDAFILIADO
					+ '\n Hola ' + dbo.FNK_CAPITALIZAR_TEXTO(TRIM(@NOMBREAFI))
					+ ', desde ' + dbo.FNK_CAPITALIZAR_TEXTO(TRIM(@RAZONSOCIAL))
					+ ' ' + dbo.FNK_CAPITALIZAR_TEXTO(TRIM(@NOMBRE_SEDE))
					+ ', estamos contentos de atenderte, accede al siguiente enlace para el dia ' + DBO.FNK_GET_STR_FECHA(@FECHA,NULL,NULL) +
					' a las '+RIGHT(CONVERT(VARCHAR,@FECHA, 100),7)+', con el profesional ' +@NOMBREMEDI 

				--SELECT @SMS = @MENSAJE + @LINK
				--EXEC SPK_SEND_WHATSAPP @NUMERO = @NUMERO, @MENSAJE = @MENSAJE, @LINK = @LINK
				EXEC SPK_SENDSMS @NUMERO, @SMS, 'POST'
			END

         END
      END
      FETCH NEXT FROM PG_CURSOR    
      INTO @IDKPAGE,@NOADMISION,@USUARIO,@IDTERCERO,@PROCEDENCIA,@TABLA,@paymentOrderId,@VALOR,@ESTADO
   END
   CLOSE PG_CURSOR
   DEALLOCATE PG_CURSOR

END



