CREATE OR ALTER PROCEDURE DBO.SPQ_XML_CREA_IEXI @JSON NVARCHAR(MAX)
WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX),@MODELO VARCHAR(100)   ,@METODO VARCHAR(100)
,@USUARIO VARCHAR(12)   ,@COMPANIA VARCHAR(2)      ,@IDSEDE      VARCHAR(5)
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)          ,@DATOS1 VARCHAR(MAX)
      ,@ID_TRX VARCHAR(50)                ,@ID_OPE_LIN VARCHAR(20)         ,@TIP_MOV  VARCHAR(10)
      ,@COD_SEDE VARCHAR(10)              ,@COD_ALM  varchar(20)           ,@COD_ART   varchar(20)
      ,@CANT_ART SMALLINT                 ,@PRE_MED_ART DECIMAL(14,2)      ,@FEC_LOTE DATETIME
      ,@NUM_LOTE VARCHAR(20)              ,@ID_OPE_CAB VARCHAR(20)
      ,@NVOCONSEC VARCHAR(20)
BEGIN
SELECT *
INTO #JSON
FROM OPENJSON(@json) WITH (
MODELO VARCHAR(100) '$.MODELO'
,METODO VARCHAR(100) '$.METODO'
,USUARIO VARCHAR(12) '$.USUARIO'
,PARAMETROS NVARCHAR(MAX) AS JSON
)


SELECT   @MODELO = MODELO,@METODO = METODO
,@PARAMETROS = PARAMETROS,@USUARIO = USUARIO
FROM #JSON

   IF @METODO='COMPRA_ARTICULO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS VARCHAR(MAX)
      )
      SELECT @DATOS1=@DATOS
      SELECT @DATOS=REPLACE(@DATOS,'ns1:','')
      SELECT @DATOS=REPLACE(@DATOS,' xmlns:ns1="http://integrador.clinicainternacional.com.pe/Traspaso"','')
      SELECT @DATOS=dbo.FNK_LIMPIATEXTO(@DATOS,'0-9 A-Z </>:.=_"')

      DECLARE @XmlDocumentHandle int;

      EXEC sp_xml_preparedocument @XmlDocumentHandle OUTPUT, @DATOS;

     SELECT @ID_TRX=ID_TRX,@ID_OPE_CAB=ID_OPE_CAB,@ID_OPE_LIN=ID_OPE_LIN,@TIP_MOV=TIP_MOV,@COD_SEDE=COD_SEDE,@COD_ALM=COD_ALM,
            @COD_ART=COD_ART,@CANT_ART=CANT_ART,@PRE_MED_ART=CONVERT(DECIMAL(14,2),PRE_MED_ART),
            @FEC_LOTE=CONVERT(DATETIME,CONVERT(DATE,LEFT(FEC_LOTE,4)+'/'+RIGHT(LEFT(FEC_LOTE,6),2)+'/'+RIGHT(FEC_LOTE,2))),
            @NUM_LOTE=NUM_LOTE
     FROM OPENXML (@XmlDocumentHandle, '/Traspaso',2)
               WITH (ID_TRX VARCHAR(50),  
                     ID_OPE_CAB VARCHAR(20),
                     ID_OPE_LIN VARCHAR(20),
                     TIP_MOV  VARCHAR(10),
                     COD_SEDE VARCHAR(10),
                     COD_ALM  varchar(20),
                     COD_ART   varchar(20),
                     CANT_ART   varchar(10),
                     PRE_MED_ART VARCHAR(20),
                     FEC_LOTE VARCHAR(20),
                     NUM_LOTE VARCHAR(20)
                     );
     EXEC sp_xml_removedocument @XmlDocumentHandle;

     PRINT 'Comienzo las validaciones'
     IF EXISTS(SELECT * FROM IMOV WHERE OBSERVACION=@ID_TRX AND SYS_ComputerName='INTERFAXINV')
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'ID de la transacción de SAP ya fue procesada... @ID_TRX='+@ID_TRX
     END
     IF EXISTS(SELECT * FROM IMOV WHERE NODOCUMENTO=@ID_OPE_CAB AND SYS_ComputerName='INTERFAXINV')
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'ID que viene de SAP cabecera ya fue procesada... @ID_OPE_CAB='+@ID_OPE_CAB+' @ID_TRX='+@ID_TRX
     END
     IF NOT EXISTS(SELECT * FROM IART WHERE IDARTICULO=@COD_ART)
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'ID Articulo no existe en el Maestro de Articulos, @COD_ART='+@COD_ART+' @ID_TRX='+@ID_TRX
     END
     IF COALESCE(@CANT_ART,0)<=0
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'La Cantidad del Articulo no puede ser Menor o Igual a cero @ID_TRX='+@ID_TRX
     END
     IF COALESCE(@FEC_LOTE,'')='' OR @FEC_LOTE< DBO.FNK_GETDATE()+30
     BEGIN
       INSERT INTO @TBLERRORES(ERROR)
       SELECT 'Fecha de Vencimiento no Valida, debe ser mayor o Igal a 30 Dias de la fecha actual @FEC_LOTE='+CONVERT(varchar,@FEC_LOTE,103)
     END
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
        SELECT TOP 1 DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_MOV='501' THEN 'COMPRA' ELSE 'DEVOL' END,@DATOS1,@DATOS,ERROR,'ERRORES',@NVOCONSEC,@COD_ART FROM @TBLERRORES

        SELECT 'KO' OK, ERROR FROM @TBLERRORES
        RETURN
     END
     BEGIN TRY           
         EXEC SPK_GENCONSECUTIVO @COMPANIA,'01','@MOV',@NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = '01' + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         PRINT '@NVOCONSEC='+@NVOCONSEC

         INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                           FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                           IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
                           OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                           CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                           USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                           SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP,CODUNG,CODPRG,CLASEPED)  
         SELECT @NVOCONSEC,'18' ,CASE WHEN @TIP_MOV='501' THEN DBO.FNK_VALORVARIABLE('IDINVMOV_REMISION_EN') ELSE DBO.FNK_VALORVARIABLE('IDINVDEVPROVEEDOR') END
                , @ID_OPE_CAB, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                  '10401HDFAR','INTERXML',DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') , 'INTERXML',NULL, NULL, 0, NULL, NULL,
                  @ID_TRX,NULL, 0,RIGHT(LTRIM(RTRIM(@ID_OPE_LIN)),16), '4115',0, NULL, 'SALUD', 'INTERXML',
                  NULL, NULL, 0, NULL, 1, 'INTERFAXINV', 0, NULL, 0, NULL,NULL,NULL,NULL

  
         INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                           NOLOTE, NOLOTEPEDIDO,FECHAVENCE, ESTADO, IDARTICULOTF,
                           CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                           USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                           CANTIDADORI, TIENECAMBIO, IDITAR,IDSERVICIO)
         SELECT @NVOCONSEC, IART.IDARTICULO, IART.EXISTOTAL, @CANT_ART,  @CANT_ART, @PRE_MED_ART,  
                  @NUM_LOTE, @NUM_LOTE,@FEC_LOTE,0, NULL, NULL, NULL, NULL,1,0, 
                  'INTERXML', NULL, NULL, 0, NULL, NULL, NULL, 0, IART.IDITAR,IART.IDSERVICIO
         FROM IART WHERE IDARTICULO=@COD_ART

         IF @TIP_MOV='501'
         BEGIN 
            EXEC SPK_CONFIRMARENTRADAS '18',@NVOCONSEC,'INTERXML','01','01','INTERFAXINV'
         END
         ELSE
         BEGIN
            EXEC SPK_CONFIRMARSALIDAS '18',@NVOCONSEC,'INTERXML','01','01'
         END
     END TRY
     BEGIN CATCH
             INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
     END CATCH
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
        SELECT TOP 1 DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_MOV='501' THEN 'COMPRA' ELSE 'DEVOL' END,@DATOS1,@DATOS,ERROR,'ERRORES',@NVOCONSEC,@COD_ART FROM @TBLERRORES

        SELECT 'KO' OK, ERROR FROM @TBLERRORES
        RETURN
     END

     INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
     SELECT DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_MOV='501' THEN 'COMPRA' ELSE 'DEVOL' END,@DATOS1,@DATOS,'OK','ERRORES',@NVOCONSEC,@COD_ART 

     SELECT 'OK' OK
     RETURN 
   END
END