IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_GEN_TRAMAS_PERU' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_GEN_TRAMAS_PERU
END
GO
CREATE PROCEDURE DBO.SPK_GEN_TRAMAS_PERU 
@ENVIO VARCHAR(6) 
WITH ENCRYPTION
AS  
DECLARE @EXISTE INT
DECLARE @IDSSEGU VARCHAR(20)
DECLARE @NITIPS  VARCHAR(20)
   DECLARE 
    @VLR_HONOR_SIN_IGV      DECIMAL(14,2)
   ,@VLR_ODONTO_SIN_IGV     DECIMAL(14,2)
   ,@VLR_HSCT_SIN_IGV       DECIMAL(14,2)
   ,@VLR_LAB_SIN_IGV        DECIMAL(14,2)
   ,@VLR_RX_SIN_IGV         DECIMAL(14,2)
   ,@VLR_INV_SIN_IGV        DECIMAL(14,2)
   ,@VLR_PROTESIS_SIN_IGV   DECIMAL(14,2)
   ,@VLR_OTROS_SIN_IGV      DECIMAL(14,2)
   ,@VLR_MED_EXONE          DECIMAL(14,2)
   ,@BASEIMP                DECIMAL(14,2)
   ,@IDSER                  VARCHAR(20)
   ,@DIF                    DECIMAL(14,2)
   ,@SUMADETALLE            DECIMAL(14,2)
   ,@ITEM                   INT
   ,@N_FACTURA              VARCHAR(20)
BEGIN

   DELETE TRAMA_DATE WHERE IDTRAMA=@ENVIO
   DELETE TRAMA_DSER WHERE IDTRAMA=@ENVIO
   DELETE TRAMA_DFAC WHERE IDTRAMA=@ENVIO
   DELETE TRAMA_DFAR WHERE IDTRAMA=@ENVIO

   SELECT @IDSSEGU=COALESCE(IDALTERNA2,NIT),@NITIPS=NIT FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')


  INSERT INTO TRAMA_DFAC(IDTRAMA, F_ENVIO, NUM_LOTE, COD_IAFAS, IDRUC, COD_IPRESS, TDOC_PAGO, NUMDOC_PAGO, F_EMISION, PRODUCTO, 
                            N_PRESTACIONES, MPAGO, SUB_MPAGO, VLR_PREPACTADO, F_INICIO_PER, TMONEDA, VLR_EXONERADO,  VLR_COPAGO_FIJO, 
                            VLR_COPAGO_FIJO_EX, VLR_COPAGO_VAR, VLR_COPAGO_VAR_EX, VLR_BASEIMP, VLR_IGV, VLR_TOTAL, CLASE, CNSFNOT, 
                            VLR_TOTAL_NOTA, F_NOTA, M_NOTA, F_PENVIO_FTR, IND_FTR )
   SELECT @ENVIO,RIPS.FECHAENVIO,REPLACE(SPACE(7-LEN(RIPS.ENVIO)),SPACE(1),0)+RIPS.ENVIO,LEFT(COALESCE(TER.IDALTERNA2,NIT),5),LEFT(@NITIPS,11),COALESCE(DBO.FNK_BUSCA_RENIPRESS(FTR.N_FACTURA),LEFT(@IDSSEGU,8)),'01',
   SUBSTRING(FTR.N_FACTURA,0,5)+REPLACE(SPACE(8-LEN(RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5))),SPACE(1),0)+RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5) N_FACTURA,
   FTR.F_FACTURA,CASE WHEN COALESCE(S.NAUTORIZACION,'')<> '' THEN S.PRODUCTO ELSE 
   CASE WHEN FTR.IDTERCERO IN('0100003516','') THEN '99999' ELSE CASE WHEN COALESCE(AFI.SISBENNIVEL,1)=1 THEN '02' WHEN COALESCE(AFI.SISBENNIVEL,3)=3 THEN '03' ELSE'02' END END END,
   REPLACE(SPACE(5-LEN('1')),SPACE(1),0)+LTRIM(RTRIM(STR(1))),
   CASE WHEN COALESCE(FTR.PAQUETE,0)=1 THEN '02'ELSE '01' END,CASE WHEN COALESCE(FTR.PAQUETE,0)=1 THEN '011'ELSE '999' END,
   CASE WHEN COALESCE(FTR.PAQUETE,0)<>1 THEN 0.00 ELSE CASE WHEN COALESCE(FTR.VIVA,0)>0 
        THEN  COALESCE(FTR.VALORCOPAGO,0.00)ELSE 0.00 END +FTR.VR_TOTAL-COALESCE(FTR.VIVA,0) END 
   ,CASE WHEN COALESCE(FTR.PAQUETE,0)=1 THEN COALESCE(S.FAUTORIZA,(SELECT MIN(FTRD.FECHAPREST)FROM FTRD WHERE FTRD.N_FACTURA=FTR.N_FACTURA)) ELSE NULL END,1,
   CASE WHEN COALESCE(FTR.VIVA,0)<=0 THEN FTR.VALORSERVICIOS ELSE 0.00 END
   ,0.00,0.00,
   CASE WHEN COALESCE(FTR.VIVA,0)>0 THEN  COALESCE(FTR.VALORCOPAGO,0.00)ELSE 0.00 END,
   CASE WHEN COALESCE(FTR.VIVA,0)<=0 THEN  COALESCE(FTR.VALORCOPAGO,0.00)ELSE 0.00 END,
   CASE WHEN COALESCE(FTR.VIVA,0)>0 THEN FTR.VR_TOTAL-(COALESCE(FTR.VIVA,0)) ELSE 0.00 END,
   COALESCE(FTR.VIVA,0),FTR.VR_TOTAL ,'N',NULL,NULL,NULL,NULL,NULL,'N'
   FROM RIPSD INNER JOIN RIPS ON RIPSD.ENVIO=RIPS.ENVIO
              INNER JOIN FTR ON RIPSD.N_FACTURA=FTR.N_FACTURA
              INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
              LEFT JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
              LEFT JOIN AFI  ON FTR.IDAFILIADO=AFI.IDAFILIADO
              LEFT JOIN TRAMA_SITEDS S ON FTR.VENDEDOR=S.NAUTORIZACION
   WHERE RIPSD.ENVIO=@ENVIO
   ORDER BY RIPSD.N_FACTURA



    INSERT INTO TRAMA_DATE (IDTRAMA, IDRUC, COD_IPRESS, TDOC_PAGO, NUMDOC_PAGO, CORRELATIVO, CODINTERNO, TIPO_AFILIADO, COD_ASE_PACIENTE, 
               TIPO_DOC_AFI, DOC_AFILIADO, NUM_HCA, DOC_AUT, NUM_AUT, DOC_AUT2, NUM_AUT2,  TCOBERTURA, SUB_COBERTURA, IDDX, IDDX2, IDDX3, F_PRESTACION, 
               TIPO_PROF_RESPONSABLE, NUM_CPRP, TIPO_DOC, NUM_DOC, IDRUC_REF, F_TRANSFERENCIA, TIPO_HOSP, F_INGRESO, F_EGRESO, TIPO_EGRESO,  
               DIAS_ESTANCIA, VLR_HONOR_SIN_IGV , VLR_ODONTO_SIN_IGV, VLR_HSCT_SIN_IGV, VLR_LAB_SIN_IGV, VLR_RX_SIN_IGV, VLR_INV_SIN_IGV, 
               VLR_PROTESIS_SIN_IGV, VLR_OTROS_SIN_IGV, COPAGO_FIJO,  COPAGO_FIJO_EXO, COPAGO_VAR, COPAGO_VAR_EXO, TOTAL_GASTOS,VLR_MED_EXONE
               )

   SELECT  @ENVIO,LEFT(@NITIPS,11),COALESCE(DBO.FNK_BUSCA_RENIPRESS(FTR.N_FACTURA),LEFT(@IDSSEGU,8)),'01',SUBSTRING(FTR.N_FACTURA,0,5)+REPLACE(SPACE(8-LEN(RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5))),SPACE(1),0)+RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5) N_FACTURA,
   REPLACE(SPACE(5-LEN('1')),SPACE(1),0)+LTRIM(RTRIM(STR(1))),COALESCE(DBO.FNK_BUSCA_RENIPRESS(FTR.N_FACTURA),LEFT(@IDSSEGU,8)),COALESCE(AFI.SISBENNIVEL,1),COALESCE(AFI.IDALTERNA,AFI.DOCIDAFILIADO),TGEN.VALOR1,
   AFI.DOCIDAFILIADO, RIGHT(FTR.NOREFERENCIA,8),'01',COALESCE(FTR.VENDEDOR,''),'99','','1','289',--COALESCE(HADMAUT.TIPOCOBER,'1'),COALESCE(HADMAUT.SUBTIPOCOBER,'289'),--tipocites
   DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'DXHC1'),NULL,--DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'DXHC2'),
   NULL,-- DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'DXHC3'),
   MIN(FTRD.FECHAPREST),COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'TIPO_RES'),'00'),LEFT(COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'N_REG'),''),6),
   COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'TIPO_DOC'),''),COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'IDMEDICO'),''),--fechaatencion
   LEFT(DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),11),NULL,'',NULL,NULL,'','',
   SUM(CASE WHEN PRE.CODRUBRO='02' THEN FTRD.VLR_SERVICI -COALESCE(FTRD.VIVA,0) ELSE 0.00 END),
   0.00,
   SUM(CASE WHEN PRE.CODRUBRO='03' THEN FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0) ELSE 0.00 END),
   SUM(CASE WHEN PRE.CODRUBRO='04' THEN FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0) ELSE 0.00 END),
   SUM(CASE WHEN PRE.CODRUBRO='06' THEN FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0) ELSE 0.00 END),
   SUM(CASE WHEN PRE.CODRUBRO='05' AND COALESCE(FTRD.VIVA,0)>0 THEN FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0) ELSE 0.00 END),0.00,
   SUM(CASE WHEN PRE.CODRUBRO='15' THEN FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0) ELSE 0.00 END),
   --SUM(CASE WHEN COALESCE(PPT.COPAGOIND,0)=1 AND COALESCE(FTRD.VIVA,0)>0  THEN COALESCE(FTRD.VLR_COPAGOS,0.00) ELSE 0.00 END),
   --SUM(CASE WHEN COALESCE(PPT.COPAGOIND,0)=1 AND COALESCE(FTRD.VIVA,0)<=0  THEN COALESCE(FTRD.VLR_COPAGOS,0.00) ELSE 0.00 END),
   --SUM(CASE WHEN COALESCE(PPT.COPAGOIND,0)=0 AND COALESCE(FTRD.VIVA,0)>0  THEN COALESCE(FTRD.VLR_COPAGOS,0.00) ELSE 0.00 END),
   --SUM(CASE WHEN COALESCE(PPT.COPAGOIND,0)=0 AND COALESCE(FTRD.VIVA,0)<=0  THEN COALESCE(FTRD.VLR_COPAGOS,0.00) ELSE 0.00 END),
   0.00,0.00,
   SUM(CASE WHEN COALESCE(FTRD.VIVA,0)>0  THEN COALESCE(FTRD.VLR_COPAGOS,0.00) ELSE 0.00 END),
   SUM(CASE WHEN COALESCE(FTRD.VIVA,0)<=0  THEN COALESCE(FTRD.VLR_COPAGOS,0.00) ELSE 0.00 END),
   SUM(FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0)),
   SUM(CASE WHEN PRE.CODRUBRO='05' AND COALESCE(FTRD.VIVA,0)<=0 THEN FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0) ELSE 0.00 END)
   FROM RIPSD INNER JOIN RIPS ON RIPSD.ENVIO=RIPS.ENVIO
              INNER JOIN FTR ON RIPSD.N_FACTURA=FTR.N_FACTURA
              INNER JOIN FTRD ON FTR.N_FACTURA=FTRD.N_FACTURA
              INNER JOIN PRE ON FTRD.PREFIJO=PRE.PREFIJO
              INNER JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
              INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
              LEFT JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
              LEFT JOIN TGEN ON AFI.TIPO_DOC=TGEN.CODIGO AND TGEN.TABLA='General' AND TGEN.CAMPO='TIPOIDENT'
              LEFT JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
   WHERE RIPSD.ENVIO=@ENVIO
	AND NOT EXISTS(SELECT * FROM ESP WHERE ESP.IDPROVEEDOR=FTR.IDTERCERO AND FTR.IDPLAN=ESP.IDPLAN AND FTRD.REFERENCIA=ESP.IDSERVICIO AND COALESCE(ESP.PAQUETE,0)=1)
   GROUP BY FTR.N_FACTURA,COALESCE(AFI.SISBENNIVEL,1),AFI.IDALTERNA,TGEN.VALOR1,
   AFI.DOCIDAFILIADO, RIGHT(FTR.NOREFERENCIA,8),FTR.VENDEDOR,DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'DXHC1'),
   FTR.F_FACTURA,COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'TIPO_RES'),'00'),LEFT(COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'N_REG'),''),6),
   COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'TIPO_DOC'),''),COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'IDMEDICO'),'')
   ORDER BY FTR.N_FACTURA

   PRINT 'PRIMER UPDATE'
   UPDATE TRAMA_DATE SET  TCOBERTURA=CASE WHEN ISNUMERIC(HADMAUT.TIPOCOBER)=0 THEN 0 ELSE HADMAUT.TIPOCOBER END , SUB_COBERTURA =LEFT(HADMAUT.SUBTIPOCOBER,3),
   DOC_AUT=CASE WHEN COALESCE(HADMAUT.TIPOCITES,'')='' THEN  DOC_AUT ELSE LEFT(HADMAUT.TIPOCITES,2) END
   FROM TRAMA_DATE INNER JOIN HADMAUT ON TRAMA_DATE.NUM_AUT=HADMAUT.AUTORIZACION
   WHERE TRAMA_DATE.IDTRAMA=@ENVIO

   PRINT 'SEGUNDO UPDATE '

   UPDATE TRAMA_DATE SET  TCOBERTURA=CASE WHEN ISNUMERIC(S.TIPO)=0 THEN 0 ELSE S.TIPO END , SUB_COBERTURA =LEFT(S.SUBTIPO,3),
   DOC_AUT=CASE  WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN '01' ELSE CASE WHEN  COALESCE(HADMAUT.TIPOCITES,'')='' THEN  DOC_AUT ELSE LEFT(HADMAUT.TIPOCITES,2) END END,
   F_PRESTACION=CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.FAUTORIZA ELSE F_PRESTACION END ,
   TIPO_DOC= CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.TIPODOC ELSE TIPO_DOC END,
   DOC_AFILIADO=CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.DOCIDAFILIADO ELSE DOC_AFILIADO END,
  -- COD_IPRESS=CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.RENIPRESS ELSE COD_IPRESS END,
  -- CODINTERNO=CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.RENIPRESS ELSE CODINTERNO END,
   COD_ASE_PACIENTE=CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.CODASEG ELSE COD_ASE_PACIENTE END
   FROM TRAMA_DATE INNER JOIN TRAMA_SITEDS S  ON TRAMA_DATE.NUM_AUT=S.NAUTORIZACION
                   INNER JOIN HADMAUT  ON TRAMA_DATE.NUM_AUT=HADMAUT.AUTORIZACION
   WHERE TRAMA_DATE.IDTRAMA=@ENVIO

   DECLARE TRAMAFAC_CURSOR CURSOR FOR 
   SELECT NUMDOC_PAGO, CASE WHEN COALESCE(VLR_BASEIMP,0)>0 THEN COALESCE(VLR_BASEIMP,0)  ELSE COALESCE(VLR_EXONERADO,0) END  FROM TRAMA_DFAC 
   WHERE IDTRAMA=@ENVIO
   AND COALESCE(VLR_PREPACTADO,0)=0
   ORDER BY NUMDOC_PAGO
   OPEN TRAMAFAC_CURSOR    
   FETCH NEXT FROM TRAMAFAC_CURSOR    
   INTO @N_FACTURA,@BASEIMP
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
      SELECT @DIF=(TOTAL_GASTOS-(COPAGO_FIJO+COPAGO_FIJO_EXO+COPAGO_VAR))-@BASEIMP
      FROM TRAMA_DATE
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA
      PRINT '@DIF 1='+CAST(@DIF AS VARCHAR(20))
      IF COALESCE(@DIF,0)<>0
      BEGIN
         IF @DIF<0
         BEGIN
            UPDATE TRAMA_DATE SET TOTAL_GASTOS=TOTAL_GASTOS+@DIF
            WHERE IDTRAMA=@ENVIO
            AND NUMDOC_PAGO=@N_FACTURA
         END
         ELSE
         BEGIN
            UPDATE TRAMA_DATE SET TOTAL_GASTOS=TOTAL_GASTOS-@DIF
            WHERE IDTRAMA=@ENVIO
            AND NUMDOC_PAGO=@N_FACTURA
         END
      END
      PRINT 'DEFAC @N_FACTURA ='+@N_FACTURA
      SELECT @DIF=(VLR_HONOR_SIN_IGV+VLR_ODONTO_SIN_IGV+VLR_HSCT_SIN_IGV+VLR_LAB_SIN_IGV+VLR_RX_SIN_IGV+
			VLR_INV_SIN_IGV+VLR_PROTESIS_SIN_IGV+VLR_OTROS_SIN_IGV+VLR_MED_EXONE)-TOTAL_GASTOS
      FROM TRAMA_DATE
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA

      PRINT '@DIF ='+CAST(COALESCE(@DIF,0) AS VARCHAR(20))
      IF COALESCE(@DIF,0)<0
      BEGIN
         IF EXISTS(SELECT *  FROM TRAMA_DATE  WHERE IDTRAMA=@ENVIO  AND NUMDOC_PAGO=@N_FACTURA AND VLR_INV_SIN_IGV>0)
         BEGIN
            UPDATE TRAMA_DATE SET VLR_INV_SIN_IGV=VLR_INV_SIN_IGV+ABS(@DIF)  WHERE IDTRAMA=@ENVIO  AND NUMDOC_PAGO=@N_FACTURA AND VLR_INV_SIN_IGV>0
         END
         ELSE
         BEGIN
            UPDATE TRAMA_DATE SET VLR_LAB_SIN_IGV=VLR_LAB_SIN_IGV+ABS(@DIF)  WHERE IDTRAMA=@ENVIO  AND NUMDOC_PAGO=@N_FACTURA AND VLR_INV_SIN_IGV>0
         END
      END
      ELSE
      BEGIN
         IF EXISTS(SELECT *  FROM TRAMA_DATE  WHERE IDTRAMA=@ENVIO  AND NUMDOC_PAGO=@N_FACTURA AND VLR_INV_SIN_IGV>0)
         BEGIN
            UPDATE TRAMA_DATE SET VLR_INV_SIN_IGV=VLR_INV_SIN_IGV-ABS(@DIF)  WHERE IDTRAMA=@ENVIO  AND NUMDOC_PAGO=@N_FACTURA AND VLR_INV_SIN_IGV>0
         END
         ELSE
         BEGIN
            UPDATE TRAMA_DATE SET VLR_LAB_SIN_IGV=VLR_LAB_SIN_IGV-ABS(@DIF)  WHERE IDTRAMA=@ENVIO  AND NUMDOC_PAGO=@N_FACTURA AND VLR_INV_SIN_IGV>0
         END
      END
      FETCH NEXT FROM TRAMAFAC_CURSOR    
      INTO @N_FACTURA,@BASEIMP
   END
   CLOSE TRAMAFAC_CURSOR
   DEALLOCATE TRAMAFAC_CURSOR

   --

   INSERT INTO TRAMA_DSER(IDTRAMA, IDRUC, COD_IPRESS, TDOC_PAGO, NUMDOC_PAGO,CORRELATIVO,CORRE_PRESTA, TIPO_CLASIFICACION, IDSERVICIO, DESCSERVICIO, 
               FECHA_PROC, IDEMEDICA, NUM_CPR, TIPO_DOC_PRO, IDMEDICO, CANTIDAD, VLR_UNITARIO,  VLRCOPAGO_VARIABLE, VLRCOPAGO_FIJO, VLR_TOTAL, 
               VLR_NOCUBIERTO, IDDX, SER_EXENTO, COD_RUBRO )

   SELECT @ENVIO,LEFT(@NITIPS,11),COALESCE(DBO.FNK_BUSCA_RENIPRESS(FTR.N_FACTURA),LEFT(@IDSSEGU,8)),'01',
   SUBSTRING(FTR.N_FACTURA,0,5)+REPLACE(SPACE(8-LEN(RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5))),SPACE(1),0)+RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5) N_FACTURA,
   REPLACE(SPACE(5-LEN(1)),SPACE(1),0)+LTRIM(RTRIM(STR(1))),
   REPLACE(SPACE(4-LEN(FTRD.N_CUOTA)),SPACE(1),0)+LTRIM(RTRIM(STR(FTRD.N_CUOTA))),
   COALESCE(PRE.TIPOTRMA,'03'),LEFT(SER.CODCUPS,10),LEFT(SER.DESCRIPCION_CUPS,70)DESCSERVICIO,CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.FAUTORIZA ELSE  FTRD.FECHA END,
   COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'TIPO_RES'),'00'),
   COALESCE(LEFT(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'N_REG'),6),''),
   DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'TIPO_DOC'),
   COALESCE(DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'IDMEDICO'),''),
   CONVERT(INT,FTRD.CANTIDAD),--REPLACE(SPACE(5-LEN(CONVERT(INT,FTRD.CANTIDAD))),SPACE(1),0)+LTRIM(RTRIM(STR(FTRD.CANTIDAD))),
   FTRD.VALOR,COALESCE(FTRD.VLR_COPAGOS,0.00),0.00,FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0),0.00,DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'DXHC1'),
   'A',COALESCE(PRE.CODRUBRO,'02')
   FROM RIPSD INNER JOIN RIPS ON RIPSD.ENVIO=RIPS.ENVIO
              INNER JOIN FTR ON RIPSD.N_FACTURA=FTR.N_FACTURA
              INNER JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
              INNER JOIN FTRD ON FTR.N_FACTURA=FTRD.N_FACTURA AND RIPSD.N_FACTURA=FTRD.N_FACTURA
              INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
              INNER JOIN SER ON FTRD.REFERENCIA=SER.IDSERVICIO
              INNER JOIN PRE ON SER.PREFIJO=PRE.PREFIJO
              LEFT JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
              LEFT JOIN TGEN ON AFI.TIPO_DOC=TGEN.CODIGO AND TGEN.TABLA='General' AND TGEN.CAMPO='TIPOIDENT'
              LEFT JOIN TRAMA_SITEDS S ON FTR.VENDEDOR=S.NAUTORIZACION
   WHERE RIPSD.ENVIO=@ENVIO
   AND COALESCE(SER.MEDICAMENTOS,0)<>1
   AND NOT EXISTS(SELECT * FROM ESP WHERE ESP.IDPROVEEDOR=FTR.IDTERCERO AND FTR.IDPLAN=ESP.IDPLAN AND FTRD.REFERENCIA=ESP.IDSERVICIO AND COALESCE(ESP.PAQUETE,0)=1)
   ORDER BY RIPSD.N_FACTURA

   INSERT INTO TRAMA_DFAR (IDTRAMA, IDRUC, COD_IPRESS, TDOC_PAGO, NUMDOC_PAGO, CORRELATIVO, CORRE_PRESTA, TPRODUC, 
   TCATALOGO, IDSERVICIO, FDISPENSA, CANTIDAD, TDISPENSA, VLRUNITA, VLCOPAGO, VLTOTAL, VLNOCUBIERTO,  IDDX, EXENTO, 
   GUIAENTREGA)
   SELECT @ENVIO,LEFT(@NITIPS,11),COALESCE(DBO.FNK_BUSCA_RENIPRESS(FTR.N_FACTURA),LEFT(@IDSSEGU,8)),'01',
   SUBSTRING(FTR.N_FACTURA,0,5)+REPLACE(SPACE(8-LEN(RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5))),SPACE(1),0)+RIGHT(FTR.N_FACTURA,LEN(FTR.N_FACTURA)-5) N_FACTURA,
   REPLACE(SPACE(5-LEN(1)),SPACE(1),0)+LTRIM(RTRIM(STR(1))),
   REPLACE(SPACE(4-LEN(FTRD.N_CUOTA)),SPACE(1),0)+LTRIM(RTRIM(STR(FTRD.N_CUOTA))),
   CASE WHEN FTRD.PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS') and ANEXO NOT LIKE '%AGUJA%' THEN  'M' ELSE 'I' END,
   CASE WHEN FTRD.PREFIJO=DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS') and ANEXO NOT LIKE '%AGUJA%' THEN  1 ELSE 2 END,LEFT(SER.CODCUPS,13),CASE WHEN COALESCE(S.NAUTORIZACION,'')<>'' THEN S.FAUTORIZA ELSE  FTRD.FECHA END,
   CONVERT(INT,FTRD.CANTIDAD),1,COALESCE(FTRD.VALOR,0),CONVERT(DECIMAL(14,2),COALESCE(FTRD.VLR_COPAGOS,0)),CONVERT(DECIMAL(14,2),FTRD.VLR_SERVICI-COALESCE(FTRD.VIVA,0)),
   0, DBO.FNK_BUSCADATOSTRAMAS(RIPSD.N_FACTURA,'DXHC1'),
   CASE WHEN COALESCE(FTRD.VIVA,0)>0 THEN 'A' ELSE 'D' END,
   FTRD.NOPRESTACION
   FROM RIPSD INNER JOIN RIPS ON RIPSD.ENVIO=RIPS.ENVIO
              INNER JOIN FTR ON RIPSD.N_FACTURA=FTR.N_FACTURA
              INNER JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
              INNER JOIN FTRD ON FTR.N_FACTURA=FTRD.N_FACTURA AND RIPSD.N_FACTURA=FTRD.N_FACTURA
              INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
              INNER JOIN SER ON FTRD.REFERENCIA=SER.IDSERVICIO
              INNER JOIN PRE ON SER.PREFIJO=PRE.PREFIJO
               LEFT JOIN TRAMA_SITEDS S ON FTR.VENDEDOR=S.NAUTORIZACION
   WHERE RIPSD.ENVIO=@ENVIO
    AND (COALESCE(SER.MEDICAMENTOS,0)=1 OR ISNULL(PRE.MINVENTARIOS,0)=1)
   ORDER BY RIPSD.N_FACTURA


              
       
   PRINT 'VALIDO POR GRUPOS SEGUN TRAMAS_DATE'
   DECLARE TRAMDATE_CURSOR CURSOR FOR 
   SELECT NUMDOC_PAGO, VLR_HONOR_SIN_IGV , VLR_ODONTO_SIN_IGV, VLR_HSCT_SIN_IGV, VLR_LAB_SIN_IGV, VLR_RX_SIN_IGV, VLR_INV_SIN_IGV, 
               VLR_PROTESIS_SIN_IGV, VLR_OTROS_SIN_IGV,VLR_MED_EXONE
   FROM TRAMA_DATE
   WHERE IDTRAMA=@ENVIO
   ORDER BY NUMDOC_PAGO
   OPEN TRAMDATE_CURSOR    
   FETCH NEXT FROM TRAMDATE_CURSOR    
   INTO @N_FACTURA, @VLR_HONOR_SIN_IGV ,@VLR_ODONTO_SIN_IGV  ,@VLR_HSCT_SIN_IGV   ,@VLR_LAB_SIN_IGV ,@VLR_RX_SIN_IGV ,@VLR_INV_SIN_IGV,@VLR_PROTESIS_SIN_IGV,@VLR_OTROS_SIN_IGV,@VLR_MED_EXONE 
   WHILE @@FETCH_STATUS = 0    
   BEGIN 
      PRINT 'COMIENZO '+@N_FACTURA
      PRINT 'CODRUBRO=02'
      SET @SUMADETALLE=0
      SELECT @SUMADETALLE=SUM(VLR_TOTAL)
      FROM TRAMA_DSER
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA
      AND COD_RUBRO='02'
      IF @SUMADETALLE-@VLR_HONOR_SIN_IGV<>0
      BEGIN
         SELECT @DIF=@SUMADETALLE-@VLR_HONOR_SIN_IGV   
         SELECT TOP 1 @ITEM=ITEM
         FROM TRAMA_DSER
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='02'
         AND  VLR_TOTAL-CONVERT(INT,VLR_TOTAL)>0

         UPDATE TRAMA_DSER SET VLR_UNITARIO=VLR_UNITARIO-@DIF,VLR_TOTAL=VLR_TOTAL-@DIF
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='02'
         AND ITEM=@ITEM
      END
      PRINT 'CODRUBRO=03'
      SET @SUMADETALLE = 0
      SELECT @SUMADETALLE=SUM(VLR_TOTAL)
      FROM TRAMA_DSER
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA
      AND COD_RUBRO='03'
      IF @SUMADETALLE-@VLR_HSCT_SIN_IGV<>0
      BEGIN
         SELECT @DIF=@SUMADETALLE-@VLR_HSCT_SIN_IGV   
         SELECT TOP 1 @ITEM=ITEM
         FROM TRAMA_DSER
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='03'
         AND  VLR_TOTAL-CONVERT(INT,VLR_TOTAL)>0

         UPDATE TRAMA_DSER SET VLR_UNITARIO=VLR_UNITARIO-@DIF,VLR_TOTAL=VLR_TOTAL-@DIF
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='03'
         AND ITEM=@ITEM
      END
      PRINT 'CODRUBRO=04'
      SET @SUMADETALLE=0
      SELECT @SUMADETALLE=SUM(VLR_TOTAL)
      FROM TRAMA_DSER
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA
      AND COD_RUBRO='04'
      IF @SUMADETALLE-@VLR_LAB_SIN_IGV<>0
      BEGIN
         SELECT @DIF=@SUMADETALLE-@VLR_LAB_SIN_IGV   
         SELECT TOP 1 @ITEM=ITEM
         FROM TRAMA_DSER
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='04'
         AND  VLR_TOTAL-CONVERT(INT,VLR_TOTAL)>0

         UPDATE TRAMA_DSER SET VLR_UNITARIO=VLR_UNITARIO-@DIF,VLR_TOTAL=VLR_TOTAL-@DIF
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='04'
         AND ITEM=@ITEM
      END
      PRINT 'CODRUBRO=06'
      SET @SUMADETALLE=0
      SELECT @SUMADETALLE=SUM(VLR_TOTAL)
      FROM TRAMA_DSER
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA
      AND COD_RUBRO='06'
      IF @SUMADETALLE-@VLR_RX_SIN_IGV<>0
      BEGIN
         SELECT @DIF=@SUMADETALLE-@VLR_RX_SIN_IGV   
         SELECT TOP 1 @ITEM=ITEM
         FROM TRAMA_DSER
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='06'
         AND  VLR_TOTAL-CONVERT(INT,VLR_TOTAL)>0

         UPDATE TRAMA_DSER SET VLR_UNITARIO=VLR_UNITARIO-@DIF,VLR_TOTAL=VLR_TOTAL-@DIF
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='06'
         AND ITEM=@ITEM
      END
      PRINT 'CODRUBRO=05'
      SET @SUMADETALLE=0
      SELECT @SUMADETALLE=SUM(VLTOTAL)
      FROM TRAMA_DFAR
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA

      PRINT '@SUMADETALLE='+CAST(COALESCE(@SUMADETALLE,0) AS VARCHAR(20))
      PRINT '@VLR_INV_SIN_IGV='+CAST(COALESCE(@VLR_INV_SIN_IGV,0)+COALESCE(@VLR_MED_EXONE,0) AS VARCHAR(20))
      IF @SUMADETALLE-(@VLR_INV_SIN_IGV+@VLR_MED_EXONE)<>0
      BEGIN
         SELECT @DIF=@SUMADETALLE-(@VLR_INV_SIN_IGV+@VLR_MED_EXONE)
         PRINT '@DIF='+CAST(COALESCE(@DIF,0) AS VARCHAR(20))
         SELECT TOP 1 @ITEM=ITEM
         FROM TRAMA_DFAR
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND  VLTOTAL-CONVERT(INT,VLTOTAL)>0
         ORDER BY VLRUNITA DESC

         UPDATE TRAMA_DFAR SET VLRUNITA=VLRUNITA-@DIF,VLTOTAL=VLTOTAL-@DIF
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND ITEM=@ITEM
      END
    PRINT 'CODRUBRO=15'
    SET @SUMADETALLE=0
      SELECT @SUMADETALLE=SUM(VLR_TOTAL)
      FROM TRAMA_DSER
      WHERE IDTRAMA=@ENVIO
      AND NUMDOC_PAGO=@N_FACTURA
      AND COD_RUBRO='15'
      IF @SUMADETALLE-@VLR_OTROS_SIN_IGV<>0
      BEGIN
         SELECT @DIF=@SUMADETALLE-@VLR_OTROS_SIN_IGV   
         SELECT TOP 1 @ITEM=ITEM
         FROM TRAMA_DSER
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='15'
         AND  VLR_TOTAL-CONVERT(INT,VLR_TOTAL)>0

         UPDATE TRAMA_DSER SET VLR_UNITARIO=VLR_UNITARIO-@DIF,VLR_TOTAL=VLR_TOTAL-@DIF
         WHERE IDTRAMA=@ENVIO
         AND NUMDOC_PAGO=@N_FACTURA
         AND COD_RUBRO='15'
         AND ITEM=@ITEM
      END
      FETCH NEXT FROM TRAMDATE_CURSOR    
      INTO  @N_FACTURA, @VLR_HONOR_SIN_IGV ,@VLR_ODONTO_SIN_IGV  ,@VLR_HSCT_SIN_IGV   ,@VLR_LAB_SIN_IGV ,@VLR_RX_SIN_IGV ,@VLR_INV_SIN_IGV,@VLR_PROTESIS_SIN_IGV,@VLR_OTROS_SIN_IGV,@VLR_MED_EXONE
   END
   CLOSE TRAMDATE_CURSOR
   DEALLOCATE TRAMDATE_CURSOR

   UPDATE TRAMA_DFAR SET VLTOTAL=(VLTOTAL+(((CANTIDAD*VLRUNITA)-VLTOTAL)-0.25))
   WHERE IDTRAMA=@ENVIO
   AND ABS((CANTIDAD*VLRUNITA)-VLTOTAL)>0.25
   
   PRINT 'TERMINO INSERT DE UPDATE '

   UPDATE TRAMA_DATE SET TRAMATEX=CAST(CASE WHEN LEN(COALESCE(IDRUC,''))<11 THEN REPLACE(SPACE(11-LEN(COALESCE(IDRUC,''))),SPACE(1),CHAR(10))+COALESCE(IDRUC,'') ELSE LEFT(COALESCE(IDRUC,''),11) END AS VARCHAR(11))+
   CAST(CASE WHEN LEN(COALESCE(COD_IPRESS,''))<8 THEN REPLACE(SPACE(8-LEN(COALESCE(COD_IPRESS,''))),SPACE(1),'0')+COALESCE(COD_IPRESS,'') ELSE LEFT(COALESCE(COD_IPRESS,''),8) END AS VARCHAR(8))+
   CAST(CASE WHEN LEN(COALESCE(TDOC_PAGO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(TDOC_PAGO,'') ELSE LEFT(COALESCE(TDOC_PAGO,''),11) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUMDOC_PAGO,''))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(NUMDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(NUMDOC_PAGO,'') ELSE LEFT(COALESCE(NUMDOC_PAGO,''),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(CORRELATIVO,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(CORRELATIVO,''))),SPACE(1),CHAR(10))+COALESCE(CORRELATIVO,'') ELSE LEFT(COALESCE(CORRELATIVO,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(CODINTERNO,''))<10 THEN REPLACE(SPACE(10-LEN(COALESCE(CODINTERNO,''))),SPACE(1),CHAR(10))+COALESCE(CODINTERNO,'') ELSE LEFT(COALESCE(CODINTERNO,''),10) END AS VARCHAR(10))+
   CAST(CASE WHEN LEN(COALESCE(TIPO_AFILIADO,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TIPO_AFILIADO,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_AFILIADO,'') ELSE LEFT(COALESCE(TIPO_AFILIADO,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(COD_ASE_PACIENTE,''))<20 THEN REPLACE(SPACE(20-LEN(COALESCE(COD_ASE_PACIENTE,''))),SPACE(1),CHAR(10))+COALESCE(COD_ASE_PACIENTE,'') ELSE LEFT(COALESCE(COD_ASE_PACIENTE,''),20) END AS VARCHAR(20))+
   CAST(CASE WHEN LEN(COALESCE(TIPO_DOC_AFI,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TIPO_DOC_AFI,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_DOC_AFI,'') ELSE LEFT(COALESCE(TIPO_DOC_AFI,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(DOC_AFILIADO,''))<15 THEN REPLACE(SPACE(15-LEN(COALESCE(DOC_AFILIADO,''))),SPACE(1),CHAR(10))+COALESCE(DOC_AFILIADO,'') ELSE LEFT(COALESCE(DOC_AFILIADO,''),15) END AS VARCHAR(15))+
   CAST(CASE WHEN LEN(COALESCE(NUM_HCA,''))<8 THEN REPLACE(SPACE(8-LEN(COALESCE(NUM_HCA,''))),SPACE(1),CHAR(10))+COALESCE(NUM_HCA,'') ELSE LEFT(COALESCE(NUM_HCA,''),8) END AS VARCHAR(8))+
   CAST(CASE WHEN LEN(COALESCE(DOC_AUT,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(DOC_AUT,''))),SPACE(1),CHAR(10))+COALESCE(DOC_AUT,'') ELSE LEFT(COALESCE(DOC_AUT,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUM_AUT,''))<20 THEN REPLACE(SPACE(20-LEN(COALESCE(NUM_AUT,''))),SPACE(1),CHAR(10))+COALESCE(NUM_AUT,'') ELSE LEFT(COALESCE(NUM_AUT,''),20) END AS VARCHAR(20))+
   CAST(CASE WHEN LEN(COALESCE(DOC_AUT2,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(DOC_AUT2,''))),SPACE(1),CHAR(10))+COALESCE(DOC_AUT2,'') ELSE LEFT(COALESCE(DOC_AUT2,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUM_AUT2,''))<20 THEN REPLACE(SPACE(20-LEN(COALESCE(NUM_AUT2,''))),SPACE(1),CHAR(10))+COALESCE(NUM_AUT2,'') ELSE LEFT(COALESCE(NUM_AUT2,''),20) END AS VARCHAR(20))+
   CAST(CASE WHEN LEN(COALESCE(TCOBERTURA,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TCOBERTURA,''))),SPACE(1),CHAR(10))+COALESCE(TCOBERTURA,'') ELSE LEFT(COALESCE(TCOBERTURA,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(SUB_COBERTURA,''))<4 THEN COALESCE(SUB_COBERTURA,'')+REPLACE(SPACE(4-LEN(COALESCE(SUB_COBERTURA,''))),SPACE(1),CHAR(10)) ELSE LEFT(COALESCE(SUB_COBERTURA,''),4) END AS VARCHAR(4))+
   CAST(CASE WHEN LEN(COALESCE(IDDX,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(IDDX,''))),SPACE(1),CHAR(10))+COALESCE(IDDX,'') ELSE LEFT(COALESCE(IDDX,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(IDDX2,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(IDDX2,''))),SPACE(1),CHAR(10))+COALESCE(IDDX2,'') ELSE LEFT(COALESCE(IDDX2,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(IDDX3,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(IDDX3,''))),SPACE(1),CHAR(10))+COALESCE(IDDX3,'') ELSE LEFT(COALESCE(IDDX3,''),5) END AS VARCHAR(5))+
   REPLACE(CONVERT(DATE,F_PRESTACION),'-','')+LEFT(REPLACE(CONVERT(TIME,F_PRESTACION),':',''),6) +  
   CAST(CASE WHEN LEN(COALESCE(TIPO_PROF_RESPONSABLE,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TIPO_PROF_RESPONSABLE,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_PROF_RESPONSABLE,'') ELSE LEFT(COALESCE(TIPO_PROF_RESPONSABLE,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUM_CPRP,''))<6 THEN REPLACE(SPACE(6-LEN(COALESCE(NUM_CPRP,''))),SPACE(1),CHAR(10))+COALESCE(NUM_CPRP,'') ELSE LEFT(COALESCE(NUM_CPRP,''),6) END AS VARCHAR(6))+
   CAST(CASE WHEN LEN(COALESCE(TIPO_DOC,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TIPO_DOC,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_DOC,'') ELSE LEFT(COALESCE(CASE WHEN TIPO_DOC=0 THEN '' ELSE LTRIM(RTRIM(STR(TIPO_DOC))) END,''),1) END  AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(NUM_DOC,''))<15 THEN REPLACE(SPACE(15-LEN(COALESCE(NUM_DOC,''))),SPACE(1),CHAR(10))+COALESCE(NUM_DOC,'') ELSE LEFT(COALESCE(NUM_DOC,''),15) END AS VARCHAR(15))+
   CAST(CASE WHEN LEN(COALESCE(IDRUC_REF,''))<11 THEN REPLACE(SPACE(11-LEN(COALESCE(IDRUC_REF,''))),SPACE(1),CHAR(10))+COALESCE(IDRUC_REF,'') ELSE LEFT(COALESCE(IDRUC_REF,''),11) END AS VARCHAR(11))+
   CASE WHEN F_TRANSFERENCIA IS NOT NULL THEN  REPLACE(CONVERT(DATE,F_TRANSFERENCIA),'-','')+LEFT(REPLACE(CONVERT(TIME,F_TRANSFERENCIA),':',''),6) ELSE SPACE(14) END +  
   CAST(CASE WHEN LEN(COALESCE(TIPO_HOSP,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TIPO_HOSP,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_HOSP,'') ELSE LEFT(COALESCE(TIPO_HOSP,''),1) END AS VARCHAR(1))+
   CASE WHEN F_INGRESO IS NOT NULL THEN REPLACE(CONVERT(DATE,F_INGRESO),'-','') ELSE SPACE(8) END + 
   CASE WHEN F_EGRESO IS NOT NULL  THEN REPLACE(CONVERT(DATE,F_EGRESO),'-','') ELSE SPACE(8) END + 
   CAST(CASE WHEN LEN(COALESCE(TIPO_EGRESO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TIPO_EGRESO,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_EGRESO,'') ELSE LEFT(COALESCE(TIPO_EGRESO,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(DIAS_ESTANCIA,''))<3 THEN REPLACE(SPACE(3-LEN(COALESCE(DIAS_ESTANCIA,''))),SPACE(1),CHAR(10))+COALESCE(DIAS_ESTANCIA,'') ELSE LEFT(COALESCE(DIAS_ESTANCIA,''),11) END AS VARCHAR(3))+
   CAST(CASE WHEN LEN(COALESCE(VLR_HONOR_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_HONOR_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_HONOR_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_HONOR_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_ODONTO_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_ODONTO_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_ODONTO_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_ODONTO_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_HSCT_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_HSCT_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_HSCT_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_HSCT_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_LAB_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_LAB_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_LAB_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_LAB_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_RX_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_RX_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_RX_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_RX_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_INV_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_INV_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_INV_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_INV_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_PROTESIS_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_PROTESIS_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_PROTESIS_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_PROTESIS_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_MED_EXONE,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_MED_EXONE,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_MED_EXONE,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_MED_EXONE,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_OTROS_SIN_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_OTROS_SIN_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_OTROS_SIN_IGV,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_OTROS_SIN_IGV,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(COPAGO_FIJO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(COPAGO_FIJO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(COPAGO_FIJO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(COPAGO_FIJO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(COPAGO_FIJO_EXO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(COPAGO_FIJO_EXO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(COPAGO_FIJO_EXO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(COPAGO_FIJO_EXO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(COPAGO_VAR,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(COPAGO_VAR,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(COPAGO_VAR,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(COPAGO_VAR,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(COPAGO_VAR_EXO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(COPAGO_VAR_EXO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(COPAGO_VAR_EXO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(COPAGO_VAR_EXO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(TOTAL_GASTOS,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(TOTAL_GASTOS,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(TOTAL_GASTOS,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(TOTAL_GASTOS,0.00),12) END AS VARCHAR(12))
   WHERE IDTRAMA=@ENVIO
   --FECHA_PROC

    PRINT 'TERMINO INSERT DE TRAMA_DSER '


   UPDATE TRAMA_DSER SET TRAMATEX=CAST(CASE WHEN LEN(COALESCE(IDRUC,''))<11 THEN REPLACE(SPACE(11-LEN(COALESCE(IDRUC,''))),SPACE(1),CHAR(10))+COALESCE(IDRUC,'') ELSE LEFT(COALESCE(IDRUC,''),11) END AS VARCHAR(11))+
   CAST(CASE WHEN LEN(COALESCE(COD_IPRESS,''))<8 THEN REPLACE(SPACE(8-LEN(COALESCE(COD_IPRESS,''))),SPACE(1),'0')+COALESCE(COD_IPRESS,'') ELSE LEFT(COALESCE(COD_IPRESS,''),8) END AS VARCHAR(8))+
   CAST(CASE WHEN LEN(COALESCE(TDOC_PAGO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(TDOC_PAGO,'') ELSE LEFT(COALESCE(TDOC_PAGO,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUMDOC_PAGO,''))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(NUMDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(NUMDOC_PAGO,'') ELSE LEFT(COALESCE(NUMDOC_PAGO,''),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(CORRELATIVO,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(CORRELATIVO,''))),SPACE(1),CHAR(10))+COALESCE(CORRELATIVO,'') ELSE LEFT(COALESCE(CORRELATIVO,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(CORRE_PRESTA,''))<4 THEN REPLACE(SPACE(4-LEN(COALESCE(CORRE_PRESTA,''))),SPACE(1),CHAR(10))+COALESCE(CORRE_PRESTA,'') ELSE LEFT(COALESCE(CORRE_PRESTA,''),4) END AS VARCHAR(4))+
   CAST(CASE WHEN LEN(COALESCE(TIPO_CLASIFICACION,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TIPO_CLASIFICACION,''))),SPACE(1),CHAR(10))+COALESCE(TIPO_CLASIFICACION,'') ELSE LEFT(COALESCE(TIPO_CLASIFICACION,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(IDSERVICIO,''))<10 THEN COALESCE(IDSERVICIO,'')+ REPLACE(SPACE(10-LEN(COALESCE(IDSERVICIO,''))),SPACE(1),CHAR(10)) ELSE LEFT(COALESCE(IDSERVICIO,''),10) END AS VARCHAR(10))+
   CAST(CASE WHEN LEN(COALESCE(DESCSERVICIO,''))<70 THEN COALESCE(LTRIM(RTRIM(DESCSERVICIO)),'')+REPLACE(SPACE(70-LEN(COALESCE(LTRIM(RTRIM(DESCSERVICIO)),''))),SPACE(1),CHAR(10)) ELSE LEFT(COALESCE(DESCSERVICIO,''),70) END AS VARCHAR(70))+
   CASE WHEN FECHA_PROC IS NOT NULL THEN REPLACE(CONVERT(DATE,FECHA_PROC),'-','') ELSE SPACE(8) END + 
   CAST(CASE WHEN LEN(COALESCE(IDEMEDICA,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(IDEMEDICA,''))),SPACE(1),'0')+COALESCE(IDEMEDICA,'') ELSE LEFT(COALESCE(IDEMEDICA,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUM_CPR,''))<6 THEN REPLACE(SPACE(6-LEN(COALESCE(NUM_CPR,''))),SPACE(1),CHAR(10))+COALESCE(NUM_CPR,'') ELSE LEFT(COALESCE(NUM_CPR,''),6) END AS VARCHAR(6))+
   CAST(CASE WHEN LEN(COALESCE(TIPO_DOC_PRO,''))<1 THEN ' ' ELSE LEFT(CASE WHEN  COALESCE(TIPO_DOC_PRO,'0')='0' THEN ' ' ELSE LTRIM(RTRIM(STR(TIPO_DOC_PRO))) END,1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(IDMEDICO,''))<15 THEN COALESCE(IDMEDICO,'')+REPLACE(SPACE(15-LEN(COALESCE(IDMEDICO,''))),SPACE(1),CHAR(10)) ELSE LEFT(COALESCE(IDMEDICO,''),15) END AS VARCHAR(15))+
   CAST(CASE WHEN LEN(COALESCE(CANTIDAD,0))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(CANTIDAD,0))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(CANTIDAD,0) AS varchar(20)))) ELSE LEFT(COALESCE(CANTIDAD,0),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(VLR_UNITARIO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_UNITARIO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST( COALESCE(VLR_UNITARIO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_UNITARIO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLRCOPAGO_VARIABLE,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLRCOPAGO_VARIABLE,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLRCOPAGO_VARIABLE,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLRCOPAGO_VARIABLE,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLRCOPAGO_FIJO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLRCOPAGO_FIJO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLRCOPAGO_FIJO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLRCOPAGO_FIJO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_TOTAL,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_TOTAL,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_TOTAL,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_TOTAL,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLR_NOCUBIERTO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_NOCUBIERTO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_NOCUBIERTO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_NOCUBIERTO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(IDDX,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(IDDX,''))),SPACE(1),CHAR(10))+COALESCE(IDDX,'') ELSE LEFT(COALESCE(IDDX,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(SER_EXENTO,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(SER_EXENTO,''))),SPACE(1),CHAR(10))+COALESCE(SER_EXENTO,'') ELSE LEFT(COALESCE(SER_EXENTO,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(COD_RUBRO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(COD_RUBRO,''))),SPACE(1),CHAR(10))+COALESCE(COD_RUBRO,'') ELSE LEFT(COALESCE(COD_RUBRO,''),2) END AS VARCHAR(2))
   WHERE IDTRAMA=@ENVIO

  --FDISPENSA
   PRINT 'TERMINO INSERT DE TRAMA_DFAR '

   UPDATE TRAMA_DFAR SET TRAMATEX=CAST(CASE WHEN LEN(COALESCE(IDRUC,''))<11 THEN REPLACE(SPACE(11-LEN(COALESCE(IDRUC,''))),SPACE(1),CHAR(10))+COALESCE(IDRUC,'') ELSE LEFT(COALESCE(IDRUC,''),11) END AS VARCHAR(11))+
   CAST(CASE WHEN LEN(COALESCE(COD_IPRESS,''))<8 THEN REPLACE(SPACE(8-LEN(COALESCE(COD_IPRESS,''))),SPACE(1),'0')+COALESCE(COD_IPRESS,'') ELSE LEFT(COALESCE(COD_IPRESS,''),8) END AS VARCHAR(8))+
   CAST(CASE WHEN LEN(COALESCE(TDOC_PAGO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(TDOC_PAGO,'') ELSE LEFT(COALESCE(TDOC_PAGO,''),2) END AS VARCHAR(2))+
   CAST(CASE WHEN LEN(COALESCE(NUMDOC_PAGO,''))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(NUMDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(NUMDOC_PAGO,'') ELSE LEFT(COALESCE(NUMDOC_PAGO,''),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(CORRELATIVO,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(CORRELATIVO,''))),SPACE(1),CHAR(10))+COALESCE(CORRELATIVO,'') ELSE LEFT(COALESCE(CORRELATIVO,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(CORRE_PRESTA,''))<4 THEN REPLACE(SPACE(4-LEN(COALESCE(CORRE_PRESTA,''))),SPACE(1),CHAR(10))+COALESCE(CORRE_PRESTA,'') ELSE LEFT(COALESCE(CORRE_PRESTA,''),4) END AS VARCHAR(4))+
   CAST(CASE WHEN LEN(COALESCE(TPRODUC,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TPRODUC,''))),SPACE(1),CHAR(10))+COALESCE(TPRODUC,'') ELSE LEFT(COALESCE(TPRODUC,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(TCATALOGO,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TCATALOGO,''))),SPACE(1),CHAR(10))+COALESCE(TCATALOGO,'') ELSE LEFT(COALESCE(TCATALOGO,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(IDSERVICIO,''))<13 THEN COALESCE(IDSERVICIO,'')+REPLACE(SPACE(13-LEN(COALESCE(IDSERVICIO,''))),SPACE(1),CHAR(10)) ELSE LEFT(COALESCE(IDSERVICIO,''),13) END AS VARCHAR(13))+
   CASE WHEN FDISPENSA IS NOT NULL THEN REPLACE(CONVERT(DATE,FDISPENSA),'-','') ELSE REPLACE(SPACE(8),SPACE(1),CHAR(10)) END +
   CAST(CASE WHEN LEN(COALESCE(CANTIDAD,0.00))<7 THEN REPLACE(SPACE(7-LEN(COALESCE(CANTIDAD,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(CANTIDAD,0.00) AS varchar(7)))) ELSE LEFT(COALESCE(CANTIDAD,0.00),7) END AS VARCHAR(7))+
   CAST(CASE WHEN LEN(COALESCE(TDISPENSA,''))<1 THEN COALESCE(TDISPENSA,'1') ELSE LEFT(COALESCE(TDISPENSA,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(VLRUNITA,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLRUNITA,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLRUNITA,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLRUNITA,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLCOPAGO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLCOPAGO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLCOPAGO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLCOPAGO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLTOTAL,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLTOTAL,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLTOTAL,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLTOTAL,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(VLNOCUBIERTO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLNOCUBIERTO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLNOCUBIERTO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLNOCUBIERTO,0.00),12) END AS VARCHAR(12))+
   CAST(CASE WHEN LEN(COALESCE(IDDX,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(IDDX,''))),SPACE(1),CHAR(10))+COALESCE(IDDX,'') ELSE LEFT(COALESCE(IDDX,''),5) END AS VARCHAR(5))+
   CAST(CASE WHEN LEN(COALESCE(EXENTO,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(EXENTO,''))),SPACE(1),CHAR(10))+COALESCE(EXENTO,'') ELSE LEFT(COALESCE(EXENTO,''),1) END AS VARCHAR(1))+
   CAST(CASE WHEN LEN(COALESCE(GUIAENTREGA,''))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(GUIAENTREGA,''))),SPACE(1),CHAR(10))+COALESCE(GUIAENTREGA,'') ELSE LEFT(COALESCE(GUIAENTREGA,''),12) END AS VARCHAR(12))
   FROM TRAMA_DFAR
   WHERE IDTRAMA=@ENVIO


 
   PRINT 'TERMINO INSERT DE TRAMA_DFAC '


   UPDATE TRAMA_DFAC SET TRAMATEX= REPLACE(CONVERT(DATE,F_ENVIO),'-','')+LEFT(REPLACE(CONVERT(TIME,F_ENVIO),':',''),6) +
      CAST(CASE WHEN LEN(COALESCE(NUM_LOTE,''))<7 THEN REPLACE(SPACE(7-LEN(COALESCE(NUM_LOTE,''))),SPACE(1),'')+COALESCE(NUM_LOTE,'') ELSE LEFT(COALESCE(NUM_LOTE,''),7) END AS VARCHAR(7))+
      CAST(CASE WHEN LEN(COALESCE(COD_IAFAS,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(COD_IAFAS,''))),SPACE(1),CHAR(10))+COALESCE(COD_IAFAS,'') ELSE LEFT(COALESCE(COD_IAFAS,''),5) END AS VARCHAR(5))+
      CAST(CASE WHEN LEN(COALESCE(IDRUC,''))<11 THEN REPLACE(SPACE(11-LEN(COALESCE(IDRUC,''))),SPACE(1),CHAR(10))+COALESCE(IDRUC,'') ELSE LEFT(COALESCE(IDRUC,''),11) END AS VARCHAR(11))+
      CAST(CASE WHEN LEN(COALESCE(COD_IPRESS,''))<8 THEN REPLACE(SPACE(8-LEN(COALESCE(COD_IPRESS,''))),SPACE(1),CHAR(10))+COALESCE(COD_IPRESS,'') ELSE LEFT(COALESCE(COD_IPRESS,''),8) END AS VARCHAR(8))+
      CAST(CASE WHEN LEN(COALESCE(TDOC_PAGO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(TDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(TDOC_PAGO,'') ELSE LEFT(COALESCE(TDOC_PAGO,''),2) END AS VARCHAR(2))+
      CAST(CASE WHEN LEN(COALESCE(NUMDOC_PAGO,''))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(NUMDOC_PAGO,''))),SPACE(1),CHAR(10))+COALESCE(NUMDOC_PAGO,'') ELSE LEFT(COALESCE(NUMDOC_PAGO,''),12) END AS VARCHAR(12))+
      REPLACE(CONVERT(DATE,F_EMISION),'-','')+
      CAST(CASE WHEN LEN(COALESCE(PRODUCTO,''))<5 THEN COALESCE(PRODUCTO,'')+REPLACE(SPACE(5-LEN(COALESCE(PRODUCTO,''))),SPACE(1),CHAR(10)) ELSE LEFT(COALESCE(PRODUCTO,''),5) END AS VARCHAR(5))+
      CAST(CASE WHEN LEN(COALESCE(N_PRESTACIONES,''))<5 THEN REPLACE(SPACE(5-LEN(COALESCE(N_PRESTACIONES,''))),SPACE(1),'0')+LTRIM(RTRIM(STR(COALESCE(N_PRESTACIONES,'')))) ELSE LEFT(COALESCE(N_PRESTACIONES,''),5) END AS VARCHAR(5))+
      CAST(CASE WHEN LEN(COALESCE(MPAGO,''))<2 THEN REPLACE(SPACE(2-LEN(COALESCE(MPAGO,''))),SPACE(1),CHAR(10))+COALESCE(MPAGO,'') ELSE LEFT(COALESCE(MPAGO,''),2) END AS VARCHAR(2))+
      CAST(CASE WHEN LEN(COALESCE(SUB_MPAGO,''))<3 THEN REPLACE(SPACE(3-LEN(COALESCE(SUB_MPAGO,''))),SPACE(1),CHAR(10))+COALESCE(SUB_MPAGO,'') ELSE LEFT(COALESCE(SUB_MPAGO,''),3) END AS VARCHAR(3))+
      CAST(CASE WHEN LEN(COALESCE(VLR_PREPACTADO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_PREPACTADO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_PREPACTADO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_PREPACTADO,0.00),12) END AS VARCHAR(12))+
      CASE WHEN F_INICIO_PER IS NOT NULL THEN REPLACE(CONVERT(DATE,F_INICIO_PER),'-','') ELSE SPACE(8) END + 
      CAST(CASE WHEN LEN(COALESCE(TMONEDA,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(TMONEDA,''))),SPACE(1),CHAR(10))+COALESCE(TMONEDA,'') ELSE LEFT(COALESCE(TMONEDA,''),1) END AS VARCHAR(1))+
      CAST(CASE WHEN LEN(COALESCE(VLR_EXONERADO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_EXONERADO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_EXONERADO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_EXONERADO,0.00),11) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_COPAGO_FIJO,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_COPAGO_FIJO,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_COPAGO_FIJO,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_COPAGO_FIJO,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_COPAGO_FIJO_EX,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_COPAGO_FIJO_EX,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_COPAGO_FIJO_EX,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_COPAGO_FIJO_EX,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_COPAGO_VAR,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_COPAGO_VAR,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_COPAGO_VAR,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_COPAGO_VAR,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_COPAGO_VAR_EX,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_COPAGO_VAR_EX,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_COPAGO_VAR_EX,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_COPAGO_VAR_EX,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_BASEIMP,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_BASEIMP,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_BASEIMP,0.00) AS varchar(20)))) ELSE LEFT(COALESCE(VLR_BASEIMP,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_IGV,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_IGV,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_IGV,'') AS varchar(20)))) ELSE LEFT(COALESCE(VLR_IGV,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_TOTAL,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_TOTAL,0.00))),SPACE(1),CHAR(10))+LTRIM(RTRIM(CAST(COALESCE(VLR_TOTAL,'') AS varchar(20)))) ELSE LEFT(COALESCE(VLR_TOTAL,0.00),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(CLASE,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(CLASE,''))),SPACE(1),CHAR(10))+COALESCE(CLASE,'') ELSE LEFT(COALESCE(CLASE,''),12) END AS VARCHAR(1))+
      CAST(CASE WHEN LEN(COALESCE(CNSFNOT,''))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(CNSFNOT,''))),SPACE(1),CHAR(10))+COALESCE(CNSFNOT,'') ELSE LEFT(COALESCE(CNSFNOT,''),12) END AS VARCHAR(12))+
      CAST(CASE WHEN LEN(COALESCE(VLR_TOTAL_NOTA,0.00))<12 THEN REPLACE(SPACE(12-LEN(COALESCE(VLR_TOTAL_NOTA,0.00))),SPACE(1),CHAR(10))+CASE WHEN COALESCE(VLR_TOTAL_NOTA,0)=0 THEN SPACE(4) ELSE  LTRIM(RTRIM(CAST(COALESCE(VLR_TOTAL_NOTA,0.00) AS varchar(20))))END ELSE LEFT(COALESCE(VLR_TOTAL_NOTA,0.00),12) END AS VARCHAR(12))+
      CASE WHEN F_NOTA IS NOT NULL THEN REPLACE(CONVERT(DATE,F_NOTA),'-','') ELSE SPACE(8) END + 
      CAST(CASE WHEN LEN(COALESCE(M_NOTA,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(M_NOTA,''))),SPACE(1),CHAR(10))+COALESCE(M_NOTA,'') ELSE LEFT(COALESCE(M_NOTA,''),1) END AS VARCHAR(1))+
      CASE WHEN F_PENVIO_FTR IS NOT NULL THEN REPLACE(CONVERT(DATE,F_PENVIO_FTR),'-','') ELSE SPACE(8) END + 
      CAST(CASE WHEN LEN(COALESCE(IND_FTR,''))<1 THEN REPLACE(SPACE(1-LEN(COALESCE(IND_FTR,''))),SPACE(1),CHAR(10))+COALESCE(IND_FTR,'') ELSE LEFT(COALESCE(IND_FTR,''),1) END AS VARCHAR(1))
   WHERE IDTRAMA=@ENVIO

   UPDATE TRAMA_DATE SET TRAMATEX=REPLACE(TRAMATEX,CHAR(13),'')  WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DATE SET TRAMATEX=REPLACE(TRAMATEX,CHAR(10),' ') WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DFAC SET TRAMATEX=REPLACE(TRAMATEX,CHAR(13),'')  WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DFAC SET TRAMATEX=REPLACE(TRAMATEX,CHAR(10),' ') WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DSER SET TRAMATEX=REPLACE(TRAMATEX,CHAR(13),'')  WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DSER SET TRAMATEX=REPLACE(TRAMATEX,CHAR(10),' ') WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DFAR SET TRAMATEX=REPLACE(TRAMATEX,CHAR(13),'')  WHERE IDTRAMA=@ENVIO
   UPDATE TRAMA_DFAR SET TRAMATEX=REPLACE(TRAMATEX,CHAR(10),' ') WHERE IDTRAMA=@ENVIO

END



