IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_GEN_AUT' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_GEN_AUT
END
GO
CREATE PROCEDURE DBO.SPK_GEN_AUT
   @CNSRPDX  VARCHAR(20),
   @SEDE     VARCHAR(5),
   @EQUIPO   VARCHAR(254),
   @MISMAAUT BIT=0, --Permite generar una sola autorización con todos los prefijos
   @MENTREGA VARCHAR(20)=NULL
WITH ENCRYPTION
AS
DECLARE @IDAUT VARCHAR(20)
DECLARE @NOAUT VARCHAR(20)
DECLARE @PROVEEDOR_FAR VARCHAR(40)
DECLARE @PROVEEDOR_EXA VARCHAR(40)
DECLARE @PROVEEDOR_APO VARCHAR(40)
DECLARE @CORREGIMIENTO VARCHAR(40)
DECLARE @HOY   DATETIME
DECLARE @FIX   INT
DECLARE @FIXTO INT
DECLARE @F_AUT DATETIME -- SE AGREGA FECHA DE AUTORIZADO POR EL MEDICO JAG 17/01/2022

DECLARE @AUT	TABLE (
	ID			INT PRIMARY KEY IDENTITY(1,1), 
	ITEM		INT,
	CONSECUTIVO VARCHAR(20),
	USUARIO		VARCHAR(12),
	PREFIJO		VARCHAR(6),
	IDAFILIADO	VARCHAR(20),
	IDTERCERO	VARCHAR(20),
	IDPLAN		VARCHAR(6),
	IDAREA		VARCHAR(20),
	CCOSTO		VARCHAR(20),
	NROAUT		VARCHAR(20),
	IDPROVEEDOR VARCHAR(20),
	IDMEDICO	VARCHAR(20),
	FECHA       DATETIME,
	CONSECUTIVOCIT VARCHAR(20)
)
DECLARE @AUTD	TABLE (
	ITEM		INT,
	ITEM_AUT	INT,
	IDSERVICIO	VARCHAR(20),
	CANTIDAD	DECIMAL(18,6),
	CODCUPS		VARCHAR(20),
	AMBITO		VARCHAR(2),
	MARCA		TINYINT,
	NROAUT		VARCHAR(20),
    TABLA       VARCHAR(20),
    CODOM       VARCHAR(20),
    PROTOCOLO   BIT
)
BEGIN

    --Actualizo el campo CANTIDAD = 99 para SACAR de la autorizaciones los servicios con errores en contratacion
    UPDATE RPDX SET CANTIDAD = 99 WHERE CNS = @CNSRPDX and CANTIDAD=3
    -- Fin Actualziacion de RPDX

    PRINT 'Ingreso los diferentes prefijos para iniciar While'
    SELECT @F_AUT= MAX(S. FECHA1)
        FROM RPDX P INNER JOIN RPDX S ON P.CNS=S.CNS AND P.ITEM=S.CANTIDAD1 AND S.CANTIDAD IN (1,2)
	    WHERE P.CNS=@CNSRPDX AND P.CANTIDAD=0
		    AND NOT EXISTS (SELECT 1 FROM RPDX A WHERE P.CNS=A.CNS AND P.ITEM=A.CANTIDAD1 AND A.CANTIDAD=3) --Si existe una aurotización con inconvenientes no generará
       
    IF @MISMAAUT = 1
        INSERT INTO @AUT (ITEM, CONSECUTIVO, USUARIO, PREFIJO, IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NROAUT, IDPROVEEDOR, IDMEDICO, CONSECUTIVOCIT)
        SELECT '', P.ID1, P.ID2, MIN(P.ID3), P.ID5, S.ID6, S.ID7, S.ID8, S.ID9, P.ID20, S.ID10, S.ID11, COALESCE(P.CNS1, '')
        FROM RPDX P INNER JOIN RPDX S ON P.CNS=S.CNS AND P.ITEM=S.CANTIDAD1 AND S.CANTIDAD IN (1,2)
	    WHERE P.CNS=@CNSRPDX AND P.CANTIDAD=0
		    AND NOT EXISTS (SELECT 1 FROM RPDX A WHERE P.CNS=A.CNS AND P.ITEM=A.CANTIDAD1 AND A.CANTIDAD=3) --Si existe una aurotización con inconvenientes no generará
        GROUP BY P.ID1, P.ID2, P.ID5, S.ID6, S.ID7, S.ID8, S.ID9, P.ID20, S.ID10, S.ID11,cast(S.FECHA1 as DATE), COALESCE(P.CNS1, '')
    ELSE
        INSERT INTO @AUT (ITEM, CONSECUTIVO, USUARIO, PREFIJO, IDAFILIADO, IDTERCERO, IDPLAN, IDAREA, CCOSTO, NROAUT, IDPROVEEDOR, IDMEDICO, CONSECUTIVOCIT)
        SELECT DISTINCT P.ITEM, P.ID1, P.ID2, P.ID3, P.ID5, S.ID6, S.ID7, S.ID8, S.ID9, P.ID20, S.ID10, S.ID11, COALESCE(P.CNS1, '')
        FROM RPDX P INNER JOIN RPDX S ON P.CNS=S.CNS AND P.ITEM=S.CANTIDAD1 AND S.CANTIDAD IN (1,2)
	    WHERE P.CNS=@CNSRPDX AND P.CANTIDAD=0
		    AND NOT EXISTS (SELECT 1 FROM RPDX A WHERE P.CNS=A.CNS AND P.ITEM=A.CANTIDAD1 AND A.CANTIDAD=3) --Si existe una aurotización con inconvenientes no generará

    --Dejo RPDX igual como inicio el SPK para que continue con el proceso NORMAL
    UPDATE RPDX SET CANTIDAD = 3 WHERE CNS = @CNSRPDX and CANTIDAD=99
    -- Fin Actualziacion de RPDX
    SELECT @FIXTO=MAX(ID) FROM @AUT
    SET @FIX = 1
    SET @HOY = CONVERT(SMALLDATETIME,GETDATE())
    WHILE @FIX <= @FIXTO
    BEGIN
	    DELETE @AUTD

	    INSERT INTO @AUTD (ITEM, ITEM_AUT, IDSERVICIO, CANTIDAD, CODCUPS, AMBITO, MARCA, NROAUT, TABLA, CODOM, PROTOCOLO)
	    SELECT S.ITEM, A.ITEM, S.ID4, S.VALOR1, SER.CODCUPS, SER.AMBITO, S.CANTIDAD, S.ID20, COALESCE(S.ID19,'HCA'), S.ID18, S.CANTIDAD2
        FROM @AUT A 
        INNER JOIN RPDX S ON @CNSRPDX=S.CNS AND S.CANTIDAD IN (1,2) AND A.IDAFILIADO=S.ID5 
						    AND A.CONSECUTIVO=S.ID1 AND A.USUARIO=S.ID2 AND A.PREFIJO=(CASE @MISMAAUT WHEN 1 THEN A.PREFIJO ELSE S.ID3 END)
        INNER JOIN SER   ON S.ID4=SER.IDSERVICIO
        WHERE A.ID=@FIX


	    IF EXISTS (SELECT 1 FROM @AUTD WHERE MARCA=1)
	    BEGIN
		    PRINT 'Genero consecutivo IDAUT'
		    EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@AUT',@IDAUT OUTPUT
		    SELECT @IDAUT = @SEDE + RIGHT('00000000'+CONVERT(VARCHAR(8),@IDAUT),8)
		    PRINT @IDAUT
      
		    PRINT 'Genero consecutivo NOAUT'
		    EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@AUTF',@NOAUT OUTPUT
		    SELECT @NOAUT = @SEDE + RIGHT('00000000'+CONVERT(VARCHAR(8),@NOAUT),8)
		    PRINT @NOAUT

			SELECT TOP 1 @CORREGIMIENTO = AFI.CORREGIMIENTO 
			FROM @AUT A INNER JOIN AFI ON AFI.IDAFILIADO=A.IDAFILIADO
			
			SELECT TOP 1 @PROVEEDOR_FAR = EXA.CODIGO
			FROM TGEN DIR
			INNER JOIN TGEN EXA ON EXA.TABLA='DISTRIBUIDORES' AND EXA.CAMPO=DIR.TABLA AND EXA.CODIGO=DIR.CAMPO
			WHERE DIR.TABLA = 'FARMACIA' AND DIR.CODIGO=@CORREGIMIENTO

			SELECT TOP 1 @PROVEEDOR_EXA = EXA.CODIGO
			FROM TGEN DIR
			INNER JOIN TGEN EXA ON EXA.TABLA='DISTRIBUIDORES' AND EXA.CAMPO=DIR.TABLA AND EXA.CODIGO=DIR.CAMPO
			WHERE DIR.TABLA = 'EXAMENES' AND DIR.CODIGO=@CORREGIMIENTO

			SELECT TOP 1 @PROVEEDOR_APO = EXA.CODIGO
			FROM TGEN DIR
			INNER JOIN TGEN EXA ON EXA.TABLA='DISTRIBUIDORES' AND EXA.CAMPO=DIR.TABLA AND EXA.CODIGO=DIR.CAMPO
			WHERE DIR.TABLA = 'APOYO' AND DIR.CODIGO=@CORREGIMIENTO

		    INSERT INTO AUT (
			    IDAUT, NOAUT, FECHA, FECHAVENCE, IDAFILIADO, NUMCARNET, IDPLAN, PREFIJO, IDSEDE, TIPOAUTORIZACION, 
			    ALTOCOSTO, ATENCION, IMPUTABLE_A, IDSOLICITANTE, IDPROVEEDOR, ESTADO, AUTORIZADOPOR, FECHAAUTORIZA, IDPESPECIAL, AUTORIZADO, 
			    USUARIO, IDCAUSAEXT, AMBITO, FINALIDAD, PERSONAL_AT, DXPPAL, TIPOURGENCIA, SPD, IDCONTRATANTE, TIPOCOPAGO, 
			    CLASECONT, FECHAGEN, PROCEDENCIA, IDAREAH, IDAREA, CCOSTO, NIVELATENCION, FACTURADA, FACTURABLE, IDIPS, 
			    CLASECONTRATO, ENPAQUETE, SOAT, COBRARA, IDTERCEROCA, CONSECUTIVOHCA, SYS_COMPUTERNAME, TIPOUSUARIO, IDPLAN_AFI, IDTERCERO_AFI, 
			    CLASEORDEN, URGENCIA, VALORBENEFICIO, VALOREXEDENTE, VALORTOTALCOSTO, VALORCOPAGOCOSTO, IMPRESO, CXPGEN, CXCGEN, PEDIDOINV,
			    ESCONTINUACION, SEMANASCOT, LIQUIDAPC, ESDEINV, VFACTURAS, DESCUENTO, MARCAFAC, PERIODICIDAD, CONTINUACION, MARCAENV,
			    COPAGOPROPIO, ESDELAB, ENLAB, PIDECCOSTO, RIESGO, NUMAUTORIZA, TIPOAFILIADO, MENTREGA, CONSECUTIVOCIT, TIPOPREVIO, GENERADO, 
				ESPROGRAMAS, IDFARMACIA
		    )
		    SELECT 
			    @IDAUT, @NOAUT,CASE WHEN DBO.FNK_VALORVARIABLE('AUT_FECHA_GENERA')='SI' THEN @F_AUT ELSE @HOY END FECHA , 
				DATEADD(DAY,COALESCE(PRE.VIGENCIA,0), CASE WHEN DBO.FNK_VALORVARIABLE('AUT_FECHA_GENERA')='SI' THEN A.FECHA ELSE @HOY END ) FECHAVENCE,
				AFI.IDAFILIADO, AFI.NUMCARNET, A.IDPLAN, A.PREFIJO, COALESCE(CIT.IDSEDE,@SEDE) IDSEDE, 'Previa' TIPOAUTORIZACION, --STORRES SE AGREGA VIGENCIA DE LA ORDEN CON COMANDO DATEADD
			    'No' ALTOCOSTO, 'Ambulatoria' ATENCION, 'Administradora' IMPUTABLE_A, A.IDMEDICO IDSOLICITANTE, 
				COALESCE(A.IDPROVEEDOR,AFI.IDPROVEEDOR) IDPROVEEDOR, 'Pendiente' ESTADO, A.USUARIO AUTORIZADOPOR,
				CASE WHEN DBO.FNK_VALORVARIABLE('AUT_FECHA_GENERA')='SI' THEN A.FECHA ELSE @HOY END FECHAAUTORIZA, CIT.IDPESPECIAL, 0 AUTORIZADO, 
			    A.USUARIO, COALESCE(HCA.CAUSA_EXT,(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDCAUSAEXTERNA')) IDCAUSAEXT, LEFT(COALESCE(HCA.AMBITO,'1') ,2)AMBITO, 
                CASE WHEN COALESCE(HCA.FINALIDAD,'')<>'' 
					THEN HCA.FINALIDAD ELSE (CASE WHEN COALESCE(PRE.FINALIDAD,'')<>'' 
												  THEN PRE.FINALIDAD ELSE (SELECT DATO FROM USVGS WHERE IDVARIABLE='FINCONSULTADEFAULT') END) END AS FINALIDAD, 
                MES.PERSONAL_AT, CASE (SELECT DATO FROM USVGS WHERE IDVARIABLE='AUTDXDESDEHC') WHEN 'NO' THEN '' ELSE COALESCE(HCA.IDDX,'') END DXPPAL, 'NA' TIPOURGENCIA
				, 0 SPD, A.IDTERCERO IDCONTRATANTE, 'N' TIPOCOPAGO, 
			    'ENGE' CLASECONT, @HOY FECHAGEN, 'HC' PROCEDENCIA, COALESCE(CIT.IDAREAH,AFU.IDAREAH)IDAREAH, CEN.IDAREA, CEN.CCOSTO, '1' NIVELATENCION,
				0 FACTURADA, 1 FACTURABLE, AFI.IDPROVEEDOR IDIPS, 
			    CASE PPT.CAPITADO WHEN 1 THEN 'C' ELSE 'E' END CLASECONTRARTO, 
			    0 ENPAQUETE, 0 SOAT, 'C' COBRARA, A.IDTERCERO IDTERCEROCA, COALESCE(HCA.CONSECUTIVO,'') CONSECUTIVOHCA, @EQUIPO SYS_COMPUTERNAME
				, USUSU.TIPO TIPOUSUARIO, AFI.IDPLAN IDPLAN_AFI, AFI.IDADMINISTRADORA IDTERCERO_AFI, 
			    COALESCE(CIT.CLASEORDEN,'Normal') CLASEORDEN, 0 URGENCIA, 0 VALORBENEFICIO, 0 VALOREXEDENTE, 0 VALORTOTALCOSTO, 0 VALORCOPAGOCOSTO, 0 IMPRESO, 0 CXPGEN,
				0 CXCGEN, 0 PEDIDOINV,
			    0 ESCONTINUACION, 0 SEMANASCOT, 0 LIQUIDAPC, ISNULL(MINVENTARIOS,0) ESDEINV, 0 VFACTURAS, 0 DESCUENTO, 0 MARCAFAC, 0 PERIODICIDAD, 0 CONTINUACION, 0 MARCAENV,
			    0 COPAGOPROPIO, 0 ESDELAB, 0 ENLAB, 0 PIDECCOSTO, (CASE HCA.RIESGO WHEN '' THEN NULL ELSE HCA.RIESGO END) RIESGO, 
				A.NROAUT NUMAUTORIZA,left( AFI.TIPOAFILIADO,1) TIPOAFILIADO, @MENTREGA, A.CONSECUTIVOCIT, 1, 0, 
				COALESCE(CIT.ESPROGRAMAS,0), CASE (SELECT TOP 1 CODOM FROM @AUTD) 
											WHEN DBO.FNK_VALORVARIABLE('OMCODMEDICAMENTOS') THEN @PROVEEDOR_FAR
											WHEN DBO.FNK_VALORVARIABLE('OMCODLABORATORIO') THEN @PROVEEDOR_EXA
											WHEN DBO.FNK_VALORVARIABLE('OMCODAPOYODX') THEN @PROVEEDOR_APO
											ELSE '' END
		    FROM @AUT A
			    INNER JOIN AFI   ON AFI.IDAFILIADO=A.IDAFILIADO
			    INNER JOIN USUSU ON USUSU.USUARIO=A.USUARIO
			    INNER JOIN PRE	ON A.PREFIJO=PRE.PREFIJO
			    LEFT  JOIN HCA   ON HCA.CONSECUTIVO=A.CONSECUTIVO
			    LEFT  JOIN CIT   ON CIT.CONSECUTIVO=COALESCE(HCA.CONSECUTIVOCIT,HCA.NOADMISION) AND ISNULL(CIT.CONSECUTIVO,'')<>'' AND CIT.IDAFILIADO=HCA.IDAFILIADO
			    LEFT  JOIN MED   ON MED.IDMEDICO=A.IDMEDICO
			    LEFT  JOIN MES   ON MES.IDEMEDICA=MED.IDEMEDICA
			    LEFT  JOIN PPT   ON PPT.IDTERCERO=(CASE ISNULL(A.IDTERCERO,'') WHEN '' THEN COALESCE(CIT.IDCONTRATANTE,AFI.IDADMINISTRADORA) ELSE A.IDTERCERO END)
								    AND PPT.IDPLAN=(CASE ISNULL(A.IDPLAN,'') WHEN '' THEN COALESCE(CIT.IDPLAN,AFI.IDPLAN) ELSE A.IDPLAN END)
			    LEFT  JOIN UBEQ  ON UBEQ.SYS_ComputerName=@EQUIPO
			    LEFT  JOIN CEN   ON CEN.CCOSTO=(CASE ISNULL(A.CCOSTO,'') WHEN '' THEN COALESCE(CIT.CCOSTO,UBEQ.CCOSTO) ELSE A.CCOSTO END)
			    LEFT  JOIN AFU   ON CEN.IDAREA=AFU.IDAREA
		    WHERE A.ID=@FIX

		    INSERT INTO AUTD (
			    IDAUT, NO_ITEM, IDSERVICIO, CANTIDAD, VALOR, VALORCOPAGO, VALORCOPAGOCOSTO, VALOREXCEDENTE, VALORTOTALCOSTO, IDPLAN, 
			    IMPRESO, AUTORIZADO, COMENTARIOS, PCOBERTURA, OBS, NORDEN, CCOSTO, CODIGOCPCJ, MARCAPAGO, NOAUTORIZEXT, 
			    ESDELAB, ENLAB, IDTERCEROCA, IDCONTRATO, FACTURADA, N_FACTURA, CNSFCT, AQUIENCOBRO, MARCACOPAGOORDEN, VALORPROV, 
			    PCOSTO, ITFC, CNSITFC, SYS_COMPUTERNAME, NOCOBRABLE, MDOSIFICACION, CANTIDIA, DIAS, FRECUENCIA, CODCUPS, 
			    POSOLOGIA, SINCRONIZADO, APOYODG_AMBITO, CITAAUTORIZADA, CLASEPOSOLOGIA, MARCA, USUARIOMARCA, 
			    NUM_ORDEN, PROCESADA, PRIORIDAD, GENERADO, PROTOCOLO
		    )
		    SELECT 
			    @IDAUT, ROW_NUMBER() OVER (ORDER BY D.ITEM), D.IDSERVICIO, D.CANTIDAD, 0, 0, 0, 0, 0, A.IDPLAN,
			    0, 0, '', 100, '', '', A.CCOSTO, '', 0, D.NROAUT, 
			    0, 0, A.IDTERCERO, 'SIN_DEFINIR', 0, '', '', 'N', 0, NULL, 
			    0, 0, NULL, @EQUIPO, 0, 0, 0, 0, 0, D.CODCUPS, 
			    '', 0, D.AMBITO, 0, 'Tomar', 0, '', 
				0, 0, 0, 0, D.PROTOCOLO
		    FROM @AUT A INNER JOIN @AUTD D ON A.ITEM=(CASE @MISMAAUT WHEN 1 THEN A.ITEM ELSE D.ITEM_AUT END)
		    WHERE A.ID=@FIX AND D.MARCA=1

		    EXEC SPK_CONFIRMAR_AUT @IDAUT

		    IF DBO.FNK_VALORVARIABLE('PEDIRFARMACIACE') = 'SI'
		    BEGIN
			    DECLARE @USUARIO VARCHAR(20), @IDBODEGA VARCHAR(20), @COMPANIA VARCHAR(20)
			    SELECT @USUARIO=USUARIO FROM AUT WHERE IDAUT=@IDAUT
				SELECT @IDBODEGA = ISNULL(IDBODEGA,IDBODEGA2), @COMPANIA = COMPANIA FROM UBEQ WHERE SYS_ComputerName = @EQUIPO

				IF DBO.FNK_VALORVARIABLE('BODEGA_PEDIDOINV_CE') = 'SEDE'
					SELECT @IDBODEGA = ISNULL(IDBODEGACM,IDBODEGALOG) FROM SED WHERE IDSEDE = @SEDE					
			    
				EXEC SPK_PEDIDOINVCE @IDAUT, @IDBODEGA, @COMPANIA, @SEDE, @USUARIO, @EQUIPO
		    END

		    PRINT 'Cambio el campo HCATD.APLICADA 0=SinAutorizar, 1=Autorizado, 2=NoAutorizado'
		    UPDATE HCATD SET APLICADA=D.MARCA
		    FROM @AUT A INNER JOIN @AUTD D ON A.ITEM=(CASE @MISMAAUT WHEN 1 THEN A.ITEM ELSE D.ITEM_AUT END)
			    INNER JOIN HCATD ON HCATD.CONSECUTIVO=A.CONSECUTIVO AND HCATD.IDSERVICIO=D.IDSERVICIO
		    WHERE A.ID=@FIX AND COALESCE(A.CONSECUTIVO,'')<>'' AND D.TABLA='HCA'

		    UPDATE FMED SET APLICADA=D.MARCA
		    FROM @AUT A INNER JOIN @AUTD D ON A.ITEM=(CASE @MISMAAUT WHEN 1 THEN A.ITEM ELSE D.ITEM_AUT END)
			    INNER JOIN FMED ON FMED.NOCONSECUTIVO=A.CONSECUTIVO AND FMED.IDSERVICIO=D.IDSERVICIO
		    WHERE A.ID=@FIX AND COALESCE(A.CONSECUTIVO,'')<>'' AND D.TABLA='FME'

		    PRINT 'Borro RPDX'
	    END
	    ELSE
	    BEGIN
		    UPDATE HCATD SET APLICADA=D.MARCA
		    FROM @AUT A INNER JOIN @AUTD D ON A.ITEM=(CASE @MISMAAUT WHEN 1 THEN A.ITEM ELSE D.ITEM_AUT END)
			    INNER JOIN HCATD ON HCATD.CONSECUTIVO=A.CONSECUTIVO AND HCATD.IDSERVICIO=D.IDSERVICIO
		    WHERE A.ID=@FIX AND COALESCE(A.CONSECUTIVO,'')<>'' AND D.MARCA=2 AND D.TABLA='HCA'

		    UPDATE FMED SET APLICADA=D.MARCA
		    FROM @AUT A INNER JOIN @AUTD D ON A.ITEM=(CASE @MISMAAUT WHEN 1 THEN A.ITEM ELSE D.ITEM_AUT END)
			    INNER JOIN FMED ON FMED.NOCONSECUTIVO=A.CONSECUTIVO AND FMED.IDSERVICIO=D.IDSERVICIO
		    WHERE A.ID=@FIX AND COALESCE(A.CONSECUTIVO,'')<>'' AND D.MARCA=2 AND D.TABLA='FME'
	    END
        SET @FIX = @FIX + 1
    END
    DELETE RPDX WHERE CNS=@CNSRPDX AND CANTIDAD IN (1,2)
    DELETE RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=0 
	    AND NOT EXISTS (SELECT 1 FROM RPDX D WHERE CANTIDAD=3
		    AND RPDX.CNS=D.CNS AND RPDX.ID1=D.ID1 AND RPDX.ID2=D.ID2 AND RPDX.ID3=D.ID3 AND RPDX.ID5=D.ID5)
END


