CREATE OR ALTER PROCEDURE DBO.SPQ_MAGD_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				,@IDMODELOAG_OLD VARCHAR(12)	,@ITEM INT
		,@COMPANIA VARCHAR(2)				,@IDSEDE      VARCHAR(5)		,@PREFIJO   VARCHAR(20)
		,@SYS_COMPUTERNAME VARCHAR(200)		,@CNSLOG	VARCHAR(20)			,@IDMODELOAG VARCHAR(12)
		,@PROCESO VARCHAR(100)= 'INSERT'	,@NOW VARCHAR(20) = REPLACE(CONVERT(VARCHAR,GETDATE(),102),'.','') 

BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

	IF @METODO = 'GUARDAR_MAGD'
	BEGIN
		
		SELECT @SYS_COMPUTERNAME = SYS_ComputerName FROM USUSU WHERE USUARIO = @USUARIO
		SELECT @IDSEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
		SELECT @COMPANIA = COMPANIA FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME

		BEGIN TRY
			SELECT @ITEM = ITEM, @IDMODELOAG = IDMODELOAG
			FROM OPENJSON(@PARAMETROS) WITH (
				ITEM		VARCHAR(20) '$.ITEM'
				,IDMODELOAG	VARCHAR(12)	'$.IDMODELOAG'
			)

			SELECT * INTO #MAGD 
			FROM OPENJSON(@PARAMETROS) WITH (
				 IDMODELOAG		VARCHAR(12)	'$.IDMODELOAG'
				,DIA			SMALLINT	'$.DIA'
				,HORAINICIAL	VARCHAR(6)	'$.HORAINICIAL_T'
				,HORAFINAL		VARCHAR(6)	'$.HORAFINAL_T'
				,INTERVALO		SMALLINT	'$.INTERVALO'
				,DISPONIBILIDAD	VARCHAR(20)	'$.DISPONIBILIDAD'
				,MPLAN			SMALLINT	'$.MPLAN'
				,IDPLAN			VARCHAR(6)	'$.IDPLAN'
				,WEB			BIT			'$.WEB'
				,MMODELO		SMALLINT	'$.MMODELO'
				,MODELOS		VARCHAR(256)'$.MODELOS'
				,VIRTUAL		SMALLINT	'$.VIRTUAL'
				,IDMODELOAG_OLD	VARCHAR(12)	'$.IDMODELOAG_OLD'
				,DIA_OLD		SMALLINT	'$.DIA_OLD'
				,DISPONIBILIDAD_OLD	VARCHAR(20)	'$.DISPONIBILIDAD_OLD'
				,IDPLAN_OLD		VARCHAR(6)	'$.IDPLAN_OLD'
				,HORAINICIAL_OLD DATETIME	'$.HORAINICIAL_OLD'
			)

			IF EXISTS (SELECT 1 FROM #MAGD WHERE COALESCE(INTERVALO,0)<1)
			BEGIN				
				SELECT 'KO' OK
				SELECT ERROR = 'El intervalo de minutos no puede ser menor o igual a 0 (cero)'
				RETURN	
			END

			EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@LOG', @CNSLOG OUTPUT
			SELECT @CNSLOG = @IDSEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @CNSLOG), 8)

			IF @ITEM IS NOT NULL SET @PROCESO='UPDATE'

			INSERT INTO @TBLERRORES(ERROR)
			SELECT 'La programación que intenta guardar es de tipo "MODELO" pero no incluye modelos de programas especiales'
			FROM #MAGD 
			WHERE DISPONIBILIDAD = 'Mode'
			AND COALESCE(MODELOS, '')='' 

			IF(SELECT COUNT(*) FROM @TBLERRORES) = 0
			BEGIN
				BEGIN -- USLOG y USLOGH
					INSERT INTO USLOG (CNSLOG ,COMPANIA ,NOADMISION ,PROCESO ,REQUEST ,REFERENCIA ,USUARIO ,FECHA ,SYS_ComputerName ,TABLA)
					SELECT	 CNSLOG=@CNSLOG		,COMPANIA=@COMPANIA		,NOADMISION=@IDMODELOAG		,PROCESO='MODELOS AGENDA' 
							,REQUEST=@PROCESO	,REFERENCIA = 'MAGD:IDMODELOAG ='+@IDMODELOAG		,USUARIO = @USUARIO 
							,FECHA = DBO.FNK_GETDATE()		,SYS_ComputerName = @SYS_COMPUTERNAME	,TABLA='MAGD'

					INSERT INTO USLOGH (CNSLOG ,ITEM ,CAMPO ,VALORANT ,VALORNVO )   
					SELECT @CNSLOG,1,'IDMODELOAG' , COALESCE(MAGD.IDMODELOAG,''), #MAGD.IDMODELOAG 
					FROM #MAGD LEFT JOIN
					MAGD ON MAGD.IDMODELOAG=COALESCE(#MAGD.IDMODELOAG_OLD, #MAGD.IDMODELOAG)
						AND	MAGD.DIA = COALESCE(#MAGD.DIA_OLD, #MAGD.DIA)
						AND MAGD.HORAINICIAL = COALESCE(#MAGD.HORAINICIAL_OLD, #MAGD.HORAINICIAL)
						AND	MAGD.DISPONIBILIDAD = COALESCE(#MAGD.DISPONIBILIDAD_OLD, #MAGD.DISPONIBILIDAD)
						AND	MAGD.IDPLAN = COALESCE(#MAGD.IDPLAN_OLD, #MAGD.IDPLAN) 
					UNION ALL
					SELECT @CNSLOG,2,'DIA' , COALESCE(CAST(MAGD.DIA AS VARCHAR),''), CAST(#MAGD.DIA AS VARCHAR)
					FROM #MAGD LEFT JOIN
					MAGD ON MAGD.IDMODELOAG=COALESCE(#MAGD.IDMODELOAG_OLD, #MAGD.IDMODELOAG)
						AND	MAGD.DIA = COALESCE(#MAGD.DIA_OLD, #MAGD.DIA)
						AND MAGD.HORAINICIAL = COALESCE(#MAGD.HORAINICIAL_OLD, #MAGD.HORAINICIAL)
						AND	MAGD.DISPONIBILIDAD = COALESCE(#MAGD.DISPONIBILIDAD_OLD, #MAGD.DISPONIBILIDAD)
						AND	MAGD.IDPLAN = COALESCE(#MAGD.IDPLAN_OLD, #MAGD.IDPLAN)
					UNION ALL
					SELECT @CNSLOG,3,'HORAINICIAL_TIME' , COALESCE(CONVERT(VARCHAR,MAGD.HORAINICIAL,108),''), CAST(CONVERT(VARCHAR,#MAGD.HORAINICIAL,108) AS VARCHAR)
					FROM #MAGD LEFT JOIN
					MAGD ON MAGD.IDMODELOAG=COALESCE(#MAGD.IDMODELOAG_OLD, #MAGD.IDMODELOAG)
						AND	MAGD.DIA = COALESCE(#MAGD.DIA_OLD, #MAGD.DIA)
						AND MAGD.HORAINICIAL = COALESCE(#MAGD.HORAINICIAL_OLD, #MAGD.HORAINICIAL)
						AND	MAGD.DISPONIBILIDAD = COALESCE(#MAGD.DISPONIBILIDAD_OLD, #MAGD.DISPONIBILIDAD)
						AND	MAGD.IDPLAN = COALESCE(#MAGD.IDPLAN_OLD, #MAGD.IDPLAN)
					UNION ALL
					SELECT @CNSLOG,4,'HORAFINAL_TIME' , COALESCE(CONVERT(VARCHAR,MAGD.HORAFINAL,108),''), CAST(CONVERT(VARCHAR,#MAGD.HORAFINAL,108) AS VARCHAR)
					FROM #MAGD LEFT JOIN
					MAGD ON MAGD.IDMODELOAG=COALESCE(#MAGD.IDMODELOAG_OLD, #MAGD.IDMODELOAG)
						AND	MAGD.DIA = COALESCE(#MAGD.DIA_OLD, #MAGD.DIA)
						AND MAGD.HORAINICIAL = COALESCE(#MAGD.HORAINICIAL_OLD, #MAGD.HORAINICIAL)
						AND	MAGD.DISPONIBILIDAD = COALESCE(#MAGD.DISPONIBILIDAD_OLD, #MAGD.DISPONIBILIDAD)
						AND	MAGD.IDPLAN = COALESCE(#MAGD.IDPLAN_OLD, #MAGD.IDPLAN)
					UNION ALL
					SELECT @CNSLOG,5,'DISPONIBILIDAD' , COALESCE(CAST(MAGD.DISPONIBILIDAD AS VARCHAR),''), CAST(#MAGD.DISPONIBILIDAD AS VARCHAR)
					FROM #MAGD LEFT JOIN
					MAGD ON MAGD.IDMODELOAG=COALESCE(#MAGD.IDMODELOAG_OLD, #MAGD.IDMODELOAG)
						AND	MAGD.DIA = COALESCE(#MAGD.DIA_OLD, #MAGD.DIA)
						AND MAGD.HORAINICIAL = COALESCE(#MAGD.HORAINICIAL_OLD, #MAGD.HORAINICIAL)
						AND	MAGD.DISPONIBILIDAD = COALESCE(#MAGD.DISPONIBILIDAD_OLD, #MAGD.DISPONIBILIDAD)
						AND	MAGD.IDPLAN = COALESCE(#MAGD.IDPLAN_OLD, #MAGD.IDPLAN)
					UNION ALL
					SELECT @CNSLOG,6,'MODELOS' , COALESCE(CAST(MAGD.MODELOS AS VARCHAR),''), CAST(#MAGD.MODELOS AS VARCHAR)
					FROM #MAGD LEFT JOIN
					MAGD ON MAGD.IDMODELOAG=COALESCE(#MAGD.IDMODELOAG_OLD, #MAGD.IDMODELOAG)
						AND	MAGD.DIA = COALESCE(#MAGD.DIA_OLD, #MAGD.DIA)
						AND MAGD.HORAINICIAL = COALESCE(#MAGD.HORAINICIAL_OLD, #MAGD.HORAINICIAL)
						AND	MAGD.DISPONIBILIDAD = COALESCE(#MAGD.DISPONIBILIDAD_OLD, #MAGD.DISPONIBILIDAD)
						AND	MAGD.IDPLAN = COALESCE(#MAGD.IDPLAN_OLD, #MAGD.IDPLAN)
				END

				IF @PROCESO='INSERT'
				BEGIN
				
					INSERT INTO MAGD (IDMODELOAG ,DIA ,HORAINICIAL ,HORAFINAL ,INTERVALO ,DISPONIBILIDAD ,MPLAN ,IDPLAN 
						,WEB ,MMODELO ,MODELOS ,VIRTUAL )   
					SELECT IDMODELOAG ,DIA 
						,CAST(CONCAT(@NOW,' ',HORAINICIAL,':00') AS DATETIME) AS HORAINICIAL 
						,CAST(CONCAT(@NOW,' ',HORAFINAL,':00') AS DATETIME) AS HORAFINAL 
						,INTERVALO ,DISPONIBILIDAD ,MPLAN ,COALESCE(IDPLAN,'')
						,WEB 
						,CASE WHEN DISPONIBILIDAD = 'Mode' THEN 1 ELSE COALESCE(MMODELO,0) END 
						,MODELOS ,COALESCE(VIRTUAL,0)
					FROM #MAGD AS T
				END
				ELSE
				BEGIN
					PRINT 'ACTUALIZO MAGD'
					PRINT 'MODELOS: ' + COALESCE(JSON_VALUE(@PARAMETROS,'$.MODELOS'), '')

					UPDATE MAGD
					SET  IDMODELOAG = T.IDMODELOAG
						,DIA		= T.DIA
						,HORAINICIAL= CAST(CONCAT(@NOW,' ',T.HORAINICIAL,':00') AS DATETIME)  
						,HORAFINAL	= CAST(CONCAT(@NOW,' ',T.HORAFINAL,':00') AS DATETIME)  
						,INTERVALO	= T.INTERVALO
						,DISPONIBILIDAD=T.DISPONIBILIDAD
						,MPLAN		= T.MPLAN
						,IDPLAN		= COALESCE(T.IDPLAN,'')
						,WEB		= T.WEB
						,MMODELO	= CASE WHEN T.DISPONIBILIDAD = 'Mode' THEN 1 ELSE COALESCE(T.MMODELO,0) END 
						,MODELOS	= T.MODELOS
						,VIRTUAL	= COALESCE(T.VIRTUAL,0)
					FROM #MAGD AS T INNER JOIN MAGD ON 
						MAGD.IDMODELOAG=T.IDMODELOAG_OLD
					AND	MAGD.DIA = T.DIA_OLD
					AND CAST(MAGD.HORAINICIAL AS TIME) = CAST(T.HORAINICIAL_OLD AS TIME)
					AND CAST(MAGD.HORAINICIAL AS TIME) = CAST(T.HORAINICIAL_OLD AS TIME)
					AND MAGD.DISPONIBILIDAD = T.DISPONIBILIDAD_OLD
					AND MAGD.IDPLAN = T.IDPLAN_OLD
				END
			END

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()          
		END CATCH

		IF(SELECT COUNT(*) FROM @TBLERRORES) >0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' OK

		RETURN
	END

	IF @METODO = 'ELIMINAR_MAGD'
	BEGIN
		
		SELECT @SYS_COMPUTERNAME = SYS_ComputerName FROM USUSU WHERE USUARIO = @USUARIO
		SELECT @IDSEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME
		SELECT @COMPANIA = COMPANIA FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME

		BEGIN TRY
			SELECT @ITEM = ITEM, @IDMODELOAG = IDMODELOAG
			FROM OPENJSON(@PARAMETROS) WITH (
				ITEM		VARCHAR(20) '$.ITEM'
				,IDMODELOAG	VARCHAR(12)	'$.IDMODELOAG'
			)

			SELECT * INTO #D 
			FROM OPENJSON(@PARAMETROS) WITH (
				 IDMODELOAG		VARCHAR(12)	'$.IDMODELOAG'
				,DIA			SMALLINT	'$.DIA'
				,HORAINICIAL	VARCHAR(6)	'$.HORAINICIAL_T'
				,HORAFINAL		VARCHAR(6)	'$.HORAFINAL_T'
				,INTERVALO		SMALLINT	'$.INTERVALO'
				,DISPONIBILIDAD	VARCHAR(20)	'$.DISPONIBILIDAD'
				,MPLAN			SMALLINT	'$.MPLAN'
				,IDPLAN			VARCHAR(6)	'$.IDPLAN'
				,WEB			BIT			'$.WEB'
				,MMODELO		SMALLINT	'$.MMODELO'
				,MODELOS		VARCHAR(256)'$.MODELOS'
				,VIRTUAL		SMALLINT	'$.VIRTUAL'
				,IDMODELOAG_OLD	VARCHAR(12)	'$.IDMODELOAG_OLD'
				,DIA_OLD		SMALLINT	'$.DIA_OLD'
				,DISPONIBILIDAD_OLD	VARCHAR(20)	'$.DISPONIBILIDAD_OLD'
				,IDPLAN_OLD		VARCHAR(6)	'$.IDPLAN_OLD'
				,HORAINICIAL_OLD DATETIME	'$.HORAINICIAL_OLD'
			)

			EXEC SPK_GENCONSECUTIVO @COMPANIA, @IDSEDE, '@LOG', @CNSLOG OUTPUT
			SELECT @CNSLOG = @IDSEDE + RIGHT('00000000' + CONVERT(VARCHAR(8), @CNSLOG), 8)

			BEGIN -- USLOG y USLOGH
				INSERT INTO USLOG (CNSLOG ,COMPANIA ,NOADMISION ,PROCESO ,REQUEST ,REFERENCIA ,USUARIO ,FECHA ,SYS_ComputerName ,TABLA)
				SELECT	 CNSLOG=@CNSLOG		,COMPANIA=@COMPANIA		,NOADMISION=@IDMODELOAG		,PROCESO='MODELOS AGENDA' 
						,REQUEST='DELETE'	,REFERENCIA = 'MAGD:IDMODELOAG ='+@IDMODELOAG		,USUARIO = @USUARIO 
						,FECHA = DBO.FNK_GETDATE()		,SYS_ComputerName = @SYS_COMPUTERNAME	,TABLA='MAGD'

				INSERT INTO USLOGH (CNSLOG ,ITEM ,CAMPO ,VALORANT ,VALORNVO )   
				SELECT @CNSLOG,1,'IDMODELOAG' , COALESCE(MAGD.IDMODELOAG,''), #D.IDMODELOAG 
				FROM #D LEFT JOIN
				MAGD ON MAGD.IDMODELOAG=COALESCE(#D.IDMODELOAG_OLD, #D.IDMODELOAG)
					AND	MAGD.DIA = COALESCE(#D.DIA_OLD, #D.DIA)
					AND MAGD.HORAINICIAL = COALESCE(#D.HORAINICIAL_OLD, #D.HORAINICIAL)
					AND	MAGD.DISPONIBILIDAD = COALESCE(#D.DISPONIBILIDAD_OLD, #D.DISPONIBILIDAD)
					AND	MAGD.IDPLAN = COALESCE(#D.IDPLAN_OLD, #D.IDPLAN) 
				UNION ALL
				SELECT @CNSLOG,2,'DIA' , COALESCE(CAST(MAGD.DIA AS VARCHAR),''), CAST(#D.DIA AS VARCHAR)
				FROM #D LEFT JOIN
				MAGD ON MAGD.IDMODELOAG=COALESCE(#D.IDMODELOAG_OLD, #D.IDMODELOAG)
					AND	MAGD.DIA = COALESCE(#D.DIA_OLD, #D.DIA)
					AND MAGD.HORAINICIAL = COALESCE(#D.HORAINICIAL_OLD, #D.HORAINICIAL)
					AND	MAGD.DISPONIBILIDAD = COALESCE(#D.DISPONIBILIDAD_OLD, #D.DISPONIBILIDAD)
					AND	MAGD.IDPLAN = COALESCE(#D.IDPLAN_OLD, #D.IDPLAN)
				UNION ALL
				SELECT @CNSLOG,3,'HORAINICIAL_TIME' , COALESCE(CONVERT(VARCHAR,MAGD.HORAINICIAL,108),''), CAST(CONVERT(VARCHAR,#D.HORAINICIAL,108) AS VARCHAR)
				FROM #D LEFT JOIN
				MAGD ON MAGD.IDMODELOAG=COALESCE(#D.IDMODELOAG_OLD, #D.IDMODELOAG)
					AND	MAGD.DIA = COALESCE(#D.DIA_OLD, #D.DIA)
					AND MAGD.HORAINICIAL = COALESCE(#D.HORAINICIAL_OLD, #D.HORAINICIAL)
					AND	MAGD.DISPONIBILIDAD = COALESCE(#D.DISPONIBILIDAD_OLD, #D.DISPONIBILIDAD)
					AND	MAGD.IDPLAN = COALESCE(#D.IDPLAN_OLD, #D.IDPLAN)
				UNION ALL
				SELECT @CNSLOG,4,'HORAFINAL_TIME' , COALESCE(CONVERT(VARCHAR,MAGD.HORAFINAL,108),''), CAST(CONVERT(VARCHAR,#D.HORAFINAL,108) AS VARCHAR)
				FROM #D LEFT JOIN
				MAGD ON MAGD.IDMODELOAG=COALESCE(#D.IDMODELOAG_OLD, #D.IDMODELOAG)
					AND	MAGD.DIA = COALESCE(#D.DIA_OLD, #D.DIA)
					AND MAGD.HORAINICIAL = COALESCE(#D.HORAINICIAL_OLD, #D.HORAINICIAL)
					AND	MAGD.DISPONIBILIDAD = COALESCE(#D.DISPONIBILIDAD_OLD, #D.DISPONIBILIDAD)
					AND	MAGD.IDPLAN = COALESCE(#D.IDPLAN_OLD, #D.IDPLAN)
				UNION ALL
				SELECT @CNSLOG,5,'DISPONIBILIDAD' , COALESCE(CAST(MAGD.DISPONIBILIDAD AS VARCHAR),''), CAST(#D.DISPONIBILIDAD AS VARCHAR)
				FROM #D LEFT JOIN
				MAGD ON MAGD.IDMODELOAG=COALESCE(#D.IDMODELOAG_OLD, #D.IDMODELOAG)
					AND	MAGD.DIA = COALESCE(#D.DIA_OLD, #D.DIA)
					AND MAGD.HORAINICIAL = COALESCE(#D.HORAINICIAL_OLD, #D.HORAINICIAL)
					AND	MAGD.DISPONIBILIDAD = COALESCE(#D.DISPONIBILIDAD_OLD, #D.DISPONIBILIDAD)
					AND	MAGD.IDPLAN = COALESCE(#D.IDPLAN_OLD, #D.IDPLAN)
				UNION ALL
				SELECT @CNSLOG,6,'MODELOS' , COALESCE(CAST(MAGD.MODELOS AS VARCHAR),''), CAST(#D.MODELOS AS VARCHAR)
				FROM #D LEFT JOIN
				MAGD ON MAGD.IDMODELOAG=COALESCE(#D.IDMODELOAG_OLD, #D.IDMODELOAG)
					AND	MAGD.DIA = COALESCE(#D.DIA_OLD, #D.DIA)
					AND MAGD.HORAINICIAL = COALESCE(#D.HORAINICIAL_OLD, #D.HORAINICIAL)
					AND	MAGD.DISPONIBILIDAD = COALESCE(#D.DISPONIBILIDAD_OLD, #D.DISPONIBILIDAD)
					AND	MAGD.IDPLAN = COALESCE(#D.IDPLAN_OLD, #D.IDPLAN)
            END
			
			DELETE MAGD
			FROM #D AS T INNER JOIN MAGD ON 
				MAGD.IDMODELOAG=T.IDMODELOAG_OLD
			AND	MAGD.DIA = T.DIA_OLD
			AND MAGD.HORAINICIAL = T.HORAINICIAL_OLD
			AND MAGD.DISPONIBILIDAD = T.DISPONIBILIDAD_OLD
			AND MAGD.IDPLAN = T.IDPLAN_OLD

		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()          
		END CATCH

		IF(SELECT COUNT(*) FROM @TBLERRORES) >0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END

		SELECT 'OK' OK
		RETURN
	END

	IF @METODO = 'PROGRAMAS'
	BEGIN
		SELECT 'OK' AS OK

		SELECT IDPESPECIAL, DESCESPECIAL
        FROM MPE
		ORDER BY DESCESPECIAL
 
      SELECT CODIGO AS value, CONCAT(CODIGO,' - ',DESCRIPCION) AS label FROM TGEN 
      WHERE TABLA='AFI'
      AND CAMPO='TIPOATENCION'
      AND DATO2='EXTRAMURAL'
      RETURN
	END
END



