CREATE OR ALTER PROCEDURE DBO.SPQ_FTR_MASIVA_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@CONSECUTIVO VARCHAR(20)           ,@DPR VARCHAR(20)                 ,@TIPOFAC VARCHAR(2)
      ,@N_fACTURA VARCHAR(20)             ,@FECHAFACT DATETIME              ,@IDTERCERO VARCHAR(20)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF @METODO='FACTURAR_CITAUT'     
   BEGIN         
      SELECT @CONSECUTIVO=CONSECUTIVO        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CONSECUTIVO  VARCHAR(20)   '$.CONSECUTIVO'
      )
      SELECT @DPR=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'),@COMPANIA='01',@IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
      FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_COMPUTERNAME=UBEQ.SYS_COMPUTERNAME
      WHERE USUARIO=@USUARIO
      SELECT @TIPOFAC='Factura',@FECHAFACT=DBO.FNK_GETDATE()
      PRINT 'Valido sede'
      IF NOT EXISTS(SELECT * FROM FDIAN WHERE IDENTIFICADOR=@IDSEDE AND PROCEDENCIA='FTR' AND COALESCE(VENCIDA,0)=0 )
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Sede: '+@IDSEDE+' No habilitada para emitir Facturas, Comuniquese con el Administrador del Sistema'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN

      END
	  IF EXISTS (SELECT * FROM CIT WHERE CONSECUTIVO = @CONSECUTIVO AND IDTERCEROCA = DBO.FNK_VALORVARIABLE('IDTERCEROPARTICULAR'))
	  BEGIN
		INSERT INTO @TBLERRORES(ERROR)
		SELECT 'La atencion a facturar es Particular, por lo que no se puede facturar.'ERROR

         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
	  END
      IF NOT EXISTS(SELECT * FROM CIT WHERE COALESCE(FACTURADA,0)=1 AND COALESCE(N_FACTURA,'')='' AND CONSECUTIVO=@CONSECUTIVO) 
      BEGIN
         BEGIN TRY   
            EXEC SPK_FACTURACE_CITAUT_COL @CONSECUTIVO,@DPR,@COMPANIA,@IDSEDE, @USUARIO,'','','','','','CI','', 'FALSE', NULL,@FECHAFACT,@TIPOFAC, @IDTERCERO                 
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'Cita ya Facturada o con Valores en Cero(0), Verifique e intente de nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @N_FACTURA=N_FACTURA FROM CIT WHERE CONSECUTIVO=@CONSECUTIVO
      SELECT 'OK' OK,@N_FACTURA N_FACTURA
      RETURN 
   END
END