IF EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_INVENTARIO' AND IDCONTROL='EXIS_COSTO' AND DESCRIPCION='Informe de Existencia-Costo')
BEGIN
   UPDATE  USPROH SET DESCRIPCION='Informes',SUBLABEL='Existencias,Listados,Kardex',ICONO='fa-solid fa-signal' WHERE IDPROCEDIMIENTO='MENUQ_INVENTARIO' AND IDCONTROL='EXIS_COSTO' AND DESCRIPCION='Informe de Existencia-Costo'
END
IF NOT EXISTS(SELECT * FROM USPROH WHERE IDPROCEDIMIENTO='MENUQ_INVENTARIO' AND IDCONTROL='AJUSTES_INV')
BEGIN
   INSERT INTO USPROH(IDPROCEDIMIENTO, IDCONTROL, TIPO, DESCRIPCION, WEB, RUTA, ICONO, CODIGOPADRE, AUTOMATICO, SEPARADOR, ORDEN, SUBLABEL, CODIGO, PAISES)
   SELECT 'MENUQ_INVENTARIO', 'AJUSTES_INV', 'M', 'Ajustes Generales', 1, 'inv.Ajustes_gnral', 'fa-solid fa-person-digging', 40, 0, 0, 210, 'Costos, Existencias', NULL, NULL
END