IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'VWK_AUT_FTR' AND TYPE='V')
BEGIN
   DROP VIEW VWK_AUT_FTR
END

GO
CREATE VIEW DBO.VWK_AUT_FTR WITH ENCRYPTION AS
SELECT DISTINCT AUT.IDAUT, AUT.NOAUT, AUT.FECHA, AUT.FECHAVENCE, AUT.IDAFILIADO,AFI.DOCIDAFILIADO,AFI.TIPO_DOC,AFI.NOMBREAFI, AUT.NUMCARNET, AUTD.IDPLAN,
      AUT.PREFIJO,PRE.NOM_PREFIJO,
       AUT.IDSEDE, AUT.TIPOAUTORIZACION, AUT.ALTOCOSTO, AUT.ATENCION, AUT.URGENCIA, AUT.IMPUTABLE_A, AUT.IDSOLICITANTE,
       AUT.IDPROVEEDOR, AUT.ESTADO, AUT.CONSANULADO, AUT.IDOPERADORANULA, AUT.FECHAANULA, AUT.CAUSALANULA, 
       AUT.NO_ITEMES, AUT.VALORTOTAL, AUT.VALORCOPAGO, AUT.VALORBENEFICIO, AUT.VALOREXEDENTE, AUT.VALORTOTALCOSTO,
       AUT.VALORCOPAGOCOSTO, AUT.IMPRESO, AUT.CXPGEN, AUT.CXCGEN, AUT.AUTORIZADOPOR, AUT.NUMAUTORIZA, AUT.FECHAAUTORIZA,
       AUT.AUTORIZADO, AUT.IDPESPECIAL, AUT.IDESTADOE, AUT.USUARIO, AUT.RECOBRARA, AUT.FUENTE, AUT.IDCAUSAEXT, 
       AUT.AMBITO, AUT.FINALIDAD, AUT.PERSONAL_AT, AUT.DXPPAL, AUT.DXRELACIONADO, AUT.COMPLICACION, AUT.FORMAQX,
       AUT.TIPOURGENCIA, AUT.SPD, AUT.NORECIBOCAJA, AUT.CLASEORDEN, AUT.GENEROCAJA, AUTD.IDTERCEROCA AS IDCONTRATANTE, 
       AUT.TIPOCOPAGO, AUT.PEDIDOINV, AUT.ENVIO, AUT.OBS, AUT.ESCONTINUACION, AUT.NOAUTORIGEN, AUT.IDSEDEORIGEN, 
       AUT.SEMANASCOT,
       AUT.LIQUIDAPC, AUT.OBSDX, AUT.COMITE, AUT.CERTIFICACION, AUT.IDCLASEAUT, AUT.CLASECONT, AUT.ESDEINV, 
       AUT.NOGENERACIONOPS, AUT.FECHAGEN, AUT.IDAREA, AUT.NIVELATENCION, AUT.CNSAFIAA, AUT.SUBCCOSTO, AUT.CCOSTO,
       AUT.PROCEDENCIA, AUT.IDAREAH, AUTD.FACTURADA, AUTD.N_FACTURA, AUTD.CNSFCT, AUT.VFACTURAS, AUT.FACTURABLE,
       AUT.DESCUENTO, AUT.TIPODTO, AUT.MARCAFAC, AUT.IDIPS, AUT.CLASECONTRATO, AUT.ENPAQUETE, AUT.IDCIRUGIA,
       AUT.SOAT, AUT.NOADMISION, AUT.IDCONTRATO, AUT.RUBRO, AUT.CLASERUBRO, AUT.FECHASOL, AUT.PERIODICIDAD, 
       AUT.CNSFACT, AUT.CONTINUACION, AUT.VLRUTOTRA, AUT.TIPOCONT, AUT.DXRELACIONADO2, AUT.FECHACOMITE,
       AUT.IDALTERNA, AUT.MARCAENV, AUT.COPAGOPROPIO, AUT.CNSHACTRAN, AUT.ESDELAB, AUT.ENLAB, AUT.COBRARA, 
       AUTD.IDTERCEROCA, AUT.CONSECUTIVOHCA, AUT.RAZONANULACION, AUT.FECHAREALIZACION, AUT.IDGRUPOSER, AUT.PEXTERNA,
       AUT.PIDECCOSTO, AUT.CODCAJA, AUT.TIPOCAJA, AUT.CERRADA    
FROM   AUT INNER JOIN AUTD ON AUT.IDAUT = AUTD.IDAUT
           INNER JOIN AFI  ON AUT.IDAFILIADO=AFI.IDAFILIADO
           INNER JOIN PRE ON  AUT.PREFIJO=PRE.PREFIJO
--WHERE  AUTD.FACTURADA = 0 OR AUTD.FACTURADA IS NULL


