CREATE OR ALTER PROCEDURE DBO.SPQ_CONTRATOS_ESPE @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
   DECLARE @PROCESO VARCHAR(20)           ,@IDTERCERO VARCHAR(20)           ,@NIT VARCHAR(20)
   ,@RAZONSOCIAL VARCHAR(20)              ,@IDPLAN VARCHAR(20)              ,@DESCPLAN VARCHAR(20)
   ,@PREFIJO VARCHAR(20)                  ,@NOM_PREFIJO VARCHAR(20)         ,@COPAFIJO DECIMAL(14,2)
   ,@COPAVAR DECIMAL(14,2)                ,@PRCOPAFIJO VARCHAR(20)          ,@PRCOPAVAR DECIMAL(14,2)
   ,@MOVILIDAD VARCHAR(20)                ,@IDPPTCNT INT                    ,@CIUDAD VARCHAR(20)
   ,@DISTRITO VARCHAR(20)                 ,@VALOR DECIMAL(14,2)             ,@ZONA VARCHAR(20)
   ,@IDPPTMOVI INT
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='CRUD_PPTCNT'     
   BEGIN   
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )

      SELECT @PROCESO=PROCESO,@IDPPTCNT=IDPPTCNT,@IDTERCERO=IDTERCERO, @NIT=NIT, @RAZONSOCIAL=RAZONSOCIAL,@IDPLAN=IDPLAN, @DESCPLAN=DESCPLAN,
         @PREFIJO=PREFIJO, @NOM_PREFIJO=NOM_PREFIJO,  @COPAFIJO=COPAFIJO, @COPAVAR=COPAVAR,    @PRCOPAFIJO=PRCOPAFIJO,
         @PRCOPAVAR=PRCOPAVAR, @MOVILIDAD=CASE WHEN MOVILIDAD='true' THEN 1 ELSE 0 END
      FROM   OPENJSON (@DATOS)
      WITH   (   
         IDPPTCNT  VARCHAR(20)     '$.ID',
         PROCESO VARCHAR(20)       '$.PROCESO',
         IDTERCERO VARCHAR(20)     '$.IDTERCERO',
         NIT VARCHAR(20)           '$.NIT',
         RAZONSOCIAL VARCHAR(120)  '$.RAZONSOCIAL',
         IDPLAN VARCHAR(20)        '$.IDPLAN',
         DESCPLAN VARCHAR(20)      '$.DESCPLAN',
         PREFIJO VARCHAR(20)       '$.PREFIJO',
         NOM_PREFIJO VARCHAR(20)   '$.NOM_PREFIJO',
         COPAFIJO DECIMAL(14,2)    '$.COPAFIJO',
         COPAVAR DECIMAL(14,2)     '$.COPAVAR',
         PRCOPAFIJO VARCHAR(20)    '$.PRCOPAFIJO',
         PRCOPAVAR DECIMAL(14,2)   '$.PRCOPAVAR',
         MOVILIDAD VARCHAR(10)     '$.MOVILIDAD'
        )  
      IF @PROCESO='Nuevo'            
      BEGIN
         IF NOT EXISTS(SELECT * FROM PPTCNT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND PREFIJO=@PREFIJO)
         BEGIN
            INSERT INTO PPTCNT (IDTERCERO, IDPLAN, PREFIJO, COPAFIJO, COPAVAR, PRCOPAFIJO, PRCOPAVAR, MOVILIDAD, IDMOVILIDAD)
            SELECT @IDTERCERO, @IDPLAN, @PREFIJO, @COPAFIJO, @COPAVAR, @PRCOPAFIJO, @PRCOPAVAR, @MOVILIDAD, NULL
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Ya existe un Contrato Especial para este tercero, contrato y categoria'
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         IF NOT EXISTS(SELECT * FROM PPTCNT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND PREFIJO=@PREFIJO AND ID<>@IDPPTCNT)
         BEGIN
            BEGIN TRY           
               UPDATE PPTCNT SET IDTERCERO=@IDTERCERO,IDPLAN=@IDPLAN,PREFIJO=@PREFIJO,COPAFIJO=@COPAFIJO,COPAVAR=@COPAVAR,
               PRCOPAFIJO=@PRCOPAFIJO,PRCOPAVAR=@PRCOPAVAR,MOVILIDAD=@MOVILIDAD
               WHERE ID=@IDPPTCNT                             
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Ya existe un Contrato Especial para este tercero, contrato y categoria'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
   IF @METODO='CRUD_PPTMOVI'     
   BEGIN   
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )

      SELECT @PROCESO=PROCESO,@IDPPTMOVI=IDPPTMOVI,@IDTERCERO=IDTERCERO, @NIT=NIT, @RAZONSOCIAL=RAZONSOCIAL,@IDPLAN=IDPLAN, @DESCPLAN=DESCPLAN,
             @CIUDAD=CIUDAD,@DISTRITO=DISTRITO,@VALOR=VALOR,@ZONA=ZONA,@COPAVAR=COPAVAR,@PRCOPAVAR=PRCOPAVAR
      FROM   OPENJSON (@DATOS)
      WITH   (   
         IDPPTMOVI  VARCHAR(20)    '$.ID',
         PROCESO VARCHAR(20)       '$.PROCESO',
         IDTERCERO VARCHAR(20)     '$.IDTERCERO',
         NIT VARCHAR(20)           '$.NIT',
         RAZONSOCIAL VARCHAR(120)  '$.RAZONSOCIAL',
         IDPLAN VARCHAR(20)        '$.IDPLAN',
         DESCPLAN VARCHAR(20)      '$.DESCPLAN',
         CIUDAD VARCHAR(20)        '$.CIUDAD',
         DISTRITO VARCHAR(20)      '$.DISTRITO',
         VALOR DECIMAL(14,2)       '$.VALOR',
         COPAVAR DECIMAL(14,2)     '$.COPAVAR',
         PRCOPAVAR DECIMAL(14,2)   '$.PRCOPAVAR',
         ZONA VARCHAR(20)          '$.ZONA'
        )  
      IF @PROCESO='Nuevo'            
      BEGIN
         IF NOT EXISTS(SELECT * FROM PPTMOVI WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND CIUDAD=@CIUDAD AND DISTRITO=@DISTRITO)
         BEGIN
            INSERT INTO PPTMOVI (IDTERCERO, IDPLAN, CIUDAD, DISTRITO, VALOR, ZONA,COPAVAR,PRCOPAVAR)
            SELECT @IDTERCERO, @IDPLAN, @CIUDAD, @DISTRITO, @VALOR, @ZONA,@COPAVAR,@PRCOPAVAR
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Ya existe una Zona de Movilidad para este tercero, Paquete  y Distrito'
         END
      END
      IF @PROCESO='Editar'
      BEGIN
         IF NOT EXISTS(SELECT * FROM PPTMOVI WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN AND CIUDAD=@CIUDAD AND DISTRITO=@DISTRITO AND ID<>@IDPPTMOVI)
         BEGIN
            PRINT 'Voy a actualizar'
            BEGIN TRY           
               UPDATE PPTMOVI SET IDTERCERO=@IDTERCERO,IDPLAN=@IDPLAN,CIUDAD=@CIUDAD,DISTRITO=@DISTRITO,VALOR=@VALOR,ZONA=@ZONA,COPAVAR=@COPAVAR,PRCOPAVAR=@PRCOPAVAR
               WHERE ID=@IDPPTMOVI                             
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
         END
         ELSE
         BEGIN
            INSERT INTO @TBLERRORES(ERROR)
            SELECT 'Ya existe una Zona de Movilidad para este tercero, Paquete  y Distrito'
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
END