CREATE OR ALTER PROCEDURE DBO.SPQ_RPT_NOMINA @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@CNSNIEPE VARCHAR(20)              ,@CNSPAGO  VARCHAR(20)           ,@NUMDOC    VARCHAR(20)
      ,@NRODOCUMENTO VARCHAR(20)          ,@SEXO VARCHAR(20)               ,@PNOMBRE VARCHAR(20)
      ,@SNOMBRE VARCHAR(20)               ,@PEAPELLIDO VARCHAR(20)         ,@SAPELLIDO VARCHAR(20)
      ,@F_NACIMIENTO DATE                 ,@DIRECCION VARCHAR(20)          ,@TELEFONO VARCHAR(20)
      ,@ESTCIVIL VARCHAR(20)              ,@GRUPO_SANG VARCHAR(20)         ,@NROCUENTA VARCHAR(20)
      ,@BANCO VARCHAR(20)                 ,@NOMINA VARCHAR(20)             ,@CCOSTO VARCHAR(20)
      ,@TCONTRATO VARCHAR(20)             ,@CODCARGO VARCHAR(20)           ,@GRADO VARCHAR(20)
      ,@NIVEL VARCHAR(20)                 ,@F_INGRESO DATETIME             ,@BASICO VARCHAR(20)
      ,@CIUD_DOC VARCHAR(20)              ,@NITSALUD VARCHAR(20)           ,@NITPENSION VARCHAR(20)
      ,@NITAREL VARCHAR(20)               ,@EMAIL VARCHAR(1000)              ,@NROLINEAS INT
      ,@CNSRPDX VARCHAR(20)               ,@INDICE INT                     ,@ERROR VARCHAR(2024)
      ,@XFECHA VARCHAR(20)                ,@TIPODOC VARCHAR(10)            ,@ER BIT
      ,@BASICOC DECIMAL(14,2)             ,@ESTRUCTURA INT                 ,@SEDEMPLE VARCHAR(6)
      ,@ITEM INT                          ,@XFECHA1 VARCHAR(20)            ,@TERRORES SMALLINT 
      ,@TOK SMALLINT                      ,@TODOS SMALLINT                 ,@IDTERCERO VARCHAR(20)
      ,@IDTERCERONEW VARCHAR(20)          ,@NUMDOCNEW VARCHAR(20)          ,@PLANTANEW VARCHAR(20)
      ,@DIASXCARGO INT                    ,@HORASLABOR INT                 
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON

   IF @METODO='COLILLAS'     
   BEGIN  
      PRINT 'INGRESO AL DATO'
      SELECT @CNSNIEPE=CNSNIEPE,@CNSPAGO=CNSPAGO,@NUMDOC=NUMDOC       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSNIEPE VARCHAR(20) '$.CNSNIEPE',
        CNSPAGO VARCHAR(20) '$.CNSPAGO',
        NUMDOC VARCHAR(20) '$.NUMDOC'
       )           
      IF EXISTS(SELECT * FROM NIEPE WHERE CNSNIEPE=@CNSNIEPE AND CNSPAGO=@CNSPAGO AND NUMDOC=@NUMDOC)
      BEGIN
         SELECT  'OK' OK
         SELECT NIEPE.CODNOMINA,NIEPE.CNSPAGO,NIEPE.NOMBRE_PERIODO,NOMBRE_AREA,NOMBRE_CCOSTO,TER.NIT,TER.RAZONSOCIAL,
         NIEPE.DETALLE_CARGO,NIEPE.BASICO,NIEPE.VALOR_INGRESOS,VALOR_EGRESOS,NIEPE.VALOR_APORTES,NIEPE.VALOR_NETO
         FROM NIEPE INNER JOIN NPER ON NIEPE.CNSPAGO=NPER.CNSPAGO
                    INNER JOIN NPPAG ON NPER.CODPPAG=NPPAG.CODPPAG
                    INNER JOIN TER ON NIEPE.NUMDOC=TER.IDTERCERO
         WHERE CNSNIEPE=@CNSNIEPE 
         AND NIEPE.CNSPAGO=@CNSPAGO 
         AND NUMDOC=@NUMDOC
         SELECT CODCONCEPTO+'  '+NOMBRE_CONCEPTO+CASE WHEN COALESCE(IDTERCERO_PRF,'')<>'' AND IDTERCERO_PRF<>NUMDOC THEN ' : '+RAZONSOCIAL_PRF ELSE '' END NOMBRE_CONCEPTO,
                CONVERT(DECIMAL(14,2),CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),CASE WHEN TIPO='Ingreso' THEN VALOR ELSE 0 END) DEVENGADOS,
                CONVERT(DECIMAL(14,2),CASE WHEN TIPO='Egreso' AND VALOR> 0 THEN VALOR ELSE 0 END) DEDUCIDOS,
                CONVERT(DECIMAL(14,2),CASE WHEN TIPO='Egreso' AND VALOR =0 THEN VALOR_APORTES ELSE 0 END) EMPLEADOR 
         FROM NIEPED
         WHERE CNSNIEPE=@CNSNIEPE 
         AND NUMDOC=@NUMDOC
      END
   END   
   IF @METODO='LISTA_PAGOS'     
   BEGIN         
      SELECT @CNSPAGO= CNSPAGO     
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         CNSPAGO VARCHAR(20) '$.CNSPAGO'
         )           
      IF EXISTS(SELECT  * FROM NIEPE WHERE CNSPAGO=@CNSPAGO)
      BEGIN
         SELECT 'OK' OK

         SELECT CNSNIEPE,CNSPAGO,NIEPE.NUMDOC,TER.NIT,NIEPE.NOMBRE_EMPLEADO,COALESCE(NEMP.EMAIL,TER.EMAIL)EMAIL
         FROM NIEPE INNER JOIN TER ON NIEPE.NUMDOC=TER.IDTERCERO
                    INNER JOIN NEMP ON NIEPE.NUMDOC=NEMP.NUMDOC
         WHERE CNSPAGO=@CNSPAGO
         ORDER BY TER.NIT ASC
         RETURN
      END
   END   
	IF @METODO = 'CREA_RPDX'     
	BEGIN         
		SELECT @CNSRPDX = ''
		     , @IDSEDE = COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE)
			 , @COMPANIA = COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA)
			 , @SYS_COMPUTERNAME = COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU 
		     LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE 
		     USUSU.USUARIO = @USUARIO
		
		BEGIN TRY           
			PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE=' + COALESCE(@IDSEDE,'SIN SEDE')   
			SELECT @CNSRPDX=''

			EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT  
			SELECT @CNSRPDX = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)

			PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'')   
            
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSRPDX CNSRPDX
		RETURN 
	END   
	IF @METODO='CARGAR_NEMP'
	BEGIN
			
		DECLARE @LINEA AS VARCHAR(MAX)
		DECLARE @TABLA AS TABLE(
			ITEM INT IDENTITY(1,1),
			VALOR VARCHAR(MAX)
		)

      SELECT  @NROLINEAS=COUNT(*)
		FROM OPENJSON(@PARAMETROS, '$.LINEAS') 

      PRINT '@NROLINEAS='+CAST(@NROLINEAS AS VARCHAR(20))
      IF @NROLINEAS>0
      BEGIN

		   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		   WHERE USUSU.USUARIO=@USUARIO

		   PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT  
		   SELECT @CNSRPDX = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'') 

         SELECT @INDICE=0
		   DECLARE SUBIR_CURSOR CURSOR FOR   
	      SELECT VALUE 
		   FROM OPENJSON(@PARAMETROS, '$.LINEAS')		  
		   OPEN SUBIR_CURSOR  
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   WHILE @@FETCH_STATUS = 0  
		   BEGIN  
			   DELETE @TABLA WHERE 1=1

			   INSERT INTO @TABLA(VALOR)
			   SELECT VALUE FROM string_split(@LINEA,',')
            
            SELECT @ESTRUCTURA=COUNT(*) FROM @TABLA


            SET @ERROR=''
            SET @ER=0
            SELECT  @NRODOCUMENTO = NULL,@SEXO = NULL,@PNOMBRE = NULL,@SNOMBRE = NULL,@PEAPELLIDO = NULL,@SAPELLIDO = NULL,
                    @F_NACIMIENTO = NULL,@DIRECCION = NULL,@TELEFONO = NULL,@ESTCIVIL = NULL,@GRUPO_SANG = NULL,@NROCUENTA = NULL,
                    @BANCO = NULL,@NOMINA = NULL,@CCOSTO = NULL,@TCONTRATO = NULL,@CODCARGO = NULL,@GRADO = NULL,@NIVEL = NULL,
                    @F_INGRESO = NULL,@BASICO = NULL,@CIUD_DOC = NULL,@NITSALUD = NULL,@NITPENSION = NULL,@NITAREL = NULL,
                    @EMAIL = NULL,@SEDEMPLE=NULL

            BEGIN TRY           
               SELECT @NRODOCUMENTO=VALOR FROM @TABLA WHERE ITEM=1+@INDICE
               SELECT @TIPODOC=VALOR FROM @TABLA WHERE ITEM=2+@INDICE
               SELECT @SEXO=VALOR FROM @TABLA WHERE ITEM=3+@INDICE
               SELECT @PNOMBRE=VALOR FROM @TABLA WHERE ITEM=4+@INDICE
               SELECT @SNOMBRE=VALOR FROM @TABLA WHERE ITEM=5+@INDICE
               SELECT @PEAPELLIDO=VALOR FROM @TABLA WHERE ITEM=6+@INDICE
               SELECT @SAPELLIDO=VALOR FROM @TABLA WHERE ITEM=7+@INDICE
               SELECT @XFECHA=VALOR FROM @TABLA WHERE ITEM=8+@INDICE
               IF ISDATE(@XFECHA)=1
               BEGIN
               SELECT @F_NACIMIENTO=CONVERT(DATE,VALOR) FROM @TABLA WHERE ITEM=8+@INDICE
               END
               ELSE 
               BEGIN
                  SELECT @F_NACIMIENTO=NULL,@ER=1,@ERROR='Fecha de Nacimiento no Valida '+@XFECHA
               END
               SELECT @DIRECCION=VALOR FROM @TABLA WHERE ITEM=9+@INDICE
               SELECT @TELEFONO=VALOR FROM @TABLA WHERE ITEM=10+@INDICE
               SELECT @ESTCIVIL=VALOR FROM @TABLA WHERE ITEM=11+@INDICE
               SELECT @GRUPO_SANG=VALOR FROM @TABLA WHERE ITEM=12+@INDICE
               SELECT @NROCUENTA=VALOR FROM @TABLA WHERE ITEM=13+@INDICE
               SELECT @BANCO=VALOR FROM @TABLA WHERE ITEM=14+@INDICE
               SELECT @NOMINA=VALOR FROM @TABLA WHERE ITEM=15+@INDICE
               SELECT @CCOSTO=VALOR FROM @TABLA WHERE ITEM=16+@INDICE
               SELECT @TCONTRATO=VALOR FROM @TABLA WHERE ITEM=17+@INDICE
               SELECT @CODCARGO=VALOR FROM @TABLA WHERE ITEM=18+@INDICE
               SELECT @GRADO=VALOR FROM @TABLA WHERE ITEM=19+@INDICE
               SELECT @NIVEL=VALOR FROM @TABLA WHERE ITEM=20+@INDICE
               SELECT @XFECHA=VALOR FROM @TABLA WHERE ITEM=21+@INDICE
               IF ISDATE(@XFECHA)=1
               BEGIN
                  SELECT @F_INGRESO=CONVERT(DATE,VALOR) FROM @TABLA WHERE ITEM=21+@INDICE
               END
               ELSE 
               BEGIN
                  SELECT @F_INGRESO=NULL,@ER=1,@ERROR='Fecha de Ingreso no Valida ='+@XFECHA
               END
               SELECT @BASICO=VALOR FROM @TABLA WHERE ITEM=22+@INDICE
               SELECT @CIUD_DOC=VALOR FROM @TABLA WHERE ITEM=23+@INDICE
               SELECT @NITSALUD=VALOR FROM @TABLA WHERE ITEM=24+@INDICE
               SELECT @NITPENSION=VALOR FROM @TABLA WHERE ITEM=25+@INDICE
               SELECT @NITAREL=VALOR FROM @TABLA WHERE ITEM=26+@INDICE
               SELECT @EMAIL=VALOR FROM @TABLA WHERE ITEM=27+@INDICE
               SELECT @SEDEMPLE=VALOR FROM @TABLA WHERE ITEM=28+@INDICE
               IF @ESTRUCTURA <> 28
               BEGIN
                  SELECT @ER=1,@ERROR='Error de Estructura Campos ='+CAST(@ESTRUCTURA AS VARCHAR(4))
               END            

               IF @ER=1
               BEGIN
                  INSERT INTO RPDX(CNS,IDTERCERO,CNS1,ID1,ID2,ID3,ID4,ID5,FECHA1,STRINGMEDIO1,ID8,ID9,ID10,ID11,ID12,ID13,
                                    ID14,ID16,ID17,ID18,ID19,FECHA2,VALOR1,ID20,STRINGCORTO1,STRINGCORTO2,STRINGMEDIO3,
                                    STRINGGRANDE2,CANTIDAD10,STRINGMAX,CNS2)
                  SELECT @CNSRPDX,@NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,@NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,
                         @GRADO,@NIVEL,@F_INGRESO,CASE WHEN ISNUMERIC(@BASICO)=1 THEN @BASICO ELSE 0 END,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,@EMAIL,1,@ERROR,@SEDEMPLE
               END
               ELSE
               BEGIN
                  PRINT 'Validaición de existencia de datos'
                  
                  IF LEN(@TIPODOC)<=0 OR LEN(@TIPODOC)>3
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Tipo de Documento no Valido'
                  END
                  IF LEN(@NRODOCUMENTO)<=6 OR LEN(@NRODOCUMENTO)>11
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Nro  de Documento no Valido'
                  END
                  IF @F_INGRESO>DBO.FNK_GETDATE()
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Fecha de Ingreso Mayor a la Actual'
                  END
                  IF  @F_NACIMIENTO > DBO.FNK_GETDATE()
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Fecha de Nacimiento Mayor a la Actual'
                  END
                  IF NOT EXISTS(SELECT * FROM NOMI WHERE CODNOMINA=@NOMINA)
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+', Codigo de la Nomina No existe'
                  END
                  IF NOT EXISTS(SELECT * FROM CEN WHERE CCOSTO=@CCOSTO AND ESTADO='Activo')
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Centro de Costo  No existe o Esta inactivo @CCOSTO='+@CCOSTO
                  END
                  IF NOT EXISTS(SELECT * FROM NCARNG WHERE CODCARGO=@CODCARGO AND GRADO=@GRADO AND NIVEL=@NIVEL)
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',No existe el Codigo de Cargo, Grado y Nivel Verifique CODCARGO='+@CODCARGO+' GRADO='+@GRADO
                  END 
                  ELSE
                  BEGIN
                     IF ISNUMERIC(@BASICO)=1
                     BEGIN
                        SELECT TOP 1 @BASICOC=BASICO FROM NCARNGV WHERE CODCARGO=@CODCARGO AND GRADO=@GRADO AND NIVEL=@NIVEL ORDER BY FECHA DESC
                        IF @BASICO <> @BASICO
                        BEGIN
                           SELECT @ER=1,@ERROR=@ERROR+',Inconsistencia entre el Basico del Cargo vs el Basico del Empleado'
                        END
                     END
                     ELSE
                     BEGIN
                        SELECT @ER=1,@ERROR=@ERROR+',Error en el Basico = '+@BASICO
                     END
                  END
                  IF NOT EXISTS(SELECT * FROM TER WHERE (IDTERCERO=@NITSALUD OR NIT=@NITSALUD))
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',El idtercero para Aportes en SALUD  no Existe '
                  END
                  IF NOT EXISTS(SELECT * FROM TER WHERE (IDTERCERO=@NITPENSION OR NIT=@NITPENSION))
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',El idtercero para Aportes en PENSION  no Existe '
                  END
                  IF NOT EXISTS(SELECT * FROM TER WHERE (IDTERCERO=@NITAREL OR NIT=@NITAREL))
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',El idtercero para Aportes en ARL  no Existe '
                  END
                  IF LEN(@EMAIL)<5 OR CHARINDEX('@',@EMAIL,0)=0
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Correo Electronico no Valido '
                  END
                  IF NOT EXISTS(SELECT  * FROM SED WHERE IDSEDE=@SEDEMPLE)
                  BEGIN
                     SELECT @ER=1,@ERROR=@ERROR+',Sede Asociada al Empleado no Existe '+@SEDEMPLE
                  END
  
                  INSERT INTO RPDX(CNS,IDTERCERO,CNS1,ID1,ID2,ID3,ID4,ID5,FECHA1,STRINGMEDIO1,ID8,ID9,ID10,ID11,ID12,ID13,
                                    ID14,ID16,ID17,ID18,ID19,FECHA2,VALOR1,ID20,STRINGCORTO1,STRINGCORTO2,STRINGMEDIO3,
                                    STRINGGRANDE2,CANTIDAD10,STRINGMAX,CNS2)
                  SELECT @CNSRPDX,@NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,@NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,
                         @GRADO,@NIVEL,@F_INGRESO,CASE WHEN ISNUMERIC(@BASICO)=1 THEN @BASICO ELSE 0 END,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,@EMAIL,@ER,@ERROR,@SEDEMPLE
               END
            END TRY
            BEGIN CATCH
                SELECT @NRODOCUMENTO=VALOR FROM @TABLA WHERE ITEM=1+@INDICE
                INSERT INTO RPDX(CNS,IDTERCERO,STRINGGRANDE1,STRINGMAX,CANTIDAD10)
                SELECT @CNSRPDX,@NUMDOC,ERROR_MESSAGE(),@LINEA,1
            END CATCH
            
           SET @INDICE += @ESTRUCTURA
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   END  
		  
		   CLOSE SUBIR_CURSOR  
		   DEALLOCATE SUBIR_CURSOR  

         SELECT @NROLINEAS=COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX --AND CANTIDAD=1

         SELECT @TERRORES=SUM(CASE WHEN CANTIDAD10=1 THEN 1 ELSE 0 END),@TOK =SUM(CASE WHEN CANTIDAD10=1 THEN 0 ELSE 1 END)
         FROM RPDX WHERE CNS=@CNSRPDX 

         SELECT 'OK' OK,@CNSRPDX CNSRPDX,@NROLINEAS TODOS,@TERRORES ERRADOS,@TOK TOK
         RETURN

      END
      ELSE
      BEGIN
         SELECT 'KO','No se encontraron Datos para Procesar, Verfique e intente de nuevo' ERROR
         RETURN
      END
	END
   IF @METODO='VALIDAR_RPDXEMP'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS NVARCHAR(MAX) AS JSON 
      )
                 
      SELECT @CNSRPDX=CNS, @ITEM=ID, @NRODOCUMENTO= NRODOCUMENTO,@TIPODOC= TIPO_DOC,@SEXO= SEXO,@PNOMBRE= PNOMBRE,@SNOMBRE= SNOMBRE,@PEAPELLIDO= PEAPELLIDO,@SAPELLIDO= SAPELLIDO,
            @XFECHA=CONVERT(VARCHAR,CAST(REPLACE(F_NACIMIENTO,'-','/') AS DATE),103),@DIRECCION= DIRECCION,@TELEFONO= TELEFONO,@ESTCIVIL= ESTCIVIL,@GRUPO_SANG= GRUPO_SANG,@NROCUENTA= NROCUENTA,
            @BANCO= BANCO,@NOMINA= NOMINA,@CCOSTO= CCOSTO,@TCONTRATO= TCONTRATO,@CODCARGO= CODCARGO,@GRADO= GRADO,@NIVEL= NIVEL,@XFECHA1=CONVERT(VARCHAR,CAST(REPLACE(F_INGRESO,'-','/')AS DATE),103),
            @BASICO= BASICO,@CIUD_DOC= CIUD_DOC,@NITSALUD= NITSALUD,@NITPENSION= NITPENSION,@NITAREL= NITAREL,@EMAIL= EMAIL,@SEDEMPLE= IDSEDE,@ERROR= ERRORTXT
      FROM   OPENJSON (@DATOS)
      WITH   (  
      CNS VARCHAR(20)           '$.CNS',   
      ID INT                    '$.ID',   
      NRODOCUMENTO VARCHAR(20)  '$.NRODOCUMENTO',
      TIPO_DOC VARCHAR(20)      '$.TIPO_DOC',
      SEXO VARCHAR(20)          '$.SEXO',
      PNOMBRE VARCHAR(20)       '$.PNOMBRE',
      SNOMBRE VARCHAR(20)       '$.SNOMBRE',
      PEAPELLIDO VARCHAR(20)    '$.PEAPELLIDO',
      SAPELLIDO VARCHAR(20)     '$.SAPELLIDO',
      F_NACIMIENTO VARCHAR(20)  '$.F_NACIMIENTO',
      DIRECCION VARCHAR(20)     '$.DIRECCION',
      TELEFONO VARCHAR(20)      '$.TELEFONO',
      ESTCIVIL VARCHAR(20)      '$.ESTCIVIL',
      GRUPO_SANG VARCHAR(20)    '$.GRUPO_SANG',
      NROCUENTA VARCHAR(20)     '$.NROCUENTA',
      BANCO VARCHAR(20)         '$.BANCO',
      NOMINA VARCHAR(20)        '$.NOMINA',
      CCOSTO VARCHAR(20)        '$.CCOSTO',
      TCONTRATO VARCHAR(20)     '$.TCONTRATO',
      CODCARGO VARCHAR(20)      '$.CODCARGO',
      GRADO VARCHAR(20)         '$.GRADO',
      NIVEL VARCHAR(20)         '$.NIVEL',
      F_INGRESO VARCHAR(20)     '$.F_INGRESO',
      BASICO VARCHAR(20)        '$.BASICO',
      CIUD_DOC VARCHAR(20)      '$.CIUD_DOC',
      NITSALUD VARCHAR(20)      '$.NITSALUD',
      NITPENSION VARCHAR(20)    '$.NITPENSION',
      NITAREL VARCHAR(20)       '$.NITAREL',
      EMAIL VARCHAR(20)         '$.EMAIL',
      IDSEDE VARCHAR(20)        '$.IDSEDE',
      ERRORTXT VARCHAR(20)      '$.ERRORTXT'
      )    

      PRINT 'Validaición de existencia de datos'
      SELECT @ER=0, @ERROR=''
      
      IF LEN(@TIPODOC)<=0 OR LEN(@TIPODOC)>3
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',Tipo de Documento no Valido'
      END
      IF LEN(@NRODOCUMENTO)<=6 OR LEN(@NRODOCUMENTO)>11
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',Nro  de Documento no Valido'
      END
      IF ISDATE(@XFECHA1)=0
      BEGIN
         SELECT @ER=1,@ERROR='Fecha de Ingreso no Valida ='+@XFECHA1
      END
      ELSE
      BEGIN
         SELECT @F_INGRESO=CAST(@XFECHA1 AS DATE)
         IF @F_INGRESO>DBO.FNK_GETDATE()
         BEGIN
            SELECT @ER=1,@ERROR=@ERROR+',Fecha de Ingreso Mayor a la Actual '+@XFECHA1
         END
      END
      IF ISDATE(@XFECHA)=0
      BEGIN
         SELECT @ER=1,@ERROR='Fecha de Ingreso no Valida ='+@XFECHA
      END
      ELSE
      BEGIN
         SELECT @F_NACIMIENTO=CAST(@XFECHA AS DATE)
         IF  @F_NACIMIENTO > DBO.FNK_GETDATE()
         BEGIN
            SELECT @ER=1,@ERROR=@ERROR+',Fecha de Nacimiento Mayor a la Actual'+@XFECHA
         END
      END
      IF NOT EXISTS(SELECT * FROM NOMI WHERE CODNOMINA=@NOMINA)
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+', Codigo de la Nomina No existe'
      END
      IF NOT EXISTS(SELECT * FROM CEN WHERE CCOSTO=@CCOSTO AND ESTADO='Activo')
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',Centro de Costo  No existe o Esta inactivo @CCOSTO='+@CCOSTO
      END
      IF NOT EXISTS(SELECT * FROM NCARNG WHERE CODCARGO=@CODCARGO AND GRADO=@GRADO AND NIVEL=@NIVEL)
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',No existe el Codigo de Cargo, Grado y Nivel Verifique CODCARGO='+@CODCARGO+' GRADO='+@GRADO
      END 
      ELSE
      BEGIN
         IF ISNUMERIC(@BASICO)=1
         BEGIN
            SELECT TOP 1 @BASICOC=BASICO FROM NCARNGV WHERE CODCARGO=@CODCARGO AND GRADO=@GRADO AND NIVEL=@NIVEL ORDER BY FECHA DESC
            IF @BASICO <> @BASICO
            BEGIN
               SELECT @ER=1,@ERROR=@ERROR+',Inconsistencia entre el Basico del Cargo vs el Basico del Empleado'
            END
         END
         ELSE
         BEGIN
            SELECT @ER=1,@ERROR=@ERROR+',Error en el Basico = '+@BASICO
         END
      END
      IF NOT EXISTS(SELECT * FROM TER WHERE (IDTERCERO=@NITSALUD OR NIT=@NITSALUD))
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',El idtercero para Aportes en SALUD  no Existe '
      END
      IF NOT EXISTS(SELECT * FROM TER WHERE (IDTERCERO=@NITPENSION OR NIT=@NITPENSION))
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',El idtercero para Aportes en PENSION  no Existe '
      END
      IF NOT EXISTS(SELECT * FROM TER WHERE (IDTERCERO=@NITAREL OR NIT=@NITAREL))
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',El idtercero para Aportes en ARL  no Existe '
      END
      IF LEN(@EMAIL)<5 OR CHARINDEX('@',@EMAIL,0)=0
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',Correo Electronico no Valido '
      END
      IF NOT EXISTS(SELECT  * FROM SED WHERE IDSEDE=@SEDEMPLE)
      BEGIN
         SELECT @ER=1,@ERROR=@ERROR+',Sede Asociada al Empleado no Existe '+@SEDEMPLE
      END
      
      PRINT 'ACTUALIZO RPDX ITEM='+CAST(@ITEM AS VARCHAR(20))+'@ER='+CAST(@ER AS VARCHAR(2))
      BEGIN TRY           
         UPDATE RPDX SET IDTERCERO=@NRODOCUMENTO,CNS1=@TIPODOC,ID1=@SEXO,ID2=@PNOMBRE,ID3=@SNOMBRE,ID4=@PEAPELLIDO,ID5=@SAPELLIDO,
         FECHA1=@F_NACIMIENTO,STRINGMEDIO1=@DIRECCION,ID8=@TELEFONO,ID9=@ESTCIVIL,ID10=@GRUPO_SANG,ID11=@NROCUENTA,
         ID12=@BANCO,ID13=@NOMINA,ID14=@CCOSTO,ID16=@TCONTRATO,ID17=@CODCARGO,ID18=@GRADO,ID19=@NIVEL,FECHA2=@F_INGRESO,
         VALOR1=@BASICO,ID20=@CIUD_DOC,STRINGCORTO1=@NITSALUD,STRINGCORTO2=@NITPENSION,STRINGMEDIO3=@NITAREL,STRINGGRANDE2=@EMAIL,
         CNS2=@SEDEMPLE,CANTIDAD10=@ER,STRINGMAX=@ERROR
         WHERE ITEM=@ITEM            
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END

      SELECT @TERRORES=SUM(CASE WHEN CANTIDAD10= 1 THEN 1 ELSE 0 END),@TOK =SUM(CASE WHEN CANTIDAD10=1 THEN 0 ELSE 1 END),@TODOS=COUNT(*)
      FROM RPDX WHERE CNS=@CNSRPDX 
      SELECT 'OK' OK,@TERRORES ERRADOS,@TOK TOK,@TODOS TODOS
      RETURN 
   END
   IF @METODO='EXPORT_ERROREMP'     
   BEGIN         
      SELECT @CNSRPDX=CNS       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNS  VARCHAR(20)   '$.CNS'
      )

      SELECT 'OK' OK

      SELECT IDTERCERO AS NRODOCUMENTO,CNS1 AS TIPO_DOC,ID1 AS SEXO, ID2 AS PNOMBRE, ID3 AS SNOMBRE,
      ID4 AS PEAPELLIDO, ID5 AS SAPELLIDO,DBO.FNK_FECHA_GRINGA(FECHA1) AS F_NACIMIENTO, STRINGMEDIO1 AS DIRECCION,
      ID8 AS TELEFONO,ID9 AS ESTCIVIL,ID10 AS GRUPO_SANG, ID11 AS NROCUENTA, ID12 AS BANCO,
      ID13 AS NOMINA, ID14 AS CCOSTO, ID16 AS TCONTRATO, ID17 AS CODCARGO, ID18 AS GRADO,
      ID19 AS NIVEL, DBO.FNK_FECHA_GRINGA(FECHA2) AS F_INGRESO,VALOR1 AS BASICO, ID20 AS CIUD_DOC,
      STRINGCORTO1 AS NITSALUD, STRINGCORTO2 AS NITPENSION, STRINGMEDIO3 AS NITAREL,
      STRINGGRANDE2 AS EMAIL,CNS2 AS IDSEDE,STRINGMAX AS ERRORTXT
      FROM [dbo].[RPDX]
      WHERE CNS=@CNSRPDX
      AND CANTIDAD10 = 1       
   END  
   IF @METODO='RPDX_SUBIRNEMP'     
   BEGIN         
      SELECT @CNSRPDX=CNS,@IDTERCERO=IDTERCERO      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNS  VARCHAR(20)   '$.CNS',
      IDTERCERO  VARCHAR(20)   '$.IDTERCERO'
      )
      IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCERO AND ESTADO='Activo')
      BEGIN
         SELECT 'KO' KO,'Idtercero no encontrado en el maestro de Terceros, No se Puede continuar'ERROR
         RETURN
      END
      IF NOT EXISTS(SELECT * FROM NEMP WHERE TERCEROID=@IDTERCERO AND ESTADO='Activo')
      BEGIN
         SELECT 'KO' KO,'Idtercero no encontrado en el maestro de Empleados, No se Puede continuar'ERROR
         RETURN
      END
      SELECT * INTO #TERE FROM TER WHERE IDTERCERO=@IDTERCERO AND ESTADO='Activo'
      SELECT * INTO #NEMP FROM NEMP WHERE TERCEROID =@IDTERCERO AND ESTADO='Activo'
      SELECT @NUMDOC=NUMDOC FROM #NEMP
		SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO
      DECLARE PG_CURSOR CURSOR FOR 

      SELECT ITEM, IDTERCERO AS NRODOCUMENTO,CNS1 AS TIPO_DOC,ID1 AS SEXO, ID2 AS PNOMBRE, ID3 AS SNOMBRE,
      ID4 AS PEAPELLIDO, ID5 AS SAPELLIDO,DBO.FNK_FECHA_GRINGA(FECHA1) AS F_NACIMIENTO, STRINGMEDIO1 AS DIRECCION,
      ID8 AS TELEFONO,ID9 AS ESTCIVIL,ID10 AS GRUPO_SANG, ID11 AS NROCUENTA, ID12 AS BANCO,
      ID13 AS NOMINA, ID14 AS CCOSTO, ID16 AS TCONTRATO, ID17 AS CODCARGO, ID18 AS GRADO,
      ID19 AS NIVEL, DBO.FNK_FECHA_GRINGA(FECHA2) AS F_INGRESO,VALOR1 AS BASICO, ID20 AS CIUD_DOC,
      STRINGCORTO1 AS NITSALUD, STRINGCORTO2 AS NITPENSION, STRINGMEDIO3 AS NITAREL,
      STRINGGRANDE2 AS EMAIL,CNS2 AS IDSEDE
      FROM RPDX 
      WHERE CNS=@CNSRPDX
      AND CANTIDAD10 = 0
      ORDER BY ITEM 
      OPEN PG_CURSOR    
      FETCH NEXT FROM PG_CURSOR    
      INTO @ITEM, @NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,
           @NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,@GRADO,@NIVEL,@F_INGRESO,@BASICO,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,
           @EMAIL,@SEDEMPLE
      WHILE @@FETCH_STATUS = 0    
      BEGIN
         PRINT 'CREANDO EL TERCERO'
         IF NOT EXISTS(SELECT * FROM TER WHERE NIT=@NRODOCUMENTO AND ESTADO='Activo')
         BEGIN
            SELECT @IDTERCERONEW=SPACE(20)
            EXEC SPK_GENCONSECUTIVO '01', @IDSEDE, '@TER', @IDTERCERONEW OUTPUT  
            SELECT @IDTERCERONEW = @IDSEDE + REPLACE(SPACE(10 - LEN(@IDTERCERONEW))+LTRIM(RTRIM(@IDTERCERONEW)),SPACE(1),0)
            
            INSERT INTO TER(IDTERCERO, RAZONSOCIAL, NIT, DV, TIPO_ID, IDALTERNA1, IDALTERNA2, DIRECCION, NATJURIDICA, CIUDAD, 
                            TELEFONOS, FAX, APA, F_INSCRIPTO, F_RENOVACION, F_VENCIMIENT, R_LEGAL, TIPO_ID_R, NIT_R,  ESTADO, 
                            REQAUTORIZA, CUENTA, ZONA, CIA, ACT_ECONOMICA, ENVIODICAJA, MODOCOPAGO, EMPIDMODELOPC, DIASVTO, 
                            ESEXTRANJERO, CLASIFICADOR, IDGRUPOIMP, AUTORETENEDOR, GRANCONTRIBUYENTE,  EMAIL, URL, NOMBRES_R_LEGAL,
                            P_APELLIDO_R_LEGAL, S_APELLIDO_R_LEGAL, DE_NIT_R_LEGAL, IDACTIVIDAD, TIPOREGIMEN, MSUCURSALES, FORMAPRE,
                            CODIGO_ARP, NORAD, TIPOAPORTANTE, CODOPERADOR,  CODIGO_AFP, CODIGO_CCF, ASESOR_AFI, ASESOR_MTO, 
                            FNAC_RLEGAL, HOBBIE_RL, PROF_RL, EMAIL_RL, TIPOID_TH, NID_TH, DE_NIT_TH, NOMBRES_TH, P_APELLIDO_TH, 
                            S_APELLIDO_TH, FNAC_TH,  HOBBIE_TH, PROF_TH, EMAIL_TH, ITFC, CNSITFC, HOMOLOGO, PNOMBRE, SNOMBRE, 
                            PAPELLIDO, SAPELLIDO, CUE_BANCARIA, TIPO_CUE, BANCO, SUCURSAL, NIIF_VTAEQUIEFECTIVOS, MANFACT, 
                            CTAVIGENCIAANTE,  EMAILRECIBOFE, COD_RESP_FISCAL, MANEXO, PREFIJOXML, SUFIJOXML, SIIF, SIIFCODIGOPCI,
                            SIIFCONTRATO, SIIFCORREOSUPER, MEDIOPAGO, RUC, USUCREA, FECHACREA, CRONICO, CONTRATOID_MP,  PYM)
            SELECT @IDTERCERONEW,CONCAT(@PEAPELLIDO,' ',COALESCE(@SAPELLIDO,''),' ',@PNOMBRE,' ',COALESCE(@SNOMBRE,'')),@NRODOCUMENTO,DBO.FNK_CALCULA_DV(@NRODOCUMENTO),@TIPODOC, NULL, NULL, @DIRECCION, NATJURIDICA, CIUDAD, 
                  @TELEFONO, FAX, APA, F_INSCRIPTO, F_RENOVACION, F_VENCIMIENT, R_LEGAL, TIPO_ID_R, NIT_R,  'Activo', 
                  REQAUTORIZA, CUENTA, ZONA, CIA, ACT_ECONOMICA, ENVIODICAJA, MODOCOPAGO, EMPIDMODELOPC, DIASVTO, 
                  ESEXTRANJERO, CLASIFICADOR, IDGRUPOIMP, AUTORETENEDOR, GRANCONTRIBUYENTE,  @EMAIL, URL, NOMBRES_R_LEGAL,
                  P_APELLIDO_R_LEGAL, S_APELLIDO_R_LEGAL, DE_NIT_R_LEGAL, IDACTIVIDAD, TIPOREGIMEN, MSUCURSALES, FORMAPRE,
                  CODIGO_ARP, NORAD, TIPOAPORTANTE, CODOPERADOR,  CODIGO_AFP, CODIGO_CCF, ASESOR_AFI, ASESOR_MTO, 
                  FNAC_RLEGAL, HOBBIE_RL, PROF_RL, EMAIL_RL, TIPOID_TH, NID_TH, DE_NIT_TH, NOMBRES_TH, P_APELLIDO_TH, 
                  S_APELLIDO_TH, FNAC_TH,  HOBBIE_TH, PROF_TH, EMAIL_TH, ITFC, CNSITFC, HOMOLOGO, @PNOMBRE, @SNOMBRE, 
                  @PEAPELLIDO, @SAPELLIDO, @NROCUENTA, TIPO_CUE, @BANCO, SUCURSAL, NIIF_VTAEQUIEFECTIVOS, MANFACT, 
                  CTAVIGENCIAANTE,  @EMAIL, COD_RESP_FISCAL, MANEXO, PREFIJOXML, SUFIJOXML, SIIF, SIIFCODIGOPCI,
                  SIIFCONTRATO, SIIFCORREOSUPER, MEDIOPAGO, RUC, USUCREA, FECHACREA, CRONICO, CONTRATOID_MP,  PYM
            FROM #TERE

            IF NOT EXISTS(SELECT * FROM TEXCA WHERE IDTERCERO=@IDTERCERONEW AND IDCATEGORIA=DBO.FNK_VALORVARIABLE('TERCATEMPLEADO'))
            BEGIN
               INSERT INTO TEXCA (IDTERCERO, IDCATEGORIA, ESTADO, TIPOIPS)  
               SELECT @IDTERCERONEW, DBO.FNK_VALORVARIABLE('TERCATEMPLEADO'), 'Activo', NULL  
            END          
         END
         ELSE
         BEGIN
            SELECT @IDTERCERONEW=IDTERCERO FROM TER WHERE NIT=@NRODOCUMENTO AND ESTADO='Activo'

            UPDATE TER SET DIRECCION=@DIRECCION,TELEFONOS=@TELEFONO,BANCO=@BANCO, CUE_BANCARIA=@NROCUENTA,PNOMBRE=@PNOMBRE,
                           SNOMBRE=@SNOMBRE,PAPELLIDO=@PEAPELLIDO,SAPELLIDO=@SAPELLIDO,DV=DBO.FNK_CALCULA_DV(@NRODOCUMENTO),
                           EMAIL=@EMAIL
            WHERE IDTERCERO=@IDTERCERONEW

            IF NOT EXISTS(SELECT * FROM TEXCA WHERE IDTERCERO=@IDTERCERONEW AND IDCATEGORIA=DBO.FNK_VALORVARIABLE('TERCATEMPLEADO'))
            BEGIN
               INSERT INTO TEXCA (IDTERCERO, IDCATEGORIA, ESTADO, TIPOIPS)  
               SELECT @IDTERCERONEW, DBO.FNK_VALORVARIABLE('TERCATEMPLEADO'), 'Activo', NULL  
            END
         END
         PRINT 'VALIDACION ANTES DE CONTINUAR'
         IF NOT EXISTS(SELECT * FROM TER WHERE IDTERCERO=@IDTERCERONEW AND ESTADO='Activo')
         BEGIN
            PRINT 'Tercero con Problemas'
            UPDATE RPDX SET STRINGMAX='Tercero no fue Creado, verifique e intente de nuevo',CANTIDAD10=1 WHERE CNS=@CNSRPDX AND ITEM=@ITEM
            FETCH NEXT FROM PG_CURSOR    
            INTO @ITEM,@NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,
                 @NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,@GRADO,@NIVEL,@F_INGRESO,@BASICO,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,
                 @EMAIL,@SEDEMPLE
            CONTINUE
         END
         UPDATE RPDX SET STRINGMEDIO4='Tercero fue Creado, o Actualizado Correctamente' WHERE CNS=@CNSRPDX AND ITEM=@ITEM
         PRINT 'VAMOS A CREAR EL EMPLEADO'
         IF EXISTS(SELECT * FROM NEMP WHERE TERCEROID=@IDTERCERONEW AND ESTADO='Activo' AND (FECHARETIRO IS NULL OR FECHARETIRO>=@F_INGRESO))
         BEGIN
            PRINT 'Empleado  con Problemas'
             UPDATE RPDX SET STRINGMAX='Empleado Con contrato vigente ,verifique e intente de nuevo',CANTIDAD10=1 WHERE CNS=@CNSRPDX AND ITEM=@ITEM
            FETCH NEXT FROM PG_CURSOR    
            INTO @ITEM,@NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,
                 @NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,@GRADO,@NIVEL,@F_INGRESO,@BASICO,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,
                 @EMAIL,@SEDEMPLE
            CONTINUE            
         END
         PRINT 'CREANDO EL EMPLEADO NUEVO'
         SELECT @NUMDOCNEW=SPACE(20)
         EXEC SPK_GENCONSECUTIVO '01', @IDSEDE, '@NEMP', @NUMDOCNEW OUTPUT  
         SELECT @NUMDOCNEW = @IDSEDE + REPLACE(SPACE(8 - LEN(@NUMDOCNEW))+LTRIM(RTRIM(@NUMDOCNEW)),SPACE(1),0)

         INSERT INTO NEMP(NUMDOC, SEXO, PRIMERNOMBRE, SEGUNDONOMBRE, PRIMERAPELLIDO, SEGUNDOAPELLIDO, IDAREA, CCOSTO, FECHAINGRESO, 
                        ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, HORASDELABOR,  DIASXCARGO, CODPLANTA, 
                        TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, 
                        TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL,  FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, 
                        ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG, TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE, 
                        CODUNG, CIUDADEXP, GRUPOPOB,  CLASEMP, LIDER, EMAIL, IDFOTO, GRUPO_DOC, PROCESO, NROCONVOCA, TIPO_DOC, 
                        DOCIDEMPLEADO, TERCEROID)
         SELECT @NUMDOCNEW,CASE UPPER(LEFT(@SEXO,1)) WHEN 'F' THEN 'Femenino' ELSE 'Maculino'END, @PNOMBRE, COALESCE(@SNOMBRE,''),
                @PEAPELLIDO,COALESCE(@SAPELLIDO,''),DBO.FNK_AREADELCCOSTO(@CCOSTO),@CCOSTO,CONVERT(DATE,@F_INGRESO),'Activo',NULL,
                NULL, @BASICO, @CODCARGO, @NIVEL, @GRADO, NULL,  NULL, NULL,TIPOSALARIO, TALLA_CALZADO, TALLA_CAMISA, TALLA_PANTALON,
                @GRUPO_SANG, NULL,CONCAT(UPPER(LEFT(@ESTCIVIL,1)),LOWER(RIGHT(@ESTCIVIL,LEN(@ESTCIVIL)-1))),@TCONTRATO, @NOMINA,@NROCUENTA,@BANCO,
                SUCURSAL,CONVERT(DATE,@F_NACIMIENTO),NULL, TIPOCESANTIAS, FLEY50,ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, CODPRG,
                TIPOCOTIZANTE, SUBTIPOCOTIZANTE, CLASERESIDENTE,CODUNG,@CIUD_DOC, GRUPOPOB,  CLASEMP, LIDER, @EMAIL, NULL, NULL, PROCESO,
                NROCONVOCA, @TIPODOC, @NRODOCUMENTO, @IDTERCERONEW
         FROM #NEMP

         IF NOT EXISTS(SELECT * FROM NEMP WHERE NUMDOC=@NUMDOCNEW)
         BEGIN
            PRINT 'Empleado  con Problemas'
            UPDATE RPDX SET STRINGMAX='no se pudo crear el empleado,verifique e intente de nuevo',CANTIDAD10=1 WHERE CNS=@CNSRPDX AND ITEM=@ITEM
            FETCH NEXT FROM PG_CURSOR    
            INTO @ITEM,@NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,
                 @NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,@GRADO,@NIVEL,@F_INGRESO,@BASICO,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,
                 @EMAIL,@SEDEMPLE
            CONTINUE 
         END
         UPDATE RPDX SET STRINGMEDIO6='Empleado Creado correctamente' WHERE CNS=@CNSRPDX AND ITEM=@ITEM
         PRINT ' VAMOS POR LA PLANTA'

         PRINT 'CREANDO EL PLANTA  NUEVA'
         SELECT @PLANTANEW=SPACE(20)
         EXEC SPK_GENCONSECUTIVO '01', @IDSEDE, '@NPLA', @PLANTANEW OUTPUT  
         SELECT @PLANTANEW = @IDSEDE + REPLACE(SPACE(8 - LEN(@PLANTANEW))+LTRIM(RTRIM(@PLANTANEW)),SPACE(1),0)

         SELECT @HORASLABOR=HORASDELABOR,@DIASXCARGO=DIAS,@BASICO=BASICO
         FROM NCARNGV WHERE CODCARGO=@CODCARGO AND GRADO=@GRADO AND NIVEL=@NIVEL ORDER BY FECHA DESC

         UPDATE NEMP SET HORASDELABOR=@HORASLABOR,DIASXCARGO=@DIASXCARGO
         WHERE NUMDOC=@NUMDOCNEW

         INSERT INTO NPLA(CODPLANTA, IDAREA, CCOSTO, CODCARGO, NIVEL, GRADO, NUMDOC, IDSEDE, CODUNG)
         SELECT @PLANTANEW, dbo.FNK_AREADELCCOSTO(@CCOSTO),@CCOSTO, @CODCARGO, @NIVEL, @GRADO, @NUMDOCNEW,@SEDEMPLE,
         (SELECT TOP 1 CODUNG FROM SEDUNG WHERE IDSEDE=@SEDEMPLE AND CCOSTO=@CCOSTO AND ESTADO='Activo')

         UPDATE RPDX SET STRINGMEDIO7='Empleado Agregado a la planta correctamente '+@PLANTANEW WHERE CNS=@CNSRPDX AND ITEM=@ITEM

         UPDATE NEMP SET HORASDELABOR=@HORASLABOR,DIASXCARGO=@DIASXCARGO,CODPLANTA=@PLANTANEW
         WHERE NUMDOC=@NUMDOCNEW

         PRINT 'AGREGO APORTES'

         INSERT INTO NPRFE(NUMDOC, CODPRF)
         SELECT @NUMDOCNEW,CODPRF FROM NPRFE WHERE NUMDOC=@NUMDOC

         INSERT INTO NPRFED(NUMDOC, CODPRF, ITEM, FECHAINI, IDTERCERO)
         SELECT @NUMDOCNEW, NPRFED.CODPRF, ITEM, @F_INGRESO,
         (SELECT TOP 1 IDTERCERO FROM TER WHERE (IDTERCERO=@NITSALUD OR NIT=@NITSALUD AND ESTADO='Activo'))
         FROM NPRFED INNER JOIN NPRF ON NPRFED.CODPRF=NPRF.CODPRF
         WHERE NUMDOC=@NUMDOC
         AND NPRF.TIPO='Salud'
         AND NPRF.CLASE='Aporte'

         INSERT INTO NPRFED(NUMDOC, CODPRF, ITEM, FECHAINI, IDTERCERO)
         SELECT @NUMDOCNEW, NPRFED.CODPRF, ITEM, @F_INGRESO,
         (SELECT TOP 1 IDTERCERO FROM TER WHERE (IDTERCERO=@NITPENSION OR NIT=@NITPENSION AND ESTADO='Activo'))
         FROM NPRFED INNER JOIN NPRF ON NPRFED.CODPRF=NPRF.CODPRF
         WHERE NUMDOC=@NUMDOC
         AND NPRF.TIPO='Pension'
         AND NPRF.CLASE='Aporte'

         INSERT INTO NPRFED(NUMDOC, CODPRF, ITEM, FECHAINI, IDTERCERO)
         SELECT @NUMDOCNEW, NPRFED.CODPRF, ITEM, @F_INGRESO,
         (SELECT TOP 1 IDTERCERO FROM TER WHERE (IDTERCERO=@NITPENSION OR NIT=@NITPENSION AND ESTADO='Activo'))
         FROM NPRFED INNER JOIN NPRF ON NPRFED.CODPRF=NPRF.CODPRF
         WHERE NUMDOC=@NUMDOC
         AND NPRF.TIPO='FonSal'
         AND NPRF.CLASE='Aporte'

         INSERT INTO NPRFED(NUMDOC, CODPRF, ITEM, FECHAINI, IDTERCERO)
         SELECT @NUMDOCNEW, NPRFED.CODPRF, ITEM, @F_INGRESO,
         (SELECT TOP 1 IDTERCERO FROM TER WHERE (IDTERCERO=@NITAREL OR NIT=@NITAREL AND ESTADO='Activo'))
         FROM NPRFED INNER JOIN NPRF ON NPRFED.CODPRF=NPRF.CODPRF
         WHERE NUMDOC=@NUMDOC
         AND NPRF.TIPO='ARP'
         AND NPRF.CLASE='Aporte'

         INSERT INTO NOMIE(CODNOMINA, NUMDOC, ESTADO)
         SELECT @NOMINA,@NUMDOCNEW,'Activo'
         UNION ALL
         SELECT CODNOMINA,@NUMDOCNEW,'Activo'
         FROM NOMIE WHERE NUMDOC=@NUMDOC 
         AND  EXISTS(SELECT * FROM TER WHERE NOMIE.CODNOMINA=TER.IDTERCERO)

         PRINT 'POR ULTIMO NEMPHIS....'

         INSERT INTO NEMPHIS(NUMDOC, FECHAMOV, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, 
                              CODCARGO, NIVEL, GRADO, HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO,  TALLA_CAMISA, 
                              TALLA_PANTALON, GRUPOSANGUINEO, LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, 
                              SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS, FLEY50, ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, 
                              USUARIOMOD, FECHAMOD, SYS_COMPUTERNAME, OPERACION)
         SELECT NUMDOC,@F_INGRESO, SEXO, IDAREA, CCOSTO, FECHAINGRESO, ESTADO, FECHARETIRO, CAUSARETIRO, BASICO, CODCARGO, NIVEL, GRADO, 
                HORASDELABOR, DIASXCARGO, CODPLANTA, TIPOSALARIO, TALLA_CALZADO,  TALLA_CAMISA, TALLA_PANTALON, GRUPOSANGUINEO, 
                LIBRETAMILITAR, ESTADOCIVIL, TIPOCONTRATO, CODNOMINA, CTA_BCO, BANCO, SUCURSAL, FNACIMIENTO, FULTIMOPAGO, TIPOCESANTIAS,
                FLEY50,  ENSINDICATO, FORMADEPAGO, FONDODEVIVIENDA, 
                @USUARIO, dbo.FNK_GETDATE(), @SYS_COMPUTERNAME, 'Insert'
         FROM NEMP WHERE NUMDOC=@NUMDOCNEW

         UPDATE RPDX SET STRINGMEDIO8='Empleado Agregado a la NEMPHIS correctamente '+@NUMDOCNEW WHERE CNS=@CNSRPDX AND ITEM=@ITEM
         FETCH NEXT FROM PG_CURSOR    
         INTO @ITEM,@NRODOCUMENTO,@TIPODOC,@SEXO,@PNOMBRE,@SNOMBRE,@PEAPELLIDO,@SAPELLIDO,@F_NACIMIENTO,@DIRECCION,@TELEFONO,@ESTCIVIL,@GRUPO_SANG,
              @NROCUENTA,@BANCO,@NOMINA,@CCOSTO,@TCONTRATO,@CODCARGO,@GRADO,@NIVEL,@F_INGRESO,@BASICO,@CIUD_DOC,@NITSALUD,@NITPENSION,@NITAREL,
              @EMAIL,@SEDEMPLE
      END
      CLOSE PG_CURSOR
      DEALLOCATE PG_CURSOR

      SELECT 'OK' OK

      SELECT IDTERCERO,STRINGMEDIO4 as ENTERCEROS,STRINGMEDIO6 AS ENNOMINA,STRINGMEDIO7 as ENPLANTA,STRINGMEDIO8 AS ENHISTORICO
      FROM RPDX
      WHERE CNS=@CNSRPDX
      AND CANTIDAD10 = 0

      DELETE  RPDX 
      WHERE CNS=@CNSRPDX
      AND CANTIDAD10 = 0

      RETURN

   END 
   IF @METODO='BORRAR_RPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNS      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNS  VARCHAR(20)   '$.CNS'
      )
      DELETE RPDX WHERE CNS=@CNSRPDX
      SELECT 'OK'OK
      RETURN
   END
END


