CREATE OR ALTER PROCEDURE DBO.SPQ_ANEXOS_HADMFTR @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
      ,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
      ,@NOADMISION VARCHAR(20)            ,@CNSRPDX  VARCHAR(20)           ,@TAB VARCHAR(20)
      ,@TANEXO VARCHAR(20)                ,@IDTERCERO VARCHAR(20)          ,@IDPLAN VARCHAR(6)
      ,@N_FACTURA VARCHAR(20)             ,@ANEXO VARCHAR(20)              ,@CNSRPDXNEW  VARCHAR(20)
      ,@ITEM INT                          ,@DEMO VARCHAR(20)
      ,@PROCEDENCIA VARCHAR(10)           ,@IDFORMATOFTR VARCHAR(20)       ,@TIPOFAC    VARCHAR(2)
      ,@NOREFERENCIA VARCHAR(20)          ,@IMPRIMEIDALTERNA SMALLINT      ,@NROAFIS SMALLINT
      ,@VLLETRAS VARCHAR(1024)            ,@NROLETRAS SMALLINT             ,@REFERENCIA VARCHAR(20)
      ,@NOAUT VARCHAR(20)                 ,@VENDEDOR VARCHAR(20)           ,@F_FACTURA  DATETIME
      ,@USUFACTURA VARCHAR(20)            ,@NOMBREFACTU VARCHAR(120)       ,@IDFIRMA VARCHAR(20)
      ,@EQUIPO VARCHAR(256)               ,@FIMPRESION VARCHAR(70)         ,@ENTERO BIT
      ,@IXCOUNTRY VARCHAR(20)             ,@VLR_AFECTO DECIMAL(14,2)       ,@VLR_INAFECTO DECIMAL(14,2)
      ,@VLR_SUBTOTAL DECIMAL(14,2)        ,@CNSFNOT VARCHAR(20)


BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   IF DBO.FNK_VALORVARIABLE('BDATA_PRODUCCION')<>DB_NAME()
   BEGIN
      SELECT @DEMO='DEMO'
   END
   ELSE
   BEGIN
      SELECT @DEMO=''
   END
   IF @METODO='ANEXO_SINFAC'     
   BEGIN         
      SELECT @NOADMISION =NOADMISION      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      NOADMISION VARCHAR(20) '$.NOADMISION'
      )
      IF EXISTS(SELECT  * FROM HADM WHERE NOADMISION=@NOADMISION)
      BEGIN
         SELECT @IDSEDE=IDSEDE  FROM HADM WHERE NOADMISION=@NOADMISION
         IF COALESCE(@IDSEDE,'')=''
         BEGIN
            SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
            FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
            WHERE USUARIO=@USUARIO
         END
         SELECT @CNSRPDX=SPACE(20)
         EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = 'RPDX', @NVOCONSEC = @CNSRPDX OUTPUT
         BEGIN TRY           
              EXEC SPK_AFACTURAR @NOADMISION,@CNSRPDX               
         END TRY
         BEGIN CATCH
                 INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         INSERT INTO @TBLERRORES(ERROR)
         SELECT 'No se Encotro el Nro de Admision Verifique e Intente de Nuevo'
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK,@CNSRPDX CNSRPDX
      RETURN 
   END 
   IF @METODO='BORRA_RPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSRPDX VARCHAR(20) '$.CNSRPDX'
      )
      DELETE RPDX WHERE CNS=@CNSRPDX  
   END 
   IF @METODO='IMPRIMIR_ANEXO'     
   BEGIN         
      SELECT @TAB=TAB,@TANEXO=TANEXO,@ANEXO=ANEXO,@NOADMISION=NOADMISION,@IDTERCERO=IDTERCERO,@IDPLAN=IDPLAN,@N_FACTURA=N_FACTURA,
      @CNSRPDX=CNSRPDX,@ITEM=ITEM
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
       TAB  VARCHAR(20)    '$.TAB',
       TANEXO  VARCHAR(20)   '$.TANEXO',
       ANEXO  VARCHAR(20)   '$.ANEXO',
       NOADMISION  VARCHAR(20)   '$.NOADMISION',
       IDTERCERO  VARCHAR(20)   '$.IDTERCERO',
       IDPLAN  VARCHAR(20)   '$.IDPLAN',
       N_FACTURA  VARCHAR(20)   '$.N_FACTURA',
       CNSRPDX    VARCHAR(20)   '$.CNSRPDX',
       ITEM       INT           '$.ITEM'
      )
      IF @TAB<> 'Facturadas'
      BEGIN
         SELECT 'OK'OK,HADM.NOADMISION,DBO.FNK_FECHA_GRINGA(HADM.FECHA)+' '+CONVERT(VARCHAR,HADM.FECHA,108) FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,AFI.TIPOAFILIADO,
         TER.NIT,TER.RAZONSOCIAL,PPT.IDCONTRATO,PLN.TIPOSISTEMA,PLN.IDPLAN,AFI.NIVELSOCIOEC,DBO.FNK_FECHA_GRINGA(HADM.FECHAALTAMED)+' '+CONVERT(VARCHAR,HADM.FECHAALTAMED,108) F_ALTA,
         DATEDIFF(DAY,HADM.FECHA,COALESCE(HADM.FECHAALTAMED,DBO.FNK_GETDATE()))NDIAS,
         STUFF((
           SELECT DISTINCT ', '+N_FACTURA FROM HADMF WHERE  HADMF.NOADMISION=HADM.NOADMISION  AND ESTADO='P'
           FOR XML PATH('')
            ),1,1,'')FACTURAS,
         (SELECT TOP 1 DBO.FNK_FECHA_GRINGA(FTR.F_FACTURA) FROM FTR INNER JOIN HADMF ON HADMF.N_FACTURA=FTR.N_FACTURA WHERE HADMF.NOADMISION=HADM.NOADMISION AND PROCEDENCIA='SALUD' AND FTR.ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')F_FACTURA,
         (SELECT TOP 1 DBO.FNK_FECHA_GRINGA(FTR.F_VENCE) FROM  FTR INNER JOIN HADMF ON HADMF.N_FACTURA=FTR.N_FACTURA WHERE HADMF.NOADMISION=HADM.NOADMISION AND PROCEDENCIA='SALUD' AND FTR.ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')F_VENCE,
         @USUARIO USUARIORPT,DBO.FNK_FECHA_GRINGA(GETDATE())F_RPT, CONVERT(VARCHAR,GETDATE(),108)H_RPT,HADM.VLR_COPAGOEXTERNO,@DEMO ESTADO
         FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
                   INNER JOIN TER ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=TER.IDTERCERO
                   INNER JOIN PLN ON CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PLN.IDPLAN
                   LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                     CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
         WHERE HADM.NOADMISION=@NOADMISION
      END
      ELSE
      BEGIN
         SELECT 'OK'OK,HADM.NOADMISION,DBO.FNK_FECHA_GRINGA(HADM.FECHA)+' '+CONVERT(VARCHAR,HADM.FECHA,108) FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AFI.EDAD,AFI.TIPOAFILIADO,
         TER.NIT,TER.RAZONSOCIAL,PPT.IDCONTRATO,PLN.TIPOSISTEMA,PLN.IDPLAN,AFI.NIVELSOCIOEC,DBO.FNK_FECHA_GRINGA(HADM.FECHAALTAMED)+' '+CONVERT(VARCHAR,HADM.FECHAALTAMED,108) F_ALTA,
         DATEDIFF(DAY,HADM.FECHA,COALESCE(HADM.FECHAALTAMED,DBO.FNK_GETDATE()))NDIAS,HADMF.N_FACTURA AS FACTURAS,
         DBO.FNK_FECHA_DDMMAA(FTR.F_FACTURA)F_FACTURA,DBO.FNK_FECHA_DDMMAA(FTR.F_VENCE)F_VENCE,
         @USUARIO USUARIORPT,DBO.FNK_FECHA_DDMMAA(GETDATE())F_RPT, CONVERT(VARCHAR,GETDATE(),108)H_RPT,HADM.VLR_COPAGOEXTERNO,FTR.VALORSERVICIOS,FTR.VALORCOPAGO,FTR.VR_TOTAL,
         CASE WHEN COALESCE(@DEMO,'')='' THEN CASE WHEN FTR.ESTADO='A' THEN 'ANULADA' WHEN FTR.ESTADO='P' AND COALESCE(FTR.TIPOANULACION,'')='NC' THEN 'ANULADA NC' ELSE 'OK' END ELSE @DEMO END ESTADO
         FROM HADM INNER JOIN AFI ON HADM.IDAFILIADO=AFI.IDAFILIADO
                   INNER JOIN HADMF ON HADM.NOADMISION=HADMF.NOADMISION
                   INNER JOIN FTR   ON HADMF.N_FACTURA=FTR.N_FACTURA
                   INNER JOIN TER   ON FTR.IDTERCERO=TER.IDTERCERO
                   INNER JOIN PLN   ON FTR.IDPLAN=PLN.IDPLAN
                   INNER JOIN PPT   ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
         WHERE HADM.NOADMISION=@NOADMISION  
         AND HADMF.N_FACTURA=@N_FACTURA
      END
      IF @TAB='Admision'
      BEGIN
         IF @ANEXO='Normal'
         BEGIN
            SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                      CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                      ELSE SER.IDSERVICIO END
                 ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
             END IDSERVICIO, 
             REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
             CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
             CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
             HPRED.VALORCOPAGO)VALORCOPAGO,
			 CONVERT(DECIMAL(14,2),CONVERT(INT,HPRED.CANTIDAD)*CONVERT(DECIMAL(14,2),HPRED.VALOR))VALOREXCEDENTE
            FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                      INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                      INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                      INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                      LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                      LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                      LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                        CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                      LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE HPRE.NOADMISION=@NOADMISION
            AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
            AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
            AND HPRE.PREFIJO<>DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
            ORDER BY HPRE.PREFIJO ASC,HPRE.FECHA ASC

         END
         IF @ANEXO='Area'
         BEGIN
            SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                      CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                      ELSE SER.IDSERVICIO END
                 ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
             END IDSERVICIO,
             REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
             CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
             CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
             HPRED.VALORCOPAGO)VALORCOPAGO,
			 CONVERT(DECIMAL(14,2),CONVERT(INT,HPRED.CANTIDAD)*CONVERT(DECIMAL(14,2),HPRED.VALOR))VALOREXCEDENTE
			 --CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE
            FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                      INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                      INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                      INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                      LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                      LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                      LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                        CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                      LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE HPRE.NOADMISION=@NOADMISION
            AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
            AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
            AND HPRE.PREFIJO<>DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
            ORDER BY HPRE.IDAREA ASC,  HPRE.PREFIJO ASC,HPRE.FECHA ASC
         END
         IF @ANEXO='Prefijo'
         BEGIN
            SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                      CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                      ELSE SER.IDSERVICIO END
                 ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
             END IDSERVICIO,
             REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
             CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE SER.CODCUPS END CODCUM,
             CONVERT(INT,SUM(HPRED.CANTIDAD))CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
             SUM(HPRED.VALORCOPAGO))VALORCOPAGO,
			 SUM(CONVERT(DECIMAL(14,2),CONVERT(INT,HPRED.CANTIDAD)*CONVERT(DECIMAL(14,2),HPRED.VALOR)))VALOREXCEDENTE
			 --CONVERT(DECIMAL(14,2),SUM(HPRED.VALOREXCEDENTE))VALOREXCEDENTE
            FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                      INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                      INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                      INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                      LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                      LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                      LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                        CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                      LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE HPRE.NOADMISION=@NOADMISION
            AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
            AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
            AND HPRE.PREFIJO<>DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
            GROUP BY  HPRE.PREFIJO,PRE.NOM_PREFIJO, CONVERT(INT,HPRED.CANTIDAD),
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                      CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                      ELSE SER.IDSERVICIO END
                 ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
             END ,REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),''),
             CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE SER.CODCUPS END,
             CONVERT(DECIMAL(14,2),HPRED.VALOR)
            ORDER BY HPRE.PREFIJO ASC
         END
         IF @ANEXO='Ccosto'
         BEGIN
            SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                      CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                      ELSE SER.IDSERVICIO END
                 ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
             END IDSERVICIO,
             REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
             CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
             CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
             HPRED.VALORCOPAGO)VALORCOPAGO,
			 CONVERT(DECIMAL(14,2),CONVERT(INT,HPRED.CANTIDAD)*CONVERT(DECIMAL(14,2),HPRED.VALOR))VALOREXCEDENTE
			 --CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE
            FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                      INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                      INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                      INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                      LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                      LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                      LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                        CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                      LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE HPRE.NOADMISION=@NOADMISION
            AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
            AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
            AND HPRE.PREFIJO<>DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
            ORDER BY HPRE.CCOSTO ASC,  HPRE.PREFIJO ASC,HPRE.FECHA ASC
      END
      PRINT 'Agrego las Cirugias'
      SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
      CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                  CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                     CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                  ELSE SER.IDSERVICIO END
            ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
         END IDSERVICIO,
         REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
         CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
         CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
         HPRED.VALORCOPAGO)VALORCOPAGO,CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE,
         SER1.IDSERVICIO IDCIRUGIA,SER1.DESCSERVICIO NCIRUGIA
         FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                  INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                  INNER JOIN PRE ON SER.PREFIJO=PRE.PREFIJO
                  INNER JOIN SER SER1 ON HPRED.IDCIRUGIA=SER1.IDSERVICIO
                  INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                  LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                  LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                  LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                    CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                  LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
         WHERE HPRE.NOADMISION=@NOADMISION
         AND HPRE.IDTERCEROCA=CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE HPRE.IDTERCEROCA END
         AND HPRE.IDPLAN=CASE WHEN COALESCE(@IDPLAN,'')<>'' THEN @IDPLAN ELSE HPRE.IDPLAN END
         AND HPRE.PREFIJO=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
         ORDER BY HPRED.IDCIRUGIA, HPRED.IDSERVICIO ASC,HPRE.FECHA ASC

      END
      IF @TAB='PreFactura'
      BEGIN
         IF @ANEXO='Normal'
         BEGIN
            SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                        CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                        ELSE SER.IDSERVICIO END
                  ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
               END IDSERVICIO,
               REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
               CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
               CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
               HPRED.VALORCOPAGO)VALORCOPAGO,CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE
            FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                        INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                        INNER JOIN PRE ON HPRE.PREFIJO=PRE.PREFIJO
                        INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                        LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                        LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                        LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                          CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                        LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE HPRE.NOADMISION=@NOADMISION
            AND HPRED.ITEM_RPDX=@ITEM
            AND HPRE.PREFIJO<>DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
            ORDER BY HPRE.PREFIJO ASC,HPRE.FECHA ASC

            PRINT 'Agrego las Cirugias'
            SELECT HPRE.PREFIJO,PRE.NOM_PREFIJO,DBO.FNK_FECHA_GRINGA(HPRE.FECHA) FECHA,HPRE.IDAREA,AFU.DESCRIPCION AS DESCAREA,HPRE.CCOSTO,CEN.DESCRIPCION AS DESCCOSTO,
            CASE WHEN HADM.TIPOADM=DBO.FNK_VALORVARIABLE('IDTARIFASOAT') THEN
                        CASE WHEN  DBO.FNK_VALORVARIABLE('IMPRIMIR_CUMS_SOAT')='SI' THEN 
                           CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM)  ELSE SER.IDSERVICIO END
                        ELSE SER.IDSERVICIO END
                  ELSE CASE WHEN COALESCE(IMPRIMEIDALTERNA,0)=1 THEN SER.IDALTERNA ELSE SER.IDSERVICIO END
               END IDSERVICIO,
               REPLACE(REPLACE(LTRIM(RTRIM(SER.DESCSERVICIO)),CHAR(13),''),CHAR(10),'')DESCSERVICIO,
               CASE WHEN COALESCE(SER.MEDICAMENTOS,0)=1 THEN COALESCE(IART.CODCUM,SER.CODCUM) ELSE '' END CODCUM,
               CONVERT(INT,HPRED.CANTIDAD)CANTIDAD,CONVERT(DECIMAL(14,2),HPRED.VALOR)VALOR,CONVERT(DECIMAL(14,2),
               HPRED.VALORCOPAGO)VALORCOPAGO,CONVERT(DECIMAL(14,2),HPRED.VALOREXCEDENTE)VALOREXCEDENTE,
               SER1.IDSERVICIO IDCIRUGIA,SER1.DESCSERVICIO NCIRUGIA
            FROM HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
                        INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
                        INNER JOIN PRE ON SER.PREFIJO=PRE.PREFIJO
                        INNER JOIN SER SER1 ON HPRED.IDCIRUGIA=SER1.IDSERVICIO
                        INNER JOIN HADM ON HPRE.NOADMISION=HADM.NOADMISION
                        LEFT JOIN AFU  ON HPRE.IDAREA=AFU.IDAREA
                        LEFT JOIN CEN  ON HPRE.CCOSTO=CEN.CCOSTO
                        LEFT  JOIN PPT ON CASE WHEN COALESCE(@IDTERCERO,'')<>'' THEN @IDTERCERO ELSE  HADM.IDTERCERO END=PPT.IDTERCERO AND
                                          CASE WHEN COALESCE(@IDPLAN,'') <> '' THEN @IDPLAN ELSE HADM.IDPLAN END = PPT.IDPLAN
                        LEFT JOIN IART ON HPRED.IDARTICULO=IART.IDARTICULO
            WHERE HPRE.NOADMISION=@NOADMISION
            AND HPRED.ITEM_RPDX=@ITEM
            AND HPRE.PREFIJO=DBO.FNK_VALORVARIABLE('IDCIRPREFIJO')
            ORDER BY HPRED.IDCIRUGIA, HPRED.IDSERVICIO ASC,HPRE.FECHA ASC
         END
         IF @ANEXO='Item'
         BEGIN
            SELECT @IDSEDE=IDSEDE  FROM HADM WHERE NOADMISION=@NOADMISION
            IF COALESCE(@IDSEDE,'')=''
            BEGIN
               SELECT @IDSEDE= COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=UBEQ.COMPANIA 
               FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
               WHERE USUARIO=@USUARIO
            END
            SELECT @CNSRPDXNEW=SPACE(20)
            EXEC SPQ_GENSEQUENCE @SEDE = @IDSEDE, @PREFIJO = 'RPDX', @NVOCONSEC = @CNSRPDXNEW OUTPUT
            BEGIN TRY  
                 DECLARE @FECHACORTE DATETIME=DBO.FNK_GETDATE()
                 EXEC SPK_RPT_ANEXO_PREFAC @NOADMISION,@CNSRPDX,@ITEM,@CNSRPDXNEW,1,@FECHACORTE

                  SELECT  ID1 PREFIJO,PRE.NOM_PREFIJO,ID2 IDSERVICIO,RPDX.NOMBRE DESCSERVICIO,RPDX.VALOR1 VLR_UNITARIO,RPDX.VALOR2 CANTIDAD,RPDX.VALOR3 VLR_COPAGO,RPDX.VALOR4 VLR_TOTAL 
                  FROM RPDX INNER JOIN PRE ON ID1=PRE.PREFIJO
                  WHERE CNS=@CNSRPDXNEW
                  AND RPDX.IDTERCERO='SERVICIOS'

                  SELECT  ID1 PREFIJO,PRE.NOM_PREFIJO,ID2 IDSERVICIO,RPDX.NOMBRE DESCSERVICIO,RPDX.VALOR1 VLR_UNITARIO,RPDX.VALOR2 CANTIDAD,RPDX.VALOR3 VLR_COPAGO,RPDX.VALOR4 VLR_TOTAL 
                  FROM RPDX INNER JOIN PRE ON ID1=PRE.PREFIJO
                  WHERE CNS=@CNSRPDXNEW
                  AND RPDX.IDTERCERO='PROCEDIMIENTO'

            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH

         END
      END
      IF @TAB='Facturadas'
      BEGIN
         PRINT '@ANEXO='+@ANEXO
         IF @ANEXO='CUMS'
         BEGIN 
            BEGIN TRY 
               SET @CNSRPDX='AX'+@CNSRPDX
               EXEC SPK_RPT_ANEXO @NOADMISION,@N_FACTURA,'1', @IDPLAN, @CNSRPDX, 'FA' 
               PRINT 'SPK_RPT_ANEXO '''+COALESCE(@NOADMISION,'SIN HADM')+''','''+COALESCE(@N_FACTURA,'SIN FACT')+''',''1'','''+COALESCE(@IDPLAN,'SIN PLAN')+''','''+COALESCE(@CNSRPDX,'SIN RPDX')+''',''FA'''
               IF (SELECT COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX)>0
               BEGIN

                  SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
                  VALOR2 AS VALOREXCEDENTE
                  FROM RPDX WHERE CNS=@CNSRPDX
                  AND COALESCE(ID5,'')=''

                  SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID5 IDCIRUGIA,STRINGGRANDE1 NCIRUGIA,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
                  VALOR2 AS VALOREXCEDENTE
                  FROM RPDX WHERE CNS=@CNSRPDX
                  AND COALESCE(ID5,'')<>''
                  DELETE RPDX WHERE CNS= @CNSRPDX
               END
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
            
         END
         IF @ANEXO='CUPS'
         BEGIN
            BEGIN TRY 
               SET @CNSRPDX='AX'+@CNSRPDX
               EXEC SPK_RPT_ANEXO @NOADMISION,@N_FACTURA,'1', @IDPLAN, @CNSRPDX, 'FC'  
               IF (SELECT COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX)>0
               BEGIN

                  SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
                  VALOR2 AS VALOREXCEDENTE
                  FROM RPDX WHERE CNS=@CNSRPDX
                  AND COALESCE(ID5,'')=''

                  SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID5 IDCIRUGIA,STRINGGRANDE1 NCIRUGIA,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
                  VALOR2 AS VALOREXCEDENTE
                  FROM RPDX WHERE CNS=@CNSRPDX
                  AND COALESCE(ID5,'')<>''
                  DELETE RPDX WHERE CNS= @CNSRPDX
               END
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
            
         END
         IF @ANEXO='MIPRES'
         BEGIN
            BEGIN TRY 
               SET @CNSRPDX='AX'+@CNSRPDX
               EXEC SPK_RPT_ANEXO @NOADMISION,@N_FACTURA,'1', @IDPLAN, @CNSRPDX, 'FB'  
               IF (SELECT COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX)>0
               BEGIN

                  SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
                  VALOR2 AS VALOREXCEDENTE
                  FROM RPDX WHERE CNS=@CNSRPDX
                   AND COALESCE(ID5,'')=''

                  SELECT ID2 PREFIJO ,STRINGMEDIO1 NOM_PREFIJO,ID5 IDCIRUGIA,STRINGGRANDE1 NCIRUGIA,ID3 IDSERVICIO,STRINGGRANDE2 DESCSERVICIO,COALESCE(NOMBRE,'') AS CODCUM,CANTIDAD,VALOR1 AS VALOR,
                  VALOR2 AS VALOREXCEDENTE
                  FROM RPDX WHERE CNS=@CNSRPDX
                  AND COALESCE(ID5,'')<>''
                  DELETE RPDX WHERE CNS= @CNSRPDX
               END
            END TRY
            BEGIN CATCH
                    INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
            END CATCH
            
         END
      END
      RETURN
   END  
   IF @METODO='ANEXO_MASIVA'     
   BEGIN         
      SELECT @N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
                 
      SELECT 'OK'OK,FTR.N_FACTURA, TER.NIT,TER.RAZONSOCIAL,VALORSERVICIOS,VALORCOPAGO,VR_TOTAL,
      DBO.FNK_FECHA_DDMMAA(F_FACTURA)F_FACTURA, DBO.FNK_FECHA_DDMMAA(F_VENCE)F_VENCE,
      CASE WHEN COALESCE(@DEMO,'')='' THEN CASE WHEN FTR.ESTADO='A' THEN 'ANULADA' 
           WHEN FTR.ESTADO='P' AND COALESCE(FTR.TIPOANULACION,'')='NC' THEN 'ANULADA NC' ELSE 'OK' END ELSE @DEMO END ESTADO,
       @USUARIO USUARIORPT,DBO.FNK_FECHA_DDMMAA(GETDATE())F_RPT, CONVERT(VARCHAR,GETDATE(),108)H_RPT
      FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
               INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
      WHERE N_FACTURA=@N_FACTURA

      SELECT FTRD.NOADMISION, DBO.FNK_FECHA_DDMMAA(CIT.FECHA)FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,CIT.NOAUTORIZACION,
             FTRD.CANTIDAD,FTRD.VALOR,FTRD.VLR_COPAGOS,FTRD.VLR_SERVICI,FTRD.REFERENCIA,FTRD.ANEXO,
             COALESCE(CIT.IDDX,HCA.IDDX)DXPPAL,CASE WHEN COALESCE(FTRD.IDPROVEEDOR,'')<>'' THEN  ('PROVEEDOR='+TER.NIT+' - '+TER.RAZONSOCIAL) ELSE '' END PROVEEDOR
      FROM FTRD INNER JOIN CIT ON FTRD.NOADMISION=CIT.CONSECUTIVO
                INNER JOIN AFI ON CIT.IDAFILIADO=AFI.IDAFILIADO
                LEFT  JOIN MDX ON CIT.IDDX=MDX.IDDX
                LEFT  JOIN TER ON FTRD.IDPROVEEDOR=TER.IDTERCERO
                LEFT  JOIN HCA ON CIT.CONSECUTIVO=HCA.CONSECUTIVOCIT
      WHERE FTRD.N_FACTURA=@N_FACTURA
      AND FTRD.PROCEDENCIA='CI'
      UNION ALL
      SELECT FTRD.NOADMISION, DBO.FNK_FECHA_DDMMAA(AUT.FECHA)FECHA,AFI.TIPO_DOC,AFI.DOCIDAFILIADO,AFI.NOMBREAFI,AUT.NUMAUTORIZA,
             FTRD.CANTIDAD,FTRD.VALOR,FTRD.VLR_COPAGOS,FTRD.VLR_SERVICI,FTRD.REFERENCIA,FTRD.ANEXO,
             AUT.DXPPAL,CASE WHEN COALESCE(AUT.IDPROVEEDOR,'')<>'' THEN  ('PROVEEDOR='+TER.NIT+' - '+TER.RAZONSOCIAL) ELSE '' END PROVEEDOR
      FROM FTRD INNER JOIN AUT ON FTRD.NOADMISION=AUT.NOAUT
                INNER JOIN AFI ON AUT.IDAFILIADO=AFI.IDAFILIADO
                LEFT  JOIN MDX ON AUT.DXPPAL=MDX.IDDX
                LEFT  JOIN TER ON AUT.IDPROVEEDOR=TER.IDTERCERO
      WHERE FTRD.N_FACTURA=@N_FACTURA
      AND FTRD.PROCEDENCIA='CE'
      RETURN
   END  
   IF @METODO='ANEXO_NORMAL'
   BEGIN
      SELECT @N_FACTURA=N_FACTURA        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      SELECT @PROCEDENCIA=PROCEDENCIA,@IDFORMATOFTR=LTRIM(RTRIM(COALESCE(IDFORMATO,''))),@TIPOFAC=TIPOFAC, @NOREFERENCIA=NOREFERENCIA,
             @IMPRIMEIDALTERNA=COALESCE(PPT.IMPRIMEIDALTERNA,0),@IDSEDE=FTR.IDSEDE,
              @VLLETRAS=LTRIM(RTRIM(TRIM(DBO.FNK_DE_VALORES_A_LETRAS(FTR.VR_TOTAL)))),
              @REFERENCIA=NOREFERENCIA,@VENDEDOR=VENDEDOR,@USUFACTURA=FTR.USUARIOFACTURA
      FROM FTR LEFT  JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
      WHERE N_FACTURA=@N_FACTURA

      SELECT @EQUIPO=COALESCE(SYS_COMPUTERNAME,HOST_NAME()) FROM USUSU WHERE USUARIO=@USUARIO

      SELECT 'OK'OK,FTR.N_FACTURA,TER.TIPO_ID,TER.NIT,TER.DV,TER.RAZONSOCIAL,TER.IDALTERNA2,TRIM(TER.DIRECCION) DIRECCION,COALESCE(TER.TELEFONOS,'')TELEFONOS,
               COALESCE(TER.EMAIL,'')EMAIL,UPPER(CIU.NOMBRE) NOMBRE,UPPER(DEP.NOMBRE) AS DPTO,CONVERT(VARCHAR,F_FACTURA,103)F_FACTURA,CONVERT(varchar,FECHAFAC,108)HFACTURA,
			COALESCE(CONVERT(VARCHAR,FTRE.FECHA,103),'')FECHAVAL,CONVERT(VARCHAR,FTRE.FECHA,108)HVALIDA,
               CONVERT(VARCHAR,F_VENCE,103)F_VENCE,LTRIM(RTRIM(COALESCE(IDFORMATO,'')))IDFORMATO,
               FTR.PROCEDENCIA,COALESCE(FTR.FACTE,0)ESTDIAN,FTR.VR_ABONOS,
               CASE WHEN @DEMO='' THEN  CASE WHEN FTR.ESTADO='A' THEN 'ANULADA' ELSE CASE WHEN COALESCE(TIPOANULACION,'')<>'' THEN 'ANULADA NC' ELSE 'OK' END END ELSE @DEMO END ESTADO,
               AFI.DOCIDAFILIADO,AFI.TIPO_DOC,AFI.NOMBREAFI,AFI.EDAD,DBO.FN_EDAD_PACIENTE(AFI.FNACIMIENTO,FTR.F_FACTURA,'ALL') EDAD1,AFI.DIRECCION AS AFI_DIR,AFI.TELEFONORES AS AFI_TEL,
               AFI.CELULAR,UPPER(CIUF.NOMBRE) CIUD_AFI,UPPER(DEPF.NOMBRE) AS DPTO_AFI,
               AFI.TIPOAFILIADO, @EQUIPO EQUIPO,@FIMPRESION FIMPRESION,@USUARIO USUARIO,
               CASE   WHEN AFI.TIPOAFILIADO = 'C' THEN 'Cotizante'
                     WHEN AFI.TIPOAFILIADO = 'B' THEN 'Beneficiario'
                     WHEN AFI.TIPOAFILIADO = 'J' THEN 'Jubilado'
                     WHEN AFI.TIPOAFILIADO = 'A' THEN 'Adicional'
                     WHEN AFI.TIPOAFILIADO = 'S' THEN 'Sustitución Pensional'
                     WHEN AFI.TIPOAFILIADO = 'Sb' THEN 'Subsidiado'
                     WHEN AFI.TIPOAFILIADO = 'SR' THEN 'Sin régimen'
                     WHEN AFI.TIPOAFILIADO = 'TA' THEN 'Tomador/Amparado'
                     WHEN AFI.TIPOAFILIADO = 'RE' THEN 'Régimen Especial'
                     WHEN AFI.TIPOAFILIADO = 'SN' THEN 'Subsidiado'
                     WHEN AFI.TIPOAFILIADO = 'S/' THEN 'Subsidiado'
                     WHEN AFI.TIPOAFILIADO = 'S/N' THEN 'Subsidiado' ELSE '' END TIPOAFI_NOMBRE,
               AFI.NIVELSOCIOEC,AFI.SEXO, AFI.SISBENNUMFICHA ,AFI.SISBENNIVEL,
               FTR.IDPLAN,PLN.DESCPLAN,PLN.TIPOSISTEMA,
               COALESCE(DBO.FNK_VALORVARIABLE('FTR_IMPNOCONTRATO'),'') FTR_IMPNOCONTRATO,
               CASE WHEN COALESCE(DBO.FNK_VALORVARIABLE('FTR_IMPNOCONTRATO'),'') = 'SI' THEN 
               CASE WHEN  COALESCE(PPT.NROCONTRATO,'')<>'' THEN COALESCE(PPT.NROCONTRATO,'') 
               WHEN COALESCE(PPT.IDCONTRATO,'')<>'' THEN  COALESCE(PPT.IDCONTRATO,'') ELSE '' END END IDCONTRATO,
               CASE WHEN COALESCE(@NOAUT,'')<>'' THEN @NOAUT ELSE  FTR.NOREFERENCIA END NOREFERENCIA,
               CONVERT(VARCHAR, CONVERT(VARCHAR, CAST(FTR.VALORSERVICIOS  AS MONEY), 1))VALORSERVICIOS,
               CONVERT(VARCHAR, CONVERT(VARCHAR, CAST(FTR.VALORCOPAGO  AS MONEY), 1))VALORCOPAGO,
               CONVERT(VARCHAR, CONVERT(VARCHAR, CAST(FTR.DESCUENTO  AS MONEY), 1))DESCUENTO,
               CONVERT(VARCHAR, CONVERT(VARCHAR, CAST(FTR.VR_TOTAL  AS MONEY), 1))VR_TOTAL,
               FTR.VALORSERVICIOS AS VSERVICIOS,FTR.VALORCOPAGO AS VCOPAGO,FTR.DESCUENTO AS VDESCUENTO,FTR.VR_TOTAL AS VTOTAL,
               FTR.VIVA,COALESCE(@VLR_AFECTO,0)AFECTO,COALESCE(@VLR_INAFECTO,0)INAFECTO,COALESCE(@VLR_SUBTOTAL,0)VLR_SUBTOTAL,
               @VLLETRAS+CASE WHEN @IXCOUNTRY='PERU' THEN ' SOLES ' ELSE ' PESOS M/CTE. ' END AS LETRAS,
            --dbo.FNK_MontoEscrito(FTR.VR_TOTAL)LETRAS,
               CASE WHEN COALESCE(@NOMBREFACTU,'')<>'' THEN @NOMBREFACTU ELSE USUSU.NOMBRE END AS NFACTURADOR,USUSU.CARGO,
               CASE WHEN @IXCOUNTRY='PERU' THEN (SELECT CUFE FROM FTRE WHERE FTRN_FACTURA=FTR.N_FACTURA) ELSE COALESCE(FTR.CUFE,'') END CUFE,
               REPLACE(REPLACE(LTRIM(RTRIM(COALESCE(DBO.FNK_RTF(FDIAN.TITULO),''))),CHAR(13),''),CHAR(10),'')RESOL,
               CASE WHEN @IXCOUNTRY='PERU' THEN (SELECT CUFE FROM FTRE WHERE FTRN_FACTURA=FTR.N_FACTURA) ELSE COALESCE(DBO.FNK_QRCODE(FTR.N_FACTURA),'') END CODQR,
               CASE WHEN EXISTS(SELECT DICOM FROM ARCHIVOS WHERE ID =@IDFIRMA ) 
                  THEN  (SELECT DICOM FROM ARCHIVOS WHERE ID =@IDFIRMA)
                  ELSE '' END DICOM,
               COALESCE(SED.LEGAL,'')+COALESCE(SED.LEGAL2,'') AS LEGAL,
               COALESCE(SED.LEGAL3,'')+COALESCE(SED.LEGAL4,'') AS LEGAL1,
               (SELECT NOMBRE FROM USUSU WHERE USUARIO=@USUARIO)IMPRESO,
               CASE WHEN @IXCOUNTRY='PERU' THEN CASE WHEN TIPOFIN='N' THEN 'CONTADO' ELSE 'CREDITO A '+CAST(CASE WHEN COALESCE(PPT.DIASVTO,30)<=0 THEN 30 ELSE PPT.DIASVTO END  AS VARCHAR(4))+' Días' END ELSE 'Forma de Pago:'+CASE WHEN COALESCE(TER.ENVIODICAJA,0)=1 THEN 'Contado' ELSE 'Credito '+CAST(COALESCE(PPT.DIASVTO,30) AS VARCHAR(4))+' Días' END END FPAGO,
               (SELECT 'PROVEEDOR ELECTRÓNICO: '+LTRIM(RTRIM(TER.RAZONSOCIAL))+', NIT:'+LTRIM(RTRIM(NIT))+'-'+LTRIM(RTRIM(STR(DV)))  
               FROM TER WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO'))PROFE,
               (SELECT CASE WHEN DBO.FNK_VALORVARIABLE('DATOSPROPIETARIO')='SEDE' AND DBO.FNK_VALORVARIABLE('FACTSEDE') ='NO'
               THEN COALESCE(SED.CODHABILITA,TER.IDALTERNA2) ELSE TER.IDALTERNA2 END FROM TER LEFT JOIN SED ON TER.NIT=SED.NIT
               WHERE IDTERCERO=DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
               AND SED.IDSEDE=FTR.IDSEDE)CODHABILITA                   
               ,CASE WHEN @TIPOFAC='M' THEN @NROAFIS ELSE 1 END NROAFI,
               DBO.FNK_VALORVARIABLE('FTR_03F_NOAUT') FTR_03F_NOAUT ,FTR.USUARIOFACTURA,USUSU.NOMBRE AS NUSUFACTURA,
               @ENTERO AS ENTERO,CASE TIPOFIN WHEN 'N' THEN 'B' ELSE 'F' END TIPOFACT,
               CASE WHEN @IXCOUNTRY='PERU' AND VR_TOTAL>700 THEN ROUND((VR_TOTAL*0.12),2) ELSE 0 END VR_DETRA,
               COALESCE(FTR.PAQUETE,0)PAQUETE,
               @USUARIO USUARIORPT,DBO.FNK_FECHA_GRINGA(GETDATE())F_RPT, CONVERT(VARCHAR,GETDATE(),108)H_RPT
      FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO
               INNER JOIN PLN ON FTR.IDPLAN=PLN.IDPLAN
               LEFT  JOIN AFI ON FTR.IDAFILIADO=AFI.IDAFILIADO
               LEFT  JOIN CIU ON TER.CIUDAD=CIU.CIUDAD
               LEFT  JOIN CIU CIUF ON AFI.CIUDAD=CIUF.CIUDAD
               LEFT  JOIN DEP ON CIU.DPTO=DEP.DPTO
               LEFT  JOIN DEP DEPF ON CIUF.DPTO=DEPF.DPTO
               LEFT  JOIN PPT ON FTR.IDTERCERO=PPT.IDTERCERO AND FTR.IDPLAN=PPT.IDPLAN
               LEFT JOIN USUSU ON FTR.USUARIOFACTURA=USUSU.USUARIO
               LEFT JOIN ARCHIVOS ON USUSU.IDFIRMA=ARCHIVOS.ID
               LEFT JOIN FDIAN ON FTR.CNSRESOL=FDIAN.CNSRESOL
               LEFT JOIN FTRE  ON FTR.N_FACTURA=FTRE.FTRN_FACTURA AND FTR.PREFIJODIANFE=FTRE.PREFIJO AND FTR.CNSDIANFE=FTRE.N_FACTURA
               LEFT JOIN CNT   ON PPT.IDCONTRATO=CNT.IDCONTRATO
               LEFT JOIN SED   ON FTR.IDSEDE=SED.IDSEDE
      WHERE FTR.N_FACTURA=@N_FACTURA

      IF @PROCEDENCIA='CI' OR ( @REFERENCIA='UNIWEB' AND @PROCEDENCIA<>'CE')
      BEGIN
         IF @TIPOFAC='I'
         BEGIN
            SELECT MED.NOMBRE,MES.DESCRIPCION,MED.NO_REGISTRO,COALESCE(CIT.NOAUTORIZACION,'') NOAUTORIZACION,CONVERT(VARCHAR,CIT.FECHA,103)FECHAING,CONVERT(VARCHAR,CIT.FECHA,103)FECHAEGR,
                     CASE COALESCE(CIT.MODALIDAD,'Presencial') WHEN 'Virtual' THEN 'Virtual' ELSE 'Presencial' END MODALIDAD,HCA.IDDX,MDX.DESCRIPCION AS DESCMDX
            FROM CIT INNER JOIN MED ON CIT.IDMEDICO=MED.IDMEDICO
                     INNER JOIN MES ON CASE WHEN COALESCE(CIT.IDEMEDICA,'')='' THEN MED.IDEMEDICA ELSE COALESCE(CIT.IDEMEDICA,'') END=MES.IDEMEDICA
                     LEFT  JOIN HCA ON CIT.CONSECUTIVO=HCA.CONSECUTIVOCIT
                     LEFT  JOIN MDX ON HCA.IDDX=MDX.IDDX
            WHERE CIT.CONSECUTIVO=@NOREFERENCIA
         END
         ELSE
         BEGIN
            SELECT TOP 1 MED.NOMBRE,MES.DESCRIPCION,COALESCE(CIT.NOAUTORIZACION,'')NOAUTORIZACION,CONVERT(VARCHAR,MIN(CIT.FECHA),103)FECHAING,CONVERT(VARCHAR,MAX(CIT.FECHA),103)FECHAEGR
            FROM FTRD LEFT JOIN CIT ON FTRD.NOADMISION=CIT.CONSECUTIVO
                        LEFT JOIN MED ON CIT.IDMEDICO=MED.IDMEDICO
                        LEFT JOIN MES ON CASE WHEN COALESCE(CIT.IDEMEDICA,'')='' THEN MED.IDEMEDICA ELSE COALESCE(CIT.IDEMEDICA,'') END=MES.IDEMEDICA
            WHERE FTRD.N_FACTURA=@N_FACTURA
            GROUP BY MED.NOMBRE,MES.DESCRIPCION,COALESCE(CIT.NOAUTORIZACION,'')
         END
      END
      IF @PROCEDENCIA='CE'
      BEGIN
         IF @TIPOFAC='I'
         BEGIN
            SELECT COALESCE(MED.NOMBRE,'')NOMBRE,COALESCE(MES.DESCRIPCION,'')DESCRIPCION,COALESCE(AUT.NUMAUTORIZA,'')NOAUTORIZACION,CONVERT(VARCHAR,AUT.FECHA,103)FECHAING,CONVERT(VARCHAR,AUT.FECHA,103)FECHAEGR,
                  HCA.IDDX,MDX.DESCRIPCION AS DESCMDX
            FROM AUT LEFT JOIN MED ON AUT.IDSOLICITANTE=MED.IDMEDICO
                     LEFT JOIN MES ON MED.IDEMEDICA=MES.IDEMEDICA
                     LEFT JOIN HCA ON AUT.CONSECUTIVOHCA=HCA.CONSECUTIVO
                     LEFT JOIN MDX ON HCA.IDDX=MDX.IDDX
            WHERE NOAUT=@NOREFERENCIA  
         END
         ELSE
         BEGIN
            SELECT COALESCE(MED.NOMBRE,'')NOMBRE,COALESCE(MES.DESCRIPCION,'')DESCRIPCION,COALESCE(AUT.NUMAUTORIZA,'')NOAUTORIZACION
                  ,CONVERT(VARCHAR,FECHA,103)FECHAING,CONVERT(VARCHAR,FECHA,103)FECHAEGR
            FROM AUT LEFT JOIN MED ON AUT.IDSOLICITANTE=MED.IDMEDICO
                     LEFT JOIN MES ON MED.IDEMEDICA=MES.IDEMEDICA
            WHERE NOAUT=@NOAUT   
            UNION ALL
            SELECT TOP 1 MED.NOMBRE,MES.DESCRIPCION,COALESCE(CIT.NOAUTORIZACION,'')NOAUTORIZACION,CONVERT(VARCHAR,MIN(CIT.FECHA),103)FECHAING,CONVERT(VARCHAR,MAX(CIT.FECHA),103)FECHAEGR
            FROM FTRD LEFT JOIN CIT ON FTRD.NOADMISION=CIT.CONSECUTIVO
                        LEFT JOIN MED ON CIT.IDMEDICO=MED.IDMEDICO
                        LEFT JOIN MES ON COALESCE(CIT.IDEMEDICA,MED.IDEMEDICA)=MES.IDEMEDICA
            WHERE FTRD.N_FACTURA=@N_FACTURA
            GROUP BY MED.NOMBRE,MES.DESCRIPCION,COALESCE(CIT.NOAUTORIZACION,'')
               
         END
      END

      SELECT DBO.FNK_FECHA_DDMMAA(FTRD.FECHA)FECHA,FTRD.PREFIJO,PRE.NOM_PREFIJO,
             IDSERVICIO=CASE WHEN DBO.FNK_VALORVARIABLE('IMPRIMIR_CUPS') ='SI' THEN SER.CODCUPS ELSE SER.IDSERVICIO END,
             DESCSERVICIO=CASE WHEN DBO.FNK_VALORVARIABLE('IMPRIMIR_CUPS') ='SI' THEN SER.DESCRIPCION_CUPS ELSE SER.DESCSERVICIO END,
             FTRD.CANTIDAD,FTRD.VALOR,FTRD.VLR_SERVICI
         FROM FTRD INNER JOIN SER ON FTRD.REFERENCIA=SER.IDSERVICIO
                  INNER JOIN PRE ON FTRD.PREFIJO=PRE.PREFIJO
                  LEFT  JOIN AFU ON FTRD.AREAPRESTACION=AFU.IDAREA
      WHERE N_FACTURA= @N_FACTURA
      AND 1= CASE WHEN DBO.FNK_VALORVARIABLE('ANEXOIMPNOCOBRABLE')='NO' THEN CASE WHEN FTRD.VR_TOTAL>0 THEN 1 ELSE 0 END ELSE 1 END
      ORDER BY  FTRD.N_CUOTA 

   END
END




