CREATE OR ALTER  PROCEDURE DBO.SPQ_SAP
@JSON  NVARCHAR(MAX) 
WITH ENCRYPTION
AS
DECLARE  @PARAMETROS	NVARCHAR(MAX)	,@MODELO			VARCHAR(100)	,@METODO		VARCHAR(100)	,@USUARIO		VARCHAR(12)		
		,@GRUPO			VARCHAR(8)		,@SYS_COMPUTERNAME	VARCHAR(254)	,@IDSEDE		VARCHAR(5)	
      ,@COMPANIA VARCHAR(2)      
      ,@DATOS    VARCHAR(MAX)            ,@DATOS1 VARCHAR(MAX)      
      ,@TIP_OPE VARCHAR(10)               ,@TIP_ART VARCHAR(10)            ,@COD_ART  varchar(20)
      ,@DES_ART varchar(200)              ,@COD_LAB VARCHAR(20)            ,@IDSERVICIO VARCHAR(20)
      ,@ID_TRX VARCHAR(50)                ,@ID_OPE_LIN VARCHAR(20)         ,@TIP_MOV  VARCHAR(10)
      ,@COD_SEDE VARCHAR(10)              ,@COD_ALM  varchar(20)           ,@CANT_ART SMALLINT                 
      ,@PRE_MED_ART DECIMAL(14,2)         ,@FEC_LOTE DATETIME              ,@NUM_LOTE VARCHAR(20) 
      ,@ID_OPE_CAB VARCHAR(20)            ,@NVOCONSEC VARCHAR(20)          ,@XmlDocumentHandle int;    
      DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
BEGIN 
	SET LANGUAGE Spanish;  
	SET DATEFORMAT dmy
	SELECT *
	INTO #JSON
	FROM OPENJSON (@json)
	WITH (
		MODELO         VARCHAR(100)     '$.MODELO',
		METODO         VARCHAR(100)     '$.METODO',
		USUARIO        VARCHAR(12)      '$.USUARIO',
		PARAMETROS     NVARCHAR(MAX)  AS JSON
	)

	SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
	FROM #JSON
	--SELECT @GRUPO = DBO.FNK_DESCIFRAR(GRUPO), @USUNOMBRE = NOMBRE FROM USUSU WHERE USUARIO = @USUARIO
	--SELECT @SYS_COMPUTERNAME = SYS_COMPUTERNAME, @COMPANIA = COMPANIA, @CODCAJERO= CODCAJERO FROM USUSU WHERE USUARIO = @USUARIO
	--SELECT @IDSEDE = IDSEDE, @SEDE = IDSEDE FROM UBEQ WHERE SYS_ComputerName = @SYS_COMPUTERNAME

	IF @METODO = 'FPA'
	BEGIN
		
		SELECT OK = 'OK'
		

		SELECT * FROM FPA
		WHERE FORMAPAGO=COALESCE(JSON_VALUE(@PARAMETROS,'$.FORMAPAGO'), FORMAPAGO)

	END

	IF @METODO = 'ERROR_ARITMETICO'
	BEGIN
		BEGIN TRY
			SELECT 1 / 0
		END TRY  
		BEGIN CATCH 
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
		END CATCH  
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' KO
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK'OK
	END

	IF @METODO = 'ERRORES_CONTROLADOS'
	BEGIN

		INSERT INTO @TBLERRORES(ERROR) 
		SELECT 'La forma de pago es obligatoria'  
		UNION ALL SELECT 'El documento de identificación es obligatorio'  
		

		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' KO
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK'OK
	END
   IF @METODO='COMPRA_ARTICULO'     
   BEGIN      
      PRINT '@PARAMETROS='+COALESCE(@PARAMETROS,'SIN DATOS')
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS VARCHAR(MAX) 
      )
      PRINT '@DATOS ='+@DATOS
      SELECT @DATOS1=@DATOS
      SELECT @DATOS=REPLACE(@DATOS,'ns1:','')
      SELECT @DATOS=REPLACE(@DATOS,' xmlns:ns1="http://integrador.clinicainternacional.com.pe/Traspaso"','')
      SELECT @DATOS=dbo.FNK_LIMPIATEXTO(@DATOS,'0-9 A-Z </>:.=_"')

      EXEC sp_xml_preparedocument @XmlDocumentHandle OUTPUT, @DATOS;

     SELECT @ID_TRX=ID_TRX,@ID_OPE_CAB=ID_OPE_CAB,@ID_OPE_LIN=ID_OPE_LIN,@TIP_MOV=TIP_MOV,@COD_SEDE=COD_SEDE,@COD_ALM=COD_ALM,
            @COD_ART=COD_ART,@CANT_ART=CANT_ART,@PRE_MED_ART=CONVERT(DECIMAL(14,2),PRE_MED_ART),
            @FEC_LOTE=CONVERT(DATETIME,CONVERT(DATE,LEFT(FEC_LOTE,4)+'/'+RIGHT(LEFT(FEC_LOTE,6),2)+'/'+RIGHT(FEC_LOTE,2))),
            @NUM_LOTE=NUM_LOTE
     FROM OPENXML (@XmlDocumentHandle, '/Traspaso',2)
               WITH (ID_TRX VARCHAR(50),  
                     ID_OPE_CAB VARCHAR(20),
                     ID_OPE_LIN VARCHAR(20),
                     TIP_MOV  VARCHAR(10),
                     COD_SEDE VARCHAR(10),
                     COD_ALM  varchar(20),
                     COD_ART   varchar(20),
                     CANT_ART   varchar(10),
                     PRE_MED_ART VARCHAR(20),
                     FEC_LOTE VARCHAR(20),
                     NUM_LOTE VARCHAR(20)
                     );
     EXEC sp_xml_removedocument @XmlDocumentHandle;

     PRINT 'Comienzo las validaciones'
     IF EXISTS(SELECT * FROM IMOV WHERE OBSERVACION=@ID_TRX AND SYS_ComputerName='INTERFAXINV')
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'ID de la transacción de SAP ya fue procesada... @ID_TRX='+COALESCE(@ID_TRX,'')
     END
     IF EXISTS(SELECT * FROM IMOV WHERE NODOCUMENTO=@ID_OPE_CAB AND SYS_ComputerName='INTERFAXINV')
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'ID que viene de SAP cabecera ya fue procesada... @ID_OPE_CAB='+COALESCE(@ID_OPE_CAB,'')+' @ID_TRX='+COALESCE(@ID_TRX,'')
     END
     IF NOT EXISTS(SELECT * FROM IART WHERE IDARTICULO=@COD_ART)
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'ID Articulo no existe en el Maestro de Articulos, @COD_ART='+COALESCE(@COD_ART,'')+' @ID_TRX='+COALESCE(@ID_TRX,'')
     END
     IF COALESCE(@CANT_ART,0)<=0
     BEGIN
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'La Cantidad del Articulo no puede ser Menor o Igual a cero @ID_TRX='+COALESCE(@ID_TRX,'')
     END
     IF COALESCE(@FEC_LOTE,'')='' OR @FEC_LOTE< DBO.FNK_GETDATE()+30
     BEGIN
       INSERT INTO @TBLERRORES(ERROR)
       SELECT 'Fecha de Vencimiento no Valida, debe ser mayor o Igal a 30 Dias de la fecha actual @FEC_LOTE='+CONVERT(varchar,@FEC_LOTE,103)
     END
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
        SELECT TOP 1 DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_MOV='501' THEN 'COMPRA' ELSE 'DEVOL' END,@DATOS1,@DATOS,ERROR,'ERRORES',@NVOCONSEC,@COD_ART FROM @TBLERRORES

        SELECT 'KO' KO, ERROR FROM @TBLERRORES
        RETURN
     END
     BEGIN TRY           
         EXEC SPK_GENCONSECUTIVO @COMPANIA,'01','@MOV',@NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = '01' + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         PRINT '@NVOCONSEC='+@NVOCONSEC

         INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                           FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                           IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
                           OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                           CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                           USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                           SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP,CODUNG,CODPRG,CLASEPED)  
         SELECT @NVOCONSEC,'M019' ,CASE WHEN @TIP_MOV='501' THEN DBO.FNK_VALORVARIABLE('IDINVMOV_REMISION_EN') ELSE DBO.FNK_VALORVARIABLE('IDINVDEVPROVEEDOR') END
                , @ID_OPE_CAB, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                  '10401HDFAR','INTERXML',DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO') , 'INTERXML',NULL, NULL, 0, NULL, NULL,
                  @ID_TRX,NULL, 0,RIGHT(LTRIM(RTRIM(@ID_OPE_LIN)),16), '4115',0, NULL, 'SALUD', 'INTERXML',
                  NULL, NULL, 0, NULL, 1, 'INTERFAXINV', 0, NULL, 0, NULL,NULL,NULL,NULL

  
         INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                           NOLOTE, NOLOTEPEDIDO,FECHAVENCE, ESTADO, IDARTICULOTF,
                           CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                           USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                           CANTIDADORI, TIENECAMBIO, IDITAR,IDSERVICIO)
         SELECT @NVOCONSEC, IART.IDARTICULO, IART.EXISTOTAL, @CANT_ART,  @CANT_ART, @PRE_MED_ART,  
                  @NUM_LOTE, @NUM_LOTE,@FEC_LOTE,0, NULL, NULL, NULL, NULL,1,0, 
                  'INTERXML', NULL, NULL, 0, NULL, NULL, NULL, 0, IART.IDITAR,IART.IDSERVICIO
         FROM IART WHERE IDARTICULO=@COD_ART
         IF @TIP_MOV='501'
         BEGIN 
            EXEC SPK_CONFIRMARENTRADAS 'M019',@NVOCONSEC,'INTERXML','01','01','INTERFAXINV'
         END
         ELSE
         BEGIN
            EXEC SPK_CONFIRMARSALIDAS 'M019',@NVOCONSEC,'INTERXML','01','01'
         END
     END TRY
     BEGIN CATCH
             INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
     END CATCH
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
        SELECT TOP 1 DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_MOV='501' THEN 'COMPRA' ELSE 'DEVOL' END,@DATOS1,@DATOS,ERROR,'ERRORES',@NVOCONSEC,@COD_ART FROM @TBLERRORES

        SELECT 'KO' KO, ERROR FROM @TBLERRORES
        RETURN
     END

     INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
     SELECT DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_MOV='501' THEN 'COMPRA' ELSE 'DEVOL' END,@DATOS1,@DATOS,'OK','ERRORES',@NVOCONSEC,@COD_ART 

     SELECT 'OK' OK
     RETURN 
   END
   IF @METODO='CREA_ARTICULO'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      DATOS VARCHAR(MAX)
      )
      SELECT @DATOS1=@DATOS
      SELECT @DATOS=REPLACE(@DATOS,'ns1:','')
      SELECT @DATOS=REPLACE(@DATOS,' xmlns:ns1="http://integrador.clinicainternacional.com.pe/Articulo"','')
      SELECT @DATOS=dbo.FNK_LIMPIATEXTO(@DATOS,'0-9 A-Z </>:.=_"')

      EXEC sp_xml_preparedocument @XmlDocumentHandle OUTPUT, @DATOS;

     SELECT @ID_TRX=ID_TRX, @TIP_OPE=TIP_OPE,@TIP_ART=TIP_ART,@COD_ART=COD_ART,@DES_ART=DES_ART,@COD_LAB=COD_LAB
     FROM OPENXML (@XmlDocumentHandle, '/Articulo',2)
               WITH (ID_TRX VARCHAR(50),
                     TIP_OPE VARCHAR(10),
                     TIP_ART VARCHAR(10),
                     COD_ART  varchar(20),
                     DES_ART varchar(200),
                     COD_LAB VARCHAR(20)
                     );
     EXEC sp_xml_removedocument @XmlDocumentHandle;
       
     PRINT 'Comienzo las validaciones'
     PRINT '@COD_ART ='+@COD_ART
     IF COALESCE(@COD_ART,'')='' OR @COD_ART IS NULL
     BEGIN 
        INSERT INTO @TBLERRORES(ERROR)
        SELECT 'Codigo de Articulo no Puede ser null @ID_TRX='+@ID_TRX 
     END
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        SELECT 'KO' KO, ERROR FROM @TBLERRORES
        RETURN
     END
     IF NOT EXISTS(SELECT * FROM IART WHERE IDARTICULO=@COD_ART)
     BEGIN
       PRINT 'NO EXISTE'
        BEGIN TRY           
           INSERT INTO IART(IDARTICULO,IDCLASE,IDSUBCLASE,IDGRUPO,DESCRIPCION,IDPRINACTIVO,IDFORFARM,IDCONCENTRA,IDUNIDAD,PCOSTO,EXISTOTAL,IDITAR,IDSERVICIO,PRINCIPAL,IDFABRICANTE)   
           SELECT @COD_ART,'NA','NA','NA',@DES_ART,'NA','NA','NA','NA',0,0,CASE WHEN @TIP_ART='ZMED' THEN '01' ELSE '02' END,@COD_ART,1,@COD_LAB

            PRINT 'INSERTANDO EN SER'
            IF (OBJECT_ID('tempdb.dbo.#SERINTER','U')) IS NOT  NULL
            BEGIN
               DROP TABLE #SERINTER
            END
            SELECT TOP 1 PREFIJO, IDSERVICIO, DESCSERVICIO, IDACTIVIDAD, NIVELATENCION, NIVELFUNCIONARIO, NIVELSEDE, GRUPOQX, IDJERARQUIA, 
                        IDSUBJERARQUIA, NOM_GENERICO, PRESENTACION, CANTIDAD, CANTMAXIMA, COMENTARIOS,  DIASRESTAUTO, POSS, POS, ESTADO, SEXO,
                        TIPORANGOE, EDADINICIAL, EDADFINAL, IDPREPARACION, MPROVEEDOR, CLASIF1, CLASIF2, CODIGORIPS, MEDICAMENTOS, IDALTERNA,
                        PYP, SPD,  MRECARGONOCTURNO, TIPORECARGONOC, VLRRECARGONOC, HIRECNOC, HFRECNOC, DIASIGRN, IDREFERENCIA, CCOSTO, 
                        IDARTICULO, MPERSONAL_AT, IDMODELOCONT, MSUBSERVICIO, REQAUTORIZACION, TIPOAUTORIZACION,  MOBSOBLIGATORIA, CIRUGIA,
                        IDSECCION, IDPLANILLA, IDMUESTRA, DURACIONMUESTRA, IDGRUPOIMP, IMPRIMELAB, IDGENERICO, ISS04, ACLARAISS04, IVA, 
                        IDIMPUESTO, IDCLASE, ITFC, CNSITFC,  IDALTERNA_ORI, ESVACUNA, CODCUPS, DESCRIPCION_CUPS, MAMOGRAFIA, CODCUM, 
                        CODFURIPS, AMBITO, MCF, CODFCT, CLASEHTX, MDOSIF, EQUICC, PRESUNI, T_ESTABILIDAD, VLRCOSTO, 
                        MEZCLA, VIA,  IDSERVICIOM, TERAPIA, SERIAL, EQUICCINF, VPAI, VTIPOEDAD, VEDADINI, VEDADFIN, COLOR, 
                        ANTECESOR, IDEMEDICA, ENINTERFAZ, ANESTESIA, SERIADO, CODSISPRO, MULTIDOSIS, REPORTA, TEXDEFAUL,  
                        GRUPO, EXCLUYEPOSOLOGIA, TRANSFORMADO, GARANTIA, MINUTOSMS, CANTMAXIMA_CE, CANTMAXIMA_FME, TELECONSULTA, SMS, 
                        LIBREFORMULACION, ATENCION, MLATERALIDAD, PRIORITARIO, VEXIST,  CUPS_ID, DURACIONCITA, EQUIPOMUES, 
                        IDEQUIPO_MUESTRA, INICIALES, MPRINCIPAL, BIOFAR, SESIONES, TIPOSES, ONCOLOGIA, HORARIO, HDESDE, HHASTA 
                        INTO #SERINTER
            FROM SER 
            WHERE PREFIJO=CASE WHEN @TIP_ART='ZMED'  THEN DBO.FNK_VALORVARIABLE('PREFIJOMEDICAMENTOS') 
                  ELSE DBO.FNK_VALORVARIABLE('PREFIJOMATERIALES') END
            AND SER.ESTADO='Activo'
            AND EXISTS(SELECT * FROM TARDV WHERE SER.IDSERVICIO=TARDV.IDSERVICIO)

            SELECT @IDSERVICIO= IDSERVICIO FROM #SERINTER

            UPDATE #SERINTER SET IDSERVICIO=@COD_ART,IDARTICULO=@COD_ART,DESCSERVICIO=@DES_ART,DESCRIPCION_CUPS=@DES_ART,IDALTERNA=@COD_ART,
                                 EQUICC=NULL,MDOSIF=0
            WHERE IDSERVICIO=@IDSERVICIO

            INSERT INTO SER(PREFIJO, IDSERVICIO, DESCSERVICIO, IDACTIVIDAD, NIVELATENCION, NIVELFUNCIONARIO, NIVELSEDE, GRUPOQX, IDJERARQUIA, 
                        IDSUBJERARQUIA, NOM_GENERICO, PRESENTACION, CANTIDAD, CANTMAXIMA, COMENTARIOS,  DIASRESTAUTO, POSS, POS, ESTADO, SEXO,
                        TIPORANGOE, EDADINICIAL, EDADFINAL, IDPREPARACION, MPROVEEDOR, CLASIF1, CLASIF2, CODIGORIPS, MEDICAMENTOS, IDALTERNA,
                        PYP, SPD,  MRECARGONOCTURNO, TIPORECARGONOC, VLRRECARGONOC, HIRECNOC, HFRECNOC, DIASIGRN, IDREFERENCIA, CCOSTO, 
                        IDARTICULO, MPERSONAL_AT, IDMODELOCONT, MSUBSERVICIO, REQAUTORIZACION, TIPOAUTORIZACION,  MOBSOBLIGATORIA, CIRUGIA,
                        IDSECCION, IDPLANILLA, IDMUESTRA, DURACIONMUESTRA, IDGRUPOIMP, IMPRIMELAB, IDGENERICO, ISS04, ACLARAISS04, IVA, 
                        IDIMPUESTO, IDCLASE, ITFC, CNSITFC,  IDALTERNA_ORI, ESVACUNA, CODCUPS, DESCRIPCION_CUPS, MAMOGRAFIA, CODCUM, 
                        CODFURIPS, AMBITO, MCF, CODFCT, CLASEHTX, MDOSIF, EQUICC, PRESUNI, T_ESTABILIDAD, VLRCOSTO, 
                        MEZCLA, VIA,  IDSERVICIOM, TERAPIA, SERIAL, EQUICCINF, VPAI, VTIPOEDAD, VEDADINI, VEDADFIN, COLOR, 
                        ANTECESOR, IDEMEDICA, ENINTERFAZ, ANESTESIA, SERIADO, CODSISPRO, MULTIDOSIS, REPORTA, TEXDEFAUL,  
                        GRUPO, EXCLUYEPOSOLOGIA, TRANSFORMADO, GARANTIA, MINUTOSMS, CANTMAXIMA_CE, CANTMAXIMA_FME, TELECONSULTA, SMS, 
                        LIBREFORMULACION, ATENCION, MLATERALIDAD, PRIORITARIO, VEXIST,  CUPS_ID, DURACIONCITA, EQUIPOMUES, 
                        IDEQUIPO_MUESTRA, INICIALES, MPRINCIPAL, BIOFAR, SESIONES, TIPOSES, ONCOLOGIA, HORARIO, HDESDE, HHASTA)
            SELECT PREFIJO, IDSERVICIO, DESCSERVICIO, IDACTIVIDAD, NIVELATENCION, NIVELFUNCIONARIO, NIVELSEDE, GRUPOQX, IDJERARQUIA, 
                        IDSUBJERARQUIA, NOM_GENERICO, PRESENTACION, CANTIDAD, CANTMAXIMA, COMENTARIOS,  DIASRESTAUTO, POSS, POS, ESTADO, SEXO,
                        TIPORANGOE, EDADINICIAL, EDADFINAL, IDPREPARACION, MPROVEEDOR, CLASIF1, CLASIF2, CODIGORIPS, MEDICAMENTOS, IDALTERNA,
                        PYP, SPD,  MRECARGONOCTURNO, TIPORECARGONOC, VLRRECARGONOC, HIRECNOC, HFRECNOC, DIASIGRN, IDREFERENCIA, CCOSTO, 
                        IDARTICULO, MPERSONAL_AT, IDMODELOCONT, MSUBSERVICIO, REQAUTORIZACION, TIPOAUTORIZACION,  MOBSOBLIGATORIA, CIRUGIA,
                        IDSECCION, IDPLANILLA, IDMUESTRA, DURACIONMUESTRA, IDGRUPOIMP, IMPRIMELAB, IDGENERICO, ISS04, ACLARAISS04, IVA, 
                        IDIMPUESTO, IDCLASE, ITFC, CNSITFC,  IDALTERNA_ORI, ESVACUNA, CODCUPS, DESCRIPCION_CUPS, MAMOGRAFIA, CODCUM, 
                        CODFURIPS, AMBITO, MCF, CODFCT, CLASEHTX, MDOSIF, EQUICC, PRESUNI, T_ESTABILIDAD, VLRCOSTO, 
                        MEZCLA, VIA,  IDSERVICIOM, TERAPIA, SERIAL, EQUICCINF, VPAI, VTIPOEDAD, VEDADINI, VEDADFIN, COLOR, 
                        ANTECESOR, IDEMEDICA, ENINTERFAZ, ANESTESIA, SERIADO, CODSISPRO, MULTIDOSIS, REPORTA, TEXDEFAUL,  
                        GRUPO, EXCLUYEPOSOLOGIA, TRANSFORMADO, GARANTIA, MINUTOSMS, CANTMAXIMA_CE, CANTMAXIMA_FME, TELECONSULTA, SMS, 
                        LIBREFORMULACION, ATENCION, MLATERALIDAD, PRIORITARIO, VEXIST,  CUPS_ID, DURACIONCITA, EQUIPOMUES, 
                        IDEQUIPO_MUESTRA, INICIALES, MPRINCIPAL, BIOFAR, SESIONES, TIPOSES, ONCOLOGIA, HORARIO, HDESDE, HHASTA
            FROM #SERINTER

            PRINT 'INSERTANDO TARIFAS'

            INSERT INTO TARD(IDTARIFA, IDSERVICIO, VALOR, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION)
            SELECT TOP 1 IDTARIFA, @COD_ART, VALOR, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION
            FROM TARD WHERE IDSERVICIO=@IDSERVICIO
            

            INSERT INTO TARDV(IDTARIFA, IDSERVICIO, NOITEM, VALOR, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION, TIPOVALOR)
            SELECT TOP 1 IDTARIFA, @COD_ART, NOITEM, 0, FECHAINI, FECHAFIN, CIRUGIA, VLRPAQUETEREF, PAQUETE, PCIR, PANE, PAYU, PDS, PMYM, CALCULADOPAQ, ITFC, CNSITFC, CODIFICACION, TIPOVALOR
            FROM TARDV 
            WHERE IDSERVICIO=@IDSERVICIO
            ORDER BY NOITEM DESC
   
        END TRY
        BEGIN CATCH
           INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
        END CATCH
     END
     ELSE
     BEGIN
        PRINT 'ACTUALIZO'
        UPDATE IART SET DESCRIPCION=@DES_ART,IDITAR=CASE WHEN @TIP_ART='ZMED' THEN '01' ELSE '02' END,IDFABRICANTE=@COD_LAB WHERE IDARTICULO=@COD_ART
     END
     IF(SELECT COUNT(*) FROM @TBLERRORES)>0
     BEGIN
        INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
        SELECT TOP 1 DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_OPE='MM1' THEN 'CREA IART' ELSE 'ACT IART' END,@DATOS1,@DATOS,ERROR,'ERRORES',NULL,@COD_ART FROM @TBLERRORES
        SELECT 'KO' OK, ERROR FROM @TBLERRORES
        RETURN
     END
     INSERT INTO INTERFAXINV(FECHA,ID_TRX,PROCESO,SOLICITUD,FORMATEADO,RESPUESTA,ESTADO,CNSMOV,IDARTICULO)
     SELECT DBO.FNK_GETDATE(), @ID_TRX,CASE WHEN @TIP_OPE='MM1' THEN 'CREA IART' ELSE 'ACT IART' END,@DATOS1,@DATOS,'OK','TERMINADO',NULL,@COD_ART

     SELECT 'OK' OK
     RETURN 
   END
END

