CREATE OR ALTER PROCEDURE DBO.SPQ_VERIFA_COPAGOS_FTRE @N_FACTURA VARCHAR(20)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @PROCEDENCIA VARCHAR(20)
BEGIN
   IF EXISTS(SELECT * FROM FTRD WHERE N_fACTURA=@N_FACTURA AND COALESCE(TCOPAGO,'')='')
   BEGIN
      SELECT @PROCEDENCIA=PROCEDENCIA FROM FTR WHERE N_FACTURA=@N_FACTURA
      UPDATE FTRD SET TCOPAGO=DBO.FNK_TRAE_TIPOCOPAGO(FTRD.NOPRESTACION,COALESCE(FTRD.PROCEDENCIA,@PROCEDENCIA)) WHERE N_FACTURA=@N_FACTURA
   END
END