CREATE OR ALTER PROCEDURE DBO.SPQ_EXISTENCIA
@JSON NVARCHAR(MAX)
WITH ENCRYPTION
AS
DECLARE   @PARAMETROS       NVARCHAR(MAX),      @MODELO         VARCHAR(100)	,@METODO      VARCHAR(100)
        , @QUERY            VARCHAR(MAX),       @USUARIO        VARCHAR(12)		,@NVOCONSEC   VARCHAR(20)
        , @SEDE             VARCHAR(5)        , @NOADMISION     VARCHAR(16)		,@FECHA       VARCHAR(20)         
        , @HORA             VARCHAR(10)       , @ITEM           SMALLINT		,@OBS         VARCHAR(2048)
        , @SYS_COMPUTERNAME VARCHAR(254)      , @GRUPO          VARCHAR(8)		,@PENDIENTES  SMALLINT
        , @CNSMOV           VARCHAR(20)		  , @FIRMA			VARBINARY(MAX)	,@IDBODEGA VARCHAR(20)
		, @CNSITRA			VARCHAR(20)			,@datoIMOVH NVARCHAR(MAX)	, @PROCESO VARCHAR(50)
		,@NOLOTE VARCHAR(50)	, @datoIMOV NVARCHAR(MAX)	, @TIPO VARCHAR(20),	@MAYOR0 BIT	,@ESTADO VARCHAR(20)
		,@BODEGAACTUAL BIT		,@SELECCIONADO BIT	,@IDARTICULO VARCHAR(20)	,@BODEGASELECCIONADA VARCHAR(20)
DECLARE @CONTROL BIT	,@FECHAINI VARCHAR(10), @FECHAFIN VARCHAR(10), @IDTIPOMOV VARCHAR(20)
	, 	@CCOSTO VARCHAR(20), @IDAREA VARCHAR(20), @IDTERCERO VARCHAR(20)
BEGIN   
   SET DATEFORMAT dmy
   --SELECT @JSON
   SELECT *
   INTO #JSON
   FROM OPENJSON (@json)
   WITH (
      MODELO  VARCHAR(100) '$.MODELO',
      METODO  VARCHAR(100) '$.METODO',
      USUARIO VARCHAR(20) '$.USUARIO',
      PARAMETROS NVARCHAR(MAX) AS JSON
   )
   SELECT @MODELO = MODELO , @METODO = METODO , @PARAMETROS = PARAMETROS, @USUARIO = USUARIO
   FROM #JSON
   --DEFINICION DE TABLA DE ERRORES
   DECLARE @TBLERRORES TABLE(ERROR VARCHAR(200));
   --  
   IF @METODO = 'CONSULTAR_HADM'
   BEGIN
      
      SELECT  @NOADMISION = NOADMISION, @PENDIENTES = PENDIENTES      
      FROM OPENJSON (@PARAMETROS)
      WITH ( 
             NOADMISION            VARCHAR(16)   '$.NOADMISION',
             PENDIENTES            SMALLINT      '$.PENDIENTES'
      )
       -- ANTES DE INSERTAR SE HACE VALIDACIONES
      --IF ( @FECHAHNAT < @FECHAADM ) 
      --     INSERT INTO @TBLERRORES(ERROR) SELECT 'Fecha No puede ser Anterior a la Fecha de Admisi?...'
      
      IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
      BEGIN
         SELECT 'KO' OK, '' CONSECUTIVO
         SELECT ERROR FROM @TBLERRORES
         RETURN
      END
      --SI CONTINUA ES PQ NO SE ENCONTRO ERROR
      --
      SELECT 'OK' OK

      SELECT IMOV.CNSMOV, IMOV.IDBODEGA, IMOV.IDTIPOMOV, ITMO.DESCRIPCION, CONVERT(VARCHAR(10), IMOV.FECHAMOV, 103) FECHA, IMOV.IDSOLICITA,
             IMOV.USUARIOCONF, CONVERT(VARCHAR(10),FECHACONF,103) FECHACONF, CLASEPED, 
             CASE IMOV.ESTADO WHEN 0 THEN 'Pendiente' WHEN 1 THEN 'Confirmado' WHEN 2 THEN 'Anulado' END ESTADO 
      FROM   IMOV INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
      WHERE  IMOV.NODOCUMENTO = @NOADMISION
      AND    IMOV.ESTADO      = CASE @PENDIENTES WHEN 1 THEN 0 ELSE IMOV.ESTADO END

      RETURN
   END
	IF @METODO = 'IMPRIME_POR_SEDE'
	BEGIN
      
		SELECT  @TIPO = TIPO, @MAYOR0 = MAYOR0  , @ESTADO = ESTADO, @BODEGAACTUAL = BODEGAACTUAL, @SELECCIONADO   =SELECCIONADO
				,@IDARTICULO = IDARTICULO, @IDBODEGA = IDBODEGA
		FROM OPENJSON (@PARAMETROS)
		WITH ( 
				TIPO				VARCHAR(20)		'$.TIPO'
				,ESTADO				VARCHAR(20)		'$.ESTADO'
				,MAYOR0				BIT				'$.MAYOR0'
				,BODEGAACTUAL		BIT				'$.BODEGAACTUAL'
				,SELECCIONADO		BIT				'$.SELECCIONADO'
				,IDARTICULO			VARCHAR(20)		'$.IDARTICULO'
				,IDBODEGA			VARCHAR(20)		'$.IDBODEGA'
		)
      
		BEGIN TRY
			IF @MAYOR0 = 1 
			BEGIN
				SELECT 'OK' OK
				
				SELECT ITAR.IDITAR, ITAR.DESCRIPCION, (SELECT  SUM(PCOSTO* EXISTOTAL)  FROM IART	WHERE    IART.IDITAR = ITAR.IDITAR AND IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END ) TOTAL FROM ITAR 
				WHERE EXISTS ( SELECT  * FROM  IBODS WHERE IDBODEGA = @IDBODEGA AND TIPO = 'ITAR' AND ITAR.IDITAR = IBODS.VALOR)
				AND EXISTS (SELECT  * FROM IART INNER JOIN IEXI ON IART.IDARTICULO = IEXI.IDARTICULO WHERE ITAR.IDITAR = IART.IDITAR 
						AND COALESCE( IEXI.EXISLOTE,0) >0  AND IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END )
			--IDUNIDAD
				SELECT ITAR.DESCRIPCION [TIPO], IDARTICULO
				, LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(convert(nvarchar(max),REPLACE(IART.DESCRIPCION,'	 ',' ')),CHaR(10),' ') ,CHaR(13),' ') ,'  ',' '),' 	',' '))) [ARTICULO]
				, IUNI.DESCRIPCION [U. MEDIDA], PCOSTO [COSTO UNI.], EXISTOTAL [EXISTENCIA], PCOSTO* EXISTOTAL [COSTO TOTAL] 
				FROM IART
					LEFT JOIN ITAR ON IART.IDITAR = ITAR.IDITAR
					LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END
				--AND  IART.IDITAR IN (SELECT ITAR.IDITAR FROM ITAR WHERE ITAR.MPRINCIPAL = 1 ) 
				AND EXISTS (SELECT  * FROM IEXI WHERE IART.IDARTICULO = IEXI.IDARTICULO AND IEXI.EXISLOTE>0)
				AND EXISTS ( SELECT  * FROM  IBODS WHERE IDBODEGA = @IDBODEGA AND TIPO = 'ITAR' AND ITAR.IDITAR = IBODS.VALOR)
				ORDER BY  IART.IDITAR, IDARTICULO  ASC

			END
			IF @MAYOR0 = 0
			BEGIN
				SELECT 'OK' OK
				
				SELECT ITAR.IDITAR, ITAR.DESCRIPCION , (SELECT  SUM(PCOSTO* EXISTOTAL)  FROM IART	WHERE    IART.IDITAR = ITAR.IDITAR ) TOTAL
				FROM ITAR 
				WHERE EXISTS ( SELECT  * FROM  IBODS WHERE IDBODEGA = @IDBODEGA AND TIPO = 'ITAR' AND ITAR.IDITAR = IBODS.VALOR)
				AND EXISTS (SELECT  * FROM IART INNER JOIN IEXI ON IART.IDARTICULO = IEXI.IDARTICULO WHERE ITAR.IDITAR = IART.IDITAR 
							AND IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END    )
				ORDER BY  IDITAR  ASC
			
				SELECT ITAR.DESCRIPCION [TIPO], IDARTICULO
				, LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(convert(nvarchar(max),REPLACE(IART.DESCRIPCION,'	 ',' ')),CHaR(10),' ') ,CHaR(13),' ') ,'  ',' '),' 	',' '))) [ARTICULO]
				, IUNI.DESCRIPCION [U. MEDIDA], PCOSTO [COSTO UNI.], EXISTOTAL [EXISTENCIA], PCOSTO* EXISTOTAL [COSTO TOTAL] 
				FROM IART
				LEFT JOIN ITAR ON IART.IDITAR = ITAR.IDITAR
				LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE  IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END
				--AND IART.IDITAR IN (SELECT ITAR.IDITAR FROM ITAR WHERE ITAR.MPRINCIPAL = 1 ) 
				AND EXISTS ( SELECT  * FROM  IBODS WHERE IDBODEGA = @IDBODEGA AND TIPO = 'ITAR' AND ITAR.IDITAR = IBODS.VALOR)

				ORDER BY  IART.IDITAR, IDARTICULO  ASC
			
			END
		END TRY
		BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
	END
	IF @METODO = 'IMPRIME_POR_BODEGA'
	BEGIN
      
		SELECT  @TIPO = TIPO, @MAYOR0 = MAYOR0  , @ESTADO = ESTADO, @BODEGAACTUAL = BODEGAACTUAL, @SELECCIONADO   =SELECCIONADO
				,@IDARTICULO = IDARTICULO, @IDBODEGA = IDBODEGA, @BODEGASELECCIONADA = BODEGASELECCIONADA
		FROM OPENJSON (@PARAMETROS)
		WITH ( 
				TIPO						VARCHAR(20)		'$.TIPO'
				,ESTADO						VARCHAR(20)		'$.ESTADO'
				,MAYOR0						BIT				'$.MAYOR0'
				,BODEGAACTUAL				BIT				'$.BODEGAACTUAL'
				,SELECCIONADO				BIT				'$.SELECCIONADO'
				,IDARTICULO					VARCHAR(20)		'$.IDARTICULO'
				,IDBODEGA					VARCHAR(20)		'$.IDBODEGA'
				,BODEGASELECCIONADA			VARCHAR(20)		'$.BODEGASELECCIONADA'
		)
      
		BEGIN TRY
			IF @MAYOR0 = 1 
			BEGIN
				SELECT 'OK' OK
				
				/*SELECT ITAR.DESCRIPCION [TIPO], IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA], IDXB.IDBODEGA [ID BODEGA], IBOD.DESCRIPCION [BODEGA]
				, IDXB.EXISTOTAL [EXISTENCIA], IART.PCOSTO [COSTO UNI.],IDXB.EXISTOTAL*IART.PCOSTO [COSTO TOTAL]  
				FROM IDXB
				INNER JOIN IBOD ON IDXB.IDBODEGA = IBOD.IDBODEGA
				INNER JOIN IART ON IDXB.IDARTICULO = IART.IDARTICULO
				INNER JOIN ITAR ON IART.IDITAR = ITAR.IDITAR
				LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END
					AND IDXB.EXISTOTAL> 0 
					AND IDXB.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IDXB.IDBODEGA END
					AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				ORDER BY  ITAR.IDITAR, IART.IDARTICULO  ASC*/

				SELECT ITAR.DESCRIPCION [TIPO], IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA], IBOD.IDBODEGA [ID BODEGA], IBOD.DESCRIPCION [BODEGA]
				, IEXI.EXISLOTE [EXISTENCIA], IEXI.PCOSTO [COSTO UNI.],IEXI.EXISLOTE*IEXI.PCOSTO [COSTO TOTAL]  , IART.CODCUM, IEXI.RINVIMA, IEXI.NOLOTE, IEXI.NOLOTEPEDIDO,DBO.FNK_FECHA_DDMMAA(IEXI.FECHAVENCE)FECHAVENCE
				FROM IEXI
					INNER JOIN IBOD ON IEXI.IDBODEGA = IBOD.IDBODEGA
					INNER JOIN IART ON IEXI.IDARTICULO = IART.IDARTICULO
					INNER JOIN ITAR ON IART.IDITAR = ITAR.IDITAR
					LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END
					AND IEXI.EXISLOTE> 0 
					AND IEXI.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IEXI.IDBODEGA END
					AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				ORDER BY  ITAR.IDITAR, IART.IDARTICULO  ASC
			END
			IF @MAYOR0 = 0
			BEGIN
				SELECT 'OK' OK
				
				SELECT ITAR.DESCRIPCION [TIPO], IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA], IDXB.IDBODEGA [ID BODEGA], IBOD.DESCRIPCION [BODEGA]
				, IDXB.EXISTOTAL [EXISTENCIA], IART.PCOSTO [COSTO UNI.],IDXB.EXISTOTAL*IART.PCOSTO [COSTO TOTAL]  
				FROM IDXB
				INNER JOIN IBOD ON IDXB.IDBODEGA = IBOD.IDBODEGA
				INNER JOIN IART ON IDXB.IDARTICULO = IART.IDARTICULO
				INNER JOIN ITAR ON IART.IDITAR = ITAR.IDITAR
				LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				--WHERE IART.IDARTICULO = 'DM01-1' AND IDXB.EXISTOTAL> 0
				WHERE IART.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IART.IDARTICULO END
					AND IDXB.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IDXB.IDBODEGA END
					AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				ORDER BY  ITAR.IDITAR, IART.IDARTICULO  ASC
			END
		END TRY
		BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
	END
	IF @METODO = 'IMPRIME_POR_LOTE'
	BEGIN
		SELECT  @TIPO = TIPO, @MAYOR0 = MAYOR0  , @ESTADO = ESTADO, @BODEGAACTUAL = BODEGAACTUAL, @SELECCIONADO   =SELECCIONADO
				,@IDARTICULO = IDARTICULO, @IDBODEGA = IDBODEGA, @BODEGASELECCIONADA = BODEGASELECCIONADA
		FROM OPENJSON (@PARAMETROS)
		WITH ( 
				TIPO						VARCHAR(20)		'$.TIPO'
				,ESTADO						VARCHAR(20)		'$.ESTADO'
				,MAYOR0						BIT				'$.MAYOR0'
				,BODEGAACTUAL				BIT				'$.BODEGAACTUAL'
				,SELECCIONADO				BIT				'$.SELECCIONADO'
				,IDARTICULO					VARCHAR(20)		'$.IDARTICULO'
				,IDBODEGA					VARCHAR(20)		'$.IDBODEGA'
				,BODEGASELECCIONADA			VARCHAR(20)		'$.BODEGASELECCIONADA'
		)
      
		BEGIN TRY
			IF @MAYOR0 = 1 
			BEGIN
				SELECT 'OK' OK
				
				SELECT IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA], IEXI.NOLOTE [N° LOTE] , SUM(IEXI.EXISLOTE) [EXISTENCIA]
				,  IART.PCOSTO [COSTO UNI.], SUM(IART.PCOSTO* IEXI.EXISLOTE) [COSTO TOTAL] 
				FROM IEXI 
					INNER JOIN IART ON IEXI.IDARTICULO = IART.IDARTICULO
					LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE IEXI.EXISLOTE> 0 
				AND IEXI.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IEXI.IDARTICULO END
				AND IEXI.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IEXI.IDBODEGA END
				AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				GROUP BY IART.IDARTICULO, IART.DESCRIPCION , IUNI.DESCRIPCION , IEXI.NOLOTE, IART.PCOSTO
				ORDER BY  IART.IDARTICULO, IEXI.NOLOTE  ASC
			END
			IF @MAYOR0 = 0
			BEGIN
				SELECT 'OK' OK
				
				SELECT IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA], IEXI.NOLOTE [N° LOTE] , SUM(IEXI.EXISLOTE) [EXISTENCIA]
				,  IART.PCOSTO [COSTO UNI.], SUM(IART.PCOSTO* IEXI.EXISLOTE) [COSTO TOTAL] 
				FROM IEXI 
					INNER JOIN IART ON IEXI.IDARTICULO = IART.IDARTICULO
					LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE 
				IEXI.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IEXI.IDARTICULO END
				AND IEXI.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IEXI.IDBODEGA END
				AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				GROUP BY IART.IDARTICULO, IART.DESCRIPCION , IUNI.DESCRIPCION , IEXI.NOLOTE, IART.PCOSTO
				ORDER BY  IART.IDARTICULO, IEXI.NOLOTE  ASC
			END
		END TRY
		BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
	END
	IF @METODO = 'IMPRIME_POR_BOD_LOTE'
	BEGIN
		SELECT  @TIPO = TIPO, @MAYOR0 = MAYOR0  , @ESTADO = ESTADO, @BODEGAACTUAL = BODEGAACTUAL, @SELECCIONADO   =SELECCIONADO
				,@IDARTICULO = IDARTICULO, @IDBODEGA = IDBODEGA, @BODEGASELECCIONADA = BODEGASELECCIONADA
		FROM OPENJSON (@PARAMETROS)
		WITH ( 
				TIPO						VARCHAR(20)		'$.TIPO'
				,ESTADO						VARCHAR(20)		'$.ESTADO'
				,MAYOR0						BIT				'$.MAYOR0'
				,BODEGAACTUAL				BIT				'$.BODEGAACTUAL'
				,SELECCIONADO				BIT				'$.SELECCIONADO'
				,IDARTICULO					VARCHAR(20)		'$.IDARTICULO'
				,IDBODEGA					VARCHAR(20)		'$.IDBODEGA'
				,BODEGASELECCIONADA			VARCHAR(20)		'$.BODEGASELECCIONADA'
		)
      
		BEGIN TRY
			IF @MAYOR0 = 1 
			BEGIN
				SELECT 'OK' OK
				
				SELECT IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA],IEXI.IDBODEGA [ID BODEGA], IBOD.DESCRIPCION [BODEGA], IEXI.NOLOTE [N° LOTE] , IEXI.EXISLOTE [EXISTENCIA],  IART.PCOSTO [COSTO UNI.], IART.PCOSTO* IEXI.EXISLOTE [COSTO TOTAL] 
				FROM IEXI 
					INNER JOIN IART ON IEXI.IDARTICULO = IART.IDARTICULO
					INNER JOIN IBOD ON IEXI.IDBODEGA = IBOD.IDBODEGA
					LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE IEXI.EXISLOTE> 0 
					AND IEXI.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IEXI.IDARTICULO END
					AND IEXI.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IEXI.IDBODEGA END
					AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				ORDER BY  IART.IDARTICULO, IBOD.IDBODEGA, IEXI.NOLOTE  ASC

			END
			IF @MAYOR0 = 0
			BEGIN
				SELECT 'OK' OK
				
				SELECT IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IUNI.DESCRIPCION [U. MEDIDA],IEXI.IDBODEGA [ID BODEGA], IBOD.DESCRIPCION [BODEGA], IEXI.NOLOTE [N° LOTE] , IEXI.EXISLOTE [EXISTENCIA],  IART.PCOSTO [COSTO UNI.], IART.PCOSTO* IEXI.EXISLOTE [COSTO TOTAL] 
				FROM IEXI 
					INNER JOIN IART ON IEXI.IDARTICULO = IART.IDARTICULO
					INNER JOIN IBOD ON IEXI.IDBODEGA = IBOD.IDBODEGA
					LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE 
					IEXI.IDARTICULO = CASE WHEN  @SELECCIONADO = 1 THEN @IDARTICULO ELSE IEXI.IDARTICULO END
					AND IEXI.IDBODEGA = CASE WHEN @BODEGAACTUAL = 1 THEN @IDBODEGA WHEN @BODEGAACTUAL = 0 AND @BODEGASELECCIONADA IS NOT NULL THEN @BODEGASELECCIONADA ELSE IEXI.IDBODEGA END
					AND IART.ESTADO =  CASE WHEN @ESTADO = 'Activo' THEN 'Activo' WHEN @ESTADO = 'Inactivo' THEN 'Inactivo' ELSE IART.ESTADO END
				ORDER BY  IART.IDARTICULO, IBOD.IDBODEGA, IEXI.NOLOTE  ASC
			END
		END TRY
		BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
	END
	IF @METODO = 'IMPRIME_POR_INST'
	BEGIN
		SELECT  @TIPO = TIPO, @MAYOR0 = MAYOR0  , @ESTADO = ESTADO, @BODEGAACTUAL = BODEGAACTUAL, @SELECCIONADO   =SELECCIONADO
				,@IDARTICULO = IDARTICULO, @IDBODEGA = IDBODEGA, @BODEGASELECCIONADA = BODEGASELECCIONADA
		FROM OPENJSON (@PARAMETROS)
		WITH ( 
				TIPO						VARCHAR(20)		'$.TIPO'
				,ESTADO						VARCHAR(20)		'$.ESTADO'
				,MAYOR0						BIT				'$.MAYOR0'
				,BODEGAACTUAL				BIT				'$.BODEGAACTUAL'
				,SELECCIONADO				BIT				'$.SELECCIONADO'
				,IDARTICULO					VARCHAR(20)		'$.IDARTICULO'
				,IDBODEGA					VARCHAR(20)		'$.IDBODEGA'
				,BODEGASELECCIONADA			VARCHAR(20)		'$.BODEGASELECCIONADA'
		)
      
		BEGIN TRY
			IF @MAYOR0 = 1 
			BEGIN
				SELECT 'OK' OK
				
				SELECT IART.IDITAR, IDARTICULO
					, LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(convert(nvarchar(max),REPLACE(IART.DESCRIPCION,'	 ',' ')),CHaR(10),' ') ,CHaR(13),' ') ,'  ',' '),' 	',' '))) [ARTICULO]
					, IUNI.DESCRIPCION [U. MEDIDA], PCOSTO [COSTO UNI.], EXISTOTAL [EXISTENCIA], PCOSTO* EXISTOTAL [COSTO TOTAL] 
				FROM IART
				LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE   IART.IDITAR IN (SELECT ITAR.IDITAR FROM ITAR WHERE ITAR.MPRINCIPAL = 1 ) AND COALESCE(IART.INSTITUCIONAL,0) = 1
				ORDER BY  IART.IDITAR, IDARTICULO  ASC

			END
			IF @MAYOR0 = 0
			BEGIN
				SELECT 'OK' OK
				
				SELECT IART.IDITAR, IDARTICULO
					, LTRIM(RTRIM(REPLACE(REPLACE(REPLACE(REPLACE(convert(nvarchar(max),REPLACE(IART.DESCRIPCION,'	 ',' ')),CHaR(10),' ') ,CHaR(13),' ') ,'  ',' '),' 	',' '))) [ARTICULO]
					, IUNI.DESCRIPCION [U. MEDIDA], PCOSTO [COSTO UNI.], EXISTOTAL [EXISTENCIA], PCOSTO* EXISTOTAL [COSTO TOTAL] 
				FROM IART
				LEFT JOIN IUNI ON IART.IDUNIDAD = IUNI.IDUNIDAD
				WHERE   IART.IDITAR IN (SELECT ITAR.IDITAR FROM ITAR WHERE ITAR.MPRINCIPAL = 1 ) AND COALESCE(IART.INSTITUCIONAL,0) = 1
				ORDER BY  IART.IDITAR, IDARTICULO  ASC

			END
		END TRY
		BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE();
         END CATCH
         IF(SELECT COUNT(*) FROM @TBLERRORES)>0
         BEGIN
            SELECT 'KO' OK
            SELECT ERROR FROM @TBLERRORES
            RETURN
         END
         SELECT 'OK' OK
	END
	IF @METODO = 'EXPORTA_INFORME_ARTICULO_MOV_BODEGA'
	BEGIN
		
		SELECT  @PROCESO = PROCESO, @CONTROL = CONTROL_DATA  , @TIPO = TIPO, @FECHA = FECHA, @FECHAINI   =FECHAINI
				,@FECHAFIN = FECHAFIN, @IDBODEGA = IDBODEGA, @IDARTICULO = IDARTICULO	,@IDTIPOMOV = IDTIPOMOV
		FROM OPENJSON (@PARAMETROS)
		WITH ( 
				PROCESO			VARCHAR(20)		'$.PROCESO'
				,CONTROL_DATA	BIT				'$.CONTROL'			,TIPO			VARCHAR(20)		'$.TIPO'
				,FECHA			VARCHAR(10)		'$.FECHA'			,FECHAINI		VARCHAR(10)		'$.FECHAINI'
				,FECHAFIN		VARCHAR(10)		'$.FECHAFIN'		,IDBODEGA		VARCHAR(20)		'$.IDBODEGA'
				,IDARTICULO		VARCHAR(20)		'$.IDARTICULO'		,IDTIPOMOV		VARCHAR(20)		'$.IDTIPOMOV'		)
      
	  SELECT @FECHA = REPLACE(@FECHA,'-','')
	  SELECT @FECHAINI = REPLACE(@FECHAINI,'-','')
	  SELECT @FECHAFIN = REPLACE(@FECHAFIN,'-','')

	  IF @PROCESO = 'histMovimiento'
	  BEGIN
		SELECT 'OK' OK
		SELECT * FROM FNK_HISTORICO_IMOV (@TIPO,@FECHA,@IDBODEGA,@IDARTICULO,@CONTROL)
		
	  END
	  IF @PROCESO = 'mediControlados'
	  BEGIN
		SELECT 'OK' OK
		IF @TIPO = 'M'
		BEGIN
			SELECT  IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IBOD.IDBODEGA, IBOD.DESCRIPCION [BODEGA], IMOV.CNSMOV, IMOV.FECHAMOV, IMOV.FECHACONF, IMOVH.PCOSTO, IMOVH.CANTIDAD  
				,ITMO.IDTIPOMOV, ITMO.DESCRIPCION [TIPO MOVIMIENTO]
			FROM IMOVH 
				INNER JOIN IART  ON IMOVH.IDARTICULO = IART.IDARTICULO
				INNER JOIN IMOV  ON IMOVH.CNSMOV = IMOV.CNSMOV
				LEFT JOIN IBOD ON IMOV.IDBODEGA = IBOD.IDBODEGA
				LEFT JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
			WHERE IMOV.ESTADO = '1'
				AND IMOV.IDBODEGA      = CASE WHEN COALESCE(@IDBODEGA,'') = '' THEN IMOV.IDBODEGA ELSE @IDBODEGA END
				AND IMOV.IDTIPOMOV     = CASE WHEN COALESCE(@IDTIPOMOV,'') = '' THEN IMOV.IDTIPOMOV ELSE @IDTIPOMOV END
				AND IMOVH.IDARTICULO    = CASE WHEN COALESCE(@IDARTICULO,'') = '' THEN IMOVH.IDARTICULO ELSE @IDARTICULO END 
				AND COALESCE(IART.CONT_ESPECIAL,0) = CASE WHEN COALESCE(@CONTROL,0) = 0 THEN COALESCE(IART.CONT_ESPECIAL,0) ELSE @CONTROL END 
				AND IMOV.FECHAMOV >= CONVERT(DATE,@FECHAINI) AND IMOV.FECHAMOV <= CONVERT(DATE,@FECHAFIN) 
			ORDER BY IMOVH.IDARTICULO,IMOV.IDBODEGA,  IMOV.IDTIPOMOV DESC
		END
		IF @TIPO = 'C'
		BEGIN
			SELECT  IART.IDARTICULO, IART.DESCRIPCION [ARTICULO], IBOD.IDBODEGA, IBOD.DESCRIPCION [BODEGA], IMOV.CNSMOV, IMOV.FECHAMOV, IMOV.FECHACONF, IMOVH.PCOSTO, IMOVH.CANTIDAD  
				,ITMO.IDTIPOMOV, ITMO.DESCRIPCION [TIPO MOVIMIENTO]
			FROM IMOVH 
				INNER JOIN IART  ON IMOVH.IDARTICULO = IART.IDARTICULO
				INNER JOIN IMOV  ON IMOVH.CNSMOV = IMOV.CNSMOV
				LEFT JOIN IBOD ON IMOV.IDBODEGA = IBOD.IDBODEGA
				LEFT JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV
			WHERE IMOV.ESTADO = '1'
				AND IMOV.IDBODEGA      = CASE WHEN COALESCE(@IDBODEGA,'') = '' THEN IMOV.IDBODEGA ELSE @IDBODEGA END
				AND IMOV.IDTIPOMOV     = CASE WHEN COALESCE(@IDTIPOMOV,'') = '' THEN IMOV.IDTIPOMOV ELSE @IDTIPOMOV END
				AND IMOVH.IDARTICULO    = CASE WHEN COALESCE(@IDARTICULO,'') = '' THEN IMOVH.IDARTICULO ELSE @IDARTICULO END 
				AND COALESCE(IART.CONT_ESPECIAL,0) = CASE WHEN COALESCE(@CONTROL,0) = 0 THEN COALESCE(IART.CONT_ESPECIAL,0) ELSE @CONTROL END 
				AND IMOV.FECHACONF >= CONVERT(DATE,@FECHAINI) AND IMOV.FECHACONF <= CONVERT(DATE,@FECHAFIN) 
			ORDER BY IMOVH.IDARTICULO,IMOV.IDBODEGA,  IMOV.IDTIPOMOV DESC
		END
	  END
	END
	IF @METODO = 'EXPORT_PRECIO_COSTO'
	BEGIN
		SELECT 'OK' OK
		SELECT SER.IDSERVICIO, SER.DESCSERVICIO, IART.PCOSTO, 0 PVENTA, 0 [MARGEN] FROM SER
		LEFT JOIN IART ON SER.IDSERVICIO = IART.IDARTICULO
	END
	IF @METODO = 'EXPORTA_INFORME_CONSUMOS'
	BEGIN
		SELECT @PROCESO = PROCESO, @FECHAINI = FECHAINI, @FECHAFIN = FECHAFIN, @IDBODEGA = IDBODEGA
			, @IDARTICULO = IDARTICULO, @IDTIPOMOV = IDTIPOMOV, @CCOSTO = CCOSTO, @IDAREA = IDAREA, @IDTERCERO = IDTERCERO
		FROM OPENJSON(@PARAMETROS)
		WITH(	PROCESO	VARCHAR(20)		'$.PROCESO', FECHAINI	VARCHAR(20)		'$.FECHAINI',
				FECHAFIN	VARCHAR(20)		'$.FECHAFIN',		IDBODEGA	VARCHAR(20)		'$.IDBODEGA',
				IDARTICULO	VARCHAR(20)		'$.IDARTICULO', IDTIPOMOV	VARCHAR(20)		'$.IDTIPOMOV',
				CCOSTO	VARCHAR(20)		'$.CCOSTO', IDAREA	VARCHAR(20)		'$.IDAREA',
				IDTERCERO	VARCHAR(20)		'$.IDTERCERO')
	
	
		IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
		BEGIN
			SELECT 'KO' OK
			SELECT ERROR FROM @TBLERRORES
			RETURN
		END
		ELSE
		BEGIN
			BEGIN TRY
				SELECT @FECHAINI = REPLACE(@FECHAINI, '-', '')
				SELECT @FECHAFIN = REPLACE(@FECHAFIN, '-', '')
				SELECT 'OK' OK
				IF @PROCESO = 'consumoAreaTercero'
				BEGIN
					SELECT * FROM FNK_MOVIMIENTOS(@FECHAINI,@FECHAFIN,@IDBODEGA,@CCOSTO,@IDAREA,@TIPO, @IDTIPOMOV, @IDTERCERO,@IDARTICULO) ORDER BY IDBODEGA,CCOSTO,IDAREA,IDTIPOMOV,TIPO,IDTERCERO,DESARTICULO
				END
				IF @PROCESO = 'consumoArticulo'
				BEGIN
					SELECT VW_INVCONSUMO.IDARTICULO, DESCRIPCION, SUM(CANTIDAD) [CANTIDAD], SUM(CANTIDAD*VW_INVCONSUMO.PCOSTO) [PCOSTO]
					FROM VW_INVCONSUMO,IART
					WHERE VW_INVCONSUMO.IDARTICULO = IART.IDARTICULO AND FECHAMOV BETWEEN
					@FECHAINI AND @FECHAFIN 
					AND VW_INVCONSUMO.IDARTICULO = COALESCE(@IDARTICULO, VW_INVCONSUMO.IDARTICULO )
					GROUP BY VW_INVCONSUMO.IDARTICULO,DESCRIPCION ORDER BY DESCRIPCION
				END


			END TRY  
			BEGIN CATCH 
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE() ;  
			END CATCH  
			IF (SELECT COUNT(*) FROM @TBLERRORES)> 0
			BEGIN
				SELECT 'KO' OK
				SELECT ERROR FROM @TBLERRORES
				RETURN
			END
			SELECT 'OK'OK
		END 
	END
END







