IF EXISTS (SELECT name FROM sysobjects 
   WHERE name = 'SPK_ESTADO_CORTECUENTA' AND type = 'P')
   DROP PROCEDURE SPK_ESTADO_CORTECUENTA
GO
CREATE PROC DBO.SPK_ESTADO_CORTECUENTA
@NOADMISION VARCHAR(16),
@RPDX       VARCHAR(20),
@FECHACORTE DATETIME,
@PASO       VARCHAR(1) = '',
@CENTROS    VARCHAR(MAX) = ''
WITH ENCRYPTION
AS
DECLARE @CONT                 INT
DECLARE @COPAGONOAUTORIZACION VARCHAR(20)
DECLARE @COPAGOVALOR          DECIMAL(14,2)
DECLARE @VALOR                DECIMAL(14,2)
DECLARE @NOPRESTACION         VARCHAR(16)
DECLARE @DATO                 VARCHAR(80)
DECLARE @IDPLAN               VARCHAR(6) 
DECLARE @CERRADA              SMALLINT
DECLARE @MAN_COPAGOEXT		   SMALLINT
DECLARE @VLR_COPAGOEXTERNO	   DECIMAL(14,2)
DECLARE @TIPOADM              VARCHAR(2)
DECLARE @USACTC               SMALLINT
DECLARE @CONTAR               INT
BEGIN
   SELECT @CERRADA = CERRADA, @TIPOADM = TIPOADM, @USACTC = USACTC, @IDPLAN = IDPLAN FROM HADM WHERE NOADMISION = @NOADMISION
   IF COALESCE(@CENTROS,'') = ''
      IF @CERRADA <> 0
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'YA TIENE ALTA. DEBE FACTURARSE NORMALMENTE. '
      END

   IF (SELECT ISNULL(COUNT(*),0) 
       FROM   PPT INNER JOIN HADM ON PPT.IDTERCERO = HADM.IDTERCERO AND PPT.IDPLAN = HADM.IDPLAN 
       AND    HADM.NOADMISION = @NOADMISION
       AND    PPT.PFACTURARIND = 0 ) > 0
   BEGIN
      INSERT INTO RPDX ( CNS, NOMBRE ) 
	   SELECT @RPDX, 'NO PERMITE FACTURAR INDIVIDUALMENTE. DEBE SER MASIVA '
   END
   
   SELECT @CONT = ISNULL(COUNT(*),0) FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
   
   IF @CONT = 0
   BEGIN
      PRINT 'SIN CARGOS'
      INSERT INTO RPDX ( CNS, NOMBRE ) 
      SELECT @RPDX, 'ADMISION SIN PRESTACIONES (CARGOS)'
      RETURN
   END
   IF DBO.FNK_VALORVARIABLE('MAN_AUD_CONCURENTE')='SI'
   BEGIN
	IF (SELECT COUNT(*) FROM HPRE WHERE NOADMISION=@NOADMISION AND  COALESCE(REVAUD,0)<>2
	AND EXISTS (SELECT * FROM HADM WHERE NOADMISION=@NOADMISION AND CERRADA IN(3))
	AND CCOSTO IN (SELECT WORD FROM DBO.FNK_EXPLODE(@CENTROS,',')))>0
	INSERT INTO RPDX (CNS, NOMBRE)
    SELECT @RPDX, LEFT('La admisión no ha sido aprobada por el departamento de Auditoría, debe envíar a su respectiva revisión ó debe esperar la respuesta por parte de ellos.',150)      
   END
   IF @CENTROS = ''
	BEGIN
      IF (SELECT COUNT(*) 
          FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
          WHERE  HPRE.NOADMISION = @NOADMISION
          AND    ISNULL(HPRE.ANULADO,0)    = 0
          AND    ISNULL(HPRED.ANULADO,0)   = 0
          AND    ISNULL(HPRED.FACTURADA,0) = 0
          AND    HPRE.FECHA <= @FECHACORTE + 1
         ) = 0
      BEGIN
         PRINT 'NO EXISTEN CARGOS PARA FACTURAR HASTA LA FECHA DE CORTE.'
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'NO EXISTEN CARGOS PARA FACTURAR HASTA LA FECHA DE CORTE.'
         RETURN
      END
	END
   ELSE
	BEGIN
      IF (SELECT COUNT(*) 
          FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
          WHERE  HPRE.NOADMISION = @NOADMISION
          AND    ISNULL(HPRE.ANULADO,0)    = 0
          AND    ISNULL(HPRED.ANULADO,0)   = 0
          AND    ISNULL(HPRED.FACTURADA,0) = 0
          AND    HPRE.FECHA <= @FECHACORTE + 1
          AND    COALESCE(HPRED.CCOSTO,HPRE.CCOSTO) IN (SELECT WORD FROM DBO.FNK_EXPLODE(@CENTROS,','))
         ) = 0
      BEGIN
         PRINT 'NO EXISTEN CARGOS PARA FACTURAR HASTA LA FECHA DE CORTE.'
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'NO EXISTEN CARGOS PARA FACTURAR HASTA LA FECHA DE CORTE.'
         RETURN
      END
	END
   SELECT @COPAGONOAUTORIZACION = COPAGONOAUTORIZACION, @COPAGOVALOR = COPAGOVALOR 
   FROM   HADM
   WHERE  NOADMISION = @NOADMISION
   
   PRINT 'MIRAR HPRE SIN HPRED O HPRED CON VALORES EN 0'

   IF @CENTROS = ''
   BEGIN
      DECLARE PRESTACIOND_CURSOR CURSOR FOR  
      SELECT NOPRESTACION FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0 AND FECHA <= @FECHACORTE + 1
      AND    EXISTS( SELECT 1 FROM HPRED WHERE HPRED.NOPRESTACION = HPRE.NOPRESTACION
                     AND ISNULL(HPRED.NOCOBRABLE,0)=0 AND ISNULL(HPRED.ANULADO,0)=0
                   )
   END
   ELSE
   BEGIN
      DECLARE PRESTACIOND_CURSOR CURSOR FOR  
      SELECT NOPRESTACION FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
      AND    HPRE.FECHA <= @FECHACORTE + 1
      AND    EXISTS( SELECT 1 FROM HPRED WHERE HPRED.NOPRESTACION = HPRE.NOPRESTACION
                     AND ISNULL(HPRED.NOCOBRABLE,0)=0 AND ISNULL(HPRED.ANULADO,0)=0
                     AND    COALESCE(HPRED.CCOSTO,HPRE.CCOSTO) IN (SELECT WORD FROM DBO.FNK_EXPLODE(@CENTROS,',') )
                   )
   END
   OPEN PRESTACIOND_CURSOR  
   FETCH NEXT FROM PRESTACIOND_CURSOR  
   INTO @NOPRESTACION
   WHILE @@FETCH_STATUS = 0  
   BEGIN        
      SELECT @CONT = COALESCE(COUNT(*),0) FROM HPRED WHERE HPRED.NOPRESTACION = @NOPRESTACION AND ISNULL(NOCOBRABLE,0)=0 AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
      IF @CONT = 0
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'PRESTACION '+@NOPRESTACION+' SIN DETALLES'         
      END
      
      SELECT @CONT = COUNT(*) FROM HPRED 
      WHERE  HPRED.NOPRESTACION = @NOPRESTACION
      AND    COALESCE(HPRED.VALOR,0)        = 0 
      AND    COALESCE(HPRED.NOCOBRABLE,0)   = 0
      AND    ISNULL(ANULADO,0)  = 0 --SJUNCO REQ 1803
      AND    COALESCE(HPRED.ENCARGOS,0) = 0
      AND    COALESCE(HPRED.FACTURADA,0) = 0
      IF @CONT > 0
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'PRESTACION '+RTRIM(LTRIM(@NOPRESTACION))+' Tiene Detalles con valor en 0'         
      END
           
      FETCH NEXT FROM PRESTACIOND_CURSOR  
      INTO @NOPRESTACION
   END
   CLOSE PRESTACIOND_CURSOR  
   DEALLOCATE PRESTACIOND_CURSOR  

   SELECT @CONT = 0

   PRINT 'MIRAR HPRED QUE NO CUADREN VALORES'
   IF @CENTROS = ''
   BEGIN
      DECLARE PRESTACIOND_CURSOR CURSOR FOR  
      SELECT NOPRESTACION FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
      AND    HPRE.FECHA <= @FECHACORTE + 1
   END
   ELSE
   BEGIN
      DECLARE PRESTACIOND_CURSOR CURSOR FOR  
      SELECT NOPRESTACION FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
      AND    HPRE.FECHA <= @FECHACORTE + 1
      AND    EXISTS( SELECT 1 FROM HPRED WHERE HPRED.NOPRESTACION = HPRE.NOPRESTACION
                     AND ISNULL(HPRED.NOCOBRABLE,0)=0 AND ISNULL(HPRED.ANULADO,0)=0
                     AND    COALESCE(HPRED.CCOSTO,HPRE.CCOSTO) IN (SELECT WORD FROM DBO.FNK_EXPLODE(@CENTROS,',') )
                   )
   END
   OPEN PRESTACIOND_CURSOR  
   FETCH NEXT FROM PRESTACIOND_CURSOR  
   INTO @NOPRESTACION
   WHILE @@FETCH_STATUS = 0  
   BEGIN        
      SELECT @CONT = COUNT(*) FROM HPRED 
      WHERE  HPRED.NOPRESTACION = @NOPRESTACION
      AND    COALESCE(HPRED.NOCOBRABLE,0) = 0
      AND   ABS( COALESCE(VALOREXCEDENTE,0) - (((COALESCE(VALOR,0) * COALESCE(CANTIDAD,0))) - COALESCE(VALORCOPAGO,0) - COALESCE(VALORPCOMP,0)
											-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN COALESCE(VLRSERVICIOH,0) ELSE 0 END))>=1
      IF @CONT > 0
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'PRESTACION '+RTRIM(LTRIM(@NOPRESTACION))+' Valores difieren: (Valor * Cantidad) - copago - pagocomp'         
      END
      FETCH NEXT FROM PRESTACIOND_CURSOR  
      INTO @NOPRESTACION
   END
   CLOSE PRESTACIOND_CURSOR  
   DEALLOCATE PRESTACIOND_CURSOR  

   PRINT 'REVISION SI TIENE AUTORIZACION LA ADMISION '
   IF @COPAGONOAUTORIZACION IS NOT NULL AND @COPAGONOAUTORIZACION <> ''
   BEGIN 
      SELECT @VALOR = SUM(HPRE.VALORCOPAGO) FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0     
      IF @VALOR <> @COPAGOVALOR
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'COPAGO SIN DISTRIBUIR TOTALMENTE'
      END
   END  
   PRINT 'CIRUGIA' 
   SELECT @CONT = ISNULL(COUNT(*),0) FROM QXPCX WHERE NOADMISION = @NOADMISION AND LIQ_ADC = 0
   AND    QXPCX.FECHA <= @FECHACORTE+1
   IF @CONT > 0
   BEGIN
      PRINT 'ENTRE A CIRUGIA SIN LIQUIDAR'
      INSERT INTO RPDX ( CNS, NOMBRE ) 
      SELECT @RPDX, 'CIRUGIA SIN LIQUIDAR'
   END
   --PRINT 'REVISION DE DOCUMENTACION'
   --SELECT @CONT = ISNULL(COUNT(*),0) FROM HREQ WHERE NOADMISION = @NOADMISION AND COALESCE(CUMPLIDO,0) = 0
   --IF @CONT > 0
   --BEGIN
   --   INSERT INTO RPDX ( CNS, NOMBRE ) 
   --   SELECT @RPDX, 'DOCUMENTACION INCOMPLETA'
   --END
   PRINT 'REVISION DE PEDIDOS A INVENTARIO DESDE CARGOS'
   SELECT @CONT = COALESCE(COUNT(*),0) FROM HPRE WHERE NOADMISION = @NOADMISION AND ESDEINV = 1 AND PEDIDOINV = 0 AND ISNULL(ANULADO,0)= 0 --SJUNCO REQ 1803
   AND    HPRE.FECHA <= @FECHACORTE+1
   IF @CONT > 0  
   BEGIN
      INSERT INTO RPDX ( CNS, NOMBRE ) 
      SELECT @RPDX, 'CARGOS SIN PEDIR A INVENTARIOS'
   END
   
   PRINT 'REVISA PEDIDOS A INVENTARIOS SIN CONFIRMAR'
   SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'PALTASINCONF'
   IF @DATO <> 'SI'
   BEGIN
      SELECT @CONT = COALESCE(COUNT(*),0) FROM IMOV WHERE NODOCUMENTO = @NOADMISION AND ESTADO = '0' 
      AND    IMOV.FECHAMOV <= @FECHACORTE + 1
      AND    PROCEDENCIA IN ('HTX', 'SALUD', 'FORMEDASIS')    
      AND    IDBODEGA <> DBO.FNK_VALORVARIABLE('IDBODEGA_APROV ')
      IF @CONT > 0
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'CARGOS/ PEDIDOS HTX SIN CONFIRMAR EN INVENTARIO'
      END
   END  

   --PRINT 'REVISA DATOS RECIEN NACIDO'
   --SELECT @CONT = COALESCE(COUNT(*),0)
   --FROM   QXPCX INNER JOIN QXPCXD ON QXPCX.CONSECUTIVO = QXPCXD.CONSECUTIVO
   --WHERE  QXPCX.NOADMISION = @NOADMISION
   --AND    QXPCXD.IDSERVICIO IN (SELECT CODIGO FROM TGEN WHERE TABLA = 'General' AND CAMPO = 'CXCONRNACIDO')
   --IF @CONT > 0
   --BEGIN
   --   SELECT @CONT = COALESCE(COUNT(*),0) FROM QXRCN WHERE NOADMISION = @NOADMISION
   --   IF @CONT < 1
   --   BEGIN
   --      INSERT INTO RPDX ( CNS, NOMBRE ) 
   --      SELECT @RPDX, 'SIN REGISTRO DE RECIEN NACIDO'
   --   END
   --   ELSE
   --   BEGIN
   --      SELECT @CONT = COUNT(*) FROM QXRCN 
   --      WHERE  NOADMISION = @NOADMISION
	  --  AND    ((CMPERIODOGES IS NULL OR CMPERIODOGES = '') OR
   --              (CMCONTROLPRE IS NULL OR CMCONTROLPRE = '') OR
		 --      (RNFECHANACE IS NULL OR RNFECHANACE = '') OR
   --              (RNSEXO IS NULL OR RNSEXO = '') OR
   --              (RNPESO IS NULL OR RNPESO = '') OR
   --              (RNTALLA IS NULL OR RNTALLA = '') OR
   --              (RNDX IS NULL OR RNDX = '') OR
   --              (ESTADORN IS NULL OR ESTADORN = '') OR
   --              (RNAPGAR5 IS NULL OR RNAPGAR5 = ''))
   --      IF @CONT > 0
	  --  BEGIN
   --         INSERT INTO RPDX ( CNS, NOMBRE ) 
   --         SELECT @RPDX, 'SIN DATOS DE RECIEN NACIDO'
   --      END
   --   END
   --END
   PRINT 'REVISA FECHAS DE NACIMIENTO INVALIDA'
   IF (SELECT AFI.FNACIMIENTO
       FROM   AFI INNER JOIN HADM ON AFI.IDAFILIADO = HADM.IDAFILIADO
       WHERE  HADM.NOADMISION = @NOADMISION) IS NULL
   BEGIN 
       INSERT INTO RPDX ( CNS, NOMBRE ) 
       SELECT @RPDX, 'AFILIADO SIN FECHA DE NACIMIENTO'
   END
   PRINT 'REVISA NUMERO DE CEDULAS INVALIDOS'
   IF (SELECT DBO.FNK_SOLONUMEROS(DOCIDAFILIADO) 
       FROM   AFI INNER JOIN HADM ON AFI.IDAFILIADO = HADM.IDAFILIADO
       WHERE  HADM.NOADMISION = @NOADMISION
       AND    AFI.TIPO_DOC    = 'CC') > 0
   BEGIN
       INSERT INTO RPDX ( CNS, NOMBRE ) 
       SELECT @RPDX, 'EL TIPO DE DOCUMENTO  CC  NO ACEPTA CARACTERES ALFANUMERICOS'
   END
   IF DBO.FNK_VALORVARIABLE('IDCON_CONTAB_X_HPRE') = 'HPRE'
   BEGIN
      IF (SELECT COUNT(*) FROM HPRE WHERE NOADMISION = @NOADMISION AND CERRADA = 0 AND ISNULL(ANULADO,0)=0 
          AND    HPRE.FECHA <= @FECHACORTE+1) > 0 --SJUNCO REQ 1803
      BEGIN
         INSERT INTO RPDX ( CNS, NOMBRE ) 
         SELECT @RPDX, 'TIENE PRESTACIONES SIN CERRAR (CTA CTE)'
      END
   END
   -- ADD. JQUIROGA 20090406 - AARROYO
	IF EXISTS(	SELECT DISTINCT HPRE.NOPRESTACION 
               FROM   HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				   WHERE  HPRE.VALORTOTAL = 0 
               AND    HPRED.NOCOBRABLE <> 1 
               AND    HPRE.NOADMISION = @NOADMISION 
               AND    COALESCE(HPRE.ANULADO,0)   = 0--SJUNCO REQ 1803
               AND    COALESCE(HPRED.ENCARGOS,0) = 0 
               AND    HPRE.FECHA <= @FECHACORTE+1
               AND    ISNULL(HPRED.FACTURADA,0)<>1
               AND    COALESCE(HPRED.ENCARGOS,0) = 0 )
	BEGIN
	   INSERT INTO RPDX ( CNS, NOMBRE ) 
	   SELECT DISTINCT @RPDX, HPRED.NOPRESTACION+': PRESTACION COBRABLE CON VALOR CERO O CON VALOR NULO '
       FROM   HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
				         WHERE  HPRE.VALORTOTAL = 0 
                     AND    HPRED.NOCOBRABLE <> 1 
                     AND    HPRE.NOADMISION = @NOADMISION 
                     AND    COALESCE(HPRE.ANULADO,0)   = 0--SJUNCO REQ 1803
                     AND    COALESCE(HPRED.ENCARGOS,0) = 0 
                     AND    HPRE.FECHA <= @FECHACORTE+1
                     AND    ISNULL(HPRED.FACTURADA,0)<>1
                     AND    COALESCE(HPRED.ENCARGOS,0) = 0 
                     AND    HPRE.FECHA <= @FECHACORTE+1
	END

   
   /* NO PERMITIR PRESTACIONES NO COBRABLES CON VALOR MAYOR A CERO */
   IF EXISTS(	SELECT DISTINCT HPRE.NOPRESTACION 
               FROM   HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
               AND    COALESCE(HPRED.NOCOBRABLE,0) = 1
               AND    HPRE.NOADMISION = @NOADMISION 
               AND    COALESCE(HPRE.ANULADO,0)   = 0 
               AND    COALESCE(HPRED.ENCARGOS,0) = 0
               AND    COALESCE(HPRED.FACTURADA,0) = 0
               AND    HPRE.FECHA <= @FECHACORTE+1
               AND    (HPRED.VALOR>0 OR HPRED.VALOREXCEDENTE>0) )
	BEGIN
	   INSERT INTO RPDX ( CNS, NOMBRE ) 
	   SELECT DISTINCT @RPDX, HPRED.NOPRESTACION+': PRESTACION NO COBRABLE CON VALOR MAYOR A CERO - IDSERVICIO: '+HPRED.IDSERVICIO
      FROM   HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
      AND    COALESCE(HPRED.NOCOBRABLE,0) = 1
      AND    HPRE.NOADMISION = @NOADMISION 
      AND    COALESCE(HPRE.ANULADO,0)   = 0 
      AND    COALESCE(HPRED.ENCARGOS,0) = 0
      AND    COALESCE(HPRED.FACTURADA,0) = 0
      AND    HPRE.FECHA <= @FECHACORTE+1
      AND    (HPRED.VALOR>0 OR HPRED.VALOREXCEDENTE>0)
	END


   /*NO PERMITIR VALORES DE CANTIDADES NEGATIVAS NI VALORES NEGATIVOS   JEDM.2011.10.10*/
   IF (	SELECT COALESCE(COUNT(*),0)
         FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE  HPRED.CANTIDAD < 0 
         AND    HPRED.NOCOBRABLE <> 1 
         AND    HPRE.NOADMISION = @NOADMISION 
         AND    COALESCE(HPRE.ANULADO,0)   = 0--SJUNCO REQ 1803
         AND    COALESCE(HPRED.ENCARGOS,0) = 0 
         AND    HPRE.FECHA <= @FECHACORTE+1) > 0        
	BEGIN
	   INSERT INTO RPDX ( CNS, NOMBRE ) 
	   SELECT @RPDX, 'PRESTACIONES CON CANTIDAD NEGATIVA, NOPRESTACION = '+HPRED.NOPRESTACION
	   FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
		WHERE  HPRED.CANTIDAD < 0 
      AND    HPRE.NOADMISION = @NOADMISION 
      AND    COALESCE(HPRE.ANULADO,0)   = 0--SJUNCO REQ 1803
      AND    COALESCE(HPRED.ENCARGOS,0) = 0
      AND    HPRE.FECHA <= @FECHACORTE+1
	END
	
   IF (	SELECT COALESCE(COUNT(*),0)
         FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
			WHERE  COALESCE(HPRED.VALOR,0) < 0 
         AND    HPRE.NOADMISION = @NOADMISION 
         AND    COALESCE(HPRE.ANULADO,0)   = 0--SJUNCO REQ 1803
         AND    COALESCE(HPRED.ENCARGOS,0) = 0 
         AND    HPRE.FECHA <= @FECHACORTE+1) > 0        
	BEGIN
	   INSERT INTO RPDX ( CNS, NOMBRE ) 
	   SELECT @RPDX, 'PRESTACIONES CON VALORES NEGATIVOS, NOPRESTACION = '+HPRED.NOPRESTACION
	   FROM   HPRE INNER JOIN HPRED ON HPRE.NOPRESTACION = HPRED.NOPRESTACION
		WHERE  HPRED.CANTIDAD < 0 
      AND    HPRED.NOCOBRABLE <> 1 
      AND    HPRE.NOADMISION = @NOADMISION 
      AND    COALESCE(HPRE.ANULADO,0)   = 0--SJUNCO REQ 1803
      AND    COALESCE(HPRED.ENCARGOS,0) = 0
      AND    HPRE.FECHA <= @FECHACORTE+1
	END
	
   -- ADD. JQUIROGA 20090427 - El valor del copago externo no puede ser mayor al valor copago interno.
   /*
	SELECT @MAN_COPAGOEXT = MANCOPAGOEXT, @VLR_COPAGOEXTERNO = VLR_COPAGOEXTERNO FROM HADM WHERE NOADMISION = @NOADMISION
	IF @MAN_COPAGOEXT = 1
	BEGIN
		IF @VLR_COPAGOEXTERNO > (SELECT SUM(VALORCOPAGO) FROM HPRE WHERE NOADMISION = @NOADMISION AND ISNULL(ANULADO,0)=0)--SJUNCO REQ 1803
		BEGIN
			INSERT INTO RPDX ( CNS, NOMBRE ) 
			SELECT @RPDX, 'EL COPAGO EXTERNO DE LA ADMISION NO PUEDE SUPERAR EL COPAGO DE LOS CARGOS'
		END
	END
	*/
	/* */
	IF (SELECT DBO.FNK_VALORVARIABLE('IDTARIFASOAT')) = @TIPOADM
	BEGIN	
	   PRINT 'ACCIDENTE DE TRANSITO no se puede hacer corte.'  
      INSERT INTO RPDX ( CNS, NOMBRE ) 
	   SELECT @RPDX, 'ACCIDENTE DE TRANSITO no se puede hacer corte.' 
	END
	/*SE REVISA SI SE DEBE REVISAR SI LOS MEDICAMENTOS DE LA HTX APLICADOS ESTAN CARGADOS */
	
	IF DBO.FNK_VALORVARIABLE('FTR_VALHTXSINCARGAR') = 'SI'
	BEGIN
	   IF (SELECT COALESCE(COUNT(*),0) FROM HTX WHERE NOADMISION = @NOADMISION
	       AND    COALESCE(APLICADO,0) = 1
	       AND    COALESCE(ENCARGOS,0) = 0
            AND    HTX.FECHAREQ <= @FECHACORTE+1) > 0
	   BEGIN
           INSERT INTO RPDX (CNS, NOMBRE)
           SELECT @RPDX, 'Existen Items de La Hoja de Tratamiento Aplicados sin Enviar a Cargos.'
        END
        /*SE REVISA htx QUE NO HALLAN HECHO NADA diferente de suspendidos*/
	   IF (SELECT COALESCE(COUNT(*),0) FROM HTX 
	       WHERE  NOADMISION = @NOADMISION
	       AND    COALESCE(SOLICITADO,0)  = 0
	       AND    COALESCE(APLICADO,0)    = 0
	       AND    COALESCE(HTX.ANULADA,0) = 0
	       AND    COALESCE (HTX.CLASEANULA,'') = ''
	       AND    COALESCE (HTX.ANULADA,0) = 0
	       AND    COALESCE(HTX.CLASEHTX,'') <> 'NA' 
	       AND    COALESCE(HTX.INDDEV,0) <> 1
            AND    COALESCE(HTX.ESTADO,'') <> 'S'
            AND    HTX.FECHAREQ <= @FECHACORTE+1) > 0
	   BEGIN
	      INSERT INTO RPDX (CNS, NOMBRE)
           SELECT @RPDX, 'Existen Items de La Hoja de Tratamiento Sin Definir Sin APlicar y Sin NO APlicar.'
	   END    
        /*SE REVISA htx los suspendidos QUE fueron solicitados a Inventario pero no han sido corregidos*/
	   IF (SELECT COALESCE(COUNT(*),0) FROM HTX 
	       WHERE  NOADMISION = @NOADMISION
	       AND    COALESCE(SOLICITADO,0)  = 1
            AND    COALESCE(HTX.LISTOENTREGA,0) = 0
            AND    COALESCE(HTX.ENTREGADO,0) = 0
	       AND    COALESCE(HTX.APLICADO,0)    = 0
	       AND    COALESCE(HTX.ANULADA,0) = 0
	       AND    COALESCE (HTX.CLASEANULA,'') = ''
	       AND    COALESCE (HTX.ANULADA,0) = 0
	       AND    COALESCE(HTX.CLASEHTX,'') <> 'NA' 
	       AND    COALESCE(HTX.INDDEV,0) <> 1
            AND    COALESCE(HTX.ESTADO,'') = 'S'
            AND    COALESCE(HTX.CANTIDADINV,0) > 0 
            AND    HTX.FECHAREQ <= @FECHACORTE+1) > 0
	   BEGIN
	      INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, 'Existen Items de La Hoja de Tratamiento Suspendidos Pedidos a Inventarios Sin Corregir .'
	   END    

	   /*SE REVISA QUE LOS ITEMS SOLICITADO A INVENTARIO ESTEN APLICADOS */
      IF (SELECT COALESCE(COUNT(*),0) FROM HTX 
	       WHERE  NOADMISION = @NOADMISION
	       AND    COALESCE(HTX.SOLICITADO,0)   = 1 
	       AND    COALESCE(HTX.LISTOENTREGA,0) = 1 
	       AND    COALESCE(HTX.ENTREGADO,0)    = 1 
	       AND    COALESCE(HTX.APLICADO,0)     = 0 
	       AND    COALESCE(HTX.INDDEV,0)       = 0
	       AND    COALESCE (HTX.CLASEANULA,'') = ''
	       AND    COALESCE (HTX.ANULADA,0) = 0 
          AND    COALESCE(HTX.ESTADO,'') <> 'S' 
          AND    HTX.FECHAREQ <= @FECHACORTE+1)> 0
	   BEGIN
	      INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, 'Existen Items de La Hoja de Tratamiento Traidos del Inventario Sin APlicar'
	   END   
      /*SE REVISA htx los suspendidos QUE fueron solicitados a Inventario Y ENTREGADOS pero no han sido Devueltos*/
      IF (SELECT COALESCE(COUNT(*),0) FROM HTX 
	       WHERE  NOADMISION = @NOADMISION
	       AND    COALESCE(SOLICITADO,0)  = 1
          AND    COALESCE(HTX.LISTOENTREGA,0) = 1
          AND    COALESCE(HTX.ENTREGADO,0) = 1
	       AND    COALESCE(HTX.APLICADO,0)    = 0
	       AND    COALESCE(HTX.ANULADA,0) = 0
	       AND    COALESCE (HTX.CLASEANULA,'') = ''
	       AND    COALESCE (HTX.ANULADA,0) = 0
	       AND    COALESCE(HTX.CLASEHTX,'') <> 'NA' 
	       AND    COALESCE(HTX.INDDEV,0) <> 1
          AND    COALESCE(HTX.ESTADO,'') = 'S'
          AND    COALESCE(HTX.CANTIDADINV,0) > 0 
          AND    HTX.FECHAREQ <= @FECHACORTE+1) > 0
	   BEGIN
	      INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, 'Existen Items de La Hoja de Tratamiento Suspendidos Traidos del Inventarios Sin Devolver .'
	   END    
	END
	
   /*Revisar Que Los q se configuren como Req el Proveedor lo tengan*/
   IF DBO.FNK_VALORVARIABLE('FTR_VALPROVEEDORES') = 'SI'
	BEGIN
	   IF (SELECT COALESCE(COUNT(*),0) 
	       FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
	                    INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
	       WHERE  NOADMISION = @NOADMISION
	       AND    COALESCE(ENCARGOS,0)           = 0
	       AND    COALESCE(HPRED.IDPROVEEDOR,'') = ''
	       AND    COALESCE(SER.MPROVEEDOR,0)     = 1  
          AND    HPRE.FECHA <= @FECHACORTE+1) > 0
	   BEGIN
         INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, 'Prestacion no.:'+ HPRED.NOPRESTACION+' Item:'+CAST(HPRED.NOITEM AS VARCHAR(5))+'. NO Tiene Proveedor.'
         FROM   HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION
	                    INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
	      WHERE  NOADMISION = @NOADMISION
	      AND    COALESCE(ENCARGOS,0)           = 0
	      AND    COALESCE(HPRED.IDPROVEEDOR,'') = ''
	      AND    COALESCE(SER.MPROVEEDOR,0)     = 1  
         AND    HPRE.FECHA <= @FECHACORTE + 1
      END
	END
	/*VALIDAMOS FORMATO JUSTIFICAION NO POS*/
	IF ( SELECT DBO.FNK_VALORVARIABLE('UTILIZACTC') ) = 'SI' AND @USACTC = 1
	BEGIN
	   IF ( SELECT COALESCE(COUNT(*),0) FROM HJNOPOS WHERE NOADMISION = @NOADMISION AND ESTADO <> 'Aceptado' ) > 0
	   BEGIN
         INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, LEFT('Justificaci?n NO POS Sin Estado Aceptado No.'+ HJNOPOS.CNSHJNOPOS +' Servicio:'+ HJNOPOS.IDSERVICIO,150)
       
		   FROM   HJNOPOS iNNER jOIN HCA on HCA.CONSECUTIVO=HJNOPOS.CONSECUTIVOHCA
	      WHERE  HJNOPOS.NOADMISION = @NOADMISION
	      AND    ESTADO    <> 'Aceptado'
		  and hca.FECHA <= @FECHACORTE + 1
	   END
	END
	/*VALIDAMOS SI EXISTEN FORMULAS MEDICAS QUE PERMITEN DAR LOS MEDICAMENTOS EN ALTA QUE NO SE HALLAN CARGADO*/
	IF (SELECT COALESCE(PPT.MEDROGAALTA,0) 
       FROM   PPT INNER JOIN HADM ON PPT.IDTERCERO = HADM.IDTERCERO 
                                 AND PPT.IDPLAN    = HADM.IDPLAN
       WHERE  HADM.NOADMISION = @NOADMISION ) = 1
   BEGIN
      IF (SELECT COALESCE(COUNT(*),0) 
          FROM   FME 
          WHERE  PROCEDENCIA = 'QX' 
          AND    NOADMISION = @NOADMISION 
          AND    COALESCE(PEDIDOINV,0)  = 0) > 0  
      BEGIN    
         INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, LEFT('Formulas M?dicas: Orden Sin Pedir a Farmacia y Permite Dar Droga de Alta'+ FME.NOCONSECUTIVO ,150)
         FROM   FME INNER JOIN FMED ON FME.NOCONSECUTIVO = FMED.NOCONSECUTIVO
                     LEFT JOIN SER ON FMED.IDSERVICIO = SER.IDSERVICIO
                     LEFT JOIN PRE ON SER.PREFIJO = PRE.PREFIJO
         WHERE  PROCEDENCIA = 'QX' 
         AND    NOADMISION = @NOADMISION 
         AND    COALESCE(PEDIDOINV,0)  = 0                  
         AND    PRE.MINVENTARIOS = 1
      END
      IF (SELECT COALESCE(COUNT(*),0) 
          FROM   FME 
          WHERE  PROCEDENCIA = 'QX' 
          AND    NOADMISION = @NOADMISION 
          AND    COALESCE(PEDIDOINV,0)  = 1
          AND    COALESCE(ENCARGOS,0)   = 0) > 0  
      BEGIN    
         INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, LEFT('Formulas M?dicas: Sin Cargar'+ FME.NOCONSECUTIVO ,150)
         FROM   FME 
         WHERE  PROCEDENCIA = 'QX' 
         AND    NOADMISION = @NOADMISION 
         AND    COALESCE(PEDIDOINV,0)  = 1
         AND    COALESCE(ENCARGOS,0)   = 0
      END      
   END    
	/*
	IF @IDTERCERO <> @IDTERCEROAT
   BEGIN
      INSERT INTO RPDX (CNS, NOMBRE)
      SELECT @RPDX, 'EL TERCERO DEL ACCIDENTE DE TRANSITO NO CORRESPONDE AL TERCERO DE LA ADMISION.'
   END
   */
   
   /* JEDM   08.07.2011  VERIFICACION QUE A LOS PROVEEDORES NO VAYAN A LLEGARLE FXP Y FXPD SIN VALORES */   
SELECT @CONTAR=COUNT(HPRE.PREFIJO)
   FROM   HPRED,SER,HPRE,PXS    
   WHERE  HPRE.NOADMISION   = @NOADMISION 
   AND    SER.IDSERVICIO    = HPRED.IDSERVICIO   
   AND    HPRE.NOPRESTACION = HPRED.NOPRESTACION   
   AND    HPRED.IDPROVEEDOR IS NOT NULL   
   AND    HPRED.IDPROVEEDOR <> ''   
   AND    ISNULL(HPRE.ANULADO,0)  = 0 --SJUNCO REQ 1803
   AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
   AND    HPRED.IDPROVEEDOR <> DBO.FNK_VALORVARIABLE('IDTERCEROINSTALADO')
   AND    COALESCE(HPRED.NOCOBRABLE,0)=0 
   AND    HPRED.IDPROVEEDOR=PXS.IDTERCERO
   AND    HPRE.IDTERCEROCA=PXS.IDADMINISTRADORA
   AND    HPRE.IDPLAN=PXS.IDPLAN
   AND    HPRE.PREFIJO=PXS.PREFIJO  
   GROUP BY HPRED.IDPROVEEDOR
   ORDER BY HPRED.IDPROVEEDOR  

   PRINT '4'
   
   IF (@CONTAR) < 1
   BEGIN
      INSERT INTO RPDX (CNS, NOMBRE)
      SELECT @RPDX, LEFT('NO tiene configuracion de valor a pagar al Proveedor:'+IDPROVEEDOR+'-Para el Servicio:'+IDSERVICIO+
                         '- Contratante:'+HPRE.IDTERCEROCA+' -noprestacion:'+HPRE.NOPRESTACION ,150)
      FROM   HPRED INNER JOIN HPRE ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
      WHERE  NOADMISION= @NOADMISION 
   END
   
   IF DBO.FNK_VALORVARIABLE('MODOCOBROAPOYODX') = 'ENAPOYODX'
	BEGIN
	   IF  DBO.FNK_VALORVARIABLE('APDX_REVISASINTRAER') = 'SI'
	   BEGIN
	      IF (  SELECT COALESCE(COUNT(*),0) 
	            FROM   HPRED INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
	                         INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION                      
	            WHERE  COALESCE(SER.AMBITO,'') <> ''
	            AND    HPRE.NOADMISION = @NOADMISION
	            AND    HPRED.ENCARGOS = 2
               AND    COALESCE(HPRED.NOCOBRABLE, 0) <> 1 --JFRANCO 22/05/2015
               AND    HPRE.FECHA <= @FECHACORTE +1 
   	         
	          ) > 0
	      BEGIN
	         INSERT INTO RPDX (CNS, NOMBRE)
            SELECT @RPDX, LEFT('EXISTEN ORDENES EN APOYO DIAGNOSTICO SIN TRAER',150)
	      END
	   END
	   IF DBO.FNK_VALORVARIABLE('VALIDAR_APOYODX') = 'SI'
	   BEGIN
	      IF (  SELECT COALESCE(COUNT(*),0) 
	            FROM   HPRED INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
	                         INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION                      
	                         -- INNER JOIN LORD ON HPRED.NORDEN       = LORD.NORDEN
	                         --                AND HPRED.IDSERVICIO   = LORD.IDSERVICIO
	            WHERE  COALESCE(SER.AMBITO,'') <> ''
	            AND    HPRE.NOADMISION = @NOADMISION
	            AND    HPRED.ENCARGOS  = 1
	            --AND    LORD.REALIZADO  = 1
               AND    COALESCE(HPRED.NOCOBRABLE, 0) <> 1 --JFRANCO 22/05/2015
               AND    HPRE.FECHA <= @FECHACORTE + 1
	          ) > 0
	      BEGIN
	         INSERT INTO RPDX (CNS, NOMBRE)
            SELECT @RPDX, LEFT('No Prestaci?n:'+HPRED.NOPRESTACION+'//No Item:'+CONVERT (VARCHAR,HPRED.NOITEM)+'//EXISTEN ORDENES EN APOYO DIAGNOSTICO TRAIDAS SIN CERRAR',150)	         
            FROM    HPRED INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO
                          INNER JOIN HPRE ON HPRED.NOPRESTACION = HPRE.NOPRESTACION                      
	                         -- INNER JOIN LORD ON HPRED.NORDEN       = LORD.NORDEN
	                         --                AND HPRED.IDSERVICIO   = LORD.IDSERVICIO
            WHERE  COALESCE(SER.AMBITO,'') <> ''
            AND    HPRE.NOADMISION = @NOADMISION
            AND    HPRED.ENCARGOS  = 1
            AND    COALESCE(HPRED.NOCOBRABLE, 0) <> 1 --JFRANCO 22/05/2015
            AND    HPRE.FECHA <= @FECHACORTE + 1
	      END   
	   END   
   END
   
   --VALIDACION DE PERIODO CERRADO EN CARTERA 
 --  IF (SELECT DATEPART(DAY,GETDATE())) >5
	--BEGIN 
	--    PRINT 'VALIDANDO QUE ESTE CERRADO EL PERIODO DIA MAYOR DE 5 '
	--    IF ( SELECT COALESCE(CERRADO_CARTERA ,0)
	--         FROM PRI 
	--         WHERE ANO = CASE  DATEPART(MONTH,GETDATE())
	--                       WHEN 12 THEN DATEPART(YEAR,GETDATE())-1 ELSE DATEPART(YEAR,GETDATE()) 
	--                     END
	--           AND MES = CASE  DATEPART(MONTH,GETDATE()) 
	--                       WHEN 1 THEN 12 ELSE DATEPART(MONTH,GETDATE())-1
	--                     END 
	--       )<>1
	--    BEGIN 
	--        INSERT INTO RPDX ( CNS, NOMBRE ) 
 --          SELECT @RPDX, 'NO SE HA CERRADO EL PERIODO EN CARTERA DEL MES ANTERIOR'
	--    END 
	--END
   IF DBO.FNK_VALORVARIABLE('VALESTADOHAUT')='SI'
   BEGIN
      PRINT 'REVISO LAS SOLICITUDES DE AUTORIZACION '
      IF (SELECT COUNT(*) FROM HAUT WHERE NOADMISION=@NOADMISION AND ESTADO='PENDIENTE')>0
      BEGIN
	      INSERT INTO RPDX (CNS, NOMBRE)
         SELECT @RPDX, LEFT('EXISTEN SOLICITUD DE AUTORIZACIONES SIN DEFINIR, COMUNIQUESE CON EL AREA ENCARGADA DE AUTORIZACION DE SERVICIOS',150)      
      
           INSERT INTO RPDX (CNS, NOMBRE)
           SELECT  @RPDX, 'CNSHAUT: '+CNSHAUT+' TIPO: '+COALESCE(TIPO,'SIN DEFINI')+' CLASE: '+COALESCE(CLASE,'SIN DEFINIR')+' FECHASOLICITUD: '+COALESCE(DBO.FNK_FECHA(FECHA),'SIN DEFINIR') 
           FROM HAUT WHERE ESTADO='PENDIENTE' AND NOADMISION=@NOADMISION     
      END
   END
END

