IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_RELIQUIDAR_HADM' AND type = 'P')
   DROP PROCEDURE SPK_RELIQUIDAR_HADM

GO
CREATE PROC DBO.SPK_RELIQUIDAR_HADM
	@NOADMISION   VARCHAR(20),
	@CUBRIMIENTO  BIT=0,
	@TCONTRA	  BIT=0,
	@PREFIJOS     VARCHAR(100)='',
	@IDAREA		  VARCHAR(20)='' 
WITH ENCRYPTION
AS
/* 
Fecha:		 2018-11-10
Descripci?: Procedimiento que reliquidaruna admisi? y enviara copago solo lo necesario
*/
--SET NOCOUNT ON
DECLARE 
	@NOPRESTACION	 VARCHAR(16),
	@NOITEM			 SMALLINT,
	@MAREA			 SMALLINT,
	@NUMNC			 SMALLINT,
	@TIPO			 VARCHAR(1),
	@Q				 DECIMAL(18,6),
	@IDSERVICIO		 VARCHAR(20),
	@IDTERCERO		 VARCHAR(20),
	@IDPLAN			 VARCHAR(20),
	@PCUBRIMIENTO	 DECIMAL(7,2),
	@COPAGONOAUT	 VARCHAR(20),
	@NIVELSOCIOEC	 VARCHAR(2),
	@IDAFILIADO		 VARCHAR(20),
	@FNACIMIENTO	 DATETIME,
	@PYP			 SMALLINT,
	@CLASIFPC		 VARCHAR(5),
	@TIPOAFILIADO	 VARCHAR(12),
	@COPAGO			 DECIMAL(14,2),
	@COPAGO_ANEXO6   DECIMAL(14,2),
	@TIPOADM		 VARCHAR(2),
	@CNSHACTRAN		 VARCHAR(20),
	@PAQUETE		 BIT,
	@TOTAL			 BIGINT,
	@FIX			 INT, 
	@FIX_TO			 INT,
	@FIX2			 INT, 
	@FIX_TO2		 INT,
	@TIPOURG         INT,
	@MANCOPAGOEXT    SMALLINT,
	@COPAGO_HADM_EXT DECIMAL(14,2),
	@COPAGO_EXT      DECIMAL(14,2),
	@SINCERRARCONVALOR VARCHAR(20)
DECLARE @HPRED	TABLE (ID INT IDENTITY(1,1), NOPRESTACION VARCHAR(20), NOITEM INT, IDSERVICIO VARCHAR(20), CERRADA INT, IDSEDE VARCHAR(5), 
						IDAREA VARCHAR(20), CCOSTO VARCHAR(20), PREFIJO VARCHAR(6), ENCARGOS INT, NIVEL VARCHAR(5))
DECLARE @NOCOB  TABLE (IDSERVICIO VARCHAR(20), MAREA INT, CANTIDAD SMALLINT, TIPO VARCHAR(1)) 
BEGIN
	SELECT @SINCERRARCONVALOR=DATO FROM USVGS WHERE IDVARIABLE='SINCERRARCONVALOR'

	SELECT @IDTERCERO=IDTERCERO, @IDPLAN=IDPLAN, @PCUBRIMIENTO=PCUBRIMIENTO, @COPAGONOAUT=COPAGONOAUTORIZACION, @NIVELSOCIOEC=NIVELSOCIOEC, 
		@PYP=PYP, @IDAFILIADO=IDAFILIADO, @COPAGO_ANEXO6=ISNULL(TOPECOPAGO_ANX6,0), @TIPOADM=TIPOADM, @CNSHACTRAN=CNSHACTRAN, @PAQUETE=ISNULL(PAQUETE,0),
		@MANCOPAGOEXT=ISNULL(MANCOPAGOEXT,0), @COPAGO_HADM_EXT=ISNULL(VLR_COPAGOEXTERNO,0), @TIPOAFILIADO=TIPOAFILIADO
	FROM HADM WHERE NOADMISION=@NOADMISION

	SELECT @TIPOURG=CASE WHEN TIPOATENCION='U' THEN 1 ELSE 0 END  FROM HTAD WHERE TIPOADM= @TIPOADM

	SELECT @FNACIMIENTO=FNACIMIENTO, @CLASIFPC=CLASIFPC, @TIPOAFILIADO=CASE ISNULL(@TIPOAFILIADO,'') WHEN '' THEN TIPOAFILIADO ELSE @TIPOAFILIADO END
	FROM AFI WHERE IDAFILIADO=@IDAFILIADO

	SET @TIPOAFILIADO = CASE @TIPOAFILIADO WHEN 'C' THEN 'Cotizante' WHEN 'B' THEN 'Beneficiario' WHEN 'A' THEN 'Adicional' END

	IF EXISTS(SELECT * FROM HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION 
				WHERE HPRE.NOADMISION=@NOADMISION AND ( HPRE.IDTERCEROCA<>HPRED.IDTERCEROCA OR HPRE.IDPLAN<>HPRED.IDPLAN))
	BEGIN 
	PRINT 'CORREGIMOS PRESTACIONES QUE NO CONCUERDAN CON CONTRATANTE'
		UPDATE HPRED SET IDTERCEROCA=HPRE.IDTERCEROCA, IDPLAN=HPRE.IDPLAN FROM  HPRE INNER JOIN HPRED ON HPRED.NOPRESTACION=HPRE.NOPRESTACION 
		WHERE HPRE.NOADMISION=@NOADMISION AND ( HPRE.IDTERCEROCA<>HPRED.IDTERCEROCA OR HPRE.IDPLAN<>HPRED.IDPLAN)
				AND HPRE.PREFIJO<>DBO.FNK_VALORVARIABLE( 'IDCIRPREFIJO')

	END 

	UPDATE HPRED SET CCOSTO=HPRE.CCOSTO, IDAREA=HPRE.IDAREA
	FROM HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
	WHERE HPRE.NOADMISION=@NOADMISION AND UPPER(ISNULL(HPRE.CIRUGIA,''))<>'SI' AND COALESCE(HPRED.FACTURADA,0)=0
		AND HPRE.CCOSTO<>HPRED.CCOSTO

	INSERT INTO @HPRED (NOPRESTACION, NOITEM, IDSERVICIO, CERRADA, IDSEDE, IDAREA, CCOSTO, PREFIJO, ENCARGOS, NIVEL)
	SELECT HPRED.NOPRESTACION, HPRED.NOITEM, HPRED.IDSERVICIO, COALESCE(HPRE.CERRADA,0), HPRE.IDSEDE, CEN.IDAREA, CEN.CCOSTO, 
		SER.PREFIJO, COALESCE(ENCARGOS,0), SER.NIVELATENCION
	FROM HPRED
		INNER JOIN HPRE ON HPRE.NOPRESTACION=HPRED.NOPRESTACION 
		INNER JOIN CEN  ON CEN.CCOSTO=COALESCE(HPRED.CCOSTO,HPRE.CCOSTO)
		INNER JOIN SER  ON SER.IDSERVICIO=HPRED.IDSERVICIO
	WHERE HPRE.NOADMISION=@NOADMISION AND UPPER(ISNULL(HPRE.CIRUGIA,''))<>'SI' AND COALESCE(HPRED.FACTURADA,0)=0

	IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='IDCON_CONTAB_X_HPRE') = 'HPRE'
		DELETE @HPRED WHERE CERRADA=1

	IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='MSEDETERCERO') = 'SI'
		DELETE @HPRED WHERE IDSEDE NOT IN (SELECT IDSEDE FROM SED WHERE COALESCE(TERCERIZADA,0)=0)

	IF @IDAREA <> ''
		DELETE @HPRED WHERE IDAREA NOT IN (SELECT WORD FROM DBO.FNK_EXPLODE(@IDAREA,''))

	IF @PREFIJOS <> ''
		DELETE @HPRED WHERE PREFIJO IN (SELECT WORD FROM DBO.FNK_EXPLODE(@PREFIJOS,''))
		
	UPDATE HPRED SET VALORCOPAGO=0, VALOREXCEDENTE=0, VALORPCOMP=0, VALORCOPAGONORMAL=0, VALORCOPAGOEXTERNO=0
	FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
		AND COALESCE([MANUAL],0)=0

	UPDATE HPRED SET VALOR=0
	FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
		AND COALESCE([MANUAL],0)=0

	UPDATE HPRE SET VALORCOPAGO=0, VALORTOTAL=0, VALOREXEDENTE=0, VALORPCOMP=0
	FROM HPRE WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRE.NOPRESTACION=A.NOPRESTACION)

	--Modifico las prestaciones al tercero de la admisi?
	IF @TCONTRA=1
	BEGIN
		UPDATE HPRED SET COBRARA='C', IDTERCEROCA=@IDTERCERO, IDPLAN=@IDPLAN
		FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)

		UPDATE HPRE SET COBRARA='C', IDTERCEROCA=@IDTERCERO, IDPLAN=@IDPLAN
		FROM HPRE WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRE.NOPRESTACION=A.NOPRESTACION)

		UPDATE LING SET IDTERCERO=@IDTERCERO, IDPLAN=@IDPLAN FROM LING WHERE EXISTS  (SELECT 1 FROM @HPRED A WHERE LING.NOPRESTACION=A.NOPRESTACION)
	END
	
	IF @CUBRIMIENTO = 1
	BEGIN
		UPDATE HPRED SET PCUBRIMIENTO=@PCUBRIMIENTO
		FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)

		UPDATE HPRE SET PCUBRIMIENTO=@PCUBRIMIENTO
		FROM HPRE WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRE.NOPRESTACION=A.NOPRESTACION)
	END

	--Acumulaci? de no cobrables
	DELETE FROM USACU WHERE IDACUMULADOR='QXNOCOBRABLE' AND ID1=@NOADMISION
	
	INSERT INTO USACU (IDACUMULADOR, ID1, ID2, ID3, ID4, ID5, Q1, Q2, Q3, Q4, Q5, V1, V2, V3, V4, V5)
	SELECT 'QXNOCOBRABLE', @NOADMISION, HPRED.IDSERVICIO, 
		CASE MAX(PPTD.MAREA) WHEN 1 THEN HPRE.IDAREA ELSE 'NA' END, 'NA', 'NA', 
		PPTD.CANTNOCOBRABLE, SUM(HPRED.CANTIDAD), 0, 0, 0, 0, 0, 0, 0, 0
	FROM HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
		INNER JOIN PPTD ON PPTD.IDTERCERO=HPRE.IDTERCEROCA AND PPTD.IDPLAN=HPRE.IDPLAN AND HPRED.IDSERVICIO=PPTD.IDSERVICIO 
		AND  HPRE.IDAREA=CASE WHEN COALESCE(PPTD.MAREA,0)=1 THEN  PPTD.IDAREA ELSE HPRE.IDAREA END 
	WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
	GROUP BY HPRED.IDSERVICIO, HPRE.IDAREA, HPRED.IDSERVICIO, PPTD.CANTNOCOBRABLE

	
	DECLARE @USACU TABLE (ID INT IDENTITY(1,1), NOPRESTACION VARCHAR(20), NOITEM INT, IDAREA VARCHAR(20), MAREA SMALLINT, 
								CANTNOCOBRABLE SMALLINT, TIPOCOBRABLE VARCHAR(1), CANTIDAD DECIMAL(18,6), IDSERVICIO VARCHAR(20))
	INSERT INTO @USACU (NOPRESTACION, NOITEM, IDAREA, MAREA, CANTNOCOBRABLE, TIPOCOBRABLE, CANTIDAD, IDSERVICIO)
	SELECT HPRED.NOPRESTACION, HPRED.NOITEM, HPRE.IDAREA, PPTD.MAREA, PPTD.CANTNOCOBRABLE, PPTD.TIPOCOBRABLE,
			HPRED.CANTIDAD, HPRED.IDSERVICIO
	FROM HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
		INNER JOIN PPTD ON PPTD.IDTERCERO=HPRED.IDTERCEROCA AND PPTD.IDPLAN=HPRE.IDPLAN AND HPRED.IDSERVICIO=PPTD.IDSERVICIO
		AND  HPRE.IDAREA=CASE WHEN COALESCE(PPTD.MAREA,0)=1 THEN  PPTD.IDAREA ELSE HPRE.IDAREA END 
	WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)

	SELECT @FIX=1, @FIX_TO=COUNT(1) FROM @USACU
	WHILE @FIX <= @FIX_TO 
	BEGIN
		SELECT @NOPRESTACION=NOPRESTACION, @NOITEM=NOITEM, @IDAREA=IDAREA, @MAREA=MAREA, @NUMNC=CANTNOCOBRABLE, @TIPO=TIPOCOBRABLE, @Q=CANTIDAD, @IDSERVICIO=IDSERVICIO  
		FROM @USACU WHERE ID=@FIX

		UPDATE USACU SET Q2 = Q2 + @Q 
		WHERE  IDACUMULADOR = 'QXNOCOBRABLE'
		AND    ID1          = @NOADMISION
		AND    ID2          = @IDSERVICIO 
		AND    ID3          = CASE @MAREA WHEN 1 THEN @IDAREA ELSE 'NA' END
		AND    ID4          = 'NA'
		AND    ID5          = 'NA'
        
		UPDATE HPRED SET NOCOBRABLE=1 WHERE NOPRESTACION=@NOPRESTACION AND NOITEM=@NOITEM

		SET @FIX += 1
	END


	
	PRINT 'Precio de costo a articulos'
	UPDATE HPRED SET PCOSTO=IART.PCOSTO
	FROM HPRED 
		INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO AND SER.IDARTICULO<>(SELECT DATO FROM USVGS WHERE IDVARIABLE='IDINVARTNA')
		INNER JOIN IART ON SER.IDARTICULO=IART.IDARTICULO
	WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
		AND COALESCE(HPRED.PCOSTO,0)=0 

	PRINT 'Capturo valores de servicios'
	UPDATE HPRED SET VALOR = DBO.FNK_VLR_SERVICIO(HPRED.IDTERCEROCA, HPRED.IDSERVICIO, HPRED.IDPLAN, COALESCE(HPRED.IDAREA,HPRE.IDAREA), HPRE.FECHA)
	FROM HPRED INNER JOIN HPRE ON HPRED.NOPRESTACION=HPRE.NOPRESTACION
	WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
		AND COALESCE(HPRED.NOCOBRABLE,0)=0 AND (COALESCE(HPRED.ENCARGOS,0)=0 OR COALESCE(HPRED.ENCARGOS,0)=(CASE @SINCERRARCONVALOR WHEN 'SI' THEN 1 ELSE 0 END))
		AND COALESCE([MANUAL],0)=0

	PRINT 'Descuento a la prestacion'
	UPDATE HPRED SET HPRED.VALOR = CASE HPRED.TIPODTO WHEN 'V' THEN VALOR-COALESCE(DESCUENTO,0) WHEN 'P' THEN VALOR*(1-(COALESCE(DESCUENTO,0)/100)) ELSE VALOR END
	FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
	AND COALESCE(DESCUENTO,0)<>0
	
	
	DECLARE @COPAGO_ADM DECIMAL(14,2), @EXTERNO DECIMAL(14,2)
	SELECT @COPAGO_ADM=SUM(COALESCE(VALORCOPAGO,0)), @COPAGO_EXT=SUM(COALESCE(VALORCOPAGOEXTERNO,0))
	FROM HPRED WHERE EXISTS (SELECT 1 FROM HPRE WHERE HPRE.NOPRESTACION=HPRED.NOPRESTACION AND HPRE.NOADMISION=@NOADMISION)

	IF @COPAGO_EXT < @COPAGO_HADM_EXT
		SET @COPAGO_EXT = COALESCE(@COPAGO_HADM_EXT - @COPAGO_EXT,0)

	PRINT 'Reliquidaci? de copago'
	IF @COPAGONOAUT <> ''
	BEGIN
		PRINT 'VOY A SPK_COPAGOHAQX CON @COPAGONOAUTORIZACION='+@COPAGONOAUT
		EXEC SPK_COPAGOHAQX @NOADMISION
	END
	ELSE
	BEGIN
		DECLARE @COPAG	TABLE (ID INT IDENTITY(1,1), NOPRESTACION VARCHAR(20), NOITEM INT, IDMODELOPC VARCHAR(5), COPAGO DECIMAL(14,2), COMPARTIDO DECIMAL(14,2), EXTERNO DECIMAL(14,2))
		INSERT INTO @COPAG (NOPRESTACION, NOITEM, IDMODELOPC, COPAGO, COMPARTIDO, EXTERNO)
		SELECT A.NOPRESTACION, A.NOITEM, MOC.IDMODELOPC, 0, 0, 0
		FROM @HPRED A 
			INNER JOIN HPRED ON HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM AND COALESCE(HPRED.NOCOBRABLE,0)<>1
			INNER JOIN HPRE  ON HPRE.NOPRESTACION=HPRED.NOPRESTACION
			INNER JOIN PPT   ON PPT.IDTERCERO=HPRED.IDTERCEROCA AND PPT.IDPLAN=HPRED.IDPLAN
			INNER JOIN MOC   ON PPT.IDMODELOPCH=MOC.IDMODELOPC
			INNER JOIN MOCP  ON MOC.IDMODELOPC=MOCP.IDMODELOPC AND MOC.TIPODEPAGO=MOCP.TIPODEPAGO AND A.PREFIJO=MOCP.PREFIJO AND A.NIVEL=MOCP.NIVELATENCION
			INNER JOIN MOCC  ON MOC.IDMODELOPC=MOCC.IDMODELOPC AND MOC.TIPODEPAGO=MOCC.TIPODEPAGO
			INNER JOIN CEN   ON CEN.CCOSTO=A.CCOSTO
			INNER JOIN AFU   ON AFU.IDAREA=CEN.IDAREA
			INNER JOIN MOCCD ON MOCCD.IDMODELOPC=MOC.IDMODELOPC AND MOCCD.TIPODEPAGO=MOC.TIPODEPAGO and MOCCD.ESCALASE=@NIVELSOCIOEC
			LEFT  JOIN MOCA  ON MOCA.IDMODELOPC=MOC.IDMODELOPC AND MOCA.IDAREA=AFU.IDAREA AND MOCA.IDAREAH=AFU.IDAREAH
		WHERE (A.ENCARGOS=0 OR COALESCE(HPRED.ENCARGOS,0)=(CASE @SINCERRARCONVALOR WHEN 'SI' THEN 1 ELSE 0 END))
			AND (ISNULL(CEN.GALTOCOSTO_QX,'')=CASE MOCC.EXALTOCOSTO WHEN 1 THEN 'No' ELSE ISNULL(CEN.GALTOCOSTO_QX,'') END OR ISNULL(CEN.GALTOCOSTO_QX,'')='') --Si excluye alto costo
			AND 1=CASE MOCC.EXURGENCIA WHEN 1 THEN (CASE  WHEN COALESCE(AFU.CE,0)=2 AND @TIPOURG=1 THEN 0 ELSE 1 END) ELSE 1 END --Si excluye urgencia-- mas tipo ingreso urgencia
			AND 1=CASE WHEN MOCC.EXPYP=1 AND @PYP=1 THEN 0 ELSE 1 END --Si excluye pyp
			AND 1=CASE WHEN MOCC.EXAREAS=1 AND MOCA.IDAREA IS NOT NULL THEN 0 ELSE 1 END --Si excluye areas
			AND DATEDIFF(MONTH,@FNACIMIENTO,HPRE.FECHA) >= COALESCE(MOCC.EXEDAD,0) --Excluye menores de x meses
			AND 1=CASE WHEN MOCC.COBRARCOPA='Ambos' OR MOCC.COBRARCOPA=@TIPOAFILIADO THEN 1 ELSE 0 END --Tipo de afiliado a cobrar
			AND COALESCE(HPRED.PAQUETE,0)=@PAQUETE
		ORDER BY HPRE.FECHA, HPRED.NOITEM

		SELECT @TOTAL=COUNT(1) FROM @COPAG
		PRINT CONVERT(VARCHAR,@TOTAL)+' prestaciones a generar copago'
		
		DECLARE @PPT TABLE (ID INT IDENTITY(1,1), IDMODELOPC VARCHAR(5), FORMACOBRO VARCHAR(10), REDONDEO VARCHAR(10), VALOR DECIMAL(14,2), VALOR_MAX DECIMAL(14,2)) 
		DECLARE @IDMODELOPC VARCHAR(5), @FORMACOBRO VARCHAR(10), @REDONDEO VARCHAR(10), @VALOR DECIMAL(14,2), @VALOR_MAX DECIMAL(14,2)
		INSERT INTO @PPT (IDMODELOPC, FORMACOBRO, REDONDEO, VALOR, VALOR_MAX)
		SELECT DISTINCT A.IDMODELOPC, MOCC.FORMACOBRO, MOCC.REDONDEO, MOCCD.VALOR, MOCCD.VALORMAXIMO
		FROM @COPAG A 
			INNER JOIN MOC ON A.IDMODELOPC=MOC.IDMODELOPC
			INNER JOIN MOCC  ON MOC.IDMODELOPC=MOCC.IDMODELOPC AND MOC.TIPODEPAGO=MOCC.TIPODEPAGO
			INNER JOIN MOCCD ON MOCCD.IDMODELOPC=MOC.IDMODELOPC AND MOCCD.TIPODEPAGO=MOC.TIPODEPAGO and MOCCD.ESCALASE=@NIVELSOCIOEC

		SELECT @FIX =1, @FIX_TO =COUNT(1) FROM @COPAG
		SELECT @FIX2=1, @FIX_TO2=COUNT(1) FROM @PPT
		WHILE @FIX2 <= @FIX_TO2
		BEGIN
			SELECT @IDMODELOPC=IDMODELOPC, @FORMACOBRO=FORMACOBRO, @REDONDEO=REDONDEO, @VALOR=VALOR, @VALOR_MAX=VALOR_MAX FROM @PPT WHERE ID=@FIX
			PRINT 'Copago con modelo='+@IDMODELOPC+', valor='+CONVERT(VARCHAR,@VALOR)+', TOPE='+CONVERT(VARCHAR,@VALOR_MAX)

			IF @COPAGO_ANEXO6 > 0
			BEGIN
				SET @VALOR_MAX = @COPAGO_ANEXO6
				PRINT 'Manejo tope de copago por anexo 6 en la admisi? de '+CONVERT(VARCHAR,@VALOR_MAX)
			END
            
			IF @MANCOPAGOEXT = 1
			BEGIN
				PRINT 'Maneja copago externo restante por valor de '+CONVERT(VARCHAR,@COPAGO_EXT)+', Tope interno='+CONVERT(VARCHAR,@VALOR_MAX-@COPAGO_EXT)
			END
            
			IF @PCUBRIMIENTO < 100
			BEGIN
				UPDATE A SET COMPARTIDO=ROUND(((HPRED.CANTIDAD*HPRED.VALOR) * ((100-@PCUBRIMIENTO)/100)),(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END ))
				FROM @COPAG A INNER JOIN HPRED ON HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM
			END

			UPDATE A SET COPAGO=CASE @FORMACOBRO 
				WHEN 'Porcentaje' THEN ROUND(((HPRED.CANTIDAD*HPRED.VALOR) - HPRED.VALORPCOMP) * (@VALOR/100),(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END ))
				WHEN 'Valor' THEN @VALOR END
			FROM @COPAG A INNER JOIN HPRED ON HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM

			WHILE @FIX <= @FIX_TO
			BEGIN
				SELECT @COPAGO=COPAGO, @EXTERNO=0 FROM @COPAG WHERE ID=@FIX

				IF @MANCOPAGOEXT=1 AND @COPAGO_EXT>0 AND @COPAGO>0
				BEGIN
					IF @COPAGO <= @COPAGO_EXT
						SET @EXTERNO=@COPAGO
					ELSE
						SET @EXTERNO=@COPAGO_EXT

					SET @COPAGO_EXT -= @EXTERNO
                    
					UPDATE @COPAG SET EXTERNO=@EXTERNO, COPAGO=(CASE WHEN @COPAGO=@EXTERNO THEN 0 ELSE @COPAGO-@EXTERNO END) 
					WHERE ID=@FIX
				END

				IF (@VALOR_MAX >= @COPAGO_ADM + @COPAGO) OR @VALOR_MAX=0
				BEGIN
					--PRINT '1. @COPAGO_ADM '+CONVERT(VARCHAR,@COPAGO_ADM)+' @COPAGO '+CONVERT(VARCHAR,@COPAGO)
					--SET @COPAGO_ADM += (@COPAGO-@EXTERNO)
					SET @COPAGO_ADM += @COPAGO
				END
				ELSE IF @VALOR_MAX > @COPAGO_ADM
				BEGIN
					--PRINT '2. @COPAGO_ADM '+CONVERT(VARCHAR,@COPAGO_ADM)+' @COPAGO '+CONVERT(VARCHAR,@VALOR_MAX-@COPAGO_ADM)
					UPDATE @COPAG SET COPAGO=@VALOR_MAX-@COPAGO_ADM-@EXTERNO WHERE ID=@FIX
					UPDATE @COPAG SET COPAGO=0 WHERE ID>@FIX
					SET @COPAGO_ADM = @VALOR_MAX
					SET @FIX = @FIX_TO
					SET @FIX2 = @FIX_TO2
				END
				ELSE
				BEGIN
					--PRINT '3. @COPAGO_ADM '+CONVERT(VARCHAR,@COPAGO_ADM)
					UPDATE @COPAG SET COPAGO=0 WHERE ID>=@FIX
					SET @FIX = @FIX_TO
					SET @FIX2 = @FIX_TO2
				END
				
				SET @FIX += 1
			END

			SET @FIX2 += 1
		END

		--UPDATE HPRED SET VALORCOPAGO=A.COPAGO, VALORCOPAGONORMAL=A.COPAGO-A.EXTERNO, VALORPCOMP=A.COMPARTIDO, VALORCOPAGOEXTERNO=A.EXTERNO
		UPDATE HPRED SET VALORCOPAGO=A.COPAGO+A.EXTERNO, VALORCOPAGONORMAL=A.COPAGO, VALORPCOMP=A.COMPARTIDO, VALORCOPAGOEXTERNO=A.EXTERNO
		FROM HPRED INNER JOIN @COPAG A ON HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM
		WHERE A.COPAGO>0 OR A.EXTERNO>0
	END 

   PRINT 'VOY A ACTUALIZAR HPRED @REDONDEO '+COALESCE(@REDONDEO ,'NO TENGO REDONDEO')

	--UPDATE HPRED SET VALOREXCEDENTE=ROUND(((VALOR*CANTIDAD)-VALORCOPAGO-VALORPCOMP),(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END ))
   UPDATE HPRED SET VALOR=ROUND(VALOR,(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END )),
                    VALORCOPAGO=ROUND(VALORCOPAGO,(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END ))
	FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION  AND HPRED.NOITEM=A.NOITEM)

   UPDATE HPRED SET VALOREXCEDENTE= ROUND(((VALOR*CANTIDAD)-VALORCOPAGO-VALORPCOMP),(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END ))
	FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION  AND HPRED.NOITEM=A.NOITEM)
  -- SELECT  * FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
   PRINT 'SALGO DE REDONDEO....'

	--IF( SELECT  COUNT(*) FROM HPRED 
	--	WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
	--	AND    COALESCE(HPRED.NOCOBRABLE,0) = 0
	--	AND    COALESCE(HPRED.FACTURADA,0) =0
	--	AND    COALESCE(HPRED.ANULADO,0)=0
	--	AND     ROUND((COALESCE(VALOREXCEDENTE,0)),(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END )) <> ROUND(((COALESCE(VALOR,0) * COALESCE(CANTIDAD,0)) - COALESCE(VALORCOPAGO,0) - COALESCE(VALORPCOMP,0)
	--										-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN COALESCE(VLRSERVICIOH,0) ELSE 0 END),(CASE @REDONDEO WHEN 'Unidad' THEN 0 WHEN 'Decena' THEN -1 WHEN 'Centena' THEN -2 WHEN 'Millar' THEN -3 ELSE 0 END )))>=1
	--	BEGIN 
 --        PRINT 'LAS COAS QUE PASAN'
	--			UPDATE HPRED SET  VALOR=  VALOR +
	--									CASE WHEN  CONVERT(DECIMAL(14,2),ROUND(((COALESCE(HPRED.VALOR,0) * COALESCE(HPRED.CANTIDAD,0)) - COALESCE(HPRED.VALORCOPAGO,0) - COALESCE(HPRED.VALORPCOMP,0)
	--																			-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN COALESCE(VLRSERVICIOH,0) ELSE 0 END),0) - ROUND(COALESCE(HPRED.VALOREXCEDENTE,0),0))<0 
	--										THEN ABS(CONVERT(DECIMAL(14,2),CONVERT(DECIMAL(14,2),ROUND(((COALESCE(HPRED.VALOR,0) * COALESCE(HPRED.CANTIDAD,0)) - COALESCE(HPRED.VALORCOPAGO,0) - COALESCE(HPRED.VALORPCOMP,0)
	--																			-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN COALESCE(HPRED.VLRSERVICIOH,0) ELSE 0 END),0)-ROUND(COALESCE(HPRED.VALOREXCEDENTE,0),0)))/HPRED.CANTIDAD)
											
	--										ELSE (CONVERT(DECIMAL(14,2),CONVERT(DECIMAL(14,2),ROUND(((COALESCE(HPRED.VALOR,0) * COALESCE(HPRED.CANTIDAD,0)) - COALESCE(HPRED.VALORCOPAGO,0) - COALESCE(HPRED.VALORPCOMP,0)
	--																			-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN COALESCE(HPRED.VLRSERVICIOH,0) ELSE 0 END),0)-ROUND(COALESCE(HPRED.VALOREXCEDENTE,0),0)))/HPRED.CANTIDAD)*-1 END 
	--									FROM HPRED 
	--			WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM)
	--			--HPRED.NOPRESTACION = @NOPRESTACION
	--			AND    COALESCE(HPRED.NOCOBRABLE,0) = 0
	--			AND    COALESCE(HPRED.FACTURADA,0) =0
	--			AND    COALESCE(HPRED.ANULADO,0)=0
	--			AND     ROUND((COALESCE(HPRED.VALOREXCEDENTE,0)),0) <> ROUND(((COALESCE(HPRED.VALOR,0) * COALESCE(HPRED.CANTIDAD,0)) - COALESCE(HPRED.VALORCOPAGO,0) - COALESCE(HPRED.VALORPCOMP,0)
	--												-CASE WHEN HPRED.NOLOTE='HOMOLOGO' THEN COALESCE(HPRED.VLRSERVICIOH,0) ELSE 0 END),0)

	--	END
   PRINT 'OTRO UPDATE'
	UPDATE HPRE SET VALORTOTAL=X.VALORTOTAL, VALOREXEDENTE=VALOREXCEDENTE, VALORCOPAGO=X.VALORCOPAGO, VALORPCOMP=X.VALORPCOMP
	FROM HPRE INNER JOIN (
			SELECT NOPRESTACION, VALORTOTAL=SUM(VALOR*CANTIDAD), VALOREXCEDENTE=SUM(VALOREXCEDENTE), VALORCOPAGO=SUM(VALORCOPAGO), VALORPCOMP=SUM(VALORPCOMP)
			FROM HPRED WHERE EXISTS (SELECT 1 FROM @HPRED A WHERE HPRED.NOPRESTACION=A.NOPRESTACION AND HPRED.NOITEM=A.NOITEM) GROUP BY NOPRESTACION
		)X ON HPRE.NOPRESTACION=X.NOPRESTACION
	WHERE NOADMISION=@NOADMISION

	IF @TIPOADM = (SELECT DATO FROM USVGS WHERE IDVARIABLE='IDTARIFASOAT')
		EXEC SPK_RELIQ_HACTRAN @CNSHACTRAN

	DECLARE @HOM TABLE (ID INT IDENTITY(1,1), NOPRESTACION VARCHAR(20), NOITEM INT)
	INSERT INTO @HOM (NOPRESTACION, NOITEM)
	SELECT NOPRESTACION, NOITEM 
	FROM @HPRED A WHERE EXISTS (SELECT 1 FROM HPRED WHERE A.NOPRESTACION=HPRED.NOPRESTACION AND A.NOITEM=HPRED.NOITEM AND COALESCE(NPRESTACIONH,'')<>'')
	SELECT @NOPRESTACION='', @NOITEM=0, @FIX=1, @FIX_TO=COUNT(1) FROM @HOM
	WHILE @FIX <= @FIX_TO
	BEGIN
      PRINT 'VOY POR ACA'
		SELECT @NOPRESTACION=NOPRESTACION, @NOITEM=NOITEM FROM @HOM WHERE ID=@FIX
		EXEC SPK_COPAGOQX @NOADMISION, @NOPRESTACION, @NOITEM 
		SET @FIX += 1
	END
END


