CREATE OR ALTER PROCEDURE DBO.SPQ_FNOT_COL @JSON NVARCHAR(MAX)
	WITH ENCRYPTION
AS
SET DATEFORMAT dmy
DECLARE @TBLERRORES TABLE (ERROR VARCHAR(MAX))
DECLARE  @PARAMETROS NVARCHAR(MAX)			,@MODELO VARCHAR(100)			   ,@METODO VARCHAR(100)
		,@USUARIO VARCHAR(12)				   ,@COMPANIA VARCHAR(2)		      ,@IDSEDE      VARCHAR(5)		
		,@SYS_COMPUTERNAME VARCHAR(200)     ,@DATOS    VARCHAR(MAX)
DECLARE @PROCESO VARCHAR(20)              ,@CNSFNOT VARCHAR(20)            ,@CLASE VARCHAR(20)
		,@N_FACTURA VARCHAR(20)            ,@F_NOTA VARCHAR(20)             ,@OBSERVACION VARCHAR(520)
		,@PROCEDENCIA VARCHAR(20)          ,@IDCONCEPTO VARCHAR(20)         ,@NIT VARCHAR(20)
		,@RAZONSOCIAL VARCHAR(120)         ,@DESCRIPCION VARCHAR(120)        ,@CONCEPTO BIT
		,@TIPOCONCEPTO VARCHAR(20)         ,@VALORCONCEPTO DECIMAL(14,2)      ,@SALDOFACTURA DECIMAL(14,2)
		,@VALOR DECIMAL(14,2)              ,@CNSCXC VARCHAR(20)             ,@IDTERCERO VARCHAR(20)
      ,@N_FACTU VARCHAR(20)              ,@IDCOPCENTO VARCHAR(20)         ,@DESCONCEPTO VARCHAR(120)
      ,@VALORNT DECIMAL(14,2)            ,@OBSERVA VARCHAR(512)           ,@NROLINEAS INT
      ,@ERROR VARCHAR(256)               ,@IDTER VARCHAR(20)              ,@RAZONS VARCHAR(120)
      ,@CNSRPDX VARCHAR(20)              ,@INDICE INT                     ,@TIPO VARCHAR(2)
      ,@N_CUOTA INT                      ,@IDSERVICIO VARCHAR(20)          ,@PREFIJO VARCHAR(20)           
      ,@IDAREA  VARCHAR(20)              ,@CCOSTO VARCHAR(20)              ,@CANTIDAD INT                  
      ,@VR_UNITARIO DECIMAL(14,2)        ,@VR_TOTAL DECIMAL(14,2)          ,@DETGENERADOS BIT  
	   ,@NROCOMPROBANTE VARCHAR(20)       ,@USUARIOSOL VARCHAR(20)          ,@RAZONANULA VARCHAR(255)
      ,@ITEM INT                         ,@IXCOUNTRY VARCHAR(20)           ,@PIVA DECIMAL(7,2)
      ,@VIVA DECIMAL(14,2)
BEGIN
	SELECT *
	INTO #JSON
	FROM OPENJSON(@json) WITH (
			MODELO VARCHAR(100) '$.MODELO'
			,METODO VARCHAR(100) '$.METODO'
			,USUARIO VARCHAR(12) '$.USUARIO'
			,PARAMETROS NVARCHAR(MAX) AS JSON
	)

	SELECT   @MODELO = MODELO			,@METODO = METODO
			,@PARAMETROS = PARAMETROS	,@USUARIO = USUARIO
	FROM #JSON
   SELECT @IXCOUNTRY=DBO.FNK_VALORVARIABLE('IXCOUNTRY')
	IF @METODO='FNOT_CRUD'     
	BEGIN         
		SELECT @DATOS=DATOS        
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			DATOS NVARCHAR(MAX) AS JSON 
			)           
      
			SELECT @PROCESO=PROCESO, @CNSFNOT=CNSFNOT,@CLASE=CLASE,@N_FACTURA=N_FACTURA,@CNSCXC=CNSCXC,@F_NOTA=F_NOTA,
				@OBSERVACION=OBSERVACION,@PROCEDENCIA=PROCEDENCIA,@IDCONCEPTO=IDCONCEPTO,@NIT=NIT,@RAZONSOCIAL=RAZONSOCIAL,
				@DESCRIPCION=DESCRIPCION,@CONCEPTO=CASE WHEN CONCEPTO='true' THEN 1 ELSE 0 END,@TIPOCONCEPTO=CASE WHEN TIPOCONCEPTO='Procentaje' OR TIPOCONCEPTO='P' THEN 'P'ELSE 'V' END,
            @VALORCONCEPTO=VALORCONCEPTO,	@SALDOFACTURA=SALDOFACTURA,@VALOR=VALOR,@IDTERCERO=IDTERCERO      
			FROM   OPENJSON (@DATOS)
			WITH   (  
			PROCESO VARCHAR(20)          '$.PROCESO',
			CNSFNOT VARCHAR(20)          '$.CNSFNOT',
			CLASE VARCHAR(20)            '$.CLASE',
			N_FACTURA VARCHAR(20)        '$.N_FACTURA',
			CNSCXC VARCHAR(20)           '$.CNSCXC',
			F_NOTA VARCHAR(20)           '$.F_NOTA',
			OBSERVACION VARCHAR(520)      '$.OBSERVACION',
			PROCEDENCIA VARCHAR(20)      '$.PROCEDENCIA',
			IDCONCEPTO VARCHAR(20)     '$.IDCONCEPTO',
			NIT VARCHAR(20)            '$.NIT',
			IDTERCERO VARCHAR(20)      '$.IDTERCERO',
			RAZONSOCIAL VARCHAR(120)      '$.RAZONSOCIAL',
			DESCRIPCION VARCHAR(120)      '$.DESCRIPCION',
			CONCEPTO VARCHAR(20)         '$.CONCEPTO',
			TIPOCONCEPTO VARCHAR(20)     '$.TIPOCONCEPTO',
			VALORCONCEPTO DECIMAL(14,2)    '$.VALORCONCEPTO',
			SALDOFACTURA DECIMAL(14,2)   '$.SALDOFACTURA',
			VALOR DECIMAL(14,2)          '$.VALOR'
			) 
		IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA)
		BEGIN
			BEGIN
			SELECT 'KO'KO,'Factura no Encontrada Verifique e intente de nuevo'ERROR
			RETURN
			END
		END
		IF @PROCESO='Nueva' 
		BEGIN
			IF EXISTS(SELECT * FROM FNOT WHERE N_FACTURA=@N_FACTURA AND CERRADA=0 AND ESTADO='O')
			BEGIN
			SELECT 'KO'KO,'Existe una Nota en proceso para esta Factura, No se Puede Continuar'ERROR
			RETURN
			END
			SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
			@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
			FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
			WHERE USUSU.USUARIO=@USUARIO
			BEGIN TRY
			SELECT @CNSFNOT=''
			IF @CLASE='C'
			BEGIN
			   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@FNOTC', @CNSFNOT OUTPUT  
			END
			ELSE
			BEGIN
				EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@FNOTD', @CNSFNOT OUTPUT  
			END
			PRINT '@CNSFNOT='+COALESCE(@CNSFNOT,'')   
				SELECT @CNSFNOT = @IDSEDE +LTRIM(RTRIM(@CLASE))+ REPLACE(SPACE(8 - LEN(@CNSFNOT))+LTRIM(RTRIM(@CNSFNOT)),SPACE(1),0)
				PRINT '@CNSFNOT='+COALESCE(@CNSFNOT,'')   
            
			INSERT INTO FNOT(CNSFNOT, CLASE, N_FACTURA, CNSCXC, IDTERCERO, F_NOTA, VR_TOTAL, OBSERVACION, MARCA, MARCACONT, 
							CONTABILIZADA, NROCOMPROBANTE, IMPRESO, COMPANIA, USUARIO, CERRADA, ESTADO, USUARIOANU,  
							USUARIOSOL, FECHAANU, RAZONANU, PROCEDENCIA, CNSGLO, APLICADAA, LIBERAHADM, CODUNG, CODPRG, 
							ENPRESUPUESTO, IDTERCEROCOBERTURA, COBERTURA_AUT_POR, CONCEPTO, IDCONCEPTO, TIPOCONCEPTO,  
							VALORCONCEPTO, USUARIOAPLICA, DETGENERADOS, CONSECUTIVOPPTO, RECO, FACTE, CNSRESOLFE, 
							PREFIJODIANFE, CNSDIANFE, CNSMASIVO, ZIPKEY, CUDE, FACTEP, RUTARPTA, DOCUMENTOID, DOCUXMLXZIPID,
							XMLZIPID, SOLICITUDJSON, RESPUESTAJSON, PDF) 
			SELECT @CNSFNOT, @CLASE, @N_FACTURA, @CNSCXC,@IDTERCERO, DBO.FNK_GETDATE(),0,@OBSERVACION, 0, 0, 
							0, NULL, 0, @COMPANIA, @USUARIO, 0, 'O', NULL,NULL, NULL, NULL, 'NOTAS', NULL,
							CASE WHEN COALESCE(@CNSCXC,'')='' THEN 'F' ELSE'C' END,0, NULL, NULL, 0, NULL, NULL, 
							@CONCEPTO,@IDCONCEPTO, COALESCE(@TIPOCONCEPTO,'P'),COALESCE(@VALORCONCEPTO,100), NULL, 0, NULL, NULL, NULL, NULL,NULL, NULL,
							NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0

			END TRY
			BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			SELECT ERROR AS ERROR FROM  @TBLERRORES 
			RETURN
			END CATCH
		END
		IF @PROCESO='Editar'
		BEGIN
			IF EXISTS(SELECT * FROM FNOT WHERE N_FACTURA=@N_FACTURA AND CERRADA=0 AND ESTADO='O' AND CNSFNOT<>@CNSFNOT)
			BEGIN
			SELECT 'KO'KO,'Existe una Nota en proceso para esta Factura, No se Puede Continuar'ERROR
			RETURN
			END
			BEGIN TRY       
			   UPDATE FNOT SET N_FACTURA=@N_FACTURA,IDTERCERO=@IDTERCERO,CNSCXC=@CNSCXC,IDCONCEPTO=@IDCONCEPTO,
			   CONCEPTO=@CONCEPTO,TIPOCONCEPTO=@TIPOCONCEPTO,VALORCONCEPTO=@VALORCONCEPTO,OBSERVACION=@OBSERVACION
			   WHERE CNSFNOT=@CNSFNOT
			END TRY
			BEGIN CATCH
				INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
			END CATCH
		END
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
      SELECT @DETGENERADOS=0
      IF EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE='C' AND CONCEPTO=1)
      BEGIN
         EXEC SPK_GENITEMS_NOTACR @CNSFNOT,@CLASE,@USUARIO 
         SELECT @DETGENERADOS=1
      END
		SELECT 'OK' OK,@CNSFNOT AS CNSFNOT, @DETGENERADOS AS DETGENERADOS
		RETURN 
	END  
	IF @METODO='FNOT_ADDDETA'     
	BEGIN   
		PRINT 'INGRESO AL METODO'
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE       
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE'
			)           
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		BEGIN TRY           
			EXEC SPK_GENITEMS_NOTACR @CNSFNOT,@CLASE,@USUARIO                   
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END   
	IF @METODO='FNOT_DELDETA'     
	BEGIN   
		PRINT 'INGRESO AL METODO'
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE       
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE'
			)   
            
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			PRINT '@CNSFNOT ='+@CNSFNOT
			PRINT '@CLASE ='+@CLASE
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		BEGIN TRY           
			EXEC SPK_DESITEMS_NOTACR @CNSFNOT,@CLASE,@USUARIO                   
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END  
	IF @METODO='FNOT_APLICAR'     
	BEGIN   
		PRINT 'INGRESO AL METODO'
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE       
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE'
			)   
            
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			PRINT '@CNSFNOT ='+@CNSFNOT
			PRINT '@CLASE ='+@CLASE
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		IF NOT EXISTS(SELECT * FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			SELECT 'KO'KO,'Nota Sin Detalles, no se puede Aplicar, Verifique e intente de nuevo 'ERROR
			RETURN
		END
		SELECT @F_NOTA=F_NOTA,@VALOR=VR_TOTAL,@N_FACTURA=N_FACTURA,@CNSCXC=CNSCXC 
		FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE

		IF NOT EXISTS(SELECT * FROM PRI WHERE FECHA_INI<=@F_NOTA AND FECHA_FIN>=@F_NOTA AND COALESCE(CERRADO_CARTERA,0)=0)
		BEGIN
			SELECT 'KO'KO,'Periodo de Cartera Cerrado o no Existe, Verique e Intente de Nuevo'ERROR
			RETURN
		END
		IF NOT EXISTS(SELECT * FROM PRI WHERE FECHA_INI<=@F_NOTA AND FECHA_FIN>=@F_NOTA AND COALESCE(CERRADO,0)=0)
		BEGIN
			SELECT 'KO'KO,'Periodo de Contable Cerrado o no Existe, Verique e Intente de Nuevo'ERROR
			RETURN
		END
		IF COALESCE(@VALOR,0)<=0
		BEGIN
			SELECT 'KO'KO,'El valor de la nota Credito no Puede ser Menor o Igual a Cero'ERROR
			RETURN
		END
		IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTURA AND ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')
		BEGIN
			SELECT 'KO'KO,'Inconsistencia en la Factura, Verifique el estado de la Factura'ERROR
			RETURN
		END
		IF @CLASE='C'
		BEGIN
			EXEC SPK_RELIQUIDA_FTR @CNSCXC,@N_FACTURA
		END
		IF @CLASE='C' AND NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO WHERE N_FACTURA=@N_FACTURA AND CNSCXC=CASE WHEN COALESCE(@CNSCXC,'')='' THEN 'NO RADICADA' ELSE @CNSCXC END AND SALDONETO>=@VALOR AND TIPO='F' AND CLASEINFO='SINGLO' )
		BEGIN
         PRINT '@N_FACTURA='+@N_FACTURA+ ' @CNSCXC='+COALESCE(@CNSCXC,'SIN CXC')+' VALOR'+STR(@VALOR)
			SELECT 'KO'KO,'Verique los Saldos, el Saldo de la Factura no cubre el Valor de la Nota 'ERROR
			RETURN
		END
		SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO

		BEGIN TRY   
         PRINT 'SPK_NOTASCXC'
			EXEC SPK_NOTASCXC @CNSFNOT,@CLASE,'',@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME               
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END
	IF @METODO='CARGAR_NOTAS'
	BEGIN
			
		DECLARE @LINEA AS VARCHAR(MAX)
		DECLARE @TABLA AS TABLE(
			ITEM INT IDENTITY(1,1),
			VALOR VARCHAR(MAX)
		)

      SELECT  @NROLINEAS=COUNT(*)
		FROM OPENJSON(@PARAMETROS, '$.LINEAS') 

      IF @NROLINEAS>0
      BEGIN

		   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		   WHERE USUSU.USUARIO=@USUARIO

		   PRINT 'AQUI LLAMO A GENCONSECUTIVO @IDSEDE='+COALESCE(@IDSEDE,'SIN SEDE')   
         SELECT @CNSRPDX=''
		   EXEC SPK_GENCONSECUTIVO @COMPANIA,@IDSEDE, '@RPDX', @CNSRPDX OUTPUT  
		   SELECT @CNSRPDX = @IDSEDE+REPLACE(SPACE(8 - LEN(@CNSRPDX))+LTRIM(RTRIM(@CNSRPDX)),SPACE(1),0)
		   PRINT '@CNSRPDX='+COALESCE(@CNSRPDX,'') 

         SELECT @INDICE=0
		   DECLARE SUBIR_CURSOR CURSOR FOR   
	      SELECT VALUE 
		   FROM OPENJSON(@PARAMETROS, '$.LINEAS')		  
		   OPEN SUBIR_CURSOR  
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   WHILE @@FETCH_STATUS = 0  
		   BEGIN  	  
			   DELETE FROM @TABLA WHERE 1=1

			   INSERT INTO @TABLA(VALOR)
			   SELECT VALUE FROM string_split(@LINEA,',')

            SELECT @N_FACTU=VALOR FROM @TABLA WHERE ITEM=1+@INDICE
            SELECT @IDCONCEPTO=VALOR FROM @TABLA WHERE ITEM=2+@INDICE
            SELECT @DESCONCEPTO=VALOR FROM @TABLA WHERE ITEM=3+@INDICE
            SELECT @VALOR=CONVERT(DECIMAL(14,2),VALOR) FROM @TABLA WHERE ITEM=4+@INDICE
            SELECT @OBSERVA=VALOR FROM @TABLA WHERE ITEM=5+@INDICE

            SET @ERROR=''
            IF NOT EXISTS(SELECT * FROM FTR WHERE N_FACTURA=@N_FACTU AND ESTADO='P' AND COALESCE(TIPOANULACION,'')<>'NC')
            BEGIN
               SELECT @IDTER='',@RAZONS=''
               SET @ERROR += 'Factura no existe o se encuentra anulada, no se puede procesar'
            END
            ELSE 
            BEGIN
               SELECT @IDTER=TER.NIT,@RAZONS=RAZONSOCIAL
               FROM FTR INNER JOIN TER ON FTR.IDTERCERO=TER.IDTERCERO 
               WHERE N_FACTURA=@N_FACTU
            END
            IF NOT EXISTS(SELECT * FROM VWK_CXCDIASVTO WHERE N_FACTURA=@N_FACTURA AND TIPO='F' AND SALDONETO>=@VALOR)
            BEGIN
               SET @ERROR +='Factura no tiene Saldo en Cartera en su tipo F no se puede subir'
            END
            IF NOT EXISTS(SELECT * FROM CPNT WHERE CODIGO=@IDCONCEPTO)
            BEGIN
               SET @ERROR +='Id.Concpeto no existe, o no esta homologando ante la Dian'
            END
            IF COALESCE(@VALOR,0)<=0
            BEGIN
               SET @ERROR +='Valor de la nota no puede ser menor o igual a cero, No se Puede Subir' 
            END

            INSERT INTO RPDX(CNS,ID1,ID2,ID3,STRINGMEDIO2,STRINGMEDIO1,VALOR1,STRINGGRANDE1,STRINGGRANDE2,CANTIDAD)
            SELECT @CNSRPDX,@N_FACTU,@IDCONCEPTO,@IDTER,@DESCONCEPTO,@RAZONS,@VALOR,@OBSERVA,@ERROR,CASE WHEN LEN(@ERROR)>1 THEN 1 ELSE 0 END 

            SET @INDICE +=5
		   FETCH NEXT FROM SUBIR_CURSOR INTO @LINEA
		   END  
		  
		   CLOSE SUBIR_CURSOR  
		   DEALLOCATE SUBIR_CURSOR  

         SELECT @NROLINEAS=COUNT(*) FROM RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=1


         SELECT 'OK' OK,@CNSRPDX CNSRPDX,@NROLINEAS ERRADOS
         RETURN

      END
      ELSE
      BEGIN
         SELECT 'KO','No se encontraron Datos para Procesar, Verfique e intente de nuevo' ERROR
         RETURN
      END
	END
   IF @METODO='FNOT_CREARMASIVO'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX,@CLASE=CLASE        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSRPDX VARCHAR(20) '$.CNSRPDX',
        CLASE VARCHAR(2) '$.CLASE'
            )
      IF NOT EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX)
      BEGIN
         SELECT 'KO'KO,'El Consecutivo no fue encontrado.'ERROR
         RETURN
      END
		SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO

      PRINT 'Borrando Registros con error'
      DELETE RPDX WHERE CNS=@CNSRPDX AND CANTIDAD=1
      BEGIN TRY           
         EXEC SPK_APLICA_FNOT_MASIVA @CNSRPDX, @COMPANIA,@IDSEDE,@USUARIO,@CLASE                             
      END TRY
      BEGIN CATCH
            INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      PRINT 'Borrando Registros Temporales'
      DELETE RPDX WHERE CNS=@CNSRPDX
      SELECT 'OK' OK
      RETURN       
   END   
   IF @METODO='FNOT_LIMPIARPDX'     
   BEGIN         
      SELECT @CNSRPDX=CNSRPDX      
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
        CNSRPDX VARCHAR(20) '$.CNSRPDX'
      )
      IF EXISTS(SELECT * FROM RPDX WHERE CNS=@CNSRPDX)
      BEGIN
         DELETE RPDX WHERE CNS=@CNSRPDX
      END
      SELECT 'OK' OK
      RETURN
    END
   IF @METODO='FNOT_CRUDFNOTD'     
   BEGIN         
      SELECT @DATOS=DATOS        
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
         DATOS NVARCHAR(MAX) AS JSON 
            )           
      SELECT @PROCESO=PROCESO, @CNSFNOT=CNSFNOT,@CLASE=CLASE,@ITEM=CONVERT(INT,ITEM),@TIPO=TIPO,@N_FACTURA=N_FACTURA,@N_CUOTA=N_CUOTA,@IDSERVICIO=IDSERVICIO,
             @DESCRIPCION=DESCRIPCION,@PREFIJO=PREFIJO,@IDAREA=IDAREA,@CCOSTO=CCOSTO,@CANTIDAD=CANTIDAD,@VR_UNITARIO=VR_UNITARIO,
             @VR_TOTAL=VR_TOTAL,@OBSERVACION=OBSERVACION,@VIVA =VIVA,@PIVA =PIVA            
      FROM   OPENJSON (@DATOS)
      WITH   ( 
         PROCESO VARCHAR(20)           '$.PROCESO',
         CNSFNOT VARCHAR(20)           '$.CNSFNOT',
         CLASE VARCHAR(20)             '$.CLASE',
         ITEM  VARCHAR(10)             '$.item',
         TIPO VARCHAR(3)               '$.TIPO',
         N_FACTURA VARCHAR(20)         '$.N_FACTURA',
         N_CUOTA INT                   '$.N_CUOTA',
         IDSERVICIO VARCHAR(20)        '$.IDSERVICIO',
         DESCRIPCION VARCHAR(120)      '$.DESCRIPCION',
         PREFIJO VARCHAR(20)           '$.PREFIJO',
         IDAREA  VARCHAR(20)           '$.IDAREA',
         CCOSTO VARCHAR(20)            '$.CCOSTO',
         CANTIDAD INT                  '$.CANTIDAD',
         VR_UNITARIO DECIMAL(14,2)     '$.VR_UNITARIO',
         VIVA  DECIMAL(14,2)   '$.VIVA',
         PIVA  DECIMAL(7,2)   '$.PIVA',
         VR_TOTAL DECIMAL(14,2)        '$.VR_TOTAL',
         OBSERVACION VARCHAR(256)      '$.OBSERVACION'      
      )  
      
      IF NOT EXISTS(SELECT  * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ESTADO='O' AND CERRADA=0)
      BEGIN
         SELECT 'KO'KO,'Nota No Encontrada, Revise e intente de nuevo'ERROR
         RETURN
      END
      IF DBO.FNK_VALORVARIABLE('IXCOUNTRY')='PERU'
      BEGIN
         SELECT @VR_UNITARIO=@VR_TOTAL
      END
      IF @PROCESO='Nuevo'
      BEGIN
         PRINT 'Ingresando un nuevo item'
		   SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		   @SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		   FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		   WHERE USUSU.USUARIO=@USUARIO

         SELECT @ITEM=COALESCE(MAX(ITEM),0)+1 FROM FNOTD WHERE  CNSFNOT=@CNSFNOT AND CLASE=@CLASE
         
         BEGIN TRY           
            INSERT INTO FNOTD(CNSFNOT, CLASE, ITEM, TIPO, IDSERVICIO, DESCRIPCION, CANTIDAD, VR_UNITARIO, VR_TOTAL, COMPANIA, 
                              USUARIO, OBSERVACION, N_CUOTA, PIVA, VALORIVA, N_FACTURA, CCOSTO, IDAREA, PREFIJO, CUENTA )
            SELECT @CNSFNOT, @CLASE, @ITEM, @TIPO, @IDSERVICIO, @DESCRIPCION, @CANTIDAD, @VR_UNITARIO, @VR_TOTAL, @COMPANIA, 
                   @USUARIO, @OBSERVACION, @N_CUOTA, @PIVA, @VIVA, @N_FACTURA, @CCOSTO, @IDAREA, @PREFIJO, NULL                               
         END TRY
         BEGIN CATCH
               PRINT 'HBO ERROR'
               INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
         END CATCH
      END
      ELSE
      BEGIN
         IF @PROCESO='Editar'
         BEGIN
            print 'Editando item '+COALESCE(STR(@ITEM),'ANDA')
            UPDATE FNOTD SET @IDSERVICIO=@IDSEDE,DESCRIPCION=@DESCRIPCION,CANTIDAD=@CANTIDAD,VR_UNITARIO=@VR_UNITARIO,
                             VR_TOTAL=@VR_TOTAL,N_CUOTA=@N_CUOTA,N_FACTURA=@N_FACTURA,CCOSTO=@CCOSTO,PREFIJO=@PREFIJO,
                             IDAREA=@IDAREA,OBSERVACION=@OBSERVACION,PIVA=@PIVA,VALORIVA=@VIVA
            WHERE CNSFNOT=@CNSFNOT
            AND CLASE=@CLASE
            AND ITEM=@ITEM
         END
         ELSE
         BEGIN
            PRINT 'Borrando item'
            DELETE FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE AND ITEM=@ITEM
         END
      END
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT @VR_TOTAL=SUM(VR_TOTAL) FROM FNOTD WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE
      UPDATE FNOT SET VR_TOTAL=@VR_TOTAL WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE
      SELECT 'OK' OK
      RETURN 
  END
	IF @METODO='FNOT_ANULANOTA'     
	BEGIN   
		PRINT 'INGRESO AL METODO'
		SELECT @CNSFNOT=CNSFNOT,@CLASE=CLASE,@USUARIOSOL=USUARIOSOL,@RAZONANULA=RAZONANULA     
		FROM   OPENJSON (@PARAMETROS)
		WITH (           
			CNSFNOT VARCHAR(20) '$.CNSFNOT',
			CLASE   VARCHAR(2) '$.CLASE',
         USUARIOSOL VARCHAR(20) '$.USUARIOSOL',
         RAZONANULA VARCHAR(255) '$.RAZONANULA'
			)   
            
		IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE)
		BEGIN
			PRINT '@CNSFNOT ='+@CNSFNOT
			PRINT '@CLASE ='+@CLASE
			SELECT 'KO'KO,'Nota no encontrada, Verifique e intente de nuevo'ERROR
			RETURN
		END
		
      SELECT @IDSEDE=COALESCE(UBEQ.IDSEDE,USUSU.IDSEDE),@COMPANIA=COALESCE(UBEQ.COMPANIA,USUSU.COMPANIA),
		@SYS_COMPUTERNAME=COALESCE(USUSU.SYS_ComputerName,HOST_NAME())
		FROM USUSU LEFT JOIN UBEQ ON USUSU.SYS_ComputerName=UBEQ.SYS_ComputerName
		WHERE USUSU.USUARIO=@USUARIO
      SELECT @NROCOMPROBANTE=NROCOMPROBANTE,@PROCEDENCIA=PROCEDENCIA FROM FNOT WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE 
		BEGIN TRY           
			EXEC DBO.SPK_ANULANOTA_CR @CNSFNOT,@NROCOMPROBANTE,'',@IDSEDE,@COMPANIA,@USUARIO,@SYS_COMPUTERNAME,@PROCEDENCIA                  
		END TRY
		BEGIN CATCH
			INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
		END CATCH
		IF(SELECT COUNT(*) FROM @TBLERRORES)>0
		BEGIN
			SELECT 'KO' OK, ERROR FROM @TBLERRORES
			RETURN
		END
      UPDATE FNOT SET ESTADO='A',USUARIOANU=@USUARIO,USUARIOSOL=@USUARIOSOL,
      FECHAANU=DBO.FNK_GETDATE(),RAZONANU=@RAZONANULA 
      WHERE CNSFNOT=@CNSFNOT AND CLASE=@CLASE

		SELECT 'OK' OK,@CNSFNOT CNSFNOT
		RETURN 
	END  
   IF @METODO='FNOT_ENVIARSUNAT'     
   BEGIN         
      SELECT @CNSFNOT=CNSFNOT, @N_FACTURA=N_FACTURA       
      FROM   OPENJSON (@PARAMETROS)
      WITH (           
      CNSFNOT  VARCHAR(20)   '$.CNSFNOT',
      N_FACTURA  VARCHAR(20)   '$.N_FACTURA'
      )
      IF @IXCOUNTRY !='PERU'
      BEGIN
         SELECT 'KO'KO,'Variable Pais no es Perú'ERROR
         RETURN
      END
      IF NOT EXISTS(SELECT * FROM FNOT WHERE CNSFNOT=@CNSFNOT AND N_FACTURA=@N_FACTURA AND COALESCE(FACTEP,'')<>'OK')
      BEGIN
         SELECT 'KO'KO,'Nota No esta Pendiente de Enviar 'ERROR
         RETURN
      END
      BEGIN TRY           
         EXEC SPK_GENERA_JSON_PERU_NOTADBCR @CNSFNOT,@N_FACTURA               
      END TRY
      BEGIN CATCH
              INSERT INTO @TBLERRORES(ERROR) SELECT ERROR_MESSAGE()
      END CATCH
      IF(SELECT COUNT(*) FROM @TBLERRORES)>0
      BEGIN
         SELECT 'KO' OK, ERROR FROM @TBLERRORES
         RETURN
      END
      SELECT 'OK' OK
      RETURN 
   END  
END

