--COBRA O NO COPAGO
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'IMOVH'  AND   C.NAME = 'COBRACOPA')
BEGIN
   ALTER TABLE IMOVH  ADD COBRACOPA BIT 
END
--AUTORIZADO
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'IMOVH'  AND   C.NAME = 'AUTORIZADO')
BEGIN
   ALTER TABLE IMOVH  ADD AUTORIZADO BIT
END
--USUARIO QUE AUTORIZA
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'IMOVH'  AND   C.NAME = 'USUAUTORIZA')
BEGIN
   ALTER TABLE IMOVH  ADD USUAUTORIZA VARCHAR(20) 
END
--VALOR COPOAGO
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'IMOVH'  AND   C.NAME = 'VLR_COPAGO')
BEGIN
   ALTER TABLE IMOVH  ADD VLR_COPAGO DECIMAL(14,2) 
END
IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'AUT'  AND   C.NAME = 'CONSECUTIVOCIT')
BEGIN
   ALTER TABLE AUT  ADD CONSECUTIVOCIT VARCHAR(20)
END