IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'SPK_ASIGNA_COPAGOS_IMOVH' AND TYPE = 'P')
BEGIN
   DROP PROCEDURE SPK_ASIGNA_COPAGOS_IMOVH
END
GO
CREATE PROCEDURE DBO.SPK_ASIGNA_COPAGOS_IMOVH
@CNSMOV VARCHAR(20)
WITH ENCRYPTION
AS
DECLARE @IDARTICULO_C VARCHAR(20)
DECLARE @CNSTRAN_C VARCHAR(20)
DECLARE @CNSHTX_C VARCHAR(20)
DECLARE @IDPLAN_C VARCHAR(6)
DECLARE @PVENTA_C DECIMAL(14,2)
DECLARE @PORCOPA_C DECIMAL(7,2)
DECLARE @VLCOPAGO_C DECIMAL(14,2)
DECLARE @IDTERCERO  VARCHAR(20)
DECLARE @NOADMISION VARCHAR(20)
DECLARE @CNSIZSOL   VARCHAR(20)
DECLARE @COPAGO_C   BIT
DECLARE @AUTORIZADO BIT
DECLARE @PAUTO      SMALLINT
DECLARE @PROCE      VARCHAR(20)
DECLARE @IDPLANB    VARCHAR(6)
DECLARE @COPAGO     DECIMAL(14,2)
DECLARE @AUTORIZA   VARCHAR(4)
DECLARE @IDSERVICIO VARCHAR(20)
DECLARE @VIVACOPA   DECIMAL(14,2)
DECLARE @VIVATCOPA   DECIMAL(14,2)
DECLARE @VIVATVENTA   DECIMAL(14,2)
DECLARE @PVENTAT   DECIMAL(14,2)
DECLARE @CANT      SMALLINT

BEGIN
	PRINT '@CNSMOV='+@CNSMOV
	IF EXISTS(SELECT * FROM IMOV WHERE CNSMOV=@CNSMOV AND ESTADO<>0)
	BEGIN
		PRINT 'MOVIMIENTO CONFIRMADO O ANULADO '
		RETURN
	END
	SELECT @CNSIZSOL= NODOCUMENTO FROM IMOV WHERE CNSMOV=@CNSMOV
	SELECT @NOADMISION=NOADMISION,@PAUTO=COALESCE(PAUTO,0),@PROCE=CLASE FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL
   IF @PROCE='CE'
   BEGIN
      SELECT @IDTERCERO=IDTERCEROCA,@IDPLANB=IDPLAN FROM AUT WHERE NOAUT=@NOADMISION
   END
   ELSE
   BEGIN
	   SELECT @IDTERCERO=IDTERCERO,@IDPLANB=IDPLAN FROM HADM WHERE NOADMISION=@NOADMISION
   END
	DECLARE IMOVH_COPA CURSOR FOR  
	SELECT IMOVH.IDARTICULO, IMOVH.CNSTRAN, IMOVH.CNSHTX, COALESCE(IMOVH.COBRACOPA,0), 
			COALESCE(IMOVH.AUTORIZADO,0), COALESCE(IMOVH.VLR_COPAGO,0), IART.IDSERVICIO_FAC,CANTIDAD
	FROM   IMOVH INNER JOIN IART ON IART.IDARTICULO=IMOVH.IDARTICULO
	WHERE  CNSMOV=@CNSMOV
	GROUP BY IMOVH.IDARTICULO, IMOVH.CNSTRAN, IMOVH.CNSHTX, COALESCE(IMOVH.COBRACOPA,0), 
			COALESCE(IMOVH.AUTORIZADO,0), COALESCE(IMOVH.VLR_COPAGO,0), IART.IDSERVICIO_FAC,CANTIDAD
	OPEN IMOVH_COPA    
	FETCH NEXT FROM IMOVH_COPA    
	INTO @IDARTICULO_C,	@CNSTRAN_C,	@CNSHTX_C,	@COPAGO_C,	@AUTORIZADO,	@VLCOPAGO_C, @IDSERVICIO, @CANT
	WHILE @@FETCH_STATUS = 0    
	BEGIN
		PRINT 'EMPIEZO LA REVISION DE IMOVH'
		IF @PROCE<>'FMEX'
		BEGIN
      
			SELECT @IDPLAN_C=NULL
			SELECT @PVENTA_C=NULL
			IF COALESCE(@PROCE,'')='HTX'
			BEGIN
				SELECT @IDPLAN_C=HTX.IDPLAN FROM IZSOLD INNER JOIN HTX ON IZSOLD.CNSHBALI=HTX.CNSHTX
				WHERE IZSOLD.CNSIZSOLD=@CNSHTX_C
			END

			IF COALESCE(@IDPLAN_C,'')=''
			BEGIN
				SELECT @IDPLAN_C=@IDPLANB
			END
			PRINT '@IDPLAN_C='+COALESCE(@IDPLAN_C,'NO ENCONTRE PLAN...')

			SELECT @PVENTA_C =ROUND(VLRSERVICIO,2) FROM SERTOT1
			WHERE IDPLAN=@IDPLAN_C
			AND IDTERCERO=@IDTERCERO
			AND IDSERVICIO=@IDARTICULO_C
			AND FECHAFIN>GETDATE()
			AND FECHAINI<=GETDATE()
			AND FECHAFINFD>GETDATE()
			AND FECHAINIFD<=GETDATE()

			PRINT 'VALOR SERVICIO ='+STR(COALESCE(@PVENTA_C,0))

			IF NOT EXISTS(SELECT 1 FROM PPT WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN_C AND COALESCE(COBRACOPAGO,0)=1)
				AND NOT EXISTS (SELECT 1 FROM PPTD WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN_C AND COALESCE(TIPORESTRICCION,'')='C' AND IDSERVICIO=@IDSERVICIO)
			BEGIN 
				PRINT 'CONTRATO NO  COBRA COPAGO...'
				UPDATE IMOVH SET COBRACOPA=0,AUTORIZADO=1,USUAUTORIZA='Automatico',VLR_COPAGO=0,PVENTA=COALESCE(@PVENTA_C,0)
				WHERE  IMOVH.CNSMOV=@CNSMOV
				AND    CNSTRAN    = @CNSTRAN_C
				AND    CNSHTX     = @CNSHTX_C
				AND    IDARTICULO = @IDARTICULO_C

				FETCH NEXT FROM IMOVH_COPA    
				INTO @IDARTICULO_C,@CNSTRAN_C,@CNSHTX_C,@COPAGO_C,@AUTORIZADO,@VLCOPAGO_C,@IDSERVICIO, @CANT
				CONTINUE
			END 
			IF EXISTS(SELECT 1 FROM IART WHERE IDARTICULO=@IDARTICULO_C AND COALESCE(ENTREGA_TURNO,0)=1 AND COALESCE(UTILIDAD,0)>0)
				OR EXISTS (SELECT 1 FROM PPTD WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN_C AND COALESCE(TIPORESTRICCION,'')='C' AND IDSERVICIO=@IDSERVICIO)
			BEGIN
				PRINT 'CONTRATO COBRA COPAGO Y IART TIENE COPOAGO'
         
				IF EXISTS (SELECT 1 FROM PPTD WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN_C AND COALESCE(TIPORESTRICCION,'')='C' AND IDSERVICIO=@IDSERVICIO)
					SELECT @PORCOPA_C=COALESCE(CANTNOCOBRABLE,0) FROM PPTD WHERE IDTERCERO=@IDTERCERO AND IDPLAN=@IDPLAN_C AND COALESCE(TIPORESTRICCION,'')='C' AND IDSERVICIO=@IDSERVICIO
				ELSE
					SELECT @PORCOPA_C=UTILIDAD FROM IART WHERE IDARTICULO=@IDARTICULO_C AND COALESCE(ENTREGA_TURNO,0)=1 AND COALESCE(UTILIDAD,0)>0

				PRINT 'HACEMOS CALCULOS'
				SELECT @COPAGO=ROUND(@PVENTA_C*(@PORCOPA_C/100),4)

				PRINT 'HACEMOS LOS UPDATE NECESARIOS'
				IF @PAUTO=0 OR @PAUTO=1
				BEGIN
					PRINT 'En proceso de Dispensacion o Autorizacion...'
					UPDATE IMOVH SET COBRACOPA= CASE WHEN @COPAGO > 0 THEN 1 ELSE 0 END,PVENTA=@PVENTA_C,VLR_COPAGO=@COPAGO,
							AUTORIZADO = CASE WHEN @COPAGO > 0 THEN  
												CASE WHEN COALESCE(@AUTORIZADO,0)=0 THEN 0 
													WHEN COALESCE(@AUTORIZADO,0) =1 AND ( @COPAGO<>@VLCOPAGO_C OR USUAUTORIZA='Automatico') THEN  0 
													ELSE AUTORIZADO END 
											ELSE 1
										END,
							USUAUTORIZA = CASE WHEN @COPAGO > 0 THEN  
												CASE WHEN COALESCE(@AUTORIZADO,0)=0 THEN 'Sin Autorizardor' 
													WHEN COALESCE(@AUTORIZADO,0)=1  AND (@COPAGO<>@VLCOPAGO_C OR USUAUTORIZA='Automatico')  THEN  'Sin Autorizardor'  
													ELSE USUAUTORIZA END 
											ELSE 'Automatico'
										END
					WHERE IMOVH.CNSMOV=@CNSMOV
					AND CNSTRAN=@CNSTRAN_C
					AND CNSHTX=@CNSHTX_C
					AND IDARTICULO=@IDARTICULO_C
				END
				ELSE
				BEGIN
					UPDATE IMOVH SET COBRACOPA= CASE WHEN @COPAGO > 0 THEN 1 ELSE 0 END,PVENTA=@PVENTA_C,VLR_COPAGO=@COPAGO,
							AUTORIZADO = CASE WHEN @COPAGO > 0 THEN CASE WHEN @AUTORIZADO = 'ND' THEN 0 ELSE AUTORIZADO END ELSE 1 END,
							USUAUTORIZA = CASE WHEN @COPAGO > 0 THEN CASE WHEN @AUTORIZADO = 'ND' THEN 'Sin Autorizardor' ELSE USUAUTORIZA END ELSE 'Automatico' END
					WHERE IMOVH.CNSMOV=@CNSMOV
					AND CNSTRAN=@CNSTRAN_C
					AND CNSHTX=@CNSHTX_C
					AND IDARTICULO=@IDARTICULO_C
				END
			END
			ELSE
			BEGIN
				PRINT 'CONTRATO COBRA COPAGO Y IART NO TIENE COPOAGO'
				UPDATE IMOVH SET COBRACOPA=0,PVENTA=@PVENTA_C,AUTORIZADO=1,USUAUTORIZA='Automatico',VLR_COPAGO=0
				WHERE IMOVH.CNSMOV=@CNSMOV
				AND CNSTRAN=@CNSTRAN_C
				AND CNSHTX=@CNSHTX_C
				AND IDARTICULO=@IDARTICULO_C
			END
		END
		ELSE
		BEGIN
			SELECT @PVENTA_C=COALESCE(SINIGV_VLRUNI,0), 
			@COPAGO=COALESCE(SINIGV_VLR_COPA_UNI,0),
			@VIVACOPA= COALESCE(CONIGV_VLR_COPA_UNI,0) ,
			@VIVATCOPA=CASE WHEN @CANT=CANTIDAD THEN  COALESCE(CONIGV_VLR_COPATOTAL,0)ELSE @CANT*COALESCE(CONIGV_VLR_COPA_UNI,0)  END ,
			@VIVATVENTA= COALESCE(CONIGV_VLRUNI,0),
			@PVENTAT=CASE WHEN @CANT=CANTIDAD THEN  COALESCE(CONIGV_VRTOTAL,0)  ELSE @CANT*COALESCE(CONIGV_VLRUNI,0) END
			FROM IFMEXD WHERE CNSIZSOLD=@CNSHTX_C

			PRINT 'En proceso de Dispensacion o Autorizacion...'
			UPDATE IMOVH SET COBRACOPA= CASE WHEN @COPAGO > 0 THEN 1 ELSE 0 END,PVENTA=ROUND(@PVENTA_C,2),VLR_COPAGO=ROUND(@COPAGO,2),
					AUTORIZADO = CASE WHEN @COPAGO > 0 THEN  
										CASE WHEN COALESCE(@AUTORIZADO,0)=0 THEN 0 
											WHEN COALESCE(@AUTORIZADO,0)=1 AND ( @COPAGO*CANTIDAD<>@VLCOPAGO_C OR USUAUTORIZA='Automatico') THEN  0 
											ELSE AUTORIZADO END 
									ELSE 1
								END,
					USUAUTORIZA = CASE WHEN @COPAGO > 0 THEN  
										CASE WHEN COALESCE(@AUTORIZADO,0)=0 THEN 'Sin Autorizardor' 
											WHEN COALESCE(@AUTORIZADO,0)=1  AND (@COPAGO<>@VLCOPAGO_C OR USUAUTORIZA='Automatico')  THEN  'Sin Autorizardor'  
											ELSE USUAUTORIZA END 
									ELSE 'Automatico'
								END,
				VIVACOPA=@VIVACOPA,
				VIVATCOPA=@VIVATCOPA,
				VIVATVENTA=@VIVATVENTA,
				PVENTAT=@PVENTAT
			WHERE IMOVH.CNSMOV=@CNSMOV
			AND CNSTRAN=@CNSTRAN_C
			AND CNSHTX=@CNSHTX_C
			AND IDARTICULO=@IDARTICULO_C
		END
		UPDATE IMOVH SET COBRACOPA=1, VLR_COPAGO=PVENTA
		WHERE CNSMOV=@CNSMOV
		AND CNSTRAN=@CNSTRAN_C
		AND CNSHTX=@CNSHTX_C
		AND IDARTICULO=@IDARTICULO_C
		AND COALESCE(UPPER(ODCILINDRO),'')='SI'
		print 'terminó cursor'
		FETCH NEXT FROM IMOVH_COPA
		INTO @IDARTICULO_C,@CNSTRAN_C,@CNSHTX_C,@COPAGO_C,@AUTORIZADO,@VLCOPAGO_C,@IDSERVICIO,@CANT
	END
	CLOSE IMOVH_COPA
	DEALLOCATE IMOVH_COPA
END


