IF NOT EXISTS ( SELECT O.object_id, C.column_id, C.NAME FROM  SYS.OBJECTS O INNER JOIN SYS.columns C ON O.object_id = C.object_id  WHERE O.NAME = 'KCEREP'  AND   C.NAME = 'F_ESTERIL')
BEGIN
   ALTER TABLE KCEREP  ADD F_ESTERIL DATETIME 
END