IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_PEDIDOINVQX' AND type = 'P')
   DROP PROCEDURE SPK_PEDIDOINVQX

GO
CREATE PROCEDURE DBO.SPK_PEDIDOINVQX 
@NOPRESTACION     VARCHAR(16),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@RPDX             VARCHAR(20) = NULL,
@IDBODEGASOLI	   VARCHAR(20)  = ''
WITH ENCRYPTION
AS
DECLARE @CUANTAS        INT
DECLARE @IDINVARTNA     VARCHAR(80)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDITAR         VARCHAR(2)
DECLARE @IDTIPOMOV      VARCHAR(2)
DECLARE @CCOSTO         VARCHAR(20)
DECLARE @IDAREAH        VARCHAR(20)
DECLARE @IDAREA         VARCHAR(20)
DECLARE @NA             VARCHAR(5) 
DECLARE @ESTRANSITO     SMALLINT
DECLARE @OK             SMALLINT
DECLARE @IDTERCERO      VARCHAR(20)
DECLARE @TMB            VARCHAR(1)
DECLARE @IDBODEGA       VARCHAR(20)
DECLARE @IDBODEGA2      VARCHAR(20)
DECLARE @INVPIDEAUTOMQX VARCHAR(20)
DECLARE @CONFAUT        SMALLINT
DECLARE @CODUNG         VARCHAR(5)
DECLARE @CODPRG         VARCHAR(20) 
DECLARE @IDBODEGACUR    VARCHAR(20) 
DECLARE @INSERTS        INT
DECLARE @UPDATES        INT
DECLARE @TIPOBODEGA     VARCHAR(10)
DECLARE @CNSIZSOL       VARCHAR(20)
DECLARE @SECTOR         VARCHAR(20)
DECLARE @CNSIZSOLD      VARCHAR(20)
DECLARE @CLASEPED       VARCHAR(10)
BEGIN
   SELECT @OK = PEDIDOINV FROM HPRE WHERE NOPRESTACION = @NOPRESTACION
   IF @OK = 1
   BEGIN
      RETURN
   END
   --PRINT 'INICIE'
   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'
   SELECT @CUANTAS = COUNT(*) FROM HPRED,SER WHERE HPRED.IDSERVICIO = SER.IDSERVICIO 
   AND HPRED.NOPRESTACION = @NOPRESTACION 
   AND SER.IDARTICULO <> '' 
   AND SER.IDARTICULO <> @IDINVARTNA
   AND COALESCE(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
   
   IF @CUANTAS = 0
   BEGIN
      UPDATE HPRE SET PEDIDOINV = 1 WHERE NOPRESTACION = @NOPRESTACION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
      RETURN
   END
    
   PRINT 'PASE PEDODINV  '
   SELECT @NOADMISION = NOADMISION, @CCOSTO = CCOSTO, @IDAREA = IDAREA, @IDAREAH = IDAREAH,
          @NA = NIVELATENCION,@CLASEPED=COALESCE(CODOM,'')
   FROM HPRE WHERE NOPRESTACION = @NOPRESTACION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
   
   -- SE BUSCA EL MANEJO DE BODEGA PARA SABER LAS BODEGAS A LAS QUE ENVIA
   SELECT @TMB = TIPOMANEJOBODEGA, @IDBODEGA = IDBODEGA, @IDBODEGA2 = IDBODEGA2 
   FROM   UBEQ 
   WHERE  COMPANIA = @COMPANIA
   AND    SYS_COMPUTERNAME = @SYS_COMPUTERNAME

   PRINT 'BODEGA DE PEDIDO = = '+COALESCE(@IDBODEGA,'')

   IF DBO.FNK_VALORVARIABLE('PEDIDOHPREAIZSOL')<>'SI'
   BEGIN
      PRINT 'VARIABLE DIFERENTE A SI '
      IF @TMB = 'A'     
      BEGIN
         SELECT @IDBODEGA = BODEGADIA, @IDBODEGA2 = BODEGADIA2 FROM AFU WHERE
         IDAREA = @IDAREA
      END
   
	   -- ADD.JQUIROGA 20090623 - Venezuela. Manejar Bodega recibida en @IDBODEGASOLI desde Asistencial
	   IF DBO.FNK_VALORVARIABLE('PEDIRCARGOS_A_BODEGA') = 'SI' AND @IDBODEGASOLI <> '' AND @TMB = 'M'
	   BEGIN
		   SET @IDBODEGA = @IDBODEGASOLI
	   END
   
      SELECT @IDTERCERO = HPRED.IDTERCEROCA 
      FROM   HPRED 
      WHERE  NOPRESTACION = @NOPRESTACION AND ISNULL(ANULADO,0) = 0 --SJUNCO REQ 1803
   
      /*AQUI SE MIRA A LA BODEGA  A LA QUE SE PIDE*/
      CREATE TABLE #PED_BOD (IDSERVICIO VARCHAR(20) COLLATE database_default, CANTIDAD DECIMAL(18,6), 
                             IDARTICULO VARCHAR(20) COLLATE database_default,
                             IDBODEGA01 VARCHAR(20) COLLATE database_default, EXISTENCIA01 DECIMAL(14,2), SINCONFIRMAR01 DECIMAL(14,2), EXISREAL01 DECIMAL(14,2))  
      INSERT INTO #PED_BOD (IDSERVICIO, CANTIDAD, IDARTICULO, IDBODEGA01, EXISTENCIA01, SINCONFIRMAR01, EXISREAL01 ) 
      SELECT HPRED.IDSERVICIO, HPRED.CANTIDAD, SER.IDARTICULO, @IDBODEGA,0 ,0 ,0
      FROM   HPRED INNER JOIN SER ON HPRED.IDSERVICIO = SER.IDSERVICIO 
      WHERE  HPRED.NOPRESTACION = @NOPRESTACION 
      AND    SER.IDARTICULO <> '' 
      AND    SER.IDARTICULO <> @IDINVARTNA 
      AND    ISNULL(HPRED.ANULADO,0) = 0 --SJUNCO REQ 1803
      AND    COALESCE(HPRED.CNSMOV,'')=''
   
      UPDATE #PED_BOD SET EXISTENCIA01 = COALESCE(B.EXISLOTE,0)
      FROM   #PED_BOD INNER JOIN ( SELECT COALESCE(SUM(IEXI.EXISLOTE),0) AS EXISLOTE, IEXI.IDARTICULO, IEXI.IDBODEGA
                                   FROM   IEXI
                                   WHERE  IEXI.FECHAVENCE     > GETDATE() 
                                   GROUP BY IEXI.IDARTICULO, IEXI.IDBODEGA
                                 ) B ON #PED_BOD.IDARTICULO = B.IDARTICULO
                                    AND #PED_BOD.IDBODEGA01 = B.IDBODEGA      

      UPDATE #PED_BOD SET SINCONFIRMAR01 = COALESCE(B.CANTPEDIDA ,0)
      FROM   #PED_BOD INNER JOIN ( SELECT COALESCE(SUM(IMOVH.CANTPEDIDA),0) AS CANTPEDIDA, IMOV.IDBODEGA, IMOVH.IDARTICULO 
                                   FROM   IMOVH INNER JOIN IMOV ON IMOVH.CNSMOV   = IMOV.CNSMOV 
                                                INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV 
                                   WHERE  IMOVH.ESTADO     = 0 
                                   AND    ITMO.TIPO        = 'Debito'
                                   GROUP BY IMOV.IDBODEGA, IMOVH.IDARTICULO
                                  ) B ON  #PED_BOD.IDBODEGA01 = B.IDBODEGA
                                     AND  #PED_BOD.IDARTICULO = B.IDARTICULO        
   
      UPDATE #PED_BOD SET EXISREAL01 = COALESCE(EXISTENCIA01 - SINCONFIRMAR01,0)
     
      IF COALESCE(@IDBODEGA2,'') <> '' AND @IDBODEGA2 <> @IDBODEGA
      BEGIN
         UPDATE #PED_BOD SET IDBODEGA01 = '', EXISREAL01 = 0, EXISTENCIA01 = 0, SINCONFIRMAR01 = 0
         WHERE  EXISREAL01 < CANTIDAD 
            
         UPDATE #PED_BOD SET EXISTENCIA01 = B.EXISLOTE 
         FROM   #PED_BOD INNER JOIN (SELECT COALESCE(SUM(IEXI.EXISLOTE),0) AS EXISLOTE, IEXI.IDBODEGA, IEXI.IDARTICULO
                                     FROM   IEXI
                                     WHERE  IEXI.FECHAVENCE     > GETDATE() 
                                     AND    IEXI.IDBODEGA = @IDBODEGA2 
                                     GROUP BY IEXI.IDBODEGA, IEXI.IDARTICULO
                                    ) B ON #PED_BOD.IDARTICULO = B.IDARTICULO
         WHERE  #PED_BOD.IDBODEGA01 = ''     
      
         UPDATE #PED_BOD SET SINCONFIRMAR01 = COALESCE(B.CANTPEDIDA,0) 
         FROM   #PED_BOD INNER JOIN ( SELECT COALESCE(SUM(IMOVH.CANTPEDIDA),0) AS CANTPEDIDA, IMOV.IDBODEGA, IMOVH.IDARTICULO 
                                      FROM   IMOVH INNER JOIN IMOV ON IMOVH.CNSMOV   = IMOV.CNSMOV 
                                                   INNER JOIN ITMO ON IMOV.IDTIPOMOV = ITMO.IDTIPOMOV 
                                      WHERE  IMOVH.ESTADO     = 0 
                                      AND    ITMO.TIPO        = 'Debito'
                                      AND    IMOV.IDBODEGA    = @IDBODEGA2
                                      GROUP BY IMOV.IDBODEGA, IMOVH.IDARTICULO
                                     ) B ON  #PED_BOD.IDARTICULO = B.IDARTICULO              
         WHERE  #PED_BOD.IDBODEGA01 = ''

         UPDATE #PED_BOD SET IDBODEGA01 = @IDBODEGA2 WHERE IDBODEGA01 = ''
      END
      UPDATE #PED_BOD SET EXISREAL01 = COALESCE(EXISTENCIA01 - SINCONFIRMAR01,0) WHERE IDBODEGA01 = @IDBODEGA2
      --UPDATE #PED_BOD SET IDBODEGA01 = '', EXISREAL01 = 0, EXISTENCIA01 = 0, SINCONFIRMAR01 = 0
      --WHERE  EXISREAL01 < CANTIDAD 
      --AND    IDBODEGA01 = @IDBODEGA2
   
      --SELECT * FROM #PED_BOD

      CREATE TABLE #TITAR (IDITAR VARCHAR(2))
      /***********************************************************/
      /* AQUI BUSCAMOS LAS BODEGAS Y HACEMOS CURSOR POR BODEGA   */
      /***********************************************************/
      DECLARE BOD_CURSOR CURSOR FOR  
      SELECT DISTINCT IDBODEGA01 FROM #PED_BOD
      OPEN  BOD_CURSOR  
      FETCH NEXT FROM BOD_CURSOR  
      INTO  @IDBODEGACUR
      WHILE @@FETCH_STATUS = 0  
      BEGIN     
        
         PRINT 'ANTES DE #TITAR'
         DELETE #TITAR
         IF DBO.FNK_VALORVARIABLE('IDINVENTRADAUNICA') = 'SI'
         BEGIN        
            INSERT INTO #TITAR (IDITAR) 
            SELECT DBO.FNK_VALORVARIABLE('IDINVIDITARUNICA')        
         END
         ELSE
         BEGIN
             INSERT INTO #TITAR(IDITAR)
             SELECT DISTINCT IART.IDITAR 
             FROM   #PED_BOD INNER JOIN IART ON #PED_BOD.IDARTICULO = IART.IDARTICULO
             WHERE  #PED_BOD.IDBODEGA01 = @IDBODEGACUR 
         END  
      
         SELECT @IDTIPOMOV = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOVPRE'
         SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
      
         SELECT @CODUNG =DBO.FNK_CODUNG_CODPRG(@USUARIO, 'CODUNG')
         SELECT @CODPRG =DBO.FNK_CODUNG_CODPRG(@USUARIO, 'CODPRG')
      
         DECLARE IMOV_CURSOR CURSOR FOR  
         SELECT IDITAR FROM #TITAR  
         OPEN  IMOV_CURSOR  
         FETCH NEXT FROM IMOV_CURSOR  
         INTO  @IDITAR
         WHILE @@FETCH_STATUS = 0  
         BEGIN  
            BEGIN TRAN
               SELECT @INSERTS = 0
               SELECT @UPDATES = 0
               EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MOV',@NVOCONSEC OUTPUT  
               SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
               PRINT '@NVOCONSEC='+@NVOCONSEC
               INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                                FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                                IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
                                OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                                CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                                USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                                SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP,CODUNG,CODPRG,CLASEPED)  
               SELECT @NVOCONSEC,@IDBODEGACUR ,@IDTIPOMOV, @NOADMISION, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                      @CCOSTO, @USUARIO, @IDTERCERO, @USUARIO, NULL, NULL, '0', NULL, NULL,
                      '',NULL, 0, @NOPRESTACION, @IDAREA,0, NULL, 'SALUD', @USUARIO,
                      NULL, NULL, 0, @IDAREAH, @NA, @SYS_COMPUTERNAME, 0, @IDITAR, @ESTRANSITO, NULL,@CODUNG,@CODPRG,
                      CASE WHEN COALESCE(@CLASEPED,'')='' THEN NULL ELSE @CLASEPED END
            
               INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                                 NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                                 CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                                 USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                                 CANTIDADORI, TIENECAMBIO, IDITAR,IDSERVICIO)
               SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, SUM(HPRED.CANTIDAD), IART.PCOSTO,  
                      MIN(HPRED.NOITEM), NULL ,0, NULL, NULL, NULL, NULL, MIN(HPRED.NOITEM), MAX(HPRED.VALOR), 
                      @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0, IART.IDITAR,HPRED.IDSERVICIO
               FROM   HPRED INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
                            INNER JOIN IART ON SER.IDARTICULO = IART.IDARTICULO
               WHERE  HPRED.NOPRESTACION = @NOPRESTACION 
               AND    SER.IDARTICULO <> '' 
               AND    SER.IDARTICULO <> @IDINVARTNA
               AND    COALESCE(HPRED.CNSMOV,'')=''
               AND    IART.IDITAR  = CASE DBO.FNK_VALORVARIABLE('IDINVENTRADAUNICA') 
                                      WHEN 'SI' THEN IART.IDITAR
                                      ELSE @IDITAR
                                     END
               AND    ISNULL(HPRED.ANULADO,0)=0 --SJUNCO REQ 1803
               AND    HPRED.IDSERVICIO IN (SELECT IDSERVICIO FROM #PED_BOD WHERE IDBODEGA01 = @IDBODEGACUR)
               GROUP BY SER.IDARTICULO, IART.EXISTOTAL, IART.PCOSTO,IART.IDITAR,HPRED.IDSERVICIO
               /*****************************************************************/
               /* INGRESO DEL NUMERO DE MOVIMIENTO DE INVENTARIO EN HPRED       */
               /*****************************************************************/
               UPDATE HPRED SET CNSMOV = @NVOCONSEC
               FROM   HPRED INNER JOIN SER  ON HPRED.IDSERVICIO   = SER.IDSERVICIO 
                            INNER JOIN IART ON SER.IDARTICULO     = IART.IDARTICULO
               WHERE  HPRED.NOPRESTACION = @NOPRESTACION 
               AND    SER.IDARTICULO <> '' 
               AND    SER.IDARTICULO <> @IDINVARTNA
               AND    IART.IDITAR  = CASE DBO.FNK_VALORVARIABLE('IDINVENTRADAUNICA')
                                      WHEN 'SI' THEN IART.IDITAR
                                      ELSE @IDITAR
                                     END
               AND    HPRED.IDSERVICIO IN (SELECT IDSERVICIO FROM #PED_BOD WHERE IDBODEGA01 = @IDBODEGACUR)
               AND    ISNULL(HPRED.ANULADO,0)=0 --SJUNCO REQ 1803
            
               SELECT @INSERTS = COALESCE(COUNT(*),0) FROM IMOVH WHERE CNSMOV = @NVOCONSEC
               SELECT @UPDATES = COALESCE(COUNT(*),0) FROM HPRED WHERE CNSMOV = @NVOCONSEC
               IF @INSERTS <> @UPDATES
               BEGIN
                  ROLLBACK TRAN
               END
               ELSE
               BEGIN
                  COMMIT TRAN
               END
            
               /*****************************************************************/
               /* CONFIRMACION AUTOMATICA DE INVENTARIOS                        */--COMENTARIADO JJIMENEZ--SOLO BODEGA VIRTRUAL
               /*****************************************************************/
               --SELECT @INVPIDEAUTOMQX = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'INVPIDEAUTOMQX'
               --IF @INVPIDEAUTOMQX = 'SI'
               --BEGIN
               --   EXEC SPK_CONFIRMARSALIDAS @IDBODEGACUR, @NVOCONSEC, @USUARIO, 	@COMPANIA, 	@SEDE
               --END
               --ELSE
               --BEGIN 
            
                  SELECT @CONFAUT = COALESCE(CONFIRMAAUTOMDESDEQX,0),@TIPOBODEGA=TIPOBODEGA FROM IBOD WHERE IDBODEGA = @IDBODEGACUR
                  IF @CONFAUT = 1 AND @TIPOBODEGA='Virtual'
                  BEGIN
                     PRINT'LLENA AUTOMATICA ISAL'
                     EXEC SPK_INSERTAISAL_AUT @IDBODEGACUR,@NVOCONSEC
                     PRINT 'CONFIRMA AUTOMATICO'
                     EXEC SPK_CONFIRMARSALIDAS @IDBODEGACUR, @NVOCONSEC, @USUARIO, @COMPANIA, @SEDE
                  END
               --END
              
               FETCH NEXT FROM IMOV_CURSOR  
               INTO @IDITAR   
         END   
         CLOSE IMOV_CURSOR  
         DEALLOCATE IMOV_CURSOR                                                                    
         FETCH NEXT FROM BOD_CURSOR  
         INTO  @IDBODEGACUR
      END
      CLOSE BOD_CURSOR
      DEALLOCATE BOD_CURSOR
      UPDATE HPRE SET PEDIDOINV = 1, CNSMOV=CASE WHEN COALESCE(CNSMOV,'')='' THEN  @NVOCONSEC ELSE CNSMOV END WHERE NOPRESTACION = @NOPRESTACION AND ISNULL(ANULADO,0)=0 --SJUNCO REQ 1803
      DROP TABLE #PED_BOD
      DROP TABLE #TITAR
   END
   ELSE
   BEGIN
      PRINT 'VOY PARA IZSOL E IZSOLD'
      SELECT @CNSIZSOL = ''
      EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOL', @CNSIZSOL OUTPUT  
      SELECT @CNSIZSOL = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOL))+LTRIM(RTRIM(@CNSIZSOL)),SPACE(1),0)  
      
      PRINT '@CNSIZSOL == '+@CNSIZSOL
      SELECT @SECTOR=SECTOR FROM HHAB WHERE NOADMISION=@NOADMISION

      IF ISNULL(@SECTOR,'')=''  --MNKR 8/02/2017: Sector cuando ya no tiene cama
      BEGIN
            SELECT TOP 1 @SECTOR=HABCAMA FROM HPRE INNER JOIN HHAB ON HPRE.IDAREA=HHAB.IDAREA AND HPRE.CCOSTO=HHAB.CCOSTO
            WHERE HPRE.NOPRESTACION=@NOPRESTACION AND HHAB.CLASE='Sector'
            PRINT 'AL NO TENER CAMA SE TOMARÁ EL SECTOR CORRESPONDIENTE AL IDAREA Y CCOSTO DE LA PRESTACIÓN. SECTOR='+@SECTOR
      END

      INSERT INTO IZSOL (CNSIZSOL, FECHASOL, USUARIOSOL, ESTADO, IDBODEGAATIENDE, SECTOR, CLASE, NOADMISION, CNSIZSOLM ,IDSEDE)
      SELECT @CNSIZSOL,  GETDATE(), @USUARIO, 1, @IDBODEGA, @SECTOR, 'HPRE', @NOADMISION, @NOPRESTACION ,@SEDE

      DECLARE @BANDERA INT
      DECLARE @LIMITE  INT
      SELECT @BANDERA=0,@LIMITE=0
      
      SELECT @LIMITE=MAX(NOITEM) FROM HPRED WHERE NOPRESTACION=@NOPRESTACION
   
      --WHILE @BANDERA<=@LIMITE
      --BEGIN
      --   SELECT @CNSIZSOLD = ''
      --   EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOLD', @CNSIZSOLD OUTPUT  
      --   SELECT @CNSIZSOLD = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOLD))+LTRIM(RTRIM(@CNSIZSOLD)),SPACE(1),0)  
      --   INSERT INTO IZSOLD (CNSIZSOLD , CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,IDPRINCIPIO) 
      --   SELECT @CNSIZSOLD,@CNSIZSOL,SER.IDARTICULO,HPRED.CANTIDAD,1,NULL,HPRED.CANTIDAD,24,0,0,0,24,HPRED.IDSERVICIO, IART.IDSERVICIO
      --   FROM HPRED INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
      --      LEFT JOIN IART ON IART.IDARTICULO=SER.IDARTICULO
      --   WHERE NOPRESTACION=@NOPRESTACION AND NOITEM=@BANDERA 
      
      --   SELECT @BANDERA=@BANDERA+1       
      --END

      INSERT INTO IZSOLD (CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,IDPRINCIPIO) 
      SELECT @CNSIZSOLD,SER.IDARTICULO,HPRED.CANTIDAD,1,NULL,HPRED.CANTIDAD,24,0,0,0,24,HPRED.IDSERVICIO, IART.IDSERVICIO
      FROM HPRED INNER JOIN SER ON HPRED.IDSERVICIO=SER.IDSERVICIO
         LEFT JOIN IART ON IART.IDARTICULO=SER.IDARTICULO
      WHERE NOPRESTACION=@NOPRESTACION 


	   SELECT @CONFAUT=CONFIRMAAUTOMDESDEQX, @TIPOBODEGA=TIPOBODEGA FROM IBOD WHERE IDBODEGA=@IDBODEGA
   IF @CONFAUT=1 AND @TIPOBODEGA='Virtual'
   BEGIN
      IF EXISTS (SELECT 1 FROM IZSOL WHERE CNSIZSOL=@CNSIZSOL)
      BEGIN
         PRINT 'VOY A CONFIRMAR AUTOMATICO....'
         EXEC SPK_INSERTA_IZOLDT_AUT @CNSIZSOL,@IDBODEGA,@SEDE,@USUARIO

		  UPDATE HPRE SET PEDIDOINV=1, CNSMOV=CASE WHEN COALESCE(CNSMOV,'')='' THEN @CNSIZSOL ELSE CNSMOV END 
		  WHERE NOPRESTACION=@NOPRESTACION AND ISNULL(ANULADO,0)=0 
      END
   END
   ELSE 
   BEGIN 
      UPDATE HPRE SET PEDIDOINV=1, CNSMOV=CASE WHEN COALESCE(CNSMOV,'')='' THEN @CNSIZSOL ELSE CNSMOV END 
      WHERE NOPRESTACION=@NOPRESTACION AND ISNULL(ANULADO,0)=0 
	  END
   END
END




