IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='SPK_PEDIDOINV_FMED' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_PEDIDOINV_FMED
END

GO
CREATE PROCEDURE DBO.SPK_PEDIDOINV_FMED
@NOCONSECUTIVO    VARCHAR(16),  
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @CUANTAS     INT
DECLARE @IDBODEGA    VARCHAR(20)
DECLARE @IDINVARTNA  VARCHAR(80)
DECLARE @NVOCONSEC   VARCHAR(20)
DECLARE @NOADMISION  VARCHAR(16)
DECLARE @IDITAR      VARCHAR(2)
DECLARE @IDTIPOMOV   VARCHAR(2)
DECLARE @CCOSTO      VARCHAR(20)
DECLARE @IDAREAH     VARCHAR(20)
DECLARE @IDAREA      VARCHAR(20)
DECLARE @NA          VARCHAR(5) 
DECLARE @ESTRANSITO  SMALLINT
DECLARE @OK          SMALLINT
DECLARE @IDTERCERO   VARCHAR(20)
DECLARE @PROCEDENCIA VARCHAR(10)
DECLARE @CNSIZSOL    VARCHAR(20)
DECLARE @SECTOR      VARCHAR(20)
DECLARE @CNSIZSOLD   VARCHAR(20)
BEGIN
   PRINT 'ENTRE A GENERAR PEDIDO DESDE FMED'
   SELECT @OK = COALESCE(PEDIDOINV,0) FROM FME WHERE NOCONSECUTIVO = @NOCONSECUTIVO
   IF @OK = 1
      BEGIN
         PRINT 'FORMULA MEDICA YA ESTA PEDIDA'
         RETURN
      END

   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'

   SELECT @CUANTAS = COUNT(*) FROM FMED, SER WHERE FMED.IDSERVICIO = SER.IDSERVICIO 
   AND FMED.NOCONSECUTIVO = @NOCONSECUTIVO
   AND SER.IDARTICULO <> '' 
   AND SER.IDARTICULO <> @IDINVARTNA

   IF COALESCE(@CUANTAS,0) = 0
      BEGIN 
         UPDATE FME SET PEDIDOINV = 1, CNSMOV =  'NO_ES_SER'
         WHERE NOCONSECUTIVO = @NOCONSECUTIVO
         RETURN
      END
  
   SELECT @NOADMISION = NOADMISION, @PROCEDENCIA = PROCEDENCIA FROM FME WHERE NOCONSECUTIVO = @NOCONSECUTIVO

	IF @PROCEDENCIA = 'QX'
	BEGIN
      SET @PROCEDENCIA = 'FORMEDASIS'
      SELECT @IDTERCERO = IDTERCERO FROM HADM WHERE NOADMISION = @NOADMISION
      SELECT @SECTOR=SECTOR FROM HHAB WHERE NOADMISION=@NOADMISION
	END	
	ELSE IF @PROCEDENCIA = 'HCCE'
	BEGIN
		SET @PROCEDENCIA = 'FORMEDCE'
		SELECT @IDTERCERO = IDADMINISTRADORA FROM AFI WHERE IDAFILIADO = @NOADMISION
	END
   
   SELECT @CCOSTO = CCOSTO FROM UBEQ WHERE SYS_COMPUTERNAME = @SYS_COMPUTERNAME

   CREATE TABLE #TITAR (IDITAR VARCHAR(2))
   
   INSERT INTO #TITAR(IDITAR)
   SELECT DISTINCT IART.IDITAR FROM FMED, SER, IART WHERE FMED.IDSERVICIO = SER.IDSERVICIO 
   AND FMED.NOCONSECUTIVO = @NOCONSECUTIVO
   AND SER.IDARTICULO <> '' 
   AND SER.IDARTICULO <> @IDINVARTNA
   AND SER.IDARTICULO = IART.IDARTICULO 
     
   SELECT @IDTIPOMOV = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOVPRE'
   SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
   --SELECT @IDBODEGA = DATO FROM USVGS WHERE IDVARIABLE = 'IDBODEGAFME'

   SELECT @IDBODEGA = IDBODEGALOG  FROM SED WHERE IDSEDE = @SEDE
   
   DECLARE IMOV_CURSOR CURSOR FOR  
   SELECT IDITAR FROM #TITAR  
   OPEN IMOV_CURSOR  
   FETCH NEXT FROM IMOV_CURSOR  
   INTO @IDITAR
   WHILE @@FETCH_STATUS = 0  
   BEGIN
      IF DBO.FNK_VALORVARIABLE('PEDIDOHPREAIZSOL')<>'SI'
      BEGIN   
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MOV',@NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                          FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                          IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
                          OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                          CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                          USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                          SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP, NOCONSECUTIVO)  
         SELECT @NVOCONSEC,@IDBODEGA,@IDTIPOMOV, @NOADMISION, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                @CCOSTO, @USUARIO, @IDTERCERO, @USUARIO, NULL, NULL, '0', NULL, NULL,
                '',NULL, 0, '', @IDAREA,0, NULL, @PROCEDENCIA, @USUARIO,
                NULL, NULL, 0, @IDAREAH, @NA, @SYS_COMPUTERNAME, 0, @IDITAR, @ESTRANSITO, NULL, @NOCONSECUTIVO
                
         INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                           NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                           CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                           USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                           CANTIDADORI, TIENECAMBIO,IDSERVICIO)
         SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, FMED.CANTIDAD, IART.PCOSTO,  
                FMED.NOITEM, NULL ,0, NULL, NULL, NULL, NULL, FMED.NOITEM, 0, 
                @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0,FMED.IDSERVICIO      
         FROM FMED, SER, IART 
         WHERE FMED.IDSERVICIO = SER.IDSERVICIO 
         AND FMED.NOCONSECUTIVO = @NOCONSECUTIVO
         AND SER.IDARTICULO <> '' 
         AND SER.IDARTICULO <> @IDINVARTNA
         AND SER.IDARTICULO = IART.IDARTICULO
         AND IART.IDITAR    = @IDITAR
         AND COALESCE(FMED.MEXTERNO,0)=0
           
         FETCH NEXT FROM IMOV_CURSOR  
         INTO @IDITAR
      END
      ELSE
      BEGIN
         PRINT 'VOY PARA IZSOL E IZSOLD'
         SELECT @CNSIZSOL = ''
         EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOL', @CNSIZSOL OUTPUT  
         SELECT @CNSIZSOL = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOL))+LTRIM(RTRIM(@CNSIZSOL)),SPACE(1),0)  
      
         PRINT '@CNSIZSOL == '+@CNSIZSOL

         INSERT INTO IZSOL (CNSIZSOL, FECHASOL, USUARIOSOL, ESTADO, IDBODEGAATIENDE, SECTOR, CLASE, NOADMISION, CNSIZSOLM )
         SELECT @CNSIZSOL,  DBO.FNK_FECHA_SIN_MLS(GETDATE()), @USUARIO, 1, @IDBODEGA, 'FORMULA', 'HPRE', @NOADMISION, @NOCONSECUTIVO

         DECLARE @BANDERA INT
         DECLARE @LIMITE  INT
         SELECT @BANDERA=1,@LIMITE=0
      
         SELECT @BANDERA=MIN(NOITEM),@LIMITE=MAX(NOITEM) FROM FMED WHERE NOCONSECUTIVO=@NOCONSECUTIVO AND COALESCE(FMED.MEXTERNO,0)=0
   
         --WHILE @BANDERA<=@LIMITE
         --BEGIN
         --   SELECT @CNSIZSOLD = ''
         --   EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOLD', @CNSIZSOLD OUTPUT  
         --   SELECT @CNSIZSOLD = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOLD))+LTRIM(RTRIM(@CNSIZSOLD)),SPACE(1),0)  
         --   INSERT INTO IZSOLD (CNSIZSOLD , CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,IDPRINCIPIO) 
         --   SELECT @CNSIZSOLD,@CNSIZSOL,SER.IDARTICULO,FMED.CANTIDAD,1,NULL,FMED.CANTIDAD,24,0,0,0,24,FMED.IDSERVICIO, IART.IDSERVICIO
         --   FROM FMED INNER JOIN SER ON FMED.IDSERVICIO=SER.IDSERVICIO
         --             LEFT JOIN IART ON IART.IDARTICULO=SER.IDARTICULO
         --   WHERE NOCONSECUTIVO=@NOCONSECUTIVO 
         --   AND NOITEM=@BANDERA 
         --   AND COALESCE(FMED.MEXTERNO,0)=0
      
         --   SELECT @BANDERA=@BANDERA+1   
         --END
         INSERT INTO IZSOLD ( CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,IDPRINCIPIO) 
         SELECT @CNSIZSOL,SER.IDARTICULO,FMED.CANTIDAD,1,NULL,FMED.CANTIDAD,24,0,0,0,24,FMED.IDSERVICIO, IART.IDSERVICIO
         FROM FMED INNER JOIN SER ON FMED.IDSERVICIO=SER.IDSERVICIO
                     LEFT JOIN IART ON IART.IDARTICULO=SER.IDARTICULO
         WHERE NOCONSECUTIVO=@NOCONSECUTIVO 
         AND COALESCE(FMED.MEXTERNO,0)=0

         FETCH NEXT FROM IMOV_CURSOR  
         INTO @IDITAR
      END 
   END  
   CLOSE IMOV_CURSOR  
   DEALLOCATE IMOV_CURSOR
   
   UPDATE FME SET PEDIDOINV = 1, CNSMOV =  @NVOCONSEC
   WHERE NOCONSECUTIVO = @NOCONSECUTIVO
END







