IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_PEDIDOINVHTX' AND type = 'P')
   DROP PROCEDURE SPK_PEDIDOINVHTX

GO
CREATE PROCEDURE DBO.SPK_PEDIDOINVHTX
@NOADMISION       VARCHAR(16),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254),
@RPDX             VARCHAR(20) = NULL,
@CLASEHTX         VARCHAR(2)  = 'NE',
@TIPOBOD_         VARCHAR(5)  = '',
@PRIORITARIO      BIT=0
WITH ENCRYPTION
AS
DECLARE @CUANTAS          INT
DECLARE @IDINVARTNA       VARCHAR(80)
DECLARE @NVOCONSEC        VARCHAR(20)
DECLARE @CNSHTX           VARCHAR(16)
DECLARE @IDITAR           VARCHAR(2)
DECLARE @IDTIPOMOV        VARCHAR(2)
DECLARE @CCOSTO           VARCHAR(20)
DECLARE @IDAREAH          VARCHAR(20)
DECLARE @IDAREA           VARCHAR(20)
DECLARE @NA               VARCHAR(5) 
DECLARE @ESTRANSITO       SMALLINT
DECLARE @OK               SMALLINT
DECLARE @IDTERCERO        VARCHAR(20)
DECLARE @TMB              VARCHAR(1)
DECLARE @IDBODEGA         VARCHAR(20)
DECLARE @IDBODEGA2        VARCHAR(20)
DECLARE @INVPIDEAUTOMQX   VARCHAR(20)
DECLARE @CONFAUT          SMALLINT
DECLARE @CODUNG           VARCHAR(5)
DECLARE @CODPRG           VARCHAR(20) 
DECLARE @FECHACARGO       DATETIME
DECLARE @IDPLAN           VARCHAR(6)
DECLARE @VALOR            DECIMAL(14,2)
DECLARE @IDSERVICIO       VARCHAR(20)
DECLARE @ESDEOTRAHADM     SMALLINT
DECLARE @LENADM           INT
DECLARE @NOADMISIONF      VARCHAR(16)
DECLARE @IDBODEGACUR      VARCHAR(20)
DECLARE @INSERTS          INT
DECLARE @UPDATES          INT
DECLARE @HTX_PIDEINV      VARCHAR(20)
DECLARE @INV_ARTGENERICO  VARCHAR(20)
DECLARE @TIPOBODEGA	      VARCHAR(10)
DECLARE @CNSIZSOL         VARCHAR(20)
DECLARE @SECTOR           VARCHAR(20)
DECLARE @CNSIZSOLD        VARCHAR(20)
DECLARE @IDARTICULO_CUR   VARCHAR(20)
DECLARE @CANTIDASOL       DECIMAL(14,2)
DECLARE @CANTIDHTX        DECIMAL(14,2)
DECLARE @CODOM_CUR        VARCHAR(20)
DECLARE @IDSERVICIOHTX    VARCHAR(20)
DECLARE @CNSHTX_CUR       VARCHAR(20)
DECLARE @IXCOUNTRY        VARCHAR(20)
DECLARE @CONSECUTIVOHCA   VARCHAR(20)
BEGIN
   SELECT @INV_ARTGENERICO = DBO.FNK_VALORVARIABLE('INV_ARTGENERICO') -- PARA LA NUEVA FORMA DE INVENTARIO
   SELECT @IXCOUNTRY=dbo.FNK_VALORVARIABLE('IXCOUNTRY')

   SELECT @ESDEOTRAHADM = 0
   SELECT @LENADM = LEN(IDSEDE) + 8 FROM HADM WHERE NOADMISION = @NOADMISION  
   SELECT @OK = COUNT(*)  FROM HTX 
   WHERE NOADMISION = @NOADMISION AND COALESCE(MARCAINV,0) = 1 AND COALESCE(HTX.SOLICITADO,0) = 0
   AND    HTX.CLASEHTX     = @CLASEHTX
   --AND    HTX.HOST_MPEDINV = @USUARIO
   IF @OK < 1
   BEGIN
      RETURN
   END
   
   PRINT 'INICIE NORMAL'
   
   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'
   SELECT @CUANTAS = COUNT(*) 
   FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO = SER.IDSERVICIO 
      INNER JOIN PRE ON PRE.PREFIJO=SER.PREFIJO
   WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0
   AND    HTX.HOST_MPEDINV = @USUARIO
   AND    HTX.CLASEHTX     = @CLASEHTX
   AND    SER.IDARTICULO <> '' 
   AND    SER.IDARTICULO <> @IDINVARTNA
   AND    (COALESCE(PRE.MINVENTARIOS,0)=1 OR COALESCE(SER.MEDICAMENTOS,0)=1)
   
   IF @CUANTAS = 0
   BEGIN     
      RETURN
   END
   
   PRINT 'PASE PEDIDO INV'
   
   SELECT @FECHACARGO = CONVERT(date,GETDATE())
   
   SELECT @HTX_PIDEINV = DBO.FNK_VALORVARIABLE('HTX_MODO_PIDEINV')
   IF @HTX_PIDEINV = 'KVOM'
   BEGIN
      PRINT 'MODO PEDIR A INVENTARIO = KVOM'
      UPDATE HTX SET CNSMOV = 'NO_APLICA', SOLICITADO = 1, CLASEANUINV = 0 
      FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO
      WHERE  HTX.NOADMISION = @NOADMISION AND COALESCE(HTX.MARCAINV,0) = 1 AND COALESCE(HTX.SOLICITADO,0) = 0
            --AND    HTX.HOST_MPEDINV = @USUARIO
      AND    HTX.CLASEHTX     = @CLASEHTX
      AND    SER.IDARTICULO <> '' 
      AND    SER.IDARTICULO <> @IDINVARTNA 
      
      RETURN     
   END
   
   -- SELECT @FECHACARGO = FECHAREQ, @IDSERVICIO = IDSERVICIO   
   -- FROM   HTX 
   -- WHERE  NOADMISION = @NOADMISION AND ISNULL(MARCAINV,0) = 1 AND HTX.SOLICITADO = 0
   
   /*SE DEBE CONSEGUIR CCOSTO,IDAREA, IDAREAH, NIVELATENCION POR AHORA LOS SACAREMOS DEL EQUIPO */
   -- @NA = NIVELATENCION NIVEL DE ATENCION NO TENGO DE DONDE SACARLO AUN   
   -- SE BUSCA EL MANEJO DE BODEGA PARA SABER LAS BODEGAS A LAS QUE ENVIA
   
   SELECT TOP 1 @CCOSTO = CCOSTO, @IDAREA = IDAREA
   FROM   HTX 
   WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(HTX.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0
   AND    HTX.CLASEHTX   = @CLASEHTX
   
   IF @TIPOBOD_ = 'APROV'
   BEGIN
      SELECT @IDBODEGA = dbo.FNK_VALORVARIABLE('IDBODEGA_APROV')
   END
   ELSE
   BEGIN
      SELECT @TMB = TIPOMANEJOBODEGA, @IDBODEGA = IDBODEGA, @IDBODEGA2 = IDBODEGA2
      FROM   UBEQ 
      WHERE  COMPANIA         = @COMPANIA
      AND    SYS_COMPUTERNAME = @SYS_COMPUTERNAME
       
      IF @TMB = 'A'     
      BEGIN
         SELECT @IDBODEGA = BODEGADIA, @IDBODEGA2 = BODEGADIA2 FROM AFU WHERE IDAREA = @IDAREA
      END
   END
   --ADD.JQUIROGA 20090623 - Venezuela. Manejar Bodega recibida en @IDBODEGASOLI desde Asistencial
   --IF DBO.FNK_VALORVARIABLE('PEDIRCARGOS_A_BODEGA') = 'SI' AND @IDBODEGASOLI <> ''
   --BEGIN
   --   SET @IDBODEGA = @IDBODEGASOLI
   --END
   

   SELECT @IDPLAN=MAX(IDPLAN) FROM HTX WHERE NOADMISION = @NOADMISION AND COALESCE(MARCAINV,0) = 1 AND COALESCE(HTX.SOLICITADO,0) = 0
   AND    HTX.CLASEHTX     = @CLASEHTX

   SELECT @IDTERCERO = HADM.IDTERCERO, @IDPLAN = (CASE WHEN ISNULL(@IDPLAN,'')='' THEN HADM.IDPLAN ELSE @IDPLAN END)
   FROM   HADM
   WHERE  NOADMISION = @NOADMISION 
   PRINT '@IDBODEGA=' + @IDBODEGA + ' // @IDBODEGA2=' + @IDBODEGA2
         

   CREATE TABLE #TITAR (IDITAR VARCHAR(2))
     
   PRINT 'ANTES DE #TITAR'
   
   IF DBO.FNK_VALORVARIABLE('IDINV_HTX_ENT_UNICA') = 'SI'
   BEGIN   
      INSERT INTO #TITAR (IDITAR) 
      SELECT DBO.FNK_VALORVARIABLE('IDINVIDITARUNICA')
   END
   ELSE
   BEGIN  
      INSERT INTO #TITAR(IDITAR)
      SELECT DISTINCT IART.IDITAR FROM HTX,SER,IART 
      WHERE  HTX.IDSERVICIO   = SER.IDSERVICIO 
      AND    HTX.NOADMISION   = @NOADMISION AND ISNULL(MARCAINV,0) = 1 AND HTX.SOLICITADO = 0
      --AND    HTX.HOST_MPEDINV = @USUARIO
      AND    HTX.CLASEHTX     = @CLASEHTX
      AND    SER.IDARTICULO  <> ''
      AND    SER.IDARTICULO  <> @IDINVARTNA
      AND    SER.IDARTICULO   = IART.IDARTICULO
   END  
      
   SELECT @IDTIPOMOV = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOVHTX'
   SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
      
   SELECT @CODUNG =DBO.FNK_CODUNG_CODPRG(@USUARIO, 'CODUNG')
   SELECT @CODPRG =DBO.FNK_CODUNG_CODPRG(@USUARIO, 'CODPRG')
   IF DBO.FNK_VALORVARIABLE('PEDIDOHPREAIZSOL')<>'SI'
   BEGIN   
      PRINT 'ANTES DE CURSOR'
      DECLARE IMOV_CURSOR CURSOR FOR  
      SELECT IDITAR FROM #TITAR  
      OPEN  IMOV_CURSOR  
      FETCH NEXT FROM IMOV_CURSOR  
      INTO  @IDITAR
      WHILE @@FETCH_STATUS = 0  
      BEGIN  
         BEGIN TRAN  
         SELECT @INSERTS = 0
         SELECT @UPDATES = 0  
         EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MOV',@NVOCONSEC OUTPUT  
         SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
         PRINT '@NVOCONSEC='+@NVOCONSEC
        
         INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                          FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                          IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
                          OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                          CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                          USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                          SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP,
                          CODUNG, CODPRG,CLASEPED)
         SELECT @NVOCONSEC,@IDBODEGA,@IDTIPOMOV, @NOADMISION, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                @CCOSTO, @USUARIO, @IDTERCERO, @USUARIO, NULL, NULL, '0', NULL, NULL,
                'HTX',NULL, 0, NULL, @IDAREA,0, NULL, 'HTX', @USUARIO,       ---- DEBO SABER QUE PROVIENE DE HTX
                NULL, NULL, 0, @IDAREAH, @NA, @SYS_COMPUTERNAME, 0, @IDITAR, @ESTRANSITO, NULL,@CODUNG,@CODPRG,'24H'
         PRINT 'PASE IMOV'
           
         PRINT '@IDINVARTNA='+@IDINVARTNA+'/@IDITAR='+@IDITAR
         PRINT '@IDTERCERO = '+@IDTERCERO+'/@IDPLAN='+@IDPLAN+'/@IDAREA='+@IDAREA+'/@FECHACARGO='+CAST(@FECHACARGO AS VARCHAR(20))
         INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                           NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                           CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                           USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                           CANTIDADORI, TIENECAMBIO, IDITAR,IDSERVICIO)
         SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, 
                CASE COALESCE(SER.MDOSIF,0) WHEN 1 THEN HTX.CANTIDADINV
                                            ELSE HTX.CANTIDAD
                END, 
                IART.PCOSTO,  
                HTX.CNSHTX, NULL ,0, NULL, NULL, NULL, NULL, NULL, dbo.FNK_VALORSERVICIO(@IDTERCERO, @IDPLAN, HTX.IDSERVICIO, @IDAREA, @FECHACARGO ,0), 
                @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0, IART.IDITAR,HTX.IDSERVICIO--, HTX.CNSHTX
         FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO , IART 
         WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(HTX.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0 AND ISNULL(HTX.CNSMOV,'') = ''
              --AND    HTX.HOST_MPEDINV = @USUARIO
         AND    HTX.CLASEHTX     = @CLASEHTX
         AND    SER.IDARTICULO   <> '' 
         AND    SER.IDARTICULO   <> @IDINVARTNA
         AND    SER.IDARTICULO   = IART.IDARTICULO
         AND    HTX.CNSHTX       = CASE WHEN COALESCE(HTX.MDOSIF,0) = 0 THEN  HTX.CNSHTX
                                        WHEN COALESCE(HTX.MDOSIF,0) = 1 THEN  CASE WHEN COALESCE(HTX.CANTIDADINV,0) > 0 THEN HTX.CNSHTX
                                                                                   ELSE 'KRYSTALOS9('
                                                                              END
                                   END      
         AND    IART.IDITAR     = CASE WHEN DBO.FNK_VALORVARIABLE('IDINV_HTX_ENT_UNICA') = 'SI' THEN IART.IDITAR ELSE @IDITAR END     
         --GROUP BY SER.IDARTICULO, IART.EXISTOTAL, IART.PCOSTO, HTX.IDSERVICIO, IART.IDITAR
            
         /*****************************************************************/
         /* INGRESO DEL NUMERO DE MOVIMIENTO DE INVENTARIO EN HTX         */
         /*****************************************************************/
         IF @IXCOUNTRY='PERU'
            UPDATE HTX SET CNSMOV = @NVOCONSEC, SOLICITADO = 1, CLASEANUINV = 0, MARCAINV = 0
            FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO , IART  
            WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(htx.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0  AND ISNULL(HTX.CNSMOV,'') = ''
            --AND    HTX.HOST_MPEDINV = @USUARIO
            AND    HTX.CLASEHTX     = @CLASEHTX
            AND    HTX.CNSHTX     = CASE WHEN COALESCE(HTX.MDOSIF,0) = 0 THEN  HTX.CNSHTX
                                          WHEN COALESCE(HTX.MDOSIF,0) = 1 THEN  CASE WHEN COALESCE(HTX.CANTIDADINV,0) > 0 THEN HTX.CNSHTX
                                                                                    ELSE 'KRYSTALOS9('
                                                                                END
                                    END      
            AND    SER.IDARTICULO <> '' 
            AND    SER.IDARTICULO <> @IDINVARTNA
            AND    SER.IDARTICULO =  IART.IDARTICULO
            AND    IART.IDITAR    =  CASE WHEN DBO.FNK_VALORVARIABLE('IDINV_HTX_ENT_UNICA') = 'SI' THEN IART.IDITAR ELSE @IDITAR END
         ELSE
            UPDATE HTX SET CNSMOV = @NVOCONSEC, SOLICITADO = 1, CLASEANUINV = 0
            FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO , IART  
            WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(htx.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0  AND ISNULL(HTX.CNSMOV,'') = ''
            --AND    HTX.HOST_MPEDINV = @USUARIO
            AND    HTX.CLASEHTX     = @CLASEHTX
            AND    HTX.CNSHTX     = CASE WHEN COALESCE(HTX.MDOSIF,0) = 0 THEN  HTX.CNSHTX
                                         WHEN COALESCE(HTX.MDOSIF,0) = 1 THEN  CASE WHEN COALESCE(HTX.CANTIDADINV,0) > 0 THEN HTX.CNSHTX
                                                                                    ELSE 'KRYSTALOS9('
                                                                               END
                                    END      
            AND    SER.IDARTICULO <> '' 
            AND    SER.IDARTICULO <> @IDINVARTNA
            AND    SER.IDARTICULO =  IART.IDARTICULO
            AND    IART.IDITAR    =  CASE WHEN DBO.FNK_VALORVARIABLE('IDINV_HTX_ENT_UNICA') = 'SI' THEN IART.IDITAR ELSE @IDITAR END
         COMMIT TRAN
      
             /***************************************************/
             /* VERIFICAR CONFIRMACION AUTOMATICA EN INVENTARIO SOLO PARA BODEGA VIRTUAL */
             /***************************************************/
          
         SELECT @CONFAUT = COALESCE(CONFIRMAAUTOMDESDEQX,0),@TIPOBODEGA=TIPOBODEGA FROM IBOD WHERE IDBODEGA = @IDBODEGA
      
         PRINT 'CONFIRMA AUTO= '+STR(@CONFAUT)
         PRINT 'TIPO BODEGA '+@TIPOBODEGA
      
         IF @CONFAUT = 1 AND @TIPOBODEGA='Virtual'
         BEGIN
            PRINT'LLENA AUTOMATICA ISAL'
            EXEC SPK_INSERTAISAL_AUT @IDBODEGA,@NVOCONSEC
            PRINT 'CONFIRMA AUTOMATICO'
            EXEC SPK_CONFIRMARSALIDAS @IDBODEGA, @NVOCONSEC, @USUARIO, @COMPANIA, @SEDE
         END
                  
         FETCH NEXT FROM IMOV_CURSOR  
         INTO @IDITAR
      END   
      CLOSE IMOV_CURSOR  
      DEALLOCATE IMOV_CURSOR 
   END
   ELSE
   BEGIN
      PRINT 'HTX A IZSOL...'
      SELECT @CNSIZSOL = ''
      EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOL', @CNSIZSOL OUTPUT  
      SELECT @CNSIZSOL = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOL))+LTRIM(RTRIM(@CNSIZSOL)),SPACE(1),0)  
      PRINT '@CNSIZSOL == '+@CNSIZSOL
      IF @IXCOUNTRY='PERU'
      BEGIN 
         SELECT @SECTOR=MAX(IDPLAN), @CONSECUTIVOHCA=MAX(CONSECUTIVOHCA) FROM HTX WHERE HTX.NOADMISION=@NOADMISION AND ISNULL(HTX.MARCAINV,0)=1 AND ISNULL(HTX.SOLICITADO,0)=0 AND ISNULL(HTX.CNSMOV,'')=''
      END
      ELSE
      BEGIN
         SELECT @SECTOR=SECTOR, @CONSECUTIVOHCA=NULL FROM HHAB WHERE NOADMISION=@NOADMISION
      END
            
      INSERT INTO IZSOL (CNSIZSOL, FECHASOL, USUARIOSOL, ESTADO, IDBODEGAATIENDE, SECTOR, CLASE, NOADMISION, CNSIZSOLM, CONSECUTIVOHCA, IDSEDE, IDPLAN, CODAZUL)
      SELECT @CNSIZSOL, DBO.FNK_FECHA_SIN_MLS(GETDATE()), @USUARIO, 1, @IDBODEGA, @SECTOR, 'HTX', @NOADMISION, NULL, @CONSECUTIVOHCA, @SEDE, @IDPLAN, @PRIORITARIO

	   --DECLARE PEDIDO_IZSOLD CURSOR FOR  
    --  SELECT  SER.IDARTICULO, CASE COALESCE(SER.MDOSIF,0) WHEN 1 THEN ISNULL(HTX.CANTIDADINV,HTX.CANTIDAD) ELSE HTX.CANTIDAD END, HTX.CODOM,HTX.CANTIDAD,HTX.IDSERVICIO,HTX.CNSHTX
    --  FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO  
    --     INNER JOIN PRE ON PRE.PREFIJO=SER.PREFIJO, IART
    --  WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(HTX.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0 AND ISNULL(HTX.CNSMOV,'') = ''
    --  AND    SER.IDARTICULO   <> '' 
    --  AND    SER.IDARTICULO   <> @IDINVARTNA
    --  AND    SER.IDARTICULO   = IART.IDARTICULO
    --  AND    HTX.CNSHTX       = CASE WHEN COALESCE(HTX.MDOSIF,0)=0 THEN  HTX.CNSHTX
    --                                   WHEN COALESCE(HTX.MDOSIF,0) = 1 THEN  CASE WHEN COALESCE(HTX.CANTIDADINV,0) > 0 THEN HTX.CNSHTX
    --                                                                             ELSE 'KRYSTALOS9('
    --                                                                       END
    --                             END           
	   --AND    (COALESCE(PRE.MINVENTARIOS,0)=1 OR COALESCE(SER.MEDICAMENTOS,0)=1)

    --  OPEN PEDIDO_IZSOLD    
	   --FETCH NEXT FROM PEDIDO_IZSOLD    
	   --INTO @IDARTICULO_CUR,@CANTIDASOL,@CODOM_CUR,@CANTIDHTX,@IDSERVICIOHTX,@CNSHTX_CUR
	   --WHILE @@FETCH_STATUS = 0    
	   --BEGIN 
    --     SELECT @CNSIZSOLD = ''
    --     EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOLD', @CNSIZSOLD OUTPUT  
    --     SELECT @CNSIZSOLD = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOLD))+LTRIM(RTRIM(@CNSIZSOLD)),SPACE(1),0)


    --     INSERT INTO IZSOLD(CNSIZSOLD, CNSIZSOL, IDARTICULO, CANTIDADSOL, ESTADO, CODOM, CANTIDAD, FRECUENCIA, NUMDOSIS, CANTIDADBOLO, QIMPREGNACION,
    --                        DURACION, IDSERVICIO, TIPOENT, CNSHBALI, TIPOM, IDPRINCIPIO, COBRADODY)
    --     SELECT  @CNSIZSOLD,@CNSIZSOL,@IDARTICULO_CUR,@CANTIDASOL,1,@CODOM_CUR,@CANTIDASOL,24,1,0,0,24,@IDSERVICIOHTX,NULL,@CNSHTX_CUR,NULL,NULL,NULL
         
    --     IF @IXCOUNTRY='PERU'
    --        UPDATE HTX SET CNSMOV = @CNSIZSOL, SOLICITADO = 1, CLASEANUINV=0, MARCAINV=0 WHERE CNSHTX=@CNSHTX_CUR
    --     ELSE
    --        UPDATE HTX SET CNSMOV = @CNSIZSOL, SOLICITADO = 1, CLASEANUINV=0 WHERE CNSHTX=@CNSHTX_CUR

	   --FETCH NEXT FROM PEDIDO_IZSOLD    
	   --INTO @IDARTICULO_CUR,@CANTIDASOL,@CODOM_CUR,@CANTIDHTX,@IDSERVICIOHTX,@CNSHTX_CUR
	   --END
	   --CLOSE PEDIDO_IZSOLD
	   --DEALLOCATE PEDIDO_IZSOLD

       INSERT INTO IZSOLD(CNSIZSOL, IDARTICULO, CANTIDADSOL, ESTADO, CODOM, CANTIDAD, FRECUENCIA, NUMDOSIS, CANTIDADBOLO, QIMPREGNACION,
                            DURACION, IDSERVICIO, TIPOENT, CNSHBALI, TIPOM, IDPRINCIPIO, COBRADODY)
      SELECT @CNSIZSOL, SER.IDARTICULO, CASE COALESCE(SER.MDOSIF,0) WHEN 1 THEN ISNULL(HTX.CANTIDADINV,HTX.CANTIDAD) ELSE HTX.CANTIDAD END,
          1, HTX.CODOM,HTX.CANTIDAD,24,1,0,0,24,HTX.IDSERVICIO,NULL,HTX.CNSHTX,NULL,NULL,NULL
      FROM   HTX INNER JOIN SER ON HTX.IDSERVICIO   = SER.IDSERVICIO  
         INNER JOIN PRE ON PRE.PREFIJO=SER.PREFIJO, IART
      WHERE  HTX.NOADMISION = @NOADMISION AND ISNULL(HTX.MARCAINV,0) = 1 AND ISNULL(HTX.SOLICITADO,0) = 0 AND ISNULL(HTX.CNSMOV,'') = ''
      AND    SER.IDARTICULO   <> '' 
      AND    SER.IDARTICULO   <> @IDINVARTNA
      AND    SER.IDARTICULO   = IART.IDARTICULO
      AND    HTX.CNSHTX       = CASE WHEN COALESCE(HTX.MDOSIF,0)=0 THEN  HTX.CNSHTX
                                       WHEN COALESCE(HTX.MDOSIF,0) = 1 THEN  CASE WHEN COALESCE(HTX.CANTIDADINV,0) > 0 THEN HTX.CNSHTX
                                                                                 ELSE 'KRYSTALOS9('
                                                                           END
                                 END           
	   AND    (COALESCE(PRE.MINVENTARIOS,0)=1 OR COALESCE(SER.MEDICAMENTOS,0)=1)

      UPDATE HTX SET CNSMOV = @CNSIZSOL, SOLICITADO = 1, CLASEANUINV=0, MARCAINV = CASE WHEN  @IXCOUNTRY='PERU' THEN 0 ELSE MARCAINV END
      FROM HTX INNER JOIN IZSOLD ON HTX.CNSHTX=IZSOLD.CNSHBALI
      WHERE IZSOLD.CNSIZSOL=@CNSIZSOL




            /***************************************************/
            /* VERIFICAR CONFIRMACION AUTOMATICA EN INVENTARIO SOLO PARA BODEGA VIRTUAL */
            /***************************************************/
          
      SELECT @CONFAUT = COALESCE(CONFIRMAAUTOMDESDEQX,0),@TIPOBODEGA=TIPOBODEGA FROM IBOD WHERE IDBODEGA = @IDBODEGA
      
      PRINT 'CONFIRMA AUTO= '+STR(@CONFAUT)
      PRINT 'TIPO BODEGA '+@TIPOBODEGA
      
      IF @CONFAUT = 1 AND @TIPOBODEGA='Virtual'
      BEGIN
         PRINT'CONFIRMA AUTOMATICO DESDE IZSOLD'
         EXEC SPK_INSERTA_IZOLDT_AUT @CNSIZSOL,@IDBODEGA,@SEDE,@USUARIO
      END
   END                                                                   
   DROP TABLE #TITAR
END

