IF EXISTS (SELECT name FROM sysobjects 
         WHERE name = 'SPK_PEDIDOINVCX' AND type = 'P')
   DROP PROCEDURE SPK_PEDIDOINVCX

GO
CREATE PROCEDURE DBO.SPK_PEDIDOINVCX 
@CONSECUTIVO      VARCHAR(13),
@ITEM             SMALLINT,
@IDBODEGA         VARCHAR(20),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @CUANTAS        INT
DECLARE @IDINVARTNA     VARCHAR(80)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDITAR         VARCHAR(2)
DECLARE @IDTIPOMOV      VARCHAR(2)
DECLARE @CCOSTO         VARCHAR(20)
DECLARE @IDAREAH        VARCHAR(20)
DECLARE @IDAREA         VARCHAR(20)
DECLARE @NA             VARCHAR(5) 
DECLARE @ESTRANSITO     SMALLINT
DECLARE @OK             SMALLINT
DECLARE @INVPIDEAUTOMQX VARCHAR(20)
DECLARE @TMB            VARCHAR(1)
DECLARE @IDBODEGA2      VARCHAR(20)
DECLARE @IDPROVEEDOR    VARCHAR(20)
DECLARE @CNSIZSOL       VARCHAR(20)
DECLARE @SECTOR         VARCHAR(20)
DECLARE @CNSIZSOLD      VARCHAR(20)
DECLARE @CLASEPED       VARCHAR(10)
BEGIN
   PRINT 'EMPIEZO.........'
   SELECT @OK = COUNT(1) FROM QXPCXI WHERE CONSECUTIVO = @CONSECUTIVO 
   AND  ISNULL(PEDIDOINV,0)=0 AND ITEM = @ITEM
   AND  ISNULL(MARCAINV,0) = 1 
   AND  CANTIDADEST > 0   
   
   IF @OK = 0
   BEGIN
      PRINT 'ME DEVUELVO DE PRIMERAS'
      RETURN
   END
   
   SELECT @OK = COUNT(1) FROM QXPCXI WHERE CONSECUTIVO=@CONSECUTIVO 
   AND ISNULL(CANTIDADDEV,0) > CANTIDADEST AND ITEM=@ITEM AND COALESCE(PEDIDOINV,0)<>1
   AND ISNULL(MARCAINV,0)=1
    
   IF @OK > 0
   BEGIN
      PRINT 'ME DEVUELVO DE segunda'
      RETURN 
   END
   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'
   
   SELECT @CUANTAS = COUNT(*) FROM QXPCXI,SER 
   WHERE QXPCXI.ARTICULO = SER.IDSERVICIO
   AND   QXPCXI.CONSECUTIVO = @CONSECUTIVO 
   AND   QXPCXI.ITEM = @ITEM
   AND   SER.IDARTICULO <> '' 
   AND   SER.IDARTICULO <> @IDINVARTNA
   AND   COALESCE(QXPCXI.PEDIDOINV,0) <> 1
   AND   ISNULL(MARCAINV,0) = 1
   AND   QXPCXI.CANTIDADEST > 0
   
   IF @CUANTAS = 0
   BEGIN
     PRINT 'ME DEVUELVO DE tercero'
      RETURN
   END


   PRINT 'PASE LOS RETURN........'
   SELECT @NOADMISION = NOADMISION, @CCOSTO = CCOSTO, @IDAREA = IDAREA, @IDAREAH = IDAREAH,
          @NA = NIVEL
   FROM QXPCX WHERE CONSECUTIVO = @CONSECUTIVO 
   /* B1- JEDM 05.SEP.2006 22:10 */
   -- SE BUSCA EL MANEJO DE BODEGA PARA SABER LAS BODEGAS A LAS QUE ENVIA
   SELECT @TMB = TIPOMANEJOBODEGA, @IDBODEGA = IDBODEGA, @IDBODEGA2 = IDBODEGA2 
   FROM   UBEQ 
   WHERE  COMPANIA = @COMPANIA
   AND    SYS_COMPUTERNAME = @SYS_COMPUTERNAME
   
   IF @TMB = 'A'     
   BEGIN
      SELECT @IDBODEGA = BODEGADIA, @IDBODEGA2 = BODEGADIA2 FROM AFU WHERE
      IDAREA = @IDAREA
   END
   /* B1 */

   SELECT @IDPROVEEDOR = IDPROVEEDOR FROM QXPCXD WHERE CONSECUTIVO = @CONSECUTIVO 

 
    CREATE TABLE #TITAR (IDITAR VARCHAR(2))
   
    IF DBO.FNK_VALORVARIABLE('IDINVENTRADAUNICA') = 'SI' 
    BEGIN
       INSERT INTO #TITAR (IDITAR )
       SELECT DBO.FNK_VALORVARIABLE('IDINVIDITARUNICA') AS IDITAR
    END
    ELSE
    BEGIN
       INSERT INTO #TITAR(IDITAR)
       SELECT DISTINCT IART.IDITAR FROM QXPCXI,SER,IART WHERE QXPCXI.ARTICULO = SER.IDSERVICIO 
       AND QXPCXI.CONSECUTIVO = @CONSECUTIVO 
       AND QXPCXI.ITEM = @ITEM
       AND SER.IDARTICULO <> '' 
       AND SER.IDARTICULO <> @IDINVARTNA
       AND SER.IDARTICULO = IART.IDARTICULO 
       AND COALESCE(QXPCXI.PEDIDOINV,0) <> 1
       AND ISNULL(MARCAINV,0) = 1
       AND QXPCXI.CANTIDADEST > 0
    END
      
   SELECT @IDTIPOMOV = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOVPRE'
   SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
   
   CREATE TABLE #TIMOVH(CNSMOV VARCHAR(20), IDARTICULO VARCHAR(20), EXISTENCIA DECIMAL(14,2),
                  CANTIDAD DECIMAL(14,2), CANTPEDIDA DECIMAL(14,2), PCOSTO DECIMAL(14,2),
                  ITEM INT IDENTITY, PVENTA DECIMAL(14,2), IDITAR VARCHAR(2),IDSERVICIO VARCHAR(20)) 
   IF DBO.FNK_VALORVARIABLE('PEDIDOHPREAIZSOL')<>'SI'
   BEGIN
       PRINT 'VARIABLE DIFERENTE A SI ' 
      DECLARE IMOV_CURSOR CURSOR FOR  
      SELECT IDITAR FROM #TITAR  
      OPEN IMOV_CURSOR  
      FETCH NEXT FROM IMOV_CURSOR  
      INTO @IDITAR
      WHILE @@FETCH_STATUS = 0  
      BEGIN  
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MOV',@NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

            PRINT '@NVOCONSEC = '+@NVOCONSEC

            INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                             FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                             IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
                             OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                             CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                             USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                             SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP)  
            SELECT @NVOCONSEC,@IDBODEGA,@IDTIPOMOV, @NOADMISION, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                   @CCOSTO, @USUARIO, @IDPROVEEDOR, @USUARIO, NULL, NULL, '0', NULL, NULL,
                   '',NULL, 0, @CONSECUTIVO, @IDAREA,0, NULL, 'QXCX', @USUARIO,
                   NULL, NULL, 0, @IDAREAH, @NA, @SYS_COMPUTERNAME, 0, @IDITAR, @ESTRANSITO, NULL
         
            DELETE FROM #TIMOVH
            INSERT INTO #TIMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                                PVENTA, IDITAR,IDSERVICIO )
            SELECT @NVOCONSEC, SER.IDARTICULO, COALESCE(IART.EXISTOTAL,0), 0, COALESCE(QXPCXI.CANTIDADEST,0), 
                   COALESCE(IART.PCOSTO,0), COALESCE(QXPCXI.VALOR,0), IART.IDITAR,SER.IDSERVICIO
            FROM   QXPCXI, SER, IART 
            WHERE  QXPCXI.ARTICULO = SER.IDSERVICIO 
            AND    QXPCXI.CONSECUTIVO = @CONSECUTIVO 
            AND    QXPCXI.ITEM = @ITEM
            AND    SER.IDARTICULO <> '' 
            AND    SER.IDARTICULO <> @IDINVARTNA
            AND    SER.IDARTICULO = IART.IDARTICULO
            AND    IART.IDITAR  = CASE DBO.FNK_VALORVARIABLE('IDINVENTRADAUNICA') 
                                   WHEN 'SI' THEN IART.IDITAR
                                   ELSE @IDITAR
                                  END
            AND COALESCE(QXPCXI.PEDIDOINV,0) <> 1
            AND ISNULL(MARCAINV,0) = 1
            AND QXPCXI.CANTIDADEST > 0
         
            INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                              NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                              CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                              USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                              CANTIDADORI, TIENECAMBIO, IDITAR,IDSERVICIO)
            SELECT @NVOCONSEC, #TIMOVH.IDARTICULO, #TIMOVH.EXISTENCIA, 0, #TIMOVH.CANTPEDIDA, 
                   #TIMOVH.PCOSTO, #TIMOVH.ITEM, NULL ,0, NULL, NULL, NULL, NULL, 
                   @ITEM, #TIMOVH.PVENTA, @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0, #TIMOVH.IDITAR,#TIMOVH.IDSERVICIO     
            FROM #TIMOVH
            PRINT 'VOY A ACTUALIZAR...'
            UPDATE QXPCXI SET PEDIDOINV = 1, PCOSTO = IART.PCOSTO,CNSMOV=@NVOCONSEC
            FROM   SER, IART 
            WHERE  QXPCXI.ARTICULO    = SER.IDSERVICIO 
            AND    QXPCXI.CONSECUTIVO = @CONSECUTIVO 
            AND    QXPCXI.ITEM        = @ITEM
            AND    SER.IDARTICULO    <> '' 
            AND    SER.IDARTICULO    <> @IDINVARTNA
            AND    SER.IDARTICULO     = IART.IDARTICULO
            AND    IART.IDITAR  = CASE DBO.FNK_VALORVARIABLE('IDINVENTRADAUNICA') 
                                   WHEN 'SI' THEN IART.IDITAR
                                   ELSE @IDITAR
                                  END
            AND    COALESCE(QXPCXI.PEDIDOINV,0) <> 1
            AND ISNULL(MARCAINV,0) = 1
            AND    QXPCXI.CANTIDADEST > 0
         
            SELECT @INVPIDEAUTOMQX = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'INVPIDEAUTOMQX'

            IF @INVPIDEAUTOMQX = 'SI'
            BEGIN
               EXEC SPK_CONFIRMARSALIDAS @IDBODEGA, @NVOCONSEC, @USUARIO, 	@COMPANIA, 	@SEDE
            END 
            FETCH NEXT FROM IMOV_CURSOR  
            INTO @IDITAR  
      END  
      CLOSE IMOV_CURSOR  
      DEALLOCATE IMOV_CURSOR                                                                    
	END                                                                   
	ELSE
	BEGIN
      PRINT 'VOY PARA IZSOL E IZSOLD'
      SELECT @IDBODEGA=DBO.FNK_BUSCA_BODEGA_IZSOL(@SEDE,@SECTOR)
      DELETE FROM #TIMOVH
      INSERT INTO #TIMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
					      PVENTA, IDITAR,IDSERVICIO )
      SELECT @NVOCONSEC, SER.IDARTICULO, COALESCE(IART.EXISTOTAL,0), 0, COALESCE(QXPCXI.CANTIDADEST,0), 
	      COALESCE(IART.PCOSTO,0), COALESCE(QXPCXI.VALOR,0), IART.IDITAR,SER.IDSERVICIO
      FROM   QXPCXI, SER, IART 
      WHERE  QXPCXI.ARTICULO = SER.IDSERVICIO 
      AND    QXPCXI.CONSECUTIVO = @CONSECUTIVO 
      AND    QXPCXI.ITEM = @ITEM
      AND    SER.IDARTICULO <> '' 
      AND    SER.IDARTICULO <> @IDINVARTNA
      AND    SER.IDARTICULO = IART.IDARTICULO
      AND COALESCE(QXPCXI.PEDIDOINV,0) <> 1
      AND QXPCXI.CANTIDADEST > 0
      AND ISNULL(QXPCXI.MARCAINV,0)=1

      SELECT @CNSIZSOL = ''
      EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOL', @CNSIZSOL OUTPUT  
      SELECT @CNSIZSOL = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOL))+LTRIM(RTRIM(@CNSIZSOL)),SPACE(1),0)  
      
      PRINT '@CNSIZSOL == '+@CNSIZSOL
      SELECT  @SECTOR=SECTOR FROM HHAB WHERE  NOADMISION=@NOADMISION

      INSERT INTO IZSOL (CNSIZSOL, FECHASOL, USUARIOSOL, ESTADO, IDBODEGAATIENDE, SECTOR, CLASE, NOADMISION, CNSIZSOLM )
      SELECT @CNSIZSOL,  DBO.FNK_FECHA_SIN_MLS(GETDATE()), @USUARIO, 1, @IDBODEGA, @SECTOR, 'QXPGCX', @NOADMISION, @CONSECUTIVO

      DECLARE @BANDERA INT
      DECLARE @LIMITE  INT
      SELECT @BANDERA=1,@LIMITE=0
      
      SELECT @LIMITE=COUNT(*) FROM #TIMOVH
   
     -- WHILE @BANDERA<=@LIMITE
     -- BEGIN
     --    SELECT @CNSIZSOLD = ''
     --    EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOLD', @CNSIZSOLD OUTPUT  
     --    SELECT @CNSIZSOLD = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOLD))+LTRIM(RTRIM(@CNSIZSOLD)),SPACE(1),0)  
     --    INSERT INTO IZSOLD (CNSIZSOLD , CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,CNSHBALI,IDPRINCIPIO) 
     --    SELECT @CNSIZSOLD,@CNSIZSOL,A.IDARTICULO,A.CANTPEDIDA,1,NULL,A.CANTPEDIDA,24,0,0,0,24,A.IDSERVICIO,@CONSECUTIVO,IART.IDSERVICIO
     --    FROM #TIMOVH A
     --       LEFT JOIN IART ON IART.IDARTICULO COLLATE DATABASE_DEFAULT=A.IDARTICULO COLLATE DATABASE_DEFAULT
		   --WHERE ITEM=@BANDERA 
      
     --    SELECT @BANDERA=@BANDERA+1       
     -- END
      INSERT INTO IZSOLD ( CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,CNSHBALI,IDPRINCIPIO) 
      SELECT @CNSIZSOL,A.IDARTICULO,A.CANTPEDIDA,1,NULL,A.CANTPEDIDA,24,0,0,0,24,A.IDSERVICIO,@CONSECUTIVO,IART.IDSERVICIO
      FROM #TIMOVH A
         LEFT JOIN IART ON IART.IDARTICULO COLLATE DATABASE_DEFAULT=A.IDARTICULO COLLATE DATABASE_DEFAULT


      UPDATE QXPCXI SET PEDIDOINV = 1, PCOSTO = IART.PCOSTO,CNSMOV=@CNSIZSOL
      FROM   SER, IART 
      WHERE  QXPCXI.ARTICULO    = SER.IDSERVICIO 
      AND    QXPCXI.CONSECUTIVO = @CONSECUTIVO 
      AND    QXPCXI.ITEM        = @ITEM
      AND    SER.IDARTICULO    <> '' 
      AND    SER.IDARTICULO    <> @IDINVARTNA
      AND    SER.IDARTICULO     = IART.IDARTICULO
      AND    COALESCE(QXPCXI.PEDIDOINV,0) <> 1
      AND    QXPCXI.CANTIDADEST > 0
      AND    ISNULL(QXPCXI.MARCAINV,0)=1
   END
END

