IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME= 'SPK_PEDIDOINVCE' AND TYPE='P')
BEGIN
   DROP PROCEDURE SPK_PEDIDOINVCE
END

GO
CREATE PROCEDURE DBO.SPK_PEDIDOINVCE
@IDAUT    VARCHAR(16),
@IDBODEGA VARCHAR(20),
@COMPANIA VARCHAR(2),
@SEDE     VARCHAR(5),
@USUARIO  VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @CUANTAS    INT
DECLARE @IDINVARTNA VARCHAR(80)
DECLARE @NVOCONSEC  VARCHAR(20)
--DECLARE @IDAUT    VARCHAR(16)
DECLARE @IDITAR     VARCHAR(2)
DECLARE @IDTIPOMOV  VARCHAR(2)
DECLARE @CCOSTO     VARCHAR(20)
DECLARE @IDAREAH    VARCHAR(20)
DECLARE @IDAREA     VARCHAR(20)
DECLARE @NA         VARCHAR(5) 
DECLARE @ESTRANSITO SMALLINT
DECLARE @PEDIDOINV SMALLINT
DECLARE @IDAFILIADO VARCHAR(20)
DECLARE @NOAUT      VARCHAR(16)
DECLARE @IDPROVEEDOR VARCHAR(20)
DECLARE @IDSOLICITANTE VARCHAR(20)
DECLARE @DATO       VARCHAR(20)
DECLARE @CODUNG VARCHAR(2)
DECLARE @CODPRG VARCHAR(2)
DECLARE @CNSIZSOL         VARCHAR(20)
DECLARE @SECTOR           VARCHAR(20)
DECLARE @CNSIZSOLD        VARCHAR(20)
DECLARE @IDARTICULO_CUR   VARCHAR(20)
DECLARE @CANTIDASOL       DECIMAL(14,2)
DECLARE @CANTIDHTX        DECIMAL(14,2)
DECLARE @CODOM_CUR        VARCHAR(20)
DECLARE @IDSERVICIOHTX    VARCHAR(20)
DECLARE @CNSHTX_CUR       VARCHAR(20)
DECLARE @CONFAUT          SMALLINT
DECLARE @TIPOBODEGA	      VARCHAR(10)
DECLARE @CNSFMED          VARCHAR(20)
DECLARE @SOLOIART		  BIT
BEGIN
   SELECT @PEDIDOINV=PEDIDOINV, @NOAUT=NOAUT, @IDAFILIADO=IDAFILIADO, @IDPROVEEDOR=IDPROVEEDOR, 
		@IDSOLICITANTE=IDSOLICITANTE, @CODUNG=CODUNG, @CODPRG=CODPRG
   FROM AUT WHERE IDAUT = @IDAUT

   IF @PEDIDOINV = 1
   BEGIN
		IF (SELECT DATO FROM USVGS WHERE IDVARIABLE='PEDIDOHPREAIZSOL')<>'SI'
			UPDATE IMOV SET ESTADO=2 WHERE ESTADO=0 AND NODOCUMENTO=@NOAUT AND PROCEDENCIA='CE'
		ELSE
			UPDATE IZSOL SET ESTADO=0 WHERE CLASE='CE' AND IDSEDE=@SEDE AND NOADMISION=@IDAUT
				AND NOT EXISTS (SELECT 1 FROM IMOV WHERE PROCEDENCIA='CM_SOL' AND ESTADO IN (0,1) AND IZSOL.CNSIZSOL=IMOV.NODOCUMENTO)

		UPDATE AUT SET PEDIDOINV=0 WHERE IDAUT=@IDAUT
      RETURN
   END

   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'
   SELECT @DATO = DATO FROM USVGS WHERE IDVARIABLE = 'CETIPOAUTORIZACION'
   IF @DATO = 'CEHOSP'
   BEGIN
      SELECT @CUANTAS = COUNT(*) FROM AUTD,SER WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
      AND AUTD.IDAUT = @IDAUT 
      AND SER.IDARTICULO <> '' 
      AND SER.IDARTICULO <> @IDINVARTNA  
      AND SER.SPD = 1
   END
   ELSE
   BEGIN
      SELECT @CUANTAS = COUNT(*) FROM AUTD,SER WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
      AND AUTD.IDAUT = @IDAUT 
      AND SER.IDARTICULO <> '' 
      AND SER.IDARTICULO <> @IDINVARTNA
   END
   
   IF @CUANTAS = 0
   BEGIN
      PRINT 'NO ENCONTRE NADA QUE ENVIAR A IVENTARIO'
      RETURN
   END
   
   SELECT @IDAUT = IDAUT, @CCOSTO = CCOSTO, @IDAREA = IDAREA, @IDAREAH = IDAREA,
          @NA = NIVELATENCION
   FROM AUT WHERE IDAUT = @IDAUT
   
   IF DBO.FNK_VALORVARIABLE('PEDIDOHPREAIZSOL')<>'SI'
   BEGIN
      CREATE TABLE #TITAR (IDITAR VARCHAR(2))
   
      IF @DATO = 'CEHOSP'
      BEGIN
       IF DBO.FNK_VALORVARIABLE('TIPOITARUNICO')='SI'
         INSERT INTO #TITAR(IDITAR)
         SELECT MAX( IART.IDITAR )FROM AUTD, SER, IART WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
         AND AUTD.IDAUT = @IDAUT 
         AND SER.IDARTICULO <> '' 
         AND SER.IDARTICULO <> @IDINVARTNA
         AND SER.IDARTICULO = IART.IDARTICULO       
         AND SER.SPD= 1
	     ELSE
	     INSERT INTO #TITAR(IDITAR)
         SELECT DISTINCT IART.IDITAR FROM AUTD, SER, IART WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
         AND AUTD.IDAUT = @IDAUT 
         AND SER.IDARTICULO <> '' 
         AND SER.IDARTICULO <> @IDINVARTNA
         AND SER.IDARTICULO = IART.IDARTICULO       
         AND SER.SPD        = 1
	  
      END
      ELSE
      BEGIN
         INSERT INTO #TITAR(IDITAR)
         SELECT DISTINCT IART.IDITAR FROM AUTD,SER,IART WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
         AND AUTD.IDAUT = @IDAUT 
         AND SER.IDARTICULO <> '' 
         AND SER.IDARTICULO <> @IDINVARTNA
         AND SER.IDARTICULO = IART.IDARTICULO 
      END
      SELECT @IDTIPOMOV = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOVAUT'
      SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
   
      DECLARE IMOV_CURSOR CURSOR FOR  
      SELECT IDITAR FROM #TITAR  
      OPEN IMOV_CURSOR  
      FETCH NEXT FROM IMOV_CURSOR  
      INTO @IDITAR
      WHILE @@FETCH_STATUS = 0  
   
      BEGIN  
            EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MOV',@NVOCONSEC OUTPUT  
            SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)
            INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
                             FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
                             IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, CNSTRAN,
                             OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
                             CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
                             USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
                             SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP,CODUNG,CODPRG)  
            SELECT @NVOCONSEC,@IDBODEGA,@IDTIPOMOV, @NOAUT, NULL, DBO.FNK_FECHA_SIN_MLS(GETDATE()),
                   @CCOSTO, @IDSOLICITANTE,@IDPROVEEDOR, @USUARIO, @IDAFILIADO, NULL, '0', NULL, NULL,
                   '',NULL, 0, NULL, @IDAREA,0, NULL, 'CE', @USUARIO,
                   NULL, NULL, 0, @IDAREAH, @NA, @SYS_COMPUTERNAME, 0, @IDITAR, @ESTRANSITO, NULL,@CODUNG,@CODPRG
   

         
            IF @DATO = 'CEHOSP'
            BEGIN
		      IF   DBO.FNK_VALORVARIABLE('TIPOITARUNICO')='SI' 

               INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                              NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                              CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                              USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                              CANTIDADORI, TIENECAMBIO,IDSERVICIO)
               SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, AUTD.CANTIDAD, IART.PCOSTO,  
                   '', NULL ,0, NULL, NULL, NULL, NULL, AUTD.NO_ITEM, AUTD.VALOR, 
                   @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0,AUTD.IDSERVICIO     
               FROM AUTD, SER, IART 
               WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
               AND AUTD.IDAUT = @IDAUT 
               AND SER.IDARTICULO <> '' 
               AND SER.IDARTICULO <> @IDINVARTNA
               AND SER.IDARTICULO = IART.IDARTICULO
               AND SER.SPD = 1
			   ELSE
			    INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                              NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                              CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                              USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                              CANTIDADORI, TIENECAMBIO,IDSERVICIO)
               SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, AUTD.CANTIDAD, IART.PCOSTO,  
                   '', NULL ,0, NULL, NULL, NULL, NULL, AUTD.NO_ITEM, AUTD.VALOR, 
                   @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0,AUTD.IDSERVICIO     
               FROM AUTD, SER, IART 
               WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
               AND AUTD.IDAUT = @IDAUT 
               AND SER.IDARTICULO <> '' 
               AND SER.IDARTICULO <> @IDINVARTNA
               AND SER.IDARTICULO = IART.IDARTICULO
               AND IART.IDITAR    = @IDITAR
               AND SER.SPD = 1
            END
            ELSE
            BEGIN
               INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
                              NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
                              CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
                              USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
                              CANTIDADORI, TIENECAMBIO,IDSERVICIO)
               SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, AUTD.CANTIDAD, IART.PCOSTO,  
                   '', NULL ,0, NULL, NULL, NULL, NULL, AUTD.NO_ITEM, AUTD.VALOR, 
                   @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0,AUTD.IDSERVICIO    
               FROM AUTD, SER, IART 
               WHERE AUTD.IDSERVICIO = SER.IDSERVICIO 
               AND AUTD.IDAUT = @IDAUT 
               AND SER.IDARTICULO <> '' 
               AND SER.IDARTICULO <> @IDINVARTNA
               AND SER.IDARTICULO = IART.IDARTICULO
               AND IART.IDITAR    = @IDITAR
            END
           
            FETCH NEXT FROM IMOV_CURSOR  
            INTO @IDITAR  
      END  
      CLOSE IMOV_CURSOR  
      DEALLOCATE IMOV_CURSOR                                                                    
   END
   ELSE
   BEGIN
     PRINT 'HTX A IZSOL...'
      SELECT @CNSIZSOL = ''
      EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOL', @CNSIZSOL OUTPUT  
      SELECT @CNSIZSOL = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOL))+LTRIM(RTRIM(@CNSIZSOL)),SPACE(1),0)  
      PRINT '@CNSIZSOL == '+@CNSIZSOL
      SELECT @SECTOR = ''
            
      INSERT INTO IZSOL (CNSIZSOL, FECHASOL, USUARIOSOL, SYS_COMPUTER, ESTADO, IDBODEGAATIENDE, SECTOR, CLASE, NOADMISION, CNSIZSOLM,CONSECUTIVOHCA,IDSEDE )
      SELECT @CNSIZSOL, DBO.FNK_FECHA_SIN_MLS(GETDATE()), @USUARIO, @SYS_COMPUTERNAME, 1, @IDBODEGA, @SECTOR, 'CE', @IDAUT, NULL,NULL,@SEDE

	   --DECLARE PEDIDO_IZSOLD CURSOR FOR  
  --    SELECT  COALESCE(AUTD.IDARTICULO,SER.IDARTICULO),
		-- AUTD.CANTIDAD, '01',AUTD.CANTIDAD, COALESCE(AUTD.IDARTICULO,AUTD.IDSERVICIO), AUTD.IDAUT,AUTD.CNSFMED,
		-- (CASE WHEN COALESCE(AUTD.IDARTICULO,'') NOT IN (SER.IDARTICULO,'') THEN 1 ELSE 0 END)
  --    FROM   AUTD 
		--INNER JOIN SER ON AUTD.IDSERVICIO   = SER.IDSERVICIO 
		--INNER JOIN IART ON SER.IDARTICULO   = IART.IDARTICULO   
  --    WHERE  AUTD.IDAUT = @IDAUT
  --    AND    SER.IDARTICULO   <> '' 
  --    AND    SER.IDARTICULO   <> @IDINVARTNA 
	  
	   --OPEN PEDIDO_IZSOLD    
	   --FETCH NEXT FROM PEDIDO_IZSOLD    
	   --INTO @IDARTICULO_CUR,@CANTIDASOL,@CODOM_CUR,@CANTIDHTX,@IDSERVICIOHTX,@CNSHTX_CUR,@CNSFMED,@SOLOIART
	   --WHILE @@FETCH_STATUS = 0    
	   --BEGIN 
    --     SELECT @CNSIZSOLD = ''
    --     EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOLD', @CNSIZSOLD OUTPUT  
    --     SELECT @CNSIZSOLD = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOLD))+LTRIM(RTRIM(@CNSIZSOLD)),SPACE(1),0)


   --      INSERT INTO IZSOLD(CNSIZSOLD, CNSIZSOL, IDARTICULO, CANTIDADSOL, ESTADO, CODOM, CANTIDAD, FRECUENCIA, NUMDOSIS, CANTIDADBOLO, QIMPREGNACION,
   --                         DURACION, IDSERVICIO, TIPOENT, CNSHBALI, TIPOM, IDPRINCIPIO, COBRADODY,OPTI,CNSFMED)
   --      SELECT  @CNSIZSOLD,@CNSIZSOL,@IDARTICULO_CUR,@CANTIDASOL,1,@CODOM_CUR,@CANTIDASOL,24,1,0,0,24,@IDSERVICIOHTX,NULL,@CNSHTX_CUR,NULL,
			--IIF(@SOLOIART=1,@IDARTICULO_CUR,(SELECT IDSERVICIO FROM IART WHERE IDARTICULO=@IDARTICULO_CUR)),
			--NULL,CASE WHEN COALESCE(@CNSFMED,'')<>'' THEN 1 ELSE 0 END,@CNSFMED
         
         
       --  UPDATE HTX SET CNSMOV = @CNSIZSOL, SOLICITADO = 1, CLASEANUINV = 0 WHERE CNSHTX=@CNSHTX_CUR

	   --FETCH NEXT FROM PEDIDO_IZSOLD    
	   --INTO @IDARTICULO_CUR,@CANTIDASOL,@CODOM_CUR,@CANTIDHTX,@IDSERVICIOHTX,@CNSHTX_CUR,@CNSFMED,@SOLOIART
	   --END
	   --CLOSE PEDIDO_IZSOLD
	   --DEALLOCATE PEDIDO_IZSOLD

         INSERT INTO IZSOLD(CNSIZSOL, IDARTICULO, CANTIDADSOL, ESTADO, CODOM, CANTIDAD, FRECUENCIA, NUMDOSIS, CANTIDADBOLO, QIMPREGNACION,
                            DURACION, IDSERVICIO, TIPOENT, CNSHBALI, TIPOM, IDPRINCIPIO, COBRADODY,OPTI,CNSFMED)
         SELECT @CNSIZSOL,COALESCE(AUTD.IDARTICULO,SER.IDARTICULO),AUTD.CANTIDAD,1,'01',AUTD.CANTIDAD,24,1,0,0,24, COALESCE(AUTD.IDARTICULO,AUTD.IDSERVICIO),
                  NULL, AUTD.IDAUT,NULL,NULL,(CASE WHEN COALESCE(AUTD.IDARTICULO,'') NOT IN (SER.IDARTICULO,'') THEN 1 ELSE 0 END),
          CASE WHEN COALESCE(AUTD.CNSFMED,'')<>'' THEN 1 ELSE 0 END,AUTD.CNSFMED
         FROM   AUTD 
		   INNER JOIN SER ON AUTD.IDSERVICIO   = SER.IDSERVICIO 
		   INNER JOIN IART ON SER.IDARTICULO   = IART.IDARTICULO   
         WHERE  AUTD.IDAUT = @IDAUT
         AND    SER.IDARTICULO   <> '' 
         AND    SER.IDARTICULO   <> @IDINVARTNA 

            /***************************************************/
            /* VERIFICAR CONFIRMACION AUTOMATICA EN INVENTARIO SOLO PARA BODEGA VIRTUAL */
            /***************************************************/
          
      SELECT @CONFAUT = COALESCE(CONFIRMAAUTOMDESDEQX,0),@TIPOBODEGA=TIPOBODEGA FROM IBOD WHERE IDBODEGA = @IDBODEGA
      
      PRINT 'CONFIRMA AUTO= '+STR(@CONFAUT)
      PRINT 'TIPO BODEGA '+@TIPOBODEGA
      
      IF @CONFAUT = 1 AND @TIPOBODEGA='Virtual'
      BEGIN
         PRINT'CONFIRMA AUTOMATICO DESDE IZSOLD'
         EXEC SPK_INSERTA_IZOLDT_AUT @CNSIZSOL,@IDBODEGA,@SEDE,@USUARIO
      END
   END                                                          
   UPDATE AUT SET PEDIDOINV = 1 WHERE IDAUT = @IDAUT  
END

