IF EXISTS (SELECT name FROM sysobjects WHERE name = 'SPK_PEDIDOINVCX_002' AND type = 'P')
   DROP PROCEDURE SPK_PEDIDOINVCX_002

GO
CREATE PROCEDURE DBO.SPK_PEDIDOINVCX_002 
@NOPROGRAMACION   VARCHAR(13),
@ITEM             SMALLINT,
@IDBODEGA         VARCHAR(20),
@COMPANIA         VARCHAR(2),
@SEDE             VARCHAR(5),
@USUARIO          VARCHAR(12),
@SYS_COMPUTERNAME VARCHAR(254)
WITH ENCRYPTION
AS
DECLARE @CUANTAS        INT
DECLARE @IDINVARTNA     VARCHAR(80)
DECLARE @NVOCONSEC      VARCHAR(20)
DECLARE @NOADMISION     VARCHAR(16)
DECLARE @IDITAR         VARCHAR(2)
DECLARE @IDTIPOMOV      VARCHAR(2)
DECLARE @CCOSTO         VARCHAR(20)
DECLARE @IDAREAH        VARCHAR(20)
DECLARE @IDAREA         VARCHAR(20)
DECLARE @NA             VARCHAR(5) 
DECLARE @ESTRANSITO     SMALLINT
DECLARE @OK             SMALLINT
DECLARE @INVPIDEAUTOMQX VARCHAR(20)
DECLARE @TMB            VARCHAR(1)
DECLARE @IDBODEGA2      VARCHAR(20)
DECLARE @TIPOBODEGA     VARCHAR(10)
DECLARE @CNSIZSOL       VARCHAR(20)
DECLARE @SECTOR         VARCHAR(20)
DECLARE @CNSIZSOLD      VARCHAR(20)
DECLARE @CLASEPED       VARCHAR(10)
BEGIN

   SELECT @OK = COUNT(*) FROM CXPSI WHERE NOPROGRAMACION = @NOPROGRAMACION 
   AND COALESCE(CXPSI.PEDIDOINV,0) <> 1 
   
   IF @OK = 0
      RETURN

   SELECT @OK = COUNT(*) FROM CXPSI WHERE NOPROGRAMACION = @NOPROGRAMACION 
   AND CANTIDADDEV > CANTIDADREAL
    
   --IF @OK > 0
   --   RETURN 

   SELECT @IDINVARTNA = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVARTNA'

   SELECT @CUANTAS = COUNT(*) FROM CXPSI,SER WHERE CXPSI.IDSERVICIO = SER.IDSERVICIO 
   AND CXPSI.NOPROGRAMACION = @NOPROGRAMACION 
   AND SER.IDARTICULO <> '' 
   AND SER.IDARTICULO <> @IDINVARTNA
   AND COALESCE(CXPSI.PEDIDOINV,0) <> 1 

   IF @CUANTAS = 0
   BEGIN
      RETURN
   END

   SELECT @NOADMISION = NOADMISION, @CCOSTO = CCOSTO, @IDAREA = IDAREA, @IDAREAH = IDAREAH,
          @NA = NIVEL
   FROM   CXPS WHERE NOPROGRAMACION = @NOPROGRAMACION 
   
   SELECT @TMB = TIPOMANEJOBODEGA, @IDBODEGA = IDBODEGA, @IDBODEGA2 = IDBODEGA2 
   FROM   UBEQ 
   WHERE  COMPANIA = @COMPANIA
   AND    SYS_COMPUTERNAME = @SYS_COMPUTERNAME
   
   IF @TMB = 'A'     
   BEGIN
      SELECT @IDBODEGA = BODEGADIA, @IDBODEGA2 = BODEGADIA2 FROM AFU WHERE
      IDAREA = @IDAREA
   END

   SELECT @IDITAR = DBO.FNK_VALORVARIABLE('IDINVIDITARUNICA') 
          
   SELECT @IDTIPOMOV = DATO FROM USVGS WHERE IDVARIABLE = 'IDINVMOVPRE'
   SELECT @ESTRANSITO = GENTRANSITO FROM ITMO WHERE IDTIPOMOV = @IDTIPOMOV 
	
   CREATE TABLE #TIMOVH(CNSMOV VARCHAR(20), IDARTICULO VARCHAR(20), EXISTENCIA DECIMAL(14,2),
						CANTIDAD DECIMAL(14,2), CANTPEDIDA DECIMAL(14,2), PCOSTO DECIMAL(14,2),
						ITEM INT IDENTITY, PVENTA DECIMAL(14,2), IDITAR VARCHAR(2), IDSERVICIO VARCHAR(20)) 
   
   DELETE FROM #TIMOVH

	INSERT INTO #TIMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
						PVENTA, IDITAR, IDSERVICIO )
	SELECT @NVOCONSEC, SER.IDARTICULO, IART.EXISTOTAL, 0, CXPSI.CANTIDADEST, 
			IART.PCOSTO, CXPSI.PVENTA, IART.IDITAR, CXPSI.IDSERVICIO 
	FROM   CXPSI, SER, IART 
	WHERE  CXPSI.IDSERVICIO = SER.IDSERVICIO 
	AND    CXPSI.NOPROGRAMACION = @NOPROGRAMACION 
	AND    SER.IDARTICULO <> '' 
	AND    SER.IDARTICULO <> @IDINVARTNA
	AND    SER.IDARTICULO = IART.IDARTICULO
	AND COALESCE(CXPSI.PEDIDOINV,0) <> 1 

   IF DBO.FNK_VALORVARIABLE('PEDIDOHPREAIZSOL')<>'SI'
   BEGIN
      PRINT 'VARIABLE DIFERENTE A SI '    
   
	   EXEC SPK_GENCONSECUTIVO @COMPANIA,@SEDE,'@MOV',@NVOCONSEC OUTPUT
	   SELECT @NVOCONSEC = @SEDE + REPLACE(SPACE(8 - LEN(@NVOCONSEC))+LTRIM(RTRIM(@NVOCONSEC)),SPACE(1),0)

	   INSERT INTO IMOV(CNSMOV, IDBODEGA, IDTIPOMOV, NODOCUMENTO, TIPODOCU,
						FECHAMOV, CCOSTO, IDSOLICITA, IDTERCERO, IDFUNCIONARIO,
						IDRECIBE, FACTORVENTA, ESTADO, IDBODEGAEXTERNA, cnstran,
						OBSERVACION, CNSFCOM, SUBIOCOMPRA, NOPRESTACION, IDAREA,
						CONTABILIZADA, NROCOMPROBANTE, PROCEDENCIA, USUARIO,
						USUARIOCONF, FECHACONF, PARCIAL, IDAREAH, NIVELATENCION, 
						SYS_ComputerName, TIENECAMBIO, IDITAR, ESTRANSITO, CNSREP)  
	   SELECT @NVOCONSEC,@IDBODEGA,@IDTIPOMOV, @NOADMISION,
			  CASE COALESCE(@NOADMISION,'') WHEN '' THEN 'SN' ELSE NULL END, 
			  DBO.FNK_FECHA_SIN_MLS(GETDATE()), @CCOSTO, @USUARIO, NULL, @USUARIO, NULL, NULL, '0', NULL, NULL,
			  '',NULL, 0, @NOPROGRAMACION, @IDAREA,0, NULL, 'QXPGCX', @USUARIO,
			  NULL, NULL, 0, @IDAREAH, @NA, @SYS_COMPUTERNAME, 0, @IDITAR, @ESTRANSITO, NULL
        

	   INSERT INTO IMOVH(CNSMOV, IDARTICULO, EXISTENCIA, CANTIDAD, CANTPEDIDA, PCOSTO,
						 NOLOTE, NOLOTEPEDIDO, ESTADO, IDARTICULOTF,
						 CANTIDADTF, PCOSTOANTES, CNSTRAN, ITEM, PVENTA, USUARIO, 
						 USUARIOCONF, FECHACONF, PRIEXI, FECHAREPOSI, IDARTICULOORI,
						 CANTIDADORI, TIENECAMBIO, IDITAR, IDSERVICIO)
	   SELECT @NVOCONSEC, #TIMOVH.IDARTICULO, #TIMOVH.EXISTENCIA, 0, #TIMOVH.CANTPEDIDA, 
			  #TIMOVH.PCOSTO, #TIMOVH.ITEM, NULL ,0, NULL, NULL, NULL, NULL, 
			  @ITEM, #TIMOVH.PVENTA, @USUARIO, NULL, NULL, 0, NULL, NULL, NULL, 0, #TIMOVH.IDITAR,
			  #TIMOVH.IDSERVICIO      
	   FROM   #TIMOVH
   
	   UPDATE CXPSI SET PEDIDOINV = 1, PCOSTO = IART.PCOSTO,CNSMOV=@NVOCONSEC
	   FROM   SER, IART 
	   WHERE  CXPSI.IDSERVICIO    = SER.IDSERVICIO 
	   AND    CXPSI.NOPROGRAMACION = @NOPROGRAMACION 
	   AND    SER.IDARTICULO    <> '' 
	   AND    SER.IDARTICULO    <> @IDINVARTNA
	   AND    SER.IDARTICULO     = IART.IDARTICULO
	   AND    COALESCE(CXPSI.PEDIDOINV,0) <> 1 

	   SELECT @INVPIDEAUTOMQX = LEFT(DATO,20) FROM USVGS WHERE IDVARIABLE = 'INVPIDEAUTOMQX'
	   IF @INVPIDEAUTOMQX = 'SI'
	   BEGIN
		  EXEC SPK_CONFIRMARSALIDAS @IDBODEGA, @NVOCONSEC, @USUARIO, 	@COMPANIA, 	@SEDE
	   END 
	END
	ELSE
	BEGIN
      PRINT 'VOY PARA IZSOL E IZSOLD'
      SELECT @CNSIZSOL = ''
      EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOL', @CNSIZSOL OUTPUT  
      SELECT @CNSIZSOL = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOL))+LTRIM(RTRIM(@CNSIZSOL)),SPACE(1),0)  
      
      PRINT '@CNSIZSOL == '+@CNSIZSOL
      SELECT TOP 1 @SECTOR=SECTOR FROM HHAB WHERE IDAREA=DBO.FNK_VALORVARIABLE('TMIDAREAQX') AND CLASE='Sector'
	  IF COALESCE(@SECTOR,'')=''
	  BEGIN
		 SELECT @SECTOR='PROGRAQX'
	  END
     SELECT @IDBODEGA=DBO.FNK_BUSCA_BODEGA_IZSOL(@SEDE,@SECTOR)

      INSERT INTO IZSOL (CNSIZSOL, FECHASOL, USUARIOSOL, ESTADO, IDBODEGAATIENDE, SECTOR, CLASE, NOADMISION, CNSIZSOLM )
      SELECT @CNSIZSOL,  DBO.FNK_FECHA_SIN_MLS(GETDATE()), @USUARIO, 1, @IDBODEGA, @SECTOR, 'QXPGCX', @NOPROGRAMACION, @NOPROGRAMACION

      DECLARE @BANDERA INT
      DECLARE @LIMITE  INT
      SELECT @BANDERA=1,@LIMITE=0
      
      SELECT @LIMITE=COUNT(*) FROM #TIMOVH
   
     -- WHILE @BANDERA<=@LIMITE
     -- BEGIN
     --    SELECT @CNSIZSOLD = ''
     --    EXEC SPK_GENCONSECUTIVO '01',@SEDE,'@IZSOLD', @CNSIZSOLD OUTPUT  
     --    SELECT @CNSIZSOLD = @SEDE + REPLACE(SPACE(10 - LEN(@CNSIZSOLD))+LTRIM(RTRIM(@CNSIZSOLD)),SPACE(1),0)  
         
     --    INSERT INTO IZSOLD (CNSIZSOLD , CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,CNSHBALI,IDPRINCIPIO) 
     --    SELECT @CNSIZSOLD,@CNSIZSOL,A.IDARTICULO,A.CANTPEDIDA,1,NULL,A.CANTPEDIDA,24,0,0,0,24,A.IDSERVICIO,@NOPROGRAMACION, IART.IDSERVICIO
     --    FROM #TIMOVH A LEFT JOIN IART ON IART.IDARTICULO COLLATE DATABASE_DEFAULT  =A.IDARTICULO COLLATE DATABASE_DEFAULT 
		   --WHERE ITEM=@BANDERA 
      
     --    SELECT @BANDERA=@BANDERA+1       
     -- END
      INSERT INTO IZSOLD (CNSIZSOL , IDARTICULO , CANTIDADSOL , ESTADO, CODOM,CANTIDAD,FRECUENCIA,NUMDOSIS,CANTIDADBOLO,QIMPREGNACION,DURACION,IDSERVICIO,CNSHBALI,IDPRINCIPIO) 
      SELECT @CNSIZSOL,A.IDARTICULO,A.CANTPEDIDA,1,NULL,A.CANTPEDIDA,24,0,0,0,24,A.IDSERVICIO,@NOPROGRAMACION, IART.IDSERVICIO
      FROM #TIMOVH A LEFT JOIN IART ON IART.IDARTICULO COLLATE DATABASE_DEFAULT  =A.IDARTICULO COLLATE DATABASE_DEFAULT 

	   UPDATE CXPSI SET PEDIDOINV = 1, PCOSTO = IART.PCOSTO,CNSMOV=@CNSIZSOL
	   FROM   SER, IART 
	   WHERE  CXPSI.IDSERVICIO    = SER.IDSERVICIO 
	   AND    CXPSI.NOPROGRAMACION = @NOPROGRAMACION 
	   AND    SER.IDARTICULO    <> '' 
	   AND    SER.IDARTICULO    <> @IDINVARTNA
	   AND    SER.IDARTICULO     = IART.IDARTICULO
	   AND    COALESCE(CXPSI.PEDIDOINV,0) <> 1 
	END
END

